import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-08-responsive-viewport-media"],
  slug: "css-08-responsive-viewport-media",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 8,
  title: "viewport, 상대 단위와 모바일 우선 미디어 쿼리",
  subtitle: "기기 이름별 화면을 따로 만드는 대신 CSS pixel·viewport·font/container 단위와 content-driven breakpoint·사용자 preference를 조합해 zoom·mobile browser UI·input modality까지 견디는 layout을 설계합니다.",
  level: "고급",
  estimatedMinutes: 215,
  coreQuestion: "화면 폭·font·사용자 설정·component container가 바뀌어도 content 손실과 2차원 scroll 없이 읽고 조작할 수 있게 어떤 단위와 conditional rule을 선택할까요?",
  summary: "원본의 viewport meta, em/rem/vw/vh, 800/1200px min-width, float 20/60/20→100vw, 폭별 background image를 모두 audit합니다. 존재하지 않는 wh 오타와 viewport 설명을 교정하고 CSS pixel, layout/visual viewport, %, em/rem/ch/lh, vw/vh/vi/vb/vmin/vmax와 sv/lv/dv 변형을 실제 수치로 확인합니다. mobile-first base→content breakpoint enhancement, range syntax, source-order overlap, print·hover/pointer·prefers-reduced-motion/color-scheme/contrast·forced-colors를 다룹니다. clamp/min/max, Grid minmax, responsive image, reflow 320 CSS px/400% zoom, 100vw scrollbar overflow, container query와 progressive support까지 release workflow로 연결합니다.",
  objectives: [
    "viewport meta가 mobile layout viewport와 initial scale에 미치는 역할을 설명하고 zoom 차단 설정을 피할 수 있다.",
    "CSS px·%·em·rem·ch·lh·viewport/동적 viewport 단위의 기준과 사용 위험을 계산할 수 있다.",
    "고정 breakpoint를 기기 이름이 아니라 content가 깨지는 지점에서 선택하고 mobile-first로 source order를 설계할 수 있다.",
    "min/max/range media condition과 overlapping query의 cascade 결과를 정확히 예측할 수 있다.",
    "hover/pointer·print·reduced motion·color scheme·contrast·forced colors preference를 기능/접근성 enhancement에 사용할 수 있다.",
    "viewport query와 container query를 page environment/component available space 책임으로 구분하고 320px·400% zoom에서 reflow를 검증할 수 있다.",
  ],
  prerequisites: [
    { title: "relative·absolute·fixed·sticky와 stacking context", reason: "viewport·visual viewport·dvh와 overlay geometry를 배웠으므로 이제 전체 layout을 fluid/conditional하게 설계합니다.", sessionSlug: "css-07-position-stacking-modal" },
  ],
  keywords: ["viewport meta", "CSS pixel", "em", "rem", "ch", "vw", "vh", "dvh", "svh", "media query", "mobile first", "breakpoint", "clamp", "reflow", "prefers-reduced-motion", "container query"],
  chapters: [
    {
      id: "viewport-css-pixel-meta",
      title: "viewport meta는 mobile browser의 layout viewport와 초기 확대를 device CSS pixel 기준으로 맞춥니다",
      lead: "physical device pixel·CSS pixel·layout viewport·visual viewport를 구분해야 breakpoint와 zoom 결과를 정확히 해석할 수 있습니다.",
      explanations: [
        "`<meta name='viewport' content='width=device-width, initial-scale=1'>`은 mobile browser가 desktop용 넓은 virtual layout viewport로 page를 축소해 보이는 legacy behavior 대신 device width에 맞는 layout viewport를 설정하는 일반 baseline입니다. device-width를 'browser 자체'로 설명하기보다 device의 screen CSS pixel 기준과 user agent 처리를 구분합니다.",
        "CSS px는 physical pixel 하나와 항상 같지 않습니다. devicePixelRatio, display density, OS scaling, browser zoom에서 여러 device pixel이 한 CSS px를 표현할 수 있습니다. media query width와 getBoundingClientRect는 주로 CSS pixel 좌표를 사용합니다.",
        "layout viewport는 document layout 기준, visual viewport는 pinch zoom·on-screen keyboard·browser chrome으로 현재 보이는 부분입니다. mobile fixed overlay와 100vh 문제는 두 viewport 차이를 함께 봅니다.",
        "maximum-scale=1 또는 user-scalable=no로 zoom을 막으면 저시력 사용자가 text를 확대하지 못할 수 있습니다. responsive 문제를 zoom 제한으로 숨기지 않고 content가 확대·reflow되게 만듭니다.",
        "initial-scale=1은 '1부터 10까지 확대 범위'가 아니라 초기 scale 관계를 정하는 값입니다. browser/accessibility 설정이 최종 behavior에 영향을 줄 수 있으므로 actual device와 zoom을 test합니다.",
      ],
      concepts: [
        { term: "CSS pixel", definition: "CSS layout·media query·geometry API가 사용하는 reference pixel 단위이며 physical display pixel과 1:1일 필요가 없습니다.", detail: ["zoom/devicePixelRatio에 따라 device pixel mapping이 달라집니다.", "breakpoint는 CSS px 기준입니다."] },
        { term: "layout viewport", definition: "document가 layout되는 기준 viewport rectangle입니다.", detail: ["width media query와 viewport unit 기준에 관여합니다.", "visual viewport와 다를 수 있습니다."] },
        { term: "viewport meta", definition: "mobile user agent에 initial layout viewport width·scale 처리 hint를 제공하는 HTML metadata입니다.", detail: ["width=device-width, initial-scale=1이 일반 baseline입니다.", "user zoom을 막지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "mobile에서 page 전체가 desktop 축소판처럼 작게 보이고 media query가 예상보다 넓은 폭으로 match한다.", likelyCause: "viewport meta가 없거나 잘못되어 legacy virtual layout viewport가 사용됩니다.", checks: ["head의 viewport meta가 한 개이고 syntax가 정확한지 확인합니다.", "innerWidth·visualViewport.width·devicePixelRatio를 기록합니다.", "actual device/remote debugging으로 확인합니다."], fix: "width=device-width, initial-scale=1 baseline을 추가하고 layout을 mobile CSS pixel 폭에 맞게 reflow합니다.", prevention: "mobile emulation과 actual device에서 viewport metadata·innerWidth·horizontal overflow smoke test를 둡니다." },
      ],
    },
    {
      id: "relative-length-families",
      title: "상대 단위는 각각 containing block·font metric·root·viewport·container라는 다른 기준을 가집니다",
      lead: "반응형이라는 이유로 모든 숫자를 vw로 바꾸지 않고 값의 의미와 함께 커져야 할 기준을 선택합니다.",
      explanations: [
        "%는 property마다 percentage reference가 다릅니다. inline-size:50%는 보통 containing block inline size, padding percentage는 specification의 기준, translate percentage는 자기 reference box를 사용할 수 있습니다. property 정의를 확인합니다.",
        "font-size의 em은 parent computed font size를 기준으로 하고, 다른 property의 em은 해당 element의 computed font size를 기준으로 합니다. rem은 root element font size, ch는 font의 '0' glyph advance를 대략 기준으로 해 text measure·input width hint에 유용하지만 모든 글자 수를 보장하지 않습니다.",
        "lh는 element line-height, rlh는 root line-height 기준입니다. vertical rhythm과 scroll margin에 유용하지만 browser target과 fallback을 확인합니다. 단위 없는 line-height는 font-size에 비례해 descendant inheritance가 안전한 경우가 많습니다.",
        "vw/vh는 default viewport의 1%, vi/vb는 writing-mode inline/block axis, vmin/vmax는 두 축 작은/큰 dimension의 1%입니다. 원본 주석의 wh는 존재하지 않으며 height는 vh입니다. 100wh도 유효하지 않습니다.",
        "small(sv*), large(lv*), dynamic(dv*) viewport unit은 mobile retracting UI의 작은/큰/현재 dynamic size를 구분합니다. svh는 UI가 펼쳐진 상태에도 content를 맞추기, lvh는 가능한 큰 영역, dvh는 UI 변화에 따라 update될 수 있습니다. motion/layout cost와 keyboard를 test합니다.",
        "viewport-only font-size:10vh/10vw는 landscape·ultrawide·zoom에서 너무 작거나 커질 수 있습니다. `clamp(1rem, .8rem + 2vw, 2.5rem)`처럼 user root size와 fluid term, min/max를 결합하고 200% text를 확인합니다.",
      ],
      concepts: [
        { term: "font-relative unit", definition: "em·rem·ch·lh처럼 현재/parent/root font metric 또는 line-height를 기준으로 한 length입니다.", detail: ["typography와 함께 scale할 수 있습니다.", "기준 metric은 unit마다 다릅니다."] },
        { term: "viewport-percentage unit", definition: "vw/vh/vi/vb/vmin/vmax 및 sv/lv/dv 변형처럼 viewport dimension의 1%인 length입니다.", detail: ["mobile browser UI 변화를 고려합니다.", "text에 단독 사용하면 zoom/reflow 위험이 있습니다."] },
        { term: "fluid value", definition: "available viewport/container/font 조건에 따라 연속적으로 변하되 min/max guard를 가진 값입니다.", detail: ["clamp/min/max로 표현할 수 있습니다.", "breakpoint를 완전히 대체하지는 않습니다."] },
      ],
      codeExamples: [
        {
          id: "relative-unit-calculator",
          title: "em·rem·%·vw의 기준을 exact computed value로 비교하기",
          language: "html",
          filename: "relative-units.html",
          purpose: "viewport 1000px fixture에서 parent/root/containing-block/viewport 기준이 서로 다른 값을 숫자로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>상대 단위 계산</title>\n  <style>\n    html { font-size: 16px; }\n    body { margin: 0; }\n    .parent { font-size: 20px; inline-size: 400px; }\n    .em { font-size: 2em; }\n    .rem { font-size: 2rem; }\n    .percent { inline-size: 50%; block-size: 1px; }\n    .viewport { inline-size: 10vw; block-size: 1px; }\n  </style>\n</head>\n<body>\n  <div class=\"parent\">\n    <span class=\"em\">em</span><span class=\"rem\">rem</span>\n    <div class=\"percent\"></div><div class=\"viewport\"></div>\n  </div>\n  <pre id=\"result\"></pre>\n  <script>\n    const px = (s, p) => getComputedStyle(document.querySelector(s))[p];\n    const viewportWidth = parseFloat(px('.viewport', 'width'));\n    document.querySelector('#result').textContent = [\n      `em-font=${px('.em', 'fontSize')}`,\n      `rem-font=${px('.rem', 'fontSize')}`,\n      `percent-width=${px('.percent', 'width')}`,\n      `vw-contract=${Math.abs(viewportWidth - innerWidth * .1) < .1}`,\n      `viewport-positive=${innerWidth > 0}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-14", explanation: "root 16px, parent 20px/400px, child 2em·2rem·50%·10vw를 각각 한 기준만 달리해 설정합니다." },
            { lines: "18-21", explanation: "모든 test element가 같은 parent 안에 있어 em/rem과 percentage 기준을 분리합니다." },
            { lines: "24-31", explanation: "computed font/width와 actual viewport CSS px를 한 output에 기록합니다." },
          ],
          run: { environment: ["현대 desktop browser", "DevTools responsive viewport를 정확히 1000 CSS px로 설정", "browser zoom 100%"], command: "viewport 폭 1000px에서 relative-units.html 열기" },
          output: { value: "em-font=40px\nrem-font=32px\npercent-width=200px\nvw-contract=true\nviewport-positive=true", explanation: ["2em은 parent 20×2, 2rem은 root 16×2입니다.", "50%는 400px containing block의 절반입니다.", "10vw는 어떤 viewport에서도 innerWidth의 10%라는 계산 계약으로 검증합니다."] },
          experiments: [
            { change: "parent font-size를 24px로 바꿉니다.", prediction: "em-font=48px, rem-font=32px로 rem은 유지됩니다.", result: "em과 rem의 기준 차이입니다." },
            { change: "viewport를 500px로 줄입니다.", prediction: "vw-width=50px이고 parent/percent가 overflow할 수 있습니다.", result: "viewport unit만 연속적으로 변하고 fixed parent는 reflow하지 않습니다." },
            { change: "html font-size를 20px로 바꿉니다.", prediction: "rem-font=40px이며 em-font는 parent가 20px로 고정되어 40px입니다.", result: "root/user font preference와 component font 기준을 구분합니다." },
          ],
          sourceRefs: ["web-viewport-source", "css-values-4"],
        },
      ],
      diagnostics: [
        { symptom: "font-size:10vw인 heading이 ultrawide에서 지나치게 크고 mobile landscape/zoom에서 읽기 어렵다.", likelyCause: "viewport term에 min/max/root-font guard 없이 typography를 전부 연결했습니다.", checks: ["320~2560px·200/400% zoom에서 computed font를 기록합니다.", "long Korean/English heading wrapping을 test합니다.", "user default font size를 변경합니다."], fix: "rem 기반 min/max와 fluid term을 clamp로 결합하고 readable line length/line-height를 검증합니다.", prevention: "typography token마다 min/max/zoom/long-content visual fixture를 둡니다." },
      ],
    },
    {
      id: "fluid-sizing-reflow",
      title: "fluid sizing과 intrinsic layout은 breakpoint 사이에서도 content가 자연스럽게 reflow되게 합니다",
      lead: "고정 200/400/800px box를 단계적으로 키우기보다 available space와 min/max-content를 활용합니다.",
      explanations: [
        "`inline-size:min(100%, 70rem)`과 auto margin은 viewport보다 넓어지지 않는 content container를 만듭니다. `padding-inline:clamp(1rem,4vw,3rem)`은 좁은/넓은 사이 연속 spacing을 제공합니다.",
        "Grid `repeat(auto-fit,minmax(min(16rem,100%),1fr))`은 card 최소 readable width를 유지하며 available space에 따라 열 수를 자동 조절합니다. media query 없이도 많은 intermediate 폭을 처리하고 breakpoint는 큰 navigation/semantic mode 변화에 집중합니다.",
        "min()/max()/clamp()에서 unit이 섞여도 compatible length로 계산할 수 있습니다. clamp(min, preferred, max)는 min guard가 max보다 우선하는 spec behavior 등 edge case를 확인하고 negative/zoom 결과를 test합니다.",
        "width:100vw는 vertical scrollbar를 포함하는 viewport 기준으로 content area보다 넓어 horizontal overflow를 만들 수 있고 body margin/padding 안에서는 더 넘칩니다. 일반 block full width는 auto/100%/inline-size:100%를 사용하고 viewport escape가 정말 필요한 경우만 calc와 scrollbar behavior를 검토합니다.",
        "reflow 요구에서는 320 CSS px 폭 또는 1280px에서 400% zoom 등에서 대부분 content를 양방향 scroll 없이 읽을 수 있어야 합니다. data table·map처럼 본질적으로 2차원인 예외는 component 내부 scroll과 instruction을 제공합니다.",
      ],
      concepts: [
        { term: "intrinsic sizing", definition: "content의 min-content/max-content contribution과 available space를 이용해 box 크기를 결정하는 layout model입니다.", detail: ["고정 breakpoint 사이를 자연스럽게 처리합니다.", "긴 unbreakable content를 test합니다."] },
        { term: "reflow", definition: "viewport/zoom 변화에서 content가 손실 없이 새 줄·열로 배치되어 주로 한 방향 scroll로 읽히는 behavior입니다.", detail: ["320 CSS px와 400% zoom을 검증합니다.", "clip/hide와 다릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "mobile에서 각 column을 width:100vw로 바꿨는데 page가 조금씩 가로 scroll된다.", likelyCause: "100vw가 scrollbar/viewport 전체를 기준으로 하고 body padding·border와 합쳐져 containing block을 넘었습니다.", checks: ["documentElement.scrollWidth/clientWidth를 비교합니다.", "overflow element rect와 box sizing을 찾습니다.", "100vw rule을 100%/auto로 바꿔 test합니다."], fix: "normal-flow block은 inline-size:auto/100%와 parent padding을 사용하고 viewport unit full-bleed는 명시적 wrapper pattern으로 제한합니다.", prevention: "320px·scrollbar-present·long-word fixture에서 horizontal overflow assertion을 둡니다." },
      ],
    },
    {
      id: "media-query-logic-cascade",
      title: "media query는 environment predicate로 rule 후보를 걸러내고 match한 rule끼리는 다시 cascade합니다",
      lead: "breakpoint에서 이전 style이 사라지는 것이 아니라 조건이 true인 declaration들이 함께 후보가 되어 layer·specificity·order로 경쟁합니다.",
      explanations: [
        "`@media (min-width:800px)`는 viewport width가 800 CSS px 이상일 때 내부 rule이 relevant합니다. 원본 1200px query도 800px query와 동시에 true이며 specificity가 같고 뒤에 있어 800px 결과를 override합니다.",
        "mobile-first는 base rule을 좁은 환경에 usable하게 쓰고 `min-width`로 공간이 생길 때 enhancement합니다. desktop-first max-width가 틀린 것은 아니지만 override를 되돌리는 declaration과 range overlap이 늘 수 있습니다. codebase 한 방향을 일관되게 사용합니다.",
        "modern range syntax `(width >= 50rem)` 또는 `(30rem <= width < 60rem)`은 경계를 읽기 쉽게 할 수 있습니다. target browser와 build tooling을 확인하고 기존 min/max syntax fallback을 필요에 따라 유지합니다.",
        "comma는 OR query list, `and`는 모두 true, `not`은 query negation입니다. operator precedence와 괄호를 명확히 하고 deprecated/비주류 media type을 device taxonomy로 남발하지 않습니다. 기본 all과 print/screen requirement를 사용합니다.",
        "breakpoint를 iPhone/iPad/desktop이라는 device 이름으로 정하면 split-screen·zoom·foldable·browser side panel을 놓칩니다. content가 겹치거나 line length·target size가 깨지는 첫 폭을 측정하고 token으로 이름 붙입니다.",
      ],
      concepts: [
        { term: "media query", definition: "viewport·output device·user preference·interaction capability 같은 environment feature 조건이 true일 때 style rule을 relevant하게 만드는 CSS 조건입니다.", detail: ["match한 rule도 cascade합니다.", "JavaScript matchMedia와 같은 condition을 관찰할 수 있습니다."] },
        { term: "content-driven breakpoint", definition: "특정 기기 폭이 아니라 component/content가 현재 layout에서 더 이상 usable하지 않은 지점으로 정한 threshold입니다.", detail: ["zoom/split view에 견고합니다.", "content 변경 후 재검증합니다."] },
        { term: "mobile-first", definition: "좁고 제약된 환경에서 작동하는 base style을 먼저 두고 min-width 등으로 available space enhancement를 추가하는 strategy입니다.", detail: ["기능을 mobile에서 제거한다는 뜻이 아닙니다.", "source order와 cascade가 단순해질 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "mobile-first-query-proof",
          title: "390px·900px에서 mobile-first query와 cascade mode 확인",
          language: "html",
          filename: "media-query.html",
          purpose: "base one-column과 min-width three-column enhancement가 viewport condition에 따라 어떻게 relevant해지는지 exact state로 출력합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>모바일 우선 미디어 쿼리</title>\n  <style>\n    :root { --layout-columns: 1; }\n    .layout { display: grid; grid-template-columns: 1fr; gap: 1rem; }\n    .panel { min-inline-size: 0; padding: 1rem; border: 1px solid #777; }\n    @media (min-width: 800px) {\n      :root { --layout-columns: 3; }\n      .layout { grid-template-columns: 1fr 2fr 1fr; }\n    }\n  </style>\n</head>\n<body>\n  <main class=\"layout\"><aside class=\"panel\">목차</aside><article class=\"panel\">본문</article><aside class=\"panel\">복습</aside></main>\n  <pre id=\"result\"></pre>\n  <script>\n    const wide = matchMedia('(min-width: 800px)').matches;\n    const columns = getComputedStyle(document.documentElement).getPropertyValue('--layout-columns').trim();\n    const expectedColumns = wide ? '3' : '1';\n    const sourceOrder = [...document.querySelectorAll('.panel')].map((panel) => panel.textContent).join('>');\n    document.querySelector('#result').textContent = [\n      `wide-contract=${wide === (innerWidth >= 800)}`,\n      `columns-contract=${columns === expectedColumns}`,\n      `source-order=${sourceOrder}`,\n      `overflow=${document.documentElement.scrollWidth > document.documentElement.clientWidth}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-10", explanation: "base는 한 열/columns=1이며 모든 panel은 min-inline-size:0으로 긴 content가 Grid를 밀지 않게 합니다." },
            { lines: "11-14", explanation: "800 CSS px 이상에서 custom state와 Grid track을 함께 세 열로 enhancement합니다." },
            { lines: "20-22", explanation: "semantic source order 목차→본문→복습은 viewport와 무관하게 유지됩니다." },
            { lines: "25-27", explanation: "matchMedia, computed custom property, document horizontal overflow를 exact text로 출력합니다." },
          ],
          run: { environment: ["현대 browser", "DevTools responsive mode", "zoom 100%"], command: "viewport 390px에서 열고 기록한 뒤 900px로 변경해 reload" },
          output: { value: "wide-contract=true\ncolumns-contract=true\nsource-order=목차>본문>복습\noverflow=false", explanation: ["현재 viewport가 어느 폭이든 matchMedia와 innerWidth의 boundary 판단이 일치합니다.", "computed column token은 wide에서 3, narrow에서 1이라는 정책과 일치합니다.", "DOM/reading order는 모든 폭에서 목차→본문→복습이고 horizontal overflow가 없습니다."] },
          experiments: [
            { change: "query를 max-width:799px로 바꾸고 three-column을 base로 둡니다.", prediction: "같은 visual mode를 desktop-first로 구현할 수 있지만 좁은 override에서 더 많은 property reset이 필요할 수 있습니다.", result: "방향은 architecture choice이며 consistency와 override cost를 비교합니다." },
            { change: "첫 query 뒤에 @media(min-width:1200px){:root{--layout-columns:4}}를 추가합니다.", prediction: "1200px 이상에서는 두 query가 true지만 뒤 rule이 columns=4를 이깁니다.", result: "media query가 previous rule을 끄는 것이 아니라 matching 후보가 함께 cascade합니다." },
            { change: "panel 안에 200자 unbreakable token을 넣습니다.", prediction: "overflow-wrap가 없으면 panel content 자체가 overflow할 수 있습니다.", result: "responsive track과 content wrapping은 함께 test해야 합니다." },
          ],
          sourceRefs: ["web-media-breakpoint-source", "web-media-columns-source", "mediaqueries-5", "wai-reflow"],
        },
      ],
      diagnostics: [
        { symptom: "1200px 이상 style이 800px style과 충돌해 예상치 못한 값이 남는다.", likelyCause: "min-width query는 누적 match되며 둘 다 true라는 사실과 cascade/source order를 놓쳤습니다.", checks: ["matchMedia로 각 condition을 기록합니다.", "DevTools에서 두 matching @media rule의 specificity/order를 비교합니다.", "property를 mode별로 표로 만듭니다."], fix: "mobile-first 누적 enhancement를 의도하거나 mutually exclusive range condition을 사용하고 shared property를 명확히 override합니다.", prevention: "breakpoint boundary 직전/정확/직후와 largest viewport computed snapshot을 test합니다." },
      ],
    },
    {
      id: "responsive-layout-content-order",
      title: "responsive layout은 content를 숨기기보다 priority와 DOM order를 유지하며 열·navigation mode를 바꿉니다",
      lead: "원본 float 20/60/20을 mobile에서 각각 100vw로 바꾸는 대신 Grid/Flex flow와 semantic task 순서를 설계합니다.",
      explanations: [
        "mobile에서는 main content가 먼저 필요하다고 해서 CSS order로 DOM을 뒤집으면 screen reader/focus 순서와 visual order가 달라질 수 있습니다. source에서 user task에 맞는 logical order를 정하고 desktop Grid area도 가능한 한 이를 존중합니다.",
        "side navigation을 좁은 폭에서 display:none으로 제거하면 기능을 잃습니다. native details/disclosure button으로 접거나 heading 뒤로 이동하되 keyboard/name/state/focus가 유지되어야 합니다.",
        "percentage columns에 큰 fixed padding을 더하면 box-sizing과 min-content 때문에 100%를 넘을 수 있습니다. gap과 clamp padding, minmax(0,...)를 사용하고 long URL/code/table overflow를 component별로 처리합니다.",
        "height:100vh 중앙 배경 page는 mobile toolbar에서 잘릴 수 있고 background-attachment:fixed는 mobile support/performance가 다릅니다. min-block-size:100svh/dvh, content flow와 reduced data/motion을 고려합니다.",
        "background image를 breakpoint마다 바꾸면 모든 asset preloading/cache와 art direction 의미를 검토합니다. content image라면 picture/source media와 alt를 사용하고 CSS background는 decorative/presentational image에 제한합니다.",
      ],
      concepts: [
        { term: "responsive priority", definition: "좁은 공간에서 어떤 content/action을 먼저 보여 주고 어떻게 접근하게 할지 정한 정보 architecture입니다.", detail: ["숨김이 유일한 전략이 아닙니다.", "DOM/reading/focus order와 함께 설계합니다."] },
        { term: "art direction", definition: "viewport/context에 따라 단순 해상도뿐 아니라 crop·composition이 다른 image source를 선택하는 방식입니다.", detail: ["content image는 picture/source를 고려합니다.", "각 source가 같은 의미/alt를 유지해야 합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "mobile에서 오른쪽 sidebar를 display:none 처리하자 중요한 복습 link와 문의 action이 사라진다.", likelyCause: "layout 보조와 기능 content를 구분하지 않고 공간 확보를 위해 숨겼습니다.", checks: ["hidden content의 user task/analytics/accessibility를 inventory합니다.", "keyboard/URL로 대체 경로가 있는지 봅니다.", "disclosure/reorder/별도 page 대안을 검토합니다."], fix: "semantic content를 DOM에 유지하고 accessible disclosure 또는 main 흐름 아래로 reflow합니다.", prevention: "breakpoint별 기능 parity와 critical action availability를 E2E test합니다." },
      ],
    },
    {
      id: "capability-and-preference-media",
      title: "media query는 폭뿐 아니라 print·hover/pointer·motion·color·contrast 같은 환경과 사용자 선호를 존중합니다",
      lead: "device label 대신 실제 capability와 preference를 query하고 baseline 기능은 모든 환경에 남깁니다.",
      explanations: [
        "`(hover:hover)`와 `(pointer:fine)`은 primary input capability를 query합니다. any-hover/any-pointer는 보조 input도 고려합니다. touch device에 hover-only tooltip을 제공하지 않고 click/focus baseline 위에 hover preview를 enhancement합니다.",
        "`prefers-reduced-motion:reduce`에서는 parallax·large transform·auto animation을 제거하거나 duration을 최소화하되 loading/progress 같은 의미 있는 state를 숨기지 않습니다. JavaScript matchMedia listener와 animation library도 같은 preference를 반영합니다.",
        "`prefers-color-scheme:dark`는 theme hint이며 contrast token을 함께 검증합니다. dark mode를 단순 color invert로 만들지 않고 image/form/focus/visited/code block과 `color-scheme` UA control rendering을 확인합니다.",
        "`prefers-contrast`와 `forced-colors`는 더 높은 contrast/forced palette 환경을 다룹니다. background image/color만으로 icon/state를 전달하면 사라질 수 있어 border/currentColor/system color와 forced-color-adjust를 신중히 사용합니다.",
        "`@media print`에서는 navigation/button/video를 숨기는 것보다 URL/heading/table page break·ink·contrast·source order를 설계합니다. `display:none`으로 필요한 citation/answer를 잃지 않고 print preview/PDF를 실제 확인합니다.",
        "`prefers-reduced-data` 등 newer feature는 target support를 확인하고 optional high-bandwidth media를 줄일 수 있습니다. query가 false/unknown이어도 core content와 manual choice가 남아야 합니다.",
      ],
      concepts: [
        { term: "capability query", definition: "hover·pointer 등 현재 input/output 환경이 실제로 제공하는 능력을 검사하는 media feature입니다.", detail: ["device category보다 직접적입니다.", "primary와 any-*를 구분합니다."] },
        { term: "user preference media feature", definition: "motion·color scheme·contrast·transparency·data 등 사용자가 OS/browser에 표시한 선호를 style에 반영하는 query입니다.", detail: ["기능 제거보다 부담 감소를 설계합니다.", "support/fallback을 확인합니다."] },
        { term: "forced colors", definition: "user agent가 author color를 제한된 사용자/system palette로 강제하는 display mode입니다.", detail: ["색-only state가 사라질 수 있습니다.", "native controls/currentColor/border를 test합니다."] },
      ],
      codeExamples: [
        {
          id: "preference-media-observer",
          title: "motion·scheme·hover preference와 CSS mode를 한 번에 관찰하기",
          language: "html",
          filename: "preferences.html",
          purpose: "DevTools emulation에서 media feature와 computed custom property가 함께 변경되는 것을 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>사용자 선호 미디어</title>\n  <style>\n    :root { color-scheme: light dark; --motion: full; --theme: light; }\n    .demo { transition: transform 500ms; }\n    .demo:hover { transform: scale(1.05); }\n    @media (prefers-reduced-motion: reduce) { :root { --motion: reduce; } .demo { transition: none; } }\n    @media (prefers-color-scheme: dark) { :root { --theme: dark; } }\n    @media (forced-colors: active) { .demo { border: 2px solid ButtonText; } }\n  </style>\n</head>\n<body>\n  <button class=\"demo\">미리보기</button><pre id=\"result\"></pre>\n  <script>\n    const root = getComputedStyle(document.documentElement);\n    const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;\n    const dark = matchMedia('(prefers-color-scheme: dark)').matches;\n    const hover = matchMedia('(hover: hover)').matches;\n    const forced = matchMedia('(forced-colors: active)').matches;\n    document.querySelector('#result').textContent = [\n      `motion-contract=${root.getPropertyValue('--motion').trim() === (reduce ? 'reduce' : 'full')}`,\n      `theme-contract=${root.getPropertyValue('--theme').trim() === (dark ? 'dark' : 'light')}`,\n      `hover-query-boolean=${typeof hover === 'boolean'}`,\n      `forced-colors-boolean=${typeof forced === 'boolean'}`,\n      `button-label=${document.querySelector('.demo').textContent}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-11", explanation: "light/full baseline 위에 reduced motion·dark·forced color enhancement를 독립 query로 추가합니다." },
            { lines: "16-23", explanation: "세 media feature match와 CSS custom property resolved state를 같은 output에 기록합니다." },
          ],
          run: { environment: ["Chromium DevTools Rendering에서 prefers-reduced-motion=reduce, prefers-color-scheme=dark", "hover 가능한 desktop pointer", "설정 변경 후 reload"], command: "두 preference를 emulation한 desktop에서 preferences.html 열기" },
          output: { value: "motion-contract=true\ntheme-contract=true\nhover-query-boolean=true\nforced-colors-boolean=true\nbutton-label=미리보기", explanation: ["어떤 OS/DevTools preference에서도 CSS custom token과 JavaScript media query가 같은 state를 봅니다.", "hover와 forced-colors 결과는 환경마다 달라도 boolean query로 안전하게 관찰됩니다.", "기능 baseline인 visible button label은 preference와 무관하게 남습니다."] },
          experiments: [
            { change: "reduced motion emulation을 no-preference로 바꿉니다.", prediction: "reduce=false와 motion-token=full이 됩니다.", result: "base/full state가 fallback입니다." },
            { change: "dark emulation을 light로 바꿉니다.", prediction: "dark=false와 theme-token=light가 됩니다.", result: "theme query와 token이 동기화됩니다." },
            { change: "touch device emulation으로 hover를 false로 만듭니다.", prediction: "hover=false이며 button core activation은 여전히 가능해야 합니다.", result: "hover animation은 enhancement이지 기능 trigger가 아닙니다." },
          ],
          sourceRefs: ["mediaqueries-5", "wai-reflow"],
        },
      ],
      diagnostics: [
        { symptom: "reduce preference인데도 JavaScript carousel/parallax는 계속 움직인다.", likelyCause: "CSS animation만 media query로 끄고 JS/library animation state는 preference를 읽지 않았습니다.", checks: ["matchMedia reduce 결과와 JS animation owner를 확인합니다.", "auto-play timer·scroll listener를 추적합니다.", "meaningful progress indicator가 필요한지 구분합니다."], fix: "shared preference service로 CSS/JS animation을 줄이고 user override control을 제공하며 essential state feedback은 유지합니다.", prevention: "reduce/no-preference 양쪽 E2E와 animation budget을 둡니다." },
      ],
    },
    {
      id: "container-query-component",
      title: "media query는 environment를, container query는 component가 실제 배치된 available space를 기준으로 합니다",
      lead: "같은 card가 main과 좁은 sidebar에서 동시에 쓰이면 viewport 폭 하나로 component layout을 결정하기 어렵습니다.",
      explanations: [
        "media query는 viewport/device/user preference를 query합니다. component가 1200px viewport의 280px sidebar에 놓여도 `(min-width:1000px)`는 true라 wide card layout을 잘못 적용할 수 있습니다.",
        "container-type:inline-size를 ancestor에 설정하고 @container (inline-size > 30rem)로 descendant layout을 바꾸면 실제 component available inline size에 반응합니다. container-name으로 nested container 중 의도한 기준을 선택할 수 있습니다.",
        "size containment는 layout sizing에 영향을 줄 수 있어 container를 component 자체가 아닌 wrapper에 설정하는 pattern과 intrinsic/fallback size를 검토합니다. query 대상 descendant가 query container 자신의 style을 직접 조건부로 바꾸는 cycle 제한도 이해합니다.",
        "cqi/cqw 등 container-relative unit은 nearest suitable query container dimension의 1%입니다. font/spacing에 쓸 때 clamp와 accessibility zoom guard를 유지합니다.",
        "container query가 unsupported한 target에서는 mobile/stacked baseline이 사용 가능해야 하고 @supports(container-type:inline-size)로 optional enhancement를 감쌀 수 있습니다. media query와 container query를 경쟁시키지 말고 page shell vs component responsibility로 분리합니다.",
      ],
      concepts: [
        { term: "query container", definition: "descendant @container condition이 size/style feature를 검사할 기준 element입니다.", detail: ["size query는 container-type 설정이 필요합니다.", "name으로 특정 container를 선택할 수 있습니다."] },
        { term: "container query", definition: "viewport가 아니라 ancestor query container의 inline/block size 또는 style condition에 따라 descendant style을 적용하는 conditional rule입니다.", detail: ["reusable component에 적합합니다.", "containment와 cycle 제한을 고려합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "desktop viewport에서 sidebar card가 wide horizontal layout이 되어 text/image가 눌린다.", likelyCause: "component가 실제 280px container가 아니라 viewport min-width query만 보고 wide mode를 선택했습니다.", checks: ["card containing wrapper inline size와 media condition을 비교합니다.", "같은 card를 main/sidebar fixture에 동시에 render합니다.", "container-type/name computed style을 확인합니다."], fix: "component wrapper를 inline-size query container로 두고 card 내부 layout을 @container로 전환하며 stacked baseline을 유지합니다.", prevention: "같은 viewport의 여러 container 폭 fixture와 container boundary 직전/후 visual test를 둡니다." },
      ],
    },
    {
      id: "container-query-intrinsic-component-boundary",
      title: "container query는 component가 실제로 받은 inline-size에 반응하며 intrinsic sizing 계약을 요구합니다",
      lead: "page viewport가 아니라 재사용되는 card의 배치 공간을 기준으로 분기하고, query container가 만드는 containment·minimum·fallback을 함께 설계합니다.",
      explanations: [
        "`container-type:inline-size`는 element를 inline-size query container로 만들고 관련 containment를 적용합니다. descendant의 `@container (inline-size >= 30rem)` rule은 viewport가 아니라 nearest eligible container의 content box를 평가합니다. 같은 viewport에서도 sidebar와 main의 같은 card가 다른 layout을 가질 수 있습니다.",
        "query container 자신의 style을 자신의 descendant query로 직접 바꾸려 하지 않습니다. query는 descendants에 적용되므로 outer shell과 inner card 역할을 분리합니다. name이 여러 container에 중첩되면 `container-name`으로 owner를 명시하고 DevTools에서 matched container를 확인합니다.",
        "container가 좁을 때 long URL·button·image의 min-content 때문에 query breakpoint보다 먼저 overflow할 수 있습니다. flex/grid child의 min-inline-size:0, overflow-wrap, replaced image max-inline-size와 aspect-ratio를 함께 설계합니다. breakpoint는 device 이름이 아니라 content가 깨지는 경계에서 정합니다.",
        "지원하지 않는 환경에서도 semantic source order와 single-column baseline이 작동해야 합니다. `@supports (container-type:inline-size)` 안 enhancement를 둘 수 있으며 JavaScript resize loop로 style을 복제하지 않습니다. ResizeObserver가 필요하다면 state threshold와 loop 방지를 설계합니다.",
        "containment는 성능 최적화 가능성을 주지만 layout·style scope에 새 경계를 만듭니다. large dashboard에서 style/layout 비용을 trace로 측정하고 무조건 모든 wrapper에 적용하지 않습니다. CSS query는 authorization이 아니므로 hidden admin component와 data를 client에 미리 보내지 않습니다.",
      ],
      concepts: [
        { term: "query container", definition: "descendant의 container condition이 size·style 등을 질의하는 ancestor element입니다.", detail: ["container-type이 eligibility를 정합니다.", "nearest eligible 또는 named container를 사용합니다."] },
        { term: "component breakpoint", definition: "device 이름이 아니라 component content와 controls가 재배치되어야 하는 available-size 경계입니다.", detail: ["long-content fixture로 결정합니다.", "viewport breakpoint와 다를 수 있습니다."] },
        { term: "containment boundary", definition: "subtree의 size·layout·style 계산 영향 범위를 제한하기 위해 browser가 설정하는 경계입니다.", detail: ["성능과 sizing behavior를 함께 바꿉니다.", "실제 trace와 fallback을 검증합니다."] },
      ],
      codeExamples: [
        {
          id: "wide-narrow-container-query-proof",
          title: "같은 viewport의 wide·narrow container에서 card layout 분기 검증",
          language: "html",
          filename: "container-query-proof.html",
          purpose: "두 shell의 fixed inline-size만 바꾸고 nearest container query가 grid/block layout을 독립적으로 선택하는지 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>container query 검증</title>\n  <style>\n    body { margin: 0; }\n    .shell { container-type: inline-size; }\n    .wide { inline-size: 360px; }\n    .narrow { inline-size: 240px; }\n    .card { display: block; box-sizing: border-box; inline-size: 100%; border: 1px solid navy; }\n    @container (inline-size >= 300px) { .card { display: grid; grid-template-columns: 100px 1fr; gap: 8px; } }\n  </style>\n</head>\n<body>\n  <section class=\"shell wide\"><article class=\"card\"><strong>제목</strong><span>설명</span></article></section>\n  <section class=\"shell narrow\"><article class=\"card\"><strong>제목</strong><span>설명</span></article></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const wideShell = document.querySelector('.wide');\n    const narrowShell = document.querySelector('.narrow');\n    const wide = getComputedStyle(wideShell.querySelector('.card'));\n    const narrow = getComputedStyle(narrowShell.querySelector('.card'));\n    document.querySelector('#result').textContent = [\n      `container-type=${getComputedStyle(wideShell).containerType}`,\n      `wide-display=${wide.display}`,\n      `wide-two-columns=${wide.gridTemplateColumns.split(' ').length === 2}`,\n      `narrow-display=${narrow.display}`,\n      `wide-width=${Math.round(wideShell.getBoundingClientRect().width)}`,\n      `narrow-width=${Math.round(narrowShell.getBoundingClientRect().width)}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-12", explanation: "두 shell을 query container로 만들고 360/240px만 다르게 한 뒤 300px에서 inner card를 grid로 바꿉니다." },
            { lines: "15-18", explanation: "같은 semantic card를 두 available size에 렌더링합니다." },
            { lines: "21-24", explanation: "각 shell의 inner card computed display/track을 읽습니다." },
            { lines: "25-32", explanation: "container type·wide grid·narrow block·actual widths를 안정적인 값으로 출력합니다." },
          ],
          run: { environment: ["CSS Container Queries를 지원하는 현대 Chromium"], command: "browser에서 container-query-proof.html을 열고 결과 확인" },
          output: { value: "container-type=inline-size\nwide-display=grid\nwide-two-columns=true\nnarrow-display=block\nwide-width=360\nnarrow-width=240", explanation: ["viewport는 같지만 wide shell만 300px threshold를 넘어 grid가 됩니다.", "narrow shell은 semantic block baseline을 유지합니다.", "query container는 inline-size type으로 계산됩니다."] },
          experiments: [
            { change: "wide shell을 299px로 바꿉니다.", prediction: "wide card도 block이 됩니다.", result: "condition은 viewport가 아니라 container content width를 봅니다." },
            { change: "container-type을 제거합니다.", prediction: "eligible ancestor가 없어 두 card 모두 baseline block입니다.", result: "@container rule에는 명시적 owner가 필요합니다." },
            { change: "card 설명에 매우 긴 token을 넣습니다.", prediction: "grid child minimum을 조정하지 않으면 wide card도 overflow할 수 있습니다.", result: "breakpoint와 intrinsic sizing을 함께 설계합니다." },
          ],
          sourceRefs: ["css-contain-3", "css-values-4", "wai-reflow"],
        },
      ],
      diagnostics: [
        { symptom: "같은 card가 main에서는 잘 보이지만 sidebar에서 넘치고 @media를 추가할수록 예외가 늘어난다.", likelyCause: "viewport만 질의해 component의 실제 available size와 min-content를 보지 않았습니다.", checks: ["card의 nearest query container와 content width를 확인합니다.", "long token/image/button의 min-content를 찾습니다.", "container rule의 matched owner를 DevTools에서 봅니다."], fix: "outer shell을 inline-size container로 정하고 inner card를 content breakpoint에서 분기하며 min-inline-size·wrapping을 교정합니다.", prevention: "한 viewport 안 wide/narrow fixture와 long-content container regression을 둡니다." },
      ],
    },
    {
      id: "responsive-assets-preferences-zoom-security",
      title: "responsive asset·user preference·zoom은 network와 접근성·보안까지 포함한 조건부 전달 계약입니다",
      lead: "화면 너비에 따라 모양만 바꾸지 말고 필요한 asset, motion·contrast preference, dynamic viewport와 400% reflow를 하나의 검증 matrix로 묶습니다.",
      explanations: [
        "viewport meta의 `width=device-width, initial-scale=1`은 mobile layout viewport를 device width와 맞추는 일반 baseline입니다. maximum-scale·user-scalable=no로 pinch zoom을 막지 않습니다. CSS pixel과 device pixel, layout viewport와 visual viewport를 구분합니다.",
        "`picture`·`source media`·srcset/sizes는 viewport·resolution·format에 맞는 image candidate를 browser가 선택하게 합니다. CSS background-image breakpoint는 decorative art direction에 쓸 수 있지만 alt semantics가 없고 숨긴 rule의 모든 resource가 반드시 download되지 않는다고 단정할 수 없어 Network에서 확인합니다.",
        "svh·lvh·dvh는 mobile browser chrome 변화의 small/large/dynamic viewport를 표현합니다. full-screen panel에 100vh만 고정해 controls가 가려지지 않도록 min-block-size와 safe-area inset, content scrolling을 검증합니다. text 영역은 fixed height보다 content-driven growth를 우선합니다.",
        "prefers-reduced-motion은 animation을 무조건 제거하는 boolean이 아니라 non-essential movement를 줄이고 state 변화는 즉시 이해되게 만드는 preference입니다. hover/pointer capability와 forced-colors도 실제 media query 결과에 맞춰 enhancement하며 keyboard/touch baseline을 유지합니다.",
        "CSS media query는 access control이나 privacy boundary가 아닙니다. 작은 화면에서 display:none인 data도 DOM에 있고 third-party background URL은 IP·referrer를 노출할 수 있습니다. 승인되지 않은 data는 server에서 제외하고 asset origin·CSP·cache·license를 감사합니다.",
      ],
      concepts: [
        { term: "responsive image candidate", definition: "source/srcset/sizes와 media/type 조건에서 browser가 환경에 맞춰 선택하는 image resource입니다.", detail: ["art direction과 density selection을 구분합니다.", "Network와 currentSrc로 확인합니다."] },
        { term: "dynamic viewport unit", definition: "browser UI 변화에 따라 현재 viewport 크기를 반영하는 dvh/dvw 계열 단위입니다.", detail: ["sv/lv 단위와 경계가 다릅니다.", "fixed controls와 safe area를 test합니다."] },
        { term: "preference contract", definition: "motion·contrast·color 같은 사용자 설정에 따라 효과를 줄이면서 task와 state 전달을 보존하는 규칙입니다.", detail: ["query와 computed 결과를 함께 test합니다.", "색·motion 하나에 의미를 의존하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "viewport-picture-motion-contract-proof",
          title: "viewport meta·responsive image·reduced-motion computed 계약 검증",
          language: "html",
          filename: "responsive-preference-proof.html",
          purpose: "data SVG candidate와 CSS range/preference query를 외부 network 없이 실행해 환경별 결과가 정책과 일치하는지 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>responsive preference 검증</title>\n  <style>\n    .tile { inline-size: 200px; min-block-size: 80px; transition-duration: .25s; background-image: linear-gradient(lavender, lightblue); }\n    @media (width >= 0px) { .tile { border: 2px solid navy; } }\n    @media (prefers-reduced-motion: reduce) { .tile { transition-duration: 0s; } }\n  </style>\n</head>\n<body>\n  <main><h1>과정 카드</h1><picture><source media=\"(width >= 0px)\" srcset=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40'%3E%3Crect width='40' height='40' fill='navy'/%3E%3C/svg%3E\"><img id=\"art\" width=\"40\" height=\"40\" alt=\"파란 학습 표시\" src=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40'%3E%3C/svg%3E\"></picture><section class=\"tile\">설명</section></main>\n  <pre id=\"result\"></pre>\n  <script>\n    const tile = document.querySelector('.tile');\n    const art = document.querySelector('#art');\n    const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;\n    const duration = getComputedStyle(tile).transitionDuration;\n    document.querySelector('#result').textContent = [\n      `viewport-meta=${Boolean(document.querySelector('meta[name=viewport]'))}`,\n      `range-match=${matchMedia('(width >= 0px)').matches}`,\n      `responsive-image=${art.currentSrc.startsWith('data:image/svg+xml')}`,\n      `background-layer=${getComputedStyle(tile).backgroundImage !== 'none'}`,\n      `dvh-supported=${CSS.supports('height', '100dvh')}`,\n      `motion-contract=${reduce ? duration === '0s' : duration === '0.25s'}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "3-10", explanation: "zoom을 막지 않는 viewport meta와 range/reduced-motion CSS를 선언합니다." },
            { lines: "13-15", explanation: "picture candidate와 informative alt, visible card를 external network 없이 둡니다." },
            { lines: "18-22", explanation: "현재 preference와 computed transition duration을 읽습니다." },
            { lines: "23-30", explanation: "meta·range·image·background·dvh·motion policy를 모두 boolean invariant로 출력합니다." },
          ],
          run: { environment: ["responsive images와 Media Queries Level 4+ 지원 Chromium"], command: "browser에서 responsive-preference-proof.html을 열고 reduced-motion 양쪽에서 확인" },
          output: { value: "viewport-meta=true\nrange-match=true\nresponsive-image=true\nbackground-layer=true\ndvh-supported=true\nmotion-contract=true", explanation: ["현재 viewport는 width>=0 range를 만족하고 data SVG candidate를 선택합니다.", "dvh 문법을 지원하며 decorative background layer가 존재합니다.", "사용자 motion preference가 어느 쪽이든 computed duration이 정책과 일치합니다."] },
          experiments: [
            { change: "reduced-motion을 DevTools에서 reduce로 emulation합니다.", prediction: "raw duration은 0s가 되지만 motion-contract는 true입니다.", result: "환경 종속 snapshot 대신 정책 불변식을 test합니다." },
            { change: "viewport meta에 maximum-scale=1을 추가합니다.", prediction: "script output은 존재만 확인해 통과하지만 pinch-zoom 접근성 검토에서는 실패합니다.", result: "자동 output과 수동 zoom task를 함께 수행합니다." },
            { change: "data SVG를 third-party URL로 바꿉니다.", prediction: "Network에 외부 request가 생겨 privacy·CSP·failure 검토가 필요합니다.", result: "responsive 전달은 resource governance까지 포함합니다." },
          ],
          sourceRefs: ["web-media-background-source", "mediaqueries-5", "css-viewport-1", "html-responsive-images", "wai-reflow"],
        },
      ],
      diagnostics: [
        { symptom: "mobile browser UI가 접히거나 400% zoom할 때 full-screen panel의 마지막 button이 보이지 않는다.", likelyCause: "100vh fixed height·overflow hidden과 zoom 제한 viewport meta가 dynamic visual viewport와 content growth를 막았습니다.", checks: ["viewport meta의 scale 제한을 확인합니다.", "100vh를 svh/dvh·min-block-size와 비교합니다.", "320 CSS px·400% zoom에서 keyboard로 마지막 control까지 이동합니다."], fix: "zoom을 허용하고 content-driven size·dvh/safe-area·내부 scrolling을 목적에 맞게 적용합니다.", prevention: "mobile chrome 변화·orientation·400% zoom·reduced-motion을 release matrix에 둡니다." },
      ],
    },
    {
      id: "responsive-verification-performance",
      title: "반응형 품질은 breakpoint screenshot이 아니라 연속 폭·zoom·content·preference·network의 task 결과로 검증합니다",
      lead: "정해진 세 기기 preset만 통과해도 그 사이 폭·split screen·browser side panel에서 깨질 수 있습니다.",
      explanations: [
        "최소 320px부터 넓은 desktop까지 연속 drag 또는 automated viewport matrix로 horizontal overflow·overlap·clip·unreachable focus를 찾습니다. breakpoint -1/exact/+1과 root font 16/20/24, 200/400% zoom을 함께 봅니다.",
        "long Korean/English/German, unbreakable URL/code, empty/loading/error, 1/10/100 cards, image missing/slow를 fixture로 둡니다. responsive는 viewport 문제가 아니라 content variability 문제이기도 합니다.",
        "matchMedia listener와 ResizeObserver/container query 변화가 state를 duplicate하거나 layout thrash를 만들지 확인합니다. CSS로 가능한 layout을 JS innerWidth snapshot으로만 구현하면 resize/SSR/hydration drift가 생길 수 있습니다.",
        "breakpoint마다 큰 background image를 바꾸면 network가 어떤 resource를 request/decode하는지 Performance/Network에서 확인합니다. content image는 srcset/sizes/picture, decorative CSS image는 image-set/media와 reduced-data strategy를 사용합니다.",
        "print preview, reduced motion, dark/light, forced colors, coarse/no hover, portrait/landscape, virtual keyboard를 test matrix에 포함합니다. 모든 환경을 픽셀 동일하게 만들기보다 content·action·focus·meaning parity를 보장합니다.",
        "자동 assertion은 document scrollWidth<=clientWidth, focus rect viewport 교차, critical element visible, no clipped text heuristic, media state token과 route task를 검사합니다. 사람은 readability·information priority·motion discomfort·art direction을 review합니다.",
      ],
      concepts: [
        { term: "boundary test", definition: "조건 threshold 바로 전·정확한 값·바로 후를 검사해 off-by-one/overlap/gap을 찾는 test입니다.", detail: ["media/container query 모두 적용합니다.", "root font/zoom 변화도 포함합니다."] },
        { term: "content stress fixture", definition: "long/short/empty/error/large-count/broken-media content를 의도적으로 넣어 layout resilience를 검증하는 data set입니다.", detail: ["device preset보다 실제 변동을 드러냅니다.", "privacy-safe synthetic data를 사용합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "375/768/1440 preset은 통과하지만 820px side-by-side window에서 navigation과 card가 겹친다.", likelyCause: "기기 preset만 test하고 content-driven breakpoint 사이의 연속 폭과 actual available container를 검증하지 않았습니다.", checks: ["320~1440 continuous sweep과 overflow observer를 실행합니다.", "breakpoint token과 component min-content를 비교합니다.", "sidebar/container query 필요를 확인합니다."], fix: "content가 깨지는 실제 지점으로 breakpoint를 조정하고 intrinsic/container layout을 사용합니다.", prevention: "continuous/resized viewport visual test와 breakpoint boundary matrix를 CI에 추가합니다." },
      ],
      expertNotes: [
        "Server-side Client Hints로 image/layout variant를 미리 선택하면 cache key·privacy·first request·Accept-CH lifecycle이 복잡해집니다. CSS/HTML responsive primitive를 우선하고 측정된 필요에서만 도입합니다.",
        "foldable viewport segments, dynamic-range, inverted-colors 등 newer media feature는 target/product requirement가 있을 때 progressive enhancement로 추가하며 unknown=false baseline을 유지합니다.",
      ],
    },
  ],
  lab: {
    title: "float 3열·고정 배경 page를 mobile-first intrinsic layout과 preference-aware component로 재구성하기",
    scenario: "기존 page는 20/60/20 float, max-width 1014에서 각 column 100vw, 100vh fixed background와 세 device 폭 image를 사용해 scrollbar·mobile toolbar·zoom·touch에서 깨집니다.",
    setup: ["원본 viewport/media file 4개를 read-only evidence로 준비합니다.", "320~1600px responsive mode, 200/400% zoom, root font 변경, motion/dark/forced-colors emulation을 준비합니다.", "long text·URL·image missing·error·many cards synthetic fixture를 준비합니다."],
    steps: [
      "viewport meta·CSS px·innerWidth/visualViewport/devicePixelRatio를 환경별로 기록합니다.",
      "invalid wh/100wh와 rigid vw/vh typography/height를 rem/clamp/sv-dv unit으로 교정합니다.",
      "one-column semantic base와 intrinsic Grid/Flex를 만들고 content가 깨지는 폭에서만 min-width enhancement를 추가합니다.",
      "100vw column을 auto/100% containing-block sizing으로 바꾸고 scrollWidth overflow를 0으로 만듭니다.",
      "hover-only behavior를 focus/click baseline으로 바꾸고 reduced motion/dark/forced colors/print rule을 추가합니다.",
      "reusable card는 viewport query 대신 inline-size container query를 적용하고 main/sidebar 동시 fixture를 test합니다.",
      "320px·400% zoom·breakpoint -1/exact/+1·long content·touch/no-hover·keyboard task를 수행합니다.",
      "responsive image/network·layout shift·matchMedia/container state·horizontal overflow evidence를 자동화합니다.",
    ],
    expectedResult: ["viewport metadata가 정확하고 zoom을 제한하지 않습니다.", "모든 relative/viewport unit의 기준과 min/max guard를 설명할 수 있습니다.", "320 CSS px와 400% zoom에서 page 전체 horizontal scroll 없이 content/action을 사용합니다.", "breakpoint는 content 근거가 있고 exact boundary에서 cascade gap/overlap이 없습니다.", "motion/color/contrast/hover preference에도 meaning·focus·function이 유지됩니다.", "같은 card가 wide main과 narrow sidebar에서 container 크기에 맞게 독립 반응합니다."],
    cleanup: ["실험용 maximum-scale/user-scalable, 100vw overflow, autoplay motion, large test image를 제거합니다.", "DevTools preference/zoom/device emulation을 reset하고 actual default 환경에서 clean navigation을 재검증합니다."],
    extensions: ["picture/srcset/sizes와 CSS image-set의 network selection을 DPR·viewport별로 기록합니다.", "Playwright viewport/zoom 대체(root scaling)/preference matrix와 screenshot diff를 CI에 추가합니다.", "container query units cqi와 clamp typography를 main/sidebar component에서 비교하고 actual readability를 user test합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "em·rem·%·vw·vh 값을 동일 page에서 계산하고 prediction과 computed output을 비교하세요.", requirements: ["root/parent/containing block/viewport 값을 명시합니다.", "500px와 1000px viewport 결과를 모두 기록합니다.", "wh 오타와 100vw overflow case를 재현합니다.", "200% zoom/root font change 결과를 설명합니다."], hints: ["em은 property context에 따라 기준을 확인합니다.", "100vw와 parent 100%는 기준이 다릅니다."], expectedOutcome: "각 단위의 exact 기준과 변화량을 계산하고 overflow/typography에 적합한 단위를 선택합니다.", solutionOutline: ["기준 rectangle/font 표를 먼저 만듭니다.", "한 단위씩 isolated property로 측정합니다."] },
    { difficulty: "응용", prompt: "desktop-first float 3열을 mobile-first Grid와 content breakpoint로 리팩터링하세요.", requirements: ["narrow one-column baseline과 min-width enhancement를 사용합니다.", "DOM/reading/focus order를 보존합니다.", "minmax(0,...)·gap·fluid padding을 적용합니다.", "320px·breakpoint 경계·long URL·200/400% zoom을 test합니다.", "document horizontal overflow를 assertion합니다."], hints: ["device 이름 대신 content가 겹치는 폭을 찾습니다.", "각 column 100vw를 사용하지 않습니다."], expectedOutcome: "연속 viewport와 zoom에서 content가 잘리지 않고 wide 환경에서만 의도한 3열이 됩니다.", solutionOutline: ["CSS-off DOM priority를 먼저 확정합니다.", "intrinsic layout 후 정말 필요한 breakpoint만 추가합니다."] },
    { difficulty: "설계", prompt: "design system의 responsive token·container query·preference·test governance를 설계하세요.", requirements: ["page media와 component container 책임을 분리합니다.", "breakpoint naming/근거와 rem/px 결정 정책을 정의합니다.", "motion/scheme/contrast/forced-colors/hover/print baseline을 포함합니다.", "responsive image·performance/data policy를 설계합니다.", "continuous width·zoom·content stress·preference CI와 수동 review를 정의합니다."], hints: ["동일 component가 다른 container에 들어가는 case를 포함합니다.", "breakpoint 개수보다 intrinsic range를 먼저 사용합니다."], expectedOutcome: "팀이 기기 preset과 임의 pixel을 늘리지 않고 접근 가능·재사용 가능·측정 가능한 responsive system을 구현합니다.", solutionOutline: ["environment/container/content/user axes를 matrix로 분리합니다.", "각 axis의 source of truth와 test owner를 정합니다."] },
  ],
  reviewQuestions: [
    { question: "CSS 1px은 physical pixel 하나인가요?", answer: "항상 그렇지 않습니다. CSS reference pixel이며 density·devicePixelRatio·zoom에 따라 여러 physical pixel로 표현될 수 있습니다." },
    { question: "viewport meta의 initial-scale=1은 확대 범위를 1~10으로 정하나요?", answer: "아닙니다. initial layout scale을 정하는 hint이며 zoom 범위 설명과 다릅니다." },
    { question: "wh라는 viewport 단위가 있나요?", answer: "없습니다. width는 vw, height는 vh이며 vi/vb와 sv/lv/dv 변형도 있습니다." },
    { question: "em과 rem은 어떻게 다른가요?", answer: "font-size의 em은 parent font, 다른 em은 element font를 주로 기준으로 하고 rem은 root font size를 기준으로 합니다." },
    { question: "100vw는 항상 parent의 full width인가요?", answer: "아닙니다. viewport width 기준이라 scrollbar·parent padding 안에서 overflow할 수 있습니다. parent full width는 auto/100%를 검토합니다." },
    { question: "min-width 800과 min-width 1200 query는 1300px에서 하나만 true인가요?", answer: "둘 다 true이며 matching rule이 함께 cascade합니다. specificity/layer/source order가 최종 값을 정합니다." },
    { question: "breakpoint는 iPhone/tablet/desktop 폭으로 정하면 되나요?", answer: "특정 기기보다 content/layout이 unusable해지는 actual CSS pixel 폭을 측정해 정합니다." },
    { question: "hover media query가 false면 tooltip 기능을 없애도 되나요?", answer: "핵심 정보는 focus/click/visible text baseline으로 제공하고 hover는 추가 convenience로 사용합니다." },
    { question: "media query와 container query의 핵심 차이는 무엇인가요?", answer: "media query는 viewport/environment/user preference, container query는 component ancestor의 actual available size/style을 기준으로 합니다." },
    { question: "container query는 자기 container element의 style을 직접 바꾸나요?", answer: "일반적으로 query container의 descendant에 적용됩니다. outer shell과 inner component를 분리해 설계합니다." },
    { question: "container-type:inline-size는 단순 marker인가요?", answer: "아닙니다. query eligibility와 inline-size containment 관련 behavior를 만들므로 intrinsic sizing 영향도 검증해야 합니다." },
    { question: "@container breakpoint도 device 이름으로 정하나요?", answer: "아닙니다. 해당 component의 text·media·controls가 실제로 재배치되어야 하는 available-size 경계로 정합니다." },
    { question: "prefers-reduced-motion이 reduce이면 모든 state change를 없애나요?", answer: "아닙니다. non-essential movement를 줄이되 state와 결과는 즉시 명확하게 전달해야 합니다." },
    { question: "picture의 source media와 CSS background media는 접근성 역할이 같은가요?", answer: "아닙니다. informative img는 alt semantics를 제공하지만 CSS background는 장식이며 대체 text를 제공하지 않습니다." },
    { question: "작은 화면에서 display:none 처리한 admin data는 안전한가요?", answer: "아닙니다. media query는 paint 조건일 뿐 DOM·network data의 authorization을 제공하지 않습니다." },
  ],
  completionChecklist: [
    "viewport meta·CSS/layout/visual viewport·device pixel 차이를 설명하고 zoom 제한을 제거했다.",
    "%·em·rem·ch/lh·vw/vh/vi/vb/vmin/vmax·sv/lv/dv 단위 기준을 계산했다.",
    "fluid min/max/clamp와 intrinsic Grid/Flex를 breakpoint보다 먼저 사용했다.",
    "breakpoint를 content failure로 정하고 matching query의 cascade/source order를 검증했다.",
    "DOM/reading/focus order와 critical 기능을 모든 layout mode에서 유지했다.",
    "motion/scheme/contrast/forced-colors/hover-pointer/print preference를 baseline 위 enhancement로 적용했다.",
    "reusable component는 actual container size가 필요할 때 @container와 fallback을 사용했다.",
    "320px·400% zoom·boundary·long content·preference·network에서 overflow/clip/task를 검증했다.",
    "wide/narrow container에서 같은 component의 matched container와 computed layout을 검증했다.",
    "container child의 min-content·min-inline-size·wrapping·image ratio를 stress test했다.",
    "responsive image candidate와 CSS background의 semantic·network 차이를 currentSrc/Network로 확인했다.",
    "svh·lvh·dvh와 safe-area에서 mobile browser UI 변화 뒤 마지막 control이 보이는지 확인했다.",
    "reduced-motion query와 computed duration이 preference contract에 일치하는지 검증했다.",
    "viewport meta가 pinch zoom을 막지 않고 400% reflow task를 완료하는지 확인했다.",
    "media/container query를 authorization 또는 민감 data hiding 수단으로 사용하지 않았다.",
  ],
  nextSessions: ["css-09-flexbox-axes-alignment"],
  sources: [
    { id: "web-viewport-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex08_viewport.html", usedFor: ["viewport meta", "em/rem", "vw/vh/vmin/vmax", "wh 오타", "font sizing"], evidence: "원본 주석과 2rem/10vh 예제를 audit해 CSS pixel·dynamic viewport·fluid typography와 invalid wh를 교정했습니다." },
    { id: "web-media-breakpoint-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex09_media.html", usedFor: ["min-width 800/1200", "cumulative media query", "box size/color", "media type"], evidence: "두 누적 min-width rule의 cascade를 exact match/output example과 content breakpoint 설명으로 확장했습니다." },
    { id: "web-media-columns-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex10_media.html", usedFor: ["float 20/60/20", "max-width", "100vw mobile", "column reflow"], evidence: "세 column mobile rule을 audit해 100vw overflow·DOM order·Grid mobile-first로 교정했습니다." },
    { id: "web-media-background-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex11_media.html", usedFor: ["range query", "viewport height", "fixed background", "breakpoint image"], evidence: "780~1024 및 <=779 background art direction을 responsive image/network·dvh·preference 관점으로 확장했습니다." },
    { id: "css-values-4", repository: "W3C CSS Working Group", path: "TR/css-values-4/", publicUrl: "https://www.w3.org/TR/css-values-4/", usedFor: ["font/viewport length units", "sv/lv/dv", "min/max/clamp", "value calculation"], evidence: "CSS Values and Units Level 4의 length family와 dynamic viewport/value function 정의를 단위 계산 기준으로 확인했습니다." },
    { id: "mediaqueries-5", repository: "W3C CSS Working Group", path: "TR/mediaqueries-5/", publicUrl: "https://www.w3.org/TR/mediaqueries-5/", usedFor: ["width/range", "hover/pointer", "motion/color/contrast/data preference", "forced colors", "query logic"], evidence: "2026-07-12 기준 Media Queries Level 5의 range/capability/preference feature를 conditional design 기준으로 사용했습니다." },
    { id: "css-contain-3", repository: "W3C CSS Working Group", path: "TR/css-contain-3/", publicUrl: "https://www.w3.org/TR/css-contain-3/", usedFor: ["container-type/name", "@container", "container units", "size containment"], evidence: "container query와 viewport media query의 responsibility/containment 차이를 공식 definition으로 확인했습니다." },
    { id: "wai-reflow", repository: "W3C Web Accessibility Initiative", path: "WCAG21/Understanding/reflow", publicUrl: "https://www.w3.org/WAI/WCAG21/Understanding/reflow", usedFor: ["320 CSS px", "400% zoom", "two-dimensional scroll", "content loss"], evidence: "reflow success criterion explanation을 viewport/zoom release gate에 반영했습니다." },
    { id: "css-viewport-1", repository: "W3C CSS Working Group", path: "TR/css-viewport-1/#viewport-meta", publicUrl: "https://www.w3.org/TR/css-viewport-1/#viewport-meta", usedFor: ["viewport meta translation", "initial zoom", "layout viewport", "user zoom boundary"], evidence: "mobile viewport meta와 CSS viewport model을 zoom 제한 없는 responsive baseline 설명 및 실행 예제에 반영했습니다." },
    { id: "html-responsive-images", repository: "WHATWG HTML Standard", path: "multipage/embedded-content.html#the-picture-element", publicUrl: "https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element", usedFor: ["picture/source", "srcset candidate selection", "media art direction", "currentSrc"], evidence: "picture의 media source와 data SVG candidate 선택을 외부 network 없는 실행 예제로 검증했습니다." },
  ],
  sourceCoverage: {
    filesRead: 4,
    filesUsed: 4,
    uncoveredNotes: [
      "원본은 viewport unit과 width breakpoint·column/background 변화를 충실히 보여 줍니다. dynamic viewport, range syntax, user preference, intrinsic/container query, reflow/zoom은 최신 W3C specification으로 교정·보강했습니다.",
      "Flex item sizing은 다음 css-09, Grid track algorithm과 responsive image build optimization은 capstone/DevOps 과정에서 더 깊게 확장합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
