import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-10-responsive-layout-capstone"],
  slug: "css-10-responsive-layout-capstone",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 10,
  title: "반응형 카드·팀 소개 페이지 설계와 회귀 점검",
  subtitle: "원본 고양이 gallery와 Our Team을 semantic source order, intrinsic Grid/Flex, resilient card, keyboard·motion·content stress와 자동 회귀 기준을 갖춘 공개 가능한 page로 완성합니다.",
  level: "고급",
  estimatedMinutes: 270,
  coreQuestion: "고정 vw/vh 카드와 hover 중심 예제를 어떻게 DOM 순서·긴 콘텐츠·이미지 실패·320px reflow·키보드·사용자 선호·성능까지 견디는 재사용 layout system으로 바꿀까요?",
  summary: "원본 ex21은 Flex wrap과 768/769~1024 media query로 고양이 이미지를 1/2/3열에 배치하고, ex22와 our-team.css는 30vw×60vh fixed team card·10vh heading·빈 alt·`href=#` icon link를 사용합니다. 이를 requirements/source audit에서 시작해 semantic section/list/article와 logical DOM order로 재구성합니다. Flexbox의 한 축 content distribution과 Grid의 두 축 track alignment를 비교하고 `repeat(auto-fit,minmax(min(100%,16rem),1fr))`, `minmax(0,1fr)`, intrinsic size·automatic minimum을 실제 720px geometry로 계산합니다. aspect-ratio/object-fit/intrinsic image size, content-driven card height, long word·missing image·1/100 cards를 다루고 hover와 focus-visible, reduced motion, real link/accessibility name, touch target를 통합합니다. 마지막에는 320px·200/400% zoom·RTL·forced colors·slow network·boundary width·DOM/focus order를 자동/수동으로 검증하고 visual snapshot을 의미/geometry assertion과 함께 운영하는 CSS capstone workflow를 완성합니다.",
  objectives: [
    "원본 page의 fixed viewport sizing, placeholder link, media/alt, source order, state와 responsive gap을 재현 가능한 audit로 기록할 수 있다.",
    "Flexbox와 Grid를 axis·track·alignment·content dependency 기준으로 선택하고 필요하면 component 내부/외부에서 함께 사용할 수 있다.",
    "auto-fit/auto-fill·minmax·fr·gap·intrinsic minimum이 responsive column 수와 track width를 어떻게 정하는지 계산할 수 있다.",
    "이미지 ratio와 content-driven card height를 유지하고 긴 이름·번역·빈 값·broken media·많은 card에서 overflow를 막을 수 있다.",
    "hover·focus-visible·touch·reduced motion·forced colors에서 동일한 정보와 action을 제공할 수 있다.",
    "continuous width·zoom·content stress·keyboard·network·visual/geometry regression을 release gate로 자동화할 수 있다.",
  ],
  prerequisites: [
    { title: "Flexbox 축, 정렬, 줄바꿈과 아이템 크기 협상", reason: "원본 gallery/team의 wrap과 card 내부 정렬을 flex line·min-size·gap 관점에서 분석하고 Grid track과 비교합니다.", sessionSlug: "css-09-flexbox-axes-alignment" },
    { title: "position·stacking context와 접근 가능한 modal", reason: "card overlay/social control을 normal flow와 absolute positioning 중 선택하고 focus/stacking을 안전하게 구성합니다.", sessionSlug: "css-07-position-stacking-modal" },
  ],
  keywords: ["CSS capstone", "responsive cards", "CSS Grid", "Flexbox", "auto-fit", "auto-fill", "minmax", "fr", "intrinsic sizing", "aspect-ratio", "object-fit", "focus-visible", "prefers-reduced-motion", "content stress", "visual regression", "reflow"],
  chapters: [
    {
      id: "audit-before-redesign",
      title: "capstone은 예쁜 재작성보다 원본 의도·결함·완료 기준을 evidence로 고정하는 데서 시작합니다",
      lead: "무엇이 깨졌는지 재현하지 않으면 CSS를 많이 바꾸고도 같은 오류를 다른 breakpoint로 옮길 수 있습니다.",
      explanations: [
        "ex21의 목적은 세 image가 wide에서 한 줄, tablet에서 `.pic{width:45%}`, <=768px에서 column이 되는 responsive gallery입니다. 하지만 wide `.pic`의 명시적 width가 없고 image intrinsic size에 의존해 source image 크기에 따라 wrap 결과가 달라집니다. mobile의 flex-direction:column과 gap:1px도 필요한 spacing인지 검토합니다.",
        "ex22는 heading, 세 team member, role, 네 social icon이라는 content hierarchy가 명확합니다. 하지만 generic div만 사용하고 icon link가 모두 `href=#`, accessible name이 없으며 portrait alt가 빈 문자열입니다. 빈 alt가 항상 틀린 것은 아니지만 adjacent name과 image 목적이 redundant/decorative인지 decision을 기록해야 합니다.",
        "our-team.css의 h1 10vh, column width 30vw/height 60vh는 viewport에 content를 맞춥니다. 작은 viewport, browser toolbar, 200% zoom, 긴 번역 name/role에서 text가 넘치거나 잘릴 수 있습니다. card는 content가 높이를 결정하고 max inline size만 제한하는 쪽이 견고합니다.",
        "검은 30px shadow와 fixed border는 visual intent이지만 forced colors, dark scheme, contrast와 card density를 검사합니다. effect를 제거하는 것이 목표가 아니라 design token으로 강도·색·motion을 관리하고 user context에서 기능을 방해하지 않게 합니다.",
        "test.html의 justify-content:start/left와 LTR/RTL 비교는 logical alignment의 중요성을 보여 줍니다. team card source/visual/focus order를 RTL과 CSS off에서도 의미 있게 유지하고 left/right 대신 inline/block logical property를 기본으로 합니다.",
        "audit 표에는 source selector/property, 현재 viewport/content, expected task, actual geometry/accessibility tree, severity, reproduction과 proposed acceptance criterion을 둡니다. screenshot만이 아니라 scrollWidth, card rect, column count, focus sequence와 link target을 기록합니다.",
      ],
      concepts: [
        { term: "layout audit", definition: "현재 DOM·style·content·viewport에서 의도와 실제 geometry/interaction 차이를 재현 가능한 evidence로 기록하는 과정입니다.", detail: ["before baseline을 만듭니다.", "source selector와 user impact를 연결합니다."] },
        { term: "acceptance criterion", definition: "구현 완료를 판정할 수 있는 관찰 가능한 결과 조건입니다.", detail: ["예: 320px에서 document horizontal overflow 0입니다.", "visual·semantic·interaction·performance를 포함합니다."] },
        { term: "content-driven sizing", definition: "viewport 고정 높이보다 실제 text/media와 available space가 component 크기를 결정하게 하는 설계입니다.", detail: ["번역·zoom에 견고합니다.", "필요하면 min/max guard를 둡니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "desktop screenshot은 비슷해졌지만 mobile에서 card role과 social link가 card 밖으로 잘린다.", likelyCause: "원본 60vh height를 유지한 채 visual spacing만 조정했고 long content/zoom acceptance criterion이 없습니다.", checks: ["card scrollHeight/clientHeight와 overflow computed value를 기록합니다.", "role을 3줄·root font 200%로 바꿉니다.", "fixed/min/max block-size 선언을 찾습니다."], fix: "fixed block-size를 제거하고 content flow와 padding이 높이를 만들게 하며 필요한 경우 min-block-size만 사용합니다.", prevention: "long localization·200/400% zoom fixture에서 clipped text 0을 release gate로 둡니다." },
      ],
    },
    {
      id: "semantic-source-order-card-structure",
      title: "layout 전에 section·list·article·heading·실제 link와 논리적인 source order를 완성합니다",
      lead: "CSS Grid/Flex가 없어도 읽기·Tab·복사·검색 순서가 자연스러워야 visual rearrangement가 안전합니다.",
      explanations: [
        "team collection은 `<section aria-labelledby=...>` 안 heading과 `<ul>`/`li` 또는 article sequence로 표현할 수 있습니다. 각 member는 article/h2, role paragraph, contact list를 가집니다. 같은 page에서 heading level이 건너뛰지 않도록 page outline 문맥을 봅니다.",
        "portrait가 member identification에 필수이고 nearby name만으로 충분하지 않다면 적절한 alt를 제공합니다. 바로 아래 동일 이름 heading이 이미지의 모든 정보를 전달해 반복 announcement만 만든다면 `alt=\"\"`를 선택할 수 있습니다. 어떤 선택이든 alt attribute 자체는 존재하고 purpose decision을 문서화합니다.",
        "icon-only anchor에는 `aria-label=\"James Turner의 GitHub\"`처럼 destination/action을 식별하는 accessible name이 필요합니다. Font Awesome `<i>`는 `aria-hidden=true`로 장식 처리하고 실제 https/mailto target을 사용합니다. `href=#`는 keyboard activation 시 page top 이동이라는 원치 않는 기능입니다.",
        "card 전체를 하나의 link로 감싸면서 내부에 또 link/button을 중첩하지 않습니다. click area 확대가 필요하면 heading link의 pseudo-element stretched-link pattern을 검토하되 다른 actions와 stacking/focus가 충돌하지 않게 합니다.",
        "Grid `order`, explicit grid-area 또는 dense placement로 visual order를 바꿀 수 있지만 reading/Tab source order는 자동으로 같아지지 않습니다. member priority와 contact sequence를 DOM에서 먼저 결정하고 visual reorder는 의미 없는 장식에만 제한합니다.",
        "image 실패·social account 없음·role empty도 semantic state입니다. broken image icon만 남기지 않고 fallback, 없는 link 제거, empty role 대체 정책을 data renderer와 함께 정합니다.",
      ],
      concepts: [
        { term: "source order", definition: "HTML DOM에 나타나는 content 순서로 CSS off, speech, sequential focus의 기본 순서입니다.", detail: ["visual order보다 먼저 의미를 정합니다.", "Grid/Flex reorder가 자동 수정하지 않습니다."] },
        { term: "accessible name", definition: "assistive technology가 link/button/image 같은 object를 식별하는 계산된 이름입니다.", detail: ["visible text·label·aria-label·alt 등이 source가 됩니다.", "icon glyph만으로 충분하지 않습니다."] },
        { term: "redundant image", definition: "바로 인접한 text와 같은 정보를 반복해 추가 의미가 없는 image입니다.", detail: ["빈 alt가 적합할 수 있습니다.", "목적/context마다 판단합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "screen reader가 social links를 모두 ‘link’ 또는 ‘Twitter icon’으로만 읽는다.", likelyCause: "icon font class만 있고 anchor의 사람+destination accessible name이 없습니다.", checks: ["accessibility tree에서 각 link name을 봅니다.", "i의 aria-hidden과 anchor aria-label/visible text를 확인합니다.", "href가 실제 destination인지 test합니다."], fix: "anchor에 고유한 사람·서비스 목적의 accessible name과 실제 URL/mailto를 주고 icon은 장식으로 숨깁니다.", prevention: "unnamed interactive element 0과 placeholder href 0을 automated DOM audit에 둡니다." },
      ],
    },
    {
      id: "choose-flex-or-grid",
      title: "Flexbox는 한 축의 content 협상, Grid는 행과 열 track의 2차원 정렬에 우선합니다",
      lead: "둘 중 하나를 승자로 고르는 대신 page collection과 card 내부의 다른 요구에 각각 배치합니다.",
      explanations: [
        "Flexbox는 각 flex line 안에서 item base size와 free space를 나누고 secondary axis의 line 정렬을 수행합니다. 원본 gallery처럼 이미지가 content 크기에 따라 자연스럽게 wrap하고 한 줄의 분배가 핵심이면 Flex가 좋은 후보입니다.",
        "Grid는 column/row track을 먼저 만들고 item을 cell/area에 배치해 여러 행의 card가 같은 column line에 맞습니다. 팀 card collection처럼 균등 column과 gap, 2차원 alignment가 중요하면 Grid가 의도를 더 직접 표현합니다.",
        "page collection은 Grid, card 내부의 social link row는 Flex처럼 함께 씁니다. markup hierarchy마다 formatting context를 만들고 outer grid item의 automatic min-size와 inner flex item overflow를 각각 진단합니다.",
        "`repeat(3,minmax(0,1fr))`은 세 flexible track을 만들고 `minmax(0,...)`가 long min-content 때문에 track이 container를 밀어내는 것을 줄입니다. 그러나 3열을 항상 강제하므로 narrow mode에는 query 또는 auto-fit intrinsic repetition이 필요합니다.",
        "`repeat(auto-fit,minmax(min(100%,16rem),1fr))`은 최소 track이 container보다 커지지 않게 하고 들어갈 수 있는 만큼 반복합니다. auto-fit은 empty repeated tracks를 collapse해 existing cards가 공간을 채우고, auto-fill은 empty track 자리를 유지할 수 있습니다.",
        "`fr`은 fixed gap과 non-flexible track을 제외한 leftover space의 fraction이며 무조건 container 전체의 퍼센트가 아닙니다. intrinsic minimum, spanning item과 track sizing algorithm이 먼저 영향을 줍니다.",
      ],
      concepts: [
        { term: "grid track", definition: "인접한 두 grid line 사이의 row 또는 column 공간입니다.", detail: ["fixed·intrinsic·flexible sizing을 가질 수 있습니다.", "gap은 track이 아닌 gutter입니다."] },
        { term: "fr unit", definition: "grid container의 leftover space에서 flexible track이 차지하는 비율을 나타냅니다.", detail: ["gap과 고정/intrinsic 요구 뒤에 계산됩니다.", "item min-content가 minimum을 제한할 수 있습니다."] },
        { term: "auto-fit versus auto-fill", definition: "available space에 반복 track을 만들되 empty repeated track을 collapse할지 유지할지의 차이입니다.", detail: ["auto-fit은 빈 track을 collapse합니다.", "item 수와 desired empty slot에 따라 선택합니다."] },
      ],
      codeExamples: [
        {
          id: "intrinsic-grid-geometry",
          title: "720px에서 auto-fit card 3개의 track 폭 계산·측정",
          language: "html",
          filename: "team-grid-geometry.html",
          purpose: "최소 200px, gap 20px, 최대 720px grid가 세 column을 만들고 leftover를 fr로 나누는 exact geometry를 Chromium에서 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>팀 Grid 기하</title>\n  <style>\n    * { box-sizing: border-box; }\n    html, body { margin: 0; }\n    .team {\n      display: grid;\n      grid-template-columns: repeat(auto-fit, minmax(min(100%, 200px), 1fr));\n      gap: 20px;\n      inline-size: min(720px, calc(100vw - 32px));\n      margin-inline: auto;\n    }\n    .card { min-inline-size: 0; }\n  </style>\n</head>\n<body>\n  <main class=\"team\">\n    <article class=\"card\">A</article><article class=\"card\">B</article><article class=\"card\">C</article>\n  </main>\n  <pre id=\"out\"></pre>\n  <script>\n    const grid = document.querySelector('.team');\n    const card = document.querySelector('.card');\n    const columns = getComputedStyle(grid).gridTemplateColumns.split(' ').length;\n    document.querySelector('#out').textContent = [\n      `grid=${grid.getBoundingClientRect().width.toFixed(0)}`,\n      `columns=${columns}`,\n      `card=${card.getBoundingClientRect().width.toFixed(2)}`,\n      `overflow=${document.documentElement.scrollWidth > document.documentElement.clientWidth}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-17", explanation: "global border-box와 auto-fit/minmax/min combination, 20px gap, 720px upper bound를 정의합니다." },
            { lines: "20-22", explanation: "동일한 세 card를 logical DOM order로 둡니다." },
            { lines: "25-33", explanation: "resolved track list, grid/card rectangle와 document horizontal overflow를 출력합니다." },
          ],
          run: { environment: ["Chromium headless 또는 DevTools content viewport가 752 CSS px 이상", "zoom 100%"], command: "chrome --headless=new --window-size=800,600 --dump-dom team-grid-geometry.html" },
          output: { value: "grid=720\ncolumns=3\ncard=226.66\noverflow=false", explanation: ["세 최소 track과 두 gap의 최소는 640px이라 720px 안에 들어갑니다.", "gap 40px을 뺀 680px을 세 1fr track이 나눠 약 226.66px이 됩니다.", "min(100%,200px)는 더 좁은 container에서 200px minimum이 document를 밀지 않게 합니다."] },
          experiments: [
            { change: "card를 두 개만 남기고 auto-fit을 유지합니다.", prediction: "empty repeated track이 collapse되어 두 card가 더 넓게 공간을 나눕니다.", result: "empty slot을 유지하려면 auto-fill behavior와 design intent를 비교합니다." },
            { change: "gap을 60px로 바꿉니다.", prediction: "세 track 최소 600+두 gap 120=720으로 각각 200px이 됩니다.", result: "gap도 column 수를 결정하는 available space에서 차감됩니다." },
            { change: "min(100%,200px)을 200px로 바꾸고 180px container에 넣습니다.", prediction: "track minimum이 container보다 커 document/component overflow 가능성이 생깁니다.", result: "component가 extreme narrow container를 허용할지 guard를 설계합니다." },
          ],
          sourceRefs: ["web-kitten-responsive-source", "web-team-source", "css-grid-2", "css-sizing-4"],
        },
      ],
      diagnostics: [
        { symptom: "`repeat(3,1fr)`인데 긴 URL card 하나 때문에 전체 grid가 container 밖으로 넓어진다.", likelyCause: "flexible track/item의 automatic min-content minimum이 줄어들지 않고 unbreakable content가 track을 밀었습니다.", checks: ["resolved gridTemplateColumns와 item min-width를 봅니다.", "문제 text의 min-content와 overflow-wrap을 확인합니다.", "minmax(0,1fr)/min-inline-size:0 isolated test를 합니다."], fix: "track에 minmax(0,1fr), item에 min-inline-size:0을 적용하고 실제 URL/code에는 overflow-wrap:anywhere 또는 intentional scroll을 설계합니다.", prevention: "긴 unbreakable Latin/URL/CJK fixture에서 container/document overflow 0을 test합니다." },
      ],
    },
    {
      id: "resilient-card-media-content",
      title: "card는 고정 높이 대신 media ratio·content flow·footer alignment와 intrinsic minimum을 설계합니다",
      lead: "동일 높이를 위해 text를 자르기 전에 어떤 정보가 반드시 보여야 하고 어느 영역만 늘어날지 정합니다.",
      explanations: [
        "portrait wrapper에 `aspect-ratio:1` 또는 design ratio를 주고 img에 inline-size/block-size:100%, object-fit:cover를 적용하면 source 비율이 달라도 slot을 안정화합니다. 사람 얼굴 crop focal point는 object-position/data metadata로 조정하고 의미 손실을 review합니다.",
        "img width/height attribute 또는 aspect-ratio는 resource load 전 layout space를 예약해 cumulative layout shift를 줄입니다. CSS로 responsive display size를 바꾸더라도 intrinsic aspect ratio 정보는 HTML에 둡니다.",
        "card를 `display:grid; grid-template-rows:auto auto 1fr auto`로 만들면 portrait, name, flexible description, action row를 정렬할 수 있습니다. 모든 card에 fixed 60vh를 주지 않고 collection의 row stretch/subgrid 지원과 content 요구를 비교합니다.",
        "긴 이름에는 ellipsis를 무조건 쓰지 않습니다. member identity가 핵심이면 wrap을 허용하고 `overflow-wrap:anywhere`, hyphens, language를 검토합니다. line clamp를 쓰면 full value를 다른 접근 가능한 경로로 제공하고 zoom/translation에서 action을 가리지 않는지 test합니다.",
        "missing image는 broken icon과 alt text만 겹치지 않게 renderer가 fallback initials/avatar를 선택하고 status를 decorative/meaningful에 맞게 알립니다. source image가 third-party면 width/height, format, cache/CORS/privacy와 failure timeout을 관리합니다.",
        "shadow/transform은 overflow clip과 stacking context를 만들 수 있습니다. hover에서 card를 translate할 때 grid gap보다 큰 이동으로 neighbor를 가리거나 focus outline을 clip하지 않게 wrapper overflow와 z-index를 확인합니다.",
      ],
      concepts: [
        { term: "aspect-ratio", definition: "box의 preferred width 대 height 비율을 지정해 한 축이 auto일 때 다른 축 sizing에 참여하는 property입니다.", detail: ["media slot 안정화에 유용합니다.", "min/max/intrinsic constraint와 함께 계산됩니다."] },
        { term: "object-fit", definition: "replaced content가 지정된 content box 안에 어떤 비율/크기로 맞을지 정합니다.", detail: ["cover는 crop할 수 있습니다.", "contain은 letterbox 여백이 생길 수 있습니다."] },
        { term: "layout shift", definition: "사용자 입력 없이 이미 그려진 element 위치가 resource load 등으로 바뀌는 현상입니다.", detail: ["intrinsic media dimension으로 줄일 수 있습니다.", "시각적 안정성과 클릭 오류에 영향 줍니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "profile image가 로드될 때 social link가 아래로 밀려 사용자가 다른 link를 누른다.", likelyCause: "image intrinsic width/height 또는 reserved aspect-ratio slot이 없어 load 전 높이가 0이었습니다.", checks: ["img width/height attribute와 computed aspect-ratio를 확인합니다.", "Network slow에서 layout-shift entry를 기록합니다.", "fallback/failed image state의 slot 크기를 비교합니다."], fix: "HTML intrinsic dimensions와 CSS responsive size/object-fit를 제공하고 success/failure 모두 같은 media slot을 유지합니다.", prevention: "slow/failed image fixture와 layout shift budget을 performance test에 둡니다." },
      ],
    },
    {
      id: "interaction-focus-motion-links",
      title: "hover는 focus-visible·activation·touch baseline 위의 enhancement로만 추가합니다",
      lead: "card가 움직이는 것보다 모든 사용자가 각 contact의 이름·상태·목적을 알고 실행할 수 있는지가 먼저입니다.",
      explanations: [
        "anchor는 native keyboard activation과 visited/context menu behavior를 제공하므로 실제 navigation에는 button/div click 대신 anchor를 사용합니다. 외부 new tab이 꼭 필요하면 사용자 기대와 rel을 검토하고 무조건 target blank를 강제하지 않습니다.",
        "`:focus-visible`에 background와 구분되는 outline을 주고 `outline:none`만 쓰지 않습니다. outline-offset, border radius와 forced-colors에서 system color/outline이 보이는지 확인합니다. hover와 focus-visible이 동일한 essential information을 드러내게 합니다.",
        "touch/coarse pointer에는 hover가 없거나 tap 뒤 sticky hover가 생길 수 있습니다. social links는 기본 상태에서도 보이고 충분한 target/spacing을 가지며 `(hover:hover) and (pointer:fine)`에서만 lift effect를 강화합니다.",
        "`prefers-reduced-motion:reduce`에서는 큰 translate/scale/continuous animation과 smooth scroll을 줄이되 focus·loading·success 같은 상태 차이를 제거하지 않습니다. transition-duration을 아주 짧게 하거나 transform을 끄고 non-motion color/border cue를 유지합니다.",
        "card hover로 정보를 reveal하는 경우 keyboard focus-within과 click/expanded control을 함께 설계합니다. CSS `:has(:focus-visible)` 또는 `:focus-within`은 parent highlight에 유용하지만 핵심 content 자체를 display:none으로 숨기지 않습니다.",
        "social icon library CDN 실패를 고려합니다. accessible name은 icon glyph와 독립적이어야 하고 self-host/version/SRI/CSP/cache를 관리하거나 inline SVG/icon component를 사용합니다. icon이 사라져도 link purpose가 assistive technology와 fallback text에 남아야 합니다.",
      ],
      concepts: [
        { term: "focus-visible", definition: "user agent heuristic상 명확한 focus indicator가 필요한 focus 상태를 선택하는 pseudo-class입니다.", detail: ["keyboard interaction에서 보통 match합니다.", "focus 자체를 제거하지 않습니다."] },
        { term: "pointer capability", definition: "hover 가능 여부와 primary pointing device의 정확도를 media feature로 나타낸 환경 특성입니다.", detail: ["device category와 동일하지 않습니다.", "기능 제거보다 enhancement 분기에 씁니다."] },
        { term: "reduced motion", definition: "사용자가 비필수 motion을 줄여 달라고 설정한 preference입니다.", detail: ["상태 feedback은 유지합니다.", "CSS와 JavaScript animation 모두 반영합니다."] },
      ],
      codeExamples: [
        {
          id: "semantic-team-card-audit",
          title: "semantic card와 link/media contract를 실행 중 자동 점검하기",
          language: "html",
          filename: "team-card-audit.html",
          purpose: "원본의 unnamed `href=#` icon link를 실제 destination/accessibility name으로 교정하고 구조적 acceptance criterion을 exact output으로 검사합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>팀 카드 audit</title>\n  <style>\n    .team { display:grid; grid-template-columns:repeat(auto-fit,minmax(min(100%,16rem),1fr)); gap:1rem; }\n    .social { display:flex; gap:.75rem; }\n    a:focus-visible { outline:3px solid CanvasText; outline-offset:4px; }\n    @media (hover:hover) and (pointer:fine) { article:hover { transform:translateY(-.25rem); } }\n    @media (prefers-reduced-motion:reduce) { article { transition:none; } article:hover { transform:none; } }\n  </style>\n</head>\n<body>\n  <section aria-labelledby=\"team-title\"><h1 id=\"team-title\">팀</h1><div class=\"team\">\n    <article><img src=\"james.webp\" width=\"320\" height=\"320\" alt=\"\"><h2>James Turner</h2><p>Founder</p><nav class=\"social\" aria-label=\"James Turner 연락처\"><a href=\"https://example.com/james\" aria-label=\"James Turner의 GitHub\">GitHub</a><a href=\"mailto:james@example.com\">이메일</a></nav></article>\n    <article><img src=\"luna.webp\" width=\"320\" height=\"320\" alt=\"\"><h2>Luna Hall</h2><p>Developer</p><nav class=\"social\" aria-label=\"Luna Hall 연락처\"><a href=\"https://example.com/luna\" aria-label=\"Luna Hall의 GitHub\">GitHub</a><a href=\"mailto:luna@example.com\">이메일</a></nav></article>\n    <article><img src=\"hope.webp\" width=\"320\" height=\"320\" alt=\"\"><h2>Hope Carpenter</h2><p>Designer</p><nav class=\"social\" aria-label=\"Hope Carpenter 연락처\"><a href=\"https://example.com/hope\" aria-label=\"Hope Carpenter의 GitHub\">GitHub</a><a href=\"mailto:hope@example.com\">이메일</a></nav></article>\n  </div></section>\n  <pre id=\"out\"></pre>\n  <script>\n    const links = [...document.querySelectorAll('a')];\n    const images = [...document.images];\n    document.querySelector('#out').textContent = [\n      `cards=${document.querySelectorAll('article').length}`,\n      `headings=${document.querySelectorAll('article h2').length}`,\n      `links=${links.length}`,\n      `placeholder-links=${links.filter(a => a.getAttribute('href') === '#').length}`,\n      `unnamed-links=${links.filter(a => !(a.textContent.trim() || a.getAttribute('aria-label'))).length}`,\n      `images-with-alt=${images.filter(img => img.hasAttribute('alt')).length}`,\n      `images-with-size=${images.filter(img => img.hasAttribute('width') && img.hasAttribute('height')).length}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-13", explanation: "Grid collection, Flex action row, focus-visible와 capability/motion media rule을 구성합니다." },
            { lines: "17-19", explanation: "각 card가 heading/role, redundant portrait empty alt decision, labeled contact nav와 실제 link를 가집니다." },
            { lines: "24-34", explanation: "card/heading/link 수, placeholder/unnamed link와 alt/intrinsic dimension 누락을 DOM에서 검사합니다." },
          ],
          run: { environment: ["현대 browser", "image file은 없어도 DOM audit output은 동일하며 production에서는 실제 optimized asset 필요"], command: "browser에서 team-card-audit.html을 열고 결과 확인" },
          output: { value: "cards=3\nheadings=3\nlinks=6\nplaceholder-links=0\nunnamed-links=0\nimages-with-alt=3\nimages-with-size=3", explanation: ["세 card가 각각 heading을 가져 collection을 탐색할 수 있습니다.", "모든 link는 실제 href와 visible/ARIA name을 갖습니다.", "portrait alt는 adjacent name과 중복이라 empty로 결정했지만 attribute와 intrinsic size는 모두 존재합니다."] },
          experiments: [
            { change: "첫 GitHub anchor를 `<a href=\"#\"><i ...></i></a>`로 되돌립니다.", prediction: "placeholder-links=1, icon에 text/aria-label이 없으면 unnamed-links=1도 됩니다.", result: "visual icon 존재와 accessible link contract는 다릅니다." },
            { change: "Tab으로 모든 link를 순회하고 reduced motion을 emulate합니다.", prediction: "focus outline은 유지되고 hover transform은 줄어듭니다.", result: "motion을 줄여도 action/state 식별은 유지합니다." },
            { change: "portrait가 adjacent heading과 다른 정보를 전달하도록 바꿉니다.", prediction: "empty alt decision을 재검토해야 합니다.", result: "alt는 파일 종류가 아니라 image purpose/context에 따라 정합니다." },
          ],
          sourceRefs: ["web-team-source", "web-team-css-source", "wai-focus-visible", "wai-images", "mediaqueries-5"],
        },
      ],
      diagnostics: [
        { symptom: "mouse hover에서는 card가 떠오르지만 keyboard 사용자는 현재 card와 link를 구분할 수 없다.", likelyCause: "hover transform/shadow만 있고 :focus-visible 또는 :focus-within indicator가 없습니다.", checks: ["Tab sequence와 computed outline을 확인합니다.", "forced colors/reduced motion에서 indicator를 봅니다.", "outline이 overflow:hidden에 잘리는지 확인합니다."], fix: "interactive link에 높은 대비 focus-visible outline을 주고 card에 focus-within cue를 추가하며 clip 영역을 조정합니다.", prevention: "mouse 없이 모든 action 수행과 focus screenshot/geometry assertion을 CI·수동 QA에 둡니다." },
      ],
    },
    {
      id: "content-stress-reflow-container",
      title: "responsive는 device 이름이 아니라 available container·zoom·극단 content에서 검증합니다",
      lead: "375/768/1440 screenshot 세 장보다 그 사이 폭과 긴 이름 한 개가 실제 algorithm의 약점을 더 잘 드러냅니다.",
      explanations: [
        "viewport를 320px부터 연속 sweep하고 breakpoint -1/exact/+1, split view와 sidebar embed를 test합니다. card component가 viewport보다 실제 parent width에 반응해야 하면 wrapper에 container-type:inline-size와 @container를 사용합니다.",
        "200%/400% zoom 또는 root font 확대에서 text가 잘리거나 2차원 scroll을 요구하지 않는지 봅니다. WCAG reflow 기준의 예외가 아닌 일반 team content는 narrow width에서 한 column으로 reflow하고 기능/정보를 잃지 않아야 합니다.",
        "content fixture는 한/영 긴 name, unbreakable URL, 1·2·3·4·100 cards, empty role, 8개 social links, missing/slow/tall/wide image, translated heading, RTL을 포함합니다. synthetic data만 사용해 개인정보를 공개 test에 넣지 않습니다.",
        "`min-inline-size:0`과 `overflow-wrap:anywhere`는 content를 무조건 잘라내는 hack이 아니라 layout item이 shrink하고 text가 legal emergency break를 만들게 합니다. code/table처럼 2D scroll이 본질이면 해당 region만 labeled overflow container로 둡니다.",
        "container query는 component 내부 mode를 actual wrapper width로 선택하고 media query는 page shell·user preference를 담당하게 분리합니다. 같은 viewport에서 main 700px와 sidebar 280px card를 동시에 render해 독립 반응을 검증합니다.",
        "document scrollWidth<=clientWidth 하나만으로 text clip을 모두 잡지는 못합니다. 각 critical card의 scrollWidth/clientWidth, bounding rect, computed overflow, visible focus rect와 screenshot을 함께 사용합니다.",
      ],
      concepts: [
        { term: "content stress test", definition: "길이·개수·언어·empty/error/media 실패를 극단화한 synthetic data로 layout resilience를 검증하는 test입니다.", detail: ["device preset의 빈틈을 찾습니다.", "privacy-safe fixture를 사용합니다."] },
        { term: "reflow", definition: "확대 또는 좁은 viewport에서 content가 한 방향으로 다시 배치되어 두 방향 scroll 없이 읽고 사용할 수 있게 되는 behavior입니다.", detail: ["정보/기능 손실이 없어야 합니다.", "본질적 2D content는 예외를 별도 처리합니다."] },
        { term: "container query", definition: "viewport가 아니라 ancestor query container의 actual size/style을 조건으로 descendant component style을 바꾸는 CSS rule입니다.", detail: ["재사용 component에 적합합니다.", "size containment와 fallback을 고려합니다."] },
      ],
      codeExamples: [
        {
          id: "narrow-card-stress-assertion",
          title: "320px component에서 긴 이름과 여러 card의 overflow를 자동 검사",
          language: "html",
          filename: "card-stress.html",
          purpose: "실제 viewport와 무관하게 320px fixture container를 만들고 intrinsic Grid와 emergency wrap이 한 column/무 overflow를 만드는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>Card stress</title>\n<style>\n  * { box-sizing:border-box; } body { margin:0; }\n  .fixture { inline-size:320px; max-inline-size:100%; display:grid; grid-template-columns:repeat(auto-fit,minmax(min(100%,200px),1fr)); gap:16px; }\n  .card { min-inline-size:0; border:1px solid; padding:12px; }\n  .card h2, .card a { overflow-wrap:anywhere; }\n</style></head>\n<body><main class=\"fixture\">\n  <article class=\"card\"><h2>아주긴이름을가진학습자겸개발자</h2><a href=\"https://example.com/very-long-profile-identifier-without-shortening\">프로필</a></article>\n  <article class=\"card\"><h2>InternationalizationWithoutNaturalBreaks</h2></article>\n  <article class=\"card\"><h2>빈 역할 fixture</h2></article>\n  <article class=\"card\"><h2>네 번째 구성원</h2></article>\n</main><pre id=\"out\"></pre>\n<script>\n  const fixture = document.querySelector('.fixture');\n  const cards = [...document.querySelectorAll('.card')];\n  const columns = getComputedStyle(fixture).gridTemplateColumns.split(' ').length;\n  document.querySelector('#out').textContent = [\n    `fixture=${fixture.getBoundingClientRect().width.toFixed(0)}`,\n    `columns=${columns}`,\n    `card-overflow=${cards.some(card => card.scrollWidth > card.clientWidth)}`,\n    `document-overflow=${document.documentElement.scrollWidth > document.documentElement.clientWidth}`,\n    `names=${document.querySelectorAll('.card h2').length}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "4-8", explanation: "320px Grid, min(100%,200px) track, card min-width 0과 emergency word break를 정의합니다." },
            { lines: "10-14", explanation: "한글 무공백·긴 Latin·empty role·추가 card variation을 synthetic fixture로 넣습니다." },
            { lines: "17-26", explanation: "resolved column 수와 component/document overflow, heading 수를 자동 assertion할 값으로 출력합니다." },
          ],
          run: { environment: ["content viewport 320 CSS px 이상인 현대 browser", "zoom 100% exact output 후 200/400% 별도 수동 검증"], command: "browser에서 card-stress.html을 열고 결과 확인" },
          output: { value: "fixture=320\ncolumns=1\ncard-overflow=false\ndocument-overflow=false\nnames=4", explanation: ["두 200px track과 16px gap은 320px에 들어가지 않아 한 column입니다.", "min-inline-size와 overflow-wrap으로 long min-content가 card를 밀지 않습니다.", "component fixed fixture가 viewport보다 크지 않도록 max-inline-size 100%를 둡니다."] },
          experiments: [
            { change: "overflow-wrap과 min-inline-size:0을 제거합니다.", prediction: "긴 Latin content에서 card 또는 document overflow가 true가 될 수 있습니다.", result: "track/item/text 세 층의 intrinsic minimum을 함께 진단합니다." },
            { change: "fixture inline-size를 416px로 바꿉니다.", prediction: "200+200+16이 정확히 들어가 2 columns가 됩니다.", result: "content-based boundary의 -1/exact/+1을 test합니다." },
            { change: "root font를 200%로 바꾸고 track minimum을 12.5rem으로 표현합니다.", prediction: "minimum CSS px가 커져 더 일찍 한 column으로 reflow합니다.", result: "rem breakpoint/track은 사용자 font preference와 함께 반응합니다." },
          ],
          sourceRefs: ["web-kitten-responsive-source", "web-team-css-source", "css-grid-2", "wai-reflow"],
        },
      ],
      diagnostics: [
        { symptom: "viewport 1440px인데 280px sidebar의 team card가 3열로 눌린다.", likelyCause: "component mode를 viewport media query로만 결정하고 actual container width를 보지 않았습니다.", checks: ["sidebar content box와 viewport width를 함께 기록합니다.", "same card main/sidebar fixture를 render합니다.", "container-type/name과 query match를 확인합니다."], fix: "stacked mobile baseline을 유지하고 card wrapper의 inline-size container query 또는 intrinsic auto-fit tracks로 actual space에 반응합니다.", prevention: "동일 viewport에서 240/320/700px container matrix를 visual/geometry test에 둡니다." },
      ],
    },
    {
      id: "integrated-grid-collection-flex-component-contract",
      title: "collection은 intrinsic Grid, card 내부는 Flex로 책임을 나눠 source order와 min-size를 보존합니다",
      lead: "capstone에서는 property를 많이 쓰는 대신 각 formatting context가 해결할 축과 content variation을 명확히 나누고 geometry invariant로 검증합니다.",
      explanations: [
        "team/gallery collection은 row와 column track 정렬이 동시에 필요하므로 Grid가 자연스럽습니다. `repeat(auto-fit,minmax(min(100%,18rem),1fr))`은 available size에 맞춰 column 수를 연속적으로 바꾸고 narrow container에서는 minimum이 100%를 넘지 않게 합니다.",
        "card 내부의 portrait·text·actions는 한 축 흐름과 group separation이 중심이므로 Flex가 적합합니다. text wrapper에는 min-inline-size:0, media에는 explicit dimensions/aspect-ratio, actions에는 gap과 wrap을 둡니다. layout primitive의 책임이 겹치지 않게 합니다.",
        "Grid `1fr`도 track minimum이 auto이면 min-content 때문에 넘칠 수 있습니다. `minmax(0,1fr)` 또는 content-aware minimum을 사용하고 long URL·localization·200~400% zoom에서 root scrollWidth를 확인합니다. fixed vw/vh card height로 content를 자르지 않습니다.",
        "auto-placement와 visual reorder는 DOM reading/focus order를 바꾸지 않습니다. 이름·역할·action의 semantic source order를 먼저 만들고 Grid area는 같은 의미 순서를 유지하는 presentation에만 사용합니다. RTL·vertical writing에서 start/end alignment도 확인합니다.",
        "large card list의 layout/paint 비용은 representative dataset으로 측정합니다. virtualization은 screen reader·find-in-page·focus 복귀에 영향을 주므로 무조건 적용하지 않고, content-visibility와 image lazy loading도 intrinsic placeholder와 user task를 검증합니다.",
      ],
      concepts: [
        { term: "layout responsibility split", definition: "collection의 2D track은 Grid, component 내부 한 축 흐름은 Flex처럼 각 formatting context의 책임을 분리하는 설계입니다.", detail: ["중첩은 목적이 있을 때 사용합니다.", "각 boundary의 min-size를 문서화합니다."] },
        { term: "intrinsic collection", definition: "고정 device breakpoint보다 item minimum과 available size로 column 수를 결정하는 collection layout입니다.", detail: ["auto-fit/minmax를 사용할 수 있습니다.", "long content floor를 검증합니다."] },
        { term: "source-order invariant", definition: "layout mode가 바뀌어도 의미·reading·focus·copy 순서가 DOM에서 유지되는 조건입니다.", detail: ["CSS order로 의미를 바꾸지 않습니다.", "keyboard와 accessibility tree로 검사합니다."] },
      ],
      codeExamples: [
        {
          id: "intrinsic-grid-flex-card-proof",
          title: "420px collection의 2×204px Grid와 Flex actions geometry 검증",
          language: "html",
          filename: "intrinsic-grid-flex.html",
          purpose: "fixed device breakpoint 없이 180px item minimum·12px gap에서 두 column을 만들고 DOM order·overflow를 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>intrinsic Grid와 Flex card</title>\n  <style>\n    body { margin: 0; }\n    .gallery { display: grid; inline-size: 420px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }\n    .card { box-sizing: border-box; min-inline-size: 0; border: 1px solid navy; padding: 8px; }\n    .actions { display: flex; flex-wrap: wrap; gap: 4px; }\n  </style>\n</head>\n<body>\n  <section class=\"gallery\" aria-label=\"학습자 목록\"><article class=\"card\" data-name=\"Alpha\"><h2>Alpha</h2><div class=\"actions\"><button>보기</button></div></article><article class=\"card\" data-name=\"Beta\"><h2>Beta</h2><div class=\"actions\"><button>보기</button></div></article><article class=\"card\" data-name=\"Gamma\"><h2>Gamma</h2><div class=\"actions\"><button>보기</button></div></article></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const gallery = document.querySelector('.gallery');\n    const cards = [...gallery.querySelectorAll('.card')];\n    const style = getComputedStyle(gallery);\n    document.querySelector('#result').textContent = [\n      `columns=${style.gridTemplateColumns.split(' ').length}`,\n      `tracks=${style.gridTemplateColumns}`,\n      `first-width=${Math.round(cards[0].getBoundingClientRect().width)}`,\n      `gap=${style.columnGap}`,\n      `actions-display=${getComputedStyle(cards[0].querySelector('.actions')).display}`,\n      `source-order=${cards.map((card) => card.dataset.name).join('>')}`,\n      `no-overflow=${gallery.scrollWidth === gallery.clientWidth}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-10", explanation: "420px Grid에 180px minimum과 12px gap, zero-minimum card와 Flex actions를 선언합니다." },
            { lines: "13-15", explanation: "Alpha-Beta-Gamma semantic DOM order를 세 article로 유지합니다." },
            { lines: "18-20", explanation: "collection·card list·computed track을 읽습니다." },
            { lines: "21-29", explanation: "두 204px tracks, gap, Flex 내부, source order와 no-overflow를 출력합니다." },
          ],
          run: { environment: ["CSS Grid/Flexbox 지원 현대 Chromium"], command: "browser에서 intrinsic-grid-flex.html을 열고 결과 확인" },
          output: { value: "columns=2\ntracks=204px 204px\nfirst-width=204\ngap=12px\nactions-display=flex\nsource-order=Alpha>Beta>Gamma\nno-overflow=true", explanation: ["420px에서 gap 12px을 뺀 408px이 두 204px tracks로 나뉩니다.", "card 내부 actions는 Flex로 별도 formatting context를 가집니다.", "DOM source order와 no-overflow invariant가 유지됩니다."] },
          experiments: [
            { change: "gallery inline-size를 179px로 바꿉니다.", prediction: "180px minimum 때문에 horizontal overflow가 생길 수 있습니다.", result: "production에서는 minmax(min(100%,180px),1fr) 같은 narrow guard를 사용합니다." },
            { change: "grid-auto-flow:dense와 explicit placement를 섞습니다.", prediction: "visual 순서가 DOM과 달라질 수 있습니다.", result: "dense packing은 reading/focus sequence를 바꾸지 않으므로 의미 order에 주의합니다." },
            { change: "collection을 flex-wrap으로 바꿉니다.", prediction: "wrap은 가능하지만 서로 다른 line의 columns가 track으로 정렬되지 않습니다.", result: "1D Flex와 2D Grid의 책임 차이를 확인합니다." },
          ],
          sourceRefs: ["web-kitten-responsive-source", "css-grid-2", "css-flexbox-1", "css-sizing-4"],
        },
      ],
      diagnostics: [
        { symptom: "responsive gallery의 card widths가 line마다 어긋나고 long title이 root를 넘친다.", likelyCause: "2D collection을 ad-hoc flex percentages로 만들고 item automatic minimum을 방치했습니다.", checks: ["Grid/Flex overlay에서 track/line을 비교합니다.", "long item의 min-content·min-inline-size를 확인합니다.", "gallery scrollWidth와 320px boundary를 기록합니다."], fix: "collection을 intrinsic Grid tracks로 전환하고 card/text zero-minimum·wrapping 계약을 명시합니다.", prevention: "continuous width·long localization·DOM order fixture를 capstone CI에 둡니다." },
      ],
    },
    {
      id: "accessible-card-assets-motion-security-contract",
      title: "card의 image·link·focus·motion은 responsive geometry와 함께 실패·보안 계약으로 검증합니다",
      lead: "보기 좋은 portfolio card를 넘어 image 실패, keyboard, external link, reduced motion, forced colors와 untrusted content 경계를 하나의 component acceptance로 묶습니다.",
      explanations: [
        "portrait alt는 context에서 image가 전달하는 정보를 설명합니다. 인접 name을 단순 반복하는 장식 portrait라면 빈 alt가 적절할 수 있고, 사람 식별에 필요하면 이름을 포함합니다. width/height 또는 aspect-ratio로 load 전 공간을 예약해 layout shift를 줄입니다.",
        "social link는 icon 모양만 두지 않고 accessible name 또는 visible label을 제공합니다. external new tab에는 사용자 기대와 `rel=noopener` 경계를 검토하고, URL은 신뢰된 data model에서 생성합니다. `javascript:`·raw SVG·untrusted href를 그대로 삽입하지 않습니다.",
        "hover elevation은 keyboard focus-visible과 touch baseline을 함께 제공합니다. prefers-reduced-motion에서 transform transition을 줄여도 border·outline·text로 state가 남아야 합니다. forced colors에서 box-shadow가 사라져도 control boundary와 focus가 보이는지 확인합니다.",
        "card는 320px container·400% zoom·긴 name/role·0/1/many links에서 content-driven height로 자랍니다. fixed vh height와 overflow hidden으로 text를 자르지 않고 min-inline-size:0·overflow-wrap을 사용합니다. RTL과 vertical writing에서 logical padding/gap을 검사합니다.",
        "lazy loading과 third-party image는 performance·privacy·CSP·failure fallback을 포함합니다. 로그에는 raw profile URL·token을 남기지 않고 aggregate layout/error code만 기록합니다. CSS로 숨긴 private card도 DOM에서 읽히므로 server authorization으로 data를 제외합니다.",
      ],
      concepts: [
        { term: "accessible card contract", definition: "heading·image alternative·role text·action names·focus order가 layout 변화와 무관하게 유지되는 component 규칙입니다.", detail: ["card 전체 click target 중첩을 피합니다.", "0/1/many actions를 test합니다."] },
        { term: "resource reservation", definition: "image/font load 전에 width·height·aspect-ratio와 fallback으로 필요한 layout 공간을 확보하는 전략입니다.", detail: ["layout shift를 줄입니다.", "failure에서도 content를 보존합니다."] },
        { term: "external-link trust boundary", definition: "외부 URL의 scheme/origin, 새 창 관계, accessible label을 승인된 policy로 통제하는 경계입니다.", detail: ["raw user href를 사용하지 않습니다.", "rel·CSP와 server validation을 결합합니다."] },
      ],
      codeExamples: [
        {
          id: "accessible-team-card-release-proof",
          title: "320px team card의 image·links·focus·motion·overflow release invariant",
          language: "html",
          filename: "team-card-release.html",
          purpose: "external resource 없이 semantic card를 렌더링하고 geometry·alt·safe rel·focus·preference를 exact output으로 감사합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>team card release</title>\n  <style>\n    body { margin: 0; }\n    .card { box-sizing: border-box; display: flex; flex-direction: column; inline-size: 320px; min-inline-size: 0; gap: 8px; padding: 12px; border: 2px solid navy; transition: transform .2s; }\n    .portrait { inline-size: 80px; block-size: 80px; object-fit: cover; border-radius: 50%; }\n    .links { display: flex; flex-wrap: wrap; gap: 8px; }\n    .links a:focus { outline: 3px solid currentColor; outline-offset: 2px; }\n    @media (prefers-reduced-motion: reduce) { .card { transition-duration: 0s; } }\n  </style>\n</head>\n<body>\n  <article class=\"card\"><img class=\"portrait\" width=\"80\" height=\"80\" alt=\"Luna 학습자\" src=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Crect width='80' height='80' fill='lavender'/%3E%3C/svg%3E\"><h1>Luna</h1><p>Frontend learner</p><nav class=\"links\" aria-label=\"Luna 외부 링크\"><a href=\"https://example.com/profile\" rel=\"noopener noreferrer\">프로필</a><a href=\"https://example.org/notes\" rel=\"noopener noreferrer\">학습 노트</a></nav></article>\n  <pre id=\"result\"></pre>\n  <script>\n    const card = document.querySelector('.card');\n    const image = document.querySelector('.portrait');\n    const links = [...document.querySelectorAll('.links a')];\n    links[0].focus();\n    const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;\n    const duration = getComputedStyle(card).transitionDuration;\n    document.querySelector('#result').textContent = [\n      `card-width=${Math.round(card.getBoundingClientRect().width)}`,\n      `image=${Math.round(image.getBoundingClientRect().width)}x${Math.round(image.getBoundingClientRect().height)}`,\n      `alt=${image.alt}`,\n      `links=${links.length}`,\n      `safe-rel=${links.every((link) => link.relList.contains('noopener') && link.relList.contains('noreferrer'))}`,\n      `focus-target=${document.activeElement === links[0]}`,\n      `motion-contract=${reduce ? duration === '0s' : duration === '0.2s'}`,\n      `no-overflow=${card.scrollWidth === card.clientWidth}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-12", explanation: "320px content-driven Flex card, reserved portrait, wrapping links, focus와 motion preference를 선언합니다." },
            { lines: "15-17", explanation: "semantic article·heading·informative alt·visible external link labels와 safe rel을 둡니다." },
            { lines: "20-25", explanation: "card/image/links를 읽고 첫 link focus와 current motion preference를 적용합니다." },
            { lines: "26-35", explanation: "geometry·alt·link safety·focus·motion·overflow release invariants를 출력합니다." },
          ],
          run: { environment: ["현대 Chromium", "reduced-motion emulation 선택"], command: "browser에서 team-card-release.html을 열고 결과 확인" },
          output: { value: "card-width=320\nimage=80x80\nalt=Luna 학습자\nlinks=2\nsafe-rel=true\nfocus-target=true\nmotion-contract=true\nno-overflow=true", explanation: ["card와 reserved portrait geometry가 정확히 유지됩니다.", "두 external links는 visible name과 noopener/noreferrer를 갖고 첫 link가 focus됩니다.", "motion preference 양쪽에서 policy와 computed duration이 일치하며 overflow가 없습니다."] },
          experiments: [
            { change: "role text를 매우 긴 독일어/한국어로 바꿉니다.", prediction: "card height는 늘고 inline overflow는 없어야 합니다.", result: "content-driven height와 wrapping을 release gate로 둡니다." },
            { change: "image src를 실패 URL로 바꿉니다.", prediction: "reserved 80×80 공간과 alt는 남고 layout shift가 제한됩니다.", result: "resource failure에서도 card task를 유지합니다." },
            { change: "href를 사용자 입력 javascript:로 바꿉니다.", prediction: "CSS는 막지 못하므로 URL validation policy에서 거부해야 합니다.", result: "link security는 trusted data boundary 책임입니다." },
          ],
          sourceRefs: ["web-team-source", "web-team-css-source", "web-logical-alignment-source", "css-flexbox-1", "mediaqueries-5", "wai-focus-visible", "wai-images"],
        },
      ],
      diagnostics: [
        { symptom: "team card가 hover에서는 멋지지만 keyboard focus가 안 보이고 image load 때 page가 밀린다.", likelyCause: "hover shadow·unreserved image만 설계하고 focus/resource failure contract를 누락했습니다.", checks: ["Accessibility tree와 Tab 순서를 확인합니다.", "image width/height와 load 전후 Layout Shift를 기록합니다.", "forced-colors/reduced-motion에서 style을 봅니다."], fix: "visible/action name·focus outline·image dimensions/aspect ratio·preference fallback을 component contract로 추가합니다.", prevention: "keyboard·image failure·motion·forced-colors·zoom fixture를 release CI에 둡니다." },
      ],
    },
    {
      id: "release-observability-performance-privacy-governance",
      title: "release evidence는 screenshot을 넘어 geometry·accessibility·network·performance·privacy를 연결합니다",
      lead: "완료 기준을 예쁜 한 viewport가 아니라 continuous widths와 실패 조건에서 task가 유지된다는 재현 가능한 증거로 정의합니다.",
      explanations: [
        "320~1440px continuous width sweep에서 root overflow, column count, card minimum, focus clipping을 자동 검사하고 content-driven boundary 양옆을 집중 확인합니다. exact pixel은 fixed geometry에, boolean/range는 font·scrollbar 의존 결과에 사용합니다.",
        "visual regression은 border·shadow·spacing drift를 잡지만 DOM order·accessible name·keyboard·Network failure를 보장하지 않습니다. semantic assertion, tab task, axe/manual screen reader, computed geometry와 screenshot을 risk별로 결합합니다.",
        "Performance panel과 Web Vitals로 image/font layout shift, long task, style/layout/paint 비용을 측정합니다. observer와 analytics가 모든 card text·URL·rect를 수집하지 않게 aggregate sentinel과 sampling을 사용하고 개인정보·token은 log에서 제거합니다.",
        "Console error·unhandled rejection·failed request를 0으로 유지하되 의도적 failure fixture는 assertion으로 소비합니다. source map·error report에 local path·secret query가 들어가지 않는지 확인하고 external asset CSP·SRI/version·license를 감사합니다.",
        "release checklist는 owner와 재현 URL/fixture, expected output, browser/AT matrix, budget을 포함합니다. 예외는 만료일과 근거를 두며 다음 변경에서 자동으로 재평가합니다. design token 수치보다 user-visible invariant를 우선합니다.",
      ],
      concepts: [
        { term: "release invariant", definition: "viewport·content·preference가 달라도 반드시 유지되어야 하는 task·order·overflow·focus 조건입니다.", detail: ["환경별 exact/range를 구분합니다.", "실패 fixture에도 적용합니다."] },
        { term: "privacy-preserving observability", definition: "사용자 content·URL·정밀 geometry를 과수집하지 않고 aggregate error/performance signal만 수집하는 운영 방식입니다.", detail: ["sampling과 redaction을 사용합니다.", "local reproduction fixture와 연결합니다."] },
        { term: "evidence bundle", definition: "source provenance, automated result, browser geometry, accessibility task, network/performance trace를 한 release decision에 연결한 기록입니다.", detail: ["단일 screenshot보다 재현 가능합니다.", "owner와 환경을 포함합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "visual snapshot은 통과하지만 production에서 console error·horizontal overflow·개인 URL logging이 발생한다.", likelyCause: "paint 비교만 release gate로 사용하고 behavior/network/privacy evidence를 연결하지 않았습니다.", checks: ["console·network·root scroll invariant를 수집합니다.", "analytics payload에 raw text/URL/rect가 있는지 봅니다.", "keyboard·zoom·failure fixture를 실행합니다."], fix: "geometry·semantic·interaction·network·performance·privacy gates를 evidence bundle로 묶고 실패 owner를 지정합니다.", prevention: "continuous width와 logs0/privacy scan을 CI 및 pre-release checklist에 포함합니다." },
      ],
    },
    {
      id: "visual-regression-performance-release",
      title: "release gate는 screenshot diff에 geometry·DOM·focus·network·preference assertion을 더합니다",
      lead: "픽셀 차이는 원인을 알려 주지 않고, 픽셀 동일은 접근성 tree와 link가 깨지지 않았다는 보장도 아닙니다.",
      explanations: [
        "automated matrix는 narrow/boundary/wide container, 320/768/1024/1440 viewport, long/empty/many content, light/dark/forced colors, reduced motion, LTR/RTL을 선택합니다. 모든 조합을 무작정 screenshot하지 않고 위험 기반 representative pair와 property assertion을 구성합니다.",
        "geometry assertion에는 document/card overflow, column count, card overlap, focus rect viewport intersection, image aspect slot, action target rect가 포함됩니다. DOM assertion에는 article-heading 관계, link accessible name/href, alt decision, positive tabindex 0, duplicate id 0을 둡니다.",
        "visual regression은 stable font/image/animation/time/viewport를 사용하고 anti-aliasing tolerance를 정합니다. snapshot update에는 before/after와 requirement 근거가 필요하며 실패를 모두 baseline 갱신으로 덮지 않습니다.",
        "Performance에서는 responsive image가 적절한 intrinsic size/format을 요청하는지, CSS/Font Awesome CDN이 render를 막는지, image load 전후 layout shift와 card count 증가 시 style/layout/paint cost를 측정합니다. box-shadow/blur/filter/transform animation은 low-end device에서 profile합니다.",
        "keyboard 수동 test는 skip/heading navigation, Tab/Shift+Tab order, Enter activation, focus visibility, no trap을 확인합니다. 200/400% zoom과 browser text-only zoom, high contrast/forced colors, touch 실제 기기에서 information/action parity를 봅니다.",
        "production monitoring에는 layout shift, resource error, rage click 같은 aggregate privacy-safe signal을 둘 수 있지만 content/URL/PII를 그대로 수집하지 않습니다. synthetic fixture와 local absolute path/private backup URL이 public output에 들어가지 않게 scan합니다.",
        "완료 문서에는 original evidence, design decisions, supported browser/feature fallback, run command, exact output, known limitation과 next regression owner를 남깁니다. capstone은 page 한 장보다 반복 가능한 workflow가 산출물입니다.",
      ],
      concepts: [
        { term: "visual regression", definition: "동일한 통제 환경의 screenshot을 승인 baseline과 비교해 의도하지 않은 rendering 변화를 찾는 test입니다.", detail: ["semantic assertion을 대신하지 않습니다.", "font/animation/data를 안정화합니다."] },
        { term: "geometry assertion", definition: "element rectangle·overflow·column/overlap처럼 layout 결과를 수치/boolean으로 검사하는 assertion입니다.", detail: ["pixel diff 원인 파악을 돕습니다.", "continuous/boundary test에 적합합니다."] },
        { term: "regression matrix", definition: "viewport/container/content/preference/input/network 축에서 위험을 대표하는 조합을 선정한 test set입니다.", detail: ["전수조합보다 목적 있게 고릅니다.", "자동과 수동 owner를 나눕니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "screenshot test는 통과하지만 social link 세 개가 모두 같은 profile URL로 이동한다.", likelyCause: "visual pixel만 비교하고 DOM href/accessible name과 activation 결과를 검사하지 않았습니다.", checks: ["각 card의 link name/href pair를 snapshot합니다.", "keyboard/click 후 destination을 intercept해 비교합니다.", "data key와 rendered URL mapping을 확인합니다."], fix: "semantic DOM contract와 navigation integration assertion을 visual test 옆에 추가합니다.", prevention: "card별 unique fixture ID와 expected destination matrix를 release gate에 둡니다." },
        { symptom: "작은 text anti-aliasing 차이 때문에 visual baseline이 매번 실패한다.", likelyCause: "OS/font/browser/animation을 통제하지 않고 strict pixel equality를 사용했습니다.", checks: ["runner OS/browser/font version과 device scale을 기록합니다.", "webfont load와 animation settle을 기다렸는지 봅니다.", "diff가 geometry/content인지 edge rendering noise인지 분류합니다."], fix: "고정 runner/font/browser, reduced motion/animation disable, deterministic data를 사용하고 의미 있는 tolerance/mask를 최소 범위에 적용합니다.", prevention: "baseline environment를 container/CI image로 versioned하고 geometry/DOM assertion으로 핵심 실패를 별도 포착합니다." },
      ],
      expertNotes: [
        "Grid dense auto-placement는 빈 칸을 채우려고 visual order를 바꿀 수 있으므로 card collection에서는 reading/focus order 영향을 먼저 검증합니다.",
        "subgrid를 사용하면 nested card의 name/role/action row가 parent track에 맞을 수 있지만 fallback과 content coupling 비용을 비교합니다. card 자체 content flow로 충분하면 단순 구조가 낫습니다.",
        "container query와 content-visibility 최적화는 실제 측정 후 도입합니다. offscreen rendering 절감이 find-in-page, focus, intrinsic size와 accessibility behavior에 미치는 영향을 target browser에서 확인합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 Our Team과 고양이 gallery를 공개 가능한 responsive component page로 재구축하기",
    scenario: "현재 page는 30vw×60vh card, 10vh heading, intrinsic-size-dependent gallery, 빈/placeholder social link와 hover 중심 effect를 사용해 narrow/zoom/RTL/keyboard/image failure에서 깨집니다.",
    setup: [
      "원본 HTML/CSS 네 파일과 사용 image의 intrinsic size·license·alt purpose를 read-only evidence로 inventory합니다.",
      "320~1600px continuous viewport와 240/320/700px container, root font 100/200/400%, RTL·reduced motion·forced colors 환경을 준비합니다.",
      "normal/long/empty/100 cards, broken/slow/wide/tall image, icon CDN failure synthetic fixture를 준비합니다.",
      "before screenshot, DOM/accessibility tree, scrollWidth, card rect/column count, Tab sequence와 network/layout shift를 기록합니다.",
    ],
    steps: [
      "section/list/article/heading/role/contact의 semantic DOM과 logical source/focus order를 CSS 없이 완성합니다.",
      "portrait alt purpose, intrinsic width/height, aspect-ratio/object-fit/fallback policy와 actual asset/license를 결정합니다.",
      "collection은 intrinsic Grid auto-fit/minmax, card 내부 action은 Flex를 사용하고 fixed vw/vh size를 content flow/token으로 교체합니다.",
      "long content에 min-inline-size:0/overflow-wrap, missing/empty/data count state와 card footer alignment를 적용합니다.",
      "placeholder link를 실제 destination과 accessible name으로 바꾸고 focus-visible/focus-within/touch target을 구현합니다.",
      "hover transform은 fine-pointer enhancement로 제한하고 reduced motion/forced colors에서 non-motion state cue를 유지합니다.",
      "320px·zoom·breakpoint/container boundary·RTL·long/100 cards·broken/slow image에서 overflow/overlap/focus/task를 검증합니다.",
      "DOM/geometry/accessibility/network assertion과 stable screenshot diff를 CI release gate로 만들고 decision/known limit을 문서화합니다.",
    ],
    expectedResult: [
      "CSS가 없어도 member와 contact source order가 논리적이고 모든 action은 실제 link/name을 가집니다.",
      "collection은 available container에 따라 1~여러 column으로 reflow하고 320px·400% zoom에서 page horizontal overflow가 없습니다.",
      "긴 이름·역할·missing image·많은 card에서도 content/action이 잘리거나 겹치지 않습니다.",
      "hover 없이 keyboard/touch로 모든 action을 식별·실행하고 reduced motion/forced colors에서 focus·상태가 유지됩니다.",
      "image load 전후 slot이 안정적이고 responsive asset/network/CLS budget을 만족합니다.",
      "visual change가 DOM·geometry·focus·destination assertion과 함께 review되어 baseline 남용 없이 회귀가 차단됩니다.",
    ],
    cleanup: ["실험용 placeholder URL, missing image request, debug outline, motion override와 100-card fixture를 production bundle에서 제거합니다.", "DevTools emulation/zoom/locale을 reset하고 default 환경에서 final keyboard/navigation을 다시 검증합니다."],
    extensions: ["parent/child card row alignment에 subgrid를 적용하고 fallback/complexity를 비교합니다.", "picture/srcset/sizes와 AVIF/WebP fallback을 추가해 viewport/DPR별 실제 request bytes를 측정합니다.", "Playwright 또는 동등 browser runner로 continuous-width sample, axe/DOM contract, visual/CLS gate를 자동화합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 Our Team을 semantic article card와 intrinsic Grid로 바꾸고 720px track geometry를 계산하세요.", requirements: ["section heading과 card h2를 사용합니다.", "placeholder link를 actual href/name으로 바꿉니다.", "auto-fit/minmax/gap과 card min-inline-size를 적용합니다.", "계산한 column/card width와 getBoundingClientRect output을 비교합니다."], hints: ["gap을 먼저 제외한 leftover를 fr로 나눕니다.", "portrait empty alt가 적절한지 nearby name과 목적을 근거로 결정합니다."], expectedOutcome: "세 card가 720px에서 계산한 3열로 배치되고 DOM/link/media audit가 모두 통과합니다.", solutionOutline: ["semantic DOM→base one-column→intrinsic Grid→measurement 순으로 진행합니다.", "Grid와 card 내부 Flex의 책임을 분리합니다."] },
    { difficulty: "응용", prompt: "team card에 long/empty/broken image/RTL/reduced motion/forced colors stress state를 추가하세요.", requirements: ["240/320/700px container와 200/400% zoom을 test합니다.", "긴 한글/Latin/URL의 overflow를 막되 identity를 숨기지 않습니다.", "image slot/fallback과 layout shift를 관리합니다.", "focus-visible와 touch action을 hover 없이 제공합니다.", "document/card overflow와 focus rect를 자동 assertion합니다."], hints: ["fixed block-size를 먼저 의심합니다.", "min-inline-size와 text wrapping을 track/item/content 세 층에서 봅니다."], expectedOutcome: "모든 state에서 card content와 action이 사용 가능하고 horizontal overflow·overlap·focus loss가 없습니다.", solutionOutline: ["synthetic fixture를 data-driven으로 생성합니다.", "preference/input mode는 기능 제거가 아니라 enhancement 분기에 씁니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 reusable card layout과 회귀 test governance를 설계하세요.", requirements: ["Grid/Flex/container/media 책임과 design token을 정의합니다.", "semantic/card image/link/alt contract를 정합니다.", "viewport·container·content·locale·zoom·preference·network matrix를 만듭니다.", "DOM/geometry/accessibility/performance/visual gate와 tolerance를 정의합니다.", "baseline 승인, browser support/fallback, privacy-safe telemetry와 owner를 포함합니다."], hints: ["screenshot만으로 완료하지 않습니다.", "모든 조합 대신 위험 기반 representative matrix와 boundary를 고릅니다."], expectedOutcome: "여러 module이 같은 card primitive를 안전하게 재사용하고 변경 근거와 회귀 owner가 명확한 implementation-ready specification이 완성됩니다.", solutionOutline: ["component invariant와 environment axes를 분리합니다.", "자동 assertion과 사람이 판단할 readability/crop/motion 항목을 나눕니다."] },
  ],
  reviewQuestions: [
    { question: "Flexbox와 Grid 중 어느 것이 항상 더 좋은가요?", answer: "항상 우위인 것은 없습니다. 한 축 content distribution/wrap은 Flex, 행·열 track의 2차원 alignment는 Grid가 더 직접적이며 함께 사용할 수 있습니다." },
    { question: "1fr은 container 전체의 1/n인가요?", answer: "항상 아닙니다. gap·고정/intrinsic track과 minimum 요구를 처리한 leftover space를 flexible track끼리 나눕니다." },
    { question: "auto-fit과 auto-fill의 핵심 차이는 무엇인가요?", answer: "available space에 반복 track을 만들되 auto-fit은 empty track을 collapse하고 auto-fill은 그 자리를 유지할 수 있습니다." },
    { question: "`minmax(0,1fr)`의 0은 왜 쓰나요?", answer: "track의 automatic min-content minimum이 긴 content 때문에 container를 밀어내지 않게 flexible shrink 하한을 0으로 두기 위해 사용합니다." },
    { question: "모든 card 높이를 60vh로 맞추면 왜 위험한가요?", answer: "viewport·toolbar·zoom·번역 content와 무관한 fixed 높이라 text/action이 넘치거나 빈 공간이 커집니다. content flow와 track alignment를 사용합니다." },
    { question: "team portrait의 alt는 반드시 이름이어야 하나요?", answer: "목적에 따라 다릅니다. adjacent heading이 동일 정보를 충분히 제공해 반복이면 empty alt가 적절할 수 있고 이미지가 추가 식별 정보를 전달하면 설명합니다." },
    { question: "hover effect가 있으면 focus style도 자동으로 생기나요?", answer: "아닙니다. :focus-visible/:focus-within과 keyboard activation을 별도로 설계해야 합니다." },
    { question: "prefers-reduced-motion에서는 모든 변화와 focus indicator를 없애나요?", answer: "아닙니다. 비필수 motion을 줄이되 focus·loading·success 같은 상태 정보는 non-motion cue로 유지합니다." },
    { question: "responsive test는 세 device preset이면 충분한가요?", answer: "아닙니다. 연속/경계 폭, 실제 container, zoom, long/empty/many content, RTL, preference와 network 상태가 필요합니다." },
    { question: "visual snapshot이 같으면 접근성 회귀도 없나요?", answer: "아닙니다. href, accessible name, DOM/focus order와 keyboard behavior는 pixel이 같아도 깨질 수 있어 별도 assertion이 필요합니다." },
    { question: "collection에 Grid, card 내부에 Flex를 함께 써도 되나요?", answer: "네. 2D track collection과 1D component flow처럼 각 formatting context의 책임이 분명하면 자연스러운 조합입니다." },
    { question: "420px Grid에서 두 columns와 12px gap이면 각 track은 얼마인가요?", answer: "다른 고정 track이 없다면 (420-12)/2=204px입니다." },
    { question: "grid-auto-flow:dense가 DOM reading order도 재정렬하나요?", answer: "아닙니다. visual placement만 바뀌므로 의미·focus order와 어긋날 수 있습니다." },
    { question: "image width/height attribute는 responsive image를 고정 크기로만 만드나요?", answer: "아닙니다. intrinsic ratio와 load 전 공간을 제공하며 CSS max size로 responsive rendering할 수 있습니다." },
    { question: "external link에 rel만 추가하면 untrusted URL이 안전해지나요?", answer: "아닙니다. scheme/origin validation과 trusted data boundary가 필요하며 rel은 새 browsing context 위험 일부만 줄입니다." },
    { question: "모든 card의 exact screenshot만 저장하면 release evidence가 충분한가요?", answer: "아닙니다. geometry·DOM order·keyboard·accessible name·network failure·performance·privacy 결과를 함께 연결해야 합니다." },
  ],
  completionChecklist: [
    "원본 네 파일의 intent와 fixed size/link/media/source-order 결함을 재현 evidence로 기록했다.",
    "CSS off에서도 section/card heading/contact DOM과 focus 순서가 논리적이다.",
    "Grid collection과 Flex card 내부를 axis/track 요구로 선택하고 geometry를 계산했다.",
    "auto-fit/auto-fill·minmax·fr·gap·automatic minimum 차이를 실행 결과로 검증했다.",
    "fixed vw/vh card를 content flow, intrinsic media ratio와 responsive max size로 교체했다.",
    "long/empty/missing/many/RTL content에서 overflow·clip·overlap이 없다.",
    "실제 link/accessibility name, alt purpose, intrinsic image size와 failure fallback을 제공했다.",
    "hover·focus-visible·touch·reduced motion·forced colors에서 정보와 action이 유지된다.",
    "320px·200/400% zoom·container/breakpoint 경계와 slow image에서 reflow/CLS를 검증했다.",
    "DOM·geometry·focus·network·visual regression gate와 baseline 승인 절차를 문서화했다.",
    "intrinsic Grid collection과 Flex card 내부의 책임·minimum·gap을 수치로 검산했다.",
    "DOM source order와 visual Grid placement를 keyboard·accessibility tree에서 대조했다.",
    "portrait dimensions/aspect ratio·alt·failure fallback으로 layout shift와 정보 손실을 줄였다.",
    "external URL scheme/origin·rel·visible label을 trusted link policy로 검증했다.",
    "continuous width·long locale·RTL·motion·forced colors에서 release invariants를 통과했다.",
    "logs0·root overflow·Web Vitals·privacy redaction을 evidence bundle에 포함했다.",
  ],
  nextSessions: ["xml-01-wellformed-tree-encoding"],
  sources: [
    { id: "web-kitten-responsive-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex21_test.html", usedFor: ["Flex gallery", "image width/height", "768/769~1024 media", "1/2/3 column intent"], evidence: "세 kitten image의 wrap/45% tablet/column mobile rule을 intrinsic Grid/Flex·image ratio·continuous boundary test의 실제 출발점으로 사용했습니다." },
    { id: "web-team-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex22_flex_test.html", usedFor: ["Our Team content", "three member cards", "portrait alt", "social icon links", "external icon CSS"], evidence: "James/Luna/Hope의 name·role·portrait·네 social links 전체를 semantic card와 link/accessibility/media audit에 반영했습니다." },
    { id: "web-team-css-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/css/our-team.css", usedFor: ["10vh heading", "30vw×60vh card", "Flex wrap/center", "border/radius/shadow"], evidence: "fixed viewport sizing과 heavy shadow를 content-driven Grid/card token으로 교정하고 zoom/long-content regression의 근거로 사용했습니다." },
    { id: "web-logical-alignment-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/test.html", usedFor: ["justify start versus left", "LTR/RTL", "logical alignment", "source order review"], evidence: "LTR/RTL start/left 비교를 physical property 대신 logical DOM/layout order를 검증하는 capstone criterion으로 확장했습니다." },
    { id: "css-grid-2", repository: "W3C CSS Working Group", path: "TR/css-grid-2/", publicUrl: "https://www.w3.org/TR/css-grid-2/", usedFor: ["2D Grid model", "track/line/cell", "repeat auto-fit/auto-fill", "minmax/fr", "auto placement", "reordering accessibility", "subgrid"], evidence: "2026-07-12 확인한 Grid Level 2의 track sizing·repeat·placement와 source-order accessibility guidance를 collection layout 기준으로 사용했습니다." },
    { id: "css-flexbox-1", repository: "W3C CSS Working Group", path: "TR/css-flexbox-1/", publicUrl: "https://www.w3.org/TR/css-flexbox-1/", usedFor: ["single-axis layout", "wrap/free space", "automatic minimum", "source/visual order"], evidence: "Grid와 Flex의 역할 비교 및 card 내부 social action row의 sizing/order 기준으로 사용했습니다." },
    { id: "css-sizing-4", repository: "W3C CSS Working Group", path: "TR/css-sizing-4/", publicUrl: "https://www.w3.org/TR/css-sizing-4/", usedFor: ["intrinsic/min/max sizing", "aspect-ratio", "min-content/max-content", "containment sizing"], evidence: "fixed vw/vh를 content/intrinsic sizing으로 교체하고 media ratio와 overflow minimum을 설명하는 기준으로 사용했습니다." },
    { id: "mediaqueries-5", repository: "W3C CSS Working Group", path: "TR/mediaqueries-5/", publicUrl: "https://www.w3.org/TR/mediaqueries-5/", usedFor: ["width range", "hover/pointer", "prefers-reduced-motion", "forced colors/preferences", "conditional enhancement"], evidence: "viewport와 input/user preference를 capability 기반 progressive enhancement로 분기하는 기준으로 사용했습니다." },
    { id: "wai-reflow", repository: "W3C Web Accessibility Initiative", path: "WCAG22/Understanding/reflow", publicUrl: "https://www.w3.org/WAI/WCAG22/Understanding/reflow.html", usedFor: ["320 CSS px", "400% zoom", "two-dimensional scroll", "content/function preservation"], evidence: "narrow/zoom release gate에서 general team card가 한 방향으로 reflow하고 정보·기능을 잃지 않는 기준으로 사용했습니다." },
    { id: "wai-focus-visible", repository: "W3C Web Accessibility Initiative", path: "WCAG22/Understanding/focus-visible", publicUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html", usedFor: ["keyboard focus indicator", "focus visibility", "persistent state cue", "manual QA"], evidence: "hover-only card를 keyboard에서도 식별·작동하게 하는 focus-visible criterion의 근거로 사용했습니다." },
    { id: "wai-images", repository: "W3C Web Accessibility Initiative", path: "tutorials/images/", publicUrl: "https://www.w3.org/WAI/tutorials/images/", usedFor: ["informative/redundant/decorative image", "alt decision", "functional image"], evidence: "team portrait와 gallery image의 목적을 context별로 판단하고 빈 alt를 자동 오류로 취급하지 않는 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 4,
    filesUsed: 4,
    uncoveredNotes: [
      "원본 네 파일은 Flex responsive gallery, team card content와 fixed viewport styling, LTR/RTL logical alignment를 직접 제공합니다. semantic/accessibility, intrinsic Grid, content/media stress, visual regression과 performance는 W3C CSS/WAI 표준으로 보강했습니다.",
      "원본에는 실제 social destination, asset license/build pipeline, automated browser test와 design token system이 없습니다. 공개 site에 적용할 때는 real data/asset provenance와 route별 integration 결과를 별도 확인해야 합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
