import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-06-borders-shadows-margin-collapse"],
  slug: "css-06-borders-shadows-margin-collapse",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 6,
  title: "테두리·둥근 모서리·그림자와 마진 상쇄",
  subtitle: "box의 경계를 그리는 border부터 논리 방향, radius clipping, 접근 가능한 outline, 다층 shadow, auto·negative margin과 세로 margin collapse의 실제 geometry까지 측정하며 익힙니다.",
  level: "중급",
  estimatedMinutes: 225,
  coreQuestion: "box의 크기와 문서 흐름을 망가뜨리지 않으면서 경계·깊이·간격을 표현하고, 예상 밖의 여백을 실제 geometry로 어떻게 진단할까요?",
  summary: "원본의 solid·dotted·dashed border, 개별 면 색, border shorthand, 둥근 이미지, 단일 box-shadow, margin shorthand와 인접 블록의 margin collapse를 출발점으로 삼습니다. 이후 border-box 계산, writing mode에 대응하는 logical side, 타원형 radius와 overflow clipping, outline과 focus indicator, 다층·inset shadow의 paint 비용과 대비, auto/negative margin의 used geometry, 양수·음수 margin collapse 계산, 부모·자식·빈 block 조건, BFC와 display:flow-root, flex/grid gap 선택까지 확장합니다. 마지막에는 getComputedStyle과 getBoundingClientRect로 선언값이 아니라 실제 border box·간격을 검증하는 재현 가능한 진단 절차를 완성합니다.",
  objectives: [
    "border shorthand가 width·style·color longhand를 어떻게 설정하며 box-sizing에 따라 바깥 크기가 어떻게 달라지는지 계산할 수 있다.",
    "left/right 대신 inline/block logical side를 선택하고 direction·writing-mode 변화에도 같은 의미의 경계를 유지할 수 있다.",
    "border-radius의 수평·수직 반지름, 반지름 축소 규칙과 descendant clipping 조건을 설명하고 이미지·카드에 올바르게 적용할 수 있다.",
    "border·outline·box-shadow를 레이아웃·포커스·장식 목적에 맞게 구분하고 forced-colors와 대비를 검증할 수 있다.",
    "margin:auto와 음수 margin의 사용값을 예측하고, 흐름을 겹치게 만드는 음수 값의 위험을 진단할 수 있다.",
    "인접 형제·부모와 첫/마지막 자식·빈 block의 세로 margin collapse 조건과 양수·음수 결합 결과를 계산할 수 있다.",
    "flow-root·border·padding·flex/grid·gap 중 어떤 수단이 collapse를 막는지와 각 수단의 부작용을 비교할 수 있다.",
  ],
  prerequisites: [
    { title: "display와 box model", reason: "content·padding·border·margin edge와 normal flow, block/inline/flex의 차이를 알아야 이번 세션의 크기·간격 계산을 실제 layout 결과와 연결할 수 있습니다.", sessionSlug: "css-05-display-box-model" },
  ],
  keywords: ["border", "logical properties", "border-radius", "overflow clipping", "outline", "focus indicator", "box-shadow", "margin auto", "negative margin", "margin collapsing", "block formatting context", "flow-root", "gap", "getBoundingClientRect"],
  chapters: [
    {
      id: "border-edge-and-shorthand",
      title: "border는 content 밖의 네 면을 차지하는 실제 box 영역입니다",
      lead: "테두리는 단순한 선이 아니라 padding edge와 margin edge 사이에 폭을 가진 영역이며, box-sizing과 함께 최종 크기를 결정합니다.",
      explanations: [
        "원본 ex10은 모든 div에 border-width:5px를 주고 solid·dotted·dashed style을 바꿉니다. 중요한 첫 규칙은 style의 초기값이 none이라는 점입니다. width와 color만 지정해도 style이 none이면 보이는 선이 없고, used border width도 layout에서는 0으로 취급됩니다. 선이 안 보일 때 색보다 border-style을 먼저 확인합니다.",
        "border shorthand는 순서가 엄격한 세 자리 문법이 아니라 width·style·color를 각 문법으로 구분하므로 border:1px solid orange처럼 흔히 씁니다. 생략한 구성 요소는 해당 longhand의 초기값으로 재설정됩니다. 예를 들어 기존 border-left-color:red 뒤에 border:2px solid를 선언하면 색은 currentcolor로 돌아갑니다. shorthand를 추가하는 순간 이전 개별 면 설정이 지워질 수 있다는 뜻입니다.",
        "기본 content-box에서 width:200px, 양쪽 padding 20px, 양쪽 border 5px라면 바깥 border box 너비는 200+40+10=250px입니다. border-box에서는 선언한 200px 안에서 padding과 border를 떼고 content width가 150px이 됩니다. component 크기를 예측하기 쉽게 하려면 전역 또는 component boundary에서 box-sizing:border-box를 일관되게 사용합니다.",
        "border-top-width처럼 physical longhand는 각 면을 직접 제어합니다. 네 값 shorthand는 top→right→bottom→left 순서이며, 세 값은 top→좌우→bottom, 두 값은 상하→좌우, 한 값은 전부입니다. 원본의 margin shorthand와 같은 시계 방향 축약 규칙이지만 logical property와 혼합하면 cascade 순서를 더 주의해야 합니다.",
        "transparent border도 공간은 차지합니다. hover 때 0에서 2px border로 바꾸면 주변 layout이 흔들리지만 처음부터 2px transparent를 예약하고 color만 바꾸면 크기는 유지됩니다. 반면 장식 ring을 box-shadow나 outline으로 그리면 대개 layout 공간을 추가하지 않습니다.",
      ],
      concepts: [
        { term: "border area", definition: "padding edge와 border edge 사이의 네 띠 영역입니다.", detail: ["width·style·color가 각 면의 paint를 결정합니다.", "border width는 box model 크기 계산에 참여합니다."] },
        { term: "border shorthand", definition: "border-width·border-style·border-color를 한 선언으로 모든 면에 설정하는 shorthand입니다.", detail: ["생략한 longhand는 이전 값을 보존하지 않고 초기값으로 재설정됩니다.", "개별 면 shorthand와 선언 순서가 cascade 결과를 바꿉니다."], caveat: "border-image 관련 longhand도 shorthand 재설정 영향을 받을 수 있으므로 긴 component rule에서 무심코 덮지 않습니다." },
        { term: "box-sizing", definition: "width·height가 content box를 뜻할지 border box를 뜻할지 정합니다.", detail: ["content-box가 초기값입니다.", "border-box는 padding과 border를 선언 크기 안에 포함합니다."] },
      ],
      codeExamples: [
        {
          id: "border-logical-radius-inspection",
          title: "border box·logical side·타원 radius·outline을 CSSOM과 geometry로 확인",
          language: "html",
          filename: "border-inspection.html",
          purpose: "원본의 border와 radius 예제를 하나의 고정 크기 card로 합치고 선언이 실제 어느 면·크기로 계산되는지 정확한 출력으로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>테두리 측정</title>\n  <style>\n    * { box-sizing: border-box; }\n    .card {\n      direction: ltr;\n      inline-size: 240px;\n      block-size: 120px;\n      border: 2px solid #334155;\n      border-inline-start: 6px dashed #c2410c;\n      border-radius: 24px 8px / 16px 8px;\n      overflow: hidden;\n      outline: 3px solid #0f766e;\n      outline-offset: 4px;\n      box-shadow: 0 2px 4px rgb(15 23 42 / .2), 0 0 0 4px rgb(14 116 144 / .25);\n      padding: 1rem;\n    }\n  </style>\n</head>\n<body>\n  <article id=\"card\" class=\"card\">경계가 측정되는 카드</article>\n  <pre id=\"result\"></pre>\n  <script>\n    const card = document.querySelector('#card');\n    const style = getComputedStyle(card);\n    const rect = card.getBoundingClientRect();\n    document.querySelector('#result').textContent = [\n      `border-box=${Math.round(rect.width)}x${Math.round(rect.height)}`,\n      `top=${style.borderTopWidth} ${style.borderTopStyle}`,\n      `inline-start=${style.borderInlineStartWidth} ${style.borderInlineStartStyle}`,\n      `radius-top-left=${style.borderTopLeftRadius}`,\n      `outline=${style.outlineWidth} offset=${style.outlineOffset}`,\n      `shadow=${style.boxShadow === 'none' ? 'none' : 'painted'}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-9", explanation: "border-box를 전제로 inline-size 240px와 block-size 120px를 선언하므로 padding과 border를 포함한 실제 border box가 정확히 240×120 CSS px가 됩니다." },
            { lines: "10-11", explanation: "모든 면에 2px solid를 먼저 설정한 뒤 inline-start 면만 6px dashed로 override합니다. LTR에서는 왼쪽이지만 의미는 글 진행 시작 면입니다." },
            { lines: "12-13", explanation: "slash 앞은 수평, 뒤는 수직 radius입니다. overflow:hidden은 둥근 padding edge 밖으로 descendant content가 삐져나오는 것을 clip합니다." },
            { lines: "14-16", explanation: "outline과 두 shadow는 border box 밖에 그려지지만 정상 흐름의 box 크기를 키우지 않습니다." },
            { lines: "26-35", explanation: "getComputedStyle은 cascade 뒤 계산값을, getBoundingClientRect는 viewport 기준 실제 border box geometry를 읽습니다. 둘을 함께 봐야 선언과 결과를 혼동하지 않습니다." },
          ],
          run: { environment: ["logical border property와 CSSOM을 지원하는 현대 browser", "browser zoom 100% 권장"], command: "border-inspection.html을 저장해 browser에서 열고 결과 영역 확인" },
          output: { value: "border-box=240x120\ntop=2px solid\ninline-start=6px dashed\nradius-top-left=24px 16px\noutline=3px offset=4px\nshadow=painted", explanation: ["border-box sizing이므로 실제 사각형은 선언한 240×120입니다.", "LTR의 top은 기본 2px solid이고 inline-start는 override된 6px dashed입니다.", "첫 모서리는 수평 24px·수직 16px 타원으로 serialize됩니다.", "outline과 shadow가 그려져도 rect 크기는 늘지 않습니다."] },
          experiments: [
            { change: "box-sizing:border-box를 content-box로 바꿉니다.", prediction: "border box는 inline 축에서 240+32px padding+8px border=280px가 됩니다.", result: "width가 어느 box를 가리키는지에 따라 같은 선언의 바깥 크기가 달라집니다." },
            { change: "direction을 rtl로 바꿉니다.", prediction: "6px dashed inline-start가 오른쪽으로 이동하고 borderInlineStart 출력은 유지됩니다.", result: "logical side는 방향에 따라 physical 면으로 mapping됩니다." },
            { change: "overflow:hidden을 제거하고 긴 child 이미지를 넣습니다.", prediction: "card 자신의 background와 border는 둥글지만 child content는 둥근 corner 밖으로 보일 수 있습니다.", result: "border-radius와 descendant clipping은 같은 기능이 아닙니다." },
          ],
          sourceRefs: ["web-border-source", "web-radius-source", "css-backgrounds-borders", "css-logical"],
        },
      ],
      diagnostics: [
        { symptom: "border-width와 border-color를 주었는데 선이 보이지 않는다.", likelyCause: "border-style이 초기값 none이거나 shorthand가 style을 none으로 재설정했습니다.", checks: ["DevTools Computed에서 각 면 border-style을 확인합니다.", "해당 rule이 취소선인지와 shorthand 선언 순서를 봅니다.", "forced-colors에서 color가 조정되었는지도 별도로 확인합니다."], fix: "필요한 면에 non-none style을 함께 선언하고 component API에서는 완전한 border shorthand 또는 명시적인 longhand 묶음을 사용합니다.", prevention: "visual regression뿐 아니라 computed border width/style assertion을 둡니다." },
        { symptom: "hover·validation 때 card와 주변 text가 2px씩 흔들린다.", likelyCause: "상태 변화 때 border-width가 0에서 2px로 바뀌어 border box 크기나 content 영역이 변했습니다.", checks: ["상태 전후 getBoundingClientRect를 비교합니다.", "box-sizing과 고정 width를 확인합니다.", "layout shift 기록에서 영향 node를 봅니다."], fix: "기본 상태에 같은 폭의 transparent border를 예약하고 color만 변경하거나, 목적에 맞으면 outline/box-shadow ring을 사용합니다.", prevention: "interaction state별 geometry snapshot을 테스트합니다." },
      ],
    },
    {
      id: "logical-sides-and-writing-modes",
      title: "left·right보다 inline-start·block-end가 콘텐츠 방향의 의미를 보존합니다",
      lead: "논리 방향은 번역이나 세로쓰기에서 물리 면이 바뀌어도 ‘읽기 시작 쪽 경계’라는 설계 의도를 유지합니다.",
      explanations: [
        "physical property의 top/right/bottom/left는 viewport 축의 면을 가리킵니다. logical property의 inline-start/end와 block-start/end는 writing-mode와 direction이 정한 글 흐름 축을 가리킵니다. 가로 LTR에서는 inline-start=left, RTL에서는 right이며, vertical writing mode에서는 inline 축 자체가 세로가 됩니다.",
        "border-inline, border-inline-start, border-block-end처럼 width·style·color를 논리 면별로 묶을 수 있습니다. margin-inline과 padding-block도 같은 사고 모델을 공유합니다. card의 강조선이 ‘왼쪽 장식’ 자체라면 physical left가 맞고, ‘읽기 시작 쪽 인용선’이면 logical inline-start가 맞습니다.",
        "physical과 logical longhand가 같은 최종 면을 설정하면 둘 다 같은 cascade에 참여합니다. 어느 쪽이 본질적으로 우선하는 것이 아니라 origin·importance·layer·specificity·source order 결과로 이깁니다. border-left와 border-inline-start를 여러 파일에서 섞으면 LTR에서는 우연히 맞고 RTL에서 역전되는 maintenance bug가 생깁니다.",
        "corner도 border-start-start-radius 같은 logical longhand가 있습니다. 첫 start는 block 축, 둘째 start는 inline 축의 corner를 뜻합니다. 팀이 지원할 browser 범위를 확인한 뒤, component가 다국어 방향을 지원한다면 physical corner 네 개보다 의미 있는 logical corner를 검토합니다.",
        "logical property를 썼다는 이유만으로 화면이 자동 번역되지는 않습니다. HTML dir, 실제 언어, writing-mode와 icon 방향성까지 함께 검토해야 합니다. 화살표·timeline처럼 물리 방향 자체가 의미인 요소는 무조건 뒤집지 않습니다.",
      ],
      concepts: [
        { term: "inline axis", definition: "한 줄 안에서 글자가 진행하는 축입니다.", detail: ["start/end는 direction과 writing-mode에 따라 physical 면에 mapping됩니다.", "margin-inline·border-inline·inset-inline이 이 축을 공유합니다."] },
        { term: "block axis", definition: "line box가 다음 줄로 쌓이는 축입니다.", detail: ["가로쓰기에서는 대체로 위에서 아래입니다.", "세로쓰기에서는 물리 가로축이 될 수 있습니다."] },
        { term: "logical corner", definition: "block/inline의 start·end 조합으로 이름 붙인 모서리입니다.", detail: ["border-start-start-radius처럼 씁니다.", "문자 방향에 따라 physical corner가 달라집니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "RTL에서 강조선이 text 시작 면이 아니라 반대쪽에 남는다.", likelyCause: "border-left 같은 physical property로 의미적 시작 면을 고정했습니다.", checks: ["root 또는 component의 dir 값을 바꿉니다.", "Computed의 border-inline-start와 physical border 면을 함께 봅니다.", "physical/logical 선언이 뒤에서 서로 override하는지 확인합니다."], fix: "의도가 읽기 시작 면이면 border-inline-start로 통일하고 physical override를 제거합니다.", prevention: "LTR·RTL fixture와 vertical writing smoke test를 component review에 포함합니다." },
      ],
      comparisons: [
        { title: "physical side와 logical side 선택", options: [
          { name: "top/right/bottom/left", chooseWhen: "지도 나침반·물리 위치처럼 화면 면 자체가 의미일 때", avoidWhen: "문자 진행의 시작·끝에 맞춰야 하는 간격과 경계", tradeoffs: ["직관적이지만 방향 전환에 수동 override가 필요합니다.", "legacy code와 호환이 쉽습니다."] },
          { name: "block/inline start/end", chooseWhen: "읽기 흐름·번역·RTL·세로쓰기에도 component 의미를 유지할 때", avoidWhen: "물리 방향이 업무 의미이고 뒤집히면 잘못될 때", tradeoffs: ["국제화에 견고합니다.", "팀이 writing-mode mental model과 지원 범위를 이해해야 합니다."] },
        ] },
      ],
    },
    {
      id: "radius-shape-and-clipping",
      title: "border-radius는 모서리 곡선을 만들지만 descendant를 자동으로 잘라내지는 않습니다",
      lead: "원형 avatar와 둥근 card가 비슷해 보여도 비율·타원 반지름·overflow clipping·focus ring 경계는 따로 설계해야 합니다.",
      explanations: [
        "원본 ex11은 350×350으로 강제한 같은 이미지에 35px, 50%, 위쪽 두 corner만 25px radius를 비교합니다. 정사각 border box의 50%는 원처럼 보이지만 가로·세로가 다르면 타원이 됩니다. 원형 avatar가 목적이면 aspect-ratio:1과 object-fit:cover를 함께 사용해 이미지 왜곡 없이 정사각 box를 먼저 보장합니다.",
        "border-radius:24px 8px / 16px 8px에서 slash 앞 목록은 corner의 수평 반지름, 뒤는 수직 반지름입니다. 네 값은 top-left→top-right→bottom-right→bottom-left 순서로 배치됩니다. 단일 radius는 원호, 두 축 값은 타원호를 만듭니다.",
        "모든 corner 반지름 합이 box의 너비나 높이를 넘으면 browser는 곡선이 겹치지 않도록 비례 축소합니다. 따라서 매우 작은 card에 9999px을 주어 pill을 만드는 패턴은 유효하지만 computed 선언값만 보고 실제 사용 곡선을 단순 계산하면 틀릴 수 있습니다. screenshot과 실제 크기 변형을 테스트합니다.",
        "element 자신의 background는 radius에 맞춰 그려지고 border curve도 함께 만들어집니다. 그러나 child image나 child background가 부모 corner 밖으로 넘는 것을 막으려면 overflow:hidden/clip 같은 clipping이 필요합니다. overflow:hidden은 scroll container 동작·sticky·shadow clipping 등 다른 영향을 만들 수 있으므로 단지 ‘둥글게 보이게’ 하려고 무조건 부모에 넣지 않습니다. 이미지 자체에 radius를 주는 대안도 있습니다.",
        "둥근 box의 focus indicator가 잘려서는 안 됩니다. ancestor가 overflow:hidden이면 child button의 바깥 outline이 clip될 수 있습니다. outline-offset을 음수로 안쪽에 넣는 응급 처방보다 focusable element 주변에 안전한 공간을 두거나 clipping boundary를 재설계합니다.",
      ],
      concepts: [
        { term: "elliptical radius", definition: "한 corner에 서로 다른 수평·수직 반지름을 적용한 타원 원호입니다.", detail: ["slash 문법으로 두 축 목록을 분리합니다.", "각 corner pair가 box 크기에 맞춰 축소될 수 있습니다."] },
        { term: "corner clipping", definition: "background·border·content가 둥근 곡선 주변에서 잘리는 규칙입니다.", detail: ["background painting과 descendant overflow clipping은 구분합니다.", "ancestor clipping은 child focus indicator와 shadow에도 영향을 줍니다."] },
        { term: "pill", definition: "높이의 절반 이상 radius를 사용해 양 끝이 반원처럼 보이는 capsule 형태입니다.", detail: ["content 길이가 변해도 큰 radius 값으로 유지할 수 있습니다.", "원형 avatar와 달리 inline size는 가변입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "둥근 card 모서리 밖으로 child 이미지의 직각 모서리가 보인다.", likelyCause: "부모 border-radius만 설정하고 child content overflow는 clip하지 않았습니다.", checks: ["부모와 child 각각의 border radius와 overflow computed value를 봅니다.", "이미지 자체가 card 전체를 덮는지 확인합니다.", "overflow 변경이 sticky·shadow·scroll에 미칠 영향을 확인합니다."], fix: "단순 media라면 이미지 자체에 대응 radius를 주고, compound card 전체 clipping이 필요하면 의도적으로 overflow:hidden/clip을 사용합니다.", prevention: "다양한 image ratio와 keyboard focus를 포함한 corner visual test를 둡니다." },
        { symptom: "50% avatar가 원이 아니라 타원이고 얼굴이 찌그러진다.", likelyCause: "border box가 정사각형이 아니거나 width와 height로 intrinsic image 비율을 강제했습니다.", checks: ["getBoundingClientRect로 실제 width/height를 비교합니다.", "object-fit과 aspect-ratio를 확인합니다.", "원본 image intrinsic ratio를 봅니다."], fix: "avatar wrapper에 aspect-ratio:1을 주고 img에 inline-size/block-size:100%, object-fit:cover, border-radius:50%를 적용합니다.", prevention: "가로·세로·작은 source image fixture를 모두 테스트합니다." },
      ],
    },
    {
      id: "outline-border-and-focus",
      title: "outline은 포커스 경계이고 border는 box 경계입니다",
      lead: "둘 다 선처럼 보이지만 outline은 정상 흐름 공간을 차지하지 않고, 접근성 포커스 표시에는 사용자 환경에서 살아남는 별도 계약이 필요합니다.",
      explanations: [
        "border는 box model 일부라 크기 계산과 background 경계를 형성합니다. outline은 box 바깥에 그려지며 공간을 예약하지 않아 인접 콘텐츠와 겹칠 수 있고 일반적으로 radius를 border처럼 보장하는 장식 수단도 아닙니다. 경계가 layout을 밀어야 한다면 border, keyboard focus처럼 layout을 바꾸지 않아야 한다면 outline이 기본 선택입니다.",
        "outline:none을 전역으로 선언하고 box-shadow만 남기면 forced-colors/high-contrast 환경에서 shadow가 사라져 focus가 보이지 않을 수 있습니다. :focus-visible에 명확한 outline을 제공하고, 브랜드 ring을 shadow로 더하더라도 outline fallback을 유지합니다. mouse click에 항상 ring이 필요한지는 component와 browser heuristic을 존중합니다.",
        "outline-offset 양수는 border edge 밖으로 선을 밀고 음수는 안으로 당깁니다. 너무 큰 양수는 clipping ancestor에 잘리고, 음수는 content나 border 대비와 겹칩니다. indicator는 주변 색과 충분히 구분되고 focus 전후 차이가 명확해야 하며, 작은 control에서도 식별 가능한 두께와 면적을 확보해야 합니다.",
        "outline은 여러 line box를 가진 inline element에서 모양이 복잡할 수 있고 다른 element 아래에 가려질 수도 있습니다. z-index만 무작정 높이기 전에 clipping·stacking context·scroll container를 찾아 focus 요소가 실제 viewport에 보이는지 확인합니다.",
        "error·selected·focus를 색 하나로만 구분하지 않습니다. border color와 icon/text, outline 또는 shape 변화처럼 중복 단서를 제공합니다. focus ring 색은 밝은 배경과 어두운 배경 모두에서 확인하고 시스템 color CanvasText/Highlight 같은 forced-color 대응도 검토합니다.",
      ],
      concepts: [
        { term: "outline", definition: "border edge 주위에 그려지지만 box model 공간을 차지하지 않는 선입니다.", detail: ["focus indicator의 기본 도구입니다.", "outline-offset으로 border와 거리를 조정합니다."] },
        { term: ":focus-visible", definition: "user agent가 focus indicator 표시가 필요하다고 판단한 focus에 match하는 pseudo-class입니다.", detail: ["keyboard navigation에서 보이는 ring을 설계합니다.", ":focus와 동일한 순간만을 뜻하지는 않습니다."] },
        { term: "forced colors", definition: "사용자 agent가 가독성을 위해 author 색을 제한된 system palette로 강제하는 표시 모드입니다.", detail: ["shadow·background image가 사라질 수 있습니다.", "native outline과 system colors를 실제 모드에서 검증합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "일반 화면에서는 focus ring이 있지만 Windows 고대비 모드에서는 사라진다.", likelyCause: "outline을 제거하고 box-shadow 또는 background color만으로 focus를 표현했습니다.", checks: ["keyboard Tab으로 실제 focus를 이동합니다.", "forced-colors emulation/실제 모드에서 outline computed value를 봅니다.", "ancestor overflow가 ring을 clip하는지 확인합니다."], fix: ":focus-visible에 solid outline과 offset을 복원하고 필요한 경우 @media (forced-colors:active)에서 system color를 명시합니다.", prevention: "keyboard·forced-colors·200% zoom focus state를 접근성 회귀 항목에 넣습니다." },
      ],
      comparisons: [
        { title: "경계 효과 선택", options: [
          { name: "border", chooseWhen: "component의 실제 box 경계·구분선·입력 상태를 표현할 때", avoidWhen: "상태 변화로 layout 크기를 흔들면 안 될 때", tradeoffs: ["box model과 radius에 통합됩니다.", "폭 변경은 layout에 영향을 줍니다."] },
          { name: "outline", chooseWhen: "keyboard focus처럼 layout을 바꾸지 않는 외곽 indicator가 필요할 때", avoidWhen: "공간을 예약하거나 정확한 rounded clipping이 필요할 때", tradeoffs: ["forced-colors에 비교적 견고합니다.", "겹침·clipping을 별도로 검토해야 합니다."] },
          { name: "box-shadow ring", chooseWhen: "다층 브랜드 ring·부드러운 장식을 보조로 추가할 때", avoidWhen: "유일한 focus/상태 단서로 사용할 때", tradeoffs: ["radius를 따르고 여러 층을 만들기 쉽습니다.", "고대비에서 사라질 수 있고 paint 비용이 있습니다."] },
        ] },
      ],
    },
    {
      id: "box-shadow-layers-performance-contrast",
      title: "box-shadow는 layout 밖에서 여러 paint layer를 쌓습니다",
      lead: "offset·blur·spread·inset의 geometry와 목록 순서를 이해하면 과장된 그림자 없이 깊이·ring·inner edge를 분리할 수 있습니다.",
      explanations: [
        "원본 ex09는 2px x/y offset, 2px blur, 2px spread, #222인 단일 shadow를 버튼에 적용합니다. 기본 문법은 [inset] x-offset y-offset blur-radius spread-radius color입니다. x가 양수면 오른쪽, y가 양수면 아래로 이동하며 blur는 음수가 될 수 없고 spread는 음수도 가능합니다.",
        "comma로 여러 shadow를 나열하면 첫 shadow가 사용자에게 가장 가까운 위 layer이고 뒤 항목들이 아래에 그려집니다. 얇은 0 0 0 1px ring, 낮은 0 1px 2px contact shadow, 넓은 0 12px 28px ambient shadow처럼 역할을 나누면 한 개의 검고 큰 blur보다 자연스럽고 조정하기 쉽습니다.",
        "inset은 바깥 투영이 아니라 box 안쪽에 움푹 들어간 edge를 그립니다. input 내부 highlight나 pressed state에 쓸 수 있지만 text 대비를 해치거나 affordance를 모호하게 만들지 않습니다. shadow는 layout 크기를 늘리지 않으며 scrollable overflow 영역도 키우거나 scrolling을 유발하지 않습니다. 다만 ancestor overflow에 clip되거나 이웃 위에 겹쳐 보이고 screenshot·paint 영역은 넓어질 수 있습니다.",
        "큰 blur radius와 넓은 spread는 paint해야 할 pixel 영역을 키웁니다. 많은 card가 scroll되거나 shadow를 매 frame animation하면 repaint와 GPU memory 비용이 커질 수 있습니다. opacity/transform animation이 흔히 compositing에 유리하지만 shadow layer를 무조건 승격시키는 will-change는 메모리를 낭비하므로 Performance/Rendering panel에서 실제 paint를 측정합니다.",
        "그림자는 의미나 대비를 단독으로 전달하지 않습니다. white card와 아주 밝은 background의 경계가 shadow만으로 구분되는지, shadow가 사라진 forced-colors에서도 border 또는 공간 구조가 남는지 확인합니다. elevation token은 숫자가 클수록 무조건 진하다는 규칙보다 overlay 관계·interaction state를 명확히 정의해야 합니다.",
      ],
      concepts: [
        { term: "blur radius", definition: "shadow edge를 흐리게 확산시키는 non-negative 길이입니다.", detail: ["커질수록 paint 영역이 넓어집니다.", "box 크기나 normal flow는 바꾸지 않습니다."] },
        { term: "spread radius", definition: "blur 전 shadow shape를 바깥 또는 안쪽으로 팽창·수축시키는 길이입니다.", detail: ["양수는 확장, 음수는 축소합니다.", "0 blur와 함께 ring처럼 사용할 수 있습니다."] },
        { term: "inset shadow", definition: "border 안쪽에 그려져 내부가 눌리거나 파인 것처럼 보이는 shadow입니다.", detail: ["outset shadow와 같은 목록에서 결합할 수 있습니다.", "content 가독성을 침범하지 않게 합니다."] },
      ],
      codeExamples: [
        {
          id: "multi-shadow-without-layout-change",
          title: "다층·inset shadow가 border box 크기를 바꾸지 않음을 확인",
          language: "html",
          filename: "shadow-layers.html",
          purpose: "단일 shadow 원본을 contact·ambient·inset 세 역할로 확장하고 visual effect와 layout geometry를 분리합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>그림자 층</title>\n  <style>\n    .sample { box-sizing: border-box; inline-size: 180px; block-size: 60px; border: 1px solid #64748b; }\n    .shadowed {\n      box-shadow:\n        0 1px 2px rgb(15 23 42 / .22),\n        0 10px 24px rgb(15 23 42 / .18),\n        inset 0 0 0 1px rgb(255 255 255 / .7);\n    }\n  </style>\n</head>\n<body>\n  <div id=\"plain\" class=\"sample\">기본</div>\n  <div id=\"shadowed\" class=\"sample shadowed\">그림자</div>\n  <pre id=\"result\"></pre>\n  <script>\n    const plain = document.querySelector('#plain').getBoundingClientRect();\n    const shadowed = document.querySelector('#shadowed');\n    const shadowRect = shadowed.getBoundingClientRect();\n    const value = getComputedStyle(shadowed).boxShadow;\n    document.querySelector('#result').textContent = [\n      `shadow-property=${value === 'none' ? 'none' : 'set'}`,\n      `contains-inset=${value.includes('inset')}`,\n      `plain-border-box=${Math.round(plain.width)}x${Math.round(plain.height)}`,\n      `same-border-box=${plain.width === shadowRect.width && plain.height === shadowRect.height}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6", explanation: "두 sample 모두 동일한 180×60 border box를 갖도록 고정해 shadow만 독립 변수로 만듭니다." },
            { lines: "8-11", explanation: "첫 층은 접촉 edge, 둘째는 넓은 ambient depth, 셋째 inset은 내부 highlight입니다. 앞 항목이 위에 paint됩니다." },
            { lines: "20-29", explanation: "computed shadow의 존재와 inset을 확인하고 두 getBoundingClientRect 크기를 비교합니다. visual overflow를 rect가 포함한다고 가정하지 않습니다." },
          ],
          run: { environment: ["현대 browser", "JavaScript 활성화"], command: "shadow-layers.html을 browser에서 열고 결과와 두 box의 visual overflow를 비교" },
          output: { value: "shadow-property=set\ncontains-inset=true\nplain-border-box=180x60\nsame-border-box=true", explanation: ["box-shadow 계산값은 none이 아니며 inset layer를 포함합니다.", "그림자는 바깥에 보이지만 getBoundingClientRect의 border box는 두 요소 모두 180×60입니다.", "visual overflow와 layout geometry를 별도 지표로 다뤄야 합니다."] },
          experiments: [
            { change: "ambient shadow를 0 30px 80px 30px로 키웁니다.", prediction: "border box 출력은 그대로지만 paint/visual overflow 영역은 크게 증가합니다.", result: "shadow는 layout을 밀지 않으면서 rendering 비용은 키울 수 있습니다." },
            { change: "shadow를 1px solid border로 교체하고 content-box를 사용합니다.", prediction: "선은 덜 흐리지만 선언 width 밖에 border가 더해질 수 있습니다.", result: "장식 선택은 geometry 계약과 함께 결정합니다." },
            { change: "forced-colors를 활성화합니다.", prediction: "author shadow가 사라지거나 조정될 수 있지만 border는 경계 단서로 남습니다.", result: "shadow를 유일한 구분·focus 단서로 사용하지 않습니다." },
          ],
          sourceRefs: ["web-shadow-source", "css-backgrounds-borders", "wcag-focus"],
        },
      ],
      diagnostics: [
        { symptom: "긴 card 목록을 scroll할 때 끊기고 paint flashing이 넓게 번쩍인다.", likelyCause: "각 item의 큰 blur/spread shadow가 넓은 영역을 반복해서 paint하거나 shadow 속성을 animation합니다.", checks: ["Performance에서 Paint event와 duration을 기록합니다.", "Rendering의 paint flashing으로 영향 영역을 봅니다.", "shadow를 잠시 none으로 바꾼 baseline과 비교합니다.", "will-change layer 수와 GPU memory 증가를 확인합니다."], fix: "blur/spread·layer 수·동시 animation을 줄이고 elevation token을 단순화하며, 움직임은 가능한 transform/opacity 중심으로 설계한 뒤 다시 측정합니다.", prevention: "대표 저사양 device와 긴 list fixture에 paint budget을 둡니다." },
        { symptom: "shadow가 card 경계에서 잘리거나, shadow가 큰데도 scroll로 끝까지 볼 수 없다.", likelyCause: "ancestor overflow가 ink overflow를 clip했거나 box-shadow 자체가 명세상 scrollable overflow 영역을 키우지 않기 때문입니다.", checks: ["ancestor 체인의 overflow 값을 확인합니다.", "clip이 필요한 축과 실제 scroll container를 찾습니다.", "shadow를 제거해 clip 차이를 비교합니다.", "scrollbar가 새로 생겼다면 shadow가 아닌 content·margin·transform 등 다른 overflow 원인을 측정합니다."], fix: "clipping boundary와 shadow owner를 분리하거나 충분한 padding을 둔 wrapper 안에 실제 layout 공간을 예약합니다. shadow만으로 scrollable 여유 공간이 생길 것이라 기대하지 않습니다.", prevention: "모달·carousel·scroll container 안에서 elevation clipping과 scroll extent를 별도 회귀 테스트합니다." },
      ],
    },
    {
      id: "margin-auto-negative-and-logical",
      title: "margin은 배경 없는 바깥 간격이며 auto와 음수 값은 서로 다른 layout 도구입니다",
      lead: "auto는 남는 공간 배분 규칙에 참여하고, 음수 margin은 이웃과 box를 끌어당겨 겹침까지 만들 수 있습니다.",
      explanations: [
        "원본 ex12는 1·2·4개 margin shorthand를 비교합니다. 네 값은 top→right→bottom→left, 두 값은 block 방향 상하와 inline 방향 좌우입니다. 현대 component에서는 margin-block과 margin-inline을 사용하면 writing mode가 바뀌어도 의미가 유지됩니다.",
        "block element를 margin-inline:auto로 가운데 두려면 inline size가 containing block보다 작아 남는 공간이 있어야 합니다. 원본 .box7은 width:100%라 auto가 나눌 여유가 사실상 없으므로 중앙 정렬 효과를 관찰하기 어렵습니다. 400px container 안 160px child라면 남은 240px을 양쪽 auto가 120px씩 나눕니다.",
        "auto의 의미는 layout mode마다 다릅니다. normal-flow block의 inline auto margin은 남는 inline 공간을 나누지만 block-axis auto margin은 보통 0처럼 계산됩니다. flex item의 auto margin은 해당 축의 free space를 흡수해 item을 끝으로 밀거나 중앙에 둘 수 있습니다. 같은 단어를 mode와 축 없이 암기하면 안 됩니다.",
        "음수 margin은 허용되며 box를 이웃 쪽으로 당기거나 available size 계산을 바꿉니다. margin-inline-start:-1rem으로 장식 이미지를 bleed시키는 패턴은 가능하지만 source order·focus ring·pointer target·horizontal overflow를 확인해야 합니다. 단지 pixel을 맞추기 위한 연쇄 음수 값은 responsive content에서 쉽게 깨집니다.",
        "percentage margin은 일반적인 horizontal writing에서 block 방향 margin도 containing block의 inline size를 기준으로 계산되는 legacy 규칙이 있어 직관과 다를 수 있습니다. 일정한 세로 rhythm에는 rem, container-relative spacing에는 설계된 logical length 또는 layout gap을 우선하고 percentage를 쓰면 resize fixture로 검증합니다.",
      ],
      concepts: [
        { term: "auto margin", definition: "layout algorithm이 남는 공간을 배분해 사용값을 정하는 margin 값입니다.", detail: ["고정 폭 block의 inline 중앙 정렬에 흔히 사용합니다.", "flex에서는 free space absorber로 동작합니다."] },
        { term: "negative margin", definition: "0보다 작은 바깥 간격으로 box 사이 거리를 줄이거나 overlap을 만드는 값입니다.", detail: ["normal flow 참여 자체를 제거하지 않습니다.", "overflow·focus·hit target 겹침을 검사해야 합니다."] },
        { term: "margin shorthand", definition: "1~4개 값으로 네 physical 면 margin을 설정하는 shorthand입니다.", detail: ["1=모두, 2=상하/좌우, 3=상/좌우/하, 4=상/우/하/좌입니다.", "logical 축 의도에는 margin-block/inline이 더 명시적입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "margin:0 auto를 주었지만 element가 가운데로 이동하지 않는다.", likelyCause: "element가 가용 inline width를 이미 전부 차지하거나 inline element이거나, flex/grid의 다른 alignment 규칙이 작동합니다.", checks: ["element/containing block의 getBoundingClientRect width를 비교합니다.", "display와 width/max-width를 확인합니다.", "flex/grid container의 justify/align과 auto margin 축을 봅니다."], fix: "normal block이면 width 또는 max-inline-size를 제한한 뒤 margin-inline:auto를 쓰고, flex/grid이면 해당 layout의 alignment 또는 auto margin 의도를 명확히 선택합니다.", prevention: "narrow/wide viewport에서 좌우 offset을 geometry assertion으로 검증합니다." },
        { symptom: "음수 margin으로 올린 badge가 link 클릭을 막거나 focus ring과 겹친다.", likelyCause: "시각적 overlap이 stacking·pointer hit testing·focus outline 공간까지 침범했습니다.", checks: ["Elements overlay와 pointer target을 확인합니다.", "Tab focus 순서와 ring을 관찰합니다.", "z-index/positioned stacking context를 확인합니다.", "200% zoom과 긴 번역 text로 재현합니다."], fix: "장식은 pseudo-element/positioned layer로 의미와 hit target을 분리하고, 필요한 overlap 공간을 component contract에 예약합니다.", prevention: "overlap component에 keyboard·pointer·zoom·RTL test matrix를 둡니다." },
      ],
    },
    {
      id: "vertical-margin-collapse-algorithm",
      title: "세로 margin collapse는 더하기가 아니라 adjoining margin 집합의 결합입니다",
      lead: "두 block 사이 30px+50px가 80px이 아닌 50px이 되는 이유와 음수 값까지 하나의 계산 규칙으로 설명합니다.",
      explanations: [
        "원본 ex13의 normal-flow block 세 개는 각각 margin:30px입니다. 첫 box의 bottom 30px과 다음 box의 top 30px이 adjoining vertical margin이므로 둘 사이 gap은 60px가 아니라 30px입니다. 상쇄라는 번역 때문에 하나가 사라진다고 외우기보다 여러 margin이 하나의 collapsed margin을 형성한다고 이해합니다.",
        "양수 margin만 있으면 collapsed 결과는 가장 큰 양수입니다. 30px과 50px이면 50px입니다. 양수와 음수가 섞이면 가장 큰 양수와 가장 작은, 즉 절댓값이 큰 음수를 더합니다. 30px과 -10px은 20px입니다. 전부 음수라면 가장 작은 값 하나가 결과가 되어 -20px과 -35px은 -35px이고 두 box가 35px 겹칠 수 있습니다.",
        "collapse는 block formatting context 안의 in-flow block-level box가 block 축으로 adjoining할 때 생깁니다. inline-axis 좌우 margin은 collapse하지 않습니다. flex item·grid item의 margin도 서로 collapse하지 않고, absolute positioned box와 floating box의 margin도 collapse하지 않습니다.",
        "인접 형제만이 아닙니다. 부모에 block-start border·padding·inline content·clearance가 없으면 부모의 block-start margin과 첫 in-flow child의 block-start margin이 collapse할 수 있습니다. block-end에서도 부모의 min-height/height·padding/border와 마지막 child 조건에 따라 collapse합니다. 결과 margin이 부모 바깥에서 보이므로 ‘child padding이 사라졌다’고 오해하기 쉽습니다.",
        "빈 block은 border·padding·height/min-height·inline content·clearance가 없을 때 자신의 block-start와 block-end margin이 collapse할 수 있고, 그 집합이 앞뒤 sibling margin과 연쇄적으로 결합할 수 있습니다. DOM 한 칸만 보고 계산하지 말고 adjoining chain 전체를 찾습니다.",
        "overflow가 visible이 아닌 새 BFC root, display:flow-root, flex/grid container 등은 부모와 child margin collapse 경계를 바꿉니다. 하지만 BFC 안의 일반 block sibling끼리의 margin까지 모두 자동으로 분리하는 것은 아닙니다. ‘BFC면 모든 collapse 없음’이라는 과도한 규칙을 피합니다.",
      ],
      concepts: [
        { term: "adjoining margins", definition: "border·padding·content·clearance 같은 분리 요소 없이 block 축에서 맞닿아 collapse 후보가 되는 margin 집합입니다.", detail: ["형제뿐 아니라 parent/child와 빈 block을 연결할 수 있습니다.", "같은 BFC 안의 조건을 따집니다."] },
        { term: "collapsed margin", definition: "adjoining vertical margins가 하나의 사용 간격으로 결합된 결과입니다.", detail: ["양수는 최댓값, 음수는 최솟값을 사용합니다.", "혼합은 최대 양수와 최소 음수의 합입니다."] },
        { term: "margin chain", definition: "빈 block이나 parent/child를 통해 셋 이상의 margin이 adjoining하는 연결 집합입니다.", detail: ["DOM 인접 두 개만 계산하면 틀릴 수 있습니다.", "border/padding/height/BFC 경계를 표시해 끊기는 지점을 찾습니다."] },
      ],
      codeExamples: [
        {
          id: "margin-geometry-matrix",
          title: "auto·양수/음수 collapse·부모 collapse·flow-root·gap을 실제 좌표로 측정",
          language: "html",
          filename: "margin-geometry.html",
          purpose: "원본 margin 두 예제를 fixed geometry fixture로 재구성해 숫자 예측과 browser layout 결과를 한 줄씩 대조합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>마진 geometry</title>\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; }\n    .frame, .case { inline-size: 400px; display: flow-root; }\n    .center { inline-size: 160px; block-size: 20px; margin-inline: auto; }\n    .box { block-size: 20px; margin: 0; }\n    .positive .first { margin-block-end: 30px; }\n    .positive .second { margin-block-start: 50px; }\n    .mixed .first { margin-block-end: 30px; }\n    .mixed .second { margin-block-start: -10px; }\n    .negative .first { margin-block-end: -20px; }\n    .negative .second { margin-block-start: -35px; }\n    .shell { inline-size: 400px; display: flow-root; }\n    .parent, .child { margin: 0; }\n    .child { block-size: 20px; margin-block-start: 24px; }\n    .isolated { display: flow-root; }\n    .flex { display: flex; flex-direction: column; gap: 16px; }\n  </style>\n</head>\n<body>\n  <section id=\"frame\" class=\"frame\"><div id=\"center\" class=\"center\"></div></section>\n  <section class=\"case positive\"><div class=\"box first\"></div><div class=\"box second\"></div></section>\n  <section class=\"case mixed\"><div class=\"box first\"></div><div class=\"box second\"></div></section>\n  <section class=\"case negative\"><div class=\"box first\"></div><div class=\"box second\"></div></section>\n  <section class=\"shell\"><div id=\"normal\" class=\"parent\"><div id=\"normal-child\" class=\"child\"></div></div></section>\n  <section class=\"shell\"><div id=\"isolated\" class=\"parent isolated\"><div id=\"isolated-child\" class=\"child\"></div></div></section>\n  <section class=\"case flex\"><div class=\"box first\"></div><div class=\"box second\"></div></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const rect = (selector) => document.querySelector(selector).getBoundingClientRect();\n    const gap = (selector) => {\n      const first = rect(`${selector} .first`);\n      const second = rect(`${selector} .second`);\n      return Math.round(second.top - first.bottom);\n    };\n    const offset = (parent, child) => Math.round(rect(child).top - rect(parent).top);\n    document.querySelector('#result').textContent = [\n      `center-offset=${Math.round(rect('#center').left - rect('#frame').left)}`,\n      `positive-positive-gap=${gap('.positive')}`,\n      `positive-negative-gap=${gap('.mixed')}`,\n      `negative-negative-gap=${gap('.negative')}`,\n      `normal-child-offset=${offset('#normal', '#normal-child')}`,\n      `flow-root-child-offset=${offset('#isolated', '#isolated-child')}`,\n      `flex-gap=${gap('.flex')}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-9", explanation: "400px frame과 160px child의 남는 inline 공간 240px을 두 auto margin이 120px씩 나눕니다." },
            { lines: "11-16", explanation: "양수/양수, 양수/음수, 음수/음수 adjoining margin 집합을 서로 다른 case에서 격리해 collapse 계산을 비교합니다." },
            { lines: "17-21", explanation: "normal parent에서는 첫 child margin이 parent 밖으로 collapse하고, flow-root parent에서는 경계 안 24px offset으로 남습니다." },
            { lines: "22", explanation: "flex column의 item margin collapse 대신 explicit gap 16px을 사용합니다." },
            { lines: "35-51", explanation: "getBoundingClientRect의 top/bottom/left 차이만으로 visual 추측이 아닌 실제 border-box 간격을 계산합니다." },
          ],
          run: { environment: ["display:flow-root와 logical margin을 지원하는 현대 browser", "browser zoom 100% 권장"], command: "margin-geometry.html을 browser에서 열고 출력된 일곱 geometry 값을 확인" },
          output: { value: "center-offset=120\npositive-positive-gap=50\npositive-negative-gap=20\nnegative-negative-gap=-35\nnormal-child-offset=0\nflow-root-child-offset=24\nflex-gap=16", explanation: ["auto margin은 남은 240px을 반으로 나눠 120px offset을 만듭니다.", "양수끼리는 50px, 30과 -10은 20px, 음수끼리는 -35px이 collapsed 결과입니다.", "normal parent/첫 child는 margin이 밖으로 collapse해 내부 offset 0이고 flow-root는 collapse를 막아 24px을 유지합니다.", "flex item 사이에는 margin collapse가 없고 선언한 gap 16px이 그대로 측정됩니다."] },
          experiments: [
            { change: ".positive parent에 padding-block-start:1px을 주는 것이 아니라 두 sibling 사이에 1px border element를 삽입합니다.", prediction: "두 margin은 더 이상 adjoining하지 않아 gap에 양쪽 margin과 separator 크기가 더해집니다.", result: "collapse 여부는 DOM에서 실제로 무엇이 두 margin을 분리하는지에 달려 있습니다." },
            { change: "#normal에 border-block-start:1px solid transparent를 줍니다.", prediction: "parent/first-child collapse가 끊겨 child offset은 25px이 됩니다.", result: "transparent border도 실제 border 영역이어서 collapse 경계를 만듭니다." },
            { change: ".flex child에 30px/50px margin까지 다시 추가합니다.", prediction: "flex item margin은 collapse하지 않고 두 margin 80px과 gap 16px이 모두 들어가 96px이 됩니다.", result: "gap을 선택했다면 item 외부 margin을 중복 적용하지 않는 spacing policy가 필요합니다." },
          ],
          sourceRefs: ["web-margin-shorthand-source", "web-margin-collapse-source", "css-box-model", "css2-collapsing-margins", "css-display"],
        },
      ],
      diagnostics: [
        { symptom: "두 section에 각각 40px 여백을 주었는데 실제 사이는 80px이 아니라 40px이다.", likelyCause: "normal-flow block 형제의 adjoining block-axis margins가 collapse했습니다.", checks: ["두 element의 computed margin-block-end/start를 확인합니다.", "getBoundingClientRect로 second.top-first.bottom을 계산합니다.", "flex/grid item인지 float/absolute인지 확인합니다.", "사이에 border·padding·content·clearance가 있는지 봅니다."], fix: "문서 block rhythm으로 40px 하나가 의도라면 그대로 두고, 두 간격을 반드시 합쳐야 하면 parent gap 또는 padding/구조로 명시합니다.", prevention: "spacing token 이름에 ‘각 component 외부’와 ‘container item gap’ 소유권을 구분합니다." },
        { symptom: "첫 h2의 margin-top 때문에 card 안 여백이 아니라 card 전체가 아래로 내려간다.", likelyCause: "부모 block-start border/padding/content가 없어 첫 child margin이 부모와 collapse해 바깥에 나타났습니다.", checks: ["parent.top과 child.top 차이를 측정합니다.", "parent border/padding/flow-root를 toggle해 비교합니다.", "empty text node가 아니라 실제 inline formatting content가 있는지 확인합니다."], fix: "card 내부 여백은 parent padding-block-start가 소유하게 하거나 component boundary에 flow-root를 의도적으로 적용합니다.", prevention: "component 첫/마지막 child가 heading·paragraph·빈 block일 때 geometry test를 둡니다." },
      ],
    },
    {
      id: "bfc-flow-root-gap-selection",
      title: "collapse를 멈추는 값보다 간격의 소유자를 먼저 결정합니다",
      lead: "1px transparent border로 우연히 고치는 것과 component가 새 BFC·padding·gap을 책임지도록 설계하는 것은 유지보수 의미가 다릅니다.",
      explanations: [
        "부모와 child collapse를 막는 직접적인 방법은 두 margin이 adjoining하지 않게 만드는 것입니다. parent padding/border는 내부 공간·경계라는 실제 디자인 의미가 있을 때 좋습니다. display:flow-root는 새 block formatting context를 명시적으로 만들어 child margin이 root 밖과 collapse하지 않고 float도 포함합니다.",
        "overflow:auto/hidden도 새 BFC를 만들 수 있지만 clipping이나 scroll container라는 부작용이 있습니다. collapse만 막으려고 overflow:hidden을 쓰면 shadow·sticky·focus ring이 잘리고 예상 밖 scroll 동작이 생길 수 있습니다. flow-root가 의도를 더 정확히 표현하는 경우가 많습니다.",
        "flex와 grid container에서는 item margin이 collapse하지 않고 gap으로 반복 간격을 중앙에서 관리할 수 있습니다. card list처럼 sibling 관계의 균일한 간격은 각 child의 margin보다 container gap이 유지보수에 좋습니다. 첫/마지막 item의 바깥 여백이 자동으로 생기지 않는 것도 장점입니다.",
        "gap은 margin과 완전히 같은 도구가 아닙니다. item 사이에만 공간을 넣고 outer edge는 만들지 않으며, auto margin과는 free-space 흡수 역할이 다릅니다. wrapping flex/grid에서는 행·열 gap이 생기고 multi-column에서도 의미가 있으므로 layout mode를 확인합니다.",
        "문서 typography처럼 heading/paragraph 자체가 앞뒤 rhythm을 소유하는 흐름은 margin collapse가 유용할 수 있습니다. 모든 margin을 0으로 지우고 wrapper를 늘리는 것도 정답은 아닙니다. component boundary에서는 parent padding/gap, long-form prose에서는 collapsed block margin처럼 소유권 정책을 정합니다.",
      ],
      concepts: [
        { term: "block formatting context", definition: "내부 block 배치와 float 상호작용을 바깥과 독립시키는 formatting 영역입니다.", detail: ["BFC root와 자식 margin은 collapse하지 않습니다.", "BFC 내부 normal block sibling margins는 여전히 collapse할 수 있습니다."] },
        { term: "display:flow-root", definition: "element가 새 BFC를 만드는 block container가 되도록 명시하는 display 값입니다.", detail: ["float를 포함하고 parent/child margin collapse 경계를 만듭니다.", "overflow clipping을 부수 효과로 요구하지 않습니다."] },
        { term: "gap", definition: "multi-column·flex·grid container가 item track 사이에 만드는 gutter입니다.", detail: ["첫/마지막 outer edge에는 생기지 않습니다.", "item margin과 중복하면 합산될 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "margin collapse를 막으려고 overflow:hidden을 넣은 뒤 sticky header와 shadow가 잘린다.", likelyCause: "BFC 생성 효과만 필요했는데 clipping/scroll container 효과까지 가진 overflow를 선택했습니다.", checks: ["overflow를 visible로 돌려 sticky/shadow 변화를 봅니다.", "flow-root로 바꾼 비교 fixture를 만듭니다.", "실제로 overflow clipping이 제품 요구인지 확인합니다."], fix: "clipping 요구가 없다면 display:flow-root 또는 의미 있는 padding/border로 formatting boundary를 만듭니다.", prevention: "BFC 생성 기법을 선택할 때 float containment·clipping·scroll·sticky 영향표를 review합니다." },
        { symptom: "flex list item 사이가 디자인의 두 배로 벌어진다.", likelyCause: "container gap과 child margin-block을 동시에 spacing source로 사용했습니다.", checks: ["DevTools Flex/Grid overlay에서 gap을 확인합니다.", "item computed margin을 봅니다.", "첫/마지막 outer edge와 중간 gap을 각각 측정합니다."], fix: "반복 item 간격은 container gap 하나가 소유하도록 child 외부 margin을 reset하고, outer inset은 container padding으로 분리합니다.", prevention: "component contract에 outer padding·item gap·item internal padding을 별도 token으로 정의합니다." },
      ],
      comparisons: [
        { title: "세로 간격·collapse 경계 설계", options: [
          { name: "child margin", chooseWhen: "긴 prose에서 heading·paragraph가 자체 rhythm을 갖고 collapse가 자연스러울 때", avoidWhen: "독립 component list의 일정 item spacing을 container가 소유해야 할 때", tradeoffs: ["문서 흐름에 간결합니다.", "parent/empty block과 collapse를 이해해야 합니다."] },
          { name: "parent padding", chooseWhen: "content와 component 경계 사이의 내부 여백일 때", avoidWhen: "sibling 사이 gutter만 필요할 때", tradeoffs: ["collapse를 명확히 끊고 background 영역에 포함됩니다.", "outer spacing과 의미가 다릅니다."] },
          { name: "flow-root", chooseWhen: "새 BFC와 float containment가 component 경계 의미일 때", avoidWhen: "단지 sibling 간격을 수치로 만들 목적일 때", tradeoffs: ["overflow clipping 없이 BFC를 명시합니다.", "formatting context 변화가 float/layout에 영향을 줍니다."] },
          { name: "flex/grid gap", chooseWhen: "container가 반복 item 사이의 일관된 gutter를 소유할 때", avoidWhen: "normal block prose 흐름의 개별 의미 간격", tradeoffs: ["collapse 없이 간격이 명시적입니다.", "layout mode를 바꾸며 item sizing/alignment도 함께 달라질 수 있습니다."] },
        ] },
      ],
    },
    {
      id: "decoration-layout-invariants-and-collapse-boundaries",
      title: "outline·shadow는 layout 바깥 장식이고 flow-root는 margin collapse 경계를 명시합니다",
      lead: "보이는 외곽의 크기와 layout box를 구분하고, margin이 사라졌다는 감각 대신 collapse 대상·BFC 경계·실제 geometry를 수치로 검증합니다.",
      explanations: [
        "border는 border box와 used size 계산에 참여하지만 outline과 box-shadow는 layout 공간을 예약하지 않습니다. 두 장식이 바깥으로 그려져도 DOMRect와 sibling 배치는 border box가 기준이며, ancestor overflow가 focus outline을 자르는지는 별도로 확인합니다.",
        "outline은 border-radius와 똑같이 clip된다고 가정하지 않습니다. focus를 shadow 하나로 표현하면 Windows High Contrast에서 사라질 수 있으므로 native outline 또는 system color fallback을 유지하고 zoom·forced colors에서 실제 모양을 봅니다.",
        "큰 blur와 여러 shadow layer는 paint damage area·memory를 키울 수 있습니다. scroll 중 card가 끊기면 Performance panel의 Paint·Composite를 측정하고 smaller blur·border·pseudo-element opacity를 비교하며 will-change를 상시 남기지 않습니다.",
        "parent와 first child의 block margin은 adjoining 조건에서 collapse합니다. parent에 border·padding·inline content가 있거나 새 BFC를 만들면 차단됩니다. display:flow-root는 parent/child 경계를 만들지만 같은 BFC 안 모든 sibling collapse를 없애는 spacing utility는 아닙니다.",
        "negative margin·clipping·shadow는 보안 경계가 아닙니다. 장식 overlay가 control을 덮으면 pointer/stacking/focus를 검사하고, 권한과 민감 data는 server에서 통제합니다. DevTools Box Model·Rendering·Performance를 함께 사용합니다.",
        "logical border·margin은 horizontal-tb, vertical-rl, LTR/RTL에서 검증합니다. margin-block-start의 resolved physical side를 Computed와 rectangle로 비교하고 400% zoom에서도 outline이 text와 focus를 가리지 않는지 확인합니다.",
      ],
      concepts: [
        { term: "paint-only decoration", definition: "border box used size를 늘리지 않고 주변에 그려지는 outline·shadow 같은 시각 효과입니다.", detail: ["DOMRect와 paint bounds가 다를 수 있습니다.", "clipping·forced colors를 별도 검증합니다."] },
        { term: "collapse boundary", definition: "adjoining block margins가 결합되는 것을 막는 border·padding·BFC 등의 경계입니다.", detail: ["flow-root가 명시적 BFC를 만듭니다.", "sibling과 parent/child collapse를 구분합니다."] },
        { term: "paint invalidation", definition: "style·geometry 변화 뒤 다시 그릴 화면 영역을 browser가 정하는 과정입니다.", detail: ["큰 blur는 넓은 영역을 만들 수 있습니다.", "실제 trace로 비용을 측정합니다."] },
      ],
      codeExamples: [
        {
          id: "outline-shadow-layout-invariant",
          title: "outline·shadow가 border-box geometry를 바꾸지 않는지 검증",
          language: "html",
          filename: "outline-shadow-invariant.html",
          purpose: "button의 outline과 shadow를 DOMRect·offset size와 비교해 layout/paint 경계를 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>outline과 shadow geometry</title>\n  <style>\n    body { margin: 0; padding: 20px; }\n    .action { box-sizing: border-box; inline-size: 120px; block-size: 48px; border: 2px solid navy; outline: 3px solid #b00020; outline-offset: 3px; box-shadow: 8px 6px 12px rgb(0 0 0 / .35); background: white; color: #111; }\n    @media (forced-colors: active) { .action { box-shadow: none; outline-color: Highlight; } }\n  </style>\n</head>\n<body>\n  <button class=\"action\" type=\"button\">저장</button>\n  <pre id=\"result\"></pre>\n  <script>\n    const action = document.querySelector('.action');\n    const style = getComputedStyle(action);\n    const rect = action.getBoundingClientRect();\n    document.querySelector('#result').textContent = [\n      `rect=${Math.round(rect.width)}x${Math.round(rect.height)}`,\n      `offset=${action.offsetWidth}x${action.offsetHeight}`,\n      `outline=${style.outlineWidth}/${style.outlineOffset}`,\n      `shadow-present=${style.boxShadow !== 'none'}`,\n      `layout-invariant=${Math.round(rect.width) === 120 && Math.round(rect.height) === 48}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-9", explanation: "120×48 border-box에 outline·offset·blur shadow와 forced-colors fallback을 선언합니다." },
            { lines: "12-14", explanation: "visible label button과 결과 영역을 둡니다." },
            { lines: "17-19", explanation: "computed paint property와 두 layout geometry API를 읽습니다." },
            { lines: "20-26", explanation: "장식과 무관하게 border-box가 120×48인지 출력합니다." },
          ],
          run: { environment: ["현대 Chromium"], command: "browser에서 outline-shadow-invariant.html을 열고 결과 확인" },
          output: { value: "rect=120x48\noffset=120x48\noutline=3px/3px\nshadow-present=true\nlayout-invariant=true", explanation: ["outline과 shadow는 120×48 layout geometry에 포함되지 않습니다.", "offsetWidth와 DOMRect가 같은 border-box size를 보고합니다.", "forced colors에서도 label과 outline fallback이 남습니다."] },
          experiments: [
            { change: "border를 10px로 늘립니다.", prediction: "rect는 120×48이고 content area만 줄어듭니다.", result: "border-box 안 border와 paint-only outline을 구분합니다." },
            { change: "parent에 overflow:hidden을 적용합니다.", prediction: "outline·shadow가 clip될 수 있지만 rect는 같습니다.", result: "geometry와 focus 가시성은 별도입니다." },
            { change: "shadow blur를 80px로 늘립니다.", prediction: "geometry는 같지만 Paint 비용이 커질 수 있습니다.", result: "Performance trace로 판단합니다." },
          ],
          sourceRefs: ["web-shadow-source", "css-backgrounds-borders", "wcag-focus"],
        },
        {
          id: "flow-root-parent-margin-collapse-proof",
          title: "normal parent와 flow-root parent의 child margin collapse 비교",
          language: "html",
          filename: "flow-root-margin-collapse.html",
          purpose: "같은 logical margin이 parent와 collapse되는 경우와 BFC 안에 유지되는 경우를 geometry로 비교합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>margin collapse 경계</title>\n  <style>\n    body { margin: 0; }\n    .case { inline-size: 200px; border: 1px solid transparent; margin-block-end: 10px; }\n    .parent { background: lavender; }\n    .flow .parent { display: flow-root; }\n    .child { block-size: 20px; margin-block-start: 30px; background: navy; }\n  </style>\n</head>\n<body>\n  <section class=\"case normal\" aria-label=\"일반 block\"><div class=\"parent\"><div class=\"child\"></div></div></section>\n  <section class=\"case flow\" aria-label=\"flow root\"><div class=\"parent\"><div class=\"child\"></div></div></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const measure = (selector) => {\n      const parent = document.querySelector(`${selector} .parent`);\n      const child = parent.querySelector('.child');\n      return { parent, child, offset: Math.round(child.getBoundingClientRect().top - parent.getBoundingClientRect().top), height: Math.round(parent.getBoundingClientRect().height) };\n    };\n    const normal = measure('.normal');\n    const flow = measure('.flow');\n    document.querySelector('#result').textContent = [\n      `normal-offset=${normal.offset}`,\n      `flow-root-offset=${flow.offset}`,\n      `normal-height=${normal.height}`,\n      `flow-root-height=${flow.height}`,\n      `flow-display=${getComputedStyle(flow.parent).display}`,\n      `logical-margin=${getComputedStyle(flow.child).marginBlockStart}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-11", explanation: "두 fixture를 같게 두고 두 번째 parent만 flow-root로 만듭니다." },
            { lines: "14-17", explanation: "30px logical margin과 20px child를 동일하게 렌더링합니다." },
            { lines: "20-26", explanation: "child-parent offset과 parent height를 rectangle로 계산합니다." },
            { lines: "27-35", explanation: "normal collapse와 flow-root BFC 결과를 출력합니다." },
          ],
          run: { environment: ["display:flow-root 지원 browser"], command: "browser에서 flow-root-margin-collapse.html을 열고 결과 확인" },
          output: { value: "normal-offset=0\nflow-root-offset=30\nnormal-height=20\nflow-root-height=50\nflow-display=flow-root\nlogical-margin=30px", explanation: ["normal parent에서는 first-child margin이 collapse해 top이 같습니다.", "flow-root에서는 margin이 parent 안에 남아 height가 50px입니다.", "computed margin 자체는 모두 30px입니다."] },
          experiments: [
            { change: "normal parent에 padding-block-start:1px을 추가합니다.", prediction: "offset 31px, height 51px이 됩니다.", result: "padding이 adjoining 조건을 끊습니다." },
            { change: "child margin을 -10px로 바꿉니다.", prediction: "negative collapse 공식에 따라 위치·높이가 달라집니다.", result: "positive/negative 집합으로 계산합니다." },
            { change: "children을 flex column에 넣습니다.", prediction: "flex item margins는 collapse하지 않습니다.", result: "layout mode에 맞춰 gap을 검토합니다." },
          ],
          sourceRefs: ["web-margin-collapse-source", "css2-collapsing-margins", "css-display", "css-logical"],
        },
      ],
      diagnostics: [
        { symptom: "focus outline과 shadow가 card 경계에서 잘린다.", likelyCause: "ancestor overflow clipping과 paint-only decoration을 layout spacing처럼 취급했습니다.", checks: ["ancestor overflow·clip-path·radius를 disable합니다.", "forced-colors와 400% zoom에서 focus를 봅니다.", "DOMRect와 paint bounds를 구분합니다."], fix: "outline이 clip되지 않는 wrapper/offset과 system color fallback을 사용합니다.", prevention: "keyboard·forced-colors·overflow fixture를 visual regression에 포함합니다." },
      ],
    },
    {
      id: "geometry-diagnostics-and-production-policy",
      title: "Computed 탭과 실제 좌표로 border·margin 문제를 재현합니다",
      lead: "보이는 빈 공간을 눈대중으로 고치지 않고 cascade 값→formatting context→border-box 좌표→paint·접근성 순서로 좁혀 갑니다.",
      explanations: [
        "첫 단계는 문제 element와 이웃·parent의 box를 DevTools overlay로 표시하고 computed display, position, float, overflow, box-sizing, border, padding, margin을 기록하는 것입니다. Styles 탭의 선언값만 보지 말고 shorthand가 어떤 longhand를 reset했는지 Computed에서 확인합니다.",
        "두 번째는 getBoundingClientRect로 실제 border box 좌표를 측정합니다. 형제 gap은 next.top-current.bottom, parent 내부 offset은 child.top-parent.top, 중앙 정렬은 child.left-parent.left로 계산합니다. rect에는 margin과 shadow가 포함되지 않으며 transform 후 viewport 좌표라는 점을 기록합니다. subpixel layout에서는 무조건 반올림하지 말고 tolerance를 둡니다.",
        "세 번째는 formatting context를 판별합니다. normal block인지 flex/grid item인지, BFC root인지, absolute/float인지에 따라 auto margin과 collapse 규칙이 달라집니다. display를 임시로 flow-root/flex로 바꾸어 증상 변화만 보는 것은 유용하지만 그 값이 제품에 적합한지는 별도 판단합니다.",
        "네 번째는 paint와 접근성을 검증합니다. border/outline/shadow는 screenshot에서 비슷해도 layout·forced-colors·clipping·paint 비용이 다릅니다. keyboard focus, 200% zoom, RTL, 고대비, 긴 text, list 100개 scroll을 대표 fixture로 둡니다.",
        "자동 테스트에서는 computed style 문자열 전체를 browser 간 snapshot하기보다 중요한 계약을 수치·predicate로 검증합니다. 예를 들어 card width 허용 오차 0.5px, sibling gap 16px, focus outline-style이 none이 아님, shadow 제거 baseline보다 paint 시간이 예산 안이라는 식입니다. CSSOM color serialization 차이를 피하고 실제 사용자 결과에 가까운 assertion을 선택합니다.",
        "운영 design system은 border width/radius/elevation/spacing token을 역할 이름으로 제공합니다. raw 17px·-13px 값을 금지하는 것이 목적이 아니라 component 간 일관성, 고대비 fallback, 성능 budget과 변경 영향 범위를 중앙에서 관리하는 것이 목적입니다. 예외는 이유·소유자·테스트를 남깁니다.",
      ],
      concepts: [
        { term: "getBoundingClientRect", definition: "transform이 반영된 element border box의 viewport 기준 사각형을 반환하는 DOM API입니다.", detail: ["margin과 box-shadow는 rect 크기에 포함되지 않습니다.", "scroll·zoom·subpixel·transform을 고려해 비교합니다."] },
        { term: "computed style", definition: "cascade와 기본값 처리를 거친 CSS property의 계산값을 읽는 표현입니다.", detail: ["used geometry와 항상 같은 의미는 아닙니다.", "shorthand보다 longhand를 확인하는 데 유용합니다."] },
        { term: "spacing ownership", definition: "outer space·item gutter·internal inset을 어느 component/container가 책임지는지 정한 설계 계약입니다.", detail: ["margin/gap/padding 중복을 막습니다.", "component 재배치 때 예측 가능성을 높입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "Computed margin은 50px인데 화면에서 측정한 gap은 30px뿐이다.", likelyCause: "다른 adjoining margin과 음수 값이 collapse했거나 transform/overlap이 geometry 관찰을 바꿨습니다.", checks: ["양쪽 element의 모든 block-axis margin을 기록합니다.", "adjoining chain에 빈 block이 있는지 확인합니다.", "rect gap을 소수점 그대로 출력합니다.", "transform과 relative positioning을 잠시 해제해 layout 좌표와 paint 위치를 구분합니다."], fix: "collapse 집합을 최대 양수+최소 음수 규칙으로 다시 계산하고, 의도한 spacing owner가 container라면 gap/padding으로 옮깁니다.", prevention: "margin 값 snapshot 대신 실제 gap geometry test를 사용합니다." },
        { symptom: "getBoundingClientRect는 같은데 화면상 한 card가 훨씬 커 보인다.", likelyCause: "shadow·outline·filter 같은 ink effect가 border box 밖에 paint됩니다. transform은 rect에도 반영되므로 같은 rect라면 우선 원인에서 제외합니다.", checks: ["shadow/outline/filter를 하나씩 끕니다.", "transform이 있다면 제거 전후 rect도 함께 비교합니다.", "paint flashing과 screenshot bounds를 봅니다.", "rect가 margin/shadow를 포함하지 않는 API 계약을 확인합니다."], fix: "layout size와 ink overflow를 별도 지표로 관리하고 clipping·overlap·screenshot 영역에 필요한 안전 공간을 설계합니다.", prevention: "geometry assertion과 visual regression을 서로 대체하지 않고 함께 둡니다." },
      ],
      expertNotes: [
        "Layout Shift API나 Performance panel로 border state 변화의 실제 CLS 영향을 확인하되, user input 직후 허용되는 shift와 초기 load shift를 구분합니다.",
        "container query·component theme가 추가되어도 spacing ownership과 focus fallback 계약을 token layer에 유지하면 local override가 shadow·margin 부채로 번지는 것을 줄일 수 있습니다.",
      ],
    },
  ],
  lab: {
    title: "collapse와 clipping이 있는 학습 카드 목록을 측정 기반으로 재설계하기",
    scenario: "학습 카드 목록에서 제목 첫 margin이 카드 밖으로 빠지고, item margin과 gap이 중복되며, 둥근 media가 corner 밖으로 보이고, hover border가 layout을 흔들며, 큰 shadow 때문에 scroll이 끊기고 keyboard focus ring은 clipping됩니다.",
    setup: ["원본 day04의 border·radius·shadow·margin 5개 파일을 read-only 근거로 준비합니다.", "고정 400px fixture와 responsive fixture, LTR/RTL, keyboard, forced-colors, 200% zoom 환경을 준비합니다.", "DevTools Box Model·Flex/Grid overlay·Performance·Rendering paint flashing과 console geometry 기록표를 엽니다."],
    steps: [
      "각 card의 content/padding/border/margin edge와 현재 spacing owner를 도식화합니다.",
      "border shorthand와 개별 면 rule의 최종 longhand를 Computed에서 기록하고 border-box 크기를 측정합니다.",
      "읽기 시작 강조선을 border-inline-start로 바꾸고 LTR·RTL에서 physical mapping을 확인합니다.",
      "media 자체 radius 또는 card clipping boundary를 선택하고 child focus ring·shadow가 잘리지 않는지 검증합니다.",
      "hover/focus state는 transparent border 예약과 :focus-visible outline으로 분리하고 상태 전후 rect를 비교합니다.",
      "다층 shadow를 contact/ambient/ring 역할로 단순화하고 100개 list scroll의 paint baseline과 비교합니다.",
      "모든 인접/parent-child margin chain을 표시하고 실제 gap을 getBoundingClientRect로 출력합니다.",
      "card list의 반복 간격은 container gap, outer inset은 padding, prose rhythm은 필요한 margin으로 소유권을 재배치합니다.",
      "collapse boundary에 flow-root가 필요한지 overflow 부작용표로 결정하고 normal/flex/grid fixture를 회귀 테스트합니다.",
      "keyboard·forced-colors·zoom·RTL·긴 제목에서 focus, contrast, overlap, horizontal overflow를 최종 확인합니다.",
    ],
    expectedResult: ["상태 변화 전후 card border box 크기가 같고 layout shift가 없습니다.", "LTR·RTL 모두 읽기 시작 면에 강조선이 배치됩니다.", "media corner는 의도대로 clip되며 child focus indicator와 shadow는 보입니다.", "item 사이 gap과 card 내부/외부 여백이 각각 한 소유자에게만 정의됩니다.", "양수·음수·parent-child collapse 예측값과 실제 rect gap이 일치합니다.", "forced-colors에서도 keyboard focus와 component 경계가 식별됩니다.", "shadow 단순화 후 긴 목록의 paint 비용이 정한 budget 안에 들어옵니다."],
    cleanup: ["진단용 fixed width·색상·console output·paint flashing을 제거합니다.", "임시 overflow:hidden, transparent separator, 음수 margin patch를 제품 코드에 남기지 않습니다.", "clean reload 후 production stylesheet와 실제 content로 geometry/accessibility 회귀를 다시 실행합니다."],
    extensions: ["vertical-rl writing mode에서 logical border/radius/margin을 검증합니다.", "container width를 320~1440px로 바꾸며 subpixel gap tolerance를 자동 측정합니다.", "Playwright로 focus outline·rect gap·RTL mapping을 CI assertion으로 옮깁니다.", "100·500·1000개 card에서 shadow layer와 blur별 paint 시간을 비교해 elevation budget을 만듭니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 border·radius·shadow card를 border-box와 논리 방향 속성으로 다시 만들고 geometry를 출력하세요.", requirements: ["inline-size 240px card에 padding과 서로 다른 inline-start border를 적용합니다.", "타원 radius와 image clipping 방식을 설명합니다.", ":focus-visible outline을 유지하고 shadow는 장식으로만 사용합니다.", "getComputedStyle longhand와 getBoundingClientRect width를 출력합니다.", "LTR·RTL 결과를 비교합니다."], hints: ["shorthand 뒤에 logical side override를 둡니다.", "radius는 child clipping을 자동 보장하지 않습니다."], expectedOutcome: "두 방향에서 의미적 시작 면이 맞고 card border box 크기·focus indicator가 안정적인 runnable page가 완성됩니다.", solutionOutline: ["box-sizing부터 고정합니다.", "physical 면이 아니라 inline-start를 사용합니다.", "computed style과 rect를 별도 기록합니다."] },
    { difficulty: "응용", prompt: "양수·음수·parent-child margin collapse bug가 섞인 article card를 진단하고 spacing owner를 재배치하세요.", requirements: ["adjoining margin chain을 그립니다.", "50/30, 30/-10, -20/-35 결과를 예측하고 측정합니다.", "parent 첫 child collapse를 재현합니다.", "prose rhythm은 보존하고 component list는 gap/padding으로 바꿉니다.", "flow-root와 overflow:hidden의 부작용을 비교합니다."], hints: ["형제 둘만 보지 말고 빈 block까지 chain을 찾습니다.", "BFC는 내부 sibling collapse를 모두 없애지 않습니다."], expectedOutcome: "선언 margin과 실제 gap 차이를 숫자로 설명하고 clipping 부작용 없이 의도한 간격을 유지합니다.", solutionOutline: ["최대 양수와 최소 음수를 찾습니다.", "container/item/internal spacing을 분리합니다.", "경계 의미에 맞는 padding·gap·flow-root를 선택합니다."] },
    { difficulty: "설계", prompt: "대규모 design system의 border·radius·elevation·spacing·focus 정책과 회귀 체계를 설계하세요.", requirements: ["logical/physical property 선택 기준을 정의합니다.", "border/radius/shadow token의 역할과 고대비 fallback을 정합니다.", "negative margin 허용 조건과 spacing ownership 규칙을 만듭니다.", "normal block/flex/grid/BFC의 collapse matrix를 문서화합니다.", "geometry·visual·keyboard·forced-colors·RTL·performance CI를 설계합니다.", "raw 예외의 승인·만료·측정 근거를 정의합니다."], hints: ["token 숫자보다 어떤 의미와 test를 보장하는지가 중요합니다.", "getBoundingClientRect와 screenshot은 서로 다른 실패를 찾습니다."], expectedOutcome: "팀이 효과를 임의로 누적하지 않고 layout·접근성·성능 계약으로 검증할 수 있는 운영 가능한 CSS 정책이 완성됩니다.", solutionOutline: ["목적별 property decision table을 만듭니다.", "spacing owner와 formatting context를 component API에 포함합니다.", "대표 fixture와 수치 budget을 CI에 연결합니다."] },
  ],
  reviewQuestions: [
    { question: "border-width와 color가 있는데 선이 안 보일 수 있는 가장 기본적인 이유는 무엇인가요?", answer: "border-style 초기값이 none이기 때문입니다. non-none style이 없으면 visible border가 만들어지지 않습니다." },
    { question: "border shorthand를 뒤에 선언할 때 기존 개별 면 색이 사라질 수 있는 이유는 무엇인가요?", answer: "shorthand는 생략한 longhand까지 초기값으로 재설정하므로 기존 border color·width·style override를 보존하지 않기 때문입니다." },
    { question: "border-inline-start와 border-left는 언제 같은 면이고 언제 달라지나요?", answer: "horizontal LTR에서는 둘 다 왼쪽이지만 RTL에서는 inline-start가 오른쪽이며 writing-mode에 따라 inline 축이 세로가 될 수도 있습니다." },
    { question: "부모에 border-radius를 주면 child 이미지도 항상 그 곡선으로 잘리나요?", answer: "아닙니다. 부모 background/border curve와 descendant overflow clipping은 별개라 이미지 자체 radius 또는 의도적인 overflow clipping이 필요합니다." },
    { question: "keyboard focus에는 border·outline·box-shadow 중 무엇을 기본으로 선택하나요?", answer: "layout을 바꾸지 않고 forced-colors에서도 살아남기 쉬운 :focus-visible outline을 기본으로 하고, shadow ring은 보조 장식으로 사용합니다." },
    { question: "box-shadow가 card의 getBoundingClientRect width를 키우나요?", answer: "아닙니다. rect는 border box를 나타내고 shadow visual overflow는 밖에 paint되지만 layout border-box 크기에 포함되지 않습니다." },
    { question: "400px container 안 160px block에 margin-inline:auto를 주면 시작 offset은 얼마인가요?", answer: "남은 240px을 양쪽 auto margin이 나누므로 120px입니다." },
    { question: "30px bottom margin과 50px top margin이 collapse하면 결과는 얼마인가요?", answer: "양수끼리는 큰 값인 50px입니다. 80px로 합산하지 않습니다." },
    { question: "30px과 -10px, 그리고 -20px과 -35px의 collapsed 결과는 각각 얼마인가요?", answer: "혼합은 최대 양수와 최소 음수의 합이라 20px이고, 모두 음수면 가장 작은 값인 -35px입니다." },
    { question: "display:flow-root를 주면 내부 모든 block sibling의 margin collapse가 사라지나요?", answer: "아닙니다. BFC root와 child margin collapse는 막지만 같은 BFC 안 normal-flow sibling의 adjoining margin은 여전히 collapse할 수 있습니다." },
    { question: "반복 card 간격에 child margin보다 gap이 흔히 유리한 이유는 무엇인가요?", answer: "container 한 곳이 item 사이 gutter를 소유하고 첫/마지막 outer edge에는 불필요한 여백을 만들지 않으며 margin collapse도 없기 때문입니다." },
    { question: "computed margin과 실제 빈 공간이 다를 때 어떤 수치를 측정해야 하나요?", answer: "인접 형제라면 next.getBoundingClientRect().top-current.getBoundingClientRect().bottom을 계산하고 formatting context와 adjoining margin chain을 함께 확인합니다." },
    { question: "outline-offset 3px은 button width·height에 더해지나요?", answer: "아닙니다. outline과 offset은 paint 위치이며 border-box layout size와 DOMRect를 늘리지 않습니다." },
    { question: "flow-root를 주면 모든 sibling margin collapse가 사라지나요?", answer: "아닙니다. BFC root와 child 경계는 바뀌지만 같은 BFC 안 normal-flow sibling margins는 여전히 collapse할 수 있습니다." },
    { question: "box-shadow만으로 focus를 표시하면 forced colors에서도 항상 보이나요?", answer: "아닙니다. shadow가 제거될 수 있으므로 outline·system color fallback과 실제 High Contrast 검증이 필요합니다." },
    { question: "negative margin으로 화면 밖에 옮긴 data는 보호되나요?", answer: "아닙니다. geometry는 권한 경계가 아니며 DOM·network data는 그대로 읽힐 수 있습니다." },
  ],
  completionChecklist: [
    "border shorthand와 longhand reset, style:none, box-sizing에 따른 최종 크기를 설명하고 계산했다.",
    "physical/logical side를 의도에 맞게 선택하고 LTR·RTL mapping을 확인했다.",
    "원형·타원 radius와 반지름 축소, descendant clipping 조건을 다양한 content 비율에서 검증했다.",
    "border·outline·shadow 목적을 분리하고 keyboard·forced-colors에서 focus indicator를 확인했다.",
    "다층·inset shadow의 순서와 offset/blur/spread를 설명하고 긴 목록 paint 비용을 측정했다.",
    "margin shorthand·logical margin·auto의 layout mode별 의미와 음수 margin 위험을 검증했다.",
    "양수·음수 margin collapse 결과와 형제·parent/child·empty block 조건을 계산했다.",
    "BFC/flow-root가 막는 collapse 범위와 overflow 부작용을 구분했다.",
    "component 반복 간격은 gap, 내부 inset은 padding, prose rhythm은 margin처럼 spacing owner를 명확히 했다.",
    "getComputedStyle과 getBoundingClientRect로 선언값·border box·actual gap·visual overflow를 구분했다.",
    "zoom·RTL·긴 text·keyboard·forced-colors·scroll performance 회귀를 수행했다.",
    "outline·outline-offset·shadow가 border-box를 늘리지 않는지 DOMRect와 offset size로 검산했다.",
    "forced-colors·keyboard·400% zoom에서 shadow 없이도 focus indicator가 식별되는지 확인했다.",
    "normal block과 flow-root의 parent/child margin offset·height를 실제 geometry로 비교했다.",
    "large blur·multi-shadow의 Paint/Composite 비용과 clipping 범위를 측정했다.",
    "CSS overlap·negative margin·clipping을 secret 또는 authorization 수단으로 사용하지 않았다.",
  ],
  nextSessions: ["css-07-position-stacking-modal"],
  sources: [
    { id: "web-shadow-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex09_box_shadow.html", usedFor: ["box-shadow offset/blur/spread/color", "button 비교", "다층 shadow 확장"], evidence: "그림자 없는 버튼과 2px offset·blur·spread의 단일 그림자 버튼 전체를 읽고 shadow geometry·layer·성능 실습의 출발점으로 사용했습니다." },
    { id: "web-border-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex10_border.html", usedFor: ["border width/style/color", "개별 면 color", "border shorthand"], evidence: "solid·dotted·dashed, top/left color override와 1px solid orange shorthand를 audit해 style:none·shorthand reset·logical side·box-sizing으로 확장했습니다." },
    { id: "web-radius-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex11_border_radious.html", usedFor: ["35px radius", "50% circle", "위쪽 corner radius", "image clipping"], evidence: "같은 kitten image의 기본·35px·50%·top corners variant를 모두 읽고 aspect-ratio·object-fit·타원 radius·descendant clipping 경계를 보강했습니다." },
    { id: "web-margin-shorthand-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex12_margin.html", usedFor: ["1/2/4값 margin shorthand", "inline-block spacing", "margin auto"], evidence: "10px, 20px 10px, 20px 0 50px 20px와 width:100%/auto 예제를 audit해 auto가 보이려면 free space가 필요하다는 geometry 실험으로 교정·확장했습니다." },
    { id: "web-margin-collapse-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex13_margin.html", usedFor: ["인접 block collapse", "empty block", "parent/child collapse", "absolute/float/flex/grid 예외"], evidence: "세 200×100 block의 30px margin과 원본 주석의 collapse 조건·예외를 읽고 양수/음수 집합 계산·BFC/flow-root/gap 측정으로 확장했습니다." },
    { id: "css-backgrounds-borders", repository: "W3C CSS Working Group", path: "TR/css-backgrounds-3/", publicUrl: "https://www.w3.org/TR/css-backgrounds-3/", usedFor: ["border longhand/shorthand", "rounded corner clipping", "overlapping radii", "box-shadow shape/layer/layout"], evidence: "2026-07-12 확인한 CSS Backgrounds and Borders Level 3의 border, rounded corners, corner clipping과 drop shadow 정의를 기준으로 설명과 실험을 검증했습니다." },
    { id: "css-box-model", repository: "W3C CSS Working Group", path: "TR/css-box-4/", publicUrl: "https://www.w3.org/TR/css-box-4/", usedFor: ["content/padding/border/margin area", "margin values", "box model terminology"], evidence: "CSS Box Model Level 4의 edge·area·margin/padding 정의를 geometry 진단과 spacing ownership 설명의 기준으로 사용했습니다." },
    { id: "css2-collapsing-margins", repository: "W3C CSS Working Group", path: "TR/CSS22/box.html#collapsing-margins", publicUrl: "https://www.w3.org/TR/CSS22/box.html#collapsing-margins", usedFor: ["adjoining vertical margin", "parent/child/empty block 조건", "positive/negative collapse 계산", "non-collapsing cases"], evidence: "CSS 2.2 box model의 collapsing margins 규칙으로 원본 주석을 재검증하고 양수·음수·연쇄 margin 계산을 작성했습니다." },
    { id: "css-logical", repository: "W3C CSS Working Group", path: "TR/css-logical-1/", publicUrl: "https://www.w3.org/TR/css-logical-1/", usedFor: ["block/inline axis", "logical border/margin", "logical corner", "direction/writing-mode mapping"], evidence: "CSS Logical Properties and Values Level 1을 기준으로 physical side와 flow-relative side 선택 및 RTL/vertical writing 설명을 검증했습니다." },
    { id: "css-display", repository: "W3C CSS Working Group", path: "TR/css-display-3/", publicUrl: "https://www.w3.org/TR/css-display-3/", usedFor: ["block formatting context", "flow-root", "inner/outer display", "flex/grid item behavior"], evidence: "CSS Display Level 3의 flow-root와 formatting context 정의를 BFC 경계·float containment·layout mode 비교에 사용했습니다." },
    { id: "wcag-focus", repository: "W3C Web Accessibility Initiative", path: "TR/WCAG22/#focus-appearance", publicUrl: "https://www.w3.org/TR/WCAG22/#focus-appearance", usedFor: ["focus indicator visibility", "size/contrast 검토", "keyboard accessibility", "forced-colors test"], evidence: "WCAG 2.2 Focus Appearance 기준을 outline/shadow 선택, 대비·면적과 keyboard/고대비 검증 checklist에 반영했습니다." },
  ],
  sourceCoverage: {
    filesRead: 5,
    filesUsed: 5,
    uncoveredNotes: [
      "원본 5개는 border style/color/shorthand, 이미지 radius, 단일 shadow, margin shorthand/auto와 collapse 조건을 모두 포함합니다. logical properties, radius 축소·clipping, outline 접근성, 다층 shadow 성능, 음수 collapse 계산, flow-root·gap, geometry API는 W3C 명세 기반 전문가 보강 범위입니다.",
      "border-image, mask/clip-path, filter:drop-shadow, anchor positioning과 전체 rendering pipeline은 이 세션의 단일 질문을 넘으므로 후속 시각 효과·layout 심화 범위로 남깁니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
