import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-09-flexbox-axes-alignment"],
  slug: "css-09-flexbox-axes-alignment",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 9,
  title: "Flexbox 축, 정렬, 줄바꿈과 아이템 크기 협상",
  subtitle: "가운데 정렬 property 조합을 넘어 flex formatting context가 item의 base size·min/max·free space를 계산하고 main/cross axis와 line별로 배치하는 과정을 수치로 추적합니다.",
  level: "고급",
  estimatedMinutes: 235,
  coreQuestion: "flex item들이 content·basis·grow·shrink·min-size·gap을 바탕으로 한 줄 또는 여러 줄의 공간을 어떻게 나누며, visual reorder 없이 다양한 writing mode와 responsive content를 어떻게 정렬할까요?",
  summary: "원본 ex12~20의 direction·wrap·justify·auto margin·align-items·baseline·align-content·중앙 정렬·gap을 모두 하나의 Flexbox model로 연결합니다. flex container/item/anonymous item, main/cross start, row/column과 direction, single/multi-line, flex base/hypothetical size, positive/negative free space, scaled shrink, freeze/clamp, automatic min-size와 min-inline-size:0을 실제 600px 계산으로 증명합니다. justify-content·auto margin·align-items/self·baseline·stretch·align-content·gap의 적용 조건을 분리하고 order/reverse가 DOM·reading·Tab order를 바꾸지 않는 접근성 위험, intrinsic content·overflow·RTL·zoom·performance 진단까지 다룹니다.",
  objectives: [
    "flex container와 direct child flex item, main/cross axis와 start/end를 flex-direction·writing mode·direction에서 결정할 수 있다.",
    "nowrap/wrap/wrap-reverse의 line 생성과 한 line 안 item order, 여러 line cross-size 배치를 설명할 수 있다.",
    "flex-basis·grow·shrink·min/max의 free-space 분배를 계산하고 flex shorthand를 정확히 해석할 수 있다.",
    "automatic minimum size 때문에 item이 줄지 않는 현상을 진단하고 min-inline-size:0·overflow 전략을 선택할 수 있다.",
    "justify-content·auto margin·align-items/self·baseline·align-content·gap이 어느 axis/조건에서 작동하는지 구분할 수 있다.",
    "row-reverse·order를 visual 편의로 남용하지 않고 DOM·reading·focus 순서를 responsive layout과 일치시킬 수 있다.",
  ],
  prerequisites: [
    { title: "viewport, 상대 단위와 모바일 우선 미디어 쿼리", reason: "available inline size와 content breakpoint를 기반으로 flex item이 한 축의 공간을 협상하고 wrap하는 알고리즘을 배웁니다.", sessionSlug: "css-08-responsive-viewport-media" },
  ],
  keywords: ["Flexbox", "flex container", "flex item", "main axis", "cross axis", "flex-direction", "flex-wrap", "flex-basis", "flex-grow", "flex-shrink", "free space", "justify-content", "align-items", "align-content", "gap", "order"],
  chapters: [
    {
      id: "flex-formatting-axes",
      title: "display:flex는 direct child를 flex item으로 만들고 하나의 main axis와 수직 cross axis를 정의합니다",
      lead: "row가 항상 왼쪽→오른쪽, column이 항상 위→아래라는 물리 좌표 암기 대신 writing mode·direction·flex-direction으로 start/end를 결정합니다.",
      explanations: [
        "flex container의 in-flow direct child는 flex item이 됩니다. grandchild는 자동 flex item이 아니며 해당 child가 다시 display:flex/grid를 선언할 때 별도 formatting context가 됩니다. text run은 anonymous flex item으로 감싸질 수 있어 직접 selector/style 제어가 어렵습니다.",
        "main axis는 flex-direction이 정합니다. row/row-reverse는 container의 inline axis, column/column-reverse는 block axis를 따릅니다. horizontal-tb LTR에서 row main-start는 left지만 RTL에서는 right입니다. 물리 left/right보다 start/end를 사용합니다.",
        "cross axis는 main axis와 수직이며 cross-start 방향은 writing mode에 의해 결정됩니다. justify-*가 무조건 horizontal, align-*가 무조건 vertical이라는 설명은 column/vertical writing에서 틀립니다. justify-content는 flex main axis, align-items/self/content는 cross axis를 중심으로 봅니다.",
        "display:flex는 block-level outer display와 flex inner layout, inline-flex는 inline-level outer display와 flex inner layout을 만듭니다. parent flow에서 container가 어떻게 참여하는지와 내부 item layout을 분리합니다.",
        "float/clear와 vertical margin collapse 같은 일부 normal-flow behavior가 flex formatting context에서 달라집니다. flex item margin은 collapse하지 않고 float은 flex item layout에 기대한 효과를 주지 않습니다.",
      ],
      concepts: [
        { term: "flex container", definition: "computed display가 flex/inline-flex여서 자식 flex items에 flex layout을 설정하는 box입니다.", detail: ["outer display와 inner flex formatting을 구분합니다.", "direct in-flow child가 item입니다."] },
        { term: "main axis", definition: "flex items가 한 line 안에서 배치되는 주 방향이며 flex-direction이 정합니다.", detail: ["main-start/end가 있습니다.", "writing mode와 direction에 의존합니다."] },
        { term: "cross axis", definition: "main axis에 수직인 축이며 item/line의 cross alignment와 size가 배치됩니다.", detail: ["cross-start/end가 있습니다.", "align-* property가 주로 작동합니다."] },
      ],
      codeExamples: [
        {
          id: "direction-versus-dom-order",
          title: "row-reverse의 visual order와 DOM order 차이 출력",
          language: "html",
          filename: "flex-direction-order.html",
          purpose: "flex-direction이 visual main-axis placement를 바꿔도 DOM·keyboard source order를 바꾸지 않는 사실을 geometry와 DOM 배열로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>Flex 방향과 순서</title>\n  <style>\n    .row { display: flex; inline-size: 300px; }\n    .reverse { flex-direction: row-reverse; }\n    button { inline-size: 100px; block-size: 40px; }\n  </style>\n</head>\n<body>\n  <div id=\"normal\" class=\"row\"><button>1</button><button>2</button><button>3</button></div>\n  <div id=\"reverse\" class=\"row reverse\"><button>1</button><button>2</button><button>3</button></div>\n  <pre id=\"result\"></pre>\n  <script>\n    const order = (id, visual = false) => {\n      const items = [...document.querySelectorAll(`#${id} button`)];\n      if (visual) items.sort((a, b) => a.getBoundingClientRect().left - b.getBoundingClientRect().left);\n      return items.map((item) => item.textContent).join(',');\n    };\n    document.querySelector('#result').textContent = [\n      `normal-dom=${order('normal')}`,\n      `normal-visual=${order('normal', true)}`,\n      `reverse-dom=${order('reverse')}`,\n      `reverse-visual=${order('reverse', true)}`\n    ].join('\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-9", explanation: "300px container와 100px button 세 개로 line을 정확히 채우고 두 번째만 row-reverse합니다." },
            { lines: "13-14", explanation: "두 container의 DOM button 순서는 모두 1,2,3입니다." },
            { lines: "17-22", explanation: "기본은 DOM array, visual=true이면 bounding left 좌표로 sort해 화면 왼쪽→오른쪽 순서를 얻습니다." },
            { lines: "23-28", explanation: "normal/reverse의 DOM과 visual order를 함께 출력합니다." },
          ],
          run: { environment: ["현대 browser", "LTR horizontal writing mode", "zoom 100%"], command: "browser에서 flex-direction-order.html을 열고 결과 확인" },
          output: { value: "normal-dom=1,2,3\nnormal-visual=1,2,3\nreverse-dom=1,2,3\nreverse-visual=3,2,1", explanation: ["row-reverse는 visual main-start/end placement만 뒤집습니다.", "DOM 순서와 일반 Tab focus 순서는 계속 1,2,3입니다.", "화면 순서로 의미 있는 단계/순위를 만들면 접근성 충돌이 생깁니다."] },
          experiments: [
            { change: "html에 dir=rtl을 설정합니다.", prediction: "row의 physical visual left→right 결과도 direction 영향을 받아 달라집니다.", result: "row start는 고정 left가 아니라 inline-start입니다." },
            { change: "각 button에 order:3,2,1을 부여합니다.", prediction: "visual order는 order-modified되지만 DOM/Tab order는 그대로입니다.", result: "order property도 semantic/focus order를 수정하지 않습니다." },
            { change: "DOM 자체를 3,2,1로 바꿉니다.", prediction: "DOM·visual·Tab이 모두 새 source order와 일치합니다.", result: "의미 순서가 바뀌어야 한다면 markup/data order를 고칩니다." },
          ],
          sourceRefs: ["web-flex-direction-source", "css-flexbox-1"],
        },
      ],
      diagnostics: [
        { symptom: "row-reverse navigation은 화면상 홈→과정→소개인데 Tab과 screen reader는 소개→과정→홈으로 이동한다.", likelyCause: "visual order로 정보 순서를 고치고 DOM order를 그대로 두었습니다.", checks: ["DOM text order·bounding visual order·Tab sequence를 각각 기록합니다.", "order/flex-direction reverse를 확인합니다.", "CSS off 결과를 봅니다."], fix: "논리적 data/DOM order를 사용자 task에 맞게 수정하고 reverse/order를 장식적 상황에만 사용합니다.", prevention: "responsive mode별 visual·DOM·focus order parity E2E를 둡니다." },
      ],
    },
    {
      id: "flex-lines-wrap",
      title: "flex-wrap은 item을 여러 flex line으로 나누고 각 line에서 sizing과 main-axis distribution을 독립 수행합니다",
      lead: "wrap은 Grid column 시스템이 아니라 source order item을 available main size에 맞춰 line으로 수집하는 과정입니다.",
      explanations: [
        "nowrap이 initial이며 모든 item을 한 line에 두고 필요하면 flex-shrink로 줄입니다. item min-size 때문에 더 줄지 못하면 overflow합니다. 원본 700px 안 six boxes는 width+padding+margin의 actual outer size를 계산해야 wrap 여부를 예측할 수 있습니다.",
        "wrap은 다음 item의 outer hypothetical main size가 line available size를 넘을 때 새 line을 만들 수 있습니다. flex item size가 최종 grow/shrink되기 전 line collection에 사용되는 size와 gap을 고려합니다.",
        "wrap-reverse는 line이 쌓이는 cross-start 방향을 뒤집지만 각 line item source order 자체를 자동 역순으로 만들지 않습니다. visual/reading order와 cross-axis expectation을 test합니다.",
        "한 line container에서 align-content는 효과가 없습니다. 여러 line이고 cross axis에 남는 공간이 있어야 line 집합을 distribute합니다. item 한 line 안 cross alignment는 align-items/self입니다.",
        "카드 collection은 Flex wrap도 가능하지만 행/열 track alignment가 중요한 2차원 layout이면 Grid가 더 직접적입니다. navigation/toolbar처럼 한 축 content 흐름과 wrapping이 핵심이면 Flexbox가 적합합니다.",
      ],
      concepts: [
        { term: "flex line", definition: "flex container main axis에서 함께 배치·size되는 flex item들의 한 줄 grouping입니다.", detail: ["wrap일 때 여러 line이 생깁니다.", "각 line이 free space를 별도 분배합니다."] },
        { term: "line breaking", definition: "available main size와 item outer hypothetical size를 사용해 item을 어느 flex line에 넣을지 정하는 과정입니다.", detail: ["gap과 item size가 영향을 줍니다.", "source/order-modified 순서를 따릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "flex-wrap:wrap인데 긴 URL을 가진 item 하나가 container를 밀어 page horizontal scroll을 만든다.", likelyCause: "item automatic min-size/min-content와 unbreakable content가 line/container보다 작아지지 않습니다.", checks: ["item min-width/min-inline-size computed value를 확인합니다.", "scrollWidth/clientWidth와 longest token을 봅니다.", "overflow-wrap/word-break requirement를 검토합니다."], fix: "flex item에 min-inline-size:0과 content에 overflow-wrap:anywhere 또는 명시적 overflow를 적용합니다.", prevention: "long URL/code/localization fixture와 document overflow assertion을 둡니다." },
      ],
    },
    {
      id: "flex-base-free-space-algorithm",
      title: "Flexbox는 flex base size에서 시작해 positive/negative free space를 grow/shrink factor로 분배하고 min/max에서 freeze합니다",
      lead: "flex:1이 단순히 width:동일이라는 말보다 basis·available space·gap·min-content를 수치로 계산합니다.",
      explanations: [
        "flex shorthand는 grow, shrink, basis를 설정합니다. initial은 0 1 auto, auto는 1 1 auto, none은 0 0 auto입니다. 흔한 flex:1은 browser grammar상 대개 1 1 0% 계열로 content basis보다 zero basis에서 space를 나누는 효과를 가집니다. explicit `flex:1 1 0`처럼 의도를 분명히 할 수 있습니다.",
        "flex-basis:auto는 main-size property(width/height depending axis)가 auto가 아니면 그 값을 참고하고 둘 다 auto면 content basis로 갑니다. basis가 auto가 아닌 경우 main-size property보다 basis가 초기 flex sizing을 주도할 수 있습니다.",
        "positive free space는 container inner main size에서 item outer base sizes와 gap 등을 빼고 grow factor 비율로 나눕니다. grow가 0이면 extra space를 흡수하지 않습니다. factor 합이 1보다 작은 fractional behavior 같은 세부는 spec algorithm을 따릅니다.",
        "negative free space는 shrink factor만이 아니라 flex base size를 곱한 scaled shrink factor 비율로 줄입니다. 큰 base item이 같은 shrink factor에서도 더 많이 줄 수 있습니다. min/max clamp에 닿은 item은 freeze되고 남은 space를 다시 분배합니다.",
        "border/padding/margin·box-sizing·aspect-ratio·replaced element·intrinsic contribution이 outer size에 참여합니다. 계산 lab에서는 decoration을 0으로 격리하고 실제 component에서는 DevTools Flex overlay의 base/size 정보를 봅니다.",
      ],
      concepts: [
        { term: "flex base size", definition: "flex item이 free-space 분배 전 flex-basis와 content/main-size 규칙으로 계산한 출발 main size입니다.", detail: ["min/max clamp와 구분됩니다.", "grow/shrink 계산의 basis입니다."] },
        { term: "free space", definition: "flex line의 available inner main size에서 item outer sizes와 gap을 뺀 남거나 부족한 공간입니다.", detail: ["positive면 grow, negative면 shrink가 주로 작동합니다.", "line별로 계산합니다."] },
        { term: "freeze", definition: "flex algorithm에서 item이 target size를 확정하고 이후 free-space 재분배에서 더 이상 변하지 않는 상태입니다.", detail: ["min/max violation에서 발생합니다.", "나머지 unfrozen item이 space를 다시 나눕니다."] },
      ],
      codeExamples: [
        {
          id: "flex-grow-math",
          title: "600px line에서 1:2:1 grow와 20px gap 계산",
          language: "html",
          filename: "flex-grow.html",
          purpose: "zero basis item이 gap을 제외한 560px positive free space를 1:2:1로 나누는 exact width를 측정합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>Flex grow 계산</title>\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; }\n    .line { display: flex; inline-size: 600px; gap: 20px; }\n    .item { min-inline-size: 0; block-size: 40px; padding: 0; border: 0; }\n    .a { flex: 1 1 0; }\n    .b { flex: 2 1 0; }\n    .c { flex: 1 1 0; }\n  </style>\n</head>\n<body>\n  <div class=\"line\"><div class=\"item a\">A</div><div class=\"item b\">B</div><div class=\"item c\">C</div></div>\n  <pre id=\"result\"></pre>\n  <script>\n    const width = (selector) => document.querySelector(selector).getBoundingClientRect().width;\n    document.querySelector('#result').textContent = [\n      `container=${document.querySelector('.line').getBoundingClientRect().width}`,\n      `gap=${getComputedStyle(document.querySelector('.line')).columnGap}`,\n      `A=${width('.a')}`, `B=${width('.b')}`, `C=${width('.c')}`,\n      `sum=${width('.a') + width('.b') + width('.c') + 40}`\n    ].join('\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "9-13", explanation: "container 600, gap 두 개 총 40, item decoration/min-size 영향을 제거하고 grow factor만 1:2:1로 둡니다." },
            { lines: "20-26", explanation: "container/gap/item border-box width와 width sum+gap을 출력합니다." },
          ],
          run: { environment: ["현대 browser", "zoom 100%", "subpixel scale이 없는 600 CSS px fixture"], command: "browser에서 flex-grow.html을 열고 결과 확인" },
          output: { value: "container=600\ngap=20px\nA=140\nB=280\nC=140\nsum=600", explanation: ["gap 40을 뺀 free space 560을 grow 총합 4로 나눠 factor 1당 140입니다.", "B는 factor 2라 280입니다.", "item과 gap 합이 container 600을 정확히 채웁니다."] },
          experiments: [
            { change: "B를 flex:1 1 0으로 바꿉니다.", prediction: "세 item이 각각 약 186.671875px 등 subpixel로 동일 분배되고 sum은 600에 근접/일치합니다.", result: "browser는 device/CSS pixel rounding을 item에 배분할 수 있습니다." },
            { change: "A에 min-inline-size:200px를 설정합니다.", prediction: "A는 200에서 clamp/freeze되고 B/C가 남은 공간을 재분배해 단순 1:2:1 결과가 깨집니다.", result: "min/max constraint는 factor 비율보다 최종 target을 제한합니다." },
            { change: "basis를 각각 100px로 바꾸고 grow를 0으로 둡니다.", prediction: "item은 100px씩이고 남은 260px는 justify-content/auto margin이 없으면 line end에 남습니다.", result: "grow 0은 positive free space를 item size로 흡수하지 않습니다." },
          ],
          sourceRefs: ["web-flex-direction-source", "web-flex-wrap-source", "css-flexbox-1", "css-align-3"],
        },
      ],
      diagnostics: [
        { symptom: "flex:1 card인데 text가 긴 card만 더 넓거나 다른 card가 눌린다.", likelyCause: "flex-basis:auto/content 또는 automatic min-size가 content contribution을 유지해 zero-basis equal distribution이 아닙니다.", checks: ["computed flex-basis/grow/shrink/min-inline-size를 확인합니다.", "DevTools Flex overlay에서 base/final size를 봅니다.", "long unbreakable content를 isolated fixture로 test합니다."], fix: "동일 distribution이면 flex:1 1 0과 min-inline-size:0을 사용하고 content wrapping/overflow를 정의합니다.", prevention: "short/long/empty/replaced content fixture의 item final widths를 regression test합니다." },
      ],
    },
    {
      id: "automatic-minimum-overflow",
      title: "flex item의 automatic minimum size는 content를 보호하지만 예상보다 줄지 않아 overflow를 만들 수 있습니다",
      lead: "width:0이나 flex-shrink를 더 키우기 전에 min-inline-size:auto와 min-content contribution을 확인합니다.",
      explanations: [
        "flex item의 main-axis automatic min-size는 overflow와 content/intrinsic size 제안에 따라 content-based minimum이 될 수 있습니다. 그래서 flex-shrink:1이어도 긴 word/image/table보다 작아지지 않습니다.",
        "`min-inline-size:0`은 item이 content min-size 아래로 shrink하도록 허용하는 일반 해결입니다. 그 후 content에 overflow-wrap:anywhere, overflow:auto/hidden, text-overflow 등의 실제 presentation policy를 적용합니다. 무조건 clip하면 정보 손실이 생깁니다.",
        "nested flex에서 outer item과 inner text wrapper 모두 automatic min-size가 병목일 수 있습니다. overflow element를 찾을 때 ancestor chain의 scrollWidth/clientWidth와 min-width를 추적합니다.",
        "image/video 같은 replaced element는 intrinsic dimensions·aspect-ratio와 max-inline-size:100%를 고려합니다. flex-basis:0만으로 image가 안전하게 줄지 않으므로 media CSS를 따로 둡니다.",
        "column flex에서는 main axis가 block이라 min-block-size:auto와 nested scroll region 문제가 생깁니다. app shell header/main/footer에서 middle `min-block-size:0; overflow:auto`가 필요한 이유를 axis 기준으로 이해합니다.",
      ],
      concepts: [
        { term: "automatic minimum size", definition: "min-width/min-height auto가 flex item의 content·overflow·size suggestion에 따라 제공하는 최소 main size입니다.", detail: ["content를 무작정 눌리지 않게 보호합니다.", "overflow 원인이 될 수 있습니다."] },
        { term: "min-content contribution", definition: "content가 가능한 wrapping을 해도 필요한 최소 intrinsic size contribution입니다.", detail: ["긴 unbreakable token이 크게 만듭니다.", "flex line sizing/min-size에 참여합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "flex item에 width:0; flex:1을 줬는데도 긴 code block 때문에 page가 넘친다.", likelyCause: "nested item의 automatic min-inline-size와 pre/code의 min-content가 shrink를 막습니다.", checks: ["overflowing descendant부터 flex ancestors의 scrollWidth/clientWidth를 확인합니다.", "min-inline-size computed value와 white-space를 봅니다.", "min-width:0을 어느 item boundary에 둘지 test합니다."], fix: "해당 flex item에 min-inline-size:0을 주고 code에는 overflow:auto 또는 wrapping/copy affordance를 설계합니다.", prevention: "long code/URL/table nested flex fixture와 document horizontal overflow test를 둡니다." },
      ],
    },
    {
      id: "main-axis-distribution-auto-margin",
      title: "justify-content는 grow/auto margin 뒤 남은 main-axis free space를 item group 사이에 분배합니다",
      lead: "item이 flex-grow로 모든 공간을 흡수하거나 auto margin이 먼저 소비하면 justify-content가 움직일 공간이 없습니다.",
      explanations: [
        "flex-start/end/center는 item group 위치, space-between은 item 사이만, space-around는 각 item 주변 절반 edge, space-evenly는 모든 interval을 균등하게 분배합니다. item 수 1개일 때 between behavior와 negative free space/safe alignment를 확인합니다.",
        "justify-content는 flex-direction의 main axis에 작동합니다. column이면 vertical main direction, row RTL이면 physical right/left가 바뀝니다. left/right보다 flex-start/end 또는 start/end의 의미를 구분합니다.",
        "원본 box2 margin-left:auto는 main-start auto margin이 available free space를 흡수해 box2와 이후 item을 line end로 밀어 toolbar group divider처럼 동작합니다. margin-right:auto는 반대 group 분리를 만듭니다. logical margin-inline-start:auto가 direction에 견고합니다.",
        "main-axis auto margin은 justify-content alignment 전에 positive free space를 흡수하므로 둘을 동시에 쓰면 justify 결과가 예상과 다를 수 있습니다. 여러 auto margin은 space를 나눕니다.",
        "gap은 item/line 사이 minimum gutter이며 edge 바깥 공간을 만들지 않습니다. margin으로 양쪽 gutter를 두 번 계산하거나 negative container margin hack을 쓰기보다 gap을 사용하고 older target만 fallback합니다.",
      ],
      concepts: [
        { term: "justify-content", definition: "flex line main axis의 남은 free space 안에서 item group을 정렬·분배하는 property입니다.", detail: ["item size 협상 뒤 작동합니다.", "main axis는 direction에 따라 바뀝니다."] },
        { term: "auto margin absorption", definition: "flex item main-axis auto margin이 positive free space를 받아 item/group을 분리·정렬하는 behavior입니다.", detail: ["justify-content보다 먼저 space를 소비합니다.", "logical margin을 사용합니다."] },
        { term: "gap", definition: "flex items/lines 사이에 추가되는 fixed/fluid gutter이며 outer edge에는 자동 공간을 만들지 않습니다.", detail: ["row-gap/column-gap axis mapping은 flex direction/wrap을 확인합니다.", "item margin과 별개입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "justify-content:space-between을 줬는데 item 사이가 벌어지지 않는다.", likelyCause: "flex-grow item이 positive free space를 모두 흡수하거나 item outer size가 line을 이미 채웠습니다.", checks: ["container inner main size와 item final sizes/gap을 합산합니다.", "flex-grow와 auto margin을 확인합니다.", "DevTools free-space overlay를 봅니다."], fix: "item sizing 의도와 distribution 의도를 분리해 grow를 줄이거나 group wrapper/auto margin/gap을 선택합니다.", prevention: "1개/2개/많은 item과 narrow/extra-space fixture에서 alignment를 test합니다." },
      ],
    },
    {
      id: "cross-axis-alignment-lines",
      title: "align-items/self는 한 line item을, align-content는 여러 flex line 집합을 cross axis에서 배치합니다",
      lead: "container height를 줬다고 align-content가 항상 작동하지 않으며 single-line과 multi-line을 먼저 구분합니다.",
      explanations: [
        "align-items는 flex container의 모든 item 기본 cross-axis self-alignment, align-self는 개별 item override입니다. stretch는 cross-size가 auto이고 margin 등 조건이 맞을 때 line cross size에 맞춥니다. item에 fixed height가 있으면 stretch가 보이지 않을 수 있습니다.",
        "baseline은 item의 alignment baseline을 맞춰 font size가 다른 text의 baseline을 정렬합니다. box top/center가 같아지는 것이 아니며 replaced/orthogonal item의 baseline fallback을 확인합니다.",
        "align-content는 wrap으로 여러 line이 생기고 container cross size에 extra space가 있을 때 line들을 flex-start/end/center/space-between/around/evenly/stretch로 배치합니다. nowrap/single line에서는 기대한 효과가 없습니다.",
        "column-gap/row-gap이 physical row/column 이름처럼 보이지만 flex에서 main/cross line/item 사이 적용은 flex-direction/wrap을 함께 봅니다. shorthand gap:first second의 mapping을 computed overlay로 확인합니다.",
        "safe center 등 overflow alignment는 item이 scroll container 시작 edge 밖으로 밀려 접근 불가능해지는 것을 예방할 수 있습니다. browser target과 actual overflow/focus를 test합니다.",
      ],
      concepts: [
        { term: "align-items/align-self", definition: "flex line cross axis에서 item의 self-alignment를 container default/개별 override로 정합니다.", detail: ["stretch·baseline·start/end/center 등이 있습니다.", "item cross auto size와 margin이 영향을 줍니다."] },
        { term: "align-content", definition: "여러 flex line이 차지한 cross size와 container cross size 사이의 extra space를 line 집합에 분배합니다.", detail: ["multi-line에서만 의미가 있습니다.", "item 한 개 alignment가 아닙니다."] },
        { term: "baseline alignment", definition: "item 내부 text/content가 제공하는 alignment baseline을 같은 cross-axis 위치에 맞추는 방식입니다.", detail: ["font size가 달라도 text line이 정렬됩니다.", "box edge alignment와 다릅니다."] },
      ],
      codeExamples: [
        {
          id: "items-versus-content-alignment",
          title: "align-items와 align-content가 서로 다른 대상을 움직이는 예",
          language: "html",
          filename: "flex-cross-axis.html",
          purpose: "두 flex line과 높이가 다른 item을 만들어 item alignment와 line distribution을 geometry로 구분합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>교차축 정렬</title>\n  <style>\n    body { margin: 0; }\n    .box { display: flex; flex-wrap: wrap; inline-size: 220px; block-size: 240px; align-items: center; align-content: space-between; gap: 0 20px; background: #eee; }\n    .item { flex: 0 0 100px; block-size: 40px; background: #acf; }\n    .tall { block-size: 80px; }\n  </style>\n</head>\n<body>\n  <div id=\"box\" class=\"box\"><div id=\"a\" class=\"item\">A</div><div id=\"b\" class=\"item tall\">B</div><div id=\"c\" class=\"item\">C</div><div id=\"d\" class=\"item\">D</div></div>\n  <pre id=\"result\"></pre>\n  <script>\n    const top = (id) => document.querySelector(id).offsetTop;\n    document.querySelector('#result').textContent = [\n      `A-top=${top('#a')}`, `B-top=${top('#b')}`,\n      `C-top=${top('#c')}`, `D-top=${top('#d')}`,\n      `line-gap=${top('#c') - (top('#b') + 80)}`\n    ].join('\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-10", explanation: "220px line에 100+20+100 두 item이 정확히 들어가 두 line이 생성됩니다. 첫 line cross size는 tall 80, 둘째는 40입니다." },
            { lines: "14", explanation: "A/B가 첫 line, C/D가 둘째 line에 source order로 배치됩니다." },
            { lines: "17-22", explanation: "offsetTop으로 첫 line 내 center alignment와 line 집합 space-between 결과를 출력합니다." },
          ],
          run: { environment: ["현대 browser", "zoom 100%", "default horizontal writing mode"], command: "browser에서 flex-cross-axis.html을 열고 결과 확인" },
          output: { value: "A-top=20\nB-top=0\nC-top=200\nD-top=200\nline-gap=120", explanation: ["첫 line cross size 80 안에서 40px A가 center되어 top 20, tall B는 top 0입니다.", "align-content:space-between이 첫 line을 top, 둘째 40px line을 container bottom 200에 둡니다.", "두 line content 사이의 remaining gap은 120입니다."] },
          experiments: [
            { change: "align-items:flex-start로 바꿉니다.", prediction: "A-top=0과 B-top=0이 되며 line positions는 유지됩니다.", result: "align-items는 line 내부 item을 움직입니다." },
            { change: "align-content:center로 바꿉니다.", prediction: "line group 총 120px이 240px container 중앙에 놓여 첫 line top 60, 둘째 line top 140이 됩니다.", result: "align-content는 line 집합 extra cross space를 배치합니다." },
            { change: "flex-wrap:nowrap으로 바꿉니다.", prediction: "한 line에 네 item이 shrink/overflow하고 align-content 효과가 없어집니다.", result: "align-content는 multi-line 조건이 필요합니다." },
          ],
          sourceRefs: ["web-flex-align-items-source", "web-flex-align-content-source", "css-align-3", "css-flexbox-1"],
        },
      ],
      diagnostics: [
        { symptom: "align-content:center가 아무 변화도 만들지 않는다.", likelyCause: "nowrap 또는 item 수/폭 때문에 flex line이 하나뿐이거나 container cross size에 extra space가 없습니다.", checks: ["DevTools Flex overlay에서 line 수를 확인합니다.", "computed flex-wrap과 container/item cross sizes를 측정합니다.", "원하는 대상이 item인지 line인지 묻습니다."], fix: "single-line item이면 align-items/self를 사용하고 multi-line distribution이면 wrap과 definite/available cross space를 구성합니다.", prevention: "single/multi-line fixture를 별도 test하고 alignment property 목적을 code comment에 기록합니다." },
      ],
    },
    {
      id: "flex-patterns-responsive",
      title: "toolbar·navigation·media object·center·card row를 sizing/axis contract로 조합합니다",
      lead: "property recipe를 복사하기보다 content가 늘고 줄 때 어느 item이 grow·shrink·wrap·scroll해야 하는지 먼저 정합니다.",
      explanations: [
        "toolbar는 actions의 intrinsic size를 유지하고 separator 앞 item에 margin-inline-start:auto를 줘 group을 나눌 수 있습니다. 좁은 폭에서 wrap할지 overflow menu/disclosure로 전환할지 keyboard/priority와 함께 결정합니다.",
        "media object는 image flex:none과 text flex:1 1 auto; min-inline-size:0을 사용하고 container query에서 column으로 바꿀 수 있습니다. image는 max-inline-size/aspect-ratio/object-fit을 따로 설정합니다.",
        "한 item을 viewport 중앙에 두는 `display:flex; place-content?`가 아니라 justify-content:center+align-items:center 조합은 single-line container에서 동작합니다. body height:100vh 대신 min-block-size:100dvh/svh와 content overflow를 고려합니다. Grid place-items:center가 더 간결할 수 있습니다.",
        "card rows는 wrap+gap+flex-basis:min()/clamp로 만들 수 있지만 각 row column alignment가 필요하면 Grid auto-fit/minmax를 고려합니다. Flex line마다 grow가 독립이라 마지막 line card가 예상보다 크게 늘 수 있습니다.",
        "navigation을 order/reverse로 mobile/desktop 재배치하지 않고 DOM priority를 유지합니다. label이 길어질 때 flex-shrink로 unreadable target을 만들기보다 wrap/disclosure와 min target size를 설계합니다.",
      ],
      concepts: [
        { term: "flex pattern contract", definition: "component에서 각 item의 basis·grow·shrink·min-size·wrap·overflow 책임을 명시한 layout 계약입니다.", detail: ["property recipe보다 content variation을 설명합니다.", "breakpoint/container behavior를 포함합니다."] },
        { term: "last-line growth", definition: "wrapped flex layout에서 각 line이 free space를 독립 분배해 마지막 line의 적은 item이 더 넓어지는 현상입니다.", detail: ["원하는 card grid인지 확인합니다.", "Grid가 더 적합할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "wrapped card 마지막 줄의 한 card가 전체 폭을 차지해 앞 줄 column과 맞지 않는다.", likelyCause: "flex:1 item이 line별 positive free space를 독립적으로 흡수합니다.", checks: ["각 line item count와 final widths를 확인합니다.", "basis/grow를 분리합니다.", "2차원 column alignment requirement를 확인합니다."], fix: "grow를 0으로 하고 explicit basis/max를 두거나 Grid auto-fit/minmax로 2차원 track을 설계합니다.", prevention: "item count 1~N과 incomplete last row visual fixture를 test합니다." },
      ],
    },
    {
      id: "flex-debugging-accessibility",
      title: "Flex 문제는 axis→line→base/min/max→free space→alignment→overflow→DOM order 순서로 진단합니다",
      lead: "justify/align 값을 무작정 바꾸기 전에 실제 algorithm stage와 accessibility consequence를 찾습니다.",
      explanations: [
        "computed flex-direction/writing-mode/direction으로 main/cross axis를 그립니다. wrap과 DevTools line overlay를 확인하고 item별 flex-basis/grow/shrink/min/max/outer decoration을 표로 만듭니다.",
        "container inner main size에서 gap과 base/target size를 빼 free space 부호를 구합니다. grow/shrink가 작동했는지, min/max clamp/freeze가 있었는지, auto margin이 space를 소비했는지 확인한 뒤 justify-content를 봅니다.",
        "cross axis는 line cross size·item cross auto/fixed·align-items/self, multi-line이면 align-content extra space를 구분합니다. baseline은 font metric/line box를 overlay로 확인합니다.",
        "overflow는 item/descendant의 min-content, min-inline/block-size:auto, white-space, replaced intrinsic size를 root까지 추적합니다. display:flex 자체를 원인으로만 보지 않습니다.",
        "visual order를 bounding rect로, DOM order를 children array로, focus order를 Tab E2E로 각각 기록합니다. CSS order/reverse와 aria-flowto/tabindex로 억지 보정하지 않고 logical DOM을 수정합니다.",
        "performance는 많은 nested flex layout과 JS geometry read/write에서 Layout cost를 측정합니다. Flexbox는 일반적으로 효율적이지만 무한 resize observer loop·content measurement thrash를 피합니다.",
      ],
      concepts: [
        { term: "flex overlay", definition: "DevTools가 flex container의 axis·line·gap·item size를 시각화하는 layout debugging 도구입니다.", detail: ["algorithm 가설을 확인합니다.", "browser마다 UI가 다릅니다."] },
        { term: "order-modified document order", definition: "Flex layout이 order property로 visual item processing 순서를 정한 순서입니다.", detail: ["DOM/reading/focus source order와 다를 수 있습니다.", "접근성 의미 순서를 바꾸는 데 사용하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "Flex layout이 깨질 때 align-items:center를 제거하면 우연히 고쳐지지만 다른 width에서 다시 깨진다.", likelyCause: "item min-size/overflow/line cross-size 문제를 alignment property로 가렸습니다.", checks: ["axis/line/base/min/max/free-space 표를 작성합니다.", "min-inline-size:0 isolated test를 합니다.", "cross fixed height와 content overflow를 확인합니다."], fix: "실제 sizing/overflow constraint를 수정하고 alignment는 intended axis behavior만 담당하게 합니다.", prevention: "Flex component에 algorithm-stage checklist와 long/zoom/wrap fixture를 둡니다." },
      ],
      expertNotes: [
        "Flex fragmentation/print behavior의 상세 algorithm은 구현 차이가 있을 수 있으므로 multi-page print/PDF에서 item split·order·header 반복을 실제 검증합니다.",
        "Subgrid는 Grid 기능이며 Flexbox line 사이 column alignment를 제공하지 않습니다. Flex와 Grid를 경쟁 도구가 아니라 one-dimensional/two-dimensional 책임으로 조합합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 Flex 실험 9개를 하나의 responsive toolbar·card·center layout 진단 lab으로 통합하기",
    scenario: "direction/reverse, wrap, justify, auto margin, align-items/content, center, gap 예제가 서로 분리되어 실제 page에서 item이 왜 줄고 넘치는지 설명하기 어렵습니다. sizing 수치와 접근성까지 한 lab으로 재구성합니다.",
    setup: ["원본 ex12~20 file을 read-only evidence로 준비합니다.", "DevTools Flex overlay·Computed·Performance, 320~1200px, keyboard/RTL/zoom 환경을 준비합니다.", "short/long/URL/image/empty/1~10 item fixture를 준비합니다."],
    steps: [
      "각 container의 main/cross axis, direction, wrap, line 수와 DOM/visual order를 표로 만듭니다.",
      "item outer base size와 container inner size/gap을 계산해 line break를 prediction합니다.",
      "flex shorthand를 grow/shrink/basis로 펼치고 positive/negative free-space target size를 계산합니다.",
      "long item overflow를 automatic min-size 관점에서 재현해 min-inline-size:0과 content overflow policy로 수정합니다.",
      "justify-content와 main auto margin, align-items/self와 multi-line align-content를 각각 격리 test합니다.",
      "toolbar/card/center pattern을 responsive container query와 gap/logical margin으로 구현합니다.",
      "row-reverse/order를 제거하고 DOM·visual·Tab/reading order를 일치시킵니다.",
      "320px·RTL·200/400% zoom·long content·missing image·many items에서 geometry/overflow/focus를 자동화합니다.",
    ],
    expectedResult: ["모든 Flex property가 어느 axis·item/line·algorithm 단계에 적용되는지 설명됩니다.", "grow/shrink/min/max/gap 결과가 prediction과 geometry output에 일치합니다.", "long content에서도 page horizontal overflow 없이 item policy가 유지됩니다.", "single/multi-line alignment property를 혼동하지 않습니다.", "toolbar/card/center가 viewport/content 변화에 자연스럽게 wrap/reflow합니다.", "DOM·visual·focus·screen reader order가 일치하고 reverse/order로 의미를 바꾸지 않습니다."],
    cleanup: ["실험용 fixed width/height·inline style·float·order/reverse·overflow clip을 제거합니다.", "DevTools overlay/RTL/zoom을 reset하고 clean default 환경에서 regression을 다시 실행합니다."],
    extensions: ["같은 card layout을 Grid auto-fit/minmax로 구현해 last-line/track alignment를 비교합니다.", "flex shrink factor가 다른 300/200/100px basis item의 scaled shrink를 손 계산하고 subpixel rounding과 대조합니다.", "Playwright로 DOM/visual/focus order와 width/gap/overflow matrix를 CI에 추가합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 direction/wrap/justify/align 예제의 axis와 line을 그려 실제 item 좌표를 예측하세요.", requirements: ["row/row-reverse/column/column-reverse와 LTR/RTL을 포함합니다.", "nowrap/wrap에서 line count를 계산합니다.", "justify와 align-items가 움직이는 axis를 표시합니다.", "bounding rect/DevTools overlay와 prediction을 비교합니다."], hints: ["justify=horizontal이라는 암기를 버립니다.", "item outer width에 padding/margin을 포함합니다."], expectedOutcome: "각 mode의 visual placement와 DOM/focus order를 정확히 설명합니다.", solutionOutline: ["writing mode→main/cross→line→free space→alignment 순서로 그립니다.", "한 property씩 격리합니다."] },
    { difficulty: "응용", prompt: "long content toolbar와 responsive card row의 flex sizing/overflow를 해결하세요.", requirements: ["각 item flex shorthand와 min-size policy를 문서화합니다.", "auto margin group divider와 gap을 사용합니다.", "long URL/image/label·320px·RTL·zoom을 test합니다.", "last-line card growth를 의도적으로 선택하거나 Grid로 전환합니다.", "DOM/Tab order를 visual과 일치시킵니다."], hints: ["min-inline-size:0만 넣고 content를 숨기지 않습니다.", "각 line은 free space를 독립 분배합니다."], expectedOutcome: "toolbar action과 card content가 손실 없이 wrap/scroll하고 item size 계산이 예측 가능합니다.", solutionOutline: ["base/min-content/free-space 표를 만듭니다.", "component별 grow/shrink/overflow owner를 정합니다."] },
    { difficulty: "설계", prompt: "design system의 Stack·Inline·Cluster·Toolbar·Center·MediaObject Flex primitives를 설계하세요.", requirements: ["axis/wrap/gap/alignment/shorthand API와 default min-size를 정의합니다.", "order/reverse 접근성 제한과 RTL/logical behavior를 명시합니다.", "intrinsic content/replaced media/scroll region contract를 포함합니다.", "Flex vs Grid 선택 기준과 container query interop을 설명합니다.", "geometry/overflow/order/keyboard/zoom/performance test를 설계합니다."], hints: ["property pass-through만 제공하면 invalid 조합이 늘어납니다.", "primitive마다 item sizing responsibility를 문서화합니다."], expectedOutcome: "팀이 ad-hoc flex recipe 없이 예측 가능한 one-dimensional layout primitive를 재사용할 수 있습니다.", solutionOutline: ["사용자 task와 content variation에서 primitive invariant를 도출합니다.", "invalid combination과 escape hatch를 제한합니다."] },
  ],
  reviewQuestions: [
    { question: "display:flex를 주면 모든 descendant가 flex item인가요?", answer: "아닙니다. in-flow direct child가 flex item이며 grandchild는 해당 child 내부 formatting context를 따릅니다." },
    { question: "justify-content는 가로, align-items는 세로 정렬인가요?", answer: "항상 아닙니다. justify-content는 main axis, align-items는 cross axis이며 flex-direction/writing mode에 따라 physical 방향이 바뀝니다." },
    { question: "row-reverse는 DOM과 Tab 순서도 바꾸나요?", answer: "아닙니다. visual placement만 바꾸므로 의미 순서에는 사용하지 않습니다." },
    { question: "flex:1은 정확히 무엇을 뜻하나요?", answer: "흔히 grow 1, shrink 1, zero 계열 basis로 해석되어 available free space를 나누지만 shorthand expansion과 min-size/content를 함께 확인합니다." },
    { question: "flex-shrink:1인데 item이 왜 넘치나요?", answer: "automatic min-size/min-content·replaced intrinsic size가 더 줄어드는 것을 막을 수 있습니다. min-inline-size:0과 content policy를 검토합니다." },
    { question: "justify-content가 안 보이는 이유는 무엇인가요?", answer: "grow나 auto margin이 positive free space를 이미 소비했거나 item이 line을 채워 분배할 공간이 없을 수 있습니다." },
    { question: "align-content는 item 하나를 중앙에 놓나요?", answer: "아닙니다. 여러 flex line 집합을 cross axis extra space에 배치하며 single line에는 효과가 없습니다." },
    { question: "gap과 margin은 같은가요?", answer: "아닙니다. gap은 item/line 사이 gutter이고 outer edge 공간을 만들지 않으며 margin은 item box에 속하고 auto margin은 alignment에도 참여합니다." },
    { question: "Flexbox와 Grid 중 무엇이 더 최신인가요?", answer: "최신/구식 관계가 아니라 Flex는 주로 one-dimensional flow/space negotiation, Grid는 2차원 track alignment에 적합합니다." },
  ],
  completionChecklist: [
    "flex container/item과 main/cross axis를 writing mode·direction·flex-direction에서 그렸다.",
    "wrap line 수와 item outer hypothetical size/gap을 계산했다.",
    "flex shorthand를 grow/shrink/basis로 펼치고 positive/negative free space를 계산했다.",
    "automatic min-size/min-content/replaced media overflow를 min-size와 content policy로 해결했다.",
    "justify-content·auto margin·gap의 main-axis space 소비 순서를 확인했다.",
    "align-items/self와 multi-line align-content·baseline·stretch 조건을 구분했다.",
    "reverse/order로 의미 순서를 바꾸지 않고 DOM·visual·focus order를 일치시켰다.",
    "320px·RTL·zoom·long/empty/many content에서 geometry·overflow·accessibility를 검증했다.",
  ],
  nextSessions: ["css-10-responsive-layout-capstone"],
  sources: [
    { id: "web-flex-direction-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex12_flex.html", usedFor: ["flex container/item", "row/reverse/column", "axis", "box sizing"], evidence: "네 direction container와 fixed item dimensions를 DOM/visual order·writing mode example로 확장했습니다." },
    { id: "web-flex-wrap-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex13_flex.html", usedFor: ["nowrap/wrap/wrap-reverse", "six item lines", "direction"], evidence: "700px six-box wrap 실험을 line collection·min-content/overflow 계산으로 보강했습니다." },
    { id: "web-flex-justify-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex14_flex.html", usedFor: ["justify start/end/center", "space-between/around/evenly", "overlapping rule source order"], evidence: "여섯 justify modes와 opt id 중복 declaration을 main-axis free-space/cascade 설명에 사용했습니다." },
    { id: "web-flex-auto-margin-end-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex15_flex.html", usedFor: ["margin-right auto", "group separation", "justify interaction"], evidence: "box2 end auto margin을 logical auto-margin free-space absorption으로 교정했습니다." },
    { id: "web-flex-auto-margin-start-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex16_flex.html", usedFor: ["margin-left auto", "toolbar group", "main start"], evidence: "box2 start auto margin을 direction-safe logical toolbar pattern으로 확장했습니다." },
    { id: "web-flex-align-items-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex17_flex.html", usedFor: ["align-items", "start/end/center/baseline/stretch", "cross axis"], evidence: "150px five-mode example을 cross-size auto/fixed·baseline·line item alignment로 보강했습니다." },
    { id: "web-flex-align-content-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex18_flex.html", usedFor: ["multi-line align-content", "space distribution", "wrap", "container cross size"], evidence: "300px wrapped containers의 일곱 align-content modes를 line-set geometry example으로 사용했습니다." },
    { id: "web-flex-center-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex19_flex.html", usedFor: ["viewport center", "justify+align", "100vh", "button"], evidence: "body flex center recipe를 dynamic viewport·content overflow·Grid alternative와 연결했습니다." },
    { id: "web-flex-gap-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex20_flex.html", usedFor: ["gap", "align-items center", "fixed item width", "margin non-collapse"], evidence: "650px five-item gap example을 item/gutter/free-space calculation의 근거로 사용했습니다." },
    { id: "css-flexbox-1", repository: "W3C CSS Working Group", path: "TR/css-flexbox-1/", publicUrl: "https://www.w3.org/TR/css-flexbox-1/", usedFor: ["flex box model", "axis/line", "flex shorthand/basis", "layout algorithm", "automatic min-size", "order accessibility"], evidence: "2026-07-12 기준 Flexbox Level 1의 current CRD algorithm과 min-size/order guidance를 sizing mental model의 기준으로 확인했습니다." },
    { id: "css-align-3", repository: "W3C CSS Working Group", path: "TR/css-align-3/", publicUrl: "https://www.w3.org/TR/css-align-3/", usedFor: ["justify/align", "content/item/self", "gap", "safe overflow alignment", "baseline"], evidence: "Box Alignment Level 3의 abstract axes·distribution·gap 정의를 alignment 조건 설명에 반영했습니다." },
  ],
  sourceCoverage: {
    filesRead: 9,
    filesUsed: 9,
    uncoveredNotes: [
      "원본은 Flexbox Level 1의 주요 container alignment property를 연속적으로 모두 실습합니다. grow/shrink/base/min-size algorithm, DOM/focus order, writing mode, intrinsic overflow는 current W3C spec으로 전문가 수준까지 보강했습니다.",
      "Grid track/subgrid와 CSS Anchor/advanced fragmentation은 별도 layout/overlay 심화에서 다루며 다음 css-10에서는 실제 team/card page 회귀로 통합합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
