import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-03-combinators-attributes-pseudo"],
  slug: "css-03-combinators-attributes-pseudo",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 3,
  title: "관계·속성·상태·가상요소 선택자",
  subtitle: "DOM의 부모·자식·형제 관계, attribute token/value, 사용자 interaction state와 generated box를 정확히 선택하고 keyboard·privacy·접근성·성능 경계를 함께 검증합니다.",
  level: "중급",
  estimatedMinutes: 205,
  coreQuestion: "component DOM과 사용자 상태를 과도한 class나 JavaScript 없이 표현하면서도 구조 변화·keyboard·privacy·보조기술에 견고한 selector를 어떻게 고를까요?",
  summary: "원본의 child/descendant, nested list, nth-of-type, attribute prefix/contains/suffix, link/hover/active/focus, first/last/nth/not, ::before/after/first-letter/line/marker/selection/placeholder를 모두 재검증합니다. >·space·+·~, `[attr]`의 7개 연산·i/s flag, :focus-visible/:focus-within, form state, An+B와 `of S`, :has()까지 actual match count와 computed output으로 확인합니다. 방문 이력 privacy 제한, hover-only 기능, first-child/of-type 혼동, substring URL 오탐, generated content에 의미를 숨기는 오류, placeholder/selection 지원 범위를 진단하고 component DOM 계약과 progressive enhancement를 설계합니다.",
  objectives: [
    "descendant·child·adjacent sibling·subsequent sibling combinator가 요구하는 DOM 관계를 정확히 그릴 수 있다.",
    "attribute 존재·정확값·token·hyphen-prefix·prefix·suffix·substring과 case flag를 data 의미에 맞게 선택할 수 있다.",
    ":hover·:active·:focus·:focus-visible·:focus-within과 form/link state를 input modality·privacy 관점에서 설계할 수 있다.",
    ":first-child·:first-of-type·:nth-child(An+B of S) 차이를 sibling list에서 계산할 수 있다.",
    ":not·:is·:where·:has의 matching·specificity·support·style invalidation tradeoff를 설명할 수 있다.",
    "::before/after/marker/placeholder/selection/first-line/first-letter를 장식·typography에 쓰되 핵심 의미·interaction을 DOM에 유지할 수 있다.",
  ],
  prerequisites: [
    { title: "전체·타입·class·id 선택자와 명시도", reason: "simple/compound/complex selector와 specificity tuple을 바탕으로 관계·상태·pseudo-element를 결합합니다.", sessionSlug: "css-02-basic-selectors-specificity" },
  ],
  keywords: ["combinator", "descendant", "child", "sibling", "attribute selector", "pseudo-class", "focus-visible", "nth-child", ":has", "pseudo-element", "generated content", "marker", "selection"],
  chapters: [
    {
      id: "dom-relationship-combinators",
      title: "combinator는 두 compound selector 사이의 DOM 관계를 요구합니다",
      lead: "공백·>·+·~는 보기 좋은 구분자가 아니라 descendant·direct child·바로 다음 sibling·뒤 sibling 관계를 각각 표현합니다.",
      explanations: [
        "원본 .a > p는 class a element의 direct child p만 선택하므로 span 안 손자 p는 제외합니다. .b p는 깊이에 상관없이 b descendant인 모든 p를 선택합니다. wrapper를 추가할 가능성이 있는 component인지 direct child contract가 중요한지에 따라 고릅니다.",
        "E + F는 같은 parent를 공유하면서 E 바로 뒤에 오는 F 하나를, E ~ F는 E 뒤의 모든 matching F sibling을 선택합니다. label+input처럼 실제 DOM 순서가 안정적인 인접 element에 유용하지만 error/help wrapper가 끼면 + match가 끊길 수 있습니다.",
        "combinator는 specificity를 더하지 않지만 양쪽 simple selector는 모두 기여합니다. .panel > p.note는 class 두 개와 type 하나로 (0,2,1)입니다. 관계가 길어질수록 specificity뿐 아니라 DOM coupling이 증가합니다.",
        "#c > li는 top-level menu item만 style하고 nested ol/ul의 li는 제외합니다. 단순 li rule은 모든 깊이에 cascade되어 nested item도 green이 될 수 있습니다. inheritance와 direct match를 DevTools에서 구분합니다.",
        "DOM은 source indentation이 아니라 parser가 만든 tree입니다. invalid list/table markup이 parser recovery로 이동되면 눈으로 예상한 relationship selector가 match하지 않을 수 있으므로 Elements tree와 matches를 확인합니다.",
      ],
      concepts: [
        { term: "descendant combinator", definition: "A B에서 B가 A 안 임의 깊이의 descendant일 것을 요구하는 whitespace combinator입니다.", detail: ["중간 wrapper 수와 무관합니다.", "component 밖까지 깊게 퍼지지 않게 boundary를 둡니다."] },
        { term: "child combinator", definition: "A > B에서 B의 parent가 정확히 A일 것을 요구합니다.", detail: ["top-level item과 nested item을 구분합니다.", "wrapper refactor에 민감합니다."] },
        { term: "sibling combinator", definition: "A + B는 바로 다음, A ~ B는 뒤의 matching sibling을 선택합니다.", detail: ["같은 parent가 필요합니다.", "DOM source order를 따릅니다."] },
      ],
      codeExamples: [
        {
          id: "combinator-match-count",
          title: "direct child·descendant·adjacent·subsequent sibling match 수 확인",
          language: "html",
          filename: "combinators.html",
          purpose: "원본의 nested paragraph/list 관계를 네 combinator의 exact query count로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>관계 선택자</title><style>.panel > p { border-inline-start: 3px solid navy; } .panel p { padding-inline-start: .25rem; } .panel h1 + p { font-weight: 700; } .panel h1 ~ p { color: #333; }</style></head>\n<body>\n  <section class=\"panel\">\n    <h1>관계 실험</h1>\n    <p class=\"note\">직계 문단 A</p>\n    <div class=\"group\"><p class=\"note\">손자 문단 B</p></div>\n    <p>직계 문단 C</p>\n    <p>직계 문단 D</p>\n  </section>\n  <pre id=\"result\"></pre>\n  <script>\n    const selectors = [\n      '.panel > p',\n      '.panel p',\n      '.panel h1 + p',\n      '.panel h1 ~ p'\n    ];\n    document.querySelector('#result').textContent = selectors\n      .map((selector) => `${selector}=${document.querySelectorAll(selector).length}`)\n      .join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-11", explanation: "panel 아래 h1, direct p 세 개와 group 안 nested p 하나를 의도적으로 배치합니다." },
            { lines: "15-20", explanation: "네 relationship selector를 같은 querySelectorAll API로 평가합니다." },
            { lines: "21-23", explanation: "selector text와 match count를 안정적인 한 줄씩 출력합니다." },
          ],
          run: { environment: ["현대 browser"], command: "browser에서 combinators.html을 열고 결과 확인" },
          output: { value: ".panel > p=3\n.panel p=4\n.panel h1 + p=1\n.panel h1 ~ p=3", explanation: ["child는 direct A/C/D 세 p, descendant는 nested B까지 네 p입니다.", "adjacent +는 h1 바로 다음 A 하나입니다.", "subsequent ~는 h1 뒤 같은 parent의 A/C/D 세 p이며 div 안 B는 sibling이 아닙니다."] },
          experiments: [
            { change: "h1과 첫 p 사이에 div를 추가합니다.", prediction: "h1 + p는 0, h1 ~ p는 여전히 뒤 direct p 세 개를 match합니다.", result: "+는 바로 인접해야 하고 ~는 중간 sibling을 허용합니다." },
            { change: "group div를 제거하고 B p를 panel direct child로 옮깁니다.", prediction: "child/descendant/~ count가 각각 4가 됩니다.", result: "visual indentation이 아니라 실제 parent/sibling tree가 기준입니다." },
            { change: "selector를 '.panel > .group > p'로 추가합니다.", prediction: "손자 B 하나만 match합니다.", result: "여러 child combinator는 explicit DOM contract가 됩니다." },
          ],
          sourceRefs: ["web-combinator-source", "selectors-4"],
        },
      ],
      diagnostics: [
        { symptom: ".menu > li style이 nested item에도 보이는 것처럼 보인다.", likelyCause: "color 같은 inherited property가 top-level li에서 descendant로 전달되거나 nested li에 별도 broad rule이 match했습니다.", checks: ["nested li의 Styles에서 direct matched rule과 inherited section을 구분합니다.", "nested item에 color를 명시해 inheritance를 test합니다.", "li broad rule과 selector order를 확인합니다."], fix: "top-level/nested item에 명시적 component class 또는 scoped selector를 주고 inherited property 의도를 문서화합니다.", prevention: "nested menu fixture의 top/nested computed style을 별도 assertion합니다." },
      ],
    },
    {
      id: "attribute-selector-operators",
      title: "attribute selector는 DOM attribute의 존재·정확값·token·문자열 조각을 구분합니다",
      lead: "substring 연산자는 편리하지만 URL·state의 의미를 추론하는 데 쓰면 오탐과 보안 오해를 만들 수 있습니다.",
      explanations: [
        "[disabled]는 attribute 존재, [type='password']는 정확값을 match합니다. [class~='card']의 ~=는 whitespace-separated token 하나, [lang|='ko']의 |=는 ko 또는 ko-로 시작하는 language subtag pattern에 적합합니다.",
        "[href^='mailto:']는 prefix, [href$='.pdf']는 suffix, [href*='daum']은 arbitrary substring입니다. 원본 a[href$='com']은 mailto address가 .com으로 끝나도 match하고 query string 끝에 com이 있어도 match할 수 있어 domain 판정으로 부정확합니다.",
        "URL의 origin/hostname/path semantics를 CSS substring으로 보안 판단하지 않습니다. external link 표시가 필요하면 server/template가 rel/data-external class를 부여하거나 URL parser로 state를 만들고 CSS는 그 state를 표현합니다.",
        "attribute value case sensitivity는 document language/property semantics에 따릅니다. `[data-state='open' i]`의 i는 ASCII case-insensitive, s는 case-sensitive matching을 명시합니다. 지원과 실제 data contract를 확인하고 value normalization을 우선합니다.",
        "attribute selector는 class와 같은 B specificity column에 1을 더합니다. `[aria-current='page']`, `[data-variant='danger']`, `:disabled`는 state/variant hook으로 유용하지만 ARIA attribute를 visual style만 위해 거짓으로 설정하지 않습니다. semantic state가 실제 behavior와 동기화되어야 합니다.",
      ],
      concepts: [
        { term: "attribute presence selector", definition: "[attr]처럼 attribute가 존재하는 element를 value와 무관하게 match합니다.", detail: ["boolean HTML attribute에 유용합니다.", "attr='false'도 attribute는 존재하므로 [attr]가 match할 수 있습니다."] },
        { term: "token selector", definition: "[attr~='token']처럼 whitespace-separated token list에 정확한 token이 있는지 match합니다.", detail: ["class·rel 같은 tokenized value에 적합합니다.", "substring보다 경계를 보존합니다."] },
        { term: "substring selector", definition: "^=·$=·*=로 attribute 문자열의 시작·끝·포함을 match하는 selector입니다.", detail: ["문자열 패턴일 뿐 URL/domain parsing이 아닙니다.", "오탐과 escaping을 test합니다."] },
      ],
      codeExamples: [
        {
          id: "attribute-selector-matrix",
          title: "attribute 연산자의 match 차이와 URL substring 오탐",
          language: "html",
          filename: "attributes.html",
          purpose: "원본 mailto/domain/input type selector를 안전한 token/state 예제로 확장하고 exact match count를 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>속성 선택자</title><style>[rel~=\"external\"] { text-decoration: underline; } [data-state=\"open\" i] { font-weight: 700; } input[type=\"password\"][required] { border: 2px solid firebrick; }</style></head>\n<body>\n  <a href=\"mailto:student@example.com\" rel=\"contact external\">메일 문의</a>\n  <a href=\"https://example.com/course\" rel=\"external help\">외부 도움말</a>\n  <a href=\"/redirect?next=daum.example\" rel=\"help\">내부 redirect</a>\n  <button data-state=\"OPEN\" aria-expanded=\"true\">목차</button>\n  <input type=\"password\" required>\n  <pre id=\"result\"></pre>\n  <script>\n    const selectors = [\n      '[href^=\"mailto:\"]',\n      '[href*=\"daum\"]',\n      '[rel~=\"external\"]',\n      '[data-state=\"open\" i]',\n      'input[type=\"password\"][required]'\n    ];\n    document.querySelector('#result').textContent = selectors\n      .map((s) => `${s}=${document.querySelectorAll(s).length}`).join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-7", explanation: "mailto/external/redirect URL과 rel token을 분리해 substring과 token matching 차이를 드러냅니다." },
            { lines: "8-9", explanation: "case가 다른 data state와 두 attribute를 동시에 가진 password input을 준비합니다." },
            { lines: "13-19", explanation: "prefix, substring, token, case-insensitive exact, compound attribute selector를 같은 방식으로 셉니다." },
          ],
          run: { environment: ["Selectors Level 4 attribute flag 지원 browser"], command: "browser에서 attributes.html을 열고 결과 확인" },
          output: { value: "[href^=\"mailto:\"]=1\n[href*=\"daum\"]=1\n[rel~=\"external\"]=2\n[data-state=\"open\" i]=1\ninput[type=\"password\"][required]=1", explanation: ["daum substring 하나는 외부 daum site가 아니라 내부 redirect query이므로 의미 추론 오탐입니다.", "rel~=external은 token 경계를 지켜 두 link를 정확히 match합니다.", "i flag가 OPEN과 open을 ASCII case-insensitive하게 match합니다."] },
          experiments: [
            { change: "메일 link rel을 'contact-external'로 바꿉니다.", prediction: "[rel~=external] count는 1이 됩니다.", result: "~=는 hyphen substring이 아니라 whitespace token을 match합니다." },
            { change: "i flag를 제거합니다.", prediction: "data-state exact lowercase selector는 OPEN을 match하지 않아 count 0이 됩니다.", result: "attribute value case contract를 명시합니다." },
            { change: "href*=daum 결과에 external icon을 붙입니다.", prediction: "내부 redirect가 외부 link로 잘못 표시됩니다.", result: "CSS 문자열 selector를 URL security/semantics parser로 사용하지 않습니다." },
          ],
          sourceRefs: ["web-attribute-selector-source", "selectors-4"],
        },
      ],
      diagnostics: [
        { symptom: "[disabled='false']인 button도 흐리게 보이거나 동작이 비활성처럼 혼란스럽다.", likelyCause: "HTML boolean attribute는 문자열 false가 아니라 존재 자체가 true state이고 [disabled]도 match합니다.", checks: ["button.disabled property와 attribute 존재를 확인합니다.", "aria-disabled와 native disabled를 구분합니다.", "form submission/focus behavior를 test합니다."], fix: "활성 상태에서는 disabled attribute를 완전히 제거하고 native disabled behavior를 사용합니다.", prevention: "boolean attribute renderer가 false에서 attribute를 omit하는지 component test합니다." },
      ],
    },
    {
      id: "interaction-state-pseudo-classes",
      title: "interaction pseudo-class는 mouse·keyboard·touch·history에서 서로 다른 순간을 표현합니다",
      lead: "hover 하나에 기능을 숨기지 않고 focus-visible과 native state를 함께 설계해 모든 input modality에서 같은 task를 완료하게 합니다.",
      explanations: [
        ":link는 방문하지 않은 hyperlink, :visited는 방문한 link를 나타내지만 history sniffing을 막기 위해 적용 가능한 property와 script-observable computed style에 privacy 제한이 있습니다. visited state에 icon/content/display를 바꿔 sensitive history를 노출하지 않습니다.",
        ":hover는 pointing device가 가리킬 때, :active는 activation 중, :focus는 focus된 element, :focus-visible은 user agent가 focus indicator가 필요하다고 판단한 focus입니다. keyboard focus를 hover와 같은 visual importance로 제공하고 outline을 제거하지 않습니다.",
        ":focus-within은 element 자신 또는 descendant가 focus될 때 parent group을 강조합니다. form field wrapper·menu group에서 JavaScript class 없이 유용합니다. :focus-visible 지원/fallback과 high-contrast mode를 test합니다.",
        "touch device에는 persistent hover가 없거나 tap으로 hover가 남을 수 있습니다. tooltip·submenu·필수 설명을 hover에서만 제공하지 않고 focus/click/native disclosure와 visible text를 사용합니다. `(hover: hover)` media feature는 capability enhancement에 활용할 수 있습니다.",
        ":disabled/:enabled, :checked, :required/:optional, :valid/:invalid, :in-range/:out-of-range는 native form state를 match합니다. page load부터 빈 required field를 invalid red로 표시하기보다 submitted/touched state와 accessible error text를 함께 관리합니다.",
      ],
      concepts: [
        { term: ":focus-visible", definition: "현재 focus가 사용자에게 indicator로 보일 필요가 있다고 user agent heuristic이 판단할 때 match하는 pseudo-class입니다.", detail: ["keyboard focus outline에 적합합니다.", "focus 자체와 완전히 같은 것은 아닙니다."] },
        { term: ":focus-within", definition: "element 자신 또는 descendant가 focus를 가질 때 match합니다.", detail: ["field/card/group boundary를 강조합니다.", "DOM focus state를 그대로 반영합니다."] },
        { term: ":visited privacy", definition: "방문 이력 노출을 막기 위해 visited style과 script observation을 browser가 제한하는 보안 model입니다.", detail: ["색 계열 등 제한된 style만 기대합니다.", "getComputedStyle로 history를 판별하려 하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "keyboard-state-card",
          title: "hover·focus-visible·focus-within·invalid를 함께 제공하는 검색 form",
          language: "html",
          filename: "interaction-states.html",
          purpose: "mouse 없이도 focus가 보이고 field group·validation state를 CSS로 표현하되 error 의미는 DOM text에 유지합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>상태 선택자</title>\n  <style>\n    .field { padding: .75rem; border: 2px solid #aaa; }\n    .field:focus-within { border-color: #165a9e; background: #eef7ff; }\n    input:focus-visible, button:focus-visible { outline: 3px solid #a33b00; outline-offset: 3px; }\n    button:hover { background: #def; }\n    form.was-submitted input:invalid { border-color: #b00020; }\n    form:not(.was-submitted) .error { display: none; }\n  </style>\n</head>\n<body>\n  <main>\n    <h1>과정 검색</h1>\n    <form id=\"search\" novalidate>\n      <div class=\"field\">\n        <label for=\"query\">검색어</label>\n        <input id=\"query\" name=\"q\" required aria-describedby=\"query-error\">\n        <p id=\"query-error\" class=\"error\">검색어를 입력하세요.</p>\n      </div>\n      <button>검색</button>\n    </form>\n    <pre id=\"result\"></pre>\n  </main>\n  <script>\n    const form = document.querySelector('#search');\n    form.addEventListener('submit', (event) => {\n      event.preventDefault();\n      form.classList.add('was-submitted');\n      const input = document.querySelector('#query');\n      input.setAttribute('aria-invalid', String(!input.validity.valid));\n      if (!input.validity.valid) input.focus();\n      const field = document.querySelector('.field');\n      const error = document.querySelector('.error');\n      const inputStyle = getComputedStyle(input);\n      const fieldStyle = getComputedStyle(field);\n      document.querySelector('#result').textContent = [\n        `valid=${input.validity.valid}`,\n        `field-focus-within=${field.matches(':focus-within')}`,\n        `submitted=${form.classList.contains('was-submitted')}`,\n        `화면: 검색어를 입력하세요. ${getComputedStyle(error).display === 'none' ? '숨김' : '표시'}`,\n        `focus: ${document.activeElement === input ? '빈 검색어 input' : '다른 요소'}, ${inputStyle.outlineColor === 'rgb(163, 59, 0)' ? 'orange outline' : inputStyle.outlineColor}과 ${fieldStyle.borderTopColor === 'rgb(22, 90, 158)' ? 'blue field border' : fieldStyle.borderTopColor}`\n      ].join('\\n');\n    });\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-12", explanation: "group focus, keyboard focus, mouse hover, submitted invalid, pre-submit error visibility를 서로 다른 selector로 분리합니다." },
            { lines: "19-24", explanation: "visible label·required·DOM error text와 aria-describedby를 유지해 CSS generated content에 오류를 숨기지 않습니다." },
            { lines: "31-40", explanation: "submit state class를 추가하고 native ValidityState와 aria-invalid를 동기화한 뒤 exact state를 출력하고 invalid field에 focus합니다." },
          ],
          run: { environment: ["현대 browser", "keyboard"], command: "interaction-states.html을 열고 Tab으로 빈 검색 button까지 이동해 Enter" },
          output: { value: "valid=false\nfield-focus-within=true\nsubmitted=true\n화면: 검색어를 입력하세요. 표시\nfocus: 빈 검색어 input, orange outline과 blue field border", explanation: ["invalid input에 focus한 뒤 parent field가 :focus-within을 match합니다.", "was-submitted 뒤 invalid border와 error text가 나타납니다.", "실제 color perception만이 아니라 DOM error/aria-invalid가 의미를 전달합니다."] },
          experiments: [
            { change: "검색어에 CSS를 입력하고 다시 제출합니다.", prediction: "valid=true, aria-invalid=false이며 결과의 field-focus-within은 submit 시 focus 위치에 따라 true일 수 있습니다.", result: "state는 DOM focus와 value timing에 따라 동적으로 재평가됩니다." },
            { change: "focus-visible rule을 outline:none으로 바꿉니다.", prediction: "keyboard 사용자가 current focus를 찾기 어렵습니다.", result: "focus indicator는 hover decoration이 아니라 navigation feedback입니다." },
            { change: "error p를 ::after content로만 교체합니다.", prediction: "보조기술·번역·복사·DOM test에서 오류 전달이 불안정해집니다.", result: "핵심 error는 DOM text와 programmatic relation으로 유지합니다." },
          ],
          sourceRefs: ["web-pseudo-class-source", "selectors-4", "wai-forms"],
        },
      ],
      diagnostics: [
        { symptom: "mouse hover에서는 submenu/tooltip을 볼 수 있지만 keyboard와 touch로 열 수 없다.", likelyCause: ":hover만 interaction trigger로 사용하고 focus/click/disclosure semantics를 구현하지 않았습니다.", checks: ["Tab/Enter/Space/Escape와 touch tap을 test합니다.", ":focus-within과 button aria-expanded를 확인합니다.", "hover capability media를 봅니다."], fix: "실제 button disclosure와 aria-expanded/hidden state를 구현하고 hover는 capable device의 추가 편의로만 사용합니다.", prevention: "mouse·keyboard·touch input modality matrix를 component acceptance criteria에 둡니다." },
      ],
    },
    {
      id: "structural-pseudo-classes",
      title: "child index와 type index는 다른 sibling list를 세며 An+B는 1부터 시작합니다",
      lead: "nth-child(2)가 두 번째 li라는 설명은 두 번째 child 자체가 li인 경우에만 맞습니다.",
      explanations: [
        ":first-child는 parent의 모든 element child 중 첫 번째인 element, p:first-of-type은 sibling 중 p type의 첫 번째를 match합니다. p 앞에 span이 있으면 p:first-child는 false지만 p:first-of-type은 true일 수 있습니다.",
        ":nth-child(2)는 전체 element siblings에서 두 번째 position, p:nth-of-type(2)는 p siblings만 세어 두 번째 p입니다. text/comment node는 element child index에 포함되지 않지만 다른 element type은 포함됩니다.",
        "An+B는 1-indexed이고 n은 0 이상 정수입니다. 2n은 even, 2n+1은 odd, -n+3은 첫 세 개, n+4는 네 번째부터를 나타냅니다. 시각 row stripe는 DOM hidden/filter/reorder와 일치하는지 확인합니다.",
        ":nth-child(2n of .visible)는 matching sibling subset을 먼저 만들고 그중 짝수 position을 선택합니다. display:none은 selector match set에서 자동 제외되지 않으므로 명시적 state selector가 필요할 수 있습니다.",
        ":only-child, :empty도 유용하지만 :empty는 element/text node content에 민감하고 whitespace behavior/spec evolution을 확인합니다. 빈 상태 UI를 CSS만으로 결정하기보다 async data state를 명시하는 것이 견고할 수 있습니다.",
      ],
      concepts: [
        { term: ":nth-child()", definition: "parent의 element child 목록 또는 of selector로 필터한 목록에서 An+B position인 element를 match합니다.", detail: ["1-indexed입니다.", "element type을 자동 구분하지 않습니다."] },
        { term: ":nth-of-type()", definition: "같은 expanded element name을 가진 sibling들 중 An+B position을 match합니다.", detail: ["다른 type sibling은 count에서 제외합니다.", "class subset은 nth-child(... of S)를 고려합니다."] },
        { term: "An+B", definition: "non-negative n에 대해 A×n+B로 선택 position 집합을 표현하는 CSS microsyntax입니다.", detail: ["odd/even keyword가 있습니다.", "-n+k로 처음 k개를 선택할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "첫 paragraph에 first-child style이 적용될 것으로 예상했지만 앞 heading 때문에 적용되지 않는다.", likelyCause: "p:first-child를 '첫 p'로 오해했습니다. p는 첫 element child가 아닙니다.", checks: ["parent의 모든 element child 순서를 나열합니다.", "p:first-child와 p:first-of-type matches를 각각 실행합니다.", "정말 첫 child인지 첫 p인지 요구를 확인합니다."], fix: "첫 p가 목적이면 p:first-of-type 또는 component class를 사용하고 DOM 변화에 대한 contract를 test합니다.", prevention: "structural selector fixture에 다른 type sibling을 앞/중간에 추가한 case를 포함합니다." },
        { symptom: "필터로 숨긴 list에서 stripe 색이 visible row 기준으로 어긋난다.", likelyCause: "display:none item도 :nth-child index에서 sibling으로 남습니다.", checks: ["hidden item의 DOM/state와 selector match를 확인합니다.", "nth-child(... of :not([hidden])) 지원/selector를 검토합니다.", "virtual/filter rendering 방식과 accessibility를 확인합니다."], fix: "visible item만 DOM에 render하거나 명시적 state를 제외한 of selector/row class를 사용하고 fallback을 제공합니다.", prevention: "filter·sort·insert/delete 후 stripe와 reading order regression test를 둡니다." },
      ],
    },
    {
      id: "logical-functional-pseudo-classes",
      title: ":not·:is·:where·:has는 selector logic을 표현하지만 specificity와 invalidation 범위를 함께 설계합니다",
      lead: "JavaScript class 없이 parent state를 style할 수 있어도 복잡한 relational selector가 component contract를 숨기지 않게 합니다.",
      explanations: [
        ":not(.no)는 해당 argument를 match하지 않는 element를 선택합니다. `.not li:not(.no)`는 class no가 없는 li입니다. 여러 argument가 가능하지만 outer li 조건이 없으면 page의 훨씬 많은 element를 match할 수 있으므로 positive boundary를 유지합니다.",
        ":is(header, main, footer)와 :where(...)는 OR grouping을 간결하게 합니다. :where는 specificity 0, :is는 최고 argument specificity입니다. match logic은 비슷해도 public override contract는 다릅니다.",
        ":has(> input:invalid)는 direct child invalid input을 가진 field wrapper를 선택할 수 있고 `.card:has(.badge)`는 badge 존재에 따라 parent layout을 바꿉니다. 이전에는 JS parent class가 필요했던 relational condition을 CSS로 표현합니다.",
        ":has() argument는 relative selector이며 pseudo-element nesting 제한 등 syntax를 확인합니다. selector list invalidity가 progressive enhancement를 깨뜨릴 수 있어 @supports selector(:has(*))로 optional enhancement를 감쌀 수 있습니다.",
        "broad `body:has(...)`나 deep relational selector가 빈번한 DOM mutation에서 style invalidation 범위를 늘릴 수 있습니다. browser 구현은 최적화되지만 실제 application의 large DOM/performance를 측정하고 explicit state class가 더 명확한지 비교합니다.",
      ],
      concepts: [
        { term: "logical pseudo-class", definition: ":is·:not·:where처럼 selector argument의 논리 OR/NOT matching을 구성하는 functional pseudo-class입니다.", detail: ["specificity 규칙이 함수마다 다릅니다.", "positive component boundary와 함께 씁니다."] },
        { term: "relational pseudo-class", definition: ":has(relative-selector-list)처럼 anchor element와 관련된 descendant/child/sibling 존재 조건으로 anchor를 match하는 selector입니다.", detail: ["parent/previous element styling을 가능하게 합니다.", "support와 invalidation을 측정합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: ":not(.disabled) rule이 site 거의 모든 element에 적용돼 예상치 못한 color를 바꾼다.", likelyCause: "positive type/component boundary 없이 broad negation만 사용했습니다.", checks: ["querySelectorAll(':not(.disabled)').length를 확인합니다.", "selector rightmost subject와 intended component를 비교합니다.", "inheritance까지 확인합니다."], fix: ".button:not(.disabled) 또는 native button:enabled처럼 positive boundary/state semantic을 추가합니다.", prevention: "logical pseudo-class는 component root/type과 결합하고 match-count budget을 test합니다." },
        { symptom: ":has 기반 page가 old browser에서 entire rule을 잃거나 dynamic update가 느리다.", likelyCause: "support/fallback 없이 critical behavior를 :has에만 의존하거나 broad anchor로 큰 DOM을 재평가합니다.", checks: ["CSS.supports('selector(:has(*))')를 확인합니다.", "Performance에서 Recalculate Style을 측정합니다.", "critical task가 CSS 없이 가능한지 봅니다."], fix: "semantic DOM/native behavior baseline을 유지하고 @supports enhancement 또는 explicit state class로 범위를 좁힙니다.", prevention: "browser target과 large-DOM mutation performance fixture를 CI/monitoring에 둡니다." },
      ],
    },
    {
      id: "pseudo-elements-generated-boxes",
      title: "pseudo-element는 DOM element가 아니라 element 일부 또는 generated box를 style하는 추상 대상입니다",
      lead: "::before/after content는 장식에 사용하고 제품 이름·오류·NEW 상태 같은 핵심 의미를 CSS에만 숨기지 않습니다.",
      explanations: [
        "::before와 ::after는 originating element의 child처럼 생성되는 styleable pseudo-element이며 content가 none/normal이면 box가 생성되지 않을 수 있습니다. decorative underline·quote mark·icon background에 유용하지만 실제 DOM node가 아니므로 querySelector로 얻지 못합니다.",
        "원본 .badge::before { content:'NEW ' }는 화면에는 상태가 보이지만 CSS가 실패하거나 일부 보조기술/복사/번역에서 의미가 누락될 수 있습니다. 상품 신규 상태가 중요한 data면 DOM text 또는 accessible label/state에 넣고 pseudo-element는 배경·장식만 담당합니다.",
        "::marker는 list item marker를 제한된 property로 style하면서 ul/ol semantics를 유지합니다. list-style:none+generated bullet로 실제 marker를 재구현하기보다 native marker를 우선합니다.",
        "::placeholder는 placeholder text를 style하지만 placeholder는 label이 아닙니다. ::selection은 사용자가 선택한 text highlight를 style하며 selection color/background contrast를 모두 확인합니다. browser/user preference가 override할 수 있습니다.",
        "::first-line은 layout 결과의 첫 formatted line이라 viewport/font 변경 때 범위가 달라지고, ::first-letter는 language/punctuation/typographic unit 규칙을 따릅니다. source 첫 character를 단순 선택하는 것이 아닙니다. generated ::before content가 first-letter 대상에 영향을 줄 수도 있습니다.",
        "pseudo-element는 specificity의 C column에 type selector처럼 기여합니다. pseudo-class(:hover)와 pseudo-element(::before)의 colon·역할을 구분하고 legacy single-colon 호환에 의존하지 않습니다.",
      ],
      concepts: [
        { term: "pseudo-element", definition: "DOM에 실제 element로 존재하지 않지만 element의 특정 부분·generated content·marker 등을 style하도록 추상화한 selector 대상입니다.", detail: [":: 표기를 사용합니다.", "querySelector로 Element를 반환하지 않습니다."] },
        { term: "generated content", definition: "content property로 ::before/::after 등에 생성되는 text/image/counter content입니다.", detail: ["장식과 자동 numbering에 유용합니다.", "핵심 의미·interactive content를 맡기지 않습니다."] },
        { term: "originating element", definition: "pseudo-element가 연관되어 생성·style되는 실제 DOM element입니다.", detail: ["inheritance와 containing context를 제공합니다.", "pseudo-element lifecycle은 originating element에 의존합니다."] },
      ],
      codeExamples: [
        {
          id: "decorative-pseudo-semantic-state",
          title: "신규 상태는 DOM에, 장식 점과 underline은 pseudo-element에 두기",
          language: "html",
          filename: "pseudo-elements.html",
          purpose: "원본 badge/icon/underline 예제를 CSS 실패와 accessibility에도 의미가 남는 pattern으로 교정합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>가상 요소</title>\n  <style>\n    .product-title { position: relative; display: inline-block; padding-inline-start: 1rem; }\n    .product-title::before { content: ''; position: absolute; inline-size: .5rem; block-size: .5rem; border-radius: 50%; background: #b00020; inset-inline-start: 0; inset-block-start: .65em; }\n    .product-title::after { content: ''; display: block; block-size: .15rem; background: currentColor; transform: scaleX(.35); transform-origin: left; }\n    .status { margin-inline-start: .5rem; font-size: .75em; font-weight: 700; }\n    .items li::marker { color: #8a1743; font-size: 1.2em; }\n    ::selection { color: #fff; background: #51327a; }\n  </style>\n</head>\n<body>\n  <main>\n    <h1 class=\"product-title\">HTML 학습 카드 <span class=\"status\">신규</span></h1>\n    <ul class=\"items\"><li>문서 구조</li><li>선택자</li></ul>\n    <pre id=\"result\"></pre>\n  </main>\n  <script>\n    const title = document.querySelector('.product-title');\n    document.querySelector('#result').textContent = [\n      `dom-text=${JSON.stringify(title.textContent.trim().replace(/\\s+/g, ' '))}`,\n      `before=${getComputedStyle(title, '::before').content}`,\n      `after-display=${getComputedStyle(title, '::after').display}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-9", explanation: "before는 empty decorative dot, after는 empty underline box입니다. 핵심 text를 content property에 넣지 않습니다." },
            { lines: "10-12", explanation: "신규 DOM text style, native list marker, selection highlight를 각각 적절한 pseudo-element 범위로 처리합니다." },
            { lines: "16-17", explanation: "신규 상태는 실제 span text라 CSS가 없어도 document에 남습니다." },
            { lines: "21-26", explanation: "DOM text와 pseudo-element computed content/display를 분리해 exact output으로 증명합니다." },
          ],
          run: { environment: ["pseudo-element getComputedStyle를 지원하는 현대 browser"], command: "browser에서 pseudo-elements.html을 열고 결과 확인" },
          output: { value: "dom-text=\"HTML 학습 카드 신규\"\nbefore=\"\"\nafter-display=block", explanation: ["DOM text에는 신규가 있어 copy·translation·accessibility baseline에 남습니다.", "before content는 빈 문자열 장식이며 generated dot는 CSS box로 만듭니다.", "after underline은 block pseudo-element로 표시됩니다."] },
          experiments: [
            { change: "status span을 삭제하고 .product-title::before content를 'NEW '로 바꿉니다.", prediction: "화면에는 보일 수 있지만 dom-text에서 신규가 사라집니다.", result: "critical state를 CSS generated content에만 두지 않습니다." },
            { change: "stylesheet를 disable합니다.", prediction: "장식 dot/underline/marker color는 사라지지만 HTML 학습 카드 신규와 list content는 남습니다.", result: "progressive baseline과 장식 책임이 분리됩니다." },
            { change: "::before content에 '주의: '를 추가하고 ::first-letter style을 적용합니다.", prediction: "first-letter가 원래 H가 아니라 generated content의 첫 글자를 포함할 수 있습니다.", result: "generated content가 typography pseudo-element 범위에 영향을 줍니다." },
          ],
          sourceRefs: ["web-pseudo-element-source", "css-pseudo-4", "css-content-3"],
        },
      ],
      diagnostics: [
        { symptom: "NEW badge나 필수 표시가 화면에는 보이지만 CSS off·copy·translation·screen reader output에서 사라진다.", likelyCause: "핵심 상태 text를 ::before/after content에만 넣었습니다.", checks: ["element.textContent와 accessibility tree를 확인합니다.", "stylesheet를 disable하고 task를 수행합니다.", "generated content의 localization source를 확인합니다."], fix: "의미 있는 상태/label을 DOM text·ARIA/native attribute로 제공하고 pseudo-element는 시각 장식에 제한합니다.", prevention: "CSS-generated non-empty 문자열을 lint/report하고 content owner/accessibility review를 요구합니다." },
      ],
    },
    {
      id: "relational-has-progressive-performance",
      title: ":has()는 후손을 검사해 부모를 꾸미지만 범위·fallback·무효화 비용까지 설계해야 합니다",
      lead: "relational pseudo-class는 오래 필요했던 parent selection을 제공하지만 JavaScript state machine을 자동으로 대체하지 않으며, 좁은 component anchor와 검증 가능한 baseline이 핵심입니다.",
      explanations: [
        "`:has(relative-selector-list)`는 각 element를 anchor로 삼아 argument의 relative selector가 하나라도 성립하면 그 anchor를 match합니다. `.choice:has(> input:checked)`는 checked input 자체가 아니라 그 input을 direct child로 둔 choice를 선택합니다. 앞에서 배운 descendant와 child 관계가 argument 안에서도 그대로 적용되므로 DOM 계약을 먼저 그려야 합니다.",
        "`:has()`의 specificity는 argument 안에서 가장 높은 specificity로 대체됩니다. `.card:has(#danger:checked)`는 id가 섞여 override가 매우 어려워질 수 있습니다. 공개 component API에는 class·data state를 사용하고, 필요하면 `:where()`로 baseline specificity를 낮춘 뒤 cascade layer에서 override 순서를 관리합니다.",
        "지원하지 않는 browser에서 selector list 전체가 무효가 되는 시나리오를 고려합니다. 필수 기능은 native checked·disabled·details/summary 또는 JavaScript가 부여하는 명시적 state class로 먼저 동작하게 하고, `@supports selector(.choice:has(input:checked))` 안에서 parent highlight만 enhancement합니다. CSS 지원 여부가 submit·validation·disclosure의 동작 여부를 결정하면 안 됩니다.",
        "browser는 descendant mutation이 생길 때 어떤 ancestor의 `:has()` 결과가 달라지는지 다시 평가해야 합니다. `body:has(.error)`처럼 넓은 anchor와 deep descendant, universal selector를 결합하면 큰 문서에서 style invalidation 후보가 많아집니다. `.checkout-field:has(> input:user-invalid)`처럼 component boundary와 direct relationship을 좁히고 실제 Performance trace에서 Recalculate Style을 비교합니다.",
        "`:has()`는 security 검사기가 아닙니다. DOM에 `.admin`이나 `[data-secret]`가 있는지 감지해 화면만 숨겨도 data와 control은 이미 client에 전달되었습니다. authorization은 server/API에서 강제하고 CSS selector는 허가된 DOM의 표현만 맡습니다. DevTools에서 rule match, selector specificity, invalidation과 accessibility tree를 함께 확인합니다.",
      ],
      concepts: [
        { term: "relational pseudo-class", definition: "anchor element를 기준으로 relative selector가 성립하는지 검사해 anchor 자체를 match하는 pseudo-class입니다.", detail: ["`:has()`가 대표적입니다.", "argument의 관계는 anchor에서 출발합니다."] },
        { term: "progressive enhancement", definition: "지원 여부와 무관하게 핵심 task가 가능한 baseline 위에 최신 selector의 시각적 편의를 추가하는 전략입니다.", detail: ["`@supports selector(...)`로 enhancement를 격리합니다.", "native state와 semantic DOM을 baseline으로 둡니다."] },
        { term: "style invalidation", definition: "DOM·attribute·state 변경 뒤 어떤 element의 selector match와 computed style을 다시 계산할지 정하는 browser 작업입니다.", detail: ["anchor 범위가 넓을수록 후보가 늘 수 있습니다.", "추측 대신 실제 trace로 측정합니다."] },
      ],
      codeExamples: [
        {
          id: "has-checked-disabled-nth-of-proof",
          title: ":has checked·disabled parent와 `nth-child(of S)`의 실제 match 증명",
          language: "html",
          filename: "has-and-nth-of.html",
          purpose: "접근 가능한 native checkbox를 유지하면서 parent card enhancement와 filtered sibling index를 computed style·match count로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>관계형 선택자 검증</title>\n  <style>\n    .choice { display: block; border: 2px solid #777; padding: .5rem; }\n    .choice:has(> input:checked) { border: 4px solid #006400; background: honeydew; }\n    .choice:has(> input:disabled) { opacity: .55; }\n    .task-list > li:nth-child(2 of .active) { font-weight: 700; }\n  </style>\n</head>\n<body>\n  <main>\n    <h1>학습 과정 선택</h1>\n    <label class=\"choice\" id=\"selected-card\"><input type=\"checkbox\" checked> CSS 선택자</label>\n    <label class=\"choice\" id=\"disabled-card\"><input type=\"checkbox\" disabled> 준비 중 과정</label>\n    <ol class=\"task-list\"><li class=\"active\">첫 번째</li><li class=\"paused\">보류</li><li class=\"active\">세 번째</li></ol>\n    <pre id=\"result\"></pre>\n  </main>\n  <script>\n    const selected = document.querySelector('#selected-card');\n    const disabled = document.querySelector('#disabled-card');\n    const secondActive = document.querySelector('.task-list > li:nth-child(2 of .active)');\n    const selectedStyle = getComputedStyle(selected);\n    document.querySelector('#result').textContent = [\n      `checked-card=${selected.matches('.choice:has(> input:checked)')}`,\n      `disabled-card=${disabled.matches('.choice:has(> input:disabled)')}`,\n      `active-second-count=${document.querySelectorAll('.task-list > li:nth-child(2 of .active)').length}`,\n      `active-second-text=${secondActive.textContent}`,\n      `border=${selectedStyle.borderTopColor} ${selectedStyle.borderTopWidth}`,\n      `background=${selectedStyle.backgroundColor}`,\n      `opacity=${getComputedStyle(disabled).opacity}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-10", explanation: "baseline border와 parent `:has()` enhancement, disabled opacity, filtered sibling index를 서로 독립된 rule로 선언합니다." },
            { lines: "13-19", explanation: "visible label 안 native checkbox를 두고 active가 아닌 sibling을 끼워 DOM index와 filtered index를 구분합니다." },
            { lines: "22-26", explanation: "선택된 card·disabled card·두 번째 active item을 selector API로 직접 찾습니다." },
            { lines: "27-36", explanation: "matches·count·text와 실제 computed border/background/opacity를 직렬화해 screenshot 추측을 제거합니다." },
          ],
          run: { environment: ["Selectors Level 4 :has와 nth-child(of S)를 지원하는 현대 browser"], command: "browser에서 has-and-nth-of.html을 열고 결과 확인" },
          output: { value: "checked-card=true\ndisabled-card=true\nactive-second-count=1\nactive-second-text=세 번째\nborder=rgb(0, 100, 0) 4px\nbackground=rgb(240, 255, 240)\nopacity=0.55", explanation: ["checked input의 parent card만 4px dark-green border와 honeydew background를 얻습니다.", "disabled native control을 가진 두 번째 card는 opacity .55 enhancement를 얻지만 label과 disabled semantics는 DOM에 남습니다.", "`2 of .active`는 전체 세 번째 li이지만 active subset에서는 두 번째인 항목 하나를 고릅니다."] },
          experiments: [
            { change: "첫 checkbox의 checked attribute를 제거합니다.", prediction: "checked-card=false이고 baseline 2px gray border와 transparent background가 됩니다.", result: "`:has()` 결과는 descendant의 native state 변화에 따라 다시 계산됩니다." },
            { change: "`:has(> input:checked)`에서 `>`를 제거하고 nested wrapper 안에 input을 옮깁니다.", prediction: "descendant version은 계속 match하지만 direct-child version은 match하지 않습니다.", result: "relative selector 안 combinator도 component DOM contract입니다." },
            { change: "paused li에 active class를 추가합니다.", prediction: "두 번째 li가 active subset의 두 번째가 되어 bold target이 바뀝니다.", result: "`of S`는 먼저 S로 sibling set을 filter한 뒤 index를 계산합니다." },
          ],
          sourceRefs: ["web-structural-source", "selectors-4", "selectors-relational-has", "wai-forms"],
        },
      ],
      diagnostics: [
        { symptom: "checkbox를 바꿀 때 page 전체의 style recalculation이 커지고 scroll이 끊긴다.", likelyCause: "body 같은 광범위 anchor에 deep `:has()`를 여러 개 적용해 mutation마다 많은 ancestor 후보를 다시 평가합니다.", checks: ["Performance panel에서 interaction 전후 Recalculate Style duration과 affected node 수를 기록합니다.", "`:has()` rule을 disable해 baseline과 비교합니다.", "anchor를 component class와 direct child로 좁힌 variant를 측정합니다."], fix: "relational selector를 가장 가까운 component boundary로 제한하고 빈번한 cross-tree state는 owner가 data/class로 명시합니다.", prevention: "대표 large-DOM fixture에 selector invalidation budget과 interaction trace regression을 둡니다." },
      ],
    },
    {
      id: "form-state-accessibility-lifecycle",
      title: "form pseudo-class는 validation 수명주기와 접근 가능한 오류 전달을 함께 표현합니다",
      lead: "`:required`·`:disabled`·`:checked`·`:invalid`는 native state를 잘 보여 주지만, 언제 오류를 노출하고 사용자가 무엇을 고쳐야 하는지는 별도의 interaction 설계가 필요합니다.",
      explanations: [
        "`:enabled`와 `:disabled`는 해당 HTML element가 실제로 enable/disable semantics를 가질 때 match합니다. `aria-disabled='true'`는 native `:disabled`가 아니며 focus·click·form submission도 자동으로 막지 않습니다. 가능한 경우 native disabled를 사용하고, custom widget이면 behavior·ARIA·style을 같은 state owner에서 동기화합니다.",
        "`:checked`는 checkbox·radio·option의 선택 state를 표현합니다. label을 input과 연결하면 pointer target과 accessible name을 함께 얻습니다. 시각적으로 input을 감출 때 `display:none`으로 keyboard/accessibility tree에서 제거하지 말고, robust visually-hidden pattern과 high-contrast·zoom에서 focus indicator를 시험합니다.",
        "`:valid`와 `:invalid`는 constraint validation 결과이며 required field는 page load 직후에도 invalid일 수 있습니다. 사용자가 아직 입력하지 않았는데 모든 field를 빨갛게 만들면 오류인지 필수 표시인지 구분하기 어렵습니다. submit attempt·blur·`:user-invalid` 지원 정책을 정하고 DOM error text를 `aria-describedby`로 연결합니다.",
        "`:focus-visible`은 keyboard modality의 focus indicator를 보존하는 데 쓰되 `outline: none`을 global로 선언하지 않습니다. forced-colors mode에서는 author color가 조정될 수 있으므로 outline/border thickness와 system color fallback을 확인합니다. focus order는 CSS visual reorder가 아니라 DOM order와 interaction logic을 따라야 합니다.",
        "DevTools에서는 Elements의 Force state로 `:focus`, `:hover`, `:active`를 고정하고 Styles의 matched rule·Computed의 최종 outline을 확인합니다. 그러나 `:user-invalid`나 실제 keyboard heuristic은 강제 state만으로 충분하지 않으므로 Tab·submit·reset 시나리오를 실제로 수행하고 accessibility tree의 name/description/state도 기록합니다.",
      ],
      concepts: [
        { term: "constraint validation", definition: "required·type·pattern·min/max 같은 HTML 제약으로 form control의 validity를 계산하는 native mechanism입니다.", detail: ["`:valid`/`:invalid`가 결과를 표현합니다.", "오류 message와 노출 timing은 별도 설계가 필요합니다."] },
        { term: ":user-invalid", definition: "사용자 interaction 뒤 invalid로 판단된 control을 대상으로 하려는 user-action pseudo-class입니다.", detail: ["지원 범위를 확인합니다.", "server error와 native constraint error를 혼동하지 않습니다."] },
        { term: "accessible error", definition: "화면에 보이고 programmatic relation으로 control과 연결되며 수정 방법을 전달하는 오류 message입니다.", detail: ["색만으로 알리지 않습니다.", "focus 이동과 live announcement를 과도하게 만들지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "필수 form이 처음 열리자마자 전부 빨갛고 screen reader는 어떤 오류를 고칠지 설명하지 않는다.", likelyCause: "`:invalid` 색 rule만 사용하고 submit/touched lifecycle과 DOM error description을 만들지 않았습니다.", checks: ["load 전후 validity와 was-submitted state를 확인합니다.", "error text의 id와 aria-describedby 연결을 검사합니다.", "색을 제거하거나 forced-colors에서 의미가 남는지 확인합니다."], fix: "오류 노출 시점을 정의하고 visible error text·summary·focus policy를 추가하며 CSS는 그 authoritative state를 표현합니다.", prevention: "empty load·keyboard submit·server error·reset 시나리오를 접근성 통합 test로 유지합니다." },
      ],
    },
    {
      id: "generated-content-writing-modes-privacy-security",
      title: "pseudo-element는 writing mode와 privacy·security 경계 안에서 장식 box로 사용합니다",
      lead: "generated box는 DOM 없이 유연한 장식을 만들지만 의미·보안·레이아웃 방향을 대신하지 못하며, logical property와 CSS failure 기준으로 검토해야 합니다.",
      explanations: [
        "`::before`와 `::after`는 originating element의 formatting context에 참여하는 generated box입니다. badge·required text·버튼 이름을 `content`에만 넣으면 CSS download 실패, user stylesheet, translation, copy/paste, 일부 accessibility 조합에서 의미가 사라질 수 있습니다. 핵심 문자열은 HTML에 두고 empty pseudo-element로 dot·line·shape를 만듭니다.",
        "horizontal writing을 가정한 `left`, `right`, `border-left`는 `writing-mode: vertical-rl`이나 RTL locale에서 의도와 다른 쪽에 배치됩니다. `inset-inline-start`, `margin-inline`, `border-block-start` 같은 logical property를 사용하고 horizontal-tb/vertical-rl 및 ltr/rtl matrix에서 실제 containing block과 computed physical mapping을 확인합니다.",
        "`::marker`는 list semantics를 보존하면서 marker의 제한된 style을 꾸미는 데 적합합니다. list-style:none 뒤 decorative pseudo-element로 bullet을 재구현하면 high-contrast·zoom·wrapped line alignment와 semantics를 다시 해결해야 합니다. native list가 목적에 맞는지 먼저 판단합니다.",
        "`:visited`는 history sniffing을 막기 위해 허용 property와 computed-style observation이 제한됩니다. 방문 여부에 따라 `content`, display, size, URL icon을 바꾸거나 script가 pseudo-element style을 읽어 business logic을 결정해서는 안 됩니다. visited color도 다른 state와 충분한 contrast를 유지하는 단순한 affordance로만 씁니다.",
        "CSS는 secret masking이나 authorization layer가 아닙니다. `content: attr(data-token)`, DOM attribute 속 비밀, `display:none` admin control은 DevTools와 source에서 읽힙니다. 민감한 data는 client에 보내지 않고 server가 권한을 강제합니다. 성능 면에서는 수천 개 row의 heavy pseudo-element shadow/filter를 paint profile로 측정하고 reduced-motion·forced-colors fallback을 둡니다.",
      ],
      concepts: [
        { term: "originating element", definition: "pseudo-element가 생성되고 style·formatting context의 기준이 되는 실제 element입니다.", detail: ["pseudo-element는 DOM child와 동일하지 않습니다.", "positioning containing block을 명시적으로 확인합니다."] },
        { term: "logical property", definition: "left/right/top/bottom 대신 inline/block 축과 start/end를 기준으로 표현하는 CSS property입니다.", detail: ["writing mode와 direction에 적응합니다.", "computed physical mapping을 DevTools에서 확인합니다."] },
        { term: "history sniffing", definition: "visited style 차이를 관찰해 사용자의 browsing history를 추론하려는 privacy attack입니다.", detail: ["browser가 style/observation을 제한합니다.", "visited state를 logic source로 쓰지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "세로쓰기 또는 RTL에서 pseudo-element badge가 text를 덮고 반대쪽에 붙는다.", likelyCause: "absolute position을 left/top과 고정 physical margin으로 작성해 inline/block 축 변화를 무시했습니다.", checks: ["writing-mode와 direction을 각각 강제합니다.", "containing block과 inset computed physical value를 확인합니다.", "200% zoom과 줄바꿈에서 overlap을 검사합니다."], fix: "originating element를 명확한 containing block으로 만들고 logical inset/size/margin으로 배치하며 의미 text는 normal flow에 둡니다.", prevention: "horizontal/vertical·LTR/RTL·zoom·forced-colors visual fixture를 component CI에 둡니다." },
      ],
    },
    {
      id: "selector-architecture-verification",
      title: "관계·상태 selector는 component DOM 계약과 input modality matrix로 검증합니다",
      lead: "selector가 한 screenshot에서 match했다는 사실보다 wrapper·insert·filter·focus·touch·CSS failure 변화에 견디는지가 중요합니다.",
      explanations: [
        "component fixture에 direct child, extra wrapper, preceding help text, nested list, hidden/filtered item, disabled/invalid state를 모두 둡니다. querySelectorAll count와 key computed style을 기록하면 structural selector 회귀를 빠르게 찾습니다.",
        "mouse hover·mouse active·keyboard Tab/Shift+Tab·touch tap·programmatic focus·screen reader virtual navigation을 구분합니다. hover와 focus를 동일 selector list로 묶기만 해도 behavior 차이가 남으므로 실제 task를 수행합니다.",
        "attribute state는 DOM property와 accessibility behavior를 함께 검증합니다. [aria-expanded=true] style이 보이면 button click/keyboard로 값과 controlled panel hidden state가 동기화되어야 합니다. CSS는 state를 생성하지 않고 표현합니다.",
        "structural stripe/first/last selector는 sort/filter/pagination/virtualization 뒤 DOM 기준이 user-visible order와 일치하는지 확인합니다. visual reorder만 하면 nth와 focus/reading order가 어긋날 수 있습니다.",
        "pseudo-element는 screenshot/visual regression과 함께 DOM text/accessibility tree/CSS-off를 검사합니다. getComputedStyle(element,'::before').content는 debug에 유용하지만 browser serialization과 privacy 제한을 product logic으로 사용하지 않습니다.",
      ],
      concepts: [
        { term: "input modality matrix", definition: "mouse·keyboard·touch·voice·assistive technology 등 interaction 방식별로 focus/state/task 결과를 기록한 test 표입니다.", detail: ["hover-only gap을 찾습니다.", "visual state와 actual behavior를 함께 봅니다."] },
        { term: "DOM contract fixture", definition: "component가 지원해야 할 wrapper·child·state·content 변형을 의도적으로 담은 rendered test tree입니다.", detail: ["structural selector coupling을 검증합니다.", "match count·computed style·accessibility assertion을 결합합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "aria-expanded=true 스타일은 보이지만 panel은 닫혀 있거나 screen reader는 상태를 다르게 읽는다.", likelyCause: "CSS attribute selector를 state machine처럼 취급하고 DOM property/controlled region behavior를 동기화하지 않았습니다.", checks: ["button.ariaExpanded와 panel.hidden을 확인합니다.", "keyboard activation과 focus 이동을 test합니다.", "accessibility tree state/name/controls relation을 봅니다."], fix: "JavaScript/native element가 authoritative state를 변경하고 ARIA·hidden·focus를 함께 동기화하며 CSS는 그 attribute를 표현만 합니다.", prevention: "state transition별 DOM·ARIA·visual·focus integration test를 둡니다." },
      ],
      expertNotes: [
        "`:visited` style은 privacy 보호로 script에서 실제 방문 여부를 관찰하지 못하게 가장될 수 있습니다. analytics/business logic에 computed color를 사용하지 않습니다.",
        "container style query와 :state/custom state가 확장되더라도 semantic/native behavior source of truth와 selector 표현 layer를 분리하는 원칙은 같습니다.",
      ],
    },
  ],
  lab: {
    title: "nested menu·form·badge를 관계·상태·pseudo-element selector로 재구성하기",
    scenario: "원본 선택자 demo를 하나의 과정 목차 component로 합치려는데 nested li가 top-level style을 받고, keyboard focus가 안 보이며, NEW/error text가 pseudo-element에만 있고, URL substring icon이 오탐합니다.",
    setup: ["원본 selector file 5개를 read-only evidence로 준비합니다.", "desktop mouse·keyboard·touch emulation·Accessibility tree·Performance panel을 준비합니다.", "selector match count·specificity·state owner·CSS-off result를 기록할 표를 만듭니다."],
    steps: [
      "top-level/nested list DOM을 그리고 child/descendant/sibling selector의 expected match set을 적습니다.",
      "attribute operator별 URL/rel/data/ARIA fixture를 만들고 substring 오탐을 재현합니다.",
      "hover·active·focus-visible·focus-within·expanded·invalid state를 native element/ARIA와 동기화합니다.",
      "first-child/of-type/nth-child/of selector를 다른 type sibling·hidden/filter item과 함께 test합니다.",
      ":has parent enhancement를 @supports 안에 추가하고 explicit state class fallback과 성능을 비교합니다.",
      "NEW/error/required text를 DOM으로 옮기고 ::before/after/marker는 장식에만 사용합니다.",
      "mouse·keyboard·touch·CSS off·screen reader에서 menu/form task와 focus/error를 수행합니다.",
      "match counts·computed styles·ARIA state·CSS generated content·Recalculate Style 결과를 자동/수동 evidence로 남깁니다.",
    ],
    expectedResult: ["top-level과 nested item selector가 의도한 DOM set만 match합니다.", "external/status styling은 parsed/semantic state hook을 사용하고 URL substring 오탐이 없습니다.", "mouse 없이 모든 control을 사용하고 focus-visible/error text가 보입니다.", "filter/insert/wrapper 변화에서도 structural style과 reading order가 일치합니다.", "핵심 label/state/error가 DOM/accessibility tree에 있고 CSS off에도 남습니다.", ":has unsupported/large DOM에서도 baseline task와 성능 budget이 유지됩니다."],
    cleanup: ["실험용 malicious URL·invalid selector·generated critical text·hover-only rule을 제거합니다.", "touch emulation과 Performance recording/debug class를 해제하고 clean reload로 재검증합니다."],
    extensions: ["details/summary native disclosure와 custom button+aria-expanded를 selector/behavior 관점에서 비교합니다.", "large 10,000-node fixture에서 deep descendant와 :has scope를 바꿔 Recalculate Style을 측정합니다.", "CSS selector match snapshot과 Playwright keyboard/touch task를 CI에 통합합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 .a/.b/#c tree에서 child와 descendant selector가 match하는 element를 모두 표시하세요.", requirements: ["DOM parent/child/sibling tree를 그립니다.", ">와 space selector별 match count/text를 기록합니다.", "nested li color에서 direct match와 inheritance를 구분합니다.", "querySelectorAll/matches 결과와 prediction을 비교합니다."], hints: ["indentation이 아니라 Elements tree를 봅니다.", "#c > li는 nested list li를 직접 match하지 않습니다."], expectedOutcome: "모든 p/li의 match 경로와 최종 computed color/background를 정확히 설명합니다.", solutionOutline: ["selector 양쪽 compound를 먼저 match한 뒤 관계를 검사합니다.", "Styles의 inherited section을 별도 표기합니다."] },
    { difficulty: "응용", prompt: "accessible form field와 disclosure menu를 pseudo-class/attribute selector로 구현하세요.", requirements: ["hover·focus-visible·focus-within을 모두 설계합니다.", "button aria-expanded와 panel hidden/focus를 동기화합니다.", "submitted invalid state와 DOM error text를 연결합니다.", "[aria-*] style은 actual behavior와 같은 state를 표현합니다.", "mouse·keyboard·touch matrix를 test합니다."], hints: ["CSS는 state를 만들지 않고 표현합니다.", "hover-only submenu를 피합니다."], expectedOutcome: "모든 input modality에서 같은 task를 완료하고 visual·ARIA·DOM state가 일치합니다.", solutionOutline: ["state transition table을 먼저 만듭니다.", "native pseudo-state와 JS state owner를 분리합니다."] },
    { difficulty: "설계", prompt: "대규모 component library의 relational/state/generated-content selector 정책과 회귀 체계를 설계하세요.", requirements: ["combinator depth·attribute state·:has scope·structural selector 사용 기준을 정의합니다.", "browser support/@supports와 performance budget을 포함합니다.", "focus/visited/privacy/ARIA/native state contract를 설계합니다.", "generated content 접근성·localization 정책을 만듭니다.", "match count·computed·visual·keyboard/touch·accessibility CI를 정의합니다."], hints: ["selector 문법이 가능하다는 것과 component public API가 좋은 것은 다릅니다.", "CSS-off와 dynamic DOM mutation fixture를 포함합니다."], expectedOutcome: "팀이 DOM coupling·hover-only·substring 오탐·generated semantic을 예방하면서 현대 selector를 안전하게 사용하는 governance가 완성됩니다.", solutionOutline: ["selector category별 risk/owner/test matrix를 만듭니다.", "legacy 예외 감소 metric을 정의합니다."] },
  ],
  reviewQuestions: [
    { question: ".a > p와 .a p는 어떻게 다른가요?", answer: "앞은 parent가 바로 .a인 p만, 뒤는 .a 안 임의 깊이의 모든 p descendant를 match합니다." },
    { question: "A + B와 A ~ B의 차이는 무엇인가요?", answer: "+는 A 바로 다음 B 하나, ~는 A 뒤 같은 parent의 모든 matching B sibling입니다." },
    { question: "[rel~='external']과 [rel*='external']은 같은가요?", answer: "아닙니다. ~=는 whitespace token, *=는 임의 substring이라 contact-external 같은 값도 match할 수 있습니다." },
    { question: "href*=example로 외부 domain을 안전하게 판정할 수 있나요?", answer: "아닙니다. query/path에도 문자열이 있을 수 있으므로 URL parser/template가 semantic state를 만들고 CSS는 표현만 합니다." },
    { question: ":hover가 있으면 keyboard focus style도 자동 생기나요?", answer: "아닙니다. :focus-visible/:focus-within과 native focus indicator를 별도로 설계해야 합니다." },
    { question: "p:first-child는 parent의 첫 p인가요?", answer: "p가 전체 element child 중 첫 번째일 때만 match합니다. 첫 p type이면 p:first-of-type을 검토합니다." },
    { question: "display:none item은 nth-child count에서 빠지나요?", answer: "아닙니다. DOM sibling으로 남아 selector index에 포함됩니다. of selector나 rendering/state 전략을 사용합니다." },
    { question: ":has()는 무엇을 선택하나요?", answer: "argument 관계를 만족하는 descendant/child/sibling을 가진 anchor element 자체를 match하는 relational pseudo-class입니다." },
    { question: "::before content로 오류·NEW text를 넣어도 되나요?", answer: "핵심 의미는 DOM text/ARIA/native state에 두고 pseudo-element는 장식에 제한해야 CSS 실패·번역·복사·보조기술에 견고합니다." },
    { question: "`.choice:has(> input:checked)`에서 match되는 element는 input인가요?", answer: "아닙니다. direct child checked input을 가진 `.choice` anchor가 match됩니다. input을 고르려면 별도 selector가 필요합니다." },
    { question: "`:has()`가 지원되지 않으면 form 제출도 막아야 하나요?", answer: "아닙니다. native form semantics와 JavaScript behavior가 baseline task를 담당하고 `:has()`는 parent highlight 같은 progressive enhancement만 맡아야 합니다." },
    { question: "`:has()`가 느리다는 말만 듣고 전부 금지해야 하나요?", answer: "일률 금지보다 component anchor·relationship을 좁히고 실제 large-DOM interaction의 Recalculate Style을 측정해 budget으로 판단합니다." },
    { question: "`aria-disabled='true'`가 있으면 `:disabled`도 match하나요?", answer: "아닙니다. native disabled state와 ARIA attribute는 다릅니다. custom control이면 click·focus·ARIA·style을 직접 동기화해야 합니다." },
    { question: "required input에 `:invalid` rule만 있으면 접근 가능한 오류가 완성되나요?", answer: "아닙니다. 적절한 노출 시점, visible error text, programmatic description, 색 이외의 표시와 keyboard focus 정책이 필요합니다." },
    { question: "`:visited`에 `::after { content: '방문함' }`을 넣어도 되나요?", answer: "방문 이력 privacy 제한 때문에 기대대로 적용·관찰할 수 없고 history를 의미 source로 사용해서도 안 됩니다. 허용된 단순 color affordance만 사용합니다." },
  ],
  completionChecklist: [
    "descendant·child·adjacent·subsequent combinator의 exact DOM match set을 검증했다.",
    "attribute operator를 존재·token·문자열 의미에 맞게 사용하고 URL/security 판정을 분리했다.",
    "hover·active·focus-visible·focus-within·form state를 mouse/keyboard/touch에서 test했다.",
    "first-child/of-type/nth-child/An+B/of selector를 실제 sibling list에서 계산했다.",
    ":not/:is/:where/:has의 matching·specificity·support·performance를 component boundary 안에서 검증했다.",
    "핵심 상태·label·error는 DOM에 두고 pseudo-element를 장식/typography에 제한했다.",
    "ARIA/data attribute visual state와 actual behavior/focus/controlled region을 동기화했다.",
    "wrapper·insert·filter·CSS off·large DOM fixture에서 selector 회귀와 성능을 확인했다.",
    "`:has()` anchor를 component boundary로 제한하고 unsupported browser에서도 핵심 task가 가능한 baseline을 확인했다.",
    "`:has()` argument의 combinator와 specificity를 계산하고 high-specificity id가 섞이지 않았는지 검토했다.",
    "large DOM에서 descendant mutation 전후 Recalculate Style을 측정해 relational selector budget을 기록했다.",
    "native checked·disabled·validity와 ARIA/data state의 semantic·behavior 차이를 test했다.",
    "오류는 submit/touched lifecycle에 맞춰 visible DOM text와 programmatic description으로 전달했다.",
    "horizontal/vertical writing mode와 LTR/RTL에서 pseudo-element logical inset·size·margin을 확인했다.",
    "visited style·generated content·hidden DOM을 history 판정이나 secret/authorization 수단으로 사용하지 않았다.",
  ],
  nextSessions: ["css-04-typography-color-icons"],
  sources: [
    { id: "web-combinator-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex15_css_selector.html", usedFor: ["child·descendant", "nested p", "top-level/nested li", "inheritance"], evidence: "a/b paragraph와 #c nested list tree 전체를 match-count와 inherited style diagnostic의 근거로 사용했습니다." },
    { id: "web-structural-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex16_cs_selector.html", usedFor: ["nth-of-type", "first/last-of-type", "sibling type index"], evidence: "page-level·nested p sequence를 읽어 child index와 type index 차이를 보강했습니다." },
    { id: "web-attribute-selector-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex01_selector.html", usedFor: ["attribute exact/prefix/contains/suffix", "mailto/domain", "input type"], evidence: "href와 input selector를 audit해 token/case flag·URL substring 오탐·state hook 경계로 확장했습니다." },
    { id: "web-pseudo-class-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex02_selector.html", usedFor: ["link/visited", "hover/active/focus", "first/last/nth-child", "odd/even/not"], evidence: "원본 interaction/structural pseudo-class 전체를 keyboard·touch·privacy·An+B/of selector 기준으로 현대화했습니다." },
    { id: "web-pseudo-element-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex03_selector.html", usedFor: ["before/after", "first-letter/line", "marker/selection/placeholder", "icon/underline/badge"], evidence: "모든 pseudo-element demo를 읽어 generated content의 semantic/accessibility 경계와 exact CSSOM output으로 확장했습니다." },
    { id: "selectors-4", repository: "W3C CSS Working Group", path: "TR/selectors-4/", publicUrl: "https://www.w3.org/TR/selectors-4/", usedFor: ["combinator", "attribute operator/flags", "interaction/structural pseudo-class", "An+B of S", ":has", ":visited privacy"], evidence: "2026-07-12 기준 Selectors Level 4의 current matching·case·privacy·nth/has 규칙을 기준으로 확인했습니다." },
    { id: "css-pseudo-4", repository: "W3C CSS Working Group", path: "TR/css-pseudo-4/", publicUrl: "https://www.w3.org/TR/css-pseudo-4/", usedFor: ["before/after", "first-line/letter", "marker", "selection", "originating element"], evidence: "CSS Pseudo-Elements Level 4의 generated/typographic/highlight pseudo-element 정의를 사용했습니다." },
    { id: "css-content-3", repository: "W3C CSS Working Group", path: "TR/css-content-3/", publicUrl: "https://www.w3.org/TR/css-content-3/", usedFor: ["content property", "generated content", "counter/content functions"], evidence: "generated content의 범위와 CSS failure/semantic boundary 설명의 표준 근거로 사용했습니다." },
    { id: "wai-forms", repository: "W3C Web Accessibility Initiative", path: "tutorials/forms/", publicUrl: "https://www.w3.org/WAI/tutorials/forms/", usedFor: ["label/error text", "keyboard focus", "validation notification"], evidence: "focus/invalid selector example에서 visible label·DOM error·programmatic relation을 유지하는 기준으로 반영했습니다." },
    { id: "selectors-relational-has", repository: "W3C CSS Working Group", path: "TR/selectors-4/#relational", publicUrl: "https://www.w3.org/TR/selectors-4/#relational", usedFor: [":has relative selector", "anchor matching", "specificity", "progressive enhancement"], evidence: "checked·disabled descendant를 가진 parent card와 scoped performance/fallback 설명을 Selectors Level 4 relational pseudo-class 정의에 맞춰 검증했습니다." },
  ],
  sourceCoverage: {
    filesRead: 5,
    filesUsed: 5,
    uncoveredNotes: [
      "원본은 관계·속성·상태·pseudo-element의 핵심을 매우 폭넓게 포함합니다. sibling combinator, attribute flags/token, :focus-visible/within, nth-of-S, :has, visited privacy와 generated-content 접근성은 최신 W3C specification으로 보강했습니다.",
      "transition/animation·container query·custom state·shadow parts의 selector interaction은 후속 CSS/React component 과정에서 확장합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
