import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-07-position-stacking-modal"],
  slug: "css-07-position-stacking-modal",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 7,
  title: "relative·absolute·fixed·sticky와 stacking context",
  subtitle: "좌표를 외우는 대신 normal flow·containing block·scrollport·stacking context·top layer를 추적하고, 시각 중앙 배치와 실제 modal dialog의 focus/inert 계약을 분리합니다.",
  level: "고급",
  estimatedMinutes: 220,
  coreQuestion: "positioned box가 어느 rectangle을 기준으로 어디에 배치되고 어떤 stacking context 안에서 paint되는지 어떻게 증명하며, overlay를 keyboard·screen reader까지 진짜 modal로 만들려면 무엇이 더 필요할까요?",
  summary: "원본의 relative 이동, absolute child/parent, fixed 중첩, sticky, translate 중앙 modal, 배경 overlay, z-index image를 모두 감사합니다. static/relative의 flow slot, absolute/fixed의 out-of-flow, containing block을 만드는 ancestor, logical inset·over-constraint, sticky scroll container·inset·boundary, viewport/dvh/safe area를 정확히 다룹니다. z-index가 전역 숫자가 아니라 stacking context 내부 순서이며 transform·opacity·isolation 등 새 context와 dialog top layer가 결과를 바꾸는 것을 elementFromPoint로 증명합니다. div.modal을 native dialog showModal/::backdrop/focus/Escape/return-focus로 교정하고 content sizing·scroll lock·nested overlay·DevTools Layers 진단까지 연결합니다.",
  objectives: [
    "static·relative·absolute·fixed·sticky가 normal flow와 box position에 미치는 차이를 설명할 수 있다.",
    "absolute/fixed box의 containing block을 nearest positioned ancestor라는 단순 규칙을 넘어 transform·contain 등까지 추적할 수 있다.",
    "physical top/right/bottom/left와 logical inset property, auto/size/over-constraint를 writing mode에 맞게 사용할 수 있다.",
    "sticky가 어느 scroll container에서 어떤 inset과 containing-block 경계 사이에 붙는지 진단할 수 있다.",
    "stacking context 생성 조건과 내부 atomic stacking을 이해해 z-index 999999가 지는 이유를 설명할 수 있다.",
    "native dialog의 top layer·backdrop·accessible name·inert·focus 이동/containment·Escape·focus return을 검증할 수 있다.",
  ],
  prerequisites: [
    { title: "테두리·둥근 모서리·그림자와 마진 상쇄", reason: "box geometry·BFC·margin 흐름을 바탕으로 flow에서 벗어난 box의 좌표와 겹침을 추적합니다.", sessionSlug: "css-06-borders-shadows-margin-collapse" },
  ],
  keywords: ["position", "static", "relative", "absolute", "fixed", "sticky", "containing block", "inset", "scroll container", "z-index", "stacking context", "top layer", "dialog", "modal", "focus management"],
  chapters: [
    {
      id: "normal-flow-static-relative",
      title: "static은 formatting context의 normal flow를 따르고 relative는 원래 flow slot을 남긴 채 box만 offset합니다",
      lead: "relative로 이동한 box 때문에 뒤 sibling이 자동으로 비켜나는 것이 아니므로 overlap과 빈 공간을 함께 관찰합니다.",
      explanations: [
        "position의 initial value는 static입니다. static box의 containing block과 layout은 block/inline/flex/grid formatting context가 결정하며 일반적인 inset property는 static positioning에서 위치 offset으로 작동하지 않습니다. margin·alignment·layout system으로 먼저 배치합니다.",
        "relative box는 static position으로 먼저 normal flow에 배치된 뒤 inset으로 visual position을 offset합니다. 원래 차지한 flow space는 그대로 남고 sibling layout은 이동 전 위치를 기준으로 합니다. 원본 두 번째 section을 top/left 50px 이동하면 세 번째 section이 내려가지 않아 겹칠 수 있습니다.",
        "relative 자체는 offset이 모두 auto면 눈에 보이는 이동이 없지만 absolute descendant의 containing block 또는 z-index stacking context 목적에 쓰일 수 있습니다. 'position:relative는 absolute 부모용'으로만 외우지 않고 자기 box offset·stacking behavior까지 이해합니다.",
        "top과 bottom, left와 right를 동시에 non-auto로 주면 size/auto/writing direction과 position scheme에 따라 over-constrained 해결 규칙이 적용됩니다. 원본처럼 top:50,bottom:50,left:50,right:50을 모두 넣어 이동 방향을 추측하지 말고 필요한 logical inset 한쪽 또는 inset shorthand와 size contract를 명확히 합니다.",
        "relative offset은 transform translate와 시각적으로 비슷할 수 있지만 containing block·stacking·percentage 기준·animation/rendering behavior가 다릅니다. layout intent와 performance를 측정해 선택합니다.",
      ],
      concepts: [
        { term: "normal flow", definition: "positioning·float 등 특별한 이탈 전, formatting context의 규칙에 따라 box가 차례로 배치되는 기본 흐름입니다.", detail: ["block/inline/flex/grid마다 규칙이 다릅니다.", "source/DOM order와 밀접합니다."] },
        { term: "relative positioning", definition: "box를 normal flow에 배치한 뒤 자기 static position을 기준으로 offset하되 원래 flow space를 유지하는 scheme입니다.", detail: ["sibling은 원래 slot을 기준으로 배치됩니다.", "absolute descendant containing block이 될 수 있습니다."] },
        { term: "inset", definition: "positioned box의 containing block 각 edge와의 offset을 지정하는 top/right/bottom/left 및 logical shorthand 계열입니다.", detail: ["auto와 size 조합으로 위치·크기를 결정합니다.", "writing mode에는 logical inset을 고려합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "relative로 card를 아래로 옮겼더니 다음 card와 겹치고 원래 자리에는 빈 공간이 남는다.", likelyCause: "relative offset은 normal-flow slot을 재배치하지 않고 visual box만 이동합니다.", checks: ["DevTools Layout에서 original/translated box를 확인합니다.", "다음 sibling의 offsetTop을 비교합니다.", "실제 의도가 spacing인지 overlay인지 묻습니다."], fix: "문서 흐름 간격이면 margin/gap/Grid/Flex로 배치하고 intentional overlap일 때만 relative offset을 사용합니다.", prevention: "macro spacing에 positional offset을 금지하고 overlap acceptance test를 둡니다." },
      ],
    },
    {
      id: "absolute-containing-block",
      title: "absolute box는 normal flow에서 빠지고 자신의 absolute-position containing block을 기준으로 배치됩니다",
      lead: "'relative parent가 없으면 body'가 아니라 containing block을 실제 offsetParent·geometry·ancestor property로 찾아야 합니다.",
      explanations: [
        "absolute-positioned box는 일반 flow에서 제거되어 보통 sibling이 그 공간을 예약하지 않습니다. position scheme과 inset/size/margin으로 위치·크기를 계산하며 content가 길면 fixed height에서 overflow할 수 있습니다.",
        "가장 흔한 pattern은 component root position:relative와 child position:absolute입니다. 그러나 containing block은 단순 DOM parent가 아니라 nearest ancestor 중 positioned box나 transform/filter/perspective/contain/will-change 등 specification이 containing block을 형성하는 조건에 따라 달라질 수 있습니다.",
        "적합한 ancestor가 없으면 initial containing block을 기준으로 합니다. 이는 항상 body element box와 같다고 단정할 수 없습니다. document/viewport/page context와 scrolling을 구분합니다.",
        "offsetParent는 debug hint지만 CSS containing block 정의와 모든 경우 정확히 일치하는 보편 API는 아닙니다. table/SVG/fixed/transform/hidden 등에 차이가 있을 수 있어 getBoundingClientRect와 computed ancestor property를 함께 확인합니다.",
        "absolute는 badge·icon·overlay·tooltip anchor처럼 flow content를 덮는 의도가 있을 때 유용합니다. 본문 column·form label·전체 page layout을 absolute 좌표로 만들면 text zoom·translation·dynamic error에 깨지므로 Grid/Flex/normal flow를 우선합니다.",
      ],
      concepts: [
        { term: "containing block", definition: "percentage size와 positioned inset 계산의 기준 rectangle을 제공하는 CSS layout 개념입니다.", detail: ["DOM parent와 항상 같지 않습니다.", "position scheme과 ancestor property에 따라 형성됩니다."] },
        { term: "out of flow", definition: "normal-flow sibling 배치에서 box가 공간을 차지하지 않는 상태입니다.", detail: ["absolute/fixed box가 대표적입니다.", "접근성 tree/DOM 순서에서 제거된다는 뜻은 아닙니다."] },
        { term: "initial containing block", definition: "다른 containing block ancestor가 없을 때 root canvas/viewport/page와 관련해 초기 layout 기준을 제공하는 rectangle입니다.", detail: ["body box와 단순 동일시하지 않습니다.", "continuous/paged media에서 의미가 다를 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "absolute-containing-block-proof",
          title: "badge의 offsetParent와 flow sibling 위치로 absolute behavior 증명",
          language: "html",
          filename: "absolute-box.html",
          purpose: "component root가 containing block을 제공하고 absolute child가 sibling flow 공간을 차지하지 않는 것을 exact DOM geometry로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>절대 위치 기준</title>\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; }\n    .card { position: relative; inline-size: 320px; padding: 20px; border: 2px solid #444; }\n    .badge { position: absolute; inset-block-start: 12px; inset-inline-end: 16px; inline-size: 72px; block-size: 28px; }\n    .line { display: block; block-size: 24px; }\n  </style>\n</head>\n<body>\n  <article id=\"card\" class=\"card\">\n    <span id=\"before\" class=\"line\">제목</span>\n    <span id=\"badge\" class=\"badge\">신규</span>\n    <span id=\"after\" class=\"line\">설명</span>\n  </article>\n  <pre id=\"result\"></pre>\n  <script>\n    const badge = document.querySelector('#badge');\n    const before = document.querySelector('#before');\n    const after = document.querySelector('#after');\n    const style = getComputedStyle(badge);\n    document.querySelector('#result').textContent = [\n      `offsetParent=${badge.offsetParent.id}`,\n      `position=${style.position}`,\n      `inset-block-start=${style.insetBlockStart}`,\n      `flow-gap=${after.offsetTop - before.offsetTop}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-11", explanation: "card가 relative containing block, badge가 logical inset absolute box이고 두 line은 각 24px normal-flow block입니다." },
            { lines: "15-19", explanation: "badge가 source에서 두 line 사이에 있어도 out-of-flow라 after line을 아래로 밀지 않습니다." },
            { lines: "23-31", explanation: "offsetParent, computed position/inset, 두 flow line의 offsetTop 차이를 출력합니다." },
          ],
          run: { environment: ["현대 browser", "default zoom 100%"], command: "browser에서 absolute-box.html을 열고 결과 확인" },
          output: { value: "offsetParent=card\nposition=absolute\ninset-block-start=12px\nflow-gap=24", explanation: ["relative card가 badge의 offsetParent hint로 확인됩니다.", "absolute badge는 before/after 사이의 24px flow 간격을 늘리지 않습니다.", "logical inset serialization은 horizontal writing mode에서 12px로 resolve됩니다."] },
          experiments: [
            { change: ".card의 position:relative를 제거합니다.", prediction: "offsetParent가 body 또는 다른 ancestor로 바뀌고 badge가 card 밖 다른 기준에 배치됩니다.", result: "DOM parent만으로 containing block이 되지 않습니다." },
            { change: "card 바깥 wrapper에 transform:translateZ(0)을 적용합니다.", prediction: "wrapper가 containing block/stacking context에 관여해 badge 기준이 달라질 수 있습니다.", result: "position 외 property도 containing block을 만들 수 있습니다." },
            { change: "badge를 position:static으로 바꿉니다.", prediction: "flow-gap이 badge line box 영향을 받아 24보다 커지고 inset이 위치를 옮기지 않습니다.", result: "out-of-flow 여부가 sibling layout을 바꿉니다." },
          ],
          sourceRefs: ["web-position-absolute-source", "css-position-3"],
        },
      ],
      diagnostics: [
        { symptom: "absolute tooltip이 card가 아니라 page corner에 붙는다.", likelyCause: "의도한 anchor가 containing block을 만들지 않거나 중간 transform/contain ancestor가 다른 기준을 만들었습니다.", checks: ["tooltip.offsetParent와 ancestor computed position/transform/contain을 확인합니다.", "anchor/tooltip rect 차이를 계산합니다.", "portal로 DOM 위치가 바뀌었는지 봅니다."], fix: "의도한 root에 적절한 positioning/anchor contract를 제공하거나 top-layer/anchor-positioning library로 좌표를 계산합니다.", prevention: "nested/portal/transformed ancestor fixture의 tooltip geometry를 test합니다." },
      ],
    },
    {
      id: "fixed-viewport-and-mobile",
      title: "fixed는 보통 viewport에 고정되지만 containing-block ancestor와 mobile viewport·safe area를 확인해야 합니다",
      lead: "parent 유무를 무시한다는 설명은 transform 등 fixed containing block을 바꾸는 조건에서 깨집니다.",
      explanations: [
        "fixed-position box는 보통 viewport를 containing block으로 하고 scroll해도 같은 위치에 보입니다. 원본 box3/box4가 겹치는 것은 일반 ancestor가 기준을 바꾸지 않기 때문이지만 모든 parent를 무시한다는 뜻은 아닙니다.",
        "transform·perspective·filter 또는 contain 같은 ancestor는 fixed descendant의 containing block을 형성할 수 있어 viewport 대신 해당 ancestor와 함께 scroll하게 합니다. app shell에 transform:translateZ(0)을 성능 hack으로 추가한 뒤 modal/toast가 잘리는 흔한 원인입니다.",
        "mobile browser에는 layout viewport와 visual viewport, dynamic toolbar 변화가 있습니다. height:100vh가 보이는 영역보다 크거나 작게 느껴질 수 있어 svh/lvh/dvh와 VisualViewport, actual device test를 고려합니다. 무조건 100dvh도 keyboard resize와 content scroll을 검증합니다.",
        "notch/home indicator에는 env(safe-area-inset-*)를 padding에 더할 수 있습니다. fixed close/button/toast가 safe area에 가려지지 않고 200% zoom·orientation·virtual keyboard에서 접근 가능한지 확인합니다.",
        "fixed header/footer는 content를 가릴 수 있습니다. main의 scroll-padding/scroll-margin, anchor focus, skip link target, sticky 대안, reduced viewport height를 함께 설계합니다.",
      ],
      concepts: [
        { term: "fixed positioning", definition: "box를 fixed-position containing block에 대해 배치하고 일반 scroll에서 위치를 유지하는 positioning scheme입니다.", detail: ["보통 viewport 기준입니다.", "특정 ancestor property가 기준을 바꿀 수 있습니다."] },
        { term: "visual viewport", definition: "pinch zoom·on-screen keyboard·browser UI를 반영해 사용자가 현재 실제로 보는 viewport 영역입니다.", detail: ["layout viewport와 다를 수 있습니다.", "mobile overlay geometry에 중요합니다."] },
        { term: "safe area inset", definition: "notch·rounded corner·system UI를 피하도록 environment가 제공하는 edge inset입니다.", detail: ["env()로 사용할 수 있습니다.", "fallback과 device test가 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "fixed modal이 viewport가 아니라 transformed app container 안에서 잘리고 scroll된다.", likelyCause: "ancestor transform/filter/contain이 fixed containing block 또는 stacking context를 만들었습니다.", checks: ["ancestor chain의 transform/filter/perspective/contain/will-change를 확인합니다.", "modal rect와 visual viewport를 비교합니다.", "portal/top-layer 여부를 확인합니다."], fix: "불필요한 ancestor transform을 제거하거나 dialog/top layer/적절한 portal root로 overlay를 이동합니다.", prevention: "overlay를 transformed/overflow-clipped shell 안에 render하는 fixture를 CI에 둡니다." },
      ],
    },
    {
      id: "sticky-scroll-container",
      title: "sticky는 normal flow 위치와 nearest scrollport inset 사이를 이동하며 containing block 끝에서 멈춥니다",
      lead: "position:sticky만으로 붙지 않고 적어도 한 축 inset, 실제 scroll container, 이동할 공간과 boundary가 필요합니다.",
      explanations: [
        "sticky box는 normal flow에 참여하면서 scroll 시 inset threshold를 넘지 않도록 상대적으로 조정됩니다. top/inset-block-start가 auto인 채 bottom만 주면 기대한 header behavior와 다릅니다. 목적 축의 inset을 명시합니다.",
        "nearest ancestor의 overflow hidden/auto/scroll/clip과 actual scrolling mechanism이 sticky 기준을 바꿀 수 있습니다. page를 scroll한다고 생각해도 중간 overflow container가 sticky scrollport가 되어 움직이지 않는 것처럼 보일 수 있습니다.",
        "sticky는 containing block 범위를 벗어나지 않아 parent 높이가 sticky box와 같거나 scroll distance가 짧으면 붙을 공간이 없습니다. 원본의 앞/뒤 긴 div와 float 조합보다 명확한 scroll container와 content height fixture로 진단합니다.",
        "flex/grid item stretch, table section, overflow, block size도 sticky behavior에 영향을 줍니다. align-self:start와 min-height를 무작정 처방하지 않고 computed size와 scrollHeight/clientHeight를 측정합니다.",
        "sticky heading이 content를 가리면 stacking/background와 anchor scroll margin을 제공합니다. 여러 sticky row가 겹치면 accumulated offset과 z-index/stacking context를 설계합니다.",
      ],
      concepts: [
        { term: "scroll container", definition: "overflow와 scrolling mechanism을 제공해 descendant의 scrollport를 정의하는 box입니다.", detail: ["sticky 기준이 될 수 있습니다.", "scrollHeight/clientHeight로 실제 overflow를 확인합니다."] },
        { term: "sticky view rectangle", definition: "inset으로 scrollport에서 줄인 rectangle이며 sticky box가 이 경계를 벗어나지 않도록 위치를 조정합니다.", detail: ["box가 너무 크면 end inset이 조정될 수 있습니다.", "containing block 경계도 지킵니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "position:sticky; top:0인데 page를 내려도 element가 붙지 않는다.", likelyCause: "중간 overflow ancestor·scroll 공간 부족·parent boundary·stretch/size 때문에 sticky threshold를 통과하지 못합니다.", checks: ["ancestor overflow와 실제 scrollTop 변화를 확인합니다.", "scrollHeight>clientHeight인지 봅니다.", "sticky rect와 containing parent rect를 scroll 전후 기록합니다.", "computed inset-block-start가 auto가 아닌지 확인합니다."], fix: "의도한 scroll container와 충분한 content range를 만들고 불필요한 overflow/stretch를 제거하며 correct inset을 지정합니다.", prevention: "nested scroll container·short parent·zoom·dynamic content sticky geometry test를 둡니다." },
      ],
    },
    {
      id: "stacking-context-z-index",
      title: "z-index는 전역 높이 숫자가 아니라 같은 stacking context 안의 stack level을 정합니다",
      lead: "child의 999999도 parent stacking context가 sibling 아래라면 그 경계를 탈출해 위로 올라갈 수 없습니다.",
      explanations: [
        "root는 stacking context를 형성하고 특정 positioned box+non-auto z-index, fixed/sticky, opacity<1, transform/filter, isolation:isolate, 일부 flex/grid item과 contain 등도 새 context를 만들 수 있습니다. 정확한 생성 조건을 DevTools Layers/3D view와 computed styles로 추적합니다.",
        "stacking context는 parent context에서 하나의 atomic unit처럼 쌓입니다. parent A가 z-index:1, sibling B가 z-index:2면 A 안 child z-index:999는 B context 위로 나갈 수 없습니다. 숫자 크기를 계속 늘리는 것은 해결이 아닙니다.",
        "z-index:auto와 0, positioned/non-positioned/flex/grid item의 적용 차이를 구분합니다. source/painting order, negative stack level, block background, floats, inline content 등 전체 painting order를 단순 '높은 숫자 위'로 축약하지 않습니다.",
        "negative z-index image를 배경처럼 두면 parent stacking context/background 뒤로 숨어 보이지 않거나 page 다른 content 아래로 내려갈 수 있습니다. 장식 image가 진짜 background이면 CSS background를, content image면 semantic img와 explicit overlay/pseudo-element를 선택합니다.",
        "stacking context를 intentional boundary로 만들 때 isolation:isolate가 유용합니다. component 내부 negative/positive z-index가 page 밖과 섞이지 않게 하지만 tooltip/popover가 clip/context를 넘어야 한다면 portal/top layer가 필요합니다.",
      ],
      concepts: [
        { term: "stacking context", definition: "descendant의 paint 순서를 내부에서 계산한 뒤 parent context에 하나의 atomic stacking unit으로 참여하는 3차원 grouping입니다.", detail: ["여러 CSS property가 생성합니다.", "child z-index는 context 경계를 넘지 못합니다."] },
        { term: "stack level", definition: "한 stacking context 안에서 positioned/stacking item이 다른 content와 비교되는 z-axis 순서입니다.", detail: ["z-index가 한 입력입니다.", "painting order category와 함께 해석합니다."] },
        { term: "top layer", definition: "fullscreen·modal dialog·popover 등 특정 UA-managed element가 document stacking context 바깥 최상위 layer에 놓이는 구조입니다.", detail: ["z-index 경쟁과 다릅니다.", "::backdrop도 함께 관리됩니다."] },
      ],
      codeExamples: [
        {
          id: "stacking-context-trap",
          title: "z-index 999 child가 z-index 2 sibling에게 지는 장면",
          language: "html",
          filename: "stacking-context.html",
          purpose: "nested stacking context의 atomic behavior를 elementFromPoint와 computed z-index로 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>스태킹 컨텍스트</title>\n  <style>\n    body { margin: 0; }\n    .scene { position: relative; inline-size: 260px; block-size: 180px; }\n    .group-a, .group-b { position: absolute; inline-size: 180px; block-size: 120px; }\n    .group-a { inset: 0 auto auto 0; z-index: 1; }\n    .group-b { inset: 40px auto auto 60px; z-index: 2; }\n    .red { position: absolute; inset: 0; z-index: 999; background: rgb(200, 40, 40); }\n    .blue { position: absolute; inset: 0; background: rgb(40, 80, 200); }\n  </style>\n</head>\n<body>\n  <div id=\"scene\" class=\"scene\">\n    <div id=\"group-a\" class=\"group-a\"><div id=\"red\" class=\"red\"></div></div>\n    <div id=\"group-b\" class=\"group-b\"><div id=\"blue\" class=\"blue\"></div></div>\n  </div>\n  <pre id=\"result\"></pre>\n  <script>\n    const scene = document.querySelector('#scene').getBoundingClientRect();\n    const topNode = document.elementFromPoint(scene.left + 100, scene.top + 80);\n    document.querySelector('#result').textContent = [\n      `group-a=${getComputedStyle(document.querySelector('#group-a')).zIndex}`,\n      `red=${getComputedStyle(document.querySelector('#red')).zIndex}`,\n      `group-b=${getComputedStyle(document.querySelector('#group-b')).zIndex}`,\n      `top-at-overlap=${topNode.id}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-13", explanation: "두 sibling parent가 각각 z-index 1/2 stacking context를 만들고 red child만 999를 가집니다." },
            { lines: "17-20", explanation: "red/blue 영역이 x 60~180, y 40~120에서 겹치도록 배치합니다." },
            { lines: "24-31", explanation: "겹침 내부 point(100,80)의 실제 topmost element와 세 z-index를 출력합니다." },
          ],
          run: { environment: ["현대 browser", "page zoom 100%", "overlay/extension이 page point를 덮지 않는 환경"], command: "browser에서 stacking-context.html을 열고 결과 확인" },
          output: { value: "group-a=1\nred=999\ngroup-b=2\ntop-at-overlap=blue", explanation: ["red 999는 group-a 내부에서만 강합니다.", "group-b context 2가 group-a context 1보다 위라 blue가 실제 hit-test top입니다.", "elementFromPoint는 paint/hit-test 결과를 직접 확인합니다."] },
          experiments: [
            { change: "group-a의 z-index를 3으로 바꿉니다.", prediction: "top-at-overlap=red가 됩니다.", result: "parent context 순서를 바꿔야 child context가 함께 위로 이동합니다." },
            { change: "두 group z-index/position context를 제거합니다.", prediction: "red의 z-index가 더 상위 context에서 blue와 직접 경쟁해 red가 위가 될 수 있습니다.", result: "context 경계 유무가 숫자보다 중요합니다." },
            { change: "group-b에 opacity:.99만 주고 z-index를 제거합니다.", prediction: "opacity가 새 context를 만들며 source/stack order에 따라 여전히 red와 별도 atomic group으로 경쟁합니다.", result: "positioned z-index 외 property도 stacking context를 생성합니다." },
          ],
          sourceRefs: ["web-z-index-source", "css-position-3"],
        },
      ],
      diagnostics: [
        { symptom: "tooltip에 z-index:999999를 줘도 header/card 아래에 가려진다.", likelyCause: "tooltip ancestor가 더 낮은 stacking context 또는 overflow clip 안에 있습니다.", checks: ["tooltip에서 root까지 stacking-context trigger와 z-index를 tree로 그립니다.", "sibling parent context 순서를 비교합니다.", "overflow clip과 top-layer/portal 여부를 확인합니다."], fix: "불필요한 context/clip을 제거하거나 overlay owner context/portal/top layer로 옮기고 component isolation을 설계합니다.", prevention: "overlay nested in transform/opacity/isolation/overflow fixture와 hit-test E2E를 둡니다." },
      ],
    },
    {
      id: "modal-is-behavior-not-position",
      title: "화면 중앙 div는 modal이 아니며 dialog top layer·inert·focus·keyboard lifecycle이 있어야 합니다",
      lead: "position:fixed와 box-shadow는 시각 overlay만 만들 뿐 background interaction과 보조기술 context를 제한하지 않습니다.",
      explanations: [
        "원본 .modal div는 중앙에 보이지만 dialog role/name이 없고 background link가 focus 가능하며 Tab이 밖으로 나가고 Escape/close/focus return이 없습니다. placeholder만 있고 label/name도 부족합니다. CSS가 아니라 widget behavior 문제입니다.",
        "native dialog element를 showModal()로 열면 modal dialog가 top layer에 놓이고 document의 나머지 content가 inert 처리되는 platform behavior를 활용합니다. open attribute를 직접 toggle하는 것과 showModal의 modal mode는 같지 않습니다.",
        "dialog에는 visible heading을 aria-labelledby로 연결하거나 적절한 name을 제공합니다. 열 때 content 성격에 맞는 inside element로 focus를 옮기고 Tab/Shift+Tab이 dialog 안에 머무는지, Escape cancel event와 visible close/cancel button, 닫은 뒤 invoker focus return을 test합니다.",
        "::backdrop으로 dim 처리하되 opacity/contrast만으로 modal state를 전달하지 않습니다. background click으로 닫을지 accidental data loss·nested dialog·pointer coordinate를 고려해 product rule을 정합니다.",
        "긴 modal은 viewport보다 작게 max-block-size와 overflow:auto를 주고 heading/action이 보이도록 설계합니다. fixed height·line-height 중앙 정렬은 long text·zoom·form error를 잘라냅니다. 320px·200% zoom·virtual keyboard를 test합니다.",
        "dialog unsupported target이 있거나 custom modal이 꼭 필요하면 role=dialog, aria-modal=true, inert/focus trap/return/Escape를 직접 구현해야 하지만 native behavior를 우선합니다. ARIA attribute만 붙인다고 behavior가 자동 생기지 않습니다.",
      ],
      concepts: [
        { term: "modal dialog", definition: "열려 있는 동안 외부 content interaction을 막고 dialog 내부 task에 focus/context를 제한하는 overlay window입니다.", detail: ["accessible name과 close path가 필요합니다.", "시각 dim만으로 modal이 되지 않습니다."] },
        { term: "inert", definition: "subtree가 사용자 interaction·focus와 accessibility tree 노출에서 비활성화되는 상태/behavior입니다.", detail: ["showModal이 외부 document에 modal behavior를 제공합니다.", "수동 inert 사용 시 lifecycle을 관리합니다."] },
        { term: "focus return", definition: "dialog가 닫힌 뒤 열었던 control 또는 다음 logical workflow target으로 keyboard focus를 되돌리는 behavior입니다.", detail: ["invoker가 사라졌을 때 fallback이 필요합니다.", "close reason과 task result를 고려합니다."] },
      ],
      codeExamples: [
        {
          id: "native-modal-dialog",
          title: "showModal·top layer·autofocus·Escape·focus return을 가진 로그인 dialog",
          language: "html",
          filename: "modal-dialog.html",
          purpose: "원본 fixed div modal을 native dialog lifecycle과 exact state output을 가진 접근 가능한 widget으로 교정합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>로그인 대화상자</title>\n  <style>\n    dialog { inline-size: min(28rem, calc(100% - 2rem)); max-block-size: calc(100dvh - 2rem); overflow: auto; border: 0; border-radius: 1rem; padding: 1.5rem; }\n    dialog::backdrop { background: rgb(0 0 0 / .65); }\n    dialog form { display: grid; gap: .75rem; }\n    button:focus-visible, input:focus-visible { outline: .2rem solid #a33b00; outline-offset: .15rem; }\n  </style>\n</head>\n<body>\n  <main><h1>학습 기록</h1><button id=\"open\">로그인 열기</button></main>\n  <dialog id=\"login\" aria-labelledby=\"dialog-title\">\n    <form method=\"dialog\">\n      <h2 id=\"dialog-title\" tabindex=\"-1\">로그인</h2>\n      <label for=\"user-id\">아이디</label><input id=\"user-id\" name=\"userId\" autocomplete=\"username\">\n      <label for=\"password\">비밀번호</label><input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\">\n      <button value=\"login\">로그인</button><button id=\"cancel\" value=\"cancel\" formnovalidate>취소</button>\n    </form>\n  </dialog>\n  <pre id=\"result\"></pre>\n  <script>\n    const opener = document.querySelector('#open');\n    const dialog = document.querySelector('#login');\n    const title = document.querySelector('#dialog-title');\n    const result = document.querySelector('#result');\n    opener.addEventListener('click', () => {\n      dialog.showModal();\n      title.focus();\n      result.textContent = [\n        `open=${dialog.open}`,\n        `modal=${dialog.matches(':modal')}`,\n        `focus=${document.activeElement.id}`\n      ].join('\\n');\n    });\n    dialog.addEventListener('close', () => {\n      result.textContent += `\nclosed=${dialog.returnValue}\nreturn-focus=${document.activeElement.id}`;\n    });\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-11", explanation: "dialog는 viewport보다 작게 content scroll을 허용하고 ::backdrop·focus-visible을 제공합니다. 중앙 배치는 UA dialog behavior를 활용합니다." },
            { lines: "15-22", explanation: "실제 invoker와 named dialog, label/input, method=dialog action buttons를 semantic DOM으로 구성합니다." },
            { lines: "29-39", explanation: "showModal로 top layer/modal mode를 열고 긴 content를 읽기 좋은 heading에 focus한 뒤 open/:modal/activeElement를 출력합니다." },
            { lines: "40-42", explanation: "close 뒤 returnValue와 platform focus return 결과를 기록합니다." },
          ],
          run: { environment: ["dialog·:modal·showModal 지원 현대 browser", "keyboard"], command: "modal-dialog.html을 열고 로그인 열기 button 활성화" },
          output: { value: "open=true\nmodal=true\nfocus=dialog-title\nclosed=cancel\nreturn-focus=open", explanation: ["showModal은 open attribute와 :modal state를 동시에 만듭니다.", "초기 focus는 명시적으로 heading에 이동합니다.", "취소 button으로 close한 뒤 browser가 invoker open button으로 focus를 반환합니다."] },
          experiments: [
            { change: "dialog.showModal()을 dialog.setAttribute('open','')으로 바꿉니다.", prediction: "open은 true여도 :modal=false이고 top layer/inert/focus containment modal behavior가 없습니다.", result: "open attribute와 modal lifecycle은 동일하지 않습니다." },
            { change: "dialog를 div class=modal로 바꾸고 CSS만 유지합니다.", prediction: "시각 box는 보일 수 있지만 showModal/method=dialog/Escape/inert/name/focus behavior가 사라집니다.", result: "positioning은 widget semantics를 만들지 않습니다." },
            { change: "dialog content를 viewport보다 길게 늘리고 200% zoom을 적용합니다.", prediction: "dialog 내부가 scroll되고 actions에 접근할 수 있어야 합니다.", result: "fixed height 대신 max-block-size와 overflow strategy가 필요합니다." },
          ],
          sourceRefs: ["web-modal-absolute-source", "web-modal-fixed-source", "whatwg-dialog", "wai-dialog-pattern", "wai-dialog-technique"],
        },
      ],
      diagnostics: [
        { symptom: "modal이 보이는데 Tab이 background link로 이동하고 screen reader가 page와 dialog를 동시에 탐색한다.", likelyCause: "fixed div와 dim CSS만 사용하고 modal semantics/inert/focus lifecycle을 구현하지 않았습니다.", checks: ["element가 dialog showModal 또는 role/aria-modal인지 확인합니다.", "Tab/Shift+Tab/Escape/close/focus return을 test합니다.", "background accessibility tree/focusability를 확인합니다."], fix: "가능하면 native dialog.showModal을 사용하고 name·inside focus·close path·return focus를 구현합니다.", prevention: "modal component에 APG keyboard/focus E2E와 background inert assertion을 둡니다." },
      ],
    },
    {
      id: "positioning-responsive-logical",
      title: "positioning은 logical coordinates·content size·writing mode·zoom·scroll을 함께 견뎌야 합니다",
      lead: "top/left pixel과 fixed width/height로 맞춘 screenshot보다 inline/block 방향과 intrinsic content를 기준으로 배치합니다.",
      explanations: [
        "inset-inline-start/end와 inset-block-start/end는 writing mode와 direction에 따라 물리 edge가 바뀝니다. badge를 항상 text 시작/끝에 두는 의도라면 left/right보다 logical property가 국제화에 견고합니다.",
        "translate(-50%,-50%) centering에서 percentage는 transform reference box 자기 크기를 기준으로 하므로 top/left 50% containing block 기준과 결합해 중앙이 됩니다. 그러나 content가 viewport보다 크면 edge가 잘릴 수 있어 modal에는 max size/scroll 또는 Grid place-items/top layer를 함께 사용합니다.",
        "positioned box의 percentage size/inset은 containing block에 의존하고 auto margin·shrink-to-fit·intrinsic size가 계산에 참여합니다. width/height를 모두 fixed로 두지 않고 min()/max()/clamp(), max-inline-size, max-block-size를 사용합니다.",
        "absolute/fixed visual 위치와 DOM reading/focus order는 다릅니다. toast를 화면 top에 보여도 source 끝이면 screen reader announcement/focus behavior를 별도로 제공하고, CSS order/position으로 logical task 순서를 숨기지 않습니다.",
        "scrollbar·zoom·font loading·dynamic error가 geometry를 바꾸므로 ResizeObserver/positioning library를 고려하되 layout thrashing을 피합니다. style write와 geometry read를 반복하면 forced synchronous layout이 생길 수 있습니다.",
      ],
      concepts: [
        { term: "logical inset", definition: "writing mode의 inline/block 시작·끝 기준으로 positioned offset을 지정하는 inset-inline/block property입니다.", detail: ["LTR/RTL/vertical writing에 대응합니다.", "물리 top/right/bottom/left와 섞을 때 over-constraint를 주의합니다."] },
        { term: "shrink-to-fit/intrinsic sizing", definition: "absolute 등 특정 formatting에서 available space와 min/max content contribution으로 auto inline size가 결정되는 sizing behavior입니다.", detail: ["고정 width가 없어도 box가 계산됩니다.", "긴 unbreakable content를 test합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "RTL에서 badge가 text 시작 쪽이 아니라 반대 edge에 남고 content와 겹친다.", likelyCause: "left/right physical inset과 padding을 LTR 기준으로 hard-code했습니다.", checks: ["dir=rtl과 vertical writing fixture를 적용합니다.", "computed inset-inline-start/end를 확인합니다.", "long translation/zoom을 test합니다."], fix: "의도에 맞는 logical inset/padding/margin으로 전환하고 physical media-specific 예외만 명시합니다.", prevention: "LTR/RTL/long-label screenshot+geometry regression을 component test에 둡니다." },
      ],
    },
    {
      id: "top-layer-dialog-stacking-focus-security",
      title: "top layer는 z-index 경쟁을 벗어나지만 modal의 focus·inert·보안 책임은 남습니다",
      lead: "dialog를 화면 중앙에 그리는 것과 사용자 interaction을 modal로 만드는 일을 분리하고, stacking context tree와 top-layer lifecycle을 실제 browser state로 검증합니다.",
      explanations: [
        "position과 z-index는 같은 stacking context 안에서만 직접 비교됩니다. transform·opacity·isolation·filter 등은 새 context를 만들 수 있어 child의 매우 큰 z-index도 parent context 밖 sibling을 이기지 못합니다. DevTools Layers와 stacking context badge에서 ancestor chain을 먼저 찾습니다.",
        "`dialog.showModal()`은 element를 top layer에 올리고 나머지 document를 inert한 modal interaction으로 만듭니다. top layer는 author stacking context 밖 별도 순서를 가지므로 arbitrary z-index escalation보다 강합니다. `::backdrop`도 top-layer entry와 함께 paint됩니다.",
        "top layer가 접근성을 자동 완성하지는 않습니다. dialog에는 accessible name, 목적에 맞는 description, 초기 focus, Tab containment, Escape/cancel, close action, invoker로 focus 복귀가 필요합니다. 긴 content에서는 첫 paragraph나 heading에 tabindex=-1을 두는 전략도 검토합니다.",
        "fixed position은 보통 viewport를 containing block으로 하지만 transformed ancestor 등은 fixed containing block을 바꿀 수 있습니다. top-layer dialog는 normal ancestor clipping·stacking과 다른 규칙을 가지므로 custom fixed overlay와 동일하다고 추론하지 말고 실제 rect·hit test를 봅니다.",
        "modal은 authorization boundary가 아닙니다. overlay 뒤 control을 inert하게 만들어도 API 권한은 server가 확인해야 하고, DOM에 민감 data를 미리 넣어 CSS로 가리지 않습니다. iframe embedding·clickjacking은 CSP frame-ancestors 같은 응답 정책으로 다룹니다.",
      ],
      concepts: [
        { term: "top layer", definition: "fullscreen·modal dialog·popover 등이 document stacking contexts 위에서 정해진 순서로 그려지는 browser-managed layer입니다.", detail: ["z-index 숫자 경쟁과 다릅니다.", "entry마다 backdrop을 가질 수 있습니다."] },
        { term: "modal focus lifecycle", definition: "열기 전 invoker 기억, 초기 focus, 내부 순환, 닫기와 focus 복귀까지의 interaction 계약입니다.", detail: ["visible centering과 별개입니다.", "keyboard·screen reader로 검증합니다."] },
        { term: "stacking context atomicity", definition: "한 stacking context의 descendants가 외부 sibling과 개별적으로 섞이지 않고 context 전체가 한 단위로 쌓이는 성질입니다.", detail: ["child z-index만 키워 해결할 수 없습니다.", "ancestor trigger를 찾아야 합니다."] },
      ],
      codeExamples: [
        {
          id: "top-layer-dialog-over-transform-proof",
          title: "transform stacking context 안 dialog의 top-layer·focus·hit-test 검증",
          language: "html",
          filename: "top-layer-dialog.html",
          purpose: "transformed ancestor 아래 선언된 dialog가 showModal 후 top layer와 modal focus lifecycle을 얻는지 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>top layer dialog</title>\n  <style>\n    body { margin: 0; min-block-size: 100vh; }\n    .context { position: relative; z-index: 1; transform: translateZ(0); }\n    dialog { position: fixed; box-sizing: border-box; inline-size: 240px; padding: 20px; border: 2px solid navy; }\n    dialog::backdrop { background: rgb(0 0 0 / .4); }\n  </style>\n</head>\n<body>\n  <main class=\"context\"><button id=\"open\" type=\"button\">설정 열기</button><dialog id=\"settings\" aria-labelledby=\"title\"><h1 id=\"title\">설정</h1><button id=\"close\" type=\"button\" autofocus>닫기</button></dialog></main>\n  <pre id=\"result\"></pre>\n  <script>\n    const dialog = document.querySelector('#settings');\n    dialog.showModal();\n    const rect = dialog.getBoundingClientRect();\n    const centerNode = document.elementFromPoint(rect.left + rect.width / 2, rect.top + rect.height / 2);\n    const style = getComputedStyle(dialog);\n    document.querySelector('#result').textContent = [\n      `open=${dialog.open}`,\n      `modal=${dialog.matches(':modal')}`,\n      `active=${document.activeElement.id}`,\n      `position=${style.position}`,\n      `z-index=${style.zIndex}`,\n      `hit-test-inside=${dialog.contains(centerNode)}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-10", explanation: "ancestor stacking context와 fixed dialog/backdrop를 의도적으로 함께 둡니다." },
            { lines: "13-15", explanation: "invoker·accessible heading·autofocus close button을 semantic dialog에 연결합니다." },
            { lines: "18-22", explanation: "showModal 뒤 rect center hit test와 computed positioning을 읽습니다." },
            { lines: "23-30", explanation: "open/modal/focus/position/z-index/hit-test state를 정확히 출력합니다." },
          ],
          run: { environment: ["HTML dialog와 :modal을 지원하는 현대 Chromium"], command: "browser에서 top-layer-dialog.html을 열고 결과 확인" },
          output: { value: "open=true\nmodal=true\nactive=close\nposition=fixed\nz-index=auto\nhit-test-inside=true", explanation: ["showModal이 open과 :modal state를 만들고 autofocus close button으로 focus를 이동합니다.", "author z-index가 auto여도 top layer에서 ancestor stacking context 위에 표시됩니다.", "dialog 중심 hit test가 dialog subtree를 반환합니다."] },
          experiments: [
            { change: "showModal을 show로 바꿉니다.", prediction: "open은 true지만 :modal은 false이고 나머지 document가 inert하지 않습니다.", result: "modeless display와 modal behavior를 구분합니다." },
            { change: "dialog를 일반 div와 z-index:999999로 바꿉니다.", prediction: "ancestor stacking context·clipping에 갇힐 수 있고 focus/inert lifecycle이 자동 제공되지 않습니다.", result: "큰 z-index는 modal primitive가 아닙니다." },
            { change: "close 후 open button focus 복귀를 구현합니다.", prediction: "document.activeElement가 invoker가 됩니다.", result: "닫기까지가 modal acceptance test입니다." },
          ],
          sourceRefs: ["web-position-relative-source", "web-position-fixed-source", "whatwg-dialog", "wai-dialog-pattern", "css-position-3"],
        },
      ],
      diagnostics: [
        { symptom: "z-index를 계속 키워도 modal이 transformed header 아래에 남는다.", likelyCause: "modal이 낮은 ancestor stacking context 안에 있고 top layer가 아닌 custom div입니다.", checks: ["ancestor transform·opacity·isolation을 찾습니다.", "DevTools stacking context tree를 확인합니다.", "dialog.matches(':modal')과 top-layer primitive 사용 여부를 봅니다."], fix: "가능하면 native dialog showModal을 사용하고 custom overlay라면 portal 위치와 full focus/inert lifecycle을 명시합니다.", prevention: "nested transform fixture와 keyboard modal E2E를 component CI에 둡니다." },
      ],
    },
    {
      id: "sticky-scrollport-containing-block-performance",
      title: "sticky는 nearest scrollport와 inset·containing block·overflow chain을 함께 계산합니다",
      lead: "viewport에 붙는다는 암기 대신 어떤 ancestor가 scroll container인지, sticky view rectangle과 parent boundary가 어디인지 측정합니다.",
      explanations: [
        "sticky box는 normal flow 자리를 유지하면서 nearest scrolling mechanism의 scrollport와 inset에 따라 이동합니다. 의도하지 않은 ancestor의 overflow:auto·hidden이 viewport 대신 기준이 될 수 있습니다. overflow가 실제로 scroll되지 않아도 sticky 기준을 바꾸는지 확인합니다.",
        "sticky가 작동하려면 관련 축 inset이 auto가 아니어야 하고 scroll할 여유와 containing block 범위가 있어야 합니다. parent height가 header와 같거나 앞뒤 content가 없으면 붙을 이동 구간이 없습니다. `inset-block-start`를 사용하면 writing mode 변화에 의도를 보존합니다.",
        "fixed·absolute containing block도 ancestor transform·filter·contain에 의해 달라질 수 있습니다. Elements에서 offsetParent 하나만 보고 결론내리지 말고 specification trigger와 rectangle coordinate를 확인합니다. getBoundingClientRect는 viewport physical 좌표입니다.",
        "sticky header의 background·z-index가 없으면 아래 content가 비쳐 읽기 어렵고 focus target이 가려질 수 있습니다. skip link·anchor 이동에는 scroll-margin-block-start를 제공하고 400% zoom에서 sticky 영역이 viewport 대부분을 가리지 않는지 봅니다.",
        "scroll event마다 rect를 읽고 style을 쓰면 forced layout과 jank가 생깁니다. CSS sticky를 우선하고 IntersectionObserver가 필요한 state class만 갱신하며 passive listener와 Performance trace로 확인합니다. overlay로 UI를 가리는 것은 접근 통제나 clickjacking 방어가 아닙니다.",
      ],
      concepts: [
        { term: "sticky view rectangle", definition: "sticky inset과 nearest scrollport로 만들어져 box 위치를 제한하는 rectangle입니다.", detail: ["scroll container 선택이 핵심입니다.", "containing block 밖으로 벗어나지 않습니다."] },
        { term: "scrollport", definition: "scroll container에서 사용자가 볼 수 있는 padding-box 기반 영역입니다.", detail: ["viewport와 같지 않을 수 있습니다.", "overflow chain을 따라 찾습니다."] },
        { term: "scroll occlusion", definition: "fixed/sticky UI가 anchor target·focus indicator·본문을 가리는 문제입니다.", detail: ["scroll-margin/padding으로 완화합니다.", "zoom과 keyboard에서 검증합니다."] },
      ],
      codeExamples: [
        {
          id: "sticky-nearest-scrollport-proof",
          title: "nearest overflow container에서 sticky inset geometry 검증",
          language: "html",
          filename: "sticky-scrollport.html",
          purpose: "nested scroller를 programmatic scroll하고 sticky header의 physical offset과 logical inset을 측정합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>sticky scrollport</title>\n  <style>\n    body { margin: 0; }\n    .scroller { box-sizing: border-box; inline-size: 240px; block-size: 120px; overflow: auto; border: 2px solid navy; }\n    .sticky { position: sticky; inset-block-start: 0; block-size: 30px; background: white; z-index: 1; }\n    .content { block-size: 300px; background: linear-gradient(lavender, lightblue); }\n  </style>\n</head>\n<body>\n  <section class=\"scroller\" aria-label=\"학습 목록\"><h1 class=\"sticky\">목차</h1><div class=\"content\"></div></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const scroller = document.querySelector('.scroller');\n    const sticky = document.querySelector('.sticky');\n    scroller.scrollTop = 80;\n    requestAnimationFrame(() => {\n      const offset = Math.round(sticky.getBoundingClientRect().top - scroller.getBoundingClientRect().top);\n      const style = getComputedStyle(sticky);\n      document.querySelector('#result').textContent = [\n        `scroll-top=${scroller.scrollTop}`,\n        `sticky-offset=${offset}`,\n        `position=${style.position}`,\n        `overflow-y=${getComputedStyle(scroller).overflowY}`,\n        `inset-block-start=${style.insetBlockStart}`,\n        `stuck=${offset === 2}`\n      ].join('\\n');\n    });\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "6-10", explanation: "120px bordered scroller, logical inset sticky header와 tall content를 만듭니다." },
            { lines: "13-15", explanation: "heading semantics를 유지한 sticky header를 nested scroll container에 둡니다." },
            { lines: "18-22", explanation: "scrollTop 80을 적용하고 다음 animation frame에 geometry를 측정합니다." },
            { lines: "23-31", explanation: "border 안 2px offset·overflow·logical inset과 stuck invariant를 출력합니다." },
          ],
          run: { environment: ["position:sticky를 지원하는 현대 Chromium"], command: "browser에서 sticky-scrollport.html을 열고 결과 확인" },
          output: { value: "scroll-top=80\nsticky-offset=2\nposition=sticky\noverflow-y=auto\ninset-block-start=0px\nstuck=true", explanation: ["scrollTop이 80이어도 header는 nearest scrollport의 border 안 top 2px에 붙습니다.", "computed position과 logical inset은 sticky/0px입니다.", "viewport가 아니라 nested overflow container가 기준입니다."] },
          experiments: [
            { change: "scroller overflow를 visible로 바꿉니다.", prediction: "nested scrollTop이 동작하지 않고 sticky 기준이 상위 scrollport로 이동합니다.", result: "nearest scrolling mechanism이 기준을 결정합니다." },
            { change: "inset-block-start를 auto로 바꿉니다.", prediction: "해당 축에서 normal relative처럼 동작해 top에 붙지 않습니다.", result: "sticky에는 non-auto inset이 필요합니다." },
            { change: "scroller block-size를 content보다 크게 만듭니다.", prediction: "scroll 여유가 없어 sticky 이동을 관찰할 수 없습니다.", result: "작동 실패와 이동 구간 부재를 구분합니다." },
          ],
          sourceRefs: ["web-position-sticky-source", "css-position-3"],
        },
      ],
      diagnostics: [
        { symptom: "sticky header가 viewport가 아니라 작은 wrapper 안에서만 붙거나 전혀 움직이지 않는다.", likelyCause: "중간 ancestor overflow가 nearest scrollport를 만들었거나 inset/scroll range가 없습니다.", checks: ["ancestor overflow chain을 위로 추적합니다.", "relevant axis inset과 parent height를 확인합니다.", "scroller scrollHeight/clientHeight와 rect offset을 기록합니다."], fix: "의도한 scroll owner에 overflow를 두고 logical inset과 충분한 scroll range를 제공하며 불필요한 clipping wrapper를 제거합니다.", prevention: "nested overflow·zoom·anchor focus fixture를 sticky regression에 포함합니다." },
      ],
    },
    {
      id: "position-debugging-workflow",
      title: "위치·겹침 문제는 flow→containing block→scrollport→stacking context→clip→top layer 순서로 진단합니다",
      lead: "숫자를 바꾸기 전에 각 box가 참여하는 coordinate·paint system을 tree로 그립니다.",
      explanations: [
        "먼저 position computed value와 normal-flow 여부, original slot을 확인합니다. absolute/fixed면 containing block 후보 ancestor의 position/transform/filter/contain/will-change를 root까지 기록합니다. rect 차이와 offsetParent는 증거로 사용합니다.",
        "sticky면 scroll ancestor의 overflow, clientHeight/scrollHeight/scrollTop, sticky inset과 containing parent rect를 scroll 전후 측정합니다. page scroll과 nested scroll을 혼동하지 않습니다.",
        "겹침이면 각 element에서 root까지 stacking-context trigger와 z-index를 tree로 그립니다. 같은 context의 stack level인지 parent contexts가 먼저 경쟁하는지 확인하고 overflow:clip/hidden, clip-path, mask가 자르는지도 봅니다.",
        "dialog/popover가 top layer인지 :modal/:popover-open state와 DevTools top-layer 표시로 확인합니다. top layer element를 일반 z-index로 이기려 하지 않습니다.",
        "geometry API getBoundingClientRect, elementFromPoint/elementsFromPoint, VisualViewport, DevTools Layout/Layers/scroll badge를 사용합니다. production issue에는 viewport·zoom·scroll position·writing mode·font load·active focus를 포함합니다.",
      ],
      concepts: [
        { term: "hit testing", definition: "viewport point에서 pointer event 대상이 될 painted element를 결정하는 과정입니다.", detail: ["elementFromPoint로 top target을 관찰할 수 있습니다.", "pointer-events·top layer·clip도 영향을 줍니다."] },
        { term: "geometry snapshot", definition: "특정 viewport/scroll/zoom 상태에서 관련 element의 bounding rect·computed position·z-index·overflow를 기록한 진단 자료입니다.", detail: ["재현 가능한 비교를 만듭니다.", "layout 변화 전후 regression에 사용합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "DevTools에서 z-index를 올릴 때마다 잠깐 보이지만 다른 page/state에서 다시 가려진다.", likelyCause: "stacking context/containing block/clip architecture를 고치지 않고 local 숫자만 escalation했습니다.", checks: ["context tree와 clip ancestor를 작성합니다.", "hit-test top element와 parent z-index를 확인합니다.", "overlay가 top layer/portal이 필요한지 결정합니다."], fix: "overlay ownership과 context/isolation/portal/top-layer architecture를 바로잡고 z-index token을 제한된 layer scale로 사용합니다.", prevention: "z-index token registry와 nested overlay fixture, context-tree review를 둡니다." },
      ],
      expertNotes: [
        "CSS Anchor Positioning은 anchor-name/position-anchor/position-area/position-try로 tooltip/popover fallback을 platform에 맡길 수 있지만 target browser와 top-layer/overflow/accessibility behavior를 검토합니다.",
        "popover attribute는 light-dismiss/top-layer behavior를 제공하지만 modal이 아니며 background를 inert로 만들지 않습니다. tooltip/menu/dialog의 interaction requirement에 맞는 primitive를 선택합니다.",
      ],
    },
  ],
  lab: {
    title: "fixed div 로그인 overlay를 native dialog로 교체하고 z-index/sticky/viewport 회귀까지 해결하기",
    scenario: "기존 app은 transformed shell 안 fixed modal, sticky header, z-index 999999 tooltip이 섞여 mobile에서 잘리고 keyboard focus가 background로 빠집니다. 시각 좌표와 widget behavior를 함께 재설계합니다.",
    setup: ["원본 position/modal/z-index file 7개를 read-only evidence로 준비합니다.", "desktop/mobile visual viewport, 320px·200% zoom, keyboard, DevTools Layout/Layers/Accessibility를 준비합니다.", "flow/containing-block/scrollport/stacking-context/top-layer tree를 기록할 template를 만듭니다."],
    steps: [
      "각 positioned element의 computed position·normal-flow 여부·inset·containing block·offsetParent·rect를 기록합니다.",
      "relative spacing misuse와 absolute page layout을 normal flow/Grid/Flex로 돌리고 badge/overlay만 positioning에 남깁니다.",
      "fixed overlay ancestor의 transform/filter/contain과 overflow clip을 제거하거나 dialog top layer로 이동합니다.",
      "sticky header의 actual scroll container·inset·parent boundary와 anchor scroll-margin을 검증합니다.",
      "stacking context tree와 overlap hit-test를 작성해 z-index escalation 없이 overlay token/context를 정리합니다.",
      "div modal을 dialog.showModal, visible title/labels, initial focus, Tab containment, Escape/cancel, return focus로 교체합니다.",
      "320px·200% zoom·dvh/virtual keyboard·RTL·safe area에서 dialog/close/action/content scroll을 확인합니다.",
      "geometry·elementFromPoint·:modal·activeElement·background inert·focus return assertions를 E2E에 추가합니다.",
    ],
    expectedResult: ["positioning이 필요한 box만 flow 밖에 있고 content spacing/layout은 normal flow로 안정적입니다.", "모든 absolute/fixed/sticky box의 기준 rectangle을 증거로 설명할 수 있습니다.", "sticky가 intended scroll container에서 작동하고 content/anchor를 가리지 않습니다.", "overlay z-order가 context token/architecture로 해결되어 임의 큰 숫자가 없습니다.", "dialog는 top layer·inert·name·inside focus·Escape·visible close·return focus를 충족합니다.", "mobile/zoom/keyboard/RTL/safe area에서 content와 action이 잘리지 않습니다."],
    cleanup: ["실험용 transform hack·z-index 999999·fixed height·manual aria-hidden/inert를 제거합니다.", "DevTools emulation/scroll position을 reset하고 clean navigation부터 E2E를 다시 실행합니다."],
    extensions: ["non-modal tooltip은 popover/anchor positioning으로 구현하고 dialog와 inert 차이를 비교합니다.", "nested dialog/confirm workflow와 destructive least-action focus를 APG 기준으로 test합니다.", "visualViewport resize를 이용한 on-screen keyboard 대응을 측정하되 native scroll behavior와 충돌하지 않게 설계합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "relative·absolute 세 box의 flow slot과 containing block을 측정하세요.", requirements: ["static/relative/absolute sibling을 같은 container에 둡니다.", "offsetParent·offsetTop·bounding rect·computed inset을 출력합니다.", "relative offset 전후 sibling 위치를 비교합니다.", "containing root position을 제거한 결과를 기록합니다."], hints: ["relative는 원래 slot을 남깁니다.", "absolute parent 기준은 DOM parent가 아니라 containing block입니다."], expectedOutcome: "각 box의 coordinate 기준과 flow 영향, overlap을 정확한 숫자로 설명합니다.", solutionOutline: ["원본 slot/rect table을 먼저 만듭니다.", "한 property씩 바꾸며 clean reload합니다."] },
    { difficulty: "응용", prompt: "sticky header·absolute badge·tooltip의 z-index/scroll 문제를 수정하세요.", requirements: ["scroll container와 sticky boundary를 측정합니다.", "badge에 logical inset과 stable containing block을 사용합니다.", "stacking context tree와 elementFromPoint 증거를 만듭니다.", "arbitrary z-index escalation과 overflow clip을 제거합니다.", "320px·RTL·zoom을 test합니다."], hints: ["tooltip child 숫자보다 parent context를 먼저 봅니다.", "sticky는 inset과 이동할 공간이 필요합니다."], expectedOutcome: "scroll/RTL/dynamic content에서도 header·badge·tooltip이 의도 위치와 hit order를 유지합니다.", solutionOutline: ["flow→containing block→scrollport→context→clip 순서로 조사합니다.", "overlay owner/portal 필요를 결정합니다."] },
    { difficulty: "설계", prompt: "app 전체 overlay system의 dialog·popover·tooltip·toast·menu position/focus/z-index architecture를 설계하세요.", requirements: ["각 primitive의 modal/non-modal·top layer·dismiss·focus·inert 계약을 정의합니다.", "portal/containing block/anchor/scroll/clip strategy를 설명합니다.", "z-index/context/isolation token과 nested overlay policy를 만듭니다.", "mobile visual viewport·safe area·zoom·RTL을 포함합니다.", "geometry/hit-test/keyboard/screen reader/performance E2E를 설계합니다."], hints: ["모든 overlay가 modal이거나 z-index 최대일 필요는 없습니다.", "native dialog/popover와 custom behavior 경계를 먼저 정합니다."], expectedOutcome: "팀이 임의 fixed 좌표·focus trap·z-index 숫자를 반복하지 않고 일관된 overlay infrastructure를 구현할 수 있습니다.", solutionOutline: ["interaction taxonomy와 lifecycle state table을 먼저 만듭니다.", "top-layer/portal root와 focus owner를 architecture decision으로 고정합니다."] },
  ],
  reviewQuestions: [
    { question: "relative box를 top:50px 이동하면 다음 sibling도 50px 내려가나요?", answer: "아닙니다. 원래 flow slot은 남고 visual box만 offset되어 sibling과 겹칠 수 있습니다." },
    { question: "absolute element는 relative인 직접 parent를 항상 기준으로 하나요?", answer: "직접 parent가 아니라 containing block을 형성하는 nearest 적합 ancestor를 기준으로 하며 transform/contain 등도 영향을 줄 수 있습니다." },
    { question: "ancestor가 있으면 fixed가 viewport 기준이 아닌가요?", answer: "일반 ancestor는 보통 영향이 없지만 transform/filter/contain 등은 fixed containing block을 바꿀 수 있습니다." },
    { question: "sticky가 작동하려면 무엇이 필요한가요?", answer: "목적 축의 non-auto inset, 실제 scroll range, 올바른 scroll container와 containing-block 이동 공간이 필요합니다." },
    { question: "z-index 999999면 모든 element 위에 오나요?", answer: "아닙니다. 자신의 stacking context 안에서만 경쟁하며 낮은 parent context를 벗어나지 못합니다." },
    { question: "transform:translateZ(0)은 z-index에 영향이 없나요?", answer: "transform은 containing block과 stacking context를 만들 수 있어 fixed/overlay와 z-order를 바꿀 수 있습니다." },
    { question: "fixed 중앙 div에 aria-modal=true만 추가하면 modal인가요?", answer: "아닙니다. dialog name, inert/background 차단, inside focus/Tab, Escape/close, return focus behavior가 필요합니다." },
    { question: "dialog open attribute와 showModal은 같은가요?", answer: "아닙니다. showModal은 modal mode와 top layer/inert behavior를 제공하며 open만 설정한 dialog는 modal이 아닙니다." },
    { question: "top/left 대신 logical inset을 쓰는 이유는 무엇인가요?", answer: "inline/block start/end 의도를 writing mode와 RTL에서도 유지하기 위해서입니다." },
    { question: "top layer dialog에 z-index:999999가 꼭 필요한가요?", answer: "아닙니다. top layer는 document stacking contexts 밖에서 관리되므로 arbitrary z-index escalation이 핵심이 아닙니다." },
    { question: "dialog.show()와 showModal()은 interaction이 같은가요?", answer: "아닙니다. show는 modeless이고 showModal은 :modal·top layer·나머지 document inert behavior를 제공합니다." },
    { question: "modal을 닫은 뒤 focus는 어디로 가야 하나요?", answer: "일반적으로 열었던 invoker 또는 workflow상 다음 logical control로 명시적으로 복귀해야 합니다." },
    { question: "overflow:hidden ancestor는 sticky 기준과 무관한가요?", answer: "아닙니다. scrolling mechanism을 만들어 nearest sticky scrollport 선택을 바꿀 수 있습니다." },
    { question: "sticky에 inset이 모두 auto이면 어떻게 되나요?", answer: "해당 축에서 sticky offset이 생기지 않아 사실상 relative처럼 normal position에 머뭅니다." },
    { question: "overlay로 뒤 UI를 가리면 API 권한도 보호되나요?", answer: "아닙니다. inert·paint는 client interaction일 뿐이며 server가 각 요청의 authorization을 검증해야 합니다." },
  ],
  completionChecklist: [
    "position scheme별 normal-flow 참여와 original slot을 확인했다.",
    "absolute/fixed containing block을 ancestor computed property·offsetParent·rect로 증명했다.",
    "logical inset과 content-driven size를 사용하고 over-constraint를 제거했다.",
    "sticky의 actual scroll container·inset·scroll range·parent boundary를 측정했다.",
    "stacking-context tree와 hit-test로 z-index 승자를 설명하고 arbitrary 큰 숫자를 제거했다.",
    "overlay clip/transform context를 정리하고 필요한 경우 top layer/portal을 사용했다.",
    "modal dialog의 name·inert·inside focus·Tab·Escape·visible close·return focus를 검증했다.",
    "320px·200% zoom·dynamic viewport·keyboard·safe area·RTL에서 geometry와 task를 확인했다.",
    "ancestor stacking-context trigger를 추적하고 child z-index escalation 대신 구조적 원인을 해결했다.",
    "showModal의 top-layer·:modal·backdrop·autofocus state를 실제 browser에서 확인했다.",
    "modal close·cancel·Escape 후 invoker focus 복귀와 screen reader name을 검증했다.",
    "nearest overflow scrollport와 sticky view rectangle을 rect·scrollTop으로 측정했다.",
    "sticky/fixed UI가 anchor·focus를 가리지 않도록 scroll-margin/padding과 zoom을 검사했다.",
    "scroll listener의 geometry read/write를 줄이고 CSS sticky·observer로 성능을 검증했다.",
    "overlay·inert·z-index를 authorization 또는 secret hiding 수단으로 사용하지 않았다.",
  ],
  nextSessions: ["css-08-responsive-viewport-media"],
  sources: [
    { id: "web-position-relative-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex01_position.html", usedFor: ["static/relative", "flow slot", "top/left offset", "overlap"], evidence: "세 section의 relative 이동과 네 physical inset 선언을 audit해 normal-flow slot·over-constraint·logical inset으로 교정했습니다." },
    { id: "web-position-absolute-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex02_positon.html", usedFor: ["absolute", "relative ancestor", "out-of-flow", "containing block"], evidence: "ab1/ab2/#box2의 parent 설명을 읽고 body 단순화 대신 formal containing-block 추적으로 확장했습니다." },
    { id: "web-position-fixed-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex03_position.html", usedFor: ["fixed overlap", "absolute/fixed comparison", "ancestor boundary"], evidence: "box3/box4 겹침을 일반 viewport behavior와 transform-containing-block 예외로 교정했습니다." },
    { id: "web-position-sticky-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex04_position.html", usedFor: ["sticky", "scroll content", "bottom inset", "float"], evidence: "긴 앞/뒤 content와 sticky box를 scroll container·inset·parent boundary diagnostic으로 확장했습니다." },
    { id: "web-modal-absolute-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex05_position_modal.html", usedFor: ["absolute 50%/translate center", "fixed size", "modal definition"], evidence: "시각 중앙 div와 actual modal widget의 semantic/focus 차이를 capstone example의 baseline으로 사용했습니다." },
    { id: "web-modal-fixed-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex06_position_modal2.html", usedFor: ["fixed modal", "background", "login fields", "shadow/radius"], evidence: "fixed login overlay를 native dialog·labels·responsive sizing·backdrop·focus lifecycle로 재구성했습니다." },
    { id: "web-z-index-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day05/ex07_z_index.html", usedFor: ["z-index", "overlapping absolute boxes", "negative image", "CSS background comparison"], evidence: "10/9/8 stacking과 negative img를 stacking-context atomicity·hit-test·background semantics로 확장했습니다." },
    { id: "css-position-3", repository: "W3C CSS Working Group", path: "TR/css-position-3/", publicUrl: "https://www.w3.org/TR/css-position-3/", usedFor: ["five position schemes", "containing block", "inset", "sticky view rectangle", "stacking context/z-index"], evidence: "2026-07-12 기준 CSS Positioned Layout Level 3의 current definitions를 position·sticky·stacking 설명의 기준으로 확인했습니다." },
    { id: "whatwg-dialog", repository: "WHATWG HTML Standard", path: "multipage/interactive-elements.html#the-dialog-element", publicUrl: "https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element", usedFor: ["dialog", "showModal", "top layer", "close/cancel", "focus/inert"], evidence: "native dialog modal lifecycle과 method=dialog behavior를 example/diagnostics에 반영했습니다." },
    { id: "wai-dialog-pattern", repository: "W3C WAI-ARIA Authoring Practices", path: "patterns/dialog-modal/", publicUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/", usedFor: ["inside focus", "Tab containment", "Escape", "name", "return focus"], evidence: "modal dialog keyboard/focus/name/description 판단을 production acceptance criteria로 사용했습니다." },
    { id: "wai-dialog-technique", repository: "W3C Web Accessibility Initiative", path: "WCAG21/Techniques/html/H102", publicUrl: "https://www.w3.org/WAI/WCAG21/Techniques/html/H102", usedFor: ["HTML dialog", "focus order", "return to invoker"], evidence: "HTML dialog sufficient technique의 focus lifecycle을 native example 검증에 반영했습니다." },
  ],
  sourceCoverage: {
    filesRead: 7,
    filesUsed: 7,
    uncoveredNotes: [
      "원본은 다섯 position mode와 modal/z-index를 시각적으로 충실히 보여 줍니다. formal containing block, transform/fixed exception, sticky scrollport, atomic stacking context, dialog top layer와 focus/inert는 최신 W3C/WHATWG/WAI 자료로 교정·보강했습니다.",
      "CSS Anchor Positioning/popover는 architecture 선택만 소개했으며 브라우저 target이 확정된 후 별도 modern overlay lab에서 상세 syntax를 확장합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
