import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-04-typography-color-icons"],
  slug: "css-04-typography-color-icons",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 4,
  title: "폰트, 웹폰트, 색상 체계와 아이콘 폰트",
  subtitle: "글자를 꾸미는 속성 모음에서 멈추지 않고, glyph 선택·상대 크기·line box·font loading·색 공간·대비·강제 색상·아이콘의 접근 가능한 이름을 하나의 렌더링 계약으로 이해합니다.",
  level: "기초",
  estimatedMinutes: 215,
  coreQuestion: "사용자의 기기·네트워크·확대·색상 설정이 달라도 본문과 아이콘이 빠르고 읽기 쉽고 의미 있게 남도록 폰트와 색을 어떻게 설계할까요?",
  summary: "webstudy의 색상, 시스템 폰트, Google 웹폰트, Font Awesome 원본 네 파일을 실제 Chromium에서 실행하고 계산 스타일·FontFaceSet·가상요소를 조사합니다. font-family fallback과 글자별 glyph 대체, em/rem과 unitless line-height, weight·style·variable font 축, @font-face와 FOIT/FOUT·font-display·subset·metrics override, RGB/HEX/HSL/alpha와 Oklch·Display P3, WCAG 대비·색상 단독 전달 금지·forced colors, 아이콘 폰트의 실패 모드와 inline SVG 경계를 초보부터 운영 수준까지 연결합니다.",
  objectives: [
    "font-family 목록이 앞에서부터 family와 glyph를 탐색하고 마지막 generic family로 대체되는 과정을 설명할 수 있다.",
    "px·em·rem·clamp를 문맥에 맞게 선택하고 unitless line-height의 상속 결과를 계산할 수 있다.",
    "font-weight·font-style과 variable font의 weight·width·slant·optical-size 축을 고수준 CSS 속성으로 제어할 수 있다.",
    "@font-face의 src·font-display·fallback과 Font Loading API를 이용해 로딩 성공·실패·FOIT·FOUT를 진단할 수 있다.",
    "named·HEX/HEXA·rgb/hsl·Oklab/Oklch·Display P3 색의 표현 범위와 alpha·opacity 차이를 설명할 수 있다.",
    "본문·큰 글자·UI 그래픽의 대비를 검사하고 색상 외 단서와 forced-colors 대응을 설계할 수 있다.",
    "장식·정보·기능 아이콘을 구분해 아이콘 폰트 또는 SVG를 선택하고 접근 가능한 이름을 제공할 수 있다.",
    "폰트·아이콘 CDN의 성능·CORS·CSP·무결성·개인정보·라이선스 경계를 검토할 수 있다.",
  ],
  prerequisites: [
    {
      title: "관계·속성·상태·가상요소 선택자",
      reason: "웹폰트와 아이콘 예제는 class·attribute·::before를 선택하고 :focus-visible·forced-colors 상태를 스타일합니다. 생성 콘텐츠에 핵심 의미를 숨기지 않는 원칙도 이어집니다.",
      sessionSlug: "css-03-combinators-attributes-pseudo",
    },
  ],
  keywords: ["font-family", "fallback", "system-ui", "font-size", "em", "rem", "line-height", "variable font", "@font-face", "font-display", "FOIT", "FOUT", "FontFaceSet", "RGB", "HEX", "Oklch", "contrast", "forced-colors", "icon font", "SVG"],
  chapters: [
    {
      id: "font-selection-fallback",
      title: "브라우저는 family 목록과 실제 glyph 지원 범위를 따라 글자마다 사용할 폰트를 고릅니다",
      lead: "font-family는 한 글꼴을 강제로 보장하는 명령이 아니라 사용할 수 있는 후보를 우선순위대로 제공하는 목록입니다.",
      explanations: [
        "원본 ex04는 '맑은 고딕', 돋움, 굴림, Arial, Helvetica, sans-serif 순서의 목록을 둡니다. 브라우저는 앞 후보가 설치·로드되었고 요청한 style/weight와 해당 Unicode glyph를 제공하면 사용합니다. family가 존재해도 한글 glyph가 없으면 그 문자 cluster만 다음 후보로 넘어갈 수 있어 한 줄에 여러 실제 폰트가 섞일 수 있습니다.",
        "공백이 있는 family 이름은 따옴표로 묶는 것이 안전합니다. 마지막에는 serif·sans-serif·monospace·system-ui 같은 generic family를 둬 모든 앞 후보가 실패했을 때 사용자 환경이 적절한 기본 폰트를 선택하게 합니다. generic 이름은 따옴표로 감싸지 않습니다.",
        "system-ui는 운영체제 UI에 익숙한 family를 요청하므로 별도 다운로드 없이 빠르게 렌더링되는 본문·관리 화면에 유용합니다. 다만 기기마다 모양과 metrics가 달라 pixel-identical 결과를 보장하지 않습니다. 제품 브랜드가 아니라 가독성과 native 느낌이 목표일 때 적합합니다.",
        "한글·라틴·숫자·emoji를 함께 시험합니다. 영문 샘플만 보고 웹폰트가 완전하다고 결론 내리면 한글에서 fallback이 일어나 글자 폭과 baseline이 달라질 수 있습니다. 네모 상자(tofu), 빠진 결합 문자, 깨진 emoji는 요청 family의 glyph coverage와 fallback chain을 먼저 확인합니다.",
        "Computed Style의 font-family는 선언된 후보 목록을 보여 줄 뿐 실제 각 glyph를 그린 face를 항상 직접 알려 주지는 않습니다. DevTools의 rendered fonts 정보, Network font 요청, FontFaceSet 상태를 함께 봅니다. screenshot만으로 family 이름을 추측하지 않습니다.",
      ],
      concepts: [
        { term: "font family list", definition: "사용할 수 있는 font family 후보를 우선순위대로 나열한 쉼표 구분 목록입니다.", detail: ["앞 family가 없거나 glyph를 제공하지 않으면 다음 후보를 찾습니다.", "마지막에 generic family를 둡니다."], analogy: "첫 식당이 닫혔거나 원하는 메뉴가 없으면 다음 식당으로 이동하는 후보 목록과 같습니다." },
        { term: "glyph fallback", definition: "선택한 face에 특정 문자 cluster를 그릴 glyph가 없을 때 다른 family의 face로 해당 부분을 렌더링하는 처리입니다.", detail: ["한 element 안에서도 여러 실제 face가 쓰일 수 있습니다.", "metrics 차이로 baseline·폭·줄바꿈이 바뀔 수 있습니다."] },
        { term: "generic family", definition: "sans-serif·serif·monospace·system-ui처럼 사용자 환경이 실제 설치 폰트로 해석하는 일반 family keyword입니다.", detail: ["따옴표를 쓰지 않습니다.", "fallback chain의 안전망 역할을 합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "개발자 PC에서는 한글이 원하는 모양인데 다른 운영체제에서는 폭·줄바꿈·모양이 달라진다.", likelyCause: "첫 family가 다른 기기에 없거나 한글 glyph가 없어 서로 다른 fallback face가 선택됐습니다.", checks: ["Rendered Fonts 또는 동등한 DevTools 정보에서 실제 face를 확인합니다.", "한글·라틴·숫자·emoji fixture를 각각 봅니다.", "font-family 마지막 generic 후보와 요청 weight/style을 확인합니다."], fix: "목적에 맞는 cross-platform system stack 또는 검증된 웹폰트와 명시적 generic fallback을 사용하고 metrics 차이에 견디는 layout을 만듭니다.", prevention: "Windows·macOS·Android와 느린 네트워크에서 visual regression을 수행하고 text container를 고정 pixel 폭에 과도하게 맞추지 않습니다." },
        { symptom: "일부 문자만 네모 상자나 다른 글꼴로 보여 한 단어 안에서 모양이 섞인다.", likelyCause: "첫 face의 unicode coverage에 해당 glyph가 없거나 요청한 subset이 로드되지 않았습니다.", checks: ["문자의 Unicode code point와 webfont unicode-range를 확인합니다.", "Network에서 필요한 subset 요청 성공 여부를 봅니다.", "family 후보별 glyph 지원과 emoji variation selector를 확인합니다."], fix: "필요한 언어·기호 subset을 제공하고 그 범위를 덮는 fallback family를 추가합니다.", prevention: "실제 지원 언어 corpus와 특수문자·combining mark·emoji 회귀 fixture를 둡니다." },
      ],
      comparisons: [
        { title: "본문 기본 family를 어떻게 구성할까요?", options: [
          { name: "system stack", chooseWhen: "빠른 첫 렌더링·OS 친화성·다운로드 최소화가 중요할 때", avoidWhen: "동일한 brand glyph 형태가 핵심일 때", tradeoffs: ["추가 font request가 없습니다.", "기기마다 실제 face와 metrics가 다릅니다.", "사용자의 언어·접근성 설정과 잘 어울릴 수 있습니다."] },
          { name: "web font + fallback", chooseWhen: "브랜드·다국어 glyph·숫자 형태를 제품이 통제해야 할 때", avoidWhen: "용량·라이선스·로딩 정책을 운영할 수 없을 때", tradeoffs: ["일관된 디자인과 glyph coverage를 제공할 수 있습니다.", "network·CORS·FOIT/FOUT·CLS 비용이 생깁니다.", "실패해도 읽히는 fallback이 반드시 필요합니다."] },
        ] },
      ],
    },
    {
      id: "relative-size-line-height",
      title: "font-size는 기준을 선택하고 line-height는 descendant의 크기에 맞게 다시 계산되도록 설계합니다",
      lead: "em은 부모의 계산 font-size, rem은 root의 계산 font-size를 기준으로 하며 unitless line-height는 각 descendant 크기에 곱해집니다.",
      explanations: [
        "원본에서 html 16px, h1 3em은 48px, p 2em은 32px입니다. parent 32px 안 child 1.5em은 48px이고 다시 nested 2em은 96px로 증폭됩니다. 반면 nested2 2rem은 중첩 깊이와 무관하게 root 16px의 두 배인 32px입니다. 이 계산을 손으로 할 수 있어야 예상치 못한 거대 텍스트를 찾을 수 있습니다.",
        "rem은 사이트 전체 typography scale과 spacing token에 안정적이고, em은 button padding·icon 크기처럼 component의 현재 글자 크기와 함께 비례해야 할 때 유용합니다. px 자체가 접근성 위반인 것은 아니며 browser zoom은 CSS pixel도 확대합니다. 다만 root font size를 고정하고 사용자 기본 크기를 무시하거나 container를 고정 높이로 잠가 확대를 막지 않습니다.",
        "responsive heading은 clamp(최소, 유동값, 최대)로 범위를 둘 수 있지만 viewport unit만 사용해 작은 화면에서 지나치게 작아지지 않게 rem 성분을 섞습니다. 200% 확대에서 text·label·control이 잘리거나 겹치지 않는지 실제로 검증합니다. 수식이 멋지다는 이유보다 읽기 범위와 line length를 기준으로 선택합니다.",
        "line-height:1.5 같은 unitless number는 상속될 때 number 그대로 내려가 각 descendant의 computed font-size에 곱해집니다. 16px text는 24px, 24px text는 36px line height가 됩니다. 반면 부모의 line-height:24px 또는 150%는 계산된 length가 상속될 수 있어 큰 child text에도 24px가 남아 glyph와 line box가 겹칠 수 있습니다.",
        "line-height:normal은 font metrics에 따라 결정돼 family fallback 전후 값과 line box가 달라질 수 있습니다. 본문은 대개 1.4~1.7 범위에서 글꼴·언어·폭을 실제로 읽어 조정하되 숫자를 법칙처럼 외우지 않습니다. 한글 조합, 위아래 첨자, inline icon이 잘리지 않는지도 봅니다.",
      ],
      concepts: [
        { term: "em", definition: "font-size에서는 부모의 computed font-size를, 다른 속성에서는 보통 현재 요소의 font-size를 기준으로 하는 font-relative length입니다.", detail: ["중첩 font-size에서 곱셈이 누적될 수 있습니다.", "component 내부 icon·padding 비례에 유용합니다."] },
        { term: "rem", definition: "root element의 em 기준, 일반적으로 root computed font-size에 비례하는 길이입니다.", detail: ["중첩 깊이와 무관한 전역 scale을 만듭니다.", "사용자 기본 크기·zoom과 함께 검증합니다."] },
        { term: "unitless line-height", definition: "길이 단위 없는 숫자를 현재 요소의 computed font-size에 곱해 preferred line height를 정하는 값입니다.", detail: ["number 자체가 상속됩니다.", "서로 다른 child font-size에 맞춰 재계산됩니다."], caveat: "너무 작은 값은 glyph·ruby·accent·inline control을 겹치게 할 수 있으므로 실제 콘텐츠로 검증합니다." },
      ],
      codeExamples: [
        {
          id: "relative-type-metrics",
          title: "rem·em 중첩과 unitless line-height 계산 확인",
          language: "html",
          filename: "type-metrics.html",
          purpose: "원본의 16→32→48→96px 계산을 component 문맥으로 재구성하고 browser computed value를 exact output으로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n<meta charset=\"utf-8\"><title>타이포그래피 계산</title>\n<style>\n  :root { font-size: 16px; }\n  body { font-family: system-ui, \"Segoe UI\", sans-serif; font-size: 1rem; line-height: 1.5; }\n  .card { font-size: 1.25rem; }\n  .card p { font-size: 0.8em; }\n  .card strong { font-size: 1.5em; }\n  .card .rem-note { font-size: 2rem; }\n</style>\n</head>\n<body>\n<section class=\"card\">\n  <p id=\"paragraph\">본문 <strong id=\"strong\">중요</strong></p>\n  <p class=\"rem-note\" id=\"rem-note\">루트 기준 메모</p>\n</section>\n<pre id=\"result\"></pre>\n<script>\n  const metric = (selector) => {\n    const style = getComputedStyle(document.querySelector(selector));\n    return `${style.fontSize}/${style.lineHeight}`;\n  };\n  document.querySelector(\"#result\").textContent = [\n    `root=${getComputedStyle(document.documentElement).fontSize}`,\n    `body=${metric(\"body\")}`,\n    `card=${metric(\".card\")}`,\n    `paragraph=${metric(\"#paragraph\")}`,\n    `strong=${metric(\"#strong\")}`,\n    `rem-note=${metric(\"#rem-note\")}`,\n    `family=${getComputedStyle(document.body).fontFamily}`,\n  ].join(\"\\n\");\n</script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-11", explanation: "root 16px와 body 1rem/1.5를 기준으로 card를 1.25rem=20px로 만듭니다. card p의 0.8em은 20×0.8=16px입니다." },
            { lines: "9-10", explanation: "strong 1.5em은 부모 p의 16px를 기준으로 24px, rem-note 2rem은 card 깊이와 무관하게 root 기준 32px입니다. 더 구체적인 .card .rem-note가 .card p 규칙을 이깁니다." },
            { lines: "20-24", explanation: "getComputedStyle로 각 element의 최종 font-size와 line-height를 읽습니다. 선언값이 아니라 cascade·상속·상대 단위 계산이 끝난 결과입니다." },
            { lines: "25-33", explanation: "root부터 descendant까지 exact metric과 선언된 family list를 한 줄씩 출력합니다. unitless 1.5가 16·20·24·32px에 각각 다시 곱해지는지 확인합니다." },
          ],
          run: { environment: ["UTF-8로 저장", "현대 Chromium 브라우저", "JavaScript 활성화", "기본 zoom 100%에서 exact CSS pixel 확인"], command: "browser에서 type-metrics.html 열기" },
          output: {
            value: "root=16px\nbody=16px/24px\ncard=20px/30px\nparagraph=16px/24px\nstrong=24px/36px\nrem-note=32px/48px\nfamily=system-ui, \"Segoe UI\", sans-serif",
            explanation: ["card의 20px는 root 16px×1.25이고 paragraph의 16px는 card 20px×0.8입니다.", "strong은 paragraph 16px×1.5=24px이고 line-height는 상속된 1.5×24px=36px입니다.", "rem-note는 2rem=32px이며 line-height는 48px입니다. 부모 card가 20px여도 rem 기준은 root입니다.", "family 출력은 후보 목록이며 실제 glyph face는 운영체제와 문자별 지원에 따라 달라질 수 있습니다."],
          },
          experiments: [
            { change: ".card .rem-note를 .rem-note로 낮춰 .card p와 specificity를 비교합니다.", prediction: ".card p가 더 구체적이어서 rem-note도 0.8em=16px가 됩니다.", result: "상대 단위 계산 전에 cascade winner가 먼저 결정됩니다." },
            { change: "body line-height를 24px로 바꿉니다.", prediction: "card·strong·rem-note도 상속된 24px line-height를 사용해 큰 글자의 줄 상자가 지나치게 좁아집니다.", result: "본문 상속에는 unitless number가 descendant 크기에 더 견고합니다." },
            { change: ":root font-size를 20px로 바꾸고 exact output을 다시 계산합니다.", prediction: "rem 기반 body/card/rem-note와 그 descendant em 값이 모두 비례해 커집니다.", result: "전역 scale과 component-local scale의 연결을 확인합니다." },
          ],
          sourceRefs: ["web-day04-font-source", "css-fonts-4", "css-values-3", "css-inline-3", "wcag22"],
        },
      ],
      diagnostics: [
        { symptom: "component를 중첩할수록 글자가 32→48→96px처럼 예상보다 급격히 커진다.", likelyCause: "여러 depth에서 font-size em 배율을 반복 적용해 곱셈이 누적됐습니다.", checks: ["부모 chain의 computed font-size를 위에서 아래로 기록합니다.", "각 em이 어느 부모 computed size를 기준으로 하는지 계산합니다.", "전역 heading scale인지 component-local 비례인지 구분합니다."], fix: "전역 typography는 rem/token으로 고정하고 정말 부모와 비례해야 하는 내부 요소만 em을 사용합니다.", prevention: "nested fixture와 computed metric test를 design-system 문서에 둡니다." },
        { symptom: "큰 글자·위첨자·한글 받침이 위아래 줄과 겹치거나 잘린다.", likelyCause: "부모에서 계산된 고정 length line-height가 큰 child에 상속됐거나 line-height를 1처럼 지나치게 낮췄습니다.", checks: ["parent와 child의 computed font-size/line-height를 비교합니다.", "overflow hidden·fixed height·vertical alignment를 확인합니다.", "fallback font·zoom 200%·실제 다국어 문장을 시험합니다."], fix: "본문 상속은 unitless line-height를 사용하고 fixed height/overflow를 제거한 뒤 glyph와 UI 요구에 맞는 값을 선택합니다.", prevention: "200% resize, 다국어 glyph, sub/sup, inline icon 회귀 테스트를 수행합니다." },
      ],
    },
    {
      id: "weight-style-variable-fonts",
      title: "weight·style·width는 요청값이며 variable font는 하나의 face 안에서 연속 축을 제공할 수 있습니다",
      lead: "font-weight 숫자를 적었다고 해당 굵기의 실제 glyph가 자동 존재하는 것은 아니며 face matching·axis range·합성 여부를 확인해야 합니다.",
      explanations: [
        "font-weight:400은 normal, 700은 bold의 일반 대응이지만 현대 CSS는 더 세밀한 숫자 요청을 허용합니다. 설치 또는 @font-face family에 요청 weight가 없으면 browser가 가까운 face를 선택하거나 합성 bold를 만들 수 있습니다. 브랜드 glyph 품질이 중요하면 실제 제공 face와 font-synthesis 정책을 검토합니다.",
        "font-style은 normal·italic·oblique를 구분합니다. italic은 설계된 italic face, oblique는 기울어진 형태를 요청하는 의미가 다릅니다. family가 해당 face를 제공하지 않으면 synthetic style이 나타날 수 있으므로 한글과 라틴 모두에서 glyph를 봅니다.",
        "variable font는 OpenType variation axis를 하나의 font resource에 담아 weight(wght), width(wdth), slant/italic, optical size(opsz) 등의 연속 범위를 제공할 수 있습니다. @font-face에서 font-weight:100 900처럼 지원 범위를 선언해야 matching engine이 중간 weight를 올바르게 선택합니다.",
        "표준 축은 font-weight·font-width 또는 구현에서 널리 쓰이는 대응 high-level property·font-style·font-optical-sizing을 우선합니다. font-variation-settings:'wght' 650처럼 저수준 목록을 직접 쓰면 개별 cascade가 어렵고 fallback face matching에도 덜 적합합니다. custom axis처럼 고수준 대안이 없을 때만 사용합니다.",
        "variable font 하나가 여러 static file을 줄일 수 있지만 항상 더 작지는 않습니다. 사용 glyph·축·instance 수, subset 결과, cache 재사용을 실제 전송 bytes로 비교합니다. 모든 축을 animation하면 layout·paint 비용과 읽기 방해가 생길 수 있으므로 기능적 이유와 reduced-motion 문맥도 검토합니다.",
      ],
      concepts: [
        { term: "font matching", definition: "family 후보 안에서 요청 style·weight·width와 glyph 지원을 바탕으로 실제 face를 선택하는 과정입니다.", detail: ["정확한 face가 없으면 가까운 face나 synthesis가 사용될 수 있습니다.", "@font-face descriptor 범위가 selection에 참여합니다."] },
        { term: "variable font", definition: "하나의 font resource가 하나 이상 variation axis의 연속 값을 지원하는 OpenType/TrueType font입니다.", detail: ["weight range를 @font-face descriptor에 선언할 수 있습니다.", "한 파일이 무조건 작은 것은 아니므로 subset과 사용 instance를 측정합니다."] },
        { term: "optical sizing", definition: "글자 크기에 맞게 stroke·spacing·세부 형태를 조정하는 opsz variation을 사용하는 기능입니다.", detail: ["지원 font에서 font-optical-sizing으로 제어합니다.", "단순 scale과 다른 glyph 디자인 조정입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "font-weight:600을 줬는데 500 또는 700과 거의 같거나 한글만 가짜로 굵어진다.", likelyCause: "family에 600 face/축 범위가 없고 browser가 가까운 face 또는 synthetic bold를 사용했습니다.", checks: ["Rendered Fonts와 실제 loaded file을 확인합니다.", "@font-face font-weight descriptor가 단일값인지 range인지 봅니다.", "라틴·한글 glyph별 fallback과 font-synthesis를 비교합니다."], fix: "필요한 weight face 또는 올바른 variable range를 제공하고 지원되지 않는 weight token을 정리합니다.", prevention: "design token별 실제 face mapping과 glyph-language screenshot test를 유지합니다." },
      ],
      comparisons: [
        { title: "여러 굵기를 어떻게 전달할까요?", options: [
          { name: "static faces", chooseWhen: "400·700처럼 소수 weight만 쓰고 각 file을 강하게 subset할 수 있을 때", avoidWhen: "연속 축과 많은 instance가 필요한 때", tradeoffs: ["face별 결과와 cache가 단순합니다.", "weight/style 수만큼 request와 bytes가 늘 수 있습니다.", "사용하지 않는 face는 로드하지 않게 구성할 수 있습니다."] },
          { name: "variable font", chooseWhen: "여러 weight·width·optical size를 실제로 사용하고 variable resource가 효율적일 때", avoidWhen: "한두 instance만 쓰는데 subset static files가 훨씬 작을 때", tradeoffs: ["연속 축과 fewer resources가 가능합니다.", "초기 file이 클 수 있습니다.", "axis range 선언·browser/font 품질 검증이 필요합니다."] },
        ] },
      ],
    },
    {
      id: "webfont-loading-lifecycle",
      title: "웹폰트는 발견·요청·검증·활성화·swap 단계를 거치며 실패해도 fallback text가 남아야 합니다",
      lead: "@font-face는 resource와 face 특성을 등록하고 실제 text가 그 face를 요구할 때 browser가 필요 file을 선택해 로드합니다.",
      explanations: [
        "원본 ex05는 Google Fonts stylesheet 두 개를 @import하고 Nanum Pen Script·Gugi에 각각 cursive fallback을 둡니다. 실행 환경에서 외부 stylesheet가 많은 unicode-range @font-face를 선언했고 실제 heading에 필요한 일부 face만 loaded, 나머지는 unloaded였습니다. 이는 family 하나가 file 하나라는 단순 모델보다 lazy subset loading을 잘 보여 줍니다.",
        "@font-face의 font-family는 CSS에서 사용할 내부 family 이름이고 src는 local/URL 후보를 우선순위로 제공합니다. font-style·font-weight range·unicode-range를 실제 resource와 일치시켜야 browser가 올바른 face를 선택합니다. 가능하면 압축된 WOFF2와 적법한 라이선스를 사용하고 fallback을 항상 둡니다.",
        "FOIT(Flash of Invisible Text)는 block period 동안 invisible fallback으로 text가 보이지 않는 경험, FOUT(Flash of Unstyled Text)는 fallback이 먼저 보였다가 webfont로 바뀌는 경험을 가리키는 실무 용어입니다. font-display:block·swap·fallback·optional은 block/swap/failure period 정책을 제어하지만 실제 기간은 user agent가 조정할 수 있습니다.",
        "본문은 즉시 읽히는 것이 우선이므로 fallback 또는 optional을 검토하고, swap은 fallback text를 즉시 보여 준 뒤 늦게 교체할 수 있어 layout shift를 관리해야 합니다. block은 font 모양 없이는 기능을 이해할 수 없는 매우 작은 범위 외에는 조심합니다. 잘못 설계된 icon font 때문에 block을 택하기보다 의미 있는 text/SVG 구조로 바꾸는 편이 안전합니다.",
        "CSS @import는 stylesheet를 받은 뒤 추가 stylesheet를 발견하게 해 critical font discovery가 늦어질 수 있습니다. provider link 또는 self-hosted @font-face를 문서 head에서 발견하게 하고 정말 첫 화면에 필요한 exact font resource만 preload를 검토합니다. preload의 href·type·crossorigin이 실제 CSS request와 다르면 중복 다운로드가 생깁니다.",
        "document.fonts는 FontFaceSet입니다. load()로 특정 font shorthand와 text를 로드하고 성공/실패 Promise를 처리할 수 있으며 ready는 현재 필요한 font loading과 관련 layout이 끝난 뒤 resolve됩니다. check()가 true라는 사실만으로 눈으로 기대한 glyph face까지 단순 보장한다고 과해석하지 말고 face status·network·rendered font를 함께 봅니다.",
      ],
      concepts: [
        { term: "@font-face", definition: "downloadable 또는 local font resource를 CSS family·style·weight·range와 연결하는 at-rule입니다.", detail: ["src 후보와 format을 선언합니다.", "face는 실제 사용 text와 matching될 때 선택적으로 로드될 수 있습니다."] },
        { term: "font-display", definition: "font face가 준비되기 전·후 text를 invisible fallback, visible fallback, webfont 중 무엇으로 표시할지 block/swap 기간 정책을 정하는 descriptor입니다.", detail: ["auto·block·swap·fallback·optional 값이 있습니다.", "user agent가 기간을 조정할 수 있습니다."] },
        { term: "FOIT / FOUT", definition: "웹폰트 로딩 중 text가 잠시 보이지 않거나 fallback으로 보였다가 바뀌는 사용자 경험을 가리키는 실무 약어입니다.", detail: ["FOIT는 읽기 지연, FOUT는 시각 교체와 layout shift 위험이 있습니다.", "font-display와 fallback metrics·network가 결과에 함께 영향 줍니다."] },
        { term: "FontFaceSet", definition: "document.fonts로 노출되어 font face의 상태·load/check·ready/events를 다루는 CSS Font Loading API 집합입니다.", detail: ["ready는 현재 font와 layout 완료 동기화에 유용합니다.", "추후 다른 content가 새 font load를 시작할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "첫 화면 본문이 수 초 동안 비어 있거나 network 실패 시 계속 보이지 않는다.", likelyCause: "본문 face에 부적절한 block 정책을 사용했거나 fallback color/visibility 처리로 text를 숨겼습니다.", checks: ["느린 3G·offline에서 filmstrip과 font-display를 확인합니다.", "Network의 font request 상태·CORS·response MIME을 봅니다.", "fallback family만 남긴 상태에서 text가 읽히는지 확인합니다."], fix: "읽기가 우선인 text에 적합한 swap/fallback/optional 정책과 가독성 있는 fallback을 제공하고 JS로 text visibility를 font load에 묶지 않습니다.", prevention: "offline·timeout·blocked-third-party 조건을 performance/accessibility acceptance test에 포함합니다." },
        { symptom: "webfont 적용 뒤 제목·버튼 폭이 바뀌며 CLS가 발생하거나 줄이 다시 감긴다.", likelyCause: "fallback과 webfont의 advance width·ascent·descent·line gap metrics 차이가 큽니다.", checks: ["Performance panel에서 Layout Shift entry를 봅니다.", "fallback/webfont rendered metrics와 line break를 비교합니다.", "size-adjust·ascent/descent/line-gap override와 font-display 정책을 확인합니다."], fix: "metrics가 가까운 fallback을 고르고 필요하면 @font-face metrics override를 검증해 적용하며 fixed-height text container를 피합니다.", prevention: "font 차단/느린 로딩 visual test와 CLS budget을 CI·RUM에 둡니다." },
        { symptom: "폰트 request가 404·CORS·CSP로 실패하고 fallback만 표시된다.", likelyCause: "상대 URL·배포 base path·cross-origin header·font-src CSP·preload crossorigin이 실제 resource와 맞지 않습니다.", checks: ["Network request URL/status/response header와 console 오류를 확인합니다.", "CSS file 기준 relative URL을 계산합니다.", "Access-Control-Allow-Origin, CSP font-src, preload attributes를 대조합니다."], fix: "배포 경로와 MIME/CORS/CSP를 일치시키고 preload가 실제 CSS request와 같은 URL·credentials mode를 사용하게 합니다.", prevention: "production-origin smoke test에서 document.fonts.load와 network failure를 검증합니다." },
      ],
    },
    {
      id: "font-performance-privacy",
      title: "subset·preload·metrics·호스팅은 전송량만이 아니라 개인정보와 운영 책임까지 함께 최적화합니다",
      lead: "폰트 최적화는 file을 줄이는 한 번의 작업이 아니라 필요한 glyph·face·시점·origin을 측정하는 과정입니다.",
      explanations: [
        "unicode-range는 특정 code point 범위에 맞는 face를 선언해 실제 content가 요구할 때 필요한 subset만 가져오게 할 수 있습니다. 라틴·한글·기호를 나누면 첫 페이지 bytes를 줄일 수 있지만 범위를 잘못 자르면 글자별 fallback이 늘고 request가 지나치게 쪼개집니다. 지원 언어와 cache hit를 실제 route corpus로 측정합니다.",
        "preload는 render 전에 font를 발견하게 해 주지만 모든 weight·subset을 preload하면 bandwidth 경쟁으로 CSS·LCP image를 늦춥니다. 첫 화면에서 확실히 쓰는 face만 선택하고 unused preload warning과 duplicate request를 봅니다. 아래 route에서만 쓰는 display font는 lazy discovery가 더 낫습니다.",
        "fallback metrics와 webfont가 다르면 swap 때 CLS가 생깁니다. CSS Fonts의 size-adjust, ascent-override, descent-override, line-gap-override는 fallback face의 크기·vertical metrics를 맞추는 도구지만 숫자를 추측하면 clipping과 baseline 오류를 만듭니다. 실제 font metrics와 여러 glyph로 계산·시각 검증합니다.",
        "third-party font stylesheet는 사용자의 IP·user agent·referer 등 network metadata가 외부 provider로 전달될 수 있고 provider 장애·정책 변경에 의존합니다. self-hosting은 privacy·cache·version 통제를 높이지만 license, update, compression, CORS, CDN cache를 직접 운영해야 합니다. 법적·조직 요구를 기술 결정과 함께 기록합니다.",
        "외부 stylesheet/script에는 SRI가 유용할 수 있지만 provider가 동적으로 생성하는 Google Fonts CSS처럼 response가 user agent·query에 따라 변하면 고정 hash 운영이 어렵습니다. CSP style-src/font-src와 allowlist를 최소화하고, 외부 icon CSS는 version을 고정해 예기치 않은 glyph mapping 변경을 막습니다.",
      ],
      concepts: [
        { term: "unicode-range", definition: "@font-face가 담당할 Unicode code point 범위를 선언해 필요한 glyph subset face를 선택적으로 사용하게 하는 descriptor입니다.", detail: ["실제 지원 언어와 범위를 맞춥니다.", "과도한 조각화는 request와 fallback 복잡도를 높입니다."] },
        { term: "font metrics override", definition: "size-adjust·ascent/descent/line-gap override로 face의 크기와 line metrics를 조정하는 @font-face descriptor 집합입니다.", detail: ["fallback/webfont 교체 시 layout shift를 줄일 수 있습니다.", "실제 metrics 기반으로 검증해야 합니다."] },
        { term: "critical font", definition: "첫 viewport의 핵심 text를 즉시 렌더링하는 데 실제 필요한 face/subset입니다.", detail: ["모든 family file과 같지 않습니다.", "preload 여부는 route와 performance trace로 결정합니다."] },
      ],
      codeExamples: [
        {
          id: "font-failure-svg-fallback",
          title: "깨진 웹폰트에서도 읽히는 text와 visible-label SVG button",
          language: "html",
          filename: "font-failure-icon.html",
          purpose: "의도적으로 invalid WOFF2를 로드해 FontFaceSet 실패를 관찰하고 fallback text 및 font-independent SVG icon 구조가 유지되는지 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n<meta charset=\"utf-8\"><title>폰트 실패와 아이콘</title>\n<style>\n  @font-face {\n    font-family: \"StudyBroken\";\n    src: url(\"data:font/woff2;base64,AA==\") format(\"woff2\");\n    font-display: swap;\n  }\n  .sample { font-family: \"StudyBroken\", system-ui, sans-serif; }\n  .save { color: rgb(0 102 204); font: inherit; }\n  .save svg { inline-size: 1em; block-size: 1em; fill: currentColor; }\n</style>\n</head>\n<body>\n<p class=\"sample\" id=\"sample\">학습 기록은 계속 보입니다.</p>\n<button class=\"save\" type=\"button\">\n  <svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 3h12l2 2v16H5z\"/></svg>\n  <span>저장</span>\n</button>\n<pre id=\"result\">pending</pre>\n<script>\n(async () => {\n  let loadResult = \"loaded\";\n  try {\n    await document.fonts.load('16px \"StudyBroken\"', \"학습\");\n  } catch (error) {\n    loadResult = error.name;\n  }\n  const face = [...document.fonts].find((item) => item.family === \"StudyBroken\");\n  const sample = document.querySelector(\"#sample\");\n  const button = document.querySelector(\".save\");\n  const svg = button.querySelector(\"svg\");\n  document.querySelector(\"#result\").textContent = [\n    `font-load=${loadResult}`,\n    `face-status=${face.status}`,\n    `font-check=${document.fonts.check('16px \"StudyBroken\"', \"학습\")}`,\n    `fallback-list=${getComputedStyle(sample).fontFamily}`,\n    `text=${sample.textContent}`,\n    `button-text=${button.textContent.trim()}`,\n    `svg-hidden=${svg.getAttribute(\"aria-hidden\")}`,\n    `svg-fill=${getComputedStyle(svg).fill}`,\n  ].join(\"\\n\");\n})();\n</script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-10", explanation: "학습 목적으로 bytes가 깨진 WOFF2 data URL을 StudyBroken face로 등록하고 swap을 지정합니다. 실제 제품에서는 유효하고 라이선스가 확인된 font만 사용합니다." },
            { lines: "11-13", explanation: "sample은 StudyBroken 실패 뒤 system-ui·sans-serif로 계속 읽히며 button color를 SVG fill=currentColor가 공유합니다." },
            { lines: "17-21", explanation: "button의 visible text '저장'이 accessible name의 핵심이고 같은 의미를 반복하는 SVG는 aria-hidden=true로 장식 처리합니다. icon-only button이라면 button 자체에 정확한 이름이 필요합니다." },
            { lines: "24-31", explanation: "FontFaceSet.load를 await하고 실패 DOMException 이름을 기록합니다. 실패를 무시하지 않되 본문 표시를 Promise에 종속시키지 않습니다." },
            { lines: "32-44", explanation: "face status/check, 선언된 fallback 목록, 실제 text, button label, SVG 숨김·currentColor 결과를 exact output으로 만듭니다." },
          ],
          run: { environment: ["UTF-8로 저장", "Font Loading API와 inline SVG를 지원하는 현대 Chromium 브라우저", "JavaScript 활성화", "예제는 의도된 font decoding 오류를 발생시킴"], command: "browser에서 font-failure-icon.html 열기" },
          output: {
            value: "font-load=NetworkError\nface-status=error\nfont-check=false\nfallback-list=StudyBroken, system-ui, sans-serif\ntext=학습 기록은 계속 보입니다.\nbutton-text=저장\nsvg-hidden=true\nsvg-fill=rgb(0, 102, 204)",
            explanation: ["invalid font decoding으로 load Promise가 NetworkError, face status가 error가 되고 check는 false입니다.", "계산 font-family는 후보 목록을 유지하지만 visible text는 system fallback으로 계속 표시됩니다.", "button의 visible text가 기능 이름을 제공하고 SVG는 동일 의미를 중복 낭독하지 않도록 숨겼습니다.", "SVG fill=currentColor가 button의 rgb(0,102,204)를 받아 icon font file 없이 색상 token과 함께 동작합니다."],
          },
          experiments: [
            { change: "system-ui, sans-serif fallback을 제거하고 느린 network를 모의합니다.", prediction: "browser 기본 fallback은 여전히 생길 수 있지만 개발자가 의도한 언어·metrics 선택과 테스트가 불명확해집니다.", result: "명시적 generic fallback은 실패 정책을 문서화합니다." },
            { change: "button의 span을 제거하고 SVG의 aria-hidden만 유지합니다.", prediction: "button이 눈에는 icon으로 보이지만 접근 가능한 이름이 비어 기능을 알기 어렵습니다.", result: "icon-only control은 button에 aria-label 또는 연결된 visible/visually-hidden text를 제공해야 합니다." },
            { change: "SVG path를 Font Awesome private-use glyph ::before로 바꾸고 font load를 차단합니다.", prediction: "icon이 사라지거나 대체 glyph가 보일 수 있지만 visible '저장' text는 기능을 계속 전달합니다.", result: "기능의 유일한 정보원을 icon font에 맡기지 않습니다." },
          ],
          sourceRefs: ["web-day04-webfont-source", "web-day04-iconfont-source", "css-fonts-4", "css-font-loading-3", "wai-aria24"],
        },
      ],
      diagnostics: [
        { symptom: "font를 preload했는데 같은 file이 두 번 내려받거나 unused preload 경고가 나온다.", likelyCause: "preload URL·type·crossorigin·credentials mode가 CSS request와 다르거나 첫 viewport에서 해당 face/subset을 쓰지 않습니다.", checks: ["Network initiator와 cache key를 비교합니다.", "@font-face src와 preload href를 byte-for-byte 대조합니다.", "실제 첫 화면 text가 face의 style/weight/unicode-range와 match하는지 확인합니다."], fix: "정말 critical한 exact resource만 올바른 type/crossorigin으로 preload하고 나머지는 CSS discovery에 맡깁니다.", prevention: "route별 preload budget과 duplicate/unused request CI trace를 둡니다." },
      ],
      expertNotes: ["실사용자 네트워크·cache·언어에 따라 font loading 결과가 달라지므로 lab trace만으로 완료하지 않고 RUM의 LCP·CLS·font failure를 privacy-safe하게 집계합니다.", "local() src는 설치 font 버전·glyph·metrics가 달라 재현성이 낮을 수 있습니다. 다운로드 절감과 디자인 일관성 trade-off를 명시적으로 결정합니다."],
    },
    {
      id: "css-color-alpha",
      title: "색상 표기법은 같은 색을 다른 좌표로 표현하며 alpha는 색만 투명하게 만들고 layout을 제거하지 않습니다",
      lead: "named·HEX·rgb·hsl은 주로 sRGB 색을 표현하고 alpha는 배경과 합성될 비율을 추가합니다.",
      explanations: [
        "원본 ex07은 skyblue·green·red 같은 named color, rgb/rgba, 6·8자리 HEX를 배경·글자·border에 적용합니다. named color는 기억하기 쉽지만 design token에는 의도를 설명하는 --color-text, --color-danger처럼 역할 이름을 두는 편이 theme과 유지보수에 유리합니다.",
        "#RRGGBB는 red·green·blue 각 8bit를 16진수 두 자리로, #RRGGBBAA는 마지막 alpha도 두 자리로 표현합니다. #FF000088의 0x88/255는 약 0.533이므로 Chromium 계산값은 rgba(255,0,0,0.533)입니다. 3·4자리 shorthand는 각 digit을 복제하는 규칙이 있어 팀에서는 가독성을 위해 한 형식으로 통일할 수 있습니다.",
        "현대 rgb()는 rgb(255 0 0 / 50%)처럼 공백 구분과 slash alpha를 지원하며 rgba()는 별도 기능이 아니라 alpha를 허용하는 alias입니다. HSL은 hue·saturation·lightness로 조절하기 편하지만 숫자상 lightness가 동일하다고 지각 밝기나 WCAG 대비가 동일한 것은 아닙니다.",
        "alpha 0인 background-color는 완전히 투명해 부모 배경이 보이지만 element, text, event target, layout box는 남습니다. 원본의 rgba(...,0)과 #RRGGBB00이 이 경우입니다. element 전체 opacity:0은 자식까지 합성해 보이지 않게 하지만 역시 layout·상호작용 가능성이 남아 숨김 UI 수단으로 부적절할 수 있습니다.",
        "원본의 세 번째 HEX 예제는 실제 declaration #00FF77인데 설명에는 #FFFF00=RGB(255,255,0)이라고 적혀 있습니다. 브라우저는 주석이 아니라 declaration을 실행해 rgb(0,255,119)로 계산합니다. 색 이름·주석·token 이름보다 computed color와 visual/contrast test를 신뢰해야 합니다.",
      ],
      concepts: [
        { term: "sRGB", definition: "named·HEX·전통 rgb/hsl 색이 일반적으로 해석되는 표준 RGB 색 공간입니다.", detail: ["각 device가 color management를 통해 표시합니다.", "Display P3 등 더 넓은 gamut보다 표현 범위가 좁습니다."] },
        { term: "alpha", definition: "foreground color가 뒤 배경과 얼마나 불투명하게 합성되는지 나타내는 성분입니다.", detail: ["0은 완전 투명, 1 또는 100%는 완전 불투명입니다.", "element 자체와 layout을 제거하지 않습니다."], caveat: "최종 대비는 alpha color 자체가 아니라 실제 모든 배경과 합성된 결과로 계산합니다." },
        { term: "design token", definition: "#1f2937 같은 raw 값 대신 --color-text처럼 역할과 사용 목적에 이름을 붙인 재사용 값입니다.", detail: ["light/dark/forced-color theme 전환을 중앙화합니다.", "token 이름만으로 대비 적합성을 자동 보장하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "color-alpha-contrast",
          title: "계산 색상·alpha·WCAG sRGB 대비 수치 확인",
          language: "html",
          filename: "color-contrast.html",
          purpose: "원본의 HEX·RGB·alpha를 semantic token으로 재구성하고 실제 computed color와 contrast ratio를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n<meta charset=\"utf-8\"><title>색상과 대비</title>\n<style>\n  :root { --ink: #1f2937; --surface: #fff; --accent: rgb(0 102 204); }\n  body { color: var(--ink); background-color: var(--surface); }\n  #accent { color: var(--accent); }\n  #alpha { min-height: 20px; background-color: rgb(255 0 0 / 0); }\n</style>\n</head>\n<body>\n<p id=\"ink\">기본 본문</p>\n<p id=\"accent\">강조 링크</p>\n<div id=\"alpha\">투명 배경도 레이아웃은 남습니다.</div>\n<pre id=\"result\"></pre>\n<script>\n  const rgb = (value) => value.match(/[\\d.]+/g).slice(0, 3).map(Number);\n  const luminance = (value) => {\n    const [r, g, b] = rgb(value).map((channel) => {\n      const normalized = channel / 255;\n      return normalized <= 0.04045\n        ? normalized / 12.92\n        : ((normalized + 0.055) / 1.055) ** 2.4;\n    });\n    return 0.2126 * r + 0.7152 * g + 0.0722 * b;\n  };\n  const contrast = (a, b) => {\n    const [light, dark] = [luminance(a), luminance(b)].sort((x, y) => y - x);\n    return ((light + 0.05) / (dark + 0.05)).toFixed(2);\n  };\n  const ink = getComputedStyle(document.querySelector(\"#ink\")).color;\n  const accent = getComputedStyle(document.querySelector(\"#accent\")).color;\n  const surface = getComputedStyle(document.body).backgroundColor;\n  const alpha = document.querySelector(\"#alpha\");\n  document.querySelector(\"#result\").textContent = [\n    `ink=${ink}`,\n    `accent=${accent}`,\n    `surface=${surface}`,\n    `alpha-bg=${getComputedStyle(alpha).backgroundColor}`,\n    `alpha-opacity=${getComputedStyle(alpha).opacity}`,\n    `alpha-layout=${alpha.getBoundingClientRect().height > 0}`,\n    `ink-contrast=${contrast(ink, surface)}:1`,\n    `accent-contrast=${contrast(accent, surface)}:1`,\n  ].join(\"\\n\");\n</script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-9", explanation: "raw colors를 본문 ink·surface·accent 역할 token으로 선언하고 alpha 0 red background를 가진 box를 만듭니다." },
            { lines: "17-26", explanation: "computed rgb channel을 sRGB relative luminance로 변환합니다. 0.04045 경계와 0.2126/0.7152/0.0722 계수는 WCAG contrast 계산에 쓰이는 공식입니다." },
            { lines: "27-30", explanation: "두 luminance 중 밝은 값을 분자로 놓고 각각 0.05를 더해 contrast ratio를 소수 둘째 자리까지 출력합니다." },
            { lines: "31-43", explanation: "cascade가 끝난 foreground/background, transparent background와 element opacity/layout 존재, 두 text contrast를 같은 실행에서 검증합니다." },
          ],
          run: { environment: ["UTF-8로 저장", "현대 Chromium 브라우저", "JavaScript 활성화", "기본 sRGB computed serialization"], command: "browser에서 color-contrast.html 열기" },
          output: {
            value: "ink=rgb(31, 41, 55)\naccent=rgb(0, 102, 204)\nsurface=rgb(255, 255, 255)\nalpha-bg=rgba(255, 0, 0, 0)\nalpha-opacity=1\nalpha-layout=true\nink-contrast=14.68:1\naccent-contrast=5.57:1",
            explanation: ["#1f2937과 #fff가 computed rgb로 직렬화되고 본문 대비는 14.68:1입니다.", "accent rgb(0,102,204)는 흰 배경에서 5.57:1로 일반 크기 text의 4.5:1 기준을 넘습니다.", "alpha-bg는 완전 투명하지만 element opacity는 1이고 height가 남아 layout=true입니다.", "수치는 현재 opaque 흰 배경 조합에만 해당합니다. theme·gradient·image·state가 달라지면 다시 측정합니다."],
          },
          experiments: [
            { change: "accent를 #99ccff로 바꾸고 대비를 다시 계산합니다.", prediction: "흰 배경과 luminance 차이가 줄어 일반 text 4.5:1 기준을 통과하지 못할 가능성이 큽니다.", result: "색 이름이나 채도보다 실제 foreground/background contrast를 검사합니다." },
            { change: "alpha background를 rgb(255 0 0 / 50%)로 바꾸고 흰색·검은색 부모에서 비교합니다.", prediction: "같은 foreground 선언도 합성 배경에 따라 최종 보이는 색과 대비가 달라집니다.", result: "semi-transparent text/UI color는 모든 실제 배경 위에서 측정합니다." },
            { change: "background alpha 대신 element에 opacity:0을 적용합니다.", prediction: "text와 자식까지 보이지 않지만 layout box와 focus/hit-test 가능성은 별도로 남을 수 있습니다.", result: "visibility·interaction을 숨기는 목적에는 적절한 hidden/display/inert 정책을 사용합니다." },
          ],
          sourceRefs: ["web-day01-color-source", "css-color-4", "wcag22"],
        },
      ],
      diagnostics: [
        { symptom: "주석에는 노란색이라고 되어 있지만 화면과 computed value는 초록 계열이다.", likelyCause: "원본 declaration #00FF77과 설명 #FFFF00이 서로 다르며 browser는 declaration만 실행합니다.", checks: ["Styles에서 cascade winner의 exact token을 확인합니다.", "Computed color와 source comment/token 이름을 비교합니다.", "screenshot eyedropper만 아니라 CSSOM serialization을 봅니다."], fix: "의도한 값으로 declaration·token·설명·test fixture를 함께 수정합니다.", prevention: "색상 token preview와 computed snapshot/contrast test를 자동 생성해 문서 drift를 줄입니다." },
        { symptom: "alpha 0을 줬는데 element가 공간을 차지하거나 클릭된다.", likelyCause: "color alpha 또는 opacity는 layout/display를 제거하는 속성이 아닙니다.", checks: ["box model과 getBoundingClientRect를 확인합니다.", "opacity·background alpha·visibility·display 값을 구분합니다.", "tab order와 pointer event를 시험합니다."], fix: "단지 투명 색이 목적이면 유지하고 UI를 숨길 목적이면 hidden/display:none/inert 등 semantics와 interaction 요구에 맞는 방법을 사용합니다.", prevention: "visible·layout·focus·accessibility 상태를 각각 명시하는 component state test를 둡니다." },
      ],
    },
    {
      id: "modern-color-spaces",
      title: "Oklch·Lab·Display P3는 더 넓거나 지각적으로 다루기 쉬운 좌표를 제공하지만 fallback과 gamut 검증이 필요합니다",
      lead: "CSS Color 4는 sRGB 밖의 색과 device-independent 색 공간을 표현할 수 있게 하지만 모든 device가 같은 gamut을 낼 수 있는 것은 아닙니다.",
      explanations: [
        "lab()/lch()와 oklab()/oklch()는 lightness와 상대 색 좌표를 분리해 theme scale·gradient를 만들 때 RGB/HSL보다 지각 변화가 균일한 방향을 제공할 수 있습니다. 특히 Oklch는 L(lightness), C(chroma), H(hue)로 읽지만 같은 L이 WCAG contrast 통과를 자동 보장하지 않습니다.",
        "color(display-p3 ...)는 sRGB보다 넓은 Display P3 gamut의 색을 표현할 수 있습니다. 선언이 CSS 문법상 valid해도 사용 device gamut 밖일 수 있어 browser가 mapping합니다. wide-gamut screenshot을 sRGB pipeline으로 저장하거나 color management가 없는 도구에서 보면 색이 달라질 수 있습니다.",
        "progressive enhancement는 먼저 sRGB fallback을 선언하고 뒤에 지원되는 modern color를 둡니다. @supports (color: oklch(60% 0.2 250)) 또는 @media (color-gamut:p3)를 사용할 수 있지만 feature support와 실제 panel gamut은 별도입니다. 핵심 상태를 wide-gamut 차이 하나로만 전달하지 않습니다.",
        "theme token은 raw color space보다 역할과 state를 먼저 표현합니다. --text-primary, --surface, --border-focus에 light/dark/forced mode 값을 매핑하고 각 조합을 측정합니다. Oklch로 scale을 생성해도 최종 사용 color의 contrast·gamut·state 차이를 자동 test합니다.",
      ],
      concepts: [
        { term: "gamut", definition: "특정 color space 또는 출력 device가 표현할 수 있는 색의 범위입니다.", detail: ["Display P3는 일반 sRGB보다 넓은 영역을 표현합니다.", "valid CSS color가 모든 화면에서 원래 색 그대로 출력된다는 뜻은 아닙니다."] },
        { term: "Oklch", definition: "Oklab의 polar form으로 lightness L, chroma C, hue H를 사용하는 CSS color function입니다.", detail: ["지각상 비교적 균일한 scale 설계에 유용합니다.", "WCAG contrast와 device gamut은 별도로 검증합니다."] },
        { term: "progressive color fallback", definition: "기본 sRGB 색을 먼저 제공하고 지원되는 환경에서 modern/wide-gamut 색으로 덮는 전략입니다.", detail: ["지원 실패에도 콘텐츠가 읽힙니다.", "두 값 모두 contrast와 상태 구분을 확인합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "P3 모니터에서는 선명한 brand color가 일반 모니터·screenshot·인쇄에서 탁하거나 다르게 보인다.", likelyCause: "색이 sRGB gamut 밖이고 capture/export/device color-management 경로가 서로 다릅니다.", checks: ["color(display-p3)와 sRGB fallback을 각각 확인합니다.", "@media (color-gamut) 결과와 실제 monitor profile을 봅니다.", "screenshot/export file의 color profile을 확인합니다."], fix: "허용 가능한 sRGB fallback을 설계하고 wide-gamut은 enhancement로 적용하며 핵심 정보는 색조 차이에만 의존하지 않습니다.", prevention: "sRGB·P3·print/high-contrast 환경의 visual/contrast acceptance test를 둡니다." },
      ],
    },
    {
      id: "contrast-forced-colors",
      title: "대비는 실제 foreground와 background 조합으로 측정하고 사용자의 강제 색상 palette를 존중합니다",
      lead: "예쁜 token 하나가 접근 가능한 것이 아니라 text 크기·weight·배경·alpha·상태까지 정해진 최종 조합이 기준을 충족해야 합니다.",
      explanations: [
        "WCAG 2.2 AA의 일반 text와 text image는 최소 4.5:1, large-scale text는 최소 3:1 contrast ratio가 기준입니다. 큰 text 예외를 얻으려고 CSS pixel만 대충 보고 판단하지 말고 WCAG large-scale 정의와 실제 weight를 확인합니다. logo·incidental 예외를 일반 본문에 확대 적용하지 않습니다.",
        "사용자가 control과 필요한 graphic을 식별하는 non-text contrast는 인접 색과 최소 3:1을 검토합니다. focus outline, checkbox border, icon-only control의 핵심 shape가 해당합니다. decorative graphic이나 visible text가 같은 정보를 충분히 전달하는 icon은 맥락이 다르지만 control 자체의 focus·boundary는 여전히 검토합니다.",
        "색을 오류·성공·필수의 유일한 단서로 쓰지 않습니다. 색과 함께 text, icon shape, border/pattern, programmatic state를 제공합니다. 예를 들어 빨간 border만이 아니라 오류 메시지와 aria-invalid를 연결합니다. 색각 차이 simulation은 보조 도구이고 실제 task 수행과 contrast 계산을 대체하지 않습니다.",
        "forced-colors:active에서는 browser가 사용자의 system palette에 맞게 color·background·border·outline·SVG fill/stroke 등을 강제로 바꿀 수 있고 box-shadow/text-shadow가 사라질 수 있습니다. box-shadow만으로 focus ring을 만들면 사라지므로 outline 같은 강제 색상 대응 속성을 유지합니다.",
        "@media (forced-colors:active)에서 Canvas·CanvasText·ButtonText·Highlight 같은 system color를 사용할 수 있습니다. forced-color-adjust:none으로 author color를 고정하는 것은 사용자 선택을 무력화하므로 로고·color swatch처럼 색 자체가 정보인 좁은 경우에도 대체 설명과 대비를 검토한 뒤 최소 범위에만 사용합니다.",
        "light/dark theme 각각 normal·hover·focus·disabled·selected·error를 검사합니다. 투명 foreground는 실제 배경 이미지/gradient의 가장 불리한 지점과 합성해 측정합니다. 자동 도구 결과가 경계값 근처이면 anti-aliasing·thin font에서 읽기 어려울 수 있어 여유 있는 token을 선택합니다.",
      ],
      concepts: [
        { term: "contrast ratio", definition: "두 색의 relative luminance에 기반해 1:1부터 21:1까지 계산한 밝기 차이 비율입니다.", detail: ["foreground/background 순서를 바꿔도 ratio는 같습니다.", "alpha가 있으면 실제 합성 색을 사용합니다."] },
        { term: "forced colors mode", definition: "사용자 가독성을 위해 user agent가 author color를 제한된 system palette로 대체하는 접근성 mode입니다.", detail: ["forced-colors media query로 감지할 수 있습니다.", "system colors와 native semantics가 대응에 유리합니다."] },
        { term: "system color", definition: "CanvasText·ButtonText처럼 사용자 agent/OS palette의 의미 역할을 나타내는 CSS color keyword입니다.", detail: ["forced colors에서 사용자 선택과 일관성을 유지합니다.", "고정 RGB 값과 다릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "일반 mode에서는 보이던 focus ring·아이콘이 Windows High Contrast/forced colors에서 사라진다.", likelyCause: "box-shadow·background-image·author fill 색에만 의존했고 강제 palette에서 제거·대체됐습니다.", checks: ["DevTools forced-colors emulation 또는 실제 OS mode에서 확인합니다.", "outline·border·SVG currentColor의 used value를 봅니다.", "forced-color-adjust:none 범위를 검색합니다."], fix: "native control/outline과 currentColor/system colors를 사용하고 forced-colors media query에서 필요한 shape·border를 보강합니다.", prevention: "light/dark뿐 아니라 forced colors와 200% zoom을 visual/accessibility CI matrix에 포함합니다." },
        { symptom: "색 대비 도구는 통과했지만 반투명 text가 image/gradient 일부에서 읽히지 않는다.", likelyCause: "token의 raw RGB만 측정하고 alpha compositing 및 변하는 실제 background의 최저 대비를 계산하지 않았습니다.", checks: ["foreground alpha를 각 배경 지점과 합성합니다.", "gradient/image의 최소 대비 영역을 찾습니다.", "text shadow가 사라지는 조건과 thin weight를 봅니다."], fix: "불투명 surface/backplate를 제공하거나 색을 바꾸고 가장 불리한 실제 조합에서 기준을 만족하게 합니다.", prevention: "dynamic background fixture와 최소 대비 sampling, 수동 읽기 검사를 결합합니다." },
      ],
      comparisons: [
        { title: "강제 색상에서 author color를 어떻게 다룰까요?", options: [
          { name: "auto + system colors", chooseWhen: "text·button·focus·상태 UI처럼 사용자 palette를 존중해야 할 때", avoidWhen: "색 자체를 정확히 보여 주는 color picker swatch 같은 매우 좁은 영역", tradeoffs: ["사용자 대비 선호와 일관됩니다.", "원래 brand 색은 바뀔 수 있습니다.", "native semantics/currentColor가 대응을 단순화합니다."] },
          { name: "forced-color-adjust:none", chooseWhen: "정확한 색 자체가 정보이고 대체 설명·경계가 별도로 제공될 때", avoidWhen: "일반 text·control·focus indicator·장식 brand 영역", tradeoffs: ["author color를 보존합니다.", "사용자 가독성 설정을 무력화할 위험이 큽니다.", "최소 범위와 실제 forced palette 검증이 필요합니다."] },
        ] },
      ],
    },
    {
      id: "icon-font-svg-boundary",
      title: "아이콘은 장식·정보·기능 역할을 먼저 정하고 font glyph와 SVG 중 실패에 강한 표현을 선택합니다",
      lead: "보이는 집·사람·달력 모양보다 control의 accessible name과 font가 차단됐을 때 남는 기능이 우선입니다.",
      explanations: [
        "원본 ex06은 Font Awesome 6.7.2 CDN CSS를 SRI·crossorigin과 함께 불러와 i.fa-solid의 ::before private-use glyph를 icon font로 렌더링합니다. 실행 결과 첫 icon의 family는 Font Awesome 6 Free, weight 900, ::before에는 private-use glyph가 있었지만 i에 aria-hidden이 없고 icon은 a 링크의 자식이 아니라 앞 sibling이었습니다.",
        "원본 링크에는 '메뉴1' visible text가 있으므로 기능 이름은 남지만 icon이 link 밖이면 icon과 클릭 target이 분리되고 어떤 icon이 어떤 link 설명인지 구조가 약합니다. 더 견고한 구조는 a 안 장식 icon과 visible label을 함께 두고 icon에 aria-hidden=true를 주는 것입니다. control 전체의 accessible name은 visible label에서 옵니다.",
        "icon-only button은 icon element에만 aria-label을 붙이는 것보다 button 자체에 기능을 설명하는 accessible name을 둡니다. 예를 들어 저장 모양은 aria-label='저장'이고 tooltip만으로 이름을 대신하지 않습니다. 상태 icon이면 '즐겨찾기에 추가'와 '즐겨찾기에서 제거'처럼 현재 action/state를 코드와 함께 갱신합니다.",
        "아이콘 폰트는 CSS 한 번으로 color·size를 text처럼 다루고 오래된 library 생태계를 활용하기 쉽지만 private-use glyph mapping, font 차단/사용자 font override, hinting·baseline, 필요한 icon보다 큰 file, forced colors에서의 구분 문제가 있습니다. 생성 콘텐츠에 핵심 text를 넣지 않는 원칙이 그대로 적용됩니다.",
        "inline SVG는 실제 path만 포함하고 viewBox로 확장하며 fill/stroke=currentColor로 text token과 색을 공유할 수 있습니다. 장식 SVG는 aria-hidden=true·focusable=false 관행을 검토하고, standalone informative graphic은 role=img와 정확한 accessible name/description을 제공합니다. button 안 visible label이 이미 이름이면 SVG title을 중복하지 않습니다.",
        "SVG가 항상 정답은 아닙니다. 단순 decorative shape는 CSS pseudo-element/mask, 표준 의미가 있는 문자는 Unicode, 작은 고정 icon set은 sprite/component가 적합할 수 있습니다. 선택 기준은 bundle·cache·theme·animation·접근성·authoring workflow이며 구현 후 font 차단과 forced colors를 실제 시험합니다.",
      ],
      concepts: [
        { term: "icon font", definition: "문자 code point를 pictogram glyph에 매핑한 font와 CSS class/가상요소로 icon을 표시하는 방식입니다.", detail: ["font loading과 glyph fallback 실패 모드를 가집니다.", "private-use glyph를 의미 있는 text로 취급하지 않습니다."] },
        { term: "decorative icon", definition: "옆의 visible label과 같은 정보를 반복하거나 순수 장식인 icon입니다.", detail: ["보조기술에서 aria-hidden 처리할 수 있습니다.", "control 이름은 실제 label이 제공합니다."] },
        { term: "functional icon", definition: "link/button의 action을 식별하는 icon이며 control에 목적을 설명하는 accessible name이 필요합니다.", detail: ["모양 설명보다 결과/action 이름을 제공합니다.", "icon-only일 때도 keyboard focus와 충분한 target이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "아이콘 폰트를 차단하거나 사용자 stylesheet가 font-family를 바꾸면 메뉴에 빈 칸·네모·엉뚱한 문자가 보인다.", likelyCause: "기능과 상태의 유일한 표현을 private-use font glyph에 맡겼습니다.", checks: ["Network font blocking과 user font override를 모의합니다.", "visible/visually-hidden text와 control accessible name을 확인합니다.", "::before content code point와 fallback glyph를 봅니다."], fix: "기능에는 text accessible name을 제공하고 장식 icon은 SVG/currentColor 또는 실패해도 label이 남는 구조로 바꿉니다.", prevention: "font-off·CSS-off·forced-colors·screen-reader control list를 icon component acceptance test에 둡니다." },
        { symptom: "screen reader가 링크 이름과 함께 이해할 수 없는 icon 문자 또는 같은 의미를 두 번 읽는다.", likelyCause: "visible label이 있는데 icon glyph/SVG를 접근성 tree에서 숨기지 않았거나 icon에 중복 label을 붙였습니다.", checks: ["Accessibility tree에서 link/button name과 child node를 확인합니다.", "aria-hidden 위치와 control visible text를 봅니다.", "icon이 control 밖 sibling인지 확인합니다."], fix: "visible label과 같은 장식 icon은 control 안에 두고 aria-hidden=true로 숨기며 control label은 한 곳에서 제공합니다.", prevention: "component별 decorative/informative/functional icon contract와 accessible-name snapshot을 둡니다." },
      ],
      comparisons: [
        { title: "UI icon을 어떤 기술로 표현할까요?", options: [
          { name: "icon font", chooseWhen: "기존 library·많은 text-like monochrome glyph를 이미 운영하고 fallback/ARIA를 통제할 때", avoidWhen: "몇 개 icon만 필요하거나 font 차단 시 기능이 사라질 때", tradeoffs: ["font-size/color로 일괄 styling하기 쉽습니다.", "font resource·private-use mapping·baseline 실패가 있습니다.", "필요 glyph보다 큰 payload가 될 수 있습니다."] },
          { name: "inline SVG/component", chooseWhen: "정확한 path·viewBox·currentColor·다색/stroke·부분 bundle이 필요할 때", avoidWhen: "단순 문자를 SVG로 불필요하게 복제할 때", tradeoffs: ["font와 독립적이고 필요한 path만 포함할 수 있습니다.", "markup/component 관리가 필요합니다.", "장식/정보 role과 accessible name을 명시해야 합니다."] },
        ] },
      ],
      expertNotes: ["외부 icon CSS version과 SRI hash를 함께 고정하면 update 때 둘을 동시에 갱신해야 합니다. CDN 장애·CSP·privacy 요구가 있으면 self-hosted subset 또는 SVG component로 dependency를 줄입니다.", "SVG path 자체는 신뢰 경계 밖의 임의 markup이 될 수 있습니다. 사용자 제공 SVG를 그대로 innerHTML에 넣지 않고 검증·sanitization하거나 승인된 component allowlist만 사용합니다."],
    },
    {
      id: "debug-test-source-audit",
      title: "폰트·색·아이콘 문제는 선언, resource, computed value, 실제 rendered 결과, 접근성 순서로 진단합니다",
      lead: "Styles 패널 하나만 보지 말고 cascade부터 network와 사용자 설정까지 단계별 증거를 모읍니다.",
      explanations: [
        "첫째 Styles에서 selector·specificity·상속 winner를 찾고 Computed에서 font-size/line-height/color/opacity를 읽습니다. 둘째 Network에서 stylesheet/font URL·status·MIME·CORS·cache·initiator를 봅니다. 셋째 document.fonts와 rendered fonts에서 face status와 실제 glyph face를 확인합니다.",
        "넷째 100%·200% zoom, 320 CSS px viewport, slow/offline network에서 text reflow·FOIT/FOUT·CLS·overflow를 관찰합니다. 다섯째 light/dark/forced colors와 색각 simulation에서 대비·focus·상태를 봅니다. 여섯째 Accessibility tree에서 icon control name과 장식 child 숨김을 확인합니다.",
        "ex04_font 원본은 실제 computed result가 h1 48px, p 32px, child 48px, nested 96px, nested2 32px였고 li line-height는 24/16/80px이었습니다. 이 수치는 em/rem과 line-height 계산의 실행 증거이며 normal 값은 face metrics에 따라 달라질 수 있어 별도로 해석합니다.",
        "ex05_webfont 원본은 두 @import가 외부 Google CSS와 많은 unicode-range face를 추가했고 일부만 loaded되었습니다. ex06_iconfont는 Font Awesome ::before glyph와 900 weight를 확인했지만 icon/anchor 구조와 aria-hidden이 개선 지점이었습니다. ex07_color는 alpha 0에서도 opacity 1과 layout이 남았고 #00FF77이 실제 rgb(0,255,119)로 계산돼 설명 오타를 드러냈습니다.",
        "자동 test는 computed metric·contrast·accessible name·font load failure를 잡지만 '이 font가 한국어 장문에 읽기 좋은가', '아이콘 모양이 문화적으로 이해되는가', 'heading의 hierarchy가 시각적으로 충분한가'를 완전히 판단하지 못합니다. 실제 사용자와 콘텐츠 리뷰를 결합합니다.",
      ],
      concepts: [
        { term: "rendering evidence", definition: "source 선언뿐 아니라 network·computed style·font face·layout·accessibility 결과를 재현 가능한 값으로 기록한 증거입니다.", detail: ["환경과 명령을 함께 남깁니다.", "외부 service 결과는 시점·환경에 따라 달라질 수 있음을 구분합니다."] },
        { term: "failure matrix", definition: "font 차단·느린 network·zoom·theme·forced colors·user font override 등 독립 실패 조건을 조합해 검사하는 표입니다.", detail: ["정상 경로만으로 완료하지 않습니다.", "각 실패에서 text와 기능이 남아야 합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "font-family와 color 선언은 Styles에 보이는데 실제 화면 결과가 예상과 다르다.", likelyCause: "선언 존재만 확인하고 cascade winner·glyph fallback·alpha 합성·forced used value를 확인하지 않았습니다.", checks: ["Computed value와 rule origin을 봅니다.", "Rendered Fonts·Network·document.fonts를 확인합니다.", "background 합성·forced-colors·user stylesheet를 비교합니다."], fix: "원인 층에 맞춰 selector, resource, fallback, token 또는 user-preference 대응을 수정합니다.", prevention: "선언 snapshot이 아니라 실제 browser computed/rendered/accessibility assertion을 추가합니다." },
      ],
      expertNotes: ["font rendering pixel은 OS rasterizer·subpixel/antialiasing·device scale에 따라 달라져 strict screenshot diff가 noisy할 수 있습니다. metrics/DOM assertion과 허용오차 visual diff를 조합합니다.", "대비 test는 token pair를 빠르게 검증하지만 blending·gradient·image·state·forced used color는 실제 browser/화면 조건에서 보완해야 합니다."],
    },
  ],
  lab: {
    title: "느린 네트워크와 강제 색상에서도 읽히는 학습 카드 디자인 시스템",
    scenario: "한국어 학습 카드의 본문·제목·코드·상태·저장 버튼을 system/web font, semantic color token, accessible SVG icon으로 구현하고 font 실패·200% 확대·forced colors까지 검증합니다.",
    setup: [
      "UTF-8 편집기, 현대 Chromium DevTools, HTML validator와 접근성 tree를 준비합니다.",
      "실제 배포 가능한 WOFF2를 사용할 경우 라이선스·CORS·CSP·출처를 확인합니다. 그렇지 않으면 system stack만으로 먼저 완성합니다.",
      "DevTools Network throttling/offline, 320px viewport, forced-colors emulation 또는 실제 OS High Contrast를 사용할 수 있게 합니다.",
      "개인정보·비밀 URL·사용자 입력 raw SVG/HTML은 넣지 않습니다.",
    ],
    steps: [
      "body에 system-ui와 한국어·sans-serif fallback을 포함한 family list, 1rem base, unitless line-height를 선언합니다.",
      "제목·본문·보조 text scale을 rem으로 만들고 button icon/padding만 em으로 비례시킵니다. 각 computed font-size/line-height를 표로 기록합니다.",
      "선택한 webfont가 있다면 @font-face family/src/format/weight range/unicode-range/font-display를 작성하고 fallback만으로도 card를 읽을 수 있게 합니다.",
      "Network slow/offline에서 FOIT/FOUT, fallback, document.fonts status, loaded subset, CLS를 기록합니다. 본문을 font Promise 전까지 숨기지 않습니다.",
      "--text, --surface, --accent, --danger, --focus token을 만들고 light/dark state의 normal·hover·focus·disabled 조합을 계산합니다.",
      "일반 text 4.5:1, large text 3:1, 필수 UI graphic/focus 3:1 기준을 자동 도구와 수동 검토로 확인하고 색상 외 text/icon/border 단서를 추가합니다.",
      "저장 button 안에 aria-hidden inline SVG와 visible '저장' label을 두고 fill=currentColor를 사용합니다. icon-only 변형은 button accessible name과 tooltip을 별도 설계합니다.",
      "Font Awesome 방식도 비교 fixture로 만들되 font request를 차단하고 user font override에서 glyph·label·accessible name이 어떻게 남는지 기록합니다.",
      "forced-colors:active에서 focus outline·button boundary·SVG가 보이는지 확인하고 system color 보강을 추가합니다. 불필요한 forced-color-adjust:none은 제거합니다.",
      "200% zoom과 320px viewport에서 text/control이 잘리거나 겹치지 않고 긴 한글·영문·숫자·emoji가 fallback과 함께 표시되는지 확인합니다.",
      "production network trace에서 preload 중복·unused face·third-party request·CSP 위반을 확인하고 선택 근거와 source evidence를 문서화합니다.",
    ],
    expectedResult: [
      "font resource를 차단해도 모든 본문·button label과 기능이 즉시 읽히고 사용할 수 있습니다.",
      "em/rem과 unitless line-height 계산표가 browser computed value와 일치하며 200% 확대에서도 clipping이 없습니다.",
      "필요한 face/subset만 로드되고 preload duplicate가 없으며 webfont swap의 CLS가 budget 안에 있습니다.",
      "모든 text·UI 상태가 목표 contrast를 만족하고 오류·선택 상태가 색 하나에만 의존하지 않습니다.",
      "forced colors에서 native/system palette로 text·focus·button·SVG가 식별됩니다.",
      "decorative SVG는 접근성 tree에서 숨고 button accessible name은 '저장'으로 한 번만 노출됩니다.",
      "source, Network, computed style, FontFaceSet, rendered font, accessibility 결과가 하나의 검증 기록으로 연결됩니다.",
    ],
    cleanup: ["고의로 깨뜨린 WOFF2·CORS·낮은 대비 fixture만 분리하고 정상 card와 실패 검증 기록은 다음 layout 세션에 재사용합니다."],
    extensions: [
      "같은 family의 static 400/700과 variable 100~900 subset을 실제 transfer size·cache·render time으로 비교합니다.",
      "size-adjust·ascent/descent/line-gap override를 실제 metrics에서 계산해 CLS 전후를 비교합니다.",
      "Oklch token scale과 sRGB fallback을 만들고 P3·sRGB·forced colors visual matrix를 작성합니다.",
      "icon font menu를 tree-shaken SVG component로 migration하고 bundle·accessible-name·forced-color 결과를 비교합니다.",
    ],
  },
  exercises: [
    {
      difficulty: "따라하기",
      prompt: "원본 font/color 예제를 현재 표준의 읽기 좋은 학습 카드로 다시 작성하세요.",
      requirements: ["system-ui와 한국어·generic fallback을 가진 family list를 만듭니다.", "root 16px에서 rem/em 네 요소와 unitless line-height의 exact computed 값을 출력합니다.", "HEX·rgb/slash alpha 세 표기를 token으로 적용하고 alpha 0에서도 layout이 남는지 확인합니다.", "본문·accent와 surface contrast를 계산해 기준 통과 여부를 기록합니다.", "visible label이 있는 저장 button 안에 aria-hidden currentColor SVG를 넣습니다."],
      hints: ["font-family computed string은 후보 목록이며 실제 face는 별도입니다.", "line-height number는 child의 font-size에 다시 곱해집니다.", "투명 color와 숨겨진 element를 구분합니다."],
      expectedOutcome: "원본의 시각 예제를 font selection·metric·color 합성·접근성 evidence가 있는 한 카드로 재현합니다.",
      solutionOutline: ["semantic HTML과 system fallback부터 작성합니다.", "relative unit 계산을 손으로 예측합니다.", "computed style과 contrast output을 실행합니다.", "SVG label과 forced-color 기본 동작을 검수합니다."],
    },
    {
      difficulty: "응용",
      prompt: "느린 네트워크·폰트 실패·저대비·아이콘 폰트 결함을 가진 페이지를 진단하세요.",
      requirements: ["@import webfont, font-display:block, fallback 없는 family, 24px fixed line-height, low-contrast alpha text, color-only error, icon-only private-use link를 포함한 fixture를 만듭니다.", "Network·FontFaceSet·Rendered Fonts·Computed·Accessibility tree에서 각 결함의 증거를 기록합니다.", "fallback/font-display/metrics를 수정하고 offline에도 text를 보존합니다.", "일반 text와 UI graphic 대비를 고치고 색상 외 오류 문구를 추가합니다.", "icon font 차단과 forced colors에서 기능 이름·focus가 남도록 visible/hidden text 또는 SVG 구조로 교정합니다."],
      hints: ["document.fonts.ready만 기다렸다고 앞으로 모든 font가 영원히 준비된 것은 아닙니다.", "alpha text는 최종 background와 합성해 측정합니다.", "아이콘의 모양 설명보다 control이 하는 일을 이름으로 제공합니다."],
      expectedOutcome: "정상 network가 아닌 실패 경로에서도 읽기·layout·contrast·control 이름을 보장합니다.",
      solutionOutline: ["cascade와 request 실패를 분리합니다.", "font fallback과 loading policy를 고칩니다.", "actual composed colors와 states를 재측정합니다.", "decorative/functional icon semantics를 다시 설계합니다."],
    },
    {
      difficulty: "설계",
      prompt: "다국어 공개 학습자료 사이트의 typography·color·icon 운영 체계를 설계하세요.",
      requirements: ["한국어·영문·code·emoji glyph coverage와 system/web fallback 정책을 정의합니다.", "rem scale·unitless line-height·clamp·200% resize acceptance criteria를 만듭니다.", "static/variable face, subset, preload, font-display, metrics override, self-host/third-party privacy·license trade-off를 비교합니다.", "sRGB fallback과 Oklch/P3 enhancement, light/dark/forced color token과 WCAG contrast CI를 정의합니다.", "decorative/informative/functional icon component API와 icon font→SVG migration 경계를 정합니다.", "CSP font-src/style-src, CORS, SRI/version pin, sanitizer, RUM/CLS/font failure monitoring을 포함합니다.", "자동 검사와 실제 사용자 typography·icon 이해도 검토를 구분합니다."],
      hints: ["한 family가 모든 glyph를 제공한다고 가정하지 않습니다.", "모든 font를 preload하는 것은 최적화가 아닙니다.", "Oklch L과 WCAG contrast를 같은 수치로 보지 않습니다.", "forced-color-adjust:none은 예외이지 기본 전략이 아닙니다."],
      expectedOutcome: "디자인 token만이 아니라 resource·실패·접근성·보안·운영 책임이 연결된 production-ready 정책을 제시합니다.",
      solutionOutline: ["콘텐츠 언어와 사용자 preference를 먼저 모델링합니다.", "fallback-first typography와 semantic color contract를 설계합니다.", "font/icon delivery architecture를 측정해 선택합니다.", "browser matrix·failure matrix·RUM과 governance를 정의합니다."],
    },
  ],
  reviewQuestions: [
    { question: "font-family의 첫 이름이 설치되어 있으면 모든 글자가 반드시 그 font로 보이나요?", answer: "아닙니다. 해당 face에 특정 glyph가 없거나 style/weight가 맞지 않으면 글자 cluster별로 다음 fallback face가 사용될 수 있습니다." },
    { question: "system-ui의 장점과 한계는 무엇인가요?", answer: "추가 다운로드 없이 OS 친화적이고 빠르지만 기기마다 실제 face와 metrics가 달라 pixel-identical 디자인을 보장하지 않습니다." },
    { question: "font-size에서 em과 rem의 기준은 어떻게 다른가요?", answer: "em은 부모의 computed font-size, rem은 root element의 em 기준을 사용하므로 em은 중첩 배율이 누적되고 rem은 깊이와 무관합니다." },
    { question: "본문 line-height를 24px보다 1.5처럼 unitless로 상속하는 이유는 무엇인가요?", answer: "number가 descendant에 그대로 상속되어 각자의 font-size에 다시 곱해지므로 큰 child text에도 비례하는 line box를 만들기 쉽습니다." },
    { question: "font-weight:650을 쓰면 모든 family가 정확한 650 glyph를 제공하나요?", answer: "아닙니다. 실제 face/variable axis 범위가 없으면 가까운 face 또는 synthetic weight가 선택될 수 있습니다." },
    { question: "font-display:swap은 FOIT와 CLS를 모두 자동 제거하나요?", answer: "fallback text를 빨리 보여 FOIT를 줄이지만 webfont 교체 때 metrics가 다르면 FOUT와 layout shift가 생길 수 있습니다." },
    { question: "document.fonts.ready가 resolve되면 이후 font load는 절대 없나요?", answer: "아닙니다. 현재 필요한 font와 layout이 안정된 시점이며 이후 새 text/style이 다른 face를 요구하면 추가 load가 시작될 수 있습니다." },
    { question: "rgba(.../0) background는 element를 DOM·layout·접근성에서 제거하나요?", answer: "아닙니다. 색만 완전 투명하며 element와 layout, text, interaction은 별도로 남습니다." },
    { question: "Oklch lightness가 같으면 WCAG contrast도 같나요?", answer: "그렇지 않습니다. Oklch는 색 설계에 유용하지만 최종 sRGB/wide-gamut used color와 실제 background로 contrast ratio를 별도 계산해야 합니다." },
    { question: "WCAG AA 일반 text와 large text의 최소 contrast는 각각 얼마인가요?", answer: "일반 text는 4.5:1, large-scale text는 3:1입니다. UI component와 필요한 graphic은 non-text contrast 3:1도 검토합니다." },
    { question: "forced-colors에서 brand RGB를 유지하려고 모든 요소에 forced-color-adjust:none을 줘도 되나요?", answer: "안 됩니다. 사용자 palette를 무력화하므로 일반 text/control에는 auto와 system colors를 쓰고 색 자체가 정보인 좁은 예외만 검토합니다." },
    { question: "visible '저장' label 옆 SVG나 icon font는 어떻게 접근성 처리하나요?", answer: "같은 의미를 반복하는 장식 icon은 control 안에서 aria-hidden=true로 숨기고 accessible name은 visible label에서 한 번 제공하는 것이 견고합니다." },
    { question: "icon-only button의 aria-label은 icon 요소와 button 중 어디에 두는 편이 좋은가요?", answer: "상호작용하고 focus받는 button 자체에 기능 이름을 두어 control의 accessible name을 명확히 합니다." },
  ],
  completionChecklist: [
    "family 후보·generic family·glyph fallback을 구분하고 실제 rendered face를 확인할 수 있다.",
    "system stack과 webfont를 성능·일관성·privacy 기준으로 선택할 수 있다.",
    "em/rem 중첩과 unitless line-height의 computed pixel 값을 계산할 수 있다.",
    "200% text resize에서 clipping·overlap·기능 손실을 검증할 수 있다.",
    "static/variable face와 font-weight/style/optical sizing의 matching 범위를 설명할 수 있다.",
    "@font-face·font-display·FontFaceSet·FOIT/FOUT·fallback·CLS를 함께 진단할 수 있다.",
    "subset·preload·metrics override·CORS·CSP·라이선스·third-party privacy를 검토할 수 있다.",
    "named·HEX/HEXA·rgb/hsl·Oklch/P3와 alpha·opacity의 차이를 설명할 수 있다.",
    "실제 foreground/background 합성으로 text·non-text contrast를 계산할 수 있다.",
    "색상 외 단서와 light/dark/forced colors 대응을 설계할 수 있다.",
    "장식·정보·기능 icon을 구분하고 accessible name/aria-hidden을 올바른 요소에 적용할 수 있다.",
    "icon font 차단과 SVG currentColor의 실패 결과를 browser에서 검증할 수 있다.",
  ],
  nextSessions: ["css-05-display-box-model"],
  sources: [
    { id: "web-day01-color-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day01/ex07_color.html", usedFor: ["named color", "background/text/border color", "RGB·RGBA", "HEX·HEXA", "alpha 0", "설명과 #00FF77 불일치"], evidence: "전체 source와 주석을 읽고 Chromium에서 skyblue=rgb(135,206,235), alpha-zero background와 layout 유지, #00FF77=rgb(0,255,119), #FF000088 alpha serialization을 실행 확인했습니다." },
    { id: "web-day04-font-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex04_font.html", usedFor: ["font-family fallback", "weight", "px·em·rem", "중첩 크기", "line-height"], evidence: "전체 source를 읽고 Chromium computed result h1 48px, p 32px, child 48px, nested 96px, nested2 32px, li line-height 24/16/80px를 실행 확인했습니다." },
    { id: "web-day04-webfont-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex05_webfont.html", usedFor: ["Google Fonts @import", "Nanum Pen Script·Gugi", "cursive fallback", "unicode-range lazy loading"], evidence: "전체 source를 읽고 external stylesheet 로딩 뒤 FontFaceSet과 computed family를 조사했습니다. 현재 응답은 많은 unicode-range face를 선언하고 실제 heading에 필요한 일부만 loaded했습니다." },
    { id: "web-day04-iconfont-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex06_iconfont.html", usedFor: ["Font Awesome CDN", "SRI·crossorigin", "::before private-use glyph", "navigation icon markup"], evidence: "전체 source를 읽고 Chromium에서 Font Awesome 6 Free, weight 900, ::before glyph, aria-hidden 부재, icon과 anchor가 sibling인 구조를 실행 확인했습니다." },
    { id: "css-fonts-4", repository: "W3C CSS Fonts Module Level 4", path: "TR/css-fonts-4/", publicUrl: "https://www.w3.org/TR/css-fonts-4/", usedFor: ["font-family matching", "@font-face src/descriptors", "font-display periods", "variable font ranges", "font variations", "metrics override", "unicode-range"], evidence: "2026-07-12 기준 W3C specification의 family/glyph fallback, face matching, font-display, variable axis와 metrics descriptor를 확인했습니다." },
    { id: "css-font-loading-3", repository: "W3C CSS Font Loading Module Level 3", path: "TR/css-font-loading/", publicUrl: "https://www.w3.org/TR/css-font-loading/", usedFor: ["document.fonts", "FontFaceSet load/check/status", "ready와 layout 안정 시점", "loading events"], evidence: "FontFaceSet load/check/ready의 Promise와 상태 계약을 확인하고 invalid font 실행 예제의 NetworkError/error/false 결과와 대조했습니다." },
    { id: "css-values-3", repository: "W3C CSS Values and Units Module Level 3", path: "TR/css-values-3/", publicUrl: "https://www.w3.org/TR/css-values-3/", usedFor: ["font-relative em/rem units", "root em 기준", "relative/absolute length"], evidence: "em과 rem이 current/root font metrics에 상대적인 길이라는 표준 정의를 확인했습니다." },
    { id: "css-inline-3", repository: "W3C CSS Inline Layout Module Level 3", path: "TR/css3-linebox/#line-height-property", publicUrl: "https://www.w3.org/TR/css3-linebox/#line-height-property", usedFor: ["line-height number·length·percentage", "상속 차이", "line box와 font metrics"], evidence: "unitless number가 number로 상속되고 각 element font-size에 곱해지며 length/percentage 상속과 다른 결과를 낸다는 정의를 확인했습니다." },
    { id: "css-color-4", repository: "W3C CSS Color Module Level 4", path: "TR/css-color-4/", publicUrl: "https://www.w3.org/TR/css-color-4/", usedFor: ["RGB·HSL·alpha 현대 문법", "4/8-digit HEX", "Lab/LCH·Oklab/Oklch", "Display P3·predefined spaces", "system colors"], evidence: "2026-07-12 기준 sRGB와 wide/device-independent color function, slash alpha, HEX alpha, color-space/gamut 정의를 확인했습니다." },
    { id: "wcag22", repository: "W3C Web Content Accessibility Guidelines 2.2", path: "TR/WCAG22/#distinguishable", publicUrl: "https://www.w3.org/TR/WCAG22/#distinguishable", usedFor: ["use of color", "text contrast 4.5:1·large 3:1", "non-text contrast", "200% resize", "images of text"], evidence: "WCAG 2.2의 1.4.1, 1.4.3, 1.4.4, 1.4.11 요구를 typography/color/icon acceptance criteria에 반영했습니다." },
    { id: "css-color-adjust-1", repository: "W3C CSS Color Adjustment Module Level 1", path: "TR/css-color-adjust-1/#forced-color-palettes", publicUrl: "https://www.w3.org/TR/css-color-adjust-1/#forced-color-palettes", usedFor: ["forced colors palette", "force-adjusted properties", "system colors", "forced-color-adjust"], evidence: "forced colors가 user palette로 color/background/border/fill/stroke 등을 조정하고 shadow/background-image 일부를 제거할 수 있다는 표준 동작을 확인했습니다." },
    { id: "wai-aria24", repository: "W3C WAI Technique ARIA24", path: "WAI/WCAG21/Techniques/aria/ARIA24.html", publicUrl: "https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA24.html", usedFor: ["font icon semantic identification", "visible label과 aria-hidden decorative icons", "icon-only link accessible name", "user font override"], evidence: "visible text가 이름을 제공할 때 여러 font icon을 별도 element에 두고 aria-hidden 처리하는 예와 icon-only link에 이름을 제공하는 경계를 확인했습니다." },
  ],
  sourceCoverage: {
    filesRead: 4,
    filesUsed: 4,
    uncoveredNotes: [
      "원본 네 파일의 source·주석을 모두 읽고 data-URL instrumentation을 더한 Chromium headless 실행으로 computed color/font, FontFaceSet, ::before icon 상태를 확인했습니다. local provenance는 repository-relative path만 기록했습니다.",
      "원본의 100~900·em/rem·line-height 설명은 current W3C CSS Fonts/Values/Inline의 variable ranges·unitless inheritance·glyph matching으로 확장했습니다.",
      "원본 Google Fonts·Font Awesome 외부 URL은 학습 source의 감사 대상일 뿐 이 세션 sources의 공개 근거 URL로 재사용하지 않았습니다. 운영 예제는 외부 service 없이 fallback·invalid-font 실패와 inline SVG로 재현했습니다.",
      "FOIT/FOUT, font-display, FontFaceSet, variable font, metrics override, Oklch/P3, WCAG contrast, forced colors, SVG·icon accessible-name 경계는 원본을 초보→전문가 과정으로 보강한 범위입니다.",
      "font file 제작·hinting·OpenType table 편집, 고급 color-management pipeline과 SVG path authoring은 별도 전문 도구 세션 범위로 남깁니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
