import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-05-display-box-model"],
  slug: "css-05-display-box-model",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 5,
  title: "normal flow, display와 content-box/border-box 계산",
  subtitle: "DOM에서 box tree가 만들어지는 순간부터 block·inline·inline-block의 흐름, 숨김 경계, 네 겹 box model, intrinsic sizing과 overflow, 실제 DOMRect 진단까지 수치로 추적합니다.",
  level: "기초",
  estimatedMinutes: 215,
  coreQuestion: "element가 어떤 box를 만들고 normal flow에 어떻게 참여하며, 선언한 width가 padding·border·content와 결합되어 화면의 실제 크기가 되는 과정을 어떻게 계산하고 검증할까요?",
  summary: "원본 display 예제의 block·inline·inline-block·none·visibility 주석, box-sizing 예제의 200px content-box/border-box 계산, border 예제의 style·width·color 조합을 모두 감사했습니다. DOM tree와 box tree의 차이, outer/inner display type, normal flow, display:none·contents와 visibility·opacity의 layout·interaction·accessibility 경계, content/padding/border/margin box, box-sizing의 정확한 가로·세로 공식, auto·min/max·min-content·max-content·fit-content, replaced element의 natural size와 aspect ratio, overflow 값의 scroll container 차이, getComputedStyle·getClientRects·getBoundingClientRect·client/scroll size를 이용한 production 진단까지 하나의 측정 가능한 mental model로 확장합니다.",
  objectives: [
    "DOM element와 CSS box가 1:1이라고 가정할 수 없는 이유와 normal flow의 block/inline formatting을 설명할 수 있다.",
    "outer display type과 inner display type을 분리해 block·inline·inline-block·flow-root·flex·grid의 역할을 예측할 수 있다.",
    "display:none·display:contents·visibility:hidden·opacity:0이 layout·hit testing·focus·speech/accessibility에 미치는 차이를 설명할 수 있다.",
    "content·padding·border·margin area와 edge를 구분하고 border box·margin box 크기를 손으로 계산할 수 있다.",
    "content-box와 border-box에서 width·height가 가리키는 edge를 구분하고 실제 content 크기까지 정확히 계산할 수 있다.",
    "auto·min/max·min-content·max-content·fit-content와 replaced element의 intrinsic size·aspect ratio가 used size를 제한하는 과정을 설명할 수 있다.",
    "overflow visible·hidden·clip·auto·scroll의 clipping과 scroll container 차이를 선택 기준과 접근성 위험까지 포함해 판단할 수 있다.",
    "DevTools와 CSSOM geometry API로 border box·overflow·fragment를 측정하고 layout 문제를 단계적으로 진단할 수 있다.",
  ],
  prerequisites: [
    {
      title: "폰트, 웹폰트, 색상 체계와 아이콘 폰트",
      reason: "inline box와 line box의 실제 크기는 font metrics와 line-height의 영향을 받고 border·background·opacity는 색과 painting 단계에 연결됩니다. typography와 alpha를 알아야 크기 문제와 paint 문제를 구분할 수 있습니다.",
      sessionSlug: "css-04-typography-color-icons",
    },
  ],
  keywords: ["normal flow", "box tree", "display", "outer display", "inner display", "block", "inline", "inline-block", "flow-root", "none", "contents", "visibility", "opacity", "box model", "content box", "padding box", "border box", "margin box", "box-sizing", "intrinsic size", "min-content", "max-content", "fit-content", "replaced element", "overflow", "getBoundingClientRect"],
  chapters: [
    {
      id: "dom-to-box-tree-normal-flow",
      title: "CSS는 DOM tree를 그대로 배치하지 않고 zero-or-more box를 가진 box tree로 변환합니다",
      lead: "layout 문제를 element 좌표 하나로만 생각하면 anonymous box·inline fragment·display:none·contents를 설명할 수 없습니다. 먼저 DOM과 box tree를 분리합니다.",
      explanations: [
        "HTML parser가 만든 DOM은 의미와 parent/child 관계를 담습니다. CSS cascade가 각 node의 computed value를 정한 뒤 display와 layout 규칙이 rendering용 box tree를 만듭니다. 대부분 element는 principal box 하나를 만들지만 list-item은 marker box도 만들고 table은 wrapper와 grid box를 만들며 inline content는 여러 line의 box fragment로 나뉠 수 있습니다. 반대로 display:none은 subtree box를 만들지 않고 display:contents는 element 자신의 box만 없앨 수 있습니다.",
        "normal flow는 position:absolute/fixed처럼 flow 밖으로 빼거나 float로 옆에 띄우지 않은 in-flow box가 기본 formatting 규칙에 따라 놓이는 상태를 뜻합니다. 별도의 display 값이 아니라 layout 출발점입니다. block formatting에서 block-level box는 block axis를 따라 차례로 놓이고, inline formatting에서 text와 inline-level box는 line box 안에서 inline axis를 따라 흐르다가 가용 너비에서 줄을 바꿉니다.",
        "horizontal writing mode에서 block은 흔히 위아래, inline은 좌우라고 설명하지만 이것은 writing mode에 따른 결과입니다. vertical writing에서는 block/inline axis 방향이 달라집니다. 전문가 코드는 width/height만 외우기보다 inline-size·block-size, margin-inline·padding-block 같은 logical property를 사용해 문서 방향 변화에도 의도가 보이게 할 수 있습니다.",
        "원본은 div의 display를 block·inline·inline-block으로 바꾸어 한 element가 다른 box 역할을 갖는 모습을 보여 줍니다. HTML element 이름은 기본 UA style을 제공하지만 div가 영원히 block이고 span이 영원히 inline인 문법 규칙은 아닙니다. CSS display를 바꿔도 div의 HTML 의미가 span으로, span의 semantic role이 button으로 변하지는 않습니다.",
        "box tree에는 DOM에 없는 anonymous box가 생길 수 있습니다. block container 안에서 inline text와 block child가 섞이거나 table-internal box가 잘못 배치되면 formatting context가 요구하는 wrapper를 browser가 생성합니다. DevTools DOM만 보고 모든 intermediate box가 보인다고 기대하지 말고 specification의 formatting model과 rendered fragments를 함께 봅니다.",
      ],
      concepts: [
        { term: "box tree", definition: "computed CSS와 display/layout 규칙을 바탕으로 document tree에서 생성되는 formatting 구조입니다.", detail: ["한 element가 zero·one·multiple box를 만들 수 있습니다.", "DOM에 없는 anonymous box가 생길 수 있습니다.", "layout·fragmentation·painting은 이 구조를 사용합니다."], analogy: "원고의 문단 구조가 인쇄 조판에서 페이지·단·줄 조각으로 다시 나뉘는 것과 비슷합니다." },
        { term: "principal box", definition: "element가 생성하는 주된 box로, containing block과 하위 content layout의 기준 역할을 합니다.", detail: ["추가 marker/table box가 있을 수 있습니다.", "display:none과 contents에서는 element 자신의 principal box가 없습니다."] },
        { term: "normal flow", definition: "box가 기본 flow layout 규칙에 참여해 source order와 formatting context에 따라 배치되는 상태입니다.", detail: ["position:static/relative의 in-flow box가 대표적입니다.", "absolute/fixed box는 normal flow 공간을 차지하지 않습니다.", "block flow와 inline flow를 포함합니다."] },
        { term: "box fragment", definition: "한 box가 line·page·column 경계에서 나뉘어 만들어진 개별 rendering 조각입니다.", detail: ["긴 inline은 여러 client rect를 가질 수 있습니다.", "하나의 bounding rectangle이 실제 그려진 모든 내부 빈 공간을 뜻하지는 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "DOM에는 element 하나인데 getClientRects()가 여러 rectangle을 반환하거나 반대로 element가 있는데 rect가 0×0이다.",
          likelyCause: "inline box가 여러 line fragment로 나뉘었거나 display:none/contents처럼 element와 associated box가 1:1이 아닙니다.",
          checks: ["computed display 값을 확인합니다.", "getClientRects().length와 각 rect를 기록합니다.", "ancestor에 display:none이 있는지 확인합니다.", "display:contents element 자체가 아닌 child box를 측정합니다.", "text wrapping과 writing mode를 확인합니다."],
          fix: "측정 목적에 맞게 fragment 목록 또는 실제 child box를 사용하고 DOM node 수를 geometry box 수로 간주하지 않습니다.",
          prevention: "layout code의 계약에 '어느 edge의 어느 fragment를 측정하는가'를 명시하고 multi-line·hidden·contents fixture를 test합니다.",
        },
      ],
      expertNotes: ["layout read는 style/layout 계산을 요구할 수 있습니다. 반복 loop에서 DOM write와 geometry read를 번갈아 수행하면 forced synchronous layout이 누적되므로 read phase와 write phase를 나누고 변화 관찰에는 ResizeObserver를 고려합니다.", "visual order와 DOM order는 다른 tree를 소비하는 사용자에게 다르게 보일 수 있습니다. 이후 flex/grid에서도 source order를 logical reading·focus order의 기준으로 유지합니다."],
    },
    {
      id: "outer-inner-display-block-inline",
      title: "outer display는 자기 box의 흐름 참여를, inner display는 자식 layout 방식을 정합니다",
      lead: "block·inline을 element의 고정 종류로 외우지 않고 '밖에서는 어떻게 놓이고 안에서는 무엇으로 자식을 배치하는가'라는 두 축으로 읽습니다.",
      explanations: [
        "CSS Display의 modern model에서 display는 outer와 inner type을 가질 수 있습니다. outer block은 principal box가 flow layout에서 block-level로 참여하고 outer inline은 inline-level로 참여합니다. inner flow는 자식을 normal flow로 배치하고 flow-root는 독립 block formatting context를 만들며 flex와 grid는 각각 별도 formatting context를 만듭니다.",
        "legacy single keyword `block`은 일반적으로 `block flow`, `inline`은 `inline flow`, `inline-block`은 `inline flow-root`에 대응합니다. 따라서 inline-block은 밖에서 text처럼 한 line에 놓이는 atomic inline-level box지만, 내부는 block container처럼 독립적으로 content를 배치하고 width/height를 적용받습니다. `flex`는 block flex, `inline-flex`는 inline flex이므로 flex라는 inner layout과 바깥 흐름 참여를 분리할 수 있습니다.",
        "normal-flow non-replaced block box의 width:auto는 단순히 width:100%로 치환되는 값이 아닙니다. containing block의 가용 inline size에서 margin·border·padding을 고려하는 constraint equation으로 used width가 정해집니다. 반면 content-box에서 width:100%를 명시한 뒤 padding과 border를 더하면 containing block보다 커질 수 있습니다. 'block은 부모 100%'라는 원본 설명은 첫 감각으로는 유용하지만 운영 진단에는 auto와 percentage를 구분해야 합니다.",
        "non-replaced inline box에는 width가 적용되지 않고 content가 line box 안에서 fragment를 만듭니다. height도 block처럼 box 높이를 강제하지 않으며 line-height와 font metrics가 line box에 관여합니다. inline의 좌우 padding·border·margin은 flow에 반영되지만 위아래 decoration은 그려져도 주변 line 간격을 block box처럼 밀어내지 않아 겹침이 생길 수 있습니다. 정확한 크기 control이 필요하면 inline-block 또는 적절한 layout context를 선택합니다.",
        "inline-block의 width:auto는 content와 available space를 함께 고려하는 fit-content/shrink-to-fit 성격을 가집니다. 여러 inline-block 사이 source whitespace는 text space로 layout되어 예상치 못한 gap이 보이고 기본 baseline alignment 때문에 아래쪽 여백처럼 보일 수 있습니다. gap 해결을 위해 font-size:0 같은 부작용 있는 hack보다 flex/grid의 gap을 선택하는 경우가 많습니다.",
        "display:flow-root는 outer block·inner flow-root로 새 block formatting context를 만듭니다. float containment, margin interaction, 외부 float 회피 같은 boundary를 만들 수 있지만 무조건 모든 wrapper에 적용할 값은 아닙니다. 원인을 모르고 overflow:hidden으로 BFC를 만들면 content clipping까지 생길 수 있으므로 layout boundary 의도에는 flow-root가 더 직접적입니다.",
      ],
      concepts: [
        { term: "outer display type", definition: "principal box 자체가 parent의 flow layout에서 block-level인지 inline-level인지 정하는 축입니다.", detail: ["block과 inline이 대표적입니다.", "replaced element에도 outer role은 영향을 줍니다.", "position/float에 따라 computed display가 blockification될 수 있습니다."] },
        { term: "inner display type", definition: "non-replaced element의 descendant box를 어떤 formatting context로 배치할지 정하는 축입니다.", detail: ["flow·flow-root·flex·grid·table 등이 있습니다.", "replaced element 내부 content layout은 CSS display의 범위 밖입니다."] },
        { term: "inline-block", definition: "outer inline과 inner flow-root를 결합한 atomic inline-level block container입니다.", detail: ["한 line에 놓일 수 있습니다.", "width·height를 적용받습니다.", "baseline과 source whitespace를 고려해야 합니다."] },
        { term: "block formatting context", definition: "내부 block layout을 외부 float·margin 등과 일정 부분 분리하는 독립 formatting 환경입니다.", detail: ["flow-root가 명시적으로 생성합니다.", "flex/grid container도 각각 독립 formatting context 특성을 가집니다.", "상세 margin collapse는 다음 세션에서 다룹니다."] },
      ],
      codeExamples: [
        {
          id: "display-box-generation-matrix",
          title: "block·inline·inline-block·none·contents의 computed display와 box 생성 측정",
          language: "html",
          filename: "display-matrix.html",
          purpose: "원본 display 예제를 span 기반으로 재구성해 width/height 적용, box 미생성, contents child box 보존을 exact boolean과 DOMRect로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>display box 측정</title>\n  <style>\n    body { margin: 0; font: 16px/1 sans-serif; }\n    .sample { width: 100px; height: 40px; }\n    #block { display: block; box-sizing: border-box; }\n    #inline { display: inline; }\n    #inline-block { display: inline-block; box-sizing: border-box; }\n    #none { display: none; }\n    #contents { display: contents; }\n  </style>\n</head>\n<body>\n  <span id=\"block\" class=\"sample\">블록</span>\n  <span id=\"inline\" class=\"sample\">인라인</span>\n  <span id=\"inline-block\" class=\"sample\">인라인 블록</span>\n  <span id=\"none\">없음</span>\n  <span id=\"contents\"><span id=\"contents-child\">contents 자식</span></span>\n  <pre id=\"output\"></pre>\n  <script>\n    const byId = (id) => document.querySelector(\"#\" + id);\n    const size = (id) => {\n      const rect = byId(id).getBoundingClientRect();\n      return Math.round(rect.width) + \"x\" + Math.round(rect.height);\n    };\n    const lines = [\n      \"block | display=\" + getComputedStyle(byId(\"block\")).display + \" | rect=\" + size(\"block\"),\n      \"inline | display=\" + getComputedStyle(byId(\"inline\")).display + \" | rect-width<100=\" + (byId(\"inline\").getBoundingClientRect().width < 100),\n      \"inline-block | display=\" + getComputedStyle(byId(\"inline-block\")).display + \" | rect=\" + size(\"inline-block\"),\n      \"none | display=\" + getComputedStyle(byId(\"none\")).display + \" | rects=\" + byId(\"none\").getClientRects().length,\n      \"contents | display=\" + getComputedStyle(byId(\"contents\")).display + \" | rects=\" + byId(\"contents\").getClientRects().length + \" | child-rects=\" + byId(\"contents-child\").getClientRects().length,\n    ];\n    document.querySelector(\"#output\").textContent = lines.join(\"\\n\");\n    console.log(lines.join(\"\\n\"));\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "1-13", explanation: "font·line-height·body margin을 고정하고 세 visible sample에 같은 100×40 선언을 둡니다. block과 inline-block은 border-box로 정확한 rect를 만들지만 non-replaced inline에는 width/height가 적용되지 않습니다." },
            { lines: "15-21", explanation: "각 display value와 contents child를 실제 DOM에 둡니다. output pre는 browser console이 없어도 exact 결과를 화면에서 복사하게 합니다." },
            { lines: "23-27", explanation: "getBoundingClientRect의 CSS pixel 값을 반올림해 block/inline-block의 선언 크기를 검산합니다." },
            { lines: "28-34", explanation: "computed display, inline actual rect가 100px보다 작은지, box가 없는 none/contents의 client rect 수, contents child가 계속 box를 만드는지를 한 줄씩 출력합니다." },
            { lines: "35-36", explanation: "화면과 Console에 같은 문자열을 남겨 visual result와 자동 test 결과를 일치시킵니다." },
          ],
          run: { environment: ["현대 Chromium·Firefox·Safari 계열 browser", "DevTools Console"], command: "browser에서 display-matrix.html을 열고 화면의 pre와 Console 출력 비교" },
          output: {
            value: "block | display=block | rect=100x40\ninline | display=inline | rect-width<100=true\ninline-block | display=inline-block | rect=100x40\nnone | display=none | rects=0\ncontents | display=contents | rects=0 | child-rects=1",
            explanation: ["block과 inline-block은 width/height가 used border box 크기가 되어 100×40입니다.", "inline은 선언된 width가 non-replaced inline에 적용되지 않아 text 폭이 100보다 작습니다.", "none subtree는 associated box가 없고 contents element도 자신의 box가 없습니다.", "contents의 normal child는 box를 계속 생성하므로 child rect는 하나입니다."],
          },
          experiments: [
            { change: "#inline을 display:inline-block으로 바꿉니다.", prediction: "두 번째 줄의 display가 inline-block, rect-width<100은 false가 됩니다.", result: "outer inline은 유지하면서 atomic box에 width/height가 적용됩니다." },
            { change: "#contents에 padding:20px과 border:5px solid를 추가합니다.", prediction: "contents element의 rects는 여전히 0이고 자신의 padding/border 배경 box가 보이지 않습니다.", result: "box를 생성하지 않는 element의 non-inherited box decoration에는 그릴 대상이 없습니다." },
            { change: "#none을 visibility:hidden으로 바꿉니다.", prediction: "display computed value는 inline이고 rect가 생겨 layout 공간은 남지만 visible/interactable하지 않습니다.", result: "box 생성과 rendering visibility는 서로 다른 축입니다." },
          ],
          sourceRefs: ["web-display-source", "css-display-3", "cssom-view-1", "css22-visual-sizing"],
        },
      ],
      diagnostics: [
        {
          symptom: "span에 width:100px과 height:100px을 줬는데 computed style에는 값이 보이면서 화면 크기는 content 그대로다.",
          likelyCause: "non-replaced inline box에는 width/height가 적용되지 않으며 line box 크기는 font와 line-height의 영향을 받습니다.",
          checks: ["computed display가 inline인지 확인합니다.", "element가 img 같은 replaced element인지 구분합니다.", "getClientRects로 line fragment를 봅니다.", "line-height와 vertical padding/border가 주변 line을 실제로 밀어내는지 확인합니다."],
          fix: "정확한 atomic size가 필요하면 inline-block으로, sibling layout과 gap 관리까지 필요하면 flex/grid container로 설계합니다.",
          prevention: "component 요구를 outer flow·inner layout·sizing 세 항목으로 적고 element 이름만 보고 display behavior를 추정하지 않습니다.",
        },
      ],
      comparisons: [
        {
          title: "text 흐름 안의 작은 UI를 어떻게 배치할까요?",
          options: [
            { name: "inline", chooseWhen: "문장 속 강조 text처럼 content 크기와 line wrapping을 그대로 따를 때", avoidWhen: "정확한 width/height와 독립 내부 layout이 필요할 때", tradeoffs: ["자연스럽게 여러 line에 fragment됩니다.", "non-replaced inline에는 width/height가 적용되지 않습니다.", "vertical decoration이 line 간격을 예상대로 밀지 않을 수 있습니다."] },
            { name: "inline-block", chooseWhen: "badge·작은 control처럼 한 덩어리로 line에 놓고 크기를 지정할 때", avoidWhen: "많은 sibling의 gap·정렬·반응형 wrap을 체계적으로 관리할 때", tradeoffs: ["width/height와 내부 flow-root를 얻습니다.", "baseline·whitespace gap을 관리해야 합니다.", "atomic하여 내부에서 line fragment로 쪼개지지 않습니다."] },
            { name: "inline-flex", chooseWhen: "icon+label처럼 내부 item 축 정렬이 필요하면서 바깥에서는 inline으로 흐를 때", avoidWhen: "단순 text 의미만 필요한 경우", tradeoffs: ["inner flex alignment와 gap을 제공합니다.", "flex item sizing 규칙을 추가로 이해해야 합니다.", "DOM logical order는 유지해야 합니다."] },
          ],
        },
      ],
    },
    {
      id: "box-generation-visibility-accessibility",
      title: "display:none·contents, visibility:hidden, opacity:0은 box·paint·interaction 경계를 서로 다르게 자릅니다",
      lead: "모두 '안 보인다'고 말할 수 있지만 layout 공간, child box, pointer hit test, keyboard navigation, speech/accessibility 결과가 다릅니다.",
      explanations: [
        "display:none은 element와 descendant가 box와 text sequence를 생성하지 않게 합니다. DOM에서 node가 삭제되는 것은 아니므로 querySelector와 state 변경은 가능하지만 layout 공간·visual rendering·일반 interactivity와 speech output에서 빠집니다. 숨긴 control 안에 focus가 있었다면 상태 전환 전에 focus를 합리적인 trigger나 다음 content로 이동시켜야 합니다.",
        "display:contents는 element 자신의 box를 없애고 child·pseudo-element box를 parent formatting context에 놓습니다. selector matching, event bubbling, property inheritance처럼 DOM tree 기반 관계는 남습니다. 그러나 padding·border·background·getBoundingClientRect를 적용할 own box가 없고, replaced element·form control·unusual table/SVG/MathML element에는 special behavior가 있습니다.",
        "CSS Display 표준은 display:contents가 document semantics를 바꾸지 않아야 한다고 설명하면서도 major browser 구현이 accessibility tool에 element semantics를 전달하지 못할 수 있다고 경고합니다. semantic list·table·button wrapper를 단순 layout 편의를 위해 contents로 없애지 말고 target browser/AT matrix에서 accessibility tree를 확인합니다. box가 필요 없다는 layout 요구와 role이 필요 없다는 의미 요구는 같지 않습니다.",
        "visibility:hidden은 box generation을 유지해 공간은 남기지만 box를 render하지 않고 navigation·interaction·speech에서 제외합니다. visibility는 inherited이지만 descendant에 visibility:visible을 주면 child가 보일 수 있어 semantic container 관계가 복잡해집니다. 표준도 invisible parent와 visible semantic child 조합의 AT 구현 문제를 경고하므로 단순 hide/show 외 패턴은 신중히 test합니다.",
        "opacity:0은 element와 descendant를 offscreen image처럼 paint한 뒤 완전히 transparent하게 합성할 뿐입니다. layout box, hit testing, pointer click, keyboard focus, accessibility semantics는 기본적으로 남습니다. 따라서 보이지 않는 button이 click을 가로채거나 Tab focus를 받는 trap이 생길 수 있습니다. opacity는 fade animation과 visual transparency에 쓰고 '완전히 비활성/숨김' state는 hidden/display, visibility, inert, focus 관리 등 요구에 맞는 mechanism으로 설계합니다.",
        "pointer-events:none은 pointer hit testing만 바꾸며 keyboard focus와 accessibility tree를 제거하지 않습니다. aria-hidden은 visual layout을 바꾸지 않고 focusable descendant와 함께 사용하면 모순이 생깁니다. 한 속성으로 모든 tree를 동시에 숨긴다고 가정하지 말고 DOM, box, paint, hit testing, focus navigation, accessibility tree를 acceptance table로 만듭니다.",
      ],
      concepts: [
        { term: "display:none", definition: "element subtree가 CSS box tree에 box나 text sequence를 생성하지 않게 하는 display-box 값입니다.", detail: ["layout 공간이 없습니다.", "일반 navigation·interaction·speech에서도 빠집니다.", "DOM node와 JavaScript state는 남습니다."] },
        { term: "display:contents", definition: "element 자신의 box를 없애고 children과 pseudo-elements가 box를 평소처럼 생성하게 하는 값입니다.", detail: ["DOM selector·event·inheritance 관계는 남습니다.", "element 자체의 padding/background/rect가 없습니다.", "unusual element와 accessibility 구현을 test해야 합니다."] },
        { term: "visibility:hidden", definition: "box를 layout에 남기면서 invisible하게 만들고 interaction·navigation에서 제외하는 visibility 값입니다.", detail: ["공간을 유지해 reflow를 줄일 수 있습니다.", "descendant가 visible로 override할 수 있습니다.", "opacity:0과 다릅니다."] },
        { term: "opacity:0", definition: "element 전체 rendering을 완전히 transparent하게 합성하는 paint/compositing 상태입니다.", detail: ["box와 hit testing은 남습니다.", "focus/accessibility가 자동으로 제거되지 않습니다.", "opacity가 1 미만이면 stacking context를 만듭니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "화면에는 아무것도 없는데 Tab focus가 사라지거나 보이지 않는 영역을 click하면 button이 실행된다.",
          likelyCause: "opacity:0을 hide/disable mechanism으로 사용해 box·hit testing·focusability가 그대로 남았습니다.",
          checks: ["activeElement와 Tab 순서를 확인합니다.", "Elements에서 opacity·visibility·display·pointer-events를 함께 봅니다.", "accessibility tree에 control이 남는지 확인합니다.", "elementFromPoint로 pointer target을 검사합니다.", "hide transition 종료 전후 state 순서를 확인합니다."],
          fix: "fade가 끝난 뒤 실제 hidden state를 적용하고 focus를 trigger로 복귀시키며, interaction 차단이 필요하면 inert 등 semantic state를 함께 사용합니다.",
          prevention: "visible·fading·hidden state마다 layout, pointer, keyboard, AT acceptance 조건을 component test에 명시합니다.",
        },
        {
          symptom: "display:contents를 적용한 list/table/navigation wrapper의 visual layout은 좋아졌지만 screen reader에서 group role이나 이름이 사라진다.",
          likelyCause: "own box 제거와 DOM semantics 보존이라는 표준 의도에도 browser/AT 구현 차이가 있고 unusual element special rule이 적용될 수 있습니다.",
          checks: ["target browser의 accessibility tree를 전후 비교합니다.", "element가 replaced/form/table/SVG/MathML special case인지 봅니다.", "wrapper의 border/background/geometry 의존 code를 찾습니다.", "keyboard navigation과 event bubbling을 시험합니다."],
          fix: "semantic wrapper에는 box를 유지하고 필요한 layout은 child wrapper 또는 grid/flex 구조로 해결합니다. 지원 matrix에서 검증된 경우에만 contents를 제한적으로 사용합니다.",
          prevention: "display:contents 사용을 accessibility review 대상으로 지정하고 visual snapshot만으로 승인하지 않습니다.",
        },
      ],
      comparisons: [
        {
          title: "UI를 어떤 방식으로 숨길까요?",
          options: [
            { name: "display:none 또는 HTML hidden state", chooseWhen: "layout·interaction·일반 accessibility navigation에서 subtree를 완전히 제외할 때", avoidWhen: "자리 크기를 유지하거나 fade 중간 frame이 필요할 때", tradeoffs: ["공간과 box가 사라집니다.", "show/hide 시 reflow가 생깁니다.", "focus를 미리 안전한 곳으로 이동해야 합니다."] },
            { name: "visibility:hidden", chooseWhen: "layout 공간을 유지하면서 일시적으로 보이지 않고 상호작용하지 않게 할 때", avoidWhen: "descendant override와 semantic container 관계가 복잡한 component일 때", tradeoffs: ["box geometry가 남습니다.", "navigation·speech에서는 제외됩니다.", "상속과 visible descendant를 주의합니다."] },
            { name: "opacity:0", chooseWhen: "fade animation의 visual endpoint처럼 box와 compositing을 유지할 때", avoidWhen: "숨겨진 control이 focus·click·AT에서 사라져야 할 때", tradeoffs: ["부드러운 transparency 전환에 적합합니다.", "hit testing과 focus가 남습니다.", "stacking context와 paint 비용이 생길 수 있습니다."] },
          ],
        },
      ],
      expertNotes: ["accessible name/description 계산에는 숨겨진 referenced text가 특별히 사용되는 경우가 있어 'accessibility tree에서 숨김'을 단순 DOM 삭제와 동일시할 수 없습니다. 최종 control의 computed name/description을 실제 accessibility API로 확인합니다.", "display는 일반적으로 HTML semantics를 바꾸지 않습니다. span에 display:block을 줘도 heading이나 button role이 생기지 않으며 semantic element와 keyboard behavior를 HTML에서 먼저 설계합니다."],
    },
    {
      id: "four-box-areas-border-source",
      title: "content·padding·border·margin은 네 개의 nested area와 edge를 만들고 서로 다른 책임을 가집니다",
      lead: "width 하나를 말할 때 content edge인지 border edge인지 먼저 정하지 않으면 개발자와 DOM API가 서로 다른 숫자를 보고도 모두 맞다고 주장하게 됩니다.",
      explanations: [
        "모든 CSS box는 content area와 선택적인 padding, border, margin area를 가집니다. content box는 text·descendant·replaced content가 놓이는 내부, padding box는 content와 안쪽 여백, border box는 padding 바깥 테두리까지, margin box는 neighboring box와의 바깥 간격까지 포함합니다. 각 area 둘레의 content/padding/border/margin edge가 sizing·background·clipping·geometry API의 기준이 됩니다.",
        "padding은 box 내부 공간이며 background painting 영역과 hit area를 넓히는 데 참여합니다. margin은 border 바깥의 투명한 spacing이고 background가 그려지지 않으며 음수일 수도 있습니다. 인접 block의 vertical margin은 조건에 따라 collapse되므로 단순히 항상 두 margin을 더한 값이 최종 간격이라고 할 수 없습니다. collapse 상세는 다음 session에서 분리해 다룹니다.",
        "원본 border 예제는 모든 div에 width:200px, height:100px, border-width:5px를 주고 class별 solid·dotted·dashed와 color를 바꿉니다. border-width만 선언해도 initial border-style이 none이면 visible border가 생기지 않습니다. style이 none이면 used border width가 zero처럼 처리되므로 DevTools에서 선언 문자열만 보지 말고 computed style과 실제 border box를 확인합니다.",
        "border shorthand `border:1px solid orange`는 width·style·color를 한 번에 정해 누락을 줄이지만 관련 longhand와 border-image를 reset할 수 있습니다. component override에서 `border-color`만 바꾸려는지 전체 border 계약을 바꾸려는지 구분합니다. dotted/dashed pattern의 실제 dash 길이는 UA에 따라 다를 수 있어 pixel-perfect data 표시 수단으로 사용하지 않습니다.",
        "outline은 border box 바깥에 그려질 수 있지만 box model 크기와 normal flow 공간을 늘리지 않습니다. 그래서 focus indicator로 outline을 써도 sibling layout이 흔들리지 않습니다. outline을 border로 바꾸면 border-box size 또는 content size가 변할 수 있으므로 focus 시 layout shift가 생기지 않도록 box-sizing과 초기 border 예약을 확인합니다.",
        "physical top/right/bottom/left 대신 padding-inline, margin-block, border-inline-start 같은 logical property를 쓰면 writing mode와 direction에 맞게 edge가 매핑됩니다. 디자인 토큰에서 space와 border를 logical axis 기준으로 정의하면 LTR·RTL·vertical writing 대응이 쉬워집니다.",
      ],
      concepts: [
        { term: "content box", definition: "width/height와 content가 기본적으로 관계하는 가장 안쪽 rectangle입니다.", detail: ["text·descendant·replaced content가 놓입니다.", "content-box sizing에서 length width가 이 edge를 지정합니다."] },
        { term: "padding box", definition: "content와 padding area를 포함해 padding edge까지의 rectangle입니다.", detail: ["background와 overflow clipping의 기준이 될 수 있습니다.", "padding은 음수가 될 수 없습니다."] },
        { term: "border box", definition: "content·padding·border를 포함해 border edge까지의 rectangle입니다.", detail: ["border-box sizing의 length width가 이 edge를 지정합니다.", "getClientRects는 각 box fragment의 border area를 기술합니다.", "margin은 포함하지 않습니다."] },
        { term: "margin box", definition: "border 바깥 margin area까지 포함한 layout box입니다.", detail: ["background가 그려지지 않습니다.", "margin collapse·negative margin 때문에 단순 합과 실제 간격이 다를 수 있습니다.", "getBoundingClientRect에 포함되지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "border-width:5px를 선언했는데 테두리가 보이지 않고 box 크기에도 5px이 더해지지 않는다.",
          likelyCause: "border-style의 initial value가 none이라 visible border가 생성되지 않고 used border width가 0이 됩니다.",
          checks: ["computed border-*-style을 확인합니다.", "shorthand가 style을 reset했는지 cascade를 봅니다.", "getBoundingClientRect와 content/padding 합을 비교합니다.", "transparent border인지 color도 확인합니다."],
          fix: "border:5px solid currentColor처럼 width·style·color 계약을 함께 선언하거나 필요한 longhand를 모두 지정합니다.",
          prevention: "border component token에 style을 포함하고 visual regression과 geometry test를 함께 둡니다.",
        },
      ],
      comparisons: [
        {
          title: "요소 사이 공간을 padding과 margin 중 어디에 둘까요?",
          options: [
            { name: "padding", chooseWhen: "배경·click area·border 안쪽에서 content와 edge 사이 공간이 필요할 때", avoidWhen: "독립 sibling 사이 외부 rhythm만 조절할 때", tradeoffs: ["background와 hit area에 포함됩니다.", "border box 크기에 참여합니다.", "content-box에서는 지정 width 밖으로 더해집니다."] },
            { name: "margin", chooseWhen: "box border 바깥에서 sibling 또는 container와 간격을 만들 때", avoidWhen: "배경을 포함하거나 click target을 넓혀야 할 때", tradeoffs: ["background·hit area에 포함되지 않습니다.", "negative와 collapse 규칙이 있습니다.", "margin box는 DOMRect에 직접 포함되지 않습니다."] },
            { name: "layout gap", chooseWhen: "flex/grid child 사이의 일관된 간격을 parent가 소유할 때", avoidWhen: "단일 element의 내부 breathing room이 필요할 때", tradeoffs: ["first/last child 예외와 margin collapse를 줄입니다.", "flex/grid formatting context가 필요합니다.", "후속 layout session에서 상세히 다룹니다."] },
          ],
        },
      ],
    },
    {
      id: "content-box-border-box-exact-math",
      title: "box-sizing은 length·percentage size가 content edge와 border edge 중 어디에 적용되는지 정합니다",
      lead: "원본의 200 + 20 + 20 + 10 + 10 계산을 가로·세로·margin·DOMRect까지 확장해 선언값과 실제 box를 정확히 연결합니다.",
      explanations: [
        "box-sizing의 initial value는 content-box입니다. width:200px이면 content width가 200px이고 좌우 padding 20px씩과 border 10px씩이 바깥에 더해져 padding box 240px, border box 260px이 됩니다. 좌우 margin이 각각 11px이면 margin box의 산술 폭은 282px입니다. height:100px도 같은 원리로 상하 padding 40px과 border 20px이 더해져 border box 160px입니다.",
        "border-box에서는 width:200px가 border box 전체를 뜻합니다. 좌우 padding 40px과 border 20px을 빼 content width는 140px입니다. height:100px에서는 content height가 40px입니다. margin은 두 방식 모두 지정 width 밖에 있으므로 좌우 11px까지 포함한 margin box 산술 폭은 222px입니다.",
        "공식은 content-box에서 borderWidth = contentWidth + paddingInlineStart + paddingInlineEnd + borderInlineStart + borderInlineEnd입니다. border-box에서 contentWidth = max(0, declaredBorderWidth - padding - border)입니다. padding+border가 declared border-box보다 크면 content가 음수가 되지 않고 0에서 floor되므로 실제 border box가 선언 width보다 커질 수 있습니다. border-box가 모든 overflow를 마법처럼 막는 것은 아닙니다.",
        "box-sizing은 inherited property가 아닙니다. `*, *::before, *::after { box-sizing:border-box }`는 generated box까지 직접 적용하는 common reset이고, html에 border-box를 둔 뒤 모든 element/pseudo-element에 inherit시키는 pattern은 component가 subtree에서 다른 sizing model을 선택할 여지를 줍니다. third-party widget과 form control의 UA default를 바꾸는 영향은 regression test합니다.",
        "percentage width도 box-sizing의 영향을 받습니다. content-box width:100%에 padding이 추가되면 container를 넘을 수 있지만 border-box width:100%는 padding·border가 percentage border box 안에 들어갑니다. 다만 margin, min-content constraint, unbreakable content, scrollbar, transform, positioned child는 여전히 overflow 원인이 될 수 있습니다.",
        "computed style 숫자는 API와 browser가 반환하는 resolved value 의미를 확인해야 합니다. border-box element에서 getComputedStyle().width는 border-box used size를 가리킬 수 있고 getBoundingClientRect는 transforms를 반영한 border-area bounding rectangle입니다. content size가 필요하면 padding과 border를 빼거나 ResizeObserver의 적절한 box option을 사용합니다.",
      ],
      concepts: [
        { term: "box-sizing:content-box", definition: "length/percentage sizing property가 content box의 inner size를 지정하고 padding·border는 그 밖에 더해지는 기본 model입니다.", detail: ["margin은 항상 지정 width 밖입니다.", "원본 box1의 border box는 260×160입니다.", "intrinsic keyword는 일반 length와 다르게 처리됩니다."] },
        { term: "box-sizing:border-box", definition: "length/percentage sizing property가 padding·border를 포함한 border box size를 지정하는 model입니다.", detail: ["content는 남은 공간을 차지하고 0 아래로 내려가지 않습니다.", "margin은 포함하지 않습니다.", "원본 box2의 content는 140×40입니다."] },
        { term: "used size", definition: "cascade와 computed value 뒤 실제 formatting context·constraints를 적용해 layout에 사용하는 크기입니다.", detail: ["auto·percentage·min/max·intrinsic size에 따라 computed 값과 달라질 수 있습니다.", "DOM geometry API는 특정 edge의 actual geometry를 제공합니다."] },
      ],
      codeExamples: [
        {
          id: "box-sizing-arithmetic-proof",
          title: "200px content-box와 border-box의 content·border·margin 폭 검산",
          language: "html",
          filename: "box-sizing-proof.html",
          purpose: "원본 ex08_box의 exact 수식을 DOMRect와 computed padding/border/margin 값으로 다시 계산해 선언 width와 실제 width의 차이를 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>box-sizing 계산</title>\n  <style>\n    body { margin: 0; }\n    .box {\n      width: 200px;\n      height: 100px;\n      padding: 20px;\n      border: 10px solid #777;\n      margin: 7px 11px;\n    }\n    #content-box { box-sizing: content-box; }\n    #border-box { box-sizing: border-box; }\n  </style>\n</head>\n<body>\n  <div id=\"content-box\" class=\"box\"></div>\n  <div id=\"border-box\" class=\"box\"></div>\n  <pre id=\"output\"></pre>\n  <script>\n    const inspect = (id) => {\n      const element = document.querySelector(\"#\" + id);\n      const style = getComputedStyle(element);\n      const rect = element.getBoundingClientRect();\n      const horizontalPadding = parseFloat(style.paddingLeft) + parseFloat(style.paddingRight);\n      const verticalPadding = parseFloat(style.paddingTop) + parseFloat(style.paddingBottom);\n      const horizontalBorder = parseFloat(style.borderLeftWidth) + parseFloat(style.borderRightWidth);\n      const verticalBorder = parseFloat(style.borderTopWidth) + parseFloat(style.borderBottomWidth);\n      const horizontalMargin = parseFloat(style.marginLeft) + parseFloat(style.marginRight);\n      const contentWidth = rect.width - horizontalPadding - horizontalBorder;\n      const contentHeight = rect.height - verticalPadding - verticalBorder;\n      return id + \" | content=\" + contentWidth + \"x\" + contentHeight + \" | border=\" + rect.width + \"x\" + rect.height + \" | margin-width=\" + (rect.width + horizontalMargin);\n    };\n    const lines = [inspect(\"content-box\"), inspect(\"border-box\")];\n    document.querySelector(\"#output\").textContent = lines.join(\"\\n\");\n    console.log(lines.join(\"\\n\"));\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "1-16", explanation: "두 box에 width 200, height 100, 사방 padding 20, border 10, horizontal margin 11을 똑같이 주고 box-sizing만 바꿉니다." },
            { lines: "18-20", explanation: "빈 content를 사용해 font·text wrapping이 측정에 개입하지 않게 합니다." },
            { lines: "22-32", explanation: "computed style에서 네 방향 padding·border·margin을 숫자로 바꾸고 getBoundingClientRect가 제공한 border box에서 content size를 역산합니다." },
            { lines: "33-34", explanation: "margin은 rect에 포함되지 않으므로 horizontal margin을 별도로 더합니다. height 계산도 같은 원리를 적용합니다." },
            { lines: "36-38", explanation: "두 결과를 화면과 Console에 같은 exact 문자열로 출력합니다." },
          ],
          run: { environment: ["현대 browser", "page zoom 100% 권장", "DevTools Console"], command: "browser에서 box-sizing-proof.html을 열고 pre와 Console 출력 확인" },
          output: {
            value: "content-box | content=200x100 | border=260x160 | margin-width=282\nborder-box | content=140x40 | border=200x100 | margin-width=222",
            explanation: ["content-box의 200×100은 content이고 padding 40·border 20이 각 축에 추가됩니다.", "border-box의 200×100은 border edge이며 content는 padding·border를 뺀 140×40입니다.", "getBoundingClientRect에는 margin이 없어서 22px을 별도로 더한 282와 222가 됩니다."],
          },
          experiments: [
            { change: "border-box의 width를 40px로 두고 사방 padding 20px, border 10px을 유지합니다.", prediction: "content width는 0에서 floor되고 padding+border 60px 때문에 실제 border box가 60px까지 커질 수 있습니다.", result: "border-box도 padding+border보다 작은 선언 size를 강제로 유지해 negative content를 만들지는 않습니다." },
            { change: "두 box의 border-style을 none으로 바꿉니다.", prediction: "used border width가 0이 되어 content-box border width는 240, border-box content width는 160이 됩니다.", result: "border-width declaration만이 아니라 computed/used border style이 geometry에 관여합니다." },
            { change: "box width를 100%, container width를 300px로 바꿉니다.", prediction: "content-box는 padding+border 때문에 360px, border-box는 300px border box가 됩니다.", result: "responsive component에서 border-box reset이 horizontal overflow를 줄이는 이유를 수치로 볼 수 있습니다." },
          ],
          sourceRefs: ["web-box-sizing-source", "web-border-source", "css-box-4", "css-sizing-3", "cssom-view-1"],
        },
      ],
      diagnostics: [
        {
          symptom: "width:100%인 card가 parent보다 정확히 padding+border만큼 넓어져 horizontal scrollbar를 만든다.",
          likelyCause: "content-box에서 100%가 content width에 적용되고 좌우 padding·border가 바깥에 더해졌습니다.",
          checks: ["computed box-sizing을 확인합니다.", "DevTools box model에서 content/padding/border 수치를 더합니다.", "getBoundingClientRect().width와 parent content width를 비교합니다.", "margin·min-width·scrollbar·100vw도 함께 배제합니다."],
          fix: "component 계약에 맞게 border-box를 적용하거나 width:auto를 유지하고 padding을 포함한 constraint equation으로 배치합니다.",
          prevention: "global/reset sizing policy에 pseudo-element를 포함하고 320px narrow viewport overflow test를 둡니다.",
        },
        {
          symptom: "border-box width가 40px인데 실제 rect는 60px이라 browser bug처럼 보인다.",
          likelyCause: "좌우 padding+border 합이 60px이고 content size는 음수가 될 수 없어 0에서 floor되었습니다.",
          checks: ["각 side padding과 used border width를 합합니다.", "min-width와 box-sizing을 확인합니다.", "content를 제거해도 rect가 같은지 봅니다."],
          fix: "declared width를 최소 padding+border 이상으로 늘리거나 spacing/border token을 줄이고 min-size contract를 명시합니다.",
          prevention: "dense variant에서 padding+border 합보다 작은 size token 조합을 design token validation으로 금지합니다.",
        },
      ],
    },
    {
      id: "auto-intrinsic-min-max-replaced",
      title: "auto와 intrinsic size는 content·available space·min/max·aspect ratio를 협상해 used size를 만듭니다",
      lead: "width를 선언하지 않았다고 size 규칙이 없는 것이 아닙니다. formatting context와 content가 preferred size를 제공하고 constraints가 이를 제한합니다.",
      explanations: [
        "width:auto는 고정 숫자가 아니라 해당 layout module이 automatic size를 계산하라는 값입니다. normal-flow non-replaced block에서는 available inline size를 채우는 constraint equation이 일반적이고, inline-block·float 등에서는 content의 min/max contribution과 available space를 clamp하는 fit-content/shrink-to-fit behavior가 나타납니다. 같은 auto라도 display와 containing block에 따라 결과가 다릅니다.",
        "min-content inline size는 가능한 soft wrap을 모두 사용했을 때 피할 수 있는 overflow 없이 줄일 수 있는 작은 크기로 이해할 수 있습니다. max-content는 soft wrapping 없이 content가 원하는 큰 크기입니다. fit-content size는 `clamp(min-content, stretch-fit, max-content)` mental model로 available space 안에서 너무 작지도 크지도 않게 선택합니다.",
        "긴 URL·hash·영문 identifier처럼 soft wrap opportunity가 없는 token은 min-content size 자체를 크게 만들어 container를 밀어낼 수 있습니다. overflow:hidden을 먼저 붙이면 content가 사라질 뿐 원인이 해결되지 않습니다. overflow-wrap:anywhere, word-break 정책, min-inline-size:0이 필요한 flex/grid item인지, user data를 적절히 wrap할지 결정합니다.",
        "width는 preferred size, min-width/min-inline-size는 하한, max-width/max-inline-size는 상한입니다. min/max constraint가 다시 used size를 조정하며 aspect-ratio가 있으면 반대 축 constraint가 전달될 수 있습니다. percentage height는 containing block의 block size가 indefinite이면 기대와 다르게 auto처럼 동작할 수 있어 부모 높이 chain을 확인합니다.",
        "img·video·iframe·input 일부처럼 replaced element는 내부 content layout이 CSS box tree의 normal child formatting과 다르고 natural width/height·intrinsic aspect ratio를 가질 수 있습니다. non-replaced inline span과 달리 inline img에는 width/height가 적용됩니다. 한 축만 지정하고 다른 축을 auto로 두면 intrinsic ratio로 계산할 수 있습니다.",
        "이미지에 HTML width와 height를 올바른 비율로 제공하면 resource load 전에도 preferred aspect ratio를 예약해 layout shift를 줄일 수 있습니다. `max-inline-size:100%; block-size:auto`는 container보다 커지지 않게 하면서 비율을 보존하는 common baseline입니다. object-fit은 replaced content를 이미 정해진 content box 안에 어떻게 맞출지 정할 뿐 box 자체의 used size를 대신 계산하지 않습니다.",
      ],
      concepts: [
        { term: "intrinsic size", definition: "주로 content 자체에서 유도되는 min-content 또는 max-content 계열 크기입니다.", detail: ["text wrapping opportunity와 replaced element natural dimension이 영향을 줍니다.", "containing block 숫자만으로 결정되지 않습니다."] },
        { term: "min-content", definition: "가능한 soft wrap을 사용했을 때 avoidable overflow 없이 줄일 수 있는 nominal minimum content size입니다.", detail: ["unbreakable token이 크게 만들 수 있습니다.", "최소 component width와 동일한 고정 숫자는 아닙니다."] },
        { term: "max-content", definition: "soft line break 없이 content가 차지하려는 nominal maximum content size입니다.", detail: ["긴 한 줄 text의 폭에 가깝습니다.", "available space보다 클 수 있습니다."] },
        { term: "replaced element", definition: "CSS formatting model이 element 내부 content representation을 직접 구성하지 않고 external object/natural dimension으로 대체해 배치하는 element입니다.", detail: ["img가 대표적입니다.", "natural size와 intrinsic ratio를 가질 수 있습니다.", "inner display type은 일반 non-replaced element와 같은 방식으로 적용되지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "constraints-overflow-replaced-measurement",
          title: "max-width constraint·overflow·intrinsic image ratio의 exact 측정",
          language: "html",
          filename: "sizing-boundaries.html",
          purpose: "preferred width가 max constraint로 줄어드는 과정, content가 scrollport보다 큰 상태, replaced img의 natural 2:1 ratio가 CSS width에서 유지되는 결과를 한 번에 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>sizing 경계 측정</title>\n  <style>\n    body { margin: 0; }\n    #limited {\n      box-sizing: border-box;\n      width: 300px;\n      max-width: 220px;\n      height: 50px;\n      padding: 10px;\n      border: 5px solid #555;\n    }\n    #viewport { width: 120px; height: 40px; overflow: auto; }\n    #oversized { width: 240px; height: 80px; }\n    #ratio { display: block; width: 80px; height: auto; }\n  </style>\n</head>\n<body>\n  <div id=\"limited\"></div>\n  <div id=\"viewport\"><div id=\"oversized\"></div></div>\n  <img id=\"ratio\" alt=\"\" src=\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='60'%3E%3C/svg%3E\">\n  <pre id=\"output\"></pre>\n  <script>\n    window.addEventListener(\"load\", () => {\n      const limited = document.querySelector(\"#limited\");\n      const limitedRect = limited.getBoundingClientRect();\n      const viewport = document.querySelector(\"#viewport\");\n      const image = document.querySelector(\"#ratio\");\n      const imageRect = image.getBoundingClientRect();\n      const lines = [\n        \"limited | border=\" + limitedRect.width + \"x\" + limitedRect.height + \" | content-width=\" + (limitedRect.width - 30),\n        \"overflow | rect=\" + viewport.getBoundingClientRect().width + \"x\" + viewport.getBoundingClientRect().height + \" | has-overflow=\" + (viewport.scrollWidth > viewport.clientWidth && viewport.scrollHeight > viewport.clientHeight),\n        \"image | natural=\" + image.naturalWidth + \"x\" + image.naturalHeight + \" | rendered=\" + imageRect.width + \"x\" + imageRect.height,\n      ];\n      document.querySelector(\"#output\").textContent = lines.join(\"\\n\");\n      console.log(lines.join(\"\\n\"));\n    });\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "1-16", explanation: "limited box의 preferred width 300을 max-width 220으로 제한하고, padding 20+border 10을 border-box 안에 둡니다. overflow viewport와 두 배 크기 child도 고정합니다." },
            { lines: "17", explanation: "120×60 natural dimension을 가진 data SVG를 inline resource로 만들어 network 없이 intrinsic 2:1 ratio를 재현합니다. CSS width 80, height auto가 ratio를 사용합니다." },
            { lines: "21-27", explanation: "모든 resource가 준비된 load event에서 DOMRect와 scroll/client dimension, image natural dimension을 읽습니다." },
            { lines: "28-32", explanation: "limited content width는 border box 220에서 horizontal padding+border 30을 뺀 190입니다. overflow는 scrollbar 크기 차이에 영향받지 않는 boolean으로, image는 exact natural/rendered pair로 출력합니다." },
          ],
          run: { environment: ["현대 browser", "network 연결 불필요", "DevTools Console"], command: "browser에서 sizing-boundaries.html을 열고 image load 뒤 pre와 Console 출력 확인" },
          output: {
            value: "limited | border=220x50 | content-width=190\noverflow | rect=120x40 | has-overflow=true\nimage | natural=120x60 | rendered=80x40",
            explanation: ["preferred width 300은 max-width 220에 제한되고 border-box이므로 content는 190입니다.", "child 240×80이 viewport 120×40보다 커 양 축 overflow가 true입니다. scrollbar가 client size를 줄여도 boolean은 유지됩니다.", "replaced image의 natural 120×60 ratio가 CSS width 80에서 height 40을 계산합니다."],
          },
          experiments: [
            { change: "#limited의 max-width를 none으로 바꿉니다.", prediction: "border rect는 preferred width 300×50, content width는 270이 됩니다.", result: "max-size는 preferred size 뒤에 적용되는 상한입니다." },
            { change: "#ratio에 width:80px와 height:80px를 모두 지정합니다.", prediction: "rendered box는 80×80이 되어 intrinsic 2:1 ratio가 box sizing에서 보존되지 않습니다.", result: "두 축 강제는 왜곡할 수 있고 object-fit은 box 안 content fitting을 별도로 제어합니다." },
            { change: "#viewport의 overflow를 clip으로 바꾸고 scrollLeft=30을 script에서 시도합니다.", prediction: "content는 clip되지만 scroll container가 아니어서 programmatic scrolling도 허용되지 않습니다.", result: "hidden과 clip은 보이는 scrollbar가 없다는 공통점만 있고 scrollability가 다릅니다." },
          ],
          sourceRefs: ["css-sizing-3", "css-sizing-4", "css-overflow-3", "cssom-view-1"],
        },
      ],
      diagnostics: [
        {
          symptom: "card에 max-width를 줬는데 긴 URL 하나가 container를 밀어내거나 flex/grid child가 줄어들지 않는다.",
          likelyCause: "unbreakable content가 큰 min-content contribution을 만들고 layout context의 automatic minimum size가 shrink를 제한합니다.",
          checks: ["긴 token을 짧은 text로 바꿔 비교합니다.", "min-content/max-content를 DevTools에서 실험합니다.", "overflow-wrap과 white-space를 확인합니다.", "flex/grid item이면 min-inline-size:auto와 0을 비교합니다.", "replaced content의 natural width를 확인합니다."],
          fix: "content 정책에 맞게 overflow-wrap:anywhere 또는 safe break를 적용하고, layout item이 줄어야 한다면 min-inline-size:0을 명시하며 essential content clipping은 피합니다.",
          prevention: "긴 URL·CJK·긴 영문·큰 image·localized text fixture를 component sizing test에 포함합니다.",
        },
      ],
      comparisons: [
        {
          title: "content 기반 폭을 어떤 intrinsic value로 표현할까요?",
          options: [
            { name: "min-content", chooseWhen: "가능한 wrap을 모두 사용한 content 최소 기여를 관찰·제약할 때", avoidWhen: "사람이 읽기 좋은 line length를 자동 보장한다고 기대할 때", tradeoffs: ["content의 hard-to-shrink 부분을 드러냅니다.", "unbreakable token에 의해 여전히 클 수 있습니다.", "일상 component에서 직접 지정하기보다 진단에 유용합니다."] },
            { name: "max-content", chooseWhen: "soft wrap 없이 content 전체가 한 줄에 필요한 크기를 알고 싶을 때", avoidWhen: "narrow viewport에서 overflow를 허용할 수 없을 때", tradeoffs: ["natural unwrapped size를 표현합니다.", "available space를 쉽게 넘습니다.", "menu label·measurement 등에 제한적으로 유용합니다."] },
            { name: "fit-content", chooseWhen: "min/max content 경계 안에서 available space에 맞춰 shrink-to-fit하게 할 때", avoidWhen: "항상 container를 가득 채워야 할 때", tradeoffs: ["content와 가용 공간을 함께 고려합니다.", "정확한 결과는 wrapping·containing block에 의존합니다.", "inline-block auto sizing mental model과 연결됩니다."] },
          ],
        },
      ],
    },
    {
      id: "overflow-clipping-scrolling",
      title: "overflow는 크기 계산을 대신하지 않고 box 밖 content의 clipping·scrolling policy를 정합니다",
      lead: "가로 scrollbar가 보이면 overflow:hidden부터 붙이는 대신 어떤 box가 왜 scrollable overflow area를 만들었는지 먼저 찾습니다.",
      explanations: [
        "overflow의 initial value visible은 special clipping 없이 content를 box 밖에 paint하고 해당 box를 scroll container로 만들지 않습니다. hidden은 padding box 기준으로 clip하고 user scrolling UI를 제공하지 않지만 programmatic scrolling은 허용되는 scroll container입니다. clip은 overflow clip edge에서 자르고 어떤 mechanism의 scrolling도 금지하며 자체로 새 formatting context를 만들지 않습니다.",
        "overflow:auto는 overflow가 있을 때 scroll mechanism을 제공하고 scroll은 overflow가 없어도 scrollbar/panner 공간을 표시할 수 있습니다. classic scrollbar는 clientWidth/clientHeight에서 공간을 차지하고 overlay scrollbar는 그렇지 않을 수 있어 pixel 결과가 platform마다 달라집니다. layout test는 border rect와 overflow boolean, scrollbar-gutter 정책 등 안정적인 계약을 선택합니다.",
        "overflow-x와 overflow-y를 한 값 또는 두 값 shorthand로 지정할 수 있고 visible/clip 조합은 다른 축 값에 따라 computed behavior가 변할 수 있습니다. horizontal·vertical을 독립적으로 생각하되 writing mode에서는 overflow-inline·overflow-block logical axis가 의도를 더 잘 표현할 수 있습니다.",
        "흔한 root cause는 content-box width:100%+padding, 100vw가 vertical scrollbar 폭까지 포함하는 문제, fixed/min-content child, unbreakable token, negative margin, transform, absolute positioned decoration입니다. DevTools에서 가장 오른쪽 border edge와 scrollWidth를 비교하고 temporary outline을 모든 element에 적용해 넘치는 box를 찾습니다.",
        "overflow:hidden/clip은 정보를 삭제할 수 있습니다. keyboard focus target이 clipped region 안에 들어가도 사용자가 보지 못하거나 clip에서는 scrollIntoView가 복구하지 못할 수 있습니다. horizontal scroll region은 keyboard와 touch에서 접근 가능하고 목적을 이해할 수 있어야 하며, focus indicator와 scrollbar를 무조건 숨기지 않습니다.",
        "text-overflow:ellipsis는 overflow alone이 아니라 inline overflow, clipping, wrapping 정책이 함께 맞아야 하고 잘린 text의 full value를 접근 가능한 방식으로 얻을 수 있어야 합니다. title tooltip 하나에 의존하기보다 expand control·detail view·accessible name/description을 task에 맞게 제공합니다.",
      ],
      concepts: [
        { term: "scrollable overflow", definition: "box의 scrollport 밖까지 확장되어 scrolling으로 볼 수 있는 content 영역입니다.", detail: ["scrollWidth/scrollHeight로 흔적을 확인할 수 있습니다.", "visual overflow와 완전히 같은 개념은 아닙니다."] },
        { term: "scroll container", definition: "overflow policy에 따라 scrollport와 scroll offset을 갖는 box입니다.", detail: ["hidden·auto·scroll은 scroll container가 될 수 있습니다.", "clip은 scroll container가 아닙니다.", "root scrolling behavior는 별도 special rule이 있습니다."] },
        { term: "overflow clipping", definition: "정해진 clip edge 밖의 rendering을 보이지 않게 자르는 처리입니다.", detail: ["원래 used size를 줄이지 않습니다.", "essential content와 focus indicator가 잘릴 수 있습니다.", "border-radius와 clip edge interaction이 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "페이지에 원인 모를 horizontal scrollbar가 생겼고 body에 overflow-x:hidden을 주면 겉으로만 사라진다.",
          likelyCause: "descendant의 border/margin/min-content/viewport unit/transform이 viewport보다 넓지만 root에서 symptom만 clip했습니다.",
          checks: ["documentElement.scrollWidth와 clientWidth를 비교합니다.", "모든 candidate의 getBoundingClientRect right/left를 viewport와 비교합니다.", "width:100%+padding과 box-sizing을 확인합니다.", "100vw·negative margin·transform·absolute child를 찾습니다.", "긴 user content와 image natural width를 대입합니다."],
          fix: "넘치는 실제 box의 sizing·wrapping·min-size를 수정하고 의도한 scroll region만 overflow:auto로 제한합니다.",
          prevention: "narrow viewport, zoom 200%, 긴 localized text, large image fixture에서 root horizontal overflow가 없음을 E2E로 단언합니다.",
        },
        {
          symptom: "overflow:clip panel 안의 focusable control로 Tab이 이동하지만 화면에서 control과 focus ring을 볼 수 없고 script scroll도 실패한다.",
          likelyCause: "clip은 scroll container가 아니어서 clipped content로 scroll할 수 없고 essential interactive content를 visual 영역 밖에 두었습니다.",
          checks: ["focus order와 activeElement를 기록합니다.", "overflow computed value를 hidden과 clip에서 비교합니다.", "scrollTop 변경 전후를 봅니다.", "control rect와 clip edge를 비교합니다."],
          fix: "essential content가 layout 안에 들어오도록 size/wrap을 고치거나 user가 탐색 가능한 overflow:auto region을 사용합니다.",
          prevention: "clipping component에 focusable descendant visibility invariant와 keyboard scroll test를 둡니다.",
        },
      ],
      comparisons: [
        {
          title: "넘친 content를 어떻게 처리할까요?",
          options: [
            { name: "visible", chooseWhen: "장식이 box 밖으로 그려져도 content 가독성과 overlap이 안전할 때", avoidWhen: "neighbor를 덮거나 root scrollbar를 만드는 essential content일 때", tradeoffs: ["content를 숨기지 않습니다.", "box가 scroll container가 아닙니다.", "overlap과 visual overflow를 관리해야 합니다."] },
            { name: "auto", chooseWhen: "제한된 panel에서 content가 클 때 사용자에게 scroll 접근을 제공할 때", avoidWhen: "page 안 nested scrolling이 UX를 해치는 작은 text 영역일 때", tradeoffs: ["필요할 때만 scroll UI가 나타납니다.", "scrollbar와 focus/keyboard를 test해야 합니다.", "platform별 scrollbar geometry가 다를 수 있습니다."] },
            { name: "hidden", chooseWhen: "clip하면서 script/focus navigation에 따른 programmatic scroll 가능성이 필요할 때", avoidWhen: "사용자가 직접 넘친 content를 봐야 하는데 별도 control이 없을 때", tradeoffs: ["user scroll UI는 숨깁니다.", "scroll container이며 programmatic scroll은 가능합니다.", "BFC 생성 등 side effect가 있습니다."] },
            { name: "clip", chooseWhen: "장식을 엄격히 자르고 어떤 scrolling도 원하지 않을 때", avoidWhen: "focusable·essential content가 clip edge 밖에 갈 수 있을 때", tradeoffs: ["scroll container를 만들지 않습니다.", "programmatic scrolling도 금지합니다.", "필요하면 flow-root를 별도로 결합합니다."] },
          ],
        },
      ],
    },
    {
      id: "geometry-api-devtools-diagnostics",
      title: "getComputedStyle·getClientRects·getBoundingClientRect·client/scroll size는 서로 다른 질문에 답합니다",
      lead: "한 API 숫자를 '요소의 크기'라고 부르지 말고 어느 box edge·fragment·좌표계·transform을 측정했는지 기록합니다.",
      explanations: [
        "getComputedStyle은 cascade와 value processing을 거친 resolved style을 확인하는 출발점입니다. display, boxSizing, min/max, padding, used border width, overflow를 읽어 어떤 rule이 geometry를 만들었는지 설명합니다. 그러나 style 문자열 하나가 모든 layout constraint와 transform 후 rectangle을 보여 주지는 않습니다.",
        "getClientRects는 associated box의 각 fragment border area를 DOMRect 목록으로 반환합니다. multi-line inline은 여러 rect, display:none/contents처럼 associated box가 없는 element는 empty list가 됩니다. getBoundingClientRect는 non-empty fragment를 모두 포함하는 smallest bounding rectangle이므로 line 사이 빈 영역까지 포함할 수 있고 실제 painted shape와 같지 않을 수 있습니다.",
        "DOMRect width/height는 padding과 border를 포함한 transformed border-area geometry이고 margin은 제외합니다. x/y/top/left는 viewport coordinate라 page scroll에 따라 바뀌며 document coordinate가 필요하면 scroll offset을 고려합니다. transform:scale()은 layout used width를 바꾸지 않지만 returned visual rectangle에는 transform이 반영될 수 있습니다.",
        "clientWidth/clientHeight는 일반적으로 padding box의 내부 viewport와 scrollbar 영향을 보여 주고, scrollWidth/scrollHeight는 scrollable content extent를 진단합니다. offsetWidth는 integer border-box 계열 측정이지만 table·scrollbar·rounding 규칙이 있고 DOMRect는 fractional double을 제공합니다. API마다 rounding과 included edge가 달라 equality test를 무턱대고 하지 않습니다.",
        "DevTools Box Model pane에서 content/padding/border/margin을 먼저 확인하고 Layout/Computed panel에서 containing block·formatting context·overflow를 추적합니다. temporary `outline:1px solid`은 layout size를 바꾸지 않아 범인 box 확인에 유리하지만 pseudo-element·transform·shadow·visual overflow는 별도 layer에서 봅니다.",
        "진단 순서는 selector match와 cascade, computed display/position, containing block과 available size, box-sizing과 padding/border, min/max/intrinsic contribution, overflow/scroll, transform과 paint, geometry API 순서가 효율적입니다. 앞 단계가 틀리면 뒤에서 숫자를 보정하는 JavaScript는 resize·font load·localization마다 다시 깨집니다.",
      ],
      concepts: [
        { term: "getClientRects", definition: "element associated box의 각 box fragment border area를 content order의 DOMRect 목록으로 반환하는 API입니다.", detail: ["multi-line inline 진단에 유용합니다.", "associated box가 없으면 empty list입니다.", "returned rect는 live object가 아닙니다."] },
        { term: "getBoundingClientRect", definition: "getClientRects의 non-empty rectangle을 모두 포함하는 가장 작은 viewport-relative bounding DOMRect를 반환합니다.", detail: ["border area와 transform을 반영합니다.", "margin은 포함하지 않습니다.", "fragment 사이 빈 공간을 포함할 수 있습니다."] },
        { term: "scrollWidth/clientWidth", definition: "scrollable content extent와 element 내부 client viewport를 비교해 overflow 존재를 추적하는 CSSOM View 지표입니다.", detail: ["scrollbar 형태에 따라 client size가 달라질 수 있습니다.", "rect width와 같은 edge를 뜻하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "getBoundingClientRect().width가 CSS width와 다르거나 scroll할 때 left/top 값이 계속 바뀐다.",
          likelyCause: "CSS width의 sizing edge, padding/border, box-sizing, transform, viewport-relative coordinate를 구분하지 않았습니다.",
          checks: ["computed boxSizing·width·padding·border를 기록합니다.", "transform matrix를 제거해 비교합니다.", "margin이 rect에 없음을 확인합니다.", "scrollX/scrollY와 viewport 좌표를 구분합니다.", "getClientRects로 multiple fragment인지 봅니다."],
          fix: "필요한 edge와 coordinate system에 맞는 API·계산을 사용하고 transform 전 layout size와 transform 후 visual rect를 분리합니다.",
          prevention: "geometry helper 이름에 borderBox/viewport/document를 포함하고 fractional tolerance와 writing mode fixture를 test합니다.",
        },
        {
          symptom: "resize event마다 수백 element의 rect를 읽고 style을 쓰자 scrolling이 끊기고 layout 시간이 급증한다.",
          likelyCause: "DOM write와 layout-dependent read를 교차해 style invalidation 후 synchronous layout을 반복했습니다.",
          checks: ["Performance panel에서 Layout/Recalculate Style을 봅니다.", "loop 안 getBoundingClientRect·offsetWidth와 style write 순서를 확인합니다.", "ResizeObserver로 대체 가능한지 봅니다."],
          fix: "모든 geometry read를 batch한 뒤 write를 별도 phase/requestAnimationFrame에 수행하고 observer callback에서 불필요한 재측정을 줄입니다.",
          prevention: "layout measurement utility를 중앙화하고 performance budget·large list benchmark·observer loop error test를 둡니다.",
        },
      ],
      expertNotes: ["ResizeObserver는 content-box와 border-box 변화를 비동기적으로 관찰할 수 있지만 callback에서 다시 size를 바꾸면 resize loop가 생길 수 있습니다. state threshold와 idempotent update를 설계합니다.", "서버 rendering 환경에는 layout engine이 없어 getBoundingClientRect가 없거나 test DOM library가 0을 반환할 수 있습니다. geometry-dependent behavior는 browser E2E로 검증하고 SSR path에서는 safe fallback을 둡니다."],
    },
    {
      id: "production-box-policy-testing",
      title: "production layout은 border-box reset 하나가 아니라 sizing·overflow·visibility·accessibility 계약으로 관리합니다",
      lead: "box model 공식은 출발점이고, 실제 component는 font load·localization·zoom·image failure·browser scrollbar·focus state에서 같은 계약을 지켜야 합니다.",
      explanations: [
        "global border-box policy는 responsive width 계산을 단순화하지만 component의 intrinsic size, margin, min/max, replaced content, overflow를 없애지 않습니다. reset 적용 범위와 third-party widget boundary를 정하고 pseudo-element까지 포함합니다. legacy page 일부만 content-box를 기대한다면 migration layer와 visual regression 없이 전역 한 줄을 바꾸지 않습니다.",
        "component sizing contract에는 preferred/min/max inline size, padding/border token, content wrapping, image ratio, overflow policy, hidden state, focus behavior를 적습니다. 'width 320px'만 전달하면 localization과 200% zoom에서 content가 넘칠 때 누가 책임지는지 알 수 없습니다. fixed height는 text 잘림 위험이 크므로 min-block-size와 content-driven growth를 우선 검토합니다.",
        "layout test는 exact pixel이 필요한 invariant와 content-dependent range를 구분합니다. box-sizing proof처럼 fixed empty box는 exact DOMRect를 단언할 수 있지만 text intrinsic size는 platform font rasterization에 따라 달라 boolean/range와 semantic outcome으로 test합니다. scrollbar thickness도 environment-dependent이므로 scrollWidth>clientWidth 같은 invariant가 더 안정적입니다.",
        "accessibility test에서는 display:none/visibility:hidden control이 focus order와 accessibility tree에서 빠지는지, opacity transition 중 invisible focus trap이 없는지, display:contents가 semantic role을 잃지 않는지 확인합니다. zoom 200~400%, high contrast, reduced motion, keyboard, screen reader browser 조합을 risk에 맞게 포함합니다.",
        "performance test에서는 layout shift와 forced layout을 봅니다. image natural size load로 box가 뒤늦게 커지지 않도록 dimensions/aspect-ratio를 예약하고, font swap 뒤 text reflow를 허용할 공간을 설계합니다. 숨김 state 전환이 large subtree의 style/layout을 반복시키는지 DevTools performance trace로 측정합니다.",
        "운영 telemetry는 viewport width별 horizontal overflow, clipped focus, cumulative layout shift, broken image size를 개인 data 없이 집계할 수 있습니다. 하지만 JavaScript로 모든 element rect를 계속 수집하면 performance와 privacy 비용이 커지므로 대표 sentinel과 error boundary를 선택하고 local reproduction fixture로 연결합니다.",
      ],
      concepts: [
        { term: "sizing contract", definition: "component가 허용하는 preferred/min/max size, box edge, wrapping, overflow, replaced content behavior를 명시한 규칙입니다.", detail: ["CSS declaration 목록보다 user-visible outcome을 포함합니다.", "responsive·localization·zoom fixture로 검증합니다."] },
        { term: "layout invariant", definition: "환경이 달라도 반드시 유지되어야 하는 관계나 조건입니다.", detail: ["예: root horizontal overflow 없음", "예: focus target이 clip되지 않음", "text pixel width처럼 환경 의존 값과 구분합니다."] },
        { term: "layout shift", definition: "사용자 입력 없이 visible element의 위치·크기가 frame 사이 예상치 못하게 바뀌는 현상입니다.", detail: ["image natural dimension과 font swap이 원인이 될 수 있습니다.", "space reservation과 stable hidden state가 완화합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "전역 border-box를 적용했는데도 작은 화면에서 card가 넘치고 image load 후 page가 크게 밀린다.",
          likelyCause: "unbreakable min-content, fixed min-width, margin, natural image dimensions 미예약 등 box-sizing 밖의 constraint가 남았습니다.",
          checks: ["가장 넓은 descendant rect와 scrollWidth를 찾습니다.", "min/max/white-space/overflow-wrap을 확인합니다.", "img natural/declared width-height와 aspect-ratio를 봅니다.", "font/image load 전후 Layout Shift record를 비교합니다."],
          fix: "content wrap·min-inline-size·responsive image limit·aspect ratio reservation을 component contract에 추가합니다.",
          prevention: "narrow/zoom/localized/slow-image fixture와 CLS·root overflow regression을 CI에 둡니다.",
        },
      ],
      comparisons: [
        {
          title: "크기 회귀를 어떤 assertion으로 검증할까요?",
          options: [
            { name: "exact DOMRect", chooseWhen: "font/content와 무관한 fixed box model 공식처럼 CSS pixel이 계약 자체일 때", avoidWhen: "text·scrollbar·subpixel·platform font에 의존할 때", tradeoffs: ["산술 오류를 명확히 잡습니다.", "환경 차이에 flaky할 수 있습니다.", "zoom/transform 조건을 고정해야 합니다."] },
            { name: "관계·boolean invariant", chooseWhen: "overflow 없음, child가 container 안, focus visible처럼 outcome이 중요할 때", avoidWhen: "1px border token 누락처럼 exact design 값이 중요할 때", tradeoffs: ["환경 변화에 견고합니다.", "원인 숫자를 별도 diagnostic으로 남겨야 합니다.", "접근성·responsive outcome에 적합합니다."] },
            { name: "visual regression", chooseWhen: "border style·spacing rhythm·복합 component paint를 전체적으로 비교할 때", avoidWhen: "semantic tree·keyboard·scrollability까지 자동으로 보장한다고 기대할 때", tradeoffs: ["unexpected paint 변화를 넓게 잡습니다.", "baseline 관리와 rendering noise가 있습니다.", "DOM/accessibility assertion을 함께 사용해야 합니다."] },
          ],
        },
      ],
      expertNotes: ["CSS contain/content-visibility는 rendering work를 줄이는 별도 성능 도구이며 display:none과 같은 accessibility·find-in-page behavior라고 가정하면 안 됩니다. 적용 전에 skipped subtree의 intrinsic placeholder와 interaction을 검증합니다.", "container query는 component available size에 반응하지만 query container의 own sizing과 style containment가 새 constraint를 만듭니다. 이 세션의 box edge·intrinsic size mental model이 선행됩니다."],
    },
  ],
  lab: {
    title: "box laboratory: 원본 세 page를 측정 가능한 responsive component로 통합",
    scenario: "block·inline·inline-block sample, content-box/border-box card, 여섯 border style, hidden state, 긴 content와 image를 한 lab page에 만들고 hand calculation·DevTools·DOM API 결과를 일치시킵니다.",
    setup: [
      "UTF-8 HTML 한 파일과 현대 browser, DevTools Elements·Computed·Layout·Accessibility·Performance panel을 준비합니다.",
      "원본의 display·box-sizing·border 값은 먼저 별도 표에 그대로 옮기고 수정 전 expected border box를 손으로 계산합니다.",
      "network 없이 재현할 작은 data SVG와 짧은 text·긴 URL·다국어 fixture를 준비합니다.",
      "실제 개인정보·token이 든 URL이나 private repository link는 사용하지 않습니다.",
    ],
    steps: [
      "DOM tree와 예상 box tree를 그려 각 element가 principal/additional/zero box 중 무엇을 만드는지 표시합니다.",
      "같은 span을 inline, block flow, inline flow-root로 바꾸고 computed display·getClientRects 수·100×40 적용 여부를 표로 기록합니다.",
      "display:none, contents, visibility:hidden, opacity:0 panel을 만들고 layout 공간·child rect·pointer·Tab·accessibility tree 결과 matrix를 작성합니다.",
      "width 200, height 100, padding 20, border 10인 content-box와 border-box의 content/padding/border/margin 크기를 손으로 계산합니다.",
      "getComputedStyle과 getBoundingClientRect로 계산을 검산하고 margin이 DOMRect에 포함되지 않음을 증명합니다.",
      "solid·dotted·dashed·side-specific color·border shorthand를 적용하고 border-style:none에서 used width가 사라지는 실험을 합니다.",
      "max-width가 preferred width를 제한하는 box와 2:1 natural image를 추가해 auto height·max-inline-size behavior를 확인합니다.",
      "120×40 scrollport 안에 240×80 child를 두고 visible·hidden·clip·auto·scroll의 user/programmatic scrolling과 focus visibility를 비교합니다.",
      "320px viewport, 200% zoom, 긴 URL, 한국어·영어 긴 text, image slow/failure state에서 root horizontal overflow와 layout shift를 검사합니다.",
      "Performance panel에서 geometry read/write loop를 일부러 만들어 forced layout을 확인한 뒤 reads와 writes를 batch합니다.",
      "HTML/CSS validation, 전체 detailed-session validator, accessibility keyboard test와 exact output snapshot을 통과시킵니다.",
    ],
    expectedResult: [
      "DOM element 수와 box/fragment 수가 다를 수 있는 이유를 각 fixture로 설명합니다.",
      "block·inline·inline-block의 outer/inner role과 width/height 적용 결과가 hand prediction과 일치합니다.",
      "none·contents·visibility·opacity의 layout/interaction/accessibility matrix가 실제 browser 결과와 일치합니다.",
      "content-box는 border rect 260×160, border-box는 200×100이며 content 140×40으로 측정됩니다.",
      "border style이 없을 때 visible/used border가 사라지고 shorthand 적용 뒤 geometry가 예상대로 바뀝니다.",
      "max constraint·overflow boolean·image natural/rendered ratio exact output이 모두 일치합니다.",
      "narrow viewport와 zoom에서 essential content·focus가 clip되지 않고 root horizontal overflow가 없습니다.",
      "geometry measurement가 어떤 edge·coordinate·fragment를 반환하는지 test 이름과 기록에 드러납니다.",
    ],
    cleanup: [
      "의도적으로 만든 invisible focus trap, duplicate hidden state, oversized overflow fixture는 lab 전용 section에만 남기고 production component에서는 제거합니다.",
      "정상 border-box reset·measurement helper·long-content fixture는 후속 margin/flex/grid session에서 재사용합니다.",
      "Performance recording과 screenshot에 local path·private URL·개인 data가 없는지 확인합니다.",
    ],
    extensions: [
      "writing-mode:vertical-rl에서 inline-size/block-size와 logical padding/border를 다시 계산합니다.",
      "ResizeObserver contentBoxSize·borderBoxSize와 getBoundingClientRect 결과를 비교합니다.",
      "display:contents를 list/nav/table wrapper에 적용한 전후 accessibility tree를 browser/AT matrix로 기록합니다.",
      "HTML width/height가 있는 image와 없는 image를 slow loading해 layout shift를 비교합니다.",
      "SSR 환경의 geometry fallback과 browser hydration 뒤 measurement timing을 설계합니다.",
    ],
  },
  exercises: [
    {
      difficulty: "따라하기",
      prompt: "원본 ex07_display와 ex08_box를 한 page로 옮겨 block·inline·inline-block과 두 box-sizing 결과를 예측하고 측정하세요.",
      requirements: [
        "display value마다 outer/inner type을 표로 씁니다.",
        "non-replaced inline의 width/height가 적용되지 않는 결과를 exact boolean으로 출력합니다.",
        "200×100, padding 20, border 10의 content/padding/border size를 가로·세로 모두 손계산합니다.",
        "getBoundingClientRect로 border box를 검산하고 margin은 별도 계산합니다.",
        "코드 각 핵심 줄의 역할과 값을 바꾼 실험 결과를 기록합니다.",
      ],
      hints: ["inline-block은 modern full form으로 inline flow-root입니다.", "DOMRect는 margin을 포함하지 않습니다.", "border-style:none이면 border-width 선언만으로 visible border가 생기지 않습니다."],
      expectedOutcome: "원본 화면을 재현할 뿐 아니라 선언→computed/used value→DOMRect 숫자를 설명합니다.",
      solutionOutline: ["expected table을 먼저 작성합니다.", "fixture의 font·body margin·text content를 고정합니다.", "box edge별 공식을 적용합니다.", "DevTools와 script 결과를 hand calculation과 비교합니다."],
    },
    {
      difficulty: "응용",
      prompt: "작은 화면에서 넘치고 숨김 transition 중 보이지 않는 button이 focus되는 card를 진단해 수정하세요.",
      requirements: [
        "content-box width:100%+padding, 긴 URL min-content, 큰 image 세 overflow 원인을 각각 재현합니다.",
        "display:none·visibility:hidden·opacity:0의 layout·pointer·Tab·accessibility 차이를 matrix로 기록합니다.",
        "root overflow-x:hidden으로 symptom만 가리지 않고 실제 offending box를 찾습니다.",
        "border-box·wrapping·min-inline-size·image aspect ratio reservation을 적절히 적용합니다.",
        "320px·200% zoom·keyboard·slow image load regression을 통과합니다.",
      ],
      hints: ["scrollWidth>clientWidth와 descendant rect right를 함께 봅니다.", "opacity는 hit testing을 바꾸지 않습니다.", "font/image load 전후 크기 변화도 확인합니다."],
      expectedOutcome: "box model·intrinsic sizing·visibility state가 겹친 production bug를 tree/edge별 원인으로 분리해 해결합니다.",
      solutionOutline: ["visible symptom보다 sizing 계산부터 재현합니다.", "offending border edge와 min-content를 찾습니다.", "hide state별 focus policy를 정의합니다.", "responsive/accessibility/performance fixture를 회귀 test로 남깁니다."],
    },
    {
      difficulty: "설계",
      prompt: "공개 학습자료 site의 component box policy와 geometry observability 규약을 설계하세요.",
      requirements: [
        "global box-sizing 적용 범위와 third-party/legacy escape hatch를 정의합니다.",
        "component별 preferred/min/max size, logical padding/border, overflow, replaced content ratio 계약을 정의합니다.",
        "hidden/fading/inert state의 DOM·box·paint·pointer·focus·AT acceptance table을 만듭니다.",
        "display:contents 허용/금지 기준과 browser/AT verification matrix를 포함합니다.",
        "exact DOMRect·boolean invariant·visual regression 각각의 사용 기준을 정의합니다.",
        "ResizeObserver와 getBoundingClientRect read batching, CLS·root overflow monitoring의 performance/privacy 경계를 포함합니다.",
      ],
      hints: ["box-sizing은 margin·min-content·transform을 해결하지 않습니다.", "DOM tree와 box/accessibility tree는 같은 구조가 아닙니다.", "text pixel width와 scrollbar thickness는 platform-dependent입니다."],
      expectedOutcome: "단일 CSS reset을 넘어 responsive·accessibility·performance·test가 공유하는 production box governance 문서를 만듭니다.",
      solutionOutline: ["edge·axis·tree 용어를 먼저 표준화합니다.", "sizing과 hidden state contract를 component API로 만듭니다.", "환경별 invariant와 measurement API를 연결합니다.", "CI와 운영 telemetry owner·budget을 정합니다."],
    },
  ],
  reviewQuestions: [
    { question: "DOM element 하나는 항상 CSS box 하나를 만드나요?", answer: "아닙니다. display:none/contents는 zero box, list/table은 multiple box, inline은 여러 fragment를 만들 수 있고 anonymous box도 생깁니다." },
    { question: "normal flow는 display의 한 value인가요?", answer: "아닙니다. in-flow box가 block/inline 등 기본 formatting 규칙에 따라 배치되는 상태와 과정입니다." },
    { question: "display:inline-block의 outer/inner type은 무엇인가요?", answer: "legacy inline-block은 modern model에서 outer inline, inner flow-root인 atomic inline-level block container입니다." },
    { question: "block element의 width:auto와 width:100%는 항상 같은가요?", answer: "아닙니다. auto는 margin·border·padding을 포함한 constraint로 available size를 채우지만 content-box 100%는 content만 100%여서 padding·border만큼 넘칠 수 있습니다." },
    { question: "display:contents는 element를 DOM과 event path에서도 제거하나요?", answer: "아닙니다. 자신의 box를 제거하지만 DOM selector·event·inheritance 관계는 남습니다. 다만 unusual element와 browser accessibility 구현을 검증해야 합니다." },
    { question: "visibility:hidden과 opacity:0은 interaction에서 같은가요?", answer: "아닙니다. visibility hidden box는 layout에 남지만 render·interaction·navigation에서 제외됩니다. opacity 0은 hit testing과 focus/accessibility가 기본적으로 남습니다." },
    { question: "content-box width 200, 좌우 padding 20, 좌우 border 10의 border box 폭은 얼마인가요?", answer: "200 + 20 + 20 + 10 + 10 = 260px입니다. margin은 여기에 별도로 더합니다." },
    { question: "같은 값의 border-box에서 content width는 얼마인가요?", answer: "width 200이 border box이고 padding 40·border 20을 빼므로 content width는 140px입니다." },
    { question: "border-box이면 content가 항상 선언 width 안에 완전히 들어가나요?", answer: "아닙니다. padding+border가 선언 width보다 크면 content는 0에서 floor되고 실제 border box가 선언보다 커질 수 있으며 min-content·margin·overflow 원인도 남습니다." },
    { question: "min-content와 max-content의 직관적 차이는 무엇인가요?", answer: "min-content는 가능한 soft wrap을 사용한 nominal minimum, max-content는 soft wrap 없이 content가 원하는 nominal maximum입니다." },
    { question: "overflow:hidden과 clip의 핵심 차이는 무엇인가요?", answer: "hidden은 user scroll UI 없이 clip하지만 programmatic scrolling 가능한 scroll container이고, clip은 scrolling 자체를 금지하며 scroll container가 아닙니다." },
    { question: "getBoundingClientRect에 margin이 포함되나요?", answer: "아닙니다. box fragment border area의 bounding rectangle이며 margin은 제외되고 transform과 viewport-relative coordinate를 고려해야 합니다." },
  ],
  completionChecklist: [
    "DOM tree·box tree·accessibility tree를 같은 것으로 취급하지 않는다.",
    "normal flow와 block/inline formatting context를 axis와 source order로 설명할 수 있다.",
    "outer/inner display type으로 block·inline·inline-block·flow-root·flex/grid shorthand를 해석할 수 있다.",
    "display:none·contents·visibility:hidden·opacity:0의 layout·interaction·accessibility 차이를 선택할 수 있다.",
    "content·padding·border·margin box와 edge를 그림 없이 정확히 설명할 수 있다.",
    "content-box와 border-box의 가로·세로·margin 크기를 손으로 계산하고 DOMRect로 검산할 수 있다.",
    "auto·min/max·intrinsic size·replaced element ratio가 used size를 정하는 과정을 설명할 수 있다.",
    "overflow visible·hidden·clip·auto·scroll의 scroll container 차이를 설명하고 essential content clipping을 피한다.",
    "getComputedStyle·getClientRects·getBoundingClientRect·client/scroll size의 포함 edge와 좌표 차이를 구분한다.",
    "narrow viewport·zoom·긴 text·image load·keyboard·AT·performance를 포함한 layout 회귀 test를 설계할 수 있다.",
    "원본 source path는 local relative provenance로만 기록하고 public source는 공식 W3C HTTPS URL만 사용한다.",
  ],
  nextSessions: ["css-06-borders-shadows-margin-collapse"],
  sources: [
    {
      id: "web-display-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day04/ex07_display.html",
      usedFor: ["display none", "visibility hidden 주석", "block·inline·inline-block", "width·height 적용", "flex·grid·table 소개"],
      evidence: "문서 전체의 주석과 div 세 fixture를 감사했습니다. 'block=부모 100%'와 'inline=크기 조정 불가능'을 outer/inner type, auto constraint, non-replaced inline used size로 정밀화하고 none/contents/visibility/opacity 경계를 확장했습니다.",
    },
    {
      id: "web-box-sizing-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day04/ex08_box.html",
      usedFor: ["content-box", "border-box", "width 200·height 100", "padding 20", "border 10", "margin-bottom 20", "총크기 주석"],
      evidence: "두 box의 모든 declaration과 200+20+20+10+10 주석을 감사했습니다. 가로·세로 content/padding/border/margin box와 DOMRect exact output, border-box content 140×40, content floor 경계까지 확장했습니다.",
    },
    {
      id: "web-border-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day04/ex10_border.html",
      usedFor: ["border-width", "solid·dotted·dashed", "border-color와 side color", "border shorthand", "width·height·margin geometry"],
      evidence: "여섯 class와 base div declaration을 모두 감사했습니다. style none의 used border, shorthand reset, border box geometry, outline과 focus layout 차이로 연결했습니다.",
    },
    {
      id: "css-display-3",
      repository: "W3C CSS Working Group",
      path: "TR/css-display-3/",
      publicUrl: "https://www.w3.org/TR/css-display-3/",
      usedFor: ["box tree generation", "outer/inner display type", "block·inline·inline-block·flow-root", "none·contents", "visibility", "accessibility implications"],
      evidence: "2026-07-12에 2026-06-05 Candidate Recommendation Draft를 확인해 box tree, display pair, legacy mapping, none/contents box generation, visibility interaction/navigation, display:contents AT 구현 경고를 기준으로 삼았습니다.",
    },
    {
      id: "css-box-4",
      repository: "W3C CSS Working Group",
      path: "TR/css-box-4/",
      publicUrl: "https://www.w3.org/TR/css-box-4/",
      usedFor: ["content·padding·border·margin area", "네 edge와 box", "physical/logical margin·padding", "margin collapse 범위"],
      evidence: "2026-07-12에 CSS Box Model Level 4의 네 area/edge 정의와 margin·padding property 범위를 확인했습니다.",
    },
    {
      id: "css-sizing-3",
      repository: "W3C CSS Working Group",
      path: "TR/css-sizing-3/",
      publicUrl: "https://www.w3.org/TR/css-sizing-3/",
      usedFor: ["auto·preferred/min/max size", "min-content·max-content·fit-content", "box-sizing", "content floor", "intrinsic/replaced sizing"],
      evidence: "2026-07-12에 box-sizing length가 content/border edge에 적용되는 규칙, border-box content floor, fit-content clamp, intrinsic size와 replaced natural dimension 정의를 확인했습니다.",
    },
    {
      id: "css-sizing-4",
      repository: "W3C CSS Working Group",
      path: "TR/css-sizing-4/",
      publicUrl: "https://www.w3.org/TR/css-sizing-4/",
      usedFor: ["최신 sizing vocabulary", "aspect ratio와 intrinsic sizing 확장", "stretch/contain 계열 후속 범위"],
      evidence: "2026-07-12에 Level 4가 Level 3 sizing model을 확장하는 범위를 확인하고 안정적인 Level 3 규칙과 실험적 확장을 구분했습니다.",
    },
    {
      id: "css-overflow-3",
      repository: "W3C CSS Working Group",
      path: "TR/css-overflow-3/",
      publicUrl: "https://www.w3.org/TR/css-overflow-3/",
      usedFor: ["overflow axes", "visible·hidden·clip·auto·scroll", "scroll container", "clipping", "programmatic scroll boundary"],
      evidence: "2026-07-12에 overflow-x/y와 shorthand, hidden이 programmatic scroll 가능한 scroll container인 점과 clip이 scrolling을 금지하는 차이를 확인했습니다.",
    },
    {
      id: "cssom-view-1",
      repository: "W3C CSS Working Group",
      path: "TR/cssom-view-1/",
      publicUrl: "https://www.w3.org/TR/cssom-view-1/",
      usedFor: ["getClientRects", "getBoundingClientRect", "empty associated box", "border area fragments", "client/scroll dimensions"],
      evidence: "2026-07-12에 associated box가 없을 때 empty rect list, fragment border area 목록, bounding union과 zero rectangle, scroll/client geometry API를 확인했습니다.",
    },
    {
      id: "css-color-4",
      repository: "W3C CSS Working Group",
      path: "TR/css-color-4/#transparency",
      publicUrl: "https://www.w3.org/TR/css-color-4/#transparency",
      usedFor: ["opacity postprocessing", "descendant 전체 합성", "stacking context", "hit testing 유지"],
      evidence: "2026-07-12에 opacity가 element 전체 offscreen rendering에 적용되고 1 미만에서 stacking context를 만들며 hit testing에는 영향을 주지 않는 규칙을 확인했습니다.",
    },
    {
      id: "css22-visual-sizing",
      repository: "W3C CSS 2.2",
      path: "TR/CSS22/visudet.html",
      publicUrl: "https://www.w3.org/TR/CSS22/visudet.html",
      usedFor: ["normal-flow block constraint", "non-replaced inline width", "inline-block shrink-to-fit", "replaced intrinsic width", "containing block"],
      evidence: "2026-07-12에 legacy block/inline formatting의 used width equation, inline non-replaced width 비적용, inline-block auto shrink-to-fit, replaced natural dimension 계산을 확인했습니다.",
    },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "세 원본의 display 주석과 세 visible fixture, content-box/border-box 전체 declaration과 산식, 여섯 border variant를 모두 사용했습니다.",
      "원본의 block=100%, inline width/height 불가, display none/visibility 설명은 current W3C outer/inner display, used size, box generation·interaction·accessibility vocabulary로 정밀화했습니다.",
      "display:contents, opacity hit testing, intrinsic/min/max/replaced sizing, overflow hidden/clip, CSSOM geometry, performance와 production test는 원본에 없어 W3C primary public specifications로 보강했습니다.",
      "margin collapsing·border radius/shadow는 css-06, position/containing block·stacking은 css-07, responsive/flex/grid는 후속 session에서 이 box mental model 위에 확장합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
