import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["css-02-basic-selectors-specificity"],
  slug: "css-02-basic-selectors-specificity",
  courseId: "web",
  moduleId: "02-css-cascade-layout-responsive",
  order: 2,
  title: "전체·타입·class·id 선택자와 명시도",
  subtitle: "selector가 어떤 DOM element를 match하는지와 specificity A-B-C가 어떻게 계산되는지 분리하고, :where()·:is()·:not()·nesting까지 override 가능한 component 규칙으로 설계합니다.",
  level: "기초",
  estimatedMinutes: 180,
  coreQuestion: "같은 element를 여러 selector가 선택할 때 match 여부와 specificity tuple을 어떻게 정확히 계산하고, id·!important를 늘리지 않고도 재사용 가능한 CSS API를 만들 수 있을까요?",
  summary: "원본의 * reset, p type, .fc/.a class, #bc/#container/#fc id와 selector grouping을 DOM matching·cascade와 연결합니다. universal/type/class/id의 의도와 specificity를 A-B-C tuple로 계산하고, inline/importance/layer는 specificity 밖의 앞 단계임을 명확히 합니다. selector list의 invalidation, multiple class composition, unique id contract, source-order tie, :where() zero specificity, :is()/:not()/:has() 최대 argument, CSS nesting parent-list specificity를 actual computed output으로 증명합니다. 전역 reset·ID styling·과도한 descendant chain·동적 selector injection을 진단하고 낮고 예측 가능한 component selector 전략을 설계합니다.",
  objectives: [
    "universal·type·class·ID selector의 matching 대상과 사용 의도를 DOM tree에서 설명할 수 있다.",
    "selector list와 compound/complex selector를 구분하고 invalid selector가 rule에 미치는 영향을 예측할 수 있다.",
    "specificity를 ID-class/attribute/pseudo-class-type/pseudo-element의 A-B-C tuple로 계산·비교할 수 있다.",
    "inline style·!important·layer가 specificity 점수 자체가 아니라 cascade의 다른 단계임을 설명할 수 있다.",
    ":where()의 zero specificity와 :is()·:not()·:has()·nesting의 최대 argument specificity를 실제 결과로 검증할 수 있다.",
    "class 기반 component와 낮은 specificity boundary를 설계하고 DevTools·matches/querySelector로 selector 회귀를 진단할 수 있다.",
  ],
  prerequisites: [
    { title: "인라인·내부·외부 CSS와 캐스케이드의 판단 순서", reason: "origin·importance·layer·style attribute 뒤 specificity가 비교된다는 전체 cascade 위치를 알고 selector 계산을 시작합니다.", sessionSlug: "css-01-apply-cascade" },
  ],
  keywords: ["universal selector", "type selector", "class selector", "ID selector", "selector list", "compound selector", "specificity", ":where", ":is", ":not", ":has", "CSS nesting", "source order"],
  chapters: [
    {
      id: "selector-matching-first",
      title: "selector의 첫 질문은 얼마나 강한지가 아니라 현재 DOM element와 match하는지입니다",
      lead: "match하지 않는 selector는 specificity가 아무리 높아도 해당 element의 declaration 후보가 되지 않습니다.",
      explanations: [
        "원본 ex13에서 p는 모든 p element, .fc는 class token fc를 가진 element, #bc는 id 값이 bc인 element를 선택합니다. class='fc featured'처럼 class attribute에 여러 whitespace-separated token이 있어도 .fc가 match합니다. class attribute 전체 문자열이 정확히 fc여야 하는 것은 아닙니다.",
        "selector는 DOM tree와 element state에 평가됩니다. source에 class가 있어도 JavaScript가 제거했거나 Shadow DOM boundary 밖이면 match 결과가 달라질 수 있습니다. DevTools Elements의 실제 DOM과 Element.matches('.fc')를 확인합니다.",
        "specificity는 동일 cascade 단계에서 여러 matching declaration의 우선순위를 비교하는 값입니다. #missing이 (1,0,0)으로 강해도 element id가 missing이 아니면 후보가 아니므로 .fc rule을 이길 수 없습니다.",
        "querySelector는 document에서 첫 matching element, querySelectorAll은 static NodeList, matches는 특정 element가 selector를 만족하는지 반환합니다. CSS selector와 DOM query selector는 많은 grammar를 공유하지만 pseudo-element처럼 DOM element를 직접 반환하지 않는 selector와 dynamic pseudo-state를 구분합니다.",
      ],
      concepts: [
        { term: "selector", definition: "DOM의 element를 pattern과 관계·상태로 식별해 style rule의 대상 후보를 만드는 표현식입니다.", detail: ["match 결과는 boolean/element set입니다.", "specificity 계산과 별도 단계입니다."] },
        { term: "matching", definition: "특정 element가 selector가 요구하는 type·id·class·attribute·state·관계를 모두 만족하는지 평가하는 과정입니다.", detail: ["match하지 않으면 declaration 후보가 아닙니다.", "현재 DOM/state를 기준으로 합니다."] },
        { term: "class token", definition: "class attribute의 공백으로 구분된 개별 이름이며 .name selector가 하나의 token을 match합니다.", detail: ["한 element가 여러 class를 가질 수 있습니다.", "순서는 보통 .class matching에 영향이 없습니다."] },
      ],
      codeExamples: [
        {
          id: "selector-match-matrix",
          title: "universal·type·class·ID가 한 element에 match하는지 출력하기",
          language: "html",
          filename: "selector-matches.html",
          purpose: "specificity를 비교하기 전에 실제 DOM의 match set을 Element.matches와 querySelectorAll로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>선택자 매칭</title></head>\n<body>\n  <main id=\"content\" class=\"page theme-light\">\n    <h1 class=\"title accent\">선택자 실험</h1>\n    <p id=\"lead\" class=\"copy accent\">첫 문단</p>\n    <p class=\"copy\">둘째 문단</p>\n  </main>\n  <pre id=\"result\"></pre>\n  <script>\n    const lead = document.querySelector('#lead');\n    const selectors = ['*', 'p', '.accent', '.copy.accent', '#lead', '#missing'];\n    const matches = selectors.map((selector) => `${selector}=${lead.matches(selector)}`);\n    matches.push(`p-count=${document.querySelectorAll('p').length}`);\n    matches.push(`accent-count=${document.querySelectorAll('.accent').length}`);\n    document.querySelector('#result').textContent = matches.join('\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-9", explanation: "main·h1·두 p에 id와 multiple class token을 의도적으로 다르게 배치합니다." },
            { lines: "13", explanation: "첫 p 하나를 기준 element로 선택합니다." },
            { lines: "14-15", explanation: "기본 selector 여섯 개를 같은 element.matches API로 평가해 match와 non-match를 분리합니다." },
            { lines: "16-17", explanation: "document 전체 p와 accent match 개수를 querySelectorAll의 static NodeList length로 기록합니다." },
          ],
          run: { environment: ["현대 browser", "DevTools Console"], command: "browser에서 selector-matches.html을 열고 출력 확인" },
          output: { value: "*=true\np=true\n.accent=true\n.copy.accent=true\n#lead=true\n#missing=false\np-count=2\naccent-count=2", explanation: ["universal은 lead를 포함한 element를 match하고 p type도 true입니다.", "lead에는 copy와 accent 두 token이 있어 compound .copy.accent가 true입니다.", "강한 ID처럼 보이는 #missing은 값이 다르므로 match하지 않습니다."] },
          experiments: [
            { change: "lead의 class에서 accent만 제거합니다.", prediction: ".accent와 .copy.accent는 false, accent-count는 1이 됩니다.", result: "class selector는 exact token의 현재 존재 여부를 봅니다." },
            { change: "둘째 p에도 id='lead'를 복제합니다.", prediction: "HTML id uniqueness가 깨지고 querySelector('#lead')는 첫 match만 반환합니다.", result: "CSS #lead는 중복 element도 match할 수 있지만 document contract와 fragment/DOM API가 모호해집니다." },
            { change: "selectors 배열에 'p::before'를 넣습니다.", prediction: "lead.matches('p::before')는 element 자체를 pseudo-element와 동일하게 match하지 않습니다.", result: "pseudo-element는 별도 generated box 대상이며 실제 Element node query와 구분합니다." },
          ],
          sourceRefs: ["web-basic-selector-source", "selectors-4"],
        },
      ],
      diagnostics: [
        { symptom: "selector가 강한데도 rule이 Styles panel에 전혀 나타나지 않는다.", likelyCause: "현재 element와 selector가 match하지 않거나 condition/media/scope 밖입니다.", checks: ["Elements에서 실제 tag/id/class token을 확인합니다.", "Console에서 $0.matches('selector')를 실행합니다.", "ancestor 관계와 state, Shadow DOM boundary를 확인합니다."], fix: "실제 component DOM contract에 맞는 selector로 교정하고 class/state를 생성하는 source를 고칩니다.", prevention: "component rendered fixture에 class/role/state와 key selector match assertions를 둡니다." },
      ],
    },
    {
      id: "universal-and-type-selectors",
      title: "universal과 type selector는 넓은 기본값에 유용하지만 전역 영향과 semantic 차이를 존중해야 합니다",
      lead: "* reset과 p rule은 간결하지만 site 전체 element·pseudo-element·form control에 어떤 값을 지우는지 확인합니다.",
      explanations: [
        "universal selector *는 해당 namespace의 모든 element를 match하고 specificity에 기여하지 않습니다. 원본 * { margin:0; padding:0; }는 browser default spacing을 모두 지워 heading·list·form의 읽기 구분을 사라지게 할 수 있습니다. reset/normalize 의도를 property별로 검토합니다.",
        "box-sizing:border-box를 모든 element와 ::before/::after에 적용하는 좁은 universal baseline은 널리 쓰이지만 이것도 replaced element·third-party component와 test합니다. *는 inheritance를 강제하지 않고 각 element에 declaration을 직접 match시킵니다.",
        "type selector p·h1·input은 해당 HTML element를 match하고 specificity C에 1을 더합니다. semantic element default typography를 site baseline으로 정의할 때 유용하지만 component 안 모든 p를 전역으로 바꾸면 예상치 못한 영역에 퍼질 수 있습니다.",
        "HTML document의 type matching은 일반적으로 ASCII case-insensitive한 element name behavior가 있지만 SVG/XML namespace와 case·qualified name은 다릅니다. selector namespace가 필요한 mixed document는 별도 검토합니다.",
        "type을 class API와 결합한 button.button은 markup type을 강제하고 specificity도 증가합니다. 실제 component가 a.button도 지원해야 한다면 .button만, 반드시 button semantic이어야 한다면 HTML contract/test로 보장하는 등 선택 근거를 분리합니다.",
      ],
      concepts: [
        { term: "universal selector", definition: "주어진 namespace에서 모든 element를 나타내는 * selector입니다.", detail: ["specificity는 0입니다.", "광범위한 declaration 영향은 그대로 큽니다."] },
        { term: "type selector", definition: "element의 qualified name을 기준으로 match하는 selector입니다.", detail: ["p·button·article 등이 예입니다.", "specificity C에 1을 더합니다."] },
        { term: "reset", definition: "browser user-agent style 차이와 기본 spacing 등을 의도한 baseline으로 조정하는 stylesheet입니다.", detail: ["무조건 모든 default를 지우는 것과 다릅니다.", "accessibility·form control·list marker를 검증합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "reset 적용 뒤 ul marker와 keyboard focus outline이 사라져 구조와 focus를 알 수 없다.", likelyCause: "* 또는 광범위한 type rule로 list-style/outline 등 유용한 UA default를 근거 없이 제거했습니다.", checks: ["reset 전후 computed style과 accessibility를 비교합니다.", "outline:none/list-style:none source를 찾습니다.", "CSS off와 keyboard Tab을 test합니다."], fix: "필요한 component 범위에서만 style을 변경하고 focus-visible 대체와 semantic list 표현을 명확히 제공합니다.", prevention: "reset 변경에 headings/lists/forms/focus visual regression과 accessibility review를 요구합니다." },
      ],
    },
    {
      id: "class-and-id-contracts",
      title: "class는 재사용·조합 가능한 style hook이고 id는 document 고유 identity와 fragment 관계를 우선합니다",
      lead: "원본의 .fc/.a와 #bc/#container/#fc를 비교해 style API를 identity API와 분리합니다.",
      explanations: [
        "class selector .fc는 class token fc를 가진 여러 element를 match하며 (0,1,0) specificity입니다. 한 element에 .card .card--featured .text-center처럼 여러 class를 조합할 수 있지만 naming convention과 responsibility를 정해 충돌을 줄입니다.",
        "id selector #bc는 id value가 정확한 element를 match하며 (1,0,0) specificity입니다. HTML id는 document 내 고유해야 하고 label for, fragment URL, aria-labelledby/describedby, DOM API가 참조합니다. style convenience로 id를 자주 바꾸면 이런 관계가 깨집니다.",
        "CSS engine은 duplicate id가 있어도 해당 값의 여러 element를 #id로 style할 수 있지만 HTML conformance와 document API 계약이 깨진 상태입니다. 'id selector는 하나만 선택한다'기보다 author가 id를 유일하게 유지해야 한다고 설명하는 것이 정확합니다.",
        "ID selector는 specificity가 높아 component variant/theme에서 override가 어렵습니다. page shell의 고유 anchor라도 style은 class로 제공하고 id는 behavior/relationship identity로 두는 전략이 장기 유지보수에 유리합니다.",
        "class 이름을 red·left처럼 현재 모양으로 짓기보다 alert, card__title, is-selected처럼 component/role/state 의미를 표현합니다. 그러나 class가 semantic HTML을 대신하지 않으며 button 역할은 실제 button element가 가져야 합니다.",
      ],
      concepts: [
        { term: "class selector", definition: "element의 class token을 match하는 .name selector이며 재사용·composition 가능한 author hook입니다.", detail: ["specificity B에 1을 더합니다.", "여러 element/여러 class에 사용할 수 있습니다."] },
        { term: "ID selector", definition: "element의 document id 값을 match하는 #name selector입니다.", detail: ["specificity A에 1을 더합니다.", "HTML author는 id를 document에서 고유하게 유지합니다."] },
        { term: "style hook", definition: "CSS selector가 안정적으로 target하도록 markup에 제공한 class/data/part 등의 public 또는 internal contract입니다.", detail: ["JavaScript hook과 결합 여부를 문서화합니다.", "구조 변경에 견디는 이름을 사용합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "component variant class를 추가해도 #container 또는 #fc style을 override하려고 더 긴 selector와 !important가 필요하다.", likelyCause: "고유 identity용 ID를 visual style selector로 사용해 specificity floor를 높였습니다.", checks: ["ID selector usage와 override chain을 inventory합니다.", "id가 fragment/label/ARIA/JS에서 실제 필요한지 확인합니다.", "class API로 이동했을 때 relationship이 유지되는지 test합니다."], fix: "id는 identity/reference로 유지하고 visual rule은 낮은 specificity class/component layer로 옮깁니다.", prevention: "author CSS의 ID selector를 lint 경고/금지하고 예외 근거를 요구합니다." },
        { symptom: "label을 눌러도 input focus가 안 되고 skip link도 이동하지 않는다.", likelyCause: "style refactor 중 id를 class로 바꾸거나 id 값을 변경하면서 for/href/ARIA 참조를 갱신하지 않았습니다.", checks: ["for→id, href fragment→id, aria-* token→id link integrity를 검사합니다.", "duplicate/missing id를 validator로 찾습니다.", "actual focus/accessible description을 test합니다."], fix: "relationship id는 안정적으로 복구하고 styling만 별도 class로 분리합니다.", prevention: "internal fragment와 IDREF integrity를 rendered test에 둡니다." },
      ],
    },
    {
      id: "selector-lists-and-composition",
      title: "selector list는 declaration을 공유하고 compound selector는 한 element의 조건을 동시에 요구합니다",
      lead: "comma와 공백을 혼동하면 전혀 다른 match set이 되므로 selector grammar 단위를 눈으로 분해합니다.",
      explanations: [
        "원본 h1,p { text-align:center; }는 comma로 두 complex selector를 나열해 같은 declaration block을 공유합니다. h1 p는 comma가 아니라 descendant combinator이며 h1 안의 p를 찾으므로 완전히 다른 selector입니다.",
        ".copy.accent는 공백 없이 같은 element가 두 class를 모두 가져야 하는 compound selector입니다. .copy .accent는 copy class descendant 중 accent element를 선택합니다. formatting line break가 descendant whitespace가 되는 경우를 포함해 token을 정확히 봅니다.",
        "일반 selector list에서 하나의 selector가 invalid면 전체 style rule이 invalid해질 수 있습니다. :is()·:where() 같은 forgiving selector list는 invalid argument를 다르게 처리할 수 있지만 모두 invalid인 경우 등 세부 규칙을 고려합니다. experimental selector를 stable selector와 무심코 comma로 묶지 않습니다.",
        "selector list는 DRY에 유용하지만 서로 다른 component를 우연히 결합해 변경 영향이 커질 수 있습니다. shared token/utility 또는 custom property가 더 명확한지 검토합니다.",
        "복잡한 list는 specificity가 selector마다 독립적으로 계산됩니다. h1, .title에서 h1 branch는 (0,0,1), .title branch는 (0,1,0)입니다. list 전체가 최대 specificity 한 개를 공유하는 것은 아니지만 :is()/nesting은 최대 argument 규칙이 있어 구분해야 합니다.",
      ],
      concepts: [
        { term: "selector list", definition: "comma로 구분된 하나 이상의 complex selector이며 각각 match한 element에 declaration block을 공유합니다.", detail: ["각 일반 branch는 자체 specificity를 가집니다.", "invalid branch가 전체 rule을 무효화할 수 있습니다."] },
        { term: "compound selector", definition: "combinator 없이 한 element에 적용되는 simple selector들의 sequence입니다.", detail: ["p.copy#lead처럼 type·class·id를 동시에 요구합니다.", "각 simple selector specificity가 합산됩니다."] },
        { term: "complex selector", definition: "compound selector들을 descendant/child/sibling combinator로 연결한 selector입니다.", detail: ["DOM 관계를 요구합니다.", "모든 simple selector 기여가 합산됩니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: ".card.title로 바꿨더니 card 안 title이 아니라 같은 element에 두 class가 있을 때만 style된다.", likelyCause: "descendant selector .card .title에서 공백을 제거해 compound selector로 의미를 바꿨습니다.", checks: ["selector를 compound/combinator 단위로 나눕니다.", "DOM에서 class가 같은 element인지 ancestor/descendant인지 봅니다.", "matches/querySelectorAll count를 비교합니다."], fix: "의도한 관계면 .card .title, 같은 element의 variant면 .card.title을 사용하고 DOM contract를 test합니다.", prevention: "formatter/minifier 전후 selector meaning과 component fixture match count를 검사합니다." },
      ],
    },
    {
      id: "specificity-tuple",
      title: "specificity는 십진수 한 점수가 아니라 ID·class 계열·type 계열의 A-B-C tuple입니다",
      lead: "각 column을 왼쪽부터 lexicographic하게 비교하며 10개의 class가 ID 하나로 carry되는 산수 규칙은 없습니다.",
      explanations: [
        "Selectors Level 4 기준으로 ID selector 수가 A, class·attribute·pseudo-class 수가 B, type selector·pseudo-element 수가 C입니다. universal selector와 combinator는 specificity를 추가하지 않습니다. #lead.copy p::first-line이면 (1,1,2)처럼 계산합니다.",
        "tuple은 왼쪽부터 비교합니다. (1,0,0)은 (0,100,100)보다 강합니다. 이를 100·10·1 십진수로 단순 합산하면 class 10개가 ID 하나와 같아지는 잘못된 결론을 냅니다.",
        "inline style은 이 A-B-C selector specificity tuple이 아닙니다. cascade specification에서 style attribute라는 별도 앞 단계로 비교합니다. !important도 specificity를 더하지 않고 origin/importance 단계가 달라집니다. @layer는 specificity보다 먼저 비교됩니다.",
        "같은 specificity라면 @scope proximity가 해당될 수 있고 마지막으로 appearance order가 승자를 정합니다. 따라서 두 .class rule의 뒤 rule이 이기지만 다른 layer라면 layer order가 먼저입니다.",
        "specificity를 계산하는 목적은 selector를 더 강하게 만드는 것이 아니라 override API와 예상 결과를 검증하는 것입니다. component default를 (0,1,0) 근처로 유지하면 variant/utility/user style과 협력하기 쉽습니다.",
      ],
      concepts: [
        { term: "specificity tuple", definition: "selector의 우선도를 (ID 수, class/attribute/pseudo-class 수, type/pseudo-element 수)로 나타낸 A-B-C 값입니다.", detail: ["왼쪽 column부터 비교합니다.", "universal/combinator는 0입니다."] },
        { term: "source-order tie", definition: "앞 cascade 기준과 specificity까지 모두 같을 때 appearance order상 뒤 declaration이 이기는 상황입니다.", detail: ["bundle/link order 변화에 민감합니다.", "같은 property의 shorthand/longhand도 확인합니다."] },
      ],
      codeExamples: [
        {
          id: "specificity-tournament",
          title: "type·class·ID·source order의 specificity 대결을 computed output으로 증명하기",
          language: "html",
          filename: "specificity.html",
          purpose: "같은 cascade layer·importance에서 match하는 selector의 tuple과 tie-break를 단계적으로 관찰합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>명시도 실험</title>\n  <style>\n    p { color: skyblue; }                 /* 0-0-1 */\n    .message { color: tomato; }           /* 0-1-0 */\n    p.message { color: darkgreen; }       /* 0-1-1 */\n    #notice { color: rebeccapurple; }     /* 1-0-0 */\n    .panel .message { background: beige; }/* 0-2-0 */\n    .message.is-hot { background: gold; } /* 0-2-0, later */\n  </style>\n</head>\n<body>\n  <section class=\"panel\">\n    <p id=\"notice\" class=\"message is-hot\">명시도 결과</p>\n  </section>\n  <pre id=\"result\"></pre>\n  <script>\n    const s = getComputedStyle(document.querySelector('#notice'));\n    document.querySelector('#result').textContent = `color=${s.color}\nbackground=${s.backgroundColor}`;\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-10", explanation: "모두 p를 match하지만 type<one class<type+class<ID tuple 순으로 color 승자가 정해집니다." },
            { lines: "11-12", explanation: "background 두 selector는 모두 0-2-0이고 같은 layer/origin이므로 뒤 .message.is-hot가 source-order tie를 이깁니다." },
            { lines: "16-18", explanation: "한 element가 모든 selector 조건을 충족하도록 ancestor·id·multiple class를 배치합니다." },
            { lines: "21-22", explanation: "최종 resolved color와 background를 canonical rgb로 출력합니다." },
          ],
          run: { environment: ["현대 browser", "DevTools Styles specificity 확인"], command: "browser에서 specificity.html을 열고 출력 확인" },
          output: { value: "color=rgb(102, 51, 153)\nbackground=rgb(255, 215, 0)", explanation: ["rebeccapurple ID selector가 color를 이깁니다.", "gold rule은 background specificity tie에서 나중 appearance order로 이깁니다.", "!important·layer·inline이 없으므로 specificity 실험이 격리됩니다."] },
          experiments: [
            { change: "#notice rule을 제거합니다.", prediction: "color는 p.message의 darkgreen(rgb(0,100,0))이 됩니다.", result: "0-1-1이 0-1-0과 0-0-1보다 강합니다." },
            { change: "gold rule을 beige rule보다 앞으로 이동합니다.", prediction: "background는 beige(rgb(245,245,220))가 됩니다.", result: "동일 0-2-0은 appearance order가 결정합니다." },
            { change: "p type rule에 !important를 붙입니다.", prediction: "color는 skyblue가 됩니다.", result: "importance 단계가 달라져 낮은 specificity라도 normal ID보다 먼저 승리합니다." },
          ],
          sourceRefs: ["web-basic-selector-source", "web-selector-group-source", "selectors-4", "css-cascade-6"],
        },
      ],
      diagnostics: [
        { symptom: "specificity 계산기에서 0-10-0을 1-0-0과 같다고 보고 override 결과를 틀린다.", likelyCause: "tuple을 100/10/1 십진수처럼 carry되는 숫자로 해석했습니다.", checks: ["ID·class계열·type계열을 별도 column으로 다시 셉니다.", "왼쪽부터 lexicographic 비교합니다.", "importance/layer가 같은지 먼저 확인합니다."], fix: "A-B-C tuple 표기로 기록하고 inline/important/layer를 별도 cascade column에 둡니다.", prevention: "code review와 lint/report에서 selector tuple과 layer를 함께 표시합니다." },
      ],
    },
    {
      id: "functional-pseudo-specificity",
      title: ":where()는 specificity를 0으로 만들고 :is()·:not()·:has()는 가장 강한 argument의 값을 사용합니다",
      lead: "현대 selector helper는 readability뿐 아니라 public override contract를 의도적으로 설계하는 도구입니다.",
      explanations: [
        ":where(header, main, footer)처럼 :where()와 그 argument는 specificity 0을 기여합니다. component 내부 descendant default를 :where(.card) :where(h2, p)로 쓰면 DOM 범위는 제한하면서 consumer가 한 class로 쉽게 override할 수 있습니다.",
        ":is(.card, #preview) .title은 :is() argument list에서 가장 높은 #preview의 (1,0,0)을 사용해 실제 match branch가 .card여도 높은 specificity를 가질 수 있습니다. 편리한 grouping에 ID를 섞으면 예상보다 override가 어려워집니다.",
        ":not(.disabled, #locked)도 pseudo-class 자체가 별도 한 점을 더하는 대신 가장 강한 argument specificity를 사용합니다. :has() 역시 argument의 가장 구체적인 complex selector 값을 반영합니다. 다음 css-03에서 relational/state matching을 깊게 다룹니다.",
        "CSS nesting의 & specificity는 parent selector list의 가장 높은 complex selector와 연관되어 :is()와 비슷한 결과를 만들 수 있습니다. .card, #preview { & .title {...} }에 ID를 섞으면 .card branch도 높은 specificity 영향을 받습니다.",
        ":nth-child(An+B of selector-list)는 pseudo-class 자체와 of list의 가장 높은 specificity를 함께 고려합니다. 복잡한 helper를 암기하기보다 browser DevTools/spec test로 component public selector를 검증합니다.",
      ],
      concepts: [
        { term: ":where()", definition: "argument selector 중 하나를 match하지만 함수와 arguments 전체 specificity가 0인 forgiving functional pseudo-class입니다.", detail: ["low-specificity defaults에 유용합니다.", "match 범위는 그대로 유지됩니다."] },
        { term: ":is()", definition: "argument selector 중 하나를 match하고 가장 높은 argument specificity를 사용하는 forgiving functional pseudo-class입니다.", detail: ["selector grouping을 간결하게 합니다.", "ID argument가 모든 branch specificity를 높일 수 있습니다."] },
        { term: "nesting selector", definition: "nested CSS rule에서 parent selector context를 나타내는 & selector입니다.", detail: ["부모 selector list 최대 specificity와 상호작용합니다.", "공백 유무로 self/descendant 의미가 달라집니다."] },
      ],
      codeExamples: [
        {
          id: "where-is-specificity-proof",
          title: ":where와 :is가 같은 match set에서 다른 override 결과를 만드는 예",
          language: "html",
          filename: "functional-specificity.html",
          purpose: "match 편의는 비슷하지만 specificity contract가 다른 두 helper를 computed style로 비교합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>함수형 선택자 명시도</title>\n  <style>\n    :where(#low.card) .title { color: darkgreen; } /* 0-1-0: .title만 */\n    .theme .title { color: tomato; }               /* 0-2-0: 승리 */\n\n    :is(#high.card) .label { color: rebeccapurple; } /* 1-2-0 */\n    .theme .label { color: orange; }                 /* 0-2-0: 패배 */\n  </style>\n</head>\n<body class=\"theme\">\n  <section id=\"low\" class=\"card\"><h1 class=\"title\">where 제목</h1></section>\n  <section id=\"high\" class=\"card\"><p class=\"label\">is 레이블</p></section>\n  <pre id=\"result\"></pre>\n  <script>\n    const color = (selector) => getComputedStyle(document.querySelector(selector)).color;\n    document.querySelector('#result').textContent = `where=${color('.title')}\nis=${color('.label')}`;\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-8", explanation: ":where(#low.card)는 ID/class까지 모두 zero이고 descendant .title만 0-1-0입니다. 뒤 .theme .title 0-2-0이 tomato로 이깁니다." },
            { lines: "10-11", explanation: ":is(#high.card)는 가장 높은 argument compound 1-1-0에 .label 0-1-0이 더해져 1-2-0이 되므로 .theme .label보다 강합니다. 주석의 간단 표기가 parent 부분만 지칭하지 않도록 전체 계산을 walkthrough에서 명시합니다." },
            { lines: "15-16", explanation: "두 section 모두 ID와 card를 가져 matching 자체는 명확하게 true입니다." },
            { lines: "19-20", explanation: "두 target의 resolved color를 같은 함수로 출력합니다." },
          ],
          run: { environment: ["Selectors Level 4 :where/:is 지원 browser"], command: "browser에서 functional-specificity.html을 열고 출력 확인" },
          output: { value: "where=rgb(255, 99, 71)\nis=rgb(102, 51, 153)", explanation: [":where default는 theme의 두-class selector가 쉽게 override합니다.", ":is 안 ID가 specificity를 높여 뒤 theme rule도 이기지 못합니다.", "match set만 보고 두 helper를 교환하면 cascade contract가 달라집니다."] },
          experiments: [
            { change: ":is(#high.card)를 :where(#high.card)로 바꿉니다.", prediction: "label은 orange(rgb(255,165,0))가 됩니다.", result: "zero-specificity wrapper는 consumer override를 쉽게 합니다." },
            { change: ":is(#high.card)를 :is(.card)로 바꿉니다.", prediction: "selector는 .card+.label의 0-2-0이고 뒤 .theme .label도 0-2-0이므로 source order상 orange가 이깁니다.", result: "가장 강한 argument가 specificity를 결정합니다." },
            { change: "두 section selector를 nested parent list '.card, #high'로 합쳐 .label rule을 nest합니다.", prediction: "parent list 최대 ID specificity가 .card branch에도 영향을 줄 수 있습니다.", result: "nesting selector의 specificity를 작성 편의만으로 판단하지 않습니다." },
          ],
          sourceRefs: ["selectors-4", "css-nesting-1"],
        },
      ],
      diagnostics: [
        { symptom: ":is(.card, #legacy) 안에서 .card가 match했는데도 override가 ID처럼 강하다.", likelyCause: ":is()는 실제로 match한 branch가 아니라 selector list 중 가장 높은 argument specificity를 사용합니다.", checks: [":is argument의 ID·class·type을 inventory합니다.", "DevTools에서 전체 selector specificity를 확인합니다.", ":where 또는 selector list 분리가 의도에 맞는지 검토합니다."], fix: "low-specificity default라면 :where를 사용하거나 ID branch를 별도 rule로 분리하고 class API로 migration합니다.", prevention: "public component selector의 :is/:not/:has/nesting argument에 ID를 lint/금지합니다." },
      ],
    },
    {
      id: "maintainable-selector-architecture",
      title: "유지보수 가능한 selector는 낮고 안정적인 component boundary와 명시적인 state API를 가집니다",
      lead: "DOM depth를 그대로 복사한 selector보다 의미 있는 class 한두 개와 layer contract가 refactor에 강합니다.",
      explanations: [
        "#app main section div.card ul li a.title처럼 긴 descendant chain은 specificity가 높을 뿐 아니라 wrapper 하나만 바뀌어도 match가 끊깁니다. .card__title처럼 component가 소유한 class 또는 data attribute/state를 public contract로 정합니다.",
        "BEM·utility·CSS Modules·CSS-in-JS·scoped CSS는 naming/collision 문제를 다른 방식으로 해결하지만 cascade는 여전히 존재합니다. generated class도 layer·source order·state selector와 경쟁합니다. tool을 쓰면 specificity가 사라진다고 오해하지 않습니다.",
        "base component는 class 한 개, variant는 추가 class/attribute, state는 native pseudo-class나 aria/data state를 사용합니다. disabled를 .gray class로 표현하지 않고 실제 disabled/aria-disabled behavior와 selector를 연결합니다.",
        "descendant selector는 component 내부 markup을 style하는 데 여전히 유용하지만 :where(.card) > .card__title처럼 boundary와 specificity를 제어할 수 있습니다. global element rule과 component rule, utility override의 layer order를 문서화합니다.",
        "selector 성능은 browser가 주로 오른쪽 key selector에서 후보를 찾고 관계를 확인하는 구현을 고려할 수 있지만, 대부분 application에서 readability·match 범위·style invalidation을 측정 없이 미세 최적화하지 않습니다. * 또는 deep :has가 대규모 DOM에서 hot path라면 performance profile로 판단합니다.",
      ],
      concepts: [
        { term: "component boundary", definition: "component가 소유하는 DOM과 style hook의 범위·public override 지점을 정한 계약입니다.", detail: ["외부 DOM depth에 의존하지 않습니다.", "variant/state naming을 포함합니다."] },
        { term: "specificity budget", definition: "project/component selector가 넘지 않도록 정한 specificity 복잡도 기준입니다.", detail: ["ID와 deep chain 증가를 예방합니다.", "예외는 layer/ownership 근거와 함께 review합니다."] },
        { term: "style invalidation", definition: "DOM/class/state 변화 뒤 어떤 element의 selector match/style을 다시 계산해야 하는지 browser가 갱신하는 과정입니다.", detail: ["복잡 selector 영향은 측정합니다.", "단순 query 속도만으로 architecture를 결정하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "card에 wrapper div를 하나 추가했더니 title·link·icon style이 모두 사라졌다.", likelyCause: "page DOM depth를 복사한 child/descendant chain이 component contract가 되어 구조 refactor에 취약합니다.", checks: ["broken selector의 ancestor chain을 실제 DOM과 비교합니다.", "component-owned class가 있는지 봅니다.", "외부 page id/type에 의존하는 rule을 inventory합니다."], fix: "component-owned low-specificity class와 명시적 variant/state hook으로 바꾸고 wrapper-independent fixture를 test합니다.", prevention: "component DOM contract test와 selector depth/specificity lint를 둡니다." },
      ],
    },
    {
      id: "selector-debugging-security",
      title: "selector 문제는 match set·specificity tuple·cascade 단계·dynamic input을 분리해 검증합니다",
      lead: "DevTools 취소선만 보고 결론 내리지 않고 selector 자체가 invalid하거나 untrusted data로 구성된 경우까지 확인합니다.",
      explanations: [
        "첫째 document.querySelectorAll(selector).length와 target.matches(selector)로 match를 확인합니다. 둘째 selector를 A-B-C로 계산합니다. 셋째 같은 layer/origin/importance인지 확인한 뒤 source order를 봅니다. 네 단계 표를 issue에 남기면 '더 강하게'라는 모호한 수정이 줄어듭니다.",
        "동적으로 id/class를 selector string에 삽입할 때 특수 문자는 grammar를 깨뜨릴 수 있습니다. document.querySelector('#' + id) 대신 가능하면 getElementById를 사용하거나 CSS.escape(id)로 identifier를 escape합니다. 그러나 escape는 authorization이나 HTML sanitization을 제공하지 않습니다.",
        "사용자 입력을 style element나 selector/declaration text로 조립하면 selector injection·CSS exfiltration·unexpected resource URL 등 위험이 있습니다. 허용 token을 mapping하고 untrusted raw CSS를 실행하지 않습니다.",
        "duplicate id는 validator로, missing class는 rendered component test로, invalid selector list는 CSS parser/linter로, specificity regression은 report/snapshot으로 자동화합니다. selector behavior와 visual output을 모두 test합니다.",
        "브라우저 지원이 필요한 :has·nesting 등은 @supports selector(...) 또는 build target/fallback을 검토합니다. unsupported selector가 일반 selector list 전체를 무효화할 수 있으므로 progressive enhancement boundary를 둡니다.",
      ],
      concepts: [
        { term: "CSS.escape", definition: "문자열을 CSS identifier 일부로 안전하게 표현하도록 escape하는 Web API입니다.", detail: ["selector syntax 오류를 줄입니다.", "보안 authorization/sanitization을 대신하지 않습니다."] },
        { term: "selector injection", definition: "untrusted text가 selector grammar로 해석되어 의도하지 않은 element matching이나 style behavior를 만드는 문제입니다.", detail: ["raw CSS/declaration injection과 함께 threat model합니다.", "allowlisted token mapping이 안전합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "id가 'section:1'인 element를 querySelector('#section:1')로 찾을 때 SyntaxError 또는 0 match가 난다.", likelyCause: "colon이 pseudo-class syntax로 해석되며 raw id를 CSS selector에 삽입했습니다.", checks: ["getElementById('section:1') 결과를 확인합니다.", "CSS.escape 반환 selector를 test합니다.", "id naming/third-party data source를 확인합니다."], fix: "ID lookup이면 getElementById를 사용하고 selector가 필요하면 '#' + CSS.escape(id)로 escape합니다.", prevention: "dynamic selector builder를 중앙화하고 raw user input interpolation을 lint/security review합니다." },
      ],
      expertNotes: [
        "`:has()`는 relational selector로 부모/앞 element를 조건화할 수 있어 DOM class를 줄이지만, style invalidation 범위와 fallback을 실제 large DOM에서 측정합니다. 다음 세션에서 관계/상태 selector로 구현합니다.",
        "CSS Modules의 hashed local class도 consumer override가 global layer/order에 의존할 수 있습니다. composition과 global escape hatch의 public contract를 문서화합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 selector page를 specificity가 예측 가능한 component style lab으로 리팩터링하기",
    scenario: "* reset, type rule, .fc/.a class, #bc/#container/#fc ID, inline magenta가 섞여 작은 변경에도 긴 selector와 !important가 늘고 있습니다. visual output을 보존하면서 match·specificity·identity contract를 정리합니다.",
    setup: ["원본 selector file 3개를 read-only evidence로 준비합니다.", "DevTools Styles/Computed, Element.matches/querySelectorAll, HTML/CSS validator를 준비합니다.", "각 selector의 match count·A-B-C·layer·owner·public 여부를 기록할 표를 만듭니다."],
    steps: [
      "*, type, class, ID, inline selector/declaration inventory와 실제 match count를 기록합니다.",
      "각 충돌 color/background/text-align의 matching 후보와 specificity tuple을 계산합니다.",
      "#bc/#container/#fc 중 fragment/label/ARIA/JS identity가 필요한 id와 styling-only id를 구분합니다.",
      "visual style을 component class와 variant/state class로 옮기고 ID selector·inline style을 제거합니다.",
      ":where()로 component descendant defaults를 낮추고 consumer class override가 한 단계로 되는지 확인합니다.",
      ":is()에 ID를 넣은 실패 case와 nesting parent list 최대 specificity를 재현합니다.",
      "HTML duplicate/missing ID, selector invalidity, specificity budget, rendered computed colors를 자동 test합니다.",
      "CSS off·keyboard/ARIA relationship·visual regression을 확인해 semantic behavior가 보존됐는지 기록합니다.",
    ],
    expectedResult: ["모든 selector의 match set과 A-B-C를 정확히 설명할 수 있습니다.", "style용 ID selector와 inline declaration이 class/layer contract로 이동합니다.", "label/fragment/ARIA/JS에 필요한 id는 고유하고 안정적으로 유지됩니다.", "component default는 :where 등 낮은 specificity이고 variant/utility가 !important 없이 override합니다.", "DOM wrapper 변경 fixture에서도 component style이 유지됩니다.", "duplicate ID·broken IDREF·invalid selector·specificity budget·computed output test가 통과합니다."],
    cleanup: ["실험용 duplicate id·ID-in-:is·!important·inline style을 제거합니다.", "DevTools에서 임시 변경한 class를 reload하고 source/build 결과와 일치시킵니다."],
    extensions: ["CSS Modules 또는 scoped style로 같은 component를 구현하고 global layer contract를 비교합니다.", "large DOM에서 :has/deep descendant change의 style recalculation을 Performance panel로 측정합니다.", "selector specificity report를 CI artifact로 생성하고 baseline 초과만 실패시키는 migration을 설계합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 ex13의 각 p가 어떤 color를 갖는지 match와 specificity로 예측하세요.", requirements: ["p, .fc, #bc, inline 후보를 element별로 표로 만듭니다.", "inline/importance/layer와 A-B-C를 구분합니다.", "getComputedStyle rgb와 DevTools winning source를 기록합니다.", "class/id 하나씩 제거해 prediction을 다시 검증합니다."], hints: ["먼저 match하지 않는 selector를 제거합니다.", "inline style은 A-B-C tuple에 억지로 넣지 않습니다."], expectedOutcome: "모든 p/h1의 최종 color/background를 정확히 설명하고 prediction과 actual이 일치합니다.", solutionOutline: ["DOM attribute snapshot→match 후보→cascade 앞 단계→specificity→order 순서로 표를 채웁니다.", "named color와 rgb serialization을 구분합니다."] },
    { difficulty: "응용", prompt: "ID와 deep selector를 낮은 specificity card component API로 리팩터링하세요.", requirements: ["base·element·variant·state class naming을 정의합니다.", "ID selector와 !important를 사용하지 않습니다.", ":where default와 class override를 비교합니다.", "wrapper 추가·heading type 변경·dark theme fixture를 test합니다.", "semantic id/ARIA 관계는 유지합니다."], hints: ["id identity와 class style 책임을 분리합니다.", "DOM path보다 component-owned hook을 사용합니다."], expectedOutcome: "consumer가 class 하나로 override할 수 있고 markup wrapper refactor에도 style/접근성이 유지됩니다.", solutionOutline: ["public DOM/style contract부터 작성합니다.", "specificity tuple과 layer를 API 문서에 포함합니다."] },
    { difficulty: "설계", prompt: "design system의 selector·specificity·state governance와 migration 계획을 설계하세요.", requirements: ["layer order와 component specificity budget을 정의합니다.", "ID·inline·!important·:is ID·nesting depth policy를 만듭니다.", "BEM/utility/CSS Modules/CSS-in-JS 선택과 interop을 설명합니다.", "ARIA/data/native state selector의 behavior contract를 포함합니다.", "match/specificity/visual/accessibility/performance CI를 설계합니다."], hints: ["도구가 class 이름을 hash해도 cascade는 사라지지 않습니다.", "user style과 consumer override 지점을 public API로 봅니다."], expectedOutcome: "팀이 selector를 더 강하게 만드는 방식 없이 예측 가능한 override와 component refactor를 수행하는 governance가 완성됩니다.", solutionOutline: ["현재 selector inventory와 exception baseline을 만듭니다.", "새 code rule과 legacy 감소 metric을 분리합니다."] },
  ],
  reviewQuestions: [
    { question: "높은 specificity selector가 항상 이기나요?", answer: "아닙니다. 먼저 selector가 match하고 같은 origin/importance/style-attribute/layer 단계여야 specificity를 비교합니다." },
    { question: "* selector는 specificity가 0이면 영향도 없는가요?", answer: "아닙니다. specificity 기여는 0이지만 매우 많은 element에 declaration을 직접 적용해 전역 영향이 큽니다." },
    { question: "ID selector는 정확히 한 element만 match하나요?", answer: "HTML author는 id를 고유하게 유지해야 하지만 duplicate markup이 있으면 CSS selector가 여러 element를 match할 수 있습니다. document contract가 깨진 상태입니다." },
    { question: ".card.title과 .card .title은 어떻게 다른가요?", answer: "앞은 한 element가 두 class를 모두 가져야 하고, 뒤는 .card descendant의 .title을 선택합니다." },
    { question: "specificity 0-10-0은 1-0-0과 같은가요?", answer: "아닙니다. tuple은 carry 없는 lexicographic 비교라 ID column 1이 class column 수보다 항상 먼저입니다." },
    { question: "!important는 specificity를 얼마나 더하나요?", answer: "specificity를 더하지 않습니다. origin/importance라는 더 앞 cascade 단계에서 normal declaration과 분리합니다." },
    { question: ":where(#id .class)의 specificity는 얼마인가요?", answer: ":where 함수와 모든 argument는 0입니다. selector 바깥 부분만 specificity에 기여합니다." },
    { question: ":is(.card,#preview)는 .card branch가 match하면 class specificity만 쓰나요?", answer: "아닙니다. argument list 중 가장 높은 #preview specificity를 사용해 모든 branch가 강해질 수 있습니다." },
    { question: "selector 성능을 위해 무조건 class 하나만 써야 하나요?", answer: "아닙니다. maintainability와 match scope를 우선하고 실제 style recalculation 병목은 Performance 측정으로 판단합니다." },
  ],
  completionChecklist: [
    "specificity 전에 실제 DOM과 state에서 selector match 여부를 확인했다.",
    "universal·type·class·ID를 역할과 전역 범위에 맞게 선택했다.",
    "selector list·compound·complex selector와 comma/whitespace 차이를 설명했다.",
    "모든 competing selector의 A-B-C tuple을 carry 없이 계산했다.",
    "inline·!important·layer를 specificity tuple과 별도 cascade 단계로 기록했다.",
    ":where/:is/:not/:has/nesting의 specificity 규칙을 actual output으로 검증했다.",
    "style용 ID·deep DOM chain·specificity escalation을 component class/layer API로 교체했다.",
    "duplicate/missing IDREF·invalid selector·match count·computed style·accessibility 회귀를 test했다.",
  ],
  nextSessions: ["css-03-combinators-attributes-pseudo"],
  sources: [
    { id: "web-basic-selector-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex13_css_selector.html", usedFor: ["universal·type·class·ID", "inline competition", "색상 specificity", "reset"], evidence: "*, #bc/#bc2, .fc, p와 inline magenta의 실제 충돌을 match/specificity/cascade lab의 핵심 evidence로 사용했습니다." },
    { id: "web-selector-group-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex14_css_selector.html", usedFor: ["#container·#fc", ".a", "selector grouping", "type versus class"], evidence: "레드향 page의 grouped h1,p와 .a/#fc를 감사해 selector list·style ID migration·component boundary로 확장했습니다." },
    { id: "web-attribute-selector-boundary-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex01_selector.html", usedFor: ["attribute selector boundary", "input type hook", "base selector와 attribute specificity 비교"], evidence: "attribute selector 예제를 읽고 class-equivalent specificity 범주와 다음 관계/속성 selector 세션의 경계를 확인했습니다." },
    { id: "selectors-4", repository: "W3C CSS Working Group", path: "TR/selectors-4/", publicUrl: "https://www.w3.org/TR/selectors-4/", usedFor: ["selector grammar", "specificity", "universal/type/class/ID", ":where/:is/:not/:has", "forgiving lists"], evidence: "2026-07-12 기준 Selectors Level 4의 simple/compound/complex selector와 functional pseudo specificity를 계산 기준으로 확인했습니다." },
    { id: "css-nesting-1", repository: "W3C CSS Working Group", path: "TR/css-nesting-1/", publicUrl: "https://www.w3.org/TR/css-nesting-1/", usedFor: ["nested style rules", "& selector", "parent list maximum specificity", "relative selector"], evidence: "2026-01 Working Draft의 nesting selector specificity와 relative syntax를 modern component 진단에 반영했습니다." },
    { id: "css-cascade-6", repository: "W3C CSS Working Group", path: "TR/css-cascade-6/", publicUrl: "https://www.w3.org/TR/css-cascade-6/", usedFor: ["specificity의 cascade 위치", "scope proximity", "style attribute", "appearance order"], evidence: "specificity가 origin/importance/layer 뒤, source order 앞에서 비교된다는 전체 cascade 위치를 확인했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본은 기본 selector·grouping·attribute hook을 풍부하게 제공합니다. Selectors 4의 :where/:is/:not/:has와 2026 CSS Nesting specificity, selector security/governance는 공식 W3C 문서로 보강했습니다.",
      "attribute operator·combinator·pseudo-class/element의 상세 matching과 :has performance는 다음 css-03에서 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
