import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["html-03-links-paths-navigation"],
  slug: "html-03-links-paths-navigation",
  courseId: "web",
  moduleId: "01-html-document-forms",
  order: 3,
  title: "링크, URL, 상대·절대 경로와 페이지 내 탐색",
  subtitle: "a와 href의 의미에서 출발해 URL 기준점·경로 정규화·fragment·target·링크 상태를 추적하고, 배포 경로가 바뀌어도 안전하고 접근 가능한 탐색을 설계합니다.",
  level: "입문",
  estimatedMinutes: 190,
  coreQuestion: "href에 적은 문자열은 어떤 기준 URL과 결합되어 실제 이동 주소가 되며, 폴더 이동·페이지 내 목차·새 창·키보드 탐색까지 깨지지 않는 링크는 어떻게 설계할까요?",
  summary: "원본 a 태그 주석과 외부·절대·상대 경로 예제, fragment 목차, link·visited·hover 상태 CSS를 모두 감사합니다. 링크의 의미와 URL 구성, base URL을 이용한 상대 URL 해석, 애플리케이션 context path와 정적 배포 base path, id fragment와 :target, browsing context를 고르는 target, noopener·noreferrer·referrerpolicy의 차이, 링크와 button의 역할, 링크 목적과 focus 표시, 자동·수동 링크 검사를 하나의 재현 가능한 mental model로 연결합니다.",
  objectives: [
    "href가 있는 a가 hyperlink가 되는 이유와 링크·button의 역할 차이를 설명할 수 있다.",
    "scheme·origin·path·query·fragment를 구분하고 base URL과 상대 URL로 최종 URL을 계산할 수 있다.",
    "./·../·/로 시작하는 경로의 차이를 설명하고 context path 또는 하위 경로 배포에서 404를 진단할 수 있다.",
    "고유 id와 #fragment로 문서 목차를 만들고 :target·fixed header·focus까지 고려할 수 있다.",
    "_self·_blank·_parent·_top·이름 있는 target을 선택하고 새 창의 보안·접근성 영향을 설명할 수 있다.",
    "link·visited·hover·active·focus-visible 상태를 구분하고 색·밑줄·focus indicator를 함께 설계할 수 있다.",
    "의미 있는 링크 이름, 키보드 탐색, URL 검증, 상태 코드·redirect·배포 base를 포함한 링크 품질 검사를 수행할 수 있다.",
  ],
  prerequisites: [
    {
      title: "제목·문단·텍스트 의미와 블록/인라인 흐름",
      reason: "링크의 이름은 a 내부 텍스트와 주변 문맥에서 만들어지고, fragment 목적지는 보통 의미 있는 heading·section에 붙습니다. 문서 흐름과 strong·em 같은 텍스트 의미를 알아야 링크를 단순한 파란 글자가 아니라 문서 구조의 연결로 설계할 수 있습니다.",
      sessionSlug: "html-02-text-block-inline",
    },
  ],
  keywords: ["a", "href", "hyperlink", "URL", "base URL", "relative URL", "absolute URL", "context path", "fragment", "id", "target", "noopener", "noreferrer", "referrerpolicy", ":link", ":visited", ":target", ":focus-visible", "accessibility"],
  chapters: [
    {
      id: "anchor-is-a-navigation-contract",
      title: "href가 있는 a는 현재 문서와 목적지를 잇는 탐색 계약입니다",
      lead: "밑줄과 파란색은 기본 표현일 뿐이고, 링크의 본질은 사용자가 목적지를 예측하고 브라우저의 탐색 기능을 그대로 사용할 수 있게 하는 의미와 URL입니다.",
      explanations: [
        "WHATWG HTML 표준에서 a는 href가 있을 때 그 내용으로 이름 붙은 hyperlink를 나타냅니다. href가 없으면 미래에 링크가 놓일 수 있는 placeholder일 뿐이므로 Tab 탐색·주소 복사·새 탭 열기 같은 온전한 링크 동작을 기대하면 안 됩니다. 원본의 '다른 페이지나 같은 페이지의 위치로 이동' 설명은 좋은 출발점이지만, 실제로는 HTTP(S) 문서뿐 아니라 mailto·tel·download 후보와 같은 URL도 href가 표현할 수 있습니다.",
        "사용자가 링크를 활성화하면 브라우저는 href를 URL로 해석하고 browsing context를 정한 다음 history를 포함한 navigation을 수행합니다. 이 기본 동작 덕분에 Enter 키, 우클릭 메뉴, 주소 복사, 새 탭 열기, 상태 표시줄의 목적지 미리 보기, 검색 crawler가 함께 작동합니다. div에 click listener만 붙이면 이 기능을 전부 다시 구현해야 하므로 이동은 a로 표현하는 것이 기본입니다.",
        "링크와 button은 모양이 아니라 결과로 구분합니다. 다른 문서·route·현재 문서의 section처럼 주소로 이동하면 a, 현재 화면의 menu 열기·modal 닫기·계산 실행처럼 같은 위치에서 상태나 동작을 바꾸면 button입니다. CSS로 a를 button처럼, button을 link처럼 보이게 할 수 있어도 semantic role과 keyboard behavior는 바뀌지 않습니다.",
        "a의 content model은 넓지만 내부에 또 다른 a, button·input 같은 interactive content, tabindex를 지정한 descendant를 넣을 수 없습니다. 카드 전체를 link로 만들 때 카드 안의 '좋아요' button까지 감싸면 클릭 목적이 겹치고 keyboard focus 순서가 깨집니다. 카드 제목만 명확한 link로 두거나 overlay link pattern을 매우 신중히 설계합니다.",
      ],
      concepts: [
        { term: "hyperlink", definition: "현재 자원에서 URL로 식별되는 다른 자원 또는 같은 문서의 위치로 탐색할 수 있게 하는 연결입니다.", detail: ["href가 목적지 주소를 제공합니다.", "link text와 주변 문맥은 사용자가 목적을 판단하는 이름을 제공합니다.", "browser history·주소 복사·새 탭 같은 native 기능을 보존합니다."], analogy: "교과서의 '42쪽 참고'가 목적지와 설명을 함께 제공하는 색인 항목과 비슷합니다." },
        { term: "navigation", definition: "URL을 해석해 지정한 browsing context가 다른 document 또는 같은 document의 fragment를 표시하도록 상태를 전환하는 과정입니다.", detail: ["DOM event 한 번과 동일한 개념이 아닙니다.", "history·referrer·network request·scroll 위치가 관여할 수 있습니다."] },
        { term: "accessible name", definition: "보조기술이 link를 식별해 읽는 이름으로, 일반적인 text link에서는 descendant text가 핵심 재료입니다.", detail: ["'여기'보다 '상대 URL 계산 예제'처럼 목적지를 설명합니다.", "아이콘만 있는 link는 대체 text 또는 명시적 이름이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "마우스로는 이동하지만 Tab으로 focus할 수 없고 우클릭해 새 탭에서 열거나 주소를 복사할 수 없다.",
          likelyCause: "div·span에 click listener와 cursor:pointer만 붙여 link처럼 보이게 했습니다.",
          checks: ["Elements에서 실제 element와 href 존재 여부를 확인합니다.", "Tab과 Enter만으로 동작하는지 시험합니다.", "accessibility tree에서 role과 이름을 확인합니다.", "JavaScript를 끈 상태에서 목적지 정보가 남는지 봅니다."],
          fix: "주소 이동이면 의미 있는 href가 있는 a로 바꾸고, 같은 화면의 동작이면 type=button인 button으로 바꿉니다.",
          prevention: "컴포넌트 API에서 href가 있으면 Link, event action이면 Button을 선택하도록 의미 기준을 문서화하고 keyboard test를 둡니다.",
        },
      ],
      comparisons: [
        {
          title: "클릭 가능한 UI를 어떤 element로 만들까요?",
          options: [
            { name: "a[href]", chooseWhen: "새 URL·route·문서 fragment로 이동하고 browser navigation 기능을 제공할 때", avoidWhen: "modal 열기·복사·삭제처럼 URL 이동이 없는 동작일 때", tradeoffs: ["주소 복사·새 탭·history·keyboard 동작을 기본 제공받습니다.", "유효하고 안정적인 목적지 URL이 필요합니다.", "link 목적을 text로 설명해야 합니다."] },
            { name: "button", chooseWhen: "현재 문맥에서 상태를 바꾸거나 명령을 실행할 때", avoidWhen: "사용자가 bookmark하거나 공유할 수 있는 목적지로 이동할 때", tradeoffs: ["Space와 Enter 활성화, disabled 등 button behavior를 얻습니다.", "새 탭·주소 복사 같은 navigation 기능은 없습니다.", "form 안에서는 기본 submit이므로 type을 명시해야 합니다."] },
          ],
        },
      ],
    },
    {
      id: "url-parts-and-resolution",
      title: "href 문자열은 base URL과 결합되어 scheme부터 fragment까지 가진 최종 URL이 됩니다",
      lead: "상대경로를 외우기 전에 '현재 문서의 URL이 기준점이고 browser가 new URL(href, base)와 같은 방식으로 정규화한다'는 계산 모델을 고정합니다.",
      explanations: [
        "URL은 자원의 주소이면서 처리 규칙입니다. 예를 들어 https://learn.example:443/myweb/day02/links.html?mode=full#second에서 https는 scheme, learn.example은 host, 기본 443은 port, /myweb/day02/links.html은 path, mode=full은 query, second는 fragment입니다. scheme·host·port의 조합을 origin이라고 생각하면 same-origin 보안과 origin-root-relative 경로를 이해하기 쉽습니다.",
        "절대 URL은 scheme까지 포함해 기준점 없이 해석할 수 있습니다. 상대 URL은 non-null base URL이 필요하고, HTML link의 href는 보통 그 element가 속한 document URL을 기준으로 해석됩니다. `<base href>`가 있으면 document base URL이 달라질 수 있으므로, 눈에 보이는 현재 주소와 상대 link의 기준점이 달라지는 예외도 있습니다.",
        "path가 파일처럼 끝나는 base에서 `help.html`은 마지막 segment를 바꾸고, `../day01/page.html`은 현재 directory에서 한 단계 위로 정규화한 뒤 내려갑니다. `/myweb/day01/page.html`처럼 slash 하나로 시작하면 현재 origin의 root부터 시작합니다. `//cdn.example/file.css`는 scheme-relative URL이지만 HTTPS downgrade와 가독성 문제 때문에 보통 명시적 https URL을 선호합니다.",
        "query는 서버나 client가 읽을 변수를 표현하고 fragment는 일반 HTTP request body가 아니라 최종 문서 안의 위치·client state를 가리킵니다. `?page=2#result`에서 server는 query를 받지만 fragment는 browser가 같은 문서의 target 탐색 등에 사용합니다. URL 문자를 문자열 이어 붙이기로 만들면 encoding·slash·query 구분자가 쉽게 틀리므로 JavaScript에서는 URL과 URLSearchParams를 사용합니다.",
      ],
      concepts: [
        { term: "base URL", definition: "상대 URL을 완전한 URL로 해석할 때 사용하는 기준 URL입니다.", detail: ["보통 document URL에서 결정됩니다.", "base element가 있으면 많은 상대 URL의 기준이 한꺼번에 바뀝니다.", "file URL과 HTTP URL은 origin·path 동작이 달라 개발 server에서 확인하는 편이 안전합니다."] },
        { term: "absolute URL", definition: "scheme을 포함해 다른 기준 URL 없이도 해석할 수 있는 URL입니다.", detail: ["외부 site link와 canonical 식별에 유용합니다.", "host·환경이 바뀌면 하드코딩 수정 비용이 생깁니다."] },
        { term: "relative URL", definition: "base URL을 기준으로 path·query·fragment 일부를 채워 최종 URL을 만드는 참조입니다.", detail: ["document와 함께 이동하는 내부 자료에 유리합니다.", "현재 directory와 deployment base를 모르면 결과를 예측할 수 없습니다."] },
        { term: "origin", definition: "일반적인 HTTP(S) URL에서 scheme·host·port로 정해지는 보안 경계입니다.", detail: ["`/`는 filesystem root가 아니라 현재 origin의 URL root입니다.", "다른 path라도 같은 origin일 수 있고 같은 host라도 scheme·port가 다르면 다른 origin일 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "resolve-relative-urls",
          title: "URL API로 다섯 href의 최종 주소 계산",
          language: "javascript",
          filename: "resolve-links.mjs",
          purpose: "원본의 외부 URL, `/myweb`부터 시작하는 origin-root-relative URL, `../` 상대 URL, query·fragment를 한 기준 URL에서 실제로 정규화합니다.",
          code: "const base = new URL(\"https://learn.example/myweb/day02/ex01_a.html\");\n\nconst candidates = [\n  [\"external\", \"https://www.example.org/docs\"],\n  [\"origin-root\", \"/myweb/day01/ex02_hn.html\"],\n  [\"parent\", \"../day01/ex03_paragraphs.html\"],\n  [\"same-directory\", \"./help.html?from=links#faq\"],\n  [\"fragment\", \"#second\"],\n];\n\nfor (const [label, href] of candidates) {\n  console.log(label + \" -> \" + new URL(href, base).href);\n}",
          walkthrough: [
            { lines: "1", explanation: "실행 위치와 무관한 고정 HTTPS base를 만들어 결과를 재현 가능하게 합니다. base path의 마지막 segment는 현재 HTML 파일입니다." },
            { lines: "3-9", explanation: "scheme이 있는 외부 URL, origin root부터 시작하는 경로, 상위 directory 경로, 같은 directory의 query/fragment, 같은 문서 fragment를 비교합니다." },
            { lines: "11-13", explanation: "각 href를 같은 base와 URL parser에 전달하고 serializer가 만든 완전한 href를 출력합니다. 문자열 이어 붙이기와 달리 `..` 제거와 구분자 처리를 표준 parser에 맡깁니다." },
          ],
          run: { environment: ["Node.js 20 이상", "network 연결 불필요"], command: "node resolve-links.mjs" },
          output: {
            value: "external -> https://www.example.org/docs\norigin-root -> https://learn.example/myweb/day01/ex02_hn.html\nparent -> https://learn.example/myweb/day01/ex03_paragraphs.html\nsame-directory -> https://learn.example/myweb/day02/help.html?from=links#faq\nfragment -> https://learn.example/myweb/day02/ex01_a.html#second",
            explanation: ["scheme이 있는 external은 base를 사용하지 않습니다.", "slash로 시작한 origin-root는 host 뒤부터 대체하지만 `/myweb` context를 보존했습니다.", "`../`는 day02를 제거한 뒤 day01로 내려갑니다.", "`#second`는 기존 document path를 유지하고 fragment만 바꿉니다."],
          },
          experiments: [
            { change: "origin-root 값을 `/day01/ex02_hn.html`로 바꿉니다.", prediction: "결과에서 `/myweb`이 빠져 https://learn.example/day01/ex02_hn.html이 됩니다.", result: "server application이 `/myweb` 아래 배포되었다면 존재하지 않는 경로로 404가 날 수 있습니다." },
            { change: "base 끝의 ex01_a.html을 directory처럼 ex01_a.html/로 바꿉니다.", prediction: "relative path가 ex01_a.html 아래에서 계산되어 전혀 다른 URL이 됩니다.", result: "trailing slash는 URL parser가 마지막 segment를 file처럼 교체할지 directory로 유지할지 바꾸는 중요한 신호입니다." },
            { change: "same-directory의 공백 값을 URLSearchParams로 추가합니다.", prediction: "공백과 특수문자가 안전한 query encoding으로 직렬화됩니다.", result: "URL component를 수동 연결하기보다 표준 API를 사용해야 합니다." },
          ],
          sourceRefs: ["web-link-navigation-source", "whatwg-links", "whatwg-url"],
        },
      ],
      diagnostics: [
        {
          symptom: "링크 text는 맞지만 클릭하면 예상과 다른 directory로 이동하거나 URL에 `..`가 사라진 결과가 보인다.",
          likelyCause: "href 문자열만 보고 document base URL·trailing slash·base element를 고려하지 않았습니다.",
          checks: ["Elements에서 `getAttribute('href')` 원문과 element의 `.href` 완전 URL을 비교합니다.", "document.baseURI를 Console에서 확인합니다.", "Network의 실제 request URL을 봅니다.", "head의 base element와 redirect 후 최종 document URL을 확인합니다."],
          fix: "의도한 base를 기준으로 URL API로 결과를 먼저 계산하고, 내부 구조에 맞는 path-relative 또는 deployment-aware URL로 수정합니다.",
          prevention: "link fixture마다 base URL과 expected resolved URL을 test data로 두고 directory 이동·trailing slash 배포를 CI에서 검사합니다.",
        },
      ],
      comparisons: [
        {
          title: "목적지 주소를 어떤 형태로 적을까요?",
          options: [
            { name: "scheme 포함 absolute URL", chooseWhen: "다른 origin의 공식 문서처럼 목적지가 현재 배포 위치와 독립적일 때", avoidWhen: "dev·staging·production host가 달라지는 같은 site 내부 link일 때", tradeoffs: ["base와 무관해 해석이 분명합니다.", "환경·domain 변경에 취약합니다.", "외부 이동임을 사용자에게 알려야 할 수 있습니다."] },
            { name: "origin-root-relative /path", chooseWhen: "site가 항상 origin root 기준 같은 path에 배포될 때", avoidWhen: "GitHub Pages project site·reverse proxy context처럼 하위 base path에 배포될 때", tradeoffs: ["어느 깊이의 문서에서도 같은 URL이 됩니다.", "deployment prefix를 빠뜨리면 404가 납니다.", "host는 현재 origin을 재사용합니다."] },
            { name: "path-relative ../path", chooseWhen: "문서 묶음이 directory 구조를 유지한 채 함께 이동할 때", avoidWhen: "source file 위치와 public route가 다르거나 파일 이동이 잦을 때", tradeoffs: ["host와 deployment prefix를 자연스럽게 보존합니다.", "현재 document directory에 의존합니다.", "깊은 `../../../`는 유지보수가 어렵습니다."] },
          ],
        },
      ],
    },
    {
      id: "deployment-paths-and-context",
      title: "filesystem 경로와 public URL을 분리하고 배포 base path를 계약으로 관리합니다",
      lead: "원본의 `/day01/...`과 `/myweb/day01/...` 차이는 단순 오타가 아니라 web application context와 origin root를 혼동할 때 생기는 대표적인 운영 장애입니다.",
      explanations: [
        "원본 ex01_a.html은 `/day01/ex02_hn.html`을 절대경로라고 설명하지만, application이 `/myweb` context에 배포되었다면 browser는 origin root의 `/day01`을 요청합니다. ex02_a_color.html은 `/myweb/day01/ex02_hn.html`을 사용해 context를 포함합니다. 둘 중 어느 것이 맞는지는 source disk 위치가 아니라 실제 server가 외부에 공개한 route와 배포 context가 결정합니다.",
        "Windows의 drive·backslash path를 href에 복사하면 안 됩니다. URL path separator는 slash이고 browser에게 server 내부 source directory는 보이지 않습니다. `src/main/webapp/day01` 같은 build source가 배포 후 `/myweb/day01`이 될 수도 있고 framework router가 전혀 다른 route를 만들 수도 있습니다. source tree와 public URL mapping을 build·server 설정에서 확인합니다.",
        "GitHub Pages project site처럼 `https://account.example/project/` 아래 배포되는 site에서 `/assets/app.css`는 `https://account.example/assets/app.css`를 가리켜 project prefix를 잃습니다. static site generator의 basePath·asset prefix helper를 사용하거나, 문서 구조에 맞는 relative URL을 생성해야 합니다. user site root 배포와 project subpath 배포를 둘 다 test하면 이 오류를 빨리 찾을 수 있습니다.",
        "base element는 한 줄로 모든 relative URL의 기준을 바꿀 수 있지만 a뿐 아니라 img·script·form 등 URL attribute 전반에 영향을 줍니다. fragment link `#chapter`도 base가 외부 document를 가리키면 현재 문서가 아닌 base document로 이동할 수 있습니다. 문제를 감추려고 무조건 base를 추가하기보다 router·template에서 일관된 URL 생성 책임을 정합니다.",
        "percent-encoding과 Unicode도 경로 계약의 일부입니다. 한글 파일명이 browser에서 동작할 수 있어도 server normalization, case sensitivity, NFC/NFD, 대소문자 차이 때문에 Windows에서는 성공하고 Linux 배포에서 실패할 수 있습니다. public slug는 예측 가능한 lowercase ASCII와 hyphen 규칙을 두고 표시 제목과 분리하는 편이 운영에 유리합니다.",
      ],
      concepts: [
        { term: "context path", definition: "한 web application이 origin 안에서 차지하는 URL prefix입니다.", detail: ["예: /myweb", "server container·reverse proxy 설정에서 달라질 수 있습니다.", "filesystem directory 이름과 자동으로 같다고 가정하지 않습니다."] },
        { term: "deployment base path", definition: "정적 자원과 route URL을 생성할 때 공통으로 앞에 붙어야 하는 공개 배포 경로입니다.", detail: ["root 배포에서는 /일 수 있습니다.", "project page에서는 /project/일 수 있습니다.", "build-time config와 runtime proxy prefix를 구분합니다."] },
        { term: "URL normalization", definition: "parser가 dot segment·default port·encoding 등을 표준 형태로 정리해 URL record와 문자열을 만드는 과정입니다.", detail: ["source href와 DOM `.href`가 다르게 보일 수 있습니다.", "서버의 별도 normalization·redirect와 혼동하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "개발 server root에서는 link가 열리지만 `/myweb` 또는 project subpath에 배포하면 모든 내부 link·asset이 404가 된다.",
          likelyCause: "origin-root-relative URL이 deployment base prefix를 생략했거나 build가 root 배포를 가정했습니다.",
          checks: ["Network에서 실패 URL에 context prefix가 있는지 봅니다.", "브라우저 주소의 origin과 pathname을 분리해 적습니다.", "build 설정의 basePath·publicPath·assetPrefix를 확인합니다.", "직접 중첩 route URL을 새로 열어 server fallback과 static file mapping을 검사합니다."],
          fix: "framework의 URL helper나 중앙 base 설정으로 내부 route를 생성하고, server/reverse proxy의 public prefix와 일치시킵니다.",
          prevention: "preview를 production과 같은 subpath에서 실행하고 HTML의 href/src를 crawl해 2xx·허용된 redirect인지 검사합니다.",
        },
        {
          symptom: "Windows 개발 환경에서는 열리던 `Guide.HTML` link가 Linux 배포에서 404가 된다.",
          likelyCause: "파일명 대소문자 또는 Unicode normalization이 link와 실제 resource에서 다르고 개발 filesystem이 이를 관대하게 처리했습니다.",
          checks: ["Git에 기록된 정확한 filename과 href case를 비교합니다.", "배포 artifact 목록을 확인합니다.", "percent-decoded path와 server log path를 비교합니다.", "rename이 case-only였는지 확인합니다."],
          fix: "public filename·slug 규칙을 lowercase ASCII로 통일하고 link와 artifact 이름을 같은 commit에서 수정합니다.",
          prevention: "case-sensitive 환경의 build·link checker를 CI에 포함하고 route 이름을 문자열로 흩뿌리지 않습니다.",
        },
      ],
      expertNotes: ["SSR framework의 Link component는 prefetch·client navigation을 제공할 수 있지만 최종 렌더링이 유효한 href를 가진 a인지 확인해야 합니다. component를 썼다는 사실이 배포 base 정확성을 보장하지 않습니다.", "CDN·reverse proxy가 trailing slash redirect나 URL rewrite를 수행하면 relative resolution의 base document URL도 바뀔 수 있습니다. canonical 정책과 redirect 뒤 최종 URL을 통합 test합니다."],
    },
    {
      id: "fragment-navigation",
      title: "#fragment는 새 파일이 아니라 문서의 고유 id를 target으로 만드는 주소입니다",
      lead: "긴 문서의 heading에 id를 붙이고 목차에서 그 id를 참조하면 URL 자체가 공유 가능한 독서 위치가 됩니다.",
      explanations: [
        "URL의 `#second`는 fragment identifier입니다. HTML에서 일반적으로 같은 값의 id를 가진 element가 target이 되고 browser가 그 위치로 scroll합니다. CSS `:target`은 현재 URL이 가리키는 element를 선택하므로 목적지를 시각적으로 강조할 수 있습니다. fragment만 다른 navigation은 보통 전체 document를 다시 내려받지 않지만 history와 scroll 위치는 바뀔 수 있습니다.",
        "원본은 `<h2><a id='first'>첫번째 섹터</a></h2>`처럼 빈 a를 목적지 표식으로 넣었습니다. modern HTML에서는 `<h2 id='first'>첫 번째 섹션</h2>`처럼 의미 있는 destination 자체에 global id를 붙이는 편이 단순합니다. heading을 클릭할 link로 오해할 placeholder가 사라지고 accessibility tree와 `:target` style 대상도 분명해집니다.",
        "id는 문서 안에서 고유해야 하며 link의 fragment와 철자·대소문자·encoding이 맞아야 합니다. 존재하지 않는 id면 URL hash는 바뀌어도 기대한 위치로 이동하지 않습니다. 자동 생성 heading slug는 제목 변경 때 permalink가 깨질 수 있으므로 공개된 id를 안정된 API처럼 관리하고, 변경 시 이전 fragment 호환 anchor나 redirect 전략을 고려합니다.",
        "원본의 href=#은 빈 fragment로 현재 문서를 가리키며 흔히 위쪽으로 이동하지만 '맨 위'라는 목적지를 명시하지 않습니다. `<header id='top'>`과 href=#top처럼 실제 target을 연결하면 intent와 test가 선명합니다. JavaScript 실행을 위한 가짜 href=# 또는 href=javascript:...는 history·scroll·보안·keyboard 문제를 만들므로 button으로 바꿉니다.",
        "fixed header가 target heading을 가리면 destination에 scroll-margin-top을 둡니다. smooth scrolling은 선호에 따라 motion sickness를 줄이도록 `prefers-reduced-motion`을 존중해야 합니다. fragment 이동이 항상 keyboard focus를 업무 흐름에 맞게 옮겨 주는 것은 아니므로 SPA가 client-side로 main content를 바꾸는 경우 heading focus·skip link 동작을 별도로 설계하고 시험합니다.",
      ],
      concepts: [
        { term: "fragment identifier", definition: "URL의 # 뒤에 붙어 자원 내부의 특정 부분이나 client-side 상태를 식별하는 문자열입니다.", detail: ["HTTP request target의 query와 다른 역할입니다.", "HTML에서는 같은 id의 target element 탐색에 주로 사용합니다.", "bookmark·공유 가능한 깊은 위치를 만듭니다."] },
        { term: ":target", definition: "현재 document URL의 fragment가 가리키는 target element에 match하는 CSS pseudo-class입니다.", detail: ["fragment가 없으면 target element도 없습니다.", "강조 style과 scroll 위치 보완에 사용할 수 있습니다.", "focus pseudo-class와 동일하지 않습니다."] },
        { term: "permalink", definition: "내용이 바뀌어도 가능한 한 오래 유지되는 특정 문서 또는 section의 안정적인 URL입니다.", detail: ["heading id는 public API처럼 관리합니다.", "제목 표시 문자열과 id slug를 분리할 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "fragment-table-of-contents",
          title: "고유 id·:target·명시적 top target을 가진 문서 목차",
          language: "html",
          filename: "fragment-navigation.html",
          purpose: "원본의 빈 a destination과 href=#을 modern heading id와 명시적 #top으로 바꾸고, URL hash와 실제 target을 console에서 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>링크 학습 목차</title>\n  <style>\n    html { scroll-behavior: smooth; }\n    section { min-height: 55vh; scroll-margin-top: 1rem; padding: 1rem; }\n    :target { background: #fff4c2; border-inline-start: 0.35rem solid #8a5a00; }\n    a:focus-visible { outline: 0.2rem solid #005fcc; outline-offset: 0.2rem; }\n    @media (prefers-reduced-motion: reduce) { html { scroll-behavior: auto; } }\n  </style>\n</head>\n<body>\n  <header id=\"top\">\n    <h1>URL과 링크</h1>\n  </header>\n  <nav aria-label=\"이 문서의 목차\">\n    <a href=\"#url-parts\">URL 구성</a>\n    <a href=\"#relative-path\">상대 경로</a>\n  </nav>\n  <main>\n    <section id=\"url-parts\">\n      <h2>URL 구성</h2>\n      <p>scheme, host, path, query, fragment를 구분합니다.</p>\n      <a href=\"#top\">문서 맨 위로</a>\n    </section>\n    <section id=\"relative-path\">\n      <h2>상대 경로</h2>\n      <p>base URL과 href로 최종 URL을 계산합니다.</p>\n      <a href=\"#top\">문서 맨 위로</a>\n    </section>\n  </main>\n  <script>\n    const target = document.querySelector(location.hash);\n    console.log(\"hash=\" + location.hash);\n    console.log(\"target=\" + target.id);\n    console.log(\"heading=\" + target.querySelector(\"h2\").textContent);\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "1-17", explanation: "표준 문서와 :target 강조, keyboard focus 표시, reduced motion override를 준비합니다. scroll-margin-top은 target이 고정 header에 가리는 상황에도 적용할 수 있습니다." },
            { lines: "19-26", explanation: "top이라는 실제 destination을 header에 두고 nav에 목적을 설명하는 aria-label과 두 fragment link를 둡니다." },
            { lines: "27-39", explanation: "각 section 자체에 unique id를 붙입니다. 빈 a를 target 표식으로 추가하지 않고 heading이 포함된 의미 단위를 직접 target으로 만듭니다." },
            { lines: "40-46", explanation: "실행 URL의 hash로 target element를 찾고 id와 h2 text를 안정된 문자열로 출력합니다. 실행 명령에 fragment를 반드시 포함하므로 null이 아닙니다." },
          ],
          run: { environment: ["Python 3의 간단한 HTTP server", "현대 browser와 DevTools Console"], command: "fragment-navigation.html이 있는 폴더에서 `python -m http.server 8000` 실행 후 browser로 http://localhost:8000/fragment-navigation.html#relative-path 열기" },
          output: {
            value: "hash=#relative-path\ntarget=relative-path\nheading=상대 경로",
            explanation: ["주소의 fragment가 그대로 location.hash가 됩니다.", "같은 id의 section이 target이며 :target style로 강조되고 해당 위치로 이동합니다.", "target 안 h2 text가 '상대 경로'여서 URL만 공유해도 독자는 도착 위치의 문맥을 즉시 알 수 있습니다."],
          },
          experiments: [
            { change: "두 번째 section id를 `relative-path-new`로 바꾸고 nav href는 그대로 둡니다.", prediction: "hash는 #relative-path로 남지만 target을 찾지 못해 script가 오류를 내고 section 강조·이동도 실패합니다.", result: "fragment와 id는 함께 변경해야 하는 참조 무결성 계약입니다." },
            { change: "URL의 fragment를 #top으로 바꿉니다.", prediction: "header가 target이 되어 문서 맨 위로 이동하고 console script는 h2가 없어 마지막 줄에서 오류가 납니다.", result: "실제 navigation은 성공해도 진단 script가 특정 target 구조를 가정했음을 발견합니다. production script라면 optional check가 필요합니다." },
            { change: "reduced motion OS 설정을 켭니다.", prediction: "media query가 smooth를 auto로 덮어 즉시 이동합니다.", result: "동일한 semantic navigation을 유지하면서 motion 선호를 존중할 수 있습니다." },
          ],
          sourceRefs: ["web-link-navigation-source", "css-selectors", "whatwg-url"],
        },
      ],
      diagnostics: [
        {
          symptom: "목차를 누르면 주소에 hash는 붙지만 화면이 움직이지 않거나 엉뚱한 section이 강조된다.",
          likelyCause: "destination id가 없거나 중복되었고, generated slug와 href가 달라졌을 수 있습니다.",
          checks: ["Console에서 `document.getElementById(location.hash.slice(1))` 결과를 확인합니다.", "validator와 `[id]` 목록으로 duplicate id를 찾습니다.", "percent-decoded fragment와 실제 id의 대소문자를 비교합니다.", "fixed header가 target을 가리는지 확인합니다."],
          fix: "의미 있는 destination element에 unique·stable id를 두고 모든 href를 같은 값으로 갱신하며 필요하면 scroll-margin-top을 적용합니다.",
          prevention: "build 시 heading id 중복과 내부 fragment 존재를 검사하고 공개 permalink id 변경을 review 항목으로 둡니다.",
        },
      ],
    },
    {
      id: "target-and-browsing-context",
      title: "target은 문서 속 위치가 아니라 어느 browsing context를 navigate할지 고릅니다",
      lead: "원본 주석의 target name을 같은 페이지의 anchor로 이해하면 안 됩니다. 페이지 내부 위치는 fragment이고, target name은 창·탭·iframe 같은 navigable의 이름입니다.",
      explanations: [
        "target을 생략하거나 `_self`를 쓰면 현재 browsing context가 이동합니다. `_blank`는 새 top-level context를 요청하고 browser 설정에 따라 새 탭 또는 창으로 보일 수 있습니다. `_parent`는 현재 iframe의 parent, `_top`은 최상위 context를 대상으로 하며 frame 안이 아니면 결과가 `_self`와 같을 수 있습니다.",
        "underscore가 없는 `lesson-preview` 같은 이름은 같은 이름의 browsing context를 찾거나 만듭니다. 여러 link가 같은 named target을 사용하면 매번 새 탭을 늘리지 않고 그 context를 재사용할 수 있지만, 사용자가 이전 내용을 읽고 있던 탭을 예상치 못하게 바꿀 수 있습니다. window name과 same-origin 접근 정책까지 얽히므로 명확한 요구가 없으면 기본 `_self`가 가장 예측 가능합니다.",
        "새 탭은 사용자의 선택권을 줄일 수 있습니다. 사용자는 원하면 Ctrl/Command+click, middle click, context menu로 스스로 새 탭을 열 수 있습니다. 업무 흐름상 외부 문서를 유지해야 해 `_blank`를 선택했다면 link text 또는 접근 가능한 설명으로 '새 탭'을 미리 알리고, 열린 뒤 Back button이 이전 문맥으로 돌아가지 않는다는 차이를 시험합니다.",
        "download attribute는 navigation 대신 download 의도를 전달하고 filename hint를 줄 수 있지만 browser·origin·response header 정책의 영향을 받습니다. 새 탭을 파일 download 대용으로 쓰지 말고 의도를 명시합니다. 반대로 POST·데이터 변경을 link GET navigation으로 만들면 crawler·prefetch가 의도치 않은 동작을 일으킬 수 있으므로 form/button과 HTTP method 의미를 지킵니다.",
      ],
      concepts: [
        { term: "browsing context", definition: "Document가 표시되고 navigation history를 갖는 tab·window·frame 계열 환경을 이해하기 위한 모델입니다.", detail: ["target이 어떤 context를 선택할지 지정합니다.", "same-page fragment destination과 다른 개념입니다."] },
        { term: "named target", definition: "특정 이름을 가진 browsing context를 만들거나 재사용하도록 하는 target 값입니다.", detail: ["fragment id와 연결되지 않습니다.", "같은 이름의 link는 하나의 context를 반복 사용할 수 있습니다.", "재사용이 사용자 기대와 맞는지 검토합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "target='preview'를 썼는데 현재 페이지의 id='preview' section으로 이동하지 않고 별도 탭이 열리거나 기존 탭이 바뀐다.",
          likelyCause: "target의 named browsing context와 href fragment의 document target을 혼동했습니다.",
          checks: ["href에 #preview가 있는지 확인합니다.", "target 값을 제거하고 `_self` 동작을 비교합니다.", "같은 이름을 쓰는 다른 link·iframe name을 찾습니다.", "열린 window/tab의 이름 재사용을 관찰합니다."],
          fix: "같은 문서 section 이동이면 href=#preview와 destination id만 사용하고 target을 제거합니다. 별도 context가 정말 필요할 때만 설명적인 target name을 사용합니다.",
          prevention: "코드 review에서 href fragment·element id·target context 세 용어를 분리해 기록하고, 자동 test에서 열린 page 수와 URL을 함께 단언합니다.",
        },
      ],
      comparisons: [
        {
          title: "navigation context를 어떻게 선택할까요?",
          options: [
            { name: "기본값 또는 _self", chooseWhen: "일반적인 문서·route 이동이며 사용자가 browser history로 돌아올 수 있을 때", avoidWhen: "명시적으로 별도 보조 문맥을 유지해야 하는 검증된 workflow일 때", tradeoffs: ["가장 예측 가능하고 Back button이 자연스럽습니다.", "현재 문서를 대체합니다.", "사용자는 원하면 직접 새 탭을 선택할 수 있습니다."] },
            { name: "_blank", chooseWhen: "별도 문맥이 업무상 필요하고 새 탭 알림·보안 속성·test를 제공할 때", avoidWhen: "단순 외부 link라는 이유만으로 모든 이동을 강제할 때", tradeoffs: ["현재 문맥을 유지합니다.", "focus와 tab 전환이 혼란스러울 수 있습니다.", "opener·referrer 정책을 검토해야 합니다."] },
            { name: "named target", chooseWhen: "하나의 preview/help context를 의도적으로 재사용하는 UI일 때", avoidWhen: "사용자가 여러 결과를 동시에 비교해야 하거나 name 충돌 가능성이 있을 때", tradeoffs: ["탭 폭증을 줄일 수 있습니다.", "기존 tab content를 예고 없이 교체할 수 있습니다.", "frame·window name 관리 비용이 있습니다."] },
          ],
        },
      ],
    },
    {
      id: "external-link-security-and-privacy",
      title: "새 context와 외부 URL은 opener·referrer·허용 scheme을 분리해 위협 모델링합니다",
      lead: "target=_blank에 문자열 하나를 더 붙이는 암기보다, 새 문서가 원래 window를 제어할 수 있는지와 현재 URL 정보가 어디까지 전달되는지를 각각 판단합니다.",
      explanations: [
        "noopener link type은 새 top-level context가 opener 관계를 갖지 않게 합니다. 현재 WHATWG 처리 모델은 rel=opener가 없고 target이 `_blank`이면 noopener로 취급하지만, 명시적 rel=noopener는 작성 의도를 드러내고 오래된 환경·코드 변환을 고려한 방어적 표기입니다. '최신 browser가 알아서 하므로 절대 필요 없다' 또는 '없으면 모든 browser에서 반드시 취약하다'는 식의 단정 대신 지원 범위와 생성된 최종 HTML을 확인합니다.",
        "opener가 남은 새 page가 `window.opener.location`을 바꾸면 사용자가 원래 tab으로 돌아왔을 때 피싱 page를 볼 수 있는 reverse tabnabbing 시나리오가 생깁니다. same-origin policy가 모든 navigation assignment를 막는다고 가정하면 안 됩니다. 외부·사용자 제공 destination은 새 context 관계를 최소화하고, server의 redirect destination도 검증합니다.",
        "noreferrer는 link를 따라갈 때 referrer 정보를 보내지 않도록 하며 같은 조건에서 noopener behavior도 함축합니다. 그러나 analytics·제휴·보안 감사에 필요한 유입 origin 정보도 사라질 수 있습니다. opener 차단만 필요하면 noopener, referrer까지 숨겨야 할 privacy 요구가 있으면 noreferrer 또는 적절한 referrerpolicy를 선택합니다.",
        "referrerpolicy는 no-referrer, origin, strict-origin-when-cross-origin 등 전송 범위를 link별로 조절할 수 있습니다. 기본 정책과 HTTPS→HTTP downgrade, same-origin/cross-origin을 함께 이해해야 합니다. URL query에 token·이메일·검색어 같은 민감정보를 넣으면 referrer뿐 아니라 history·log·screenshot에 남을 수 있으므로 애초에 민감정보를 URL에 싣지 않는 설계가 우선입니다.",
        "사용자 입력을 그대로 href에 넣으면 `javascript:` 같은 실행 scheme, phishing host, protocol confusion, open redirect가 생길 수 있습니다. URL parser로 해석한 뒤 허용 scheme을 https:로 제한하고 필요한 경우 host allowlist를 적용합니다. text escaping만으로 URL 의미 검증이 끝나지 않으며, display text와 실제 href host가 다른 deceptive link도 review합니다.",
      ],
      concepts: [
        { term: "opener", definition: "새 browsing context가 자신을 연 context를 참조하는 관계입니다.", detail: ["필요하지 않으면 끊어 공격 표면을 줄입니다.", "noopener는 referrer 억제와 동일하지 않습니다.", "현재 표준의 _blank 암묵 동작과 명시적 rel의 의도 표현을 구분합니다."] },
        { term: "referrer", definition: "navigation request가 어디에서 시작되었는지 destination에 전달할 수 있는 URL 관련 정보입니다.", detail: ["policy에 따라 전체 URL·origin·없음으로 달라질 수 있습니다.", "privacy와 analytics 사이의 trade-off가 있습니다.", "민감정보를 URL에 넣지 않는 것이 먼저입니다."] },
        { term: "URL allowlist", definition: "사용자·외부 data에서 만든 link가 허용된 scheme과 선택적으로 host만 사용하도록 제한하는 정책입니다.", detail: ["parse 성공만으로 안전한 목적지라는 뜻은 아닙니다.", "redirect chain과 IDN 표시도 위협 model에 포함할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "외부 새 탭을 닫고 원래 탭으로 돌아왔는데 원래 site가 login page처럼 보이는 다른 주소로 바뀌어 있다.",
          likelyCause: "새 context가 opener를 통해 원래 window를 navigate했거나 중간 redirect·script가 opener 관계를 악용했습니다.",
          checks: ["최종 렌더링된 a의 target·rel을 확인합니다.", "새 page console에서 window.opener가 null인지 허용된 test destination으로 확인합니다.", "redirect chain과 third-party destination ownership을 검토합니다.", "Content Security Policy와 legacy browser 지원 범위를 확인합니다."],
          fix: "필요한 `_blank` link에 rel=noopener를 명시하고 새 tab이 필요하지 않으면 `_self`로 되돌립니다. 사용자 제공 URL은 scheme·host 정책으로 제한합니다.",
          prevention: "외부 link component에 safe default와 새 탭 고지를 중앙화하고, rendered HTML security test에서 target/rel 조합을 검사합니다.",
        },
        {
          symptom: "외부 analytics에서 유입 page를 전혀 알 수 없거나 반대로 민감한 query가 destination log에 노출된다.",
          likelyCause: "noreferrer·referrerpolicy를 목적 없이 복사했거나 URL 자체에 민감정보를 포함했습니다.",
          checks: ["Network request의 Referer header를 same-origin·cross-origin에서 비교합니다.", "link의 rel과 referrerpolicy, page-level policy를 확인합니다.", "redirect 각 hop에서 header를 검사합니다.", "source URL query에 개인정보·token이 있는지 점검합니다."],
          fix: "privacy 요구에 맞는 최소 referrer policy를 선택하고 민감정보를 URL에서 제거합니다. opener 차단만 필요하면 noreferrer가 아닌 noopener를 고려합니다.",
          prevention: "privacy data flow 문서에 URL·referrer·analytics 필드를 기록하고 실제 browser integration test로 policy를 검증합니다.",
        },
      ],
      comparisons: [
        {
          title: "새 탭 link의 rel 정책은 어떻게 고를까요?",
          options: [
            { name: "noopener", chooseWhen: "opener 관계만 차단하고 정상 referrer 정책은 유지하고 싶을 때", avoidWhen: "destination에 referrer 자체를 보내면 안 되는 privacy 요구가 있을 때", tradeoffs: ["원래 context 제어 위험을 줄입니다.", "referrer는 별도 policy에 따라 전달될 수 있습니다.", "현재 표준의 암묵 동작과 별개로 의도를 명시합니다."] },
            { name: "noreferrer", chooseWhen: "destination에 referrer 정보를 전달하지 않아야 하고 opener도 끊고 싶을 때", avoidWhen: "유입 분석·제휴·감사에 referrer가 필요한데 대체 신호가 없을 때", tradeoffs: ["referrer 억제와 noopener behavior를 함께 제공합니다.", "analytics 정보가 줄어듭니다.", "privacy 요구가 명확할 때 선택합니다."] },
            { name: "referrerpolicy", chooseWhen: "origin만 전송하는 등 link별로 referrer 범위를 세밀하게 제어할 때", avoidWhen: "opener 차단까지 자동으로 된다고 기대할 때", tradeoffs: ["privacy·분석 요구를 세밀하게 조정합니다.", "정책 조합과 browser request를 test해야 합니다.", "noopener와 독립 축입니다."] },
          ],
        },
      ],
      expertNotes: ["URL sanitizer는 HTML escaping과 다른 계층입니다. DOM에 안전하게 넣었어도 javascript:·data:·open redirect destination이 business policy에 맞는지 별도 검증합니다.", "CSP의 navigate-to 지원 상태나 frame sandbox만 믿지 말고 link 생성 지점의 allowlist, redirect validation, opener 관계, server header를 defense in depth로 결합합니다."],
    },
    {
      id: "link-states-and-visible-affordance",
      title: "link·visited·hover·active에 focus-visible과 비색상 단서를 더해 모든 입력 방식에서 상태를 보입니다",
      lead: "원본 CSS의 밑줄 제거와 hover 색 변경은 mouse 화면만 설명합니다. link라는 사실과 keyboard focus를 색 하나에만 의존하지 않도록 확장해야 합니다.",
      explanations: [
        "CSS Selectors에서 :link는 방문하지 않은 hyperlink, :visited는 방문한 hyperlink에 match하며 두 상태는 배타적입니다. browser는 history privacy를 보호하기 위해 :visited style과 script 관찰을 제한할 수 있고 시간이 지나 visited를 unvisited로 되돌릴 수도 있습니다. 따라서 visited 여부를 application state나 권한 판단에 사용하면 안 됩니다.",
        ":hover는 pointing device가 element를 가리키는 동안이고 touch·keyboard 환경에서는 없거나 다르게 동작할 수 있습니다. :active는 link가 활성화되는 짧은 순간, 예를 들어 pointer를 누르고 있는 동안입니다. :focus는 keyboard 등 입력을 받을 focus 상태이고 :focus-visible은 user agent가 focus indicator가 필요하다고 판단하는 경우를 목표로 합니다. hover만 style하면 keyboard 사용자는 현재 위치를 잃습니다.",
        "원본은 모든 a의 text-decoration을 none으로 지우고 hover에서 tomato 색만 줍니다. 본문 link의 밑줄을 제거하면 색각 차이·낮은 대비·흑백 인쇄에서 일반 text와 구분되지 않을 수 있습니다. navigation menu처럼 위치·모양으로 link임이 분명한 경우와 본문 inline link를 구분하고, 밑줄 thickness·offset·focus outline 등 비색상 단서를 유지합니다.",
        "LVHA라는 link→visited→hover→active 순서는 같은 specificity rule이 cascade에서 의도대로 덮도록 기억하는 학습 도구입니다. 그러나 focus-visible도 반드시 포함하고 component layer·specificity·cascade layer를 함께 확인해야 합니다. source 순서 암기만으로 모든 design system conflict가 해결되지는 않습니다.",
        ":target은 현재 URL fragment의 destination, :focus-visible은 현재 keyboard focus, :active는 활성화 순간이므로 서로 바꿀 수 없습니다. 목차를 클릭한 뒤 target section을 강조하고 focus는 link에 남을 수 있습니다. 각 state가 무엇을 표현하는지 먼저 정한 뒤 style을 다르게 설계합니다.",
      ],
      concepts: [
        { term: ":link / :visited", definition: "hyperlink의 방문 history에 따라 나뉘는 mutually exclusive pseudo-class입니다.", detail: ["privacy 때문에 visited 관찰이 제한됩니다.", "핵심 기능 state 저장에 사용하지 않습니다.", "visited 차이는 사용자 orientation을 도울 수 있습니다."] },
        { term: ":hover / :active", definition: "pointer가 가리키는 상태와 element가 활성화되는 순간을 각각 표현합니다.", detail: ["hover가 없는 device가 있습니다.", "active는 current page를 뜻하지 않습니다.", "keyboard state는 focus로 따로 처리합니다."] },
        { term: ":focus-visible", definition: "focus indicator가 사용자에게 유용하다고 user agent가 판단한 focus 상태를 style하기 위한 pseudo-class입니다.", detail: ["outline 제거만 하지 않습니다.", "keyboard Tab 순서를 실제로 시험합니다.", "브라우저 기본 focus style도 안전한 출발점입니다."] },
      ],
      codeExamples: [
        {
          id: "semantic-links-and-states",
          title: "본문 link·동작 button·안전한 새 탭 link와 상태 style",
          language: "html",
          filename: "link-states.html",
          purpose: "원본의 link state CSS를 keyboard focus와 밑줄까지 확장하고, link와 button 및 target/rel 정보를 정확한 console 출력으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>링크 상태 점검</title>\n  <style>\n    a:any-link { color: #0645ad; text-decoration-thickness: 0.12em; text-underline-offset: 0.18em; }\n    a:visited { color: #5a2a82; }\n    a:hover { color: #a43d00; text-decoration-thickness: 0.2em; }\n    a:focus-visible, button:focus-visible { outline: 0.2rem solid #005fcc; outline-offset: 0.2rem; }\n    a:active { color: #8b0000; }\n  </style>\n</head>\n<body>\n  <p><a id=\"internal\" href=\"./html-intro.html\">HTML 문서 구조</a></p>\n  <p><button id=\"run\" type=\"button\">예제 실행</button></p>\n  <p><a id=\"standard\" href=\"https://html.spec.whatwg.org/multipage/links.html\" target=\"_blank\" rel=\"noopener\">WHATWG 링크 표준 (새 탭)</a></p>\n  <script>\n    const internal = document.querySelector(\"#internal\");\n    const run = document.querySelector(\"#run\");\n    const standard = document.querySelector(\"#standard\");\n    console.log(internal.textContent + \" | element=\" + internal.tagName + \" | target=\" + (internal.target || \"_self\") + \" | rel=\" + (internal.getAttribute(\"rel\") || \"(없음)\"));\n    console.log(run.textContent + \" | element=\" + run.tagName + \" | type=\" + run.type);\n    console.log(standard.textContent + \" | element=\" + standard.tagName + \" | target=\" + standard.target + \" | rel=\" + standard.rel);\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "5-11", explanation: "모든 href link의 기본 밑줄을 유지하고 visited·hover·active를 구분합니다. keyboard focus에는 색 변화만이 아닌 두꺼운 outline을 둡니다." },
            { lines: "14-16", explanation: "주소 이동은 a, 현재 화면의 실행 동작은 type=button, 새 탭 외부 link는 목적을 text로 알리고 rel=noopener를 명시합니다." },
            { lines: "17-24", explanation: "DOM tagName·target·rel·button type을 문자열로 출력해 시각 style과 semantic element가 별도 축임을 확인합니다." },
          ],
          run: { environment: ["현대 browser", "DevTools Console", "Tab key와 pointer"], command: "browser에서 link-states.html을 열고 Console을 확인한 뒤 Tab·hover·mouse down 상태를 비교" },
          output: {
            value: "HTML 문서 구조 | element=A | target=_self | rel=(없음)\n예제 실행 | element=BUTTON | type=button\nWHATWG 링크 표준 (새 탭) | element=A | target=_blank | rel=noopener",
            explanation: ["target을 생략한 내부 a는 DOM property 기준 `_self`로 해석됩니다.", "예제 실행은 URL 목적지가 없으므로 BUTTON이며 form 오작동을 막도록 type=button입니다.", "외부 표준 link는 새 탭 고지를 이름에 포함하고 명시적 noopener 관계를 가집니다.", "visited 색은 browser history와 privacy 정책에 따라 달라질 수 있으므로 console의 exact output에는 포함하지 않았습니다."],
          },
          experiments: [
            { change: "a:focus-visible rule을 제거하고 Tab으로 이동합니다.", prediction: "browser 기본 outline이 남으면 보이지만 다른 reset CSS까지 outline을 없앴다면 현재 focus를 찾기 어려워집니다.", result: "focus indicator는 hover color와 별도 요구사항이며 reset 뒤 실제 page에서 검사해야 합니다." },
            { change: "본문 a:any-link의 text-decoration을 none으로 바꾸고 grayscale로 봅니다.", prediction: "link와 일반 text 구분이 약해집니다.", result: "색 하나에 의존하지 않는 밑줄·형태 단서가 필요합니다." },
            { change: "WHATWG link의 target을 제거합니다.", prediction: "현재 tab에서 이동하고 browser Back으로 돌아올 수 있습니다.", result: "기본 `_self`가 더 예측 가능한 경우가 많고 새 tab은 요구가 있을 때만 선택합니다." },
          ],
          sourceRefs: ["web-link-color-source", "css-selectors", "whatwg-a-element", "w3c-new-window-warning"],
        },
      ],
      diagnostics: [
        {
          symptom: "mouse를 올리면 link가 잘 보이지만 Tab 사용자는 현재 focus 위치를 찾을 수 없다.",
          likelyCause: "hover만 style했고 global reset에서 outline을 제거했으며 focus-visible 대체 표시가 없습니다.",
          checks: ["mouse를 치우고 Tab·Shift+Tab으로 모든 link를 순회합니다.", "computed style에서 outline·box-shadow·contrast를 봅니다.", "hover가 없는 touch emulation을 시험합니다.", "본문 link가 색 외 형태로 구분되는지 grayscale에서 확인합니다."],
          fix: "명확한 focus-visible outline을 복원하고 본문 link 밑줄 또는 동등한 비색상 단서를 유지합니다.",
          prevention: "design token에 hover·active뿐 아니라 focus indicator를 포함하고 keyboard·high contrast·zoom QA를 release gate에 둡니다.",
        },
        {
          symptom: "JavaScript로 모든 link의 visited 여부를 읽어 개인화하려 했지만 computed color가 같거나 정보가 노출되지 않는다.",
          likelyCause: ":visited는 browsing history 유출을 막기 위해 browser가 적용 property와 script 관찰을 의도적으로 제한합니다.",
          checks: ["Selectors 표준의 visited privacy 요구를 확인합니다.", "application 완료 상태와 browser visit history를 분리합니다.", "로그인 사용자 state가 server/DB에 있는지 봅니다."],
          fix: "학습 완료 같은 product state는 인증된 application data와 class/attribute로 표현하고 :visited는 보조적인 navigation history style로만 사용합니다.",
          prevention: "privacy-protected browser state를 business logic 입력으로 사용하지 않는 원칙을 architecture 문서에 둡니다.",
        },
      ],
    },
    {
      id: "link-purpose-and-document-navigation",
      title: "링크 이름은 목적지를 설명하고 문서 구조는 중간 URL에서도 문맥을 복구시킵니다",
      lead: "사용자는 문단 전체를 순서대로 읽지 않고 link 목록·검색 결과·목차만 훑을 수 있으므로 '앞에서 설명했으니 여기라고 써도 된다'고 가정하지 않습니다.",
      explanations: [
        "WCAG 2.2의 Link Purpose (In Context)는 사용자가 link를 따를지 판단하도록 목적을 이해할 수 있어야 한다는 취지입니다. 가능하면 link text 자체가 목적을 식별하게 합니다. screen reader 사용자는 page의 link만 모아 탐색할 수 있으므로 '여기', '자세히', '클릭'이 반복되면 각 link를 구분하기 어렵습니다.",
        "`상대 URL 계산 예제 보기`처럼 목적과 대상을 함께 쓰고, 파일 형식·언어·새 탭·download처럼 결정에 영향을 주는 변화가 있으면 보이는 text와 accessible description으로 알립니다. title attribute만 추가하는 방식은 touch·keyboard·보조기술에서 일관되게 노출되지 않으므로 핵심 정보의 유일한 전달 수단으로 삼지 않습니다.",
        "현재 page를 navigation에서 표시할 때 link를 제거할 수도 있고 href를 유지한 채 aria-current=page를 사용할 수도 있습니다. aria-current는 현재 위치를 알려 주지만 link 목적이나 visual style을 자동 생성하지 않습니다. breadcrumb·목차·pagination에서는 page·step·location 중 의미에 맞는 값을 고르고 현재 항목을 색 하나로만 구분하지 않습니다.",
        "image-only link는 img alt가 link 목적을 설명하도록 하고 장식 icon은 빈 alt 또는 aria-hidden으로 중복 낭독을 피합니다. external icon의 시각 모양만으로 새 탭을 알리면 screen reader에 정보가 빠지므로 text 또는 aria-describedby를 제공합니다. 반대로 accessible name을 화면 text와 전혀 다르게 만들면 speech input 사용자가 보이는 이름으로 control을 찾기 어려워집니다.",
        "fragment로 직접 들어온 독자는 앞 section을 읽지 않았을 수 있습니다. 각 section heading은 주제를 독립적으로 설명하고 필요한 선수 개념에는 실제 link를 제공합니다. 긴 문서에 nav landmark와 skip link, heading hierarchy, '맨 위로'의 명시적 target을 두면 부분 읽기와 전체 흐름을 모두 지원합니다.",
      ],
      concepts: [
        { term: "link purpose", definition: "사용자가 link를 활성화했을 때 어디로 가고 무엇을 얻게 되는지 판단할 수 있는 의미입니다.", detail: ["text만으로 명확하게 하는 것이 가장 견고합니다.", "programmatically determined context도 기준에 포함될 수 있습니다.", "새 window·file type 등 예상 밖 변화도 필요한 만큼 알립니다."] },
        { term: "aria-current", definition: "관련 항목 집합에서 현재 page·step·location 등을 보조기술에 알리는 ARIA state입니다.", detail: ["현재 navigation item에 사용합니다.", "href와 독립적입니다.", "시각적인 현재 표시도 함께 설계합니다."] },
        { term: "deep link", definition: "site root가 아니라 특정 route·document section·application state로 직접 들어가는 URL입니다.", detail: ["중간 진입에도 heading과 context가 필요합니다.", "server route fallback과 authorization도 별도로 검증합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "screen reader link 목록에 '자세히'가 여러 번 반복되어 어느 주제의 link인지 구분할 수 없다.",
          likelyCause: "시각적으로 가까운 card나 paragraph 문맥에만 의존하고 link text 자체에는 목적을 넣지 않았습니다.",
          checks: ["browser accessibility tree 또는 screen reader link list로 이름만 추출합니다.", "같은 accessible name을 가진 서로 다른 href를 찾습니다.", "icon-only link의 alt·aria-label·aria-describedby를 확인합니다.", "새 탭·download 정보를 visual과 spoken 방식 모두에서 확인합니다."],
          fix: "각 link 이름을 'URL 경로 진단 읽기', 'fragment 실습 파일 다운로드'처럼 목적·대상 중심으로 다시 씁니다.",
          prevention: "content review에서 link text만 따로 읽는 검사를 하고 duplicate name/different destination lint를 적용합니다.",
        },
      ],
      expertNotes: ["SPA Link가 client transition을 수행하더라도 route 변경 후 document title·main heading·focus·aria-current를 갱신해야 새 document navigation에 가까운 orientation을 제공합니다.", "SEO용 anchor text를 keyword로 과도하게 반복하기보다 사람이 목적지를 판단하는 자연스러운 이름을 우선하고, canonical·redirect와 실제 href graph를 일치시킵니다."],
    },
    {
      id: "testing-and-operational-debugging",
      title: "링크 품질은 DOM 문자열이 아니라 실제 base·응답·redirect·keyboard·배포 환경으로 검증합니다",
      lead: "404 하나를 고칠 때 href 앞에 slash를 임의로 붙이지 말고 source attribute에서 최종 URL과 server 응답까지 단계별로 추적합니다.",
      explanations: [
        "첫 단계는 source href와 resolved URL을 구분하는 것입니다. `link.getAttribute('href')`는 author가 쓴 문자열에 가깝고 `link.href`는 document base를 적용한 완전 URL입니다. document.baseURI, current location, Elements, Network request를 함께 보면 parser 문제인지 URL resolution 문제인지 빠르게 나눌 수 있습니다.",
        "두 번째는 HTTP 결과입니다. 200만 성공으로 간주하면 204·authorized 3xx·download를 놓칠 수 있고, 404 page가 status 200을 반환하는 soft 404도 있습니다. redirect chain이 다른 origin·login·HTTP downgrade로 빠지는지, HEAD를 거부하고 GET만 허용하는 server인지, fragment destination이 최종 HTML에 존재하는지 검사합니다.",
        "세 번째는 탐색 방식입니다. mouse click, Enter, middle click, 새 탭 context menu, Tab/Shift+Tab, browser Back/Forward, page reload, URL 직접 입력을 시험합니다. SPA에서 click만 intercept해 동작하고 새 탭·JavaScript disabled·direct deep link에서 404가 나면 native link 계약을 완전히 지키지 못한 것입니다.",
        "네 번째는 환경 matrix입니다. origin root와 subpath preview, trailing slash on/off, case-sensitive build, authenticated/anonymous user, mobile viewport, reduced motion, high contrast를 포함합니다. 모든 외부 link를 매 build마다 공격적으로 호출하면 rate limit과 불안정성이 생기므로 내부 link는 엄격히, 외부 link는 cache·retry·allowlist·주기적 job으로 관리할 수 있습니다.",
        "자동 link checker는 시작점이지만 목적의 정확성·새 탭 예고·focus visibility·redirect가 올바른 문서로 가는지는 사람이 확인해야 합니다. sitemap과 crawler graph에서 orphan page, redirect loop, canonical mismatch를 찾고 telemetry의 404 referrer를 통해 production에서만 생기는 깨진 link를 되먹임합니다.",
      ],
      concepts: [
        { term: "soft 404", definition: "존재하지 않는 내용을 보여 주면서 HTTP status는 200으로 반환해 crawler와 monitoring이 성공으로 오인하는 상태입니다.", detail: ["화면 text뿐 아니라 status와 최종 URL을 확인합니다.", "custom error page가 올바른 404 status를 반환해야 합니다."] },
        { term: "redirect chain", definition: "처음 href에서 최종 response까지 거치는 하나 이상의 3xx location 이동입니다.", detail: ["성능과 referrer·cookie·origin에 영향을 줍니다.", "loop·HTTP downgrade·unexpected host를 검사합니다."] },
        { term: "link integrity test", definition: "resolved URL의 응답과 내부 fragment, 접근 권한, navigation semantics를 자동·수동으로 검증하는 절차입니다.", detail: ["source href string 검사만으로 끝나지 않습니다.", "build artifact와 production route를 모두 대상으로 할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        {
          symptom: "HTML validator는 통과하고 href도 존재하지만 production에서만 일부 link가 login page·404·redirect loop로 간다.",
          likelyCause: "schema 검사는 URL 존재·권한·proxy rewrite·base path·redirect 결과를 검증하지 않으며 환경별 route 계약이 다릅니다.",
          checks: ["production-like base에서 resolved href를 수집합니다.", "각 URL의 status·Location chain·최종 origin을 기록합니다.", "anonymous와 authenticated session을 나눠 시험합니다.", "server log와 reverse proxy rewrite 규칙을 확인합니다.", "최종 문서 fragment id 존재 여부를 검사합니다."],
          fix: "public route·authorization·redirect·base 설정을 하나의 계약으로 맞추고 잘못된 hard-coded href를 URL helper로 교체합니다.",
          prevention: "deploy preview crawler, internal fragment checker, keyboard smoke test, production 404 telemetry를 CI/CD와 운영 점검에 연결합니다.",
        },
      ],
      comparisons: [
        {
          title: "링크 검증을 어디까지 자동화할까요?",
          options: [
            { name: "build-time 내부 link 검사", chooseWhen: "정적 route·fragment·asset의 참조 무결성을 매 commit 보장할 때", avoidWhen: "인증·동적 데이터에 따라 목적지가 달라 이것만으로 충분하다고 볼 때", tradeoffs: ["빠르고 결정적인 404·fragment 오류를 잡습니다.", "runtime auth·proxy 차이를 못 잡을 수 있습니다.", "artifact base와 같은 설정이 필요합니다."] },
            { name: "배포 preview E2E", chooseWhen: "실제 router·server·subpath·redirect·focus를 확인할 때", avoidWhen: "모든 외부 site까지 무제한 호출할 때", tradeoffs: ["production과 가까운 통합 오류를 잡습니다.", "시간과 flaky 관리 비용이 듭니다.", "핵심 navigation을 우선순위화해야 합니다."] },
            { name: "운영 telemetry·주기 crawler", chooseWhen: "외부 link 변화와 실제 사용자 404를 장기 관찰할 때", avoidWhen: "개인 URL·민감 query를 그대로 수집할 때", tradeoffs: ["배포 뒤 drift를 찾습니다.", "privacy·retention·rate limit 설계가 필요합니다.", "근본 수정 전까지 monitor가 대신 해결하지는 않습니다."] },
          ],
        },
      ],
      expertNotes: ["client router의 prefetch가 GET link를 사용자의 명시적 activation 전에 요청할 수 있으므로 GET route는 safe semantics를 지키고 data mutation을 link navigation에 숨기지 않습니다.", "URL은 관찰 가능 data입니다. monitoring에서 전체 query를 저장하기 전에 token·email 등 민감 parameter redaction과 retention 정책을 적용합니다."],
    },
  ],
  lab: {
    title: "하위 경로 배포에도 견디는 3-page 학습 문서 navigation",
    scenario: "index, HTML 개요, 링크 실습의 세 page와 각 page 내부 목차를 만들고, `/course/` subpath에 배포된다고 가정해 상대 URL·fragment·새 탭·focus·404를 처음부터 끝까지 검증합니다.",
    setup: [
      "UTF-8 문서와 Python 3 HTTP server 또는 동등한 static preview를 준비합니다.",
      "공개 구조를 `course/index.html`, `course/lessons/html/index.html`, `course/lessons/html/links.html`로 만듭니다.",
      "실습용 외부 link는 WHATWG·W3C의 HTTPS 공식 문서만 사용하고 token·개인정보를 URL에 넣지 않습니다.",
      "browser DevTools Elements·Console·Network, keyboard, HTML validator, 간단한 link checker를 준비합니다.",
    ],
    steps: [
      "세 문서에 doctype·lang=ko·charset·고유 title·h1을 작성하고 현재 source tree와 public route mapping을 표로 적습니다.",
      "course/index.html에서 lessons/html/index.html로, HTML 개요에서 links.html로, links.html에서 두 page로 돌아가는 path-relative link를 작성합니다.",
      "각 href를 고정 base와 new URL로 계산해 expected resolved URL 표를 만들고 browser의 element.href와 비교합니다.",
      "links.html에 최소 네 section/h2와 stable id를 두고 nav 목차, #top link, :target, scroll-margin-top, focus-visible style을 구현합니다.",
      "공식 WHATWG link 하나는 기본 `_self`, 다른 복사본은 요구를 가정해 `_blank`·rel=noopener·'(새 탭)' 고지를 적용하고 경험을 비교합니다.",
      "동작 button 하나를 추가해 a와 동일하게 style하되 DOM role·Enter/Space·새 탭 메뉴 차이를 기록합니다.",
      "root preview와 `/course/` subpath preview에서 직접 deep URL을 열고 모든 내부 link·fragment·Back/Forward를 시험합니다.",
      "일부러 href의 `/course`를 빼고, id 철자를 바꾸고, filename case를 바꾼 세 장애를 만들어 resolved URL·Network status·DOM target 순서로 진단합니다.",
      "Tab·Shift+Tab으로 focus 순서와 indicator를 확인하고 pointer hover 없이도 목적지와 현재 위치를 이해할 수 있는지 검사합니다.",
      "HTML validator와 link checker를 실행하고 2xx·허용 redirect·fragment 존재·duplicate id 결과를 기록한 뒤 원래 정상 상태로 복구합니다.",
    ],
    expectedResult: [
      "모든 내부 href의 resolved URL이 `/course/` base를 보존하고 실제 document로 이동합니다.",
      "직접 links.html#relative-path를 열어도 해당 heading이 보이고 :target으로 구분되며 문맥을 이해할 수 있습니다.",
      "현재 문서 navigation은 `_self`와 Back button을 보존하고, 의도한 새 탭 link만 고지와 noopener를 가집니다.",
      "본문 link는 밑줄·focus outline이 있고 button은 URL 없이 동작 의미를 유지합니다.",
      "깨진 path·fragment·case 장애를 source href → resolved URL → request/response → DOM target 순서로 설명하고 수정할 수 있습니다.",
      "validator duplicate id가 없고 내부 link checker가 허용된 응답과 fragment를 모두 통과합니다.",
    ],
    cleanup: [
      "의도적으로 만든 broken href·duplicate id·case mismatch fixture만 제거합니다.",
      "정상 course 폴더와 expected URL 표는 후속 image·list·form 세션의 누적 site로 보존합니다.",
      "임시 HTTP server를 종료하고 browser에 남은 실습 tab을 닫습니다.",
    ],
    extensions: [
      "static generator의 basePath helper로 동일 문서를 root와 `/preview/course/` 두 위치에 build합니다.",
      "aria-current=page가 있는 global navigation과 breadcrumb를 추가하고 link list의 이름만 읽어 검수합니다.",
      "외부 link의 status·최종 origin을 cache하는 주기 checker를 설계하되 rate limit·privacy 정책을 문서화합니다.",
      "SPA client navigation에서 title·main focus·Back/Forward·direct deep link를 E2E test합니다.",
      "legacy public fragment id를 새 heading slug로 바꿀 때 호환 anchor 또는 redirect map을 설계합니다.",
    ],
  },
  exercises: [
    {
      difficulty: "따라하기",
      prompt: "원본 ex01_a.html의 외부·origin-root·parent-relative link와 세 section 목차를 작은 학습 문서로 다시 작성하세요.",
      requirements: [
        "기준 URL을 하나 정하고 각 href의 최종 URL을 클릭 전에 표로 계산합니다.",
        "문서 내부 목적지는 빈 a가 아니라 h2 또는 section의 unique id로 만듭니다.",
        "href=# 대신 명시적인 #top target을 사용합니다.",
        "본문 link의 밑줄과 focus-visible indicator를 유지합니다.",
        "기본 navigation은 target을 생략하고 새 탭 예제 하나만 목적 고지와 rel=noopener를 사용합니다.",
      ],
      hints: ["getAttribute('href')와 element.href를 비교하면 source와 resolved URL 차이가 보입니다.", "`../`는 현재 document가 있는 directory에서 한 단계 위로 갑니다.", "target name과 fragment id는 다른 namespace와 목적을 가집니다."],
      expectedOutcome: "같은 page와 다른 page로 이동하는 link를 URL 계산·semantic·keyboard 관점에서 설명하고 재현합니다.",
      solutionOutline: ["문서 URL과 directory tree를 먼저 그립니다.", "href별 new URL 결과를 확인합니다.", "heading id와 nav fragment를 1:1로 연결합니다.", "Tab·click·Back·새 탭을 각각 시험합니다."],
    },
    {
      difficulty: "응용",
      prompt: "root에서는 통과하지만 `/academy/v2/` subpath에서 깨지는 link site를 진단하고 수정하세요.",
      requirements: [
        "origin-root-relative·path-relative·base element가 섞인 최소 세 장애를 포함합니다.",
        "source href, document.baseURI, resolved href, Network 최종 URL·status를 표로 기록합니다.",
        "없는 fragment·duplicate id·fixed header 가림을 각각 재현하고 수정합니다.",
        "Windows와 case-sensitive 배포의 filename case 차이를 검사합니다.",
        "자동 내부 link/fragment 검사와 keyboard manual check를 모두 통과합니다.",
      ],
      hints: ["slash 하나로 시작하는 경로는 application folder가 아니라 origin root를 기준으로 합니다.", "base element는 fragment link를 포함한 많은 URL에 영향을 줍니다.", "200 response가 올바른 content인지 title/h1도 확인합니다."],
      expectedOutcome: "눈에 보이는 href 수정이 아니라 resolution·deployment·response·DOM target의 원인을 구분해 고칩니다.",
      solutionOutline: ["production-like subpath에서 먼저 실패를 재현합니다.", "URL API와 Network로 계산·server 문제를 분리합니다.", "중앙 base URL 생성 정책을 적용합니다.", "root와 subpath matrix를 회귀 test로 남깁니다."],
    },
    {
      difficulty: "설계",
      prompt: "초보부터 전문가까지 보는 공개 학습자료 site의 link governance와 검증 pipeline을 설계하세요.",
      requirements: [
        "route slug·heading permalink id·redirect·trailing slash·deployment base 규칙을 정의합니다.",
        "Link와 Button component 선택 기준, 외부 새 탭 고지, noopener·noreferrer·referrerpolicy 정책을 정의합니다.",
        "사용자 제공 URL의 scheme·host allowlist와 open redirect 방어를 포함합니다.",
        "link purpose·aria-current·focus·skip link·reduced motion 접근성 기준을 포함합니다.",
        "build-time internal checker, preview E2E, production 404 telemetry, external periodic checker의 책임과 실패 처리 방식을 나눕니다.",
        "URL query의 개인정보 redaction·log retention·crawler rate limit을 문서화합니다.",
      ],
      hints: ["공개 URL과 source filesystem path는 별도 API입니다.", "noopener와 referrer 억제는 같은 선택이 아닙니다.", "자동 checker는 올바른 목적과 사용자 orientation까지 완전히 판단하지 못합니다."],
      expectedOutcome: "한 개 a tag를 production URL architecture·security·accessibility·observability 정책으로 확장한 실행 가능한 설계 문서를 만듭니다.",
      solutionOutline: ["URL 생성 책임과 public route schema를 먼저 정합니다.", "semantic component와 security default를 중앙화합니다.", "환경 matrix와 acceptance test를 정의합니다.", "운영 telemetry의 privacy boundary와 owner를 배정합니다."],
    },
  ],
  reviewQuestions: [
    { question: "href가 없는 a도 정상 hyperlink인가요?", answer: "아닙니다. WHATWG 의미상 href가 있을 때 hyperlink이고, 없으면 link가 놓일 수 있는 placeholder입니다. 주소 이동에는 유효한 href가 있는 a를 사용합니다." },
    { question: "`../day01/page.html`의 최종 URL을 계산하려면 어떤 정보가 반드시 필요한가요?", answer: "상대 URL은 non-null base URL이 필요하므로 현재 document URL 또는 base element로 정해진 document base URL을 알아야 합니다." },
    { question: "`/day01/page.html`의 slash는 operating system drive root를 뜻하나요?", answer: "아닙니다. HTTP(S) URL에서는 현재 origin의 path root부터 시작하며 application context `/myweb`을 자동으로 붙이지 않습니다." },
    { question: "query와 fragment는 navigation에서 어떻게 다릅니까?", answer: "query는 URL의 `?` 뒤 component로 server request와 client logic에 전달될 수 있고, fragment는 `#` 뒤에서 browser가 문서 내부 target 등을 식별하며 일반적으로 HTTP request에는 전달되지 않습니다." },
    { question: "같은 문서의 section으로 이동하려면 target='section-name'을 사용하나요?", answer: "아닙니다. href=#section-name과 같은 id의 destination을 사용합니다. target 이름은 browsing context를 선택합니다." },
    { question: "현재 표준에서 target=_blank가 암묵적으로 noopener라면 rel=noopener 설명은 왜 남기나요?", answer: "현재 처리 모델은 rel=opener가 없는 `_blank`를 noopener로 취급하지만 명시적 rel은 보안 의도와 legacy 호환 범위를 드러냅니다. 최종 HTML과 지원 browser를 검증하며 과장 없이 설명합니다." },
    { question: "noopener와 noreferrer는 같은가요?", answer: "아닙니다. noopener는 opener 관계 차단이 목적이고, noreferrer는 referrer 억제와 함께 같은 조건에서 noopener behavior를 함축합니다. analytics·privacy trade-off가 다릅니다." },
    { question: ":active는 현재 page link를 표시하나요?", answer: "아닙니다. :active는 활성화되는 짧은 순간입니다. 현재 navigation item은 aria-current와 별도 visual style로 표시합니다." },
    { question: "hover style이 있으면 keyboard 접근성도 충족하나요?", answer: "아닙니다. hover가 없는 입력이 있고 keyboard focus는 :focus 또는 :focus-visible indicator로 별도 표시해야 합니다." },
    { question: "href가 200을 반환하면 link 검사가 끝났나요?", answer: "아닙니다. soft 404, redirect 목적지, 인증, fragment 존재, 목적 설명, focus와 Back/새 탭 behavior까지 필요 범위에 따라 확인해야 합니다." },
  ],
  completionChecklist: [
    "a[href] hyperlink와 button action을 결과 기준으로 구분할 수 있다.",
    "URL의 scheme·origin·path·query·fragment를 분해할 수 있다.",
    "base URL과 href로 absolute·origin-root-relative·path-relative URL을 계산할 수 있다.",
    "context path·subpath·trailing slash·case mismatch로 생기는 404를 단계적으로 진단할 수 있다.",
    "unique id·#fragment·:target·scroll-margin-top으로 안정적인 문서 목차를 만들 수 있다.",
    "_self·_blank·_parent·_top·named target과 fragment destination을 혼동하지 않는다.",
    "noopener·noreferrer·referrerpolicy의 보안·privacy 차이를 설명하고 정책에 맞게 선택할 수 있다.",
    ":link·:visited·:hover·:active·:focus-visible을 구분하고 색 외 link 단서를 제공할 수 있다.",
    "link text만 읽어도 목적·새 탭·download 등 필요한 정보를 판단할 수 있게 작성한다.",
    "source href→resolved URL→request/redirect/status→DOM target→keyboard 경험 순서로 link를 검증할 수 있다.",
    "public source에는 공식 HTTPS URL만 사용하고 local absolute path·private repository URL·민감 query를 노출하지 않는다.",
  ],
  nextSessions: ["html-04-images-background-media"],
  sources: [
    {
      id: "web-anchor-comment-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day01/ex09_a.html",
      usedFor: ["a·href 기본 구조", "다른 page와 같은 page 이동", "target 값에 대한 원본 주석"],
      evidence: "문서 전체를 읽어 a 기본 설명과 `_blank`·`_self`·`_parent`·name 주석을 확인했습니다. 원본의 target name과 같은-page 위치 혼동은 fragment와 browsing context 설명으로 교정했습니다.",
    },
    {
      id: "web-link-navigation-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day02/ex01_a.html",
      usedFor: ["외부 URL", "origin-root-relative 경로", "../ 상대 경로", "target 비교", "fragment 목차", "href=# top 이동"],
      evidence: "외부 Naver link, `/day01`과 `../day01` 경로, target blank/self/default, first·second·third id 목차와 반복 content를 전체 감사했습니다. `/myweb` context 손실과 빈 a destination·href=#을 재현 가능한 modern 예제로 개선했습니다.",
    },
    {
      id: "web-link-color-source",
      repository: "webstudy 학습 원본",
      path: "myweb/src/main/webapp/day02/ex02_a_color.html",
      usedFor: [":link", ":visited", ":hover", ":active 주석", "text-decoration 제거", "/myweb context 경로"],
      evidence: "원본 style과 주석을 모두 읽어 방문 전·방문 후·hover·active 상태와 밑줄 제거 의도를 확인했습니다. keyboard focus·history privacy·비색상 affordance와 context path 비교를 추가했습니다.",
    },
    {
      id: "whatwg-a-element",
      repository: "WHATWG HTML Living Standard",
      path: "multipage/text-level-semantics.html#the-a-element",
      publicUrl: "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element",
      usedFor: ["href가 있는 a의 hyperlink 의미", "href 없는 placeholder", "a content model", "target·rel·download·referrerpolicy attributes"],
      evidence: "2026-07-12에 확인한 WHATWG living standard에서 a의 category·content model·href 유무에 따른 의미와 navigation 관련 attributes를 대조했습니다.",
    },
    {
      id: "whatwg-links",
      repository: "WHATWG HTML Living Standard",
      path: "multipage/links.html",
      publicUrl: "https://html.spec.whatwg.org/multipage/links.html",
      usedFor: ["document relative href parsing", "hyperlink following", "target context", "noopener·noreferrer", "_blank implicit noopener behavior"],
      evidence: "2026-07-12에 hyperlink URL이 node document 기준으로 parsing되는 절차, target 선택, rel=opener가 없는 `_blank`의 noopener 처리, noreferrer가 noopener를 함축하는 규칙을 확인했습니다.",
    },
    {
      id: "whatwg-url",
      repository: "WHATWG URL Living Standard",
      path: "",
      publicUrl: "https://url.spec.whatwg.org/",
      usedFor: ["absolute·relative URL", "base URL 필요성", "URL component", "path-relative·path-absolute grammar", "parser·serializer mental model"],
      evidence: "2026-07-12에 relative URL parsing에 non-null base가 필요하다는 규칙과 absolute/path-relative/path-absolute, query·fragment 구조를 확인했습니다.",
    },
    {
      id: "css-selectors",
      repository: "W3C CSS Working Group Selectors Level 4",
      path: "selectors/#link",
      publicUrl: "https://drafts.csswg.org/selectors/#link",
      usedFor: [":any-link", ":link·:visited", "visited privacy", ":target", ":hover·:active·:focus"],
      evidence: "2026-07-12에 link history pseudo-class의 배타성·privacy 요구, HTML fragment와 같은 id target, :target·hover·active·focus 정의를 확인했습니다.",
    },
    {
      id: "w3c-link-purpose",
      repository: "W3C Web Accessibility Initiative WCAG 2.2",
      path: "Understanding/link-purpose-in-context.html",
      publicUrl: "https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html",
      usedFor: ["link 목적", "문맥에서 이해 가능한 이름", "보조기술 link 목록", "중간 진입 사용자 편의"],
      evidence: "2026-07-12에 사용자가 link를 따를지 판단할 수 있어야 한다는 SC 2.4.4 취지와 가능한 경우 link text 자체로 목적을 식별하라는 설명을 확인했습니다.",
    },
    {
      id: "w3c-new-window-warning",
      repository: "W3C Web Accessibility Initiative WCAG 2.2 Techniques",
      path: "Techniques/general/G201",
      publicUrl: "https://www.w3.org/WAI/WCAG22/Techniques/general/G201",
      usedFor: ["새 window/tab 사전 고지", "시각·보조기술 알림", "target=_blank 사용자 orientation"],
      evidence: "2026-07-12에 확인한 G201의 advisory technique에서 새 window/tab을 여는 일반 activation 전에 사용자에게 보이는 방식과 보조기술 방식으로 알리는 예제와 test를 확인했습니다.",
    },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "세 원본의 a 주석, 외부·절대·상대 link, target blank/self/default, fragment 목차, href=#, link·visited·hover·active CSS를 모두 사용했습니다.",
      "원본의 `/day01`과 `/myweb/day01` 불일치, target name 설명, 빈 a id destination, 전역 밑줄 제거는 현재 URL·HTML·CSS·WCAG 기준으로 진단하고 교정했습니다.",
      "URL parser 내부 규칙, `_blank`의 최신 noopener 처리, referrer privacy, link purpose, subpath 배포·자동 검사 범위는 원본에 없어 WHATWG·W3C primary public sources와 운영 관점으로 보강했습니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
