import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["html-10-document-capstone"],
  slug: "html-10-document-capstone",
  courseId: "web",
  moduleId: "01-html-document-forms",
  order: 10,
  title: "접근 가능한 지원서·상품·취미 페이지 종합 제작",
  subtitle: "문서·text·link·image·media·목록·표·form·landmark를 요구사항에서 검증까지 통합하고, 원본 6개 결과물을 공개 가능한 학습 프로젝트로 재구성합니다.",
  level: "고급",
  estimatedMinutes: 240,
  coreQuestion: "개별 tag 예제를 실제 서비스 page로 합칠 때 content 의미·사용자 task·접근성·HTTP·반응형·성능·privacy를 어떻게 하나의 반복 가능한 제작·검증 workflow로 관리할까요?",
  summary: "방송국 모집/빈 표 지원 양식/문화 축제/원형 image/강아지 article/여가 card의 원본 6개를 단순 복제하지 않고 감사합니다. 잘못된 lang, alt 불일치·누락, href='#', blank table form, heading 순서, autoplay media, header 없는 table, fixed width/height, float를 실제 요구와 사용자 task 기준으로 고칩니다. 콘텐츠 inventory→semantic wireframe→accessible 구현→responsive enhancement→HTTP form contract→자동·수동 품질 gate→근거/실행 결과 기록의 capstone workflow를 완성하고, 독립적으로 다시 열어도 이해되는 공개 학습 산출물을 만듭니다.",
  objectives: [
    "원본 page의 콘텐츠·기능·접근성·privacy·성능 요구를 구현 전에 inventory와 acceptance criteria로 바꿀 수 있다.",
    "지원서에는 실제 form, 비교 data에는 table, card에는 article/link 등 목적에 맞는 구조를 통합할 수 있다.",
    "image/media의 alt·caption·controls·autoplay·loading·dimension 전략을 content 목적과 성능 기준으로 결정할 수 있다.",
    "mobile-first CSS를 더해도 DOM·heading·landmark·focus·form contract를 보존할 수 있다.",
    "HTML validation·internal link·accessible name·keyboard·zoom·FormData·Network·privacy를 release gate로 자동·수동 검증할 수 있다.",
    "원본 출처·변경 이유·실행 방법·정확한 결과·남은 한계를 학습자가 재현하도록 기록할 수 있다.",
  ],
  prerequisites: [
    { title: "div 레이아웃을 시맨틱 랜드마크로 바꾸기", reason: "HTML 1~9회차의 문서·content·link/media·목록·표·form·page semantic을 하나의 결과물로 통합합니다.", sessionSlug: "html-09-semantic-layout-accessibility" },
  ],
  keywords: ["capstone", "content inventory", "semantic wireframe", "acceptance criteria", "accessible form", "card pattern", "media policy", "responsive", "quality gate", "provenance", "progressive enhancement"],
  chapters: [
    {
      id: "audit-before-rebuild",
      title: "원본을 고치기 전에 콘텐츠·사용자 task·문제·보존할 학습 의도를 증거표로 만듭니다",
      lead: "보이는 화면을 그대로 따라 그리면 원본의 오류와 임시 placeholder까지 복제하므로 각 element가 왜 존재하는지부터 묻습니다.",
      explanations: [
        "방송국 모집 page는 기간·분야·지원 방법·혜택과 image를 전달합니다. 지원 양식은 table의 빈 cell로 종이 서식을 흉내 냈지만 web에서 사용자가 입력·제출해야 한다면 실제 label/input/form이 필요합니다. 같은 사각형 모양이라도 사용자 task가 element 선택을 바꿉니다.",
        "축제 page는 설명·일정·먹거리·video를 제공하지만 '자세한 정보 보기'가 link가 아니고 먹거리 table에 caption/column header가 부족합니다. autoplay muted loop는 기술적으로 재생될 수 있어도 학습 자료의 인지 부담·data 사용·사용자 통제를 고려해 controls와 poster, 사용자가 시작하는 재생을 우선합니다.",
        "강아지 article과 여가 card는 반복 content component의 좋은 출발점이지만 fixed width/height·float·inline-block과 placeholder link/Latin text/image alt 누락이 있습니다. content 길이·translation·zoom에서 card가 잘리는지, card 전체 link가 중첩 interactive content를 만들지 검토합니다.",
        "원형 곰 image 예제는 CSS border-radius·shadow를 학습하는 작은 artifact입니다. capstone에서는 style 효과를 유지하되 실제 content 목적, alt, intrinsic width/height, responsive size, decorative 여부를 기록합니다. CSS 실습을 semantic page와 혼동하지 않습니다.",
        "audit 표에는 source, user task, current element, issue, risk, target element, verification, 보존할 학습 point를 둡니다. 개인 정보·실제 이메일·비공개 URL·secret이 원본에 있으면 public fixture로 옮기지 않고 synthetic data로 치환합니다.",
      ],
      concepts: [
        { term: "content inventory", definition: "page에 필요한 제목·문단·link·media·data·control과 소유자/상태를 구현 전에 목록화한 자료입니다.", detail: ["placeholder와 실제 content를 구분합니다.", "누락·중복·privacy 위험을 찾습니다."] },
        { term: "acceptance criterion", definition: "사용자 관점에서 구현 완료 여부를 관찰·검증할 수 있게 쓴 조건입니다.", detail: ["'접근 가능하게'보다 '첫 Tab으로 skip link가 보인다'처럼 구체화합니다.", "자동/수동 검사 방법을 연결합니다."] },
        { term: "semantic mismatch", definition: "화면 모양은 유사하지만 element 의미와 사용자 task가 일치하지 않는 상태입니다.", detail: ["빈 table을 form으로 쓰는 경우가 예입니다.", "CSS만으로 고칠 수 없습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "리뉴얼 page가 원본과 픽셀은 비슷하지만 사용자는 지원 내용을 입력하거나 제출할 수 없다.", likelyCause: "종이 양식 모양의 빈 table을 실제 interactive form 요구로 재해석하지 않았습니다.", checks: ["사용자가 완료해야 할 동사를 적습니다.", "각 빈 cell이 data input인지 display data인지 구분합니다.", "keyboard와 server submission path를 확인합니다."], fix: "입력 task는 label/control/form과 server contract로 재설계하고 실제 비교 data만 table로 유지합니다.", prevention: "visual reference와 별도로 user task·semantic wireframe·acceptance criteria 승인을 받습니다." },
      ],
    },
    {
      id: "semantic-wireframe",
      title: "CSS 전에 heading·landmark·content type·link/form action으로 semantic wireframe을 완성합니다",
      lead: "gray box 대신 실제 제목·section·article·list·table·form을 source order로 배치해 CSS/JavaScript 없이 task를 끝내게 합니다.",
      explanations: [
        "document에는 ko language, 목적을 구분하는 title, mobile viewport를 둡니다. body 첫 skip link 뒤 site header/nav, 유일한 main, footer를 배치하고 main h1 아래 모집 정보·혜택·지원 form을 h2 section으로 나눕니다.",
        "모집 기간·분야·지원 방법은 항목 목록 또는 description list가 적합할 수 있습니다. 일정은 순서가 날짜 흐름을 나타내면 ol, 먹거리 운영 시간·장소를 교차 비교하면 caption과 header를 가진 table입니다. 모든 반복 content를 같은 card div로 만들지 않습니다.",
        "'자세한 정보 보기'는 목적이 드러나는 link text와 실제 href를 가져야 합니다. href='#'는 완성된 route가 아니며 URL·history·new tab 기능을 제공하지 않습니다. 준비되지 않은 기능은 disabled link 흉내 대신 일반 text와 상태를 명시하거나 route를 구현합니다.",
        "지원서의 name·department·student ID·contact·field는 label/control과 fieldset/legend로 구성합니다. 수집 목적과 보관 기간이 없는 개인정보는 제거하고, 실제 server endpoint가 없다면 demo가 local에서 무엇을 하는지 분명히 표시합니다.",
        "semantic wireframe 검증은 CSS를 아예 연결하지 않은 상태에서 heading/landmark 목록, link destination, form FormData, table header, image alt를 확인하는 것입니다. 이 단계가 통과한 뒤 layout을 추가합니다.",
      ],
      concepts: [
        { term: "semantic wireframe", definition: "시각 style 없이 HTML element·heading·source order·native interaction으로 page 정보 구조와 task를 표현한 prototype입니다.", detail: ["CSS 실패 baseline이 됩니다.", "design 전에 content gap을 발견합니다."] },
        { term: "progressive enhancement", definition: "작동하는 semantic/native baseline 위에 CSS layout·JavaScript convenience를 단계적으로 추가하는 전략입니다.", detail: ["network/script failure에도 핵심 task가 남습니다.", "enhancement마다 회귀 검증합니다."] },
      ],
      codeExamples: [
        {
          id: "accessible-application-page",
          title: "모집 공고와 실제 지원 form을 통합한 semantic baseline",
          language: "html",
          filename: "broadcast-application.html",
          purpose: "원본 공고와 빈 table 지원 양식을 사용 가능한 link·list·fieldset·label·FormData demo로 재구성합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>수습 국원 모집·지원</title>\n</head>\n<body>\n  <a href=\"#content\">본문 바로가기</a>\n  <header><p>교내 방송국</p></header>\n  <main id=\"content\" tabindex=\"-1\">\n    <h1>수습 국원 모집</h1>\n    <p>방송에 관심 있는 새내기 여러분을 환영합니다.</p>\n\n    <section aria-labelledby=\"notice-title\">\n      <h2 id=\"notice-title\">모집 안내</h2>\n      <dl>\n        <dt>기간</dt><dd><time datetime=\"2026-03-02\">3월 2일</time>–<time datetime=\"2026-03-11\">3월 11일</time></dd>\n        <dt>분야</dt><dd>아나운서, PD, 엔지니어</dd>\n        <dt>방법</dt><dd>아래 지원서를 작성해 제출합니다.</dd>\n      </dl>\n    </section>\n\n    <section aria-labelledby=\"form-title\">\n      <h2 id=\"form-title\">지원서</h2>\n      <p id=\"required-help\">모든 항목은 필수입니다. 이 demo는 server로 전송하지 않고 입력 구조만 출력합니다.</p>\n      <form id=\"application\" aria-describedby=\"required-help\">\n        <label for=\"name\">이름</label>\n        <input id=\"name\" name=\"name\" autocomplete=\"name\" required value=\"홍길동\">\n        <label for=\"student-id\">학번</label>\n        <input id=\"student-id\" name=\"studentId\" inputmode=\"numeric\" required value=\"20260001\">\n        <fieldset>\n          <legend>지원 분야</legend>\n          <label><input type=\"radio\" name=\"field\" value=\"announcer\" required checked> 아나운서</label>\n          <label><input type=\"radio\" name=\"field\" value=\"producer\"> PD</label>\n          <label><input type=\"radio\" name=\"field\" value=\"engineer\"> 엔지니어</label>\n        </fieldset>\n        <button>지원 내용 확인</button>\n      </form>\n      <pre id=\"result\"></pre>\n    </section>\n  </main>\n  <footer><p>문의 정보는 공개 전 담당 부서에서 검증합니다.</p></footer>\n  <script>\n    document.querySelector('#application').addEventListener('submit', (event) => {\n      event.preventDefault();\n      const data = Object.fromEntries(new FormData(event.currentTarget));\n      document.querySelector('#result').textContent = JSON.stringify(data, null, 2);\n    });\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "1-10", explanation: "한국어 document metadata와 skip link, site header, 고유 main을 만듭니다." },
            { lines: "14-21", explanation: "모집 metadata는 빈 table이 아니라 term-description 관계인 dl과 machine-readable time으로 표현합니다." },
            { lines: "23-39", explanation: "visible instruction, explicit label, stable name, autocomplete, radio fieldset/legend를 갖춘 실제 form을 작성합니다." },
            { lines: "40-42", explanation: "이 example은 production endpoint가 아니라 입력 구조를 출력하는 demo임을 미리 고지합니다." },
            { lines: "46-51", explanation: "valid submit을 가로채 FormData의 exact name/value를 출력해 학습자가 server contract 전 단계까지 확인합니다." },
          ],
          run: { environment: ["현대 browser", "JavaScript enabled", "UTF-8 file"], command: "browser에서 broadcast-application.html을 열고 초기값 그대로 지원 내용 확인" },
          output: { value: "{\n  \"name\": \"홍길동\",\n  \"studentId\": \"20260001\",\n  \"field\": \"announcer\"\n}", explanation: ["table의 빈 칸이 아니라 실제 successful control entry가 생성됩니다.", "학번은 산술 number가 아니라 identifier string으로 leading zero 가능성을 보존합니다.", "production에서는 POST+HTTPS endpoint와 server validation·privacy notice·CSRF가 추가되어야 합니다."] },
          experiments: [
            { change: "name input의 name attribute를 삭제합니다.", prediction: "label과 화면 값은 남지만 output에서 name key가 사라집니다.", result: "id/label과 form submission name은 별도 계약입니다." },
            { change: "form을 blank table cell로 되돌립니다.", prediction: "시각 양식은 만들 수 있어도 keyboard input·FormData·validation이 모두 사라집니다.", result: "user task가 semantic element 선택을 결정합니다." },
            { change: "JavaScript를 끕니다.", prediction: "공고·label·control·button은 남지만 endpoint 없는 demo는 현재 page에 GET submit할 수 있습니다.", result: "production baseline에는 실제 action/method 또는 명확한 no-JS fallback이 필요합니다." },
          ],
          sourceRefs: ["web-capstone-recruit-source", "web-capstone-blank-form-source", "whatwg-forms", "wai-forms"],
        },
      ],
      diagnostics: [
        { symptom: "semantic wireframe을 CSS 없이 열었더니 card 순서와 heading이 무의미하고 button이 어디로 제출되는지 알 수 없다.", likelyCause: "layout mockup을 HTML로 옮겼을 뿐 content model과 interaction contract를 먼저 설계하지 않았습니다.", checks: ["heading/landmark/link/form 목록만 추출합니다.", "각 interactive element의 결과 URL/action을 확인합니다.", "CSS off keyboard task를 수행합니다."], fix: "content inventory와 semantic wireframe 단계로 돌아가 source order·heading·native element·action을 재설계합니다.", prevention: "CSS PR 전에 semantic baseline acceptance gate를 통과하도록 workflow를 분리합니다." },
      ],
    },
    {
      id: "media-content-policy",
      title: "image·video는 장식이 아니라 정보·대체 경로·network 비용·사용자 통제 계약입니다",
      lead: "alt 한 줄을 기계적으로 넣거나 autoplay를 켜는 대신 media가 없어도 무엇이 남아야 하는지 결정합니다.",
      explanations: [
        "방송국 원본은 mic.jpg에 alt='카메라'를 사용해 실제 image와 대체 text가 불일치합니다. image가 microphone으로 모집 분위기를 전달하면 '방송용 마이크'처럼 짧게 설명하고, 인접 text를 반복하는 순수 장식이면 alt=''로 accessibility tree에서 제외합니다.",
        "여가 card의 image는 link 안에서 card 목적을 보조합니다. link accessible name에 heading이 이미 포함되면 alt가 같은 title을 반복하지 않게 조정할 수 있습니다. image만 link인 경우 목적을 설명하는 alt가 필수입니다. alt는 file name이나 '이미지'라는 말이 아니라 content/function을 전달합니다.",
        "top banner처럼 CSS crop이 필요한 content image는 picture/srcset/sizes와 width/height로 responsive source·layout stability를 설계합니다. border-radius 원형 crop이 중요한 얼굴/상품을 잘라내지 않는지 object-fit/object-position을 확인합니다. intrinsic dimension은 layout shift를 줄입니다.",
        "축제 video는 controls를 제공하고 사용자가 시작하게 하며 autoplay가 꼭 필요하면 muted 조건만 보는 것이 아니라 reduced motion·data saving·인지 부담·정책을 검토합니다. 중요한 speech에는 caption, 시각 정보에는 audio description 또는 text transcript를 제공합니다.",
        "iframe이나 third-party video embed는 privacy·cookie·tracking·CSP·sandbox·title·loading 비용이 있습니다. static poster+사용자 동의 후 load pattern을 고려하고 원본 media license와 공개 권리를 확인합니다.",
      ],
      concepts: [
        { term: "alternative text decision", definition: "image의 정보·기능·주변 context를 바탕으로 구체 alt, 빈 alt, caption/long description을 선택하는 판단입니다.", detail: ["file 종류가 아니라 목적 중심입니다.", "인접 text 중복을 피합니다."] },
        { term: "media user control", definition: "사용자가 재생·일시정지·음량·caption·전체화면·motion을 통제하는 capability입니다.", detail: ["autoplay convenience보다 우선합니다.", "keyboard와 assistive tech로 접근 가능해야 합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "screen reader는 '카메라'라고 읽지만 화면에는 microphone이 있고 모집 내용과 혼란이 생긴다.", likelyCause: "alt를 file과 실제 content/function 대조 없이 복사했습니다.", checks: ["image를 숨기고 alt만 읽어 같은 정보를 얻는지 봅니다.", "인접 heading/caption과 중복을 확인합니다.", "장식인지 정보인지 결정 기록을 봅니다."], fix: "context에 맞는 간결한 alt로 교정하거나 장식이면 alt=''를 사용합니다.", prevention: "content owner가 image/alt pair를 함께 승인하고 broken/missing뿐 아니라 의미 일치도 review합니다." },
        { symptom: "page를 열자 video가 반복 재생되어 집중을 방해하고 mobile data를 소모한다.", likelyCause: "autoplay muted loop를 demo 효과로 그대로 production에 사용했습니다.", checks: ["autoplay necessity와 product metric을 확인합니다.", "prefers-reduced-motion/data-saving behavior를 test합니다.", "controls·caption·poster·transcript를 확인합니다."], fix: "기본은 poster+controls와 사용자 시작으로 바꾸고 꼭 필요한 autoplay는 명확한 pause와 preference/data policy를 적용합니다.", prevention: "autoplay media를 architecture/accessibility/performance approval 대상으로 둡니다." },
      ],
    },
    {
      id: "reusable-cards-without-rigid-boxes",
      title: "반복 card는 article/list/link 의미를 유지하고 content 길이에 따라 자연스럽게 늘어나야 합니다",
      lead: "width:20%·height:400px·inline-block보다 data shape와 interaction boundary를 먼저 정의하고 Grid가 남은 배치를 담당합니다.",
      explanations: [
        "강아지 용품 네 항목은 독립 topic article들이고 여가 활동 네 개는 destination으로 이동하는 card link 목록입니다. list 안 article 또는 article 안 link 등 구조를 선택하되 card 전체가 하나의 link면 내부에 별도 button/link를 중첩하지 않습니다.",
        "fixed height는 Latin placeholder에서는 맞아도 실제 한국어 설명·번역·200% text에서 overflow를 만듭니다. min-height가 필요한 visual rhythm인지 검토하고 기본은 content-driven height와 Grid stretch를 사용합니다. line clamp로 핵심 학습 text를 숨기지 않습니다.",
        "card link의 accessible name은 image alt+heading+description이 모두 합쳐져 과도하게 길어질 수 있습니다. heading text가 목적을 충분히 설명하고 description은 link 밖 또는 aria-describedby로 연결하는 pattern을 실제 screen reader에서 test합니다.",
        "href='#'를 네 card에 반복하면 모두 page top으로 이동하고 route 의미가 없습니다. 각 상세 document의 stable URL을 만들고 current/visited/focus state를 제공합니다. 아직 없는 route는 card를 link로 위장하지 않습니다.",
        "image는 loading='lazy'를 고려하되 viewport 첫 주요 image는 무조건 lazy로 지연하지 않습니다. srcset/sizes·intrinsic dimensions·modern format과 실패 fallback을 측정하며 실제 content license를 기록합니다.",
      ],
      concepts: [
        { term: "card interaction boundary", definition: "card에서 어떤 영역이 하나의 link/action인지와 내부에 다른 interactive element가 있는지를 정한 계약입니다.", detail: ["nested interactive content를 피합니다.", "focus indicator가 전체 clickable 영역을 보여야 합니다."] },
        { term: "content-driven sizing", definition: "고정 높이보다 실제 text/media가 필요한 공간에 따라 component block size가 늘어나는 layout입니다.", detail: ["translation·zoom·dynamic state에 강합니다.", "Grid로 row alignment를 보조할 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "responsive-activity-cards",
          title: "실제 URL·heading·alt·focus를 가진 반응형 활동 card 목록",
          language: "html",
          filename: "activity-cards.html",
          purpose: "원본 여가 card의 placeholder href·alt 누락·fixed 1200/400px를 semantic list/article과 responsive Grid로 개선합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>여가 활동 안내</title>\n  <style>\n    * { box-sizing: border-box; }\n    body { margin: 0; font-family: system-ui, sans-serif; line-height: 1.6; }\n    main { inline-size: min(72rem, 100% - 2rem); margin-inline: auto; }\n    .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(16rem, 100%), 1fr)); gap: 1rem; padding: 0; list-style: none; }\n    .card { block-size: 100%; border: 1px solid #aaa; border-radius: .75rem; overflow: hidden; }\n    .card a { display: grid; block-size: 100%; color: #17212b; text-decoration-thickness: .1em; text-underline-offset: .2em; }\n    .card a:focus-visible { outline: .25rem solid #a43d00; outline-offset: .2rem; }\n    .card img { inline-size: 100%; block-size: auto; aspect-ratio: 3 / 2; object-fit: cover; }\n    .card div { padding: 1rem; }\n  </style>\n</head>\n<body>\n  <main>\n    <h1>여가 활동 안내</h1>\n    <p>관심 있는 활동을 선택해 준비물과 접근 정보를 확인하세요.</p>\n    <ul class=\"cards\">\n      <li><article class=\"card\"><a href=\"activities/city.html\"><img src=\"images/city.webp\" width=\"600\" height=\"400\" alt=\"도심 건축물을 둘러보는 사람들\"><div><h2>도심 건축 투어</h2><p>대중교통으로 이동하는 반나절 코스입니다.</p></div></a></article></li>\n      <li><article class=\"card\"><a href=\"activities/sea.html\"><img src=\"images/sea.webp\" width=\"600\" height=\"400\" alt=\"완만한 모래 해변과 잔잔한 바다\"><div><h2>바다 산책</h2><p>무장애 이동 경로와 날씨 확인 방법을 안내합니다. 설명이 길어져도 card가 잘리지 않습니다.</p></div></a></article></li>\n    </ul>\n  </main>\n</body>\n</html>",
          walkthrough: [
            { lines: "8-16", explanation: "container는 viewport를 넘지 않고 auto-fit/minmax Grid가 card 폭에 따라 열 수를 바꿉니다. fixed height를 두지 않습니다." },
            { lines: "12-15", explanation: "article과 link가 card 높이를 채우며 keyboard focus outline이 전체 clickable boundary를 보여 줍니다." },
            { lines: "24-27", explanation: "ul의 각 li에 독립 article/link가 있고 실제 상대 URL, intrinsic image dimensions, context alt, 고유 h2를 제공합니다." },
          ],
          run: { environment: ["현대 browser", "images/city.webp와 images/sea.webp fixture", "320px 및 1200px viewport"], command: "browser에서 activity-cards.html을 열고 viewport 변경 및 Tab 이동" },
          output: { value: "1200px: 두 card가 사용 가능한 폭에 맞춰 같은 Grid row에 배치\n320px: card가 한 열로 배치되고 page horizontal overflow 없음\n긴 바다 산책 설명: 잘리지 않고 card 높이가 증가\nTab 1: 도심 건축 투어 card 전체에 focus outline\nTab 2: 바다 산책 card 전체에 focus outline", explanation: ["정확한 pixel 열 수는 font/browser 가용 폭에 따라 달라질 수 있지만 min 16rem과 container 조건을 만족합니다.", "DOM과 focus 순서는 도심→바다로 유지됩니다.", "CSS가 없으면 h1 뒤 ul의 두 link article이 source order로 읽힙니다."] },
          experiments: [
            { change: ".card에 height:400px와 overflow:hidden을 추가하고 text를 두 배로 늘립니다.", prediction: "description 일부가 잘리고 200% text에서 핵심 content를 잃습니다.", result: "content-driven sizing이 학습 자료와 번역에 더 견고합니다." },
            { change: "href를 모두 #으로 바꿉니다.", prediction: "모든 card가 같은 page top으로 이동하고 새 tab/copy link가 의미를 잃습니다.", result: "card는 실제 destination URL이 있을 때 link입니다." },
            { change: "img width/height를 제거하고 느린 network로 load합니다.", prediction: "image 공간이 늦게 생겨 content가 이동할 수 있습니다.", result: "intrinsic dimensions/aspect-ratio는 layout stability에 기여합니다." },
          ],
          sourceRefs: ["web-capstone-pet-source", "web-capstone-travel-source", "whatwg-sections", "wai-images"],
        },
      ],
      diagnostics: [
        { symptom: "한국어 설명을 추가하자 card text가 footer와 겹치거나 잘린다.", likelyCause: "placeholder text 기준의 fixed height와 float layout을 사용했습니다.", checks: ["fixed height·overflow·line clamp를 검색합니다.", "200% text와 longest translation fixture를 적용합니다.", "card scrollHeight/clientHeight를 비교합니다."], fix: "height를 제거하고 content-driven Grid/Flex sizing을 사용하며 필요한 최소/최대 정책을 content와 합의합니다.", prevention: "long-content·zoom·localization fixture를 card visual regression에 포함합니다." },
      ],
    },
    {
      id: "data-form-media-integration",
      title: "한 page의 table·form·media는 서로 다른 data/interaction 계약을 유지하면서 같은 사용자 흐름으로 연결됩니다",
      lead: "모든 정보를 card로 통일하거나 모든 입력을 table로 배치하지 않고 각 구조가 맡는 책임을 분명히 합니다.",
      explanations: [
        "축제 일정은 time element를 포함한 ol, 먹거리 운영 정보는 caption·column/row header가 있는 table, 참가 신청은 form입니다. 세 구조가 같은 visual section 안에 있어도 semantic API는 다릅니다. heading과 설명으로 사용자가 다음 action을 예측하게 합니다.",
        "form에서 축제 프로그램 option value는 table의 visible text와 독립된 stable ID를 사용하고 server가 실제 schedule/availability를 재조회합니다. 화면 가격·시간을 hidden input으로 보내 신뢰하지 않습니다. table과 form data가 같은 server source에서 생성되도록 drift test를 둡니다.",
        "video transcript와 일정 text는 media가 로드되지 않아도 핵심 행사 정보를 제공합니다. link는 상세 document와 registration endpoint를 분리하고, 외부 domain 이동·새 tab이 꼭 필요한 경우 사용자에게 알립니다.",
        "시간은 locale display와 machine datetime/timezone을 분리합니다. '1/27(월)'처럼 연도 없는 일정은 archive에서 언제인지 모호하므로 year와 timezone/venue를 명시합니다. 정확한 당시 data를 모르면 학습용 fixture임을 표시하고 사실처럼 꾸미지 않습니다.",
        "server error가 돌아오면 page heading·form error summary·입력 보존을 제공하고 media/table 위치로 focus를 잃지 않습니다. 성공하면 PRG 결과 URL과 신청 summary를 제공합니다.",
      ],
      concepts: [
        { term: "single source of truth", definition: "표시 table·form option·server validation이 동일한 authoritative schedule/product data에서 파생되는 설계입니다.", detail: ["client hidden value drift를 막습니다.", "cache/version 정책이 필요합니다."] },
        { term: "content resilience", definition: "media·CSS·JavaScript·network 일부가 실패해도 핵심 정보와 task 대체 경로가 남는 성질입니다.", detail: ["transcript와 native link/form이 기여합니다.", "error recovery도 포함합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "표에는 참가 가능으로 보이지만 form 제출 시 마감 또는 다른 가격으로 처리된다.", likelyCause: "table·form option·server rule이 서로 다른 hard-coded data에서 생성되어 drift했습니다.", checks: ["각 화면 값과 option ID의 data source/version을 추적합니다.", "cache stale 시간과 server validation response를 확인합니다.", "hidden price/time을 신뢰하는지 봅니다."], fix: "authoritative server data에서 display와 option을 생성하고 제출 시 ID로 현재 상태를 재검증해 변화 내용을 사용자에게 확인시킵니다.", prevention: "same fixture로 table rendering·FormData·server validation contract를 test하고 version/expiry를 표시합니다." },
      ],
    },
    {
      id: "quality-gates",
      title: "완료는 화면이 뜨는 순간이 아니라 자동 검사와 실제 사용자 경로가 release gate를 통과한 순간입니다",
      lead: "validator 한 종류에 의존하지 않고 구조·link·media·form·responsive·performance·privacy를 층별로 확인합니다.",
      explanations: [
        "정적 검사에서는 HTML syntax/content model, duplicate id, missing lang/title/viewport, image alt/dimensions, empty/placeholder href, form label/name, table caption/header, main count, fragment target를 확인합니다. formatter/linter는 typo를 줄이지만 의미 적합성은 사람 review가 필요합니다.",
        "rendered 검사에서는 accessibility tree의 landmark/heading/name/state, first Tab skip, full keyboard path, focus visible, form invalid/error recovery, 320px·200% text·zoom·forced colors·reduced motion을 확인합니다. mouse 없이 핵심 task를 끝냅니다.",
        "Network/HTTP에서는 broken asset/link, response status/Content-Type/charset, cache policy, form method/payload/redirect, mixed content, third-party request와 privacy를 확인합니다. file/image/video license와 크기·format·loading도 기록합니다.",
        "content 검사에서는 날짜·시간·가격·연락처·link destination과 alt/caption이 실제 content와 일치하는지 owner가 확인합니다. lorem ipsum·Title·메뉴1·href='#' 같은 placeholder를 release blocker로 검색합니다.",
        "성능은 Lighthouse 점수 하나보다 image/video bytes, layout shift, render-blocking asset, mobile network에서 핵심 text/time-to-interactive를 측정합니다. media가 학습 가치를 주지 못하면 제거가 가장 좋은 최적화입니다.",
        "privacy/security 검사에서는 local absolute path·private repo URL·secret·real PII·tracking ID·unsafe HTML injection을 찾습니다. 공개 학습 자료에는 synthetic data와 공개 가능한 provenance만 남깁니다.",
      ],
      concepts: [
        { term: "quality gate", definition: "배포 전에 반드시 통과해야 하는 측정 가능한 검사와 승인 조건입니다.", detail: ["자동 test와 사람 task review를 결합합니다.", "실패 시 owner와 해결 기준이 명확해야 합니다."] },
        { term: "placeholder debt", definition: "임시 제목·Latin text·# link·가짜 data가 완성품에 남아 의미·신뢰·기능을 훼손하는 부채입니다.", detail: ["검색 가능한 pattern으로 관리합니다.", "실제 content owner 승인이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "CI와 accessibility scanner는 통과했지만 card link가 모두 #이고 지원 form은 server endpoint가 없다.", likelyCause: "rule-based 검사만 통과 조건으로 삼고 실제 user task와 destination contract를 검증하지 않았습니다.", checks: ["모든 link를 activation해 목적지를 확인합니다.", "form success/error/refresh user journey를 수행합니다.", "placeholder pattern과 acceptance criteria를 대조합니다."], fix: "실제 task E2E와 content owner sign-off를 gate에 추가하고 구현되지 않은 기능은 명시적으로 제거/상태 표시합니다.", prevention: "release checklist를 syntax·semantic·functional·content·privacy 층으로 분리합니다." },
      ],
    },
    {
      id: "learning-artifact-documentation",
      title: "학습 산출물은 코드뿐 아니라 개념·실행·정확한 결과·실패·근거·다음 연결까지 독립적으로 재현되어야 합니다",
      lead: "몇 달 뒤 중간 topic만 열어도 왜 이렇게 작성했는지와 무엇을 확인해야 하는지 알 수 있게 기록합니다.",
      explanations: [
        "각 capstone page에는 학습 목표, 원본 문제, before/after decision, file tree, 실행 방법, expected output, browser/viewport 조건, accessibility result, known limitation을 함께 제공합니다. screenshot만 두지 않고 실제 HTML을 사용할 수 있게 합니다.",
        "source provenance는 public standard URL과 원본 repository/relative path를 연결하되 private backup URL·local absolute path를 공개하지 않습니다. 원본의 잘못된 설명을 그대로 인용하지 않고 교정 근거와 날짜를 남깁니다.",
        "실행 결과는 '잘 됨'이 아니라 landmark 목록, heading tree, FormData JSON, request/response, viewport overflow 수치처럼 재검증 가능한 값으로 기록합니다. browser별 차이가 있으면 invariant와 variation을 구분합니다.",
        "실패 사례도 학습 자산입니다. alt 불일치, number phone, GET upload, rowspan grid, fixed card height, duplicate main을 symptom→cause→check→fix→prevention 형식으로 남기면 기억이 흐려져도 진단할 수 있습니다.",
        "session 끝에는 다음 CSS module로 link해 동일 semantic HTML을 cascade·box model·Grid로 표현하는 방법을 이어갑니다. 앞 개념을 생략하지 않고 필요한 경우 해당 설명으로 deep link합니다.",
      ],
      concepts: [
        { term: "reproducible learning artifact", definition: "다른 시점·환경에서도 source·명령·조건·expected result를 따라 같은 개념과 동작을 확인할 수 있는 학습 산출물입니다.", detail: ["code와 설명·결과가 함께 있습니다.", "환경 차이와 한계를 기록합니다."] },
        { term: "provenance", definition: "어떤 source와 근거를 읽어 어떤 결론·변경을 만들었는지 추적 가능한 기록입니다.", detail: ["교정 가능성과 신뢰를 높입니다.", "privacy/publication boundary를 지킵니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "나중에 page를 열었지만 왜 table을 form으로 바꿨는지, 어떤 결과가 정상인지 알 수 없다.", likelyCause: "최종 screenshot과 code만 남기고 요구·decision·실행·expected result·근거를 기록하지 않았습니다.", checks: ["README/session 문서에 목적과 command/output이 있는지 봅니다.", "sourceRefs와 변경 근거를 추적합니다.", "처음 보는 사람이 재현해 질문한 지점을 기록합니다."], fix: "decision log, exact run/output, validation evidence, provenance, known limits와 관련 세션 link를 추가합니다.", prevention: "학습 artifact 완료 정의에 documentation/reproduction review를 포함합니다." },
      ],
      expertNotes: [
        "design system component가 semantic element를 prop으로 무제한 받으면 잘못된 조합이 늘 수 있습니다. CardLink·ArticleCard·FormField처럼 user task 중심 API와 invalid nesting test를 설계합니다.",
        "visual regression screenshot은 layout 회귀에 강하지만 semantic/name/focus 회귀를 보지 못합니다. accessibility tree snapshot과 user-event E2E를 별도 유지합니다.",
      ],
    },
  ],
  lab: {
    title: "모집·축제·취미 중 하나를 공개 가능한 독립 학습 mini-site로 완성하기",
    scenario: "원본 예제를 그대로 보여 주는 대신 처음 보는 학습자가 개념·코드·실행 결과·오류 진단을 한 page에서 재현하고 실제 keyboard/mobile 환경에서도 사용할 수 있는 mini-site를 제작합니다.",
    setup: ["원본 6개 file과 관련 image/media의 공개 가능 여부를 read-only로 inventory합니다.", "실제 개인정보·연락처·private URL 대신 synthetic/public fixture를 준비합니다.", "browser·keyboard·320px/desktop·200% zoom·reduced motion·Network throttling 환경을 준비합니다."],
    steps: [
      "대상 page의 user task·content inventory·semantic mismatch·privacy/license risk 표를 작성합니다.",
      "각 requirement를 관찰 가능한 acceptance criterion과 자동/수동 검사에 연결합니다.",
      "CSS 없는 semantic wireframe으로 lang/title/heading/landmark/list/table/form/media/link 구조를 완성합니다.",
      "모든 image alt/size, video controls/transcript, link href, table headers, form label/name/action을 content owner 관점에서 검증합니다.",
      "mobile-first Grid/Flex style을 더하고 fixed content height·positive tabindex·CSS reorder를 피합니다.",
      "320px·200% zoom·keyboard first Tab/전체 task·CSS/JS off·slow network에서 실행 결과를 기록합니다.",
      "HTML/internal link/privacy/placeholder/rendered accessibility/FormData 또는 Network test를 자동화합니다.",
      "before/after decision, exact run/output, source provenance, known limitations, 다음 CSS 학습 link를 문서화합니다.",
    ],
    expectedResult: ["CSS/JavaScript 일부가 실패해도 핵심 정보와 link/form fallback이 남습니다.", "heading·landmark·table/form/media 관계를 중간 page만 열어도 이해할 수 있습니다.", "모든 keyboard focus가 보이고 320px·200% zoom에서 content가 잘리지 않습니다.", "placeholder href/text·실제 PII·private path/URL·secret이 0건입니다.", "실행 결과가 JSON/landmark tree/Network status처럼 정확히 기록됩니다.", "source 근거와 교정 이유가 public-safe relative provenance로 추적됩니다."],
    cleanup: ["실험용 autoplay·debug outline·fake endpoint·large media와 생성된 개인정보 fixture를 제거합니다.", "배포 artifact에 원본 private path·backup URL·license 불명 asset이 포함되지 않았는지 다시 검사합니다."],
    extensions: ["동일 semantic baseline에 CSS cascade·box model·Grid 세 가지 style evolution을 별도 commit으로 적용합니다.", "Playwright+axe 계열 도구로 user task와 accessibility rule을 CI에 추가하되 수동 review 범위를 문서화합니다.", "실제 GitHub Pages 배포 preview에서 status/content type/cache/broken route/404/OG metadata까지 검증합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "방송국 모집 page의 명백한 semantic·content 오류를 고치고 근거를 기록하세요.", requirements: ["lang=ko와 구체 title/heading 계층을 사용합니다.", "mic image의 실제 목적에 맞게 alt를 교정합니다.", "모집 metadata를 적합한 list/dl과 time으로 표현합니다.", "지원 방법의 실제 link/action을 구현하거나 미구현 상태를 text로 밝힙니다.", "before/after 검증 결과를 기록합니다."], hints: ["카메라라는 alt와 mic.jpg를 비교합니다.", "bold/i는 의미 관계 전체를 대신하지 않습니다."], expectedOutcome: "CSS 없이도 모집 정보와 지원 경로가 이해되고 image 대체 text가 실제 content와 일치합니다.", solutionOutline: ["content inventory와 mismatch 표를 먼저 만듭니다.", "heading/list/link/image를 순서대로 수정합니다."] },
    { difficulty: "응용", prompt: "여가 card page를 실제 route가 있는 responsive activity catalog로 완성하세요.", requirements: ["ul/li/article/link와 고유 h2를 사용합니다.", "href=#·alt 누락·fixed 1200/400px를 제거합니다.", "intrinsic image size·responsive Grid·focus-visible을 적용합니다.", "long Korean/English text·320px·200% zoom을 test합니다.", "card accessible name과 nested interactive 여부를 검토합니다."], hints: ["card 전체 link 안에 다른 button을 넣지 않습니다.", "content height를 고정하지 않습니다."], expectedOutcome: "모든 card가 실제 상세 URL로 이동하고 long content가 잘리지 않으며 DOM/focus 순서가 유지됩니다.", solutionOutline: ["route/content data를 먼저 확정합니다.", "semantic list 후 Grid enhancement를 적용합니다."] },
    { difficulty: "설계", prompt: "세 page로 구성된 공개 HTML 학습 mini-site의 release specification과 CI gate를 설계하세요.", requirements: ["페이지별 user task·semantic wireframe·content schema를 정의합니다.", "image/video/table/form의 accessibility·performance·security/privacy contract를 포함합니다.", "HTML/link/placeholder/privacy/rendered user task 자동 검사를 설계합니다.", "keyboard/screen reader/content owner/license 수동 review를 구분합니다.", "정확한 실행 결과·provenance·known limits 문서 format을 정의합니다."], hints: ["scanner 점수만으로 실제 href/action을 보장할 수 없습니다.", "공개 artifact와 local evidence 경계를 명시합니다."], expectedOutcome: "다른 사람이 구현·검증·배포·복습할 수 있는 end-to-end 학습 site 품질 계약이 완성됩니다.", solutionOutline: ["acceptance criterion→test→evidence→owner matrix를 만듭니다.", "실패 시 deploy를 막는 gate와 warning을 구분합니다."] },
  ],
  reviewQuestions: [
    { question: "지원 양식처럼 보이는 빈 table을 왜 form으로 바꿔야 하나요?", answer: "사용자가 값을 입력·검증·제출하는 task이므로 label/control/form semantics와 HTTP contract가 필요합니다. table은 행·열 data 비교용입니다." },
    { question: "원본 화면을 그대로 복제하지 않는 이유는 무엇인가요?", answer: "학습 의도는 보존하되 잘못된 lang·alt·placeholder·fixed layout·semantic mismatch를 현재 표준과 사용자 task 기준으로 교정해야 하기 때문입니다." },
    { question: "모든 반복 box를 article로 만들면 되나요?", answer: "아닙니다. 별도로 배포해도 자체 의미가 유지되는 composition인지 판단하고 단순 목록 항목이면 li/div가 적합할 수 있습니다." },
    { question: "video는 muted면 autoplay해도 항상 괜찮나요?", answer: "아닙니다. 재생 정책 통과와 사용자 접근성·인지 부담·data 사용·reduced motion·pause control은 별도 문제입니다." },
    { question: "card의 href=#는 임시로 남겨도 되나요?", answer: "release에는 안 됩니다. 실제 destination을 구현하거나 interactive link로 보이지 않게 상태를 명시해야 합니다." },
    { question: "fixed height가 card를 가지런하게 만들지 않나요?", answer: "짧은 fixture에서는 그렇지만 실제 text·번역·zoom에서 content를 자를 수 있습니다. content-driven size와 Grid alignment를 사용합니다." },
    { question: "자동 accessibility 검사만 통과하면 배포해도 되나요?", answer: "아닙니다. 실제 keyboard task, screen reader structure, content 정확성, destination/action, privacy/license는 사람과 E2E 검증이 필요합니다." },
    { question: "학습 자료의 실행 결과는 어떻게 기록해야 하나요?", answer: "'성공'이 아니라 command/environment와 exact FormData·landmark/heading tree·HTTP status·overflow 여부처럼 다시 확인 가능한 결과를 기록합니다." },
    { question: "로컬 원본 provenance를 공개할 때 주의할 점은 무엇인가요?", answer: "private backup URL·absolute local path·PII를 노출하지 않고 repository 설명과 relative path, 공개 표준 URL, 어떤 부분에 사용했는지를 기록합니다." },
  ],
  completionChecklist: [
    "원본 6개 page의 user task·content inventory·문제·보존할 의도를 증거표로 만들었다.",
    "CSS 없는 semantic wireframe에서 heading·landmark·link·table·form·media 관계를 검증했다.",
    "image alt/dimension과 video controls/caption/transcript/autoplay 정책을 content별로 결정했다.",
    "blank table form·href=#·placeholder text·fixed content height·wrong lang/alt를 제거했다.",
    "320px·200% zoom·keyboard·CSS/JS off·slow network에서 핵심 task를 완료했다.",
    "HTML·internal link·FormData/HTTP·accessible name·privacy/placeholder 검사를 자동화했다.",
    "실제 PII·secret·private/backup URL·absolute local path·license 불명 asset을 공개 artifact에서 제거했다.",
    "개념·source·실행 방법·정확한 결과·diagnostic·known limits·다음 학습 link를 문서화했다.",
  ],
  nextSessions: ["css-01-apply-cascade"],
  sources: [
    { id: "web-capstone-recruit-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day02/ex14_test01.html", usedFor: ["모집 heading/text/list", "기간·분야·지원 방법", "mic image alt"], evidence: "방송국 모집 page의 전체 content와 mic.jpg/alt 불일치를 audit해 semantic 모집 안내와 image decision으로 교정했습니다." },
    { id: "web-capstone-blank-form-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day02/ex15_test02.html", usedFor: ["개인정보 blank table", "rowspan·colspan", "지원 양식"], evidence: "종이식 빈 table의 visual intent를 실제 web input task와 분리해 form/label/fieldset capstone으로 재설계했습니다." },
    { id: "web-capstone-festival-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day02/ex16_test03.html", usedFor: ["축제 설명", "video autoplay", "일정 ol", "먹거리 table", "자세한 정보 text"], evidence: "축제 page의 media/list/table/link 구조를 audit해 user-controlled video, machine time, caption/header table, real link contract로 확장했습니다." },
    { id: "web-capstone-image-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex18_test01.html", usedFor: ["곰 image", "border-radius", "shadow", "style artifact"], evidence: "원형 image style 실습을 intrinsic size·responsive crop·alt/content purpose와 분리해 capstone media checklist에 반영했습니다." },
    { id: "web-capstone-pet-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex19_test02.html", usedFor: ["section/article", "강아지 용품", "float 2-column", "fixed article/footer height"], evidence: "네 article의 독립 topic 구조를 보존하면서 content-driven Grid·heading·zoom 검증으로 현대화했습니다." },
    { id: "web-capstone-travel-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day04/ex20_test03.html", usedFor: ["여가 card", "inline-block", "fixed container/card", "href placeholder", "image alt 누락"], evidence: "네 travel card의 실제 source를 audit해 list/article/real link/alt/intrinsic dimensions/responsive Grid example로 재구성했습니다." },
    { id: "whatwg-sections", repository: "WHATWG HTML Standard", path: "multipage/sections.html", publicUrl: "https://html.spec.whatwg.org/multipage/sections.html", usedFor: ["heading·section·article", "page landmark shell", "header/footer"], evidence: "semantic wireframe과 반복 article 구조를 living standard의 section semantics에 맞춰 검증했습니다." },
    { id: "whatwg-forms", repository: "WHATWG HTML Standard", path: "multipage/forms.html", publicUrl: "https://html.spec.whatwg.org/multipage/forms.html", usedFor: ["form·label·input", "fieldset·legend", "submission controls"], evidence: "blank table을 실제 application form으로 바꾸는 element와 validation contract의 기준으로 사용했습니다." },
    { id: "whatwg-tables", repository: "WHATWG HTML Standard", path: "multipage/tables.html", publicUrl: "https://html.spec.whatwg.org/multipage/tables.html", usedFor: ["data table boundary", "caption·header", "span"], evidence: "지원 form과 축제 먹거리 data에서 table을 사용할/사용하지 않을 경계를 검증했습니다." },
    { id: "wai-page-structure", repository: "W3C Web Accessibility Initiative", path: "tutorials/page-structure/", publicUrl: "https://www.w3.org/WAI/tutorials/page-structure/", usedFor: ["heading", "landmark", "skip/bypass", "content structure"], evidence: "capstone page shell의 heading·region·keyboard navigation acceptance criteria에 반영했습니다." },
    { id: "wai-forms", repository: "W3C Web Accessibility Initiative", path: "tutorials/forms/", publicUrl: "https://www.w3.org/WAI/tutorials/forms/", usedFor: ["label", "grouping", "instruction", "validation", "notification"], evidence: "지원 form의 이름·group·필수 안내·error recovery 기준으로 사용했습니다." },
    { id: "wai-images", repository: "W3C Web Accessibility Initiative", path: "tutorials/images/", publicUrl: "https://www.w3.org/WAI/tutorials/images/", usedFor: ["image purpose", "alt decision", "functional/decorative image"], evidence: "mic/bear/travel image가 정보·기능·장식 중 무엇인지 판단하고 alt를 고르는 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 6,
    filesUsed: 6,
    uncoveredNotes: [
      "원본 6개는 개별 HTML/CSS 기능을 결과물로 조합하는 좋은 capstone 재료입니다. 실제 route/action, accessibility tree, responsive/performance/privacy gate와 reproducible documentation은 공식 표준에 따라 보강했습니다.",
      "이 세션은 HTML 구조를 완성합니다. 세밀한 cascade·box model·Flex/Grid·animation/container query는 다음 CSS module, JavaScript form enhancement와 automated browser test는 JavaScript/DevOps 과정에서 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
