import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["html-08-form-controls-validation"],
  slug: "html-08-form-controls-validation",
  courseId: "web",
  moduleId: "01-html-document-forms",
  order: 8,
  title: "입력 컨트롤, 레이블, 내장 검증과 파일 업로드",
  subtitle: "text·choice·date·file control을 목적에 맞게 고르고 label·fieldset·instruction·error를 연결해 keyboard·mobile·server에서도 견고한 form을 만듭니다.",
  level: "중급",
  estimatedMinutes: 190,
  coreQuestion: "사용자가 무엇을 어떤 형식으로 입력해야 하는지 이해하고 오류에서 회복하게 하면서, browser의 control·validation 기능과 server의 최종 검증 책임을 어떻게 나눌까요?",
  summary: "주문·회원가입·예약·지원서 원본 6개를 모두 감사해 label/for/id, fieldset/legend, input type, checkbox/radio/select, textarea, date/time/range, file, button/reset/image를 체계화합니다. required·min/max/step·minlength/maxlength·pattern·multiple과 ValidityState를 실제 출력으로 확인하고, phone에 number를 쓰거나 number에 pattern/maxlength를 기대하는 오류를 교정합니다. placeholder를 label로 쓰지 않으며 accessible instruction/error, autocomplete, data minimization, multipart upload의 server 검증과 안전한 storage까지 초보→전문가 흐름으로 연결합니다.",
  objectives: [
    "입력 data의 의미에 맞춰 text·email·tel·number·date·checkbox·radio·select·textarea·file control을 선택할 수 있다.",
    "visible label과 control을 명시적으로 연결하고 관련 choice를 fieldset·legend로 group할 수 있다.",
    "required·length·range·step·pattern constraint의 적용 대상과 ValidityState를 설명할 수 있다.",
    "placeholder·color·위치에만 의존하지 않고 instruction과 field error를 programmatically 연결할 수 있다.",
    "client validation의 UX 역할과 server validation·authorization의 보안 책임을 분리할 수 있다.",
    "file upload에서 multipart request부터 size/type/content/name/storage 검증까지 위협 경계를 설계할 수 있다.",
  ],
  prerequisites: [
    { title: "form 제출이 HTTP 요청 파라미터가 되는 과정", reason: "control의 name/value가 entry list와 HTTP request가 되는 과정을 바탕으로 control별 state와 validation을 깊게 다룹니다.", sessionSlug: "html-07-form-http-request" },
  ],
  keywords: ["label", "fieldset", "legend", "input type", "checkbox", "radio", "select", "textarea", "constraint validation", "ValidityState", "pattern", "autocomplete", "file upload", "multipart/form-data"],
  chapters: [
    {
      id: "label-instruction-group",
      title: "label은 입력 목적의 지속적인 이름이고 fieldset·legend는 여러 control이 공유하는 질문입니다",
      lead: "placeholder가 사라지거나 layout이 바뀌어도 각 control과 choice group의 목적·형식·필수 여부를 알 수 있어야 합니다.",
      explanations: [
        "명시적 label은 for 값과 control의 고유 id를 정확히 일치시킵니다. 원본의 배송 주소처럼 <label for='u_addr'>와 id='u_addr'가 연결되면 text를 눌러도 input에 focus되고 보조기술이 accessible name으로 사용합니다. label 안에 control을 감싸는 implicit pattern도 가능하지만 복잡한 layout과 자동 test에는 명시적 연결이 읽기 쉽습니다.",
        "id와 name은 별개입니다. id는 label과 DOM 관계, name은 제출 key입니다. 원본 일부 이름·예약 input은 id만 있고 name이 없어 제출되지 않습니다. 학습용 화면에서 보이는 것과 실제 server data contract를 반드시 Network로 함께 확인합니다.",
        "placeholder는 value가 생기면 사라지고 contrast가 낮을 수 있으며 예시인지 필수 형식인지 모호합니다. visible label을 유지하고 '010-1234-5678 형식' 같은 instruction은 control 가까이에 text로 두어 aria-describedby로 연결합니다. placeholder는 보조 예시로만 사용합니다.",
        "radio/checkbox group처럼 여러 option이 하나의 질문에 답하면 fieldset과 legend를 사용합니다. 각 option에도 개별 label이 필요합니다. legend 안에 heading을 넣어 style을 얻기보다 문서 heading과 group legend의 역할을 분리하고 CSS class로 표현합니다.",
        "필수 표시는 색과 별표만 두지 말고 label 또는 공통 instruction에 '필수'라는 text를 제공합니다. required attribute가 machine state를 제공하고, optional field가 적다면 '선택'을 표시하는 방식이 더 간결할 수 있습니다.",
      ],
      concepts: [
        { term: "accessible name", definition: "보조기술이 control의 목적을 사용자에게 제시할 때 계산하는 이름입니다.", detail: ["대부분 visible label이 가장 견고합니다.", "placeholder는 label 대체가 아닙니다."] },
        { term: "accessible description", definition: "name을 보충하는 형식·도움말·상태 설명이며 aria-describedby 등으로 연결할 수 있습니다.", detail: ["name을 반복하지 않습니다.", "오류가 생기면 error text도 description 관계에 포함할 수 있습니다."] },
        { term: "fieldset/legend", definition: "관련 form control을 하나의 group으로 묶고 공유 질문 또는 제목을 제공하는 native HTML 구조입니다.", detail: ["radio·checkbox group에 특히 중요합니다.", "각 option label을 대신하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "화면에서는 '이메일' 옆 input이 보이지만 label text를 눌러도 focus되지 않고 screen reader는 'edit text, blank'로 읽는다.", likelyCause: "label for와 input id가 없거나 값이 일치하지 않고 placeholder만 사용했습니다.", checks: ["label의 htmlFor와 control.id를 비교합니다.", "Accessibility tree의 computed name을 봅니다.", "같은 id 중복을 검사합니다."], fix: "고유 id를 주고 visible label for와 정확히 연결하며 형식 도움말은 별도 text로 둡니다.", prevention: "모든 rendered control에 non-empty accessible name과 unique id를 단언하는 test를 둡니다." },
      ],
    },
    {
      id: "choose-input-type-by-data",
      title: "input type은 겉모양이 아니라 값의 의미·keyboard·parsing·validation 계약으로 고릅니다",
      lead: "전화번호나 우편번호가 숫자 문자로만 보인다고 number를 쓰면 leading zero·pattern·mobile keyboard·spinner behavior가 어긋납니다.",
      explanations: [
        "text는 자유로운 한 줄 문자열, email은 email address syntax와 mobile keyboard hint, tel은 전화번호 문자열, url은 URL, search는 검색어 purpose를 나타냅니다. tel은 세계 전화 형식이 다양해 browser가 특정 문법을 강제하지 않으므로 product가 허용하는 format을 instruction·server normalization과 함께 설계합니다.",
        "number는 수량·가격·온도처럼 산술 magnitude를 가진 값에 씁니다. 전화번호·주민 식별자·우편번호·카드번호는 숫자로 계산하지 않고 leading zero와 separator가 중요하므로 text/tel이 적합합니다. inputmode='numeric'으로 mobile keyboard를 hint하고 pattern/minlength/maxlength를 적용할 수 있습니다.",
        "원본 연락처3의 type=number에 pattern을 두었지만 pattern은 number state에 적용되지 않습니다. number에는 min·max·step을 사용하고 browser가 유효한 number string을 관리합니다. maxlength와 size도 number에 기대한 방식으로 적용되지 않으므로 domain에 맞는 type 선택이 먼저입니다.",
        "date·month·week·time·datetime-local은 locale별 UI를 제공하지만 submitted value 형식은 정해진 machine-readable string입니다. datetime-local에는 timezone이 포함되지 않습니다. 예약 시각은 사용자의 zone 또는 장소 zone을 별도 contract로 받아 instant로 변환해야 합니다.",
        "password는 화면 masking을 제공하지만 값 암호화나 강도 보장을 하지 않습니다. HTTPS와 server password hashing이 필요하고 paste/password manager를 막지 않습니다. autocomplete='current-password'와 'new-password', username/email 같은 token을 올바르게 제공해 password manager와 autofill을 돕습니다.",
      ],
      concepts: [
        { term: "input mode", definition: "사용자 agent가 적합한 virtual keyboard를 고르는 데 주는 hint이며 inputmode attribute로 선언합니다.", detail: ["validation type과 별개입니다.", "inputmode=numeric이어도 임의 request를 막지 않습니다."] },
        { term: "machine value", definition: "date/time/number control이 UI locale과 별개로 form submission과 DOM value에 제공하는 표준 문자열 또는 number 표현입니다.", detail: ["보이는 날짜 순서와 submitted YYYY-MM-DD가 다를 수 있습니다.", "server가 다시 parse·range check합니다."] },
        { term: "autocomplete token", definition: "control이 받는 개인정보·주소·credential field의 의미를 user agent에 알려 autofill을 돕는 standardized token입니다.", detail: ["단순 on/off보다 구체적 token이 유용합니다.", "민감 field와 privacy 정책을 고려합니다."] },
      ],
      codeExamples: [
        {
          id: "purpose-driven-contact-controls",
          title: "전화번호·수량·날짜를 의미에 맞는 control로 작성하기",
          language: "html",
          filename: "delivery-controls.html",
          purpose: "겉보기 문자가 아닌 domain data에 따라 tel/text, number, date를 구분하고 exact FormData를 관찰합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>배송 정보</title></head>\n<body>\n  <main>\n    <h1>배송 정보</h1>\n    <form id=\"delivery\">\n      <p>모든 항목은 필수입니다.</p>\n\n      <label for=\"phone\">연락처</label>\n      <input id=\"phone\" name=\"phone\" type=\"tel\" inputmode=\"numeric\"\n             autocomplete=\"tel\" required pattern=\"01[016789]-[0-9]{3,4}-[0-9]{4}\"\n             aria-describedby=\"phone-help\">\n      <p id=\"phone-help\">예: 010-1234-5678</p>\n\n      <label for=\"quantity\">수량</label>\n      <input id=\"quantity\" name=\"quantity\" type=\"number\" min=\"1\" max=\"10\" step=\"1\" value=\"2\" required>\n\n      <label for=\"date\">배송 희망일</label>\n      <input id=\"date\" name=\"deliveryDate\" type=\"date\" min=\"2026-07-13\" max=\"2026-07-31\" value=\"2026-07-15\" required>\n\n      <button>확인</button>\n    </form>\n    <pre id=\"result\"></pre>\n    <script>\n      document.querySelector('#delivery').addEventListener('submit', (event) => {\n        event.preventDefault();\n        const entries = [...new FormData(event.currentTarget).entries()];\n        document.querySelector('#result').textContent = JSON.stringify(Object.fromEntries(entries), null, 2);\n      });\n    </script>\n  </main>\n</body>\n</html>",
          walkthrough: [
            { lines: "9-14", explanation: "전화번호는 tel 문자열로 두어 leading zero를 보존하고 inputmode·autocomplete·pattern·visible instruction을 제공합니다." },
            { lines: "16-17", explanation: "산술 수량은 number이며 min/max/step으로 1~10 정수를 요구합니다." },
            { lines: "19-20", explanation: "date UI가 locale마다 달라도 value는 2026-07-15 형식으로 전송됩니다." },
            { lines: "24-29", explanation: "valid submit을 가로채 FormData를 object로 출력합니다. server 전송 예제가 아니라 entry 확인용이며 server validation은 여전히 필요합니다." },
          ],
          run: { environment: ["현대 browser", "2026-07-15가 허용 범위인 fixture"], command: "browser에서 delivery-controls.html을 열고 연락처에 010-1234-5678을 입력한 뒤 확인" },
          output: { value: "{\n  \"phone\": \"010-1234-5678\",\n  \"quantity\": \"2\",\n  \"deliveryDate\": \"2026-07-15\"\n}", explanation: ["number와 date도 FormData에서는 string entry입니다.", "전화번호의 첫 0과 hyphen이 그대로 유지됩니다.", "browser UI 표시 날짜는 locale에 따라 달라도 value는 ISO-like date string입니다."] },
          experiments: [
            { change: "phone type을 number로 바꾸고 같은 pattern을 둡니다.", prediction: "hyphen을 입력할 수 없고 patternMismatch가 전화 format을 검증하지 않습니다.", result: "전화번호는 수량이 아니므로 tel/text가 적합합니다." },
            { change: "quantity에 2.5를 입력합니다.", prediction: "step=1의 기준에 맞지 않으면 stepMismatch로 submit이 막힙니다.", result: "number domain은 min/max뿐 아니라 step grid를 가집니다." },
            { change: "date value를 2026-08-01로 DevTools에서 설정합니다.", prediction: "rangeOverflow가 true가 될 수 있고 정상 interactive submit이 막힙니다.", result: "client range는 UX 보조이며 direct request는 server가 다시 거부해야 합니다." },
          ],
          sourceRefs: ["web-controls-contact-source", "web-controls-date-file-source", "whatwg-input"],
        },
      ],
      diagnostics: [
        { symptom: "010으로 시작한 전화번호가 10으로 바뀌고 pattern도 동작하지 않는다.", likelyCause: "전화번호에 type=number를 사용했습니다.", checks: ["산술 연산 대상인지 식별 문자열인지 구분합니다.", "input.validity.patternMismatch를 확인합니다.", "leading zero와 separator requirement를 확인합니다."], fix: "type=tel 또는 text와 적절한 inputmode·pattern·instruction을 사용하고 server에서 normalize/validate합니다.", prevention: "field schema에 data meaning, canonical string, display format, input type을 함께 기록합니다." },
      ],
    },
    {
      id: "choice-controls",
      title: "checkbox·radio·select는 선택 수와 option 의미를 name/value/state로 정확히 모델링합니다",
      lead: "복수 선택과 단일 선택, 아무것도 선택하지 않은 상태, 기본값과 사용자의 명시적 동의를 서로 구분합니다.",
      explanations: [
        "checkbox는 각각 독립 boolean이거나 같은 name의 복수 선택 집합입니다. 원본 상품처럼 prod name을 반복하고 각 value를 s_3·s_5처럼 명시하면 checked된 것만 여러 entry가 됩니다. 하나도 선택하지 않으면 key 자체가 없으므로 server에서 empty list로 normalize합니다.",
        "radio는 같은 name의 group에서 하나만 checked됩니다. 선물 포장 y/n처럼 모든 사용자가 하나를 골라야 하면 fieldset/legend와 required를 한 radio에 둘 수 있습니다. 민감한 동의나 마케팅 수신을 default checked하면 사용자의 명시적 선택을 왜곡할 수 있으므로 법·product policy에 맞게 기본 상태를 결정합니다.",
        "select single은 선택 option 하나, multiple은 여러 selected option을 같은 name으로 제출합니다. option value를 생략하면 text가 value가 될 수 있지만 visible wording 변경이 API contract를 깨뜨리므로 stable domain value를 명시합니다.",
        "multiple select의 Ctrl/Command 선택은 발견하기 어렵고 mobile behavior가 다릅니다. 긴 복수 선택에는 checkbox group, searchable multi-select를 고려하되 custom widget은 keyboard·focus·name/role/value·form integration을 구현해야 합니다. native control을 먼저 검토합니다.",
        "'선택하세요' placeholder option은 value=''와 disabled/selected 조합 및 required를 신중히 사용합니다. 실제 empty 선택 허용 여부를 server contract와 맞추고 option text만 보고 의미를 추정하지 않습니다.",
      ],
      concepts: [
        { term: "selection cardinality", definition: "사용자가 선택해야 하는 option 수의 규칙입니다. 0..n은 checkbox, 정확히/최대 하나는 radio 또는 single select가 주로 맞습니다.", detail: ["required와 server rule을 함께 정의합니다.", "visual toggle 모양이 기준은 아닙니다."] },
        { term: "domain value", definition: "server contract에서 option을 안정적으로 식별하는 machine value입니다.", detail: ["visible label과 분리합니다.", "번역이나 문구 수정으로 바뀌지 않아야 합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "상품을 여러 개 선택했는데 server에는 마지막 또는 첫 값 하나만 저장된다.", likelyCause: "같은 name의 repeated entry를 scalar로 binding하거나 getParameter 하나만 사용했습니다.", checks: ["Network Form Data에서 prod가 여러 번 있는지 확인합니다.", "server DTO가 list/array인지 봅니다.", "unknown·duplicate value policy를 확인합니다."], fix: "server에서 array/list로 받고 allowlist·deduplication·선택 개수 rule을 검증합니다.", prevention: "0개·1개·여러 개·중복·unknown value fixture를 contract test에 둡니다." },
        { symptom: "radio option text를 눌러도 선택되지 않고 group 질문이 screen reader에 반복되지 않는다.", likelyCause: "각 input label과 group fieldset/legend가 없습니다.", checks: ["option label click과 focus를 test합니다.", "radio name이 동일한지 확인합니다.", "accessibility tree에서 group name을 봅니다."], fix: "fieldset/legend로 공유 질문을, 각 radio의 label로 option 이름을 제공합니다.", prevention: "choice component에 group accessible name과 option accessible name assertion을 추가합니다." },
      ],
    },
    {
      id: "textarea-range-buttons",
      title: "textarea·range·button은 값 표현과 상호작용 결과를 사용자가 확인할 수 있게 설계합니다",
      lead: "control이 native라고 해서 목적·현재 값·결과 알림이 자동으로 충분한 것은 아닙니다.",
      explanations: [
        "textarea는 여러 줄 plain text control입니다. 초기 value는 value attribute가 아니라 opening/closing tag 사이 text이며 DOM에서는 value property를 사용합니다. cols/rows는 초기 크기 hint일 뿐 responsive width·resize·max length·server size limit을 CSS와 validation으로 별도 관리합니다.",
        "range는 정확한 숫자를 직접 입력하기보다 범위 안 상대값을 빠르게 고를 때 적합합니다. 현재 숫자와 min/max/단위를 visible output에 보여 주고 label/description을 연결합니다. 정밀 금액이나 접근성 요구가 높은 값은 number input을 함께 제공하거나 더 적합한 control을 선택합니다.",
        "button element는 text와 richer content를 가질 수 있고 기본 type이 form 안에서 submit이므로 action button에는 type='button', 제출에는 type='submit'을 명시합니다. 단순 <input type=button>은 JavaScript 없이 아무 제출도 하지 않습니다.",
        "reset은 현재 입력을 빈 값이 아니라 document의 initial/default state로 되돌리며 실수로 전체 작업을 잃게 할 수 있습니다. 긴 form에서는 제거하거나 confirmation/undo를 제공하고 submit button과 멀리 둡니다.",
        "input type=image는 image submitter이며 alt가 accessible name을 제공하고 click 좌표가 name.x/name.y 등으로 제출될 수 있습니다. 단순 장식 login image 대신 button과 CSS/background/image를 사용하면 예측 가능한 parameter contract가 됩니다.",
      ],
      concepts: [
        { term: "initial value", definition: "page가 load될 때 markup에서 정한 기본값이며 reset이 돌아가는 기준입니다.", detail: ["현재 value와 다릅니다.", "checkbox의 checked attribute와 checked property도 구분됩니다."] },
        { term: "output feedback", definition: "range 계산·동적 선택 결과처럼 control 변화의 결과를 사용자가 perceivable하게 확인하는 text입니다.", detail: ["단순 innerText 갱신만으로 announce가 충분한지 test합니다.", "과도한 live announcement를 피합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "취소 button을 눌렀더니 작성한 지원 동기 전체가 사라지고 복구할 수 없다.", likelyCause: "type=reset을 일반 취소 action처럼 제공했습니다.", checks: ["reset이 initial value로 되돌리는 범위를 확인합니다.", "autosave/undo가 있는지 봅니다.", "submit과 reset의 위치·style이 혼동되는지 user test합니다."], fix: "불필요한 reset을 제거하고 navigation 취소는 link/button+confirmation, 긴 text는 draft autosave/undo를 제공합니다.", prevention: "destructive action은 명확한 label·거리·confirmation·recovery를 갖추도록 component policy를 둡니다." },
      ],
    },
    {
      id: "constraint-validation-model",
      title: "내장 constraint validation은 type·required·length·range·step·pattern을 ValidityState로 구분합니다",
      lead: "한 개의 '유효/무효'가 아니라 어떤 constraint가 실패했는지 읽고 사용자가 고칠 수 있는 message와 server rule로 연결합니다.",
      explanations: [
        "required는 비어 있으면 valueMissing, email/url type syntax는 typeMismatch, pattern은 patternMismatch, minlength/maxlength는 tooShort/tooLong, number/date의 min/max는 rangeUnderflow/rangeOverflow, step grid는 stepMismatch를 만듭니다. badInput은 browser UI가 값으로 변환하지 못한 상태를 나타낼 수 있습니다.",
        "pattern은 적용되는 text-like input에서 value 전체가 regular expression과 일치해야 합니다. 원본처럼 ^와 $를 넣은 예도 동작할 수 있지만 HTML pattern 자체가 전체 값 match 의미를 가지므로 중복 anchor에 기대지 않습니다. pattern이 빈 값 자체를 required로 만들지는 않으므로 필수면 required도 둡니다.",
        "복잡한 email 정규식으로 모든 실제 주소를 완벽히 검증하려 하기보다 type=email과 product 요구를 분리하고 확인 mail flow를 사용합니다. phone도 입력 허용 형식을 지나치게 좁히면 국제 번호·공백·보조기술 입력을 거부합니다. 사용자 입력을 관대하게 받고 server에서 canonicalize하는 전략을 검토합니다.",
        "checkValidity()는 invalid event를 발생시키며 유효 여부를 반환하고 reportValidity()는 browser UI 표시를 요청합니다. setCustomValidity(message)는 customError를 만들며 valid해졌을 때 반드시 빈 문자열로 해제해야 합니다. 그렇지 않으면 수정 후에도 form이 영원히 invalid입니다.",
        "novalidate 또는 submitter formnovalidate는 browser constraint UI를 끌 수 있고 direct HTTP request는 항상 우회합니다. 내장 검증은 빠른 feedback과 일관된 control state를 제공하는 UX 층이며 server validation을 대체하지 않습니다.",
      ],
      concepts: [
        { term: "constraint validation", definition: "submittable control의 현재 value가 HTML에 선언된 type·required·range·pattern 등의 제약을 만족하는지 browser가 계산하는 model입니다.", detail: ["일부 control은 validation 대상에서 제외됩니다.", "server 검증과 병행합니다."] },
        { term: "ValidityState", definition: "valueMissing·typeMismatch·patternMismatch 등 개별 실패 flag와 종합 valid를 제공하는 DOM object입니다.", detail: ["원인별 error message/test에 활용합니다.", "browser localized validationMessage도 확인할 수 있습니다."] },
        { term: "custom validity", definition: "setCustomValidity로 application-specific 오류를 control에 설정하는 기능입니다.", detail: ["non-empty message면 customError가 true입니다.", "조건이 해소되면 반드시 ''로 clear합니다."] },
      ],
      codeExamples: [
        {
          id: "validity-state-inspector",
          title: "전화·수량·비밀번호 확인의 validation flag를 정확히 출력하기",
          language: "html",
          filename: "validation-lab.html",
          purpose: "browser popup 문구에 의존하지 않고 ValidityState와 custom validity의 변화를 안정된 text로 관찰합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>검증 실험</title></head>\n<body>\n  <main>\n    <h1>검증 실험</h1>\n    <form id=\"signup\" novalidate>\n      <label for=\"email\">이메일</label>\n      <input id=\"email\" name=\"email\" type=\"email\" required value=\"wrong\">\n\n      <label for=\"age\">나이</label>\n      <input id=\"age\" name=\"age\" type=\"number\" min=\"14\" max=\"120\" step=\"1\" value=\"13\">\n\n      <label for=\"pw\">비밀번호</label>\n      <input id=\"pw\" name=\"password\" type=\"password\" minlength=\"8\" value=\"abcdefgh\">\n      <label for=\"confirm\">비밀번호 확인</label>\n      <input id=\"confirm\" name=\"confirm\" type=\"password\" value=\"abcdefgi\">\n      <button>검사</button>\n    </form>\n    <pre id=\"result\"></pre>\n    <script>\n      const form = document.querySelector('#signup');\n      form.addEventListener('submit', (event) => {\n        event.preventDefault();\n        const pw = form.elements.password;\n        const confirm = form.elements.confirm;\n        confirm.setCustomValidity(confirm.value === pw.value ? '' : '비밀번호가 일치하지 않습니다.');\n        const fields = ['email', 'age', 'confirm'].map((id) => {\n          const input = document.querySelector('#' + id);\n          const v = input.validity;\n          return `${id}: valid=${v.valid}, valueMissing=${v.valueMissing}, typeMismatch=${v.typeMismatch}, rangeUnderflow=${v.rangeUnderflow}, customError=${v.customError}`;\n        });\n        document.querySelector('#result').textContent = fields.join('\n');\n      });\n    </script>\n  </main>\n</body>\n</html>",
          walkthrough: [
            { lines: "7", explanation: "novalidate로 browser popup을 끄고 실험 script가 모든 flag를 출력하게 합니다. 운영 form에서 무조건 끄라는 뜻이 아닙니다." },
            { lines: "9-17", explanation: "wrong email은 typeMismatch, 13은 min=14보다 작아 rangeUnderflow, 서로 다른 password는 custom rule 대상입니다." },
            { lines: "24-26", explanation: "submit마다 password 일치 여부를 계산하고 일치하면 empty string으로 custom error를 해제합니다." },
            { lines: "27-32", explanation: "browser별 localized message 대신 표준 boolean flag를 동일 순서 문자열로 출력합니다." },
          ],
          run: { environment: ["현대 browser", "JavaScript enabled"], command: "browser에서 validation-lab.html을 열고 초기값 그대로 검사" },
          output: { value: "email: valid=false, valueMissing=false, typeMismatch=true, rangeUnderflow=false, customError=false\nage: valid=false, valueMissing=false, typeMismatch=false, rangeUnderflow=true, customError=false\nconfirm: valid=false, valueMissing=false, typeMismatch=false, rangeUnderflow=false, customError=true", explanation: ["각 field가 서로 다른 constraint로 실패합니다.", "email이 비어 있지 않으므로 valueMissing은 false입니다.", "customError는 setCustomValidity의 non-empty message 때문에 true입니다."] },
          experiments: [
            { change: "email을 비웁니다.", prediction: "valueMissing=true이고 typeMismatch는 false가 됩니다.", result: "required 실패와 type syntax 실패는 구분됩니다." },
            { change: "age를 14, 두 password를 같은 값으로 바꾸고 다시 검사합니다.", prediction: "age와 confirm의 valid가 true가 됩니다.", result: "custom validity를 빈 문자열로 clear했기 때문에 회복됩니다." },
            { change: "confirm.setCustomValidity의 clear branch를 제거합니다.", prediction: "한 번 불일치한 뒤 값을 맞춰도 customError가 남을 수 있습니다.", result: "custom error lifecycle은 설정과 해제를 모두 구현해야 합니다." },
          ],
          sourceRefs: ["web-controls-signup-source", "whatwg-input", "wai-form-validation"],
        },
      ],
      diagnostics: [
        { symptom: "pattern이 있는데 빈 값이 그대로 제출된다.", likelyCause: "pattern은 non-empty value의 format을 검사할 뿐 field를 필수로 만들지 않습니다.", checks: ["required 존재를 확인합니다.", "validity.valueMissing와 patternMismatch를 각각 봅니다.", "optional field가 실제 요구인지 확인합니다."], fix: "업무상 필수이면 required를 추가하고 visible 필수 안내와 server required validation을 함께 적용합니다.", prevention: "schema의 presence rule과 format rule을 별도 test합니다." },
        { symptom: "오류를 수정했는데도 custom validation message 때문에 제출할 수 없다.", likelyCause: "setCustomValidity에 설정한 non-empty message를 조건 해소 후 빈 문자열로 clear하지 않았습니다.", checks: ["validity.customError를 확인합니다.", "input/change마다 validator가 다시 실행되는지 봅니다.", "clear branch를 확인합니다."], fix: "유효할 때 setCustomValidity('')를 호출하고 관련 error text/state를 함께 제거합니다.", prevention: "invalid→valid 전환과 valid→invalid 전환을 모두 component test에 둡니다." },
      ],
    },
    {
      id: "accessible-error-recovery",
      title: "오류는 색·popup 한 번이 아니라 요약·field message·focus·수정 방법으로 회복 가능하게 만듭니다",
      lead: "사용자가 무엇이 틀렸는지, 어디로 가야 하는지, 입력을 잃지 않고 어떻게 고치는지 알 수 있어야 합니다.",
      explanations: [
        "browser 기본 validation UI는 locale과 browser마다 다르고 여러 error를 한 번에 비교하기 어렵습니다. native constraint를 유지하면서 server/client error summary를 page heading 뒤에 제공하고 각 error link가 해당 field로 이동하게 할 수 있습니다.",
        "field error는 label과 field를 명시해 구체적인 수정 방법을 text로 씁니다. '잘못된 입력'보다 '연락처를 010-1234-5678 형식으로 입력하세요'가 낫습니다. error element id를 aria-describedby에 포함하고 aria-invalid는 실제 invalid 상태일 때만 true로 관리합니다.",
        "submit 뒤 error summary에 focus를 옮기거나 heading을 programmatically focus해 결과를 알리되 사용자 입력 중 매 keystroke마다 aggressive live message를 announce하지 않습니다. blur/submit timing과 screen reader behavior를 user test합니다.",
        "server validation error page는 사용자가 입력한 안전한 값을 보존하지만 password·file input은 다시 채울 수 없음을 설명합니다. 금융·법적·삭제 action은 검토·확인·취소 또는 되돌리기 같은 error prevention을 제공합니다.",
        "CSS :invalid는 page load부터 모든 빈 required field를 빨갛게 만들 수 있습니다. form이 제출됐거나 field가 touched된 이후 state를 표시하는 product rule을 두고, 색 외 icon/text/border와 high-contrast mode를 검증합니다.",
      ],
      concepts: [
        { term: "error summary", definition: "제출 실패 시 page 상단에서 오류 수와 각 field로 이동하는 link를 제공하는 요약 영역입니다.", detail: ["field-level message를 대체하지 않습니다.", "focus와 heading을 통해 발견 가능하게 합니다."] },
        { term: "aria-invalid", definition: "control의 현재 입력값이 application 관점에서 invalid임을 보조기술에 알리는 state입니다.", detail: ["오류가 실제 확인된 뒤 설정합니다.", "수정되면 false/제거로 동기화합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "submit 후 빨간 border만 생기고 keyboard/screen reader 사용자는 오류 위치와 이유를 모른다.", likelyCause: "색과 CSS :invalid만 사용하고 text error·description·focus strategy가 없습니다.", checks: ["색을 제거하고 error 의미가 남는지 봅니다.", "submit 직후 screen reader announcement를 확인합니다.", "각 error와 field 연결을 검사합니다."], fix: "focus 가능한 error summary, 구체적 field error text, aria-describedby/aria-invalid, visible label을 함께 제공합니다.", prevention: "error state를 keyboard·screen reader·forced-colors·zoom 조건에서 E2E test합니다." },
      ],
    },
    {
      id: "file-upload-boundary",
      title: "file input의 accept와 확장자는 선택 UI hint일 뿐이며 server가 bytes를 적대적 입력으로 검증해야 합니다",
      lead: "multipart form을 올바르게 전송한 뒤 size·count·signature·decode·filename·path·storage·serving policy를 독립적으로 적용합니다.",
      explanations: [
        "원본은 file upload에 POST와 multipart/form-data가 필요하다고 설명하지만 예제 form은 method=get이라 실제 오류를 학습하기 좋은 지점입니다. file input은 POST multipart form으로 보내고 browser가 Content-Type boundary를 생성하게 둡니다. JavaScript fetch에서 FormData를 보낼 때 Content-Type을 수동으로 고정하면 boundary가 빠질 수 있습니다.",
        "accept='image/png,image/jpeg' 또는 image/*는 file picker filter hint입니다. 사용자는 다른 client로 임의 bytes를 보낼 수 있고 MIME type·확장자·filename도 위조할 수 있습니다. server는 size/count limit, magic/signature와 실제 decoder, 허용 dimension, decompression bomb, malware policy를 검증합니다.",
        "사용자 filename을 filesystem path로 직접 결합하면 path traversal·reserved name·Unicode normalization·collision 문제가 생깁니다. server-generated opaque ID로 저장하고 원래 이름은 display metadata로 제한·escape합니다. executable directory 밖과 별도 object storage를 고려합니다.",
        "upload content를 같은 origin에서 inline serve하면 HTML/SVG/script/polyglot content가 active content로 실행될 수 있습니다. 별도 origin, safe Content-Type, Content-Disposition: attachment, nosniff, image re-encoding 등 threat model에 맞는 serving policy가 필요합니다.",
        "file input value를 script로 실제 local path에 설정할 수 없고 reset/validation error 후 재선택이 필요할 수 있습니다. upload progress·cancel·retry·413 error와 accessible status를 설계하고 실제 file bytes나 PII를 log에 남기지 않습니다.",
      ],
      concepts: [
        { term: "accept hint", definition: "file picker에서 선택할 type/extension을 제안하는 client-side filter입니다.", detail: ["server validation이 아닙니다.", "MIME type·extension 모두 위조될 수 있습니다."] },
        { term: "content sniffing", definition: "선언된 media type 외에 bytes를 검사해 content type을 추정하는 behavior입니다.", detail: ["예상치 못한 active content 실행 위험이 있습니다.", "nosniff와 안전한 serving type을 고려합니다."] },
        { term: "storage isolation", definition: "upload를 application executable/static root와 분리하고 opaque identifier·권한·serving policy로 접근을 제한하는 설계입니다.", detail: ["path traversal과 code execution impact를 낮춥니다.", "authorization은 download 시에도 다시 확인합니다."] },
      ],
      codeExamples: [
        {
          id: "safe-upload-form-contract",
          title: "multipart upload form과 client-side 사전 안내",
          language: "html",
          filename: "portfolio-upload.html",
          purpose: "올바른 form transport와 accessible instruction을 제공하되 accept/size script가 server 검증을 대체하지 않음을 보여 줍니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>포트폴리오 업로드</title></head>\n<body>\n  <main>\n    <h1>포트폴리오 업로드</h1>\n    <form action=\"/portfolio\" method=\"post\" enctype=\"multipart/form-data\">\n      <label for=\"title\">자료 제목</label>\n      <input id=\"title\" name=\"title\" required maxlength=\"80\">\n\n      <label for=\"document\">PDF 자료</label>\n      <input id=\"document\" name=\"document\" type=\"file\" accept=\"application/pdf,.pdf\" required aria-describedby=\"file-help file-error\">\n      <p id=\"file-help\">PDF 1개, 최대 10 MiB. 개인정보와 비밀번호를 제거하세요.</p>\n      <p id=\"file-error\" role=\"status\"></p>\n\n      <button type=\"submit\">업로드</button>\n    </form>\n    <script>\n      const input = document.querySelector('#document');\n      input.addEventListener('change', () => {\n        const file = input.files[0];\n        const tooLarge = file && file.size > 10 * 1024 * 1024;\n        input.setCustomValidity(tooLarge ? '파일은 10 MiB 이하여야 합니다.' : '');\n        document.querySelector('#file-error').textContent = tooLarge ? '선택한 파일이 10 MiB를 초과했습니다.' : '';\n      });\n    </script>\n  </main>\n</body>\n</html>",
          walkthrough: [
            { lines: "7", explanation: "file bytes를 전송하도록 POST multipart contract를 명시합니다." },
            { lines: "11-14", explanation: "accept는 picker hint이며 visible help가 type·count·size·privacy 요구를 설명합니다. error도 description에 연결됩니다." },
            { lines: "19-25", explanation: "선택 즉시 client size를 확인해 빠른 feedback을 주고 valid하면 custom error를 clear합니다. server는 동일 rule과 bytes 검증을 다시 수행합니다." },
          ],
          run: { environment: ["현대 browser", "10 MiB보다 큰 synthetic .pdf file", "Network panel"], command: "portfolio-upload.html을 server origin에서 열고 10 MiB 초과 file 선택" },
          output: { value: "화면 오류: 선택한 파일이 10 MiB를 초과했습니다.\ninput.validity.customError=true\ninteractive submit: browser에서 차단\nserver request: 발생하지 않음\n\n10 MiB 이하 file 선택 시 customError=false; 제출하면 Content-Type: multipart/form-data; boundary=...", explanation: ["client check는 사용자의 대기 시간을 줄이는 UX입니다.", "direct client는 우회할 수 있으므로 server limit이 실제 보안 경계입니다.", "boundary 값은 browser가 매 request 생성하므로 exact token은 달라집니다."] },
          experiments: [
            { change: "method를 get으로 바꿉니다.", prediction: "file bytes를 정상 multipart POST content로 전송하는 계약이 깨집니다.", result: "file upload form은 POST multipart로 구성합니다." },
            { change: "accept를 image/*로 바꾸고 script가 있는 SVG를 선택합니다.", prediction: "picker가 선택을 허용할 수 있지만 안전한 image임을 보장하지 않습니다.", result: "accept는 hint이고 server decode/re-encode/serve policy가 필요합니다." },
            { change: "10 MiB 이하로 다시 선택합니다.", prediction: "setCustomValidity('')와 빈 error text로 field가 회복됩니다.", result: "custom validation은 invalid와 valid 전환을 모두 처리합니다." },
          ],
          sourceRefs: ["web-controls-date-file-source", "whatwg-input", "wai-form-validation"],
        },
      ],
      diagnostics: [
        { symptom: "server가 multipart boundary를 찾지 못하고 모든 field가 비어 있다.", likelyCause: "form method/enctype가 틀렸거나 fetch에서 Content-Type을 수동 설정해 browser boundary parameter가 누락됐습니다.", checks: ["Network method와 Content-Type boundary를 확인합니다.", "request payload에 multipart part가 있는지 봅니다.", "server multipart size/parser config를 확인합니다."], fix: "native form은 method=post enctype=multipart/form-data를 쓰고 fetch FormData는 Content-Type을 browser가 설정하게 둡니다.", prevention: "text+file multipart fixture와 oversized 413 case를 integration test합니다." },
        { symptom: "avatar.jpg라는 이름의 upload가 script로 실행되거나 다른 file을 덮어쓴다.", likelyCause: "extension/filename을 신뢰해 web root에 원래 이름으로 저장하고 같은 origin에서 sniff 가능한 형태로 serve했습니다.", checks: ["실제 byte signature와 decoder 결과를 확인합니다.", "storage path 생성과 collision policy를 봅니다.", "response Content-Type/Disposition/nosniff/origin을 검사합니다."], fix: "server-generated ID로 격리 저장하고 allowlisted decode/re-encode, safe serving header/origin, authorization을 적용합니다.", prevention: "polyglot·SVG·path traversal·Unicode filename·collision·oversize security test를 유지합니다." },
      ],
    },
    {
      id: "production-form-quality",
      title: "좋은 form은 입력 수를 줄이고 keyboard·autofill·error·privacy·server contract를 한 흐름으로 검증합니다",
      lead: "모든 input type을 한 화면에 넣는 것이 목표가 아니라 사용자가 최소한의 data로 task를 안전하게 끝내고 오류에서 돌아오는 것이 목표입니다.",
      explanations: [
        "필요하지 않은 개인정보를 묻지 않는 것이 가장 강한 privacy control입니다. 각 field에 purpose, retention, access, optional/required 근거를 기록하고 autocomplete token으로 반복 입력을 줄입니다. 민감 data는 cleartext log와 analytics event에서 제외합니다.",
        "keyboard만으로 label→control→help→submit 순서를 따라가고 focus indicator와 touch target을 확인합니다. visual CSS order가 DOM/tab order와 달라지지 않게 하며 modal date picker·custom select를 추가했다면 Escape·arrow·focus return을 test합니다.",
        "mobile에서는 적합한 keyboard, zoom을 막지 않는 viewport, 긴 error와 200% text, orientation, autofill을 확인합니다. fixed two-column label layout이 좁은 화면에서 겹치면 source order 한 열로 reflow합니다.",
        "client와 server validation rule을 완전히 중복 구현하면 drift가 생길 수 있습니다. shared schema 또는 generated constraints를 고려하되 server가 authoritative하고 browser-native semantics를 잃지 않게 합니다. server error code와 field name을 stable contract로 두고 localized message는 client가 표현할 수 있습니다.",
        "E2E test는 label accessible name, keyboard submission, invalid focus/error summary, FormData shape, Network status/redirect를 함께 확인합니다. client constraints를 제거한 direct request로 server defense도 검증합니다.",
      ],
      concepts: [
        { term: "data minimization", definition: "task 수행에 필요한 최소 개인정보만 수집·보관·접근하게 하는 privacy 원칙입니다.", detail: ["optional field의 business 근거를 검토합니다.", "수집하지 않은 data는 유출될 수 없습니다."] },
        { term: "validation drift", definition: "client·server·문서의 field rule이 서로 다르게 변경되어 같은 입력을 한쪽은 허용하고 다른 쪽은 거부하는 상태입니다.", detail: ["shared schema와 contract test로 줄입니다.", "server rule이 최종 권위입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "browser에서는 가입 가능하지만 server가 같은 비밀번호를 거부하거나 반대로 browser가 server 허용값을 막는다.", likelyCause: "pattern·minlength와 backend validation rule이 별도로 변경되어 drift가 생겼습니다.", checks: ["client attributes, API schema, server validator, help text를 같은 fixture로 비교합니다.", "versioned rule과 deploy 순서를 확인합니다.", "direct request와 browser E2E 결과를 대조합니다."], fix: "authoritative schema와 stable error code를 정하고 constraints/help text를 생성·contract test하며 호환 deploy를 설계합니다.", prevention: "boundary fixture를 frontend/backend pipeline 모두에서 실행하고 rule 변경을 API change로 review합니다." },
      ],
      expertNotes: [
        "custom element가 form-associated behavior를 구현하려면 ElementInternals 등 별도 API와 browser support·fallback을 검토해야 합니다. 모양 때문에 native input을 재구현하면 autofill·validation·mobile keyboard를 잃기 쉽습니다.",
        "실시간 username availability처럼 server round trip이 필요한 validation은 debounce·stale response cancellation·privacy·rate limiting을 설계하고, 최종 submit에서 다시 확인합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 회원가입·주문 form을 접근 가능하고 server와 일치하는 production form으로 재설계하기",
    scenario: "기존 form은 placeholder와 pattern에 의존하고 일부 field에 name이 없으며 phone에 number를 사용합니다. error가 빨간색뿐이고 upload는 GET으로 설정되어 있습니다. 실제 가입·주문 흐름으로 고칩니다.",
    setup: ["원본 6개 form file의 control inventory를 read-only 표로 만듭니다.", "현대 browser, keyboard, 320px responsive viewport, accessibility tree, Network panel을 준비합니다.", "실제 개인정보 대신 한글·국제 전화·긴 이름·10 MiB 초과 synthetic fixture를 준비합니다."],
    steps: [
      "각 field의 purpose·type·id·name·required·autocomplete·server type·retention을 schema 표에 기록합니다.",
      "모든 control에 지속적인 visible label과 unique id를 연결하고 help/error description을 추가합니다.",
      "상품 choice와 mailing choice를 각각 fieldset/legend로 group하고 stable domain value를 지정합니다.",
      "전화번호를 tel/text+inputmode로, 수량을 number로, 예약일을 date로 교정하고 적용 가능한 constraint만 사용합니다.",
      "client ValidityState를 field error와 summary에 연결하고 invalid→valid 회복과 keyboard focus를 구현합니다.",
      "file form을 POST multipart로 바꾸고 client size hint와 server size/type/signature/storage policy를 작성합니다.",
      "direct HTTP request로 required·pattern·accept를 우회해 server validation과 authorization을 확인합니다.",
      "320px·200% zoom·keyboard·autofill·CSS 실패·server error response에서 task를 끝낼 수 있는지 기록합니다.",
    ],
    expectedResult: ["모든 control과 choice group이 고유한 accessible name을 가집니다.", "FormData에 schema가 기대한 name/value만 포함되고 id-only control이 없습니다.", "constraint별 오류가 구체적인 text로 연결되고 수정 후 즉시 회복됩니다.", "phone leading zero와 date machine value가 보존되며 client/server rule이 일치합니다.", "file upload는 multipart이고 accept를 우회한 위험 file이 server에서 거부됩니다.", "keyboard·mobile·zoom·autofill·error page에서 입력 손실 없이 완료할 수 있습니다."],
    cleanup: ["synthetic upload와 test account, temporary object를 삭제합니다.", "Network capture와 screenshot에서 file name·email·cookie·token을 redaction합니다."],
    extensions: ["server error code를 localized client message와 연결하고 language 전환 후 focus/description을 test합니다.", "password manager와 WebAuthn/passkey 흐름을 별도 인증 세션으로 확장합니다.", "upload virus scan이 비동기일 때 pending/quarantine/approved/rejected 상태 machine과 알림을 설계합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "예약 form의 이름·전화·이메일을 올바른 label과 control type으로 고치세요.", requirements: ["각 label for와 unique id를 일치시킵니다.", "모든 전송 control에 stable name이 있습니다.", "전화는 tel+inputmode와 visible format help를 사용합니다.", "email은 type=email, 세 field 모두 server schema와 연결합니다.", "placeholder를 유일한 label로 쓰지 않습니다."], hints: ["원본에는 id만 있고 name이 없는 field가 있습니다.", "전화번호는 산술 값이 아닙니다."], expectedOutcome: "label click·accessible name·mobile keyboard·FormData key가 모두 기대와 일치합니다.", solutionOutline: ["field contract 표를 먼저 작성합니다.", "Elements/Accessibility/FormData 세 층에서 확인합니다."] },
    { difficulty: "응용", prompt: "회원가입 form에 내장 검증과 접근 가능한 error recovery를 구현하세요.", requirements: ["required·minlength·type·적용 가능한 pattern만 사용합니다.", "비밀번호 확인 custom validity를 invalid/valid 양방향 처리합니다.", "error summary와 field message를 연결합니다.", "invalid field에 focus 이동 경로와 입력 보존을 제공합니다.", "server direct request test를 포함합니다."], hints: ["setCustomValidity('') 해제를 잊지 않습니다.", "email regex를 지나치게 좁히지 않습니다."], expectedOutcome: "여러 오류가 동시에 식별되고 keyboard/screen reader 사용자가 각 field를 수정해 성공할 수 있습니다.", solutionOutline: ["ValidityState flag별 message map을 만듭니다.", "submit 시 server rule을 authoritative하게 재검증합니다."] },
    { difficulty: "설계", prompt: "포트폴리오 PDF·프로필 이미지 upload service의 end-to-end security와 UX 계약을 설계하세요.", requirements: ["form enctype·count·size·accept hint를 정의합니다.", "server signature/decoder/dimension/malware/filename/path 검증을 설명합니다.", "격리 storage·authorization·safe serving header/origin을 설계합니다.", "progress·cancel·retry·413·scan pending/error 접근성 상태를 포함합니다.", "polyglot·SVG·path traversal·oversize·race test matrix를 만듭니다."], hints: ["확장자와 Content-Type은 공격자가 정할 수 있습니다.", "upload와 download/serve를 별도 trust boundary로 봅니다."], expectedOutcome: "accept에 의존하지 않고 bytes부터 저장·제공·삭제까지 검증 가능한 upload architecture가 완성됩니다.", solutionOutline: ["threat model과 lifecycle state를 먼저 그립니다.", "client hint와 server invariant를 분리합니다."] },
  ],
  reviewQuestions: [
    { question: "placeholder가 있으면 label을 생략해도 되나요?", answer: "안 됩니다. placeholder는 입력 시 사라지고 목적·format을 지속적으로 제공하지 못합니다. visible label을 control과 연결합니다." },
    { question: "전화번호에 type=number를 쓰면 왜 안 좋은가요?", answer: "산술 값이 아니며 leading zero와 separator가 중요하고 pattern/maxlength가 number에 기대대로 적용되지 않기 때문입니다." },
    { question: "checkbox를 하나도 선택하지 않으면 어떤 값이 전송되나요?", answer: "보통 그 name entry 자체가 없습니다. server가 missing을 empty list로 해석할지 required error로 볼지 명시합니다." },
    { question: "radio와 checkbox group에 legend가 필요한 이유는 무엇인가요?", answer: "각 option label이 공유하는 질문/문맥을 fieldset·legend가 programmatically 제공합니다." },
    { question: "pattern만 있으면 field가 필수가 되나요?", answer: "아닙니다. 빈 값 허용과 format 검증은 별개이며 필수이면 required도 필요합니다." },
    { question: "number input에서 maxlength와 pattern이 동작하나요?", answer: "number state에는 그 속성이 적용되지 않습니다. 수량은 min/max/step, digit identifier는 text/tel과 pattern/length를 사용합니다." },
    { question: "setCustomValidity 오류를 어떻게 해제하나요?", answer: "값이 유효해진 순간 setCustomValidity('')를 호출해야 customError가 사라집니다." },
    { question: "accept='.pdf'면 PDF만 안전하게 올라오나요?", answer: "아닙니다. picker hint일 뿐이므로 server가 size·bytes signature·실제 decoder·storage/serving policy를 검증해야 합니다." },
    { question: "client validation이 있으면 server validation을 줄여도 되나요?", answer: "안 됩니다. client는 조작·우회 가능하며 server가 형식·범위·business rule·authorization을 최종 검증합니다." },
  ],
  completionChecklist: [
    "모든 control에 지속적인 visible label과 unique id, 필요한 help/error description을 연결했다.",
    "fieldset·legend로 관련 choice group의 공유 질문을 제공했다.",
    "data 의미에 맞는 input type·inputmode·autocomplete를 선택했다.",
    "type별로 적용 가능한 required·length·range·step·pattern만 사용했다.",
    "ValidityState 원인별 오류와 invalid→valid custom error 해제를 구현했다.",
    "keyboard·mobile·200% zoom·autofill·error focus에서 form을 완료했다.",
    "client constraint를 우회한 request를 server validation·authorization이 거부했다.",
    "file upload의 multipart·limit·byte validation·격리 storage·safe serving을 검증했다.",
  ],
  nextSessions: ["html-09-semantic-layout-accessibility"],
  sources: [
    { id: "web-controls-contact-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex06_form.html", usedFor: ["label/id/name", "email·tel·number", "pattern", "배송 정보"], evidence: "연락처 3가지 type/pattern 예제를 감사해 number에 pattern이 적용되지 않는 점과 목적 기반 type 선택으로 교정했습니다." },
    { id: "web-controls-choice-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex07_form.html", usedFor: ["checkbox", "radio", "select", "multiple", "hidden", "repeated name"], evidence: "상품·포장·장소 option의 실제 name/value/checked/selected를 choice cardinality와 server array contract로 확장했습니다." },
    { id: "web-controls-signup-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex08_form.html", usedFor: ["회원가입", "placeholder", "pattern", "password confirmation", "reset"], evidence: "아이디·이메일·비밀번호 regex와 mailing choice를 감사해 native type, custom validity, error recovery, password manager 관점으로 보강했습니다." },
    { id: "web-controls-textarea-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex09_form.html", usedFor: ["textarea", "cols·rows", "배송 memo"], evidence: "여러 줄 memo control을 responsive size·length·server limit·input preservation 설명에 사용했습니다." },
    { id: "web-controls-date-file-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex10_form.html", usedFor: ["file", "date·month·week·time·datetime-local", "range", "button", "image submit"], evidence: "GET multipart 오류를 포함한 원본을 감사해 POST multipart, date/time zone, range feedback, submitter 좌표와 upload security로 확장했습니다." },
    { id: "web-controls-application-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day03/ex11_form.html", usedFor: ["예약", "지원서", "fieldset·legend", "radio", "textarea", "layout"], evidence: "예약·지원서 종합 form을 label/name 누락, group semantic, destructive reset, responsive layout 관점에서 audit했습니다." },
    { id: "whatwg-input", repository: "WHATWG HTML Standard", path: "multipage/input.html", publicUrl: "https://html.spec.whatwg.org/multipage/input.html", usedFor: ["input states", "attribute applicability", "file accept", "constraint validation", "ValidityState"], evidence: "2026-07-12 기준 living standard의 input type별 attribute applicability와 validation rule을 교정 기준으로 확인했습니다." },
    { id: "whatwg-form-elements", repository: "WHATWG HTML Standard", path: "multipage/form-elements.html", publicUrl: "https://html.spec.whatwg.org/multipage/form-elements.html", usedFor: ["select·option", "textarea", "button", "fieldset·legend", "output"], evidence: "form elements의 value·group·submission semantics를 choice와 textarea/button 설명에 반영했습니다." },
    { id: "wai-form-labels", repository: "W3C Web Accessibility Initiative", path: "tutorials/forms/labels/", publicUrl: "https://www.w3.org/WAI/tutorials/forms/labels/", usedFor: ["visible label", "explicit association", "click target", "accessible name"], evidence: "W3C WAI label guidance를 모든 control의 name/interaction 검증 기준으로 사용했습니다." },
    { id: "wai-form-validation", repository: "W3C Web Accessibility Initiative", path: "tutorials/forms/validation/", publicUrl: "https://www.w3.org/WAI/tutorials/forms/validation/", usedFor: ["required·format validation", "forgiving input", "server validation", "error prevention"], evidence: "내장 검증과 server validation 병행, 수정 가능한 error message 원칙을 반영했습니다." },
    { id: "wai-form-notifications", repository: "W3C Web Accessibility Initiative", path: "tutorials/forms/notifications/", publicUrl: "https://www.w3.org/WAI/tutorials/forms/notifications/", usedFor: ["error notification", "field reference", "success feedback"], evidence: "오류 식별·수정 instruction·notification을 error summary와 field description 설계에 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 6,
    filesUsed: 6,
    uncoveredNotes: [
      "원본은 HTML input type과 form UI를 폭넓게 실습합니다. type별 attribute applicability, accessible error lifecycle, autocomplete, upload threat model은 WHATWG와 W3C WAI guidance로 교정·보강했습니다.",
      "server multipart parser 구현과 storage adapter는 Servlet/Spring 세션, password hashing·CSRF는 security/authentication 관련 full-stack 세션에서 더 깊게 구현합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
