import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["xml-03-browser-parse-render"],
  slug: "xml-03-browser-parse-render",
  courseId: "web",
  moduleId: "03-xml-data-formats",
  order: 3,
  title: "XML을 브라우저에서 파싱·탐색·화면에 렌더링하기",
  subtitle: "fetch의 byte stream을 한 번 소비해 Unicode text로 만들고 namespace-aware XML DOM으로 파싱한 뒤, parser/data 오류를 분리하고 untrusted 값을 textContent로 안전하게 HTML table에 렌더링합니다.",
  level: "중급",
  estimatedMinutes: 210,
  coreQuestion: "network에서 받은 XML text가 언제 정상 Document가 되고, 어떤 element/attribute/text를 읽어 HTML UI로 옮길 때 HTTP·CORS·namespace·XSS·race 오류를 어떻게 구분할까요?",
  summary: "원본 fetch weather XML과 jQuery dataType=xml 자동차/날씨, JSON fetch, delimiter text 예제를 하나의 browser data pipeline으로 연결합니다. fetch가 HTTP error에서 reject하지 않으므로 response.ok를 확인하고 body stream을 한 번만 소비해야 한다는 점, CORS와 local file 제한, AbortController/race를 다룹니다. DOMParser(application/xml)가 invalid XML에서 parsererror Document를 반환하는 특성, namespace-aware getElementsByTagNameNS/XPath, direct text와 descendant text, missing attribute null, XMLSerializer round-trip을 설명합니다. 원본의 string concat+innerHTML XSS를 createElement/textContent/DocumentFragment로 교정하고 accessible table·loading/empty/error state·large data performance와 security parser boundary까지 검증합니다.",
  objectives: [
    "fetch의 network/HTTP/status/content-type/body stream 단계와 CORS/same-origin 경계를 설명할 수 있다.",
    "Response body를 text/json 등 한 방식으로 한 번 소비하고 bodyUsed·TypeError를 진단할 수 있다.",
    "DOMParser application/xml의 반환 Document와 parsererror를 안정적으로 검사할 수 있다.",
    "element·attribute·text node와 namespace URI/localName을 구분해 원하는 XML data를 정확히 추출할 수 있다.",
    "untrusted XML value를 innerHTML 문자열에 삽입하지 않고 HTML DOM API/textContent로 안전하게 렌더링할 수 있다.",
    "loading·HTTP·parse·shape·empty·render·abort/race 오류를 사용자 상태와 diagnostic evidence로 분리할 수 있다.",
  ],
  prerequisites: [
    { title: "요소·속성·혼합 콘텐츠와 namespace", reason: "XML expanded name·attribute·text model을 알고 browser DOM API로 같은 구조를 탐색합니다.", sessionSlug: "xml-02-elements-attributes-namespace" },
  ],
  keywords: ["fetch", "Response", "bodyUsed", "CORS", "DOMParser", "application/xml", "parsererror", "XML DOM", "namespace", "getElementsByTagNameNS", "XPath", "textContent", "DocumentFragment", "XSS", "AbortController"],
  chapters: [
    {
      id: "network-to-text-pipeline",
      title: "XML pipeline은 request→HTTP response→body consume→Unicode text→XML parse→data validate→render 단계로 나뉩니다",
      lead: "'불러오기 실패' 하나로 뭉치지 않고 마지막으로 성공한 경계를 찾아야 빠르고 정확하게 복구합니다.",
      explanations: [
        "fetch(url)는 Promise<Response>를 반환합니다. DNS/TLS/network/CORS 같은 fetch-level failure에서는 reject될 수 있지만 404·500 HTTP response는 보통 fulfilled Response이므로 `response.ok` 또는 허용 status를 직접 검사합니다.",
        "response.text()는 body를 완전히 읽어 text로 decode합니다. text가 XML처럼 보인다고 자동 XML DOM이 되는 것은 아닙니다. DOMParser로 두 번째 명시적 parse가 필요합니다. jQuery `dataType:'xml'`은 이 conversion을 library가 대신한 예입니다.",
        "원본 JSON example은 `console.log(response.json())` 뒤 다시 `await response.json()`을 호출합니다. 첫 호출이 body stream을 소비하므로 두 번째는 body가 unusable/disturbed되어 TypeError가 날 수 있습니다. text/json/blob/arrayBuffer 중 한 번 소비하고 변수로 재사용하거나 필요하면 response.clone을 사전에 사용합니다.",
        "Content-Type이 application/xml/text/xml이면 server 의도가 명확하지만 response.text 후 DOMParser type argument가 실제 parser를 결정합니다. HTTP charset·BOM·XML declaration encoding과 Fetch text decoding behavior를 server/client contract로 검증합니다.",
        "각 단계 error에는 URL/status/content-type/body length/parser root/data row count/render target를 secret 제거 후 기록합니다. raw 개인정보/XML 전체를 production log에 남기지 않습니다.",
      ],
      concepts: [
        { term: "body stream", definition: "Response content bytes를 제공하는 한 번 소비 가능한 stream입니다.", detail: ["text/json/blob 등이 consume합니다.", "bodyUsed로 소비 여부를 볼 수 있습니다."] },
        { term: "HTTP error versus network error", definition: "server가 4xx/5xx response를 돌려준 경우와 request/Fetch 자체가 response를 얻지 못한 경우의 구분입니다.", detail: ["fetch는 HTTP error에서 자동 reject하지 않습니다.", "status와 catch path를 분리합니다."] },
        { term: "data pipeline boundary", definition: "transport·decode·syntax parse·shape validation·render처럼 서로 다른 failure 책임을 나눈 경계입니다.", detail: ["오류 message와 retry 가능성을 다르게 합니다.", "observability field를 경계별로 둡니다."] },
      ],
      codeExamples: [
        {
          id: "response-single-consumption",
          title: "Response body를 한 번 읽은 뒤 두 번째 read가 실패하는 예",
          language: "html",
          filename: "response-body.html",
          purpose: "network 없이 data URL을 fetch해 status/bodyUsed와 single-consumption contract를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>Response body</title></head>\n<body>\n  <pre id=\"result\"></pre>\n  <script>\n    (async () => {\n      const source = '<catalog><item id=\"1\">XML</item></catalog>';\n      const url = 'data:application/xml;charset=utf-8,' + encodeURIComponent(source);\n      const response = await fetch(url);\n      const lines = [`status=${response.status}`, `ok=${response.ok}`, `before=${response.bodyUsed}`];\n      const text = await response.text();\n      lines.push(`after=${response.bodyUsed}`, `text=${text}`);\n      try { await response.text(); } catch (error) { lines.push(`second=${error.name}`); }\n      document.querySelector('#result').textContent = lines.join('\\n');\n    })();\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-9", explanation: "well-formed XML을 percent-encoded data URL로 만들어 external server/CORS 없이 Response를 얻습니다." },
            { lines: "10-12", explanation: "status·ok와 consume 전 bodyUsed를 기록하고 text로 한 번 읽습니다." },
            { lines: "13", explanation: "consume 후 bodyUsed/text를 기록합니다." },
            { lines: "14", explanation: "같은 Response를 두 번째 text로 읽어 TypeError name을 포착합니다." },
          ],
          run: { environment: ["Fetch/data URL을 지원하는 현대 browser"], command: "browser에서 response-body.html 열기" },
          output: { value: "status=200\nok=true\nbefore=false\nafter=true\ntext=<catalog><item id=\"1\">XML</item></catalog>\nsecond=TypeError", explanation: ["첫 text()가 body stream을 소비해 bodyUsed가 true가 됩니다.", "두 번째 consume은 unusable body라 TypeError입니다.", "parse/DOM은 아직 수행하지 않았으므로 text를 변수에서 재사용합니다."] },
          experiments: [
            { change: "첫 read 전에 const copy=response.clone()을 만들고 copy.text()도 읽습니다.", prediction: "원본과 clone에서 각각 한 번씩 같은 text를 읽을 수 있습니다.", result: "clone은 사전에 stream을 tee하지만 memory/backpressure 비용을 고려합니다." },
            { change: "data URL media type을 application/json으로 바꾸고 XML text를 유지합니다.", prediction: "response.text는 그대로 XML text를 돌려주지만 response.json은 SyntaxError가 납니다.", result: "Content-Type·consume method·실제 syntax contract를 맞춥니다." },
            { change: "response.ok check 없이 404 test server response body를 parse합니다.", prediction: "error HTML을 XML로 parse해 HTTP 원인을 parse error로 오해할 수 있습니다.", result: "status 검사를 parse보다 먼저 합니다." },
          ],
          sourceRefs: ["web-fetch-xml-source", "web-fetch-json-source", "fetch-standard"],
        },
      ],
      diagnostics: [
        { symptom: "Body has already been consumed 또는 TypeError가 발생한다.", likelyCause: "response.json/text를 logging과 실제 처리에서 두 번 호출했습니다.", checks: ["response.bodyUsed와 consume method 호출 위치를 검색합니다.", "helper/middleware가 먼저 읽었는지 확인합니다.", "clone 시점이 consume 전인지 봅니다."], fix: "body를 한 번 읽어 변수로 log/parse/reuse하고 정말 두 consumer가 필요하면 consume 전에 clone합니다.", prevention: "HTTP client wrapper가 single-consumer ownership을 갖고 body read count test를 둡니다." },
      ],
    },
    {
      id: "origin-cors-local-server",
      title: "XML fetch 가능 여부는 format이 아니라 URL origin·CORS response·document scheme에 의해 결정됩니다",
      lead: "CORS 실패를 'Spring에서만 가능'으로 외우지 않고 browser security model과 server header 계약을 확인합니다.",
      explanations: [
        "same-origin policy는 scheme·host·port가 다른 origin의 response를 script가 읽는 것을 제한합니다. cross-origin server가 request origin/method/header를 허용하는 CORS response를 제공해야 하며 client에서 임의로 우회할 수 없습니다.",
        "원본 기상청 URL이 막힌다면 XML이어서가 아니라 target CORS policy·redirect·mixed content·TLS 등의 문제일 수 있습니다. backend proxy는 credential/API key 보호·cache·rate limit·schema normalization에 쓸 수 있지만 open proxy가 되지 않게 allowlist합니다.",
        "file://에서 HTML을 직접 열고 relative XML을 fetch하면 browser의 opaque/null origin·local file policy 때문에 실패할 수 있습니다. 학습 자료도 `python -m http.server` 같은 local HTTP server로 같은 origin에서 실행합니다.",
        "`mode:'no-cors'`는 CORS를 해제해 response body를 읽게 해 주는 설정이 아닙니다. opaque response는 status/header/body를 application이 사용할 수 없어 XML data processing 해결책이 아닙니다.",
        "개발 CORS 전체 허용을 production에 복사하지 않고 exact origin·method·credential policy와 Vary:Origin/cache를 구성합니다. cookie credential과 CSRF는 별도 threat입니다.",
      ],
      concepts: [
        { term: "same-origin", definition: "두 URL의 scheme·host·port가 같은 browser origin 관계입니다.", detail: ["path는 origin 판단에 포함되지 않습니다.", "script data access의 기본 경계입니다."] },
        { term: "CORS", definition: "cross-origin response를 browser script에 노출할지 server가 HTTP header로 동의하는 protocol입니다.", detail: ["client-only 우회가 아닙니다.", "preflight/credential/cache를 함께 설계합니다."] },
        { term: "opaque response", definition: "no-cors cross-origin fetch에서 JavaScript가 status/header/body를 읽을 수 없게 제한된 response type입니다.", detail: ["data parse에 쓸 수 없습니다.", "network request 성공 증거와 readable response는 다릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "Network에는 200이 보이지만 fetch가 TypeError로 catch되고 XML text를 읽을 수 없다.", likelyCause: "cross-origin response에 필요한 CORS header가 없거나 redirect/preflight에서 policy가 실패했습니다.", checks: ["Console CORS message와 request/final origin을 확인합니다.", "Access-Control-Allow-Origin/Credentials/Vary를 봅니다.", "curl 성공과 browser readable 여부를 구분합니다."], fix: "target server CORS를 정확히 구성하거나 allowlisted backend proxy/same-origin endpoint를 사용합니다.", prevention: "production origin별 CORS integration test와 redirect/preflight/credential matrix를 둡니다." },
      ],
    },
    {
      id: "domparser-error-document",
      title: "DOMParser의 XML parse는 성공 Document 또는 parsererror root를 가진 오류 Document를 반환합니다",
      lead: "try/catch만으로 well-formedness를 판단하지 말고 returned Document의 root/localName을 검사합니다.",
      explanations: [
        "`new DOMParser().parseFromString(text,'application/xml')`은 namespace-enabled XML parser로 Unicode string을 parse합니다. HTTP byte encoding은 이미 text conversion 단계에서 처리되었고 DOMParser에는 JavaScript string이 전달됩니다.",
        "well-formed XML이면 documentElement가 source root element입니다. tag mismatch·multiple root·unescaped ampersand 같은 fatal syntax면 많은 browser가 parsererror element를 root 또는 descendant로 가진 error Document를 반환합니다. 일반적으로 exception만 기대하면 오류 data를 정상처럼 처리합니다.",
        "spec 기준 parsererror localName과 namespace를 검사할 수 있지만 browser error markup/detail은 차이가 있을 수 있습니다. `documentElement.localName==='parsererror'`와 getElementsByTagNameNS('*','parsererror')를 helper로 캡슐화하고 실제 target browser를 test합니다.",
        "parsererror message 전체를 최종 사용자에게 그대로 보여 주면 browser/version/path detail이 노출되고 이해하기 어렵습니다. 사용자에게는 '데이터 형식 오류', developer telemetry에는 sanitized source URL·length·root/error category를 기록합니다.",
        "XML parse 성공은 application schema 유효성과 다릅니다. 예상 root/catalog/item, 필수 attribute, numeric range, duplicate id를 별도 validate한 뒤 render합니다.",
      ],
      concepts: [
        { term: "DOMParser", definition: "string을 지정한 HTML/XML media type parser로 분석해 새 Document를 반환하는 browser API입니다.", detail: ["application/xml은 namespace-aware XML parser입니다.", "동기 parse라 큰 document는 main thread를 막을 수 있습니다."] },
        { term: "parsererror document", definition: "XML well-formedness 실패를 parsererror element로 표현해 반환한 Document입니다.", detail: ["exception과 다릅니다.", "error text markup은 browser-dependent할 수 있습니다."] },
        { term: "shape validation", definition: "syntax parse 뒤 application이 기대하는 root·element·attribute·type·cardinality를 검사하는 단계입니다.", detail: ["well-formed와 별개입니다.", "render 전에 수행합니다."] },
      ],
      codeExamples: [
        {
          id: "xml-parser-valid-invalid",
          title: "정상/오류 XML Document를 같은 helper로 판정하기",
          language: "html",
          filename: "xml-parser.html",
          purpose: "DOMParser가 invalid input에서 throw하지 않고 parsererror Document를 돌려주는 behavior를 stable boolean output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>XML parser</title></head>\n<body>\n  <pre id=\"result\"></pre>\n  <script>\n    const parser = new DOMParser();\n    const parse = (source) => parser.parseFromString(source, 'application/xml');\n    const hasError = (doc) => doc.documentElement.localName === 'parsererror' ||\n      doc.getElementsByTagNameNS('*', 'parsererror').length > 0;\n\n    const good = parse('<catalog><item id=\"1\">XML</item></catalog>');\n    const bad = parse('<catalog><item></catalog>');\n    document.querySelector('#result').textContent = [\n      `good-root=${good.documentElement.localName}`,\n      `good-error=${hasError(good)}`,\n      `good-items=${good.getElementsByTagName('item').length}`,\n      `bad-error=${hasError(bad)}`,\n      `bad-root=${bad.documentElement.localName}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-10", explanation: "application/xml parser와 root/namespace-aware parsererror helper를 정의합니다." },
            { lines: "12-13", explanation: "정상 catalog와 closing tag mismatch input을 각각 parse합니다." },
            { lines: "14-20", explanation: "root·error boolean·item count만 출력해 browser별 error message text 차이를 피합니다." },
          ],
          run: { environment: ["DOMParser XML을 지원하는 Chromium 계열 browser"], command: "browser에서 xml-parser.html 열기" },
          output: { value: "good-root=catalog\ngood-error=false\ngood-items=1\nbad-error=true\nbad-root=parsererror", explanation: ["정상 Document의 root와 item을 읽습니다.", "invalid source는 catch가 아니라 error Document로 확인합니다.", "Firefox 등에서는 parsererror placement/detail을 helper와 target test로 확인합니다."] },
          experiments: [
            { change: "bad source를 '<a/><b/>'로 바꿉니다.", prediction: "multiple document elements 때문에 bad-error=true입니다.", result: "XML Document는 단일 root가 필요합니다." },
            { change: "bad source의 item을 self-closing '<item/>'로 바꿉니다.", prediction: "well-formed가 되어 bad-error=false, root=catalog입니다.", result: "empty-element syntax는 valid합니다." },
            { change: "parse type을 text/html로 바꿉니다.", prediction: "HTML parser가 error recovery하고 html root를 반환해 같은 XML error semantics가 아닙니다.", result: "parser media type은 grammar와 recovery model을 결정합니다." },
          ],
          sourceRefs: ["web-fetch-xml-source", "dom-parsing"],
        },
      ],
      diagnostics: [
        { symptom: "잘못된 XML인데 catch가 실행되지 않고 querySelectorAll 결과가 0이라 empty state로 보인다.", likelyCause: "DOMParser가 parsererror Document를 반환했는데 root/error 검사를 생략했습니다.", checks: ["documentElement localName/namespace를 기록합니다.", "parsererror helper를 실행합니다.", "raw source 첫 안전한 snippet과 content-type/status를 확인합니다."], fix: "parse 직후 parsererror를 검사하고 parse failure와 valid empty data를 별도 state로 처리합니다.", prevention: "tag mismatch·multiple root·unescaped entity fixture를 parser unit test에 둡니다." },
      ],
    },
    {
      id: "xml-dom-data-extraction",
      title: "XML DOM에서는 expanded name·attribute null·descendant text를 의식해 data를 추출합니다",
      lead: "querySelector('local') 한 줄은 no-namespace 단순 문서에는 편하지만 namespace와 mixed content에서 명시적인 API가 필요합니다.",
      explanations: [
        "getElementsByTagName('local')과 querySelectorAll('local')은 단순 문서에서 사용할 수 있습니다. namespace XML에서는 prefix spelling이 source마다 달라질 수 있으므로 `getElementsByTagNameNS(namespaceURI,'local')` 또는 namespace resolver가 있는 XPath가 expanded name을 안정적으로 찾습니다.",
        "default namespace는 element에 적용되지만 unprefixed attribute에는 적용되지 않습니다. `getAttribute('ta')`와 `getAttributeNS(uri,'ta')`를 data contract에 맞게 구분합니다. missing attribute는 null이며 empty string과 다른 상태입니다.",
        "element.textContent는 모든 descendant text node를 연결합니다. product element 안 name/description child가 있으면 단순 textContent가 둘을 합쳐 버릴 수 있습니다. direct child element 또는 expected text node를 명시해 읽습니다.",
        "whitespace indentation도 text node입니다. display name은 trim할 수 있지만 mixed content·preformatted/signature data에서는 whitespace가 의미 있을 수 있습니다. data normalization rule을 schema에 둡니다.",
        "XML Node를 HTML document에 그대로 append/import하면 namespace와 default styling/behavior가 HTML element와 다릅니다. data를 추출한 뒤 `document.createElement('td')` 등 HTML namespace element로 UI를 생성합니다.",
      ],
      concepts: [
        { term: "namespace-aware lookup", definition: "prefix text가 아니라 namespace URI와 local name으로 XML element/attribute를 찾는 방법입니다.", detail: ["getElementsByTagNameNS와 XPath resolver가 대표적입니다.", "prefix 변경에 견고합니다."] },
        { term: "descendant text", definition: "element.textContent가 자신 아래 모든 text node를 document order로 결합한 값입니다.", detail: ["mixed/nested content에서 field 하나보다 넓습니다.", "trim/normalize policy를 명시합니다."] },
        { term: "missing versus empty", definition: "attribute/element가 존재하지 않는 상태(null/0 node)와 존재하지만 값이 빈 문자열인 상태의 구분입니다.", detail: ["default/error 정책이 다를 수 있습니다.", "nullish coalescing 전에 의미를 정합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "namespace가 추가된 뒤 querySelectorAll('local')이 0개이거나 prefix 변경 때 code가 깨진다.", likelyCause: "qualified prefix 문자열에 의존하고 namespace URI를 사용하지 않았습니다.", checks: ["documentElement.namespaceURI와 target localName/namespaceURI를 기록합니다.", "getElementsByTagNameNS(uri,local) count를 비교합니다.", "default namespace와 attribute namespace를 분리합니다."], fix: "namespace URI/localName 기반 API 또는 resolver XPath로 전환하고 versioned namespace contract를 문서화합니다.", prevention: "동일 URI에 다른 prefix/default namespace를 사용한 equivalent fixture를 test합니다." },
      ],
    },
    {
      id: "safe-html-rendering",
      title: "XML value는 untrusted data로 취급하고 HTML string concatenation 대신 DOM element와 textContent로 렌더링합니다",
      lead: "XML DOM 안에서 inert했던 text도 innerHTML string에 삽입하면 HTML parser가 element/event handler로 재해석할 수 있습니다.",
      explanations: [
        "원본은 `output += '<td>'+name+'</td>'` 후 log.innerHTML을 사용합니다. name이 `<img src=x onerror=...>` 같은 text/attribute 값을 포함하면 HTML markup으로 해석되어 XSS가 될 수 있습니다. source가 같은 origin/local file이어도 공급 chain·server compromise·user data를 고려합니다.",
        "`document.createElement('tr')`, `td.textContent=value`, append로 만들면 value의 `<>&`가 text로 들어가 code로 실행되지 않습니다. table caption/thead/th scope/tbody를 실제 semantic element로 생성합니다.",
        "DocumentFragment에 row를 모아 한 번 append하면 반복 DOM mutation을 줄입니다. 수천 row는 pagination/virtualization/Web Worker parse를 고려하지만 screen reader table relationship과 find/copy/export를 보존합니다.",
        "inline style에 XML color 값을 그대로 넣거나 style attribute string을 조립하지 않습니다. color는 allowlist/validated CSS color로 custom property에 setProperty하거나 text label과 함께 제공합니다. URL은 URL parser·scheme allowlist 후 href/property에 설정합니다.",
        "Trusted Types/CSP는 defense-in-depth이며 textContent를 기본 sink로 선택하는 것이 우선입니다. sanitization이 필요한 rich HTML payload는 명확한 format/schema와 검증된 sanitizer를 사용하고 XML data field와 분리합니다.",
      ],
      concepts: [
        { term: "injection sink", definition: "문자열을 HTML/CSS/URL/JavaScript code 문맥으로 parse해 실행·해석할 수 있는 API 위치입니다.", detail: ["innerHTML이 대표적입니다.", "문맥별 encoder/sanitizer가 다릅니다."] },
        { term: "textContent rendering", definition: "untrusted string을 markup이 아닌 DOM text node value로 설정하는 기본 안전 pattern입니다.", detail: ["HTML special character를 code로 해석하지 않습니다.", "style/URL context에는 별도 validation이 필요합니다."] },
        { term: "DocumentFragment", definition: "여러 DOM node를 document 밖에서 모아 한 번에 삽입하는 lightweight node container입니다.", detail: ["batch rendering에 유용합니다.", "append 후 fragment 자체는 비워집니다."] },
      ],
      codeExamples: [
        {
          id: "safe-xml-table-renderer",
          title: "XML item을 createElement/textContent로 안전한 table에 렌더링",
          language: "html",
          filename: "xml-table.html",
          purpose: "markup처럼 생긴 item text가 실행되지 않고 literal text로 table cell에 남는 것을 DOM 결과로 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>안전한 XML 표</title></head>\n<body>\n  <main><h1>과정 목록</h1><div id=\"result\"></div><pre id=\"check\"></pre></main>\n  <script>\n    const source = `<catalog>\n      <item level=\"기초\">HTML &amp; XML</item>\n      <item level=\"고급\">&lt;img src=x onerror=alert(1)&gt;</item>\n    </catalog>`;\n    const xml = new DOMParser().parseFromString(source, 'application/xml');\n    const table = document.createElement('table');\n    const caption = table.createCaption(); caption.textContent = '과정과 난이도';\n    const head = table.createTHead().insertRow();\n    for (const label of ['과정', '난이도']) { const th = document.createElement('th'); th.scope = 'col'; th.textContent = label; head.append(th); }\n    const body = table.createTBody();\n    for (const item of xml.getElementsByTagName('item')) {\n      const row = body.insertRow();\n      const name = row.insertCell(); name.textContent = item.textContent.trim();\n      const level = row.insertCell(); level.textContent = item.getAttribute('level') ?? '미정';\n    }\n    document.querySelector('#result').append(table);\n    document.querySelector('#check').textContent = [\n      `rows=${body.rows.length}`,\n      `images=${table.querySelectorAll('img').length}`,\n      `cell2=${JSON.stringify(body.rows[1].cells[0].textContent)}`\n    ].join('\\n');\n  </script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-10", explanation: "ampersand와 escaped img-like text를 가진 well-formed XML fixture를 만듭니다." },
            { lines: "12-16", explanation: "HTML table/caption/thead/th를 DOM API로 만들고 header scope를 설정합니다." },
            { lines: "17-22", explanation: "XML item마다 row/cell을 만들고 textContent와 null-aware attribute로 값을 넣습니다." },
            { lines: "24-28", explanation: "row count, 실제 img element count, 위험해 보이는 두 번째 cell literal text를 출력합니다." },
          ],
          run: { environment: ["현대 browser", "JavaScript enabled"], command: "browser에서 xml-table.html 열기" },
          output: { value: "rows=2\nimages=0\ncell2=\"<img src=x onerror=alert(1)>\"", explanation: ["img-like value는 literal cell text이며 실제 img node가 0개입니다.", "ampersand entity는 XML parse 후 HTML & XML text가 됩니다.", "table semantic structure는 screen reader header navigation에 사용됩니다."] },
          experiments: [
            { change: "name.textContent=...를 name.innerHTML=...로 바꿉니다.", prediction: "두 번째 value가 실제 img element가 되어 images=1이고 error handler 위험이 생깁니다.", result: "parsed XML data를 HTML string sink에 재삽입하면 다시 code로 해석됩니다." },
            { change: "level attribute를 첫 item에서 제거합니다.", prediction: "첫 row 난이도 cell은 미정이 됩니다.", result: "missing null과 empty value의 fallback policy를 명시합니다." },
            { change: "1000 item을 생성하고 각 row를 바로 result에 append합니다.", prediction: "동작하지만 repeated layout/paint와 긴 table UX 비용이 커질 수 있습니다.", result: "fragment/batch/pagination을 측정하고 semantics를 보존합니다." },
          ],
          sourceRefs: ["web-fetch-xml-source", "web-jquery-xml-source", "web-jquery-weather-source", "dom-standard", "wai-tables"],
        },
      ],
      diagnostics: [
        { symptom: "XML의 상품명에 tag 같은 문자열이 들어오자 page에서 image/script behavior가 실행된다.", likelyCause: "XML value를 HTML string에 concatenate해 innerHTML/.html() sink로 다시 parse했습니다.", checks: ["render path의 innerHTML/insertAdjacentHTML/jQuery .html을 찾습니다.", "table DOM에 예상치 않은 element가 생겼는지 확인합니다.", "CSP/Trusted Types report를 봅니다."], fix: "HTML DOM element를 만들고 value는 textContent로 설정하며 rich content는 별도 schema+sanitizer를 사용합니다.", prevention: "XSS payload fixture와 no-unsafe-HTML lint/Trusted Types policy를 CI에 둡니다." },
      ],
    },
    {
      id: "loading-error-empty-states",
      title: "data UI는 idle·loading·success·empty·HTTP·parse·shape·aborted 상태를 구분합니다",
      lead: "alert 하나나 catch message만 보여 주지 않고 사용자가 무엇을 할 수 있는지와 retry 안전성을 제공합니다.",
      explanations: [
        "button activation 시 disabled/aria-busy/status text로 loading을 알리고 이전 request를 abort하거나 sequence ID로 stale response를 무시합니다. 빠른 연속 click에서 느린 첫 response가 최신 결과를 덮지 않게 합니다.",
        "HTTP 404/500, network/CORS, XML parsererror, expected local element 0개, invalid numeric attribute, render exception을 다른 error code로 분리합니다. user message는 간결하고 developer evidence는 sanitized합니다.",
        "valid empty XML은 오류가 아니라 empty state입니다. '지역 정보가 없습니다'와 retry/filter reset을 제공합니다. parsererror를 empty로 숨기지 않습니다.",
        "AbortError는 사용자가 새 request를 시작했거나 page를 떠난 정상 control flow일 수 있어 빨간 error로 표시하지 않습니다. timeout을 AbortSignal.timeout/support fallback으로 설계하고 server 부하를 고려합니다.",
        "성공 후 table caption에 data 기준 시각·source를 표시하고 stale/cache 상태를 알립니다. 외부 API가 변경되면 shape validation과 monitoring이 조기에 감지합니다.",
      ],
      concepts: [
        { term: "AbortController", definition: "fetch 등 abort-aware operation에 cancellation signal을 전달하는 Web API입니다.", detail: ["stale request와 navigation cleanup에 사용합니다.", "AbortError를 expected state로 처리합니다."] },
        { term: "stale response race", definition: "먼저 시작한 느린 request가 나중 request보다 늦게 완료되어 최신 UI state를 덮는 concurrency 오류입니다.", detail: ["abort 또는 request generation으로 방지합니다.", "button disable만으로 모든 경우를 막지 못합니다."] },
        { term: "empty state", definition: "request·parse·shape는 성공했지만 표시할 record가 0개인 정상 application state입니다.", detail: ["error와 구분합니다.", "사용자 다음 action을 제공합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "빠르게 두 지역을 누르면 마지막 선택이 서울인데 부산 weather가 뒤늦게 화면을 덮는다.", likelyCause: "동시 fetch의 completion order를 UI intent order와 동일하다고 가정했습니다.", checks: ["request 시작/완료 ID와 selected key를 기록합니다.", "AbortController가 이전 request에 연결됐는지 봅니다.", "render 직전 current generation을 확인합니다."], fix: "이전 controller를 abort하거나 monotonically increasing request ID가 최신일 때만 render합니다.", prevention: "delayed/reordered response를 가진 deterministic race integration test를 둡니다." },
      ],
    },
    {
      id: "jquery-modern-boundary",
      title: "jQuery XML AJAX와 modern Fetch의 차이는 syntax보다 conversion·error·cancellation·DOM sink ownership입니다",
      lead: "legacy code를 그대로 부정하지 않고 library가 대신하던 동작을 inventory한 뒤 native API로 옮깁니다.",
      explanations: [
        "`$.ajax({dataType:'xml'})`은 request·response conversion과 success/error callback을 제공합니다. `$(response).find('product')`는 XML DOM을 jQuery wrapper로 탐색합니다. modern Fetch에서는 status check·text consume·DOMParser·parsererror를 application이 명시합니다.",
        "jQuery `.text()`는 textContent 계열 안전 sink지만 `.html(tableString)`은 string HTML sink입니다. native migration에서 단순 `.html`→innerHTML 치환은 XSS 위험을 그대로 보존합니다. DOM construction으로 함께 교정합니다.",
        "original error callback의 `response.message`는 jqXHR 표준 error detail이 아닐 수 있어 빈 alert가 될 수 있습니다. status/statusText/errorThrown·responseText를 privacy-safe mapping하고 user error region을 DOM에 둡니다.",
        "AJAX는 역사적으로 asynchronous JavaScript and XML이라는 이름이지만 JSON/text/blob도 사용합니다. format과 transport/library를 분리해 설명합니다. fetch JSON example의 double consume도 XML과 같은 Response stream contract입니다.",
        "migration은 URL/status/headers/credentials/cache/timeout/abort/data conversion/render output test를 동일 fixture로 비교합니다. jQuery가 필요 없는 경우 제거하되 legacy plugin/browser contract가 남으면 boundary wrapper로 단계적으로 옮깁니다.",
      ],
      concepts: [
        { term: "conversion ownership", definition: "HTTP body를 XML/JSON/text object로 변환하고 오류를 분류하는 책임이 library와 application 중 어디에 있는지 정한 경계입니다.", detail: ["migration 때 누락되기 쉽습니다.", "contract test로 고정합니다."] },
        { term: "safe sink migration", definition: "legacy DOM API를 native로 바꿀 때 결과만 같게 하지 않고 text/HTML/URL/style sink의 security semantics를 보존·개선하는 작업입니다.", detail: [".html→innerHTML 기계 치환을 피합니다.", "payload fixture로 test합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "jQuery XML code를 Fetch로 바꾼 뒤 404 HTML이 empty XML처럼 보이거나 error message가 달라졌다.", likelyCause: "jQuery의 status/conversion/error callback behavior를 명시적으로 대체하지 않았습니다.", checks: ["old/new request status·content-type·body read·parse flow를 표로 비교합니다.", "404/invalid/empty fixtures를 실행합니다.", "render sink 차이를 확인합니다."], fix: "fetch wrapper에 status/content-type/body-once/parse/shape/error mapping을 명시하고 동일 contract tests를 통과시킵니다.", prevention: "migration checklist에 transport/conversion/error/cancel/render/security parity를 포함합니다." },
      ],
    },
    {
      id: "performance-security-production",
      title: "production XML 처리는 main-thread parse 비용·entity/security policy·schema drift·observability를 함께 관리합니다",
      lead: "작은 local fixture가 동작해도 수십 MB XML·악성 entity·unexpected namespace·민감 data에서 같은 방식은 안전하지 않습니다.",
      explanations: [
        "DOMParser는 전체 string을 동기 parse해 전체 DOM tree를 memory에 만듭니다. 큰 feed는 download text+DOM 두 representation과 HTML rows까지 memory를 사용하고 main thread를 막습니다. server pagination/transform, worker parser, streaming/SAX-like parser를 검토합니다.",
        "browser DOMParser와 server XML library의 external entity/DTD behavior는 같다고 가정하지 않습니다. server parser에서는 DTD/external entity/XInclude를 disable하고 entity expansion/resource limit을 두며 XXE·billion-laughs 방어를 검증합니다. client에도 untrusted size/depth/count limit을 둡니다.",
        "XML signature/canonicalization이 필요한 security protocol은 DOM text normalization이나 serialize/parse round-trip으로 임의 처리하지 않습니다. 검증된 library와 algorithm/namespace/c14n contract를 사용합니다.",
        "schema version·namespace URI·required fields·numeric/date range를 telemetry metric으로 기록하고 unknown field는 forward compatibility policy에 따라 ignore/reject합니다. raw PII/XML은 log하지 않습니다.",
        "Content Security Policy와 Trusted Types는 unsafe HTML sink를 제한하고, Subresource/endpoint integrity·TLS·authentication/authorization·cache poisoning도 transport layer에서 설계합니다. CORS 허용은 data 신뢰를 의미하지 않습니다.",
      ],
      concepts: [
        { term: "tree amplification", definition: "source text를 DOM node/object와 rendered HTML로 여러 번 확장하면서 memory/CPU 사용이 커지는 현상입니다.", detail: ["size/depth/count limit이 필요합니다.", "large fixture로 측정합니다."] },
        { term: "XXE/entity expansion", definition: "XML parser의 external entity/DTD 또는 반복 entity expansion을 악용해 file/network 접근·resource exhaustion을 일으키는 공격 범주입니다.", detail: ["parser별 secure configuration을 사용합니다.", "browser/server behavior를 혼동하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "큰 XML을 누르면 UI가 수 초 멈추고 memory가 급증한다.", likelyCause: "response text·full XML DOM·table DOM을 main thread에 동시에 생성했습니다.", checks: ["Performance long task와 Memory heap/node count를 측정합니다.", "body bytes·XML node·render row 수를 기록합니다.", "server pagination/worker 가능성을 봅니다."], fix: "server에서 page/normalize하거나 worker/stream parser와 incremental bounded rendering을 사용하고 size/depth/count limit을 적용합니다.", prevention: "max-size/depth/count budget과 large/malicious fixture load test를 둡니다." },
      ],
      expertNotes: [
        "XPathEvaluator는 namespace resolver와 result type을 명시하면 complex query에 유용하지만 untrusted XPath string injection과 document size를 고려합니다. 단순 field는 DOM traversal이 더 읽기 쉽습니다.",
        "XMLSerializer는 namespace/prefix/empty-element serialization을 보존 가능한 형태로 만들지만 원 byte·attribute order·encoding declaration과 동일하다는 보장은 없습니다. digital signature는 canonicalization library를 사용합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 weather/product XML loader를 안전하고 취소 가능한 accessible table component로 재작성하기",
    scenario: "현재 button은 jQuery/fetch로 XML을 받고 string table+innerHTML로 출력하며 HTTP/parse/empty 오류를 구분하지 않습니다. 빠른 연속 click과 malicious text에서 race/XSS가 발생합니다.",
    setup: ["원본 fetch/jQuery XML file 4개와 JSON contrast file을 read-only evidence로 준비합니다.", "same-origin local HTTP server와 valid/invalid/empty/namespace/malicious/large XML fixture를 준비합니다.", "DevTools Network/Performance/Accessibility와 request state log를 준비합니다."],
    steps: [
      "request URL/status/content-type/bodyUsed/length를 기록하고 response body를 text로 한 번만 읽습니다.",
      "DOMParser application/xml 후 parsererror helper와 expected root/required field shape validation을 적용합니다.",
      "namespace URI/localName으로 local/product element를 찾고 missing/empty/invalid attribute policy를 적용합니다.",
      "caption/thead/th scope/tbody를 HTML DOM API로 만들고 모든 XML value를 textContent로 삽입합니다.",
      "idle/loading/success/empty/HTTP/network/parse/shape/abort state와 accessible status/error/focus를 구현합니다.",
      "AbortController/generation ID로 stale response race를 막고 retry/cache 정책을 정의합니다.",
      "CORS/file:// failure와 safe same-origin/server proxy 경계를 재현·문서화합니다.",
      "XSS·large/deep/entity-like fixture로 sink/size/performance/security test를 실행합니다.",
    ],
    expectedResult: ["HTTP 404와 network/CORS, invalid XML, valid empty를 서로 다른 상태로 표시합니다.", "Response body는 한 번만 consume되고 double-read test가 실패를 포착합니다.", "namespace prefix가 바뀌어도 URI/localName lookup 결과가 같습니다.", "malicious markup-like value가 literal text이며 executable element가 0개입니다.", "연속 request에서 최신 선택만 render되고 abort는 오류로 과장되지 않습니다.", "table caption/header/keyboard/320px scroll과 large-data budget이 검증됩니다."],
    cleanup: ["malicious/large fixture와 debug raw XML log를 public artifact에서 제거하거나 synthetic test 영역에 격리합니다.", "local server·throttle·CORS test proxy를 종료하고 production endpoint allowlist를 확인합니다."],
    extensions: ["Web Worker에서 XML parse/normalize하고 structured-clone 가능한 plain data만 main thread로 보내 성능을 비교합니다.", "server-side secure XML parser configuration과 client shape schema를 공유 contract test로 연결합니다.", "same data를 JSON으로 제공했을 때 bytes/parse/schema/render/error를 다음 format-choice 세션에서 비교합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "valid/invalid/empty XML 세 string을 DOMParser로 분류하고 root/item count를 출력하세요.", requirements: ["application/xml type을 사용합니다.", "parsererror helper를 구현합니다.", "parse error와 valid empty를 구분합니다.", "missing attribute null과 empty string을 따로 출력합니다."], hints: ["try/catch만 사용하지 않습니다.", "documentElement.localName과 namespace-aware parsererror를 봅니다."], expectedOutcome: "세 fixture가 success-data/syntax-error/success-empty로 정확히 분류됩니다.", solutionOutline: ["parse→error check→root validation→item extraction 순서로 함수를 나눕니다.", "boolean/count 기반 stable output을 사용합니다."] },
    { difficulty: "응용", prompt: "weather XML을 accessible table로 안전하게 렌더링하세요.", requirements: ["fetch status/body-once/parse/shape를 검사합니다.", "지역·온도·상태를 namespace-aware하게 읽습니다.", "DOM createElement/textContent만 사용합니다.", "caption/th scope와 loading/empty/error state를 제공합니다.", "malicious text·race·CORS/404 fixture를 test합니다."], hints: ["innerHTML string table을 만들지 않습니다.", "old request를 abort하거나 generation을 확인합니다."], expectedOutcome: "정상 data는 accessible table, 실패는 구체 state로 보이고 XSS/race가 없습니다.", solutionOutline: ["transport/parse/normalize/render state machine을 만듭니다.", "render function은 plain normalized record만 받게 합니다."] },
    { difficulty: "설계", prompt: "browser XML ingestion library의 API·security·observability·migration contract를 설계하세요.", requirements: ["status/content-type/body ownership/abort/retry/cache API를 정의합니다.", "parsererror/namespace/shape/version/limit policy를 포함합니다.", "safe DOM sink와 rich content 금지/예외 policy를 만듭니다.", "jQuery→Fetch migration parity와 error code를 정의합니다.", "large XML worker/server transform·XXE server configuration·PII logging test를 설계합니다."], hints: ["transport 성공과 data trust를 분리합니다.", "XML Document를 UI 곳곳에 전달하지 말고 normalized type boundary를 고려합니다."], expectedOutcome: "여러 XML endpoint가 동일한 secure pipeline·error model·test fixture로 처리되는 구현 가능한 library specification이 완성됩니다.", solutionOutline: ["bytes→text→DOM→normalized record→HTML state boundary를 API로 분리합니다.", "각 경계의 owner/limit/telemetry를 표로 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "fetch는 404에서 자동으로 catch로 가나요?", answer: "보통 아닙니다. Response가 fulfilled되므로 response.ok/status를 직접 검사해야 합니다." },
    { question: "response.json 또는 text를 두 번 호출해도 되나요?", answer: "같은 Response body는 한 번 consume됩니다. 변수로 재사용하거나 첫 read 전에 clone해야 합니다." },
    { question: "CORS 오류는 XML이라서 생기나요?", answer: "아닙니다. origin과 server CORS policy 문제이며 JSON/text에도 같습니다." },
    { question: "mode:no-cors를 쓰면 cross-origin XML을 읽을 수 있나요?", answer: "아닙니다. opaque response body/status를 JavaScript가 읽을 수 없어 data parsing 해결책이 아닙니다." },
    { question: "DOMParser는 invalid XML에서 항상 exception을 던지나요?", answer: "아닙니다. 일반적으로 parsererror Document를 반환하므로 root/namespace-aware error 검사가 필요합니다." },
    { question: "parse 성공이면 data가 유효한가요?", answer: "well-formed syntax만 확인된 것입니다. root·namespace·required field·type/range/cardinality를 별도 검증합니다." },
    { question: "element.textContent는 그 element의 직접 text만 반환하나요?", answer: "아닙니다. descendant text node 전체를 연결하므로 mixed/nested content에서는 field를 명시적으로 탐색합니다." },
    { question: "XML 값은 이미 parser를 통과했으니 innerHTML에 넣어도 안전한가요?", answer: "아닙니다. HTML parser가 다시 markup으로 해석할 수 있으므로 textContent/DOM API를 사용합니다." },
    { question: "AbortError는 항상 사용자에게 실패로 보여야 하나요?", answer: "새 요청·navigation으로 의도적으로 취소한 정상 control flow일 수 있어 별도 처리합니다." },
  ],
  completionChecklist: [
    "fetch network/CORS와 HTTP status를 분리하고 response.ok를 확인했다.",
    "Response body를 한 번만 소비하고 bodyUsed/double-read를 test했다.",
    "DOMParser application/xml 뒤 parsererror와 expected root/shape를 검사했다.",
    "namespace URI/localName·missing/empty·descendant/direct text를 구분했다.",
    "XML value는 HTML DOM API/textContent로 렌더링하고 unsafe HTML sink를 제거했다.",
    "accessible table caption/header와 loading/empty/error/retry/focus state를 제공했다.",
    "AbortController/generation으로 stale response race를 막았다.",
    "large/deep/malicious XML과 server secure-parser/size/logging policy를 검증했다.",
  ],
  nextSessions: ["xml-04-json-yaml-format-choice"],
  sources: [
    { id: "web-fetch-xml-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex14_fetch.html", usedFor: ["fetch weather XML", "response.ok/text", "DOMParser/parsererror", "local element/attribute", "innerHTML table"], evidence: "원본 전체 pipeline을 audit해 CORS·single body·shape state·safe DOM rendering으로 확장했습니다." },
    { id: "web-fetch-json-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex15_fetch.html", usedFor: ["Response JSON double consume", "HTTP error construction", "dynamic table/style", "format contrast"], evidence: "response.json 두 번 호출 문제를 XML과 공통인 body stream contract의 exact example으로 사용했습니다." },
    { id: "web-jquery-xml-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day12/ex10_ajax.html", usedFor: ["jQuery dataType xml", "find product", "text/attr", "html sink"], evidence: "자동차 XML AJAX를 Fetch conversion ownership과 safe-sink migration 비교에 반영했습니다." },
    { id: "web-jquery-weather-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day12/ex11_ajax.html", usedFor: ["weather local", "null fallback", "jQuery XML", "table"], evidence: "지역·온도·상태 extraction을 missing/empty policy와 accessible table lab의 근거로 사용했습니다." },
    { id: "web-jquery-text-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day12/ex14_ajax.html", usedFor: ["text format AJAX", "delimiter parse", "innerHTML table", "format boundary"], evidence: "text split rendering을 syntax/shape/safe DOM boundary의 대비 사례로 감사했습니다." },
    { id: "dom-parsing", repository: "W3C Web Platform Working Group", path: "TR/DOM-Parsing/", publicUrl: "https://www.w3.org/TR/DOM-Parsing/", usedFor: ["DOMParser", "application/xml", "parsererror root/namespace", "XMLSerializer"], evidence: "DOM Parsing and Serialization의 XML parsererror return model을 browser parse helper의 공식 근거로 사용했습니다." },
    { id: "fetch-standard", repository: "WHATWG Fetch Standard", path: "", publicUrl: "https://fetch.spec.whatwg.org/", usedFor: ["Response type/body", "consume body", "text UTF-8 decode", "unusable TypeError", "CORS"], evidence: "2026-07-12 기준 Fetch living standard의 body single-consumption과 response/CORS model을 transport 설명에 반영했습니다." },
    { id: "dom-standard", repository: "WHATWG DOM Standard", path: "", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["Document/Element/Text", "namespace", "textContent", "DOM construction", "tree traversal"], evidence: "XML/HTML DOM node·namespace·textContent rendering의 platform model을 사용했습니다." },
    { id: "wai-tables", repository: "W3C Web Accessibility Initiative", path: "tutorials/tables/", publicUrl: "https://www.w3.org/WAI/tutorials/tables/", usedFor: ["caption", "header scope", "table navigation", "responsive data"], evidence: "동적 table도 static table과 같은 caption/header relationship을 제공하도록 검증 기준에 반영했습니다." },
  ],
  sourceCoverage: {
    filesRead: 5,
    filesUsed: 5,
    uncoveredNotes: [
      "원본은 fetch와 jQuery를 통해 XML·JSON·text를 가져와 table로 표현하는 전체 흐름을 포함합니다. single-use body, namespace-aware API, race/cancel, DOM XSS, large XML/security boundary는 공식 Fetch/DOM 자료로 보강했습니다.",
      "서버 XML parser의 library별 secure configuration과 schema validation 구현은 Java/Spring data integration 세션에서 구체화하고 다음 xml-04에서는 JSON/YAML과 format 선택을 비교합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 390;
expertSession.chapters.push(
  {
    id: "streaming-byte-decoding-body-lifecycle",
    title: "Response stream·byte decoding·body 수명을 DOMParser 앞에서 제어합니다",
    lead: "fetch 결과를 곧바로 XML Document라고 부르지 않고 status·media type·byte stream·Unicode string·parser Document·validated records 단계를 각각 검증합니다.",
    explanations: [
      "fetch는 Request를 보내고 Response headers/body를 비동기로 제공합니다. Promise가 fulfill되어도 404·500일 수 있으므로 status/ok와 허용 status를 먼저 검사합니다. 204처럼 성공이지만 body가 없는 status를 XML parse error로 오인하지 않습니다.",
      "Content-Type은 parser 선택의 transport contract입니다. `application/xml`, `text/xml`, 합의한 `+xml`만 허용하고 HTML 오류 page나 JSON을 XML parser에 넘기지 않습니다. header comparison은 parameter를 제거한 case-insensitive media type으로 수행하며 charset 의미는 Fetch decoding 규칙과 target runtime에서 확인합니다.",
      "Response body는 ReadableStream이며 text/json/arrayBuffer 같은 convenience method는 한 번 소비합니다. bodyUsed와 stream lock을 관찰하고, log와 parse용으로 같은 Response를 두 번 읽지 않습니다. 두 consumer가 정말 필요하면 읽기 전에 clone하지만 큰 body buffering 비용을 측정합니다.",
      "network chunk는 UTF-8 character·entity·tag 경계와 일치하지 않습니다. 직접 reader를 사용하면 하나의 TextDecoder에 stream:true를 주고 끝에서 flush합니다. invalid byte를 replacement로 허용할지 fatal decode error로 만들지 정하고, XML declaration은 이미 Unicode string이 된 뒤 decoder를 다시 선택하지 않습니다.",
      "DOMParser.parseFromString은 완전한 string을 받아 synchronous하게 tree를 만듭니다. streaming read를 했더라도 accumulated text와 XML DOM이 동시에 memory에 존재할 수 있어 peak memory와 main-thread parse time을 제한해야 합니다. 매우 큰 feed는 server transform·pagination·worker/streaming parser architecture를 비교합니다.",
      "Content-Length는 누락·압축·오류·CORS exposure 제한이 있어 안전한 실제 크기 보장이 아닙니다. reader 단계에서 실제 bytes/chars를 count하고 한도 초과 시 reader.cancel과 fetch AbortController를 실행합니다. partial string/tree를 성공 UI로 render하지 않습니다.",
      "reader.read가 reject하거나 stream이 중간 종료되고 XML closing tag가 없으면 decode와 well-formedness 중 정확한 stage error로 분류합니다. network error, HTTP status, media mismatch, DECODE_ERROR, PARSE_ERROR, NAMESPACE_ERROR, SCHEMA_ERROR와 LIMIT_EXCEEDED를 하나의 catch message로 뭉개지 않습니다.",
      "CORS는 browser가 cross-origin response를 script에 노출할지 정하는 protocol이고 server authentication/authorization을 대신하지 않습니다. fetch TypeError는 CORS·CSP·mixed content·network를 포함할 수 있어 Console과 Network panel, server correlation을 함께 봅니다. raw response나 credential을 log하지 않습니다.",
      "cache와 service worker는 network 요청 없이 오래된 XML을 반환할 수 있습니다. Network의 Size/Transferred/ServiceWorker/Timing과 Cache-Control·ETag·Vary를 확인하고 schema/version migration을 cache rollout과 함께 test합니다. DevTools Disable cache가 실제 사용자 조건과 다름도 기록합니다.",
      "test는 multi-byte split, empty/204, wrong Content-Type, body double-read, invalid byte, truncated/oversize stream, abort mid-read, cached old namespace와 parsererror를 포함합니다. 각 fixture의 stage code, pending reader/network 0과 stale render 0을 assertion합니다.",
    ],
    concepts: [
      { term: "body consumption", definition: "Response body stream을 읽거나 취소해 disturbed 상태로 만드는 lifecycle입니다.", detail: ["같은 body는 일반적으로 한 번만 읽습니다.", "reader·clone·cancel ownership을 정합니다."] },
      { term: "streaming decoder", definition: "chunk 사이의 불완전 multi-byte sequence를 한 TextDecoder가 유지하며 bytes를 Unicode로 바꾸는 방식입니다.", detail: ["stream:true와 마지막 flush를 사용합니다.", "invalid-byte policy를 명시합니다."] },
      { term: "pipeline stage error", definition: "network/HTTP/media/decode/parse/namespace/schema/limit 중 실패한 경계를 안정적인 code로 구분한 오류입니다.", detail: ["복구 action과 telemetry가 달라집니다.", "raw payload를 노출하지 않습니다."] },
    ],
    codeExamples: [
      {
        id: "response-stream-xml-decode-parse",
        title: "UTF-8 chunk를 streaming decode한 뒤 XML을 한 번 parse",
        language: "html",
        filename: "xml-response-stream.html",
        purpose: "synthetic Response의 status·Content-Type을 확인하고 한글 byte 중간에서 나뉜 body를 한 decoder로 복원한 뒤 DOMParser와 bodyUsed를 exact 검증합니다.",
        code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>XML response stream</title></head>\n<body>\n  <pre id=\"out\" aria-live=\"polite\"></pre>\n  <script type=\"module\">\n    const bytes = new TextEncoder().encode('<catalog><product>한글</product></catalog>');\n    const firstMultibyte = bytes.findIndex((byte) => byte >= 0x80);\n    const split = firstMultibyte + 1;\n    const stream = new ReadableStream({\n      start(controller) {\n        controller.enqueue(bytes.slice(0, split));\n        controller.enqueue(bytes.slice(split));\n        controller.close();\n      },\n    });\n    const response = new Response(stream, {\n      status: 200,\n      headers: { 'content-type': 'application/xml; charset=utf-8' },\n    });\n\n    const reader = response.body.getReader();\n    const decoder = new TextDecoder('utf-8', { fatal: true });\n    let source = '';\n    while (true) {\n      const { value, done } = await reader.read();\n      if (done) break;\n      source += decoder.decode(value, { stream: true });\n    }\n    source += decoder.decode();\n    const documentNode = new DOMParser().parseFromString(source, 'application/xml');\n    if (documentNode.getElementsByTagNameNS('*', 'parsererror').length) throw new Error('PARSE_ERROR');\n    const lines = [\n      `status=${response.status}`,\n      `content-type=${response.headers.get('content-type')}`,\n      `product=${documentNode.querySelector('product').textContent}`,\n      `bodyUsed=${response.bodyUsed}`,\n    ];\n    document.querySelector('#out').textContent = lines.join('\\n');\n    console.log(lines.join('\\n'));\n  </script>\n</body>\n</html>",
        walkthrough: [
          { lines: "1-6", explanation: "browser shell, live 결과와 module script를 준비합니다." },
          { lines: "7-16", explanation: "한글 UTF-8 bytes를 첫 multi-byte 문자 내부에서 나누어 두 chunk Response source를 만듭니다." },
          { lines: "17-21", explanation: "명시적 200 status와 XML Content-Type을 가진 synthetic Response를 구성합니다." },
          { lines: "22-30", explanation: "body reader와 한 fatal decoder로 모든 chunk를 streaming decode하고 끝에서 flush합니다." },
          { lines: "31-32", explanation: "완전한 string을 XML mode로 한 번 parse하고 parsererror를 거부합니다." },
          { lines: "33-40", explanation: "status/media/domain text/bodyUsed를 화면·Console에 exact 기록합니다." },
          { lines: "41-43", explanation: "script와 document를 닫고 Network·Memory·Accessibility 관찰을 수행합니다." },
        ],
        run: { environment: ["최신 Chromium 또는 Firefox", "xml-response-stream.html을 UTF-8로 저장", "DevTools Console·Network·Memory·Accessibility", "keyboard로 결과 영역 탐색"], command: "브라우저에서 xml-response-stream.html을 열고 pre·Console exact 출력, bodyUsed와 한글 복원을 확인" },
        output: { value: "status=200\ncontent-type=application/xml; charset=utf-8\nproduct=한글\nbodyUsed=true", explanation: ["status와 media type은 parser 전에 관찰됩니다.", "한글 bytes가 chunk 사이에서 나뉘어도 한 decoder가 원문을 복원합니다.", "reader가 stream을 소비한 뒤 bodyUsed는 true입니다."] },
        experiments: [
          { change: "각 chunk에서 새 TextDecoder로 decode합니다.", prediction: "분할된 한글에 replacement character가 생기고 extracted text가 손상됩니다.", result: "network chunk와 character boundary 차이를 확인합니다." },
          { change: "Content-Type을 text/html로 바꿉니다.", prediction: "synthetic body는 우연히 parse되더라도 production pipeline은 MEDIA_TYPE_ERROR로 먼저 거부해야 합니다.", result: "body sniffing보다 representation contract를 우선합니다." },
          { change: "read byte limit를 한글 뒤보다 작게 두고 초과 시 reader.cancel을 호출합니다.", prediction: "partial XML을 render하지 않고 LIMIT_EXCEEDED가 됩니다.", result: "header가 아니라 실제 소비량으로 resource limit을 적용합니다." },
        ],
        sourceRefs: ["web-fetch-xml-source", "web-jquery-text-source", "dom-parsing", "fetch-standard", "dom-standard"],
      },
    ],
    diagnostics: [
      { symptom: "XML 한글이 network 상황에 따라 간헐적으로 깨지고 parsererror가 난다.", likelyCause: "Response chunk마다 독립 decode해 multi-byte character가 chunk 경계에서 손상됐습니다.", checks: ["raw bytes를 한글 중간에서 분할해 재현합니다.", "하나의 TextDecoder·stream:true·flush 사용을 확인합니다.", "decode error와 XML parsererror를 별도 기록합니다."], fix: "한 decoder의 streaming state로 전체 bytes를 Unicode string으로 만든 뒤 DOMParser에 전달하고 invalid-byte 정책을 고정합니다.", prevention: "모든 byte split offset과 invalid UTF-8 fixture를 자동 검증합니다." },
      { symptom: "대용량 XML에서 cancel을 눌러도 download와 memory 증가가 계속된다.", likelyCause: "UI state만 바꾸고 reader.cancel·fetch abort·buffer references를 정리하지 않았습니다.", checks: ["Network pending/transfer와 active reader lock을 확인합니다.", "AbortSignal이 fetch와 reader owner까지 전달되는지 봅니다.", "accumulated source와 DOM retaining path를 검사합니다."], fix: "component lifecycle owner가 reader.cancel과 AbortController.abort를 실행하고 buffers/tree references를 해제하며 stale generation을 무시합니다.", prevention: "oversize·user cancel·route dispose 뒤 pending resource와 stale mutation 0을 검증합니다." },
    ],
    expertNotes: ["Response.text decoding과 generic XML processor의 byte encoding detection은 다른 layer입니다. target Fetch runtime 규격과 실제 bytes fixture로 확인합니다.", "DOMParser는 synchronous full-tree parser라 parseFromString 실행 중 AbortSignal로 중단할 수 없습니다. size/time architecture 결정을 호출 전에 끝냅니다."],
  },
  {
    id: "abort-latest-render-security-accessibility-observability",
    title: "AbortSignal·latest-wins·안전한 render·접근성·XXE runtime 경계를 함께 운영합니다",
    lead: "빠른 검색과 route 전환에서 이전 XML load를 실제 취소하고, 가장 최신 generation만 validated DOM을 semantic HTML로 render하게 만듭니다.",
    explanations: [
      "AbortController는 Promise에 cancelled state를 추가하지 않습니다. fetch처럼 signal을 지원하는 underlying operation에 전달하고 abort reason으로 rejection을 분류합니다. timer·custom loader는 abort listener에서 handle을 clear하고 성공/실패 종료에서도 listener를 제거해야 합니다.",
      "새 요청이 시작되면 이전 controller를 abort하고 generation을 증가시킵니다. abort가 network를 중단해도 이미 끝난 parse/transform Promise가 뒤늦게 이어질 수 있어 render 직전에 generation과 signal.aborted를 다시 확인합니다. latest-wins는 cancellation과 stale-result guard 둘 다 필요합니다.",
      "loading/error/empty/success/aborted 상태를 구분합니다. 이전 검색의 AbortError는 일반 오류 banner로 깜박이지 않게 할 수 있지만 timeout·offline·HTTP·schema error는 서로 다른 복구 action을 제공합니다. finally도 stale generation이면 최신 busy state를 false로 덮지 않습니다.",
      "XML DOM의 textContent·attribute 값은 external data입니다. HTML table은 createElement/textContent로 만들고 URL·class·style은 allowlist mapping을 사용합니다. XML parser가 markup을 tree로 만들었다는 사실이 그 text를 HTML innerHTML에 넣어도 안전하다는 뜻은 아닙니다.",
      "semantic table에는 caption, th와 scope, units, missing-value label이 필요합니다. loading/result count/error는 짧은 role=status 또는 aria-live에 전달하고 매 keypress마다 전체 table을 재공지하지 않습니다. filter 뒤 focused row가 사라지면 검색 input이나 논리적 다음 control로 focus 정책을 적용합니다.",
      "jQuery `$.get`, `$.ajax`, `.find()`를 modern fetch/DOM으로 옮길 때 status/CORS, jqXHR abort, Deferred timing, selector context와 result collection 차이를 parity test합니다. migration 중 jQuery와 native handler가 동시에 붙어 duplicate render·request가 생기지 않게 owner를 하나로 정합니다.",
      "browser DOMParser에서 external entity가 expansion되지 않았다는 관찰을 server Java/Python parser의 XXE 보장으로 사용하지 않습니다. production runtime에서 DTD, external general/parameter entities, XInclude, external schema/network access를 비활성화하고 expansion/depth/size limits를 실제 sentinel로 검증합니다.",
      "DOCTYPE가 필요 없는 browser app은 source에서 DTD를 거부하는 좁은 policy를 추가할 수 있지만 문자열 precheck는 secure parser configuration이나 sanitizer가 아닙니다. encoding·grammar variants와 다른 runtime behavior를 포괄하지 못합니다.",
      "Performance는 network, decode, synchronous parse, validation, render를 User Timing으로 분리합니다. record 수와 size bucket만 privacy-safe telemetry에 남기고 raw XML, query PII, URL token, parsererror text를 기록하지 않습니다. Long task와 memory를 large fixture에서 함께 봅니다.",
      "E2E는 rapid A→B request, abort before start/mid-read/after response, stale parse, route disposal, malformed/wrong namespace/oversize, malicious text, keyboard·screen reader를 포함합니다. 종료 뒤 pending request/timer/listener 0, latest render one, duplicate rows/listeners 0을 assertion합니다.",
    ],
    concepts: [
      { term: "latest-wins", definition: "여러 비동기 요청 중 현재 generation의 결과만 UI state를 변경하도록 cancellation과 identity guard를 결합한 정책입니다.", detail: ["이전 underlying work를 abort합니다.", "render/finally에서도 generation을 확인합니다."] },
      { term: "safe XML-to-HTML render", definition: "validated XML data를 HTML parser string sink가 아니라 semantic DOM node와 textContent, allowlisted properties로 표현하는 과정입니다.", detail: ["XML text도 untrusted입니다.", "URL/style/class는 별도 검증합니다."] },
      { term: "runtime-specific XML security", definition: "DTD/entity/XInclude/schema/network 기능과 resource limits를 실제 parser library·version·configuration별로 검증하는 원칙입니다.", detail: ["browser 결과를 server에 일반화하지 않습니다.", "file/network sentinel 접근 0을 테스트합니다."] },
    ],
    codeExamples: [
      {
        id: "abort-previous-latest-loader",
        title: "이전 loader의 timer를 실제 취소하고 latest 결과만 사용",
        language: "javascript",
        filename: "xml-latest-request.mjs",
        purpose: "AbortSignal을 지원하는 custom loader에서 previous resource를 정리하고 current result만 남기며 active handle이 0인지 Node에서 exact 확인합니다.",
        code: "let active = 0;\n\nfunction loadXml(label, { signal, delay }) {\n  return new Promise((resolve, reject) => {\n    if (signal.aborted) { reject(signal.reason); return; }\n    active += 1;\n    const cleanup = () => {\n      signal.removeEventListener('abort', onAbort);\n      active -= 1;\n    };\n    const timer = setTimeout(() => {\n      cleanup();\n      resolve(`<result>${label}</result>`);\n    }, delay);\n    const onAbort = () => {\n      clearTimeout(timer);\n      cleanup();\n      reject(signal.reason);\n    };\n    signal.addEventListener('abort', onAbort, { once: true });\n  });\n}\n\nconst previousController = new AbortController();\nconst previous = loadXml('old', { signal: previousController.signal, delay: 50 })\n  .catch((error) => error.name);\npreviousController.abort(new DOMException('stale request', 'AbortError'));\n\nconst currentController = new AbortController();\nconst current = await loadXml('new', { signal: currentController.signal, delay: 0 });\nconst currentLabel = /<result>([^<]+)<\\/result>/.exec(current)[1];\nconsole.log(`previous=${await previous}`);\nconsole.log(`latest=${currentLabel}`);\nconsole.log(`active=${active}`);",
        walkthrough: [
          { lines: "1-5", explanation: "active resource counter와 signal/delay를 받는 custom XML fixture loader를 정의합니다." },
          { lines: "6-20", explanation: "timer 생성·성공·abort 모든 경로가 listener와 active handle을 정확히 한 번 정리하게 합니다." },
          { lines: "23-26", explanation: "previous request를 시작한 직후 AbortError reason으로 실제 timer를 취소하고 rejection을 분류합니다." },
          { lines: "28-33", explanation: "current request를 완료하고 고정 fixture label을 관찰한 뒤 previous/latest/active exact 결과를 출력합니다. 정규식은 일반 XML parser가 아닙니다." },
        ],
        run: { environment: ["Node.js 20 이상", "xml-latest-request.mjs를 UTF-8로 저장"], command: "node xml-latest-request.mjs" },
        output: { value: "previous=AbortError\nlatest=new\nactive=0", explanation: ["previous timer는 abort listener에서 clear되고 AbortError로 분류됩니다.", "current loader의 new 결과만 latest로 사용됩니다.", "두 settle 경로 뒤 active resource count는 0입니다."] },
        experiments: [
          { change: "clearTimeout(timer)를 제거합니다.", prediction: "Promise state는 이미 rejected여도 old timer callback이 나중에 cleanup을 다시 실행해 active가 -1이 될 수 있습니다.", result: "wrapper rejection과 underlying resource cancellation을 분리합니다." },
          { change: "이미 aborted된 signal을 loadXml에 전달합니다.", prediction: "active를 증가시키기 전에 같은 reason으로 즉시 reject합니다.", result: "already-aborted entry contract를 확인합니다." },
          { change: "browser fetch adapter에서 generation guard를 제거하고 old parse를 일부러 늦춥니다.", prediction: "abort 시점에 이미 response가 끝났다면 old render가 new UI를 덮을 수 있습니다.", result: "underlying abort와 render identity guard를 함께 사용합니다." },
        ],
        sourceRefs: ["web-jquery-xml-source", "web-jquery-weather-source", "web-jquery-text-source", "fetch-standard", "dom-abort"],
      },
    ],
    diagnostics: [
      { symptom: "검색 B 결과가 보인 뒤 늦은 검색 A XML이 화면을 덮는다.", likelyCause: "이전 request를 abort하지 않았거나 response 이후 parse/render에 generation guard가 없습니다.", checks: ["request/response/parse/render에 generation id를 기록합니다.", "새 request에서 이전 controller.abort가 호출되는지 봅니다.", "finally도 최신 state만 갱신하는지 확인합니다."], fix: "새 요청에서 이전 work를 실제 abort하고 parse/render/finally 직전에 signal과 generation을 확인해 stale mutation을 중단합니다.", prevention: "A를 느리게, B를 빠르게 만든 deterministic race test에서 latest render one을 검증합니다." },
      { symptom: "XML의 지역명이 `<img onerror=...>`일 때 table에서 code로 실행된다.", likelyCause: "XML text를 innerHTML table string에 이어 붙여 HTML parser에 다시 전달했습니다.", checks: ["innerHTML/insertAdjacentHTML/template string sink를 inventory합니다.", "XML text가 entity decoding 뒤 어떤 string인지 확인합니다.", "URL/style/class assignments도 별도 검사합니다."], fix: "semantic table nodes를 createElement로 만들고 external values는 textContent, URL/style/class는 allowlist된 property mapping으로 설정합니다.", prevention: "tag-like text·javascript URL·CSS payload fixture와 CSP/Trusted Types report를 둡니다." },
    ],
    expertNotes: ["Node 예제의 regular expression은 고정된 loader label 관찰용입니다. production XML은 namespace-aware conforming parser와 schema/domain validator로 처리합니다.", "AbortError를 UI에서 숨기더라도 telemetry와 cleanup owner는 명확해야 하며 timeout·user cancel·route dispose reason을 privacy-safe category로 구분합니다."],
  },
);

expertSession.reviewQuestions.push(
  { question: "fetch Promise가 fulfill되면 XML load 전체가 성공한 건가요?", answer: "아닙니다. HTTP status, Content-Type, byte decoding, XML well-formedness, namespace/schema와 domain validation을 차례로 통과해야 합니다." },
  { question: "Response body를 response.text로 읽은 뒤 다시 reader로 읽을 수 있나요?", answer: "일반적으로 아닙니다. body는 single-consumption lifecycle이며 두 consumer가 필요하면 읽기 전에 clone 비용과 contract를 검토합니다." },
  { question: "AbortController만 호출하면 stale UI render가 항상 막히나요?", answer: "아닙니다. 이미 끝난 response나 진행 중인 parse/transform은 이어질 수 있어 render와 finally에서 generation/signal guard도 필요합니다." },
  { question: "XML text는 XML parser를 통과했으니 innerHTML에 넣어도 안전한가요?", answer: "아닙니다. external text가 HTML markup으로 다시 해석될 수 있으므로 textContent와 allowlisted DOM properties를 사용합니다." },
  { question: "browser DOMParser의 entity 동작으로 server XXE 안전성을 판단할 수 있나요?", answer: "아닙니다. production parser의 DTD/external entity/XInclude/schema/network 설정과 resource limits를 실제 runtime에서 검증해야 합니다." },
  { question: "XML table update를 screen reader에 알릴 때 table 전체를 aria-live로 두면 좋은가요?", answer: "대개 과도한 반복 announcement가 됩니다. 짧은 status에 loading/result count/error만 알리고 table은 semantic structure와 focus를 유지합니다." },
);
expertSession.completionChecklist.push(
  "HTTP status·media type·decode·parse·namespace/schema/domain 단계를 독립 오류 code로 분리했다.",
  "Response body single-use·stream lock·TextDecoder flush·bodyUsed·cancel을 검증했다.",
  "실제 byte/char/node limits와 large XML memory/parse-time budget을 적용했다.",
  "AbortSignal을 underlying fetch/reader/custom loader에 전달하고 generation으로 stale render/finally를 막았다.",
  "external XML values를 semantic DOM/textContent와 URL/style/class allowlist로 렌더링했다.",
  "caption·th scope·units·missing label·status·focus를 keyboard와 Accessibility tree에서 검증했다.",
  "browser와 server parser의 DTD/entity/XXE configuration 경계를 분리하고 privacy-safe telemetry를 적용했다.",
);
expertSession.sources.push({ id: "dom-abort", repository: "WHATWG DOM Standard", path: "#aborting-ongoing-activities", publicUrl: "https://dom.spec.whatwg.org/#aborting-ongoing-activities", usedFor: ["AbortController", "AbortSignal", "abort reason", "already-aborted operation", "resource cancellation"], evidence: "rapid XML requests와 component disposal에서 underlying fetch/reader/timer를 중단하고 stale generation을 차단하는 lifecycle의 공식 기준으로 사용했습니다." });
