import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["xml-01-wellformed-tree-encoding"],
  slug: "xml-01-wellformed-tree-encoding",
  courseId: "web",
  moduleId: "03-xml-data-formats",
  order: 1,
  title: "XML 선언, 단일 루트와 well-formed 트리",
  subtitle: "바이트가 Unicode 문자와 markup token을 거쳐 엄격한 하나의 document tree가 되는 과정을 추적하고, 정상 문서와 fatal error를 실제 parser로 검증합니다.",
  level: "기초",
  estimatedMinutes: 230,
  coreQuestion: "XML parser는 어떤 바이트를 어떤 문자로 읽어 하나의 tree를 만들며, 어느 문법 위반에서 정상 처리를 중단해야 할까요?",
  summary: "실제 두 학습 원본의 XML declaration, BOM 없는 UTF-8 바이트, CRLF, 단일 products document element, 요소 중심 상품과 속성 중심 empty element 표현을 전부 감사합니다. version·encoding·standalone의 정확한 의미, byte decoding과 이미 Unicode인 string parsing의 차이, case-sensitive name과 올바른 nesting, empty-element tag, attribute quoting·중복·escaping, comment·CDATA·processing instruction, indentation whitespace와 DOM text node를 단계별로 설명합니다. well-formed와 schema-valid를 분리하고 Python ElementTree와 browser DOMParser의 서로 다른 오류 API를 실제 실행합니다. 마지막에는 외부 entity·entity expansion·깊이·크기 공격 payload를 만들지 않고도 DTD/entity/network 비활성화, parser patch, 입력 제한과 격리라는 안전한 방어 경계를 설계합니다.",
  objectives: [
    "XML 입력의 raw bytes가 encoding 결정과 Unicode decoding을 거쳐 markup·character data로 token화되는 순서를 설명할 수 있다.",
    "XML declaration의 version·encoding·standalone을 정확한 순서와 의미로 작성하고 실제 byte encoding과 일치시킬 수 있다.",
    "단 하나의 document element, case-sensitive matching, proper nesting과 empty-element 규칙을 적용해 well-formed document를 만들 수 있다.",
    "attribute를 quote하고 text/attribute context에 맞춰 ampersand·angle bracket·quote를 reference로 안전하게 표현할 수 있다.",
    "comment·CDATA section·processing instruction과 XML declaration을 구분하고 각 금지 문자열과 DOM node 결과를 예측할 수 있다.",
    "들여쓰기 whitespace도 text data가 될 수 있음을 DOM/ElementTree에서 확인하고 element-only 가정으로 textContent를 잘못 읽지 않을 수 있다.",
    "well-formedness와 DTD/XSD 등 schema validity를 분리하고 parser별 fatal error 전달 방식을 안전하게 처리할 수 있다.",
    "신뢰할 수 없는 XML에 DTD·외부 entity·resource exhaustion 방어, 크기·깊이·시간 제한과 parser update를 적용할 수 있다.",
  ],
  prerequisites: [
    { title: "HTML 문서 구조와 DOM tree", reason: "문서·element·text·comment node와 parent/child 관계를 이미 본 상태에서, HTML의 오류 복구와 달리 XML이 엄격한 tree를 요구하는 차이를 비교합니다.", sessionSlug: "html-01-document-anatomy-dom-tree" },
    { title: "byte와 Unicode의 기초", reason: "파일은 byte sequence이고 parser가 다루는 text는 Unicode character sequence라는 구분만 알면 됩니다. code point와 UTF-8 가변 길이 encoding은 이 세션에서 다시 설명합니다." },
  ],
  keywords: ["XML 1.0", "XML declaration", "UTF-8", "Unicode", "well-formed", "document element", "case sensitivity", "empty-element tag", "attribute quoting", "entity reference", "CDATA", "processing instruction", "text node", "DOMParser", "ParseError", "schema validity", "XXE defense"],
  chapters: [
    {
      id: "bytes-characters-tokens-tree",
      title: "XML은 꺾쇠 문자열이 아니라 bytes→characters→tokens→tree 처리 계약입니다",
      lead: "화면에 한글이 보인다는 결과만 확인하지 말고 parser가 어느 단계에서 어떤 정보를 확정하는지 나누면 encoding 오류와 문법 오류를 혼동하지 않습니다.",
      explanations: [
        "파일·HTTP response body·message queue payload는 먼저 byte sequence입니다. XML processor는 BOM, 전송 계층의 charset 정보와 XML encoding declaration을 바탕으로 bytes를 Unicode character sequence로 decode합니다. 그 다음 `<`, `>`, `&`, quote 같은 character를 markup delimiter와 reference로 해석하고 element·attribute·text·comment 등의 논리 구조를 application에 제공합니다.",
        "실제 data01.xml과 data02.xml은 첫 byte부터 `<?xml` ASCII pattern이 시작하며 UTF-8 BOM EF BB BF가 없습니다. declaration은 version 1.0과 UTF-8을 적고, 한글은 실제 UTF-8 multi-byte sequence로 저장되어 있습니다. 줄 끝은 CRLF byte pair지만 XML processor는 parsing 전에 literal CRLF/CR을 LF로 정규화하므로 DOM text에서 platform 원본 line ending과 동일하다고 가정하지 않습니다.",
        "Unicode character와 UTF-8 byte를 구분합니다. 예를 들어 한글 한 글자는 하나의 Unicode code point일 수 있지만 UTF-8에서는 여러 byte로 encode됩니다. encoding이 맞으면 parser는 동일한 character를 얻고, 맞지 않으면 decoding 단계에서 오류가 나거나 잘못된 문자로 바뀌어 이후 name/text 비교도 틀어집니다.",
        "XML document의 logical structure는 declaration text 자체를 그대로 저장한 문자열 목록이 아닙니다. parser API마다 보존하는 node가 다릅니다. browser XML DOM은 element·text·CDATA·comment·PI node를 표현할 수 있지만 Python ElementTree의 기본 parser는 comment와 PI를 tree에 넣지 않습니다. 동일하게 well-formed인 입력도 선택한 data model에서 보이는 정보가 달라집니다.",
        "파싱 성공은 업무 데이터가 맞다는 뜻이 아닙니다. `<price>무료</price>`도 XML syntax로는 well-formed일 수 있습니다. bytes decoding, well-formed parse, namespace resolution, schema validation, application validation을 독립된 gate로 두고 어느 gate가 실패했는지 기록합니다.",
      ],
      concepts: [
        { term: "XML processor", definition: "XML document를 읽어 content와 logical structure를 application에 제공하는 software module입니다.", detail: ["encoding과 well-formedness 규칙을 적용합니다.", "DOM tree, event stream, application-specific tree 등 API model은 구현마다 다를 수 있습니다."] },
        { term: "character encoding", definition: "Unicode character를 byte pattern으로 나타내고 다시 복원하는 규칙입니다.", detail: ["UTF-8과 UTF-16은 모든 XML processor가 받아들여야 하는 encoding입니다.", "declaration label과 실제 bytes가 일치해야 합니다."] },
        { term: "logical tree", definition: "하나의 document element 아래 element·text 등 node가 parent/child로 올바르게 중첩된 구조입니다.", detail: ["source indentation과 tree depth는 별개입니다.", "parser data model에 따라 comment·PI 보존 방식이 다릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "editor에서는 한글이 보이지만 서버 parser에서 깨지거나 encoding error가 난다.", likelyCause: "editor가 추측한 encoding, XML declaration, HTTP Content-Type charset 또는 실제 bytes가 서로 다릅니다.", checks: ["파일 첫 bytes와 BOM을 hex로 확인합니다.", "declaration의 encoding label을 확인합니다.", "전송 response의 Content-Type과 charset을 기록합니다.", "text mode로 먼저 decode하지 말고 원본 bytes를 parser에 주는 비교를 합니다."], fix: "생성기·파일 저장·HTTP header·XML declaration을 UTF-8 한 규칙으로 맞추고, byte boundary에서 한 번만 decode합니다.", prevention: "한글·emoji fixture를 byte-level integration test에 포함하고 생성 직후 다시 parser로 round-trip합니다." },
      ],
    },
    {
      id: "xml-declaration-version-encoding-standalone",
      title: "XML declaration은 version→encoding→standalone 순서의 decoding·외부 선언 계약입니다",
      lead: "첫 줄을 관습적으로 복사하지 않고 각 pseudo-attribute가 무엇을 보장하며 무엇을 보장하지 않는지 구분합니다.",
      explanations: [
        "document에 XML declaration을 쓴다면 document entity의 맨 앞에 와야 하며 일반 whitespace나 comment를 앞에 두지 않습니다. BOM은 encoding signature라 별도 취급됩니다. declaration 문법은 `<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>`처럼 version이 필수이고 encoding과 standalone이 선택이며 순서도 정해져 있습니다.",
        "version=1.0은 이 document가 XML 1.0 문법을 따른다는 선언입니다. `1.0`을 application 데이터 version과 혼동하지 않습니다. 상품 schema version은 root attribute나 namespace/schema contract 등 별도 application metadata로 설계합니다.",
        "encoding은 document entity의 bytes를 문자로 해석하는 encoding 이름입니다. 원본 두 파일은 `encoding=\"UTF-8\"`과 실제 bytes가 일치합니다. declaration이 없고 외부 encoding 정보도 없을 때 XML의 기본은 UTF-8이지만, 명시한다면 거짓 label을 쓰는 것보다 실제 생성 byte와 항상 동기화해야 합니다. XML processor는 UTF-8과 UTF-16을 지원해야 하며 다른 encoding 지원은 구현을 확인합니다.",
        "standalone은 파일이 하나라는 뜻, network를 쓰지 않는다는 뜻, security mode라는 뜻이 아닙니다. `yes`는 external markup declaration이 document information에 영향을 주지 않는다는 assertion이고 `no`는 외부 선언이 있을 수 있음을 나타냅니다. 실제 원본에는 standalone이 없으며 이는 standalone 값 no와 같은 문법적 default이지만, application의 외부 entity 허용 정책과 동일한 switch로 취급하지 않습니다.",
        "JavaScript DOMParser.parseFromString에 넘기는 값은 이미 JavaScript Unicode string입니다. 이때 string 안의 encoding declaration은 이미 끝난 byte decoding을 다시 수행하지 않습니다. 반대로 HTTP bytes나 file bytes를 parser에 직접 넘기면 declaration과 transport 정보가 중요합니다. test가 string API인지 byte API인지 명확히 기록합니다.",
        "XML declaration은 processing instruction과 비슷한 `<?...?>` 표면을 가졌지만 XML grammar에서 별도 markup이며 DOM Document의 PI node가 아닙니다. `xml`과 대소문자 조합으로 시작하는 name은 표준화를 위해 예약되므로 임의 PI target이나 element prefix로 사용하지 않습니다.",
      ],
      concepts: [
        { term: "XML declaration", definition: "document entity 앞에서 XML version과 선택적 encoding·standalone 정보를 제공하는 특별한 declaration입니다.", detail: ["version은 필수입니다.", "일반 processing instruction node가 아닙니다."] },
        { term: "standalone declaration", definition: "외부 markup declaration이 document 정보에 영향을 주는지에 관한 yes/no assertion입니다.", detail: ["single-file 배포나 network 차단을 보장하지 않습니다.", "DTD/entity 보안 정책을 대신하지 않습니다."] },
        { term: "byte API vs string API", definition: "parser가 encoded bytes를 받아 직접 decode하는지, 이미 decode된 Unicode string을 받는지의 입력 경계 차이입니다.", detail: ["byte API에서는 encoding detection이 실제 처리 단계입니다.", "string API의 declaration은 이미 수행된 decoding을 되돌리지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XML declaration을 추가했는데 browser JavaScript string의 깨진 글자가 복구되지 않는다.", likelyCause: "깨짐은 DOMParser 전에 잘못된 방식으로 bytes를 string으로 decode할 때 이미 발생했으며 declaration은 Unicode string을 재decode하지 않습니다.", checks: ["fetch에서 arrayBuffer와 text 중 무엇을 사용했는지 봅니다.", "response header charset과 raw bytes를 확인합니다.", "replacement character U+FFFD가 string에 이미 있는지 검사합니다."], fix: "raw bytes를 올바른 charset으로 한 번 decode하거나 XML-aware byte parser에 직접 넘깁니다. 깨진 string의 declaration만 바꾸지 않습니다.", prevention: "byte fixture와 string fixture를 분리하고 boundary별 encoding owner를 문서화합니다." },
        { symptom: "declaration 앞에 빈 줄 하나를 넣자 parser가 declaration 관련 fatal error를 낸다.", likelyCause: "XML declaration은 존재한다면 document entity의 시작에 있어야 하며 앞선 whitespace 때문에 일반 PI처럼 해석될 수 없습니다.", checks: ["BOM을 제외한 첫 bytes를 확인합니다.", "template가 leading newline을 삽입했는지 봅니다.", "concatenation 과정에서 log/header가 앞에 붙지 않았는지 확인합니다."], fix: "serializer가 declaration을 첫 위치에 쓰게 하고 앞선 whitespace·debug text를 제거합니다.", prevention: "생성된 bytes가 `<?xml` 또는 허용된 BOM으로 시작하는지 test합니다." },
      ],
    },
    {
      id: "one-document-element-and-proper-nesting",
      title: "well-formed document에는 정확히 하나의 document element가 있고 모든 element가 제대로 중첩됩니다",
      lead: "‘루트 하나’는 첫 element 이름이 root라는 뜻이 아니라 모든 content element를 포함하는 유일한 최상위 element가 있다는 문서 문법입니다.",
      explanations: [
        "XML 1.0 document production은 prolog, 정확히 하나의 element, 뒤따르는 zero or more Misc로 구성됩니다. 원본의 `<products>`가 document element이며 그 안의 네 `<product>`가 child입니다. `<products>...</products><summary/>`처럼 두 번째 top-level element를 붙이면 well-formed document가 아닙니다.",
        "document element 앞뒤에 comment와 processing instruction, 허용된 whitespace가 올 수 있습니다. 그래서 ‘파일 안 tag가 오직 하나’라는 뜻은 아닙니다. 다만 character data를 root 밖에 자유롭게 둘 수 없고, application data는 document element tree 안에 있어야 합니다.",
        "proper nesting은 start-tag가 다른 element content에서 시작되었다면 그 end-tag도 같은 element content 안에서 끝나야 한다는 뜻입니다. `<a><b></a></b>`는 HTML parser가 복구할 법한 입력이어도 XML에서는 crossing structure라 fatal error입니다. stack으로 생각하면 start-tag에서 push하고 같은 name end-tag에서 top을 pop해야 합니다.",
        "name matching은 Unicode code point representation까지 정확히 같아야 하고 case folding이 없습니다. `<Product></product>`는 mismatch입니다. visually 같은 글자라도 Unicode normalization form이 다르면 XML name match가 자동 정규화되지 않을 수 있으므로 생성기에서 naming convention과 normalization을 일관되게 유지합니다.",
        "HTML과 XML은 꺾쇠 문법을 공유하지만 parsing contract가 다릅니다. HTML은 정해진 오류 복구·implied element 규칙으로 DOM을 만들 수 있지만 XML well-formedness constraint 위반은 fatal error이고 processor는 정상 document structure를 계속 전달하면 안 됩니다. ‘browser에서 뭔가 보였다’로 XML 정확성을 판단하지 않습니다.",
      ],
      concepts: [
        { term: "document element", definition: "다른 어떤 element content에도 속하지 않으며 document의 나머지 모든 element를 포함하는 유일한 최상위 element입니다.", detail: ["흔히 root element라고 부릅니다.", "comment와 PI는 document element 밖에도 올 수 있습니다."] },
        { term: "proper nesting", definition: "element start/end boundary가 교차하지 않고 완전히 포함 관계를 이루는 규칙입니다.", detail: ["stack top과 end-tag name이 같아야 합니다.", "crossing tag는 fatal error입니다."] },
        { term: "case-sensitive match", definition: "XML name 비교에서 대소문자 변환 없이 동일한 문자 sequence여야 하는 규칙입니다.", detail: ["Product와 product는 다른 name입니다.", "Unicode normalization도 자동 name folding으로 가정하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "두 개의 독립 목록을 나란히 썼더니 ‘junk after document element’ 또는 multiple roots 오류가 난다.", likelyCause: "두 element를 감싸는 하나의 document element가 없습니다.", checks: ["첫 top-level element의 end-tag 뒤에 다른 element가 있는지 봅니다.", "comment/PI와 실제 element를 구분합니다.", "fragment를 document parser에 넘긴 것인지 확인합니다."], fix: "두 목록의 공통 의미를 가진 하나의 document element로 감싸거나, fragment API가 필요한 문제라면 XML document와 별도 contract로 다룹니다.", prevention: "serializer는 언제나 하나의 root object에서 시작하고 parse round-trip을 CI에서 실행합니다." },
        { symptom: "화면상 tag spelling이 같아 보이는데 mismatched tag fatal error가 난다.", likelyCause: "대소문자·보이지 않는 Unicode 차이·실제 nesting 순서가 다릅니다.", checks: ["start/end name의 code point와 case를 비교합니다.", "parser error position 앞의 open-element stack을 적습니다.", "editor의 normalization·confusable 문자 표시를 켭니다."], fix: "동일한 serializer/API로 start/end tag를 생성하고 hand-built concatenation을 제거합니다.", prevention: "name은 작은 허용 vocabulary와 naming convention으로 제한하고 syntax-aware formatter/validator를 사용합니다." },
      ],
    },
    {
      id: "elements-empty-elements-and-data-model",
      title: "start/end tag와 empty-element tag는 같은 빈 element를 표현합니다",
      lead: "원본 두 파일의 요소 중심·속성 중심 표현을 비교하되, 문법상 empty와 업무상 값 없음은 같지 않음을 분리합니다.",
      explanations: [
        "data01.xml의 product는 `<product><name>흰우유</name><price>950</price></product>`처럼 child element에 값을 담습니다. data02.xml은 `<product name=\"제너시트\" price=\"100\"/>`처럼 attribute만 가진 empty element입니다. 둘 다 하나의 product element이지만 application data model과 query 방식은 다릅니다.",
        "`<empty/>`는 empty-element tag이며 `<empty></empty>`와 well-formedness 관점에서 같은 빈 element를 표현합니다. slash 앞 whitespace는 허용되지만 serializer style을 일관되게 합니다. `<empty>`만 쓰고 end-tag를 생략하는 HTML식 관용은 XML에서 허용되지 않습니다.",
        "empty element는 child element가 없다는 뜻이지 attribute도 없거나 업무 값이 null이라는 뜻이 아닙니다. data02의 product는 name과 price attribute를 가졌습니다. `<value/>`, `<value></value>`, element 자체 부재, `xsi:nil` 같은 schema-aware null 표현은 application/schema semantics에서 별도로 결정해야 합니다.",
        "요소 중심 표현은 반복·중첩·mixed content·확장에 자연스럽고, attribute는 element의 식별자·mode·짧은 metadata에 편리합니다. 그러나 이 선택을 이번 세션의 syntax rule로 고정하지 않습니다. mixed content, namespace와 schema를 포함한 상세 선택은 다음 `xml-02-elements-attributes-namespace` 범위입니다.",
        "XML parser는 price를 숫자로 자동 변환하지 않습니다. data01의 text `950`과 data02의 attribute `100`은 기본적으로 character sequence입니다. integer range·통화 단위·필수 여부는 schema 또는 application validation에서 확인합니다.",
      ],
      concepts: [
        { term: "empty-element tag", definition: "`<name/>` 형태로 start와 end를 한 번에 표시하는 XML markup입니다.", detail: ["같은 name의 바로 이어진 start/end tag와 동일한 빈 element를 나타냅니다.", "HTML void element 규칙과 혼동하지 않습니다."] },
        { term: "element content", definition: "start-tag와 end-tag 사이에 있는 child markup과 character data입니다.", detail: ["element-only, text, mixed content 같은 schema model은 별도입니다.", "indentation whitespace도 character data가 될 수 있습니다."] },
        { term: "representation choice", definition: "업무 값을 child element, attribute 또는 text 중 어디에 둘지 정하는 data model 결정입니다.", detail: ["well-formedness만으로 좋은 model이 결정되지는 않습니다.", "query·확장·ordering·schema 요구를 함께 봅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "`<product ...>`를 self-closing하지 않고 end-tag도 생략했더니 뒤 product가 전부 child처럼 되거나 fatal error가 난다.", likelyCause: "XML에는 HTML식 optional end-tag가 없어 모든 non-empty start-tag가 정확히 닫혀야 합니다.", checks: ["각 start-tag에 matching end-tag 또는 `/>`가 있는지 확인합니다.", "formatter indentation이 예상 depth와 같은지 봅니다.", "parser error 이전 open-element stack을 확인합니다."], fix: "content가 없으면 `<product .../>`, content가 있으면 명시적인 `</product>`를 사용합니다.", prevention: "string concatenation 대신 XML serializer를 사용하고 생성 후 즉시 parse합니다." },
      ],
    },
    {
      id: "attributes-quoting-and-escaping",
      title: "attribute는 반드시 quote하고 context에 맞는 reference로 delimiter를 데이터와 분리합니다",
      lead: "XML escaping은 보기 좋은 치환이 아니라 parser가 markup 경계와 실제 문자 데이터를 혼동하지 않게 하는 문법입니다.",
      explanations: [
        "XML attribute value는 single quote 또는 double quote로 둘러싸야 합니다. HTML에서 일부 unquoted value가 허용되는 경험을 가져오면 안 됩니다. `<product price=100/>`는 fatal error이고 `<product price=\"100\"/>`가 well-formed입니다.",
        "같은 element의 start-tag 안에 동일한 attribute name을 두 번 쓸 수 없습니다. `<item id=\"a\" id=\"b\"/>`는 마지막 값 우선 같은 복구가 아니라 well-formedness 위반입니다. configuration merge를 markup 중복에 기대지 않습니다.",
        "character data에서 literal `&`와 `<`는 각각 `&amp;`, `&lt;` 또는 numeric character reference로 표현합니다. `>`는 보통 literal로 가능하지만 character data의 `]]>` sequence는 CDATA close delimiter와 충돌하므로 escape해야 합니다. parser가 reference를 해석한 뒤 application은 원래 `&`와 `<` character를 받습니다.",
        "attribute value에서도 literal `<`와 `&`는 금지됩니다. delimiter와 같은 quote를 값에 넣으려면 `&quot;` 또는 `&apos;`를 쓰거나 반대 quote delimiter를 선택합니다. serializer에 raw user string을 이어 붙이지 말고 API가 context-specific escaping을 수행하게 합니다.",
        "XML에는 amp·lt·gt·apos·quot 다섯 predefined general entity가 있습니다. HTML의 방대한 named character reference를 그대로 기대하지 않습니다. 선언되지 않은 `&nbsp;`는 DTD 없이 XML에서 fatal error가 될 수 있으므로 필요한 문자는 Unicode 자체나 numeric reference를 사용합니다.",
        "attribute order는 application data 의미로 사용하지 않습니다. source serializer가 order를 보존할 수 있어도 XML data model과 canonicalization·signing·diff에서는 별도 규칙이 필요합니다. 업무 priority는 명시적인 attribute 값이나 child element로 표현합니다.",
      ],
      concepts: [
        { term: "attribute value", definition: "start/empty-element tag 안에서 name과 equals 뒤 quote로 둘러싼 character data입니다.", detail: ["반드시 quote합니다.", "같은 element에서 attribute name은 중복될 수 없습니다."] },
        { term: "entity reference", definition: "ampersand로 시작하고 semicolon으로 끝나 parser가 replacement text로 바꾸는 reference입니다.", detail: ["amp·lt·gt·apos·quot가 predefined입니다.", "untrusted external/general entity 확장은 별도 보안 경계입니다."] },
        { term: "context-sensitive escaping", definition: "text, attribute, comment, CDATA 등 현재 XML grammar 위치에 맞는 delimiter 규칙을 적용하는 것입니다.", detail: ["한 번의 replace로 모든 context를 안전하게 처리할 수 없습니다.", "serializer/API에 맡기는 것이 기본입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "상품명 ‘A & B’를 넣자 not well-formed 또는 undefined entity 오류가 난다.", likelyCause: "raw ampersand가 entity/reference 시작으로 해석되었거나 HTML entity를 XML에서 사용했습니다.", checks: ["오류 위치의 `&` 뒤 sequence를 확인합니다.", "text와 attribute 중 어느 context인지 구분합니다.", "DTD에 의존하는 custom entity가 있는지 봅니다."], fix: "text/attribute serializer를 사용해 ampersand를 `&amp;`로 encode하고 parser 결과가 `A & B`인지 확인합니다.", prevention: "ampersand·quotes·angle bracket·다국어를 포함한 round-trip property test를 둡니다." },
        { symptom: "attribute 하나가 두 번 들어갔는데 parser가 어느 값을 선택하지 않고 실패한다.", likelyCause: "XML well-formedness는 동일 start-tag에서 attribute name 중복을 금지합니다.", checks: ["template spread/merge가 같은 name을 두 번 출력하는지 봅니다.", "namespace-aware expanded name 중복 여부는 다음 namespace 단계에서 확인합니다.", "raw serialized start-tag를 log에서 확인합니다."], fix: "object/map 단계에서 duplicate 정책을 결정한 뒤 serializer에는 최종 attribute 한 개만 전달합니다.", prevention: "schema 이전에도 duplicate key를 차단하는 builder API와 parse test를 사용합니다." },
      ],
    },
    {
      id: "comments-cdata-processing-instructions-dom",
      title: "comment·CDATA·processing instruction은 서로 다른 markup이고 DOM에서 다른 node가 됩니다",
      lead: "모두 본문 element와 다른 표면 문법을 쓰지만 금지 delimiter, application 노출과 serialization 결과가 같지 않습니다.",
      explanations: [
        "원본 두 파일에는 ‘XML에서는 루트가 하나다’라는 comment가 document element 앞에 있고, root 안에도 data representation을 설명하는 comment가 있습니다. comment는 `<!--`와 `-->` 사이이며 내용에 `--`가 올 수 없습니다. comment 안 markup처럼 보이는 `<tag>`는 element가 아니지만 secret·개인정보를 숨기는 안전한 장소도 아닙니다.",
        "CDATA section은 `<![CDATA[`와 `]]>` 사이의 character data를 `<`와 `&` reference 없이 적게 합니다. parser 결과에서는 markup element가 아니라 text/CDATA node이며 `]]>`를 내용에 직접 포함하거나 CDATA를 중첩할 수 없습니다. 대량 raw text를 무조건 CDATA로 감싸는 대신 serializer와 data model을 우선합니다.",
        "processing instruction은 `<?target data?>` 형태로 application에 처리 힌트를 전달할 수 있습니다. target은 XML Name이고 어떤 대소문자 조합의 xml도 예약되어 있으며 data 안에는 `?>`가 올 수 없습니다. XML declaration은 표면이 비슷하지만 별도 문법입니다.",
        "browser DOMParser로 `application/xml`을 parse하면 PI nodeType 7, comment nodeType 8, element nodeType 1을 Document child로 관찰할 수 있습니다. CDATA는 CDATASection node일 수 있지만 textContent에서는 일반 text와 함께 합쳐진 character data로 읽힙니다. API가 node type을 보존하는지 확인합니다.",
        "Python ElementTree 기본 parser는 source의 comment·PI·DOCTYPE를 tree에서 건너뜁니다. browser DOM 결과와 tree dump가 다른 것은 입력이 달라서가 아니라 target tree builder 정책일 수 있습니다. comment/PI가 업무상 필수라면 parser option과 round-trip preservation을 명시적으로 시험합니다.",
      ],
      concepts: [
        { term: "comment", definition: "application character data가 아닌 설명용 XML markup입니다.", detail: ["내용에 double hyphen을 넣을 수 없습니다.", "parser API가 comment를 application에 노출할지는 data model에 따라 다릅니다."] },
        { term: "CDATA section", definition: "대부분의 markup delimiter를 character data로 취급하게 하는 section입니다.", detail: ["close sequence `]]>`는 내용에 올 수 없습니다.", "element markup이나 automatic escaping 대체물이 아닙니다."] },
        { term: "processing instruction", definition: "target과 data를 가진 application-directed instruction markup입니다.", detail: ["DOM에서는 nodeType 7입니다.", "XML declaration과 동일한 node가 아닙니다."] },
      ],
      codeExamples: [
        {
          id: "browser-xml-node-types",
          title: "DOMParser에서 PI·comment·element·CDATA·attribute decoding 확인",
          language: "html",
          filename: "xml-dom-nodes.html",
          purpose: "XML 1.0의 서로 다른 markup이 browser XML DOM에서 어떤 node/value로 관찰되는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>XML DOM</title></head>\n<body>\n<pre id=\"result\"></pre>\n<script>\n  const xml = `<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<?course mode=\"practice\"?>\n<!-- 학습 카탈로그 -->\n<catalog note=\"A &amp; B\">\n  <item id=\"x1\"><![CDATA[1 < 2 & 그대로]]></item>\n  <empty/>\n</catalog>`;\n  const doc = new DOMParser().parseFromString(xml, 'application/xml');\n  const root = doc.documentElement;\n  const children = [...doc.childNodes]\n    .map((node) => `${node.nodeType}:${node.nodeName}`).join(',');\n  document.querySelector('#result').textContent = [\n    `document-children=${children}`,\n    `root=${root.nodeName}`,\n    `note=${root.getAttribute('note')}`,\n    `item-text=${root.querySelector('item').textContent}`,\n    `empty-child-count=${root.querySelector('empty').childNodes.length}`,\n    `parsererror=${doc.getElementsByTagName('parsererror').length}`\n  ].join('\\n');\n</script>\n</body>\n</html>",
          walkthrough: [
            { lines: "7-13", explanation: "XML declaration 뒤에 PI, comment, 하나의 catalog document element를 두고 attribute reference, CDATA와 empty element를 한 fixture에 모읍니다." },
            { lines: "14-17", explanation: "DOMParser의 XML MIME type을 사용합니다. HTML parsing과 다른 strict XML parser 결과이며 Document child node type/name을 순서대로 serialize합니다." },
            { lines: "18-25", explanation: "attribute entity와 CDATA가 application character로 decode된 값, empty element child count와 browser-specific parsererror element 존재 여부를 출력합니다." },
          ],
          run: { environment: ["현대 Chromium 계열 browser", "JavaScript와 DOMParser 활성화"], command: "xml-dom-nodes.html을 저장해 browser에서 열고 result 확인" },
          output: { value: "document-children=7:course,8:#comment,1:catalog\nroot=catalog\nnote=A & B\nitem-text=1 < 2 & 그대로\nempty-child-count=0\nparsererror=0", explanation: ["XML declaration은 Document child node 목록에 PI로 들어오지 않고 course PI·comment·catalog element만 보입니다.", "`&amp;`는 attribute 값에서 실제 ampersand로, CDATA content는 literal angle bracket과 ampersand text로 읽힙니다.", "empty element는 child node가 없고 parsererror가 없어 정상 XML DOM입니다."] },
          experiments: [
            { change: "comment 내용을 `검사--실패`로 바꿉니다.", prediction: "double hyphen 금지로 parsererror가 생기고 정상 catalog tree로 사용하면 안 됩니다.", result: "comment도 자유 문자열 저장소가 아니라 XML grammar를 따릅니다." },
            { change: "CDATA 안에 close delimiter를 하나 더 넣습니다.", prediction: "CDATA가 일찍 닫혀 뒤 문자가 markup grammar를 깨면 fatal parse result가 됩니다.", result: "CDATA는 arbitrary data를 무제한 안전하게 감싸는 container가 아닙니다." },
            { change: "XML string의 encoding을 EUC-KR로 적습니다.", prediction: "JavaScript string은 이미 Unicode여서 이 예제의 한글 text가 다시 decode되지는 않습니다.", result: "string parser와 byte parser의 encoding boundary를 구분합니다." },
          ],
          sourceRefs: ["w3c-xml-10", "whatwg-dom", "whatwg-domparser"],
        },
      ],
      diagnostics: [
        { symptom: "browser DOM에는 comment가 있는데 ElementTree로 다시 저장하니 사라진다.", likelyCause: "ElementTree 기본 XMLParser가 input comment와 PI를 기본 tree에 삽입하지 않는 builder 정책을 사용합니다.", checks: ["사용한 parser·TreeBuilder option을 기록합니다.", "원본과 serialization의 node type diff를 비교합니다.", "comment/PI가 업무 contract인지 단순 설명인지 결정합니다."], fix: "보존이 필요하면 해당 node를 지원하는 parser/TreeBuilder를 명시적으로 선택하고 round-trip test를 둡니다.", prevention: "XML library를 바꿀 때 element 값뿐 아니라 comment·PI·CDATA·attribute order 요구를 compatibility matrix로 검증합니다." },
      ],
    },
    {
      id: "whitespace-text-nodes-and-product-tree",
      title: "보기 좋은 들여쓰기 whitespace도 element content의 text가 될 수 있습니다",
      lead: "pretty-printed XML을 tree로 읽으면 element 사이 줄바꿈과 공백이 어디에 저장되는지 알아야 text 추출·서명·diff 오류를 피할 수 있습니다.",
      explanations: [
        "data01.xml의 `<products>` 바로 뒤에는 CRLF와 네 space가 있고, 각 product 뒤에도 indentation이 있습니다. XML line-end normalization 뒤 이 character들은 whitespace text data로 parser에 전달됩니다. ElementTree에서는 root.text와 child.tail에, DOM에서는 element 사이 Text node에 나타날 수 있습니다.",
        "`element.textContent.trim()`으로 화면용 값을 얻는 것과 원본 XML data model에서 whitespace를 삭제하는 것은 다릅니다. mixed content에서는 space 하나가 단어 경계를 만들 수 있습니다. schema/DTD가 element-only content라고 알려 주지 않는 한 parser가 indentation을 ‘무의미’하다고 임의 판단할 수 없습니다.",
        "DOM Node.normalize()는 adjacent Text node를 합치고 empty Text node를 제거하지만 모든 whitespace를 trim하는 API가 아닙니다. CSS selector나 children은 element만 볼 수 있는 반면 childNodes는 text/comment/CDATA까지 보므로 count 목적을 분명히 합니다.",
        "data01의 product 하나는 name·price child element를 가집니다. `.findall('product')`는 direct child product 네 개를 얻고 `.findtext('name')`은 name text를 읽습니다. 숫자 변환은 application이 명시적으로 수행하며 실패·범위 정책을 별도로 둡니다.",
        "data02의 product는 empty element와 attributes라 DOM `children.length`는 0이고 name/price는 getAttribute나 Element.attrib에서 읽습니다. 두 원본을 같은 product object로 변환하려면 syntax가 아니라 mapping layer를 설계해야 합니다. 그 설계와 namespace-aware query는 다음 세션에서 확장합니다.",
      ],
      concepts: [
        { term: "Text node", definition: "element content의 character data를 나타내는 DOM node입니다.", detail: ["들여쓰기 줄바꿈과 space도 포함할 수 있습니다.", "Element.children에는 빠지고 childNodes에는 포함됩니다."] },
        { term: "tail text", definition: "ElementTree에서 한 child end-tag 뒤 다음 markup 전까지의 character data를 저장하는 위치입니다.", detail: ["pretty-print indentation이 흔히 tail에 들어갑니다.", "DOM의 sibling Text node와 mapping 방식이 다릅니다."] },
        { term: "line-end normalization", definition: "XML processor가 parsing 전 literal CRLF와 CR을 LF로 정규화하는 규칙입니다.", detail: ["source byte line ending과 application text line ending을 동일시하지 않습니다.", "byte-exact 서명은 canonicalization 등 별도 절차가 필요합니다."] },
      ],
      codeExamples: [
        {
          id: "parse-element-centered-products",
          title: "ElementTree로 원본 요소 중심 상품과 indentation whitespace 추적",
          language: "python",
          filename: "parse_products.py",
          purpose: "data01.xml의 실제 네 상품 구조를 최소 재현해 root, child count, text, 숫자 변환과 whitespace 위치를 exact output으로 확인합니다.",
          code: "from xml.etree import ElementTree as ET\n\nsource = '''<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<products>\n    <product><name>흰우유</name><price>950</price></product>\n    <product><name>사이다</name><price>1450</price></product>\n    <product><name>물</name><price>900</price></product>\n    <product><name>쥬스</name><price>2000</price></product>\n</products>'''\n\nroot = ET.fromstring(source)\nproducts = root.findall(\"product\")\nprint(f\"root={root.tag}\")\nprint(f\"product-count={len(products)}\")\nprint(\"names=\" + \",\".join(\n    item.findtext(\"name\", default=\"\") for item in products\n))\nprint(\"price-total=\" + str(sum(\n    int(item.findtext(\"price\", default=\"0\")) for item in products\n)))\nprint(f\"root-text-whitespace={root.text.isspace()}\")\nprint(f\"first-tail-whitespace={products[0].tail.isspace()}\")",
          walkthrough: [
            { lines: "1-9", explanation: "원본 data01의 document element와 상품 4개를 보존하고 product 사이 줄바꿈·space도 source에 남깁니다." },
            { lines: "11-13", explanation: "fromstring이 well-formed document를 parse해 document element를 반환하고 direct product child 네 개를 선택합니다." },
            { lines: "14-20", explanation: "name은 character data로 join하고 price text는 application이 int로 명시 변환한 뒤 합계 5300을 계산합니다. XML parser 자체의 numeric typing이 아닙니다." },
            { lines: "21-22", explanation: "root start-tag 다음 indentation은 root.text, 첫 product end-tag 다음 indentation은 product.tail에 whitespace string으로 남았음을 검증합니다." },
          ],
          run: { environment: ["Python 3.11 이상", "표준 library xml.etree.ElementTree"], command: "python parse_products.py" },
          output: { value: "root=products\nproduct-count=4\nnames=흰우유,사이다,물,쥬스\nprice-total=5300\nroot-text-whitespace=True\nfirst-tail-whitespace=True", explanation: ["document element name은 products이고 direct product child가 정확히 네 개입니다.", "name text 순서는 source document order를 따릅니다.", "price 합계는 XML typing이 아니라 Python int 변환 후 5300입니다.", "pretty-print whitespace가 root.text와 first product.tail에 실제 data로 존재합니다."] },
          experiments: [
            { change: "첫 price를 `무료`로 바꿉니다.", prediction: "XML parse는 성공하지만 int 변환에서 ValueError가 납니다.", result: "well-formedness와 application type validation은 다른 gate입니다." },
            { change: "product 사이 모든 줄바꿈과 space를 제거합니다.", prediction: "상품 count/name/total은 같지만 root.text 또는 tail이 None이 되어 isspace 호출 전 null 처리가 필요합니다.", result: "formatting whitespace를 업무 child와 같은 방식으로 가정하면 코드가 깨질 수 있습니다." },
            { change: "두 번째 `<name>`을 `<Name>`으로 바꿉니다.", prediction: "document는 여전히 well-formed지만 case-sensitive findtext('name') 결과는 빈 기본값이 됩니다.", result: "well-formed name matching과 application vocabulary validation은 별도입니다." },
          ],
          sourceRefs: ["web-xml-elements-source", "python-elementtree", "w3c-xml-10"],
        },
      ],
      diagnostics: [
        { symptom: "root.childNodes.length가 상품 수보다 훨씬 크다.", likelyCause: "DOM childNodes가 product element뿐 아니라 indentation Text node와 comment도 포함합니다.", checks: ["각 child의 nodeType/nodeName을 출력합니다.", "children과 childNodes 길이를 비교합니다.", "CDATA/comment 보존 여부를 parser별로 확인합니다."], fix: "element 수에는 children 또는 tag query를 사용하고, text-preserving 처리는 nodeType별로 분기합니다.", prevention: "pretty/minified XML 두 fixture로 parser logic을 동일하게 검증합니다." },
        { symptom: "trim을 전 tree에 적용했더니 문장 단어가 붙거나 서명/diff가 달라진다.", likelyCause: "mixed content의 의미 있는 whitespace와 formatting indentation을 구분하지 않고 모두 삭제했습니다.", checks: ["element가 element-only인지 mixed content인지 schema/contract를 확인합니다.", "text와 tail을 원본 순서로 출력합니다.", "canonicalization 요구가 있는지 봅니다."], fix: "application vocabulary가 허용한 위치에서만 whitespace normalization을 수행하고, byte/canonical equivalence 문제는 전용 canonicalization 절차로 처리합니다.", prevention: "space-sensitive mixed content와 pretty-print round-trip test를 둡니다." },
      ],
    },
    {
      id: "wellformed-valid-and-fatal-errors",
      title: "well-formed는 syntax gate이고 valid는 선언된 문서 규칙까지 만족한 상태입니다",
      lead: "parser가 tree를 만들었다는 사실과 상품 catalog가 업무 계약을 지켰다는 사실을 분리해야 오류 처리와 보안 경계가 명확해집니다.",
      explanations: [
        "well-formed document는 XML document grammar 전체와 모든 well-formedness constraint를 만족합니다. 단일 document element, matching tag, quoted attribute, proper entity/reference가 여기에 속합니다. 위반은 XML 1.0 용어로 fatal error이며 conforming processor가 감지·보고해야 합니다.",
        "valid XML은 well-formed에 더해 DTD 또는 다른 schema language가 선언한 content·attribute constraints를 만족한다는 뜻입니다. 원본 두 파일에는 DTD/XSD validation contract가 없으므로 product 개수, name 필수, price integer/범위 같은 업무 제약은 well-formedness가 보증하지 않습니다.",
        "XML 1.0 processor는 fatal error 뒤 추가 오류 탐색을 위해 data scanning을 계속할 수 있지만 정상 character data와 logical structure를 application에 계속 전달해서는 안 됩니다. partial tree를 성공 data처럼 저장하거나 후속 업무를 실행하지 않습니다.",
        "Python ElementTree는 parse 실패에서 ParseError를 raise하고 code와 line/column position을 제공합니다. browser DOMParser는 exception 대신 parsererror element를 포함한 error document를 반환하는 구현 패턴을 사용하므로 documentElement 존재만 검사하면 실패를 놓칠 수 있습니다. 실제 runtime의 documented error signal을 test합니다.",
        "raw parser message는 runtime·locale·underlying library version에 따라 달라질 수 있습니다. 테스트는 ‘fatal로 분류되고 업무 처리가 중단됨’을 안정적으로 assert하고, diagnostic log에는 안전하게 error code/position과 correlation ID를 남깁니다. 전체 untrusted payload를 log에 복사하지 않습니다.",
        "namespace는 XML Namespaces Recommendation이 element/attribute name을 URI 기반 expanded name으로 구분하는 추가 계층입니다. 원본은 colon과 xmlns를 사용하지 않습니다. 이번 세션에서는 colon을 임의 name 구분자로 쓰지 않고 `xml` prefix 예약을 지키는 경계까지만 다루며, prefix/default namespace·expanded name query는 다음 세션으로 넘깁니다.",
      ],
      concepts: [
        { term: "well-formed", definition: "XML grammar와 모든 well-formedness constraint를 만족해 document로 parse 가능한 상태입니다.", detail: ["위반은 fatal error입니다.", "업무 data type·필수 field를 보증하지 않습니다."] },
        { term: "valid", definition: "well-formed이면서 DTD/schema가 선언한 추가 validity constraint를 만족하는 상태입니다.", detail: ["schema와 validating processor가 필요합니다.", "XSD/DTD 자체 설계는 후속 심화 범위입니다."] },
        { term: "fatal error", definition: "processor가 반드시 감지·보고하고 이후 정상 document 정보를 application에 계속 전달할 수 없는 오류입니다.", detail: ["library는 exception 또는 error document 등 다른 API로 표현합니다.", "partial processing을 success로 취급하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "fatal-error-matrix",
          title: "다섯 입력을 ElementTree로 parse해 정상과 fatal을 분리",
          language: "python",
          filename: "xml_fatal_matrix.py",
          purpose: "matching/case/nesting, 단일 root, quote와 ampersand 위반이 복구 DOM이 아니라 parse failure가 됨을 안정적인 exact output으로 확인합니다.",
          code: "from xml.etree import ElementTree as ET\n\ncases = {\n    \"valid\": \"<root><empty/></root>\",\n    \"mismatched\": \"<root><item></root>\",\n    \"two-roots\": \"<one/><two/>\",\n    \"unquoted-attribute\": \"<root id=x/>\",\n    \"raw-ampersand\": \"<root>A & B</root>\",\n}\n\nfor name, source in cases.items():\n    try:\n        root = ET.fromstring(source)\n    except ET.ParseError:\n        print(f\"{name}=fatal\")\n    else:\n        print(f\"{name}=ok:{root.tag}\")",
          walkthrough: [
            { lines: "3-9", explanation: "정상 empty element 한 건과 mismatched end-tag, 두 document element, unquoted attribute, raw ampersand 네 well-formedness 위반을 서로 독립된 최소 입력으로 만듭니다." },
            { lines: "11-14", explanation: "각 source를 새 parse call로 격리해 하나의 fatal error가 다음 case 상태를 오염시키지 않게 합니다." },
            { lines: "15-17", explanation: "ParseError의 runtime별 message를 snapshot하지 않고 fatal category만 출력하며, 성공 때만 root tag를 application result로 사용합니다." },
          ],
          run: { environment: ["Python 3.11 이상", "표준 library xml.etree.ElementTree"], command: "python xml_fatal_matrix.py" },
          output: { value: "valid=ok:root\nmismatched=fatal\ntwo-roots=fatal\nunquoted-attribute=fatal\nraw-ampersand=fatal", explanation: ["matching end-tag와 empty child를 가진 첫 input만 root tree를 반환합니다.", "나머지 네 input은 서로 다른 well-formedness constraint를 위반해 application data로 진행하지 않습니다.", "오류 문구 대신 stable classification을 출력해 runtime 차이에 덜 취약합니다."] },
          experiments: [
            { change: "mismatched input을 `<root><item/></root>`로 고칩니다.", prediction: "empty item이 정확히 닫혀 ok:root가 됩니다.", result: "HTML식 end-tag 생략이 아니라 XML empty-element syntax로 수정합니다." },
            { change: "two-roots를 `<document><one/><two/></document>`로 감쌉니다.", prediction: "document element가 하나가 되어 ok:document가 됩니다.", result: "top-level element 둘을 공통 root 아래 child로 이동했습니다." },
            { change: "raw ampersand를 `&amp;`로 바꿉니다.", prediction: "parse가 성공하고 root.text는 실제 `A & B`가 됩니다.", result: "reference는 delimiter를 피하는 source syntax이고 application character는 ampersand입니다." },
          ],
          sourceRefs: ["w3c-xml-10", "python-elementtree"],
        },
      ],
      diagnostics: [
        { symptom: "DOMParser가 exception을 던지지 않아 malformed XML을 성공으로 처리했다.", likelyCause: "browser DOMParser의 XML parse failure가 throw 대신 parsererror를 포함한 Document로 표현되는 runtime contract를 검사하지 않았습니다.", checks: ["documentElement localName/namespace와 parsererror element를 확인합니다.", "known-invalid fixture로 실제 browser behavior를 고정합니다.", "성공 path가 expected root expanded name을 요구하는지 봅니다."], fix: "parse wrapper가 runtime-specific error document를 탐지해 Result/exception으로 표준화하고 expected root를 확인한 뒤에만 업무 code로 전달합니다.", prevention: "valid·mismatched·two-root·bad-entity fixture를 parser adapter contract test에 둡니다." },
        { symptom: "XML parser는 성공했는데 price가 음수거나 name이 비어 있다.", likelyCause: "well-formedness를 schema/application validity로 오해했습니다.", checks: ["어떤 DTD/XSD/schema가 실제로 적용되었는지 확인합니다.", "required/type/range/business uniqueness validation 단계가 있는지 봅니다.", "schema version과 namespace 계약을 확인합니다."], fix: "parse 결과에 별도 schema 또는 application validation을 실행하고 field-level 오류로 분류합니다.", prevention: "decode→parse→schema→business gate를 pipeline과 metric에서 분리합니다." },
      ],
    },
    {
      id: "secure-parser-boundary-and-operations",
      title: "well-formed XML도 신뢰할 수 없는 입력이면 resource·entity·network 경계가 필요합니다",
      lead: "XXE나 entity expansion payload를 실행해 보지 않고도 공격 표면을 이해하고 parser configuration·limits·isolation을 검증할 수 있습니다.",
      explanations: [
        "well-formedness는 안전성 인증이 아닙니다. XML은 DTD와 entity를 통해 외부 resource를 참조할 수 있고, parser/library 설정에 따라 local file 또는 network 접근이 발생할 수 있습니다. 또한 nested/repeated entity expansion, 매우 깊은 tree, 거대한 text·attribute·token은 CPU와 memory를 과도하게 사용할 수 있습니다.",
        "학습 환경에서는 XXE나 Billion Laughs payload를 만들거나 실행하지 않습니다. 방어는 malicious sample 성공 여부가 아니라 parser feature matrix로 검증합니다. untrusted input path에서 DTD와 external general/parameter entity resolution, network access, XInclude를 명시적으로 비활성화하고 default가 안전하다는 추측만 남기지 않습니다.",
        "Python 공식 문서는 built-in XML parser가 Expat에 의존하며 runtime이 사용 중인 Expat version에 따라 entity expansion·large token 등 resource vulnerability 영향이 달라질 수 있다고 경고합니다. library와 system parser를 patch하고 실제 `pyexpat.EXPAT_VERSION`을 inventory에 기록합니다. 버전 확인은 size/depth/time limit을 대신하지 않습니다.",
        "입력 body compressed/uncompressed byte size, 최대 element depth, attribute 수·길이, text 길이, parse time과 memory budget을 ingress에서 제한합니다. DOM은 전체 tree를 memory에 만들므로 큰 document는 streaming/pull parser를 검토하되 streaming parser도 entity·token limit과 timeout이 필요합니다.",
        "parser는 최소 권한 process/container에서 network와 민감 file 접근 없이 실행하고, fatal/security/resource limit 오류를 사용자 입력 오류와 내부 장애로 구분합니다. log에는 parser type/version, safe error code, position, size·duration과 correlation ID를 남기되 전체 XML·secret attribute·personal data를 기록하지 않습니다.",
        "browser/client parser를 security validation 경계로 믿지 않습니다. 공격자는 client를 우회해 server에 bytes를 직접 보낼 수 있으므로 server가 동일하거나 더 강한 parse·schema·business validation과 resource limits를 적용해야 합니다.",
      ],
      concepts: [
        { term: "XXE boundary", definition: "external entity가 local/network resource를 읽거나 요청하지 못하게 parser feature와 runtime 권한을 제한하는 경계입니다.", detail: ["DTD/external entity/network를 기본 거부합니다.", "parser별 option을 공식 문서와 integration test로 확인합니다."] },
        { term: "entity expansion DoS", definition: "entity replacement나 반복 구조가 CPU/memory를 비정상적으로 증폭시키는 resource exhaustion 위험입니다.", detail: ["공격 payload를 실습하지 않습니다.", "patched parser와 expansion/size/time/depth limit으로 방어합니다."] },
        { term: "parser adapter", definition: "library별 input·error·security option을 application의 일관된 Result contract로 감싸는 boundary입니다.", detail: ["fatal error document와 exception을 표준화합니다.", "feature configuration·version·metrics를 중앙 관리합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "작은 요청 body인데 XML parse 중 CPU·memory가 급증한다.", likelyCause: "entity expansion, pathological large token, deep nesting 또는 압축 해제 뒤 size 증가를 제한하지 않았을 수 있습니다.", checks: ["payload를 출력하지 말고 compressed/uncompressed size·depth·token metrics를 수집합니다.", "parser와 underlying library version을 확인합니다.", "DTD/entity/XInclude/network feature가 실제로 꺼졌는지 integration config를 봅니다.", "timeout과 memory limit 작동 여부를 확인합니다."], fix: "요청을 격리·중단하고 parser를 update하며 DTD/external entity를 비활성화하고 byte/depth/token/time/memory limit을 적용합니다.", prevention: "safe synthetic limit fixture로 차단 동작을 test하고 dependency/security advisory monitoring을 운영합니다." },
        { symptom: "parser가 외부 URL이나 local path에 접근한 흔적이 있다.", likelyCause: "외부 entity/DTD/XInclude resolution 또는 custom resolver가 network/file access를 허용했습니다.", checks: ["egress/file audit log와 resolver 호출을 확인합니다.", "DOCTYPE/XInclude 존재만 metadata로 탐지하되 payload 내용은 log하지 않습니다.", "parser option과 sandbox 권한을 확인합니다."], fix: "요청 처리를 차단하고 resolver를 deny-by-default로 바꾸며 parser process의 network와 file 권한을 제거합니다.", prevention: "untrusted XML path의 network-denied sandbox와 no-external-resource contract test를 유지합니다." },
      ],
      expertNotes: [
        "signature·canonicalization을 도입할 때 source bytes, parsed tree, namespace와 whitespace normalization 중 무엇에 서명하는지 전용 표준과 threat model로 정의합니다. 임의 pretty-print 뒤 hash 비교로 대체하지 않습니다.",
        "parser differential은 security issue가 될 수 있습니다. gateway와 backend가 서로 다른 parser/namespace/entity 설정을 쓰면 한쪽이 거부한 구조를 다른 쪽이 해석할 수 있으므로 동일 fixture와 policy로 contract test합니다.",
      ],
    },
  ],
  lab: {
    title: "상품 XML ingestion을 byte boundary부터 safe parser result까지 설계하기",
    scenario: "요소 중심·속성 중심 상품 XML을 모두 받을 수 있는 학습 importer가 필요합니다. 한글 encoding mismatch, multiple roots, raw ampersand, pretty-print whitespace, parser별 error API와 untrusted input resource 위험을 정보 손실 없이 구분해야 합니다.",
    setup: ["두 원본 XML을 read-only evidence로 준비하고 BOM·first bytes·line ending·declaration을 기록합니다.", "Python 3 표준 ElementTree와 Chromium DOMParser 실행 환경을 준비합니다.", "valid, mismatched tag, two roots, unquoted attribute, raw ampersand의 작은 비공격성 fixture만 사용합니다.", "decode·parse·shape mapping·business validation·security limit 결과를 따로 기록할 표를 만듭니다."],
    steps: [
      "두 원본의 byte length, BOM 유무, declared encoding과 실제 UTF-8 한글 bytes를 확인합니다.",
      "declaration version/encoding/standalone을 표로 분해하고 byte API와 string API에서 적용 시점을 표시합니다.",
      "각 document의 document element와 element/text/comment tree를 그려 단일 root와 proper nesting을 확인합니다.",
      "data01 요소 중심 상품과 data02 attribute/empty-element 상품을 syntax 손실 없이 각각 parse합니다.",
      "DOM childNodes와 children, ElementTree text/tail을 출력해 indentation whitespace와 comment 보존 차이를 기록합니다.",
      "다섯 error matrix를 실행하고 ElementTree exception과 browser parsererror를 하나의 실패 Result로 mapping합니다.",
      "well-formed 성공 뒤 expected root, product shape, required name, integer price와 range를 별도 gate로 검증합니다.",
      "parser feature matrix에서 DTD/external entity/network/XInclude를 deny하고 byte/depth/attribute/text/time/memory limit을 정합니다.",
      "log에는 safe code·position·size·duration·parser version만 남기고 원문 XML과 상품 개인/비밀 값은 배제합니다.",
      "minified/pretty, 한글/emoji, empty/non-empty, fatal input으로 adapter contract test를 자동화합니다.",
    ],
    expectedResult: ["두 원본이 UTF-8 bytes에서 같은 products root의 well-formed tree로 parse됩니다.", "요소 중심 4개와 attribute 중심 4개 상품을 구분해 읽고 price가 parser 단계에서는 text임을 설명합니다.", "indentation whitespace의 DOM Text/ElementTree text·tail 위치와 comment/PI 보존 차이를 재현합니다.", "네 malformed input은 어떤 partial tree도 업무 처리하지 않고 표준 failure Result가 됩니다.", "well-formed와 schema/business validity 결과가 별도 오류 code와 metric으로 남습니다.", "DTD·external resource가 기본 거부되고 크기·깊이·시간·memory budget을 넘는 입력이 안전하게 중단됩니다."],
    cleanup: ["진단용 raw payload 출력과 hex dump를 운영 log에서 제거합니다.", "실험용 malformed fixture는 test directory에만 두고 upload/input 경로에 남기지 않습니다.", "parser feature·network deny·limit 설정을 production configuration에서 다시 읽어 evidence로 보존합니다."],
    extensions: ["다음 세션에서 두 source representation을 namespace-aware canonical Product model로 mapping합니다.", "streaming pull parser로 10만 상품을 읽으며 DOM memory와 비교하되 동일 security limits를 유지합니다.", "schema validator를 추가해 well-formed 성공·schema 실패·business 실패를 세 단계로 관찰합니다.", "line ending과 pretty-print가 다른 문서의 canonicalization 필요성을 별도 signature lab에서 분석합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "요소 중심 상품 3개를 가진 UTF-8 XML을 작성하고 tree·whitespace를 parser로 확인하세요.", requirements: ["declaration을 document 첫 위치에 둡니다.", "하나의 products document element 아래 product/name/price를 proper nesting합니다.", "상품명에 ampersand가 있으면 올바르게 escape합니다.", "Python ElementTree로 root, product count, names와 root.text/tail whitespace를 출력합니다.", "pretty와 minified 결과를 비교합니다."], hints: ["source의 `&amp;`는 parse 후 실제 `&`가 됩니다.", "children count와 text/tail은 다른 정보를 셉니다."], expectedOutcome: "한글과 특수문자가 보존되고 단일 tree와 formatting whitespace 위치를 숫자·문자열로 설명할 수 있습니다.", solutionOutline: ["serializer 또는 정확한 quote/reference를 사용합니다.", "parse success 뒤에 업무 숫자 변환을 수행합니다.", "None과 whitespace-only text를 구분합니다."] },
    { difficulty: "응용", prompt: "여섯 가지 XML 문법 오류를 하나씩 격리해 fatal matrix와 수정 근거를 만드세요.", requirements: ["multiple roots, crossing tags, case mismatch, unquoted attribute, duplicate attribute, raw ampersand를 각각 독립 입력으로 만듭니다.", "공격성 DTD/entity payload는 만들지 않습니다.", "ElementTree ParseError와 browser parsererror를 모두 확인합니다.", "runtime message 전체가 아니라 category·position·업무 중단을 기록합니다.", "수정 후 expected root와 text를 다시 assert합니다."], hints: ["한 input에 오류를 여러 개 섞으면 첫 fatal 뒤 원인을 분리하기 어렵습니다.", "XML parser는 HTML처럼 정상 tree 복구를 보장하지 않습니다."], expectedOutcome: "각 well-formedness constraint와 최소 수정이 일대일로 연결되고 malformed data가 업무 layer로 전달되지 않습니다.", solutionOutline: ["start/end stack과 document element count부터 확인합니다.", "attribute quote/uniqueness와 reference를 검사합니다.", "parser adapter의 success/failure contract를 통일합니다."] },
    { difficulty: "설계", prompt: "외부 partner XML ingestion의 안전한 parser architecture와 운영 정책을 설계하세요.", requirements: ["transport bytes·charset·declaration 우선순위와 mismatch 정책을 정합니다.", "DOM/streaming parser 선택과 comment/PI/whitespace preservation 요구를 문서화합니다.", "well-formed·namespace·schema·business validation gate를 분리합니다.", "DTD/external entity/network/XInclude deny와 byte/depth/token/time/memory limit을 포함합니다.", "parser/Expat version inventory와 patch SLA를 둡니다.", "PII/secret 없는 error logging, metric, quarantine와 재처리 흐름을 설계합니다.", "parser differential contract test를 포함합니다."], hints: ["standalone=yes는 security control이 아닙니다.", "client-side parse 성공을 server trust 근거로 쓰지 않습니다."], expectedOutcome: "encoding·syntax·validity·security·resource 실패를 정보 손실 없이 분류하면서 공격 입력을 격리하는 production-ready ingestion boundary가 완성됩니다.", solutionOutline: ["bytes부터 application object까지 단계별 Result를 정의합니다.", "parser feature matrix와 resource budget을 configuration-as-code로 둡니다.", "safe fixture와 failure injection을 CI/관측에 연결합니다."] },
  ],
  reviewQuestions: [
    { question: "XML file을 parser가 tree로 만들기 전 가장 먼저 해결해야 하는 것은 무엇인가요?", answer: "byte sequence의 encoding을 결정해 Unicode character sequence로 올바르게 decode하는 일입니다." },
    { question: "XML declaration의 세 pseudo-attribute 순서와 필수 여부는 어떻게 되나요?", answer: "version이 필수로 먼저 오고, 선택적 encoding, 선택적 standalone 순서입니다." },
    { question: "standalone=yes가 network와 external entity 접근을 차단하나요?", answer: "아닙니다. 외부 markup declaration이 document 정보에 영향을 주지 않는다는 assertion이며 parser security 설정을 대신하지 않습니다." },
    { question: "well-formed XML document의 top-level element는 몇 개인가요?", answer: "정확히 하나의 document element가 있어야 하며 comment·PI는 그 앞뒤에 올 수 있습니다." },
    { question: "`<Product></product>`가 실패하는 이유는 무엇인가요?", answer: "XML name matching은 case-sensitive이고 case folding을 하지 않아 서로 다른 name이기 때문입니다." },
    { question: "`<item/>`과 `<item></item>`은 어떤 관계인가요?", answer: "둘 다 content가 없는 같은 빈 element를 표현하는 well-formed XML syntax입니다." },
    { question: "text나 attribute에 A & B를 그대로 써도 되나요?", answer: "아닙니다. ampersand는 `&amp;` 같은 reference로 escape해야 parser 결과에서 실제 `A & B`를 얻습니다." },
    { question: "CDATA 안의 `<x>`는 child element가 되나요?", answer: "아닙니다. CDATA section의 내용은 character data이며 `]]>` close sequence는 직접 포함할 수 없습니다." },
    { question: "pretty-print indentation은 언제 무시해도 되는 whitespace인가요?", answer: "schema/application content model이 element-only 등으로 의미 없음을 정한 위치에서만 안전하게 정규화할 수 있습니다. parser는 기본적으로 character data로 전달할 수 있습니다." },
    { question: "ElementTree와 browser DOM에서 comment가 다르게 보일 수 있는 이유는 무엇인가요?", answer: "ElementTree 기본 parser는 input comment와 PI를 tree에 삽입하지 않지만 browser DOM은 해당 node type을 표현할 수 있기 때문입니다." },
    { question: "well-formed XML이면 price가 integer라는 사실도 보장되나요?", answer: "아닙니다. type·필수·범위는 schema 또는 application validation의 별도 책임입니다." },
    { question: "fatal error 뒤 partial tree를 계속 업무 처리해도 되나요?", answer: "안 됩니다. processor는 추가 진단을 할 수 있어도 정상 character data와 logical structure를 계속 application에 전달하면 안 됩니다." },
    { question: "신뢰할 수 없는 XML에서 최소 보안 경계는 무엇인가요?", answer: "DTD·external entity·network·XInclude 기본 거부, patched parser, byte/depth/token/time/memory 제한, 최소 권한 격리와 안전한 오류 기록입니다." },
  ],
  completionChecklist: [
    "원본 두 파일의 BOM·UTF-8 bytes·CRLF·declaration과 document element를 감사했다.",
    "bytes→Unicode→markup token→logical tree의 단계와 byte/string parser 차이를 설명했다.",
    "version·encoding·standalone의 순서·의미·한계를 정확히 구분했다.",
    "단일 document element, proper nesting, case-sensitive matching을 fatal fixture로 검증했다.",
    "empty-element tag와 start/end pair의 등가 및 element 부재/null과의 차이를 설명했다.",
    "attribute quote·uniqueness와 text/attribute reference escaping을 round-trip했다.",
    "comment·CDATA·PI의 금지 delimiter와 XML declaration 차이를 DOM node로 확인했다.",
    "indentation whitespace를 DOM Text/ElementTree text·tail에서 확인하고 무조건 trim하지 않았다.",
    "well-formed, schema-valid, business-valid gate를 분리했다.",
    "ElementTree ParseError와 browser DOMParser error document를 adapter에서 일관되게 처리했다.",
    "namespace는 예약 prefix/colon 경계만 다루고 prefix·expanded name은 다음 세션 범위로 남겼다.",
    "DTD·external entity·network·XInclude와 entity/resource exhaustion을 실행 없이 방어 관점으로 검토했다.",
    "parser/library version, input size·depth·token·time·memory limit과 safe logging을 운영 정책에 포함했다.",
  ],
  nextSessions: ["xml-02-elements-attributes-namespace"],
  sources: [
    { id: "web-xml-elements-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data01.xml", usedFor: ["XML 1.0/UTF-8 declaration", "single products root", "element-centered product/name/price", "comments", "indentation whitespace"], evidence: "531-byte BOM 없는 UTF-8/CRLF 원본 전체를 읽고 products 아래 product 4개, name 흰우유·사이다·물·쥬스와 price 950·1450·900·2000, root 전/내부 comment와 whitespace를 parser 예제에 반영했습니다." },
    { id: "web-xml-attributes-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data02.xml", usedFor: ["XML 1.0/UTF-8 declaration", "single products root", "attribute-centered empty product", "quoted attributes", "comments"], evidence: "316-byte BOM 없는 UTF-8/CRLF 원본 전체를 읽고 name·price attribute를 가진 self-closing product 4개와 단일 root/comment 구조를 empty-element·attribute 비교 근거로 사용했습니다." },
    { id: "w3c-xml-10", repository: "W3C XML Core Working Group", path: "TR/xml/", publicUrl: "https://www.w3.org/TR/xml/", usedFor: ["XML 1.0 Fifth Edition", "document production/root", "declaration/encoding/standalone", "name matching", "markup/reference/comment/CDATA/PI", "whitespace", "fatal error", "validity"], evidence: "2026-07-12 직접 확인한 W3C XML 1.0 Fifth Edition Recommendation의 well-formedness constraints와 processor 의무를 설명·오류 matrix·review의 기준으로 사용했습니다." },
    { id: "w3c-xml-names", repository: "W3C XML Core Working Group", path: "TR/xml-names/", publicUrl: "https://www.w3.org/TR/xml-names/", usedFor: ["colon/name boundary", "reserved xml prefix", "namespace next-session scope"], evidence: "Namespaces in XML 1.0 Third Edition을 확인해 colon을 일반 구분자로 남용하지 않고 namespace와 expanded name 전체는 다음 세션으로 분리했습니다." },
    { id: "whatwg-dom", repository: "WHATWG", path: "DOM Standard", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["Document/Element/Text/CDATA/Comment/ProcessingInstruction node", "nodeType", "textContent", "normalize distinction"], evidence: "DOM Standard의 node tree와 CharacterData 계열을 browser node-type example과 whitespace 설명의 기준으로 사용했습니다." },
    { id: "whatwg-domparser", repository: "WHATWG", path: "HTML Standard/dynamic-markup-insertion DOMParser", publicUrl: "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-domparser-parsefromstring", usedFor: ["DOMParser.parseFromString", "application/xml parsing", "XML parse error document"], evidence: "HTML Standard의 DOM parsing and serialization algorithm을 확인하고 Chromium에서 실제 parsererror contract와 정상 node output을 실행 검증했습니다." },
    { id: "python-elementtree", repository: "Python Software Foundation", path: "library/xml.etree.elementtree.html", publicUrl: "https://docs.python.org/3/library/xml.etree.elementtree.html", usedFor: ["fromstring", "Element/text/tail", "comment/PI default behavior", "ParseError code/position", "XMLParser/Expat"], evidence: "2026-07-12 Python 공식 ElementTree 문서와 실제 runtime을 대조해 두 Python 예제의 exact output, default tree preservation과 fatal exception 설명을 검증했습니다." },
    { id: "python-xml-security", repository: "Python Software Foundation", path: "library/xml.html#xml-vulnerabilities", publicUrl: "https://docs.python.org/3/library/xml.html#xml-vulnerabilities", usedFor: ["Expat dependency/version", "entity expansion", "large token/resource exhaustion", "safe parser operations"], evidence: "Python 공식 XML security 안내의 현재 Expat version/resource 위험을 확인해 공격 payload 없이 patch·feature deny·resource limit·isolation 방어만 작성했습니다." },
  ],
  sourceCoverage: {
    filesRead: 2,
    filesUsed: 2,
    uncoveredNotes: [
      "원본 두 파일은 XML declaration, UTF-8, 단일 products root, comment, 요소 중심 content, quoted attribute와 empty-element syntax를 직접 제공합니다. standalone, CDATA, PI, fatal matrix, validity와 security boundary는 W3C/WHATWG/Python 공식 문서 기반 보강 범위입니다.",
      "원본에는 namespace declaration, DTD, XSD, XPath, XSLT가 없습니다. namespace prefix·default namespace·expanded name과 요소/속성 modeling은 xml-02, browser query/render는 xml-03, schema와 보안 parser 심화는 별도 후속 범위로 남깁니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 360;
expertSession.chapters.push({
  id: "transport-decoding-streaming-validation-security-contract",
  title: "transport bytes부터 decoder·well-formed parser·validation·secure runtime까지 경계를 고정합니다",
  lead: "XML 문서를 문자열 예제로만 보지 않고 HTTP/file bytes가 Unicode가 되고 tree로 materialize된 뒤 vocabulary 규칙을 통과하는 전체 pipeline으로 검증합니다.",
  explanations: [
    "XML processor의 입력은 bytes 또는 characters일 수 있습니다. bytes 입력에서는 BOM, XML declaration의 encoding, transport metadata가 encoding detection에 관여하지만 JavaScript string처럼 이미 Unicode characters가 된 입력에서는 declaration이 다시 bytes를 decode하지 않습니다. 어느 layer가 decoding을 소유하는지 먼저 기록합니다.",
    "HTTP의 XML media types와 charset parameter는 representation metadata입니다. server Content-Type, XML declaration, 실제 bytes가 불일치하면 parser/runtime마다 silent replacement 또는 fatal error가 달라질 수 있으므로 API contract를 UTF-8로 통일하고 non-ASCII golden bytes로 검증합니다. file extension만으로 encoding을 추측하지 않습니다.",
    "UTF-8 한 code point는 여러 bytes일 수 있고 network chunk는 character나 tag 경계와 일치하지 않습니다. chunk마다 새 decoder를 만들면 분할된 문자가 U+FFFD로 손상될 수 있어 하나의 TextDecoder에 stream:true를 사용하고 끝에서 flush합니다. invalid sequence를 replacement로 허용할지 fatal error로 만들지도 data contract입니다.",
    "Unicode code point가 같아 보여도 normalization form이 다를 수 있습니다. XML processor가 application identifier의 NFC 동등성을 자동 보장한다고 가정하지 말고, 사용자 검색·signature·key 비교가 normalization에 민감한지 정책을 정합니다. 원문 preservation과 normalized domain value도 분리합니다.",
    "well-formedness는 단일 document element, proper nesting, quoted attributes, legal characters와 entity/reference 규칙을 만족하는 syntax gate입니다. parser가 tree를 반환했다는 사실과 schema/domain validity를 같은 것으로 부르지 않습니다. fatal syntax error 뒤 partial record를 성공 데이터로 사용하지 않습니다.",
    "DOMParser XML mode는 malformed string에서 항상 exception을 throw한다고 가정할 수 없습니다. parsererror가 든 Document를 반환할 수 있어 namespace-independent check를 하고 application의 PARSE_ERROR로 정규화합니다. parsererror element의 text·namespace·markup은 browser별 detail이므로 exact 문구에 의존하지 않습니다.",
    "Python ElementTree 같은 server/library parser도 API·version·configuration별 동작을 확인합니다. untrusted XML에는 DTD/external entity, network access, entity expansion, XInclude, external schema와 size/depth/node/text limits를 명시적으로 검토합니다. 한 runtime의 browser 관찰을 다른 runtime의 보안 보장으로 일반화하지 않습니다.",
    "DOCTYPE·entity가 필요 없는 application은 parser에서 해당 기능을 비활성화하고 fail-closed로 거부합니다. 문자열에서 `<!DOCTYPE`를 찾는 precheck는 빠른 policy signal일 뿐 encoding·grammar를 이해하는 secure parser configuration을 대신하지 못합니다. 실제 parser에 file/network sentinel fixture를 넣어 접근이 0인지 확인합니다.",
    "DOM tree는 전체 text와 node graph를 memory에 함께 보유할 수 있습니다. Content-Length는 누락·압축·오류가 가능하므로 실제 read bytes/chars, depth, attributes, nodes, text length와 records를 제한합니다. 대용량 feed는 SAX/pull/iterparse 같은 streaming parser를 검토하되 handler state와 early abort, namespace, schema validation을 별도로 설계합니다.",
    "streaming parser도 안전을 자동 보장하지 않습니다. record 경계 전에 잘린 document, root 종료 전 side effect, duplicate ID, late schema error를 처리해야 합니다. validate-before-commit staging을 두거나 한 record가 독립적으로 검증되는 protocol을 사용하고 malformed tail에서 이미 저장한 data를 어떻게 rollback할지 정합니다.",
    "fixture는 UTF-8 multi-byte split, BOM, declaration/transport mismatch, invalid byte, illegal character, mismatched tag, duplicate attribute, multiple roots, truncated stream, DTD/entity, oversize/deep tree를 포함합니다. 오류는 DECODE_ERROR·PARSE_ERROR·VALIDATION_ERROR·LIMIT_EXCEEDED처럼 stage code로 남기고 raw XML·file path·개인정보는 log하지 않습니다.",
  ],
  concepts: [
    { term: "decoding boundary", definition: "byte sequence를 Unicode character sequence로 변환하는 단 한 layer와 그 layer가 신뢰할 BOM·transport·declaration 정책입니다.", detail: ["이미 string이면 XML declaration이 재-decoding하지 않습니다.", "non-ASCII golden bytes로 검증합니다."] },
    { term: "fatal well-formedness error", definition: "XML processor가 정상 document tree 처리를 계속할 수 없는 문법 오류입니다.", detail: ["partial data를 성공으로 사용하지 않습니다.", "application error code로 정규화합니다."] },
    { term: "streaming commit boundary", definition: "전체 document 검증 전에 읽은 일부 record를 언제 외부 state에 반영할지 정하는 transaction 경계입니다.", detail: ["late parse/schema error rollback을 설계합니다.", "record 독립성과 root-level invariants를 구분합니다."] },
  ],
  codeExamples: [
    {
      id: "utf8-streaming-decode-boundary",
      title: "한글 UTF-8 bytes를 문자 중간에서 나눠도 한 decoder로 복원",
      language: "javascript",
      filename: "xml-utf8-boundary.mjs",
      purpose: "XML bytes의 network chunk가 multi-byte character 중간에서 나뉘는 fixture를 만들어 streaming decoder의 state와 declaration/string 경계를 exact 확인합니다.",
      code: "const source = '<?xml version=\"1.0\" encoding=\"UTF-8\"?><product>한글</product>';\nconst bytes = new TextEncoder().encode(source);\nconst firstMultibyte = bytes.findIndex((byte) => byte >= 0x80);\nconst split = firstMultibyte + 1;\nconst chunks = [bytes.slice(0, split), bytes.slice(split)];\n\nconst decoder = new TextDecoder('utf-8', { fatal: true });\nlet decoded = '';\nfor (const chunk of chunks) {\n  decoded += decoder.decode(chunk, { stream: true });\n}\ndecoded += decoder.decode();\n\nconst text = decoded.match(/<product>([^<]+)<\\/product>/)?.[1];\nconsole.log(`declaration=${decoded.includes('encoding=\"UTF-8\"')}`);\nconsole.log(`text=${text}`);\nconsole.log(`replacement=${decoded.includes('\\uFFFD')}`);\nconsole.log(`split-inside=${split === firstMultibyte + 1}`);",
      walkthrough: [
        { lines: "1-5", explanation: "UTF-8 declaration과 한글 text가 있는 XML source를 bytes로 만들고 첫 multi-byte code point의 첫 byte 뒤에서 분할합니다." },
        { lines: "7-12", explanation: "한 fatal TextDecoder instance를 모든 chunk에 재사용해 불완전 byte state를 이어 가고 마지막에 flush합니다." },
        { lines: "14-18", explanation: "이 예제의 고정 fixture에서 text를 관찰하고 declaration 존재, replacement character 부재와 의도한 split을 exact 출력합니다. 정규식은 일반 XML parser가 아닙니다." },
      ],
      run: { environment: ["Node.js 20 이상", "xml-utf8-boundary.mjs를 UTF-8로 저장"], command: "node xml-utf8-boundary.mjs" },
      output: { value: "declaration=true\ntext=한글\nreplacement=false\nsplit-inside=true", explanation: ["XML declaration은 decoded string의 문자로 남지만 decoder 선택은 code의 TextDecoder에서 이미 이루어졌습니다.", "한글 첫 code point가 chunk 사이에서 나뉘어도 streaming decoder가 원문을 복원합니다.", "새 decoder를 chunk마다 만들지 않아 replacement character가 없습니다."] },
      experiments: [
        { change: "각 chunk마다 `new TextDecoder().decode(chunk)`를 호출합니다.", prediction: "분할된 한글 문자가 replacement character로 손상됩니다.", result: "byte chunk와 Unicode character 경계가 다름을 확인합니다." },
        { change: "fatal UTF-8 decoder에 invalid continuation byte fixture를 넣습니다.", prediction: "decode가 TypeError를 throw하고 parser 단계로 진행하지 않습니다.", result: "DECODE_ERROR와 XML PARSE_ERROR를 분리합니다." },
        { change: "전체 decoded string을 NFC normalization 전후로 비교합니다.", prediction: "현재 fixture는 같지만 결합 문자 fixture에서는 byte와 string identity가 달라질 수 있습니다.", result: "identifier 비교와 원문 preservation 정책을 명시합니다." },
      ],
      sourceRefs: ["w3c-xml-10", "ietf-xml-media-types", "w3c-character-model"],
    },
    {
      id: "browser-wellformed-parsererror-contract",
      title: "DOMParser의 정상 tree와 malformed parsererror를 분리",
      language: "html",
      filename: "xml-wellformed-browser.html",
      purpose: "이미 Unicode string인 XML에서 declaration을 metadata 문자로 관찰하고 정상 root/text와 malformed parsererror를 stable application result로 구분합니다.",
      code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>XML well-formedness</title></head>\n<body>\n  <pre id=\"out\" aria-live=\"polite\"></pre>\n  <script>\n    function parse(source) {\n      const documentNode = new DOMParser().parseFromString(source, 'application/xml');\n      const failed = documentNode.getElementsByTagNameNS('*', 'parsererror').length > 0;\n      return { documentNode, failed };\n    }\n\n    const validSource = '<?xml version=\"1.0\" encoding=\"UTF-8\"?><products><product id=\"p1\">키보드</product></products>';\n    const valid = parse(validSource);\n    const invalid = parse('<products><product></products>');\n    const lines = [\n      `valid-root=${valid.documentNode.documentElement.localName}`,\n      `product-text=${valid.documentNode.querySelector('product').textContent}`,\n      `invalid-error=${invalid.failed}`,\n      `declaration-encoding=${/encoding=\"([^\"]+)\"/.exec(validSource)[1]}`,\n    ];\n    document.querySelector('#out').textContent = lines.join('\\n');\n    console.log(lines.join('\\n'));\n  </script>\n</body>\n</html>",
      walkthrough: [
        { lines: "1-5", explanation: "browser HTML shell과 결과를 알릴 status 영역을 만듭니다." },
        { lines: "6-11", explanation: "DOMParser XML mode가 반환한 Document에서 namespace 독립 parsererror 존재를 검사합니다." },
        { lines: "13-15", explanation: "정상 declaration/attribute/text fixture와 mismatched-tag fixture를 각각 parse합니다." },
        { lines: "16-24", explanation: "정상 root/text, malformed 여부와 source declaration 문자를 화면·Console에 exact 기록합니다." },
        { lines: "24-26", explanation: "script와 문서를 닫고 Elements에서 XML Document를 별도 object로 관찰합니다." },
      ],
      run: { environment: ["최신 Chromium 또는 Firefox", "xml-wellformed-browser.html을 UTF-8로 저장", "DevTools Console·Elements·Accessibility", "keyboard로 결과 영역 탐색"], command: "브라우저에서 xml-wellformed-browser.html을 열어 pre·Console exact 출력과 parsererror Document를 확인" },
      output: { value: "valid-root=products\nproduct-text=키보드\ninvalid-error=true\ndeclaration-encoding=UTF-8", explanation: ["정상 document element와 product text가 tree에서 추출됩니다.", "malformed XML은 browser-specific 오류 문구 대신 failed=true로 정규화됩니다.", "encoding declaration은 이미 만들어진 JavaScript string에서 다시 bytes를 decode하지 않습니다."] },
      experiments: [
        { change: "valid source에 두 번째 top-level root를 추가합니다.", prediction: "well-formedness가 깨져 parsererror가 검출됩니다.", result: "XML document는 정확히 하나의 document element를 가져야 합니다." },
        { change: "product id attribute 따옴표를 제거합니다.", prediction: "HTML과 달리 XML mode는 unquoted attribute를 복구하지 않고 오류로 처리합니다.", result: "HTML parser recovery와 XML fatal error를 구분합니다." },
        { change: "DTD/external entity fixture를 browser와 Python/server parser에 각각 넣습니다.", prediction: "동작과 지원 feature가 runtime별로 달라 browser 관찰만으로 server 안전을 증명할 수 없습니다.", result: "server parser에서 DTD/external resolution을 비활성화하고 file/network sentinel 접근 0을 검증합니다." },
      ],
      sourceRefs: ["web-xml-attributes-source", "w3c-xml-10", "w3c-xml-names", "whatwg-dom", "whatwg-domparser", "python-xml-security"],
    },
  ],
  diagnostics: [
    { symptom: "UTF-8 XML이 작은 응답에서는 정상인데 streaming download에서 가끔 한글이 깨진다.", likelyCause: "network chunk마다 decoder를 새로 만들어 multi-byte code point를 독립 decode했습니다.", checks: ["한글 byte 중간에서 의도적으로 chunk를 나눕니다.", "하나의 TextDecoder와 stream:true/flush 사용을 확인합니다.", "replacement와 fatal 정책을 기록합니다."], fix: "한 decoder instance로 모든 bytes를 streaming decode하고 종료에서 flush한 뒤 완전한 string 또는 검증된 streaming parser에 전달합니다.", prevention: "모든 split offset과 invalid byte fixture를 자동 순회합니다." },
    { symptom: "browser에서는 XXE가 보이지 않아 server XML upload도 그대로 허용했다.", likelyCause: "DOMParser와 production parser의 feature/default/configuration 차이를 무시했습니다.", checks: ["실제 server parser/version/effective flags를 확인합니다.", "DTD·external entity·XInclude·schema access를 각각 sentinel로 검사합니다.", "entity expansion·size·depth limits를 점검합니다."], fix: "production parser에서 필요 없는 DTD/external resolution을 명시 비활성화하고 resource limits와 실제 file/network 접근 0 test를 둡니다.", prevention: "parser upgrade마다 보안 configuration fingerprint와 malicious fixture suite를 재실행합니다." },
  ],
  expertNotes: ["Node 예제의 정규식은 decoder 결과 관찰용 고정 fixture일 뿐 XML parser가 아닙니다. 실제 XML structure·entity·namespace 처리는 conforming parser에 맡깁니다.", "streaming은 memory 절감 수단이지 자동 validity/security 기능이 아닙니다. 전체-document invariant와 commit/rollback을 별도 설계합니다."],
});

expertSession.reviewQuestions.push(
  { question: "response.text로 이미 만든 JavaScript string의 XML declaration이 encoding을 다시 선택하나요?", answer: "아닙니다. bytes에서 string으로의 decoding은 이미 끝났고 declaration은 string 안의 문자일 뿐입니다." },
  { question: "UTF-8 network chunk마다 새 TextDecoder를 만들면 왜 위험한가요?", answer: "multi-byte code point가 chunk 사이에서 나뉠 수 있어 불완전 sequence가 replacement 또는 오류가 되므로 한 decoder의 streaming state를 이어야 합니다." },
  { question: "browser DOMParser에서 external entity가 확장되지 않으면 server parser도 안전한가요?", answer: "아닙니다. runtime별 기능과 defaults가 다르므로 production parser에서 DTD/external resolution을 끄고 실제 sentinel test를 해야 합니다." },
);
expertSession.completionChecklist.push(
  "transport bytes·BOM·Content-Type·XML declaration·TextDecoder의 단일 decoding boundary를 기록했다.",
  "multi-byte split·invalid bytes·normalization fixture로 streaming decode를 검증했다.",
  "well-formedness·namespace/schema/domain validation과 parser error code를 분리했다.",
  "server parser의 DTD/external entity/XInclude/resource limits와 streaming commit rollback을 검증했다.",
);
expertSession.sources.push(
  { id: "ietf-xml-media-types", repository: "IETF RFC Editor", path: "RFC 7303 XML Media Types", publicUrl: "https://www.rfc-editor.org/rfc/rfc7303", usedFor: ["application/xml and text/xml media types", "charset parameter", "BOM and XML declaration interaction", "fragment identifiers"], evidence: "transport Content-Type과 XML 자체 encoding information의 책임을 구분하고 UTF-8 API contract를 설계하는 공식 HTTP media-type 근거로 사용했습니다." },
  { id: "w3c-character-model", repository: "W3C", path: "Character Model for the World Wide Web: Fundamentals", publicUrl: "https://www.w3.org/TR/charmod/", usedFor: ["bytes and characters", "character encoding", "Unicode code points", "normalization", "string identity"], evidence: "XML bytes→Unicode 경계와 visually equivalent strings의 normalization/identity 정책을 설명하는 Web character model 근거로 사용했습니다." },
);
