import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["xml-02-elements-attributes-namespace"],
  slug: "xml-02-elements-attributes-namespace",
  courseId: "web",
  moduleId: "03-xml-data-formats",
  order: 2,
  title: "XML 요소·속성·혼합 콘텐츠와 namespace 설계",
  subtitle: "같은 상품을 요소형·속성형·혼합형으로 모델링하고, 실제 기본 namespace 날씨 문서를 URI와 local name으로 정확히 조회합니다.",
  level: "중급",
  estimatedMinutes: 245,
  coreQuestion: "정보를 element text·child element·attribute 중 어디에 둘지 어떻게 결정하며, prefix가 바뀌어도 동일한 namespace의 이름을 안정적으로 찾으려면 무엇을 비교해야 할까요?",
  summary: "원본 data01의 child element 상품, data02의 empty element+attribute 상품, data03의 attribute+manufacturer text 혼합형, `xmlns=\"current\"` 날씨 XML을 한 자료 모델로 비교합니다. element/attribute/text node와 빈 값·누락·반복·순서·확장성·공백을 구분하고 mixed content의 text/tail order를 실제 실행합니다. namespace declaration의 lexical scope, prefix와 URI의 차이, expanded name, default namespace가 unprefixed element에는 적용되지만 unprefixed attribute에는 적용되지 않는 규칙, reserved xml/xmlns, namespace-aware ElementTree/DOM/XPath 조회와 serialization prefix 변화를 다룹니다. 마지막에는 schema/versioning, canonicalization/signature, query 성능, 안전한 parser 경계를 포함해 유지 가능한 XML vocabulary를 설계합니다.",
  objectives: [
    "element, attribute, text node와 child order를 구분하고 원본 세 상품 모델을 정확히 tree로 그릴 수 있다.",
    "반복·순서·빈 값·확장·사람이 읽는 content 요구를 근거로 element와 attribute의 위치를 선택할 수 있다.",
    "mixed content에서 element.text와 child.tail이 만드는 ordered character sequence를 손실 없이 순회할 수 있다.",
    "namespace prefix, namespace name URI, local name과 expanded name을 구분하고 prefix spelling에 의존하지 않을 수 있다.",
    "default namespace의 element/attribute 적용 차이를 설명하고 ElementTree·DOM·XPath의 namespace-aware query를 작성할 수 있다.",
    "schema version·unknown extension·serialization/canonicalization·security limit을 포함한 XML vocabulary contract를 설계할 수 있다.",
  ],
  prerequisites: [
    { title: "XML 선언, 단일 루트와 well-formed 트리", reason: "well-formed document, UTF-8, element nesting, empty-element와 attribute quoting을 알고 그 tree의 data modeling과 namespace identity로 확장합니다.", sessionSlug: "xml-01-wellformed-tree-encoding" },
  ],
  keywords: ["XML element", "attribute", "text node", "mixed content", "tail text", "empty versus missing", "namespace", "xmlns", "prefix", "namespace URI", "local name", "expanded name", "Clark notation", "XPath", "schema design"],
  chapters: [
    {
      id: "element-attribute-text-tree",
      title: "XML 정보는 element의 이름·attribute set·순서 있는 child node로 나뉩니다",
      lead: "꺾쇠 안과 밖의 문자열을 모두 같은 key/value로 보면 빈 값·순서·mixed content를 잘못 읽습니다.",
      explanations: [
        "element는 이름과 attribute, child node sequence를 가진 tree node입니다. `<product><name>흰우유</name><price>950</price></product>`에서 product는 name과 price element를 순서대로 자식으로 두고, 각 child가 text를 가집니다. indentation newline과 spaces도 parser data model에서는 text/tail이 될 수 있습니다.",
        "attribute는 start-tag에 붙은 name/value pair이며 child element가 아닙니다. `<product name=\"제너시스\" price=\"100\"/>`의 name과 price는 product.attrib에서 읽고 child count는 0입니다. attribute value는 XML schema 없이 parser가 제공할 때 일반적으로 character string이며 숫자 100으로 자동 보장되지 않습니다.",
        "data03은 name/price attribute와 product의 direct text인 제조사를 함께 사용합니다. 이것은 well-formed이지만 제조사 field에 명시적 이름이 없어 나중에 description이나 origin을 추가하면 direct text의 의미가 모호해질 수 있습니다. `<manufacturer>` child로 바꾸면 확장과 schema/query가 명확해집니다.",
        "text node는 element 시작/끝 사이의 character data입니다. ElementTree에서 element.text는 첫 child 전 text, 각 child.tail은 그 child end 뒤 다음 sibling/parent end 전 text입니다. DOM에서는 별도 Text node로 나타나며 adjacent text가 normalize될 수 있습니다.",
        "attribute order는 application 의미로 사용하지 않습니다. XML processor/serializer가 다른 순서로 출력할 수 있고 namespace declaration도 일반 application attribute와 다른 역할입니다. 의미 있는 순서는 child element sequence로 모델링합니다.",
      ],
      concepts: [
        { term: "element content", definition: "element의 start-tag와 end-tag 사이에 놓인 child element와 character data의 순서 있는 내용입니다.", detail: ["element-only, text-only, mixed, empty 형태가 가능합니다.", "indentation도 text가 될 수 있습니다."] },
        { term: "attribute", definition: "start-tag 또는 empty-element tag에 붙는 이름과 정규화된 문자열 값의 pair입니다.", detail: ["child node가 아닙니다.", "같은 element에서 같은 expanded name을 두 번 쓸 수 없습니다."] },
        { term: "tail text", definition: "ElementTree에서 한 child element가 끝난 뒤 다음 sibling 또는 parent end-tag 전의 character data입니다.", detail: ["mixed content order 복원에 필요합니다.", "DOM에서는 sibling Text node에 해당합니다."] },
      ],
      codeExamples: [
        {
          id: "compare-product-models",
          title: "요소형·속성형·direct-text 상품을 같은 record로 읽기",
          language: "python",
          filename: "product_models.py",
          purpose: "학습 원본 세 구조에서 같은 name/price/maker가 parser API의 서로 다른 위치에 있음을 exact output으로 확인합니다.",
          code: "from xml.etree import ElementTree as ET\n\nelement_xml = \"\"\"<products><product><name>흰우유</name><price>950</price></product></products>\"\"\"\nattribute_xml = \"\"\"<products><product name=\"제너시스\" price=\"100\"/></products>\"\"\"\nmixed_xml = \"\"\"<products><product name=\"K9\" price=\"90\">기아자동차</product></products>\"\"\"\n\ndef read_element(source):\n    product = ET.fromstring(source).find(\"product\")\n    return product.findtext(\"name\"), product.findtext(\"price\"), None\n\ndef read_attributes(source):\n    product = ET.fromstring(source).find(\"product\")\n    return product.get(\"name\"), product.get(\"price\"), None\n\ndef read_direct_text(source):\n    product = ET.fromstring(source).find(\"product\")\n    return product.get(\"name\"), product.get(\"price\"), (product.text or \"\").strip()\n\nfor label, row in [\n    (\"element\", read_element(element_xml)),\n    (\"attribute\", read_attributes(attribute_xml)),\n    (\"direct-text\", read_direct_text(mixed_xml)),\n]:\n    print(f\"{label}:name={row[0]},price={row[1]},maker={row[2]!r}\")",
          walkthrough: [
            { lines: "1-5", explanation: "원본의 세 modeling pattern을 한 상품씩 축소해 선언합니다." },
            { lines: "7-17", explanation: "child findtext, attribute get, direct element text를 각각 명시적인 adapter로 분리합니다." },
            { lines: "19-24", explanation: "동일한 record tuple로 만든 뒤 값과 missing maker를 repr로 출력합니다." },
          ],
          run: { environment: ["Python 3.11+ 표준 library"], command: "python product_models.py" },
          output: { value: "element:name=흰우유,price=950,maker=None\nattribute:name=제너시스,price=100,maker=None\ndirect-text:name=K9,price=90,maker='기아자동차'", explanation: ["같은 의미라도 parser 위치가 달라 adapter가 다릅니다.", "price는 출력상 숫자처럼 보여도 세 경우 모두 string입니다.", "None은 field missing이며 empty string과 구분해야 합니다."] },
          experiments: [
            { change: "element_xml에 두 번째 `<name>`을 추가합니다.", prediction: "findtext는 첫 값만 반환해 중복을 숨길 수 있습니다.", result: "schema/cardinality가 하나를 요구한다면 findall count를 먼저 검사합니다." },
            { change: "mixed_xml product 안에 `<manufacturer>` child를 넣고 기존 direct text를 유지합니다.", prediction: "product.text와 child/tail이 함께 존재하는 mixed structure가 됩니다.", result: "record data에서는 named child field가 더 명시적일 수 있습니다." },
            { change: "attribute price를 빈 문자열로 바꿉니다.", prediction: "get은 `''`를 반환하고 missing attribute의 None과 다릅니다.", result: "empty/missing/default policy를 schema에 둡니다." },
          ],
          sourceRefs: ["web-xml-elements-source", "web-xml-attributes-source", "web-xml-mixed-source", "python-elementtree"],
        },
      ],
      diagnostics: [
        { symptom: "product.find('name')이 None인데 XML에는 name이 보인다.", likelyCause: "해당 source는 name을 child element가 아니라 attribute에 저장했거나 namespace-qualified element입니다.", checks: ["product.attrib과 child tag 목록을 각각 출력합니다.", "tag의 namespace URI/local name을 확인합니다.", "세 원본 중 어느 schema/version인지 기록합니다."], fix: "source schema별 adapter를 두거나 명시적 version에서 한 canonical model로 migration합니다.", prevention: "요소형/속성형/namespace형 positive fixture와 wrong-shape negative test를 둡니다." },
      ],
    },
    {
      id: "modeling-elements-versus-attributes",
      title: "요소와 속성 선택은 길이보다 반복·순서·확장·내용의 성격으로 결정합니다",
      lead: "‘중요하면 요소, 부가 정보면 속성’은 출발점일 뿐 절대 규칙이 아니며 consumer와 schema 요구를 함께 봅니다.",
      explanations: [
        "attribute는 한 element 안에서 같은 expanded name을 한 번만 가질 수 있으므로 반복 값에 부적합합니다. 여러 category, 전화번호, 가격 이력처럼 zero-to-many가 필요하면 child element sequence가 자연스럽습니다.",
        "element는 child structure를 가질 수 있어 `price`에 currency, amount, tax breakdown을 추가하기 쉽습니다. attribute value는 markup child를 포함할 수 없고 긴 사람이 읽는 문장/mixed markup에도 적합하지 않습니다.",
        "짧고 원자적이며 element 자체를 식별·분류하는 metadata인 id, language, status, unit은 attribute가 편리할 수 있습니다. 그러나 price를 attribute로 두는 것이 틀린 것은 아니며 XSD datatype과 versioned contract가 있으면 충분히 명확할 수 있습니다.",
        "원본 data01의 name/price child는 반복·확장에 유리하고 data02의 attribute-only empty product는 compact합니다. data03의 제조사 direct text는 짧지만 field name이 없어 확장성이 낮습니다. 목표 domain이 record라면 manufacturer child/attribute 중 명시적 이름을 택합니다.",
        "순서는 child node에 자연스럽지만 attribute 순서에는 의존하면 안 됩니다. key/value 순서가 실제 의미라면 `<step index=...>` sequence 또는 document order를 schema에 명시합니다.",
        "localization과 rich text가 필요하면 element content가 유리합니다. `xml:lang`, namespace extension, whitespace policy와 함께 설계하고 label을 attribute 하나에 넣어 markup을 escape해 저장하는 anti-pattern을 피합니다.",
      ],
      concepts: [
        { term: "cardinality", definition: "한 field/element가 최소·최대 몇 번 나타날 수 있는지에 관한 구조 제약입니다.", detail: ["attribute는 이름당 최대 한 번입니다.", "child element는 schema로 반복 범위를 정할 수 있습니다."] },
        { term: "metadata", definition: "element가 나타내는 자원의 식별·분류·상태·단위 같은 설명 정보입니다.", detail: ["attribute가 흔하지만 절대 규칙은 아닙니다.", "query와 evolution 비용을 함께 봅니다."] },
        { term: "schema evolution", definition: "consumer 호환성을 유지하며 field·namespace·type·cardinality를 시간에 따라 바꾸는 과정입니다.", detail: ["version과 unknown-extension policy가 필요합니다.", "element↔attribute 이동은 breaking change일 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "한 product에 category를 여러 개 넣으려고 같은 category attribute를 반복하자 parse error가 난다.", likelyCause: "attribute name은 한 element에서 unique해야 하는데 반복 collection으로 사용했습니다.", checks: ["category의 cardinality와 order 의미를 정의합니다.", "delimiter string으로 합치려는 code가 있는지 봅니다.", "schema consumer가 반복 child를 지원하는지 확인합니다."], fix: "각 category를 반복 child element로 모델링하고 schema의 maxOccurs와 uniqueness rule을 정의합니다.", prevention: "설계 review에서 scalar/optional/repeated/ordered를 field마다 표로 정합니다." },
      ],
      comparisons: [
        { title: "상품 field의 기본 modeling 후보", options: [
          { name: "child element", chooseWhen: "반복·순서·nested structure·긴 text·향후 확장이 필요할 때", avoidWhen: "짧은 원자 metadata만 있고 compact attribute query가 기존 contract일 때", tradeoffs: ["명시적이고 확장 가능하지만 markup이 늘어납니다.", "mixed/whitespace를 의식해야 합니다.", "cardinality를 schema로 정합니다."] },
          { name: "attribute", chooseWhen: "한 element당 하나인 짧은 식별·상태·단위 metadata일 때", avoidWhen: "반복·rich content·nested structure·의미 있는 order가 필요할 때", tradeoffs: ["compact하고 접근이 쉽습니다.", "문자열 value이며 같은 이름 반복이 불가합니다.", "attribute order에 의미를 두지 않습니다."] },
          { name: "direct text", chooseWhen: "element 자체가 하나의 text value이고 child structure가 필요 없을 때", avoidWhen: "여러 named field나 mixed content가 생길 가능성이 클 때", tradeoffs: ["간결합니다.", "indentation/mixed child에서 text/tail 처리가 필요합니다.", "field name은 parent element name이 담당합니다."] },
        ] },
      ],
    },
    {
      id: "mixed-content-order",
      title: "mixed content는 text와 child element가 교대로 나타나는 순서 자체가 데이터입니다",
      lead: "`.text` 한 번이나 descendant text join만으로는 강조·link·code가 문장 어디에 있었는지 복원할 수 없습니다.",
      explanations: [
        "`<p>XML은 <em>문서</em>와 <code>데이터</code>를 표현한다.</p>`에서 p.text는 `XML은 `, em.text는 `문서`, em.tail은 `와 `, code.text는 `데이터`, code.tail은 `를 표현한다.`입니다. 이것을 source order로 이어야 원문과 inline semantics가 보존됩니다.",
        "ElementTree의 `itertext()`는 descendant character data를 document order로 연결하지만 어느 segment가 em/code 내부였는지는 잃습니다. 검색용 plain text에는 적합하지만 rich renderer나 format conversion에는 node kind와 order를 함께 보존합니다.",
        "indentation-only whitespace가 있는 element-only document와 사람이 작성한 mixed sentence의 spaces를 같은 `strip()` rule로 처리하면 단어가 붙거나 줄바꿈이 사라집니다. schema/content type별 whitespace normalization policy를 둡니다.",
        "CDATA section은 markup처럼 보이는 text를 쓰기 편한 lexical syntax이지만 parse한 logical character data는 일반 escaped text와 동일할 수 있습니다. lexical CDATA boundary 자체가 보존 요구라면 일반 tree API가 충분한지 확인합니다.",
        "HTML로 렌더링할 때 XML element 이름을 그대로 innerHTML에 연결하지 않습니다. 허용 vocabulary를 `em`→HTML em처럼 explicit mapping하고 text는 textContent로 넣으며 unknown element policy를 정의합니다.",
      ],
      concepts: [
        { term: "mixed content", definition: "한 element의 child sequence에 character data와 child element가 함께 나타나는 content model입니다.", detail: ["문서 markup에 흔합니다.", "node order가 의미입니다."] },
        { term: "itertext", definition: "ElementTree subtree의 text와 tail character data를 document order로 순회하는 helper입니다.", detail: ["plain text 추출에 유용합니다.", "markup 경계 정보는 제공하지 않습니다."] },
        { term: "lexical versus logical form", definition: "CDATA/quote/prefix 같은 source spelling과 parser가 제공하는 character/node meaning의 구분입니다.", detail: ["logical equality가 byte equality를 뜻하지 않습니다.", "round-trip 요구를 먼저 정합니다."] },
      ],
      codeExamples: [
        {
          id: "walk-mixed-text-tail",
          title: "text·element·tail을 source order로 순회하기",
          language: "python",
          filename: "mixed_content.py",
          purpose: "ElementTree mixed content의 각 segment가 `.text`와 `.tail` 어디에 저장되는지 exact sequence로 확인합니다.",
          code: "from xml.etree import ElementTree as ET\n\nroot = ET.fromstring(\"<p>XML은 <em>문서</em>와 <code>데이터</code>를 표현한다.</p>\")\nsegments = [(\"text\", root.text)]\nfor child in root:\n    segments.append((f\"element:{child.tag}\", child.text))\n    segments.append((\"tail\", child.tail))\n\nprint(\"|\".join(f\"{kind}={value!r}\" for kind, value in segments))\nprint(\"plain=\" + \"\".join(root.itertext()))",
          walkthrough: [
            { lines: "1-3", explanation: "text와 em/code child가 교차하는 한 문장을 parse합니다." },
            { lines: "4-7", explanation: "parent 시작 text, 각 child 자체 text, child 뒤 tail을 정확한 순서로 수집합니다." },
            { lines: "9-10", explanation: "structure-aware segment와 structure를 제거한 plain text를 함께 출력합니다." },
          ],
          run: { environment: ["Python 3.11+ 표준 library"], command: "python mixed_content.py" },
          output: { value: "text='XML은 '|element:em='문서'|tail='와 '|element:code='데이터'|tail='를 표현한다.'\nplain=XML은 문서와 데이터를 표현한다.", explanation: ["tail은 parent text가 아니라 앞선 child 객체에 저장됩니다.", "plain 문장은 같아도 em/code 경계 정보는 첫 line에만 남습니다.", "무조건 strip하면 필요한 spaces가 사라질 수 있습니다."] },
          experiments: [
            { change: "em 뒤의 `와 ` 앞 space를 제거합니다.", prediction: "em.tail이 `와 `가 되고 plain text도 해당 공백 없이 이어집니다.", result: "mixed content whitespace는 문장 데이터입니다." },
            { change: "`''.join(root.itertext())`만 JSON에 저장합니다.", prediction: "읽을 문장은 보존되지만 강조와 code 경계를 복구할 수 없습니다.", result: "변환 전에 보존할 의미를 결정합니다." },
            { change: "code 안에 또 다른 child를 중첩합니다.", prediction: "현재 한 단계 loop는 nested markup 구조를 완전히 기록하지 못합니다.", result: "recursive event/tree representation이 필요합니다." },
          ],
          sourceRefs: ["w3c-xml", "xml-infoset", "python-elementtree"],
        },
      ],
      diagnostics: [
        { symptom: "XML 문장을 HTML로 옮기자 강조 뒤 단어 사이 공백이 사라졌다.", likelyCause: "child.text만 읽고 child.tail을 버렸거나 모든 segment에 strip을 적용했습니다.", checks: ["parent.text와 각 child.text/tail repr를 출력합니다.", "source content model이 mixed인지 확인합니다.", "plain text와 node sequence snapshot을 비교합니다."], fix: "text→child→tail 순서를 재귀적으로 보존하고 schema가 허용한 inline element만 안전하게 mapping합니다.", prevention: "inline element 앞뒤 공백·nested emphasis·punctuation fixture의 render regression test를 둡니다." },
      ],
    },
    {
      id: "namespace-uri-prefix-expanded-name",
      title: "namespace는 prefix 철자가 아니라 URI와 local name으로 이름 충돌을 분리합니다",
      lead: "`a:item`과 `b:item`이 같을 수도 있고, 접두사 없는 두 item이 서로 다른 이름일 수도 있습니다.",
      explanations: [
        "namespace declaration `xmlns:w=\"urn:weather\"`는 prefix w를 namespace name URI에 bind합니다. `w:local`의 expanded name은 `{urn:weather}local`로 생각할 수 있습니다. prefix는 source의 짧은 alias이고 identity는 namespace URI와 local name pair입니다.",
        "동일 URI를 `w`, `wx` 또는 default namespace로 bind해도 expanded name은 같습니다. 반대로 둘 다 local name이 product여도 `{urn:shop:v1}product`와 `{urn:warehouse:v1}product`는 다른 이름입니다. prefix string을 database key나 business identity로 저장하지 않습니다.",
        "namespace URI는 이름 충돌을 피하는 identifier이며 반드시 browser에서 접속 가능한 web page일 필요는 없습니다. HTTP URI를 사용해 문서를 제공할 수는 있지만 dereference 가능성이 namespace equality 조건은 아닙니다.",
        "declaration scope는 선언한 element와 descendants에 적용되고 inner declaration이 같은 prefix를 rebind할 수 있습니다. namespace-aware parser는 scope를 해석해 expanded name을 제공하므로 query도 URI를 기준으로 합니다.",
        "`xml` prefix는 지정된 XML namespace에 예약되고 `xmlns`와 관련 namespace도 declaration 용도로 예약됩니다. 임의 vocabulary가 이 prefix를 재정의하지 않습니다. `xml:lang`, `xml:space`는 표준 의미를 가집니다.",
        "namespace versioning은 URI를 매 버전마다 바꿀지, schema version attribute를 둘지, backward-compatible extension namespace를 허용할지 consumer migration 비용과 함께 정합니다. URI 변경은 모든 expanded name을 바꾸는 큰 contract 변경입니다.",
      ],
      concepts: [
        { term: "namespace name", definition: "XML 이름 vocabulary를 식별하는 URI reference입니다.", detail: ["접속 가능한 resource일 필요는 없습니다.", "local name과 함께 expanded name을 만듭니다."] },
        { term: "prefix", definition: "문서의 특정 scope에서 namespace URI에 bind된 짧은 lexical alias입니다.", detail: ["동일 URI에 다른 prefix를 쓸 수 있습니다.", "identity가 아닙니다."] },
        { term: "expanded name", definition: "namespace name과 local name의 pair로 구분한 element/attribute의 실제 namespace-aware 이름입니다.", detail: ["ElementTree는 `{uri}local` Clark notation을 사용합니다.", "prefix 변경과 무관합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "공급자가 `w:` prefix를 `weather:`로 바꾸자 parser query가 모두 0개가 됐다.", likelyCause: "query가 namespace URI/local name이 아니라 source prefix 문자열에 결합됐습니다.", checks: ["변경 전후 namespace declaration URI를 비교합니다.", "각 node의 namespaceURI/localName 또는 `{uri}tag`를 출력합니다.", "XPath resolver가 어떤 mapping을 쓰는지 확인합니다."], fix: "application이 정한 임의 query prefix를 동일 URI에 bind하고 namespace-aware API로 local을 조회합니다.", prevention: "동일 URI를 default/w/wx prefix로 표현한 equivalent fixture를 contract test합니다." },
      ],
    },
    {
      id: "default-namespace-attribute-rule",
      title: "default namespace는 접두사 없는 element에 적용되지만 접두사 없는 attribute에는 적용되지 않습니다",
      lead: "날씨 XML의 `<local stn_id=...>`에서 element와 attribute는 서로 다른 namespace 상태입니다.",
      explanations: [
        "원본 root는 `<current xmlns=\"current\">`입니다. 이 default namespace declaration은 current 자신과 접두사 없는 weather/local descendant element 이름을 namespace `current`에 넣습니다. 따라서 ElementTree tag는 `current`가 아니라 `{current}current`, `{current}local`입니다.",
        "같은 local element의 `stn_id`, `icon`, `desc`, `ta`, `rn_hr1`, `sd_tot`에는 prefix가 없습니다. default namespace는 attribute name에 적용되지 않으므로 이들은 no-namespace attribute입니다. `get('ta')`로 읽고 `get('{current}ta')`로 읽으면 None입니다.",
        "attribute를 namespace에 넣으려면 `xmlns:m=\"urn:meta\"`처럼 prefix를 선언하고 `m:source=\"lab\"`처럼 qualified name을 사용합니다. 해당 expanded name은 `{urn:meta}source`가 됩니다.",
        "default namespace를 빈 값으로 다시 선언해 descendants의 unprefixed element를 no-namespace로 되돌리는 document도 있을 수 있습니다. parser node마다 namespaceURI를 확인하고 ancestor의 한 선언을 전역 상수처럼 추측하지 않습니다.",
        "ElementTree `find('weather/local')`는 no-namespace child를 찾으므로 원본에서 None입니다. `{current}weather/{current}local` Clark notation 또는 namespace map과 `c:weather/c:local` path를 사용합니다. query prefix c는 source에 실제 쓰인 prefix일 필요가 없습니다.",
      ],
      concepts: [
        { term: "default namespace", definition: "`xmlns=URI` 선언으로 scope 안의 접두사 없는 element 이름에 적용되는 namespace입니다.", detail: ["element 자신과 descendants에 scope가 이어집니다.", "unprefixed attribute에는 적용되지 않습니다."] },
        { term: "no-namespace attribute", definition: "prefix가 없는 attribute로 namespace name이 없는 expanded name을 가집니다.", detail: ["default namespace와 별개입니다.", "get('name')로 조회합니다."] },
        { term: "namespace map", definition: "XPath/query에서 application이 선택한 prefix를 namespace URI에 연결한 mapping입니다.", detail: ["source prefix와 달라도 됩니다.", "query readability를 높입니다."] },
      ],
      codeExamples: [
        {
          id: "query-default-namespace-weather",
          title: "기본 namespace element와 no-namespace/qualified attribute 조회",
          language: "python",
          filename: "namespace_weather.py",
          purpose: "실제 weather default namespace pattern을 축소해 plain query 실패와 expanded-name query 성공, attribute 적용 차이를 exact output으로 증명합니다.",
          code: "from xml.etree import ElementTree as ET\n\nsource = \"\"\"<current xmlns=\"current\" xmlns:m=\"urn:meta\" m:source=\"lab\">\n  <weather><local stn_id=\"108\" ta=\"5.7\">서울</local></weather>\n</current>\"\"\"\nroot = ET.fromstring(source)\nns = {\"c\": \"current\", \"m\": \"urn:meta\"}\nlocal = root.find(\"c:weather/c:local\", ns)\n\nprint(f\"root={root.tag}\")\nprint(f\"local={local.tag}\")\nprint(f\"station={local.get('stn_id')}\")\nprint(f\"temperature={local.get('ta')}\")\nprint(f\"source={root.get('{urn:meta}source')}\")\nprint(f\"plain-find={root.find('weather/local')}\")\nprint(f\"namespaced-ta={local.get('{current}ta')}\")",
          walkthrough: [
            { lines: "1-5", explanation: "default namespace current와 prefixed attribute namespace urn:meta를 가진 최소 날씨 fixture를 만듭니다." },
            { lines: "6-8", explanation: "application query prefix c/m을 URI에 bind하고 namespace-aware path로 local을 찾습니다." },
            { lines: "10-16", explanation: "expanded tag, plain attributes, qualified attribute와 의도적으로 틀린 query 결과를 출력합니다." },
          ],
          run: { environment: ["Python 3.11+ 표준 library"], command: "python namespace_weather.py" },
          output: { value: "root={current}current\nlocal={current}local\nstation=108\ntemperature=5.7\nsource=lab\nplain-find=None\nnamespaced-ta=None", explanation: ["current/weather/local element는 모두 default namespace에 있습니다.", "stn_id와 ta는 prefix가 없어 namespace가 없습니다.", "m:source만 urn:meta namespace에 있고 plain element path는 실패합니다."] },
          experiments: [
            { change: "source의 default namespace를 `urn:weather:v1`로 바꾸고 ns mapping을 그대로 둡니다.", prediction: "query는 local을 찾지 못합니다.", result: "namespace URI 변경은 contract/version 변경입니다." },
            { change: "source를 `xmlns:w=\"current\"`와 `<w:current><w:weather>...`로 바꿉니다.", prediction: "expanded tags가 같아 기존 ns query output이 유지됩니다.", result: "source prefix spelling은 identity가 아닙니다." },
            { change: "ta를 `m:ta=\"5.7\"`로 바꿉니다.", prediction: "get('ta')는 None이고 get('{urn:meta}ta')가 5.7입니다.", result: "attribute namespace는 prefix로 명시해야 합니다." },
          ],
          sourceRefs: ["web-weather-namespace-source", "w3c-namespaces", "python-elementtree"],
        },
      ],
      diagnostics: [
        { symptom: "날씨 XML에서 `findall('.//local')`이 0개인데 화면에는 local tag가 수백 개 보인다.", likelyCause: "default namespace가 모든 unprefixed local element를 `{current}local`로 확장했습니다.", checks: ["root.tag와 첫 descendant.tag repr를 출력합니다.", "root의 xmlns declaration URI를 확인합니다.", "`.//{current}local` 또는 namespace map query count를 비교합니다."], fix: "namespace map을 한 곳에 정의하고 URI/local-name 기반 query로 전환합니다.", prevention: "no-namespace와 default/prefixed 동일-URI fixture를 모두 test합니다." },
        { symptom: "`local.get('{current}ta')`가 None이라 namespace parsing이 실패했다고 생각한다.", likelyCause: "default namespace가 unprefixed attribute에도 적용된다고 잘못 가정했습니다.", checks: ["local.attrib의 실제 key repr를 출력합니다.", "ta source에 prefix가 있는지 봅니다.", "get('ta')와 namespaced get을 비교합니다."], fix: "unprefixed ta는 no-namespace `get('ta')`로 읽고 qualified attribute만 해당 URI expanded name으로 읽습니다.", prevention: "default namespace element/no-namespace attribute 차이를 schema와 code review checklist에 둡니다." },
      ],
    },
    {
      id: "namespace-aware-dom-xpath",
      title: "DOM·ElementTree·XPath는 API 모양이 달라도 expanded name 기준으로 조회합니다",
      lead: "library shorthand를 외우기보다 URI/local name을 어떤 parameter와 resolver에 전달하는지 확인합니다.",
      explanations: [
        "browser DOM의 Element.namespaceURI와 localName은 expanded name의 두 부분을 제공합니다. `getElementsByTagNameNS('current','local')`은 source prefix와 무관합니다. `getAttribute('ta')`와 `getAttributeNS('urn:meta','source')`를 구분합니다.",
        "CSS selector의 namespace syntax는 DOM querySelector에서 namespace resolver를 직접 넘기는 일반 API가 없어 복잡할 수 있습니다. namespace-rich XML은 getElementsByTagNameNS 또는 XPathEvaluator/document.evaluate의 namespace resolver를 사용합니다.",
        "XPath expression의 prefix는 expression lexical shorthand이며 resolver가 URI에 bind합니다. source에서 default namespace였더라도 XPath 1.0에서 unprefixed name test가 그 default namespace를 자동 의미한다고 가정하지 않고 `c:local` 같은 query prefix를 사용합니다.",
        "ElementTree는 `{uri}local` Clark notation과 `namespaces` mapping을 지원합니다. serializer는 입력 prefix를 그대로 보존하지 않고 자동 `ns0`를 만들 수 있으므로 prefix spelling을 snapshot assertion으로 고정하려면 explicit registration과 lexical preservation 요구를 검토합니다.",
        "wildcard `{*}local` 또는 localName-only query는 여러 vocabulary를 의도적으로 합칠 때만 사용합니다. namespace 충돌을 해결하려고 도입한 identity를 무시하면 다른 local element를 잘못 집계할 수 있습니다.",
      ],
      concepts: [
        { term: "namespace resolver", definition: "XPath expression의 prefix를 실제 namespace URI로 바꾸는 callback 또는 mapping입니다.", detail: ["source declaration과 독립적일 수 있습니다.", "unknown prefix를 명시적으로 실패시킵니다."] },
        { term: "Clark notation", definition: "ElementTree가 expanded name을 `{namespaceURI}localName` 문자열로 나타내는 표기입니다.", detail: ["source prefix는 포함하지 않습니다.", "find/tag/attribute key에 사용합니다."] },
        { term: "local-name-only query", definition: "namespace URI를 무시하고 local name만 일치시키는 조회입니다.", detail: ["migration/debug에는 편리할 수 있습니다.", "서로 다른 vocabulary 충돌을 만들 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XPath `//local`은 0개이고 `//*[local-name()='local']`은 나오지만 다른 공급자 노드까지 섞인다.", likelyCause: "default namespace를 query prefix에 bind하지 않았고 임시 local-name workaround가 namespace identity를 버렸습니다.", checks: ["각 result의 namespaceURI를 group합니다.", "XPath resolver와 expression prefix mapping을 기록합니다.", "허용 vocabulary URI 목록을 확인합니다."], fix: "resolver에 `c`→target URI를 bind하고 `//c:local`처럼 exact expanded name을 조회합니다.", prevention: "local-name-only query를 production lint/review에서 제한하고 multi-namespace collision fixture를 둡니다." },
      ],
    },
    {
      id: "empty-missing-whitespace-types",
      title: "빈 요소·빈 문자열·누락·nil과 들여쓰기 whitespace는 서로 다른 상태입니다",
      lead: "UI에서 모두 공백처럼 보여도 update/default/schema 의미는 다를 수 있습니다.",
      explanations: [
        "`<name/>`와 `<name></name>`은 같은 empty element structure를 나타낼 수 있고 ElementTree `.text`는 None일 수 있습니다. `<name>   </name>`은 whitespace character data가 있어 strip 후 empty가 될 뿐 source state는 다릅니다. name element 자체가 없으면 find 결과가 None입니다.",
        "attribute도 missing과 empty를 구분합니다. `get('code')`는 없으면 None, `code=\"\"`이면 empty string입니다. Python의 `or default`는 둘을 합치므로 business 의미가 다르면 `is None`으로 검사합니다.",
        "XML Schema instance의 `xsi:nil=\"true\"`는 namespace-qualified attribute와 schema contract가 있어야 명시적인 nil 의미를 갖습니다. element가 empty라는 이유만으로 null과 같다고 단정하지 않습니다.",
        "원본 weather에는 일부 local에서 ta가 누락되고 rn_hr1/sd_tot도 선택적입니다. 누락을 0으로 바꾸면 '관측 없음'과 실제 0.0을 혼동합니다. domain에서는 Optional decimal과 measurement status/source time을 함께 모델링합니다.",
        "모든 parsed scalar는 schema 없이 string입니다. decimal separator, range, unit, timestamp timezone을 explicit validator로 바꾸고 invalid와 missing을 별도 error/state로 유지합니다.",
      ],
      concepts: [
        { term: "empty element", definition: "child content가 없는 element로 `<x/>` 또는 `<x></x>`로 쓸 수 있습니다.", detail: ["missing element와 다릅니다.", "null 의미는 schema가 정합니다."] },
        { term: "xsi:nil", definition: "XML Schema instance namespace의 nil attribute로 schema가 허용한 element가 값 없음임을 나타냅니다.", detail: ["namespace-qualified attribute입니다.", "empty와 자동 동일하지 않습니다."] },
        { term: "optional measurement", definition: "값이 존재하지 않을 수 있으며 실제 0과 missing을 분리해야 하는 관측 field입니다.", detail: ["Optional type과 quality metadata가 유용합니다.", "default 0은 통계를 왜곡할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "서울 기온 0.0과 ta가 아예 없는 고창이 모두 0으로 표시된다.", likelyCause: "missing attribute None을 `float(value or 0)` 같은 default로 합쳤습니다.", checks: ["raw `attrib` key 존재 여부와 value repr를 기록합니다.", "0.0과 missing fixture를 각각 test합니다.", "domain/UI가 미관측 label을 지원하는지 봅니다."], fix: "missing은 None/미관측 상태로 유지하고 값이 존재할 때만 decimal parse와 range 검사를 수행합니다.", prevention: "missing/empty/zero/invalid numeric 4-state fixture를 schema와 renderer test에 둡니다." },
      ],
    },
    {
      id: "vocabulary-schema-roundtrip-security",
      title: "XML vocabulary는 schema·version·extension·round-trip·security policy까지 하나의 contract로 관리합니다",
      lead: "element/attribute 이름표를 정하는 것만으로는 여러 producer와 장기 호환되는 format이 되지 않습니다.",
      explanations: [
        "vocabulary 문서에는 target namespace, root/child expanded name, order/cardinality, element/attribute 선택, whitespace, datatype/unit, required/optional/default/nil, unknown element/attribute policy를 기록합니다. representative valid/invalid examples를 schema와 함께 version control합니다.",
        "XSD/Relax NG는 구조와 datatype을 검증할 수 있지만 cross-record uniqueness/reference, 관측 시간 관계, business authorization은 application validator로 보완합니다. well-formed→namespace-aware parse→schema→domain invariant 순서를 오류 code로 구분합니다.",
        "extension을 허용한다면 별도 namespace wildcard, must-understand flag 또는 version negotiation을 정합니다. 모르는 namespace를 모두 무시하면 중요한 보안/금액 field를 놓칠 수 있고 모두 reject하면 forward compatibility가 막힐 수 있습니다.",
        "parse→serialize round trip에서 prefix, attribute order, indentation, empty-element spelling, CDATA/comment가 변할 수 있습니다. application semantic equality와 byte/signature equality를 구분하고 signed XML은 표준 canonicalization/signature library를 사용합니다.",
        "untrusted XML에는 DTD/external entity/network access를 비활성화한 parser, raw/decompressed size·depth·node·attribute/text length·time limit을 적용합니다. namespace가 안전성을 보장하지 않으며 URI를 자동 fetch하지 않습니다.",
        "대용량 weather처럼 record가 많으면 full DOM과 namespace query 비용을 측정합니다. streaming iterparse/pull parser를 쓰더라도 root namespace/version을 먼저 검증하고 처리한 element를 clear하며 limit과 transactional output을 유지합니다.",
      ],
      concepts: [
        { term: "XML vocabulary", definition: "특정 namespace의 element/attribute 이름과 구조·의미를 함께 정의한 application language입니다.", detail: ["schema와 prose contract가 필요합니다.", "version/extension 정책을 포함합니다."] },
        { term: "must-understand", definition: "consumer가 알지 못하는 extension을 조용히 무시하지 말고 이해하지 못하면 실패하도록 표시하는 protocol pattern입니다.", detail: ["critical field loss를 막습니다.", "version negotiation과 함께 씁니다."] },
        { term: "semantic round trip", definition: "serialize/reparse 후 prefix나 whitespace 모양이 아니라 expanded name·value·order 등 application meaning이 보존되는지 확인하는 왕복입니다.", detail: ["canonical domain snapshot으로 test할 수 있습니다.", "signature byte equality와 다릅니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XML formatter를 적용한 뒤 digital signature 검증이 실패했다.", likelyCause: "pretty-print/prefix/namespace/whitespace 변화가 signed canonical node set의 bytes를 바꿨습니다.", checks: ["변경 전후 signature/reference/canonicalization algorithm을 확인합니다.", "일반 text diff보다 canonicalized digest를 비교합니다.", "signed subtree를 formatter가 수정했는지 봅니다."], fix: "검증된 XML signature/canonicalization library로 검증·생성하고 signed document를 일반 serializer로 재작성하지 않습니다.", prevention: "signature verify를 모든 transform 전후 release gate로 두고 lexical mutation을 제한합니다." },
      ],
      expertNotes: [
        "namespace URI equality는 문자열 비교 규칙을 따릅니다. application이 임의로 slash·case·percent encoding을 정규화해 같은 namespace로 합치지 않습니다.",
        "XPath query의 편의 때문에 namespace를 제거한 복제 tree를 만들면 identity와 signature/schema 의미가 깨집니다. adapter가 필요한 domain field만 URI-aware하게 추출합니다.",
        "attribute-centric record가 무조건 작거나 빠르다는 주장은 측정 없이 일반화할 수 없습니다. parser representation, compression, schema, query와 update pattern이 실제 비용을 결정합니다.",
      ],
    },
  ],
  lab: {
    title: "세 상품 XML과 기본 namespace 날씨 XML을 하나의 검증된 namespace-aware domain pipeline으로 통합하기",
    scenario: "기존 code는 child/attribute/direct text 모델을 한 query로 처리하고 `find('.//local')`과 `get('{current}ta')`를 사용해 상품/날씨가 누락됩니다. missing 기온은 0으로 바꾸고 prefix spelling을 저장해 공급자 prefix 변경에도 깨집니다.",
    setup: [
      "data01.xml, data02.xml, data03.xml, weather.xml을 read-only fixture로 준비하고 source schema/model을 기록합니다.",
      "Python ElementTree 또는 browser DOM의 namespace-aware API와 test runner를 준비합니다.",
      "default/prefixed 동일 URI, 다른 URI 같은 local name, missing/empty/zero/invalid ta, mixed content와 duplicate child fixture를 추가합니다.",
      "Product{name, price, manufacturer?}와 WeatherStation{id, name, temperature?} domain type·unit·range를 정의합니다.",
    ],
    steps: [
      "네 source의 element/attribute/text/tail와 expanded name을 tree 표로 inventory합니다.",
      "상품 model별 adapter가 cardinality와 required/missing/empty를 검사한 뒤 같은 Product record를 반환하게 합니다.",
      "weather root namespace URI를 허용 version과 비교하고 URI/local-name query로 local을 순회합니다.",
      "unprefixed stn_id/ta를 no-namespace attribute로 읽고 missing·empty·zero·invalid를 분리해 Optional decimal로 normalize합니다.",
      "source prefix를 default/w/wx로 바꾼 equivalent fixture에서 domain snapshot이 같은지 확인합니다.",
      "mixed content는 text/element/tail order를 보존하고 plain-text 전용 path와 rich-node path를 분리합니다.",
      "schema/cardinality/unknown extension, DTD/entity disable, byte/depth/node/time limit과 sanitized error를 적용합니다.",
      "serialize/reparse 후 expanded name·record order·value semantic diff를 실행하고 lexical prefix/order 변화는 별도 보고합니다.",
    ],
    expectedResult: [
      "세 상품 표현이 하나의 typed Product model로 통합되고 원본별 adapter 차이가 문서화됩니다.",
      "weather의 default namespace element와 no-namespace attribute가 정확히 조회되고 missing temperature가 0과 구분됩니다.",
      "prefix spelling을 바꿔도 동일 URI document의 domain output이 유지되고 다른 URI collision은 섞이지 않습니다.",
      "mixed content의 word/inline order와 spaces가 보존되며 plain text 변환의 손실이 명시됩니다.",
      "unsafe/oversized/invalid/schema-mismatch XML이 단계별 오류로 reject되고 actual value/secret/private path가 log에 노출되지 않습니다.",
    ],
    cleanup: ["생성한 prefix/invalid/large synthetic fixture와 output을 test directory 밖에서 제거합니다.", "parser network/DTD option과 환경 limit이 production profile과 동일한지 다시 확인합니다."],
    extensions: ["XSD 또는 Relax NG로 상품·날씨 subset schema를 만들고 positive/negative corpus를 검증합니다.", "ElementTree iterparse와 DOM full-tree의 memory/latency를 동일 record 수로 비교합니다.", "namespace version N/N+1 dual-reader와 unknown extension must-understand migration test를 설계합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 상품 세 파일에서 첫 상품을 읽어 element/attribute/direct-text 위치와 runtime type을 출력하세요.", requirements: ["child count와 attrib key를 출력합니다.", "missing과 empty를 구분합니다.", "price string을 검증 후 integer로 변환합니다.", "정확한 output과 tree 그림을 작성합니다."], hints: ["findtext와 get은 서로 다른 위치를 봅니다.", "direct text에 indentation이 있는지 repr로 확인합니다."], expectedOutcome: "세 표현 방식의 parser 위치를 설명하고 같은 Product record로 normalize합니다.", solutionOutline: ["source model별 adapter를 분리합니다.", "cardinality/type validation 뒤 domain constructor를 호출합니다."] },
    { difficulty: "응용", prompt: "weather.xml에서 서울과 ta가 누락된 지역을 namespace-aware하게 찾아 표로 만드세요.", requirements: ["root namespace URI를 검증합니다.", "source prefix와 무관한 URI/local query를 사용합니다.", "stn_id/ta가 no-namespace attribute임을 test합니다.", "missing·empty·0.0·invalid를 구분합니다.", "prefix/default equivalent fixture를 추가합니다."], hints: ["ElementTree tag repr를 먼저 출력합니다.", "default namespace는 unprefixed attribute에 적용되지 않습니다."], expectedOutcome: "지역/기온이 정확히 추출되고 관측 없음과 실제 0이 다른 state로 표시됩니다.", solutionOutline: ["namespace map→record loop→attribute presence→decimal validator 순서로 만듭니다.", "동일 URI의 query prefix는 application이 자유롭게 선택합니다."] },
    { difficulty: "설계", prompt: "다국어 상품 설명과 외부 확장을 지원하는 XML vocabulary v2를 설계하세요.", requirements: ["target/extension namespace와 version policy를 정의합니다.", "element/attribute/mixed content 선택을 field별로 근거화합니다.", "cardinality·order·empty/missing/nil·whitespace·type/unit을 명시합니다.", "unknown/must-understand와 N/N+1 compatibility를 설계합니다.", "schema+application invariant, signature/round-trip, XXE/resource limit test를 포함합니다."], hints: ["prefix spelling을 contract identity로 두지 않습니다.", "사람이 읽는 rich text와 machine record field를 분리할 수 있습니다."], expectedOutcome: "여러 producer가 같은 expanded-name와 data semantics를 만들고 안전하게 진화할 수 있는 구현 가능한 vocabulary specification이 완성됩니다.", solutionOutline: ["domain field matrix를 먼저 만들고 namespace/schema로 옮깁니다.", "positive/negative/equivalent-prefix/migration fixture를 함께 제공합니다."] },
  ],
  reviewQuestions: [
    { question: "XML attribute는 child node인가요?", answer: "아닙니다. element에 연결된 별도 name/value 정보이며 child sequence에 포함되지 않습니다." },
    { question: "attribute price=\"100\"은 parser에서 자동 integer인가요?", answer: "schema-aware typed layer가 없다면 일반 parser API에서는 문자열이며 명시적 validation/normalization이 필요합니다." },
    { question: "반복 가능한 값을 같은 이름 attribute 여러 개로 표현할 수 있나요?", answer: "아닙니다. 같은 element에서 같은 expanded-name attribute는 중복될 수 없으므로 반복 child 등을 사용합니다." },
    { question: "mixed content에서 child 뒤의 text는 ElementTree 어디에 있나요?", answer: "그 child의 `.tail`에 있습니다. parent.text와 각 child.text/tail을 순서대로 봐야 합니다." },
    { question: "namespace prefix가 다르면 다른 XML 이름인가요?", answer: "반드시 그렇지 않습니다. namespace URI와 local name pair가 같으면 expanded name은 같습니다." },
    { question: "namespace URI는 반드시 접속 가능한 web URL인가요?", answer: "아닙니다. namespace identity URI이며 dereference 가능성이 equality 조건은 아닙니다." },
    { question: "default namespace는 접두사 없는 attribute에도 적용되나요?", answer: "아닙니다. 접두사 없는 attribute는 no-namespace이며 attribute를 namespace에 넣으려면 prefix가 필요합니다." },
    { question: "ElementTree에서 default namespace local을 `find('local')`로 찾을 수 있나요?", answer: "대상 tag는 `{URI}local`이므로 Clark notation 또는 namespace map이 필요합니다." },
    { question: "빈 요소와 누락 요소는 같은가요?", answer: "아닙니다. element 존재 여부와 content empty는 다른 상태이며 nil 의미도 schema가 별도로 정합니다." },
    { question: "prefix와 attribute 순서가 serialize 후 바뀌면 의미가 항상 바뀐 건가요?", answer: "아닙니다. expanded name/value semantic은 같을 수 있습니다. 하지만 lexical/signature 요구는 별도 canonicalization으로 확인합니다." },
  ],
  completionChecklist: [
    "세 상품 원본의 element·attribute·direct text 구조와 parser 위치를 모두 설명했다.",
    "반복·순서·확장·rich content·metadata 근거로 element/attribute를 선택했다.",
    "mixed content의 parent.text·child.text·child.tail order와 whitespace를 검증했다.",
    "prefix·namespace URI·local name·expanded name을 구분하고 URI identity로 query했다.",
    "default namespace가 element에는 적용되고 unprefixed attribute에는 적용되지 않음을 exact output으로 확인했다.",
    "DOM/ElementTree/XPath의 namespace map/resolver를 source prefix와 분리했다.",
    "missing·empty·zero·invalid·xsi:nil 상태와 scalar string→typed value 경계를 정의했다.",
    "schema/cardinality/version/unknown extension/must-understand policy를 작성했다.",
    "semantic round trip과 lexical/signature equality를 구분했다.",
    "DTD/entity/network 비활성화와 byte/depth/node/time limit을 적용했다.",
  ],
  nextSessions: ["xml-03-browser-parse-render"],
  sources: [
    { id: "web-xml-elements-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data01.xml", usedFor: ["product child elements", "name/price text", "repeated product", "indentation/comment"], evidence: "products 아래 네 product가 name/price child element를 갖는 전체 구조를 element-centered record와 cardinality의 실제 근거로 사용했습니다." },
    { id: "web-xml-attributes-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data02.xml", usedFor: ["empty product element", "name/price attributes", "attribute uniqueness", "model comparison"], evidence: "self-closing product와 name/price attribute 네 건을 element/attribute adapter와 empty-element 비교에 반영했습니다." },
    { id: "web-xml-mixed-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data03.xml", usedFor: ["name/price attributes", "manufacturer direct text", "mixed model trade-off", "extension analysis"], evidence: "product attribute와 현대/기아/BMW/아우디 제조사 direct text의 결합을 field naming·확장성·normalization 사례로 사용했습니다." },
    { id: "web-weather-namespace-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/weather.xml", usedFor: ["default namespace current", "weather/local hierarchy", "no-namespace attributes", "optional ta/rn_hr1/sd_tot", "large record set"], evidence: "`xmlns=\"current\"` root와 year/month/day/hour, 수백 local의 stn_id/icon/desc/ta 및 선택적 강수·적설 attribute를 namespace·missing·streaming 실습의 실제 근거로 사용했습니다." },
    { id: "w3c-xml", repository: "W3C XML Core Working Group", path: "TR/xml/", publicUrl: "https://www.w3.org/TR/xml/", usedFor: ["element/attribute/content", "mixed content", "attribute uniqueness", "empty element", "validity"], evidence: "XML 1.0 Fifth Edition의 element/content/attribute well-formedness와 validity를 modeling 경계의 표준 기준으로 사용했습니다." },
    { id: "w3c-namespaces", repository: "W3C XML Core Working Group", path: "TR/xml-names/", publicUrl: "https://www.w3.org/TR/xml-names/", usedFor: ["namespace name", "prefix declaration/scope", "expanded name", "default namespace", "attribute rule", "reserved prefix"], evidence: "Namespaces in XML 1.0의 URI/local identity와 default namespace가 unprefixed attribute에 적용되지 않는 규칙을 핵심 query 기준으로 사용했습니다." },
    { id: "xml-infoset", repository: "W3C", path: "TR/xml-infoset/", publicUrl: "https://www.w3.org/TR/xml-infoset/", usedFor: ["element/attribute information item", "namespace properties", "character information", "lexical/semantic distinction"], evidence: "parser가 제공하는 logical information과 source lexical spelling을 분리해 round-trip/canonicalization 설명에 반영했습니다." },
    { id: "python-elementtree", repository: "Python Software Foundation", path: "library/xml.etree.elementtree.html", publicUrl: "https://docs.python.org/3/library/xml.etree.elementtree.html", usedFor: ["Element.text/tail", "find/findall", "Clark notation", "namespace mapping", "itertext", "serialization"], evidence: "세 Python exact-output 예제와 namespace-aware adapter API를 Python 공식 문서 및 현재 runtime 실행으로 검증했습니다." },
    { id: "whatwg-dom", repository: "WHATWG", path: "DOM Standard", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["namespaceURI/localName", "getElementsByTagNameNS", "getAttributeNS", "Text node", "DOM rendering boundary"], evidence: "browser XML DOM에서 expanded name과 character node를 조회하는 API 기준으로 사용했습니다." },
    { id: "xpath-31", repository: "W3C", path: "TR/xpath-31/", publicUrl: "https://www.w3.org/TR/xpath-31/", usedFor: ["expanded QName", "namespace resolver", "path selection", "local-name limitation"], evidence: "XPath의 static namespace context와 expanded QName 기준을 prefix-independent query 설명에 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 4,
    filesUsed: 4,
    uncoveredNotes: [
      "원본 네 파일은 요소형·속성형·direct-text 상품과 실제 default namespace/optional weather attribute를 모두 제공합니다. prefixed namespace·mixed inline markup·xsi:nil·schema/signature는 공식 XML/Namespaces/Infoset/DOM 자료로 보강했습니다.",
      "원본에는 XSD/Relax NG와 명시적 application version이 없습니다. 이 세션은 well-formed XML을 넘어 modeling contract를 설계하되 실제 schema artifact 작성과 browser fetch/render는 각각 후속 xml-03/데이터 검증 실습으로 연결합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 380;
expertSession.chapters.push(
  {
    id: "namespace-dom-xpath-prefix-independent-contract",
    title: "expanded name을 기준으로 DOM·XPath query를 prefix와 분리합니다",
    lead: "XML 이름의 identity는 prefix 철자가 아니라 namespace URI와 local name의 쌍입니다. default namespace와 unprefixed attribute 규칙을 DOM과 XPath에서 정확히 재현합니다.",
    explanations: [
      "QName은 source에서 `prefix:local`처럼 보이지만 namespace-aware processor는 prefix declaration을 따라 namespace name과 local part의 expanded name으로 해석합니다. 서로 다른 prefix가 같은 URI에 bound되면 같은 vocabulary name이고, 같은 prefix라도 다른 URI에 bound되면 다른 name입니다.",
      "default namespace declaration은 prefix 없는 element names에 적용되지만 prefix 없는 attribute names에는 적용되지 않습니다. `<product xmlns='urn:catalog' id='p1'>`에서 product는 `{urn:catalog}product`, id는 `{null}id`입니다. attribute를 element namespace로 getAttributeNS하면 null이 되어 missing과 혼동할 수 있습니다.",
      "namespace declaration은 일반 업무 attribute처럼 다루지 않습니다. DOM에서는 namespaceURI/localName/prefix와 getAttributeNS를 사용하고, serializer가 선택한 prefix 철자를 domain key로 저장하지 않습니다. `xmlns` attributes를 문자열 순회해 직접 namespace context를 재구현하지 않습니다.",
      "DOMParser XML mode에서 정상 Document를 얻은 뒤 documentElement의 namespaceURI/localName을 먼저 gate합니다. expected vocabulary/version이 아니면 `getElementsByTagName('product')`가 우연히 결과를 반환해도 처리하지 않습니다. wildcard namespace는 migration tool처럼 목적이 명확한 경우에만 사용합니다.",
      "getElementsByTagNameNS(namespaceURI, localName)는 prefix 변경과 무관한 live collection을 반환할 수 있습니다. querySelector는 CSS namespace resolver를 JavaScript에서 간단히 제공하지 않으므로 namespaced XML data extraction에는 namespace-aware DOM API나 XPath resolver가 더 명시적입니다.",
      "XPath에서 unprefixed element test는 source document의 default namespace를 자동 의미하지 않습니다. expression에 code-owned prefix를 쓰고 resolver가 그 prefix를 expected URI에 map하도록 합니다. document source의 prefix 철자와 XPath prefix는 같을 필요가 없습니다.",
      "XPath expression에 사용자 입력을 문자열 보간하면 query 문법·탐색 범위를 제어하게 할 수 있습니다. expression은 fixed allowlist로 두고 사용자 검색어는 추출된 validated text에 JavaScript로 적용하거나 variable binding을 지원하는 검토된 engine을 사용합니다.",
      "XPathResult NUMBER_TYPE, STRING_TYPE, FIRST_ORDERED_NODE_TYPE, ORDERED_NODE_SNAPSHOT_TYPE 등 기대 result type을 고정합니다. iterator는 tree mutation으로 invalidation될 수 있고 snapshot은 생성 시점 목록이므로 UI update 중 어떤 consistency가 필요한지 정합니다.",
      "mixed content에서는 element.textContent가 inline descendant text를 합치지만 원래 element/text 순서와 markup 의미를 잃을 수 있습니다. 문서형 content를 domain scalar로 납작하게 만들지 말고 node walk 또는 vocabulary-specific renderer를 사용하며 external text는 HTML에 textContent로 넣습니다.",
      "test matrix는 default/prefixed/alias prefix, undeclared prefix, wrong namespace, unprefixed/namespaced attribute, empty namespace, XPath empty result와 fixed query를 포함합니다. DevTools에서 XML Document의 namespaceURI/localName과 XPath count를 기록하고 source prefix spelling만 비교하는 assertion을 금지합니다.",
    ],
    concepts: [
      { term: "expanded name", definition: "namespace name과 local name의 ordered pair로 XML element/attribute identity를 나타냅니다.", detail: ["prefix 철자와 분리됩니다.", "Clark notation은 교육·도구 표현일 뿐 XML source 문법은 아닙니다."] },
      { term: "namespace resolver", definition: "XPath expression 안 prefix를 expected namespace URI에 연결하는 함수 또는 mapping입니다.", detail: ["document의 실제 prefix와 달라도 됩니다.", "고정 expression과 allowlisted URI를 사용합니다."] },
      { term: "no-namespace attribute", definition: "default namespace가 선언된 element 위에서도 prefix 없는 attribute가 갖는 null namespace identity입니다.", detail: ["getAttribute('id') 또는 getAttributeNS(null,'id')로 읽습니다.", "element namespace를 자동 상속하지 않습니다."] },
    ],
    codeExamples: [
      {
        id: "browser-namespace-dom-xpath",
        title: "default namespace·namespaced attribute·XPath resolver를 함께 검증",
        language: "html",
        filename: "xml-namespace-xpath.html",
        purpose: "DOMParser로 namespace XML을 읽고 expanded name, unprefixed/namespaced attributes와 fixed XPath count를 prefix-independent exact output으로 확인합니다.",
        code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>XML namespace XPath</title></head>\n<body>\n  <pre id=\"out\" aria-live=\"polite\"></pre>\n  <script>\n    const CATALOG = 'urn:catalog:v2';\n    const META = 'urn:meta:v1';\n    const source = `<catalog xmlns=\"${CATALOG}\" xmlns:m=\"${META}\">\n      <product id=\"p1\" m:status=\"active\">키보드</product>\n      <product id=\"p2\" m:status=\"paused\">마우스</product>\n    </catalog>`;\n    const documentNode = new DOMParser().parseFromString(source, 'application/xml');\n    if (documentNode.getElementsByTagNameNS('*', 'parsererror').length) throw new Error('PARSE_ERROR');\n\n    const root = documentNode.documentElement;\n    const products = documentNode.getElementsByTagNameNS(CATALOG, 'product');\n    const first = products[0];\n    const count = documentNode.evaluate(\n      'count(/c:catalog/c:product)',\n      documentNode,\n      (prefix) => ({ c: CATALOG, m: META })[prefix] ?? null,\n      XPathResult.NUMBER_TYPE,\n    ).numberValue;\n    const lines = [\n      `root={${root.namespaceURI}}${root.localName}`,\n      `products=${count}`,\n      `first-id=${first.getAttributeNS(null, 'id')}`,\n      `status=${first.getAttributeNS(META, 'status')}`,\n      `id-no-namespace=${first.getAttributeNode('id').namespaceURI === null}`,\n    ];\n    document.querySelector('#out').textContent = lines.join('\\n');\n    console.log(lines.join('\\n'));\n  </script>\n</body>\n</html>",
        walkthrough: [
          { lines: "1-5", explanation: "browser shell과 결과 status를 준비합니다." },
          { lines: "6-13", explanation: "default element namespace와 prefixed metadata namespace를 가진 두 product XML string을 만듭니다." },
          { lines: "14-15", explanation: "XML mode로 parse하고 parsererror를 namespace-independent하게 거부합니다." },
          { lines: "17-26", explanation: "root와 products를 namespace-aware DOM으로 읽고 fixed XPath prefix를 expected URI에 resolve해 count합니다." },
          { lines: "27-36", explanation: "expanded root, count, no-namespace id, namespaced status와 attribute namespace invariant를 화면·Console에 기록합니다." },
          { lines: "34-36", explanation: "script와 document를 닫고 DevTools에서 namespace properties와 keyboard 접근을 확인합니다." },
        ],
        run: { environment: ["최신 Chromium 또는 Firefox", "xml-namespace-xpath.html을 UTF-8로 저장", "DevTools Console·Elements·Accessibility", "keyboard로 결과 영역 탐색"], command: "브라우저에서 xml-namespace-xpath.html을 열고 pre·Console exact 출력과 namespaceURI/localName을 확인" },
        output: { value: "root={urn:catalog:v2}catalog\nproducts=2\nfirst-id=p1\nstatus=active\nid-no-namespace=true", explanation: ["default namespace element는 URI와 local name 쌍으로 식별됩니다.", "XPath의 c prefix는 resolver가 expected URI에 연결해 두 product를 셉니다.", "prefix 없는 id는 null namespace이고 m:status만 metadata namespace에 속합니다."] },
        experiments: [
          { change: "source의 m prefix를 meta로 바꾸되 같은 URI를 유지합니다.", prediction: "DOM getAttributeNS와 XPath 결과는 그대로입니다.", result: "prefix 철자와 expanded name identity를 분리합니다." },
          { change: "XPath를 count(/catalog/product)로 바꾸고 resolver를 제거합니다.", prediction: "default namespace elements가 no-namespace test와 일치하지 않아 0이 됩니다.", result: "XPath가 source default namespace를 자동 상속하지 않음을 확인합니다." },
          { change: "사용자 검색어를 XPath string에 이어 붙이는 대신 products를 추출한 뒤 textContent를 비교합니다.", prediction: "XPath metacharacter가 query grammar를 바꾸지 않습니다.", result: "fixed query와 untrusted data 경계를 유지합니다." },
        ],
        sourceRefs: ["web-weather-namespace-source", "w3c-namespaces", "xml-infoset", "whatwg-dom", "xpath-31"],
      },
    ],
    diagnostics: [
      { symptom: "default namespace XML에서 XPath `//product`가 빈 결과를 반환한다.", likelyCause: "XPath의 unprefixed name test가 document의 default namespace를 자동 사용한다고 가정했습니다.", checks: ["root.namespaceURI/localName을 출력합니다.", "expression prefix와 resolver mapping을 확인합니다.", "DOM getElementsByTagNameNS 결과와 비교합니다."], fix: "code-owned XPath prefix를 expected namespace URI에 resolve하고 `//c:product`처럼 fixed expression을 사용합니다.", prevention: "default/prefixed/alias prefix fixtures에서 같은 expanded-name result를 검증합니다." },
      { symptom: "product의 id를 getAttributeNS(catalogUri, 'id')로 읽으면 null이다.", likelyCause: "default namespace가 prefix 없는 attribute에도 적용된다고 오해했습니다.", checks: ["getAttributeNode('id').namespaceURI를 확인합니다.", "prefixed m:status와 unprefixed id를 비교합니다.", "namespace declaration과 normal attributes를 구분합니다."], fix: "prefix 없는 id는 getAttribute('id') 또는 getAttributeNS(null,'id')로 읽고 실제 namespaced attribute만 해당 URI로 조회합니다.", prevention: "element/attribute expanded-name matrix를 vocabulary contract에 포함합니다." },
    ],
    expertNotes: ["XPath prefix는 expression 내부의 임시 이름입니다. source 문서와 철자가 같아야 한다는 convention을 identity 규칙으로 오해하지 않습니다.", "querySelector로 XML namespace를 다루는 browser별 CSS namespace 제약보다 namespace-aware DOM/XPath API를 우선 검토합니다."],
  },
  {
    id: "versioned-vocabulary-schema-canonical-streaming",
    title: "versioned vocabulary를 schema·domain validation·canonicalization·streaming 정책으로 운영합니다",
    lead: "요소냐 속성이냐를 선택한 뒤에도 version evolution, missing/empty/null, schema dialect, canonical bytes와 대용량 처리 계약을 명시해야 장기 호환되는 XML이 됩니다.",
    explanations: [
      "vocabulary는 namespace URI, root local name, version, allowed children/attributes와 semantics를 함께 정의합니다. namespace URI를 반드시 fetch 가능한 schema URL로 만들 필요는 없지만 안정적이고 조직이 소유하는 identifier로 관리합니다. version을 namespace에 넣을지 별도 attribute로 둘지 migration 정책과 함께 정합니다.",
      "element와 attribute 선택은 style이 아니라 information model입니다. 반복·순서·mixed content·확장 가능성이 있으면 element가 자연스럽고 compact metadata와 identity는 attribute가 유리할 수 있습니다. attribute에는 child structure가 없고 같은 expanded name을 한 element에 중복할 수 없습니다.",
      "missing, empty string, whitespace-only, explicit nil은 다른 상태가 될 수 있습니다. XSI nil을 사용한다면 schema와 nillable contract가 필요하고, 단지 빈 tag를 nil로 간주하지 않습니다. domain adapter는 raw presence와 normalized value를 분리해 silent default로 data quality error를 숨기지 않습니다.",
      "XSD, Relax NG, Schematron과 application validation은 해결하는 문제와 표현력이 다릅니다. parser의 well-formedness 뒤 pinned local schema로 구조/type를 검사하고, cross-record uniqueness·authorization·업무 규칙은 application layer에서 확인합니다. untrusted schemaLocation을 network fetch하지 않습니다.",
      "schema version evolution은 optional additive field만 보고 끝나지 않습니다. enum 확장, numeric unit, timezone, default 의미, namespace 변경, ordering과 unknown element policy를 consumer capability와 연결합니다. tolerant reader도 unknown security-sensitive field를 무조건 무시하면 안 됩니다.",
      "round trip은 parse→domain→serialize 뒤 semantic value가 보존되는지 보는 것이지 source bytes·prefix·attribute order·quote style가 같은 것을 의미하지 않습니다. comments, CDATA boundary, entity spelling과 insignificant whitespace가 사라질 수 있으므로 lexical preservation이 필요한 문서 편집기는 일반 data binding과 다른 model을 사용합니다.",
      "digital signature와 hash는 semantic equivalence만으로 bytes가 같아지지 않아 canonicalization 규칙과 transform chain이 필요합니다. 직접 attribute sort나 whitespace 제거로 canonical XML을 흉내 내지 말고 검토된 C14N implementation, algorithm allowlist, wrapping attack 방어와 signed node identity를 사용합니다.",
      "streaming parser는 element start/end와 namespace scope event를 전달합니다. ancestor namespace context, mixed text/tail, record boundary와 root-level invariants를 state machine으로 관리하고, 한 record를 내보내기 전 required fields와 limits를 검증합니다. late document error에서 commit/rollback 정책도 필요합니다.",
      "serialization은 element/attribute text를 XML serializer에 맡겨 `& < > \" '` escaping과 legal character rules를 적용합니다. string interpolation로 markup을 조립하지 않고 DOM/ElementTree builder를 사용합니다. external URI와 schema reference는 allowlist하고 output encoding declaration과 실제 writer encoding을 일치시킵니다.",
      "contract tests는 alias prefix semantic equality, wrong namespace/version, unknown field, missing/empty/nil, duplicate ID, reordered children, mixed content, round-trip loss, schema offline, streaming truncation과 canonical signature fixture를 포함합니다. raw XML 전체를 snapshot 하나로 비교하지 말고 domain invariants와 필요한 lexical invariants를 분리합니다.",
    ],
    concepts: [
      { term: "vocabulary version", definition: "namespace·root·version marker와 element/attribute semantics의 호환성 단위를 나타냅니다.", detail: ["consumer migration 정책과 함께 관리합니다.", "schema URL과 namespace identity는 같은 개념이 아닙니다."] },
      { term: "semantic round trip", definition: "parse와 serialization을 거친 뒤 application 의미가 보존되는지 확인하는 성질입니다.", detail: ["prefix·quote·attribute order bytes는 달라질 수 있습니다.", "lexical preservation 요구는 별도 model이 필요합니다."] },
      { term: "canonicalization", definition: "signature/hash처럼 byte-level 비교가 필요한 경우 정의된 XML node-set을 표준 형태로 serialize하는 과정입니다.", detail: ["임의 whitespace 제거와 다릅니다.", "검토된 C14N implementation을 사용합니다."] },
    ],
    codeExamples: [
      {
        id: "expanded-name-domain-validation",
        title: "prefix와 분리한 expanded-name domain validator",
        language: "javascript",
        filename: "expanded-name-validator.mjs",
        purpose: "parser가 추출했다고 가정한 raw node의 namespace/local/attributes를 versioned vocabulary로 검증하고 prefix alias가 domain identity를 바꾸지 않음을 exact 확인합니다.",
        code: "const VOCABULARY = { namespaceURI: 'urn:catalog:v2', localName: 'product' };\n\nfunction expandedName(node) {\n  return `{${node.namespaceURI}}${node.localName}`;\n}\n\nfunction validateProduct(node) {\n  if (node.namespaceURI !== VOCABULARY.namespaceURI || node.localName !== VOCABULARY.localName) {\n    throw new TypeError('VOCABULARY_ERROR');\n  }\n  const id = node.attributes.get('id');\n  const rawPrice = node.attributes.get('price');\n  const price = Number(rawPrice);\n  if (!id || rawPrice === undefined || rawPrice.trim() === '' || !Number.isSafeInteger(price) || price < 0) throw new TypeError('SCHEMA_ERROR');\n  return { id, price };\n}\n\nconst first = { prefix: 'p', namespaceURI: 'urn:catalog:v2', localName: 'product', attributes: new Map([['id', 'p1'], ['price', '12000']]) };\nconst alias = { ...first, prefix: 'catalog' };\nconst product = validateProduct(first);\nconsole.log(`expanded=${expandedName(first)}`);\nconsole.log(`prefix-independent=${expandedName(first) === expandedName(alias)}`);\nconsole.log(`id=${product.id}, price=${product.price}`);\nconsole.log(`missing-category=${first.attributes.get('category') === undefined}`);",
        walkthrough: [
          { lines: "1-5", explanation: "versioned vocabulary의 expected namespace/local과 교육용 Clark notation helper를 정의합니다." },
          { lines: "7-16", explanation: "expanded name을 먼저 검사한 뒤 no-namespace attributes의 presence·empty와 safe integer domain rule을 검증합니다." },
          { lines: "18-20", explanation: "같은 URI/local에 서로 다른 prefix를 가진 raw node와 validated domain record를 만듭니다." },
          { lines: "21-24", explanation: "expanded identity, prefix alias equality, typed domain value와 missing attribute를 exact 출력합니다." },
        ],
        run: { environment: ["Node.js 20 이상", "expanded-name-validator.mjs를 UTF-8로 저장"], command: "node expanded-name-validator.mjs" },
        output: { value: "expanded={urn:catalog:v2}product\nprefix-independent=true\nid=p1, price=12000\nmissing-category=true", explanation: ["domain identity는 prefix가 아니라 URI/local pair입니다.", "문자열 price는 validation boundary에서 safe integer로 변환됩니다.", "누락 attribute는 빈 문자열과 구분되는 undefined로 관찰됩니다."] },
        experiments: [
          { change: "alias.namespaceURI를 urn:catalog:v1로 바꿉니다.", prediction: "expanded names가 달라지고 validator는 VOCABULARY_ERROR를 냅니다.", result: "같은 local/prefix 모양이 namespace version identity를 대신하지 않습니다." },
          { change: "price를 빈 문자열로 바꿉니다.", prediction: "raw empty guard가 Number 변환의 0 coercion 전에 SCHEMA_ERROR를 냅니다.", result: "conversion 전에 missing/empty lexical policy를 검사해 silent data loss를 막습니다." },
          { change: "raw node를 XML로 직접 string interpolation하지 않고 DOM/ElementTree serializer로 serialize합니다.", prediction: "특수문자 escaping과 namespace declarations를 library가 처리합니다.", result: "domain validation과 safe serialization을 별도 경계로 유지합니다." },
        ],
        sourceRefs: ["web-xml-elements-source", "web-xml-attributes-source", "w3c-xml", "w3c-namespaces", "xml-infoset", "python-elementtree"],
      },
    ],
    diagnostics: [
      { symptom: "XML round trip 뒤 signature가 깨졌지만 domain 값은 모두 같다.", likelyCause: "semantic round trip과 prefix·attribute order·whitespace까지 포함한 canonical bytes를 같은 것으로 간주했습니다.", checks: ["serialize 전후 expanded names/domain values와 raw bytes를 따로 비교합니다.", "사용한 canonicalization/transform algorithm을 확인합니다.", "signed node selection과 wrapping 가능성을 검토합니다."], fix: "signature에는 표준 C14N과 검토된 XML signature library를 사용하고 일반 serializer 결과의 byte equality를 기대하지 않습니다.", prevention: "known signature vectors와 namespace/attribute-order/wrapping regression fixtures를 둡니다." },
      { symptom: "streaming import가 끝에서 malformed XML을 발견했지만 앞 record들은 이미 DB에 저장됐다.", likelyCause: "document-level validity와 transaction commit boundary를 설계하지 않았습니다.", checks: ["record emit/DB commit 시점과 root end 확인 시점을 추적합니다.", "late schema/duplicate ID error rollback 범위를 봅니다.", "staging table 또는 batch transaction 사용을 확인합니다."], fix: "전체-document invariant가 필요하면 staging/transaction에서 최종 root 검증 뒤 commit하고 record-independent protocol만 조기 commit합니다.", prevention: "truncated tail·late duplicate·wrong closing root fixture로 rollback을 검증합니다." },
    ],
    expertNotes: ["Node 예제는 parser가 제공한 namespace-aware raw node 이후의 domain boundary를 보여 줍니다. XML source를 정규식이나 문자열 split으로 parser처럼 처리하지 않습니다.", "canonicalization과 XML Signature는 별도 보안 전문 영역입니다. 직접 구현하지 말고 알고리즘 downgrade, key trust, wrapping 공격까지 검토된 library/profile을 사용합니다."],
  },
);

expertSession.reviewQuestions.push(
  { question: "서로 다른 prefix가 같은 namespace URI와 local name을 가리키면 다른 요소인가요?", answer: "아닙니다. expanded name이 같으므로 같은 vocabulary name이며 prefix는 lexical alias입니다." },
  { question: "default namespace가 prefix 없는 attribute에도 적용되나요?", answer: "아닙니다. prefix 없는 attribute는 null namespace이고 prefix가 있는 attribute만 해당 namespace URI를 가집니다." },
  { question: "XPath의 `//product`가 source default namespace의 product를 찾나요?", answer: "일반적으로 아닙니다. expression prefix를 resolver로 expected namespace URI에 연결해야 합니다." },
  { question: "schema validation이 업무 규칙과 authorization까지 보장하나요?", answer: "아닙니다. 구조/type validation 뒤에도 uniqueness, cross-record rule, 권한과 외부 reference 정책을 application이 검증해야 합니다." },
  { question: "parse→serialize 뒤 prefix와 attribute order가 달라지면 semantic data가 손상된 건가요?", answer: "반드시 그렇지 않습니다. expanded names와 domain values가 같을 수 있으며 byte equality가 필요하면 표준 canonicalization을 별도로 사용합니다." },
);
expertSession.completionChecklist.push(
  "element/attribute identity를 namespace URI+local name으로 저장하고 prefix 철자와 분리했다.",
  "default namespace element와 no-namespace attribute를 DOM·XPath fixture로 검증했다.",
  "XPath expression·resolver·result type을 고정하고 사용자 입력을 query code에 보간하지 않았다.",
  "missing·empty·nil·typed conversion과 unknown field/version evolution 정책을 문서화했다.",
  "well-formedness·schema·domain validation·authorization을 독립 gate로 구현했다.",
  "round-trip semantic invariants와 canonical bytes/signature 요구를 분리하고 streaming rollback을 검증했다.",
);
