import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["xml-04-json-yaml-format-choice"],
  slug: "xml-04-json-yaml-format-choice",
  courseId: "web",
  moduleId: "03-xml-data-formats",
  order: 4,
  title: "XML·JSON·YAML을 비교하고 손실 없이 데이터 형식 선택하기",
  subtitle: "괄호와 들여쓰기만 비교하지 않고 각 형식의 데이터 모델·스키마·파서·보안·변환 손실을 분석한 뒤, 경계에서 정규화하고 검증하는 설계 기준을 세웁니다.",
  level: "고급",
  estimatedMinutes: 260,
  coreQuestion: "문서·API·설정 데이터를 XML, JSON, YAML 중 어디에 표현해야 하며, 서로 변환할 때 의미와 형식 정보가 사라지지 않도록 어떤 중간 모델·스키마·보안 경계를 두어야 할까요?",
  summary: "학습 원본의 상품 XML, 과목 점수 JSON, 다섯 팀 YAML을 같은 domain model 관점에서 읽습니다. XML의 ordered tree·attribute·namespace·mixed content, JSON의 object/array와 제한된 scalar, YAML의 사람이 편집하기 좋은 block syntax·comment·anchor·tag를 구분합니다. RFC 8259의 unique-name 권고와 number interoperability, YAML 1.2 schema·implicit typing·duplicate key 문제, XML infoset과 serializer 차이를 검증합니다. parse→strict duplicate 검사→normalization→schema/application validation→domain object→serialization pipeline을 실행하고, XXE/entity expansion·unsafe YAML tag/object construction·resource exhaustion·prototype pollution·secret commit 위험을 format 자체와 application 사용법으로 분리합니다. 마지막에는 API·configuration·document-centric content·signed payload·streaming·human editing 요구를 근거로 형식을 결정하고, 맹목적 text-to-text 변환 대신 보존해야 할 의미를 명시하는 migration 절차를 완성합니다.",
  objectives: [
    "XML·JSON·YAML의 syntax와 data model을 분리해 같은 정보가 각 형식에서 어떻게 표현되는지 설명할 수 있다.",
    "중복 이름·숫자 정밀도·null/missing·순서·namespace·comment·anchor처럼 형식별 경계 조건을 예측할 수 있다.",
    "PyYAML SafeLoader와 strict duplicate detection, secure XML parser setting, input size/depth 제한의 책임을 구분할 수 있다.",
    "원본 document를 normalized domain model로 옮기고 schema와 application invariant를 검증한 뒤 다시 직렬화할 수 있다.",
    "API, 사람이 편집하는 설정, 문서 중심 markup, 서명·canonicalization 요구에 맞춰 형식을 선택하고 근거를 기록할 수 있다.",
    "변환 시 손실될 comment·prefix·attribute/order·scalar style·anchor/alias·type 정보를 사전에 inventory하고 migration test를 설계할 수 있다.",
  ],
  prerequisites: [
    { title: "XML을 브라우저에서 파싱·탐색·렌더링하기", reason: "XML syntax parse와 application shape validation, 안전한 data rendering을 이미 분리한 상태에서 JSON/YAML까지 같은 ingestion pipeline으로 확장합니다.", sessionSlug: "xml-03-browser-parse-render" },
  ],
  keywords: ["XML", "JSON", "YAML", "data model", "serialization", "normalization", "RFC 8259", "YAML 1.2", "duplicate key", "JSON Schema", "XSD", "SafeLoader", "XXE", "canonicalization", "configuration", "round trip"],
  chapters: [
    {
      id: "syntax-model-contract",
      title: "형식 선택은 문장 부호 취향이 아니라 syntax·data model·schema·운영 contract의 선택입니다",
      lead: "같은 '팀 목록'도 원문 모양을 보존할 문서인지, typed application record인지, 사람이 자주 편집하는 설정인지에 따라 정답이 달라집니다.",
      explanations: [
        "syntax는 byte/text가 어떤 token과 구분자로 구성되는지를 말합니다. XML의 start/end tag, JSON의 brace/bracket, YAML의 indentation과 dash가 이 층입니다. syntax가 valid하다는 것은 application에 필요한 field·type·range·관계까지 맞다는 뜻이 아닙니다.",
        "data model은 parser가 문서를 어떤 node/value로 이해하는지입니다. XML은 element·attribute·namespace·text/comment/processing instruction가 document order로 놓인 tree입니다. JSON은 object·array·string·number·boolean·null value입니다. YAML representation graph는 mapping·sequence·scalar node와 tag·anchor/alias를 표현할 수 있어 단순 JSON tree보다 넓습니다.",
        "schema는 허용되는 구조와 type을 별도 언어 또는 application code로 정의합니다. XSD나 Relax NG는 XML, JSON Schema는 JSON instance를 검증합니다. YAML은 흔히 safe parse한 native data를 JSON Schema 또는 application-specific validator에 맞추지만 YAML tag와 mapping key type처럼 JSON model 밖의 기능을 먼저 제한해야 합니다.",
        "operational contract에는 누가 편집하는지, diff/review가 쉬워야 하는지, streaming이 필요한지, ecosystem/library가 무엇인지, backward compatibility와 versioning을 어떻게 할지, signature/canonicalization이 필요한지, untrusted input인지가 포함됩니다. 파일 크기 하나만으로 결정하지 않습니다.",
        "원본 상품 XML은 product의 name/price를 attribute, 제조사를 element text에 넣었습니다. 점수 JSON은 count가 number처럼 보여도 따옴표가 있어 string입니다. 팀 YAML은 members를 sequence로 표현하고 Jaguars에는 coach가 없습니다. parser 성공 뒤 domain rule을 적용해야 이 차이를 의도한 type과 optional field로 바꿀 수 있습니다.",
      ],
      concepts: [
        { term: "serialization format", definition: "memory의 value·object·document structure를 저장·전송 가능한 byte/text 표현으로 바꾸고 되돌리기 위한 규약입니다.", detail: ["표현 가능한 model과 interoperability가 다릅니다.", "parser 성공과 domain validity는 별도입니다."] },
        { term: "domain model", definition: "특정 파일 형식의 node가 아니라 application이 실제로 사용하는 Product·Team·Score 같은 의미 중심 type입니다.", detail: ["format adapter 뒤에 둡니다.", "schema와 business invariant의 기준이 됩니다."] },
        { term: "round trip", definition: "parse한 뒤 다시 serialize했을 때 의미 또는 원문 표현이 얼마나 보존되는지를 보는 왕복 과정입니다.", detail: ["semantic round trip과 lexical round trip은 다릅니다.", "comment/style/order/prefix가 사라질 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "JSON→YAML→JSON 변환은 성공했는데 배포 설정의 의미가 바뀌었다.", likelyCause: "syntax parse 성공만 확인하고 implicit scalar type, duplicate key, anchor merge, missing/null의 domain 의미를 검증하지 않았습니다.", checks: ["각 parser가 만든 native type과 key set을 출력합니다.", "중복 key·unknown key·missing/null fixture를 넣습니다.", "변환 전후 domain model을 canonical JSON으로 비교합니다."], fix: "각 형식을 strict하게 parse한 뒤 allowlisted normalized domain model과 schema를 검증하고 그 model에서 target을 serialize합니다.", prevention: "형식별 golden fixture와 semantic equivalence test를 versioned contract에 둡니다." },
      ],
    },
    {
      id: "xml-document-model",
      title: "XML은 namespace와 mixed content를 포함한 순서 있는 문서 tree를 표현하는 데 강합니다",
      lead: "XML을 'tag가 많은 JSON'으로 축소하면 attribute·text·namespace·order의 의미와 signature/canonicalization 요구를 놓칩니다.",
      explanations: [
        "XML element는 expanded name(namespace URI와 local name), zero or more attributes, ordered child nodes를 가집니다. attribute는 element child가 아니며 XML 정보 모델에서 attribute 순서는 application 의미로 기대하면 안 됩니다. serializer는 attribute/prefix 표기를 바꿀 수 있습니다.",
        "문서 중심 content에서는 `<p>안녕 <em>중요</em>합니다</p>`처럼 text와 child element가 섞인 mixed content의 order가 핵심입니다. JSON object/array로 옮기려면 text segment와 element를 explicit tagged sequence로 표현해야 하므로 단순 key/value 변환은 손실됩니다.",
        "namespace는 여러 vocabulary를 한 document에 결합하고 expanded name 충돌을 피합니다. prefix spelling은 별칭일 뿐 URI가 identity입니다. XML을 JSON으로 변환할 때 prefix만 key로 복사하거나 default namespace를 버리면 서로 다른 element를 합칠 수 있습니다.",
        "XML declaration·DOCTYPE·entity·CDATA·comment·processing instruction은 모두 같은 방식으로 application data가 아닙니다. 일반 tree parser가 무엇을 보존하는지 확인해야 하며 CDATA와 escaped text는 parse 후 동일한 character data로 합쳐질 수 있습니다.",
        "XSD는 element/attribute structure와 datatype, occurrence 등을 기술할 수 있지만 well-formedness와 validity는 별도 단계입니다. schema version과 namespace version을 contract로 관리하고, schema만으로 표현하기 어려운 cross-record business rule은 application validation으로 보완합니다.",
        "signed XML이나 protocol interop에서는 단순 pretty-print도 signature를 깨뜨릴 수 있습니다. canonical XML·signature library와 정확한 node set 규칙을 사용하며 직접 string sort/replace로 canonicalization을 흉내 내지 않습니다.",
      ],
      concepts: [
        { term: "mixed content", definition: "한 element의 child sequence에 text node와 element node가 함께 나타나는 XML content model입니다.", detail: ["문서 markup에 자연스럽습니다.", "순서를 보존한 변환이 필요합니다."] },
        { term: "XML infoset", definition: "XML document가 application에 제공하는 정보 항목을 기술하는 추상 정보 model입니다.", detail: ["lexical spelling 전체와 같지 않습니다.", "attribute order 같은 표면 표현을 의미로 삼지 않습니다."] },
        { term: "canonicalization", definition: "동일한 XML 정보에 안정적인 byte representation을 부여해 digest/signature 비교에 사용하는 표준화 절차입니다.", detail: ["일반 serializer와 다릅니다.", "namespace와 whitespace context가 중요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XML을 읽어 다시 저장했더니 prefix·attribute 순서·CDATA 모양이 달라져 text diff가 커졌다.", likelyCause: "semantic XML tree를 보존하는 parser/serializer에 lexical round trip까지 기대했습니다.", checks: ["consumer가 실제로 semantic equivalence와 byte identity 중 무엇을 요구하는지 확인합니다.", "comment/PI/CDATA/prefix/whitespace 보존 여부를 library별로 test합니다.", "signature가 있다면 canonicalization과 verification을 먼저 실행합니다."], fix: "편집 목적이면 lossless XML library/CST를 선택하고, data 처리 목적이면 canonical semantic comparison을 사용하며 signed document는 전용 signature workflow를 따릅니다.", prevention: "보존 요구를 항목별로 명시하고 golden byte/semantic/signature test를 각각 둡니다." },
      ],
    },
    {
      id: "json-rfc-model",
      title: "JSON은 API와 language 간 교환에 작은 공통 value model을 제공하지만 key·number 경계를 명시해야 합니다",
      lead: "JSON.parse가 성공했다는 사실만으로 object key가 유일하거나 모든 숫자가 모든 runtime에서 정확하다는 뜻은 아닙니다.",
      explanations: [
        "RFC 8259의 JSON value는 object, array, number, string, true, false, null 중 하나이며 top-level도 어떤 JSON value든 될 수 있습니다. 오래된 consumer와의 interoperability를 넓히려면 top-level object/array를 택하는 경우가 많지만 grammar 자체의 필수 조건은 아닙니다.",
        "object member name은 string이고 RFC는 한 object 안의 이름이 unique해야 predictable interoperability를 얻는다고 설명합니다. 중복 이름을 받은 library는 마지막 값을 남기거나 첫 값을 남기거나 모든 pair를 보고할 수 있습니다. security/config boundary에서는 parser hook이나 streaming layer로 명시적으로 reject합니다.",
        "JSON number grammar에는 integer와 fraction/exponent가 있지만 int/float이라는 별도 JSON type은 없습니다. consumer가 IEEE 754 binary64 number를 쓰면 매우 큰 integer가 정확히 표현되지 않을 수 있습니다. 식별자·계좌번호·64-bit 범위 값은 string contract 또는 범위가 명확한 schema를 고려합니다.",
        "원본 `count`는 `\"95\"`라 JSON string입니다. 화면에서 숫자처럼 보인다는 이유로 암묵 coercion에 맡기지 않고 decimal grammar·범위·leading zero policy를 검사해 integer로 normalize합니다. missing member와 explicit null도 다른 business state일 수 있습니다.",
        "JSON에는 표준 comment syntax가 없습니다. 설정 설명이 필요하다면 문서·schema description·별도 metadata field를 사용하거나 애초에 YAML/JSONC 같은 별도 format contract를 명시합니다. JSON parser가 우연히 comment를 허용한다고 표준 JSON endpoint에 의존하지 않습니다.",
        "network interoperability에서는 UTF-8을 사용하고 Content-Type·size/depth·schema version을 명시합니다. object member order에 business semantics를 두지 말고 의미 있는 순서는 array로 표현합니다.",
      ],
      concepts: [
        { term: "JSON object", definition: "string member name과 JSON value의 pair를 중괄호로 표현한 unordered collection입니다.", detail: ["unique name을 요구하는 contract가 안전합니다.", "의미 순서는 array로 표현합니다."] },
        { term: "interoperable integer", definition: "서로 다른 JSON 구현이 같은 수를 정확히 해석할 수 있도록 합의한 안전 범위의 integer입니다.", detail: ["binary64 기반 runtime을 고려합니다.", "범위 밖 ID는 string이 더 적합할 수 있습니다."] },
        { term: "missing versus null", definition: "member 자체가 없는 상태와 member가 존재하며 JSON null인 상태의 구분입니다.", detail: ["PATCH/default semantics가 다릅니다.", "schema와 application rule에 기록합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "backend가 보낸 큰 주문 ID 끝자리가 browser에서 바뀌었다.", likelyCause: "큰 integer를 JSON number로 보내고 JavaScript binary64 Number로 parse해 안전 정수 범위를 넘었습니다.", checks: ["원문 token과 parse 후 Number.isSafeInteger를 비교합니다.", "schema의 maximum과 producer integer 범위를 확인합니다.", "ID에 산술 연산이 실제 필요한지 확인합니다."], fix: "식별자는 string으로 계약하고 양쪽 schema/code generation을 갱신하며 이미 손상된 값을 재직렬화하지 않습니다.", prevention: "경계값과 2^53 전후의 cross-language contract test를 둡니다." },
      ],
    },
    {
      id: "yaml-human-configuration",
      title: "YAML은 사람이 편집하는 계층형 설정에 편리하지만 schema·tag·alias와 parser option을 고정해야 합니다",
      lead: "들여쓰기가 읽기 쉽다는 장점은 implicit typing과 확장 기능을 아무 제한 없이 받아도 된다는 뜻이 아닙니다.",
      explanations: [
        "YAML은 block mapping/sequence와 flow style를 제공하고 comment를 쓸 수 있습니다. 원본 팀 파일의 `team`, `manager`, optional `coach`, `members` sequence는 사람이 읽고 수정하기 쉬운 전형적인 configuration/data 모양입니다.",
        "scalar의 실제 type은 tag와 active schema가 정합니다. YAML 1.1에서 boolean처럼 해석되던 일부 단어와 YAML 1.2 core/JSON schema의 해석이 다를 수 있습니다. library version과 loader/schema mode를 고정하고 date·boolean·null·숫자처럼 보이는 경계값 fixture를 test합니다.",
        "anchor와 alias는 같은 node를 재사용하고 mapping merge를 구현하는 데 쓰이지만, parse 후 일반 dict/list나 JSON으로 serialize하면 anchor spelling과 sharing identity가 사라질 수 있습니다. alias가 매우 많이 확장되는 input은 CPU/memory 제한도 필요합니다.",
        "tag는 scalar/collection의 type을 나타냅니다. language-specific object constructor를 허용하는 unsafe loader는 untrusted YAML에서 임의 object construction이나 code execution 위험을 만들 수 있습니다. PyYAML에서는 `safe_load`/SafeLoader를 기본으로 하고 필요한 custom tag도 allowlist constructor로 제한합니다.",
        "duplicate mapping key를 library가 자동으로 모두 거부한다고 가정하지 않습니다. strict loader constructor나 schema validation 전 pair-aware parser를 사용해 중복을 오류로 만들고, merge key 적용 뒤 충돌 policy도 문서화합니다.",
        "YAML 1.2는 JSON과의 호환성을 목표로 하고 JSON syntax는 일반적으로 YAML 1.2 processor에서 받아들일 수 있지만, 실제 library의 schema/options·duplicate 처리·extension 차이까지 '항상 완전히 같은 의미'로 단정하면 안 됩니다. target parser matrix를 test합니다.",
      ],
      concepts: [
        { term: "implicit tag resolution", definition: "명시적 tag가 없는 scalar의 철자와 active schema를 보고 string·integer·boolean·null 같은 tag를 선택하는 과정입니다.", detail: ["version/schema에 따라 달라질 수 있습니다.", "quote 여부가 결과에 영향을 줄 수 있습니다."] },
        { term: "anchor and alias", definition: "YAML graph에서 node에 이름을 붙이고 다른 위치가 같은 node를 참조하는 기능입니다.", detail: ["중복 설정을 줄일 수 있습니다.", "JSON 변환에서 identity/style이 손실될 수 있습니다."] },
        { term: "safe loader", definition: "임의 language object 생성 tag를 제한하고 기본 scalar/collection 중심으로 YAML을 구성하는 loader mode입니다.", detail: ["schema validation을 대신하지 않습니다.", "size/depth/duplicate 제한도 별도입니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "YAML의 `on`, 날짜, 앞자리 0 숫자가 환경마다 boolean/date/integer/string으로 다르게 읽힌다.", likelyCause: "YAML version·schema·library loader의 implicit resolution 차이를 contract에 고정하지 않았습니다.", checks: ["library/version/loader와 active resolver를 기록합니다.", "문제 scalar를 type과 repr로 출력합니다.", "quoted/unquoted fixture와 YAML 1.1/1.2 behavior를 비교합니다."], fix: "schema mode를 고정하고 ambiguity가 있는 식별자는 quote하며 parse 후 explicit type validation/normalization을 수행합니다.", prevention: "type-sensitive scalar corpus를 모든 supported runtime에서 contract test합니다." },
      ],
    },
    {
      id: "normalize-three-formats",
      title: "형식 adapter는 XML·JSON·YAML node를 하나의 명시적인 domain model로 정규화합니다",
      lead: "원본 표현을 UI나 business code에 그대로 퍼뜨리지 않고, 경계에서 type·optional field·이름을 확정합니다.",
      explanations: [
        "상품 XML의 attribute price와 점수 JSON의 quoted count는 parser 직후 모두 string입니다. domain에서 산술이 필요하다면 decimal syntax와 range를 검사한 뒤 integer로 바꿉니다. 무조건 `int`를 호출해 예외 message를 그대로 노출하지 않고 field path가 있는 validation error를 만듭니다.",
        "YAML의 members는 sequence이므로 `list[str]`로 확인하고, 없는 coach는 missing optional field로 유지할지 explicit null/default로 만들지 정책을 정합니다. missing을 빈 문자열로 즉시 합치면 '모름'과 '없음'의 구분을 잃습니다.",
        "normalized model은 serializer에 독립적인 Product{name, price, maker}, Score{name, count}, Team{name, manager, coach?, members[]}가 됩니다. 이후 UI·database·API code는 XML Element, raw dict, YAML node에 의존하지 않습니다.",
        "canonical JSON 출력은 사람이 편집할 target format을 정하는 것이 아니라 semantic comparison을 위한 test representation입니다. key를 sort하고 whitespace를 고정해 diff noise를 줄이되 array order처럼 의미 있는 순서는 유지합니다.",
        "normalization 전에 syntax/duplicate/size를, normalization 중 type/range/required field를, 이후 cross-record uniqueness/reference invariant를 검사합니다. 오류 층을 나누면 잘못된 원본과 migration code bug를 구분할 수 있습니다.",
      ],
      concepts: [
        { term: "format adapter", definition: "특정 parser의 node/value를 domain type으로 바꾸고 format-specific 오류를 경계에서 처리하는 구성 요소입니다.", detail: ["business code의 parser 결합을 줄입니다.", "형식별 fixture test가 가능합니다."] },
        { term: "normalization", definition: "여러 허용 표현을 한 이름·type·단위·missing policy의 canonical domain representation으로 바꾸는 과정입니다.", detail: ["validation과 함께 설계합니다.", "원본 provenance를 필요에 따라 보존합니다."] },
        { term: "semantic equivalence", definition: "text 모양이 달라도 application이 관찰하는 domain meaning이 같은 관계입니다.", detail: ["canonical model로 비교할 수 있습니다.", "lexical identity와 다릅니다."] },
      ],
      codeExamples: [
        {
          id: "normalize-xml-json-yaml",
          title: "세 형식을 읽어 type이 고정된 하나의 canonical model로 만들기",
          language: "python",
          filename: "normalize_formats.py",
          purpose: "XML attribute, JSON quoted number, YAML sequence가 parser 직후 어떤 type이고 domain normalization 뒤 어떻게 통일되는지 exact output으로 확인합니다.",
          code: "import json\nfrom xml.etree import ElementTree as ET\nimport yaml\n\nxml_text = \"\"\"<products>\n  <product name=\"제너시스\" price=\"100\">현대자동차</product>\n  <product name=\"K9\" price=\"90\">기아자동차</product>\n</products>\"\"\"\njson_text = '[{\"name\":\"HTML\",\"count\":\"95\"},{\"name\":\"CSS\",\"count\":\"90\"}]'\nyaml_text = \"\"\"team: Tigers\nmanager: Kenneth\nmembers:\n  - Linda\n  - William\n\"\"\"\n\nraw_scores = json.loads(json_text)\nmodel = {\n    \"products\": [\n        {\n            \"maker\": item.text.strip(),\n            \"name\": item.attrib[\"name\"],\n            \"price\": int(item.attrib[\"price\"]),\n        }\n        for item in ET.fromstring(xml_text).findall(\"product\")\n    ],\n    \"scores\": [\n        {\"count\": int(item[\"count\"]), \"name\": item[\"name\"]}\n        for item in raw_scores\n    ],\n    \"team\": yaml.safe_load(yaml_text),\n}\nprint(json.dumps(model, ensure_ascii=False, sort_keys=True, separators=(\",\", \":\")))\nprint(\n    \"types=\"\n    f\"price:{type(model['products'][0]['price']).__name__},\"\n    f\"count-source:{type(raw_scores[0]['count']).__name__},\"\n    f\"count-normalized:{type(model['scores'][0]['count']).__name__},\"\n    f\"members:{type(model['team']['members']).__name__}\"\n)",
          walkthrough: [
            { lines: "1-3", explanation: "표준 library로 JSON/XML을, SafeLoader 기반 PyYAML로 YAML을 읽습니다." },
            { lines: "5-15", explanation: "학습 원본의 상품·점수·팀 구조를 축소한 deterministic fixture를 선언합니다." },
            { lines: "17-30", explanation: "format-specific node/dict에서 domain key를 만들고 price/count를 명시적으로 integer로 normalize합니다." },
            { lines: "31-39", explanation: "sort/compact JSON으로 semantic model과 source/normalized runtime type을 출력합니다." },
          ],
          run: { environment: ["Python 3.11+", "PyYAML 6.x (`python -m pip install PyYAML==6.0.2`)"], command: "python normalize_formats.py" },
          output: { value: "{\"products\":[{\"maker\":\"현대자동차\",\"name\":\"제너시스\",\"price\":100},{\"maker\":\"기아자동차\",\"name\":\"K9\",\"price\":90}],\"scores\":[{\"count\":95,\"name\":\"HTML\"},{\"count\":90,\"name\":\"CSS\"}],\"team\":{\"manager\":\"Kenneth\",\"members\":[\"Linda\",\"William\"],\"team\":\"Tigers\"}}\ntypes=price:int,count-source:str,count-normalized:int,members:list", explanation: ["XML attribute와 JSON count source는 string이지만 domain price/count는 int입니다.", "YAML sequence는 list가 되고 member order가 유지됩니다.", "canonical JSON은 비교용이며 XML attribute/maker text라는 원래 표현 방식까지 보존하지는 않습니다."] },
          experiments: [
            { change: "JSON count를 `\"95점\"`으로 바꿉니다.", prediction: "int conversion에서 ValueError가 발생합니다.", result: "production adapter에서는 field path와 허용 grammar를 가진 validation error로 변환합니다." },
            { change: "YAML members를 `Linda` 단일 scalar로 바꿉니다.", prediction: "safe_load는 성공하지만 domain의 list[str] contract에는 실패해야 합니다.", result: "syntax parse와 shape/type validation은 별도 단계입니다." },
            { change: "XML product의 maker 안에 child element를 넣습니다.", prediction: "item.text만 읽으면 mixed content 일부만 얻습니다.", result: "document-centric XML은 단순 record adapter와 다른 content model을 요구합니다." },
          ],
          sourceRefs: ["web-product-xml-source", "web-score-json-source", "git-tigers-yaml-source", "rfc8259-json", "yaml-122", "python-xml-security", "pyyaml-docs"],
        },
      ],
      diagnostics: [
        { symptom: "세 parser 모두 성공했지만 합쳐진 화면에서 count 정렬이 100, 20, 9 순서로 이상하다.", likelyCause: "quoted JSON count와 XML attribute price를 string 상태로 domain에 전달해 lexical comparison을 했습니다.", checks: ["raw/normalized type을 field별로 출력합니다.", "schema가 integer인지 string인지 확인합니다.", "invalid/overflow/leading zero fixture를 넣습니다."], fix: "경계 adapter에서 검증 후 integer/decimal domain type으로 변환하고 UI/database가 그 type만 받게 합니다.", prevention: "canonical model type assertion과 numeric boundary property test를 둡니다." },
      ],
    },
    {
      id: "duplicate-and-type-strictness",
      title: "중복 key·attribute와 type ambiguity는 parser 기본값에 맡기지 않고 strict ingestion policy로 거부합니다",
      lead: "같은 input을 consumer마다 다르게 해석하는 순간 보안 정책과 배포 설정은 예측할 수 없게 됩니다.",
      explanations: [
        "JSON object duplicate name은 syntax parser가 받아들일 수 있어도 consumer behavior가 갈릴 수 있습니다. Python `json.loads`의 object_pairs_hook처럼 원 pair 순서를 볼 수 있는 지점에서 첫 duplicate를 발견하면 reject합니다. parse 후 dict만 보면 이미 어느 값이 사라졌을 수 있습니다.",
        "YAML mapping duplicate도 SafeLoader라는 이름만으로 자동 reject된다고 가정하지 않습니다. mapping constructor가 pairs를 순회하며 중복을 확인하도록 만들거나 duplicate rejection이 보장된 parser option/library를 사용합니다. merge key를 허용한다면 flatten/merge 후 collision policy도 test합니다.",
        "XML에서 한 start tag에 같은 expanded-name attribute를 두 번 쓰는 것은 well-formedness 오류이므로 conforming parser가 reject합니다. 하지만 반복 child element는 합법이므로 schema의 maxOccurs나 application uniqueness rule로 검사해야 합니다.",
        "strictness는 '모든 편의를 금지'가 아니라 producer/consumer가 하나의 의미에 합의하게 하는 것입니다. unknown key reject/ignore/collect, case sensitivity, coercion, default, null policy를 endpoint/config version별로 기록합니다.",
        "오류 message는 format·location/path·category를 제공하되 secret value나 전체 document를 log하지 않습니다. configuration CI에서는 line/column을 보여 주고 service runtime에서는 sanitized error code와 source version을 남깁니다.",
      ],
      concepts: [
        { term: "duplicate-key ambiguity", definition: "같은 mapping/object 이름이 여러 번 나타나 consumer별로 어느 값을 선택할지 달라지는 interoperability 문제입니다.", detail: ["authorization/config에서 위험합니다.", "pair-aware 단계에서 reject합니다."] },
        { term: "strict ingestion", definition: "허용 grammar·key·type·size와 중복 처리 policy를 명시하고 모호한 input을 경계에서 거부하는 방식입니다.", detail: ["parser default보다 contract가 우선입니다.", "versioning과 error reporting이 필요합니다."] },
        { term: "coercion", definition: "string `95`를 integer 95처럼 한 type을 다른 type으로 암묵 또는 명시 변환하는 동작입니다.", detail: ["편리하지만 오류를 숨길 수 있습니다.", "허용 규칙과 범위를 제한합니다."] },
      ],
      codeExamples: [
        {
          id: "reject-duplicate-members",
          title: "JSON·YAML 중복 key와 XML 중복 attribute를 모두 명시적으로 거부하기",
          language: "python",
          filename: "strict_duplicates.py",
          purpose: "세 parser가 서로 다른 기본 경로로 모호한 이름을 다루더라도 application 결과는 하나의 reject policy가 되게 합니다.",
          code: "import json\nfrom xml.etree import ElementTree as ET\nimport yaml\n\ndef reject_json_pairs(pairs):\n    result = {}\n    for key, value in pairs:\n        if key in result:\n            raise ValueError(f\"duplicate key: {key}\")\n        result[key] = value\n    return result\n\nclass StrictSafeLoader(yaml.SafeLoader):\n    pass\n\ndef construct_unique_mapping(loader, node, deep=False):\n    loader.flatten_mapping(node)\n    result = {}\n    for key, value in loader.construct_pairs(node, deep=deep):\n        if key in result:\n            raise ValueError(f\"duplicate key: {key}\")\n        result[key] = value\n    return result\n\nStrictSafeLoader.add_constructor(\n    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,\n    construct_unique_mapping,\n)\n\ncases = [\n    (\"json\", lambda: json.loads('{\"mode\":\"dev\",\"mode\":\"prod\"}', object_pairs_hook=reject_json_pairs)),\n    (\"yaml\", lambda: yaml.load(\"mode: dev\\nmode: prod\\n\", Loader=StrictSafeLoader)),\n    (\"xml\", lambda: ET.fromstring('<config mode=\"dev\" mode=\"prod\"/>')),\n]\nfor name, load in cases:\n    try:\n        load()\n        print(f\"{name}=accepted\")\n    except Exception as error:\n        print(f\"{name}=rejected:{type(error).__name__}\")",
          walkthrough: [
            { lines: "5-11", explanation: "JSON pair hook이 dict를 만들기 전에 같은 member name을 확인합니다." },
            { lines: "13-27", explanation: "SafeLoader를 subclass하고 mapping constructor만 unique-key version으로 교체합니다." },
            { lines: "29-33", explanation: "같은 mode 이름 또는 attribute가 두 번 나타나는 세 fixture를 구성합니다." },
            { lines: "34-39", explanation: "library별 상세 message 대신 reject 여부와 exception type의 stable output을 기록합니다." },
          ],
          run: { environment: ["Python 3.11+", "PyYAML 6.x"], command: "python strict_duplicates.py" },
          output: { value: "json=rejected:ValueError\nyaml=rejected:ValueError\nxml=rejected:ParseError", explanation: ["JSON과 YAML은 application strict hook이 duplicate를 ValueError로 막습니다.", "XML 중복 attribute는 well-formedness ParseError입니다.", "반복 XML child는 이 예와 달리 합법일 수 있으므로 schema/cardinality 검사가 추가로 필요합니다."] },
          experiments: [
            { change: "세 fixture에서 두 번째 mode를 제거합니다.", prediction: "모두 accepted가 출력됩니다.", result: "unique 이름은 syntax/strict layer를 통과하고 이후 allowlist/type validation으로 갑니다." },
            { change: "JSON hook과 YAML custom loader를 기본 parser로 바꿉니다.", prediction: "runtime에 따라 마지막 값이 남아 accepted될 수 있습니다.", result: "보안 정책을 parser의 암묵 default에 맡기지 않습니다." },
            { change: "XML을 `<config><mode>dev</mode><mode>prod</mode></config>`로 바꿉니다.", prediction: "well-formed parse는 accepted입니다.", result: "element occurrence/cardinality는 XSD/application schema가 검사합니다." },
          ],
          sourceRefs: ["rfc8259-json", "yaml-122", "xml-10e", "pyyaml-docs"],
        },
      ],
      diagnostics: [
        { symptom: "보안 검사기는 첫 `role:user`를 봤지만 application은 뒤의 `role:admin`을 적용했다.", likelyCause: "producer·validator·consumer가 duplicate member를 서로 다르게 처리했습니다.", checks: ["raw pair token을 보존해 duplicate를 찾습니다.", "각 component parser/version/default를 비교합니다.", "signed/validated bytes와 consumed bytes가 동일한지 확인합니다."], fix: "모든 trust boundary에서 duplicate를 parsing 초기에 reject하고 동일한 canonical schema/parser profile을 공유합니다.", prevention: "duplicate·case variant·Unicode-confusable key adversarial fixture를 전체 pipeline test에 둡니다." },
      ],
    },
    {
      id: "schema-validation-evolution",
      title: "schema는 구조를, application validator는 환경·관계·운영 invariant를 검증합니다",
      lead: "문법과 schema만 통과한 데이터도 존재하지 않는 참조·위험한 경로·과도한 worker 수를 가질 수 있습니다.",
      explanations: [
        "XML XSD는 element/attribute 이름, simple datatype, sequence/choice, occurrence 등을 표현할 수 있습니다. JSON Schema Draft 2020-12는 object property, required, unevaluated properties, array, numeric/string constraint와 schema composition/reference를 제공합니다. target validator가 지원하는 dialect를 `$schema`와 toolchain에 고정합니다.",
        "YAML configuration은 safe parse 후 key가 string인 JSON-compatible subset으로 normalize하면 JSON Schema를 재사용할 수 있습니다. custom tag·non-string mapping key·timestamp object를 그대로 두면 JSON instance model과 맞지 않으므로 parse profile에서 금지하거나 adapter가 명시적으로 바꿉니다.",
        "schema가 `workers`를 integer 1..16으로 제한해도 production에서 특정 plan은 8 이하라는 정책이나 feature 간 상호 배타성, file path sandbox, database reference 존재 여부는 application validator가 담당할 수 있습니다.",
        "version evolution에서는 새 optional field 추가, unknown field policy, enum 확장, required field migration을 producer/consumer 배포 순서와 함께 설계합니다. 무조건 unknown reject가 rolling upgrade를 막을 수 있고 무조건 ignore는 typo를 숨길 수 있어 extension namespace/explicit version 같은 계약이 필요합니다.",
        "validation error는 JSON Pointer, XPath/expanded name, YAML source location처럼 사용자가 고칠 위치를 제공하고 expected/actual type을 표시합니다. secret value는 redaction하고 한 문서에서 오류를 너무 많이 수집해 resource exhaustion이 되지 않게 cap을 둡니다.",
      ],
      concepts: [
        { term: "schema dialect", definition: "schema keyword와 evaluation semantics의 특정 버전/규격입니다.", detail: ["JSON Schema Draft 2020-12 같은 식별자가 있습니다.", "validator 지원 여부를 고정합니다."] },
        { term: "structural validation", definition: "field·element의 존재, type, cardinality와 local constraint가 schema에 맞는지 검사합니다.", detail: ["syntax parse 다음 단계입니다.", "business invariant와 구분합니다."] },
        { term: "compatibility policy", definition: "old/new producer와 consumer가 field 추가·삭제·type 변경을 어느 범위에서 함께 처리할지 정한 규칙입니다.", detail: ["배포 순서를 포함합니다.", "unknown/default/version 정책이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "로컬 validator는 통과하지만 CI의 JSON Schema validator에서 `$dynamicRef`나 unevaluatedProperties 결과가 다르다.", likelyCause: "서로 다른 JSON Schema dialect 또는 부분 지원 validator를 사용했습니다.", checks: ["root `$schema` URI와 validator/version을 기록합니다.", "지원 keyword warning을 확인합니다.", "official test suite의 관련 case를 실행합니다."], fix: "한 dialect와 validator compatibility matrix를 고정하고 unsupported keyword를 build failure로 처리하거나 지원되는 표현으로 재설계합니다.", prevention: "schema lint와 positive/negative contract fixture를 동일 toolchain으로 CI에 둡니다." },
      ],
    },
    {
      id: "secure-resource-bounded-parsing",
      title: "안전한 파싱은 code 실행 방지뿐 아니라 입력 크기·깊이·확장·비밀값까지 제한합니다",
      lead: "trusted repository 설정과 internet upload는 같은 parser API를 쓸 수 있어도 threat model과 허용 기능이 같지 않습니다.",
      explanations: [
        "XML의 external entity/DTD 처리 기능은 local file 또는 network resource를 읽게 만들 수 있고 entity expansion은 CPU/memory를 소모할 수 있습니다. 사용 library의 secure-by-default 여부를 version별로 확인하고 untrusted data에는 DTD/external entity/network access를 disable한 hardened parser를 사용합니다. Python 표준 XML 문서의 vulnerability 표와 실제 deployment parser를 대조합니다.",
        "YAML에서는 arbitrary object constructor를 제공하는 loader를 untrusted input에 쓰지 않습니다. SafeLoader를 기본으로 하되 alias count/depth/document size, duplicate key, permitted tags/scalar types를 추가 제한합니다. safe라는 이름은 business schema나 denial-of-service 한계까지 자동 보장한다는 뜻이 아닙니다.",
        "JSON.parse 자체는 code를 실행하지 않지만 매우 큰/deep input은 memory/stack/latency 문제를 만들 수 있습니다. parse한 object를 unsafe deep merge하며 `__proto__` 같은 key를 특별 취급하는 application/library에서는 prototype pollution이 생길 수 있으므로 dangerous key denylist만이 아니라 safe object creation·allowlisted schema·patched merge library를 사용합니다.",
        "모든 format에서 compressed upload의 decompressed size, raw byte size, nesting depth, collection count, string length, schema error count, parse timeout을 ingress 전에/중에 제한합니다. streaming parser도 unlimited state accumulation을 하면 안전하지 않습니다.",
        "API token·database password를 YAML/JSON/XML repository에 literal로 commit하지 않습니다. 설정에는 environment variable 또는 secret-manager reference만 두고 startup에서 존재 여부와 scope를 검사합니다. example secret도 실제처럼 보이는 값 대신 명백한 placeholder를 쓰며 output/log에는 value를 출력하지 않습니다.",
        "serialization도 injection 경계입니다. XML에는 escaping을 parser/serializer에 맡기고 JSON/YAML을 shell command·HTML·SQL에 concatenate하지 않습니다. data format parse는 target context encoding/parameterization을 대신하지 않습니다.",
      ],
      concepts: [
        { term: "XXE", definition: "XML parser가 external entity를 해석하며 file/network resource에 접근하도록 악용하는 취약성 부류입니다.", detail: ["DTD/entity 기능과 관련됩니다.", "parser configuration과 network isolation이 필요합니다."] },
        { term: "resource exhaustion", definition: "큰 입력·깊은 중첩·alias/entity 확장 등으로 CPU·memory·stack·network 자원을 과도하게 쓰게 하는 공격/고장입니다.", detail: ["모든 format에 존재합니다.", "다층 limit가 필요합니다."] },
        { term: "secret reference", definition: "설정 파일에 secret value 대신 environment/secret manager에서 값을 찾을 이름 또는 identifier만 저장하는 방식입니다.", detail: ["value를 source control에서 분리합니다.", "로그에는 reference와 존재 여부만 남깁니다."] },
      ],
      codeExamples: [
        {
          id: "safe-config-boundary",
          title: "YAML 설정을 safe parse하고 allowlist·type·range·secret reference를 검증하기",
          language: "python",
          filename: "validate_config.py",
          purpose: "SafeLoader만 호출하고 끝내지 않고 unknown key와 type/range를 검사하며 secret value를 문서나 출력에 노출하지 않는 boundary를 만듭니다.",
          code: "import os\nimport yaml\n\nsource = \"\"\"mode: production\nworkers: 4\nfeatures:\n  - search\n  - export\nsecret_env: APP_TOKEN\n\"\"\"\nos.environ[\"APP_TOKEN\"] = \"demo-value-not-printed\"\nconfig = yaml.safe_load(source)\nallowed = {\"mode\", \"workers\", \"features\", \"secret_env\"}\nunknown = set(config) - allowed\nif unknown:\n    raise ValueError(f\"unknown keys: {sorted(unknown)}\")\nif config[\"mode\"] not in {\"development\", \"production\"}:\n    raise ValueError(\"invalid mode\")\nif type(config[\"workers\"]) is not int or not 1 <= config[\"workers\"] <= 16:\n    raise ValueError(\"workers must be an integer from 1 to 16\")\nif not all(isinstance(item, str) for item in config[\"features\"]):\n    raise ValueError(\"features must contain strings\")\nsecret = os.environ.get(config[\"secret_env\"])\nif secret is None:\n    raise RuntimeError(\"required secret is missing\")\n\nprint(f\"mode={config['mode']}\")\nprint(f\"workers={config['workers']}\")\nprint(f\"features={','.join(sorted(config['features']))}\")\nprint(f\"secret-source={config['secret_env']}\")\nprint(f\"secret-present={secret is not None}\")",
          walkthrough: [
            { lines: "1-10", explanation: "설정에는 secret value가 아니라 APP_TOKEN reference만 두고 SafeLoader로 기본 collection/scalar를 읽습니다." },
            { lines: "11-22", explanation: "unknown key, enum, exact integer type/range, sequence item type을 application contract로 검사합니다." },
            { lines: "23-25", explanation: "환경에서 secret을 resolve하고 없으면 startup을 실패시킵니다." },
            { lines: "27-31", explanation: "secret value는 출력하지 않고 source reference와 존재 boolean만 기록합니다." },
          ],
          run: { environment: ["Python 3.11+", "PyYAML 6.x", "예제는 process 내부에 demo environment value를 설정하며 실제 secret을 사용하지 않음"], command: "python validate_config.py" },
          output: { value: "mode=production\nworkers=4\nfeatures=export,search\nsecret-source=APP_TOKEN\nsecret-present=True", explanation: ["sequence order와 별개로 출력 비교가 안정적이도록 feature를 sort했습니다.", "secret의 실제 값은 source/output 어디에도 나타나지 않습니다.", "실제 환경에서는 process가 값을 만들지 않고 deployment secret injection을 사용합니다."] },
          experiments: [
            { change: "`worker: 4`처럼 key에 typo를 냅니다.", prediction: "unknown keys 오류가 먼저 발생합니다.", result: "unknown field reject는 조용한 default 적용을 막습니다." },
            { change: "workers를 quoted `\"4\"`로 바꿉니다.", prediction: "string이므로 exact integer type 검사에 실패합니다.", result: "암묵 coercion을 하지 않아 환경별 해석 차이를 줄입니다." },
            { change: "secret_env 대신 `token: 실제값`을 넣습니다.", prediction: "unknown key로 reject됩니다.", result: "schema/allowlist가 secret literal을 설정 contract 밖으로 밀어냅니다." },
          ],
          sourceRefs: ["git-tigers-yaml-source", "git-pumas-yaml-source", "yaml-122", "pyyaml-docs"],
        },
      ],
      diagnostics: [
        { symptom: "YAML upload 직후 예상하지 못한 Python object가 생성되거나 constructor 관련 code가 실행된다.", likelyCause: "untrusted YAML을 unsafe/full language-object loader로 처리했습니다.", checks: ["실제 loader class와 permitted tag를 확인합니다.", "custom constructor registration과 dependency version을 조사합니다.", "ingress가 trusted repository와 public upload를 구분하는지 봅니다."], fix: "SafeLoader 기반 allowlist로 전환하고 custom tag를 최소화하며 size/depth/alias limit와 schema validation을 추가합니다.", prevention: "unsafe tag fixture가 reject되는 security regression test와 dependency scanning을 둡니다." },
        { symptom: "작은 압축 파일 하나를 처리하다 service memory가 급증하고 timeout된다.", likelyCause: "decompressed size, nesting, alias/entity expansion 또는 collection count 제한이 없습니다.", checks: ["compressed/raw/decompressed byte와 node/depth count를 계측합니다.", "XML DTD/entity와 YAML alias 사용을 확인합니다.", "parser가 전체 tree를 만들고 후처리 중복 copy를 하는지 profile합니다."], fix: "ingress·decompression·parser·normalized model 각 단계에 독립 limit/timeout을 두고 초과 즉시 중단합니다.", prevention: "compression bomb·deep nesting·many alias/entity adversarial load test를 격리된 CI에서 실행합니다." },
      ],
    },
    {
      id: "conversion-loss-decision",
      title: "변환은 원문을 복사하는 일이 아니라 보존할 의미를 선택하는 migration입니다",
      lead: "XML→JSON converter 버튼을 누르기 전에 소비자가 관찰하는 정보와 편집자가 기대하는 표현을 inventory합니다.",
      explanations: [
        "XML attribute와 child element를 모두 JSON property로 평평하게 만들면 이름 충돌과 order/mixed content 문제가 생깁니다. namespace URI를 버리면 expanded name identity가 사라집니다. comment·processing instruction·CDATA lexical boundary·prefix·DOCTYPE·entity reference 모양도 일반 domain model에서 보존되지 않습니다.",
        "YAML→JSON에서는 comment, anchor/alias 이름과 shared-node identity, tag, block/flow style, quote style가 사라집니다. timestamp나 binary/custom scalar는 JSON string으로 mapping rule을 정해야 합니다. non-string mapping key도 JSON object member로 직접 옮길 수 없습니다.",
        "JSON→YAML은 대개 value tree를 표현할 수 있지만 target loader의 implicit schema가 plain scalar를 재해석하지 않도록 serializer를 사용하고 cross-runtime test합니다. duplicate JSON name이 있었다면 이미 모호하므로 변환 전에 reject해야 합니다.",
        "안전한 절차는 원본 inventory→strict parse→source schema validate→normalized domain model→business invariant validate→target serialize→target parse/validate→semantic diff→consumer integration test입니다. 원문 보존이 요구되면 별도 lossless representation 또는 원본 archive를 유지합니다.",
        "API에는 broad client ecosystem·small typed value model 때문에 JSON이 흔히 적합합니다. 사람이 자주 편집하는 deployment configuration에는 제한된 YAML profile이 편리할 수 있습니다. mixed-content document, namespace vocabulary, 기존 enterprise/protocol schema에는 XML이 더 자연스러울 수 있습니다. team/library/tooling과 existing contract도 비용에 포함합니다.",
        "형식은 보안 등급이 아닙니다. XML도 hardened parser로 안전하게 쓸 수 있고 JSON도 unsafe merge와 unlimited input으로 위험할 수 있습니다. 선택 문서에는 threat model, parser profile, schema, limits, versioning, secret policy를 함께 기록합니다.",
      ],
      concepts: [
        { term: "loss inventory", definition: "format 변환 전에 source의 comment·order·namespace·type·reference·lexical style 중 target/domain에서 보존되지 않을 항목을 목록화한 것입니다.", detail: ["승인 가능한 손실을 구분합니다.", "test oracle의 기준이 됩니다."] },
        { term: "semantic diff", definition: "변환 전후 text가 아니라 normalized domain value와 invariant가 같은지 비교하는 검사입니다.", detail: ["key formatting noise를 제거합니다.", "의미 있는 array/order는 유지합니다."] },
        { term: "parser profile", definition: "허용 version·schema·tag/entity/duplicate/coercion·size/depth option을 한 consumer contract로 고정한 설정입니다.", detail: ["형식 이름만 말하는 것보다 구체적입니다.", "보안과 interoperability를 함께 만듭니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XML→JSON migration 뒤 본문 내 강조 위치와 namespace별 확장 element가 사라졌다.", likelyCause: "record-centric key/value converter로 mixed content와 expanded name을 평탄화했습니다.", checks: ["text/element child sequence를 원본과 비교합니다.", "namespace URI/local name inventory를 만듭니다.", "consumer가 comment/PI/prefix/attribute를 관찰하는지 조사합니다."], fix: "mixed content를 tagged ordered sequence로 모델링하거나 문서 부분은 XML로 유지하고 record metadata만 별도 JSON API로 노출합니다.", prevention: "변환 승인 전에 loss inventory와 representative document semantic/render regression test를 요구합니다." },
      ],
      comparisons: [
        {
          title: "요구에 따른 기본 형식 후보",
          options: [
            { name: "XML", chooseWhen: "순서 있는 문서/mixed content, namespace vocabulary, 성숙한 XML schema/protocol/signature ecosystem이 핵심일 때", avoidWhen: "client가 단순 object/array API만 필요하고 XML toolchain 비용을 감당할 이유가 없을 때", tradeoffs: ["표현력이 넓지만 secure parser profile이 필요합니다.", "namespace/schema/canonicalization tooling이 강합니다.", "lexical round trip은 별도 요구입니다."] },
            { name: "JSON", chooseWhen: "Web/API와 여러 language 사이에서 작은 공통 value model과 넓은 tooling이 필요할 때", avoidWhen: "comment·mixed content·namespace·reference identity 자체가 보존 대상일 때", tradeoffs: ["단순하지만 number/duplicate/missing-null contract가 필요합니다.", "표준 comment가 없습니다.", "schema dialect/toolchain을 고정합니다."] },
            { name: "YAML", chooseWhen: "사람이 자주 읽고 수정하는 계층형 configuration이며 review comment와 간결한 block syntax가 중요할 때", avoidWhen: "untrusted public interchange나 parser 간 implicit type/tag 차이를 통제할 수 없을 때", tradeoffs: ["가독성이 좋지만 restricted profile이 필요합니다.", "anchor/tag/style은 JSON round trip에서 손실될 수 있습니다.", "safe loader와 duplicate/limit/schema 검사가 필요합니다."] },
          ],
        },
      ],
      expertNotes: [
        "대규모 data에서 tree 전체가 필요하지 않다면 XML pull/SAX, JSON streaming tokenizer, event-based YAML parser를 고려하되 streaming 단계에서도 depth·record count·string length와 partial-state rollback을 설계합니다.",
        "digital signature가 필요한 경우 '내 serializer output이 항상 같다'를 canonicalization으로 착각하지 않습니다. format별 표준 signature/canonical form과 검증된 library를 선택합니다.",
        "format migration은 consumer contract migration입니다. producer 파일 변환만 완료하고 old/new consumer behavior와 observability를 검증하지 않으면 완료가 아닙니다.",
      ],
    },
  ],
  lab: {
    title: "상품 XML·점수 JSON·팀 YAML을 하나의 검증된 catalog로 통합하고 형식 선택 ADR 작성하기",
    scenario: "학습 원본 세 종류를 서비스가 함께 읽어 검색 API와 운영 설정에 사용하려 합니다. 현재는 parser result를 그대로 merge하고 quoted number·missing coach·duplicate key·unsafe loader·secret literal·변환 손실을 검사하지 않습니다.",
    setup: [
      "상품 XML, 점수 JSON, 다섯 팀 YAML을 read-only source fixture로 복사하고 SHA-256 또는 version을 기록합니다.",
      "Python 3.11+와 고정된 PyYAML 6.x virtual environment, test runner를 준비합니다.",
      "valid 외에 duplicate, unknown key, invalid number, missing/explicit null, ambiguous scalar, deep/large, XML DTD/entity fixture를 격리해 준비합니다.",
      "normalized Product·Score·Team type과 허용 field/type/range/uniqueness/size limit을 먼저 문서화합니다.",
    ],
    steps: [
      "각 source를 strict parser profile로 읽고 XML expanded name, JSON duplicate number, YAML tag/duplicate/alias 정책을 적용합니다.",
      "format adapter가 parser node를 domain record로 바꾸며 number와 optional field를 명시적으로 normalize하게 합니다.",
      "source schema와 application invariant를 나누어 검증하고 error에 format·source·path/category만 남기며 value는 redaction합니다.",
      "canonical domain JSON snapshot을 생성하고 source별 record count·type·missing policy를 자동 검사합니다.",
      "같은 domain model을 candidate target JSON/YAML로 serialize한 뒤 다시 strict parse/validate하고 semantic diff를 실행합니다.",
      "comment·namespace·attribute/text·order·anchor/tag/style 등 보존되지 않은 정보를 loss inventory로 분류합니다.",
      "API payload, human-edited deployment config, document content 각각의 형식 후보를 요구·위험·tooling·migration 비용으로 비교한 ADR을 작성합니다.",
      "secret reference, input byte/depth/count/time limit, dependency update, negative fixture, rollback과 version compatibility gate를 CI에 연결합니다.",
    ],
    expectedResult: [
      "세 형식 source가 동일한 typed domain model로 통합되고 quoted count와 XML price가 integer로 검증됩니다.",
      "중복 key/attribute, unsafe tag/entity, unknown field, ambiguous/wrong type, limit 초과가 구체적인 단계에서 reject됩니다.",
      "변환 전후 canonical domain snapshot은 같고 승인되지 않은 lexical/semantic 손실은 test failure가 됩니다.",
      "API·설정·문서에 대한 형식 선택이 취향이 아니라 요구·schema·security·tooling 근거를 가진 ADR로 남습니다.",
      "실제 secret과 local absolute path/private backup URL은 fixture·output·log·공개 문서에 포함되지 않습니다.",
    ],
    cleanup: ["예제 process의 demo environment value와 임시 fixture/output을 제거합니다.", "malicious parser fixture는 공개 executable asset이 아닌 test data로 격리하고 실행 조건을 문서화합니다."],
    extensions: ["같은 domain schema를 TypeScript와 Java code generation으로 소비하고 cross-language number/null test를 추가합니다.", "큰 XML/JSON/YAML에서 streaming adapter의 memory·latency·limit behavior를 benchmark합니다.", "schema version N/N+1 rolling deployment compatibility matrix와 migration rollback rehearsal를 추가합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "상품 XML, 점수 JSON, 팀 YAML을 parse해 field path와 runtime type을 출력하고 canonical domain model로 normalize하세요.", requirements: ["XML attribute/text와 JSON quoted count를 구분합니다.", "YAML은 safe_load를 사용합니다.", "missing coach를 empty string과 구분합니다.", "정확한 canonical JSON과 type line을 제시합니다."], hints: ["parser result와 normalized result를 별도 변수로 둡니다.", "sort_keys는 object diff를 안정화하지만 list order는 그대로 둡니다."], expectedOutcome: "세 source의 표현 차이는 경계에서 흡수되고 Product·Score·Team type이 명확히 출력됩니다.", solutionOutline: ["parse→validate primitive→normalize record→canonical serialize 순서로 함수를 나눕니다.", "invalid 숫자와 missing field fixture도 한 개씩 추가합니다."] },
    { difficulty: "응용", prompt: "JSON/YAML duplicate와 type ambiguity를 거부하는 strict configuration loader를 구현하세요.", requirements: ["JSON object_pairs_hook과 YAML SafeLoader subclass 또는 동등한 strict API를 사용합니다.", "unknown key·exact type·range·secret reference를 검사합니다.", "duplicate/ambiguous scalar/missing secret/large input negative test를 만듭니다.", "오류 log에 secret value가 없음을 검사합니다."], hints: ["dict가 만들어진 뒤에는 duplicate 정보가 사라질 수 있습니다.", "SafeLoader와 schema/limit/duplicate 검사는 서로 다른 책임입니다."], expectedOutcome: "모호하거나 위험한 config가 ingestion boundary에서 deterministic error로 reject되고 정상 config만 typed value가 됩니다.", solutionOutline: ["pair-aware parse와 normalized validation을 분리합니다.", "error code와 source path를 구조화하고 값은 redaction합니다."] },
    { difficulty: "설계", prompt: "기존 XML 문서와 YAML 설정 일부를 JSON API로 옮기는 migration과 형식 선택 ADR을 작성하세요.", requirements: ["mixed content·namespace·comment·anchor/tag·number/null/order loss inventory를 만듭니다.", "source/target schema와 version compatibility를 정의합니다.", "strict parse→domain model→serialize→reparse→semantic diff gate를 설계합니다.", "XXE/unsafe tag/DoS/prototype pollution/secret threat와 limit을 포함합니다.", "dual-read/write, telemetry, rollback, consumer integration acceptance criteria를 제시합니다."], hints: ["모든 XML을 JSON으로 옮겨야 한다는 전제를 버립니다.", "lexical identity와 semantic equivalence를 따로 승인합니다."], expectedOutcome: "보존/손실/위험/비용이 명시되고 자동 gate와 rollback이 있는 실행 가능한 migration proposal이 완성됩니다.", solutionOutline: ["consumer별 관찰 정보부터 inventory합니다.", "document-centric 부분을 XML로 유지하는 hybrid도 후보에 포함합니다."] },
  ],
  reviewQuestions: [
    { question: "XML·JSON·YAML의 syntax가 valid하면 application data도 valid한가요?", answer: "아닙니다. syntax parse 뒤 schema와 required/type/range/reference 같은 application invariant 검증이 필요합니다." },
    { question: "JSON object member 순서에 business 의미를 둘 수 있나요?", answer: "두지 않는 것이 interoperability에 안전합니다. 의미 있는 순서는 array로 표현합니다." },
    { question: "JSON의 모든 integer를 JavaScript Number가 정확히 보존하나요?", answer: "아닙니다. binary64 안전 정수 범위를 넘는 값은 정밀도를 잃을 수 있어 ID를 string으로 계약하거나 범위를 제한해야 합니다." },
    { question: "PyYAML safe_load만 쓰면 모든 YAML 위험이 해결되나요?", answer: "아닙니다. 임의 object constructor 위험은 줄이지만 duplicate key, schema/type, alias/size/depth, business validation을 별도로 적용해야 합니다." },
    { question: "YAML 1.2와 JSON은 언제나 모든 parser에서 완전히 같은 의미인가요?", answer: "그렇게 단정하면 안 됩니다. 호환 목표와 syntax 수용 범위가 있어도 실제 schema/options, duplicate 처리, library extension을 target matrix로 확인해야 합니다." },
    { question: "XML attribute 순서와 namespace prefix 철자는 application identity인가요?", answer: "일반 XML 정보 모델에서 attribute 순서를 의미로 기대하지 않으며 namespace identity는 prefix가 아니라 URI와 local name입니다." },
    { question: "XML을 JSON으로 변환할 때 가장 흔한 손실은 무엇인가요?", answer: "mixed content 순서, attribute/element 구분, namespace URI, comment/PI, CDATA lexical form, prefix·DTD와 같은 문서 표현 정보입니다." },
    { question: "YAML anchor가 있는 파일을 JSON으로 바꾸면 무엇을 확인해야 하나요?", answer: "alias의 shared identity, anchor 이름, tag와 style/comment가 사라질 수 있으므로 expanded domain value가 충분한지 확인합니다." },
    { question: "형식 중 하나가 본질적으로 항상 가장 안전한가요?", answer: "아닙니다. parser 기능·limit·schema·사용 sink와 threat model이 안전성을 결정합니다. 모든 형식에 hardened profile이 필요합니다." },
    { question: "format migration 완료를 text conversion 성공으로 판단해도 되나요?", answer: "아닙니다. target reparse/schema, semantic diff, consumer integration, observability, rollback까지 통과해야 합니다." },
  ],
  completionChecklist: [
    "syntax·data model·schema·domain invariant를 서로 다른 층으로 설명했다.",
    "XML element/attribute/namespace/mixed content/order와 lexical round-trip 한계를 확인했다.",
    "JSON duplicate member·number precision·missing/null·UTF-8·comment 경계를 확인했다.",
    "YAML schema/implicit type·tag·anchor/alias·duplicate key와 restricted profile을 확인했다.",
    "세 source를 typed normalized domain model로 바꾸고 exact canonical output을 재현했다.",
    "strict duplicate loader와 wrong type/unknown key/limit negative fixture를 통과시켰다.",
    "XSD/JSON Schema와 application validator의 책임 및 dialect/version을 고정했다.",
    "XML entity, YAML unsafe tag, 큰/deep input, unsafe merge와 secret literal 위험을 완화했다.",
    "변환 loss inventory와 target reparse·semantic diff·consumer test를 완료했다.",
    "형식 선택 ADR에 요구·tooling·security·versioning·migration/rollback 근거를 기록했다.",
  ],
  nextSessions: [],
  sources: [
    { id: "web-product-xml-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data03.xml", usedFor: ["products root", "product name/price attribute", "maker text", "XML→domain normalization"], evidence: "상품명·가격이 attribute이고 제조사가 element text인 구조를 XML record mapping과 type normalization의 실제 근거로 사용했습니다." },
    { id: "web-score-json-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/data04.json", usedFor: ["JSON array/object", "quoted count", "string→integer normalization", "format contrast"], evidence: "HTML/CSS/JS/JSP count가 모두 quoted string인 사실을 parser type과 domain type의 차이를 보여 주는 fixture로 사용했습니다." },
    { id: "git-tigers-yaml-source", repository: "GITSTUDY 학습 원본", path: "tigers.yaml", usedFor: ["team mapping", "manager/coach", "members sequence", "safe configuration parsing"], evidence: "Tigers mapping과 다섯 members를 YAML block mapping/sequence 및 normalized Team model의 대표 source로 사용했습니다." },
    { id: "git-pumas-yaml-source", repository: "GITSTUDY 학습 원본", path: "pumas.yaml", usedFor: ["반복 team schema", "coach value", "sequence comparison", "strict loader lab"], evidence: "같은 field 구조와 다른 member count를 schema/cardinality fixture로 사용했습니다." },
    { id: "git-panthers-yaml-source", repository: "GITSTUDY 학습 원본", path: "panthers.yaml", usedFor: ["team collection", "members order", "multi-file normalization", "migration test"], evidence: "여러 team file을 하나의 domain collection으로 병합하면서 source provenance와 list order를 유지하는 근거로 사용했습니다." },
    { id: "git-leopards-yaml-source", repository: "GITSTUDY 학습 원본", path: "leopards.yaml", usedFor: ["team collection", "schema parity", "canonical comparison", "source coverage"], evidence: "동일 YAML schema의 반복 자료를 batch validation과 semantic snapshot 설계에 반영했습니다." },
    { id: "git-jaguars-yaml-source", repository: "GITSTUDY 학습 원본", path: "jaguars.yaml", usedFor: ["optional coach missing", "missing versus null", "schema evolution", "normalization policy"], evidence: "coach가 없는 실제 variation을 optional field와 missing/null/default 정책의 핵심 fixture로 사용했습니다." },
    { id: "xml-10e", repository: "W3C XML Standard", path: "TR/xml/", publicUrl: "https://www.w3.org/TR/xml/", usedFor: ["well-formed document", "element/attribute", "duplicate attribute", "XML syntax"], evidence: "XML document와 attribute constraint, well-formedness의 표준 기준으로 사용했습니다." },
    { id: "rfc8259-json", repository: "IETF RFC 8259", path: "rfc8259", publicUrl: "https://www.rfc-editor.org/rfc/rfc8259.html", usedFor: ["JSON value grammar", "unique object names", "number interoperability", "UTF-8"], evidence: "JSON object/array/scalar와 duplicate name 및 number 범위의 interoperability 설명을 공식 규격에 맞췄습니다." },
    { id: "yaml-122", repository: "YAML Language Development Team", path: "spec/1.2.2/", publicUrl: "https://yaml.org/spec/1.2.2/", usedFor: ["representation graph", "mapping/sequence/scalar", "tag/schema", "anchor/alias", "duplicate keys", "JSON compatibility"], evidence: "YAML 1.2.2의 node model·schema·anchor/tag와 JSON relation을 parser-independent 기준으로 사용했습니다." },
    { id: "w3c-xsd", repository: "W3C XML Schema", path: "XML/Schema", publicUrl: "https://www.w3.org/XML/Schema", usedFor: ["XML schema", "datatype", "structure validation", "versioning"], evidence: "XML well-formedness 이후 구조/type validation을 분리하는 공식 schema family의 근거로 사용했습니다." },
    { id: "json-schema-2020-12", repository: "JSON Schema", path: "draft/2020-12", publicUrl: "https://json-schema.org/draft/2020-12", usedFor: ["JSON Schema dialect", "structural validation", "vocabulary", "tool compatibility"], evidence: "JSON/YAML-normalized instance의 field/type/constraint와 validator dialect를 고정하는 기준으로 사용했습니다." },
    { id: "python-xml-security", repository: "Python Standard Library Documentation", path: "library/xml.html#xml-vulnerabilities", publicUrl: "https://docs.python.org/3/library/xml.html#xml-vulnerabilities", usedFor: ["XML parser vulnerability matrix", "entity expansion", "external entity", "secure deployment verification"], evidence: "예제의 ElementTree 사용 범위와 production XML parser threat model을 구분하는 공식 runtime 문서로 사용했습니다." },
    { id: "pyyaml-docs", repository: "PyYAML Documentation", path: "wiki/PyYAMLDocumentation", publicUrl: "https://pyyaml.org/wiki/PyYAMLDocumentation", usedFor: ["safe_load", "SafeLoader", "constructor", "Python YAML examples"], evidence: "학습 예제의 safe loader와 custom mapping constructor API를 library documentation에 맞춰 검증했습니다." },
  ],
  sourceCoverage: {
    filesRead: 7,
    filesUsed: 7,
    uncoveredNotes: [
      "원본 7개 파일은 XML attribute/text, JSON quoted scalar, YAML mapping/sequence/optional field를 비교하기에 충분했습니다. duplicate·schema dialect·parser security·canonicalization·conversion loss는 공식 규격과 library 문서로 보강했습니다.",
      "이 세션은 XML/데이터 형식 module을 마감합니다. 대용량 streaming parser 구현, binary serialization, database mapping, OpenAPI/code generation, cryptographic signature는 이후 backend/API/security 세션에서 더 깊게 연결합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
