import type { SessionSource } from "../../types";
import { appliedTopic, concept as c, nodeExample as node } from "../../session-builders/create-applied-topic.ts";
import { createExpertSession } from "../../session-builders/create-expert-session.ts";

const localQueryRefs = ["local-fetch-doc", "local-zustand-crud", "local-flow-doc", "local-guest-page", "local-guest-store", "local-guest-api"];

const topics = [
  appliedTopic({
    id: "source-manual-server-state-audit", title: "원본 fetch·store CRUD를 manual server-state machine으로 감사합니다",
    lead: "TanStack Query 도입을 전제로 하지 않고 현재 누가 request를 시작하고 loading/error/data/cache/refetch를 소유하는지부터 복원합니다.",
    mechanism: "my-app03 Guestbook은 page Effect가 list를 fetch해 Zustand store에 복사하고 mutations 뒤 local patch 또는 refetch를 수행합니다. REACT 문서들은 Fetch/Axios와 Zustand CRUD 흐름을 설명하지만 query key, freshness, cancellation, retry와 cache lifecycle은 명시적이지 않습니다.",
    workflow: "source hash를 고정하고 query inputs/auth scope, trigger, request generation, data owner, pending/error, refetch/invalidation, mutation reconciliation과 unmount/logout behavior를 sanitized graph로 기록합니다.",
    invariants: "실제 user/guestbook/password/token/endpoint/payload values를 공개 fixture에 복사하지 않고 관찰한 manual flow와 제안하는 query cache behavior를 분리하며 원본은 변경하지 않습니다.",
    edgeCases: "two mounts, route back, window focus, offline reconnect, repeated mutation, response inversion, logout/account switch와 empty/error list를 포함합니다.",
    failureModes: "Zustand store에 server list가 있다는 이유로 freshness와 dedupe가 자동 해결된다고 가정하면 duplicate request, stale overwrite와 auth cache leak를 놓칩니다.",
    verification: "source/action/request graph, duplicate owner inventory, response order, unmount/logout, sensitive sink scan과 original hash/status를 확인합니다.",
    operations: "manual/query-cache mode, query identity, data age, pending/refetch/error와 reconciliation 상태를 privacy-safe metrics로 비교합니다.",
    concepts: [c("server state", "remote authority가 소유하며 client가 cache하는 비동기 shared data입니다.", ["freshness와 invalidation이 필요합니다.", "local draft와 다릅니다."]), c("manual query state", "component/store가 loading·error·data·request lifecycle을 직접 관리하는 구조입니다.", ["유효한 선택일 수 있습니다.", "중복 계약을 감사합니다."]), c("cache ownership", "query result의 identity·freshness·retention·purge를 책임지는 layer와 owner입니다.", ["global store 존재와 다릅니다.", "auth scope를 포함합니다."])],
    codeExamples: [node("react37-source-query-graph", "redacted manual query ownership inventory", "React37SourceQueryGraph.mjs", "실제 값 없이 원본 list/mutation/cache 흐름을 구조적으로 출력합니다.", String.raw`const flow = [
  ["list", "page-effect", "store-copy", "manual-refetch"],
  ["create", "page-handler", "server", "refetch"],
  ["update", "page-handler", "server", "local-patch"],
  ["delete", "page-handler", "server", "local-remove"],
];
for (const row of flow) console.log(row.join("|"));
console.log("private-values-copied=false");`, "list|page-effect|store-copy|manual-refetch\ncreate|page-handler|server|refetch\nupdate|page-handler|server|local-patch\ndelete|page-handler|server|local-remove\nprivate-values-copied=false", localQueryRefs.concat(["tanstack-overview"]))],
  }),
  appliedTopic({
    id: "query-status-fetch-status-machine", title: "query status와 fetchStatus를 독립 state machine으로 읽습니다",
    lead: "loading boolean 하나 대신 data availability의 pending/success/error와 network activity의 idle/fetching/paused를 조합해 UI를 결정합니다.",
    mechanism: "query status는 usable data/result 상태를, fetchStatus는 query function 실행 상태를 나타내므로 cached success + background fetching, pending + paused 같은 조합이 가능합니다. derived flags는 이 조합에서 계산됩니다.",
    workflow: "initial no-data, initial fetch, success, stale background refetch, paused/offline, error with/without previous data와 retry transitions를 표로 만들고 UI skeleton/status/error/fallback을 분리합니다.",
    invariants: "background refetch가 usable data를 지우지 않고 initial failure와 refresh failure UX를 구분하며 paused를 success나 terminal error로 오해하지 않습니다.",
    edgeCases: "enabled false, cached initial, placeholder/initial data, retry delay, offline first load, suspense/error boundary와 manual refetch를 포함합니다.",
    failureModes: "isFetching만 보고 전체 화면 spinner를 띄우면 background refresh 때 content/focus가 사라지고 status error에서 previous data를 무조건 버리면 resilience가 낮아집니다.",
    verification: "허용 status×fetchStatus matrix, impossible transition negatives, data/error presence, focus/status accessibility와 offline/retry cases를 실행합니다.",
    operations: "query state combination, time-in-state, background refresh/error와 user-visible fallback을 low-cardinality로 관찰합니다.",
    concepts: [c("query status", "query data/result가 pending·success·error 중 어디에 있는지 나타내는 상태입니다.", ["network activity와 다릅니다.", "data presence와 함께 읽습니다."]), c("fetchStatus", "query function이 idle·fetching·paused 중 어디에 있는지 나타내는 실행 상태입니다.", ["offline pause를 표현합니다.", "status와 조합합니다."]), c("background refetch", "cached data를 유지한 채 freshness를 재검증하는 fetch입니다.", ["initial load와 UI가 다릅니다.", "실패 policy를 둡니다."])],
    codeExamples: [node("react37-query-states", "query status×fetchStatus UI classifier", "React37QueryStates.mjs", "state 조합을 initial/background/paused/error UI로 분류합니다.", String.raw`const cases = [
  ["pending", "fetching", false], ["success", "idle", true], ["success", "fetching", true],
  ["pending", "paused", false], ["error", "idle", false], ["error", "fetching", true],
];
for (const [status, fetchStatus, hasData] of cases) {
  const view = status === "pending" ? fetchStatus === "paused" ? "offline-empty" : "initial-loading" : status === "success" ? fetchStatus === "fetching" ? "data-refreshing" : "data" : hasData ? "stale-error-refresh" : "error-empty";
  console.log(status + ":" + fetchStatus + ":" + hasData + "=" + view);
}`, "pending:fetching:false=initial-loading\nsuccess:idle:true=data\nsuccess:fetching:true=data-refreshing\npending:paused:false=offline-empty\nerror:idle:false=error-empty\nerror:fetching:true=stale-error-refresh", ["tanstack-queries", "tanstack-important-defaults"])],
  }),
  appliedTopic({
    id: "query-key-factory-auth-scope", title: "resource·parameters·auth scope를 serializable query key factory로 고정합니다",
    lead: "문자열 하나나 URL 전체 대신 query function이 결과를 결정하는 모든 inputs를 canonical array key에 포함합니다.",
    mechanism: "TanStack Query는 top-level array query key를 deterministic hash하고 key가 cache identity, sharing, invalidation과 refetch를 결정합니다. resource, ID, filter/sort/page, locale, tenant/auth epoch와 response representation version을 필요한 범위에서 포함합니다.",
    workflow: "key factory가 validated canonical parameters를 받고 list/detail/options를 반환하며 queryFn은 QueryFunctionContext의 key에서 같은 inputs를 추출해 closure/key drift를 막습니다.",
    invariants: "서로 다른 결과는 key를 공유하지 않고 같은 logical query는 property order/undefined 차이로 불필요하게 갈라지지 않으며 secret/token/PII를 key에 넣지 않습니다.",
    edgeCases: "optional filters, date/timezone, pagination cursor, tenant switch, locale, feature version, non-serializable class/function과 large objects를 포함합니다.",
    failureModes: "auth scope 없는 ['items']는 account 간 private data를 재사용할 수 있고 full token을 key에 넣으면 devtools/log/memory에 credential이 노출됩니다.",
    verification: "same/different result equivalence corpus, serialization/canonicalization, collision/auth isolation, invalidation prefix와 token/PII sink scan을 실행합니다.",
    operations: "query family/template, cardinality, key version과 auth epoch—not identity value—를 관찰하고 excessive cardinality budget을 둡니다.",
    concepts: [c("query key", "query result cache identity를 정하는 serializable top-level array입니다.", ["queryFn inputs를 포함합니다.", "secret을 포함하지 않습니다."]), c("key factory", "resource별 canonical list/detail key를 생성하는 중앙 pure function입니다.", ["invalidation과 공유합니다.", "schema versioning을 돕습니다."]), c("auth scope", "query data를 공유할 수 있는 authenticated user/tenant/session generation 범위입니다.", ["epoch/opaque ID를 고려합니다.", "logout purge를 보완합니다."])],
    codeExamples: [node("react37-query-key", "canonical query key factory", "React37QueryKey.mjs", "filter ordering과 auth epoch를 canonical secret-free key로 만듭니다.", String.raw`function listKey({ tenantEpoch, page, filters }) {
  const canonicalFilters = Object.fromEntries(Object.entries(filters).filter(([, v]) => v !== undefined && v !== "").sort(([a], [b]) => a.localeCompare(b)));
  return ["guestbooks", "list", { tenantEpoch, page, filters: canonicalFilters }];
}
const a = listKey({ tenantEpoch: 4, page: 1, filters: { q: "synthetic", sort: "new" } });
const b = listKey({ tenantEpoch: 4, page: 1, filters: { sort: "new", q: "synthetic", empty: "" } });
console.log("equal=" + (JSON.stringify(a) === JSON.stringify(b)));
console.log("key=" + JSON.stringify(a));
console.log("contains-token=false");`, "equal=true\nkey=[\"guestbooks\",\"list\",{\"tenantEpoch\":4,\"page\":1,\"filters\":{\"q\":\"synthetic\",\"sort\":\"new\"}}]\ncontains-token=false", ["tanstack-query-keys", "tanstack-query-functions", "tanstack-cancellation", "local-guest-page"])],
  }),
  appliedTopic({
    id: "query-function-cancel-schema", title: "queryFn을 AbortSignal·HTTP/schema와 current key에 묶인 pure async boundary로 만듭니다",
    lead: "component state를 직접 mutation하는 fetch function 대신 key inputs와 signal을 받아 validated data를 반환하거나 typed failure를 throw합니다.",
    mechanism: "query function은 context의 queryKey와 signal을 사용해 request를 만들고 signal consumption은 query cancellation behavior와 연결됩니다. HTTP status/content-type/body/schema/domain validation을 통과한 immutable data만 반환합니다.",
    workflow: "key parser→request adapter(signal)→response status/body→runtime schema→domain mapper를 구성하고 retry가 판단할 stable failure metadata를 보존하며 sensitive payload를 error/log에서 redaction합니다.",
    invariants: "aborted/old key result가 cache에 commit되지 않고 invalid data가 success가 되지 않으며 queryFn이 React component/store side effect를 직접 수행하지 않습니다.",
    edgeCases: "signal already aborted, multi-request query, partial response, 204, malformed JSON, auth expiry, redirect와 provider fallback을 포함합니다.",
    failureModes: "queryFn에서 setGlobalStore와 notification을 수행하면 retry/refetch마다 side effects가 중복되고 signal을 무시하면 inactive request가 계속됩니다.",
    verification: "key parse/schema negatives, status/body corpus, abort all nested requests, no partial commit, retry metadata와 side-effect-free invocation을 실행합니다.",
    operations: "query function phase, abort/failure class, schema/client version와 endpoint template을 관찰하고 raw key/body/token은 제외합니다.",
    concepts: [c("query function", "query key/context에서 inputs를 받아 remote data를 반환하는 async fetch boundary입니다.", ["side effect를 최소화합니다.", "signal을 소비합니다."]), c("signal consumption", "제공된 AbortSignal을 fetch/Axios와 하위 requests에 전달해 query cancellation을 실제 transport에 적용하는 행위입니다.", ["promise 무시와 다릅니다.", "cleanup을 검증합니다."]), c("typed failure", "retry/UI/telemetry가 안정적으로 분기할 수 있는 safe error code와 metadata입니다.", ["raw response를 숨깁니다.", "schema failure를 포함합니다."])],
  }),
  appliedTopic({
    id: "freshness-stale-gc-refetch", title: "staleTime·gcTime·refetch triggers를 business freshness budget으로 정합니다",
    lead: "기본값을 암기하거나 모두 Infinity로 두지 않고 data volatility, user harm, request cost와 offline tolerance로 fresh/retention을 결정합니다.",
    mechanism: "fresh query는 staleness-triggered refetch를 피하고 stale query는 mount/focus/reconnect 같은 조건에서 background refetch할 수 있습니다. active observers가 없는 inactive query는 gcTime 뒤 cache에서 제거될 수 있으며 persistence retention은 별도입니다.",
    workflow: "query family별 max acceptable age, refetch triggers, active/inactive retention, manual invalidation, poll과 offline policy를 표로 만들고 current TanStack version defaults와 다른 설정을 명시합니다.",
    invariants: "freshness와 garbage collection을 혼동하지 않고 sensitive auth cache retention을 최소화하며 static/Infinity/manual invalidation semantics를 version-specific test로 고정합니다.",
    edgeCases: "window focus in devtools, reconnect storm, hidden tab, clock change, inactive back navigation, persisted cache, SSR staleTime와 memory pressure를 포함합니다.",
    failureModes: "staleTime 0을 cache 미사용으로 오해하거나 gcTime을 freshness로 쓰면 과도한 requests 또는 오래된 data 표시가 생깁니다.",
    verification: "fake/real clock fresh→stale, mount/focus/reconnect, active/inactive GC, manual invalidation, memory/auth purge와 version upgrade tests를 실행합니다.",
    operations: "cache age/fresh/stale, observer count, refetch trigger, hit/miss/GC와 memory를 query family별 budget으로 관찰합니다.",
    concepts: [c("staleTime", "query data가 fresh로 간주되는 기간/정책입니다.", ["refetch trigger에 영향 줍니다.", "retention과 다릅니다."]), c("gcTime", "inactive query가 cache에서 garbage collection되기 전 retention 시간입니다.", ["active query에는 다른 lifecycle입니다.", "freshness와 다릅니다."]), c("refetch trigger", "mount, focus, reconnect, interval, invalidation처럼 query function을 다시 실행하게 하는 사건입니다.", ["stale/enabled/network policy와 조합합니다.", "중복을 측정합니다."])],
    codeExamples: [node("react37-freshness-gc", "freshness and inactive retention model", "React37FreshnessGc.mjs", "age/staleTime/active/gcTime으로 serve/refetch/gc를 분류합니다.", String.raw`const cases = [
  { age: 10, stale: 60, active: true, inactiveAge: 0, gc: 300 },
  { age: 80, stale: 60, active: true, inactiveAge: 0, gc: 300 },
  { age: 80, stale: 60, active: false, inactiveAge: 100, gc: 300 },
  { age: 400, stale: 60, active: false, inactiveAge: 320, gc: 300 },
];
for (const x of cases) console.log(!x.active && x.inactiveAge >= x.gc ? "garbage-collect" : x.age <= x.stale ? "serve-fresh" : x.active ? "serve-stale-refetch" : "retain-stale");`, "serve-fresh\nserve-stale-refetch\nretain-stale\ngarbage-collect", ["tanstack-important-defaults", "tanstack-queries"])],
  }),
  appliedTopic({
    id: "observer-dedupe-structural-sharing", title: "observer sharing·request dedupe와 structural sharing을 identity evidence로 검증합니다",
    lead: "두 components가 같은 query를 쓰는 경우 cache record와 in-flight promise를 공유하되 각 observer의 select/render lifecycle은 별도임을 이해합니다.",
    mechanism: "동일 query key observers는 하나의 cached query를 관찰하고 concurrent fetch가 deduplicated될 수 있습니다. JSON-compatible results의 structural sharing은 unchanged branches reference를 보존해 selector/memo rendering을 줄일 수 있지만 correctness guarantee는 schema/identity가 담당합니다.",
    workflow: "observer count, in-flight request ID, raw cached data, per-observer select/equality와 render를 계측하고 large/non-JSON data에서 structural sharing cost를 측정합니다.",
    invariants: "dedupe가 서로 다른 auth/filter queries를 합치지 않고 selected data가 cache를 mutation하지 않으며 unchanged entity identity가 stable ID/version과 일치합니다.",
    edgeCases: "near-simultaneous mount, different select, abort one observer, all observers unmount, huge arrays, Date/Map/class data와 custom structural sharing을 포함합니다.",
    failureModes: "component render 수를 network request 수로 해석하거나 cache data를 selector에서 mutation하면 observer 간 invisible corruption이 생깁니다.",
    verification: "1/N observers, same/different keys, unmount one/all, select exceptions, reference preservation, large data cost와 network count를 실행합니다.",
    operations: "observers, in-flight dedupe ratio, select/render duration, structural sharing cost와 cache bytes를 관찰하고 feature flag를 둡니다.",
    concepts: [c("query observer", "component별로 cached query의 state와 selected result를 구독하는 객체/관계입니다.", ["cache record와 다릅니다.", "lifecycle을 가집니다."]), c("request deduplication", "동일 query identity의 동시 fetch consumers가 하나의 in-flight work를 공유하는 동작입니다.", ["version behavior를 확인합니다.", "auth key가 중요합니다."]), c("structural sharing", "old/new JSON-compatible data의 동일 branches reference를 재사용하는 최적화입니다.", ["mutation을 허용하지 않습니다.", "비용을 측정합니다."])],
    codeExamples: [node("react37-structural-sharing", "entity structural sharing model", "React37StructuralSharing.mjs", "같은 records는 reference를 보존하고 변경 record만 교체합니다.", String.raw`const oldData = [{ id: "a", value: 1 }, { id: "b", value: 2 }];
const incoming = [{ id: "a", value: 1 }, { id: "b", value: 3 }];
const next = incoming.map((item) => { const old = oldData.find((x) => x.id === item.id); return old && old.value === item.value ? old : item; });
console.log("a-shared=" + (next[0] === oldData[0]));
console.log("b-shared=" + (next[1] === oldData[1]));
console.log("values=" + next.map((x) => x.value).join(","));`, "a-shared=true\nb-shared=false\nvalues=1,3", ["tanstack-important-defaults", "tanstack-queries", "local-guest-store"])],
  }),
  appliedTopic({
    id: "retry-errors-boundaries", title: "query retry·error reset과 previous data resilience를 failure taxonomy로 통제합니다",
    lead: "기본 retry 횟수에 기대지 않고 failure class, attempt, deadline, auth와 user impact에 따라 retry/stop/reauth/fallback을 결정합니다.",
    mechanism: "query retry option은 failureCount/error를 기반으로 재시도 여부와 delay를 결정하고 error boundary/reset integration은 retry 가능한 render flow를 만듭니다. previous cached data가 있는 refresh error와 initial empty error를 다르게 처리합니다.",
    workflow: "abort/timeout/offline/HTTP/schema/auth/domain classes를 map하고 safe idempotent query에만 capped backoff+jitter/deadline을 적용하며 reset은 inputs/config가 바뀌거나 user가 명시적으로 시도할 때 사용합니다.",
    invariants: "401 refresh loop와 4xx/schema/domain invalid을 blind retry하지 않고 canceled query를 error alert로 과장하지 않으며 retry 중 usable data/focus를 보존합니다.",
    edgeCases: "offline pause, 429 Retry-After, 503 storm, partial outage, error boundary loop, route remount와 provider circuit를 포함합니다.",
    failureModes: "모든 error를 세 번 retry하면 validation/auth failures와 outage load를 증폭하고 boundary reset만 반복하면 root cause/config가 그대로인 loop가 됩니다.",
    verification: "failure×attempt×deadline table, delay bounds, pause/reconnect, previous data/error UI, reset conditions와 load simulation을 실행합니다.",
    operations: "failure class, attempts/delay, boundary resets, stale-data fallback와 circuit state를 query family/provider별로 관찰합니다.",
    concepts: [c("failure count", "현재 query fetch cycle에서 연속 실패한 횟수입니다.", ["retry decision에 사용합니다.", "user attempts와 다릅니다."]), c("error reset", "error boundary/query가 다음 attempt를 허용하도록 error state를 재설정하는 coordination입니다.", ["root cause 수정은 아닙니다.", "loop를 제한합니다."]), c("stale-data fallback", "refresh 실패 시 마지막 validated cache를 age/error 표시와 함께 유지하는 resilience 정책입니다.", ["민감/위험 data는 제한합니다.", "freshness를 표시합니다."])],
    codeExamples: [node("react37-retry-decision", "query retry budget model", "React37RetryDecision.mjs", "failure class/count/deadline로 retry 여부를 결정합니다.", String.raw`const cases = [
  ["network", 0, 1000], ["network", 3, 1000], ["http-404", 0, 1000],
  ["http-503", 1, 500], ["schema", 0, 1000], ["cancelled", 0, 1000], ["http-503", 1, 0],
];
for (const [kind, count, remaining] of cases) {
  const transient = kind === "network" || kind === "http-503";
  console.log(kind + ":" + count + ":" + remaining + "=" + (transient && count < 3 && remaining > 0));
}`, "network:0:1000=true\nnetwork:3:1000=false\nhttp-404:0:1000=false\nhttp-503:1:500=true\nschema:0:1000=false\ncancelled:0:1000=false\nhttp-503:1:0=false", ["tanstack-important-defaults", "tanstack-queries", "local-fetch-doc"])],
  }),
  appliedTopic({
    id: "pagination-infinite-placeholder", title: "page·cursor·infinite query를 identity·placeholder·memory budget으로 설계합니다",
    lead: "page 변경마다 화면을 비우거나 모든 pages를 무제한 누적하지 않고 key, next cursor, placeholder와 eviction을 API contract에 맞춥니다.",
    mechanism: "paginated query는 page/filter를 key에 포함하고 placeholder data로 previous result를 유지할 수 있습니다. infinite query는 pages/pageParams와 getNextPageParam을 관리하며 cursor uniqueness, hasNextPage, concurrent fetch와 max pages를 통제합니다.",
    workflow: "offset/page/cursor contract를 선택하고 canonical page params, stable item IDs, duplicate merge, filter reset, prefetch와 memory/accessibility focus behavior를 정의합니다.",
    invariants: "다른 filter/page data가 같은 key를 공유하지 않고 cursor loop/duplicate item을 탐지하며 placeholder를 current page success로 잘못 표시하지 않습니다.",
    edgeCases: "deletion/insertion between pages, repeated cursor, empty middle page, back navigation, bidirectional scroll, offline, large pages와 filter typing을 포함합니다.",
    failureModes: "array index/key로 pages를 merge하면 reorder/duplicate가 생기고 unlimited infinite cache는 memory/DOM/network를 증가시키며 focus 위치를 잃습니다.",
    verification: "page/filter key changes, placeholder flags, cursor loop/duplicate, concurrent next fetch, max pages/DOM window, keyboard/live status와 back navigation을 실행합니다.",
    operations: "pages/items/cache bytes, duplicate/cursor loop, prefetch waste, next latency와 DOM/render budget을 관찰합니다.",
    concepts: [c("page parameter", "offset/page/cursor처럼 다음 response 범위를 결정하는 query input입니다.", ["query key에 포함합니다.", "server contract를 따릅니다."]), c("placeholder data", "새 query가 fetch되는 동안 이전/대체 data를 임시 표시하는 값과 상태입니다.", ["fresh success로 과장하지 않습니다.", "focus를 보존합니다."]), c("infinite query", "여러 page results와 pageParams를 하나의 query lifecycle로 관리하는 query shape입니다.", ["cursor/memory policy가 필요합니다.", "DOM virtualization과 다릅니다."])],
    codeExamples: [node("react37-cursor-pages", "cursor page merge and loop guard", "React37CursorPages.mjs", "duplicate entities와 repeated next cursor를 탐지해 bounded merge를 수행합니다.", "const pages = [{ items: [\"a\", \"b\"], next: \"c2\" }, { items: [\"b\", \"c\"], next: \"c2\" }];\nconst items = [...new Set(pages.flatMap((page) => page.items))];\nconst cursors = pages.map((page) => page.next).filter(Boolean);\nconst cursorLoop = new Set(cursors).size !== cursors.length;\nconsole.log(\"items=\" + items.join(\",\"));\nconsole.log(\"duplicate-items=\" + (pages.flatMap((page) => page.items).length - items.length));\nconsole.log(\"cursor-loop=\" + cursorLoop);\nconsole.log(\"fetch-next=\" + !cursorLoop);", "items=a,b,c\nduplicate-items=1\ncursor-loop=true\nfetch-next=false", ["tanstack-paginated", "tanstack-infinite"])],
  }),
  appliedTopic({
    id: "ssr-hydration-auth-persistence", title: "SSR dehydration·hydration과 persisted cache를 request/auth/version scope로 격리합니다",
    lead: "prefetched cache를 HTML/client로 넘길 때 server request 간 data와 credential이 섞이지 않고 first client render가 같은 snapshot을 보게 합니다.",
    mechanism: "SSR은 request마다 QueryClient를 만들고 prefetch/dehydrate한 safe state를 client HydrationBoundary에서 hydrate합니다. staleTime/updatedAt와 clock, error redaction, serialization과 auth scope를 명시하며 persistent cache는 별도 expiry/buster/allowlist를 가집니다.",
    workflow: "per-request client factory, authenticated query allowlist, server fetch credentials, dehydrate filter/redaction, escaped serialization, client buster/schema/auth epoch와 logout purge를 구현합니다.",
    invariants: "두 HTTP requests가 cache를 공유하지 않고 token/password/error internals가 dehydrated/persisted state에 없으며 other account/tenant가 prior data를 hydrate하지 않습니다.",
    edgeCases: "streaming SSR, partial error, clock skew, app downgrade, multi-tab, offline restore, logout before hydration와 preview/public pages를 포함합니다.",
    failureModes: "process-global QueryClient는 cross-request data leak를 만들고 전체 cache persistence는 private data/error/config를 오래 남길 수 있습니다.",
    verification: "two-request isolation, serialized artifact secret scan, server/client snapshot parity, clock/version/buster, account switch/logout purge와 corrupt persistence를 실행합니다.",
    operations: "hydrate success/mismatch, cache buster/version, restored age/auth scope, purge and cross-request canary를 관찰하고 emergency cache reset을 둡니다.",
    concepts: [c("dehydrated state", "server query cache에서 client hydration에 필요한 serializable safe subset입니다.", ["token/config를 제외합니다.", "request scope입니다."]), c("HydrationBoundary", "client subtree가 dehydrated query cache를 재구성하는 React boundary입니다.", ["first render parity를 봅니다.", "authorization을 대체하지 않습니다."]), c("cache buster", "app/schema/auth generation이 달라 persisted cache를 무효화하는 version key입니다.", ["migration과 선택합니다.", "logout purge를 보완합니다."])],
  }),
  appliedTopic({
    id: "contract-tests-observability-migration", title: "QueryClient contract tests·Devtools-safe observability와 incremental migration을 운영합니다",
    lead: "manual fetch를 한 번에 교체하지 않고 query 하나씩 dual-read 없이 명확한 owner로 옮기며 behavior/performance/rollback evidence를 남깁니다.",
    mechanism: "fresh QueryClient test는 retry off/controlled defaults로 queryFn, key, cache state와 GC를 결정적으로 검증하고 component test는 provider/user UI, disposable server는 HTTP/cancel, browser는 focus/reconnect/SSR를 증명합니다.",
    workflow: "source query inventory에서 pilot를 선택해 query options factory와 adapter를 추가하고 old store copy는 compatibility selector로만 읽다가 parity/cutover 후 제거하며 feature flag로 rollback합니다.",
    invariants: "test QueryClient가 cases 사이 공유되지 않고 devtools/log/persisted cache에 secret/PII가 없으며 migration 중 two owners가 같은 data를 독립 mutation하지 않습니다.",
    edgeCases: "old/new mixed routes, cache warm/cold, HMR, test retries, version upgrade defaults, offline/SSR, rollback with persisted data와 bundle size를 포함합니다.",
    failureModes: "mock useQuery 결과만 테스트하면 key/queryFn/cache를 우회하고 dual-write store+query cache는 divergence와 invalidation complexity를 만듭니다.",
    verification: "query options/unit, QueryClient/component, HTTP/browser/SSR, privacy scan, load/memory, old/new parity, canary and rollback rehearsal를 실행합니다.",
    operations: "query family SLI, request/cache/refetch/retry/error/GC, memory, bundle/version과 migration parity/difference를 dashboard·owner·runbook에 연결합니다.",
    concepts: [c("test QueryClient", "테스트마다 fresh defaults/cache/logger를 가진 isolated QueryClient입니다.", ["retry/time을 통제합니다.", "production config도 별도 검증합니다."]), c("single owner migration", "한 query family의 authoritative client owner를 단계별로 old 또는 new 중 하나로 유지하는 전환입니다.", ["dual-write를 피합니다.", "compatibility read를 제한합니다."]), c("cache observability", "query identity·state·age·observers·fetch/retry/GC를 민감 data 없이 측정하는 telemetry입니다.", ["Devtools는 production policy를 따릅니다.", "cardinality를 통제합니다."])],
    codeExamples: [node("react37-migration-gate", "manual→query-cache migration gate", "React37MigrationGate.mjs", "parity, duplicate owners, secret-free cache와 budgets로 cutover를 평가합니다.", String.raw`const report = { contractParity: true, duplicateOwners: 0, secretFindings: 0, staleOverwrites: 0, requestDeltaPercent: -28, rollbackReady: true };
const pass = report.contractParity && report.duplicateOwners === 0 && report.secretFindings === 0 && report.staleOverwrites === 0 && report.requestDeltaPercent <= 10 && report.rollbackReady;
for (const [key, value] of Object.entries(report)) console.log(key + "=" + value);
console.log("cutover=" + (pass ? "pass" : "block"));`, "contractParity=true\nduplicateOwners=0\nsecretFindings=0\nstaleOverwrites=0\nrequestDeltaPercent=-28\nrollbackReady=true\ncutover=pass", ["tanstack-testing", "tanstack-overview", "tanstack-ssr", "local-flow-doc"])],
  }),
];

const sources: SessionSource[] = [
  { id: "local-fetch-doc", repository: "D:/dev/REACT", path: "docs/react/09-fetch-axios.md", usedFor: ["manual Fetch/Axios state flow", "loading/error lesson"], evidence: "2026-07-14 read-only sanitized audit: 108 lines, 4,797 bytes, SHA-256 3A5B8BF21C44D86E331AED7A8B6E554E3B2F65FA91D576A48CFBFF22679F3507. actual URL/key/output values는 복사하지 않았습니다." },
  { id: "local-zustand-crud", repository: "D:/dev/REACT", path: "docs/react/11-zustand-auth-crud.md", usedFor: ["auth/Todo/Memo/Guestbook state flow", "server/local state boundary"], evidence: "2026-07-14 read-only sanitized audit: 115 lines, 5,909 bytes, SHA-256 8B2C3D04101D66DBCE4489268A1C91D8A79C4D205C4832289A069629B77156F7. actual user/domain strings는 복사하지 않았습니다." },
  { id: "local-flow-doc", repository: "D:/dev/REACT", path: "docs/integration/code-flow-by-feature.md", usedFor: ["integrated auth/CRUD call-flow provenance", "migration inventory"], evidence: "2026-07-14 read-only sanitized audit: 568 lines, 32,140 bytes, SHA-256 546F6BECA265FB69250102BF8406C62D818D07F9258C44B7C23068C240E5BD62. actual token/password/user/routes/payloads는 복사하지 않았습니다." },
  { id: "local-guest-page", repository: "D:/dev/my-app03", path: "src/pages/GuestBookPage.jsx", usedFor: ["manual Effect list fetch", "mutation refetch/local patch", "auth-gated UI"], evidence: "2026-07-14 read-only sanitized audit: 253 lines, 10,636 bytes, SHA-256 40B3B9446990A0F1A499329D0AA7360E758D44D0A57552E2B5E72D1E35627077. actual user/guestbook/password/messages는 복사하지 않았습니다." },
  { id: "local-guest-store", repository: "D:/dev/my-app03", path: "src/store/useGuestbookStore.jsx", usedFor: ["server list client copy", "local patch/remove actions"], evidence: "2026-07-14 read-only sanitized audit: 21 lines, 562 bytes, SHA-256 DA1A28E1BD3D8A7632530089011576C1FC7F4BE6A75D9001BFCD04323BABF209. actual domain values는 복사하지 않았습니다." },
  { id: "local-guest-api", repository: "D:/dev/my-app03", path: "src/api/GuestBook.jsx", usedFor: ["CRUD request adapter", "query function/mutation boundary"], evidence: "2026-07-14 read-only sanitized audit: 13 lines, 365 bytes, SHA-256 42CC6DCDAFB0BA46A85307C7A762656B11FB8D3194F2DC44FBD44AF7F32D37D4. actual routes/payload values는 복사하지 않았습니다." },
  { id: "tanstack-overview", repository: "TanStack Query official documentation", path: "framework/react/overview", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/overview", usedFor: ["server-state query/cache scope"], evidence: "TanStack Query React 공식 overview입니다." },
  { id: "tanstack-queries", repository: "TanStack Query official documentation", path: "framework/react/guides/queries", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/queries", usedFor: ["query status/fetchStatus/result contract"], evidence: "TanStack Query React 공식 queries guidance입니다." },
  { id: "tanstack-query-keys", repository: "TanStack Query official documentation", path: "framework/react/guides/query-keys", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/query-keys", usedFor: ["query key arrays/hashing/dependencies"], evidence: "TanStack Query React 공식 query keys guidance입니다." },
  { id: "tanstack-query-functions", repository: "TanStack Query official documentation", path: "framework/react/guides/query-functions", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/query-functions", usedFor: ["query function/context/failure"], evidence: "TanStack Query React 공식 query functions guidance입니다." },
  { id: "tanstack-important-defaults", repository: "TanStack Query official documentation", path: "framework/react/guides/important-defaults", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/important-defaults", usedFor: ["freshness/refetch/retry/gc/structural sharing defaults"], evidence: "TanStack Query React 공식 current defaults guidance입니다." },
  { id: "tanstack-cancellation", repository: "TanStack Query official documentation", path: "framework/react/guides/query-cancellation", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/query-cancellation", usedFor: ["AbortSignal query cancellation"], evidence: "TanStack Query React 공식 cancellation guidance입니다." },
  { id: "tanstack-paginated", repository: "TanStack Query official documentation", path: "framework/react/guides/paginated-queries", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/paginated-queries", usedFor: ["page query/placeholder data"], evidence: "TanStack Query React 공식 paginated queries guidance입니다." },
  { id: "tanstack-infinite", repository: "TanStack Query official documentation", path: "framework/react/guides/infinite-queries", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries", usedFor: ["pages/pageParams/next cursor"], evidence: "TanStack Query React 공식 infinite queries guidance입니다." },
  { id: "tanstack-ssr", repository: "TanStack Query official documentation", path: "framework/react/guides/ssr", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/ssr", usedFor: ["SSR prefetch/dehydrate/hydrate/request isolation"], evidence: "TanStack Query React 공식 SSR/hydration guidance입니다." },
  { id: "tanstack-testing", repository: "TanStack Query official documentation", path: "framework/react/guides/testing", publicUrl: "https://tanstack.com/query/latest/docs/framework/react/guides/testing", usedFor: ["isolated QueryClient/testing"], evidence: "TanStack Query React 공식 testing guidance입니다." },
];

const session = createExpertSession({
  inventoryId: "react-37-api-state-machine-cache", slug: "react-37-api-state-machine-cache", courseId: "react", moduleId: "react-router-network", order: 7,
  title: "API state machine·query cache", subtitle: "manual fetch/store 흐름을 query identity, status/fetchStatus, freshness, dedupe, pagination, SSR와 auth-scoped cache 계약으로 발전시킵니다.",
  level: "고급", estimatedMinutes: 140,
  coreQuestion: "remote data를 local global state처럼 다루지 않고 identity·freshness·request lifecycle·cache retention과 실패 복구를 어떻게 일관되게 관리할까요?",
  summary: "REACT Fetch/Zustand/integration 문서와 my-app03 Guestbook page/store/API를 read-only·sanitized 감사해 manual Effect fetch, store copy, mutation refetch/local patch 흐름을 보존합니다. 실제 user/content/password/token/endpoints는 복사하지 않습니다. query status/fetchStatus, secret-free auth-scoped keys, signal/schema queryFns, freshness/gc/refetch, observer/dedupe/structural sharing, retry/errors, pagination/infinite, SSR/persistence isolation과 tests/migration/operations를 current TanStack Query 공식 계약과 일곱 executable models로 확장합니다.",
  objectives: ["원본 manual server-state ownership을 감사한다.", "query status와 fetchStatus를 state machine으로 읽는다.", "canonical auth-scoped query key factory를 설계한다.", "AbortSignal/HTTP/schema queryFn을 구현한다.", "staleTime/gcTime/refetch를 freshness budget으로 정한다.", "observer/dedupe/structural sharing을 측정한다.", "retry/error reset/stale fallback을 통제한다.", "pagination/infinite query identity와 memory를 관리한다.", "SSR/hydration/persistence를 request/auth/version으로 격리한다.", "contract tests, observability와 incremental migration을 운영한다."],
  prerequisites: [{ title: "Axios client·interceptor와 오류 경계", reason: "typed HTTP adapter, cancellation, retry, auth refresh와 schema error를 알아야 queryFn과 cache가 transport 책임을 중복하지 않고 올바르게 조율할 수 있습니다.", sessionSlug: "react-36-axios-client-interceptors" }],
  keywords: ["server state", "TanStack Query", "query key", "status", "fetchStatus", "staleTime", "gcTime", "dedupe", "structural sharing", "pagination", "SSR", "hydration"],
  topics,
  lab: { title: "원본 Guestbook manual flow를 auth-scoped query cache로 qualification하기", scenario: "원본 files는 변경하지 않고 synthetic data/disposable server에서 manual baseline과 QueryClient implementation을 동일 workload/faults로 비교합니다.", setup: ["Node 20 이상", "React and current TanStack Query fixture", "disposable HTTP/problem server", "deferred requests/fake clock/offline", "SSR two-request harness", "resource/cache metrics", "원본 6 files read-only", "synthetic non-sensitive records"], steps: ["원본 source hashes와 manual query/mutation/state owner graph를 기록합니다.", "query status×fetchStatus UI state table과 accessible pending/error/status를 구현합니다.", "resource/filter/page/auth epoch query key factories와 collision/secret scan을 검증합니다.", "signal-consuming typed queryFn과 response schema/no-partial-commit을 만듭니다.", "family별 freshness/gc/refetch/retry policy를 fake/real clock에서 실행합니다.", "same/different key observers, dedupe, structural sharing와 render/network counts를 측정합니다.", "pagination/cursor/placeholder/duplicate/max-pages와 keyboard/focus를 검증합니다.", "two-request SSR dehydrate/hydrate, cache buster/account switch/logout purge를 시험합니다.", "isolated QueryClient/component/HTTP/browser contract suite와 privacy artifact scan을 실행합니다.", "manual/new parity, canary, cutover/rollback과 cache reconciliation runbook을 rehearsal합니다."], expectedResult: ["서로 다른 auth/filter/page results가 cache에서 섞이지 않고 same query는 중복 request를 줄입니다.", "initial/background/offline/error UI가 usable data와 fetch activity를 정확히 표현합니다.", "stale/GC/retry/cancel 뒤 cache와 active resources가 policy와 baseline을 지킵니다.", "SSR/persisted cache가 request/account 사이 private data와 credentials를 누출하지 않습니다.", "manual→query cache cutover가 behavior/performance/privacy evidence와 rollback을 가집니다."], cleanup: ["QueryClients/observers/caches, requests, timers/listeners와 HTTP/SSR servers를 제거합니다.", "synthetic dehydrated/persisted states, entities, traces와 secret canaries를 폐기합니다.", "fake clocks/offline/focus events, browser storage와 feature flags를 원복합니다.", "원본 6 files hash/status unchanged를 확인합니다."], extensions: ["streamed/deferred query와 Suspense boundaries를 qualification합니다.", "persistent offline mutations와 cache buster migration을 추가합니다.", "multiple tabs broadcast와 auth epoch isolation을 검증합니다.", "query cache SLO와 automated reconciliation dashboard를 구축합니다."] },
  exercises: [
    { difficulty: "따라하기", prompt: "일곱 Node examples를 실행하고 실제 QueryClient/component/browser 결과와 대응시키세요.", requirements: ["stdout 완전 일치", "manual source graph", "state combinations", "query key", "freshness/GC", "structural sharing", "retry", "migration gate", "model 범위"], hints: ["Node cache model을 실제 TanStack Query scheduler/React rendering/HTTP 증명이라고 표현하지 마세요."], expectedOutcome: "query identity에서 cache lifecycle과 user-visible state까지 설명합니다.", solutionOutline: ["audit→state/key/queryFn→fresh/dedupe/retry→page/SSR→test/migrate 순서입니다."] },
    { difficulty: "응용", prompt: "원본 Guestbook list를 TanStack Query 기반으로 점진 이전하세요.", requirements: ["key factory/auth scope", "typed cancellable queryFn", "state UI", "fresh/gc/retry", "pagination", "SSR/logout", "isolated tests", "parity/rollback"], hints: ["Zustand list copy와 query cache를 장기간 dual-write하지 마세요."], expectedOutcome: "list data가 하나의 cache owner에서 freshness·failure·auth lifecycle을 지킵니다.", solutionOutline: ["baseline→pilot query→parity/fault→cutover→remove old owner 순서입니다."] },
    { difficulty: "설계", prompt: "조직 공통 frontend server-state governance를 작성하세요.", requirements: ["state classification", "keys/queryFns", "freshness/retention", "retry/errors", "pagination", "auth/SSR/persistence", "tests/privacy", "migration/operations"], hints: ["library defaults를 조직 freshness/security policy로 착각하지 마세요."], expectedOutcome: "모든 query family가 일관된 correctness·performance·security·recovery evidence로 운영됩니다.", solutionOutline: ["classify→identify→fetch/validate→cache/bound→isolate→observe/recover 순서입니다."] },
  ],
  nextSessions: ["react-38-mutation-invalidation-optimistic"], sources,
  sourceCoverage: { filesRead: 6, filesUsed: 6, uncoveredNotes: ["원본 docs/source의 actual endpoint, token/password/user/guestbook/payload values는 공개 content에 복사하지 않았습니다.", "원본 manual flow에는 TanStack Query가 사용됐다고 주장하지 않고 migration target과 baseline을 명확히 분리했습니다.", "source의 fetch/store/refetch/local patch를 관찰했지만 query freshness/dedupe/retry/cancel/auth isolation이 구현됐다고 과장하지 않습니다.", "Node models는 actual QueryClient observers/scheduler/structural sharing, React rendering, browser focus/offline와 SSR/hydration을 대체하지 않으므로 lab integration을 요구합니다."] },
});

export default session;
