import type { DetailedCodeExample, DiagnosticCase, SessionSource } from "../../types";
import { buildMvcSession, type MvcTopicSpec } from "./mvc-01-mybatis-config-mapper.ts";

const diag = (area: string, symptom: string, cause: string, fix: string): DiagnosticCase[] => [
  { symptom, likelyCause: cause, checks: [`${area}의 request limits→part metadata→stream validation→staging→DB state→publish/finalize 순서를 추적합니다.`, "DB/file/object states와 retries/crash points를 표로 비교합니다.", "filename·path·content·password·credential이 response/log에 노출되지 않았는지 확인합니다."], fix, prevention: `${area}의 malicious file·partial failure·crash/retry·orphan reconciliation matrix를 자동화합니다.` },
  { symptom: "JDK lifecycle example은 통과하지만 실제 upload/storage/container에서 다르게 동작한다.", likelyCause: "순수 상태 기계는 multipart parser limits, filesystem/object-store semantics, antivirus, MyBatis transaction과 browser download를 실행하지 않습니다.", checks: ["unit과 integration 범위를 구분합니다.", "container/storage/DB versions와 mount semantics를 기록합니다.", "격리된 synthetic files로 실제 stream/failure를 재현합니다."], fix: "운영 uploads/credentials 없이 container+ephemeral DB+owned temp/object namespace integration tests를 추가합니다.", prevention: "static/unit/multipart/storage/DB/security/chaos evidence를 독립 release gates로 둡니다." },
];

const audit: DetailedCodeExample = {
  id: "powershell-mvc07-original-multipart-audit", title: "guestbook2 inventory8·실행 폐쇄21의 multipart·file/DB partial-failure shape를 감사합니다", language: "powershell", filename: "verify-original-mvc07.ps1", purpose: "파일 업로드·DB·브라우저를 실행하지 않고 size config, submitted filename, write order, MIME/magic/delete와 unfinished handlers를 exact하게 보존합니다.",
  code: String.raw`param([Parameter(Mandatory)][string]$SourceRoot)
$ErrorActionPreference='Stop'
$inventory=@(
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/controller/MyController.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/WriteOKCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/UpdateOKCommand.java',
 'guestbook2/guestbook2/src/main/resources/mapper/GuestBookMapper.xml',
 'guestbook2/guestbook2/src/main/webapp/write.jsp',
 'guestbook2/guestbook2/src/main/webapp/update.jsp',
 'guestbook2/guestbook2/src/main/webapp/oneList.jsp',
 'guestbook2/guestbook2/src/main/webapp/error.jsp'
)
$closure=@(
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/Command.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/ListCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/OneListCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/WriteCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/UpdateCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/DeleteCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/DeleteOKCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/ErrorCommand.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/mapper/GuestBookMapper.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/vo/GuestBookVO.java',
 'guestbook2/guestbook2/src/main/java/org/study/guestbook2/db/DBUtil.java',
 'guestbook2/guestbook2/src/main/webapp/list.jsp',
 'guestbook2/guestbook2/src/main/resources/mybatis-config.xml'
)
$rels=@($inventory+$closure);$files=@($rels|ForEach-Object{Get-Item -LiteralPath (Join-Path $SourceRoot $_)})
if($files.Count-ne21){throw 'multipart closure drift'}
$before=@{};foreach($file in $files){$before[$file.FullName]=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}
function Active([string]$text){$value=[regex]::Replace(([regex]::Replace($text,'(?s)<!--.*?-->','')),'(?s)<%--.*?--%>','');$value=[regex]::Replace(([regex]::Replace($value,'(?s)/\*.*?\*/','')),'(?m)//.*$','');return $value}
function Count([string]$value,[string]$pattern){([regex]::Matches($value,$pattern,[Text.RegularExpressions.RegexOptions]::IgnoreCase)).Count}
$inv=Active (($files[0..7]|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine)
$all=Active (($files|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine)
$controller=[IO.File]::ReadAllText($files[0].FullName);$write=[IO.File]::ReadAllText($files[1].FullName)
$mapperInterface=[IO.File]::ReadAllText($files[16].FullName);$mapper=[regex]::Replace([IO.File]::ReadAllText($files[3].FullName),'(?s)<!--.*?-->','')
$routes=Count $controller 'case\s+"';$defaults=Count $controller '(?m)^\s*default\s*:';$configs=Count $inv '@MultipartConfig';$forms=Count $inv 'enctype="multipart/form-data"'
$parts=Count $inv '\.getPart\s*\(';$submitted=Count $inv 'getSubmittedFileName\s*\(';$uuids=Count $inv 'UUID\.randomUUID\s*\(';$realPaths=Count $inv 'getRealPath\s*\(';$writes=Count $inv '\.write\s*\('
$beforeSession=if($write-match'(?s)filePart\.write\s*\(.*DBUtil\.getSession\s*\('){1}else{0};$commits=Count $inv '\.commit\s*\('
$methods=Count $mapperInterface '(?m)^\s*(?:List<GuestBookVO>|GuestBookVO|int)\s+\w+\s*\(';$statements=Count $mapper '<(?:select|insert|update|delete)\b';$empty=Count $all 'return\s+""\s*;'
$mime=Count $all 'getContentType\s*\(';$magic=Count $all '(?:probeContentType|magicBytes|fileSignature)';$deletes=Count $all '(?:Files\.delete|\.delete\s*\()';$directEl=Count $inv '\$\{';$csrf=Count $inv '(?:csrf|_token)'
if($routes-ne8-or$defaults-ne1-or$configs-ne1-or$forms-ne2-or$parts-ne1-or$submitted-ne1-or$uuids-ne1-or$realPaths-ne1-or$writes-ne1-or$beforeSession-ne1-or$commits-ne1-or$methods-ne4-or$statements-ne3-or$empty-ne2-or$mime-ne0-or$magic-ne0-or$deletes-ne0-or$directEl-ne18-or$csrf-ne0){throw 'source shape drift'}
foreach($file in $files){if((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash-cne$before[$file.FullName]){throw 'source hash drift'}}
"files=21|inventory=8|routes=8|defaultRoutes=1|multipartConfigs=1|multipartForms=2|getParts=1|submittedNames=1|uuidNames=1|getRealPath=1|partWrites=1|writeBeforeSession=1|commits=1|mapperMethods=4|activeStatements=3|emptyMutationHandlers=2|mimeChecks=0|magicChecks=0|fileDeletes=0|directEL=18|csrfTokens=0|hashes=21/21"
"execution=static-only|upload=not-written|db=not-contacted|user-files=not-read|credentials=not-output"`,
  walkthrough: [{ lines: "1-28", explanation: "inventory8과 routes/commands/mapper/VO/DBUtil/list/config closure13을 합쳐21 files를 고정합니다." }, { lines: "29-35", explanation: "hash와 active source를 준비하고 controller/write/mapper inputs를 분리합니다." }, { lines: "36-42", explanation: "multipart API, filename/storage/write order/commit/mapper/unfinished/security shapes를 exact count합니다." }, { lines: "43-45", explanation: "source 불변성과 upload/DB/user-file 미실행을 확인합니다." }],
  run: { environment: ["PowerShell 7+", "jspstudy 저장소의 상위 폴더", "정적 읽기만", "upload/DB/Servlet/browser 불필요"], command: "pwsh -NoProfile -File verify-original-mvc07.ps1 -SourceRoot ./jspstudy" },
  output: { value: "files=21|inventory=8|routes=8|defaultRoutes=1|multipartConfigs=1|multipartForms=2|getParts=1|submittedNames=1|uuidNames=1|getRealPath=1|partWrites=1|writeBeforeSession=1|commits=1|mapperMethods=4|activeStatements=3|emptyMutationHandlers=2|mimeChecks=0|magicChecks=0|fileDeletes=0|directEL=18|csrfTokens=0|hashes=21/21\nexecution=static-only|upload=not-written|db=not-contacted|user-files=not-read|credentials=not-output", explanation: ["multipart config/form/Part/UUID는 도입됐지만 submitted filename을 붙이고 deployed webroot realPath에 씁니다.", "file write가 SqlSession/insert보다 먼저여서 DB 실패 시 orphan이 남을 수 있고 cleanup/delete는0입니다.", "mapper interface4/XML3, empty update/delete handlers2로 evolution regression이 명확하며 MIME/magic/CSRF checks도0입니다."] },
  experiments: [{ change: "file write를 staging service로 옮깁니다.", prediction: "writeBeforeSession/file write shape가 drift합니다.", result: "개선본은 staged→DB PENDING→publish/finalize와 compensation tests로 검증합니다." }, { change: "Update/Delete mapper statements를 추가합니다.", prediction: "activeStatements3/emptyHandlers2가 실패합니다.", result: "feature parity matrix와 file replacement lifecycle tests를 함께 추가합니다." }, { change: "원본 multipart request를 전송합니다.", prediction: "사용자 file이 webapp path에 기록되고 DB insert를 시도할 수 있습니다.", result: "audit는 source/hash/count만 사용합니다." }],
  sourceRefs: ["mvc07-controller", "mvc07-write-ok", "mvc07-update-ok", "mvc07-mapper", "mvc07-write-jsp", "mvc07-update-jsp", "mvc07-one-jsp", "mvc07-error-jsp", "mvc07-command", "mvc07-list-command", "mvc07-one-command", "mvc07-write-command", "mvc07-update-command", "mvc07-delete-command", "mvc07-delete-ok", "mvc07-error-command", "mvc07-mapper-interface", "mvc07-vo", "mvc07-dbutil", "mvc07-list-jsp", "mvc07-config"],
};

const topics: MvcTopicSpec[] = [
  {
    id: "mvc07-original-multipart-closure-audit", title: "guestbook2 inventory8·closure21의 upload 진화와 regression을 정확히 감사합니다", lead: "multipart 도입을 성공으로만 보지 않고 file/DB 순서, validation/lifecycle gaps와 미완성 CRUD를 source evidence로 고정합니다.",
    explanations: ["inventory8은 Multipart MyController, WriteOK/UpdateOK, mapper XML, write/update/oneList/error JSP입니다.", "직접 routes/commands/mapper/VO/DBUtil/list/config까지 따라가면 실행 closure는21 files입니다.", "controller는 MultipartConfig와 routes8/default ErrorCommand1을 가져 이전 unknown-route null failure는 개선했습니다.", "write/update forms2가 multipart/form-data이며 WriteOK는 Part, submitted filename, UUID prefix, getRealPath, Part.write를 사용합니다.", "container limits는 존재하지만 MIME/magic checks0, CSRF0이며 original filename이 stored name suffix와 HTML alt/src flow에 들어갑니다.", "file write가 DB session/insert보다 먼저이고 file delete/compensation0이어서 insert/commit 실패가 orphan file을 만듭니다.", "mapper interface methods4지만 XML statements3이고 UpdateOK/DeleteOK는 empty return2라 수정/삭제 evolution이 미완성입니다.", "direct EL18과 detail password 출력까지 남아 이전 세션의 password/XSS 위험도 regression됐습니다."],
    concepts: [{ term: "feature evolution audit", definition: "이전 version과 새 version의 기능·보안·데이터 lifecycle parity 및 regression을 source/runtime evidence로 비교하는 과정입니다.", detail: ["추가와 손실을 함께 봅니다.", "route/mapper/view를 관통합니다."] }, { term: "orphan file", definition: "DB row가 없거나 deleted인데 storage에 소유 관계 없이 남은 file object입니다.", detail: ["비용/노출을 만듭니다.", "reconciliation이 필요합니다."] }, { term: "partial failure", definition: "DB와 filesystem/object store 중 일부 side effect만 성공해 시스템 불변식이 깨진 상태입니다.", detail: ["단일 DB transaction으로 해결되지 않습니다.", "state machine/보상이 필요합니다."] }],
    diagnostics: diag("원본 multipart evolution", "DB insert가 실패했는데 upload directory에 file이 계속 남는다.", "Part.write가 SqlSession/insert보다 먼저 실행되고 catch/rows0에 file cleanup/compensation이 없습니다.", "owned staging key를 만들고 DB state/commit/publish/finalize 및 orphan reconciler를 설계합니다."),
    expertNotes: ["Adding UUID to an untrusted original filename does not by itself neutralize path separators, dangerous extensions or disclosure.", "A default route improves control flow but does not restore unfinished update/delete mapper and file lifecycle semantics."], customExample: audit,
  },
  {
    id: "mvc07-version-diff-regression-matrix", title: "guestbook1→guestbook2를 route·CRUD·security·file lifecycle parity matrix로 비교합니다", lead: "새 upload 기능 때문에 기존 update/delete/password/XSS/PRG contract가 사라지지 않게 before/after evidence를 만듭니다.",
    explanations: ["route names/casing이 writeForm/write_ok/onelist/editForm에서 write/writeOK/oneList/update 등으로 바뀌어 links/forms/controller parity가 필요합니다.", "guestbook2 default ErrorCommand는 unknown action을 error.jsp로 보내지만 status/logging이 없고 error.jsp는 JavaScript list 이동입니다.", "write는 file column까지 insert하지만 update/delete handlers는 empty이고 XML update/delete statements도 없어 CRUD parity가 깨졌습니다.", "VO에 g_file이 추가됐지만 password-bearing model/direct EL과 client/public password exposure는 제거되지 않았습니다.", "old app의 soft-delete scope, update commit와 password flaws를 새 app에서 각각 preserve/fix/migrate할지 결정해야 합니다.", "schema migration은 nullable file key, backfill, old/new app compatibility와 rollback을 포함합니다.", "route+method+form action+handler+mapper statement+view link를 한 matrix로 만들어 missing edge를 startup/test에서 찾습니다.", "security controls은 inherited-by-accident가 아니라 CSRF/auth/hash/encoding/headers별 parity/upgrade acceptance를 둡니다."],
    concepts: [{ term: "parity matrix", definition: "기능/route별 input·handler·persistence·output·security·test가 old/new version에서 존재하는지 비교한 표입니다.", detail: ["regression을 드러냅니다.", "의도적 변경을 승인합니다."] }, { term: "schema compatibility window", definition: "old/new application version이 같은 expanded schema에서 동시에 안전하게 동작하는 배포 기간입니다.", detail: ["expand/backfill/contract를 씁니다.", "rollback을 보장합니다."] }, { term: "regression budget", definition: "새 기능 도입 시 기존 기능·보안·성능 acceptance를 잃지 않도록 정한 최소 통과 기준입니다.", detail: ["미완성 handler를 차단합니다.", "release gate와 연결합니다."] }],
    diagnostics: diag("version parity", "file write는 되지만 기존 수정/삭제 button이 빈 path 또는 error로 끝난다.", "새 version에서 route/UI만 추가하고 handler/mapper/transaction/file replacement parity를 end-to-end 추적하지 않았습니다.", "old/new route-CRUD-security-storage matrix와 contract suite를 release 전에 모두 통과시킵니다."),
    expertNotes: ["A versioned rewrite should make intentionally removed behavior explicit; an empty handler return is not a migration strategy.", "Security flaws from the prior version should be tracked as must-fix parity gaps, not preserved for behavioral compatibility."],
    trace: { className: "GuestbookVersionDecision", title: "old/new capability를 preserve/upgrade/block로 판정합니다", purpose: "upload 추가와 기존 CRUD/security regression을 같은 matrix에서 관리합니다.", cases: [{ input: "LIST_DETAIL", decision: "PRESERVE_TEST", evidence: "route+view" }, { input: "CLIENT_PASSWORD", decision: "UPGRADE", evidence: "server-hash" }, { input: "EMPTY_UPDATE", decision: "BLOCK_RELEASE", evidence: "missing-mapper" }], defaultDecision: "REVIEW", defaultEvidence: "unmapped-capability", sourceRefs: ["mvc07-controller", "mvc07-update-ok", "mvc07-delete-ok", "mvc07-mapper-interface", "mvc07-mapper", "mvc06-controller"] },
  },
  {
    id: "mvc07-multipart-boundaries-limits-streaming", title: "multipart/form-data를 request·part·memory/disk·timeout 한계로 제한합니다", lead: "annotation size만 믿지 않고 proxy/container/application/storage budgets와 streaming ownership을 일관되게 만듭니다.",
    explanations: ["multipart/form-data boundary가 text fields와 binary parts를 구분하며 request parameter parsing behavior는 container에 의존합니다.", "fileSizeThreshold, maxFileSize, maxRequestSize는 개별 part/전체 request와 memory-to-disk spooling budget을 다르게 제어합니다.", "reverse proxy, load balancer, Servlet container와 application limits가 충돌하면 어느 층에서 어떤 status를 반환하는지 문서화합니다.", "part count, field count/name length, filename length와 total uncompressed/processed size도 제한합니다.", "Content-Length는 없거나 거짓일 수 있으므로 실제 stream bytes를 bounded counter로 읽고 초과 즉시 abort/cleanup합니다.", "slow upload와 stalled read에 request/read timeout, connection/pool/thread budget을 적용해 resource exhaustion을 막습니다.", "multipart parse failure는413/400 category로 매핑하고 temp parts가 container/app 양쪽에서 삭제되는지 fault test합니다.", "large test files는 synthetic generated stream을 사용하고 user uploads/production storage를 읽지 않습니다."],
    concepts: [{ term: "multipart boundary", definition: "한 HTTP body에서 여러 form fields/files를 구분하는 MIME delimiter입니다.", detail: ["Content-Type parameter입니다.", "parser가 검증합니다."] }, { term: "spooling threshold", definition: "작은 part는 memory, 큰 part는 temporary disk로 옮기기 시작하는 container resource 기준입니다.", detail: ["size limit과 다릅니다.", "temp cleanup이 필요합니다."] }, { term: "resource budget", definition: "request당 bytes/parts/time/memory/temp disk와 동시 uploads에 정한 상한입니다.", detail: ["모든 계층을 맞춥니다.", "DoS 방어입니다."] }],
    diagnostics: diag("multipart limits", "큰/느린 upload 몇 개로 heap/temp disk/request threads가 고갈된다.", "개별 maxFileSize만 두고 total parts, actual stream bytes, concurrency/time/temp cleanup budgets를 관리하지 않았습니다.", "proxy/container/app/storage 한계를 정렬하고 bounded stream/part count/time/concurrency와 cleanup tests를 적용합니다."),
    expertNotes: ["Multipart size limits are availability controls and must be coordinated across every proxy and container layer.", "Rejecting a request does not prove temporary parser files were removed; verify cleanup under parse and timeout failures."],
    trace: { className: "MultipartLimitDecision", title: "part count·bytes·time budget로 upload를 판정합니다", purpose: "annotation 하나보다 강한 fail-early resource policy를 만듭니다.", cases: [{ input: "ONE_2MB", decision: "STREAM", evidence: "within-budgets" }, { input: "ELEVEN_PARTS", decision: "413", evidence: "part-limit" }, { input: "SLOW_STALLED", decision: "408", evidence: "read-timeout" }], defaultDecision: "400", defaultEvidence: "invalid-multipart", sourceRefs: ["mvc07-controller", "mvc07-write-jsp", "mvc07-update-jsp", "jakarta-servlet", "owasp-file-upload"] },
  },
  {
    id: "mvc07-filename-path-storage-key", title: "submitted filename을 표시 metadata로만 취급하고 random storage key를 별도로 만듭니다", lead: "path traversal·reserved names·collision·dangerous extension을 막고 deployed webroot 밖의 owned storage를 사용합니다.",
    explanations: ["getSubmittedFileName 값은 client-controlled이며 directory separators, Unicode confusables, control chars, long names와 reserved device names를 포함할 수 있습니다.", "UUID prefix 뒤 original name을 그대로 붙이면 path separator/unsafe serving/content-disposition 문제는 남습니다.", "storage key는 server가 random opaque id와 allowlisted canonical extension으로 만들고 original filename과 분리합니다.", "original name이 필요하면 length/control/Unicode policy를 적용해 DB metadata로만 저장하고 HTML/header context에서 encode합니다.", "Paths.get(name).getFileName 같은 basename 처리만으로 content/extension/MIME 안전이 완성되지는 않습니다.", "getRealPath('/upload')는 exploded deployment가 아니면 null일 수 있고 redeploy 시 사라지며 webroot direct execution/serving 위험이 있습니다.", "storage root는 configuration으로 webroot 밖에 두고 resolved canonical path가 owned root 아래인지 확인하며 symlink/reparse point race를 피합니다.", "download는 opaque id로 lookup한 server path/object key를 사용하고 user path를 filesystem API에 직접 전달하지 않습니다."],
    concepts: [{ term: "storage key", definition: "server가 생성해 physical/object storage에서 file을 식별하는 opaque random 이름입니다.", detail: ["original filename과 분리합니다.", "path component로 안전합니다."] }, { term: "path traversal", definition: "`../`, absolute path, separators나 filesystem quirks로 intended root 밖의 file을 읽고 쓰는 공격입니다.", detail: ["canonical root containment을 검증합니다.", "user path를 쓰지 않습니다."] }, { term: "display filename", definition: "사용자에게 보여 줄 metadata 이름으로 storage path가 아니며 context encoding과 header-safe 처리가 필요합니다.", detail: ["길이/controls를 제한합니다.", "Content-Disposition에 안전하게 씁니다."] }],
    diagnostics: diag("filename/storage", "특수 filename upload가 upload root 밖을 덮거나 download header/HTML을 깨뜨린다.", "submitted filename을 UUID suffix와 path/HTML/header에 그대로 재사용했습니다.", "opaque storage key, root containment와 별도 sanitized display name/context encoders를 적용합니다."),
    expertNotes: ["Randomizing a prefix does not sanitize an attacker-controlled path suffix.", "Filesystem containment checks must consider symlinks/reparse points and race-resistant creation semantics on the deployed platform."],
    trace: { className: "UploadNameDecision", title: "filename input을 storage/display/reject로 분리합니다", purpose: "user name이 physical path가 되지 않게 합니다.", cases: [{ input: "PHOTO.PNG", decision: "RANDOM_KEY", evidence: "display-metadata" }, { input: "DOT_DOT", decision: "REJECT", evidence: "path-traversal" }, { input: "CONTROL_CHAR", decision: "REJECT", evidence: "header-log-safety" }], defaultDecision: "REJECT", defaultEvidence: "invalid-name", sourceRefs: ["mvc07-write-ok", "owasp-file-upload", "owasp-path-traversal"] },
  },
  {
    id: "mvc07-file-type-magic-quarantine", title: "extension·declared MIME·magic bytes를 조합하고 quarantine/scanning policy를 적용합니다", lead: "browser가 보낸 Content-Type과 filename을 신뢰하지 않고 실제 bytes·decoder behavior·serving policy로 type을 결정합니다.",
    explanations: ["Part.getContentType와 extension은 client-controlled hints이며 단독 allowlist로 충분하지 않습니다.", "허용 type마다 canonical extension, MIME set, magic/signature와 decoder parse/re-encode policy를 정의합니다.", "magic bytes도 polyglot, parser confusion, malformed/truncated file과 decompression bomb을 완전히 막지 못합니다.", "이미지는 maintained decoder로 pixel dimensions/frame count/metadata/encoded size를 제한하고 가능하면 safe format으로 re-encode합니다.", "archive/document가 필요하면 nested files, compression ratio, macros/scripts/external references와 parser sandbox를 제한합니다.", "upload는 quarantine/private state로 두고 antivirus/content disarm scan이 통과하기 전 public download/render를 금지합니다.", "scan timeout/unavailable/infected/unsupported 결과를 typed state로 기록하고 retry/quarantine/delete/alert policy를 둡니다.", "browser serving은 Content-Disposition attachment, nosniff, explicit Content-Type, CSP/sandbox와 별도 download domain을 threat model에 따라 적용합니다."],
    concepts: [{ term: "magic bytes", definition: "file 시작/구조에 나타나는 format signature로 실제 type 판별의 한 signal입니다.", detail: ["MIME보다 강하지만 완전하지 않습니다.", "parser 검증과 결합합니다."] }, { term: "polyglot file", definition: "둘 이상의 format/parser에서 유효하게 해석되어 한 검사를 통과하고 다른 parser를 공격할 수 있는 file입니다.", detail: ["serving context가 중요합니다.", "re-encode/sandbox가 도움됩니다."] }, { term: "quarantine", definition: "validation/scanning 전 file을 비공개·비실행 상태로 격리하는 lifecycle stage입니다.", detail: ["public URL을 주지 않습니다.", "TTL/cleanup을 둡니다."] }],
    diagnostics: diag("file type validation", "jpg 확장자 upload가 script/HTML로 실행되거나 image parser를 고갈시킨다.", "filename/declared MIME만 검사하고 magic/decoder limits/quarantine/serving headers가 없습니다.", "type-specific signature+decode/re-encode limits, quarantine scan와 safe download headers/domain을 적용합니다."),
    expertNotes: ["No single file-type signal is authoritative; validate the format with the parser that will later consume it.", "Antivirus scanning is one control and does not replace size limits, parser hardening, authorization or safe serving."],
    trace: { className: "FileTypeDecision", title: "extension·MIME·magic·decoder 결과를 upload state로 판정합니다", purpose: "한 signal만 맞는 file을 public publish하지 않습니다.", cases: [{ input: "ALL_MATCH_DECODE", decision: "QUARANTINE_SCAN", evidence: "type-consistent" }, { input: "MIME_ONLY", decision: "REJECT", evidence: "client-claim" }, { input: "MAGIC_MATCH_BOMB", decision: "REJECT", evidence: "resource-limit" }], defaultDecision: "REJECT", defaultEvidence: "unsupported-type", sourceRefs: ["owasp-file-upload", "jakarta-servlet"] },
  },
  {
    id: "mvc07-file-lifecycle-download-auth", title: "upload를 STAGED→QUARANTINED→READY→REPLACED/DELETED lifecycle로 관리합니다", lead: "file path 문자열 하나를 DB에 넣지 않고 ownership·scan·visibility·retention·download authorization을 state machine으로 만듭니다.",
    explanations: ["metadata row는 opaque file id/key, owner/guestbook id, display name, media type, size/hash, state, created/version을 가집니다.", "STAGED/QUARANTINED file은 public route에서 조회되지 않고 scan success 뒤 READY로 전이합니다.", "download controller는 actor/guestbook/soft-delete/file state를 authorization하고 storage key를 server lookup합니다.", "direct webroot/static URL은 authorization, audit, no-store/content headers와 soft-delete scope를 우회하므로 피합니다.", "download response는 validated Content-Type, nosniff, safe Content-Disposition와 length/range 정책을 설정합니다.", "삭제는 DB metadata를 DELETING/TOMBSTONED로 전이하고 async physical delete를 idempotently 수행합니다.", "retention/legal hold/backup/versioning과 orphan/stale multipart cleanup TTL을 문서화합니다.", "state transition마다 actor/system reason, correlation과 previous/new state를 audit하되 original content/path secret을 기록하지 않습니다."],
    concepts: [{ term: "file metadata row", definition: "storage object와 owner/resource/lifecycle/security attributes를 연결하는 database record입니다.", detail: ["path string보다 강합니다.", "version/state를 포함합니다."] }, { term: "download authorization", definition: "file id 요청마다 actor와 owning resource·state를 검증한 뒤 server가 storage key를 조회하는 정책입니다.", detail: ["direct URL을 피합니다.", "soft delete와 연결합니다."] }, { term: "tombstone", definition: "논리적으로 삭제됐음을 durable하게 표시해 retry/reconciliation이 physical absence를 안전하게 처리하게 하는 상태입니다.", detail: ["idempotent delete를 돕습니다.", "retention과 연결합니다."] }],
    diagnostics: diag("file lifecycle", "삭제된 방명록의 upload URL을 알면 계속 내려받을 수 있다.", "webroot static path를 DB/JSP에 노출해 resource state/authorization을 거치지 않습니다.", "opaque file id download controller와 owner/state authorization, tombstone/retention cleanup을 적용합니다."),
    expertNotes: ["A public object URL can outlive the database row unless visibility and lifecycle are enforced by storage policy or an authorized gateway.", "Content-Disposition filename handling is a separate header-encoding problem from storage-key safety."],
    trace: { className: "FileLifecycleDecision", title: "file state별 read/scan/delete action을 판정합니다", purpose: "staging file이 즉시 public URL이 되지 않게 합니다.", cases: [{ input: "QUARANTINED_DOWNLOAD", decision: "DENY", evidence: "scan-pending" }, { input: "READY_AUTHORIZED", decision: "STREAM", evidence: "safe-headers" }, { input: "TOMBSTONED_DELETE", decision: "IDEMPOTENT", evidence: "already-logical-delete" }], defaultDecision: "DENY", defaultEvidence: "unknown-file-state", sourceRefs: ["mvc07-write-ok", "mvc07-one-jsp", "owasp-file-upload", "owasp-authorization"] },
  },
  {
    id: "mvc07-db-file-consistency-compensation", title: "DB transaction과 file/object store 사이 partial failure를 staging·outbox·reconciliation으로 복구합니다", lead: "서로 다른 resource에 원자 commit이 없음을 인정하고 durable states와 idempotent compensations로 수렴시킵니다.",
    explanations: ["filesystem/object store write와 relational DB transaction은 기본적으로 한 ACID transaction이 아닙니다.", "권장 흐름 하나는 random staging key로 upload→validate/scan→DB PENDING metadata+guestbook/outbox commit→publish/copy→DB READY finalize입니다.", "DB commit 전 실패는 owned staging file을 즉시/TTL cleanup하고 DB row를 남기지 않습니다.", "DB commit 후 publish 실패는 PENDING row/outbox가 retry/reconciliation 대상으로 남아 사용자가 성공/processing/error 상태를 알 수 있게 합니다.", "publish 성공 후 READY update 실패는 reconciler가 storage marker/hash와 DB state를 비교해 idempotently finalize합니다.", "compensation delete도 실패할 수 있으므로 silently catch하지 않고 tombstone/retry/dead-letter/alert를 사용합니다.", "operation/idempotency key와 content hash/size/version을 각 단계에 기록해 duplicate retry와 wrong-object deletion을 막습니다.", "crash-after-each-step chaos test는 DB rows, file keys, visible states, outbox와 orphan count가 eventual invariant로 수렴하는지 검증합니다."],
    concepts: [{ term: "saga/compensation", definition: "여러 local transaction의 실패를 반대 action이나 상태 전이로 보상해 최종 일관성에 도달하는 pattern입니다.", detail: ["보상도 실패합니다.", "idempotency가 필요합니다."] }, { term: "transactional outbox", definition: "DB state와 후속 storage command event를 같은 DB transaction에 기록해 worker가 재시도 가능하게 전달하는 pattern입니다.", detail: ["dual-write gap을 줄입니다.", "consumer를 idempotent하게 합니다."] }, { term: "reconciler", definition: "DB metadata와 storage inventory를 주기적으로 비교해 stuck/orphan/missing states를 안전하게 복구하는 process입니다.", detail: ["age/state/ownership 기준을 씁니다.", "dry-run과 audit가 필요합니다."] }],
    diagnostics: diag("DB/file consistency", "DB row는 READY인데 file이 없거나 storage에는 file이 있는데 row가 없다.", "DB와 storage dual-write 순서를 success path만 구현하고 durable pending/outbox/compensation/reconciliation이 없습니다.", "staging/PENDING/outbox/READY state machine과 idempotent worker/reconciler를 적용합니다."),
    expertNotes: ["There is no general atomic commit across a local filesystem or object store and a relational database; design explicit convergence semantics.", "A cleanup job must prove ownership and age/state before deleting objects to avoid turning reconciliation into data loss."],
    trace: { className: "DbFileConsistencyDecision", title: "DB/storage state pair를 finalize/retry/cleanup/alert로 판정합니다", purpose: "partial states를 숨기지 않고 수렴 action을 선택합니다.", cases: [{ input: "PENDING+STAGED", decision: "PUBLISH", evidence: "outbox" }, { input: "NO_ROW+OLD_STAGED", decision: "CLEANUP", evidence: "owned+ttl" }, { input: "READY+MISSING", decision: "ALERT", evidence: "data-loss-risk" }], defaultDecision: "QUARANTINE", defaultEvidence: "unknown-state-pair", sourceRefs: ["mvc07-write-ok", "mvc07-mapper", "mybatis-java-api", "owasp-file-upload"] },
  },
  {
    id: "mvc07-update-replace-delete-file", title: "첨부 교체·유지·제거를 tri-state command와 versioned lifecycle로 구현합니다", lead: "새 file이 없다는 사실을 기존 file 삭제로 해석하지 않고 DB row와 old/new objects의 교체 순서를 안전하게 만듭니다.",
    explanations: ["update form은 multipart이지만 UpdateOK가 empty라 keep/replace/remove semantics가 구현되지 않았습니다.", "command는 KEEP, REPLACE(new part), REMOVE 세 상태를 명시하고 file input empty와 remove checkbox를 구분합니다.", "REPLACE는 새 file을 stage/validate/scan한 뒤 guestbook expectedVersion과 새 metadata를 transaction commit합니다.", "commit 전 old READY file을 삭제하면 rollback 시 원래 첨부를 잃으므로 old object는 새 reference가 durable해진 뒤 tombstone/delete합니다.", "commit 뒤 old delete 실패는 new update를 rollback할 수 없으므로 idempotent cleanup queue/reconciler에 남깁니다.", "REMOVE도 row version/authorization/password/CSRF와 same transaction metadata transition을 사용합니다.", "동시 두 replacement는 exactly one version commit, loser new staging cleanup과 winner old cleanup ownership을 검증합니다.", "DeleteOK는 guestbook soft delete와 attachment lifecycle/tombstone/outbox를 같은 domain outcome으로 조정합니다."],
    concepts: [{ term: "tri-state file command", definition: "기존 첨부 유지·새 첨부 교체·첨부 제거를 명시적으로 구분하는 update 입력입니다.", detail: ["empty file input과 다릅니다.", "mass assignment를 막습니다."] }, { term: "reference switch", definition: "DB owner row가 old file id에서 validated new file id로 version-aware하게 바뀌는 transaction입니다.", detail: ["old delete보다 먼저 durable해야 합니다.", "exact rows를 확인합니다."] }, { term: "deferred cleanup", definition: "commit 이후 더 이상 참조되지 않는 object를 queue/outbox로 idempotently 삭제하는 처리입니다.", detail: ["실패를 재시도합니다.", "ownership을 확인합니다."] }],
    diagnostics: diag("file replacement", "첨부 교체 DB update가 실패했는데 기존 file은 삭제되고 새 file은 orphan으로 남는다.", "old delete/new write/DB update의 순서와 compensation owner가 정의되지 않았습니다.", "new stage→versioned reference commit→old tombstone/deferred delete, loser cleanup 순서를 적용합니다."),
    expertNotes: ["Delete the old object only after the new reference is durable; otherwise rollback can cause irreversible attachment loss.", "Concurrent replacement needs versioned ownership so a losing request never deletes the winning request's object."],
    trace: { className: "AttachmentUpdateDecision", title: "KEEP/REPLACE/REMOVE와 version 결과를 lifecycle action으로 변환합니다", purpose: "empty file input과 deletion intent를 분리합니다.", cases: [{ input: "KEEP_VERSION_OK", decision: "NO_FILE_CHANGE", evidence: "metadata-only" }, { input: "REPLACE_VERSION_OK", decision: "SWITCH_DEFER_OLD", evidence: "new-ready" }, { input: "REPLACE_STALE", decision: "CLEAN_NEW_409", evidence: "optimistic-conflict" }], defaultDecision: "REJECT", defaultEvidence: "invalid-file-intent", sourceRefs: ["mvc07-update-ok", "mvc07-update-jsp", "mvc07-delete-ok", "mvc07-mapper-interface", "owasp-file-upload"] },
  },
  {
    id: "mvc07-secure-render-download-inherited-controls", title: "upload UI/상세/download에도 password·CSRF·XSS·authorization controls를 계승합니다", lead: "file 기능을 별도 섬으로 만들지 않고 이전 CRUD security contract를 모든 route·model·HTML/header sink에 적용합니다.",
    explanations: ["oneList.jsp는 password를 직접 출력하므로 guestbook2에서도 password-free projection/server verification이 필수입니다.", "writer/subject/email/content/display filename과 file URL은 direct EL 대신 HTML/attribute/URL/header context encoding을 적용합니다.", "write/update/delete/upload/download mutations는 CSRF와 object authorization/password policy를 server에서 검증합니다.", "file id/g_idx/original name/content type/size hidden/query values는 client-controlled이며 authorization/storage path 근거가 아닙니다.", "download는 owner row active/state/version을 조회하고 public-safe status, cache, Content-Type, nosniff/Content-Disposition을 적용합니다.", "images를 inline 표시할 때 SVG/HTML/polyglot 위험과 CSP/sandbox/separate origin을 평가하고 default attachment가 더 안전할 수 있습니다.", "error.jsp JavaScript redirect만 쓰지 말고 actual status, accessible message/navigation와 correlation을 제공합니다.", "render/download security tests는 password/hash absence, XSS/CRLF filename, IDOR, CSRF, deleted/quarantined file와 cache leak를 포함합니다."],
    concepts: [{ term: "IDOR", definition: "공격자가 g_idx/file id를 바꿔 server object authorization 없이 다른 resource에 접근하는 취약점입니다.", detail: ["opaque id만으로 막히지 않습니다.", "매 요청 권한을 확인합니다."] }, { term: "content disposition", definition: "browser가 response content를 inline 표시하거나 attachment로 저장하고 filename을 어떻게 제안할지 정하는 header입니다.", detail: ["header-safe encoding이 필요합니다.", "MIME/nosniff와 함께 씁니다."] }, { term: "separate download origin", definition: "upload content를 main application cookies/DOM과 다른 origin에서 제공해 script/HTML impact를 격리하는 방어입니다.", detail: ["CSP/cookie policy와 연결합니다.", "authorization URL 전략이 필요합니다."] }],
    diagnostics: diag("secure upload rendering", "다른 g_idx/file id로 quarantined/deleted 첨부를 받거나 filename/content가 script/header로 실행된다.", "direct webroot URL/direct EL과 client ids를 신뢰하고 download authorization/context encoding을 적용하지 않았습니다.", "opaque file lookup+owner/state auth, safe headers/origin와 context encoders/password-free model을 적용합니다."),
    expertNotes: ["Opaque identifiers reduce guessing but do not replace authorization on every file download.", "Serving user-controlled content from the application origin can turn a file validation miss into a session-compromising web attack."],
    trace: { className: "SecureDownloadDecision", title: "file/owner/state/type에 따라 download/inline/deny를 판정합니다", purpose: "storage existence가 곧 public 접근이 되지 않게 합니다.", cases: [{ input: "READY_OWNER_SAFE_IMAGE", decision: "INLINE_ISOLATED", evidence: "headers+origin" }, { input: "READY_OWNER_OTHER_TYPE", decision: "ATTACHMENT", evidence: "nosniff" }, { input: "QUARANTINED_OR_FORBIDDEN", decision: "404", evidence: "deny-existence" }], defaultDecision: "404", defaultEvidence: "unknown-file", sourceRefs: ["mvc07-one-jsp", "mvc07-error-jsp", "mvc07-list-jsp", "owasp-authorization", "owasp-xss", "owasp-csrf", "owasp-file-upload"] },
  },
  {
    id: "mvc07-regression-chaos-operations", title: "multipart evolution을 synthetic security·partial-failure·reconciliation·capacity tests로 release합니다", lead: "정상 작은 이미지 업로드 한 번이 아니라 crash point·악성 file·동시 replacement·orphan cleanup과 운영 budget을 증명합니다.",
    explanations: ["static audit는 closure21, route/mapper parity, filename/MIME/magic/write/delete/order/EL/CSRF shape를 외부 실행 없이 검증합니다.", "JDK unit은 type/name/limit/lifecycle/DB-storage pair/replace decisions를 warning0 exact output으로 검증합니다.", "container tests는 multipart boundary, missing/duplicate parts, limits, slow/abort와 temp cleanup/status를 synthetic streams로 확인합니다.", "file security tests는 traversal names, double extensions, MIME mismatch, magic/polyglot, malformed/image bomb, CRLF/Unicode names와 scan states를 포함합니다.", "DB/storage chaos tests는 각 stage 전후 crash, DB rows0/1/many, publish/delete failure, duplicate delivery와 restart recovery를 검증합니다.", "concurrent replacement/delete tests는 version winner, loser staging cleanup과 wrong-object deletion0을 확인합니다.", "reconciler는 dry-run, owned prefix/metadata/state/age proof, batch/rate limits와 delete audit를 거쳐 production rollout합니다.", "capacity/SLO는 upload bytes/time, active streams, temp/storage quota, scan queue age, PENDING age, orphan count, failures/retries와 alert owners를 둡니다."],
    concepts: [{ term: "crash-point test", definition: "state-machine 각 durable action 직전/직후 process 중단을 강제해 restart 후 수렴을 검증하는 test입니다.", detail: ["partial states를 만듭니다.", "reconciler를 증명합니다."] }, { term: "orphan invariant", definition: "참조 없는 storage object가 허용 staging TTL 밖에 존재하지 않아야 한다는 운영 불변식입니다.", detail: ["count/age를 관측합니다.", "ownership proof가 필요합니다."] }, { term: "upload SLO", definition: "허용 file의 성공/processing latency와 scan/pending/orphan/cleanup reliability에 대한 사용자·운영 목표입니다.", detail: ["용량 budget을 포함합니다.", "type/size별로 나눕니다."] }],
    diagnostics: diag("multipart release", "정상 tests는 통과하지만 재시작/scan 장애 뒤 PENDING와 orphan이 누적되고 storage quota가 찬다.", "crash/reconciliation/queue-age/capacity tests와 operational ownership이 없습니다.", "stepwise fault injection, idempotent workers/reconciler, quota/SLO/alerts와 safe cleanup runbook을 release gate로 둡니다."),
    expertNotes: ["Cleanup automation is destructive; begin with read-only inventory, ownership proofs, dry-run reports and bounded batches.", "Synthetic test corpora should be licensed/non-sensitive and must never include users' uploaded files."],
    trace: { className: "Mvc07EvidenceDecision", title: "multipart 변경 위험별 검증 계층을 선택합니다", purpose: "parser·file type·DB/storage consistency·browser delivery를 맞는 environment에서 검증합니다.", cases: [{ input: "LIMIT_POLICY", decision: "UNIT+CONTAINER", evidence: "actual-parser" }, { input: "PARTIAL_FAILURE", decision: "CHAOS_DB_STORAGE", evidence: "convergence" }, { input: "DOWNLOAD_HEADERS", decision: "HTTP_BROWSER", evidence: "origin+parser" }], defaultDecision: "FULL_UPLOAD_MATRIX", defaultEvidence: "unclassified-risk", sourceRefs: ["jakarta-servlet", "mybatis-java-api", "owasp-file-upload", "owasp-testing"] },
  },
];

const local = (id: string, path: string, usedFor: string[], evidence: string): SessionSource => ({ id, repository: "nohssam/jspstudy", path, usedFor, evidence });
const sources: SessionSource[] = [
  local("mvc07-controller", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/controller/MyController.java", ["MultipartConfig", "routes/default"], "size thresholds와 routes8/default ErrorCommand를 확인했습니다."),
  local("mvc07-write-ok", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/WriteOKCommand.java", ["Part", "filename", "UUID", "file-before-DB"], "submitted name/realPath/write 뒤 insert/commit 순서를 확인했습니다."),
  local("mvc07-update-ok", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/UpdateOKCommand.java", ["unfinished update", "replacement design"], "empty String return만 있음을 확인했습니다."),
  local("mvc07-mapper", "guestbook2/guestbook2/src/main/resources/mapper/GuestBookMapper.xml", ["statements3", "file insert", "missing update"], "list/insert/detail3과 g_file binding을 확인했습니다."),
  local("mvc07-write-jsp", "guestbook2/guestbook2/src/main/webapp/write.jsp", ["multipart form", "file input", "CSRF gap"], "multipart POST와 file field를 확인했습니다."),
  local("mvc07-update-jsp", "guestbook2/guestbook2/src/main/webapp/update.jsp", ["multipart replacement form", "direct EL"], "old image/direct fields와 multipart POST를 확인했습니다."),
  local("mvc07-one-jsp", "guestbook2/guestbook2/src/main/webapp/oneList.jsp", ["password exposure", "direct file URL", "XSS"], "password direct EL과 img path/content direct EL을 확인했습니다."),
  local("mvc07-error-jsp", "guestbook2/guestbook2/src/main/webapp/error.jsp", ["error navigation", "status gap"], "JavaScript list redirect를 확인했습니다."),
  local("mvc07-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/Command.java", ["multipart exception contract"], "ServletException/IOException handler signature를 확인했습니다."),
  local("mvc07-list-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/ListCommand.java", ["list closure", "error"], "getList/request model을 확인했습니다."),
  local("mvc07-one-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/OneListCommand.java", ["detail model", "file/password projection"], "full GuestBookVO model을 확인했습니다."),
  local("mvc07-write-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/WriteCommand.java", ["write form route"], "write.jsp result를 확인했습니다."),
  local("mvc07-update-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/UpdateCommand.java", ["update form model"], "full row query/update view path를 확인했습니다."),
  local("mvc07-delete-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/DeleteCommand.java", ["delete route parity"], "delete.jsp result를 확인했습니다."),
  local("mvc07-delete-ok", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/DeleteOKCommand.java", ["unfinished delete", "file cleanup gap"], "empty String return만 있음을 확인했습니다."),
  local("mvc07-error-command", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/model/ErrorCommand.java", ["default route"], "error.jsp result를 확인했습니다."),
  local("mvc07-mapper-interface", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/mapper/GuestBookMapper.java", ["methods4", "XML parity"], "list/write/detail/update method signatures를 확인했습니다."),
  local("mvc07-vo", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/vo/GuestBookVO.java", ["g_file field", "password-bearing model"], "g_file을 포함한 String fields/constructors를 확인했습니다."),
  local("mvc07-dbutil", "guestbook2/guestbook2/src/main/java/org/study/guestbook2/db/DBUtil.java", ["session", "transaction"], "manual/auto-commit SqlSession provider를 확인했습니다."),
  local("mvc07-list-jsp", "guestbook2/guestbook2/src/main/webapp/list.jsp", ["list view", "direct EL"], "writer/subject/date direct EL을 확인했습니다."),
  local("mvc07-config", "guestbook2/guestbook2/src/main/resources/mybatis-config.xml", ["mapper registration", "secret hygiene"], "credential 값은 복제하지 않고 config closure만 확인했습니다."),
  { id: "mvc06-controller", repository: "nohssam/jspstudy", path: "guestbook/guestbook/src/main/java/org/study/guestbook/controller/MyController.java", usedFor: ["version route comparison"], evidence: "guestbook1 routes와 guestbook2 naming/default를 비교했습니다." },
  { id: "jakarta-servlet", repository: "Jakarta EE", path: "Servlet 6.1 specification", publicUrl: "https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1", usedFor: ["multipart", "Part", "request limits"], evidence: "공식 Jakarta Servlet specification입니다." },
  { id: "mybatis-java-api", repository: "MyBatis", path: "Java API", publicUrl: "https://mybatis.org/mybatis-3/java-api.html", usedFor: ["transaction", "mapper", "commit"], evidence: "공식 MyBatis Java API입니다." },
  { id: "owasp-file-upload", repository: "OWASP", path: "File Upload Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html", usedFor: ["names", "types", "limits", "storage", "scan"], evidence: "OWASP file upload 방어 지침입니다." },
  { id: "owasp-path-traversal", repository: "OWASP", path: "Path Traversal", publicUrl: "https://owasp.org/www-community/attacks/Path_Traversal", usedFor: ["root containment", "filename"], evidence: "OWASP path traversal 자료입니다." },
  { id: "owasp-authorization", repository: "OWASP", path: "Authorization Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", usedFor: ["download authorization", "IDOR"], evidence: "OWASP authorization 지침입니다." },
  { id: "owasp-xss", repository: "OWASP", path: "Cross Site Scripting Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html", usedFor: ["display filename/content", "download origin"], evidence: "OWASP XSS 방어 지침입니다." },
  { id: "owasp-csrf", repository: "OWASP", path: "CSRF Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html", usedFor: ["upload/update/delete mutation"], evidence: "OWASP CSRF 방어 지침입니다." },
  { id: "owasp-testing", repository: "OWASP", path: "Web Security Testing Guide", publicUrl: "https://owasp.org/www-project-web-security-testing-guide/", usedFor: ["multipart/authorization/browser security tests"], evidence: "OWASP 공식 web security testing guide입니다." },
];

const session = buildMvcSession({
  inventoryId: "mvc-07-guestbook2-multipart-evolution", order: 7, title: "방명록2와 multipart 파일 진화", subtitle: "Part upload를 filename/type/limits/quarantine/lifecycle, DB-file consistency·replacement·secure download·chaos/reconciliation까지 완성합니다.", level: "전문가", estimatedMinutes: 1200,
  coreQuestion: "사용자 file을 안전하게 검증·저장·교체·삭제·제공하면서 DB와 storage가 부분 실패해도 orphan/손실/권한 우회 없이 최종 일관성에 수렴하려면 어떤 상태와 증거가 필요할까요?",
  summary: "inventory8과 실행 closure21을 읽었습니다. routes8/default1, MultipartConfig1/forms2/Part1/submitted-name1/UUID1/getRealPath1/write1, file write-before-session1, commit1, mapper interface4/XML3, empty mutation handlers2, MIME/magic/delete0, direct EL18/CSRF0입니다. 실제 upload/DB/user file/credential은 사용·출력하지 않았습니다. version parity, multipart budgets, filename/path/storage key, type/magic/quarantine, file lifecycle/authorized download, DB-storage saga/outbox/reconciliation, replacement semantics, inherited password/XSS/CSRF controls와 chaos/operations evidence를 10장으로 완성합니다.",
  objectives: ["guestbook1→2 route/CRUD/security/storage parity를 감사한다.", "multipart part/bytes/time/temp/concurrency budgets를 설계한다.", "submitted filename과 random opaque storage key를 분리한다.", "extension/MIME/magic/decoder/scan/quarantine을 결합한다.", "file metadata와 download authorization/lifecycle을 구현한다.", "DB/storage partial failure를 staging/outbox/compensation/reconciliation으로 수렴시킨다.", "KEEP/REPLACE/REMOVE와 optimistic version file update를 구현한다.", "password-free model, CSRF, contextual encoding과 safe download headers를 계승한다.", "multipart/security/chaos/capacity tests와 safe cleanup operations를 설계한다."],
  prerequisites: [{ title: "방명록 CRUD 보안", reason: "password hashing, CSRF, object authorization, stored-XSS와 soft-delete lifecycle을 file routes에도 적용합니다.", sessionSlug: "mvc-06-guestbook-crud-security" }, { title: "책 쓰기와 트랜잭션", reason: "DB transaction·affected rows·idempotency·partial failure를 storage dual write로 확장합니다.", sessionSlug: "mvc-03-book-write-transaction" }],
  keywords: ["multipart/form-data", "Part", "MultipartConfig", "file size", "path traversal", "storage key", "MIME", "magic bytes", "polyglot", "quarantine", "file lifecycle", "object storage", "partial failure", "compensation", "outbox", "reconciliation", "authorized download"], topics,
  lab: { title: "Crash-safe Guestbook attachment pipeline", scenario: "원본 file-before-DB webroot write를 private staging, scan, metadata/outbox와 authorized download pipeline으로 재설계하고 update/delete parity를 복구합니다.", setup: ["synthetic safe/mismatch/polyglot/oversize/traversal/slow files만 사용합니다.", "ephemeral DB, owned temp/object namespace와 fake/isolated scanner를 준비합니다.", "DB/storage/file lifecycle state-pair와 crash points를 표로 만듭니다."], steps: ["closure21/parity static audit를 실행합니다.", "proxy/container/app multipart budgets와 bounded streaming을 구현합니다.", "opaque random storage key와 safe display filename metadata를 분리합니다.", "extension/MIME/magic/decoder limits 후 quarantine scan을 적용합니다.", "file metadata STAGED/QUARANTINED/PENDING/READY/TOMBSTONED states를 migration합니다.", "DB transaction에 guestbook/file metadata/outbox를 commit하고 worker가 publish/finalize합니다.", "KEEP/REPLACE/REMOVE와 versioned reference switch/deferred cleanup을 구현합니다.", "password-free model, CSRF/authz/context encoding/safe download gateway를 적용합니다.", "crash-at-each-step, concurrent replacement, orphan reconciler dry-run과 security tests를 실행합니다.", "quota/SLO/scan queue/pending/orphan alerts, retention/backup/incident/rollback runbook을 완성합니다."], expectedResult: ["submitted filename은 physical path/object key가 되지 않습니다.", "invalid/quarantined/deleted/forbidden files는 public response에서 접근 불가합니다.", "DB/storage 어느 단계 실패·재시작에서도 states가 retry/cleanup/alert로 수렴합니다.", "update/delete parity가 복구되고 concurrent replacement가 wrong file을 삭제하지 않습니다.", "password/credential/user file bytes는 public evidence/log에 없습니다."], cleanup: ["ephemeral DB/container와 owned test storage prefix/temp files만 제거합니다.", "reconciler dry-run 후 test-owned keys만 bounded batch로 삭제합니다.", "PENDING/quarantine/orphan/open-stream/temp/pool/thread leak0과 artifact redaction을 확인합니다."], extensions: ["S3-compatible object storage의 presigned upload/download와 callback trust를 설계합니다.", "multipart resume/chunk upload의 idempotent assembly/hash verification을 추가합니다.", "CDR/image re-encode worker와 separate download origin을 배포합니다.", "legal hold/versioning/retention과 disaster restore에서 DB-object reconciliation을 검증합니다."] },
  exercises: [
    { difficulty: "따라하기", prompt: "submitted filename과 storage key를 분리하는 validation policy를 구현하세요.", requirements: ["opaque random key를 생성합니다.", "path separators/control/length를 거부합니다.", "display name은 metadata로만 둡니다.", "root containment을 검증합니다.", "HTML/header context encoding을 구분합니다."], hints: ["UUID prefix 뒤 raw filename도 unsafe할 수 있습니다."], expectedOutcome: "user filename이 storage path를 제어하지 않습니다.", solutionOutline: ["storage key·display name·canonical media type을 별도 value로 만듭니다."] },
    { difficulty: "응용", prompt: "DB/storage partial failure state machine과 reconciler를 구현하세요.", requirements: ["STAGED/PENDING/READY/TOMBSTONED를 둡니다.", "outbox/idempotency key를 사용합니다.", "각 step crash를 재현합니다.", "owned+age+state proof 뒤 cleanup합니다.", "unknown pair는 quarantine/alert합니다."], hints: ["DB transaction은 filesystem/object store를 rollback하지 못합니다."], expectedOutcome: "crash/retry 후 orphan과 missing references가 eventual invariant로 수렴합니다.", solutionOutline: ["durable state pair→allowed action table→idempotent worker 순으로 구현합니다."] },
    { difficulty: "설계", prompt: "production attachment service ADR/runbook을 작성하세요.", requirements: ["multipart/type/name/size/scan policies를 포함합니다.", "storage location/encryption/authorization/headers를 정합니다.", "DB/file saga, replacement/delete/retention을 포함합니다.", "security/chaos/capacity/restore matrix를 만듭니다.", "quota/SLO/alerts/reconciler safety를 수치화합니다.", "security-safe rollback/incident owners를 정합니다."], hints: ["cleanup automation 자체가 data-loss 위험입니다."], expectedOutcome: "보안·정합성·운영·복구 근거가 연결된 attachment architecture가 완성됩니다.", solutionOutline: ["threat→limits→states→consistency→delivery→operations 순으로 작성합니다."] },
  ],
  nextSessions: ["spring-core-01-ioc-container-bean"], sources,
  sourceCoverage: { filesRead: 21, filesUsed: 21, uncoveredNotes: ["inventory8과 controller가 참조하는 commands/mapper/VO/DBUtil/list/config closure13을 합쳐21 files를 모두 읽고 사용했습니다.", "CSS assets는 presentation styling이며 multipart/DB/file lifecycle closure에 필요하지 않아 coverage에서 제외했습니다.", "실제 upload, user file bytes, DB/credential, webroot/object storage write는 수행하지 않았고 정적 shape/hash만 확인했습니다."] },
});

export default session;
