import type { DetailedCodeExample, DiagnosticCase, SessionSource } from "../../types";
import { buildMvcSession, type MvcTopicSpec } from "./mvc-01-mybatis-config-mapper.ts";

const diag = (area: string, symptom: string, cause: string, fix: string): DiagnosticCase[] => [
  { symptom, likelyCause: cause, checks: [`${area}의 actor→CSRF→input→row lookup→password verify→authorization→DML→commit 순서를 확인합니다.`, "public response/HTML/log/trace/cache에 password·hash·session·content가 없는지 검사합니다.", "rows0/1/many, wrong password, replay와 concurrent mutation을 분리합니다."], fix, prevention: `${area}의 fail-closed decision table과 real container/DB security regression suite를 유지합니다.` },
  { symptom: "순수 보안 decision 예제는 통과하지만 실제 JSP/MyBatis에서 취약하다.", likelyCause: "JDK state machine은 hashing library, Servlet session/CSRF, mapper SQL, browser HTML parser와 DB concurrency를 실행하지 않습니다.", checks: ["unit과 integration 범위를 구분합니다.", "실제 rendered DOM과 response headers를 검사합니다.", "production-like DB/hash policy를 격리 환경에서 검증합니다."], fix: "운영 credential/data 없이 password hasher·container·MyBatis·browser security integration tests를 추가합니다.", prevention: "source audit, policy unit, integration, DAST와 dependency/security review를 독립 gates로 둡니다." },
];

const audit: DetailedCodeExample = {
  id: "powershell-mvc06-original-security-audit", title: "방명록 CRUD inventory8·보안 폐쇄19의 password·XSS·CSRF·soft-delete shape를 감사합니다", language: "powershell", filename: "verify-original-mvc06.ps1", purpose: "사용자 데이터·DB·브라우저를 실행하지 않고 client-side password exposure, server verification/hash 부재와 direct EL surface를 exact하게 보존합니다.",
  code: String.raw`param([Parameter(Mandatory)][string]$SourceRoot)
$ErrorActionPreference='Stop'
$inventory=@(
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteOKCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateOKCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteOKCommand.java',
 'guestbook/guestbook/src/main/resources/mapper/GuestBookMapper.xml',
 'guestbook/guestbook/src/main/webapp/write.jsp',
 'guestbook/guestbook/src/main/webapp/update.jsp',
 'guestbook/guestbook/src/main/webapp/list.jsp',
 'guestbook/guestbook/src/main/webapp/delete.jsp'
)
$closure=@(
 'guestbook/guestbook/src/main/java/org/study/guestbook/controller/MyController.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/Command.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/ListCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/OneListCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteFormCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateFormCommand.java',
 'guestbook/guestbook/src/main/webapp/onelist.jsp',
 'guestbook/guestbook/src/main/java/org/study/guestbook/mapper/GuestBookMapper.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/vo/GuestBookVO.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/db/DBUtil.java',
 'guestbook/guestbook/src/main/resources/mybatis-config.xml'
)
$rels=@($inventory+$closure);$files=@($rels|ForEach-Object{Get-Item -LiteralPath (Join-Path $SourceRoot $_)})
if($files.Count-ne19){throw 'security closure drift'}
$before=@{};foreach($file in $files){$before[$file.FullName]=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}
function Active([string]$text){$value=[regex]::Replace(([regex]::Replace($text,'(?s)<!--.*?-->','')),'(?s)<%--.*?--%>','');$value=[regex]::Replace(([regex]::Replace($value,'(?s)/\*.*?\*/','')),'(?m)//.*$','');return $value}
function Count([string]$value,[string]$pattern){([regex]::Matches($value,$pattern,[Text.RegularExpressions.RegexOptions]::IgnoreCase)).Count}
$inv=Active (($files[0..7]|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine)
$all=Active (($files|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine)
$params=Count $inv 'getParameter\s*\(';$dml=Count $inv 'mapper\.(?:insertGuestBook|updateGuestBook|deleteGuestBook)\s*\(';$commits=Count $inv '\.commit\s*\('
$soft=Count $inv 'g_active\s*=\s*1';$activeFilter=Count $inv 'g_active\s*=\s*0';$directEl=Count $inv '\$\{';$cOut=Count $inv '<c:out\b';$csrf=Count $inv '(?:csrf|_token)'
$hashApis=Count $all '(?:Argon2|BCrypt|PasswordEncoder|MessageDigest)';$clientSecrets=Count $all '\$\{(?:g_pwd|gvo\.g_pwd)\}';$passwordBind=Count $inv '#\{g_pwd\}'
$serverVerify=Count $all '(?:passwordMatcher|verifyPassword|matchesPassword)\s*\(';$forms=Count $inv '(?m)^\s*<form[^\r\n]*method="post"'
if($params-ne11-or$dml-ne3-or$commits-ne3-or$soft-ne1-or$activeFilter-ne1-or$directEl-ne15-or$cOut-ne0-or$csrf-ne0-or$hashApis-ne0-or$clientSecrets-ne3-or$passwordBind-ne1-or$serverVerify-ne0-or$forms-ne3){throw 'source shape drift'}
foreach($file in $files){if((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash-cne$before[$file.FullName]){throw 'source hash drift'}}
"files=19|inventory=8|parameters=11|dmlCalls=3|commits=3|softDeleteWrites=1|activeFilters=1|postForms=3|directEL=15|cOut=0|csrfTokens=0|hashApis=0|serverPasswordVerify=0|clientPasswordEL=3|passwordSqlBinds=1|hashes=19/19"
"execution=static-only|db=not-contacted|user-data=not-read|password-values=not-output"`,
  walkthrough: [{ lines: "1-27", explanation: "inventory8과 password/data flow를 설명하는 직접 closure11을 합쳐19 files를 고정합니다." }, { lines: "28-33", explanation: "hash를 보존하고 Java/XML/JSP comments를 제거합니다." }, { lines: "34-40", explanation: "DML/transaction/soft-delete/EL/CSRF/password hash·verification·client exposure counts를 분리합니다." }, { lines: "41-43", explanation: "exact shape와 source 불변성, 사용자/비밀번호 값 미사용을 확인합니다." }],
  run: { environment: ["PowerShell 7+", "D:/dev/jspstudy source root", "정적 읽기만", "DB/Servlet/browser/user data 불필요"], command: "pwsh -NoProfile -File verify-original-mvc06.ps1 -SourceRoot D:/dev/jspstudy" },
  output: { value: "files=19|inventory=8|parameters=11|dmlCalls=3|commits=3|softDeleteWrites=1|activeFilters=1|postForms=3|directEL=15|cOut=0|csrfTokens=0|hashApis=0|serverPasswordVerify=0|clientPasswordEL=3|passwordSqlBinds=1|hashes=19/19\nexecution=static-only|db=not-contacted|user-data=not-read|password-values=not-output", explanation: ["CRUD DML3/commit3과 active flag 기반 soft delete는 존재합니다.", "password hash/server verification은0이고 password EL이 update/delete/detail flow에서3번 client로 이동합니다.", "inventory JSP direct EL15, c:out0, CSRF0이므로 stored XSS와 forged mutation 경계를 교정해야 합니다."] },
  experiments: [{ change: "JSP client password comparison을 제거합니다.", prediction: "clientPasswordEL3 audit가 drift합니다.", result: "개선본에서는 server-side hash verify와 public model password absence를 검증합니다." }, { change: "c:out/context encoder를 적용합니다.", prediction: "cOut0이 실패합니다.", result: "rendered DOM XSS test와 함께 별도 개선 evidence로 남깁니다." }, { change: "command/JSP를 실제 실행합니다.", prediction: "credential/DB/user password/content에 접근할 수 있습니다.", result: "audit는 source/hash/count만 사용합니다." }],
  sourceRefs: ["mvc06-write-ok", "mvc06-update-ok", "mvc06-delete-ok", "mvc06-mapper", "mvc06-write-jsp", "mvc06-update-jsp", "mvc06-list-jsp", "mvc06-delete-jsp", "mvc06-controller", "mvc06-command", "mvc06-list-command", "mvc06-one-command", "mvc06-delete-form", "mvc06-update-form", "mvc06-one-jsp", "mvc06-mapper-interface", "mvc06-vo", "mvc06-dbutil", "mvc06-config"],
};

const topics: MvcTopicSpec[] = [
  {
    id: "mvc06-original-crud-security-audit", title: "원본 CRUD와 password/XSS/CSRF data flow를 폐쇄19에서 정확히 감사합니다", lead: "동작하는 commit·soft delete를 보존하면서 client password verification과 stored-XSS surface를 숨기지 않습니다.",
    explanations: ["inventory8은 WriteOK/UpdateOK/DeleteOK, mapper XML과 write/update/list/delete JSP입니다.", "controller/Command/List/One/DeleteForm/UpdateForm/onelist.jsp/mapper interface/VO/DBUtil/config를 따라가면 security closure는19입니다.", "세 mutation은 active parameters11(update의 g_pwd read 한 줄은 comment), mapper DML3와 commit3을 사용하고 delete는 `g_active=1`, list는 `g_active=0`으로 soft delete합니다.", "Write는 password를 그대로 VO/`#{g_pwd}`에 전달하며 hash API는0입니다.", "Update/Delete는 server password 검증이0이고 JSP JavaScript가 `${gvo.g_pwd}`/`${g_pwd}`와 user input을 비교합니다.", "detail의 hidden password까지 포함하면 password EL exposure3이라 browser source/devtools/DOM에 secret이 전달됩니다.", "inventory JSP direct EL15, c:out0, CSRF token0으로 stored XSS와 forged mutation 방어가 없습니다.", "audit는 source shape/hash만 읽고 credential/password/user content/DB/browser를 실행하거나 출력하지 않습니다."],
    concepts: [{ term: "client-side secret exposure", definition: "검증을 위해 password/hash/token을 HTML/JavaScript/DOM에 보내 공격자가 읽을 수 있게 되는 설계 결함입니다.", detail: ["hidden도 공개입니다.", "server에서 검증해야 합니다."] }, { term: "security data flow", definition: "민감 값이 입력·memory·DB·model·HTML·log를 거치는 source-to-sink 경로입니다.", detail: ["closure를 따라갑니다.", "최소화/차단 지점을 찾습니다."] }, { term: "defense in depth", definition: "한 방어 실패가 곧 침해가 되지 않도록 validation·hash·authorization·CSRF·encoding·least privilege를 겹치는 전략입니다.", detail: ["책임은 서로 다릅니다.", "대체 관계가 아닙니다."] }],
    diagnostics: diag("원본 CRUD security", "browser HTML/source에서 다른 사용자의 방명록 password가 보인다.", "DB plaintext password를 VO/request attribute/hidden/JavaScript template으로 전달해 client가 비교합니다.", "password는 adaptive hash만 저장하고 server-side verify 후 public projection에서 완전히 제거합니다."),
    expertNotes: ["A hidden input is disclosure, not protection; every value sent to the browser is attacker-readable and modifiable.", "Static counts identify dangerous flows, while runtime tests must prove that rendered responses and logs contain no password material."], customExample: audit,
  },
  {
    id: "mvc06-threat-model-trust-boundaries", title: "방명록 CRUD의 actor·asset·entry point·abuse case를 threat model로 만듭니다", lead: "작성자 password, 본문, row identity와 mutation 권한이 browser·Servlet·DB 경계를 어떻게 건너는지 먼저 그립니다.",
    explanations: ["assets는 password verifier, email/content PII, entry integrity, author identity, session/CSRF와 audit evidence입니다.", "entry points는 list/detail URLs, write/update/delete forms, hidden cmd/g_idx, password field와 stored content rendering입니다.", "attacker는 unauthenticated web user, malicious author, CSRF site, compromised account와 insider/read-only DB 접근을 포함합니다.", "trust boundary는 browser↔HTTP, controller↔service, service↔mapper/DB, model↔JSP, app↔logs/backups입니다.", "abuse cases는 password theft/reuse, forged g_idx, CSRF mutation, stored XSS, mass assignment, enumeration, brute force와 soft-delete bypass입니다.", "각 abuse case에 prevention, detection, response owner와 test evidence를 연결합니다.", "password를 content authorization에 쓰더라도 account password와 분리된 resource secret 정책·recovery/rotation을 정합니다.", "threat model은 코드 변화마다 data flow, new field/route, trust boundary와 residual risk를 업데이트합니다."],
    concepts: [{ term: "threat model", definition: "보호 자산·공격자·entry point·trust boundary·abuse case·mitigation을 구조화한 보안 설계 자료입니다.", detail: ["코드 전에 만듭니다.", "test와 owner를 연결합니다."] }, { term: "trust boundary", definition: "데이터의 신뢰 수준·owner·검증 책임이 바뀌는 경계입니다.", detail: ["browser 입력은 untrusted입니다.", "DB 값도 HTML에는 untrusted입니다."] }, { term: "abuse case", definition: "정상 기능을 공격자가 악용해 자산을 훼손/노출하는 구체 시나리오입니다.", detail: ["기능 use case와 함께 봅니다.", "재현 test를 만듭니다."] }],
    diagnostics: diag("threat model", "기능 test는 통과하지만 hidden g_idx/password 변조와 stored payload 공격이 누락된다.", "정상 사용자 흐름만 모델링하고 attacker-controlled entry/data sinks를 열거하지 않았습니다.", "asset/data-flow/abuse-case 기반 security acceptance matrix를 만듭니다."),
    expertNotes: ["Database-originated text remains untrusted at an HTML rendering boundary because an attacker may have stored it earlier.", "A resource password is an authorization credential and needs brute-force, lifecycle and recovery controls even if it is not an account password."],
    trace: { className: "GuestbookThreatDecision", title: "data flow를 trust boundary별 검증 owner로 분류합니다", purpose: "DB stored data와 hidden fields를 신뢰하지 않게 합니다.", cases: [{ input: "FORM_G_IDX", decision: "VALIDATE_AUTHZ", evidence: "client-controlled" }, { input: "DB_CONTENT_TO_HTML", decision: "ENCODE", evidence: "stored-untrusted" }, { input: "PASSWORD_TO_LOG", decision: "DROP", evidence: "secret" }], defaultDecision: "DENY", defaultEvidence: "unclassified-flow", sourceRefs: ["mvc06-controller", "mvc06-one-jsp", "owasp-threat-modeling"] },
  },
  {
    id: "mvc06-create-validation-password-hashing", title: "작성 요청을 검증하고 password를 adaptive salted hash로만 저장합니다", lead: "plaintext `g_pwd` persistence를 server-side password service와 rehash 가능한 verifier record로 바꿉니다.",
    explanations: ["writer/subject/email/content는 server length/format/Unicode policy와 DB constraints를 통과해야 합니다.", "password는 전송 중 TLS로 보호하고 request lifetime 이후 raw char/bytes를 보관·로그·view model에 넣지 않습니다.", "저장에는 Argon2id, scrypt, bcrypt 또는 PBKDF2 같은 검증된 adaptive password hashing scheme을 library로 사용합니다.", "각 password마다 random salt를 library format에 포함하고 algorithm/version/cost metadata와 hash만 저장합니다.", "pepper를 쓰면 DB와 분리된 secret manager에 두고 rotation/compromise migration 전략을 문서화합니다.", "work factor는 운영 hardware에서 login/write latency와 DoS budget을 측정해 정기적으로 조정하며 hard-coded 예시 수치를 맹신하지 않습니다.", "성공 verify 시 오래된 algorithm/cost를 current policy로 rehash하는 점진 migration을 지원합니다.", "generic failure, per-resource/actor/IP rate limiting과 telemetry로 brute force와 enumeration을 줄입니다."],
    concepts: [{ term: "adaptive password hash", definition: "공격 비용을 높이도록 memory/time work factor를 조정할 수 있는 password 전용 one-way KDF입니다.", detail: ["빠른 일반 hash를 쓰지 않습니다.", "library 검증을 사용합니다."] }, { term: "salt", definition: "각 password마다 생성해 hash 입력에 포함하는 공개 random 값으로 동일 password의 hash를 다르게 만듭니다.", detail: ["hash format에 저장합니다.", "unique random이어야 합니다."] }, { term: "pepper", definition: "DB와 분리한 secret을 hashing/verification에 추가하는 선택적 방어입니다.", detail: ["secret manager에 둡니다.", "rotation 계획이 필요합니다."] }],
    diagnostics: diag("password storage", "DB read-only 노출만으로 모든 방명록 password를 즉시 알 수 있다.", "plaintext 또는 빠른 일반 hash를 저장하고 adaptive salted password hashing을 사용하지 않았습니다.", "검증된 password hashing library, per-password salt, tuned cost와 rehash-on-success를 적용하고 기존 secrets를 폐기/migrate합니다."),
    expertNotes: ["Do not invent a password hashing construction from MessageDigest; use a maintained password-hashing library and current policy guidance.", "Hashing mitigates database disclosure but does not replace TLS, rate limiting, authorization or secret-free client models."],
    trace: { className: "PasswordStorageDecision", title: "password representation을 저장/거부/rehash로 판정합니다", purpose: "plaintext와 빠른 digest를 persistence에서 배제합니다.", cases: [{ input: "ADAPTIVE_CURRENT", decision: "STORE", evidence: "salted-versioned" }, { input: "ADAPTIVE_OLD_COST", decision: "VERIFY_REHASH", evidence: "policy-upgrade" }, { input: "PLAINTEXT", decision: "REJECT", evidence: "secret-exposure" }], defaultDecision: "REJECT", defaultEvidence: "unknown-hash-format", sourceRefs: ["mvc06-write-ok", "mvc06-mapper", "mvc06-vo", "owasp-password"] },
  },
  {
    id: "mvc06-server-password-verification", title: "수정·삭제 password를 server에서 검증하고 client에는 verifier를 보내지 않습니다", lead: "hidden/JavaScript 비교를 없애고 row lookup·hash verify·authorization·DML을 안전한 transaction flow로 묶습니다.",
    explanations: ["browser는 g_idx와 candidate password만 TLS POST로 보내고 stored hash/plaintext/password-derived data를 절대 받지 않습니다.", "server는 authorization-aware row에서 hash만 조회하고 maintained library verify를 사용합니다.", "hash format이 malformed/unsupported여도 raw exception이나 user enumeration을 노출하지 않고 generic failure로 처리합니다.", "verify timing은 library가 담당하고 app은 String equals나 client comparison을 사용하지 않습니다.", "password failure는 mutation0, session/CSRF status와 분리된 bounded audit/rate-limit event를 남깁니다.", "verify 뒤 DML까지 row version/status/tenant를 predicate에 포함해 검증-사용 사이 race를 줄입니다.", "성공 시 current cost가 아니면 같은 protected transaction 또는 별도 안전 flow에서 hash를 upgrade합니다.", "detail/list/update/delete view model·HTML·cache·logs·metrics에는 hash/password field가 존재하지 않는 negative assertions를 둡니다."],
    concepts: [{ term: "server-side verification", definition: "candidate secret과 stored password hash를 trusted application boundary에서 library로 비교하는 처리입니다.", detail: ["client에 verifier를 보내지 않습니다.", "mutation 전 수행합니다."] }, { term: "TOCTOU", definition: "권한/상태를 검사한 시점과 사용/변경 시점 사이에 대상이 바뀌어 검증이 무효화되는 race입니다.", detail: ["transaction/predicate로 줄입니다.", "version/status를 포함합니다."] }, { term: "negative disclosure assertion", definition: "response/model/log/cache에 특정 민감 field가 절대 나타나지 않음을 자동 검증하는 test입니다.", detail: ["성공/실패 모두 검사합니다.", "hash도 secret-like data입니다."] }],
    diagnostics: diag("password verification", "비밀번호를 모르는 공격자가 hidden stored password를 그대로 제출해 삭제한다.", "client-side equality를 authorization으로 사용해 공격자가 expected value와 request를 모두 제어합니다.", "server hash verify와 actor/row/status/version authorization predicate를 mutation transaction에 둡니다."),
    expertNotes: ["Sending a password hash to the browser is also unsafe because it can become an offline guessing verifier.", "Constant-time comparison is one detail; adaptive hashing, rate limiting and generic responses dominate practical password verification security."],
    trace: { className: "PasswordVerifyDecision", title: "candidate/hash/row 상태를 mutation 허용으로 변환합니다", purpose: "client comparison과 hash disclosure를 제거합니다.", cases: [{ input: "VALID_CURRENT_ACTIVE", decision: "ALLOW_DML", evidence: "server-verify" }, { input: "WRONG_PASSWORD", decision: "DENY", evidence: "generic+rate-limit" }, { input: "VALID_STALE_ROW", decision: "409", evidence: "version-status" }], defaultDecision: "DENY", defaultEvidence: "invalid-verifier-state", sourceRefs: ["mvc06-update-ok", "mvc06-delete-ok", "mvc06-update-jsp", "mvc06-delete-jsp", "mvc06-one-jsp", "owasp-authentication", "owasp-password"] },
  },
  {
    id: "mvc06-update-authz-csrf-mass-assignment", title: "수정은 CSRF·object authorization·field allowlist·optimistic lock를 모두 통과시킵니다", lead: "password 성공 하나를 모든 field/row 변경 권한으로 확대하지 않고 mutation intent와 resource freshness를 검증합니다.",
    explanations: ["POST update는 session-bound CSRF token과 SameSite defense-in-depth를 검증합니다.", "g_idx, role/active/password hash 같은 hidden/extra parameters는 untrusted이며 update command allowlist에 포함하지 않습니다.", "actor/resource/password policy를 server에서 확인하고 tenant/status/version을 UPDATE predicate에 포함합니다.", "writer/subject/email/content만 field별 validation하고 null/absent/empty 의미를 명시합니다.", "affected rows1만 commit하고0은 not-found/forbidden/stale conflict 정책, many는 rollback/security alert입니다.", "expected version으로 lost update를 감지하고 conflict UI는 current/submitted changes를 context-safe하게 보여 줍니다.", "성공은 commit 후303 PRG, validation은 safe redisplay, auth failure는 generic status와 bounded rate-limit event로 처리합니다.", "CSRF, password, object authorization, validation, version은 서로 다른 공격/정합성 문제를 막으므로 하나로 대체하지 않습니다."],
    concepts: [{ term: "object-level authorization", definition: "actor가 특정 g_idx resource를 수정할 권한이 있는지 서버가 매 요청 확인하는 정책입니다.", detail: ["CSRF와 다릅니다.", "hidden id를 신뢰하지 않습니다."] }, { term: "field allowlist", definition: "update command가 변경할 수 있는 field만 명시적으로 선택하는 mass-assignment 방어입니다.", detail: ["active/hash를 제외합니다.", "unknown을 거부/기록합니다."] }, { term: "optimistic version", definition: "편집 시작 시 본 version을 UPDATE WHERE에 포함해 concurrent stale write를 탐지하는 값입니다.", detail: ["rows0 conflict를 만듭니다.", "권한 token은 아닙니다."] }],
    diagnostics: diag("secure update", "공격자가 extra g_active/g_pwd field나 다른 g_idx를 보내 상태를 바꾼다.", "request를 VO에 자동 결합하고 field/object authorization allowlist를 적용하지 않았습니다.", "dedicated UpdateCommand fields, server row auth/password verify와 tenant/status/version predicate를 사용합니다."),
    expertNotes: ["CSRF proves request intent relative to a session, not authorization to mutate a particular guestbook row.", "Optimistic locking detects concurrent edits but does not validate the semantic legitimacy of the submitted fields."],
    trace: { className: "SecureUpdateDecision", title: "update request gate 결과를 execute/status로 판정합니다", purpose: "CSRF·password·object auth·version의 독립 책임을 명확히 합니다.", cases: [{ input: "TOKEN_AUTHZ_PASSWORD_VERSION", decision: "UPDATE", evidence: "allowlisted-fields" }, { input: "NO_CSRF", decision: "403", evidence: "request-intent" }, { input: "STALE_VERSION", decision: "409", evidence: "reload-merge" }], defaultDecision: "DENY", defaultEvidence: "incomplete-security-gates", sourceRefs: ["mvc06-update-ok", "mvc06-update-jsp", "owasp-csrf", "owasp-authorization", "owasp-mass-assignment"] },
  },
  {
    id: "mvc06-soft-delete-lifecycle", title: "soft delete를 password 검증·authorization·status/version predicate와 원자적으로 처리합니다", lead: "`g_active=1` 한 문장을 보존·복구·조회 scope·audit까지 포함한 lifecycle transition으로 확장합니다.",
    explanations: ["원본 delete는 physical DELETE 대신 active flag를1로 바꾸고 list는0만 조회하는 soft-delete 출발점을 보여 줍니다.", "삭제 command는 candidate password/actor/CSRF를 검증하고 `id + active=0 + version + tenant` predicate로 exactly one transition을 수행합니다.", "rows0은 already deleted/stale/not-found/forbidden 중 하나이며 existence disclosure 정책에 따라 동일 응답으로 처리할 수 있습니다.", "deletedAt/deletedBy/reason/version을 기록해 audit/recovery/retention 요구를 충족합니다.", "list뿐 아니라 detail/update/search/count/unique constraints가 deleted scope를 일관되게 적용해야 합니다.", "restore는 별도 authorization, uniqueness conflict와 retention expiry를 검증하고 version을 증가시킵니다.", "purge는 background privileged job, legal hold, backup/replica와 cascade/FK 정책을 따르며 user request가 직접 physical delete하지 않습니다.", "concurrent delete/update/restore를 실제 DB에서 겹쳐 허용된 상태 전이와 exactly-one winner를 확인합니다."],
    concepts: [{ term: "soft-delete state machine", definition: "ACTIVE→DELETED→RESTORED/PURGED처럼 허용된 lifecycle 전이를 명시한 모델입니다.", detail: ["flag보다 강합니다.", "version/audit를 포함합니다."] }, { term: "default scope", definition: "일반 query/mutation이 deleted rows를 자동 제외하도록 적용하는 일관된 predicate 정책입니다.", detail: ["누락을 test합니다.", "privileged scope를 별도 둡니다."] }, { term: "retention", definition: "삭제 데이터와 audit/backup을 보존·복구·폐기하는 기간과 법적/제품 정책입니다.", detail: ["purge와 연결합니다.", "owner를 정합니다."] }],
    diagnostics: diag("soft delete", "목록에서는 사라졌지만 URL detail/update로 deleted row를 읽거나 바꿀 수 있다.", "active filter를 selectAll에만 적용하고 detail/update predicate에 누락했습니다.", "active/status/tenant/version default scope와 deleted-row authorization tests를 모든 mapper method에 적용합니다."),
    expertNotes: ["Soft delete is a cross-cutting lifecycle model that changes uniqueness, analytics, authorization, backup and privacy behavior.", "Do not reveal whether a guessed identifier is already deleted when existence itself is sensitive."],
    trace: { className: "SoftDeleteDecision", title: "row lifecycle 전이를 허용/충돌/거부로 판정합니다", purpose: "active flag를 authorization-aware state machine으로 만듭니다.", cases: [{ input: "ACTIVE_DELETE_AUTHORIZED", decision: "DELETED", evidence: "version+audit" }, { input: "DELETED_DELETE", decision: "IDEMPOTENT", evidence: "no-extra-change" }, { input: "DELETED_UPDATE", decision: "409", evidence: "invalid-transition" }], defaultDecision: "DENY", defaultEvidence: "unknown-lifecycle", sourceRefs: ["mvc06-delete-ok", "mvc06-mapper", "mvc06-list-command", "mvc06-one-command", "owasp-authorization"] },
  },
  {
    id: "mvc06-stored-xss-context-encoding", title: "stored XSS를 c:out·context encoder·safe URL·CSP로 차단합니다", lead: "writer/subject/email/content가 DB에서 왔다는 이유로 신뢰하지 않고 최종 HTML parser context에서 인코딩합니다.",
    explanations: ["write form에 저장된 subject/content 공격 문자열은 이후 list/detail/update/delete viewers 모두를 공격할 수 있습니다.", "HTML text node는 c:out/XML escape 또는 maintained HTML encoder를 사용합니다.", "input value attribute는 quoted attribute encoding, textarea는 text encoding, URL component는 validated id+URL encoding을 사용합니다.", "inline JavaScript template/event handler 안에는 untrusted data를 넣지 않고 data attribute/JSON script-safe channel도 context별 serializer를 사용합니다.", "rich HTML을 허용해야 하면 output encoding 대신 maintained sanitizer allowlist와 URL protocol policy를 적용합니다.", "stored pre-escaped text는 다른 context에서 unsafe하거나 double-encoding되므로 raw canonical data를 저장하고 최종 출력에서 encode합니다.", "CSP nonce/hash와 inline handler 제거는 defense-in-depth이며 output encoding의 대체재가 아닙니다.", "rendered browser/DOM tests는 payload가 text로 남고 script/event/javascript URL/DOM clobbering sink가 생기지 않는지 검사합니다."],
    concepts: [{ term: "stored XSS", definition: "공격 payload가 persistence에 저장된 뒤 다른 response에서 실행 가능한 markup/script로 렌더링되는 취약점입니다.", detail: ["쓰기와 읽기 경계를 관통합니다.", "모든 viewer를 공격합니다."] }, { term: "contextual encoding", definition: "HTML text·attribute·URL·JavaScript 등 최종 parser 문맥에 맞는 escaping을 출력 직전에 적용하는 방어입니다.", detail: ["c:out은 text 출발점입니다.", "context별 규칙이 다릅니다."] }, { term: "sanitization", definition: "일부 HTML을 허용할 때 위험 tag/attribute/protocol을 parser 기반 allowlist로 제거하는 처리입니다.", detail: ["encoding과 목적이 다릅니다.", "maintained library를 씁니다."] }],
    diagnostics: diag("stored XSS", "방명록 제목/내용을 본 관리자 browser에서 script 또는 event handler가 실행된다.", "DB stored strings를 direct EL로 HTML/attribute/JS에 삽입하고 context encoder/c:out을 사용하지 않았습니다.", "password-free view DTO를 context별 encoder로 렌더링하고 inline JS data flow 제거·CSP·DOM regression을 적용합니다."),
    expertNotes: ["Encoding belongs at the final output context; input validation alone cannot reject every legitimate character used in markup syntax.", "CSP can reduce exploit impact and provide reports, but it does not make unsafe DOM construction acceptable."],
    trace: { className: "GuestbookOutputDecision", title: "출력 sink별 encoding/sanitize/reject를 선택합니다", purpose: "direct EL을 context-aware rendering contract로 바꿉니다.", cases: [{ input: "HTML_TEXT", decision: "C_OUT", evidence: "escapeXml" }, { input: "ATTRIBUTE", decision: "ATTRIBUTE_ENCODE", evidence: "quoted" }, { input: "INLINE_JS", decision: "REJECT", evidence: "no-untrusted-script" }], defaultDecision: "REJECT", defaultEvidence: "unknown-output-context", sourceRefs: ["mvc06-list-jsp", "mvc06-update-jsp", "mvc06-delete-jsp", "mvc06-one-jsp", "jakarta-tags", "owasp-xss"] },
  },
  {
    id: "mvc06-data-minimization-logging-cache", title: "password-free projection·safe logs·cache policy로 민감 data surface를 줄입니다", lead: "secret을 잘 숨기는 것보다 애초에 query/model/response/log/cache에 들어오지 않게 설계합니다.",
    explanations: ["list/detail/update form query는 password column을 SELECT하지 않는 explicit projection을 사용합니다.", "password verification 전용 query는 id/status/version/hash만 읽고 public DTO와 type을 분리합니다.", "GuestBookVO 전체를 request/session/cache에 넣지 않고 public list/detail/form DTO로 최소화합니다.", "server logs/traces/metrics에는 password/hash/email/content/session/CSRF/raw g_idx를 기본 제외하고 stable outcome/correlation만 기록합니다.", "request body/SQL debug logging과 APM auto-capture settings가 password/content를 수집하지 않는지 환경별 검증합니다.", "HTML form/error responses와 authorization-filtered detail은 Cache-Control no-store/private를 적용하고 shared cache key에 actor scope를 포함합니다.", "backup/export/support tooling에서도 password hash와 deleted/private content 접근을 최소 권한·audit·retention으로 통제합니다.", "negative tests는 success/failure/validation/error/log/cache artifacts 전체에서 password/hash regex/known canary가0인지 검사합니다."],
    concepts: [{ term: "data minimization", definition: "목적 수행에 필요한 최소 data만 조회·전달·저장·기록하는 원칙입니다.", detail: ["projection에서 시작합니다.", "침해 범위를 줄입니다."] }, { term: "secret-free view model", definition: "password/hash/session/internal lifecycle field가 type 수준에서 존재하지 않는 rendering DTO입니다.", detail: ["accidental EL을 막습니다.", "list/detail/form을 분리합니다."] }, { term: "canary secret test", definition: "test 전용 고유 민감 값을 넣고 response/log/cache/export 어디에도 나타나지 않음을 찾는 negative 검증입니다.", detail: ["운영 secret을 쓰지 않습니다.", "artifact 전체를 검사합니다."] }],
    diagnostics: diag("data minimization", "JSP에서는 password를 숨겼지만 access log/APM/cache dump에 hash나 content가 남는다.", "query/model 전체를 통째로 전달하고 automatic logging/caching capture를 검토하지 않았습니다.", "purpose-specific projections/types와 log/cache allowlist, canary negative scan을 적용합니다."),
    expertNotes: ["Removing a password field from HTML is insufficient if the same object is serialized into sessions, traces, caches or error reports.", "Password hashes are sensitive verifiers and should be excluded from general application logs and analytics."],
    trace: { className: "SensitiveFieldDecision", title: "field를 public/auth-only/drop으로 분류합니다", purpose: "민감 값이 일반 object graph와 observability로 이동하지 않게 합니다.", cases: [{ input: "SUBJECT", decision: "PUBLIC_ENCODED", evidence: "view-purpose" }, { input: "PASSWORD_HASH", decision: "AUTH_ONLY", evidence: "verify-service" }, { input: "RAW_PASSWORD", decision: "DROP_AFTER_VERIFY", evidence: "secret-lifetime" }], defaultDecision: "DROP", defaultEvidence: "unclassified-field", sourceRefs: ["mvc06-mapper", "mvc06-vo", "owasp-password", "owasp-logging"] },
  },
  {
    id: "mvc06-transaction-prg-audit", title: "secure CRUD gate와 DML·audit·PRG를 한 transaction/outcome으로 묶습니다", lead: "password/authorization 성공과 durable mutation·audit·response를 순서대로 확정해 race와 부분 성공을 막습니다.",
    explanations: ["request validation/CSRF는 DB 전, row password/authorization/status/version은 transaction 안에서 검증합니다.", "update/delete predicate에 id+tenant/status/version을 포함하고 affected rows exact1만 commit합니다.", "mutation과 security audit/outbox row는 같은 transaction에 기록해 성공했는데 audit가 없는 상태를 줄입니다.", "password candidate/hash와 full content는 audit에 넣지 않고 actor/opaque target/action/outcome/correlation만 기록합니다.", "commit 성공 뒤303 PRG+safe flash code를 보내고 validation/auth/conflict/dependency outcome을 typed status로 분리합니다.", "commit response loss는 idempotency/audit/version으로 reconcile하며 password를 다시 log/replay store에 저장하지 않습니다.", "wrong-password brute force는 mutation transaction을 최소화하고 rate-limit counters의 consistency/privacy/availability를 설계합니다.", "fault injection은 hash verify, DML, audit insert, commit, rollback과 response loss에서 row/audit/response invariants를 검증합니다."],
    concepts: [{ term: "security transaction", definition: "resource 상태 검증·authorization-aware DML·audit를 한 원자적 DB 경계에서 수행하는 흐름입니다.", detail: ["TOCTOU를 줄입니다.", "exact rows를 요구합니다."] }, { term: "security audit event", definition: "민감 payload 없이 actor·target·action·outcome·time/correlation을 tamper-resistant sink에 기록한 evidence입니다.", detail: ["application debug log와 다릅니다.", "접근/retention을 통제합니다."] }, { term: "commit-aware response", definition: "durable commit outcome을 확인한 뒤에만 success status/redirect를 확정하는 규칙입니다.", detail: ["partial success를 숨기지 않습니다.", "unknown은 reconcile합니다."] }],
    diagnostics: diag("secure transaction", "비밀번호 검증은 성공했지만 concurrent delete/update 후 잘못된 row 상태를 commit한다.", "verify와 DML 사이에 row status/version을 predicate로 재확인하지 않아 TOCTOU가 생겼습니다.", "same transaction의 id+tenant+status+version predicate와 exact1 affected-row contract를 사용합니다."),
    expertNotes: ["A password check performed outside the mutation transaction can become stale with respect to row lifecycle and authorization state.", "Security audit durability must be balanced with availability; define failure policy explicitly rather than silently dropping events."],
    trace: { className: "SecureCrudOutcomeDecision", title: "security gates와 DML 결과를 transaction outcome으로 판정합니다", purpose: "검증 성공만으로 response success를 확정하지 않습니다.", cases: [{ input: "GATES_OK_ROWS_1_COMMIT", decision: "303", evidence: "audit+resource" }, { input: "GATES_OK_ROWS_0", decision: "409", evidence: "stale-state" }, { input: "COMMIT_UNKNOWN", decision: "503", evidence: "reconcile" }], defaultDecision: "ROLLBACK", defaultEvidence: "incomplete-secure-outcome", sourceRefs: ["mvc06-write-ok", "mvc06-update-ok", "mvc06-delete-ok", "mybatis-java-api", "owasp-transaction-authorization"] },
  },
  {
    id: "mvc06-security-test-migration", title: "CRUD security를 source·unit·hash·DB·DOM·DAST tests로 고정하고 안전하게 migration합니다", lead: "plaintext/client verification을 한 번에 깨뜨리지 않고 dual-read/rehash·projection·route changes를 evidence와 rollback으로 전환합니다.",
    explanations: ["static audit는 password flows, direct EL/c:out, CSRF, mapper predicates와 sensitive config/log calls를 DB 없이 추적합니다.", "JDK unit은 validation, gate order, status/error/data-minimization decisions를 exact output으로 검증합니다.", "password integration은 maintained hasher의 create/verify/wrong/malformed/old-cost rehash와 bounded performance를 test secret으로 검증합니다.", "MyBatis real DB tests는 auth-aware predicates, rows0/1/many, soft-delete lifecycle, version race와 transaction/audit rollback을 검증합니다.", "container/browser tests는 CSRF, password absence, context encoding, CSP/cache headers와 stored-XSS DOM payload를 확인합니다.", "DAST/abuse tests는 hidden field tamper, brute force/rate limit, enumeration, session fixation/CSRF와 authorization bypass를 포함합니다.", "기존 plaintext migration은 exposure incident response, forced reset 또는 controlled one-time verify-and-rehash 정책을 위험/규정에 따라 결정하며 plaintext를 계속 보존하지 않습니다.", "release evidence에는 closure19, secret canary absence, dependency/SBOM scan, tests/SLO, key/pepper rotation, rollback과 incident runbook을 묶습니다."],
    concepts: [{ term: "rehash migration", definition: "성공적인 old-hash verification 때 current password policy로 새 hash를 저장하는 점진 전환입니다.", detail: ["plaintext migration과 다릅니다.", "versioned format을 사용합니다."] }, { term: "DAST", definition: "실행 중 application의 HTTP entry points에 공격 payload를 보내 취약 behavior를 찾는 동적 보안 test입니다.", detail: ["소스 audit를 보완합니다.", "격리 환경에서 실행합니다."] }, { term: "security release gate", definition: "배포 전에 반드시 충족해야 할 threat-specific negative/positive evidence와 owner 기준입니다.", detail: ["단순 scanner pass가 아닙니다.", "예외 승인/expiry를 둡니다."] }],
    diagnostics: diag("security migration", "hash migration 뒤 일부 사용자는 로그인/수정할 수 없고 rollback하면 plaintext flow가 다시 노출된다.", "credential format version, staged dual-read 기간, reset/rollback security boundary와 parity tests가 없습니다.", "versioned verifier format, controlled migration/reset, feature flags와 security-safe rollback plan을 설계합니다."),
    expertNotes: ["Rolling back to plaintext or client-side verification is not an acceptable operational rollback; security migrations need forward-fix and safe compatibility plans.", "Security test artifacts must use synthetic secrets and data, never copied production passwords, hashes or guestbook content."],
    trace: { className: "Mvc06EvidenceDecision", title: "CRUD security 변경별 검증 계층을 선택합니다", purpose: "hashing, SQL authorization와 browser sinks를 맞는 environment에서 검증합니다.", cases: [{ input: "PASSWORD_POLICY", decision: "HASH_INTEGRATION", evidence: "verify+rehash" }, { input: "AUTH_PREDICATE", decision: "CONCURRENT_DB", evidence: "rows+version" }, { input: "OUTPUT_ENCODING", decision: "BROWSER_DOM", evidence: "stored-payload" }], defaultDecision: "FULL_SECURITY_MATRIX", defaultEvidence: "unclassified-change", sourceRefs: ["owasp-password", "owasp-csrf", "owasp-authorization", "owasp-xss", "owasp-testing"] },
  },
];

const local = (id: string, path: string, usedFor: string[], evidence: string): SessionSource => ({ id, repository: "nohssam/jspstudy", path, usedFor, evidence });
const sources: SessionSource[] = [
  local("mvc06-write-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteOKCommand.java", ["create", "plaintext password flow", "commit"], "raw password/fields, VO insert와 commit을 확인했습니다."),
  local("mvc06-update-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateOKCommand.java", ["update", "password verification gap", "commit"], "update fields/DML은 있으나 server password verify가 없음을 확인했습니다."),
  local("mvc06-delete-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteOKCommand.java", ["soft delete", "authorization gap", "commit"], "g_idx delete DML/commit과 server password verify 부재를 확인했습니다."),
  local("mvc06-mapper", "guestbook/guestbook/src/main/resources/mapper/GuestBookMapper.xml", ["plaintext bind", "active filter", "soft delete"], "g_pwd bind, g_active=0/1과 update statements를 확인했습니다."),
  local("mvc06-write-jsp", "guestbook/guestbook/src/main/webapp/write.jsp", ["password input", "CSRF gap", "stored fields"], "POST form/required fields와 CSRF token 부재를 확인했습니다."),
  local("mvc06-update-jsp", "guestbook/guestbook/src/main/webapp/update.jsp", ["client password compare", "direct EL", "update form"], "`${gvo.g_pwd}` JavaScript 비교와 direct EL fields를 확인했습니다."),
  local("mvc06-list-jsp", "guestbook/guestbook/src/main/webapp/list.jsp", ["stored XSS", "direct EL", "list view"], "writer/subject/date direct EL rendering을 확인했습니다."),
  local("mvc06-delete-jsp", "guestbook/guestbook/src/main/webapp/delete.jsp", ["client password compare", "hidden id", "delete form"], "`${g_pwd}` JavaScript 비교와 POST delete를 확인했습니다."),
  local("mvc06-controller", "guestbook/guestbook/src/main/java/org/study/guestbook/controller/MyController.java", ["routes", "common security gate"], "CRUD route dispatch를 확인했습니다."),
  local("mvc06-command", "guestbook/guestbook/src/main/java/org/study/guestbook/model/Command.java", ["request/result contract"], "Servlet-coupled Command signature를 확인했습니다."),
  local("mvc06-list-command", "guestbook/guestbook/src/main/java/org/study/guestbook/model/ListCommand.java", ["active list", "request model"], "list mapper result를 request에 전달함을 확인했습니다."),
  local("mvc06-one-command", "guestbook/guestbook/src/main/java/org/study/guestbook/model/OneListCommand.java", ["detail row", "password-bearing model"], "full GuestBookVO를 gvo로 전달함을 확인했습니다."),
  local("mvc06-delete-form", "guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteFormCommand.java", ["password attribute flow"], "g_idx/g_pwd parameters를 delete view attributes로 전달함을 확인했습니다."),
  local("mvc06-update-form", "guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateFormCommand.java", ["full row update model"], "full gvo를 update view에 전달함을 확인했습니다."),
  local("mvc06-one-jsp", "guestbook/guestbook/src/main/webapp/onelist.jsp", ["hidden password exposure", "stored XSS"], "password hidden value와 direct content EL을 확인했습니다."),
  local("mvc06-mapper-interface", "guestbook/guestbook/src/main/java/org/study/guestbook/mapper/GuestBookMapper.java", ["CRUD methods", "projection evolution"], "methods5를 확인했습니다."),
  local("mvc06-vo", "guestbook/guestbook/src/main/java/org/study/guestbook/vo/GuestBookVO.java", ["password-bearing DTO", "data minimization"], "g_pwd와 public fields가 한 VO에 있음을 확인했습니다."),
  local("mvc06-dbutil", "guestbook/guestbook/src/main/java/org/study/guestbook/db/DBUtil.java", ["session/transaction"], "manual SqlSession provider를 확인했습니다."),
  local("mvc06-config", "guestbook/guestbook/src/main/resources/mybatis-config.xml", ["secret boundary", "mapper registration"], "credential values는 복제하지 않고 sensitive property 존재만 확인했습니다."),
  { id: "mybatis-java-api", repository: "MyBatis", path: "Java API", publicUrl: "https://mybatis.org/mybatis-3/java-api.html", usedFor: ["transaction", "mapper"], evidence: "공식 MyBatis Java API입니다." },
  { id: "jakarta-tags", repository: "Jakarta EE", path: "Tags 3.0 specification", publicUrl: "https://jakarta.ee/specifications/tags/3.0/", usedFor: ["c:out", "JSP rendering"], evidence: "공식 Jakarta Tags specification입니다." },
  { id: "owasp-threat-modeling", repository: "OWASP", path: "Threat Modeling Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html", usedFor: ["assets", "trust boundaries", "abuse cases"], evidence: "OWASP threat modeling 지침입니다." },
  { id: "owasp-password", repository: "OWASP", path: "Password Storage Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html", usedFor: ["adaptive hashing", "salt/pepper", "rehash"], evidence: "OWASP password storage 지침입니다." },
  { id: "owasp-authentication", repository: "OWASP", path: "Authentication Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html", usedFor: ["verification", "generic failures", "rate limits"], evidence: "OWASP authentication 지침입니다." },
  { id: "owasp-csrf", repository: "OWASP", path: "CSRF Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html", usedFor: ["mutation intent", "SameSite"], evidence: "OWASP CSRF 방어 지침입니다." },
  { id: "owasp-authorization", repository: "OWASP", path: "Authorization Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", usedFor: ["object authorization", "deny by default"], evidence: "OWASP authorization 지침입니다." },
  { id: "owasp-mass-assignment", repository: "OWASP", path: "Mass Assignment Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Mass_Assignment_Cheat_Sheet.html", usedFor: ["field allowlist"], evidence: "OWASP mass-assignment 방어 지침입니다." },
  { id: "owasp-xss", repository: "OWASP", path: "Cross Site Scripting Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html", usedFor: ["stored XSS", "context encoding", "CSP"], evidence: "OWASP XSS 방어 지침입니다." },
  { id: "owasp-logging", repository: "OWASP", path: "Logging Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html", usedFor: ["redaction", "security audit"], evidence: "OWASP logging 지침입니다." },
  { id: "owasp-transaction-authorization", repository: "OWASP", path: "Transaction Authorization Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Transaction_Authorization_Cheat_Sheet.html", usedFor: ["secure mutation transaction"], evidence: "OWASP transaction authorization 지침입니다." },
  { id: "owasp-testing", repository: "OWASP", path: "Web Security Testing Guide", publicUrl: "https://owasp.org/www-project-web-security-testing-guide/", usedFor: ["DAST", "security release matrix"], evidence: "OWASP 공식 web security testing guide입니다." },
];

const session = buildMvcSession({
  inventoryId: "mvc-06-guestbook-crud-security", order: 6, title: "방명록 CRUD 보안", subtitle: "password client 비교·직접 EL을 server hash verification, CSRF·authorization·soft-delete lifecycle·context encoding·security tests로 교정합니다.", level: "전문가", estimatedMinutes: 1140,
  coreQuestion: "방명록 작성·수정·삭제 권한과 password를 browser에 노출하지 않고 검증하며, stored XSS·CSRF·row 변조·동시 상태 변화에서도 데이터와 사용자를 어떻게 보호할까요?",
  summary: "inventory8과 security data-flow closure19를 읽었습니다. active parameters11(update g_pwd read는 comment), DML/commit3, soft-delete write1/active filter1, POST forms3, direct EL15/c:out0, CSRF0, hash API/server password verify0, client password EL3, plaintext password SQL bind1입니다. 실제 password/user data/DB/browser/credential은 사용·출력하지 않았습니다. threat model, typed validation/adaptive hashing, server verification, update authorization/CSRF/mass-assignment/version, soft-delete lifecycle, stored-XSS contextual encoding, data minimization/log/cache, secure transaction/PRG/audit와 staged security testing/migration을 10장으로 완성합니다.",
  objectives: ["CRUD trust boundaries와 abuse cases를 threat model로 만든다.", "password를 adaptive salted hash로 저장하고 rehash한다.", "stored verifier를 client에 보내지 않고 server에서 검증한다.", "CSRF와 object/field authorization, optimistic version을 구분한다.", "soft delete를 lifecycle·scope·audit·retention으로 설계한다.", "c:out/context encoder/CSP로 stored XSS를 차단한다.", "password-free projection과 log/cache data minimization을 적용한다.", "security gates·DML·audit·PRG를 commit-aware outcome으로 묶는다.", "hash/DB/DOM/DAST tests와 안전한 migration/rollback을 설계한다."],
  prerequisites: [{ title: "방명록 Front Controller", reason: "route/Command/Mapper/VO/view closure와 request-local execution을 보안 gate에 사용합니다.", sessionSlug: "mvc-05-guestbook-front-controller" }, { title: "책 쓰기와 트랜잭션", reason: "affected rows, commit/rollback, optimistic version과 CSRF mutation 경계를 확장합니다.", sessionSlug: "mvc-03-book-write-transaction" }],
  keywords: ["password hashing", "Argon2id", "salt", "pepper", "server verification", "CSRF", "object authorization", "mass assignment", "soft delete", "stored XSS", "c:out", "contextual encoding", "CSP", "data minimization", "security audit", "DAST"], topics,
  lab: { title: "Password-safe·XSS-safe Guestbook CRUD", scenario: "plaintext/client password comparison과 direct EL을 제거하고 secure create/update/delete lifecycle을 production-grade controls로 재구성합니다.", setup: ["synthetic password/XSS/CSRF/g_idx tamper/brute-force/concurrency fixtures만 사용합니다.", "ephemeral DB/container와 maintained password hasher를 준비합니다.", "threat model과 public/auth-only/drop field matrix를 작성합니다."], steps: ["closure19 static security audit를 실행합니다.", "write command를 validate하고 adaptive salted hash만 저장합니다.", "public queries/view DTO에서 password/hash field를 제거합니다.", "update/delete candidate password를 server verify합니다.", "CSRF+object authorization+field allowlist+version predicates를 적용합니다.", "soft-delete state/audit/restore/purge policy를 구현합니다.", "모든 JSP sink를 context encoding/c:out으로 바꾸고 inline secret/JS flow를 제거합니다.", "commit-aware PRG와 redacted security audit/observability를 연결합니다.", "hash/MyBatis concurrency/container DOM/DAST/canary-negative tests를 실행합니다.", "credential migration, rate-limit, incident/rollback/forward-fix runbook을 완성합니다."], expectedResult: ["DB에는 plaintext password가 없고 client/model/log/cache에는 password/hash가 없습니다.", "wrong password/CSRF/unauthorized/tampered/stale 요청은 mutation0입니다.", "stored payload는 어느 JSP context에서도 실행되지 않습니다.", "delete/update concurrency는 허용된 lifecycle transition과 exact row contract를 지킵니다.", "security evidence는 synthetic data만 사용하고 secret/PII가 없습니다."], cleanup: ["ephemeral DB/container/hash fixtures/rate-limit keys만 제거합니다.", "pool/session/thread/temporary secrets leak0을 확인합니다.", "HTTP/log/test artifacts를 canary secret scan하고 public-safe aggregate만 보존합니다."], extensions: ["resource password를 authenticated account ownership으로 migration합니다.", "WebAuthn/step-up authorization이 필요한 admin purge flow를 설계합니다.", "CSP report-only→enforce rollout과 Trusted Types 가능성을 평가합니다.", "security audit tamper evidence와 SIEM alert/burn-rate를 연결합니다."] },
  exercises: [
    { difficulty: "따라하기", prompt: "client password 비교를 server-side hash verification으로 바꾸세요.", requirements: ["stored hash를 HTML/model에 보내지 않습니다.", "maintained adaptive hasher를 사용합니다.", "wrong/malformed/old-cost를 처리합니다.", "generic failure/rate limit을 둡니다.", "response/log secret absence를 검증합니다."], hints: ["hidden password/hash도 공격자가 읽을 수 있습니다."], expectedOutcome: "candidate secret은 server verify 이후 폐기되고 client에는 verifier가 없습니다.", solutionOutline: ["auth-only projection과 PasswordService를 분리합니다."] },
    { difficulty: "응용", prompt: "soft delete update를 CSRF/auth/version-aware exact1 transition으로 만드세요.", requirements: ["id+tenant+active+version predicate를 사용합니다.", "rows1만 commit합니다.", "rows0/many 정책을 둡니다.", "audit를 같은 transaction에 기록합니다.", "delete-vs-update concurrency test를 둡니다."], hints: ["select 후 update 사이 TOCTOU를 predicate로 줄이세요."], expectedOutcome: "unauthorized/stale/deleted row가 조용히 변경되지 않습니다.", solutionOutline: ["ACTIVE→DELETED transition과 version increment를 한 statement로 만듭니다."] },
    { difficulty: "설계", prompt: "Guestbook security migration/incident ADR을 작성하세요.", requirements: ["plaintext/client exposure incident response를 포함합니다.", "hash format/cost/pepper/rotation을 포함합니다.", "CSRF/authorization/XSS/data-minimization owners를 표시합니다.", "source/hash/DB/DOM/DAST matrix를 둡니다.", "security-safe rollback/forward-fix를 설계합니다.", "rate-limit/SLO/alerts/audit retention을 정합니다."], hints: ["plaintext flow로 되돌리는 rollback은 허용할 수 없습니다."], expectedOutcome: "기능 연속성과 보안 수준을 함께 지키는 staged migration이 완성됩니다.", solutionOutline: ["contain→rotate/reset→migrate→verify→monitor 순으로 작성합니다."] },
  ],
  nextSessions: ["mvc-07-guestbook2-multipart-evolution"], sources,
  sourceCoverage: { filesRead: 19, filesUsed: 19, uncoveredNotes: ["inventory8과 password/model/route/mapper/config 직접 security closure11을 합쳐19 files를 모두 읽고 사용했습니다.", "source에 존재하는 password/credential values와 hashes, DB rows와 user content는 어떤 audit/output에도 복제하지 않았습니다.", "정적 counts는 runtime exploit 증명이 아니므로 hash/container/DB/browser security tests를 별도 acceptance로 명시했습니다."] },
});

export default session;
