import type { DetailedCodeExample, DiagnosticCase, SessionSource } from "../../types";
import { buildMvcSession, type MvcTopicSpec } from "./mvc-01-mybatis-config-mapper.ts";

const diag = (area: string, symptom: string, cause: string, fix: string): DiagnosticCase[] => [
  { symptom, likelyCause: cause, checks: [`${area}의 method/cmd→handler→model→mapper→result→dispatch trace를 확인합니다.`, "null/unknown/concurrent requests와 dependency failure를 각각 재현합니다.", "response/log에 password·session id·content·SQL/credential이 없는지 확인합니다."], fix, prevention: `${area}의 route set·thread isolation·typed result·failure contract를 자동 검증합니다.` },
  { symptom: "JDK route/state 예제는 통과하지만 실제 Servlet/MyBatis/JSP에서 실패한다.", likelyCause: "순수 예제는 container lifecycle, mapper XML registration, DB schema/transaction과 JSP rendering을 실행하지 않습니다.", checks: ["unit과 integration 범위를 구분합니다.", "Servlet/MyBatis/DB/JSP versions를 기록합니다.", "ephemeral test environment에서 동일 route를 재현합니다."], fix: "운영 credential/data 없이 container+real-engine integration test를 추가합니다.", prevention: "static closure·unit·container·DB·browser evidence를 독립 release gates로 둡니다." },
];

const audit: DetailedCodeExample = {
  id: "powershell-mvc05-original-closure-audit", title: "방명록 Front Controller의 inventory6·직접 Java/XML 폐쇄15를 정적으로 감사합니다", language: "powershell", filename: "verify-original-mvc05.ps1", purpose: "DB/Servlet 실행 없이 routes8, commands8, request-local state, mapper interface/XML과 config secret shape를 exact하게 보존합니다.",
  code: String.raw`param([Parameter(Mandatory)][string]$SourceRoot)
$ErrorActionPreference='Stop'
$rels=@(
 'guestbook/guestbook/src/main/java/org/study/guestbook/controller/MyController.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/Command.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/ListCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteFormCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteOKCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/OneListCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteFormCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteOKCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateFormCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateOKCommand.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/mapper/GuestBookMapper.java',
 'guestbook/guestbook/src/main/resources/mapper/GuestBookMapper.xml',
 'guestbook/guestbook/src/main/java/org/study/guestbook/vo/GuestBookVO.java',
 'guestbook/guestbook/src/main/java/org/study/guestbook/db/DBUtil.java',
 'guestbook/guestbook/src/main/resources/mybatis-config.xml'
)
$files=@($rels|ForEach-Object{Get-Item -LiteralPath (Join-Path $SourceRoot $_)})
if($files.Count-ne15){throw 'closure drift'}
$before=@{};foreach($file in $files){$before[$file.FullName]=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}
$text=($files|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine
$active=[regex]::Replace(([regex]::Replace($text,'(?s)<!--.*?-->','')),'(?s)/\*.*?\*/','')
$active=[regex]::Replace($active,'(?m)//.*$','')
function Count([string]$value,[string]$pattern){([regex]::Matches($value,$pattern,[Text.RegularExpressions.RegexOptions]::IgnoreCase)).Count}
$routes=Count $active 'case\s+"';$defaults=Count $active '(?m)^\s*default\s*:';$news=Count $active 'new\s+\w+Command\s*\('
$implementations=Count $active 'implements\s+Command\b';$fields=Count $active '(?m)^\s*(?:private|protected|public)\s+(?:volatile\s+)?Command\s+\w+'
$interface=[IO.File]::ReadAllText($files[10].FullName);$methods=Count $interface '(?m)^\s*(?:List<GuestBookVO>|GuestBookVO|int)\s+\w+\s*\('
$mapper=[regex]::Replace([IO.File]::ReadAllText($files[11].FullName),'(?s)<!--.*?-->','');$statements=Count $mapper '<(?:select|insert|update|delete)\b'
$commits=Count $active '\.commit\s*\(';$sessions=Count $active '\.openSession\s*\(';$sensitive=Count $active 'name="(?:username|password)"'
if($routes-ne8-or$defaults-ne0-or$news-ne8-or$implementations-ne8-or$fields-ne0-or$methods-ne5-or$statements-ne5-or$commits-ne3-or$sessions-ne1-or$sensitive-ne2){throw 'source shape drift'}
foreach($file in $files){if((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash-cne$before[$file.FullName]){throw 'source hash drift'}}
"files=15|routes=8|defaultRoutes=0|commandConstructions=8|commandImplementations=8|servletCommandFields=0|mapperMethods=5|activeStatements=5|commits=3|openSessionCalls=1|sensitiveProperties=2|redacted=True|hashes=15/15"
"execution=static-only|servlet=not-started|db=not-contacted|credentials=not-output"`,
  walkthrough: [{ lines: "1-19", explanation: "inventory6에서 controller가 직접 참조하는 commands, DBUtil/config까지 closure15를 고정합니다." }, { lines: "20-26", explanation: "hash를 보존하고 comments를 제거한 active source를 만듭니다." }, { lines: "27-34", explanation: "route/command/thread-state/mapper/transaction/config shapes를 exact count합니다." }, { lines: "35-37", explanation: "source 불변성과 credential redaction·runtime 미실행을 확인합니다." }],
  run: { environment: ["PowerShell 7+", "jspstudy 저장소의 상위 폴더", "정적 읽기만", "Servlet/MyBatis/DB 불필요"], command: "pwsh -NoProfile -File verify-original-mvc05.ps1 -SourceRoot ./jspstudy" },
  output: { value: "files=15|routes=8|defaultRoutes=0|commandConstructions=8|commandImplementations=8|servletCommandFields=0|mapperMethods=5|activeStatements=5|commits=3|openSessionCalls=1|sensitiveProperties=2|redacted=True|hashes=15/15\nexecution=static-only|servlet=not-started|db=not-contacted|credentials=not-output", explanation: ["controller는8 routes에서8 stateless-looking command를 request마다 생성하고 Command instance field는0입니다.", "Command 구현8·mapper methods5·active statements5·DML commits3이 실제 폐쇄에 있습니다.", "config의 username/password property 존재2만 확인하고 값/hash는 공개하지 않습니다."] },
  experiments: [{ change: "Command를 servlet field에 저장합니다.", prediction: "servletCommandFields0이 drift하고 concurrent request isolation이 깨질 수 있습니다.", result: "request-specific handler/result는 local variable로 유지합니다." }, { change: "unknown route default를 추가합니다.", prediction: "defaultRoutes0 audit가 실패합니다.", result: "개선 route table에서는 fail-closed result와 negative test로 검증합니다." }, { change: "DBUtil을 class-load하거나 controller를 실행합니다.", prediction: "config credential로 실제 DB 접속이 발생할 수 있습니다.", result: "audit는 텍스트/hash만 읽습니다." }],
  sourceRefs: ["mvc05-controller", "mvc05-command", "mvc05-list-command", "mvc05-write-form", "mvc05-write-ok", "mvc05-one", "mvc05-delete-form", "mvc05-delete-ok", "mvc05-update-form", "mvc05-update-ok", "mvc05-mapper-interface", "mvc05-mapper-xml", "mvc05-vo", "mvc05-dbutil", "mvc05-config"],
};

const topics: MvcTopicSpec[] = [
  {
    id: "mvc05-original-front-controller-closure", title: "원본 Front Controller의 실제 closure15와 요청 흐름을 감사합니다", lead: "inventory6에서 멈추지 않고 route가 생성하는 Command8·DBUtil/config까지 따라가며 책임과 위험을 정확히 지도화합니다.",
    explanations: ["MyController, Command, ListCommand, GuestBookMapper interface/XML, GuestBookVO가 inventory6입니다.", "controller가 직접 생성하는 WriteForm/WriteOK/OneList/DeleteForm/DeleteOK/UpdateForm/UpdateOK과 DBUtil/config를 포함하면 직접 Java/XML closure는15입니다.", "doPost는 doGet으로 위임하고 cmd8 cases가 list/form/write/detail/delete/edit actions를 분배합니다.", "command variable은 method local이고 command implementations는 request마다 새로 만들어져 servlet shared-field race를 피한 좋은 출발점입니다.", "default route는0이라 null cmd는 switch failure, unknown cmd는 null command.exec failure로 이어질 수 있습니다.", "mapper interface5와 active XML statements5가 대응하고 write/update/delete command는 각각 commit합니다.", "DBUtil의 static factory는 openSession manual commit을 제공하고 config credential properties2는 source에 존재합니다.", "audit는 credential 값/hash, DB rows, uploaded/user data를 읽지 않고 source shape/hash만 검증합니다."],
    concepts: [{ term: "actual closure", definition: "inventory뿐 아니라 controller가 직접 생성·호출하고 runtime 구성을 위해 필요한 local source 집합입니다.", detail: ["routes8을 따라갑니다.", "외부 libraries는 별도 dependency입니다."] }, { term: "Front Controller", definition: "공통 HTTP 진입점에서 routing·공통 정책·handler dispatch·result 적용을 중앙화하는 pattern입니다.", detail: ["중복을 줄입니다.", "god controller가 되지 않게 합니다."] }, { term: "request-local command", definition: "한 요청의 action/result state를 servlet method local 또는 immutable object에 두는 방식입니다.", detail: ["thread 격리를 돕습니다.", "shared dependencies와 구분합니다."] }],
    diagnostics: diag("원본 front controller", "unknown cmd에서500이 발생하고 어떤 route였는지 안전한 기록이 없다.", "default route/null guard와 stable error result가 없습니다.", "method+action route table이 unknown을400/404로 반환하고 bounded correlation log를 남기게 합니다."),
    expertNotes: ["Request-local command allocation is thread-safe with respect to handler identity, but shared DB/static collaborators still need their own thread-safety contracts.", "A source closure documents code relationships; it does not prove runtime configuration, SQL or view correctness."], customExample: audit,
  },
  {
    id: "mvc05-mvc-request-lifecycle", title: "Model 2 MVC의 request→controller→command→mapper→model→view 흐름을 고정합니다", lead: "HTTP·application·persistence·presentation 경계를 하나의 trace로 연결하되 각 계층의 책임을 섞지 않습니다.",
    explanations: ["controller는 encoding/method/routing과 공통 security/observability를 적용하고 업무 세부를 Command에 위임합니다.", "Command는 request를 validation된 use-case input으로 바꾸고 service/mapper를 호출해 typed result와 view model을 만듭니다.", "mapper는 SQL·binding·row mapping만 담당하며 HttpServletRequest/JSP path를 알지 않습니다.", "VO는 DB row transport에 적합하지만 password를 포함하므로 모든 view model에 그대로 전달하면 안 됩니다.", "view는 이미 준비된 model을 escaping/condition/iteration해 렌더링하고 DB/session을 직접 호출하지 않습니다.", "forward는 request model을 유지하고 PRG redirect는 새 GET과 flash/durable state를 사용합니다.", "controller가 PrintWriter를 미리 열거나 Command가 response body를 쓰면 dispatch ownership이 분산됩니다.", "architecture test는 mapper package의 servlet import 금지, view의 DB call 금지와 dependency direction을 검사합니다."],
    concepts: [{ term: "Model 2 MVC", definition: "Servlet controller가 요청을 받고 model/application logic을 거쳐 JSP view로 전달하는 Java web 구조입니다.", detail: ["JSP Model1 scriptlet을 줄입니다.", "routing을 중앙화합니다."] }, { term: "dependency direction", definition: "HTTP/view 계층이 application/persistence port를 사용하되 하위 계층은 Servlet/JSP를 모르게 하는 방향입니다.", detail: ["testability를 높입니다.", "framework coupling을 제한합니다."] }, { term: "view preparation", definition: "Command/controller가 rendering 전에 required model·status·view/redirect 결과를 완성하는 단계입니다.", detail: ["view는 표현에 집중합니다.", "민감 field를 제거합니다."] }],
    diagnostics: diag("MVC flow", "JSP가 session close 뒤 mapper/VO lazy data를 읽어 오류가 난다.", "persistence/session 객체를 view에 넘겨 rendering과 transaction lifecycle을 결합했습니다.", "Command 안에서 detached display DTO를 완성하고 session을 닫은 뒤 forward합니다."),
    expertNotes: ["Layering is valuable when it clarifies ownership and test boundaries, not when it merely renames pass-through classes.", "A persistence VO containing password data should never become the default view model."],
    trace: { className: "GuestbookMvcFlowDecision", title: "요청 단계별 책임 owner를 판정합니다", purpose: "routing·use case·SQL·rendering 책임이 어느 계층에 있는지 고정합니다.", cases: [{ input: "METHOD_CMD", decision: "CONTROLLER", evidence: "route" }, { input: "BUSINESS_OUTCOME", decision: "COMMAND_SERVICE", evidence: "use-case" }, { input: "SQL_MAPPING", decision: "MAPPER", evidence: "persistence" }], defaultDecision: "VIEW", defaultEvidence: "render-safe-model", sourceRefs: ["mvc05-controller", "mvc05-command", "mvc05-list-command", "mvc05-mapper-interface", "jakarta-servlet"] },
  },
  {
    id: "mvc05-route-method-action-default", title: "cmd8 switch를 method+action allowlist와 exhaustive default로 발전시킵니다", lead: "hidden cmd를 신뢰하지 않고 지원 method·action·handler·authorization metadata를 startup에 검증합니다.",
    explanations: ["원본 action names는 list, writeForm, write_ok, onelist, deleteForm, delete_ok, editForm, update_ok 여덟 개입니다.", "조회/form은 GET, 상태 변경은 POST로 구분하고 GET mutation을 허용하지 않습니다.", "cmd는 client-controlled 문자열이므로 null/blank/unknown/duplicate를 request validation 단계에서 처리합니다.", "route registry는 key 중복, handler null, result type와 required authorization policy를 startup에 검사합니다.", "default는 첫 action으로 fall back하지 않고400/404/405를 명시합니다.", "URL/action naming은 일관되게 쓰고 대소문자/underscore 변형을 조용히 허용하지 않습니다.", "path-based routes로 발전해도 actor/resource authorization은 각 use case에서 별도 검증합니다.", "route full-set test는 허용8과 method matrix, UNKNOWN을 exact output으로 보존합니다."],
    concepts: [{ term: "action allowlist", definition: "지원하는 action 문자열과 handler만 닫힌 set으로 등록하는 routing 정책입니다.", detail: ["unknown은 거부합니다.", "동적 class name 실행을 피합니다."] }, { term: "method-action matrix", definition: "각 action이 허용하는 HTTP method와 safe/idempotent/mutation 성격을 표로 만든 계약입니다.", detail: ["405/Allow와 연결합니다.", "CSRF 적용 범위를 정합니다."] }, { term: "startup route validation", definition: "traffic 전에 duplicate/missing handler·policy metadata를 검사하는 bootstrap 단계입니다.", detail: ["fail fast합니다.", "immutable registry를 만듭니다."] }],
    diagnostics: diag("route registry", "GET URL만 열어도 write/delete command가 실행되거나 cmd 오타가500이 된다.", "doPost→doGet 통합과 action switch가 method policy/default validation을 표현하지 않습니다.", "method+action route registry,405+Allow와 mutation CSRF gate를 적용합니다."),
    expertNotes: ["Central routing makes method enforcement easier, but only if method is part of the route key instead of being discarded by doPost-to-doGet delegation.", "Dynamic reflection from an action string expands the attack surface; a closed registry is simpler and safer."],
    trace: { className: "GuestbookRouteDecision", title: "method+cmd를 handler/status로 매핑합니다", purpose: "조회와 mutation을 method policy로 분리하고 unknown을 fail-closed합니다.", cases: [{ input: "GET_list", decision: "ListCommand", evidence: "safe" }, { input: "POST_write_ok", decision: "WriteOKCommand", evidence: "csrf+authz" }, { input: "GET_delete_ok", decision: "405", evidence: "Allow-POST" }], defaultDecision: "404", defaultEvidence: "unknown-action", sourceRefs: ["mvc05-controller", "rfc9110", "owasp-csrf"] },
  },
  {
    id: "mvc05-command-contract-result", title: "Command.exec의 String path를 typed input/result와 예외 계약으로 바꿉니다", lead: "handler가 request/response와 임의 path를 모두 만지는 대신 use-case input과 Forward/Redirect/Error 결과를 명시합니다.",
    explanations: ["원본 Command는 HttpServletRequest/Response를 받고 String을 반환해 handler가 parsing, business, model, dispatch를 모두 수행할 수 있습니다.", "CommandInput은 validated actor/action/resource/form fields를 담고 raw Servlet API와 분리할 수 있습니다.", "ActionResult는 Forward(status,view,model), Redirect(status,location,flash), Error(status,code)를 분리합니다.", "Command가 response writer/redirect를 직접 호출하지 않으면 controller가 response commit과 headers를 한 번 소유합니다.", "checked ServletException/IOException과 domain/persistence exception을 stable taxonomy로 mapping합니다.", "stateless command는 singleton registry로 공유 가능하지만 mutable collaborators는 constructor injection과 thread-safe contract가 필요합니다.", "command마다 새 객체를 만드는 비용은 작지만 dependencies를 내부 `new` 하면 integration test와 transaction composition이 어렵습니다.", "unit test는 Servlet mock 대신 typed input과 result equality를 검증하고 adapter test만 request parsing을 다룹니다."],
    concepts: [{ term: "command contract", definition: "한 action의 validated input, authorization, side effect, output/error와 transaction boundary를 명시한 합의입니다.", detail: ["use case 단위입니다.", "HTTP adapter와 분리할 수 있습니다."] }, { term: "typed action result", definition: "dispatch kind·status·target·model/flash를 type으로 제한한 handler 반환값입니다.", detail: ["String ambiguity를 제거합니다.", "response ownership을 중앙화합니다."] }, { term: "adapter", definition: "Servlet request/response와 framework-neutral command input/result 사이를 변환하는 경계 코드입니다.", detail: ["HTTP parsing을 담당합니다.", "업무 로직과 분리합니다."] }],
    diagnostics: diag("Command result", "Command가 `MyController?cmd=list`를 반환했는데 forward되어 URL/history가 바뀌지 않는다.", "String path가 JSP forward와 redirect URL을 구분하지 못합니다.", "typed Redirect(303, route)와 중앙 result applicator를 사용합니다."),
    expertNotes: ["A command can be framework-neutral without becoming abstract ceremony when its input and outcome correspond to a real use case.", "Stateless singleton handlers are safe only when every collaborator they share has an explicit concurrency contract."],
    trace: { className: "CommandResultDecision", title: "Command outcome을 typed dispatch로 변환합니다", purpose: "view path와 controller URL을 같은 문자열로 반환하지 않습니다.", cases: [{ input: "LIST_OK", decision: "FORWARD", evidence: "list.jsp+model" }, { input: "WRITE_COMMITTED", decision: "REDIRECT_303", evidence: "list-route+flash" }, { input: "VALIDATION", decision: "FORWARD_400", evidence: "form-errors" }], defaultDecision: "ERROR_500", defaultEvidence: "correlation-only", sourceRefs: ["mvc05-command", "mvc05-list-command", "mvc05-write-ok", "jakarta-servlet"] },
  },
  {
    id: "mvc05-mapper-vo-persistence-boundary", title: "GuestBookMapper·XML·VO의 persistence contract를 controller와 분리합니다", lead: "methods5/statements5, active filter와 password-bearing VO를 SQL·domain·view boundary로 정확히 나눕니다.",
    explanations: ["mapper interface는 selectAll, insertGuestBook, selectDetail, deleteGuestBook, updateGuestBook 다섯 method를 제공합니다.", "XML은 active rows 목록, insert, detail, soft-delete update, content update 다섯 active statement를 갖습니다.", "namespace FQCN과 id set, parameter/result types, #{} bindings와 affected-row cardinality를 startup/integration test합니다.", "GuestBookVO는 id/writer/subject/email/password/content/date/active를 모두 String으로 가지며 password가 list/detail view로 새기 쉬운 구조입니다.", "persistence row DTO와 Create/Update command, PublicListRow/PublicDetail DTO를 분리해 password/active/internal fields를 최소화합니다.", "mapper는 HttpServletRequest와 JSP path를 몰라야 하며 service가 transaction/authorization/outcome을 조정합니다.", "SELECT * 대신 explicit projection을 사용하고 public detail query에서 password column을 애초에 읽지 않습니다.", "active filter는 soft delete scope의 일부이므로 selectDetail/update/delete에도 상태/tenant predicates를 일관되게 적용합니다."],
    concepts: [{ term: "persistence port", definition: "application이 필요한 저장/조회 operation을 framework-neutral method로 표현한 interface 경계입니다.", detail: ["SQL 구현과 분리합니다.", "HTTP type을 포함하지 않습니다."] }, { term: "projection DTO", definition: "query별 필요한 column만 담아 민감 field와 mapping coupling을 줄인 결과 객체입니다.", detail: ["list/detail을 분리합니다.", "SELECT *를 피합니다."] }, { term: "soft-delete scope", definition: "active/deleted 상태를 모든 일반 조회·수정에 일관되게 적용하는 데이터 lifecycle 규칙입니다.", detail: ["단일 query 조건보다 넓습니다.", "admin/recovery scope를 분리합니다."] }],
    diagnostics: diag("mapper/VO boundary", "목록 또는 상세 응답에서 password/internal active 값이 노출된다.", "password-bearing GuestBookVO와 SELECT *를 그대로 request/view model로 사용했습니다.", "explicit public projection query와 password-free display DTO를 사용합니다."),
    expertNotes: ["Data minimization is strongest at query projection time because sensitive columns never enter application memory for that use case.", "A global soft-delete filter can hide rows needed for authorization or recovery, so privileged scopes must be explicit."],
    trace: { className: "GuestbookProjectionDecision", title: "use case별 mapper projection을 선택합니다", purpose: "password-bearing row DTO가 모든 view로 이동하지 않게 합니다.", cases: [{ input: "LIST", decision: "PUBLIC_ROW", evidence: "id+writer+subject+date" }, { input: "DETAIL", decision: "PUBLIC_DETAIL", evidence: "no-password" }, { input: "VERIFY_PASSWORD", decision: "AUTH_RECORD", evidence: "hash-only" }], defaultDecision: "REJECT", defaultEvidence: "unknown-projection", sourceRefs: ["mvc05-mapper-interface", "mvc05-mapper-xml", "mvc05-vo", "mybatis-sqlmap", "owasp-password"] },
  },
  {
    id: "mvc05-servlet-thread-safety-race", title: "Servlet shared instance와 request-local state를 구분해 race를 차단합니다", lead: "원본 local command의 장점을 보존하고 무엇을 field로 올리면 요청 값이 섞이는지 happens-before 관점으로 설명합니다.",
    explanations: ["Servlet container는 보통 한 MyController instance의 service/doGet을 여러 request threads가 동시에 호출합니다.", "원본 `cmd`와 `command`는 method local이어서 각 thread stack에 분리됩니다.", "이를 servlet field로 옮기면 thread A가 선택한 command를 B가 덮어써 A request가 다른 handler를 실행할 수 있습니다.", "HttpServletRequest/Response, model map, writer, actor, transaction/session을 instance/static field에 저장하면 안 됩니다.", "immutable route table, thread-safe service/factory와 connection pool처럼 의도된 shared collaborators만 final field로 공유합니다.", "volatile은 latest reference visibility만 돕고 여러 field/step의 request atomicity나 mutable handler thread safety를 해결하지 않습니다.", "ThreadLocal은 async dispatch/thread reuse에서 leak와 wrong context를 만들 수 있어 container context API와 explicit parameters를 우선합니다.", "latch/barrier concurrency test는 two users/actions를 겹쳐 output/handler/model/transaction이 교차하지 않는지 반복 검증합니다."],
    concepts: [{ term: "Servlet instance sharing", definition: "container가 같은 Servlet object에서 여러 요청을 서로 다른 threads로 동시에 처리할 수 있는 실행 모델입니다.", detail: ["local state를 사용합니다.", "shared collaborators를 검토합니다."] }, { term: "request confinement", definition: "한 요청의 mutable 값을 해당 호출 stack/object graph 밖에서 공유하지 않는 규칙입니다.", detail: ["race를 구조적으로 줄입니다.", "request/response/session을 field에 두지 않습니다."] }, { term: "happens-before", definition: "한 thread의 write가 다른 thread read에 보이고 순서가 보장되는 Java Memory Model 관계입니다.", detail: ["local variables는 공유되지 않습니다.", "volatile만으로 복합 불변식은 부족합니다."] }],
    diagnostics: diag("Servlet concurrency", "동시 요청에서 한 사용자의 action/model이 다른 사용자 응답에 나타난다.", "request-specific cmd/command/model/request를 servlet instance field에 저장했습니다.", "모든 request state를 local/immutable input에 제한하고 shared service의 thread safety를 검증합니다."),
    expertNotes: ["Creating a new handler per request avoids handler-state sharing but does not make static factories, caches or mutable services automatically safe.", "ThreadLocal context must be cleared on every path and is especially risky with asynchronous dispatch and pooled threads."],
    trace: { className: "ServletStatePlacementDecision", title: "Servlet 상태를 LOCAL·FINAL_SHARED·REJECT로 분류합니다", purpose: "field race를 코드 review 단계에서 차단합니다.", cases: [{ input: "REQUEST_CMD", decision: "LOCAL", evidence: "request-confined" }, { input: "IMMUTABLE_ROUTES", decision: "FINAL_SHARED", evidence: "read-only" }, { input: "SQL_SESSION", decision: "LOCAL", evidence: "transaction-scoped" }], defaultDecision: "REJECT", defaultEvidence: "unclassified-shared-state", sourceRefs: ["mvc05-controller", "jakarta-servlet", "java-memory-model"] },
  },
  {
    id: "mvc05-model-dispatch-prg", title: "request model·forward와 mutation redirect/flash를 typed result로 연결합니다", lead: "Command가 반환하는 JSP/controller 문자열을 rendering state와 navigation state로 분리합니다.",
    explanations: ["List/One/UpdateForm commands는 request attribute를 채우고 JSP로 forward하는 read/render action입니다.", "Write/Update/Delete 성공은 commit 뒤 list/detail URL로303 redirect해야 refresh mutation replay를 줄입니다.", "request attribute는 redirect에서 사라지므로 success notice만 flash로, 실제 resource state는 GET에서 다시 읽습니다.", "error.jsp 반환은 default200이 되기 쉬워 typed error status/model이 필요합니다.", "model key와 view path는 constants/schema로 검증하고 password-bearing VO를 전달하지 않습니다.", "forward target은 WEB-INF 아래에 두어 controller validation/authorization 없이 direct 접근하지 못하게 합니다.", "Location은 context-aware server route builder로 만들고 raw return URL을 사용하지 않습니다.", "dispatch integration test는 status, model allowlist, forward target 또는303 Location과 side-effect count를 함께 검증합니다."],
    concepts: [{ term: "render action", definition: "같은 request의 model을 준비해 server-side view forward로 응답을 만드는 action입니다.", detail: ["GET/read에 주로 사용합니다.", "request scope를 유지합니다."] }, { term: "navigation action", definition: "commit된 mutation 뒤 client가 새 resource를 GET하도록 redirect하는 결과입니다.", detail: ["PRG를 사용합니다.", "flash는 일회성입니다."] }, { term: "dispatch ownership", definition: "한 component가 status/headers/forward/redirect/body 중 최종 응답 방식을 한 번만 결정하는 책임입니다.", detail: ["response commit 오류를 막습니다.", "typed result가 돕습니다."] }],
    diagnostics: diag("model/dispatch", "성공 command가 controller URL을 반환했는데 forward되어 주소/refresh가 POST로 남는다.", "controller가 모든 String path를 RequestDispatcher.forward로 처리합니다.", "Forward와 Redirect303를 typed result로 분리하고 commit 뒤 redirect를 적용합니다."),
    expertNotes: ["A forward to another controller URL is not a redirect and can produce surprising paths, filters and response semantics.", "Flash messages should carry safe codes, while the redirected GET reads authoritative database state."],
    trace: { className: "GuestbookDispatchDecision", title: "command outcome별 forward/redirect/error를 선택합니다", purpose: "read model과 mutation navigation을 분리합니다.", cases: [{ input: "LIST_READ", decision: "FORWARD_200", evidence: "request-model" }, { input: "WRITE_COMMIT", decision: "REDIRECT_303", evidence: "flash+list" }, { input: "NOT_FOUND", decision: "ERROR_404", evidence: "safe-model" }], defaultDecision: "ERROR_500", defaultEvidence: "correlation-only", sourceRefs: ["mvc05-list-command", "mvc05-one", "mvc05-write-ok", "mvc05-update-ok", "mvc05-delete-ok", "jakarta-servlet"] },
  },
  {
    id: "mvc05-composition-transaction-dependencies", title: "Command 내부 new/session을 composition root·service transaction으로 옮깁니다", lead: "routing은 handler를 선택하고 dependency lifecycle·transaction owner는 bootstrap/service가 명시하게 합니다.",
    explanations: ["controller가 매 요청 concrete Command를 new하면 route와 composition이 결합되고 dependency replacement/test가 어렵습니다.", "bootstrap composition root가 mapper/session provider, services, handlers와 route registry를 구성해 immutable controller에 주입할 수 있습니다.", "read command는 short session으로 detached DTO를 만들고 write service는 여러 mapper/audit/outbox를 한 transaction으로 묶습니다.", "mapper/DAO가 각자 commit하면 use case 전체 원자성이 깨지므로 service가 commit/rollback owner입니다.", "DBUtil static initialization은 startup fail-fast 장점이 있지만 secret/profile/test isolation을 dependency injection으로 분명히 하는 편이 좋습니다.", "connection/session pool은 shared thread-safe provider이고 실제 SqlSession은 request/transaction local입니다.", "handler dependencies는 final로 두고 optional global service locator lookup과 hidden mutable singletons를 피합니다.", "composition test는 route8 모두 handler/dependencies/policies가 존재하고 startup failure가 traffic 전 드러나는지 확인합니다."],
    concepts: [{ term: "composition root", definition: "application 시작점에서 concrete dependencies를 생성·연결하고 상위 component에 주입하는 유일한 위치입니다.", detail: ["new를 중앙화합니다.", "test 구성을 교체합니다."] }, { term: "service transaction", definition: "여러 persistence operation을 하나의 업무 불변식으로 commit/rollback하는 application service 경계입니다.", detail: ["Command보다 안쪽일 수 있습니다.", "mapper는 commit하지 않습니다."] }, { term: "session provider", definition: "요청된 transaction scope에 새 SqlSession을 제공하되 factory/pool 공유와 session 비공유를 캡슐화한 dependency입니다.", detail: ["수명을 명시합니다.", "secret을 노출하지 않습니다."] }],
    diagnostics: diag("dependency composition", "한 write command의 두 번째 DB 단계 실패 후 첫 변경만 commit된다.", "각 mapper/command가 별도 session을 열고 자체 commit해 상위 transaction이 없습니다.", "service가 session 하나를 소유해 모든 mapper 호출과 audit/outbox를 함께 commit/rollback합니다."),
    expertNotes: ["A composition root reduces hidden dependencies without requiring a full dependency-injection framework.", "Transaction scope should follow a business invariant, not automatically every HTTP request or every mapper method."],
    trace: { className: "DependencyScopeDecision", title: "dependency를 application/request/transaction scope로 배치합니다", purpose: "factory와 session, handler state의 수명을 혼동하지 않습니다.", cases: [{ input: "SESSION_FACTORY", decision: "APPLICATION", evidence: "thread-safe-provider" }, { input: "SQL_SESSION", decision: "TRANSACTION", evidence: "not-shared" }, { input: "REQUEST_MODEL", decision: "REQUEST", evidence: "confined" }], defaultDecision: "REVIEW", defaultEvidence: "unknown-lifecycle", sourceRefs: ["mvc05-dbutil", "mvc05-config", "mvc05-write-ok", "mvc05-update-ok", "mvc05-delete-ok", "mybatis-java-api"] },
  },
  {
    id: "mvc05-security-error-observability", title: "Front Controller에서 공통 validation·CSRF·authorization·error/log 정책을 적용합니다", lead: "중앙 진입점의 장점을 이용하되 handler별 object authorization과 output encoding 책임을 빠뜨리지 않습니다.",
    explanations: ["controller는 method/content-type/size/encoding/correlation와 mutation CSRF 같은 공통 gate를 handler 전에 적용합니다.", "인증 actor를 request context로 전달하되 password/session id를 Command input이나 log에 복제하지 않습니다.", "write/update/delete는 handler/service가 특정 guestbook row에 대한 object-level authorization/password verification을 수행합니다.", "unknown cmd, validation, not-found, conflict, dependency failure를 stable status/error model로 중앙 매핑합니다.", "public error에는 code/message/action/correlation만, internal sink에는 access-controlled cause를 보존합니다.", "structured log는 route/outcome/status/duration/rows category를 기록하고 writer/email/content/password/SQL/credential을 제거합니다.", "rate limit과 abuse detection은 route/actor/network risk를 조합하고 로그인/비밀번호 실패에 user enumeration을 줄입니다.", "security headers와 no-store는 error/form/redirect에도 적용하고 rendered JSP output encoding은 view에서 context별 검증합니다."],
    concepts: [{ term: "cross-cutting gate", definition: "여러 route에 공통인 encoding·method·CSRF·correlation·limits를 handler 전후 중앙 적용하는 정책입니다.", detail: ["Front Controller 장점입니다.", "개별 authorization을 대체하지 않습니다."] }, { term: "object authorization", definition: "actor가 특정 row/resource에 action을 수행할 권한이 있는지 매 요청 server에서 검증하는 규칙입니다.", detail: ["id/password hidden field를 신뢰하지 않습니다.", "handler/service에서 수행합니다."] }, { term: "error mapper", definition: "validation/domain/persistence/security failure를 stable status·public model·internal log로 변환하는 component입니다.", detail: ["cause를 보존합니다.", "정보 노출을 제한합니다."] }],
    diagnostics: diag("controller security", "공통 CSRF는 통과했지만 다른 사용자의 g_idx를 바꿔 수정할 수 있다.", "CSRF를 object authorization으로 오인하고 handler가 target row 권한을 검증하지 않았습니다.", "actor+target+action authorization/password verification을 mutation transaction 안에서 수행합니다."),
    expertNotes: ["Centralized security policy is useful for cross-cutting checks, but resource authorization requires use-case context unavailable to a generic filter alone.", "Rate-limit keys and logs must avoid unbounded raw identifiers and privacy-sensitive payloads."],
    trace: { className: "ControllerSecurityDecision", title: "공통 gate와 handler security 책임을 분류합니다", purpose: "CSRF·method와 object authorization/output encoding을 혼동하지 않습니다.", cases: [{ input: "METHOD_CSRF", decision: "CONTROLLER", evidence: "cross-cutting" }, { input: "ROW_AUTHORIZATION", decision: "SERVICE", evidence: "object-context" }, { input: "HTML_ENCODING", decision: "VIEW", evidence: "output-context" }], defaultDecision: "DENY", defaultEvidence: "unowned-security-check", sourceRefs: ["mvc05-controller", "owasp-csrf", "owasp-authorization", "owasp-error", "owasp-logging"] },
  },
  {
    id: "mvc05-test-evolution-spring-mvc", title: "Front Controller를 route·concurrency·container·DB tests로 고정하고 Spring MVC로 진화합니다", lead: "pattern의 원리를 검증한 뒤 framework annotation으로 옮겨도 method·binding·service·result 계약이 유지되게 합니다.",
    explanations: ["static audit는 closure15, routes/commands8, field0, mapper5와 credential redaction을 DB 없이 검증합니다.", "JDK unit은 route matrix, typed result, validation/error/security policy와 request confinement를 exact output으로 검증합니다.", "concurrency test는 two actors/actions를 barrier로 겹쳐 handler/model/session/log context 교차가0인지 확인합니다.", "Servlet container test는 lifecycle, method/status/headers, forward/303, filters, session/flash와 response commit을 검증합니다.", "MyBatis real-engine test는 mapper registration, transaction/soft-delete/affected rows와 constraints를 검증합니다.", "browser security/a11y test는 form/JSP encoding, CSRF, navigation, keyboard/focus/error status를 확인합니다.", "Spring MVC로 옮길 때 DispatcherServlet, @Get/PostMapping, argument binding/validation, service transaction, Model/View/RedirectAttributes가 같은 역할을 맡습니다.", "release evidence에는 route inventory, concurrency/HTTP/DB/render results, secret scan, SLO/alerts, rollback과 migration compatibility를 묶습니다."],
    concepts: [{ term: "framework migration", definition: "동일한 use-case/HTTP/persistence 계약을 유지하며 hand-written infrastructure를 framework component로 교체하는 과정입니다.", detail: ["행동 parity를 검증합니다.", "pattern 이해가 선행됩니다."] }, { term: "concurrency regression", definition: "동시 요청에서 actor/action/model/transaction/log context가 섞이지 않는지 반복 검증하는 test입니다.", detail: ["barrier를 사용합니다.", "확률적 sleep을 피합니다."] }, { term: "architecture fitness function", definition: "dependency direction, forbidden imports, route/policy completeness 같은 구조 규칙을 자동 검사하는 test입니다.", detail: ["drift를 막습니다.", "runtime tests를 보완합니다."] }],
    diagnostics: diag("front controller release", "Spring MVC migration 뒤 route/status/PRG/security 동작이 조용히 달라진다.", "class 이름만 바꾸고 기존 route/result contract와 parity test를 유지하지 않았습니다.", "old/new adapters에 같은 contract suite를 실행하고 차이를 명시적으로 승인합니다."),
    expertNotes: ["Framework adoption removes boilerplate but does not remove transaction, authorization, error, threading or view-encoding responsibilities.", "Concurrency tests should control overlap at meaningful milestones rather than relying on timing sleeps."],
    trace: { className: "Mvc05EvidenceDecision", title: "Front Controller 변경별 검증 계층을 선택합니다", purpose: "route policy·threading·container·mapper·view evidence를 분리합니다.", cases: [{ input: "ROUTE_CHANGE", decision: "UNIT+HTTP", evidence: "method-action" }, { input: "STATE_FIELD", decision: "CONCURRENCY", evidence: "request-isolation" }, { input: "MAPPER_CHANGE", decision: "REAL_DB", evidence: "transaction-sql" }], defaultDecision: "FULL_MATRIX", defaultEvidence: "migration-risk", sourceRefs: ["jakarta-servlet", "mybatis-java-api", "mybatis-sqlmap", "spring-mvc-docs"] },
  },
];

const local = (id: string, path: string, usedFor: string[], evidence: string): SessionSource => ({ id, repository: "nohssam/jspstudy", path, usedFor, evidence });
const sources: SessionSource[] = [
  local("mvc05-controller", "guestbook/guestbook/src/main/java/org/study/guestbook/controller/MyController.java", ["routes8", "local command", "forward"], "switch8, default0와 method-local Command를 확인했습니다."),
  local("mvc05-command", "guestbook/guestbook/src/main/java/org/study/guestbook/model/Command.java", ["handler contract", "request/response", "String result"], "Command.exec signature를 확인했습니다."),
  local("mvc05-list-command", "guestbook/guestbook/src/main/java/org/study/guestbook/model/ListCommand.java", ["query", "model", "error"], "selectAll, request list와 view/error path를 확인했습니다."),
  local("mvc05-write-form", "guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteFormCommand.java", ["form route"], "write.jsp result를 확인했습니다."),
  local("mvc05-write-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/WriteOKCommand.java", ["insert", "commit", "result path"], "raw fields, insert, commit와 controller URL result를 확인했습니다."),
  local("mvc05-one", "guestbook/guestbook/src/main/java/org/study/guestbook/model/OneListCommand.java", ["detail", "model"], "g_idx detail query와 gvo attribute를 확인했습니다."),
  local("mvc05-delete-form", "guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteFormCommand.java", ["delete form", "password flow"], "g_idx/g_pwd를 request attributes로 전달함을 확인했습니다."),
  local("mvc05-delete-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/DeleteOKCommand.java", ["soft delete", "commit"], "deleteGuestBook와 commit path를 확인했습니다."),
  local("mvc05-update-form", "guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateFormCommand.java", ["update form", "detail model"], "detail query와 update.jsp model을 확인했습니다."),
  local("mvc05-update-ok", "guestbook/guestbook/src/main/java/org/study/guestbook/model/UpdateOKCommand.java", ["update", "commit"], "update fields, mapper call와 commit path를 확인했습니다."),
  local("mvc05-mapper-interface", "guestbook/guestbook/src/main/java/org/study/guestbook/mapper/GuestBookMapper.java", ["methods5", "persistence port"], "select/insert/detail/delete/update signatures를 확인했습니다."),
  local("mvc05-mapper-xml", "guestbook/guestbook/src/main/resources/mapper/GuestBookMapper.xml", ["statements5", "soft delete", "binding"], "active statements5와 active flag SQL을 확인했습니다."),
  local("mvc05-vo", "guestbook/guestbook/src/main/java/org/study/guestbook/vo/GuestBookVO.java", ["row fields", "password exposure", "DTO split"], "password 포함 String properties를 확인했습니다."),
  local("mvc05-dbutil", "guestbook/guestbook/src/main/java/org/study/guestbook/db/DBUtil.java", ["factory", "session lifecycle"], "static factory와 manual session을 확인했습니다."),
  local("mvc05-config", "guestbook/guestbook/src/main/resources/mybatis-config.xml", ["mapper registration", "pooled datasource", "secret hygiene"], "credential 값은 복제하지 않고 sensitive property 존재만 확인했습니다."),
  { id: "jakarta-servlet", repository: "Jakarta EE", path: "Servlet 6.1 specification", publicUrl: "https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1", usedFor: ["lifecycle", "concurrency", "routing/dispatch"], evidence: "공식 Jakarta Servlet specification입니다." },
  { id: "rfc9110", repository: "IETF", path: "RFC 9110 HTTP Semantics", publicUrl: "https://www.rfc-editor.org/rfc/rfc9110", usedFor: ["methods", "status", "redirect"], evidence: "HTTP semantics의 IETF 표준입니다." },
  { id: "mybatis-java-api", repository: "MyBatis", path: "Java API", publicUrl: "https://mybatis.org/mybatis-3/java-api.html", usedFor: ["SqlSession", "mapper", "transaction"], evidence: "공식 MyBatis Java API입니다." },
  { id: "mybatis-sqlmap", repository: "MyBatis", path: "Mapper XML", publicUrl: "https://mybatis.org/mybatis-3/sqlmap-xml.html", usedFor: ["namespace/id", "result/parameter mapping"], evidence: "공식 MyBatis mapper XML reference입니다." },
  { id: "java-memory-model", repository: "OpenJDK", path: "JLS 17 Threads and Locks", publicUrl: "https://docs.oracle.com/javase/specs/jls/se21/html/jls-17.html", usedFor: ["happens-before", "thread safety"], evidence: "Java SE21 언어 명세의 thread/memory model 장입니다." },
  { id: "spring-mvc-docs", repository: "Spring", path: "Spring MVC", publicUrl: "https://docs.spring.io/spring-framework/reference/web/webmvc.html", usedFor: ["DispatcherServlet migration", "mapping/model/view"], evidence: "공식 Spring Framework MVC reference입니다." },
  { id: "owasp-password", repository: "OWASP", path: "Password Storage Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html", usedFor: ["password projection", "hash boundary"], evidence: "OWASP password storage 지침입니다." },
  { id: "owasp-csrf", repository: "OWASP", path: "CSRF Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html", usedFor: ["mutation gate"], evidence: "OWASP CSRF 방어 지침입니다." },
  { id: "owasp-authorization", repository: "OWASP", path: "Authorization Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", usedFor: ["object authorization", "deny by default"], evidence: "OWASP authorization 지침입니다." },
  { id: "owasp-error", repository: "OWASP", path: "Error Handling Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html", usedFor: ["public/internal errors"], evidence: "OWASP error handling 지침입니다." },
  { id: "owasp-logging", repository: "OWASP", path: "Logging Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html", usedFor: ["redaction", "correlation"], evidence: "OWASP logging 지침입니다." },
];

const session = buildMvcSession({
  inventoryId: "mvc-05-guestbook-front-controller", order: 5, title: "방명록 Front Controller", subtitle: "Controller→Command→Mapper→VO→View 흐름을 method routing·typed result·request confinement·composition/service transaction·Spring MVC 진화까지 연결합니다.", level: "고급", estimatedMinutes: 990,
  coreQuestion: "하나의 Servlet이 여덟 방명록 action을 안전하게 분배하면서 요청 상태를 섞지 않고, handler·mapper·view·transaction·보안 책임을 어떻게 명확히 나눌까요?",
  summary: "inventory6과 controller가 직접 참조하는 commands8·DBUtil/config까지 실제 Java/XML closure15를 읽었습니다. routes8/default0, command constructions/implementations8, Servlet Command fields0, mapper methods/active statements5, DML commits3, DBUtil openSession1, sensitive config properties2(redacted)입니다. 실제 Servlet/MyBatis/DB/credential은 실행하지 않았습니다. Model2 MVC flow, method+action routing, typed Command result, persistence/view data minimization, servlet request confinement/race, forward/PRG, composition/service transaction, security/error/observability와 Spring MVC parity testing을 10장으로 완성합니다.",
  objectives: ["Front Controller와 Model2 MVC 전체 흐름을 설명한다.", "method+action allowlist와 exhaustive default를 구현한다.", "Command String path를 typed input/result로 발전시킨다.", "Mapper/VO를 HTTP/view와 분리하고 projection을 최소화한다.", "Servlet shared instance와 request-local state를 구분한다.", "forward model과 commit 뒤303 redirect를 분리한다.", "composition root와 service transaction owner를 설계한다.", "공통 CSRF/error/logging과 object authorization을 구분한다.", "concurrency/container/DB/browser tests와 Spring MVC migration parity를 검증한다."],
  prerequisites: [{ title: "PRG와 오류 처리", reason: "Command 결과를 forward/redirect/error로 정확히 적용하는 typed dispatch가 필요합니다.", sessionSlug: "mvc-04-prg-errors" }, { title: "MyBatis 설정·Mapper 결합", reason: "mapper interface/XML, SqlSession과 transaction lifecycle을 방명록 closure에 사용합니다.", sessionSlug: "mvc-01-mybatis-config-mapper" }],
  keywords: ["Front Controller", "Model 2 MVC", "Command pattern", "route table", "ActionResult", "request confinement", "Servlet thread safety", "mapper", "VO", "projection DTO", "composition root", "service transaction", "PRG", "authorization", "Spring MVC"], topics,
  lab: { title: "동시 요청에 안전한 Guestbook Front Controller", scenario: "원본 routes8의 기능을 유지하면서 typed routes/results, password-free view DTO, service transaction과 공통 security/observability를 갖춘 controller로 재설계합니다.", setup: ["route8 method/action/policy matrix와 null/unknown/wrong-method fixtures를 준비합니다.", "two actors/actions concurrency fixture와 ephemeral MyBatis DB/container를 준비합니다.", "public model/error/log field allowlist를 작성합니다."], steps: ["closure15 static audit를 실행합니다.", "immutable method+action registry와 startup validation을 구현합니다.", "Servlet adapter가 raw request를 typed CommandInput으로 변환합니다.", "handlers가 Forward/Redirect/Error result를 반환하게 합니다.", "password-free list/detail projection과 active scope를 만듭니다.", "service가 write/update/delete transaction을 소유합니다.", "모든 request state를 local로 제한하고 shared dependencies를 final/thread-safe로 검증합니다.", "CSRF/correlation 공통 gate와 object authorization/error mapping을 연결합니다.", "concurrency/HTTP/MyBatis/render security/a11y tests를 실행합니다.", "Spring MVC adapter에 같은 contract suite를 실행해 parity를 확인합니다."], expectedResult: ["routes8과 method policy가 exhaustive하고 unknown은 fail-closed합니다.", "동시 요청에서 actor/action/model/session/log context가 섞이지 않습니다.", "view/public log에 password·content·credential이 노출되지 않습니다.", "write transaction은 partial commit 없이303 PRG 결과를 만듭니다.", "hand-written와 Spring MVC adapter가 같은 contract를 통과합니다."], cleanup: ["ephemeral DB/container/session/flash와 owned test artifacts만 제거합니다.", "pool/session/thread/in-flight leak0을 확인합니다.", "HTTP/log evidence에서 Cookie/CSRF/PII를 redact합니다."], extensions: ["annotation processor/ArchUnit으로 forbidden dependency를 검사합니다.", "route metadata에서 authorization/audit 문서를 생성합니다.", "async Servlet로 바꾸며 context propagation과 timeout을 검증합니다.", "service interface를 REST와 JSP adapter가 함께 사용하게 합니다."] },
  exercises: [
    { difficulty: "따라하기", prompt: "cmd8 switch를 immutable method+action route table로 바꾸세요.", requirements: ["GET/POST policy를 구분합니다.", "duplicate를 startup에 거부합니다.", "null/unknown은404/400입니다.", "wrong method는405+Allow입니다.", "full route set exact test를 둡니다."], hints: ["doPost를 무조건 doGet으로 넘기지 마세요."], expectedOutcome: "오타/잘못된 method가 null command500으로 이어지지 않습니다.", solutionOutline: ["RouteKey record와 Map.copyOf registry를 만듭니다."] },
    { difficulty: "응용", prompt: "Servlet shared-field race를 재현하고 request confinement로 고치세요.", requirements: ["broken servlet field command를 만듭니다.", "barrier로 two requests를 겹칩니다.", "wrong-handler trace를 증명합니다.", "local variable로 수정합니다.", "100회 반복 exact isolation을 검증합니다."], hints: ["sleep보다 barrier로 덮어쓰기 순서를 제어하세요."], expectedOutcome: "race 원인과 수정 뒤 actor/action 교차0이 재현 가능합니다.", solutionOutline: ["field write/read 사이를 두 latch로 동기화합니다."] },
    { difficulty: "설계", prompt: "Guestbook Front Controller→Spring MVC migration ADR을 작성하세요.", requirements: ["route/result/model/service contracts를 고정합니다.", "transaction/CSRF/authorization owners를 표시합니다.", "password-free projections를 포함합니다.", "concurrency/container/DB/browser parity matrix를 만듭니다.", "secret/log/error 정책을 포함합니다.", "rollback과 staged migration을 설계합니다."], hints: ["framework migration이 보안/transaction 책임을 없애지 않습니다."], expectedOutcome: "행동 drift 없이 framework adapter를 교체하는 실행 계획이 완성됩니다.", solutionOutline: ["현재 contract→target mapping→parity tests→cutover→rollback 순으로 작성합니다."] },
  ],
  nextSessions: ["mvc-06-guestbook-crud-security"], sources,
  sourceCoverage: { filesRead: 15, filesUsed: 15, uncoveredNotes: ["inventory6에서 MyController가 생성하는 Command8과 DBUtil/config까지 직접 Java/XML closure15를 읽고 사용했습니다.", "JSP view files는 mvc-06의 CRUD/security inventory에서 상세히 다루며 이 세션 coverage에는 중복 계산하지 않았습니다.", "config credential 값/hash, 실제 DB rows, Servlet/MyBatis runtime은 사용하거나 출력하지 않았습니다."] },
});

export default session;
