import type { DetailedCodeExample, DiagnosticCase, SessionSource } from "../../types";
import { buildMvcSession, type MvcTopicSpec } from "./mvc-01-mybatis-config-mapper.ts";

const diagnostics = (area: string, symptom: string, cause: string, fix: string): DiagnosticCase[] => [
  { symptom, likelyCause: cause, checks: [`${area}의 request method·cmd·selected command·result·dispatch type·status를 한 trace로 확인합니다.`, "response committed 여부와 browser history를 확인합니다.", "public body와 internal log에서 secret·PII·stack trace를 검사합니다."], fix, prevention: `${area}의 success/validation/not-found/conflict/dependency/unknown-command test matrix를 유지합니다.` },
  { symptom: "상태 기계 unit test는 통과하지만 실제 browser/container 흐름이 다르다.", likelyCause: "JDK 예제는 Servlet dispatch, URL rewriting, session/flash, response commit과 browser navigation을 실행하지 않습니다.", checks: ["unit과 container/browser integration 범위를 구분합니다.", "실제 status·Location·Set-Cookie·history를 캡처합니다.", "JavaScript 비활성·multi-tab·refresh를 재현합니다."], fix: "격리 container와 HTTP client/browser로 POST→redirect→GET를 end-to-end 검증합니다.", prevention: "exact HTTP transcript와 public-safe log assertions를 release evidence로 둡니다." },
];

const audit: DetailedCodeExample = {
  id: "powershell-mvc04-original-static-audit", title: "오류 JSP5와 Ex12 controller의 dispatch·status·logging shape를 감사합니다", language: "powershell", filename: "verify-original-mvc04.ps1", purpose: "Servlet/browser 실행 없이 alert/location, route cases, default/null guard, forward/redirect/status/logging 부재를 exact하게 보존합니다.",
  code: String.raw`param([Parameter(Mandatory)][string]$SourceRoot)
$ErrorActionPreference='Stop'
$rels=@(
 'jspstudy/src/main/webapp/day03/ex07_db_output.jsp',
 'jspstudy/src/main/webapp/day03/ex08_db_output.jsp',
 'jspstudy/src/main/webapp/day03/ex10_error.jsp',
 'jspstudy/src/main/webapp/day03/ex12_error.jsp',
 'jspstudy/src/main/webapp/day03/ex13_error.jsp',
 'jspstudy/src/main/java/org/study/jspstudy/day03/Ex12.java'
)
$files=@($rels|ForEach-Object{Get-Item -LiteralPath (Join-Path $SourceRoot $_)})
if($files.Count-ne6){throw 'inventory drift'}
$before=@{};foreach($file in $files){$before[$file.FullName]=(Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash}
$text=($files|ForEach-Object{[IO.File]::ReadAllText($_.FullName)})-join[Environment]::NewLine
$active=[regex]::Replace(([regex]::Replace($text,'(?s)<%--.*?--%>','')),'(?s)/\*.*?\*/','')
$active=[regex]::Replace($active,'(?m)//.*$','')
function Count([string]$value,[string]$pattern){([regex]::Matches($value,$pattern,[Text.RegularExpressions.RegexOptions]::IgnoreCase)).Count}
$alerts=Count $active 'alert\s*\(';$locations=Count $active 'location\.href\s*='
$cases=Count $active 'case\s+"';$defaults=Count $active '(?m)^\s*default\s*:';$guards=Count $active '(?:command\s*==\s*null|null\s*==\s*command)'
$forwards=Count $active '\.forward\s*\(';$redirects=Count $active 'sendRedirect\s*\(';$statuses=Count $active 'setStatus\s*\('
$logs=Count $active '(?:LoggerFactory|getLogger\s*\(|\.log\s*\()'
if($alerts-ne5-or$locations-ne5-or$cases-ne8-or$defaults-ne0-or$guards-ne0-or$forwards-ne1-or$redirects-ne0-or$statuses-ne0-or$logs-ne0){throw 'source shape drift'}
foreach($file in $files){if((Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash-cne$before[$file.FullName]){throw 'source hash drift'}}
"files=6|alerts=5|jsLocations=5|routeCases=8|defaultRoutes=0|nullGuards=0|forwards=1|serverRedirects=0|statusWrites=0|loggerCalls=0|hashes=6/6"
"execution=static-only|servlet=not-started|browser=not-opened|db=not-contacted"`,
  walkthrough: [{ lines: "1-11", explanation: "오류/결과 JSP5와 controller1의 inventory를 고정합니다." }, { lines: "12-17", explanation: "hash를 저장하고 JSP/Java comments를 제외한 active source를 만듭니다." }, { lines: "18-23", explanation: "client navigation, routing fallback, server dispatch/status/logging counts를 계산합니다." }, { lines: "24-26", explanation: "exact shape와 source 불변성을 확인하고 runtime 미실행을 출력합니다." }],
  run: { environment: ["PowerShell 7+", "D:/dev/jspstudy source root", "정적 읽기만", "Servlet/browser/DB 불필요"], command: "pwsh -NoProfile -File verify-original-mvc04.ps1 -SourceRoot D:/dev/jspstudy" },
  output: { value: "files=6|alerts=5|jsLocations=5|routeCases=8|defaultRoutes=0|nullGuards=0|forwards=1|serverRedirects=0|statusWrites=0|loggerCalls=0|hashes=6/6\nexecution=static-only|servlet=not-started|browser=not-opened|db=not-contacted", explanation: ["다섯 JSP 모두 alert 뒤 JavaScript location으로 목록에 이동합니다.", "controller는 cases8이지만 default/null guard가 없어 missing/unknown cmd가 안전하게 종료되지 않습니다.", "모든 결과는 forward되고 server redirect/status/logging은0입니다."] },
  experiments: [{ change: "default command를 추가합니다.", prediction: "defaultRoutes0이 drift합니다.", result: "개선본에서는 typed400/404 route와 negative test로 검증합니다." }, { change: "sendRedirect를 추가합니다.", prediction: "serverRedirects0이 실패합니다.", result: "PRG 개선은303/Location transcript로 별도 증명합니다." }, { change: "JSP를 browser로 실행합니다.", prediction: "history 이동과 alert가 발생하고 DB-linked controller까지 접근할 수 있습니다.", result: "원본 audit는 source만 읽습니다." }],
  sourceRefs: ["mvc04-delete-missing", "mvc04-delete-fk", "mvc04-insert-error", "mvc04-id-error", "mvc04-update-error", "mvc04-controller"],
};

const topics: MvcTopicSpec[] = [
  {
    id: "mvc04-original-dispatch-error-audit", title: "원본 JSP5·controller1의 client redirect와 error contract를 정확히 감사합니다", lead: "alert/location 흐름을 PRG로 오인하지 않고 route·status·logging gaps를 source evidence로 고정합니다.",
    explanations: ["ex07/08/10/12/13 JSP는 각각 삭제 대상 없음, FK 삭제 불가, 삽입 오류, 없는 id, 수정 오류 alert를 보여 줍니다.", "다섯 JSP 모두 JavaScript `location.href`로 목록 URL에 이동하므로 JavaScript가 꺼지면 복구 navigation도 없습니다.", "Ex12 controller는 GET/POST를 한 doGet으로 모으고 cmd eight cases를 Command 구현에 매핑합니다.", "cmd가 null이면 Java switch가 실패하고 unknown 값이면 command가 null인 채 exec 호출되어 실패할 수 있습니다.", "Command가 반환한 path는 성공/오류/다른 controller URL처럼 보여도 항상 RequestDispatcher.forward에 전달됩니다.", "server redirect는0이라 mutation response가 POST body인 상태에서 refresh/replay 의미가 명확하지 않습니다.", "status write와 logger call이0이라 오류 JSP도 기본200으로 보이고 운영 원인은 보존되지 않습니다.", "audit는 source shape/hash만 확인하고 Servlet, JavaScript, browser, DB와 credential을 실행하지 않습니다."],
    concepts: [{ term: "client-side navigation", definition: "응답 HTML의 JavaScript가 browser URL을 바꾸는 후속 동작입니다.", detail: ["server status/Location과 다릅니다.", "JS 비활성 시 실행되지 않습니다."] }, { term: "dispatch contract", definition: "Command 결과가 forward/redirect/body 중 무엇이며 어떤 status와 model을 요구하는지 표현한 합의입니다.", detail: ["문자열 path보다 강한 type이 좋습니다.", "commit 전에 결정합니다."] }, { term: "fail-closed route", definition: "missing/unknown command를 임의 성공 분기로 보내지 않고 명시 오류로 종료하는 routing 정책입니다.", detail: ["default가 필요합니다.", "지원 method도 제한합니다."] }],
    diagnostics: diagnostics("원본 dispatch", "cmd가 없거나 오타면500 NullPointerException이 난다.", "switch null/unknown을 처리하는 default route와 command null guard가 없습니다.", "request를 validation한 route table이 typed400/404 result를 반환하게 합니다."),
    expertNotes: ["A JavaScript location change after a POST response is not equivalent to an HTTP redirect in status, history, caching or non-script clients.", "Returning HTTP 200 for an error view corrupts monitoring, caches and client behavior even if the human-readable text says error."], customExample: audit,
  },
  {
    id: "mvc04-front-controller-routing-result", title: "cmd switch를 method-aware route table과 typed ActionResult로 바꿉니다", lead: "문자열 path 하나에 view·redirect·status를 섞지 않고 routing과 execution 결과를 exhaustive type으로 표현합니다.",
    explanations: ["route key는 method+action으로 구성해 GET form/read와 POST mutation을 구분합니다.", "cmd는 hidden field여도 untrusted이므로 null/blank/unknown/duplicate parameter를 검증합니다.", "route table은 application startup에 duplicate key와 missing handler를 검사하고 immutable하게 publish합니다.", "ActionResult는 Forward(view,model,status), Redirect(location,status,flash), Error(status,code)를 분리할 수 있습니다.", "controller는 handler가 response를 이미 commit했는지 추측하지 않고 한 곳에서 result를 적용합니다.", "GET/POST 외 method는405와 Allow를 반환하고 unsupported action은400 또는404 정책을 고정합니다.", "command instance가 stateless인지 검증하고 request-specific 값을 servlet field에 저장하지 않습니다.", "route unit test는 전체 허용 set과 UNKNOWN을 비교해 새 action 추가 시 default 누락을 드러냅니다."],
    concepts: [{ term: "route table", definition: "method·action key를 handler에 매핑하는 검증된 immutable registry입니다.", detail: ["startup에 중복을 찾습니다.", "unknown은 명시 실패합니다."] }, { term: "ActionResult", definition: "handler의 HTTP status·dispatch kind·target·model/flash를 type으로 표현한 결과입니다.", detail: ["문자열 path ambiguity를 없앱니다.", "controller가 적용합니다."] }, { term: "405 Method Not Allowed", definition: "resource는 있지만 해당 HTTP method를 지원하지 않음을 Allow header와 함께 나타내는 status입니다.", detail: ["404와 다릅니다.", "method contract를 공개합니다."] }],
    diagnostics: diagnostics("front controller routing", "Command가 controller URL을 반환했는데 forward loop나 엉뚱한 JSP가 열린다.", "return String이 view path와 redirect location을 구분하지 못하고 controller가 모두 forward합니다.", "sealed/typed ActionResult와 중앙 dispatch applicator를 사용합니다."),
    expertNotes: ["Typed action results prevent a handler from accidentally smuggling an external URL into a server-side forward.", "Route lookup must not be an authorization decision; handlers still require actor/resource authorization."],
    trace: { className: "ActionRouteDecision", title: "method+action을 typed dispatch result로 판정합니다", purpose: "supported, wrong method와 unknown route를 exhaustive하게 분리합니다.", cases: [{ input: "GET_LIST", decision: "FORWARD_200", evidence: "list-view" }, { input: "POST_INSERT", decision: "HANDLER", evidence: "mutation" }, { input: "GET_DELETE", decision: "405", evidence: "Allow-POST" }], defaultDecision: "404", defaultEvidence: "unknown-route", sourceRefs: ["mvc04-controller", "jakarta-servlet", "rfc9110"] },
  },
  {
    id: "mvc04-post-redirect-get-state-machine", title: "POST-Redirect-GET를 transaction outcome과 연결합니다", lead: "commit된 mutation 응답은303 Location으로 끝내고 GET이 새 representation을 렌더링하게 합니다.",
    explanations: ["PRG는 browser가 POST 성공 뒤 새 GET을 수행하게 해 refresh가 mutation body를 다시 제출하지 않도록 합니다.", "redirect는 transaction commit 성공이 확정된 뒤에만 보냅니다. rollback/validation failure를 성공 URL로 redirect하면 상태가 거짓이 됩니다.", "303 See Other는 POST 결과를 Location의 GET으로 조회하라는 의도를 명확히 표현합니다.", "302는 user agent 역사적 동작에 의존할 수 있고307/308은 method/body를 유지해 mutation replay 위험이 있습니다.", "Location은 context path를 포함해 encode하고 open redirect가 되지 않도록 server-owned route builder만 사용합니다.", "PRG는 double click/concurrent retry를 완전히 막지 않으므로 idempotency key와 DB uniqueness/transaction이 여전히 필요합니다.", "GET은 mutation 결과를 durable DB에서 다시 읽고 flash는 일회성 메시지만 전달합니다.", "HTTP transcript test는 POST status303/Location/body policy, following GET200와 refresh side-effect0을 확인합니다."],
    concepts: [{ term: "PRG", definition: "POST 처리 뒤 redirect 응답을 보내고 browser가 GET으로 결과 화면을 조회하는 흐름입니다.", detail: ["refresh 재제출을 줄입니다.", "transaction/idempotency를 대체하지 않습니다."] }, { term: "303 See Other", definition: "현재 요청 결과를 Location의 다른 resource에 GET으로 조회하라고 지시하는 redirect status입니다.", detail: ["POST 이후 적합합니다.", "Location이 필요합니다."] }, { term: "open redirect", definition: "공격자가 redirect destination을 외부/위험 URL로 조작할 수 있는 취약점입니다.", detail: ["server route allowlist를 씁니다.", "raw returnUrl을 검증합니다."] }],
    diagnostics: diagnostics("PRG", "저장 뒤 새로고침할 때 중복 insert 또는 form 재전송 경고가 나타난다.", "mutation success를 forward HTML로 응답해 browser의 현재 history entry가 POST입니다.", "commit 후303+server-owned Location을 반환하고 결과 GET을 분리합니다."),
    expertNotes: ["PRG changes navigation semantics; it cannot make a non-idempotent operation safe under network retries by itself.", "Do not emit a success redirect until the commit outcome is known; an indeterminate commit needs reconciliation."],
    trace: { className: "PrgOutcomeDecision", title: "POST transaction 결과를 forward/redirect/error로 변환합니다", purpose: "성공·validation·commit unknown에 맞는 HTTP 흐름을 고정합니다.", cases: [{ input: "COMMITTED", decision: "303", evidence: "GET-resource" }, { input: "VALIDATION_FAILED", decision: "FORWARD_400", evidence: "same-request-errors" }, { input: "COMMIT_UNKNOWN", decision: "503", evidence: "reconcile" }], defaultDecision: "500", defaultEvidence: "correlation-only", sourceRefs: ["mvc04-controller", "mybatis-java-api", "rfc9110", "owasp-unvalidated-redirect"] },
  },
  {
    id: "mvc04-retry-idempotency-navigation", title: "PRG와 idempotency·double-click·network retry의 책임을 구분합니다", lead: "browser refresh를 줄이는 navigation pattern과 서버 중복 방지·unknown-outcome 복구를 서로 대체하지 않게 합니다.",
    explanations: ["PRG는 현재 history entry를 GET으로 바꾸지만 첫 POST의 double click, proxy/client retry와 response loss는 이미 두 요청을 만들 수 있습니다.", "submit button disable은 UX 보조이며 공격자·다중 탭·network retry를 막는 transaction guarantee가 아닙니다.", "idempotency key는 actor·operation·payload fingerprint에 묶고 같은 key/same payload에는 기존 결과를 반환합니다.", "같은 key/different payload는409로 거부해 공격이나 client bug를 숨기지 않습니다.", "DB unique constraint와 idempotency record/outbox를 같은 transaction에 두면 race에서도 single winner를 만들 수 있습니다.", "commit response loss는 rollback으로 단정하지 않고 key/result 조회로 reconciliation한 뒤 redirect destination을 복구합니다.", "GET result page는 mutation을 재실행하지 않고 durable resource/idempotency outcome만 읽습니다.", "concurrent POST2, retry-after-timeout, same/different payload와 back/refresh side-effect counts를 실제 DB/HTTP test로 검증합니다."],
    concepts: [{ term: "navigation idempotence", definition: "browser 이동·새로고침이 mutation을 다시 실행하지 않도록 GET representation으로 분리하는 성질입니다.", detail: ["PRG가 돕습니다.", "POST 자체 idempotency와 다릅니다."] }, { term: "mutation idempotency", definition: "동일 업무 요청이 여러 번 도착해도 durable side effect를 한 번만 적용하는 서버 계약입니다.", detail: ["key와 unique constraint를 사용합니다.", "payload mismatch를 거부합니다."] }, { term: "replay result", definition: "이미 처리된 idempotency key에 저장한 status/resource/version을 재시도 client에 다시 제공하는 결과입니다.", detail: ["secret body는 저장하지 않습니다.", "expiry 정책이 필요합니다."] }],
    diagnostics: diagnostics("PRG/idempotency", "303을 적용했는데도 double click이나 timeout 재시도에서 row가 두 개 생긴다.", "PRG를 서버 mutation idempotency로 오인해 unique key/idempotency transaction이 없습니다.", "actor-scoped key+fingerprint, unique constraint와 replay/reconciliation 결과를 구현합니다."),
    expertNotes: ["PRG is a user-agent navigation pattern, while idempotency is a server-side business guarantee under duplicate delivery.", "Idempotency result storage must be access-controlled and bounded; it is not a place to retain full sensitive request bodies."],
    trace: { className: "MutationReplayDecision", title: "중복 POST를 replay/conflict/new execution으로 판정합니다", purpose: "PRG 밖에서 발생한 duplicate delivery를 서버 transaction으로 안전하게 다룹니다.", cases: [{ input: "NEW_KEY", decision: "EXECUTE_ONCE", evidence: "reserve-key" }, { input: "SAME_KEY_SAME_BODY", decision: "REPLAY", evidence: "stored-result" }, { input: "SAME_KEY_OTHER_BODY", decision: "409", evidence: "fingerprint-mismatch" }], defaultDecision: "REJECT", defaultEvidence: "invalid-idempotency-key", sourceRefs: ["rfc9110", "owasp-transaction-authorization"] },
  },
  {
    id: "mvc04-flash-scope-once-multitab", title: "flash message를 일회성·multi-tab·distributed-session 조건에서 안전하게 전달합니다", lead: "redirect 사이 request attribute가 사라지는 문제를 secret 없는 one-time message envelope로 해결합니다.",
    explanations: ["forward의 request attribute는 redirect 뒤 새 request에 없으므로 success/error notice를 flash store에 저장할 수 있습니다.", "flash에는 message code, safe parameters, severity, target route, nonce와 expiry만 두고 raw password/form/exception을 저장하지 않습니다.", "GET이 flash를 읽을 때 atomic consume해야 refresh에서 반복되지 않습니다.", "session에 단일 flash slot을 쓰면 두 tab의 POST/GET 순서가 바뀌어 메시지가 다른 화면에 나타날 수 있습니다.", "nonce를 redirect URL이나 server correlation에 연결하고 target/user/session을 검증해 multi-tab 혼선을 줄입니다.", "cluster에서는 sticky session 또는 shared store가 필요하며 consume 원자성·TTL·serialization/version을 검증합니다.", "flash cookie를 쓴다면 서명/암호화, size, SameSite, Secure, HttpOnly와 replay를 다뤄야 합니다.", "accessibility를 위해 GET page의 notice는 role=status/alert와 focus/heading 흐름으로 인지 가능하게 합니다."],
    concepts: [{ term: "flash scope", definition: "redirect 다음 요청에서 한 번 읽고 제거하는 짧은 수명의 메시지 상태입니다.", detail: ["request보다 길고 session보다 짧습니다.", "민감 값은 저장하지 않습니다."] }, { term: "atomic consume", definition: "flash를 한 요청만 가져가고 동시에 제거해 중복 표시를 막는 연산입니다.", detail: ["race를 방지합니다.", "distributed store에서 중요합니다."] }, { term: "flash nonce", definition: "특정 mutation/redirect와 일회성 message를 연결하는 추측 어려운 식별자입니다.", detail: ["user/route와 묶습니다.", "TTL을 둡니다."] }],
    diagnostics: diagnostics("flash scope", "두 탭에서 저장하면 성공 메시지가 다른 탭에 나타나거나 두 번 보인다.", "session에 global flash 하나를 두고 target/nonce/atomic consume을 사용하지 않았습니다.", "per-operation nonce와 atomic get-and-delete, user/route/TTL validation을 적용합니다."),
    expertNotes: ["Flash state should carry presentation-safe codes, not the authoritative mutation outcome; the GET should read durable state.", "A signed flash cookie preserves integrity but does not automatically provide confidentiality."],
    trace: { className: "FlashConsumeDecision", title: "flash nonce·target·expiry로 표시 여부를 결정합니다", purpose: "wrong tab, replay와 expired message를 fail-closed 처리합니다.", cases: [{ input: "MATCH_FRESH", decision: "SHOW_ONCE", evidence: "atomic-consume" }, { input: "WRONG_TARGET", decision: "DROP", evidence: "route-mismatch" }, { input: "EXPIRED", decision: "DROP", evidence: "ttl" }], defaultDecision: "DROP", defaultEvidence: "unknown-flash", sourceRefs: ["jakarta-servlet", "owasp-session"] },
  },
  {
    id: "mvc04-validation-error-redisplay", title: "validation 오류는 입력·field errors를 보존해 같은 request로 안전하게 다시 표시합니다", lead: "모든 실패를 redirect/alert로 보내 사용자가 입력을 잃지 않게 하고 secret과 공격 문자열은 재노출하지 않습니다.",
    explanations: ["validation failure는 mutation을 실행/commit하지 않았으므로 form view에 forward해 request model을 유지하는 흐름이 단순합니다.", "field error는 field name, stable code, safe localized message를 담고 rejected raw value는 log에 복제하지 않습니다.", "비밀번호·CSRF token·file bytes는 redisplay model에 넣지 않고 사용자가 다시 입력하게 합니다.", "title/publisher 같은 비민감 값도 HTML attribute/text context에 맞게 encoding해 XSS를 막습니다.", "global errors와 field errors를 분리하고 summary에서 각 control로 accessible link/focus를 제공합니다.", "form action/method와 CSRF token은 서버가 새로 생성하고 client가 제출한 URL/cmd를 그대로 반영하지 않습니다.", "invalid request에400을 유지할지 form UX를 위해200을 쓸지 API/HTML 정책을 문서화하고 monitoring에는 outcome을 별도 기록합니다.", "validation rules와 error codes를 command unit test, rendered form DOM/a11y test로 검증합니다."],
    concepts: [{ term: "field error", definition: "특정 입력 field의 validation 실패를 field·code·safe message로 표현한 값입니다.", detail: ["raw payload와 분리합니다.", "control과 연결합니다."] }, { term: "error summary", definition: "form 상단에서 오류 수와 각 field로 이동 가능한 설명을 제공하는 접근성 pattern입니다.", detail: ["focus를 관리합니다.", "inline error와 함께 둡니다."] }, { term: "redisplay model", definition: "실패한 form을 다시 그리는 데 필요한 안전한 값·오류·새 token만 포함한 view model입니다.", detail: ["password/file은 제외합니다.", "context encoding합니다."] }],
    diagnostics: diagnostics("validation redisplay", "오류 후 사용자가 입력한 값이 사라지거나 공격 문자열이 실행된다.", "모든 실패를 alert redirect로 보내 model을 잃거나 raw input을 EL/attribute에 직접 넣었습니다.", "field-error view model과 context encoding, secret exclusion을 적용해 같은 request forward로 표시합니다."),
    expertNotes: ["Validation failures should preserve user effort without persisting or logging secrets and oversized malicious payloads.", "HTTP status policy for HTML form errors should be explicit; operational outcome metrics must not rely only on status."],
    trace: { className: "FormFailureDecision", title: "form 실패 종류에 따라 forward·redirect·error를 선택합니다", purpose: "검증 오류와 commit 후 성공/infra failure를 다른 수명으로 처리합니다.", cases: [{ input: "FIELD_ERRORS", decision: "FORWARD_FORM", evidence: "safe-redisplay" }, { input: "COMMITTED", decision: "303", evidence: "flash-code" }, { input: "DEPENDENCY_FAIL", decision: "503", evidence: "correlation" }], defaultDecision: "400", defaultEvidence: "malformed-request", sourceRefs: ["mvc04-insert-error", "mvc04-update-error", "jakarta-servlet", "owasp-xss", "owasp-input-validation"] },
  },
  {
    id: "mvc04-error-taxonomy-status-view", title: "error command/view를 stable taxonomy와 실제 HTTP status로 만듭니다", lead: "삭제 대상 없음·FK·validation·conflict·dependency failure를 같은200 alert로 축약하지 않습니다.",
    explanations: ["없는 resource는404, malformed input400, authorization policy403/404, FK/optimistic conflict409, transient dependency503, unknown500으로 분류할 수 있습니다.", "status를 response body write/forward 전에 설정해야 monitoring, cache와 client가 의미를 받습니다.", "ErrorViewModel에는 public code/message/action/correlation만 두고 stack trace, SQL, constraint name, filesystem/JDBC path를 넣지 않습니다.", "중앙 error mapper는 domain/persistence/validation exceptions를 stable category로 변환하고 cause chain은 internal log에 보존합니다.", "오류 JSP도 normal layout, charset, CSP/security headers와 accessible heading/navigation을 제공해야 합니다.", "404/403 통합은 object existence disclosure threat model에 따라 결정합니다.", "error view 자체가 예외를 내면 minimal fallback body와 original correlation을 유지하고 recursive dispatch를 막습니다.", "contract test는 category별 exact status, headers, model allowlist와 internal-cause absence를 렌더링해 검증합니다."],
    concepts: [{ term: "error taxonomy", definition: "오류를 안정된 category·status·retry·사용자 action·owner로 매핑한 체계입니다.", detail: ["vendor message와 분리합니다.", "운영 alert를 연결합니다."] }, { term: "error view model", definition: "사용자에게 공개 가능한 오류 정보만 담은 rendering DTO입니다.", detail: ["correlation을 포함합니다.", "internal cause를 제외합니다."] }, { term: "error fallback", definition: "정상 error rendering도 실패할 때 recursion 없이 최소 안전 응답을 만드는 마지막 경계입니다.", detail: ["commit 여부를 고려합니다.", "민감 상세를 숨깁니다."] }],
    diagnostics: diagnostics("error taxonomy", "오류 화면이 보이지만 HTTP status는200이라 cache/monitor가 성공으로 센다.", "JSP alert text만 바꾸고 response status를 body/forward 전에 설정하지 않았습니다.", "typed ErrorResult가 status·view model·cache headers를 중앙에서 적용하게 합니다."),
    expertNotes: ["An error page with status 200 is semantically successful to intermediaries regardless of its visible message.", "Error mapping must avoid leaking object existence when authorization policy treats it as sensitive."],
    trace: { className: "ErrorStatusDecision", title: "Book 오류 category를 status와 view action으로 매핑합니다", purpose: "기술 예외와 사용자 복구를 stable result로 연결합니다.", cases: [{ input: "BOOK_ABSENT", decision: "404", evidence: "back-to-list" }, { input: "FOREIGN_KEY", decision: "409", evidence: "preserve-reference" }, { input: "DB_UNAVAILABLE", decision: "503", evidence: "retry-later" }], defaultDecision: "500", defaultEvidence: "correlation-only", sourceRefs: ["mvc04-delete-missing", "mvc04-delete-fk", "mvc04-id-error", "mvc04-update-error", "owasp-error-handling"] },
  },
  {
    id: "mvc04-logging-correlation-redaction", title: "오류를 correlation·structured fields·redaction으로 관측합니다", lead: "사용자에게는 안전한 오류를, 운영자에게는 원인을 잃지 않는 bounded evidence를 제공합니다.",
    explanations: ["controller ingress에서 correlation id를 검증/생성하고 response와 모든 command/mapper log context에 전파합니다.", "event에는 route, method, outcome code, status, duration bucket, affected rows category, rollback result를 남깁니다.", "raw cmd/bookId가 무제한이면 log injection/PII/cardinality 문제가 있으므로 validate·normalize하거나 opaque/bounded field로 기록합니다.", "password, CSRF, cookie/session id, JDBC URL, SQL binds, book content, stack을 public log에 넣지 않습니다.", "internal exception stack은 access-controlled sink에 보존하되 retention·encryption·tamper protection과 least privilege를 적용합니다.", "alert는 unknown command spike, many-row mutation, rollback failure, commit unknown, repeated500/503에 ratio/burn-rate로 설정합니다.", "newline/control characters를 encode해 log forging을 막고 structured logger parameter APIs를 사용합니다.", "error response test와 log capture test는 같은 correlation, secret absence, category/status equality를 확인합니다."],
    concepts: [{ term: "structured logging", definition: "문자열 연결 대신 안정된 event name과 typed/bounded fields로 기록하는 방식입니다.", detail: ["query가 쉽습니다.", "redaction 정책을 적용합니다."] }, { term: "log injection", definition: "공격자가 newline/control syntax를 넣어 거짓 event나 field를 만든 것처럼 보이게 하는 위험입니다.", detail: ["structured encoder를 사용합니다.", "raw input을 제한합니다."] }, { term: "correlation", definition: "한 요청의 response·log·trace·downstream event를 동일 public-safe id로 연결하는 관측 규칙입니다.", detail: ["PII를 쓰지 않습니다.", "신뢰할 client id를 검증합니다."] }],
    diagnostics: diagnostics("error logging", "사용자는 correlation을 받았지만 log에서 원인을 찾을 수 없거나 secret이 함께 기록된다.", "generic catch가 cause를 버리거나 raw request/exception 전체를 로깅했습니다.", "stable category+correlation+allowlisted structured fields와 access-controlled internal cause sink를 분리합니다."),
    expertNotes: ["Correlation identifiers are references, not authorization secrets; they still need format and cardinality controls.", "Logging more data is not better observability when it expands breach impact and destroys signal-to-noise ratio."],
    trace: { className: "ErrorLoggingDecision", title: "오류 field를 public/internal/drop으로 분류합니다", purpose: "원인 보존과 data minimization을 동시에 검증합니다.", cases: [{ input: "CORRELATION_ID", decision: "PUBLIC", evidence: "trace-link" }, { input: "ERROR_CATEGORY", decision: "PUBLIC", evidence: "bounded" }, { input: "PASSWORD", decision: "DROP", evidence: "secret" }], defaultDecision: "INTERNAL_REVIEW", defaultEvidence: "unclassified-field", sourceRefs: ["mvc04-controller", "owasp-logging"] },
  },
  {
    id: "mvc04-response-commit-headers-cache", title: "status·Location·Content-Type·cache/security headers를 response commit 전에 확정합니다", lead: "forward/redirect/error가 이미 쓰인 body와 충돌하지 않게 한 controller가 response lifecycle을 소유합니다.",
    explanations: ["response buffer가 flush/overflow되면 status/header를 바꾸거나 sendRedirect/forward할 수 없습니다.", "controller에서 사용하지 않는 PrintWriter를 미리 얻는 것 자체가 즉시 commit은 아니지만 handler의 body write와 dispatch ownership을 혼란스럽게 합니다.", "redirect result는 status303와 validated Location을 설정하고 body는 최소화하며 no-store가 필요한 flash/error를 구분합니다.", "error/validation HTML은 UTF-8 Content-Type과 X-Content-Type-Options, CSP, frame/referrer 정책을 application 전체에서 일관되게 적용합니다.", "민감 form/error는 Cache-Control no-store, public list/detail은 authorization과 freshness에 맞는 cache policy를 사용합니다.", "response committed 뒤 예외는 새 error page를 forward하지 말고 connection/container log와 correlation으로 종료합니다.", "forward target은 응답을 한 번만 완성하고 controller와 JSP가 서로 writer/stream을 중복 소유하지 않습니다.", "container integration은 tiny buffer/early flush/exception after write를 강제해 fallback과 header timing을 검증합니다."],
    concepts: [{ term: "response commit", definition: "status와 headers가 client로 전송되어 더 이상 안전하게 변경할 수 없는 경계입니다.", detail: ["body write/flush로 발생합니다.", "dispatch 전에 확인합니다."] }, { term: "Location", definition: "redirect destination을 나타내는 response header로 URI reference와 application allowlist 정책을 따릅니다.", detail: ["context path를 고려합니다.", "open redirect를 막습니다."] }, { term: "Cache-Control", definition: "response를 누가 얼마 동안 저장/재사용할 수 있는지 지시하는 HTTP header입니다.", detail: ["no-store/private/public을 구분합니다.", "authorization과 연결합니다."] }],
    diagnostics: diagnostics("response lifecycle", "오류를 처리하려다 'response already committed'가 나고 status/header가 일부만 적용된다.", "handler/controller/JSP가 body writer를 나눠 소유하거나 write 뒤 forward/redirect했습니다.", "typed result가 body write 전 status/headers/dispatch를 한 곳에서 적용하게 합니다."),
    expertNotes: ["Security headers should be applied centrally but tested on error and redirect responses, not only successful pages.", "A committed response may be truncated; do not attempt a second HTML document after the commit boundary."],
    trace: { className: "ResponseCommitDecision", title: "response 상태별 dispatch 허용 여부를 판정합니다", purpose: "commit 뒤 redirect/forward 시도를 명시 실패로 만듭니다.", cases: [{ input: "NEW_FORWARD", decision: "ALLOW", evidence: "set-status-first" }, { input: "NEW_REDIRECT", decision: "ALLOW", evidence: "303+Location" }, { input: "COMMITTED_ERROR", decision: "LOG_CLOSE", evidence: "no-second-body" }], defaultDecision: "REJECT", defaultEvidence: "invalid-response-state", sourceRefs: ["mvc04-controller", "jakarta-servlet", "rfc9110"] },
  },
  {
    id: "mvc04-prg-error-test-operations", title: "PRG·flash·error를 HTTP transcript·multi-tab·a11y·failure tests로 완성합니다", lead: "JavaScript alert가 보인다는 수동 확인을 status/history/side-effect/accessible recovery의 재현 가능한 evidence로 바꿉니다.",
    explanations: ["route unit tests는 method/action full set, null/unknown, typed result와 no servlet field state를 검증합니다.", "transaction integration은 commit/rollback/unknown outcome이 redirect/error result보다 먼저 확정되는지 확인합니다.", "HTTP client test는 POST303 Location→GET200, refresh side-effect0, validation forward와 status/cache headers를 exact transcript로 저장합니다.", "multi-tab test는 flash nonce/target/atomic consume을 다른 순서로 요청해 cross-tab message leak가 없는지 확인합니다.", "browser test는 JS disabled, back/refresh, double click, slow network와 open redirect payload를 재현합니다.", "accessibility test는 error heading, summary links, focus, role=status/alert와 non-alert navigation fallback을 검증합니다.", "security test는 CSRF, reflected/stored XSS, CRLF Location/log injection과 internal error disclosure를 포함합니다.", "release evidence에는 source6 audit, exact unit outputs, HTTP transcripts, public-safe logs, SLO/alert, rollback/reconciliation runbook을 묶습니다."],
    concepts: [{ term: "HTTP transcript", definition: "request와 status·headers·body category·follow-up method를 순서대로 기록한 재현 가능한 protocol evidence입니다.", detail: ["PRG를 정확히 증명합니다.", "민감 header/body는 redact합니다."] }, { term: "side-effect assertion", definition: "navigation/retry/refresh 뒤 DB mutation count와 idempotency record가 늘지 않았음을 확인하는 검증입니다.", detail: ["화면만 보지 않습니다.", "PRG 한계를 보완합니다."] }, { term: "accessible recovery", definition: "오류를 assistive technology가 인지하고 사용자가 keyboard로 수정·목록·재시도를 선택할 수 있는 흐름입니다.", detail: ["alert 의존을 피합니다.", "focus와 links를 제공합니다."] }],
    diagnostics: diagnostics("PRG/error release", "happy-path POST만 통과하고 back/refresh/multi-tab에서 중복 또는 message leak가 난다.", "HTTP history와 flash concurrency를 포함한 end-to-end matrix가 없습니다.", "exact transcript+side-effect+multi-tab+browser/a11y tests를 release gate에 둡니다."),
    expertNotes: ["Tests should verify durable side effects in addition to browser navigation because PRG alone cannot guarantee idempotency.", "HTTP transcripts must redact Cookie, CSRF tokens, credentials and user content before becoming public artifacts."],
    trace: { className: "Mvc04EvidenceDecision", title: "PRG/error 변경별 필요한 검증 계층을 선택합니다", purpose: "route policy, transaction, HTTP/browser/flash evidence를 구분합니다.", cases: [{ input: "ROUTE_TABLE", decision: "JDK_UNIT", evidence: "exhaustive-actions" }, { input: "PRG_STATUS", decision: "HTTP_CLIENT", evidence: "303+GET" }, { input: "FLASH_MULTITAB", decision: "CONCURRENT_CONTAINER", evidence: "atomic-consume" }], defaultDecision: "FULL_MATRIX", defaultEvidence: "unclassified-flow", sourceRefs: ["jakarta-servlet", "rfc9110", "owasp-error-handling", "owasp-logging", "owasp-xss"] },
  },
];

const sources: SessionSource[] = [
  { id: "mvc04-delete-missing", repository: "nohssam/jspstudy", path: "jspstudy/src/main/webapp/day03/ex07_db_output.jsp", usedFor: ["missing delete", "alert/location"], evidence: "삭제 대상 없음 alert와 JS 목록 이동을 확인했습니다." },
  { id: "mvc04-delete-fk", repository: "nohssam/jspstudy", path: "jspstudy/src/main/webapp/day03/ex08_db_output.jsp", usedFor: ["foreign key error", "client navigation"], evidence: "FK 삭제 불가 alert/location을 확인했습니다." },
  { id: "mvc04-insert-error", repository: "nohssam/jspstudy", path: "jspstudy/src/main/webapp/day03/ex10_error.jsp", usedFor: ["insert error", "generic recovery"], evidence: "삽입 오류 alert/location을 확인했습니다." },
  { id: "mvc04-id-error", repository: "nohssam/jspstudy", path: "jspstudy/src/main/webapp/day03/ex12_error.jsp", usedFor: ["not found", "error status gap"], evidence: "없는 id alert/location을 확인했습니다." },
  { id: "mvc04-update-error", repository: "nohssam/jspstudy", path: "jspstudy/src/main/webapp/day03/ex13_error.jsp", usedFor: ["update error", "validation redisplay"], evidence: "수정 오류 alert/location을 확인했습니다." },
  { id: "mvc04-controller", repository: "nohssam/jspstudy", path: "jspstudy/src/main/java/org/study/jspstudy/day03/Ex12.java", usedFor: ["route switch", "forward", "method dispatch"], evidence: "cases8, default/null guard0와 unconditional forward를 확인했습니다." },
  { id: "jakarta-servlet", repository: "Jakarta EE", path: "Servlet 6.1 specification", publicUrl: "https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1", usedFor: ["forward/redirect", "response commit", "session/flash"], evidence: "공식 Jakarta Servlet specification입니다." },
  { id: "rfc9110", repository: "IETF", path: "RFC 9110 HTTP Semantics", publicUrl: "https://www.rfc-editor.org/rfc/rfc9110", usedFor: ["303", "status", "Location", "methods"], evidence: "HTTP semantics의 IETF 표준입니다." },
  { id: "mybatis-java-api", repository: "MyBatis", path: "Java API", publicUrl: "https://mybatis.org/mybatis-3/java-api.html", usedFor: ["commit/rollback outcome before redirect"], evidence: "공식 MyBatis Java API reference입니다." },
  { id: "owasp-unvalidated-redirect", repository: "OWASP", path: "Unvalidated Redirects and Forwards Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html", usedFor: ["Location allowlist", "open redirect"], evidence: "OWASP redirect/forward 방어 지침입니다." },
  { id: "owasp-session", repository: "OWASP", path: "Session Management Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html", usedFor: ["flash session", "cookie policy"], evidence: "OWASP session lifecycle 지침입니다." },
  { id: "owasp-input-validation", repository: "OWASP", path: "Input Validation Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html", usedFor: ["field errors", "safe redisplay"], evidence: "OWASP input validation 지침입니다." },
  { id: "owasp-xss", repository: "OWASP", path: "Cross Site Scripting Prevention Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html", usedFor: ["redisplay encoding", "error view"], evidence: "OWASP context-sensitive output 지침입니다." },
  { id: "owasp-error-handling", repository: "OWASP", path: "Error Handling Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html", usedFor: ["error taxonomy", "public/internal split"], evidence: "OWASP error handling 지침입니다." },
  { id: "owasp-logging", repository: "OWASP", path: "Logging Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html", usedFor: ["structured logging", "redaction", "correlation"], evidence: "OWASP logging 지침입니다." },
  { id: "owasp-transaction-authorization", repository: "OWASP", path: "Transaction Authorization Cheat Sheet", publicUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Transaction_Authorization_Cheat_Sheet.html", usedFor: ["mutation replay", "transaction result"], evidence: "OWASP transaction authorization 지침입니다." },
];

const session = buildMvcSession({
  inventoryId: "mvc-04-prg-errors", order: 4, title: "PRG와 오류 처리", subtitle: "alert·forward 흐름을 method-aware routing, typed result, 303 PRG·flash·status·redacted logging·HTTP/browser evidence로 발전시킵니다.", level: "고급", estimatedMinutes: 900,
  coreQuestion: "쓰기 결과를 중복 제출 없이 안전하게 이동시키면서 validation·conflict·dependency 오류의 status와 복구 정보, 운영 원인을 어떻게 잃지 않을까요?",
  summary: "원본6은 error/result JSP alerts5·JavaScript locations5, controller route cases8, default routes0, command null guards0, unconditional forward1, server redirects0, status writes0, logger calls0입니다. 실제 Servlet/browser/DB는 실행하지 않았습니다. method-aware route table과 typed ActionResult, commit-aware303 PRG, one-time/multi-tab flash, safe validation redisplay, error taxonomy/status/view, correlation/redaction, response commit/cache/security headers와 HTTP/browser/a11y/failure test를 10장으로 완성합니다.",
  objectives: ["원본 client navigation과 HTTP redirect를 구분한다.", "method+action route table과 typed ActionResult를 구현한다.", "commit 뒤303 POST-Redirect-GET을 적용한다.", "flash를 one-time·target-bound·multi-tab safe하게 만든다.", "validation 오류 입력을 secret 없이 안전하게 redisplay한다.", "오류 category를 status와 accessible view로 매핑한다.", "correlation·structured logging·redaction을 적용한다.", "response commit 전에 status/headers/dispatch를 확정한다.", "HTTP transcript·side-effect·browser/a11y tests로 증명한다."],
  prerequisites: [{ title: "책 쓰기와 트랜잭션", reason: "redirect 성공 여부는 commit/rollback/unknown transaction outcome 뒤에 결정되어야 합니다.", sessionSlug: "mvc-03-book-write-transaction" }, { title: "Servlet 요청 수명주기", reason: "forward/redirect/status/response commit과 request/session scope를 사용합니다.", sessionSlug: "servlet-01-mapping-lifecycle-response" }],
  keywords: ["PRG", "303 See Other", "forward", "redirect", "Location", "flash scope", "ActionResult", "error taxonomy", "HTTP status", "response commit", "correlation id", "structured logging", "redaction", "accessibility"], topics,
  lab: { title: "Book mutation의 PRG·flash·error gateway", scenario: "원본 Ex12/오류 JSP를 typed dispatch와 exact HTTP semantics로 바꾸고 multi-tab/refresh/failure에서도 중복과 정보 유실을 막습니다.", setup: ["route/action full set과 success/validation/not-found/FK/conflict/timeout/commit-unknown fixtures를 만듭니다.", "ephemeral DB/container와 HTTP client를 준비하되 운영 credential/data는 사용하지 않습니다.", "public error/flash/log field allowlist를 정의합니다."], steps: ["method+action immutable route table과 unknown/default 처리를 구현합니다.", "Forward/Redirect/Error typed result를 controller가 한 번만 적용하게 합니다.", "transaction commit 성공 후303+server-owned Location을 보냅니다.", "validation은 field-error view model로 같은 request forward합니다.", "nonce/target/TTL/atomic consume flash store를 구현합니다.", "error taxonomy가 exact status와 accessible JSP를 선택하게 합니다.", "correlation/structured log와 secret/PII redaction을 적용합니다.", "cache/security headers와 response-commit failure fallback을 검증합니다.", "HTTP transcript, refresh side-effect0, multi-tab/browser/a11y/security tests를 실행합니다.", "SLO/alert/rollback/reconciliation runbook을 배포 evidence에 포함합니다."], expectedResult: ["성공 POST는303 뒤 GET으로 끝나고 refresh side-effect가0입니다.", "validation 값은 안전하게 유지되며 password/token/file은 재노출되지 않습니다.", "missing/FK/conflict/timeout이 서로 다른 status/action으로 표현됩니다.", "flash는 해당 tab/operation에서 한 번만 보입니다.", "response/log에 stack·SQL·credential·PII가 없습니다."], cleanup: ["ephemeral DB/container/session/flash namespace만 제거합니다.", "in-flight request와 unconsumed test flash가0인지 확인합니다.", "HTTP/log artifacts에서 Cookie/CSRF/user content를 redact합니다."], extensions: ["REST JSON error format과 HTML error view가 같은 taxonomy를 공유하게 합니다.", "distributed Redis flash의 atomic consume/failover를 검증합니다.", "CSP nonce와 external script migration으로 inline alert/location을 제거합니다.", "idempotency dashboard와 commit-unknown reconciliation을 연결합니다."] },
  exercises: [
    { difficulty: "따라하기", prompt: "mutation 결과를 Forward/Redirect/Error type으로 바꾸세요.", requirements: ["validation은 forward입니다.", "commit success는303입니다.", "unknown route는404/400입니다.", "wrong method는405+Allow입니다.", "commit 뒤만 redirect합니다."], hints: ["String path는 dispatch kind를 표현하지 못합니다."], expectedOutcome: "controller가 모든 path를 무조건 forward하지 않습니다.", solutionOutline: ["sealed result와 중앙 applicator를 만듭니다."] },
    { difficulty: "응용", prompt: "multi-tab-safe flash store를 구현하세요.", requirements: ["operation nonce를 사용합니다.", "user/session/target을 묶습니다.", "TTL을 둡니다.", "atomic consume합니다.", "wrong-tab/replay/expiry concurrent tests를 둡니다."], hints: ["session의 단일 flash slot은 race가 납니다."], expectedOutcome: "두 탭의 메시지가 섞이거나 반복되지 않습니다.", solutionOutline: ["nonce-keyed compare-and-delete contract를 구현합니다."] },
    { difficulty: "설계", prompt: "PRG/error production verification plan을 작성하세요.", requirements: ["transaction outcome과 redirect ordering을 포함합니다.", "status/Location/cache/security headers를 명시합니다.", "public/internal error/log redaction을 포함합니다.", "refresh/back/multi-tab/JS-disabled/a11y matrix를 둡니다.", "idempotency와 commit unknown을 다룹니다.", "SLO/alert/rollback owners를 정합니다."], hints: ["화면 alert만으로 HTTP semantics를 증명할 수 없습니다."], expectedOutcome: "기능·프로토콜·보안·접근성·운영 evidence가 연결됩니다.", solutionOutline: ["route→transaction→result→HTTP→browser→operations 순으로 작성합니다."] },
  ],
  nextSessions: ["mvc-05-guestbook-front-controller"], sources,
  sourceCoverage: { filesRead: 6, filesUsed: 6, uncoveredNotes: ["inventory의 error/result JSP5와 Ex12 controller를 모두 읽고 사용했습니다.", "alert/location은 source shape만 확인했으며 browser navigation이나 linked DB controller를 실행하지 않았습니다.", "Book mutation command의 commit/rollback closure는 mvc-03에서 다뤘고 이 세션은 dispatch/PRG/error 경계에 집중합니다."] },
});

export default session;
