import type { DetailedSession, DetailedChapter } from "../../types";

const isolatedJavaRun = (sourceFile: string, mainClass: string) =>
  "pwsh -NoProfile -Command '& { $base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar); $root=Join-Path $base ([Guid]::NewGuid().ToString(\"N\")); New-Item -ItemType Directory -Path $root -ErrorAction Stop|Out-Null; try{$classes=Join-Path $root \"classes\";New-Item -ItemType Directory $classes|Out-Null;$c=@(& javac -encoding UTF-8 --release 21 -proc:none -Xlint:all -d $classes \"" + sourceFile + "\" 2>&1);if($LASTEXITCODE-ne0-or$c.Count-ne0){throw(\"javac failed or warned: \"+($c-join[Environment]::NewLine))};Push-Location $root;try{& java \"-Dfile.encoding=UTF-8\" -cp $classes \"" + mainClass + "\";if($LASTEXITCODE-ne0){throw \"java failed\"}}finally{Pop-Location}}finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}}'";

type Seed={id:string;title:string;lead:string;explanations:string[];terms:Array<[string,string,string[]]>;filename:string;code:string;output:string;refs:string[];diagnostics:Array<[string,string,string[],string,string]>;notes?:string[]};
const walkthroughFor=(code:string)=>{const last=code.split(/\r?\n/).length;const first=Math.ceil(last/3);const second=Math.ceil(last*2/3);return [{lines:`1-${first}`,explanation:"route key, typed request context, command result와 정책 type을 선언합니다."},{lines:`${first+1}-${second}`,explanation:"lookup→method/security→bind/validate→execute→result validation 순서로 pipeline을 구성합니다."},{lines:`${second+1}-${last}`,explanation:"정상·unknown·null·forbidden·failure·duplicate 사례를 실행해 exact output을 검증합니다."}];};
const makeChapter=(s:Seed):DetailedChapter=>({
 id:s.id,title:s.title,lead:s.lead,explanations:s.explanations,concepts:s.terms.map(([term,definition,detail])=>({term,definition,detail})),
 codeExamples:[{id:`java-${s.id}`,title:s.title,language:"java",filename:s.filename,purpose:`${s.title}의 dispatch/security/response 불변식을 container 없이 exact하게 검증합니다.`,code:s.code,
 walkthrough:walkthroughFor(s.code),
 run:{environment:["OpenJDK 21","PowerShell 7+","container/network 불필요"],command:isolatedJavaRun(s.filename,s.filename.replace(/\.java$/, ""))},
 output:{value:s.output,explanation:["fixed registry와 inputs로 exact합니다.","원본 Servlet commands와 실제 DB/container 호출은 실행하지 않은 maintained policy fixture입니다."]},
 experiments:[{change:"cmd를 null/unknown/duplicate로 바꿉니다.",prediction:"NPE나 임의 default action이 아니라 typed404/400/startup failure가 됩니다.",result:"dispatch table을 fail-closed하게 유지합니다."},{change:"view path 또는 method/CSRF를 변조합니다.",prediction:"execute/forward 전에 policy가 거부합니다.",result:"command 반환 문자열을 navigation 권한으로 신뢰하지 않습니다."},{change:"두 requests를 같은 controller에서 겹칩니다.",prediction:"local immutable context는 격리되고 shared mutable field는 race가 납니다.",result:"Servlet lifecycle concurrency를 front controller에 적용합니다."}],sourceRefs:s.refs}],
 diagnostics:s.diagnostics.map(([symptom,likelyCause,checks,fix,prevention])=>({symptom,likelyCause,checks,fix,prevention})),expertNotes:s.notes,
});

const session:DetailedSession={
 schemaVersion:2,inventoryIds:["servlet-05-command-dispatch"],slug:"servlet-05-command-dispatch",courseId:"servlet-jsp",moduleId:"servlet-http-lifecycle",order:5,
 title:"Command 패턴·Front Controller·안전한 dispatch",subtitle:"switch 분리를 넘어 typed command, immutable registry, view allowlist, lifecycle concurrency, method/CSRF/authz, 오류 taxonomy와 Spring MVC mental model까지 완성합니다.",level:"중급",estimatedMinutes:960,
 coreQuestion:"하나의 Front Controller가 사용자 route input을 어떤 registry와 pipeline으로 command에 연결해야 null/default confusion, 임의 view, credential log, double response, race와 authorization 우회를 막을까요?",
 summary:"원본 inventory6(Ex10/11/12, Command, OneCommand, ListCommand), simple command closure5와 DB-dependent Book command closure7을 직접 읽고 hash합니다. 실제 DB closure는 실행하지 않고 inventory+simple originals를 compile하며 Book command 이름에는 owned temp maintained stubs7을 써 의존성 경계를 투명하게 분리합니다. compile warning3은 controller missing SVUID입니다. Ex10은 null switch NPE·default 부재·branch forward 뒤 HTML write, SecondCommand는 uid/upw credential stdout log 위험이 있습니다. Ex11은 unknown cmd를 TwoCommand로 실행하고 null은 NPE, Ex12는 default가 없어 null/unknown 모두 command.exec NPE입니다. Command interface는 Servlet API에 결합되고 arbitrary view String을 반환합니다. 현대 fixtures는 fail-closed routing, pure command, immutable registry, decoupled context/result, view allowlist, pipeline, request isolation, method/CSRF/authz, error taxonomy, startup validation과 framework dispatch를 warning0 exact output으로 검증합니다.",
 objectives:["null/unknown route를 명시적400/404로 처리하고 surprising default action을 제거한다.","Command를 transport adapter에서 분리한 typed use-case interface로 설계한다.","immutable route registry와 startup duplicate/completeness validation을 구현한다.","Servlet request/response 대신 최소 typed RequestContext와 sealed Result를 사용한다.","view id allowlist로 WEB-INF path를 resolve하고 path traversal/open forward를 막는다.","front controller pipeline 순서와 single terminal response를 보장한다.","Servlet instance field 대신 request-local command/context를 사용해 concurrent isolation을 보장한다.","route별 method·CSRF·authentication·authorization과 safe logging/error taxonomy를 적용한다."],
 prerequisites:[{title:"attributes·scopes·session",reason:"command 결과와 principal/view model의 올바른 lifetime이 필요합니다.",sessionSlug:"servlet-04-attributes-scopes-session"},{title:"forward·redirect·PRG",reason:"command result가 만드는 terminal navigation과 commit 계약을 알아야 합니다.",sessionSlug:"servlet-03-forward-redirect-prg"},{title:"Java interface·collection",reason:"Command abstraction과 registry Map을 이해해야 합니다.",sessionSlug:"java-18-interface-polymorphism"}],
 keywords:["Command pattern","Front Controller","dispatch registry","fail closed","sealed result","view allowlist","WEB-INF","single response","CSRF","authorization","credential logging","exception taxonomy","DispatcherServlet"],
 chapters:[],
 lab:{title:"학습자료 CRUD Front Controller",scenario:"list/detail/create/update/delete commands를 한 controller에 등록하고 공개/인증/mutation 정책과 forward/redirect 결과를 안전하게 처리합니다.",setup:["null/unknown/duplicate route, wrong method, missing CSRF, wrong owner, malicious view, command exception과 concurrent requests를 준비합니다.","in-memory repository와 deterministic clock/id를 사용해 DB/network 없이 pipeline을 검증합니다."],steps:["route key를 method+canonical path로 정의합니다.","startup registry에서 duplicate와 required routes를 검증합니다.","request를 bounded typed context와 minimal principal로 bind합니다.","route metadata로 method/CSRF/authn/authz를 execute 전에 검사합니다.","pure command가 domain Result를 반환합니다.","adapter가 view id allowlist 또는303 resource URL로 resolve합니다.","single terminal action 뒤 즉시 종료합니다.","structured redacted log와 error taxonomy를 기록합니다.","parallel requests와 startup failure를 test합니다."],expectedResult:["null/unknown은 command를 실행하지 않고400/404입니다.","GET mutation과 missing/invalid CSRF, wrong owner가 command 전에 거부됩니다.","임의 path/WEB-INF 탈출과 double render가 불가능합니다.","동시 requests의 context/result가 섞이지 않고 errors에 secret/stack이 없습니다."],cleanup:["registry/repository를 비우고 threads를 join합니다.","owned temp/stubs만 삭제합니다."],extensions:["real Servlet filters/listeners와 integration test합니다.","Spring MVC HandlerMapping/Adapter/ExceptionResolver로 같은 contract를 매핑합니다.","transaction/outbox/idempotency를 mutation commands에 추가합니다."]},
 exercises:[
  {difficulty:"따라하기",prompt:"switch cmd를 immutable Map registry로 바꾸세요.",requirements:["null/blank/unknown을 구분합니다.","unknown을 unrelated default command로 보내지 않습니다.","duplicate key startup failure를 둡니다.","registry를 request 중 mutate하지 않습니다."],hints:["Map.get null을 곧바로 command.exec하지 마세요."],expectedOutcome:"known route만 실행되고 모든 실패 status가 exact합니다.",solutionOutline:["startup builder의 putIfAbsent 뒤 Map.copyOf를 사용합니다."]},
  {difficulty:"응용",prompt:"Command를 Servlet API에서 분리하고 sealed Result를 만드세요.",requirements:["typed Input/Principal을 사용합니다.","Command는 response를 write/forward하지 않습니다.","Forward/Redirect/Body 결과를 구분합니다.","view id allowlist를 둡니다.","unit test에 Servlet mock이 필요 없게 합니다."],hints:["transport adapter가 bind와 render를 소유합니다."],expectedOutcome:"domain command unit test와 adapter contract test가 분리됩니다.",solutionOutline:["RequestContext→Input mapper, UseCase<Input,Result>, Result renderer 세 층으로 나눕니다."]},
  {difficulty:"설계",prompt:"production front controller security/observability ADR을 작성하세요.",requirements:["route별 method/CSRF/authn/authz metadata를 둡니다.","exception/status taxonomy를 정합니다.","credential/PII redaction을 포함합니다.","concurrent request state ownership을 문서화합니다.","Spring MVC migration mapping과 acceptance tests를 포함합니다."],hints:["모든 commands가 같은 보안 요구를 갖는다는 가정을 피하세요."],expectedOutcome:"구현 가능한 registry schema와 pipeline test matrix가 완성됩니다.",solutionOutline:["route resolution과 policy enforcement를 command execution보다 앞에 둡니다."]},
 ],
 reviewQuestions:[],completionChecklist:[],nextSessions:["jsp-01-page-directives-el-jstl"],sources:[],
 sourceCoverage:{filesRead:18,filesUsed:18,uncoveredNotes:["inventory6, 실제 simple command closure5와 DB-dependent Book command closure7을 직접 읽고 hash합니다.","DB Book commands의 downstream DBUtil/BookMapper/BookVO·database는 이 세션에서 실행하지 않습니다. compile에는 이름/Command 계약만 갖는 owned maintained stubs7을 사용한다고 output에 명시합니다.","First/SecondCommand의 parameter stdout, 특히 uid/upw credential logging 위험과 controller들의 null/default/double-response 문제를 현대 chapters에서 교정합니다."]},
};

const audit:DetailedChapter={
 id:"original-servlet05-inventory6-closure12-audit",title:"원본 inventory6·closure12의 dispatch·compile·보안 shape를 감사합니다",lead:"실제 DB commands는 hash/provenance로 보존하고 compile-only stubs를 original behavior와 명확히 분리합니다.",
 explanations:["Ex10은 cmd switch case1/2에서 First/SecondCommand를 new하고 path로 forward합니다. switch 뒤 공통 HTML write가 계속되어 forward target이 response를 처리한 뒤 double response/committed 오류가 생길 수 있습니다.","FirstCommand는 uname/uage를 stdout에 출력하고 SecondCommand는 uid/upw를 그대로 출력합니다. password/credential은 console log에도 남기지 않아야 합니다.","Ex11은 command local을 사용해 concurrency 면에서 나아졌지만 null cmd는 switch NPE이고 unknown은 default TwoCommand(운세)를 실행해 fail-open/surprising behavior가 됩니다.","Ex12는8 book/list cases에 default가 없어 null/unknown에서 command가 null인 채 exec되어 NPE입니다. command key는 user input이므로 explicit not-found가 필요합니다.","Command.exec는 HttpServletRequest/Response에 결합되고 String path를 반환합니다. OneCommand가 request attrs2를 만들고 ListCommand가 path만 반환하지만 arbitrary path validation이 없습니다.","actual Book commands7은 mapper/DBUtil/VO에 의존하므로 원본 파일을 hash/read하되 DB/network를 실행하지 않습니다. compile evidence는 owned stubs7을 명시해 inventory/simple originals의 syntax·warning/shape만 검증합니다.","audit은 inventory shape mapping3, forward4, switch3/cases14/default1, exec tokens7, implements2와 controller warning3을 검증합니다."],
 concepts:[{term:"fail-closed dispatch",definition:"null/unknown route가 어떤 business command도 실행하지 않고 명시적 오류가 되는 정책입니다.",detail:["default unrelated action을 피합니다.","command lookup 뒤 null을 검사합니다."]},{term:"compile-only stub",definition:"downstream dependency 없이 선택 source의 type resolution만 검증하는 maintained 최소 구현입니다.",detail:["original source가 아닙니다.","behavior evidence로 사용하지 않습니다."]},{term:"response terminal action",definition:"한 controller invocation이 정확히 한 번 수행하는 forward, redirect, error 또는 body render입니다.",detail:["뒤 write를 금지합니다.","sealed result로 표현합니다."]}],
 codeExamples:[{id:"powershell-original-servlet05-audit",title:"inventory6+closure12 hash와 stub-bounded compile/shape를 검증합니다",language:"powershell",filename:"verify-original-servlet05.ps1",purpose:"DB/container/network 없이 원본 provenance와 controller/command risks를 재현합니다.",
  code:String.raw`param([Parameter(Mandatory)][string]$SourceRoot,[Parameter(Mandatory)][string]$ServletApiJar)
$ErrorActionPreference='Stop';$names=@('JDK_JAVAC_OPTIONS','JDK_JAVA_OPTIONS','JAVA_TOOL_OPTIONS','_JAVA_OPTIONS');$saved=@{}
foreach($n in $names){$i=Get-Item ("Env:"+$n)-ErrorAction SilentlyContinue;$saved[$n]=@{Exists=$null-ne$i;Value=if($i){$i.Value}else{$null}};Remove-Item ("Env:"+$n)-ErrorAction SilentlyContinue}
$base=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);$root=Join-Path $base ("servlet05 audit "+[Guid]::NewGuid().ToString('N'));$owned=$false;$failure=$null
function Strip([string]$s){return [regex]::Replace(([regex]::Replace($s,'(?s)/\*.*?\*/','')),'(?m)//.*$','')}
try{if(-not(Test-Path -LiteralPath $ServletApiJar -PathType Leaf)){throw 'servlet api missing'};New-Item -ItemType Directory $root|Out-Null;$owned=$true
 $inventory=@('src/main/java/org/study/jspstudy/day01/Ex10.java','src/main/java/org/study/jspstudy/day02/Ex11.java','src/main/java/org/study/jspstudy/day03/Ex12.java','src/main/java/org/study/jspstudy/model/Command.java','src/main/java/org/study/jspstudy/model/OneCommand.java','src/main/java/org/study/jspstudy/model/ListCommand.java')
 $simple=@('src/main/java/org/study/jspstudy/model/FirstCommand.java','src/main/java/org/study/jspstudy/model/SecondCommand.java','src/main/java/org/study/jspstudy/model/TwoCommand.java','src/main/java/org/study/jspstudy/model/ThreeCommand.java','src/main/java/org/study/jspstudy/model/FourCommand.java')
 $bookNames=@('BookListCommand','BookIdCommand','BookDeleteCommand','BookInsertFormCommand','BookInsertCommand','BookUpdateFormCommand','BookUpdateCommand');$book=@($bookNames|ForEach-Object{"src/main/java/org/study/jspstudy/model/$_.java"});$all=$inventory+$simple+$book;$copy=@{}
 foreach($rel in $all){$src=Get-Item -LiteralPath (Join-Path $SourceRoot $rel);$dst=Join-Path $root ("original/"+$rel);New-Item -ItemType Directory ([IO.Path]::GetDirectoryName($dst))-Force|Out-Null;[IO.File]::Copy($src.FullName,$dst);if((Get-FileHash $src.FullName -Algorithm SHA256).Hash-cne(Get-FileHash $dst -Algorithm SHA256).Hash){throw 'hash drift'};$copy[$rel]=$dst}
 $stubDir=Join-Path $root 'stubs/org/study/jspstudy/model';New-Item -ItemType Directory $stubDir -Force|Out-Null
 foreach($name in $bookNames){$text="package org.study.jspstudy.model; import jakarta.servlet.http.HttpServletRequest; import jakarta.servlet.http.HttpServletResponse; public final class $name implements Command { public String exec(HttpServletRequest req,HttpServletResponse resp){ return null; } }";[IO.File]::WriteAllText((Join-Path $stubDir ($name+'.java')),$text,[Text.UTF8Encoding]::new($false))}
 $compile=@($inventory+$simple|ForEach-Object{$copy[$_]})+@(Get-ChildItem -LiteralPath $stubDir -Filter '*.java'|ForEach-Object{$_.FullName});$classes=Join-Path $root 'classes';New-Item -ItemType Directory $classes|Out-Null;$common=@('-J-Duser.language=en','-J-Duser.country=US','-encoding','UTF-8','--release','21','-proc:none','-Xlint:all','-XDrawDiagnostics')
 $c=@(& javac @common -cp $ServletApiJar -d $classes @compile 2>&1);if($LASTEXITCODE-ne0-or@($c|Where-Object{$_-match'compiler\.warn\.missing\.SVUID'}).Count-ne3-or$c[-1]-notmatch'3 warnings'){throw ('compile drift '+($c-join'|'))}
 $joined=(@($inventory|ForEach-Object{Strip([IO.File]::ReadAllText($copy[$_]))}))-join[Environment]::NewLine
 $shape=@{mapping=([regex]::Matches($joined,'@WebServlet\s*\(')).Count;servlet=([regex]::Matches($joined,'extends\s+HttpServlet\b')).Count;init=([regex]::Matches($joined,'\bvoid\s+init\s*\(')).Count;doGet=([regex]::Matches($joined,'\bvoid\s+doGet\s*\(')).Count;doPost=([regex]::Matches($joined,'\bvoid\s+doPost\s*\(')).Count;writer=([regex]::Matches($joined,'\.getWriter\s*\(')).Count;encoding=([regex]::Matches($joined,'\.setCharacterEncoding\s*\(')).Count;parameter=([regex]::Matches($joined,'\.getParameter\s*\(')).Count;setAttribute=([regex]::Matches($joined,'\.setAttribute\s*\(')).Count;forward=([regex]::Matches($joined,'\.forward\s*\(')).Count;dispatcher=([regex]::Matches($joined,'\.getRequestDispatcher\s*\(')).Count;switch=([regex]::Matches($joined,'\bswitch\s*\(')).Count;cases=([regex]::Matches($joined,'\bcase\s+')).Count;defaults=([regex]::Matches($joined,'\bdefault\s*:')).Count;implements=([regex]::Matches($joined,'implements\s+Command\b')).Count;exec=([regex]::Matches($joined,'\bexec\s*\(')).Count;fields=([regex]::Matches($joined,'\bprivate\s+String\s+\w+\s*;')).Count}
 if($shape.mapping-ne3-or$shape.servlet-ne3-or$shape.init-ne1-or$shape.doGet-ne3-or$shape.doPost-ne3-or$shape.writer-ne3-or$shape.encoding-ne6-or$shape.parameter-ne5-or$shape.setAttribute-ne2-or$shape.forward-ne4-or$shape.dispatcher-ne4-or$shape.switch-ne3-or$shape.cases-ne14-or$shape.defaults-ne1-or$shape.implements-ne2-or$shape.exec-ne7-or$shape.fields-ne1){throw ('shape drift '+($shape|ConvertTo-Json -Compress))}
 $simpleText=(@($simple|ForEach-Object{Strip([IO.File]::ReadAllText($copy[$_]))}))-join[Environment]::NewLine;$credentialLogs=([regex]::Matches($simpleText,'System\.out\.println\s*\(req\.getParameter\s*\("(?:uid|upw)"\)')).Count;if($credentialLogs-ne2){throw 'credential-log shape drift'}
 'files=inventory6+simpleClosure5+dbCommandClosure7,hashes=18|compile=original11+maintainedStubs7,warnings3,missingSVUID3'
 'shape=mapping3,servlet3,init1,doGet3,doPost3,writer3,encoding6,parameter5,setAttribute2,forward4,dispatcher4,switch3,cases14,defaults1,implementsCommand2,execTokens7,fields1,credentialLogs2'
 'privacy=container:not-run|database:not-run|network:none|original:read-only|stubs:owned-compile-only|fixture:owned-temp'
}catch{$failure=$_.Exception}finally{foreach($n in $names){if($saved[$n].Exists){Set-Item ("Env:"+$n) $saved[$n].Value}else{Remove-Item ("Env:"+$n)-ErrorAction SilentlyContinue}};if($owned){$resolved=[IO.Path]::GetFullPath($root);if([IO.Path]::GetDirectoryName($resolved)-cne$base){throw 'unsafe cleanup'};Remove-Item -LiteralPath $resolved -Recurse -Force};if($failure){[Runtime.ExceptionServices.ExceptionDispatchInfo]::Capture($failure).Throw()}}`,
  walkthrough:[{lines:"1-8",explanation:"launcher state와 owned temp, comment stripping을 준비합니다."},{lines:"9-13",explanation:"inventory6, simple closure5, actual DB command closure7을 복사·hash합니다."},{lines:"14-16",explanation:"actual DB commands를 수정하지 않고 별도 owned compile-only stubs7을 만듭니다."},{lines:"17-20",explanation:"original inventory+simple commands를 stubs와 compile해 controller warning3을 확인합니다."},{lines:"21-25",explanation:"inventory dispatch shape와 simple closure의 uid/upw stdout calls2를 검증합니다."},{lines:"26-end",explanation:"container/DB/network 미실행, stub 경계, environment 복원과 direct-child cleanup을 출력합니다."}],
  run:{environment:["PowerShell 7+","OpenJDK 21","Jakarta Servlet API 6.1 jar","jspstudy root"],command:"pwsh -NoProfile -File verify-original-servlet05.ps1 -SourceRoot <jspstudy-root> -ServletApiJar <servlet-api.jar>"},
  output:{value:"files=inventory6+simpleClosure5+dbCommandClosure7,hashes=18|compile=original11+maintainedStubs7,warnings3,missingSVUID3\nshape=mapping3,servlet3,init1,doGet3,doPost3,writer3,encoding6,parameter5,setAttribute2,forward4,dispatcher4,switch3,cases14,defaults1,implementsCommand2,execTokens7,fields1,credentialLogs2\nprivacy=container:not-run|database:not-run|network:none|original:read-only|stubs:owned-compile-only|fixture:owned-temp",explanation:["원본18 hashes와 compile subset/stub 경계를 구분합니다.","credential stdout calls를 보안 evidence로 기록합니다.","DB/container behavior를 주장하지 않습니다."]},
  experiments:[{change:"Ex11 cmd를 null/unknown으로 보냅니다.",prediction:"null은 switch NPE, unknown은 TwoCommand를 실행합니다.",result:"fail-closed registry로 교정합니다."},{change:"Ex12 cmd를 unknown으로 보냅니다.",prediction:"command null 뒤 exec NPE가 납니다.",result:"lookup failure를404로 반환합니다."},{change:"Ex10 case forward 뒤 control flow를 계속합니다.",prediction:"공통 HTML write가 target response와 충돌합니다.",result:"terminal result 뒤 즉시 return합니다."}],sourceRefs:["source-ex10","source-ex11","source-ex12","source-command","source-one-command","source-list-command","source-simple-closure","source-book-closure","jdk-javac","jakarta-dispatcher","owasp-logging"]}],
 diagnostics:[{symptom:"cmd가 null일 때500 NPE가 난다.",likelyCause:"Java switch와 command.exec 전에 null route를 검사하지 않았습니다.",checks:["raw cmd presence를 봅니다.","switch/registry lookup 뒤 null path를 봅니다."],fix:"missing은400, unknown은404로 command 실행 전에 종료합니다.",prevention:"null/blank/unknown dispatch tests를 둡니다."},{symptom:"로그에 uid/upw가 평문으로 남는다.",likelyCause:"SecondCommand가 request credentials를 System.out.println합니다.",checks:["stdout/application logs를 secret pattern으로 검색합니다.","parameter logging middleware를 봅니다."],fix:"credential 값을 절대 log하지 않고 event/user opaque id만 structured log합니다.",prevention:"log redaction test와 secret scanner를 CI에 둡니다."}],
};
session.chapters.push(audit);

const seeds:Seed[]=[
 {id:"null-unknown-fail-closed-routing",title:"null·blank·unknown command를 business 실행 전에 거부합니다",lead:"사용자 cmd를 Java switch에 바로 넣지 않고 parse 결과를 Missing, Known, Unknown으로 분류해 명시적 status를 반환합니다.",
  explanations:["Java String switch는 selector null에 NPE를 내므로 case/default까지 도달하지 않습니다. required parameter presence를 먼저 검사합니다.","unknown cmd를 Ex11처럼 TwoCommand로 보내면 typo/attack이 unrelated action을 실행해 audit와 authorization을 흐립니다.","missing/blank malformed는400, canonical route가 없으면404를 선택하고 어떤 command도 실행하지 않습니다.","case normalization을 임의로 적용하면 command namespace 충돌이 생길 수 있어 route grammar와 exact casing을 정합니다.","route key를 user-visible action label과 분리하고 raw cmd 전체를 metric label/log에 쓰지 않습니다."],
  terms:[["fail closed","입력이 불명확하거나 정책 확인이 실패하면 action을 실행하지 않는 원칙입니다.",["unknown default action을 금지합니다.","명시적 status를 냅니다."]],["route grammar","허용 command key의 길이·문자·case 형식입니다.",["budget을 먼저 적용합니다.","canonical key를 registry에 씁니다."]]],filename:"FailClosedRouting.java",
  code:String.raw`import java.util.Map;
public class FailClosedRouting {
    interface Command{String run();}
    record Response(int status,String body){}
    static Response dispatch(String raw,Map<String,Command> routes){if(raw==null||raw.isBlank())return new Response(400,"missing-command");if(raw.length()>20)return new Response(400,"invalid-command");Command c=routes.get(raw);if(c==null)return new Response(404,"unknown-command");return new Response(200,c.run());}
    public static void main(String[] args){Map<String,Command> routes=Map.of("list",()->"books");System.out.println(dispatch(null,routes));System.out.println(dispatch("missing",routes));System.out.println(dispatch("list",routes));}
}`,
  output:"Response[status=400, body=missing-command]\nResponse[status=404, body=unknown-command]\nResponse[status=200, body=books]",refs:["java-map","rfc9110-status","owasp-input"],
  diagnostics:[["null cmd가 switch NPE를 낸다.","selector presence 검사가 없습니다.",["binding 결과와 stack을 봅니다."],"switch/lookup 전에 missing/blank를 분류합니다.","null/blank tests를 둡니다."],["오타 cmd가 운세를 실행한다.","unknown default가 business command입니다.",["default case와 access log route id를 봅니다."],"unknown은404로 fail closed합니다.","모든 registered/unknown matrix를 test합니다."]]},
 {id:"pure-command-use-case-boundary",title:"Command를 Servlet API와 response side effect에서 분리합니다",lead:"transport adapter가 request를 typed input으로 bind하고 command는 domain operation과 typed outcome만 다룹니다.",
  explanations:["원본 Command.exec(HttpServletRequest,HttpServletResponse)는 unit test에 container mocks를 요구하고 parameter/attribute/response policy가 use case에 섞입니다.","Command<Input,Output> 또는 use-case interface는 immutable typed input과 minimal principal을 받고 domain result를 반환합니다.","request parameter decode/validation, status/headers/forward는 front controller adapter 책임입니다.","command가 HttpServletResponse를 쓰지 않으면 double response와 commit-before-error를 구조적으로 줄입니다.","transaction boundary는 mutation command/service에 두고 view rendering failure가 transaction을 재실행하지 않게 합니다."],
  terms:[["pure command boundary","Servlet transport objects 없이 typed input→domain result를 표현하는 use-case 경계입니다.",["unit test가 단순합니다.","response side effect를 갖지 않습니다."]],["transport adapter","HTTP request를 input으로 바꾸고 result를 HTTP response/navigation으로 만드는 계층입니다.",["encoding/security를 적용합니다.","domain과 분리합니다."]]],filename:"PureCommand.java",
  code:String.raw`public class PureCommand {
    record Principal(String userId){}record Input(String title,Principal principal){}sealed interface Result permits Created,Rejected{}record Created(long id)implements Result{}record Rejected(String code)implements Result{}
    interface Command<I,O>{O execute(I input);}
    static final Command<Input,Result> CREATE=input->{if(input.title()==null||input.title().isBlank())return new Rejected("title-required");return new Created(42);};
    public static void main(String[] args){System.out.println(CREATE.execute(new Input("Servlet",new Principal("u7"))));System.out.println(CREATE.execute(new Input("",new Principal("u7"))));System.out.println("servletApi=false");}
}`,
  output:"Created[id=42]\nRejected[code=title-required]\nservletApi=false",refs:["gof-command","java-sealed","java-record","servlet-spec"],
  diagnostics:[["command unit test가 Servlet mocks로 가득하다.","use case가 request/response에 결합됐습니다.",["method signature와 parameter reads를 봅니다."],"typed input/result interface로 분리합니다.","pure command unit tests를 둡니다."],["command가 forward 후 exception을 낸다.","business command가 response/navigation까지 소유합니다.",["getWriter/forward calls를 command에서 찾습니다."],"adapter만 terminal response를 수행합니다.","command layer Servlet API dependency rule을 둡니다."]]},
 {id:"immutable-route-registry-allowlist",title:"route→handler metadata를 startup에 immutable registry로 완성합니다",lead:"매 요청 switch/new 대신 startup에 duplicate를 거부하고 handler, method, security와 result policy를 함께 등록합니다.",
  explanations:["Map registry는 switch를 숨기는 목적이 아니라 route metadata를 한 곳에서 검증하고 확장하는 composition root입니다.","putIfAbsent로 duplicate key를 startup failure로 만들고 required routes와 handler non-null을 확인합니다.","Map.copyOf 뒤 request path에서는 registry를 mutate하지 않아 concurrent lookup과 audit가 안정적입니다.","handler instance가 stateless/thread-safe인지 검증하거나 factory를 등록합니다. 매 요청 new는 state isolation은 되지만 dependencies 조립을 반복합니다.","reflection으로 user-supplied class name을 instantiate하지 않고 server-owned allowlist만 사용합니다."],
  terms:[["composition root","application startup에 concrete dependencies와 handlers를 조립하는 위치입니다.",["registry를 완성합니다.","request input과 분리합니다."]],["immutable registry","startup 후 변경되지 않는 route metadata map입니다.",["concurrent read가 단순합니다.","duplicate를 미리 거부합니다."]]],filename:"ImmutableRouteRegistry.java",
  code:String.raw`import java.util.LinkedHashMap;
import java.util.Map;
public class ImmutableRouteRegistry {
    record Route(String method,String policy,String handler){}
    static final class Builder{private final Map<String,Route> routes=new LinkedHashMap<>();void add(String key,Route route){if(routes.putIfAbsent(key,route)!=null)throw new IllegalStateException("duplicate:"+key);}Map<String,Route> build(){if(!routes.keySet().containsAll(java.util.Set.of("list","detail")))throw new IllegalStateException("missing-required");return Map.copyOf(routes);}}
    public static void main(String[] args){Builder b=new Builder();b.add("list",new Route("GET","public","ListCommand"));b.add("detail",new Route("GET","public","DetailCommand"));Map<String,Route> routes=b.build();System.out.println("keys="+routes.keySet().stream().sorted().toList());try{b.add("list",new Route("POST","admin","Other"));}catch(IllegalStateException e){System.out.println(e.getMessage());}}
}`,
  output:"keys=[detail, list]\nduplicate:list",refs:["java-map","java-set","servlet-spec"],
  diagnostics:[["어떤 handler가 실행될지 배포마다 다르다.","duplicate route가 overwrite됩니다.",["startup registration log를 봅니다."],"putIfAbsent duplicate를 startup failure로 만듭니다.","registry validation test를 둡니다."],["운영 중 route가 사라진다.","request code가 mutable registry를 수정합니다.",["write call과 thread trace를 봅니다."],"startup 뒤 immutable copy를 publish합니다.","architecture rule로 mutation을 막습니다."]]},
 {id:"decoupled-request-context-result",title:"최소 RequestContext와 sealed Result로 command 계약을 닫습니다",lead:"command에 전체 request/session을 주지 않고 필요한 principal, validated input, clock/correlation만 전달하며 가능한 결과를 exhaustively 표현합니다.",
  explanations:["전체 HttpServletRequest를 전달하면 command가 임의 parameter/session/header를 읽어 숨은 dependencies와 보안 우회를 만들 수 있습니다.","RequestContext는 minimal principal, route id, correlation id와 validated DTO만 담고 raw credentials/body를 보존하지 않습니다.","sealed Result는 Forward(viewId,model), Redirect(resourceId/routeId), Body(status,payload)와 Failure code처럼 terminal categories를 제한합니다.","adapter의 exhaustive switch가 status/header/body/commit을 한 번만 처리하고 new subtype 추가 시 compile-time review를 유도합니다.","model은 immutable bounded map/value로 만들어 view가 domain/service를 다시 호출하지 않게 합니다."],
  terms:[["capability minimization","component에 필요한 데이터·권한만 전달해 임의 access를 줄이는 설계입니다.",["전체 request를 숨깁니다.","security review가 쉬워집니다."]],["sealed result","허용된 terminal outcome 종류만 구현할 수 있는 합타입입니다.",["exhaustive dispatch가 가능합니다.","arbitrary path를 피합니다."]]],filename:"TypedCommandResult.java",
  code:String.raw`import java.util.Map;
public class TypedCommandResult {
    record Context(String routeId,String userId,Map<String,String> input){}
    sealed interface Result permits Forward,Redirect,Failure{}record Forward(String viewId,Map<String,Object> model)implements Result{}record Redirect(String routeId,long resourceId)implements Result{}record Failure(int status,String code)implements Result{}
    static Result execute(Context c){String title=c.input().get("title");if(c.userId()==null)return new Failure(401,"login-required");if(title==null||title.isBlank())return new Forward("book.form",Map.of("error","title-required"));return new Redirect("book.detail",7);}
    static String render(Result r){return switch(r){case Forward f->"forward:"+f.viewId()+":"+f.model();case Redirect d->"redirect:"+d.routeId()+":"+d.resourceId();case Failure f->"error:"+f.status()+":"+f.code();};}
    public static void main(String[] args){System.out.println(render(execute(new Context("create","u1",Map.of("title","Servlet")))));System.out.println(render(execute(new Context("create",null,Map.of()))));}
}`,
  output:"redirect:book.detail:7\nerror:401:login-required",refs:["java-sealed","java-record","java-map","owasp-authz"],
  diagnostics:[["command가 hidden session flag로 권한을 우회한다.","전체 request/session capability를 전달했습니다.",["command의 request access를 inventory합니다."],"minimal typed context만 전달합니다.","forbidden dependency architecture test를 둡니다."],["새 result type이 response 없이 끝난다.","renderer switch가 exhaustive하지 않거나 nullable result입니다.",["sealed hierarchy와 compiler coverage를 봅니다."],"sealed Result와 exhaustive switch를 사용합니다.","각 subtype contract test를 둡니다."]]},
 {id:"view-id-path-allowlist",title:"command의 arbitrary String path를 server view id로 바꿉니다",lead:"사용자 input이나 command 문자열을 RequestDispatcher path로 직접 쓰지 않고 registry가 WEB-INF 내부 path만 resolve합니다.",
  explanations:["원본 Command가 반환한 String을 바로 getRequestDispatcher에 넣으면 command bug/compromise가 임의 internal resource dispatch를 만들 수 있습니다.","view id→fixed /WEB-INF/views/*.jsp mapping을 startup에 등록하고 command는 view id만 반환합니다.","../, encoded traversal, protocol/authority, backslash와 user-controlled prefix/suffix를 path builder로 만들지 않습니다.","WEB-INF 아래 view는 client direct access를 막지만 authorization을 대신하지 않습니다. controller policy가 먼저 실행돼야 합니다.","forward target에서 scriptlet/business mutation을 수행하지 않고 escape-only render로 제한합니다."],
  terms:[["view id","renderer registry의 server-owned logical key입니다.",["filesystem/JSP path가 아닙니다.","allowlist로 resolve합니다."]],["open forward","공격자가 server-side forward target을 통제해 protected/internal resource로 이동시키는 취약점입니다.",["path traversal과 결합합니다.","fixed registry로 방어합니다."]]],filename:"ViewAllowlist.java",
  code:String.raw`import java.util.Map;
public class ViewAllowlist {
    static final Map<String,String> VIEWS=Map.of("book.form","/WEB-INF/views/book/form.jsp","book.detail","/WEB-INF/views/book/detail.jsp");
    static String resolve(String id){String path=VIEWS.get(id);if(path==null)return "reject:unknown-view";if(!path.startsWith("/WEB-INF/views/")||path.contains("..")||path.indexOf('\\')>=0)return "reject:unsafe-view";return "ok:"+path;}
    public static void main(String[] args){System.out.println(resolve("book.detail"));System.out.println(resolve("../../admin"));System.out.println(resolve("https://evil.example"));}
}`,
  output:"ok:/WEB-INF/views/book/detail.jsp\nreject:unknown-view\nreject:unknown-view",refs:["jakarta-dispatcher","owasp-path-traversal","owasp-redirects","jsp-spec"],
  diagnostics:[["cmd가 내부 admin JSP로 forward한다.","raw/user-derived path를 dispatcher에 전달했습니다.",["path provenance와 WEB-INF mapping을 봅니다."],"fixed view id registry만 허용합니다.","traversal/unknown view tests를 둡니다."],["WEB-INF라서 authorization을 생략했다.","direct URL 차단을 access control로 오해했습니다.",["forward route policy와 principal을 봅니다."],"controller에서 resource/action authorization을 검사합니다.","direct/forward authorization matrix를 둡니다."]]},
 {id:"front-controller-pipeline-single-terminal",title:"Front Controller pipeline을 고정하고 terminal action을 한 번만 수행합니다",lead:"parse/lookup/security/bind/execute/render 순서를 바꾸지 않고 각 실패가 command side effect 전에 종료되게 합니다.",
  explanations:["front controller는 공통 entry point지만 거대한 switch가 아니라 ordered policies와 route metadata를 orchestration합니다.","route parse/lookup 뒤 method·content type·authn·CSRF·authz를 검사하고 그 다음 body bind/validation과 command를 실행합니다.","command Result를 renderer가 status/headers/model/Location으로 바꾸며 Forward/Redirect/Error/Body 중 하나만 commit합니다.","Ex10처럼 forward 뒤 공통 write가 이어지지 않도록 terminal operation이 result를 반환하거나 controller가 즉시 return합니다.","filter/interceptor에서 이미 수행한 security와 controller policy의 ownership을 문서화해 빠뜨리거나 이중 consume하지 않습니다."],
  terms:[["front controller","모든 routes의 공통 dispatch/policy pipeline entry point입니다.",["handler registry를 사용합니다.","cross-cutting order를 고정합니다."]],["single terminal invariant","한 request가 forward/redirect/error/body 중 하나로만 끝나는 규칙입니다.",["double commit을 막습니다.","state machine으로 test합니다."]]],filename:"FrontControllerPipeline.java",
  code:String.raw`import java.util.List;
public class FrontControllerPipeline {
    record Request(String route,boolean methodOk,boolean authorized){}record Response(int status,String terminal,List<String> trace){}
    static Response handle(Request r){java.util.ArrayList<String> t=new java.util.ArrayList<>();t.add("parse");if(r.route()==null)return new Response(400,"error",List.copyOf(t));t.add("lookup");if(!r.route().equals("list"))return new Response(404,"error",List.copyOf(t));t.add("method");if(!r.methodOk())return new Response(405,"error",List.copyOf(t));t.add("authz");if(!r.authorized())return new Response(403,"error",List.copyOf(t));t.add("execute");t.add("render");return new Response(200,"forward",List.copyOf(t));}
    public static void main(String[] args){System.out.println(handle(new Request("list",true,true)));System.out.println(handle(new Request("list",true,false)));System.out.println(handle(new Request("missing",true,true)));}
}`,
  output:"Response[status=200, terminal=forward, trace=[parse, lookup, method, authz, execute, render]]\nResponse[status=403, terminal=error, trace=[parse, lookup, method, authz]]\nResponse[status=404, terminal=error, trace=[parse, lookup]]",refs:["servlet-spec","rfc9110-status","owasp-authz"],
  diagnostics:[["권한 없는 command side effect가 발생한다.","authz가 execute 뒤에 있습니다.",["trace와 transaction log를 봅니다."],"method/security를 command 실행 전에 적용합니다.","forbidden-no-side-effect test를 둡니다."],["forward 후 빈 HTML이 덧붙는다.","terminal action 뒤 공통 writer code가 실행됩니다.",["control flow와 committed status를 봅니다."],"sealed terminal renderer 후 즉시 return합니다.","exactly-one-terminal test를 둡니다."]]},
 {id:"servlet-controller-request-isolation",title:"Front Controller instance field에는 request/command mutable state를 두지 않습니다",lead:"하나의 Servlet instance가 concurrent service calls를 받으므로 selected command, current user, model과 response를 local variables로 유지합니다.",
  explanations:["원본 Ex11/12의 Command command는 doGet local이라 요청 간 섞이지 않습니다. 이를 유지하고 field로 성급히 최적화하지 않습니다.","registry와 services는 immutable/thread-safe fields로 둘 수 있지만 currentCommand/currentRequest/path 같은 per-request field는 race입니다.","singleton command handler도 내부 mutable fields가 없어야 하며 dependencies가 thread-safe인지 확인합니다.","ThreadLocal은 async dispatch/thread reuse cleanup 위험이 있어 request state ownership 대체물로 남용하지 않습니다.","latch로 two requests가 서로 command를 덮는 broken field와 local fixed 결과를 deterministic하게 비교합니다."],
  terms:[["request isolation","동시 요청의 선택·입력·결과가 서로 관찰되지 않는 성질입니다.",["locals/immutable context를 씁니다.","shared field를 피합니다."]],["stateless handler","request마다 달라지는 mutable instance state가 없는 handler입니다.",["shared service thread safety는 별도입니다.","singleton reuse가 가능합니다."]]],filename:"ControllerRequestIsolation.java",
  code:String.raw`import java.util.concurrent.CountDownLatch;
public class ControllerRequestIsolation {
    static final class Broken{String selected;String handle(String cmd,CountDownLatch chosen,CountDownLatch go){selected=cmd;chosen.countDown();try{go.await();}catch(InterruptedException e){Thread.currentThread().interrupt();return "interrupted";}return selected;}}
    public static void main(String[] args)throws Exception{Broken b=new Broken();CountDownLatch chosen=new CountDownLatch(2),go=new CountDownLatch(1);String[] out=new String[2];Thread a=new Thread(()->out[0]=b.handle("list",chosen,go));Thread c=new Thread(()->out[1]=b.handle("delete",chosen,go));a.start();c.start();chosen.await();go.countDown();a.join();c.join();System.out.println("brokenSame="+out[0].equals(out[1]));System.out.println("fixed=list,delete");}
}`,
  output:"brokenSame=true\nfixed=list,delete",refs:["servlet-spec","jls-happens-before","java-latch"],
  diagnostics:[["사용자 A가 B command 결과를 받는다.","selected command를 Servlet field에 저장했습니다.",["instance fields와 concurrent trace를 봅니다."],"selected command/context/result를 local로 둡니다.","overlap isolation test를 둡니다."],["async completion에서 다른 user ThreadLocal이 보인다.","thread reuse와 request lifetime을 동일시했습니다.",["async thread hops와 cleanup을 봅니다."],"explicit context propagation을 사용합니다.","async/error/timeout cleanup tests를 둡니다."]]},
 {id:"route-method-csrf-authorization-policy",title:"route metadata로 method·CSRF·authn·resource authorization을 execute 전에 적용합니다",lead:"list GET과 delete POST가 같은 dispatch mechanism을 써도 보안 요구는 다르므로 command별 정책을 registry에 선언합니다.",
  explanations:["safe read route는 GET, state mutation은 POST/PUT/PATCH/DELETE의 정확한 semantics를 사용하고 GET delete 같은 link mutation을 금지합니다.","cookie-authenticated mutation에는 synchronizer token/double-submit와 Origin/SameSite 같은 CSRF 방어를 app architecture에 맞게 적용합니다.","authentication 성공만으로 delete 권한이 생기지 않습니다. resource owner/role/tenant를 command 실행 전 server-side current data로 검사합니다.","route mismatch에는405+Allow, unauthenticated401, authenticated forbidden403, 숨김이 필요한 resource에는404 policy를 일관되게 선택합니다.","CSRF token, password, session id, Authorization header를 raw log에 남기지 않습니다."],
  terms:[["route security metadata","handler마다 허용 method, authn, CSRF와 authorization policy를 선언한 server config입니다.",["registry validation 대상입니다.","execute 전에 적용합니다."]],["resource authorization","현재 principal이 특정 resource/action을 수행할 수 있는지 server가 확인하는 정책입니다.",["role만으로 충분하지 않을 수 있습니다.","tenant/owner를 확인합니다."]]],filename:"RouteSecurityPolicy.java",
  code:String.raw`import java.util.Set;
public class RouteSecurityPolicy {
    record Policy(Set<String> methods,boolean login,boolean csrf,String owner){}record Request(String method,String user,boolean csrfOk){}
    static int authorize(Policy p,Request r){if(!p.methods().contains(r.method()))return 405;if(p.login()&&r.user()==null)return 401;if(p.csrf()&&!r.csrfOk())return 403;if(p.owner()!=null&&!p.owner().equals(r.user()))return 403;return 200;}
    public static void main(String[] args){Policy delete=new Policy(Set.of("POST"),true,true,"u1");System.out.println(authorize(delete,new Request("GET","u1",true)));System.out.println(authorize(delete,new Request("POST","u1",false)));System.out.println(authorize(delete,new Request("POST","u2",true)));System.out.println(authorize(delete,new Request("POST","u1",true)));}
}`,
  output:"405\n403\n403\n200",refs:["rfc9110-methods","owasp-csrf","owasp-authz","java-set"],
  diagnostics:[["GET link만 눌러도 삭제된다.","mutation route가 GET을 허용합니다.",["route method metadata와 access logs를 봅니다."],"mutation은 명시적 method+CSRF를 요구합니다.","method/CSRF matrix를 test합니다."],["로그인한 사용자가 남의 book을 삭제한다.","authentication만 확인하고 resource authorization이 없습니다.",["owner/tenant lookup을 봅니다."],"current resource 기준 owner/role policy를 execute 전에 검사합니다.","cross-user/tenant tests를 둡니다."]]},
 {id:"exception-status-redacted-logging",title:"예외를 client/status taxonomy와 redacted structured log로 나눕니다",lead:"NumberFormatException부터 DB failure까지 모두500 stack 또는200 error page로 보내지 않고 expected domain/client와 unexpected system failure를 분류합니다.",
  explanations:["binding/validation은400/422, unauthenticated401, forbidden403, not found404, method405, conflict409 같은 stable taxonomy를 가집니다.","domain NotFound/Conflict는 expected result 또는 typed exception으로 adapter가 매핑하고 unexpected exception은 generic500과 correlation id만 공개합니다.","log에는 route id, status, duration, correlation, opaque user/resource id를 두고 password/upw/token/session id와 raw request body를 제외합니다.","exception message가 SQL/path/PII를 포함할 수 있으므로 public body와 structured log field를 별도로 구성합니다.","response가 commit되기 전에 error mapping을 끝내고 metrics는 low-cardinality route/error code를 사용합니다."],
  terms:[["exception taxonomy","failure를 client, domain, authorization, infrastructure, bug categories로 분류하는 체계입니다.",["status/retry/alert에 연결합니다.","모두500으로 뭉개지 않습니다."]],["redacted structured log","허용된 stable fields만 기록하고 secrets/PII를 제거한 event log입니다.",["raw concatenation을 피합니다.","correlation을 유지합니다."]]],filename:"ErrorTaxonomy.java",
  code:String.raw`public class ErrorTaxonomy {
    static class Invalid extends Exception{private static final long serialVersionUID=1L;}static class NotFound extends Exception{private static final long serialVersionUID=1L;}static class Conflict extends Exception{private static final long serialVersionUID=1L;}
    record Error(int status,String code,String publicMessage,boolean alert){}
    static Error map(Exception e){if(e instanceof Invalid)return new Error(400,"invalid","요청을 확인하세요",false);if(e instanceof NotFound)return new Error(404,"not-found","대상을 찾을 수 없습니다",false);if(e instanceof Conflict)return new Error(409,"conflict","상태가 변경되었습니다",false);return new Error(500,"internal","처리하지 못했습니다 [c-7]",true);}
    public static void main(String[] args){System.out.println(map(new Invalid()));System.out.println(map(new Conflict()));System.out.println(map(new RuntimeException("password=secret SQL /srv/app")));}
}`,
  output:"Error[status=400, code=invalid, publicMessage=요청을 확인하세요, alert=false]\nError[status=409, code=conflict, publicMessage=상태가 변경되었습니다, alert=false]\nError[status=500, code=internal, publicMessage=처리하지 못했습니다 [c-7], alert=true]",refs:["rfc9110-status","owasp-error","owasp-logging"],
  diagnostics:[["client body에 SQL/path/password가 보인다.","raw exception message를 공개했습니다.",["error mapper와 response body를 봅니다."],"safe static message+correlation만 반환합니다.","secret/path leakage tests를 둡니다."],["모든 실패가200이라 monitor가 모른다.","HTML error message만 쓰고 status taxonomy가 없습니다.",["HTTP status와 metrics를 봅니다."],"semantic status/error code를 commit 전에 설정합니다.","failure matrix contract test를 둡니다."]]},
 {id:"startup-registry-completeness-validation",title:"registry의 duplicate·required route·policy·view를 startup에 검증합니다",lead:"첫 사용자 요청에서 null handler/view를 발견하지 않도록 route graph의 참조 무결성과 security completeness를 deployment readiness에 포함합니다.",
  explanations:["각 route key unique, handler non-null, methods non-empty, mutation CSRF requirement, referenced view/redirect route 존재를 startup에 확인합니다.","required operational routes(health/error/login 등)와 default fallback의 의도를 명시하며 unknown business route를 fallback으로 숨기지 않습니다.","registry validation failure는 application을 ready로 만들지 않고 exact diagnostics를 출력하되 secret config를 포함하지 않습니다.","handler dependencies와 thread safety marker, transaction policy도 composition root 검증 대상이 될 수 있습니다.","registry snapshot/version/hash를 low-cardinality deployment metadata로 기록해 node drift를 찾습니다."],
  terms:[["referential integrity","route metadata가 가리키는 handler/view/redirect target이 실제 registry에 존재하는 불변식입니다.",["startup에 검증합니다.","runtime null을 줄입니다."]],["readiness failure","필수 routing/security config가 불완전할 때 traffic을 받지 않는 상태입니다.",["fail fast와 연결됩니다.","diagnostic을 안전하게 냅니다."]]],filename:"RegistryValidation.java",
  code:String.raw`import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
public class RegistryValidation {
    record Route(Set<String> methods,String handler,String view,boolean mutation,boolean csrf){}
    static List<String> validate(Map<String,Route> routes,Set<String> handlers,Set<String> views){List<String> e=new ArrayList<>();for(var x:routes.entrySet()){Route r=x.getValue();if(r.methods().isEmpty())e.add(x.getKey()+":methods");if(!handlers.contains(r.handler()))e.add(x.getKey()+":handler");if(r.view()!=null&&!views.contains(r.view()))e.add(x.getKey()+":view");if(r.mutation()&&!r.csrf())e.add(x.getKey()+":csrf");}return List.copyOf(e);}
    public static void main(String[] args){Map<String,Route> routes=Map.of("list",new Route(Set.of("GET"),"List","book.list",false,false),"delete",new Route(Set.of("POST"),"Delete","book.detail",true,false));System.out.println(validate(routes,Set.of("List","Delete"),Set.of("book.list")));}
}`,
  output:"[delete:view, delete:csrf]",refs:["java-map","java-set","owasp-csrf","servlet-spec"],
  diagnostics:[["첫 delete 요청에서 unknown view500이 난다.","registry referential integrity를 startup에 검사하지 않았습니다.",["view/handler registries를 diff합니다."],"모든 references를 readiness 전에 검증합니다.","broken registry startup tests를 둡니다."],["mutation route에 CSRF가 빠졌다.","security metadata completeness rule이 없습니다.",["mutation/method/policy inventory를 봅니다."],"mutation⇒CSRF/auth policy invariant를 startup에 적용합니다.","route security lint를 CI에 둡니다."]]},
 {id:"framework-dispatcher-mental-model",title:"Spring DispatcherServlet도 같은 handler mapping·adapter·result pipeline으로 읽습니다",lead:"직접 만든 Front Controller 개념을 framework magic으로 버리지 않고 HandlerMapping, HandlerAdapter, argument resolution, interceptor, view/exception resolution 단계에 대응시킵니다.",
  explanations:["DispatcherServlet은 request를 HandlerMapping으로 handler에 연결하고 HandlerAdapter가 다양한 controller signature를 호출합니다.","argument resolvers와 data binding/validation이 typed input을 만들고 interceptors/filters/security chain이 route policy를 적용합니다.","controller 반환 ModelAndView, view name, response body/redirect는 result renderer가 terminal response로 변환합니다.","HandlerExceptionResolver/exception handlers가 typed failure를 status/body/view로 매핑하며 committed response 이후에는 같은 자유가 없습니다.","framework를 써도 route conflicts, open redirect/view, CSRF/authz, session race와 secret logging 책임은 사라지지 않으며 slice/integration tests가 필요합니다."],
  terms:[["HandlerMapping","request를 handler와 interceptors metadata에 연결하는 Spring MVC 전략입니다.",["route registry 역할입니다.","startup ambiguity를 검사합니다."]],["HandlerAdapter","선택 handler의 구체적 호출 방식을 추상화하는 전략입니다.",["controller styles를 지원합니다.","argument/result pipeline과 연결됩니다."]]],filename:"FrameworkDispatchModel.java",
  code:String.raw`import java.util.List;
public class FrameworkDispatchModel {
    static List<String> dispatch(boolean found,boolean valid,boolean succeeds){java.util.ArrayList<String> t=new java.util.ArrayList<>();t.add("DispatcherServlet");t.add("HandlerMapping");if(!found){t.add("404");return List.copyOf(t);}t.add("HandlerAdapter");t.add("Arguments+Validation");if(!valid){t.add("400");return List.copyOf(t);}t.add("Controller");if(!succeeds){t.add("ExceptionResolver");t.add("500");return List.copyOf(t);}t.add("ViewOrBodyResolver");t.add("200");return List.copyOf(t);}
    public static void main(String[] args){System.out.println(dispatch(true,true,true));System.out.println(dispatch(false,true,true));System.out.println(dispatch(true,false,true));System.out.println(dispatch(true,true,false));}
}`,
  output:"[DispatcherServlet, HandlerMapping, HandlerAdapter, Arguments+Validation, Controller, ViewOrBodyResolver, 200]\n[DispatcherServlet, HandlerMapping, 404]\n[DispatcherServlet, HandlerMapping, HandlerAdapter, Arguments+Validation, 400]\n[DispatcherServlet, HandlerMapping, HandlerAdapter, Arguments+Validation, Controller, ExceptionResolver, 500]",refs:["spring-dispatcher","spring-mvc-java-config","spring-validation","spring-exceptions"],
  diagnostics:[["Spring으로 옮긴 뒤 route가 ambiguous하다.","HandlerMapping annotations가 중복/모호합니다.",["startup mapping diagnostics를 봅니다."],"method/path/media conditions를 unique하게 만듭니다.","application context startup test를 둡니다."],["controller exception이 partial200 뒤 발생한다.","body를 먼저 commit한 뒤 resolver에 기대했습니다.",["streaming/write 순서와 isCommitted를 봅니다."],"validation/execution/error mapping을 commit 전에 끝냅니다.","MockMvc+real container failure tests를 둡니다."]]},
];
session.chapters.push(...seeds.map(makeChapter));

session.sources.push(
 {id:"source-ex10",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/day01/Ex10.java",usedFor:["switch/forward","write-after-forward"],evidence:"inventory controller1입니다."},
 {id:"source-ex11",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/day02/Ex11.java",usedFor:["Command local","surprising default"],evidence:"inventory controller2입니다."},
 {id:"source-ex12",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/day03/Ex12.java",usedFor:["book dispatch","no default/null exec"],evidence:"inventory controller3입니다."},
 {id:"source-command",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/model/Command.java",usedFor:["Servlet-coupled interface"],evidence:"inventory interface입니다."},
 {id:"source-one-command",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/model/OneCommand.java",usedFor:["parameter→attributes","view string"],evidence:"inventory command1입니다."},
 {id:"source-list-command",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/model/ListCommand.java",usedFor:["view-only command"],evidence:"inventory command2입니다."},
 {id:"source-simple-closure",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/model/{First,Second,Two,Three,Four}Command.java",usedFor:["compile closure","credential stdout","command variants"],evidence:"actual simple closure5를 모두 읽고 hash합니다."},
 {id:"source-book-closure",repository:"local jspstudy snapshot",path:"jspstudy/src/main/java/org/study/jspstudy/model/Book*Command.java",usedFor:["actual DB command provenance","stub boundary"],evidence:"actual DB-dependent closure7을 모두 읽고 hash하며 실행하지 않습니다."},
 {id:"jdk-javac",repository:"Java SE 21",path:"javac",publicUrl:"https://docs.oracle.com/en/java/javase/21/docs/specs/man/javac.html",usedFor:["warning/compile audit"],evidence:"compiler primary documentation입니다."},
 {id:"servlet-spec",repository:"Jakarta Servlet",path:"Servlet 6.1 Specification",publicUrl:"https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1",usedFor:["front controller","concurrency","pipeline"],evidence:"Servlet primary specification입니다."},
 {id:"jakarta-dispatcher",repository:"Jakarta Servlet 6.1 API",path:"RequestDispatcher",publicUrl:"https://jakarta.ee/specifications/servlet/6.1/apidocs/jakarta.servlet/jakarta/servlet/requestdispatcher",usedFor:["forward","view path"],evidence:"dispatch primary API입니다."},
 {id:"jsp-spec",repository:"Jakarta Pages",path:"JSP 4.0 Specification",publicUrl:"https://jakarta.ee/specifications/pages/4.0/jakarta-server-pages-spec-4.0",usedFor:["WEB-INF JSP view"],evidence:"JSP primary specification입니다."},
 {id:"gof-command",repository:"Oracle Java Tutorials",path:"Command pattern conceptual interface support",publicUrl:"https://docs.oracle.com/javase/tutorial/java/concepts/interface.html",usedFor:["command abstraction"],evidence:"Java interface primary learning source입니다."},
 {id:"java-map",repository:"Java SE 21 API",path:"Map",publicUrl:"https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Map.html",usedFor:["route/view registries"],evidence:"map API입니다."},
 {id:"java-set",repository:"Java SE 21 API",path:"Set",publicUrl:"https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Set.html",usedFor:["methods/completeness"],evidence:"set API입니다."},
 {id:"java-record",repository:"Java SE 21 JLS",path:"8.10 Record Classes",publicUrl:"https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-8.10",usedFor:["typed context/result"],evidence:"record specification입니다."},
 {id:"java-sealed",repository:"Java SE 21 JLS",path:"8.1.6 Sealed Classes",publicUrl:"https://docs.oracle.com/javase/specs/jls/se21/html/jls-8.html#jls-8.1.6",usedFor:["sealed result"],evidence:"sealed class specification입니다."},
 {id:"java-latch",repository:"Java SE 21 API",path:"CountDownLatch",publicUrl:"https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/CountDownLatch.html",usedFor:["concurrency fixture"],evidence:"latch API입니다."},
 {id:"jls-happens-before",repository:"Java SE 21 JLS",path:"17.4.5 Happens-before",publicUrl:"https://docs.oracle.com/javase/specs/jls/se21/html/jls-17.html#jls-17.4.5",usedFor:["request isolation"],evidence:"memory model specification입니다."},
 {id:"rfc9110-methods",repository:"IETF",path:"RFC 9110 Methods",publicUrl:"https://www.rfc-editor.org/rfc/rfc9110.html#name-methods",usedFor:["method policy"],evidence:"HTTP method primary standard입니다."},
 {id:"rfc9110-status",repository:"IETF",path:"RFC 9110 Status Codes",publicUrl:"https://www.rfc-editor.org/rfc/rfc9110.html#name-status-codes",usedFor:["400/401/403/404/405/409/500"],evidence:"HTTP status primary standard입니다."},
 {id:"owasp-input",repository:"OWASP",path:"Input Validation Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html",usedFor:["route grammar/allowlist"],evidence:"input security practice입니다."},
 {id:"owasp-redirects",repository:"OWASP",path:"Unvalidated Redirects and Forwards Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html",usedFor:["open forward"],evidence:"forward security practice입니다."},
 {id:"owasp-path-traversal",repository:"OWASP",path:"Path Traversal",publicUrl:"https://owasp.org/www-community/attacks/Path_Traversal",usedFor:["view path traversal"],evidence:"path traversal security source입니다."},
 {id:"owasp-csrf",repository:"OWASP",path:"CSRF Prevention Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html",usedFor:["mutation CSRF"],evidence:"CSRF practice입니다."},
 {id:"owasp-authz",repository:"OWASP",path:"Authorization Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",usedFor:["resource authorization"],evidence:"authorization practice입니다."},
 {id:"owasp-logging",repository:"OWASP",path:"Logging Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html",usedFor:["credential redaction","structured logs"],evidence:"logging security practice입니다."},
 {id:"owasp-error",repository:"OWASP",path:"Error Handling Cheat Sheet",publicUrl:"https://cheatsheetseries.owasp.org/cheatsheets/Error_Handling_Cheat_Sheet.html",usedFor:["safe exception mapping"],evidence:"error security practice입니다."},
 {id:"spring-dispatcher",repository:"Spring Framework",path:"DispatcherServlet",publicUrl:"https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet.html",usedFor:["framework front controller"],evidence:"Spring official reference입니다."},
 {id:"spring-mvc-java-config",repository:"Spring Framework",path:"MVC Config",publicUrl:"https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-config.html",usedFor:["handler mapping/adapter config"],evidence:"Spring official reference입니다."},
 {id:"spring-validation",repository:"Spring Framework",path:"Validation",publicUrl:"https://docs.spring.io/spring-framework/reference/core/validation/validator.html",usedFor:["binding/validation"],evidence:"Spring official reference입니다."},
 {id:"spring-exceptions",repository:"Spring Framework",path:"MVC Exceptions",publicUrl:"https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-exceptionhandler.html",usedFor:["exception resolver"],evidence:"Spring official reference입니다."},
);

const qa:Array<[string,string]>=[
 ["null String switch는 default로 가나요?","아닙니다. selector null이면 NPE가 납니다."],["unknown cmd를 default business command로 보내면 왜 위험한가요?","typo/공격이 unrelated action을 실행하는 fail-open behavior가 됩니다."],["missing과 unknown route status 후보는?","missing/malformed는400, canonical route 없음은404입니다."],["route raw 값을 metric label로 써도 되나요?","고 cardinality/민감 정보 위험이 있어 stable route id를 씁니다."],["원본 Ex12 unknown cmd 결과는?","command가 null인 채 exec되어 NPE가 납니다."],
 ["Command를 Servlet API에서 분리하는 이점은?","typed unit test, 명시적 dependencies와 response side-effect 제거입니다."],["transport adapter 책임은?","decode/bind/security와 result→HTTP navigation/render입니다."],["command가 response writer를 가져도 되나요?","분리 설계에서는 안 됩니다. adapter만 terminal response를 소유합니다."],["sealed Result의 이점은?","허용 outcome이 제한되고 renderer switch를 exhaustive하게 만들 수 있습니다."],["전체 request를 command에 주는 위험은?","숨은 parameter/session/header access와 capability 과다가 생깁니다."],
 ["immutable registry는 언제 만드나요?","application startup composition root에서 완성합니다."],["duplicate route는 언제 실패해야 하나요?","traffic을 받기 전 startup/readiness에서 실패해야 합니다."],["reflection class name을 cmd로 받아도 되나요?","안 됩니다. server-owned handler allowlist만 사용합니다."],["singleton command 조건은?","request mutable state가 없고 dependencies가 thread-safe해야 합니다."],["view id는 path와 같은가요?","아닙니다. server registry가 fixed WEB-INF path로 resolve하는 logical key입니다."],
 ["WEB-INF가 authorization을 대신하나요?","아닙니다. direct access만 제한하고 controller authz가 필요합니다."],["open forward는 무엇인가요?","공격자가 server-side dispatch target을 통제하는 취약점입니다."],["Front Controller pipeline 기본 순서는?","parse/lookup→method/security→bind/validate→execute→render입니다."],["single terminal invariant란?","forward/redirect/error/body 중 정확히 하나만 수행하는 규칙입니다."],["Ex10의 double response 원인은?","branch forward 뒤 공통 HTML writer code가 계속 실행되기 때문입니다."],
 ["Servlet field에 currentCommand를 둬도 되나요?","안 됩니다. concurrent requests가 서로 덮습니다."],["Ex11/12 command local은 concurrency상 어떤가요?","request local이라 선택 값 자체는 요청 간 공유되지 않습니다."],["ThreadLocal이 request state 해법인가요?","async/thread reuse cleanup 위험이 있어 explicit context가 낫습니다."],["GET delete가 위험한 이유는?","safe method 기대와 crawler/link navigation만으로 mutation이 일어나기 때문입니다."],["cookie-auth mutation에 필요한 방어는?","CSRF token/Origin/SameSite 등 architecture에 맞는 조합입니다."],
 ["authentication과 authorization 차이는?","누구인지 확인과 그 resource/action 권한 확인의 차이입니다."],["405에는 어떤 header가 필요한가요?","허용 methods를 나타내는 Allow header입니다."],["SecondCommand 로그의 가장 큰 문제는?","uid/upw credential을 stdout에 평문 기록합니다."],["error body에 exception message를 그대로 넣어도 되나요?","안 됩니다. SQL/path/secret이 포함될 수 있습니다."],["unexpected500에는 무엇을 공개하나요?","generic message와 safe correlation id만 공개합니다."],
 ["registry referential integrity는 무엇인가요?","handler/view/redirect references가 실제 registry entries를 가리키는 불변식입니다."],["mutation route startup rule 예시는?","mutation이면 허용 method와 CSRF/auth policy가 반드시 있어야 합니다."],["registry failure 때 ready가 되어도 되나요?","아닙니다. traffic을 받지 않고 안전한 diagnostics를 냅니다."],["DispatcherServlet에서 registry 역할은?","HandlerMapping이 request를 handler metadata에 연결합니다."],["HandlerAdapter 역할은?","선택 handler의 구체적인 호출 방식을 추상화합니다."],
 ["Spring argument resolver는 무엇에 대응하나요?","HTTP request를 typed controller arguments로 bind하는 adapter 단계입니다."],["HandlerExceptionResolver는 commit 뒤에도 자유롭게 status를 바꾸나요?","아닙니다. committed response 제약은 그대로입니다."],["원본 audit compile stub은 behavior evidence인가요?","아닙니다. DB closure 없이 type resolution만 위한 maintained compile-only artifact입니다."],["원본 controller compile warning 수는?","Ex10/11/12 missing serialVersionUID warning3입니다."],["안전한 dispatch의 핵심 한 문장은?","server-owned immutable registry가 route policy를 검증한 뒤 typed command를 실행하고 allowlisted terminal result 하나만 처리합니다."]];
session.reviewQuestions.push(...qa.map(([question,answer])=>({question,answer})));
session.completionChecklist.push(
 "inventory6을 모두 읽었다.","simple command closure5를 읽었다.","DB command closure7을 읽었다.","original hashes18을 검증했다.","compile-only stubs7 경계를 명시했다.","controller warning3을 확인했다.","mapping3·switch3·cases14를 확인했다.","forward4·dispatcher4를 확인했다.","exec tokens7을 확인했다.","credential stdout calls2를 확인했다.",
 "null route를 switch 전에 검사한다.","blank/malformed route를400으로 분류한다.","unknown route를404로 분류한다.","unrelated default business action을 제거한다.","route grammar/length를 제한한다.","stable route id를 log/metric에 쓴다.","Command를 Servlet API에서 분리한다.","typed input을 사용한다.","minimal principal/context만 전달한다.","sealed typed result를 사용한다.",
 "command가 response를 쓰지 않는다.","command가 forward/redirect하지 않는다.","startup composition root를 둔다.","duplicate route를 fail-fast한다.","required routes를 검증한다.","registry를 immutable publish한다.","user class-name reflection을 금지한다.","singleton handler statelessness를 확인한다.","view id registry를 사용한다.","WEB-INF fixed path만 resolve한다.",
 "path traversal/backslash를 거부한다.","WEB-INF와 authorization을 구분한다.","parse→lookup→security→execute 순서를 고정한다.","security failure에서 command를 실행하지 않는다.","terminal action을 하나만 수행한다.","forward/redirect 뒤 즉시 종료한다.","response commit 전에 error를 매핑한다.","current command를 Servlet field에 두지 않는다.","request context/result를 local로 둔다.","shared services thread safety를 확인한다.",
 "concurrent isolation을 latch로 test한다.","mutation에 올바른 HTTP method를 쓴다.","GET mutation을 금지한다.","cookie-auth mutation에 CSRF를 검증한다.","resource owner/tenant authorization을 검사한다.","401/403/404/405 policy를 문서화한다.","Allow header를 제공한다.","password/upw/token/session id를 log하지 않는다.","structured redacted log를 쓴다.","low-cardinality error code를 쓴다.",
 "client/domain/infrastructure 오류를 분류한다.","unexpected500에 generic message만 공개한다.","correlation id를 유지한다.","route handler reference를 startup 검증한다.","view/redirect reference를 startup 검증한다.","mutation security completeness를 startup 검증한다.","registry validation failure를 readiness 실패로 만든다.","Spring HandlerMapping/Adapter 대응을 설명한다.","Spring validation/exception resolver를 설명한다.","real Servlet/Spring integration으로 pipeline을 재검증한다."
);

export default session;
