import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["py-030"],
  slug: "python-030-module-import-main-guard",
  courseId: "python",
  moduleId: "03-oop-stdlib",
  order: 30,
  title: "모듈 import와 main guard",
  subtitle: "import가 파일 복사가 아니라 module 객체 생성과 top-level 실행이라는 사실을 이해하고, 재사용 가능한 library와 실행 entry point를 분리합니다.",
  level: "중급",
  estimatedMinutes: 145,
  coreQuestion: "같은 Python 파일을 다른 코드에서 안전하게 import하면서도 직접 실행·python -m·test·배포 환경에서 예측 가능한 시작점을 어떻게 만들까요?",
  summary: "module namespace·import 실행·sys.modules cache, import와 from import의 이름 binding, package와 absolute/relative import, sys.path·cwd·설치 환경을 연결합니다. main guard 유무에 따른 원본 Car 출력 부작용을 재현하고 __name__·__main__·python -m 차이를 격리 예제로 확인합니다. 순환 import·부분 초기화, import-time I/O·전역 singleton, 공개 API·resource loading·plugin 보안까지 운영 가능한 module 경계로 확장합니다.",
  objectives: [
    "module이 독립 namespace를 가진 객체이며 첫 import 때 top-level 문장이 실행되는 과정을 설명할 수 있다.",
    "import module과 from module import name이 호출부 namespace에 무엇을 bind하는지 구분할 수 있다.",
    "absolute·relative import와 package context, sys.path·cwd·설치 상태가 module 탐색에 미치는 영향을 진단할 수 있다.",
    "sys.modules cache 때문에 같은 process의 반복 import가 보통 module body를 다시 실행하지 않는다는 점을 확인할 수 있다.",
    "__name__ == '__main__' guard로 정의·실행 코드를 분리하고 직접 실행과 python -m을 목적에 맞게 선택할 수 있다.",
    "import-time 부수 효과와 순환 import의 부분 초기화 문제를 dependency 구조로 해결할 수 있다.",
    "package 공개 API·resource·configuration·plugin loading을 명시적이고 안전한 경계로 설계할 수 있다.",
  ],
  prerequisites: [
    { title: "함수 계약·스코프·반환", reason: "module top-level 절차를 main 함수와 import 가능한 작은 함수로 분리합니다.", sessionSlug: "python-021-function-contract-scope-return" },
    { title: "경로·파일 모드·context manager", reason: "module 탐색 경로와 package resource 경로를 cwd 파일 경로와 구분합니다.", sessionSlug: "python-024-path-file-modes-context-manager" },
    { title: "클래스·객체·생성자", reason: "다른 module에서 Car class 정의를 import하고 객체 생성 시점과 module 실행 시점을 구분합니다.", sessionSlug: "python-028-class-object-constructor" },
  ],
  keywords: ["Python", "module", "package", "import", "sys.modules", "sys.path", "__name__", "__main__", "main guard", "python -m", "circular import", "import side effect"],
  chapters: [
    {
      id: "module-object-execution",
      title: "module은 파일 내용이 복사되는 것이 아니라 한 번 실행되어 namespace 객체가 됩니다",
      lead: "첫 import는 module spec을 찾고 객체를 만들어 cache에 등록한 뒤 top-level 코드를 실행해 이름을 채웁니다.",
      explanations: [
        "Python source 파일 하나는 보통 module 하나가 됩니다. import day06.ex03_class는 파일 text를 호출부에 붙여 넣지 않습니다. import system이 module 객체를 만들고 module의 global namespace에서 class Car와 다른 top-level 문장을 실행한 뒤 호출부 이름에 module을 bind합니다.",
        "def와 class 문도 top-level 실행의 일부입니다. def는 함수 body를 지금 실행하지 않지만 function 객체를 만들어 이름에 bind하고, class 문은 class body를 실행해 class 객체를 만듭니다. 반면 top-level print·파일 open·network 호출은 import 중 즉시 실행됩니다.",
        "module.__dict__에는 해당 module의 global 이름이 들어 있고 module.__name__, __file__, __package__, __spec__ 같은 metadata가 import 문맥을 설명합니다. 디버깅 때 repr(module)과 __spec__을 확인할 수 있지만 production 로직을 내부 metadata 우연에 과도하게 의존시키지 않습니다.",
        "module import가 실패하면 예외가 호출자에게 전파되고 부분 초기화 상태가 관련 오류 메시지에 나타날 수 있습니다. 단순히 'module 없음'만 가정하지 말고 module body 내부의 다른 예외도 traceback의 마지막 원인과 첫 project frame으로 구분합니다.",
      ],
      concepts: [
        { term: "module object", definition: "독립 global namespace와 import metadata를 가지며 Python code·extension·namespace package 등을 나타내는 runtime 객체입니다.", detail: ["이름은 attribute로 조회할 수 있습니다.", "보통 sys.modules에서 fully qualified name으로 cache됩니다."] },
        { term: "top-level code", definition: "함수·method 내부가 아니라 module import 또는 직접 실행 중 module namespace에서 실행되는 문장입니다.", detail: ["def·class 정의도 top-level 문장입니다.", "I/O·print·thread 시작은 import 부수 효과가 됩니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "import 문에서 오류가 났지만 대상 module 파일은 실제로 존재한다.", likelyCause: "module 탐색은 성공했지만 그 module의 top-level 실행 또는 하위 import에서 예외가 발생했습니다.", checks: ["traceback의 최초 예외 type과 project source 줄을 확인합니다.", "ModuleNotFoundError.name이 요청 module인지 내부 dependency인지 봅니다.", "대상 module을 격리 process에서 import해 side effect를 재현합니다."], fix: "module body 오류·dependency 누락·환경 설정을 실제 원인에 맞게 수정하고 import-time 작업을 명시 함수로 옮깁니다.", prevention: "모든 public module을 clean environment에서 import하는 smoke test와 import-time I/O 금지 규칙을 둡니다." },
      ],
    },
    {
      id: "import-forms-and-namespaces",
      title: "import 형태마다 호출부 namespace에 bind되는 이름과 결합도가 다릅니다",
      lead: "import package.module은 module 이름을 통해 출처를 남기고 from package.module import Car는 Car 이름을 직접 bind합니다.",
      explanations: [
        "import day06.ex03_class 뒤에는 day06 또는 alias로 module을 조회하고 day06.ex03_class.Car처럼 사용합니다. from day06.ex03_class import Car는 import 과정 자체는 수행하되 현재 module global에 Car를 직접 bind합니다. 둘 다 source module body 실행 가능성이 있습니다.",
        "from module import *는 __all__ 또는 underscore 규칙에 따라 많은 이름을 가져와 출처·충돌을 숨깁니다. 교육 shell 외 production code에서는 명시 import를 사용합니다. alias는 긴 이름을 줄이거나 충돌을 피하되 관례적인 np·pd처럼 팀이 이해할 수 있는 이름을 사용합니다.",
        "import한 이름은 그 시점의 객체 reference입니다. from settings import VALUE 뒤 source module.VALUE를 새 객체로 바꿔도 호출부 VALUE 이름은 자동 재bind되지 않습니다. 동적 설정은 module attribute를 조회하거나 명시 configuration object를 전달합니다.",
        "underscore는 내부 API 의도를 나타낼 뿐 완전한 접근 제어가 아닙니다. package __init__.py의 __all__과 facade import로 public surface를 좁힐 수 있지만 실제 호환성은 문서·semantic version·test로 관리합니다.",
      ],
      concepts: [
        { term: "namespace binding", definition: "import 결과 객체를 현재 module의 특정 이름에 연결하는 동작입니다.", detail: ["import form과 alias에 따라 이름이 달라집니다.", "객체 reference binding이지 source text 복사가 아닙니다."] },
        { term: "public API surface", definition: "package 사용자가 의존하도록 공식 지원하는 module·class·함수·상수 집합입니다.", detail: ["내부 파일 구조와 분리할 수 있습니다.", "재export와 __all__은 의도 표현 수단이지 보안 장벽은 아닙니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "import 뒤 같은 이름이 다른 module의 class·function으로 바뀌거나 어디서 왔는지 알 수 없다.", likelyCause: "여러 from import 또는 star import가 현재 namespace 이름을 덮었습니다.", checks: ["value.__module__·__qualname__을 확인합니다.", "동일 이름 import와 alias를 검색합니다.", "star import와 __all__을 확인합니다."], fix: "module-qualified 호출 또는 의미 있는 alias로 출처를 명시하고 star import를 제거합니다.", prevention: "import order를 formatter로 통일하고 lint의 wildcard·redefined-name 규칙을 사용합니다." },
      ],
    },
    {
      id: "resolution-packages-sys-path",
      title: "module 탐색은 package 이름과 sys.path를 사용하며 cwd 파일 상대경로와 다른 문제입니다",
      lead: "파일이 disk에 있다는 사실만으로 import 가능한 것은 아니며 package root가 module search path에 있어야 합니다.",
      explanations: [
        "from day06.ex03_class import Car가 성공하려면 day06을 포함한 프로젝트 root가 sys.path에 있어야 합니다. 프로젝트 root에서 python -m day06.ex04_class를 실행하면 root가 search path에 들어가지만 day06 안에서 python ex04_class.py로 직접 실행하면 package context와 search path가 달라질 수 있습니다.",
        "sys.path에는 script directory, current environment의 site-packages, PYTHONPATH 등 여러 source가 들어갑니다. 코드 안에서 sys.path.append로 우연히 고치면 배포·test 순서에 따라 다른 package를 import할 수 있습니다. project를 editable install하거나 pyproject 기반 package로 설치하고 entry point를 사용합니다.",
        "absolute import는 top-level package에서 경로를 적고 relative import는 package 내부에서 .·..로 현재 package를 기준 삼습니다. relative import가 있는 파일을 경로로 직접 실행하면 known parent package가 없어 실패할 수 있어 python -m package.module을 사용합니다.",
        "project 파일 이름을 json.py, typing.py, requests.py처럼 표준·외부 package와 같게 만들면 search path 앞의 local 파일이 실제 package를 shadowing합니다. module.__file__과 spec.origin을 확인하고 충돌 이름을 바꿉니다.",
      ],
      concepts: [
        { term: "sys.path", definition: "import system이 top-level module·package를 찾을 때 순서대로 검색하는 경로 목록입니다.", detail: ["실행 방식과 environment에 따라 달라집니다.", "production 코드에서 임의 수정하기보다 package 설치를 사용합니다."] },
        { term: "package context", definition: "현재 module의 fully qualified 이름과 parent package 정보로 relative import와 python -m 실행을 해석하는 문맥입니다.", detail: ["__package__·__spec__에 반영됩니다.", "파일 경로 직접 실행은 package 문맥을 잃을 수 있습니다."] },
      ],
      codeExamples: [
        {
          id: "package-module-execution",
          title: "임시 package를 python -m으로 실행해 relative import 유지",
          language: "python",
          filename: "run_package_demo.py",
          purpose: "실제 파일을 격리 생성하고 package module entry point와 relative import 결과를 subprocess에서 확인합니다.",
          code: "from pathlib import Path\nfrom tempfile import TemporaryDirectory\nimport subprocess\nimport sys\n\nwith TemporaryDirectory() as temp_dir:\n    root = Path(temp_dir)\n    package = root / 'studyapp'\n    package.mkdir()\n    (package / '__init__.py').write_text('', encoding='utf-8')\n    (package / 'messages.py').write_text(\n        \"def greeting(name):\\n    return f'안녕, {name}'\\n\",\n        encoding='utf-8',\n    )\n    (package / 'cli.py').write_text(\n        \"from .messages import greeting\\n\"\n        \"def main():\\n    print(greeting('둘리'))\\n\"\n        \"if __name__ == '__main__':\\n    main()\\n\",\n        encoding='utf-8',\n    )\n\n    result = subprocess.run(\n        [sys.executable, '-m', 'studyapp.cli'],\n        cwd=root, text=True, capture_output=True, check=True,\n    )\n    print(result.stdout.strip())\n    print(f'stderr-empty={not result.stderr}')",
          walkthrough: [
            { lines: "1-9", explanation: "TemporaryDirectory에 __init__.py가 있는 실제 studyapp package를 만들어 현재 프로젝트를 오염시키지 않습니다." },
            { lines: "10-14", explanation: "messages module에 한글 greeting function을 작성합니다." },
            { lines: "15-21", explanation: "cli module은 .messages relative import, main 함수, main guard를 가집니다." },
            { lines: "23-27", explanation: "temporary root를 cwd로 두고 현재 Python executable의 -m 옵션으로 fully qualified module을 실행해 package context를 유지합니다." },
            { lines: "28-29", explanation: "stdout 결과와 stderr가 비었음을 안정적으로 확인합니다." },
          ],
          run: { environment: ["Python 3.8 이상", "run_package_demo.py로 저장"], command: "python run_package_demo.py" },
          output: { value: "안녕, 둘리\nstderr-empty=True", explanation: ["python -m이 studyapp.cli를 __main__으로 실행해 guard의 main이 호출됩니다.", ".messages는 studyapp package context에서 정상 해석됩니다.", "격리 package root를 subprocess cwd로 명시해 search path를 예측 가능하게 했습니다."] },
          experiments: [
            { change: "subprocess 명령을 [python, package/'cli.py'] 직접 경로 실행으로 바꿉니다.", prediction: "parent package를 알 수 없어 attempted relative import with no known parent package 오류가 납니다.", result: "package 내부 relative import entry point에는 -m 또는 설치된 console script가 적합합니다." },
            { change: "root에 studyapp.py 파일도 만듭니다.", prediction: "package와 module 이름 충돌로 resolution이 예상과 달라질 수 있습니다.", result: "top-level import 이름을 고유하게 정하고 spec.origin을 진단해야 합니다." },
          ],
          sourceRefs: ["py-import-class-source", "python-import-doc"],
        },
      ],
      diagnostics: [
        { symptom: "ModuleNotFoundError 또는 attempted relative import with no known parent package가 실행 방식에 따라 발생한다.", likelyCause: "package 내부 파일을 경로로 직접 실행해 parent package context가 없거나 package root가 sys.path에 없습니다.", checks: ["module.__package__와 sys.path[0]을 정상·실패 실행에서 비교합니다.", "python -m package.module로 재현합니다.", "활성 virtual environment에 project가 설치됐는지 확인합니다."], fix: "package root에서 -m으로 실행하거나 project를 설치하고 console entry point를 사용합니다. sys.path 임의 수정은 제거합니다.", prevention: "CI에서 설치된 package entry point와 -m 실행을 검증하고 내부 module 직접 경로 실행을 문서에서 피합니다." },
      ],
    },
    {
      id: "cache-and-import-side-effects",
      title: "첫 import 실행 결과는 sys.modules에 cache되고 import-time 부수 효과는 process 상태가 됩니다",
      lead: "같은 fully qualified 이름을 반복 import하면 보통 같은 module 객체를 돌려주므로 body가 매번 다시 실행되지 않습니다.",
      explanations: [
        "import system은 실행 전에 module을 sys.modules[name]에 넣어 recursive import를 관리하고 성공 후 같은 객체를 재사용합니다. 같은 process에서 import module을 두 번 적어도 top-level print는 보통 한 번입니다. 다른 process를 시작하면 cache가 새로 생기므로 다시 실행됩니다.",
        "원본 ex05는 main guard가 없어 Car 생성과 여러 print가 import 시 실행됩니다. ex06은 Car class만 가져오려 하지만 ex05 body 전체 출력이 먼저 발생합니다. import가 성공했다는 사실과 안전하게 재사용 가능하다는 사실은 다릅니다.",
        "import-time DB 연결·network 요청·thread 시작·환경 필수 검증은 test discovery와 CLI help까지 실패시킬 수 있습니다. module body에는 값싼 정의와 불변 metadata를 두고 expensive·fallible 작업은 main, application factory, lazy provider로 옮깁니다.",
        "importlib.reload는 기존 module 객체 namespace에서 code를 다시 실행하지만 from-import된 다른 이름·기존 instance class identity·resource cleanup이 자동 갱신되지 않습니다. production hot reload 수단으로 단순 사용하지 않고 개발 도구도 lifecycle을 명시합니다.",
      ],
      concepts: [
        { term: "sys.modules cache", definition: "현재 process에서 fully qualified module 이름을 이미 생성된 module 객체에 매핑하는 import cache입니다.", detail: ["반복 import의 body 재실행을 막습니다.", "부분 초기화 module도 순환 import 중 잠시 보일 수 있습니다."] },
        { term: "import side effect", definition: "이름 정의 외에 import만으로 발생하는 출력·I/O·전역 등록·thread 시작·환경 변경 같은 관찰 가능한 동작입니다.", detail: ["작고 의도된 registry 등록도 lifecycle을 문서화해야 합니다.", "실패 가능한 외부 작업은 명시 시작 함수로 옮깁니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "test 수집이나 단순 import만 했는데 로그 출력·파일 생성·network 연결이 발생한다.", likelyCause: "module top-level에 실행 절차가 있고 main guard 또는 명시 initialization 경계가 없습니다.", checks: ["AST·source에서 top-level call과 객체 생성을 찾습니다.", "python -c 'import target'을 격리 환경에서 실행합니다.", "하위 import까지 stdout·파일·network를 추적합니다."], fix: "정의와 side effect를 분리해 main·create_app·connect 함수로 옮기고 import 자체는 값싸고 결정적으로 만듭니다.", prevention: "import smoke test에서 stdout/stderr·network·파일 변경이 없음을 검증합니다." },
      ],
    },
    {
      id: "main-guard-entry-points",
      title: "main guard는 재사용 정의와 직접 실행 절차를 같은 파일에서 분리합니다",
      lead: "파일이 top-level script로 실행되면 __name__은 '__main__'이고 일반 import면 fully qualified module 이름입니다.",
      explanations: [
        "원본 ex03은 Car class를 정의하고 if __name__ == '__main__' 안에서만 객체를 만들고 출력합니다. ex04가 Car를 import할 때 ex03의 demo 출력은 실행되지 않고 ex04가 명시한 출력만 나옵니다. 반대로 ex05에는 guard가 없어 ex06의 import만으로 demo가 노출됩니다.",
        "guard 안에 긴 업무 로직을 직접 쓰기보다 def main(argv=None) -> int 함수로 만들고 guard에서 raise SystemExit(main())을 호출합니다. parsing·core 함수는 import해 test할 수 있고 exit code는 shell·CI 계약이 됩니다.",
        "python file.py 직접 실행은 그 파일을 __main__ module로 실행하고 script directory를 search path에 둡니다. python -m package.module은 package resolution 후 해당 module code를 __main__으로 실행하므로 relative import가 유지됩니다. 설치 package는 console_scripts entry point로 main 함수를 연결할 수 있습니다.",
        "main guard는 process가 module을 두 경로로 중복 import하는 모든 문제를 자동 해결하지 않습니다. 실행 파일이 자신의 package 이름으로 다시 import되면 __main__ module과 package.module 두 객체가 생겨 class identity·singleton이 중복될 수 있습니다. entry point는 package 내부 module을 import하고 main만 호출하도록 얇게 유지합니다.",
      ],
      concepts: [
        { term: "__main__", definition: "현재 interpreter에서 top-level 실행 대상으로 선택된 module에 주어지는 특별 이름이자 entry module입니다.", detail: ["직접 파일 실행과 -m 실행 모두 대상 module의 __name__을 '__main__'으로 둡니다.", "일반 import의 __name__은 package를 포함한 module 이름입니다."] },
        { term: "main guard", definition: "if __name__ == '__main__': 조건으로 일반 import 때 실행하지 않을 CLI·demo 시작 절차를 제한하는 패턴입니다.", detail: ["정의와 실행을 분리합니다.", "import 부수 효과 전체를 자동 제거하지는 않습니다."] },
      ],
      codeExamples: [
        {
          id: "direct-vs-import-main-guard",
          title: "같은 module을 직접 실행하고 import해 body·main 차이 비교",
          language: "python",
          filename: "main_guard_demo.py",
          purpose: "임시 tool module을 subprocess에서 직접 실행·import해 top-level body와 guard 영역의 실행 횟수를 확인합니다.",
          code: "from pathlib import Path\nfrom tempfile import TemporaryDirectory\nimport subprocess\nimport sys\n\nwith TemporaryDirectory() as temp_dir:\n    root = Path(temp_dir)\n    tool = root / 'tool.py'\n    tool.write_text(\n        \"print(f'body:{__name__}')\\n\"\n        \"def main():\\n    print('main-called')\\n\"\n        \"if __name__ == '__main__':\\n    main()\\n\",\n        encoding='utf-8',\n    )\n\n    direct = subprocess.run(\n        [sys.executable, str(tool)],\n        text=True, capture_output=True, check=True,\n    )\n    imported = subprocess.run(\n        [sys.executable, '-c', 'import tool; import tool; print(\"runner-done\")'],\n        cwd=root, text=True, capture_output=True, check=True,\n    )\n\n    print('DIRECT')\n    print(direct.stdout.strip())\n    print('IMPORTED')\n    print(imported.stdout.strip())",
          walkthrough: [
            { lines: "1-7", explanation: "격리 경로와 tool.py를 준비합니다." },
            { lines: "8-13", explanation: "tool body는 언제나 __name__을 한 번 출력하고 main 함수 정의 뒤 guard가 참일 때만 main-called를 출력합니다." },
            { lines: "16-19", explanation: "첫 subprocess는 파일을 직접 실행해 tool의 __name__이 __main__입니다." },
            { lines: "20-23", explanation: "두 번째 process는 같은 module을 두 번 import하지만 sys.modules cache로 body는 한 번이고 guard는 거짓입니다." },
            { lines: "25-29", explanation: "두 process 출력을 label과 함께 비교합니다." },
          ],
          run: { environment: ["Python 3.8 이상", "main_guard_demo.py로 저장"], command: "python main_guard_demo.py" },
          output: { value: "DIRECT\nbody:__main__\nmain-called\nIMPORTED\nbody:tool\nrunner-done", explanation: ["직접 실행은 body와 guard main을 모두 실행합니다.", "import는 body 정의를 실행하지만 main guard를 건너뜁니다.", "같은 process의 두 번째 import는 cached tool을 재사용해 body를 다시 출력하지 않습니다."] },
          experiments: [
            { change: "guard를 제거하고 main()을 top-level에서 직접 호출합니다.", prediction: "import process에서도 main-called가 출력됩니다.", result: "재사용 module의 실행 절차가 import side effect가 됩니다." },
            { change: "importlib.reload(tool)을 추가합니다.", prediction: "tool body가 다시 실행되어 body:tool이 한 번 더 출력되지만 main guard는 계속 거짓입니다.", result: "reload는 일반 반복 import와 다른 명시적 재실행입니다." },
          ],
          sourceRefs: ["py-main-guard-source", "py-import-side-effect-source", "python-main-doc"],
        },
      ],
      diagnostics: [
        { symptom: "module을 import했을 뿐인데 demo·CLI가 실행되거나 process가 종료된다.", likelyCause: "실행 절차가 main guard 밖 top-level에 있거나 import 중 SystemExit를 발생시킵니다.", checks: ["module 하단의 객체 생성·main 호출·SystemExit를 확인합니다.", "__name__ 값을 직접 실행·import에서 비교합니다.", "하위 import가 side effect를 만드는지 격리합니다."], fix: "CLI 절차를 main 함수로 옮기고 guard에서만 호출하며 library code는 process exit 대신 예외·반환으로 계약합니다.", prevention: "import만 하는 test와 main(argv) unit test, CLI subprocess integration test를 분리합니다." },
      ],
    },
    {
      id: "circular-imports",
      title: "순환 import는 부분 초기화 module을 노출하므로 dependency 방향을 다시 설계합니다",
      lead: "A가 B를 import하고 B가 A를 import하면 A body가 끝나기 전에 B가 cache의 미완성 A를 조회할 수 있습니다.",
      explanations: [
        "sys.modules에 module을 실행 전에 넣는 것은 무한 재귀를 막지만 모든 이름이 준비됐다는 뜻은 아닙니다. B가 아직 정의되지 않은 A.SomeClass를 조회하면 partially initialized module 관련 ImportError·AttributeError가 납니다.",
        "함수 안 local import로 실행 시점을 늦추면 일부 cycle을 끊을 수 있지만 dependency 설계가 숨겨지고 매 호출 lookup이 생깁니다. optional heavy dependency·typing cycle처럼 근거가 있을 때 제한적으로 사용합니다.",
        "공유 type·constant·Protocol을 세 번째 낮은 계층 module로 옮기고 A와 B가 그 module에 의존하게 하면 방향이 단방향이 됩니다. service orchestration은 상위 module이 두 하위 component를 조합합니다.",
        "type hint 때문에 생긴 cycle은 from __future__ import annotations, TYPE_CHECKING guard, 문자열 annotation을 사용할 수 있습니다. runtime에 실제 class가 필요한지 정적 도구만 필요한지 구분합니다.",
      ],
      concepts: [
        { term: "circular import", definition: "두 개 이상의 module import dependency가 cycle을 만들어 초기화 중 서로를 다시 요구하는 구조입니다.", detail: ["부분 초기화 namespace 오류가 날 수 있습니다.", "dependency inversion·공유 contract 추출로 해결합니다."] },
        { term: "partially initialized module", definition: "sys.modules에는 등록됐지만 top-level body 실행이 아직 끝나 모든 이름이 준비되지 않은 module 상태입니다.", detail: ["cycle 중 관찰될 수 있습니다.", "import 순서에 따라 증상이 달라져 보일 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "cannot import name ... from partially initialized module 또는 import 순서에 따른 AttributeError가 난다.", likelyCause: "module dependency cycle에서 상대 module의 이름이 정의되기 전에 조회됩니다.", checks: ["A→B→...→A import graph를 그립니다.", "각 module top-level에서 상대 attribute를 언제 읽는지 확인합니다.", "type hint만 필요한 import인지 분류합니다."], fix: "공유 Protocol·model을 낮은 독립 module로 추출하거나 상위 composition root가 양쪽을 조합하게 합니다. type-only cycle은 TYPE_CHECKING으로 분리합니다.", prevention: "architecture dependency rule과 import graph cycle check를 CI에 두고 module top-level orchestration을 피합니다." },
      ],
    },
    {
      id: "production-module-boundaries",
      title: "module 경계는 configuration·resource·plugin·관찰성을 명시적으로 소유해야 합니다",
      lead: "import가 어디서나 성공하고 같은 public API를 제공하려면 cwd와 import-time 외부 상태에 의존하지 않아야 합니다.",
      explanations: [
        "package에 포함된 template·data 파일을 Path.cwd나 __file__ 문자열 조합으로 찾기보다 importlib.resources를 사용하면 wheel·zip 등 distribution 형태에서도 resource abstraction을 유지할 수 있습니다. 사용자 writable data는 package resource와 분리합니다.",
        "환경 변수·secret을 module import 시 읽어 global singleton을 만들면 test마다 환경을 바꿔도 cache된 값이 남습니다. create_settings·create_app에서 명시적으로 읽고 object를 dependency로 전달합니다. 필수 설정 오류는 application 시작 경계에서 field 이름만 보고하고 secret 값은 숨깁니다.",
        "사용자 문자열을 importlib.import_module에 그대로 전달하면 arbitrary installed module code를 실행할 수 있습니다. plugin은 허용 ID→entry point/factory whitelist와 version·signature·권한 검증을 사용하고 신뢰되지 않은 code는 별도 process·sandbox가 필요합니다.",
        "import 시간을 측정하고 무거운 dependency는 실제 필요 지점 또는 optional feature boundary로 이동할 수 있습니다. 그러나 lazy import가 첫 요청 latency·동시 초기화·오류 지연을 만들 수 있으므로 startup warm-up과 thread safety를 함께 설계합니다.",
      ],
      concepts: [
        { term: "composition root", definition: "application entry에서 configuration과 concrete dependency를 생성해 component를 조립하는 명시적 시작 경계입니다.", detail: ["library module의 import-time singleton을 줄입니다.", "main·web app factory·worker bootstrap이 될 수 있습니다."] },
        { term: "plugin entry point", definition: "설치 distribution이 정해진 group과 이름으로 factory를 등록해 host가 발견할 수 있게 하는 package metadata 기반 확장 지점입니다.", detail: ["발견 가능하다는 사실은 신뢰 가능하다는 뜻이 아닙니다.", "allowlist·version·격리 정책이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [],
      comparisons: [
        { title: "Python 코드를 어떻게 시작할까요?", options: [
          { name: "python file.py", chooseWhen: "독립 단일 script거나 package relative import가 필요 없는 진입 파일일 때", avoidWhen: "package 내부 module을 파일 경로로 직접 실행할 때", tradeoffs: ["간단하고 즉시 실행됩니다.", "script directory가 import 기준이 됩니다.", "같은 module 중복 identity에 주의합니다."] },
          { name: "python -m package.module", chooseWhen: "설치·project root의 package 문맥과 relative import를 유지해 module entry를 실행할 때", avoidWhen: "사용자가 기억할 안정 CLI 이름을 제공해야 할 때", tradeoffs: ["package resolution을 사용합니다.", "cwd/search path·설치 상태가 필요합니다.", "대상 __name__은 __main__입니다."] },
          { name: "설치 console entry point", chooseWhen: "배포 package가 안정된 CLI command를 제공할 때", avoidWhen: "아직 package metadata 없는 일회성 학습 script일 때", tradeoffs: ["사용자가 module 경로를 몰라도 됩니다.", "build·install metadata가 필요합니다.", "main 함수와 exit code 계약을 명시할 수 있습니다."] },
        ] },
      ],
      expertNotes: ["subinterpreter·multiprocessing spawn에서는 module import와 global 초기화가 process/interpreter마다 다시 일어날 수 있으므로 sys.modules cache를 시스템 전체 singleton으로 오해하지 않습니다.", "supply-chain 공격을 줄이려면 dependency lock·hash·trusted index와 package 이름 typo 방어를 사용하고 import origin을 민감 경로 없이 관찰합니다."],
    },
  ],
  lab: {
    title: "재사용 가능한 학습 통계 package와 CLI entry point",
    scenario: "CSV 학습 기록을 분석하는 package를 library import, python -m 실행, 자동 test에서 부수 효과 없이 공통 사용하도록 구조화합니다.",
    setup: ["study_stats/에 __init__.py, models.py, analysis.py, cli.py, __main__.py를 만듭니다.", "pyproject 설정을 추가할 수 있지만 실제 외부 배포는 하지 않습니다.", "TemporaryDirectory의 합성 CSV만 사용합니다."],
    steps: ["models와 analysis에는 class·순수 함수 정의만 두고 import 시 print·파일 open을 하지 않습니다.", "cli.main(argv=None)->int가 argparse·파일 I/O·오류 표시를 소유하게 합니다.", "__main__.py는 from .cli import main 뒤 SystemExit(main())만 수행합니다.", "package __init__에는 안정 public API만 재export하고 내부 helper를 노출하지 않습니다.", "analysis→models 단방향 dependency를 만들고 cli가 둘을 조합해 cycle을 피합니다.", "python -m study_stats와 library import 두 subprocess를 실행해 출력·exit code를 검증합니다.", "같은 process에서 package를 두 번 import해 module body side effect가 없음을 확인합니다.", "cwd를 두 위치로 바꿔도 설치/editable package와 명시 입력 경로가 동작하는지 테스트합니다.", "잘못된 plugin 이름·누락 configuration·민감 path 로그 정책을 추가합니다."],
    expectedResult: ["library import는 stdout·파일·network side effect가 없습니다.", "python -m 실행만 CLI 결과를 출력하고 의미 있는 exit code를 반환합니다.", "relative import와 public API가 cwd 변경에도 안정적입니다.", "순환 import 없이 dependency 방향이 한눈에 보입니다.", "test가 main 함수를 직접 호출할 수 있고 CLI subprocess test는 별도입니다.", "외부 문자열이 임의 module import로 이어지지 않습니다."],
    cleanup: ["TemporaryDirectory와 합성 data를 삭제합니다.", "editable install을 사용했다면 격리 virtual environment만 제거합니다."],
    extensions: ["console script entry point를 pyproject에 등록합니다.", "importlib.resources로 package sample schema를 읽습니다.", "entry point 기반 reporter plugin을 allowlist와 conformance test로 추가합니다.", "import time profile과 lazy optional dependency 정책을 작성합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 ex03·ex04와 ex05·ex06 import 결과를 비교하세요.", requirements: ["각 파일의 직접 실행과 import에서 __name__·stdout을 기록합니다.", "guard 있는 ex03 demo가 import에서 실행되지 않음을 확인합니다.", "guard 없는 ex05 출력이 ex06 import 중 발생함을 확인합니다.", "같은 process에서 두 번 import해 cache 결과를 봅니다.", "Car class의 __module__을 출력합니다."], hints: ["subprocess로 실행을 격리하면 sys.modules cache를 통제할 수 있습니다.", "stdout line을 정의·실행 source별로 표시합니다."], expectedOutcome: "import가 module body 실행이고 main guard가 entry 절차만 제한한다는 사실을 재현합니다.", solutionOutline: ["원본을 변경 없이 각 방식으로 실행합니다.", "출력 표를 만듭니다.", "top-level 정의와 side effect 줄을 분류합니다."] },
    { difficulty: "응용", prompt: "세 파일짜리 계산 package를 import-safe CLI로 리팩터링하세요.", requirements: ["core module에는 순수 함수만 둡니다.", "cli.main(argv)->int와 __main__.py를 만듭니다.", "absolute·relative import 중 선택 근거를 적습니다.", "cwd 두 곳에서 -m 실행과 import test를 통과합니다.", "ModuleNotFoundError와 domain 오류 exit code를 구분합니다."], hints: ["package 내부 파일 경로 직접 실행을 entry로 삼지 않습니다.", "main guard 안에는 main 호출만 남깁니다."], expectedOutcome: "library와 CLI가 같은 core를 공유하되 import side effect가 없는 package를 만듭니다." },
    { difficulty: "설계", prompt: "서드파티 분석 plugin을 발견·적재하는 architecture를 설계하세요.", requirements: ["entry point group과 public Protocol·version을 정의합니다.", "사용자 입력 module 경로 직접 import를 금지하고 allowlist를 둡니다.", "import 실패·부분 초기화·cycle·느린 import를 격리합니다.", "plugin process 권한·timeout·memory·network 정책을 포함합니다.", "conformance test·dependency lock·audit log를 설계합니다.", "secret과 절대 import path를 오류 로그에서 마스킹합니다."], hints: ["설치됨과 신뢰됨은 다릅니다.", "module import 자체가 code execution입니다."], expectedOutcome: "import system을 확장성뿐 아니라 supply-chain·격리·관찰성 경계로 설계합니다." },
  ],
  reviewQuestions: [
    { question: "import는 source 파일 내용을 호출부에 복사하나요?", answer: "아닙니다. module 객체와 namespace를 만들고 top-level code를 실행한 뒤 객체를 이름에 bind합니다." },
    { question: "같은 process에서 같은 module을 두 번 import하면 body가 두 번 실행되나요?", answer: "보통 sys.modules에 cached된 같은 객체를 재사용해 두 번째 일반 import에서는 다시 실행하지 않습니다." },
    { question: "main guard가 참인 경우는 언제인가요?", answer: "해당 module이 현재 interpreter의 top-level 실행 대상이 되어 __name__이 '__main__'일 때입니다." },
    { question: "python package/module.py와 python -m package.module의 중요한 차이는 무엇인가요?", answer: "-m은 package resolution과 context를 유지해 relative import가 작동하지만 파일 직접 실행은 script로 취급될 수 있습니다." },
    { question: "guard가 있으면 모든 import 부수 효과가 사라지나요?", answer: "아닙니다. guard 밖 top-level call·하위 module import side effect는 계속 실행됩니다." },
    { question: "from module import VALUE 뒤 module.VALUE가 바뀌면 local VALUE도 자동으로 바뀌나요?", answer: "이름이 같은 객체를 가리키던 시점 이후 module.VALUE 재binding은 local VALUE를 자동 재binding하지 않습니다." },
    { question: "순환 import에서 partially initialized 오류가 나는 이유는 무엇인가요?", answer: "module이 cache에 등록됐지만 body 실행이 끝나기 전에 상대 module이 아직 정의되지 않은 이름을 조회하기 때문입니다." },
    { question: "외부 문자열을 import_module에 그대로 넣으면 왜 위험한가요?", answer: "import는 module top-level code execution이므로 공격자가 임의 설치 module을 선택할 수 있어 allowlist와 격리가 필요합니다." },
  ],
  completionChecklist: [
    "module 객체·namespace·top-level 실행 과정을 설명할 수 있다.",
    "import module·from import·alias의 binding 결과를 구분할 수 있다.",
    "sys.path·package context·shadowing을 사용해 import 실패를 진단할 수 있다.",
    "sys.modules cache와 import-time side effect의 process 수명을 설명할 수 있다.",
    "main 함수·guard·python -m·console entry point를 목적에 맞게 선택할 수 있다.",
    "순환 import graph를 찾아 shared contract 추출·dependency inversion으로 끊을 수 있다.",
    "import-safe configuration·resource·public API 경계를 설계할 수 있다.",
    "plugin import에 allowlist·version·격리·supply-chain 정책을 적용할 수 있다.",
  ],
  nextSessions: [],
  sources: [
    { id: "py-import-class-source", repository: "PYTHON-BASIC", path: "day06/ex04_class.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day06/ex04_class.py", usedFor: ["from package.module import Car", "imported class 생성", "module 경계"], evidence: "프로젝트 root에서 python -m day06.ex04_class를 실행해 ex03의 guarded demo 없이 ex04의 red·35·3000과 forward/stop/back 출력만 발생함을 확인했습니다." },
    { id: "py-main-guard-source", repository: "PYTHON-BASIC", path: "day06/ex03_class.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day06/ex03_class.py", usedFor: ["Car 정의", "__name__ guard", "직접 실행 demo 분리"], evidence: "Car class와 if __name__ == '__main__' 아래 객체 생성·출력을 감사해 import-safe 정의의 기준으로 사용했습니다." },
    { id: "py-import-side-effect-source", repository: "PYTHON-BASIC", path: "day06/ex05_class.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day06/ex05_class.py", usedFor: ["guard 없는 module", "top-level 객체 생성", "import 출력 부수 효과"], evidence: "격리 process에서 import만 해도 자동차 정보와 30km method 출력 전체가 발생함을 확인했습니다." },
    { id: "py-import-consumer-source", repository: "PYTHON-BASIC", path: "day06/ex06_class.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day06/ex06_class.py", usedFor: ["하위 import 부수 효과 전파", "main guard 필요"], evidence: "ex06 import가 ex05의 top-level 출력 전체를 먼저 실행한 뒤 import-complete로 진행됨을 확인했습니다." },
    { id: "python-import-doc", repository: "Python documentation", path: "reference/import.html", publicUrl: "https://docs.python.org/3/reference/import.html", usedFor: ["import system", "module cache", "spec", "package", "search"], evidence: "공식 import system reference를 module 생성·sys.modules·loading·package resolution 설명의 기준으로 사용했습니다." },
    { id: "python-main-doc", repository: "Python documentation", path: "library/__main__.html", publicUrl: "https://docs.python.org/3/library/__main__.html", usedFor: ["__main__", "main guard", "-m", "package entry"], evidence: "공식 __main__ 문서를 직접 실행·import·-m entry point 선택의 기준으로 사용했습니다." },
  ],
  sourceCoverage: { filesRead: 4, filesUsed: 4, uncoveredNotes: ["pyproject build backend·wheel publish·dependency resolution 전체는 가상환경/패키징 세션 py-040에서 확장합니다.", "sys.modules·순환 import·importlib.resources·plugin supply-chain은 원본 main guard 예제를 전문가 module architecture로 보강한 내용입니다."] },
} satisfies DetailedSession;

export default session;
