import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["py-025"],
  slug: "python-025-csv-rows-dictreader-transform-pipeline",
  courseId: "python",
  moduleId: "02-control-functions-io",
  order: 25,
  title: "CSV 행·DictReader·변환 파이프라인",
  subtitle: "CSV를 단순 쉼표 문자열이 아니라 dialect·header·schema가 있는 행 스트림으로 읽고, 검증·형 변환·안전한 출력까지 완성합니다.",
  level: "중급",
  estimatedMinutes: 155,
  coreQuestion: "모든 셀이 문자열로 들어오는 CSV를 인코딩·행 경계·스키마 손실 없이 읽어 검증하고, 실패 행을 추적하면서 완성된 결과 파일만 안전하게 공개하려면 어떻게 설계할까요?",
  summary: "csv.reader와 DictReader가 quoted comma·embedded newline을 record로 복원하는 과정, newline=''와 UTF-8/BOM 계약, header와 fieldnames 검증을 실제 실행으로 확인합니다. 원본 성적 CSV의 문자열 점수를 int로 변환해 합계·평균을 추가하고, 잘못된 숫자 행을 격리하는 streaming 파이프라인으로 확장합니다. DictWriter의 출력 순서와 누락·초과 field, spreadsheet formula injection, 임시 파일·fsync·os.replace를 이용한 atomic publish, 동시 writer와 관측성까지 다룹니다.",
  objectives: [
    "CSV의 delimiter·quote·record 규칙을 설명하고 문자열 split(',')이 quoted field에서 실패하는 이유를 예제로 증명할 수 있다.",
    "파일을 newline=''로 열어 csv module에 줄바꿈 처리를 맡기고 UTF-8·UTF-8 BOM 정책을 선택할 수 있다.",
    "csv.reader와 DictReader가 기본적으로 각 셀을 str로 반환함을 확인하고 숫자·불리언을 명시적으로 파싱할 수 있다.",
    "header의 누락·중복·순서·추가 field를 schema와 비교하고 잘못된 행의 line 정보와 원인을 보존할 수 있다.",
    "입력 전체를 list로 만들지 않고 한 행씩 parse→validate→transform→write하는 streaming pipeline을 구현할 수 있다.",
    "스프레드시트로 열릴 untrusted text의 formula injection 위험을 식별하고 export 경계에서 정책적으로 완화할 수 있다.",
    "임시 파일을 완전히 쓰고 검증한 뒤 os.replace하여 중간 실패에서 기존 결과를 보존할 수 있다.",
  ],
  prerequisites: [
    { title: "경로·파일 모드·context manager", reason: "CSV 파일의 경로 기준, r·w 모드, UTF-8, newline과 with 자원 수명을 안전한 변환의 바닥 계약으로 사용합니다.", sessionSlug: "python-024-path-file-modes-context-manager" },
    { title: "break·continue·for·range", reason: "reader를 한 행씩 streaming 순회하고 실패 행만 continue하며 정상·실패 건수를 추적합니다.", sessionSlug: "python-019-break-continue-for-range" },
    { title: "숫자형·진법·형 변환", reason: "문자열 점수를 int로 파싱하고 평균의 반올림·절삭 정책과 표시 문자열을 구분합니다.", sessionSlug: "python-004-numeric-types-conversion" },
  ],
  keywords: ["Python", "CSV", "csv.reader", "DictReader", "DictWriter", "newline", "UTF-8", "BOM", "schema", "streaming", "formula injection", "atomic write"],
  chapters: [
    {
      id: "csv-record-model",
      title: "CSV는 쉼표로 split하는 문자열이 아니라 quoting 규칙이 있는 record 형식입니다",
      lead: "한 field 안에도 쉼표·따옴표·줄바꿈이 들어갈 수 있으므로 parser가 물리적 줄을 논리적 행과 열로 복원해야 합니다.",
      explanations: [
        "CSV는 보통 한 record를 한 행에 놓고 delimiter로 field를 구분하지만 모든 CSV가 완전히 같은 dialect는 아닙니다. comma 대신 semicolon이나 tab을 쓸 수 있고 quotechar, doublequote, escapechar, line terminator 규칙도 다릅니다. 생산자와 소비자가 delimiter·encoding·header·newline을 함께 합의해야 합니다.",
        "이름이 Hong, Gil이면 field 안에 comma가 있으므로 writer는 따옴표로 감싼 형태를 만들고 reader는 다시 하나의 값으로 복원합니다. note field가 여러 줄이어도 quote 안의 줄바꿈은 record 끝이 아닙니다. text.split(',')나 line.split(',')는 이 상태를 이해하지 못해 열 수가 깨지고 multiline record를 두 행으로 잘못 나눕니다.",
        "csv module은 file-like object에서 한 번에 논리 row를 반환합니다. csv.reader의 row는 list이고 DictReader의 row는 header를 key로 삼는 dict입니다. reader.line_num은 reader가 소비한 물리 line 수여서 quoted multiline field 뒤에는 논리 row 번호보다 커질 수 있습니다. 업무 record id와 line_num을 같은 것으로 취급하지 않습니다.",
        "원본 ex04_file_csv.py는 csv.writer가 다섯 record를 쓰고 csv.reader가 각 행을 list로 읽습니다. 출력된 숫자 90과 bool True도 모두 따옴표가 보이는 문자열입니다. writer가 Python int·bool을 받아 text로 직렬화했고 reader는 schema를 모르므로 자동으로 원래 타입을 복원하지 않습니다.",
      ],
      concepts: [
        { term: "CSV dialect", definition: "delimiter·quotechar·escape·줄 끝처럼 CSV를 해석하고 쓰는 문법 설정 묶음입니다.", detail: ["생산자와 소비자가 같은 dialect에 합의해야 합니다.", "csv.excel이 흔한 기본이지만 외부 파일을 추측만으로 확정하지 않습니다."] },
        { term: "logical record", definition: "CSV parser가 quoting을 해석해 반환하는 한 행의 field 묶음입니다.", detail: ["quoted field의 물리적 줄바꿈을 포함할 수 있습니다.", "물리 line 수와 record 수는 다를 수 있습니다."] },
        { term: "quoting", definition: "delimiter·quote·newline이 포함된 field를 하나의 값으로 보존하기 위한 CSV 표현 규칙입니다.", detail: ["csv.writer가 필요한 quoting을 적용합니다.", "따옴표는 spreadsheet formula 실행을 막는 보안 장치가 아닙니다."] },
      ],
      codeExamples: [
        {
          id: "bom-quoted-multiline-record",
          title: "BOM·quoted comma·embedded newline을 한 record로 복원",
          language: "python",
          filename: "csv_record_model.py",
          purpose: "UTF-8 BOM을 제거하고 comma가 든 이름과 여러 줄 note를 DictReader가 올바른 field로 복원함을 확인합니다.",
          code: "import csv\nfrom io import BytesIO, TextIOWrapper\n\nraw = (\n    b\"\\xef\\xbb\\xbfid,name,note\\r\\n\"\n    b'1,\"Hong, Gil\",\"line 1\\r\\nline 2\"\\r\\n'\n)\n\nwith TextIOWrapper(BytesIO(raw), encoding=\"utf-8-sig\", newline=\"\") as stream:\n    reader = csv.DictReader(stream)\n    print(\"fieldnames:\", reader.fieldnames)\n    for row in reader:\n        print(\"id:\", row[\"id\"])\n        print(\"name:\", row[\"name\"])\n        print(\"note:\", repr(row[\"note\"]))\n        print(\"types:\", {key: type(value).__name__ for key, value in row.items()})\n        print(\"line_num:\", reader.line_num)",
          walkthrough: [
            { lines: "1-2", explanation: "disk file 없이 bytes와 text wrapper로 encoding·newline 경계를 그대로 재현합니다." },
            { lines: "4-7", explanation: "UTF-8 BOM으로 시작하는 header와 quoted comma·CRLF가 포함된 단일 data record bytes를 만듭니다." },
            { lines: "9", explanation: "utf-8-sig가 선택적 BOM을 소비하고 newline=''가 줄 끝 처리를 csv parser에 맡깁니다." },
            { lines: "10-11", explanation: "첫 논리 row를 header로 읽어 BOM 없는 id·name·note fieldnames를 만듭니다." },
            { lines: "12-16", explanation: "comma가 든 이름과 CRLF를 포함한 note가 각각 하나의 str field로 복원됐고 모든 value type이 str임을 출력합니다." },
            { lines: "17", explanation: "header 1줄과 quoted note의 2개 물리 줄을 소비해 line_num이 3임을 확인합니다." },
          ],
          run: { environment: ["Python 3.11 이상", "csv_record_model.py를 저장"], command: "python csv_record_model.py" },
          output: { value: "fieldnames: ['id', 'name', 'note']\nid: 1\nname: Hong, Gil\nnote: 'line 1\\r\\nline 2'\ntypes: {'id': 'str', 'name': 'str', 'note': 'str'}\nline_num: 3", explanation: ["BOM은 첫 key에 남지 않고 utf-8-sig decoder에서 제거됩니다.", "Hong, Gil의 comma와 note의 CRLF가 field 경계를 깨지 않습니다.", "line_num 3은 논리 data row가 세 개라는 뜻이 아니라 소비한 물리 line 위치입니다."] },
          experiments: [
            { change: "encoding을 utf-8로 바꿉니다.", prediction: "decode는 되지만 첫 fieldname 앞에 Unicode BOM 문자 \\ufeff가 남을 수 있습니다.", result: "row['id'] 조회가 KeyError가 되고 reader.fieldnames 첫 값 repr로 '\\ufeffid'를 확인합니다." },
            { change: "raw text를 줄 단위 split 후 comma split로 직접 파싱합니다.", prediction: "Hong, Gil이 두 열로 갈리고 quoted note의 둘째 물리 줄이 별도 record처럼 분리됩니다.", result: "CSV parser를 우회하는 단순 split이 data 구조를 손상시킵니다." },
          ],
          sourceRefs: ["py-csv-rows", "py-day05-csv-note"],
        },
      ],
      diagnostics: [
        { symptom: "comma가 포함된 이름이나 주소에서 열 개수가 예상보다 많아진다.", likelyCause: "csv.reader 대신 문자열 split(',')을 사용하거나 생산자의 quoting dialect와 다른 설정으로 읽었습니다.", checks: ["원본 bytes의 quotechar와 delimiter를 확인합니다.", "csv.reader 최소 예제로 같은 row를 읽습니다.", "외부 format 명세와 sample을 비교합니다."], fix: "합의한 dialect의 csv.reader 또는 DictReader를 사용하고 수동 split을 제거합니다.", prevention: "comma·quote·embedded newline·빈 field가 들어간 round-trip fixture를 둡니다." },
      ],
    },
    {
      id: "newline-encoding-bom",
      title: "newline과 encoding은 CSV schema만큼 중요한 파일 계약입니다",
      lead: "newline=''는 text layer가 줄바꿈을 먼저 바꾸지 않게 하고 csv module이 record 경계와 embedded newline을 직접 처리하게 합니다.",
      explanations: [
        "Python csv 문서는 file object를 newline=''로 열도록 권장합니다. 특히 Windows에서 text layer와 csv.writer가 줄바꿈을 각각 처리하면 행 사이 빈 줄처럼 보이는 중복이 생길 수 있습니다. 읽기에서도 quoted field 안의 줄바꿈을 parser가 정확히 해석하도록 newline=''를 유지합니다. reader와 writer 양쪽에서 같은 패턴을 습관화합니다.",
        "UTF-8 plain 파일은 encoding='utf-8'로 읽고 씁니다. UTF-8 BOM이 붙은 파일을 utf-8로 읽으면 BOM이 첫 header 문자열 일부가 되어 '\\ufeffid' 같은 key가 생길 수 있습니다. encoding='utf-8-sig'로 읽으면 BOM이 있으면 제거하고 없어도 일반 UTF-8을 읽습니다.",
        "출력에 utf-8-sig를 사용하면 BOM bytes를 새 파일 시작에 씁니다. 일부 spreadsheet가 UTF-8을 더 잘 인식하는 장점이 있지만 server pipeline은 BOM 없는 utf-8을 기대할 수 있습니다. 무조건 한쪽이 우월한 것이 아니라 target consumer와 계약을 정하고 자동 테스트합니다.",
        "writer 기본 line terminator는 흔히 CRLF입니다. Git diff나 다른 시스템에서 LF가 요구되면 csv.writer·DictWriter에 lineterminator='\\n'을 명시합니다. field 안의 줄바꿈과 record terminator는 다른 개념이며 parser가 quoting으로 구분합니다.",
      ],
      concepts: [
        { term: "newline=''", definition: "text I/O의 newline 변환을 최소화해 csv module이 줄 끝을 직접 처리하게 하는 open 인수입니다.", detail: ["읽기와 쓰기 모두 사용합니다.", "운영체제별 빈 줄·embedded newline 차이를 줄입니다."] },
        { term: "UTF-8 BOM", definition: "UTF-8 file 맨 앞의 EF BB BF bytes로 일부 도구가 encoding 표지처럼 사용합니다.", detail: ["일반 UTF-8에는 필수가 아닙니다.", "utf-8-sig는 읽을 때 BOM을 제거하고 쓸 때 추가합니다.", "header key에 섞이면 schema 검증이 실패합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "DictReader에서 row['id']가 KeyError인데 header에는 id가 보인다.", likelyCause: "BOM을 utf-8 decoder로 그대로 읽어 실제 첫 key가 '\\ufeffid'입니다.", checks: ["repr(reader.fieldnames[0])를 출력합니다.", "파일 첫 세 bytes가 EF BB BF인지 확인합니다.", "파일 생성 도구의 encoding 설정을 봅니다."], fix: "입력 계약이 BOM 가능 UTF-8이면 encoding='utf-8-sig'로 읽고 header를 다시 검증합니다.", prevention: "BOM 있음·없음 fixture를 모두 읽는 계약 테스트를 둡니다." },
        { symptom: "Windows에서 쓴 CSV를 열면 data 행 사이에 빈 줄이 생긴다.", likelyCause: "file text layer와 csv writer가 줄바꿈을 이중 변환하도록 newline 인수를 생략했습니다.", checks: ["open 호출에 newline=''가 있는지 확인합니다.", "raw bytes의 CRLF 반복을 검사합니다.", "writer lineterminator와 소비 도구를 확인합니다."], fix: "CSV file을 newline=''로 열고 record terminator는 writer 설정에 맡깁니다.", prevention: "Windows·Linux 또는 CRLF·LF fixture로 행 수 round-trip을 테스트합니다." },
      ],
    },
    {
      id: "reader-string-conversion",
      title: "CSV reader는 schema를 모르므로 모든 일반 field를 문자열로 돌려줍니다",
      lead: "화면에 90, True라고 보여도 reader가 반환한 값은 '90', 'True'이며 계산과 판정 전에 명시적으로 변환해야 합니다.",
      explanations: [
        "원본 ex04에서 writer.writerow는 int 점수와 bool 성별을 받지만 CSV에는 text 90과 True로 기록합니다. csv.reader가 다시 읽은 출력은 모든 field에 따옴표가 있는 list입니다. writer가 원래 Python type metadata를 저장한 것이 아니므로 reader가 int·bool을 자동 복원할 근거도 없습니다.",
        "int(text) 전에 strip, 빈 값 정책, 허용 범위를 검사합니다. ValueError를 잡을 때 0으로 조용히 바꾸면 총점이 틀린 정상 record처럼 보입니다. fail-fast, reject file 격리, skip 중 어떤 정책인지 정하고 row identifier·field name·원인·물리 line 위치를 남깁니다. 원문 전체를 로그에 남겨 개인정보를 노출하지 않습니다.",
        "bool('False')는 False가 아니라 True입니다. 비어 있지 않은 문자열이기 때문입니다. CSV boolean은 허용 vocabulary를 {'true': True, 'false': False}처럼 정의하고 대소문자·공백·미지정 값을 처리합니다. 날짜·Decimal·Enum도 같은 방식으로 schema parser를 둡니다.",
        "원본 평균은 int(total / len(scores) * 100) / 100으로 소수 둘째 자리에서 0 방향 절삭합니다. 반올림과 다르며 음수에서는 floor도 아닙니다. 성적처럼 정책이 중요한 수치에는 Decimal과 명시적 rounding mode 또는 정확한 format 요구를 사용합니다. f'{average:.2f}'는 저장 text 모양을 정할 뿐 계산값 타입을 보존하지 않습니다.",
      ],
      concepts: [
        { term: "parsing", definition: "외부 text를 검증하면서 int·Decimal·date·bool 같은 내부 type으로 바꾸는 경계 작업입니다.", detail: ["변환 가능성과 업무 범위를 함께 검사합니다.", "실패 원인을 field 단위로 보존합니다."] },
        { term: "type erasure in CSV", definition: "CSV text에는 Python int·bool 같은 원래 runtime type이 자동 보존되지 않는 특성입니다.", detail: ["schema가 type 복원 규칙을 제공해야 합니다.", "writer에 None을 주면 빈 field로 쓰여 None과 빈 문자열도 구분하기 어려워집니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "점수 합계가 문자열 연결처럼 '908090'이 되거나 sum에서 TypeError가 난다.", likelyCause: "reader가 반환한 '90'을 int로 변환하지 않고 문자열 + 또는 sum에 사용했습니다.", checks: ["row field의 repr과 type을 출력합니다.", "header와 column index가 맞는지 확인합니다.", "빈 값·공백·숫자 아닌 행을 찾습니다."], fix: "schema parser에서 int 변환과 0~100 범위를 검증하고 성공한 내부 record만 계산합니다.", prevention: "정상·빈 값·공백·문자·범위 밖 숫자를 포함한 table-driven parser 테스트를 둡니다." },
        { symptom: "CSV의 'False'를 bool로 변환했는데 True가 된다.", likelyCause: "bool 함수는 문자열 내용을 해석하지 않고 비어 있는지만 판단합니다.", checks: ["repr(value)와 bool(value)를 비교합니다.", "허용 boolean vocabulary를 확인합니다.", "대소문자와 공백을 정규화할지 결정합니다."], fix: "허용 문자열을 명시적 mapping으로 parse하고 unknown은 오류로 처리합니다.", prevention: "true·false·빈 값·0·yes 등 지원·비지원 입력을 계약 테스트로 고정합니다." },
      ],
    },
    {
      id: "header-schema-dictreader",
      title: "header는 편의 라벨이 아니라 행을 해석하는 schema의 입구입니다",
      lead: "DictReader는 첫 행을 fieldnames로 사용하지만 그 이름이 올바르고 유일하며 기대 schema와 맞는지는 애플리케이션이 검증해야 합니다.",
      explanations: [
        "원본 ex05_file_dict.py의 DictWriter는 name·age·addr fieldnames 순서로 header를 쓰고 dict key 입력 순서와 무관하게 그 열 순서로 record를 직렬화합니다. DictReader는 header를 key로 사용해 각 row를 dict로 반환합니다. age도 '24' 문자열입니다.",
        "reader.fieldnames를 읽고 required field 누락, 허용하지 않은 extra field, 빈 header, duplicate header를 검사합니다. duplicate 이름이 있으면 dict에서 앞 column value가 덮여 data를 잃을 수 있습니다. trim·lower로 header를 정규화한다면 서로 다른 원본 이름이 같은 이름으로 충돌하는지도 검사합니다.",
        "행에 field가 header보다 많으면 DictReader는 기본 restkey=None 아래 extra value list를 둘 수 있고, 부족하면 누락 key value가 restval 기본 None이 됩니다. 이를 정상 빈 문자열과 혼동하지 않습니다. restkey='__extra__', restval sentinel을 지정해 schema mismatch를 명시적으로 탐지할 수 있습니다.",
        "DictWriter는 fieldnames 순서로 쓰며 input dict에 예상 밖 key가 있으면 extrasaction 기본 'raise'가 오류를 냅니다. extrasaction='ignore'는 data를 조용히 버릴 수 있으므로 명시적인 projection이 더 안전합니다. 누락 key는 restval로 쓰이고 None은 csv.writer에서 빈 문자열이 되어 round-trip이 되지 않습니다.",
      ],
      concepts: [
        { term: "header schema", definition: "각 column의 이름·순서·필수 여부·type·의미를 정하는 CSV 계약입니다.", detail: ["header 문자열만으로 type과 범위가 자동 검증되지는 않습니다.", "version 변화와 backward compatibility 정책이 필요합니다."] },
        { term: "DictReader", definition: "fieldnames와 각 row field를 key-value mapping으로 연결하는 streaming reader입니다.", detail: ["첫 row를 header로 사용할 수 있습니다.", "value는 일반적으로 str이고 누락 field는 None이 될 수 있습니다.", "fieldnames와 line_num을 진단에 사용할 수 있습니다."] },
        { term: "DictWriter", definition: "fieldnames 순서에 따라 mapping을 CSV row로 직렬화하는 writer입니다.", detail: ["writeheader로 header를 씁니다.", "unexpected key와 missing key 정책을 확인합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "일부 row에서 extra column이 사라지거나 None key 아래 list로 들어간다.", likelyCause: "data row의 field 수가 header보다 많지만 schema mismatch를 검사하지 않았습니다.", checks: ["row.keys와 row.get(None)을 확인합니다.", "reader.fieldnames 길이와 실제 field 수를 비교합니다.", "quoted comma를 잘못 생성한 생산자 문제인지 봅니다."], fix: "restkey에 명시 이름을 주고 extra가 있으면 reject하거나 versioned 확장 규칙으로 처리합니다.", prevention: "열 부족·초과·duplicate header·빈 header fixture를 schema 검증에 포함합니다." },
        { symptom: "두 개의 같은 header 열 중 한쪽 값이 DictReader 결과에서 보이지 않는다.", likelyCause: "dict key가 중복돼 같은 이름의 뒤 column이 앞 값을 덮었습니다.", checks: ["reader.fieldnames의 길이와 set 길이를 비교합니다.", "원본 header row repr을 보존해 확인합니다.", "정규화 전·후 이름 충돌을 검사합니다."], fix: "duplicate header를 파일 수준 오류로 거부하고 생산자 schema를 수정합니다.", prevention: "publish 전 header uniqueness를 검증하고 schema version test를 둡니다." },
      ],
    },
    {
      id: "streaming-transform-pipeline",
      title: "한 행씩 parse→validate→transform→write하고 실패 행을 별도 결과로 남깁니다",
      lead: "reader를 list로 바꾸지 않으면 큰 파일도 제한된 메모리로 처리할 수 있고 각 행의 성공·실패를 즉시 기록할 수 있습니다.",
      explanations: [
        "원본 ex04는 input과 output을 동시에 열고 reader를 for로 순회하며 각 행 점수를 int로 변환해 total·average를 붙입니다. 이 구조는 이미 streaming transform의 핵심입니다. 입력 전체와 결과 전체를 list에 저장하지 않아 현재 row와 작은 계산 상태만 메모리에 둡니다.",
        "파이프라인 책임을 parse, validate, transform, serialize로 나눕니다. parse는 text를 type으로 바꾸고, validate는 범위와 관계를 확인하고, transform은 total·average 같은 새 값을 만들고, serialize는 출력 schema의 text로 바꿉니다. 한 함수에 index 숫자와 broad except를 몰아넣으면 어느 단계가 실패했는지 사라집니다.",
        "실패 정책은 data 중요도에 따라 정합니다. 하나라도 틀리면 전체 publish를 중단하는 fail-fast, 정상 행은 처리하고 실패 행을 rejects CSV에 남기는 quarantine, 명시적 통계와 경고 아래 skip이 있습니다. silent skip은 source row 수와 output row 수가 달라져도 원인을 찾을 수 없어 피합니다.",
        "reader.line_num은 진단에 유용하지만 multiline field에서는 물리 line의 끝 위치입니다. business id, source file id, record sequence를 함께 사용합니다. 오류 메시지에는 field 이름과 reason code를 넣고 untrusted 전체 row·개인정보·formula 문자열을 그대로 운영 로그에 남기지 않습니다.",
      ],
      concepts: [
        { term: "transformation pipeline", definition: "입력 record를 parse·validate·transform·serialize 단계로 흘려 새 schema record를 만드는 처리 구조입니다.", detail: ["각 단계의 계약과 오류를 독립 테스트합니다.", "streaming sink와 결합해 memory 사용을 제한합니다."] },
        { term: "quarantine", definition: "유효하지 않은 row를 정상 output과 분리해 reason과 제한된 식별정보로 보존하는 실패 처리 정책입니다.", detail: ["재처리와 생산자 품질 개선에 사용합니다.", "민감 data와 formula payload의 노출을 제한합니다."] },
      ],
      codeExamples: [
        {
          id: "validated-streaming-transform",
          title: "문자열 점수 변환·실패 행 격리·formula-safe export",
          language: "python",
          filename: "csv_transform.py",
          purpose: "원본 성적 변환을 header 검증, 숫자 오류 행, 정확한 평균 text와 spreadsheet export 안전 경계로 확장합니다.",
          code: "import csv\nfrom io import StringIO\n\nsource_text = \"\"\"id,name,kor,eng,math\n1,Alice,90,80,70\n2,Bob,90,oops,70\n3,=2+3,100,100,100\n\"\"\"\n\ndef parse_score(row, field):\n    text = row[field].strip()\n    try:\n        value = int(text)\n    except ValueError as error:\n        raise ValueError(f\"{field}={text!r} is not integer\") from error\n    if not 0 <= value <= 100:\n        raise ValueError(f\"{field}={value} is out of range\")\n    return value\n\ndef spreadsheet_safe(text):\n    trimmed = text.lstrip()\n    return \"'\" + text if trimmed.startswith((\"=\", \"+\", \"-\", \"@\")) else text\n\nsource = StringIO(source_text, newline=\"\")\ntarget = StringIO(newline=\"\")\nreader = csv.DictReader(source)\nexpected = [\"id\", \"name\", \"kor\", \"eng\", \"math\"]\nif reader.fieldnames != expected:\n    raise ValueError(f\"unexpected header: {reader.fieldnames}\")\n\nwriter = csv.DictWriter(\n    target,\n    fieldnames=[\"id\", \"name\", \"total\", \"average\"],\n    lineterminator=\"\\n\",\n)\nwriter.writeheader()\n\nfor row in reader:\n    try:\n        scores = [parse_score(row, field) for field in (\"kor\", \"eng\", \"math\")]\n    except ValueError as error:\n        print(f\"rejected line={reader.line_num} id={row['id']} reason={error}\")\n        continue\n    total = sum(scores)\n    writer.writerow({\n        \"id\": row[\"id\"],\n        \"name\": spreadsheet_safe(row[\"name\"]),\n        \"total\": str(total),\n        \"average\": f\"{total / len(scores):.2f}\",\n    })\n    print(f\"accepted line={reader.line_num} id={row['id']} total={total}\")\n\nprint(\"--- output ---\")\nprint(target.getvalue(), end=\"\")",
          walkthrough: [
            { lines: "1-8", explanation: "정상·숫자 오류·formula 시작 name 세 행을 가진 합성 input을 준비합니다." },
            { lines: "10-18", explanation: "field text를 strip하고 int로 parse한 뒤 0~100 범위를 검사합니다. 변환 원인을 보존한 ValueError를 다시 냅니다." },
            { lines: "20-22", explanation: "untrusted text의 leading whitespace 뒤 첫 문자가 =,+,-,@면 spreadsheet export에서 apostrophe를 앞에 붙입니다." },
            { lines: "24-29", explanation: "newline='' StringIO, DictReader와 정확한 header 순서 검증으로 file 없이도 같은 pipeline을 테스트합니다." },
            { lines: "31-36", explanation: "결정적인 LF 출력과 id·name·total·average output schema를 정하고 header를 씁니다." },
            { lines: "38-44", explanation: "한 row씩 세 점수를 parse하며 오류 행은 reason을 출력하고 continue합니다. reader 전체를 list로 만들지 않습니다." },
            { lines: "45-51", explanation: "정상 행만 total과 소수 둘째 자리 average text를 만들어 즉시 writer에 전달하고 처리 결과를 기록합니다." },
            { lines: "53-54", explanation: "최종 CSV text를 출력해 reject 행이 없고 formula 시작 name이 완화됐음을 확인합니다." },
          ],
          run: { environment: ["Python 3.11 이상", "csv_transform.py를 저장"], command: "python csv_transform.py" },
          output: { value: "accepted line=2 id=1 total=240\nrejected line=3 id=2 reason=eng='oops' is not integer\naccepted line=4 id=3 total=300\n--- output ---\nid,name,total,average\n1,Alice,240,80.00\n3,'=2+3,300,100.00", explanation: ["Bob 행은 eng parser에서 실패해 output에 쓰이지 않고 line·id·field reason이 남습니다.", "Alice와 세 번째 행은 각각 240·300 total과 고정 두 자리 average를 가집니다.", "=로 시작한 이름은 CSV quoting이 아니라 export policy에 의해 apostrophe가 추가됩니다."] },
          experiments: [
            { change: "Bob의 eng을 101로 바꿉니다.", prediction: "int parse는 성공하지만 0~100 validation에서 out of range로 reject됩니다.", result: "parse 성공과 domain validation 실패를 다른 reason으로 구분합니다." },
            { change: "spreadsheet_safe를 제거합니다.", prediction: "CSV에는 =2+3이 그대로 저장되고 spreadsheet에서 formula로 해석될 수 있습니다.", result: "csv.writer quoting만으로 formula injection을 막을 수 없음을 확인합니다." },
          ],
          sourceRefs: ["py-csv-rows", "py-csv-dicts", "py-day05-csv-note"],
        },
      ],
      diagnostics: [
        { symptom: "잘못된 숫자 한 행 뒤 output이 일부만 생겼는데 작업은 성공처럼 보인다.", likelyCause: "broad except로 오류를 삼키거나 직접 target에 streaming write한 뒤 성공·실패 count와 publish 상태를 검증하지 않았습니다.", checks: ["input·accepted·rejected·written count를 비교합니다.", "마지막 오류와 target 수정 시간을 확인합니다.", "임시 파일인지 최종 target인지 구분합니다."], fix: "명시적 fail-fast 또는 quarantine 정책과 count invariant를 적용하고 최종 publish는 atomic output 단계에서만 수행합니다.", prevention: "중간 행 오류 fault injection과 input=accepted+rejected invariant 테스트를 둡니다." },
      ],
      expertNotes: ["Decimal 평균과 rounding mode가 업무 규칙이면 float format으로 대체하지 않습니다. 내부 numeric 계산과 output text formatting을 별도 단계로 둡니다."],
    },
    {
      id: "streaming-scale-observability",
      title: "streaming은 메모리를 줄이지만 부분 결과·재처리·관측성 책임을 만듭니다",
      lead: "reader를 순회하는 동안 output도 쓰면 큰 파일을 처리할 수 있지만 뒤 행 실패 전에 앞 행이 이미 기록될 수 있습니다.",
      explanations: [
        "list(reader)는 모든 row와 모든 field 문자열을 메모리에 올립니다. 수백 MB input에서 process memory가 훨씬 커질 수 있습니다. for row in reader로 현재 row만 유지하고 output writer·reject writer·집계 counter로 바로 보냅니다. 단, grouped aggregate나 전체 정렬이 필요하면 외부 정렬·database·chunk strategy가 필요합니다.",
        "streaming pipeline의 기본 metric은 physical bytes, logical row count, accepted, rejected, written, elapsed time입니다. input rows == accepted + rejected 같은 invariant를 검사합니다. header와 blank row를 count에 포함할지 명시하고 quoted multiline 때문에 line_num을 row count로 대신하지 않습니다.",
        "재시도할 때 같은 output을 중복 append하지 않도록 run id와 output file version을 정합니다. 입력 file checksum·schema version·code version을 metadata로 남기면 어느 변환이 결과를 만들었는지 추적할 수 있습니다. 민감 row 원문은 metric label이나 일반 로그에 넣지 않습니다.",
        "csv module은 field size limit을 가질 수 있고 매우 큰 단일 field가 memory를 압박할 수 있습니다. input file byte 제한, field length, row 수, processing timeout을 둡니다. compression bomb·untrusted upload는 압축 해제 비율과 저장 quota도 경계에서 검사합니다.",
      ],
      concepts: [
        { term: "streaming backpressure", definition: "producer가 consumer·storage보다 빠를 때 memory 무한 증가를 막기 위해 처리 속도나 buffer를 제어하는 원칙입니다.", detail: ["동기 file reader/writer는 한 row 처리 구조로 자연스럽게 제한될 수 있습니다.", "queue·async pipeline에서는 bounded buffer와 취소가 필요합니다."] },
        { term: "count invariant", definition: "처리 row 분류와 출력 수 사이에 항상 성립해야 하는 관계입니다.", detail: ["accepted+rejected=input 같은 관계를 검증합니다.", "정책상 dedup·filter가 있으면 그 분류를 별도 count로 추가합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "대용량 CSV에서 memory가 급증하거나 process가 종료된다.", likelyCause: "list(reader), list(DictReader), 전체 output 누적 또는 거대한 field를 제한 없이 materialize했습니다.", checks: ["peak memory와 input byte·row·최대 field 길이를 측정합니다.", "list·read·readlines 사용을 찾습니다.", "reject data와 output도 memory에 쌓는지 봅니다."], fix: "reader→validator→writer를 row 단위로 연결하고 size limit과 bounded buffer를 적용합니다.", prevention: "제한 근처·초과 크기, 거대한 단일 quoted field, multiline record fixture로 자원 테스트를 수행합니다." },
      ],
    },
    {
      id: "spreadsheet-formula-injection",
      title: "CSV text를 spreadsheet가 formula로 실행할 수 있는 경계를 방어합니다",
      lead: "CSV 자체는 text지만 Excel·LibreOffice 같은 소비자가 =,+,-,@로 시작하는 cell을 formula로 해석하면 untrusted data가 실행 의미를 얻습니다.",
      explanations: [
        "사용자 이름이나 comment가 =HYPERLINK(...), +CMD 같은 문자열로 시작하면 csv.writer는 그것을 올바른 CSV field로 보존할 뿐 안전한 text로 강제하지 않습니다. field를 double quote로 감싸는 CSV quoting도 spreadsheet formula 해석을 중지하지 않을 수 있습니다. 형식 정확성과 소비자 보안은 별도 문제입니다.",
        "정책은 field 의미별로 적용합니다. numeric field는 parser가 실제 숫자 범위만 허용하고 canonical 숫자 text로 다시 씁니다. untrusted free text가 spreadsheet로 export될 때 leading whitespace·tab 뒤 위험 prefix까지 검사해 reject하거나 apostrophe를 붙이거나, XLSX text cell type을 명시하는 방식 중 소비 도구와 합의합니다.",
        "apostrophe prefix는 spreadsheet에서 text로 보이게 하는 흔한 완화지만 다른 CSV consumer에는 실제 apostrophe data가 됩니다. 내부 canonical data를 변형하지 말고 spreadsheet export 전용 view에서만 적용하며 reversible policy와 사용자 안내를 둡니다. 모든 spreadsheet와 버전에서 동일하다고 무검증 가정하지 않습니다.",
        "formula injection 탐지 로그에 원문 formula 전체를 남기면 공격 payload와 개인정보가 로그·dashboard로 전파됩니다. field name, row identifier, reason code와 hash처럼 최소 정보만 기록하고 원본은 접근 제한 quarantine에 보관합니다.",
      ],
      concepts: [
        { term: "CSV formula injection", definition: "untrusted CSV cell text를 spreadsheet가 formula로 해석해 링크·외부 참조·데이터 노출 등 의도하지 않은 동작을 만드는 위험입니다.", detail: ["csv quoting만으로 해결되지 않습니다.", "spreadsheet로 여는 export 경계에서 위협이 생깁니다.", "field type별 validation과 소비자별 완화가 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "CSV를 text editor에서는 정상으로 보지만 spreadsheet에서 cell이 계산식이나 링크로 실행된다.", likelyCause: "untrusted text가 formula prefix로 시작하고 export 단계가 text cell 정책을 적용하지 않았습니다.", checks: ["첫 non-whitespace 문자가 =,+,-,@ 또는 제어 문자인지 확인합니다.", "해당 field가 numeric인지 free text인지 schema를 봅니다.", "실제 지원 spreadsheet 버전에서 격리 fixture를 엽니다."], fix: "numeric은 엄격 parse 후 canonicalize하고 free text는 reject·apostrophe prefix·typed XLSX 중 검증된 export 정책을 적용합니다.", prevention: "위험 prefix, leading whitespace·tab, quoted field를 포함한 spreadsheet security regression test를 둡니다." },
      ],
      expertNotes: ["위험한 formula를 생성해 외부 연결을 실제 실행하는 테스트는 격리 환경과 무해한 fixture로 제한합니다. production data나 실제 credential을 사용하지 않습니다."],
    },
    {
      id: "atomic-output-publish",
      title: "완성된 임시 CSV만 target 이름으로 원자적으로 교체합니다",
      lead: "target을 w로 직접 열면 header와 일부 정상 행을 쓴 뒤 오류가 나도 불완전 파일이 최종 결과처럼 남습니다.",
      explanations: [
        "입력과 다른 같은 디렉터리의 임시 파일을 만들고 header·정상 row를 모두 쓴 뒤 flush하고 필요시 os.fsync합니다. 파일을 닫은 후 schema·row count·재읽기 검증을 통과하면 os.replace(temp, target)로 공개합니다. 실패하면 temp를 정리하고 기존 target은 그대로 둡니다.",
        "임시 파일은 target과 같은 file system에 있어야 atomic rename 가능성이 높습니다. tempfile.NamedTemporaryFile 또는 mkstemp로 충돌·symlink 위험을 줄이고 권한을 설정합니다. Windows에서는 열린 임시 파일 교체 제약이 있으므로 with를 빠져나와 닫은 뒤 replace합니다.",
        "os.replace는 여러 writer의 lost update를 해결하지 않습니다. 둘 다 같은 이전 input을 읽고 각각 publish하면 마지막 writer가 이깁니다. single writer, file lock, version compare, orchestration job id 또는 database transaction으로 동시성 정책을 추가합니다.",
        "fsync가 성공해도 directory entry durability와 network file system 의미는 플랫폼마다 다릅니다. 중요한 금융 data는 실제 배포 filesystem에서 crash consistency를 검증합니다. 학습 예제는 기존 완성본 또는 새 완성본만 보이게 하는 핵심 패턴을 먼저 익힙니다.",
      ],
      concepts: [
        { term: "atomic publish", definition: "완성·검증된 임시 산출물을 target 이름으로 한 번에 교체해 부분 파일 노출을 줄이는 방식입니다.", detail: ["write와 publish를 분리합니다.", "동일 file system 조건과 플랫폼 semantics를 확인합니다.", "동시 writer 조정은 별도입니다."] },
        { term: "durability", definition: "성공으로 보고한 data가 process·OS·전원 장애 뒤에도 저장 매체에 남는 정도에 대한 보장입니다.", detail: ["flush는 Python buffer, fsync는 OS에 저장 요청을 합니다.", "filesystem과 hardware 보장은 별도로 검증합니다."] },
      ],
      codeExamples: [
        {
          id: "atomic-bom-csv-publish",
          title: "UTF-8 BOM CSV를 임시 파일에 쓴 뒤 교체",
          language: "python",
          filename: "atomic_csv.py",
          purpose: "기존 target을 직접 truncate하지 않고 완성된 BOM output을 publish·재읽기·정리하는 순서를 재현합니다.",
          code: "import codecs\nimport csv\nimport os\nfrom pathlib import Path\nfrom tempfile import TemporaryDirectory\n\nwith TemporaryDirectory() as temp_dir:\n    target = Path(temp_dir) / \"report.csv\"\n    temporary = target.with_suffix(\".csv.tmp\")\n    target.write_text(\"old data\\n\", encoding=\"utf-8\")\n\n    try:\n        with temporary.open(\"w\", encoding=\"utf-8-sig\", newline=\"\") as file:\n            writer = csv.DictWriter(\n                file,\n                fieldnames=[\"id\", \"name\"],\n                lineterminator=\"\\n\",\n            )\n            writer.writeheader()\n            writer.writerows([\n                {\"id\": \"1\", \"name\": \"둘리\"},\n                {\"id\": \"2\", \"name\": \"도우너\"},\n            ])\n            file.flush()\n            os.fsync(file.fileno())\n        os.replace(temporary, target)\n    finally:\n        temporary.unlink(missing_ok=True)\n\n    raw = target.read_bytes()\n    print(\"published:\", target.exists(), \"temp exists:\", temporary.exists())\n    print(\"utf8 bom:\", raw.startswith(codecs.BOM_UTF8))\n    with target.open(\"r\", encoding=\"utf-8-sig\", newline=\"\") as file:\n        print(\"rows:\", list(csv.reader(file)))",
          walkthrough: [
            { lines: "1-5", explanation: "CSV·BOM·atomic replace와 격리 임시 디렉터리에 필요한 표준 모듈만 가져옵니다." },
            { lines: "7-10", explanation: "기존 target을 만들어 실제 교체를 증명하고 같은 디렉터리 temp 이름을 정합니다." },
            { lines: "12-22", explanation: "utf-8-sig와 newline=''로 temp에 header·두 row를 완전히 쓰고 LF terminator를 고정합니다." },
            { lines: "23-24", explanation: "Python buffer를 flush한 뒤 fsync하고 with를 나와 file handle을 닫습니다." },
            { lines: "25", explanation: "닫힌 완성 temp를 target 이름으로 교체합니다. 이 줄 전 실패에서는 기존 old target이 유지됩니다." },
            { lines: "26-27", explanation: "성공·실패 모두 남은 temp를 정리하되 이미 replace돼 없어도 허용합니다." },
            { lines: "29-33", explanation: "target 존재, temp 제거, BOM bytes와 utf-8-sig 재읽기 row를 확인합니다." },
          ],
          run: { environment: ["Python 3.11 이상", "atomic_csv.py를 저장"], command: "python atomic_csv.py" },
          output: { value: "published: True temp exists: False\nutf8 bom: True\nrows: [['id', 'name'], ['1', '둘리'], ['2', '도우너']]", explanation: ["기존 old data target이 완성된 report로 교체됐습니다.", "BOM은 raw bytes에는 있지만 utf-8-sig로 읽은 첫 header에는 남지 않습니다.", "replace 뒤 temp path는 없고 재읽은 schema와 두 row가 정확합니다."] },
          experiments: [
            { change: "os.replace 직전에 raise RuntimeError를 넣습니다.", prediction: "finally가 temp를 지우고 기존 target의 old data는 유지됩니다.", result: "write failure와 publish를 분리해 불완전 report가 target이 되지 않습니다." },
            { change: "output encoding을 utf-8로 바꿉니다.", prediction: "row 내용은 같지만 utf8 bom은 False입니다.", result: "BOM 유무가 consumer 계약에 따른 명시적 선택임을 확인합니다." },
          ],
          sourceRefs: ["py-csv-dicts", "py-day05-csv-note"],
        },
      ],
      diagnostics: [
        { symptom: "변환 중 예외 뒤 최종 CSV에 header와 앞부분 row만 남는다.", likelyCause: "최종 target을 w로 직접 열어 streaming 도중 실패했고 publish 단계가 분리되지 않았습니다.", checks: ["target·temp 수정 시간과 row count를 확인합니다.", "예외가 parse·write·flush·replace 중 어디서 났는지 구분합니다.", "기존 완성본 backup이 있는지 봅니다."], fix: "같은 디렉터리 temp에 완성·검증 후 os.replace하고 실패 시 기존 target을 보존합니다.", prevention: "중간 row·disk write·replace 직전 fault injection과 recovery test를 둡니다." },
      ],
      comparisons: [
        { title: "CSV 변환 오류를 어떻게 publish할까요?", options: [
          { name: "fail-fast + atomic replace", chooseWhen: "한 행 오류도 전체 output을 무효로 만드는 엄격 report일 때", avoidWhen: "정상 행을 반드시 부분 처리하고 rejects workflow가 합의됐을 때", tradeoffs: ["완전한 한 version만 공개합니다.", "한 오류로 전체 run이 실패합니다."] },
          { name: "quarantine + atomic output", chooseWhen: "정상 행과 reject 행을 모두 추적해 별도 산출물로 publish할 때", avoidWhen: "누락 한 건도 허용되지 않는 정산·규제 output일 때", tradeoffs: ["data 품질을 관찰하며 계속 처리합니다.", "정상·reject count와 두 파일의 일관성 계약이 필요합니다."] },
          { name: "직접 target streaming", chooseWhen: "손실돼도 다시 만들 수 있는 명시적 임시 산출물일 때", avoidWhen: "사용자가 최종 파일로 소비하거나 이전 완성본을 보존해야 할 때", tradeoffs: ["구현이 단순합니다.", "부분 파일 노출과 truncate 위험이 큽니다."] },
        ] },
      ],
      expertNotes: ["target과 input이 같은 path면 w open으로 입력을 먼저 지울 수 있습니다. in-place CSV 갱신 대신 별도 temp를 읽기와 쓰기로 분리하고 마지막에 교체합니다."],
    },
    {
      id: "pipeline-design-checklist",
      title: "CSV 파이프라인은 format·schema·failure·security·publish 다섯 계약으로 검토합니다",
      lead: "정상 sample 한 개가 변환됐다는 사실만으로 운영 가능한 CSV 처리라고 결론 내리지 않습니다.",
      explanations: [
        "format 계약에는 encoding·BOM·newline·delimiter·quote·lineterminator가 들어갑니다. schema 계약에는 header 이름·유일성·순서·필수/추가 field·type·범위·version이 들어갑니다. 같은 .csv 확장자라도 이 계약이 다르면 호환되지 않습니다.",
        "failure 계약은 file 수준 중단과 row 수준 quarantine, 오류 reason, 재처리, count invariant를 정합니다. security 계약은 최대 크기, formula injection, 민감 로그, path와 권한, untrusted file을 다룹니다. publish 계약은 temp·validation·replace·동시 writer·durability·rollback을 정합니다.",
        "테스트는 빈 파일, header만, BOM 유무, CRLF·LF, quoted comma·quote·newline, 빈 field, field 부족·초과, duplicate header, 잘못된 숫자·범위, 거대한 field, formula prefix, 중간 failure를 포함합니다. writer 결과를 같은 reader로 round-trip해 semantic row가 유지되는지도 확인합니다.",
        "전문가가 CSV를 피해야 할 때도 있습니다. nested data·명확한 type·schema evolution·transaction이 중요하면 JSON Lines, Parquet, database 또는 typed API가 더 맞을 수 있습니다. CSV를 선택했다면 단순함의 대가로 schema와 type을 애플리케이션이 책임집니다.",
      ],
      concepts: [
        { term: "round-trip test", definition: "내부 record를 writer로 직렬화하고 reader로 다시 읽어 의미 있는 field가 계약대로 복원되는지 검사하는 테스트입니다.", detail: ["comma·quote·newline·Unicode·빈 값 경계를 포함합니다.", "type은 schema parser를 거쳐 비교해야 합니다."] },
        { term: "schema versioning", definition: "column 추가·삭제·이름·의미 변경을 생산자와 소비자가 추적할 수 있게 version과 호환 정책을 두는 방식입니다.", detail: ["파일명·metadata·별도 column 등으로 표현할 수 있습니다.", "unknown version은 조용히 잘못 해석하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [],
      expertNotes: ["csv.Sniffer는 작은 sample을 기반으로 한 heuristic이므로 hostile·불규칙 input의 신뢰 경계로 사용하지 않습니다. 가능하면 생산자 명세의 dialect를 명시합니다."],
    },
  ],
  lab: {
    title: "성적 CSV 검증·변환·reject·atomic publish",
    scenario: "UTF-8 BOM 유무와 quoted 이름이 섞인 대형 성적 CSV를 한 행씩 읽어 점수를 검증하고 total·average report를 만들며, 잘못된 행은 reason code와 함께 별도 reject CSV로 격리합니다.",
    setup: ["grade_pipeline.py와 tests 폴더를 만듭니다.", "TemporaryDirectory에 input·output·reject path를 둡니다.", "합성 data만 사용하고 comma·newline·formula prefix name, 숫자 오류, 범위 밖 점수, field 부족·초과 row를 포함합니다."],
    steps: [
      "input을 encoding='utf-8-sig', newline=''로 열고 DictReader.fieldnames의 BOM 제거·중복·필수·추가 field를 검증합니다.",
      "각 row의 id·name·세 점수를 parse하고 int 0~100, id uniqueness, 빈 이름 정책을 검증합니다.",
      "정상 row는 total과 명시한 Decimal rounding average를 가진 내부 record로 변환합니다.",
      "spreadsheet export text field에는 검증된 formula injection 정책을 적용하고 canonical 내부 data는 보존합니다.",
      "실패 row는 source id·record sequence·reader.line_num·field·reason code만 reject writer에 기록하고 원문 전체 로그는 피합니다.",
      "normal temp와 reject temp를 newline='', 고정 fieldnames·lineterminator로 streaming write합니다.",
      "input == accepted + rejected와 written == accepted invariant, output header·재읽기·BOM 정책을 검증합니다.",
      "모든 검증이 성공할 때만 두 temp를 publish합니다. 두 파일을 하나의 transaction으로 보장할 수 없는 한계를 문서화하고 manifest/디렉터리 version 방식도 검토합니다.",
      "중간 numeric 오류, disk write 오류, replace 직전 오류, 동시 writer를 fault injection으로 테스트합니다.",
    ],
    expectedResult: ["정상 row는 제한된 메모리로 report에 기록되고 잘못된 row는 이유와 함께 reject에 남습니다.", "comma·embedded newline·한글·BOM 유무가 schema와 field를 깨지 않고 왕복됩니다.", "formula prefix text가 spreadsheet export 정책에 따라 안전하게 처리됩니다.", "중간 실패에서는 기존 완성 output이 유지되고 임시 파일이 정리됩니다.", "accepted·rejected·written metric과 manifest로 변환 결과를 추적할 수 있습니다."],
    cleanup: ["TemporaryDirectory가 모든 합성 CSV를 제거합니다.", "실패 시 남은 temp를 recovery test에서 확인한 뒤 제한된 기준 디렉터리 안에서만 정리합니다."],
    extensions: ["gzip.open text mode와 같은 parser 계약으로 compressed CSV를 streaming 처리합니다.", "schema version 1·2 adapter를 분리합니다.", "reject를 수정해 재투입하는 idempotent replay 도구를 만듭니다.", "Parquet typed schema로 바꿀 때 장단점과 migration plan을 작성합니다."],
  },
  exercises: [
    {
      difficulty: "따라하기",
      prompt: "원본 성적 CSV를 header가 있는 DictReader 파이프라인으로 다시 작성하세요.",
      requirements: ["newline=''와 encoding을 읽기·쓰기에 명시합니다.", "id·name·kor·eng·math·gender header를 쓰고 검증합니다.", "모든 입력 value가 str임을 한 행에서 확인합니다.", "세 점수를 int로 바꾸고 total·average를 추가합니다.", "출력 CSV를 다시 읽어 header와 다섯 행을 검증합니다."],
      hints: ["writer에 int를 주어도 CSV에는 text로 저장됩니다.", "정확한 평균 정책을 round·절삭·Decimal 중 먼저 정하세요."],
      expectedOutcome: "원본 다섯 학생의 total 260·250·270·235·230과 정책에 맞는 평균이 schema가 있는 CSV로 재현됩니다.",
      solutionOutline: ["header schema를 먼저 정의합니다.", "parse_score를 한 함수로 만듭니다.", "한 행씩 transform해 output에 씁니다.", "round-trip reader로 semantic 결과를 단언합니다."],
    },
    {
      difficulty: "응용",
      prompt: "회원 CSV의 age를 수정하되 잘못된 행을 reject하고 원본은 보존하세요.",
      requirements: ["DictReader·DictWriter와 rd.fieldnames를 사용합니다.", "name·age·addr 필수·duplicate header를 검사합니다.", "age를 0~150 int로 parse하고 target name의 나이만 바꿉니다.", "field 부족·초과·숫자 오류를 reject CSV로 보냅니다.", "정상 output은 temp 후 replace하고 source와 다른 path에 씁니다.", "BOM 유무와 한글 주소를 테스트합니다."],
      hints: ["row['age']=7은 memory dict 변경이고 writer가 text로 직렬화합니다.", "input과 output을 같은 w path로 동시에 열지 마세요."],
      expectedOutcome: "정상 회원과 수정된 대상만 output에 있고 실패 row는 reason과 함께 추적되며 source 파일은 변하지 않습니다.",
      solutionOutline: ["schema validator를 먼저 실행합니다.", "parse·transform·serialize를 분리합니다.", "정상·reject count를 검사합니다.", "완성 temp만 publish합니다."],
    },
    {
      difficulty: "설계",
      prompt: "외부 파트너가 매일 올리는 수백 GB CSV ingestion 서비스를 설계하세요.",
      requirements: ["dialect·encoding·BOM·newline·schema version 계약을 정의합니다.", "streaming·bounded queue·field/file/row/time limit을 둡니다.", "formula injection·path·권한·malware·민감 로그 경계를 포함합니다.", "fail-fast와 quarantine 선택 기준, replay·idempotency·checksum을 설계합니다.", "atomic publish와 manifest, 여러 output의 transaction 한계를 다룹니다.", "동시 upload·중복 file·late arrival·schema drift 정책을 정합니다.", "정상·quoted multiline·duplicate header·거대 field·중간 crash·disk full·동시 writer 보안/복구 테스트를 최소 20개 작성합니다."],
      hints: ["CSV parser 성공과 business validation 성공을 분리하세요.", "원본 object storage 보존과 처리 version manifest를 고려하세요.", "전체 정렬·join이 필요하면 CSV streaming만으로 해결하려 하지 마세요."],
      expectedOutcome: "작은 csv.reader 예제를 data 품질·보안·운영 복구·관측성이 있는 ingestion architecture로 확장한 설계 문서와 test matrix가 완성됩니다.",
      solutionOutline: ["format과 schema registry를 정의합니다.", "ingest·validate·transform·publish stage를 분리합니다.", "각 stage의 retry와 idempotency key를 둡니다.", "metric·reject·manifest·retention을 설계합니다.", "fault injection과 disaster recovery 절차를 검증합니다."],
    },
  ],
  reviewQuestions: [
    { question: "CSV를 line.split(',')로 읽으면 안 되는 대표 이유는 무엇인가요?", answer: "quoted field 안의 comma·quote·newline을 delimiter나 record 끝으로 잘못 해석해 열과 행 구조를 깨기 때문입니다." },
    { question: "CSV file을 newline=''로 여는 이유는 무엇인가요?", answer: "text layer의 newline 변환과 csv module 처리가 중복되지 않게 하고 embedded newline과 record terminator를 parser가 직접 처리하게 하기 위해서입니다." },
    { question: "utf-8 BOM 파일을 encoding='utf-8'로 DictReader에 주면 어떤 문제가 생길 수 있나요?", answer: "첫 header key 앞에 \\ufeff가 남아 'id'가 아니라 '\\ufeffid'가 되어 schema 검증과 key 조회가 실패할 수 있습니다." },
    { question: "csv.reader가 읽은 '90'과 'False'의 type은 무엇인가요?", answer: "둘 다 str입니다. int와 bool 규칙을 schema parser로 명시적으로 적용해야 합니다." },
    { question: "bool('False')가 True인 이유와 올바른 처리법은 무엇인가요?", answer: "비어 있지 않은 문자열이라 True입니다. 허용 문자열 vocabulary를 mapping으로 parse하고 unknown을 오류 처리합니다." },
    { question: "DictReader에서 data row의 field가 header보다 많거나 적으면 어떻게 되나요?", answer: "extra 값은 기본적으로 None key 아래 list가 될 수 있고 누락 field는 None value가 됩니다. restkey·restval과 schema 검증으로 명시적으로 처리합니다." },
    { question: "reader.line_num은 항상 논리 CSV row 번호인가요?", answer: "아닙니다. parser가 소비한 물리 line 수이며 quoted multiline field 하나가 여러 line을 차지할 수 있습니다." },
    { question: "csv.writer의 quoting이 formula injection을 막나요?", answer: "아닙니다. spreadsheet가 quoted cell text도 formula로 해석할 수 있어 field validation 또는 export 전용 완화가 필요합니다." },
    { question: "streaming output에서 뒤 행 오류가 나면 왜 atomic publish가 필요한가요?", answer: "앞 정상 행은 이미 target에 기록됐을 수 있으므로 temp에 완성·검증한 뒤 replace해야 부분 파일이 최종 결과로 노출되지 않습니다." },
    { question: "os.replace만 사용하면 여러 writer의 lost update도 해결되나요?", answer: "아닙니다. 각 replace는 원자적일 수 있지만 마지막 writer가 앞 결과를 덮을 수 있어 lock·version·single writer 정책이 별도로 필요합니다." },
  ],
  completionChecklist: [
    "quoted comma·quote·multiline field를 csv module로 정확히 round-trip할 수 있다.",
    "newline='', utf-8과 utf-8-sig의 역할과 BOM header 문제를 설명할 수 있다.",
    "reader value가 str임을 확인하고 숫자·bool parser와 범위 검증을 작성할 수 있다.",
    "header 누락·추가·중복과 행 field 부족·초과를 reject할 수 있다.",
    "DictReader→validate→transform→DictWriter를 row 단위 streaming으로 연결할 수 있다.",
    "accepted·rejected·written count invariant와 제한된 오류 provenance를 기록할 수 있다.",
    "formula injection을 CSV quoting과 구분하고 export field별 완화 정책을 적용할 수 있다.",
    "임시 file·flush·fsync·close·os.replace·cleanup 순서를 구현할 수 있다.",
    "중간 실패·대용량·BOM·multiline·schema drift·동시 writer 테스트를 설계할 수 있다.",
  ],
  nextSessions: [],
  sources: [
    { id: "py-csv-rows", repository: "PYTHON-BASIC", path: "day05/ex04_file_csv.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day05/ex04_file_csv.py", usedFor: ["csv.writer·reader", "newline=''", "문자열 행", "두 파일 변환", "합계·평균"], evidence: "격리 임시 data 디렉터리에서 Python 3.13.9로 실행해 다섯 list row, total 260·250·270·235·230과 average 86.66·83.33·90.0·78.33·76.66인 csv_sample02.csv를 확인했습니다." },
    { id: "py-csv-dicts", repository: "PYTHON-BASIC", path: "day05/ex05_file_dict.py", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/day05/ex05_file_dict.py", usedFor: ["DictWriter·DictReader", "fieldnames·header", "append", "row 수정", "새 파일 저장"], evidence: "격리 실행에서 세 회원 write/read, 공실이 append, 장길산 age 17→7 변환과 name·age·addr header를 가진 csv_sample03·04 결과를 확인했습니다." },
    { id: "py-day05-csv-note", repository: "PYTHON-BASIC", path: "notes/day05_lambda_file_excel.md", publicUrl: "https://github.com/notetester/PYTHON-BASIC/blob/main/notes/day05_lambda_file_excel.md", usedFor: ["CSV 기본", "newline", "reader·writer", "DictReader·DictWriter", "두 파일 변환", "self-check"], evidence: "Day05 노트 CSV 4절과 Q2·Q5를 감사해 원본 흐름을 유지하고 BOM·schema·실패 행·streaming·formula injection·atomic output을 원본 공백으로 구분해 보강했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본은 정상 숫자 행만 처리하므로 숫자 변환 실패·범위 오류·reject provenance는 기술 보강입니다.",
      "UTF-8 BOM, duplicate/missing/extra header와 quoted multiline field는 원본 공백을 schema·format 경계로 보강했습니다.",
      "formula injection은 spreadsheet 소비 경계의 보안 보강이며 CSV quoting과 별도 정책으로 설명했습니다.",
      "원본은 별도 output을 직접 w로 쓰므로 임시 파일·fsync·os.replace·concurrent writer는 운영 안전성 보강입니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const dialectContractChapter: DetailedSession["chapters"][number] = {
  id: "dialect-contract-and-adversarial-records",
  title: "dialect를 파일 계약으로 고정하고 multiline·schema·spreadsheet 경계를 적대적으로 시험합니다",
  lead: "CSV는 단순한 comma split이 아니라 delimiter·quote·escape·newline·encoding이 함께 레코드를 결정하는 형식이므로 생산자와 소비자가 같은 dialect와 schema를 공유해야 합니다.",
  explanations: [
    "`csv.Dialect`는 delimiter, quotechar, doublequote, escapechar, skipinitialspace, lineterminator, quoting, strict를 이름 있는 계약으로 묶습니다. 기본 `excel`이 우연히 맞는지 기대하지 말고 거래처·버전별 dialect를 코드와 fixture에 고정합니다.",
    "quoted field 안에는 delimiter와 실제 newline이 들어갈 수 있습니다. 그래서 물리적 줄 수와 CSV record 수가 다르며 `readline()` 뒤 split하거나 한 줄씩 독립 parse하면 레코드를 끊습니다. text stream 전체를 `csv.reader`가 newline state와 함께 소비하게 합니다.",
    "파일은 `open(..., newline='', encoding='utf-8')`처럼 엽니다. newline=''은 csv 모듈이 quoted newline과 platform line ending을 직접 처리하게 하고, encoding은 bytes를 str로 바꾸는 별도 경계입니다. Excel 호환을 위해 utf-8-sig를 택한다면 BOM 정책을 양쪽에 기록합니다.",
    "`Sniffer`는 표본으로 dialect/header를 추정하는 heuristic이라 짧거나 편향된 데이터에서 틀릴 수 있습니다. 신뢰할 수 없는 업로드에 자동 확정값으로 쓰지 말고 제한된 후보 dialect의 보조 신호로 사용하며, 첫 N records를 schema와 함께 검증합니다.",
    "`DictReader`의 fieldnames는 business schema가 아닙니다. 중복 header, 공백·대소문자 차이, 빈 header, 빠진 열은 별도 검사하고, `restkey`로 초과 열을 포착하며 `restval`로 부족 열을 보이게 합니다. 값은 모두 기본적으로 str이므로 정수·날짜·enum을 명시적으로 변환합니다.",
    "streaming pipeline은 record 하나를 parse→validate→normalize→emit하고 성공·거부 개수와 `reader.line_num`을 관찰합니다. 전체 파일을 list로 만들지 않아도 되지만 atomic publish가 필요하면 같은 filesystem의 임시 파일에 쓰고 flush·fsync·replace 순서를 사용합니다.",
    "`QUOTE_ALL`이나 `QUOTE_MINIMAL`은 CSV 문법 escaping일 뿐 spreadsheet formula 실행을 막지 않습니다. 외부 값이 `=`, `+`, `-`, `@`, tab, carriage return으로 시작하면 정책에 따라 거부하거나 spreadsheet가 text로 해석하도록 neutralize하고 원본·표시값을 구분합니다.",
    "formula neutralization은 대상 spreadsheet와 import 설정에 따라 검증해야 합니다. 선행 apostrophe를 붙이는 방식도 데이터 자체를 바꾸므로 원본 시스템에는 typed value를 유지하고, 다운로드 전용 export view에서만 적용하며 보안 테스트로 실제 열기를 포함합니다.",
    "회귀 fixture에는 delimiter가 든 이름, double quote, CRLF와 LF, quoted multiline, empty와 missing, extra column, BOM, 매우 긴 field, 잘못 닫힌 quote, formula prefix를 넣습니다. 출력은 다시 같은 dialect로 읽어 typed normalized record와 비교해야 합니다.",
  ],
  concepts: [
    { term: "dialect contract", definition: "CSV 레코드를 해석하고 생성하는 delimiter·quote·escape·newline 규칙의 명시적 묶음입니다.", detail: ["생산자와 소비자가 함께 버전 관리합니다.", "샘플 추정값과 구분합니다."] },
    { term: "physical line versus record", definition: "파일의 개행으로 나뉜 물리 줄과 quoted newline을 포함할 수 있는 논리 CSV 행의 차이입니다.", detail: ["한 record가 여러 물리 줄일 수 있습니다.", "csv parser가 경계를 결정해야 합니다."] },
    { term: "schema gate", definition: "header·열 수·필수값·타입·범위를 emit 전에 검사하는 pipeline 경계입니다.", detail: ["DictReader만으로 완성되지 않습니다.", "오류 위치와 원본 record를 추적합니다."] },
  ],
  codeExamples: [
    {
      id: "python-csv-explicit-dialect-multiline",
      title: "semicolon dialect에서 quoted delimiter와 multiline field를 한 record로 읽습니다",
      language: "python",
      filename: "csv_dialect_contract.py",
      purpose: "물리 newline을 포함하는 field가 명시적 dialect와 newline='' stream에서 보존되는지 exact output으로 검증합니다.",
      code: "import csv\nimport io\n\nclass StudyDialect(csv.Dialect):\n    delimiter = ';'\n    quotechar = '\"'\n    doublequote = True\n    escapechar = None\n    skipinitialspace = False\n    lineterminator = '\\r\\n'\n    quoting = csv.QUOTE_MINIMAL\n    strict = True\n\ndata = 'name;note;score\\r\\n\"Kim;A\";\"line1\\nline2\";3.5\\r\\n'\nrows = list(csv.reader(io.StringIO(data, newline=''), dialect=StudyDialect))\nprint(f'rows={len(rows)}|header={rows[0]}')\nprint(f'name={rows[1][0]}|note_lines={rows[1][1].splitlines()}|score={rows[1][2]}')",
      walkthrough: [
        { lines: "1-2", explanation: "표준 csv parser와 메모리 text stream을 사용합니다." },
        { lines: "4-12", explanation: "semicolon, quote, CRLF와 strict parsing을 하나의 dialect class에 고정합니다." },
        { lines: "14-17", explanation: "delimiter와 newline을 포함한 field를 parse하고 record 수·field 경계를 출력합니다." },
      ],
      run: { environment: ["Python 3.11 이상", "표준 라이브러리만 사용"], command: "python csv_dialect_contract.py" },
      output: { value: "rows=2|header=['name', 'note', 'score']\nname=Kim;A|note_lines=['line1', 'line2']|score=3.5", explanation: ["quoted semicolon은 이름 안에 보존됩니다.", "두 물리 줄의 note가 한 logical record에 들어갑니다.", "score는 명시 변환 전이라 str입니다."] },
      experiments: [
        { change: "strict=False로 바꾸고 닫히지 않은 quote를 넣습니다.", prediction: "일부 malformed input이 오류 대신 예상 밖 record로 읽힐 수 있습니다.", result: "strict와 별도 schema validation을 모두 둡니다." },
        { change: "StringIO에서 newline 인자를 제거해 플랫폼 파일 처리와 비교합니다.", prediction: "메모리 예제는 같을 수 있지만 실제 파일의 CRLF·quoted newline에서 차이가 드러납니다.", result: "파일 fixture를 Windows와 CI에서 함께 검사합니다." },
        { change: "delimiter를 comma로 잘못 지정합니다.", prediction: "header 전체가 한 field가 되어 schema gate가 실패합니다.", result: "parse 성공과 schema 성공을 분리합니다." },
      ],
      sourceRefs: ["python-csv-dialect-025", "python-csv-reader-025", "rfc4180-025"],
    },
    {
      id: "python-csv-dict-schema-formula-boundary",
      title: "DictReader 초과열·타입 schema와 spreadsheet formula neutralization을 분리합니다",
      language: "python",
      filename: "csv_schema_export.py",
      purpose: "header 기반 record를 typed value로 검증하고 다운로드 view에서만 formula prefix를 중화해 다시 CSV로 기록합니다.",
      code: "import csv\nimport io\n\nsource = io.StringIO('name,score,note\\nKim,7,=2+2\\n', newline='')\nreader = csv.DictReader(source, restkey='__extra__', restval=None)\nrow = next(reader)\nissues = []\nif reader.fieldnames != ['name', 'score', 'note']:\n    issues.append('header')\nif row.get('__extra__'):\n    issues.append('extra')\ntry:\n    score = int(row['score'])\nexcept (TypeError, ValueError):\n    issues.append('score')\n    score = 0\n\ndef neutralize(value):\n    return \"'\" + value if value.lstrip()[:1] in ('=', '+', '-', '@', '\\t', '\\r') else value\n\nrecord = {'name': row['name'], 'score': score, 'note': neutralize(row['note'])}\nsink = io.StringIO(newline='')\nwriter = csv.DictWriter(sink, fieldnames=['name', 'score', 'note'], lineterminator='\\n', extrasaction='raise')\nwriter.writeheader()\nwriter.writerow(record)\nformula_neutralized = record['note'].startswith(chr(39))\nprint(f'fields={reader.fieldnames}|score_type={type(score).__name__}|issues={issues}')\nprint(f'formula_neutralized={formula_neutralized}|rows={sink.getvalue().splitlines()}')",
      walkthrough: [
        { lines: "1-6", explanation: "DictReader에 restkey·restval을 지정해 ragged row를 숨기지 않습니다." },
        { lines: "7-17", explanation: "header·초과열·정수 변환을 schema gate에서 검사하고 실패를 issues에 모읍니다." },
        { lines: "18-19", explanation: "spreadsheet 위험 prefix는 export 전용 함수에서 text로 중화합니다." },
        { lines: "21-28", explanation: "typed record를 고정 header·LF로 쓰고 field/type·보안 결과를 exact 출력합니다." },
      ],
      run: { environment: ["Python 3.11 이상", "표준 라이브러리만 사용"], command: "python csv_schema_export.py" },
      output: { value: "fields=['name', 'score', 'note']|score_type=int|issues=[]\nformula_neutralized=True|rows=['name,score,note', \"Kim,7,'=2+2\"]", explanation: ["score는 schema 변환 뒤 int입니다.", "formula prefix는 다운로드 view에서 apostrophe로 중화됩니다.", "quoting 설정만으로 formula 실행을 막았다고 주장하지 않습니다."] },
      experiments: [
        { change: "row 끝에 extra field를 추가합니다.", prediction: "restkey __extra__에 list가 생기고 issues에 extra가 들어갑니다.", result: "초과열이 조용히 유실되지 않습니다." },
        { change: "score를 seven으로 바꿉니다.", prediction: "ValueError를 catch해 score issue가 생깁니다.", result: "CSV parse와 domain type conversion을 분리합니다." },
        { change: "note를 `  =cmd`로 바꿉니다.", prediction: "lstrip 검사로 위험 prefix를 발견하고 원래 공백 앞에 apostrophe를 붙입니다.", result: "leading whitespace 우회 fixture를 추가합니다." },
      ],
      sourceRefs: ["python-csv-dictreader-025", "owasp-csv-injection-025", "python-io-text-025", "python-open-text-025"],
    },
  ],
  diagnostics: [
    { symptom: "CSV record 수가 파일 줄 수보다 적거나 많습니다.", likelyCause: "quoted multiline field를 물리 줄 단위로 split했거나 newline 처리를 parser 밖에서 바꿨습니다.", checks: ["raw bytes와 newline 종류를 확인합니다.", "reader.line_num과 logical record count를 각각 기록합니다.", "quoted newline fixture를 같은 dialect로 재현합니다."], fix: "newline='' text stream을 csv.reader에 직접 넘기고 record 단위로 처리합니다.", prevention: "CRLF·LF·quoted CRLF/LF를 포함한 golden fixture를 둡니다." },
    { symptom: "CSV를 정상적으로 열었는데 spreadsheet에서 셀이 명령이나 수식으로 평가됩니다.", likelyCause: "CSV quoting을 spreadsheet formula neutralization으로 오해했습니다.", checks: ["외부 string의 첫 유효 문자를 검사합니다.", "다운로드 파일을 지원 spreadsheet에서 실제로 엽니다.", "원본 값과 export view가 분리됐는지 봅니다."], fix: "정책에 따라 위험 prefix를 거부하거나 text로 중화하고 spreadsheet별 결과를 검증합니다.", prevention: "=,+,-,@,tab,CR와 leading whitespace payload를 보안 회귀 테스트에 포함합니다." },
  ],
};

(session.chapters as DetailedSession["chapters"]).push(dialectContractChapter);

(session.sources as DetailedSession["sources"]).push(
  { id: "python-csv-reader-025", repository: "Python Standard Library", path: "csv reader and writer objects", publicUrl: "https://docs.python.org/3/library/csv.html#reader-objects", usedFor: ["reader record model", "line_num", "quoting behavior"], evidence: "CSV reader가 logical records를 반환하고 dialect에 따라 field를 해석하는 공식 계약을 확인했습니다." },
  { id: "python-csv-dictreader-025", repository: "Python Standard Library", path: "csv.DictReader", publicUrl: "https://docs.python.org/3/library/csv.html#csv.DictReader", usedFor: ["fieldnames", "restkey", "restval", "ordered dictionaries"], evidence: "header mapping과 초과·부족 field 처리의 공식 API를 확인했습니다." },
  { id: "python-csv-dialect-025", repository: "Python Standard Library", path: "Dialects and Formatting Parameters", publicUrl: "https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters", usedFor: ["delimiter", "quotechar", "escapechar", "lineterminator", "strict"], evidence: "dialect 속성과 quoting 상수의 정확한 의미를 공식 문서로 확인했습니다." },
  { id: "python-io-text-025", repository: "Python Standard Library", path: "Text I/O", publicUrl: "https://docs.python.org/3/library/io.html#text-i-o", usedFor: ["text streams", "encoding", "newline", "StringIO"], evidence: "bytes decoding과 newline translation이 CSV parsing과 별도인 text I/O 경계를 확인했습니다." },
  { id: "python-open-text-025", repository: "Python Standard Library", path: "Built-in open", publicUrl: "https://docs.python.org/3/library/functions.html#open", usedFor: ["encoding argument", "newline argument", "errors policy"], evidence: "CSV 파일을 명시적 encoding과 newline=''로 여는 공식 API를 확인했습니다." },
  { id: "rfc4180-025", repository: "IETF", path: "RFC 4180 Common Format and MIME Type for CSV Files", publicUrl: "https://datatracker.ietf.org/doc/html/rfc4180", usedFor: ["records", "CRLF", "quoted fields", "double quotes"], evidence: "CSV의 널리 쓰이는 record·quote 교환 형식을 원문 RFC로 확인했습니다." },
  { id: "owasp-csv-injection-025", repository: "OWASP", path: "CSV Injection", publicUrl: "https://owasp.org/www-community/attacks/CSV_Injection", usedFor: ["formula prefixes", "spreadsheet execution", "export neutralization"], evidence: "신뢰하지 않는 cell이 spreadsheet formula로 실행되는 공격 경계와 방어 고려사항을 확인했습니다." },
);

(session.reviewQuestions as DetailedSession["reviewQuestions"]).push(
  { question: "CSV의 물리적 줄 수와 record 수가 다른 이유는 무엇인가요?", answer: "quoted field 안에 newline이 들어갈 수 있어 하나의 logical record가 여러 물리 줄을 차지할 수 있기 때문입니다." },
  { question: "`newline=''`은 encoding을 UTF-8로 고정하나요?", answer: "아닙니다. newline 처리와 bytes decoding은 별도이며 encoding='utf-8'도 명시해야 합니다." },
  { question: "DictReader가 반환한 score는 자동으로 int인가요?", answer: "기본적으로 field는 str이며 schema 경계에서 명시적으로 변환·검증해야 합니다." },
  { question: "Sniffer 결과를 그대로 production dialect로 확정해도 되나요?", answer: "heuristic이라 오판할 수 있으므로 후보 제한과 schema 검증, 사용자 확인을 함께 둡니다." },
  { question: "QUOTE_ALL이면 spreadsheet formula injection이 차단되나요?", answer: "아닙니다. CSV quoting은 문법 escaping이고 spreadsheet는 quoted cell 내용도 수식으로 해석할 수 있어 별도 정책이 필요합니다." },
);

(session.completionChecklist as string[]).push(
  "dialect의 delimiter·quote·escape·newline 규칙을 이름 있는 계약으로 고정했다.",
  "quoted delimiter와 multiline field를 logical record 하나로 검증했다.",
  "DictReader의 restkey·restval로 초과·부족 열을 관찰한다.",
  "header 검증과 field 타입 변환을 parse 단계와 분리했다.",
  "Sniffer를 heuristic 보조 신호로만 사용한다.",
  "CSV quoting과 spreadsheet formula neutralization을 구분한다.",
);
