import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-03-event-model-listeners"],
  slug: "js-03-event-model-listeners",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 3,
  title: "DOM 이벤트 등록·전파·기본 동작과 위임",
  subtitle: "EventTarget에 listener를 등록하고 dispatch path의 capture→target→bubble, target/currentTarget, cancelation과 delegation을 실제 DOM에서 추적합니다.",
  level: "기초",
  estimatedMinutes: 285,
  coreQuestion: "사용자 또는 code가 event를 발생시켰을 때 어떤 object의 listener가 어떤 순서로 호출되며, 기본 동작·전파·listener 수명·동적 자식 처리를 어떻게 독립적으로 제어할까요?",
  summary: "원본 inline onclick 색 변경, addEventListener click/mouseover/out, external defer 상세 열기·counter, coffee thumbnail/gallery를 DOM Event dispatch model로 통합합니다. EventTarget/listener record와 handler attribute/property/addEventListener 차이, event path의 capture/AT_TARGET/bubble, target/currentTarget/eventPhase/composedPath/isTrusted를 synthetic exact output으로 검증합니다. preventDefault와 stopPropagation/stopImmediatePropagation을 분리하고 anchor `href=#`를 button으로 교정합니다. once/passive/capture/signal과 동일 callback identity, AbortController cleanup을 다룹니다. parent 한 곳의 event delegation에서 `closest`·contains·data-action을 검증하고 동적 item을 처리합니다. click/pointer/keyboard/input, mouseover/out와 mouseenter/leave, focusin/out, IME, accessible native controls를 선택합니다. 마지막에는 state→render, aria-expanded/hidden, numeric parsing, safe image allowlist, external script defer의 정확한 timing과 automated event trace로 원본 UI를 재구축합니다.",
  objectives: [
    "EventTarget·Event·listener record와 user-agent event/synthetic dispatch의 역할을 구분할 수 있다.",
    "inline handler attribute, `on...` property와 addEventListener의 등록·다중 listener·scope·cleanup trade-off를 설명할 수 있다.",
    "capture→target→bubble path와 target/currentTarget/eventPhase/composedPath를 정확한 호출 순서로 추적할 수 있다.",
    "preventDefault, stopPropagation, stopImmediatePropagation을 각각 default action·다음 target·같은 target listener 관점에서 선택할 수 있다.",
    "capture·once·passive·signal option과 stable callback identity로 listener lifetime을 관리할 수 있다.",
    "event delegation에서 closest/contains/data contract를 검증해 nested click과 dynamic child를 안전하게 처리할 수 있다.",
    "mouse·pointer·keyboard·input event를 사용자 task/semantic HTML에 맞춰 선택하고 접근 가능한 state/render를 구현할 수 있다.",
  ],
  prerequisites: [
    { title: "함수 값·콜백·스코프와 클로저", reason: "listener callback identity, ordinary/arrow this, AbortSignal cleanup과 captured state를 실제 EventTarget dispatch에 적용합니다.", sessionSlug: "js-02-callback-scope-closure" },
    { title: "HTML 버튼·링크·폼 semantics", reason: "anchor navigation과 button activation이라는 browser default behavior를 event handling과 분리합니다.", sessionSlug: "html-08-form-controls-validation" },
  ],
  keywords: ["DOM Event", "EventTarget", "addEventListener", "event path", "capture", "target", "bubble", "eventPhase", "currentTarget", "composedPath", "preventDefault", "stopPropagation", "stopImmediatePropagation", "passive", "once", "AbortSignal", "event delegation", "closest", "pointer", "keyboard"],
  chapters: [
    {
      id: "occurrence-event-dispatch-listener",
      title: "event는 occurrence를 알리는 object이고 dispatch는 EventTarget listener를 path에 따라 호출합니다",
      lead: "click이 곧 함수 이름인 것이 아니라 사용자 동작→user agent event 생성/발화→dispatch→listener callback의 단계입니다.",
      explanations: [
        "DOM Standard에서 event는 사용자 상호작용·network/load·application signal 같은 occurrence를 알리는 object입니다. Node, Document, Window 등 EventTarget 구현은 type별 listener를 등록·제거하고 event를 dispatch할 수 있습니다.",
        "Event object에는 type, target/currentTarget, bubbles/cancelable/composed, eventPhase, defaultPrevented, isTrusted와 event 종류별 좌표/key/button/input 정보가 있습니다. listener는 event argument를 받아 현재 dispatch의 context를 읽습니다.",
        "사용자 agent가 실제 interaction으로 dispatch한 event는 일반적으로 isTrusted true이고 `new Event`/dispatchEvent로 application이 만든 synthetic event는 false입니다. isTrusted 하나를 authorization/security gate로 쓰지 않고 서버 권한·CSRF/gesture requirement를 별도 적용합니다.",
        "`dispatchEvent(event)`는 동기적으로 dispatch algorithm을 수행하고 listener가 cancelable event를 성공적으로 cancel하면 false를 반환할 수 있습니다. 실제 click/keyboard event는 host task에서 들어오지만 event path 안 listener invocation 자체는 한 dispatch의 순서로 진행됩니다.",
        "custom application signal은 CustomEvent detail 또는 explicit callback/state store를 사용할 수 있습니다. global document에 이름 충돌하는 string event를 무분별하게 뿌리지 않고 owner/namespace/detail schema/bubbles/composed/cancelable contract를 정합니다.",
        "원본 bg_red/bg_green/bg_blue는 anchor activation이 click event를 만들고 inline handler가 DOM style을 바꾸는 구조입니다. href=#의 navigation/default와 color state change라는 application effect를 분리해야 합니다.",
      ],
      concepts: [
        { term: "EventTarget", definition: "type별 event listener를 등록·제거하고 event dispatch에 참여하는 DOM interface입니다.", detail: ["Element·Document·Window 등이 구현합니다.", "tree Node가 아니어도 EventTarget일 수 있습니다."] },
        { term: "synthetic event", definition: "application code가 Event/CustomEvent constructor와 dispatchEvent로 만든 event입니다.", detail: ["isTrusted는 false입니다.", "bubbles/cancelable/composed를 명시합니다."] },
        { term: "event listener record", definition: "type·callback·capture·passive·once·signal/removed 상태 등을 가진 EventTarget의 관찰 등록 정보입니다.", detail: ["callback identity가 중요합니다.", "dispatch 중 options가 behavior를 바꿉니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "dispatchEvent return이 false인데 listener가 throw한 줄 알았다.", likelyCause: "cancelable event listener가 preventDefault를 호출해 canceled flag가 설정됐습니다. listener exception과 dispatch return은 다른 channel입니다.", checks: ["event.cancelable/defaultPrevented를 기록합니다.", "listener에서 preventDefault 위치를 찾습니다.", "error reporting/console stack과 cancelation을 구분합니다."], fix: "dispatch return은 cancelation decision으로 처리하고 listener 오류는 별도 error boundary/reporting으로 관찰합니다.", prevention: "synthetic cancelable/non-cancelable fixture에서 return/defaultPrevented/error를 각각 assertion합니다." },
      ],
    },
    {
      id: "registration-inline-property-listener",
      title: "inline handler·event property·addEventListener는 같은 click을 관찰해도 composition과 scope가 다릅니다",
      lead: "새 code는 addEventListener를 기본으로 쓰되 기존 inline handler가 왜 global function과 return false에 의존하는지 읽을 수 있어야 합니다.",
      explanations: [
        "HTML `onclick=\"bg_red()\"`는 handler attribute source를 HTML event handler processing으로 compile합니다. markup과 behavior가 결합되고 특별한 scope/return behavior와 CSP inline-script 제한이 있어 refactor와 test가 어렵습니다.",
        "`element.onclick = handler`는 하나의 event handler property slot을 설정하므로 다음 assignment가 이전 property handler를 대체합니다. null을 대입해 제거할 수 있지만 동일 type에 독립 module 여러 개를 composition하기 어렵습니다.",
        "`addEventListener(type,callback,options)`는 동일 EventTarget/type에 여러 listener를 등록할 수 있고 capture/once/passive/signal을 제공합니다. 동일 type·callback·capture 조합 중복은 별도 동일 listener를 계속 추가하지 않는 규칙을 이해합니다.",
        "listener registration은 대상 element가 존재한 뒤 수행합니다. 원본 external classic script의 defer는 download를 parsing과 병렬화하면서 document parse가 끝난 뒤 실행되고 DOMContentLoaded 전에 실행될 수 있습니다. page image 등 모든 resource의 load 완료까지 기다린다는 뜻은 아닙니다.",
        "module script는 기본적으로 deferred-like processing을 가지며 dependency graph/top-level await가 timing에 영향을 줄 수 있습니다. `defer`와 `async`는 다릅니다. async classic script는 fetch 완료 시 parser 순서와 독립적으로 실행될 수 있어 DOM 존재를 가정하면 race가 납니다.",
        "listener setup function은 query null을 검사하고 mount/dispose를 idempotent하게 만듭니다. hot reload/partial navigation에서 중복 mount로 click 한 번에 두 번 실행되지 않게 owner를 정합니다.",
      ],
      concepts: [
        { term: "event handler attribute/property", definition: "HTML content attribute 또는 DOM `onclick` property로 event handler를 설정하는 legacy/convenience mechanism입니다.", detail: ["property는 type당 한 slot입니다.", "inline attribute는 markup/CSP/scope trade-off가 있습니다."] },
        { term: "defer", definition: "external classic script를 parsing을 막지 않고 fetch하며 document parsing 뒤 정해진 순서로 실행하도록 하는 script attribute입니다.", detail: ["DOMContentLoaded 전에 실행 queue에 참여합니다.", "전체 resource load 완료와 다릅니다."] },
        { term: "mount/dispose", definition: "component가 listener/resource를 등록하고 같은 owner가 제거해 lifetime을 관리하는 한 쌍의 operation입니다.", detail: ["중복 mount를 방지합니다.", "AbortSignal을 사용할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "external defer script에서 image naturalWidth가 0이라 ‘defer가 동작하지 않는다’고 판단했다.", likelyCause: "defer는 document parsing 뒤 실행을 보장하지만 image 등 모든 subresource load 완료를 기다리지 않습니다.", checks: ["DOMContentLoaded/load 시각과 image.complete/naturalWidth를 기록합니다.", "script가 classic external인지 module/async인지 확인합니다.", "DOM element 존재와 media load readiness를 구분합니다."], fix: "DOM binding은 defer/module로 처리하고 image pixel이 필요하면 image load/decode completion을 별도로 await/listen합니다.", prevention: "parse readiness와 resource readiness를 별도 integration test합니다." },
      ],
    },
    {
      id: "event-path-capture-target-bubble",
      title: "dispatch path는 ancestor capture에서 target을 거쳐 bubbles=true이면 ancestor bubble로 이동합니다",
      lead: "listener가 붙은 element와 실제로 event가 시작한 descendant를 구분하면 중첩 UI의 ‘왜 부모도 실행됐지’를 설명할 수 있습니다.",
      explanations: [
        "tree target에 event가 dispatch되면 event path가 계산됩니다. capture listener는 outer ancestor에서 target 방향 tree order로, target listener는 AT_TARGET에서, bubbles=true인 event의 non-capture ancestor listener는 target에서 outer 방향 reverse tree order로 호출됩니다.",
        "capture option은 `true` 또는 `{capture:true}`입니다. target object에 등록된 capture/non-capture listener는 둘 다 eventPhase AT_TARGET이며 등록/dispatch algorithm의 ordering을 실제 trace로 확인합니다.",
        "모든 event가 bubble하는 것은 아닙니다. focus/blur, mouseenter/leave처럼 delegation에 그대로 쓸 수 없는 event가 있고 focusin/out, pointerover/out 같은 bubbling alternative와 semantics를 비교합니다.",
        "path는 dispatch 시작 시 구성되고 Shadow DOM boundary에서는 composed flag와 retargeting이 관찰 target을 바꿀 수 있습니다. composedPath는 현재 listener가 볼 수 있는 invocation path를 반환하며 closed shadow 내부는 숨겨질 수 있습니다.",
        "listener에서 DOM을 이동/삭제해도 현재 dispatch path가 이미 결정된 특성이 있고 listener removal/once/stop flag가 invocation에 영향을 줍니다. dispatch 중 mutation에 의존한 복잡한 coordination을 피합니다.",
        "원본 detail/card/gallery처럼 button 안 icon/span을 click하면 target은 inner node일 수 있고 button listener currentTarget은 button입니다. CSS selector/data/action 판단에는 closest를 사용합니다.",
      ],
      concepts: [
        { term: "event path", definition: "dispatch 동안 listener invocation 대상과 shadow-adjusted target 등을 순서대로 보관한 path입니다.", detail: ["ancestor/target을 포함합니다.", "composedPath로 가시 부분을 볼 수 있습니다."] },
        { term: "event phase", definition: "현재 listener invocation이 NONE(0), CAPTURING(1), AT_TARGET(2), BUBBLING(3) 중 어느 단계인지 나타냅니다.", detail: ["target listener는 capture option과 관계없이 phase 2입니다.", "bubble 여부는 event initialization/type에 달렸습니다."] },
        { term: "retargeting", definition: "Shadow DOM 등 encapsulation boundary에서 외부 listener에 노출되는 event target을 적절한 host로 조정하는 과정입니다.", detail: ["원래 내부 node와 다를 수 있습니다.", "composed flag/path와 함께 봅니다."] },
      ],
      codeExamples: [
        {
          id: "event-phase-trace",
          title: "outer→button→span capture/target/bubble 순서를 exact trace로 출력",
          language: "html",
          filename: "event-phases.html",
          purpose: "nested span에 synthetic bubbling event를 dispatch해 target은 고정되고 currentTarget/eventPhase만 listener마다 바뀌는 것을 Chromium에서 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>Event phases</title></head>\n<body><div id=\"outer\"><button id=\"button\"><span id=\"label\">실행</span></button></div><pre id=\"out\"></pre>\n<script>\n  const log = [];\n  const phase = event => `${event.currentTarget.id}:${event.eventPhase}:target=${event.target.id}`;\n  for (const id of ['outer', 'button', 'label']) {\n    const node = document.querySelector(`#${id}`);\n    node.addEventListener('demo', event => log.push(`capture:${phase(event)}`), { capture:true });\n    node.addEventListener('demo', event => log.push(`bubble:${phase(event)}`));\n  }\n  document.querySelector('#label').dispatchEvent(new Event('demo', { bubbles:true, composed:true }));\n  document.querySelector('#out').textContent = log.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3", explanation: "outer>button>span의 DOM path와 output target을 만듭니다." },
            { lines: "5-10", explanation: "세 node 각각에 동일 type capture/non-capture listener를 source order로 등록합니다." },
            { lines: "11", explanation: "span을 target으로 bubbles/composed demo event를 동기 dispatch합니다." },
            { lines: "12", explanation: "listener마다 고정 target, 변화한 currentTarget/phase를 exact 순서로 출력합니다." },
          ],
          run: { environment: ["Chromium 계열 modern browser"], command: "browser에서 event-phases.html을 열고 결과 확인" },
          output: { value: "capture:outer:1:target=label\ncapture:button:1:target=label\ncapture:label:2:target=label\nbubble:label:2:target=label\nbubble:button:3:target=label\nbubble:outer:3:target=label", explanation: ["target은 dispatch한 label로 모든 invocation에서 같습니다.", "ancestor capture는 outer→button, target 두 listener는 phase 2, bubble은 button→outer입니다.", "custom Event도 bubbles를 true로 초기화해야 ancestor non-capture listener에 갑니다."] },
          experiments: [
            { change: "bubbles:false로 바꿉니다.", prediction: "ancestor capture와 target listener는 실행되지만 button/outer bubble 두 줄은 사라집니다.", result: "bubbles는 capture path 존재 여부가 아니라 ancestor bubble 여부입니다." },
            { change: "button capture listener에서 stopPropagation을 호출합니다.", prediction: "event가 다음 object인 label과 outer bubble로 진행하지 않습니다.", result: "전파 중단은 default cancel과 다릅니다." },
            { change: "label 첫 listener에서 stopImmediatePropagation을 호출합니다.", prediction: "같은 label의 뒤 listener와 다른 object listener가 호출되지 않습니다.", result: "stopImmediate는 같은 current target의 남은 listener도 막습니다." },
          ],
          sourceRefs: ["web-coffee-event-source", "dom-events", "ui-events"],
        },
      ],
      diagnostics: [
        { symptom: "button 안 icon을 누르면 handler의 event.target.dataset.action이 undefined다.", likelyCause: "target은 실제 deepest icon/span이고 data-action은 button/currentTarget에 있습니다.", checks: ["target/currentTarget/composedPath tag/id를 기록합니다.", "listener가 button 직접인지 parent delegation인지 봅니다.", "closest 결과와 container containment를 확인합니다."], fix: "direct listener는 event.currentTarget, delegation은 target.closest('[data-action]')와 contains guard를 사용합니다.", prevention: "button text/icon/svg/path 각각을 click하는 nested-target test를 둡니다." },
      ],
    },
    {
      id: "target-currenttarget-composedpath",
      title: "target은 dispatch 시작점, currentTarget은 지금 callback이 실행 중인 등록 target입니다",
      lead: "event object 하나가 path를 이동하므로 listener마다 currentTarget과 phase가 바뀌고 callback 뒤 currentTarget은 null로 돌아갈 수 있습니다.",
      explanations: [
        "event.target은 event가 dispatch된 object의 shadow-adjusted target입니다. 일반 light DOM click에서는 가장 안쪽 clicked element인 경우가 많습니다. event.currentTarget은 현재 listener가 등록된 EventTarget입니다.",
        "직접 button listener에서 arrow를 쓰든 ordinary function을 쓰든 reliable element reference는 event.currentTarget입니다. async callback 안에서 event.currentTarget을 나중에 읽지 말고 필요한 element/ID를 listener 호출 중 local const로 snapshot합니다.",
        "event.composedPath()는 invocation target sequence를 반환해 delegation과 Shadow DOM debug에 도움이 됩니다. closed shadow root 내부는 observer 위치에 따라 노출되지 않으며 path index를 domain contract로 고정하지 않습니다.",
        "relatedTarget은 mouseover/out·focus 이동에서 어디서 왔거나 어디로 가는지를 나타내고 path trimming/security에 관여합니다. mouseout을 descendant 사이 이동에도 닫기 trigger로 쓰면 flicker가 생기므로 relatedTarget/contains 또는 mouseleave/pointerleave를 검토합니다.",
        "event.timeStamp는 occurrence relative high-resolution timestamp semantics를 가지며 Date.now와 기준이 다를 수 있습니다. log correlation에는 normalized telemetry clock/sequence ID를 정합니다.",
      ],
      concepts: [
        { term: "target", definition: "event가 dispatch된 target을 listener 관점에 맞게 조정해 반환하는 Event property입니다.", detail: ["path 전체에서 대체로 고정됩니다.", "Shadow DOM retargeting이 적용될 수 있습니다."] },
        { term: "currentTarget", definition: "현재 callback을 호출하고 있는 listener가 등록된 EventTarget입니다.", detail: ["invocation마다 바뀝니다.", "callback 외부에서는 null일 수 있습니다."] },
        { term: "relatedTarget", definition: "pointer/focus transition에서 target과 짝을 이루는 이전 또는 다음 EventTarget입니다.", detail: ["mouseover/out flicker 진단에 씁니다.", "target과 같아지는 path는 조정될 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "listener 안에서 setTimeout 후 event.currentTarget을 읽자 null이다.", likelyCause: "currentTarget은 listener callback이 현재 invocation되는 동안만 해당 target이고 async callback 시점에는 dispatch가 끝났습니다.", checks: ["읽는 코드가 listener call stack 안인지 timer/Promise 뒤인지 봅니다.", "target/currentTarget snapshot 시각을 log합니다.", "필요한 값이 element reference인지 stable ID인지 정합니다."], fix: "listener 동기 구간에서 `const button=event.currentTarget` 또는 필요한 dataset value를 snapshot해 async closure에 전달합니다.", prevention: "event object 전체를 장기 state에 보관하지 않고 minimal plain data를 추출합니다." },
      ],
    },
    {
      id: "default-action-versus-propagation",
      title: "preventDefault는 browser action을, stopPropagation은 다음 EventTarget 이동을 제어합니다",
      lead: "링크 이동을 막기 위해 전파를 멈추거나 부모 click을 막기 위해 preventDefault를 쓰는 서로 바뀐 처방을 피합니다.",
      explanations: [
        "anchor click의 navigation, form submit, checkbox toggle처럼 event dispatch와 연동된 default action/activation behavior가 있습니다. cancelable event listener에서 preventDefault를 호출하면 해당 operation에 cancelation을 신호하고 defaultPrevented가 true가 됩니다.",
        "stopPropagation은 event가 current object 밖 다음 path object로 진행하는 것을 막지만 같은 current target의 다른 listener를 자동으로 막지 않을 수 있습니다. stopImmediatePropagation은 같은 target의 이후 listener와 다른 object 진행을 모두 막습니다.",
        "preventDefault는 propagation을 멈추지 않습니다. parent analytics/delegation listener는 canceled event도 받을 수 있으므로 defaultPrevented를 확인해 처리 정책을 정합니다. 반대로 stopPropagation만 호출해도 link navigation은 계속될 수 있습니다.",
        "passive listener에서는 preventDefault가 cancelation을 설정하지 못합니다. touch/wheel scroll performance 때문에 browser default/passive policy가 있을 수 있어 cancel이 정말 필요한 listener만 passive:false를 명시하고 CSS touch-action 등 더 적합한 control을 검토합니다.",
        "원본 `href=#` 상세 보기/색상 변경은 navigation resource가 아니라 UI toggle이므로 anchor default를 매 click 막기보다 `<button type=button>`을 사용합니다. semantic element 선택으로 event code와 접근성 keyboard behavior가 단순해집니다.",
        "form submit은 button click만 막지 말고 form submit event에서 validation와 preventDefault 여부를 결정합니다. Enter 제출·assistive activation·requestSubmit도 같은 contract를 거칩니다.",
      ],
      concepts: [
        { term: "default action", definition: "event dispatch와 관련해 user agent/HTML element가 수행할 수 있는 navigation·submission·toggle 같은 기본 behavior입니다.", detail: ["event propagation과 별도입니다.", "cancelable 여부와 activation spec을 봅니다."] },
        { term: "preventDefault", definition: "cancelable event를 발생시킨 operation의 default action을 취소해야 한다고 신호하는 Event method입니다.", detail: ["전파는 계속됩니다.", "passive listener에서는 성공하지 않습니다."] },
        { term: "stopImmediatePropagation", definition: "현재 target의 남은 listener와 path의 다른 target listener 호출을 더 진행하지 않게 하는 method입니다.", detail: ["강한 결합을 만들 수 있습니다.", "architecture fix를 우선 검토합니다."] },
      ],
      codeExamples: [
        {
          id: "cancel-does-not-stop-bubble",
          title: "default cancel과 bubbling을 같은 synthetic event로 분리하기",
          language: "html",
          filename: "event-cancel.html",
          purpose: "inner listener가 preventDefault를 호출해 dispatchEvent=false가 되지만 outer bubble listener는 계속 실행되는 exact result를 보여 줍니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>Cancel versus propagation</title></head>\n<body><div id=\"outer\"><button id=\"inner\">실행</button></div><pre id=\"out\"></pre>\n<script>\n  const log = [];\n  const inner = document.querySelector('#inner');\n  document.querySelector('#outer').addEventListener('save', event => {\n    log.push(`outer:defaultPrevented=${event.defaultPrevented}`);\n  });\n  inner.addEventListener('save', event => {\n    log.push('inner');\n    event.preventDefault();\n  });\n  const event = new Event('save', { bubbles:true, cancelable:true });\n  const accepted = inner.dispatchEvent(event);\n  log.push(`dispatch=${accepted}`);\n  log.push(`defaultPrevented=${event.defaultPrevented}`);\n  document.querySelector('#out').textContent = log.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "5-9", explanation: "outer bubble listener가 현재 defaultPrevented 상태를 기록합니다." },
            { lines: "10-13", explanation: "target listener는 log 후 preventDefault만 호출하고 propagation은 중단하지 않습니다." },
            { lines: "14-17", explanation: "bubbling+cancelable event를 dispatch해 boolean return과 final flag를 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 event-cancel.html을 열고 결과 확인" },
          output: { value: "inner\nouter:defaultPrevented=true\ndispatch=false\ndefaultPrevented=true", explanation: ["target inner가 먼저 cancel합니다.", "event는 계속 bubble해 outer가 defaultPrevented=true를 관찰합니다.", "successful cancelation 때문에 dispatchEvent return은 false입니다."] },
          experiments: [
            { change: "inner에서 preventDefault 대신 stopPropagation을 호출합니다.", prediction: "outer 줄은 사라지지만 dispatch=true, defaultPrevented=false입니다.", result: "전파 중단은 default cancel이 아닙니다." },
            { change: "event의 cancelable을 false로 바꿉니다.", prediction: "preventDefault가 final flag를 true로 만들지 못해 dispatch=true입니다.", result: "모든 event/default operation이 cancelable인 것은 아닙니다." },
            { change: "inner listener를 `{passive:true}`로 등록합니다.", prediction: "preventDefault는 cancelation을 설정하지 못하고 browser warning이 나타날 수 있습니다.", result: "passive contract와 cancel 요구를 함께 정합니다." },
          ],
          sourceRefs: ["web-color-event-source", "web-coffee-event-source", "dom-events", "html-activation"],
        },
      ],
      diagnostics: [
        { symptom: "parent card click을 막으려고 child link에서 preventDefault했는데 parent handler도 실행된다.", likelyCause: "preventDefault는 navigation/default를 cancel할 뿐 event propagation을 멈추지 않습니다.", checks: ["parent가 delegation인지 전체 card activation인지 봅니다.", "defaultPrevented와 event path trace를 기록합니다.", "nested interactive element 구조가 valid/필요한지 검토합니다."], fix: "parent handler가 actionable closest를 구분하도록 설계하고 정말 별개 path 차단이 필요할 때만 stopPropagation을 제한적으로 사용합니다.", prevention: "nested link/button task와 default/propagation matrix E2E를 둡니다." },
      ],
    },
    {
      id: "listener-options-lifetime-abort",
      title: "capture·once·passive·signal과 stable identity로 listener의 behavior와 lifetime을 선언합니다",
      lead: "등록 code에 callback만 보지 말고 어느 phase, 몇 번, cancel 가능, 언제 제거되는지를 options까지 읽습니다.",
      explanations: [
        "capture true는 ancestor capture phase에서 callback을 호출합니다. removeEventListener matching에서 capture flag가 중요하므로 object options를 저장하거나 abort signal로 owner lifecycle을 단순화합니다.",
        "once true listener는 한 번 invocation 뒤 제거되어 one-shot setup에 적합합니다. callback 안에서 다시 등록하거나 nested dispatch가 있을 때 exact semantics를 target browser/test로 확인하고 business state도 별도 guard합니다.",
        "passive true는 callback이 preventDefault하지 않을 것이라는 약속입니다. scroll 관련 event에서 user agent 최적화에 도움이 되지만 default를 cancel해야 하면 사용하지 않습니다. 습관적으로 모든 listener에 passive를 넣지 않습니다.",
        "AbortController signal을 여러 addEventListener에 넘기고 controller.abort()하면 같은 owner의 listener를 일괄 제거할 수 있습니다. 이미 aborted signal로 등록하면 listener가 추가되지 않는 behavior를 이해하고 controller instance 재사용/교체를 관리합니다.",
        "같은 type/callback/capture 등록은 중복 처리 규칙이 있지만 다른 anonymous function은 각각 다른 listener입니다. render마다 새 listener를 붙이지 않고 mount 한 번 또는 delegation을 사용합니다.",
        "listener callback이 object method handleEvent를 가진 EventListener object일 수도 있습니다. function identity와 instance lifetime, this semantics를 명확히 하면 class/controller에 활용할 수 있습니다.",
      ],
      concepts: [
        { term: "once listener", definition: "첫 callback invocation 후 listener record가 제거되는 addEventListener option입니다.", detail: ["one-shot event에 적합합니다.", "business idempotency를 완전히 대신하지 않습니다."] },
        { term: "passive listener", definition: "callback이 preventDefault로 event cancelation을 요청하지 않을 것임을 선언한 listener입니다.", detail: ["scroll input 성능과 관련됩니다.", "cancel이 필요하면 false입니다."] },
        { term: "AbortSignal listener lifetime", definition: "listener 등록에 signal을 연결해 AbortController.abort 시 제거되게 하는 lifecycle pattern입니다.", detail: ["여러 listener를 묶을 수 있습니다.", "controller owner를 정합니다."] },
      ],
      codeExamples: [
        {
          id: "abort-listener-group",
          title: "하나의 AbortSignal로 두 listener를 동시에 해제하기",
          language: "html",
          filename: "event-abort.html",
          purpose: "stable callback을 직접 remove하지 않아도 owner controller abort 뒤 synthetic clicks가 더 이상 호출되지 않는 exact count를 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>Abort listeners</title></head>\n<body><button id=\"a\">A</button><button id=\"b\">B</button><pre id=\"out\"></pre>\n<script>\n  const controller = new AbortController();\n  const calls = [];\n  const record = event => calls.push(event.currentTarget.id);\n  for (const id of ['a', 'b']) {\n    document.querySelector(`#${id}`).addEventListener('click', record, { signal:controller.signal });\n  }\n  document.querySelector('#a').click();\n  document.querySelector('#b').click();\n  controller.abort();\n  document.querySelector('#a').click();\n  document.querySelector('#b').click();\n  document.querySelector('#out').textContent = `calls=${calls.join(',')}\\naborted=${controller.signal.aborted}`;\n</script></body></html>",
          walkthrough: [
            { lines: "5-10", explanation: "controller와 stable record callback을 만들고 A/B listener에 같은 signal을 연결합니다." },
            { lines: "11-12", explanation: "abort 전 두 click이 currentTarget id를 기록합니다." },
            { lines: "13-15", explanation: "abort 후 두 click은 listener가 제거되어 calls를 바꾸지 않습니다." },
            { lines: "16", explanation: "call sequence와 signal state를 출력합니다." },
          ],
          run: { environment: ["addEventListener signal option을 지원하는 modern browser"], command: "browser에서 event-abort.html을 열고 결과 확인" },
          output: { value: "calls=a,b\naborted=true", explanation: ["abort 전 A/B가 한 번씩 호출됩니다.", "한 controller가 같은 owner의 두 listener lifetime을 종료합니다.", "abort 후 programmatic click은 element default/dispatch를 수행해도 record listener는 호출되지 않습니다."] },
          experiments: [
            { change: "B listener에서 signal option을 제거합니다.", prediction: "abort 후 B click이 추가되어 calls=a,b,b입니다.", result: "같은 owner resource가 모두 signal에 연결됐는지 inventory합니다." },
            { change: "A listener에 once:true도 추가합니다.", prediction: "A는 첫 click 뒤 이미 제거되고 abort는 남은 B를 제거합니다.", result: "once와 signal은 함께 사용할 수 있지만 lifetime intent를 문서화합니다." },
            { change: "abort된 controller.signal로 새 listener를 등록합니다.", prediction: "그 listener는 활성 등록되지 않습니다.", result: "remount에는 새 AbortController가 필요합니다." },
          ],
          sourceRefs: ["web-detail-event-source", "dom-events"],
        },
      ],
      diagnostics: [
        { symptom: "component를 다시 mount했는데 아무 listener도 작동하지 않는다.", likelyCause: "이전 dispose에서 abort된 AbortSignal을 새 registration에도 재사용했습니다.", checks: ["controller.signal.aborted를 확인합니다.", "mount마다 controller를 새로 만드는지 봅니다.", "listener registration call count와 signal identity를 기록합니다."], fix: "각 mount/lifecycle instance에 새 AbortController를 만들고 dispose 후 reference를 폐기합니다.", prevention: "mount→dispose→remount→event sequence를 integration test합니다." },
      ],
    },
    {
      id: "delegation-closest-dynamic-items",
      title: "event delegation은 bubbling event를 stable ancestor 한 곳에서 받고 actionable descendant를 검증합니다",
      lead: "listener 수를 줄이는 것보다 nested target·동적 item·boundary를 정확히 식별하는 것이 핵심입니다.",
      explanations: [
        "list/card/grid의 많은 child action이 bubble한다면 parent에 listener 하나를 등록하고 event.target에서 action element를 찾을 수 있습니다. 나중 append된 child도 같은 path를 사용해 별도 listener 등록이 필요 없습니다.",
        "`event.target.closest('button[data-action]')`은 icon/span click에서도 action button을 찾습니다. 하지만 closest가 delegation container 밖 ancestor를 반환하지 않게 `container.contains(button)` 또는 composedPath boundary를 확인합니다.",
        "data-action string을 function 이름으로 dynamic global lookup/eval하지 않습니다. allowlisted action map/explicit switch로 dispatch하고 data-id는 store에서 schema/authorization을 검증합니다.",
        "disabled native button은 click dispatch/activation semantics가 다를 수 있고 aria-disabled만으로 실제 기능이 막히지 않습니다. form button type과 nested interactive invalid markup을 먼저 교정합니다.",
        "stopPropagation에 의존하는 child component가 많아지면 ancestor delegation이 조용히 깨집니다. component boundary에서 event contract를 문서화하고 custom event composed/bubbles 또는 explicit callback을 선택합니다.",
        "delegation listener가 매 click마다 전체 DOM을 query하거나 layout property를 읽고 쓰면 performance가 떨어집니다. closest/Map lookup으로 좁히고 state calculation→batch render를 유지합니다.",
      ],
      concepts: [
        { term: "event delegation", definition: "여러 descendant의 bubbling event를 공통 ancestor listener 한 곳에서 action target을 판별해 처리하는 pattern입니다.", detail: ["동적 child를 처리합니다.", "target validation이 필요합니다."] },
        { term: "closest", definition: "element 자신부터 ancestor 방향으로 selector와 일치하는 첫 element를 반환하는 DOM method입니다.", detail: ["nested icon click에 유용합니다.", "container boundary를 추가 검사합니다."] },
        { term: "action allowlist", definition: "data-action 같은 external DOM string을 허용된 handler key 집합에만 mapping하는 dispatch policy입니다.", detail: ["eval/global lookup을 피합니다.", "unknown action을 명시적으로 처리합니다."] },
      ],
      codeExamples: [
        {
          id: "delegated-actions-nested-target",
          title: "nested span과 동적 button을 parent listener 하나로 처리",
          language: "html",
          filename: "event-delegation.html",
          purpose: "closest+contains+allowlist가 inner label click과 registration 후 추가된 item을 정확히 처리하는 exact output을 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>Delegation</title></head>\n<body><div id=\"actions\"><button data-action=\"save\"><span id=\"save-label\">저장</span></button></div><pre id=\"out\"></pre>\n<script>\n  const container = document.querySelector('#actions');\n  const calls = { save:0, remove:0 };\n  const handlers = {\n    save: () => { calls.save += 1; },\n    remove: () => { calls.remove += 1; },\n  };\n  container.addEventListener('click', event => {\n    if (!(event.target instanceof Element)) return;\n    const button = event.target.closest('button[data-action]');\n    if (!button || !container.contains(button)) return;\n    const handler = handlers[button.dataset.action];\n    if (handler) handler();\n  });\n  document.querySelector('#save-label').click();\n  container.insertAdjacentHTML('beforeend', '<button data-action=\"remove\"><span id=\"remove-label\">삭제</span></button>');\n  document.querySelector('#remove-label').click();\n  document.querySelector('#out').textContent = `save=${calls.save}\\nremove=${calls.remove}\\nbuttons=${container.querySelectorAll('button').length}`;\n</script></body></html>",
          walkthrough: [
            { lines: "5-10", explanation: "stable container, call state와 허용된 save/remove handler map을 만듭니다." },
            { lines: "11-17", explanation: "target Element guard, closest actionable button, container boundary와 allowlist handler를 순서대로 검사합니다." },
            { lines: "18-20", explanation: "nested save span을 click하고 listener 등록 뒤 remove button을 동적으로 추가해 nested span을 click합니다." },
            { lines: "21", explanation: "action별 count와 실제 button 수를 출력합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 event-delegation.html을 열고 결과 확인" },
          output: { value: "save=1\nremove=1\nbuttons=2", explanation: ["event.target은 span이지만 closest가 각 button을 찾습니다.", "동적 remove button에도 parent listener 하나가 적용됩니다.", "unknown data-action은 handler map에 없어 실행되지 않습니다."] },
          experiments: [
            { change: "closest 대신 `event.target.dataset.action`만 사용합니다.", prediction: "span click에는 action이 없어 save/remove가 0입니다.", result: "nested markup에 견고한 actionable ancestor lookup이 필요합니다." },
            { change: "unknown data-action=export button을 추가해 click합니다.", prediction: "아무 handler도 실행되지 않고 기존 count가 유지됩니다.", result: "unknown action logging/error 정책을 production contract에 추가합니다." },
            { change: "remove button listener에서 stopPropagation을 호출하는 child listener를 추가합니다.", prediction: "parent delegation까지 event가 오지 않아 remove가 증가하지 않습니다.", result: "delegation은 propagation contract에 의존합니다." },
          ],
          sourceRefs: ["web-color-event-source", "web-coffee-event-source", "dom-events", "selectors-closest"],
        },
      ],
      diagnostics: [
        { symptom: "동적 추가 버튼은 작동하지만 icon을 누르면 action이 실행되지 않는다.", likelyCause: "delegation code가 event.target 자체에 data-action이 있다고 가정하고 closest를 사용하지 않았습니다.", checks: ["icon/span/button click별 target path를 기록합니다.", "closest와 contains result를 확인합니다.", "pointer-events CSS로 문제를 숨기고 있지 않은지 봅니다."], fix: "target Element에서 closest actionable selector를 찾고 container boundary/action allowlist를 검증합니다.", prevention: "text/icon/svg/path와 동적 item 모두를 activation하는 E2E를 둡니다." },
      ],
    },
    {
      id: "input-pointer-keyboard-event-choice",
      title: "이벤트 종류는 device가 아니라 사용자 task와 semantic control의 기본 behavior로 선택합니다",
      lead: "mouseover만 구현하면 touch·keyboard·assistive activation이 빠지며 mouseout은 child 이동에도 반복됩니다.",
      explanations: [
        "button의 activation에는 click을 기본으로 사용하면 mouse, touch, keyboard와 assistive technology가 native semantics를 통해 연결됩니다. keydown으로 Enter/Space를 직접 재구현할 필요가 있는 custom role보다 native button을 우선합니다.",
        "pointer events는 mouse/pen/touch를 통합하고 pointerId/type/pressure/capture를 제공합니다. drag/draw gesture에는 pointerdown/move/up/cancel과 touch-action, pointer capture를 설계하지만 simple activation은 click이 더 적합합니다.",
        "mouseover/out은 descendant 경계를 오갈 때 bubble하며 반복될 수 있고 mouseenter/leave는 같은 방식으로 bubble하지 않습니다. pointerover/out와 pointerenter/leave도 목적을 구분하고 hover-only로 essential content를 숨기지 않습니다.",
        "form 값 변화에는 input이 typing/paste/drop/mobile 등 넓은 변경을 반영하고 change는 control별 commit timing이 다릅니다. keyboard keyup만 쓰면 paste·speech·autofill을 놓칩니다. IME composition 중 validation/reformat을 조심합니다.",
        "focus/blur는 bubble하지 않는 특성이 있고 focusin/focusout은 delegation에 사용할 수 있습니다. focus-visible style과 focus 이동 이유를 유지하며 click에서 강제로 blur하지 않습니다.",
        "event frequency가 높은 pointermove/scroll/input에서는 handler work를 측정하고 requestAnimationFrame/debounce/throttle를 목적별로 사용합니다. passive/cancelation과 stale state, cleanup을 함께 test합니다.",
      ],
      concepts: [
        { term: "activation event", definition: "사용자가 control의 primary action을 실행했다는 semantic interaction으로 native button/link에서는 click과 activation behavior가 연결됩니다.", detail: ["여러 input modality를 포괄합니다.", "native element를 우선합니다."] },
        { term: "PointerEvent", definition: "mouse·pen·touch 등 pointing device 입력을 공통 model로 제공하는 UI event interface입니다.", detail: ["pointerId/type/capture가 있습니다.", "simple click 대체로 무조건 쓸 필요는 없습니다."] },
        { term: "IME composition", definition: "한글·일본어·중국어 등 입력기가 여러 key/input step을 조합해 최종 text를 만드는 기간/상태입니다.", detail: ["중간 input을 확정값처럼 변형하지 않습니다.", "composition events/isComposing을 고려합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "공지 상세가 mouse hover에는 보이지만 Tab/Enter와 touch에서는 열리지 않는다.", likelyCause: "mouseover에만 essential action을 연결하고 semantic button/click state를 제공하지 않았습니다.", checks: ["keyboard focus/Enter/Space와 touch click을 수행합니다.", "control element/role/name/state를 accessibility tree에서 봅니다.", "hover media condition과 hidden content를 확인합니다."], fix: "button click으로 explicit toggle을 제공하고 hover는 optional preview로만 사용하며 aria-expanded/hidden을 state와 동기화합니다.", prevention: "mouse 없는 keyboard/touch task와 hover:none E2E를 둡니다." },
      ],
    },
    {
      id: "state-render-source-capstone",
      title: "원본 상세·counter·gallery는 event→validated action→state→render의 한 방향 흐름으로 재구축합니다",
      lead: "각 listener가 display/src/text를 제각각 바꾸지 않고 state transition 하나와 render 하나가 UI invariant를 유지합니다.",
      explanations: [
        "상세 toggle state `isOpen`을 하나로 두고 render가 detail.hidden, trigger aria-expanded와 button text를 함께 갱신합니다. open/close element를 display none으로 교차하는 두 source of truth보다 state와 DOM accessibility가 일치합니다.",
        "counter는 textContent를 읽어 `k++` coercion하는 대신 numeric state를 유지하고 min/max/step을 validation합니다. render만 state를 문자열로 쓰며 rapid click에서도 invariant를 유지합니다.",
        "coffee thumbnail은 event.target.src absolute URL을 그대로 main image에 쓰기보다 data-large/asset manifest에서 allowlisted URL과 alt를 가져옵니다. selected state/aria-current를 갱신하고 broken image fallback을 제공합니다.",
        "inline style display/background를 listener마다 쓰면 CSS state와 접근성 state가 흩어집니다. classList/hidden/aria/data-state를 render에서 적용하고 CSS가 presentation을 담당합니다. hidden이 animation 요구와 충돌하면 state machine을 확장합니다.",
        "anchor `href=#` 상세 control은 button으로 바꿔 preventDefault를 제거합니다. link는 실제 navigation, button은 current page action이라는 semantic contract를 유지합니다.",
        "external script는 module/defer로 DOM parse 뒤 mount하고 query result를 검증합니다. image/font/network full load가 필요한 effect는 별도 readiness를 기다립니다. unload보다 AbortController/dispose와 page lifecycle에 맞는 cleanup을 사용합니다.",
        "event regression test는 initial state, click/keyboard sequence, target/currentTarget nested click, DOM/ARIA snapshot, duplicate mount, dispose 후 call 0을 확인합니다. screenshot만으로 event semantics를 판단하지 않습니다.",
      ],
      concepts: [
        { term: "single source of truth", definition: "UI의 한 의미 상태를 여러 DOM style/text에 중복 저장하지 않고 한 state value에서 render하는 설계입니다.", detail: ["ARIA/visual 불일치를 줄입니다.", "transition test가 쉬워집니다."] },
        { term: "render function", definition: "검증된 application state를 DOM property/class/ARIA/text로 반영하는 effect boundary입니다.", detail: ["event handler 계산과 분리합니다.", "idempotent output을 목표로 합니다."] },
        { term: "UI invariant", definition: "모든 event transition 뒤에도 유지되어야 하는 상태 관계입니다.", detail: ["예: hidden===!aria-expanded입니다.", "counter range와 selected item unique도 포함합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "상세 내용은 보이는데 trigger의 aria-expanded는 false이고 닫기 버튼도 동시에 보인다.", likelyCause: "여러 listener가 display/ARIA를 따로 갱신해 UI state source가 분산됐습니다.", checks: ["모든 DOM write 위치를 검색합니다.", "isOpen state와 hidden/aria-expanded/button visibility를 비교합니다.", "rapid/double click sequence를 실행합니다."], fix: "한 transition이 isOpen을 바꾸고 한 render가 관련 DOM/ARIA 전체를 idempotent하게 갱신하게 합니다.", prevention: "각 state에서 UI invariant를 assertion하고 DOM write를 render module로 제한합니다." },
      ],
      expertNotes: [
        "event path와 listener list는 dispatch algorithm 중 mutation/removed flag 규칙이 있습니다. dispatch 중 listener를 추가/제거하는 trick에 architecture를 의존하지 않고 explicit state/action queue를 사용합니다.",
        "Shadow DOM component의 custom event는 bubbles/composed/detail schema를 public API로 정합니다. 내부 DOM target을 외부에서 직접 추측하지 않습니다.",
        "고주파 event 최적화 전에 handler CPU, style/layout/paint를 profile합니다. debounce는 마지막 입력 지연, throttle은 빈도 제한, requestAnimationFrame은 visual frame coalescing이라는 서로 다른 semantics입니다.",
      ],
    },
  ],
  lab: {
    title: "원본 색상·상세·counter·coffee gallery를 접근 가능한 위임형 event component로 통합하기",
    scenario: "현재 page는 inline onclick/href=#, 여러 anonymous listener, mouseover/out, text 숫자 coercion과 각 listener의 직접 style/src mutation을 사용합니다. nested icon click·keyboard/touch·duplicate mount·dispose에서 깨지고 ARIA 상태가 어긋납니다.",
    setup: [
      "원본 HTML 4개와 JS 2개를 read-only evidence로 준비하고 handler/listener/default action 표를 만듭니다.",
      "capture/target/bubble trace와 synthetic cancelable event, nested span/svg, dynamic item fixture를 준비합니다.",
      "keyboard/touch/pointer/IME, reduced motion/forced colors와 duplicate mount/dispose test 환경을 준비합니다.",
      "detail/counter/gallery state schema와 UI invariant, allowed action/image manifest를 먼저 작성합니다.",
    ],
    steps: [
      "inline onclick과 href=# action을 semantic button+module addEventListener로 교체합니다.",
      "external module/defer mount에서 DOM query null을 검증하고 AbortController를 lifecycle owner로 만듭니다.",
      "nested target event trace로 capture/target/bubble과 target/currentTarget/composedPath를 exact snapshot합니다.",
      "preventDefault/stop/stopImmediate/passive/cancelable matrix를 synthetic event로 실행합니다.",
      "container delegation에서 closest+contains+action allowlist로 static/dynamic/nested action을 처리합니다.",
      "detail isOpen, numeric counter, selected gallery asset를 pure transition으로 계산하고 한 render에서 hidden/ARIA/text/src/alt를 갱신합니다.",
      "click/keyboard/touch/input/IME와 hover optional behavior를 실제 task별로 검증합니다.",
      "mount→events→dispose/abort→late event에서 call 0, listener/DOM retention과 no overflow/focus를 자동화합니다.",
    ],
    expectedResult: [
      "event trace가 capture→target→bubble 표와 일치하고 target/currentTarget을 nested markup에서도 올바르게 사용합니다.",
      "default action과 propagation control이 서로 독립적으로 목적에 맞게 동작합니다.",
      "동적 action도 parent listener 하나로 처리되고 unknown/outside action은 실행되지 않습니다.",
      "상세/카운터/gallery state와 visual/ARIA DOM이 모든 transition 뒤 invariant를 유지합니다.",
      "mouse 없이 keyboard/touch/assistive activation으로 같은 task를 완료하고 hover는 필수가 아닙니다.",
      "duplicate mount와 dispose 후 callback이 없고 listener/large DOM이 불필요하게 retained되지 않습니다.",
    ],
    cleanup: ["synthetic debug listener, fake dynamic items와 console trace를 제거하고 AbortController.abort로 lab listener를 정리합니다.", "placeholder href/inline handler/unsafe image URL와 experiment style를 production source에서 제거합니다."],
    extensions: ["Shadow DOM 안 custom event의 bubbles/composed/retargeting을 open/closed root에서 비교합니다.", "Pointer capture 기반 drag와 keyboard alternative를 같은 state machine으로 구현합니다.", "Web Platform Tests 방식의 event order assertion과 browser matrix를 CI에 추가합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "세 nested element에 capture/non-capture listener를 붙여 target/currentTarget/eventPhase/순서를 예측·실행하세요.", requirements: ["bubbles false/true를 비교합니다.", "target 두 listener가 phase 2임을 확인합니다.", "stopPropagation/stopImmediate를 각각 한 번 적용합니다.", "composedPath와 isTrusted를 출력합니다."], hints: ["capture와 bubble path 방향을 따로 적습니다.", "currentTarget은 listener 등록 object입니다."], expectedOutcome: "모든 listener 호출 순서와 누락 이유를 event path/flag로 설명합니다.", solutionOutline: ["path를 outer→target→outer로 그립니다.", "한 flag씩만 바꿔 diff를 기록합니다."] },
    { difficulty: "응용", prompt: "동적 상품 목록의 선택·삭제·상세를 event delegation과 state/render로 구현하세요.", requirements: ["closest+contains+data-action allowlist를 사용합니다.", "nested icon/text click을 지원합니다.", "anchor/button semantics와 default action을 교정합니다.", "selected/expanded/removed state와 ARIA를 한 render에서 동기화합니다.", "AbortSignal dispose와 keyboard/touch test를 포함합니다."], hints: ["target 자체에 action이 없을 수 있습니다.", "stopPropagation보다 parent action routing을 먼저 고칩니다."], expectedOutcome: "listener 하나로 static/dynamic action이 접근 가능하게 동작하고 cleanup 후 call이 없습니다.", solutionOutline: ["event→action data→transition→render pipeline을 만듭니다.", "unknown/outside/disabled action을 early return합니다."] },
    { difficulty: "설계", prompt: "교육 사이트 component의 event contract와 test governance를 설계하세요.", requirements: ["event type/bubbles/cancelable/composed/detail schema를 정의합니다.", "default/propagation/passive/once/capture 정책을 만듭니다.", "listener owner·stable identity·AbortSignal mount/dispose를 정합니다.", "mouse/pointer/keyboard/input/IME와 native semantics 선택 기준을 포함합니다.", "phase/order·DOM/ARIA·destination·performance·heap regression matrix를 설계합니다."], hints: ["custom event와 explicit callback 중 공개 API에 적합한 것을 비교합니다.", "isTrusted를 권한 gate로 쓰지 않습니다."], expectedOutcome: "여러 component가 충돌·누수 없이 event를 조합하고 사용자 modality 전반에서 같은 task를 제공하는 specification이 완성됩니다.", solutionOutline: ["occurrence→dispatch→listener→action→state→render/default flow를 그립니다.", "자동/수동 assertion owner를 분리합니다."] },
  ],
  reviewQuestions: [
    { question: "event.target과 currentTarget의 차이는 무엇인가요?", answer: "target은 dispatch 시작점의 shadow-adjusted target이고 currentTarget은 지금 callback이 실행되는 listener 등록 EventTarget입니다." },
    { question: "capture listener는 어느 방향으로 호출되나요?", answer: "outer ancestor에서 target 방향으로 호출되고 target에서는 phase가 AT_TARGET입니다." },
    { question: "bubbles=false이면 ancestor capture도 실행되지 않나요?", answer: "아닙니다. bubble ancestor 단계가 없을 뿐 capture path와 target listener는 실행될 수 있습니다." },
    { question: "preventDefault가 event bubbling도 막나요?", answer: "아닙니다. default action cancel과 propagation은 별도입니다." },
    { question: "stopPropagation과 stopImmediatePropagation의 차이는 무엇인가요?", answer: "stopImmediate는 같은 current target의 이후 listener도 막고 다른 target 진행도 막습니다. stopPropagation은 같은 target의 다른 listener를 자동으로 모두 막지는 않습니다." },
    { question: "passive listener에서 preventDefault가 동작하나요?", answer: "successful cancelation을 설정하지 못합니다. cancel 필요와 passive performance contract를 맞춰야 합니다." },
    { question: "defer script는 모든 image가 로드된 뒤 실행되나요?", answer: "아닙니다. document parsing 뒤 실행에 참여하지만 전체 subresource load 완료와는 다릅니다." },
    { question: "removeEventListener에 같은 코드의 새 arrow를 주면 제거되나요?", answer: "아닙니다. 다른 function identity이므로 등록한 reference 또는 AbortSignal을 사용합니다." },
    { question: "event delegation에서 왜 closest가 필요한가요?", answer: "button 안 span/icon처럼 event.target이 actionable element의 descendant일 수 있기 때문입니다." },
    { question: "hover UI는 mouseover만 구현하면 되나요?", answer: "essential action은 native button click/focus/touch에서 제공하고 hover는 optional enhancement로 둡니다." },
    { question: "click event는 mouse에서만 오나요?", answer: "native control activation은 keyboard/touch/assistive input도 click/activation으로 연결될 수 있어 semantic element를 사용합니다." },
    { question: "dispatchEvent가 false를 반환하면 무슨 뜻인가요?", answer: "cancelable event가 successful preventDefault로 canceled되었다는 뜻이며 listener exception을 뜻하지 않습니다." },
  ],
  completionChecklist: [
    "EventTarget·Event·listener와 trusted/synthetic occurrence를 구분했다.",
    "inline/property/addEventListener 및 defer/async/module timing을 설명했다.",
    "capture→AT_TARGET→bubble path와 target/currentTarget/eventPhase를 exact output으로 확인했다.",
    "composedPath·retargeting·relatedTarget의 적용 경계를 설명했다.",
    "preventDefault·stopPropagation·stopImmediatePropagation을 독립적으로 test했다.",
    "capture·once·passive·signal과 cancelable/defaultPrevented를 목적에 맞게 사용했다.",
    "stable callback/capture identity 또는 AbortSignal로 listener를 cleanup했다.",
    "delegation에서 closest·contains·action allowlist와 dynamic/nested target을 처리했다.",
    "native button/link와 click/pointer/input/focus event를 사용자 task에 맞게 선택했다.",
    "detail/counter/gallery를 state transition과 한 render로 만들고 DOM/ARIA invariant를 유지했다.",
    "duplicate mount·dispose·late event·keyboard/touch/IME·heap/performance 회귀를 검증했다.",
  ],
  nextSessions: ["js-04-built-in-objects"],
  sources: [
    { id: "web-color-event-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex02_event.html", usedFor: ["inline onclick", "href placeholder/default action", "id/querySelector/NodeList", "multiple color actions"], evidence: "Red/Green/Blue inline handlers와 `href=#`, single/multiple target style mutation을 semantic button·delegation·state/render 교정의 실제 근거로 사용했습니다." },
    { id: "web-basic-listener-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex03_event.html", usedFor: ["addEventListener", "named click listener", "anonymous click/mouseover/mouseout", "anchor navigation", "box state"], evidence: "named sayHello와 세 anonymous mouse/click listener를 registration mechanism·input event choice·listener lifecycle 분석에 반영했습니다." },
    { id: "web-detail-event-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex04_event.html", usedFor: ["external defer script", "detail open/close buttons", "counter controls", "DOM readiness"], evidence: "bear detail와 plus/minus markup 및 defer comment를 parse readiness·accessible toggle·numeric state capstone으로 교정했습니다." },
    { id: "web-coffee-event-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex05_event.html", usedFor: ["thumbnail gallery", "detail href controls", "nested content", "image alt/src", "external script"], evidence: "coffee thumbnail/detail markup을 target/currentTarget·delegation·safe selected asset·link/button semantics의 실제 사례로 사용했습니다." },
    { id: "web-detail-js-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/js/ex04.js", usedFor: ["query+listener setup", "display toggle", "textContent/innerText counter", "numeric coercion", "two source of truth"], evidence: "open/close와 k++/k-- DOM text coercion을 explicit state→render·ARIA invariant와 listener cleanup으로 확장했습니다." },
    { id: "web-coffee-js-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/js/ex05.js", usedFor: ["detail link listener", "thumbnail NodeList loop", "ordinary this versus arrow event", "event.target.src", "setAttribute"], evidence: "ordinary function this와 arrow event.target 주석 및 thumbnail loop를 currentTarget/closest·asset allowlist·delegation 비교에 반영했습니다." },
    { id: "dom-events", repository: "WHATWG DOM Standard", path: "#events", publicUrl: "https://dom.spec.whatwg.org/#events", usedFor: ["Event/EventTarget", "listener options", "dispatch path/phases", "target/currentTarget/composedPath", "cancelation/propagation", "AbortSignal"], evidence: "2026-07-12 확인한 DOM living standard event dispatch/listener algorithm을 모든 exact trace와 lifecycle 설명의 기준으로 사용했습니다." },
    { id: "ui-events", repository: "W3C UI Events", path: "TR/uievents/", publicUrl: "https://www.w3.org/TR/uievents/", usedFor: ["click/keyboard/mouse event", "mouseover/out/enter/leave", "relatedTarget", "activation ordering"], evidence: "device/UI event interface와 event type 선택, relatedTarget 이동 semantics를 공식 specification에 맞춰 보강했습니다." },
    { id: "pointer-events", repository: "W3C Pointer Events", path: "TR/pointerevents3/", publicUrl: "https://www.w3.org/TR/pointerevents3/", usedFor: ["pointer unification", "pointerId/type", "pointer capture", "touch-action", "gesture cancellation"], evidence: "mouse-only listener를 pointer/touch/pen task로 확장할 때 사용할 current pointer event 기준으로 사용했습니다." },
    { id: "html-scripts-defer", repository: "WHATWG HTML Standard", path: "multipage/scripting.html#attr-script-defer", publicUrl: "https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer", usedFor: ["classic script defer", "parse completion", "DOMContentLoaded ordering", "async/module contrast"], evidence: "원본 ‘완전히 로드 후’ 주석을 document parse와 resource load를 구분하는 정확한 script processing model로 교정했습니다." },
    { id: "html-activation", repository: "WHATWG HTML Standard", path: "multipage/interaction.html#activation-behavior", publicUrl: "https://html.spec.whatwg.org/multipage/interaction.html#activation-behavior", usedFor: ["click activation", "default action", "synthetic click", "link/button behavior"], evidence: "anchor navigation과 button activation을 listener propagation과 분리하는 기준으로 사용했습니다." },
    { id: "selectors-closest", repository: "WHATWG DOM Standard", path: "#dom-element-closest", publicUrl: "https://dom.spec.whatwg.org/#dom-element-closest", usedFor: ["Element.closest", "selector matching", "delegation target lookup", "container boundary"], evidence: "nested icon/text target에서 actionable ancestor를 찾는 delegation example의 API 기준으로 사용했습니다." },
    { id: "wai-button-pattern", repository: "W3C Web Accessibility Initiative", path: "ARIA/apg/patterns/button/", publicUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/button/", usedFor: ["button activation", "keyboard interaction", "toggle state", "native element preference"], evidence: "상세 action을 placeholder anchor/hover에서 accessible button/toggle interaction으로 바꾸는 사용자 동작 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 6,
    filesUsed: 6,
    uncoveredNotes: [
      "원본 6개는 inline/property-like handler, addEventListener, mouse/click, defer script, detail/counter/gallery까지 풍부합니다. capture/bubble path·cancelation/propagation·options/AbortSignal·delegation·pointer/keyboard/IME와 automated traces는 WHATWG/W3C 표준으로 보강했습니다.",
      "DOM query/traversal 자체는 js-05, safe create/update/remove는 js-06, form property/attribute는 js-07, task/microtask/timer scheduling은 js-08에서 각각 독립적으로 더 깊게 다룹니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
