import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-08-event-loop-timers-callback"],
  slug: "js-08-event-loop-timers-callback",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 8,
  title: "동기 실행, 이벤트 루프, setTimeout과 콜백 비동기",
  subtitle: "call stack·task·microtask·rendering 순서를 추적하고, 정확하지 않은 timer를 수명과 취소가 명확한 controller로 바꿉니다.",
  level: "중급",
  estimatedMinutes: 325,
  coreQuestion: "JavaScript가 한 번에 한 실행 흐름을 처리하면서도 timer·event·network 결과에 반응하는 이유와, 지연·중복·cleanup 문제 없는 반복 작업을 어떻게 설계할까요?",
  summary: "원본의 네 줄 동기 log, 1초 setTimeout 두 개, 세 번 뒤 clearInterval, 한 줄 뉴스 rotator를 browser 실행 모델로 확장합니다. 비동기는 순서를 무시하거나 여러 JavaScript callback이 동시에 실행된다는 뜻이 아니라, 현재 실행을 끝낸 뒤 host가 준비한 작업을 event loop가 다시 실행하게 만드는 구성임을 설명합니다. ECMAScript execution context stack과 run-to-completion, HTML event loop의 task queue·task source·microtask checkpoint·rendering opportunity를 exact output으로 연결합니다. 0ms timeout도 현재 stack과 microtasks를 추월하지 못하고 delay는 정확한 실행 시각이 아니라 최소 대기 기준이라는 점, nested clamp·background throttling·긴 task·clock drift를 다룹니다. setInterval ID를 저장하고 중복 start를 막으며 clear 후 running state를 되돌리는 lifecycle, component dispose·page visibility·monotonic time·self-scheduling timeout 선택 기준을 구현합니다. callback의 closure·argument·this·throw boundary와 이름 있는 function을 통한 진단 가능성도 포함합니다. 최종 뉴스 controller는 즉시 첫 item을 보여 주고 start/stop을 idempotent하게 만들며 fake scheduler로 실제 시간을 기다리지 않고 검증합니다. 자동 회전 content에는 pause control, focus/hover 시 정지, reduced motion과 과도하지 않은 live announcement를 제공해 접근성까지 수명 계약에 포함합니다.",
  objectives: [
    "execution context stack과 run-to-completion으로 동기 함수 호출·return 순서를 그릴 수 있다.",
    "browser host API, task source/queue와 event loop가 timer callback을 현재 stack 이후에 실행하는 과정을 설명할 수 있다.",
    "task와 microtask의 checkpoint 순서 및 rendering starvation 위험을 exact output으로 예측할 수 있다.",
    "setTimeout delay가 deadline 보장이 아니며 0ms·nested clamp·background throttling·long task의 영향을 진단할 수 있다.",
    "setInterval/clearInterval ID와 running state를 소유해 중복 시작·stale callback·unmount leak을 방지할 수 있다.",
    "callback closure·this·error boundary와 named function을 사용해 비동기 실패를 추적할 수 있다.",
    "self-scheduling timeout·interval·requestAnimationFrame을 workload/visibility/cadence 요구에 맞게 선택할 수 있다.",
    "fake scheduler와 state trace로 시간 의존 code를 빠르고 결정론적으로 테스트할 수 있다.",
  ],
  prerequisites: [
    { title: "콜백·scope·closure", reason: "timer가 function reference를 나중에 호출할 때 lexical state와 identity가 어떻게 유지되는지 이미 알고 있습니다.", sessionSlug: "js-02-callback-scope-closure" },
    { title: "DOM 이벤트 등록·전파와 cleanup", reason: "사용자 event도 event loop가 처리하는 task이며 component lifecycle에서 listener와 timer를 함께 정리합니다.", sessionSlug: "js-03-event-model-listeners" },
    { title: "속성·폼·UI 상태 제어", reason: "timer callback이 DOM을 바꿀 때 authoritative running/index state와 접근성 상태를 한 render에서 유지합니다.", sessionSlug: "js-07-dom-attributes-forms" },
  ],
  keywords: ["execution context", "call stack", "run-to-completion", "host API", "event loop", "task", "task source", "task queue", "microtask", "microtask checkpoint", "rendering", "setTimeout", "setInterval", "clearInterval", "timer ID", "nested timer clamp", "throttling", "long task", "performance.now", "Page Visibility", "callback", "fake scheduler", "cleanup"],
  chapters: [
    {
      id: "sync-stack-run-to-completion",
      title: "동기 code는 execution context stack에서 호출·return 순서대로 run-to-completion합니다",
      lead: "한 줄씩 외우지 말고 어떤 function context가 stack top이고 언제 caller로 돌아가는지 그립니다.",
      explanations: [
        "ECMAScript code를 실행할 때 engine은 현재 실행 중인 execution context와 호출 관계를 stack으로 관리합니다. function을 호출하면 새 context가 push되고 return 또는 throw로 끝나면 pop되어 caller의 다음 위치로 돌아갑니다.",
        "원본 syncFunction의 네 console.log는 중간에 host에 제어를 넘기는 연산이 없으므로 첫째부터 넷째까지 순서대로 완료됩니다. 동기라는 말은 느리다는 뜻이 아니라 호출자가 결과/완료를 기다리며 같은 실행 흐름이 이어진다는 뜻입니다.",
        "run-to-completion은 한 task의 JavaScript 실행 도중 다른 timer callback이 같은 thread stack에 임의로 끼어들지 않는다는 중요한 불변식입니다. 현재 callback이 DOM state 절반만 바꾼 순간 다른 timer callback이 동시에 실행되는 식의 preemption은 일반 browser main thread에서 일어나지 않습니다.",
        "하지만 긴 synchronous loop, JSON parse, layout-triggering work가 stack을 오래 점유하면 event·timer·rendering이 기다립니다. 실행 중 data race가 없다는 장점과 main thread 응답이 멈춘다는 비용을 함께 봅니다.",
        "Web Worker는 별도 agent/event loop에서 code를 실행할 수 있지만 DOM main thread와 memory/message 경계가 있습니다. 'JavaScript는 무조건 single-thread'라고 단정하지 않고 한 agent의 execution과 여러 agents를 구분합니다.",
        "stack trace는 현재 synchronous 호출 chain을 잘 보여 주지만 나중 task의 callback은 원래 caller가 return한 뒤 실행되어 stack이 분리됩니다. DevTools async stack 지원과 명시적 operation ID가 비동기 원인을 연결합니다.",
      ],
      concepts: [
        { term: "execution context", definition: "실행 중인 ECMAScript code의 function/script/module 평가에 필요한 lexical environment·realm·state를 묶은 specification record입니다.", detail: ["stack에서 현재 context를 추적합니다.", "function call/return과 연결됩니다."] },
        { term: "run-to-completion", definition: "현재 JavaScript job/task callback이 return 또는 throw할 때까지 다른 callback이 같은 execution stack에 끼어들지 않는 성질입니다.", detail: ["중간 preemption이 없습니다.", "긴 work가 responsiveness를 막을 수 있습니다."] },
        { term: "main thread", definition: "document DOM·style·layout·많은 user interaction과 JavaScript가 공유하는 browser execution thread입니다.", detail: ["긴 task가 UI를 막습니다.", "worker와 경계를 나눕니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "대규모 loop가 도는 동안 click·spinner·timer가 모두 멈춘 것처럼 보인다.", likelyCause: "한 synchronous task가 main thread stack을 오래 점유해 event loop와 rendering opportunity가 돌아오지 못했습니다.", checks: ["Performance trace에서 long task와 scripting duration을 봅니다.", "loop/parse/layout work의 input size를 기록합니다.", "timer 자체가 아니라 main-thread blocking인지 확인합니다."], fix: "work를 algorithmically 줄이고 chunk/yield하거나 DOM이 필요 없는 CPU work를 Worker로 옮기며 사용자 피드백을 task 사이에 render합니다.", prevention: "interaction latency와 long-task budget, worst-case data fixture와 cancellation을 성능 gate에 둡니다." },
      ],
    },
    {
      id: "host-task-event-loop-model",
      title: "Timer는 callback을 병렬 실행하지 않고 host가 task를 준비하면 event loop가 나중에 선택합니다",
      lead: "setTimeout 호출·timer wait·task enqueue·callback execution을 서로 다른 단계로 나눕니다.",
      explanations: [
        "setTimeout은 ECMAScript language function이 아니라 browser Window/Worker host가 제공하는 API입니다. 호출은 timer handle을 설정하고 즉시 return하므로 원본 asyncFunction은 첫째를 출력하고 두 timeout을 등록한 뒤 셋째를 계속 출력합니다.",
        "delay 조건이 충족되면 host의 timer algorithm이 callback을 실행할 task를 준비합니다. callback JavaScript가 timer thread에서 DOM과 동시에 실행되는 것이 아니라 관련 event loop가 runnable task를 선택했을 때 새 stack에서 실행됩니다.",
        "HTML event loop에는 task queues와 task sources가 있습니다. timer, user interaction, networking 등 source별 ordering 규칙이 있고 implementation은 runnable queues 중 하나를 선택할 수 있으므로 모든 종류의 task가 하나의 전역 FIFO queue라는 그림은 지나친 단순화입니다.",
        "한 task를 실행한 뒤 event loop는 microtask checkpoint를 수행하고 필요하면 rendering을 update하는 기회를 가집니다. 실제 algorithm에는 사용자 상호작용·rendering timing·agent integration이 더 있으므로 'queue에서 하나 꺼내는 while(true)'는 mental model일 뿐 specification 전체가 아닙니다.",
        "DOMContentLoaded, click, message, timer callback은 서로 다른 trigger이지만 모두 callback이 실행되는 시점에는 run-to-completion JavaScript입니다. callback 내부 synchronous throw는 그 task의 오류 보고 경로로 가며 timeout을 등록한 caller의 과거 try/catch로 되돌아가지 않습니다.",
        "task order가 중요한 업무 workflow라면 우연한 timer delay로 순서를 맞추지 않습니다. state transition, callback continuation, Promise/async sequence 또는 explicit message protocol로 dependency를 표현합니다.",
      ],
      concepts: [
        { term: "host API", definition: "ECMAScript language 밖에서 browser/Node 같은 host가 제공하고 실행 환경과 event loop에 연결하는 API입니다.", detail: ["setTimeout이 대표적입니다.", "환경별 semantics를 확인합니다."] },
        { term: "task", definition: "event loop가 선택해 callback/code를 run-to-completion하도록 실행하는 work item입니다.", detail: ["timer와 event가 task를 준비할 수 있습니다.", "task source별 queue가 있습니다."] },
        { term: "event loop", definition: "runnable tasks를 선택·실행하고 microtask checkpoint 및 rendering update와 host steps를 조정하는 processing model입니다.", detail: ["단일 global FIFO보다 복잡합니다.", "현재 task가 끝나야 다음 callback이 실행됩니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "setTimeout callback의 throw를 timeout 등록 코드 주위 try/catch가 잡지 못한다.", likelyCause: "caller는 이미 return했고 callback은 나중 task의 새 stack에서 실행됐습니다.", checks: ["throw 시점의 async stack과 task source를 봅니다.", "callback 내부 error boundary가 있는지 확인합니다.", "Promise rejection/전역 error telemetry와 사용자 복구를 구분합니다."], fix: "callback 자체에서 예상 오류를 catch/분류하거나 task runner boundary가 error를 report하고 state를 실패로 전환하게 합니다.", prevention: "timer callback throw/retry/dispose case와 error operation ID를 test합니다." },
      ],
    },
    {
      id: "microtask-checkpoint-rendering",
      title: "현재 task가 끝나면 microtask queue를 비우는 checkpoint가 오고 그 뒤에야 timer task와 rendering 기회가 옵니다",
      lead: "Promise와 queueMicrotask가 0ms timeout보다 먼저 실행되는 이유를 queue 종류와 checkpoint로 설명합니다.",
      explanations: [
        "queueMicrotask는 callback을 microtask queue에 넣습니다. Promise reaction도 host integration을 통해 microtask로 수행됩니다. 현재 script task의 synchronous code가 모두 끝난 뒤 microtask checkpoint에서 queue order대로 실행됩니다.",
        "microtask callback이 새 microtask를 추가하면 checkpoint는 queue가 빌 때까지 계속 처리할 수 있습니다. 재귀 microtask는 timer·user event·rendering에 제어를 돌려주지 않아 starvation을 만들 수 있으므로 큰 work를 microtask로 잘게 나눴다고 자동으로 UI가 반응하는 것은 아닙니다.",
        "DOM mutation을 microtask에서 했다고 바로 paint되는 것은 아닙니다. paint는 event loop의 rendering update opportunity와 browser scheduling에서 일어나며 같은 task/microtask chain이 계속되면 사용자는 중간 state를 보지 못합니다.",
        "microtask는 state invariant를 같은 task 직후 정리하거나 mutation observers/Promise reactions를 처리하는 데 유용하지만 animation frame, long computation yield, network retry delay의 범용 scheduler가 아닙니다.",
        "Node.js는 browser HTML event loop와 별도 phases 및 process.nextTick 같은 ordering을 가집니다. 동일 JavaScript syntax라도 runtime의 공식 execution model을 확인하고 browser exact output을 Node에 무조건 일반화하지 않습니다.",
        "다음 Promise 세션에서는 fulfillment/rejection reaction이 microtask로 이어지는 규칙을 깊게 다룹니다. 현재 세션에서는 task와 microtask order를 읽을 수 있는 공통 기반을 완성합니다.",
      ],
      concepts: [
        { term: "microtask", definition: "현재 JavaScript stack/task가 끝난 뒤 event loop의 microtask checkpoint에서 처리되는 짧은 work item입니다.", detail: ["queueMicrotask/Promise reaction이 사용합니다.", "timer task보다 먼저 처리될 수 있습니다."] },
        { term: "microtask checkpoint", definition: "microtask queue가 빌 때까지 queued microtasks를 수행하는 event loop 단계입니다.", detail: ["새 microtask도 같은 checkpoint에서 이어질 수 있습니다.", "starvation을 주의합니다."] },
        { term: "rendering opportunity", definition: "browser가 style/layout/paint와 animation callbacks 등 rendering update를 수행할 수 있는 event loop 기회입니다.", detail: ["모든 line 뒤 paint하지 않습니다.", "긴 task/microtask가 지연시킵니다."] },
      ],
      codeExamples: [
        {
          id: "task-microtask-order",
          title: "동기 code·queueMicrotask·Promise reaction·0ms timer 순서",
          language: "html",
          filename: "event-loop-order.html",
          purpose: "한 script task가 끝난 뒤 FIFO microtasks를 처리하고 다음 timer task가 실행되는 순서를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>event loop order</title></head>\n<body><pre id=\"out\"></pre><script>\n  const lines = [];\n  lines.push('sync-1');\n  setTimeout(() => {\n    lines.push('timer-task');\n    document.querySelector('#out').textContent = lines.join('\\n');\n  }, 0);\n  queueMicrotask(() => lines.push('microtask-1'));\n  Promise.resolve().then(() => lines.push('promise-reaction'));\n  lines.push('sync-2');\n</script></body></html>",
          walkthrough: [
            { lines: "3-4", explanation: "현재 script task에서 첫 synchronous trace를 기록합니다." },
            { lines: "5-8", explanation: "0ms timer task를 등록하고 callback에서 최종 output을 render합니다." },
            { lines: "9-11", explanation: "두 microtasks를 등록한 뒤 synchronous 마지막 line을 먼저 실행합니다." },
          ],
          run: { environment: ["queueMicrotask와 Promise를 지원하는 modern browser"], command: "browser에서 event-loop-order.html을 열고 결과 확인" },
          output: { value: "sync-1\nsync-2\nmicrotask-1\npromise-reaction\ntimer-task", explanation: ["현재 script task의 sync-1/sync-2가 먼저 완료됩니다.", "등록 순서의 두 microtasks가 checkpoint에서 실행됩니다.", "0ms timer도 다음 task이므로 microtasks 뒤입니다."] },
          experiments: [
            { change: "Promise reaction을 queueMicrotask보다 먼저 등록합니다.", prediction: "두 microtask의 상대 순서가 바뀝니다.", result: "같은 queue의 enqueue order를 관찰합니다." },
            { change: "microtask 안에서 새 queueMicrotask를 등록합니다.", prediction: "새 microtask도 timer task 전에 같은 checkpoint에서 실행됩니다.", result: "무한 재귀가 starvation을 만들 수 있습니다." },
            { change: "timer delay를 -1 또는 NaN으로 바꿉니다.", prediction: "즉시 동기 실행이 되지 않고 host timer normalization 뒤 task로 남습니다.", result: "delay 값과 execution phase를 구분합니다." },
          ],
          sourceRefs: ["web-sync-async-source", "html-event-loops", "html-microtasks", "ecma-execution-contexts"],
        },
      ],
      diagnostics: [
        { symptom: "queueMicrotask로 work를 계속 나눴는데 화면과 click이 여전히 멈춘다.", likelyCause: "microtask가 새 microtask를 계속 enqueue해 checkpoint가 끝나지 않고 rendering/task가 starvation됩니다.", checks: ["Performance trace와 microtask enqueue chain을 봅니다.", "timer/click이 언제 실행되는지 marker를 둡니다.", "work chunk가 task/yield boundary를 만드는지 확인합니다."], fix: "사용자 응답이 필요한 긴 work는 적절한 task scheduling/Worker로 양보하고 microtask는 짧은 invariant 정리에 제한합니다.", prevention: "recursive microtask depth와 interaction latency budget을 test합니다." },
      ],
    },
    {
      id: "timer-delay-clamp-throttle",
      title: "Timer delay는 정확한 실행 시각이 아니라 callback task를 준비하기 전 최소 기준입니다",
      lead: "0ms를 즉시로 읽지 않고 현재 stack, microtasks, runnable task, rendering, clamp와 browser policy를 함께 고려합니다.",
      explanations: [
        "setTimeout(callback, delay)의 delay가 지났다고 callback이 그 순간 CPU를 선점하지 않습니다. timer task가 runnable해도 현재 task·microtasks와 앞서 선택된 work가 끝날 때까지 기다려 actual latency는 더 길 수 있습니다.",
        "delay 0은 synchronous call이 아닙니다. 원본에서 두 1000ms timers를 같은 시점에 등록해도 first/second callbacks의 실제 간격·정확한 벽시계 시각은 보장되지 않고 timer source scheduling과 callback work에 좌우됩니다.",
        "HTML timer algorithm은 깊게 중첩된 timers에 minimum delay clamp를 적용합니다. animation이나 high-frequency polling에 recursive 0ms timeout을 사용하지 않고 목적에 맞는 requestAnimationFrame, events, server push 또는 scheduler를 선택합니다.",
        "user agent는 background page, battery/CPU 정책, inactive frame에서 timers를 추가 throttle/coalesce할 수 있습니다. hidden 동안 매 tick이 정확히 실행됐다고 가정해 count를 올리면 돌아왔을 때 실제 elapsed time과 state가 어긋납니다.",
        "Date.now는 wall clock이라 system clock adjustment 영향을 받을 수 있습니다. duration과 cadence 측정은 monotonic performance.now 계열을 사용하고, 달력/서버 time은 별도 authoritative source와 policy를 둡니다.",
        "string callback `setTimeout('code',...)`은 eval과 비슷한 parsing/security 문제를 만들므로 function reference를 전달합니다. 추가 arguments를 넘길 수 있지만 closure와 explicit parameter object가 읽기 쉬운지 비교합니다.",
      ],
      concepts: [
        { term: "minimum delay", definition: "timer callback이 실행되기 전 적어도 기다리도록 요청하는 threshold이며 deadline이나 정확한 cadence 보장이 아닙니다.", detail: ["실제 실행은 더 늦을 수 있습니다.", "0도 next task입니다."] },
        { term: "timer clamping/throttling", definition: "nested 또는 background/inactive 상황에서 user agent가 timer frequency를 제한하거나 지연하는 정책입니다.", detail: ["환경에 따라 추가 지연됩니다.", "elapsed time으로 복구합니다."] },
        { term: "monotonic clock", definition: "system wall-clock 조정과 분리해 duration 측정에 쓰는 non-decreasing time origin 기반 clock입니다.", detail: ["performance.now를 사용합니다.", "절대 시각 표시는 Date/서버 time과 분리합니다."] },
      ],
      codeExamples: [
        {
          id: "zero-timeout-after-blocking-task",
          title: "0ms timer가 현재 긴 동기 task를 추월하지 못하는 결과",
          language: "html",
          filename: "timeout-blocking.html",
          purpose: "실제 duration 숫자 대신 안정된 trace로 delay 0이 minimum scheduling hint이며 current stack 뒤에 실행됨을 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>timer blocking</title></head>\n<body><pre id=\"out\"></pre><script>\n  const lines = ['scheduled'];\n  setTimeout(() => {\n    lines.push('timeout-ran');\n    document.querySelector('#out').textContent = lines.join('\\n');\n  }, 0);\n  const end = performance.now() + 25;\n  while (performance.now() < end) { /* main-thread work */ }\n  lines.push('blocking-finished');\n</script></body></html>",
          walkthrough: [
            { lines: "3-7", explanation: "0ms timer를 등록하되 callback은 아직 실행하지 않습니다." },
            { lines: "8-10", explanation: "현재 script task가 짧은 busy work로 stack을 점유합니다." },
            { lines: "11", explanation: "동기 work 완료를 기록한 뒤에야 event loop가 timer task를 실행할 수 있습니다." },
          ],
          run: { environment: ["performance.now를 지원하는 modern browser"], command: "browser에서 timeout-blocking.html을 열고 결과 확인" },
          output: { value: "scheduled\nblocking-finished\ntimeout-ran", explanation: ["timer는 scheduled 뒤 등록됩니다.", "현재 task의 busy loop와 마지막 line이 먼저 끝납니다.", "그 뒤 timer task가 선택되어 timeout-ran을 추가합니다."] },
          experiments: [
            { change: "busy duration을 250ms로 늘립니다.", prediction: "순서는 같고 사용자가 느끼는 timer 지연/UI 멈춤이 커집니다.", result: "delay는 maximum latency 보장이 아닙니다." },
            { change: "while 안에서 DOM progress text를 계속 바꿉니다.", prediction: "중간 값이 모두 paint되지 않을 수 있습니다.", result: "paint opportunity를 위해 task를 양보해야 합니다." },
            { change: "page를 background로 보내 timer 간격을 측정합니다.", prediction: "foreground보다 더 throttle될 수 있습니다.", result: "정확 count 대신 elapsed time과 visibility policy를 사용합니다." },
          ],
          sourceRefs: ["web-sync-async-source", "html-timers", "html-event-loops", "high-resolution-time"],
        },
      ],
      diagnostics: [
        { symptom: "setTimeout(...,0)을 썼는데 callback이 수백 ms 뒤 실행된다.", likelyCause: "현재/앞선 long task, microtask chain, background throttling 또는 busy event loop가 timer task 실행을 지연했습니다.", checks: ["scheduled/deadline/actual monotonic timestamps를 기록합니다.", "Performance trace의 long tasks/microtasks를 봅니다.", "document.visibilityState와 device load를 확인합니다."], fix: "blocking work를 줄이거나 양보하고 deadline-sensitive logic은 timer tick count가 아니라 elapsed time으로 계산하며 background policy를 둡니다.", prevention: "CPU throttling/background/large-data latency test와 timer drift telemetry를 둡니다." },
      ],
    },
    {
      id: "interval-handle-lifecycle",
      title: "반복 timer는 handle·running state·cleanup owner를 하나로 묶어야 합니다",
      lead: "setInterval을 시작하는 code만 쓰지 말고 중복 start, stop 전/후, component dispose와 callback-in-flight를 모두 정의합니다.",
      explanations: [
        "setInterval은 delay마다 callback 실행 task를 반복 준비하고 timer ID를 반환합니다. 원본 ex08은 ID를 chk에 저장하고 count가 3이면 clearInterval(chk)를 호출해 유한한 lifecycle을 만든 점이 좋습니다.",
        "clearInterval은 앞으로의 반복 scheduling을 취소하지만 현재 이미 실행 중인 callback을 되감지 않습니다. callback 안에서 clear한 뒤 남은 lines는 계속 실행되므로 return 위치와 state update 순서를 의도적으로 둡니다.",
        "timer ID가 null인지로 running을 명시하고 start에서 이미 running이면 false/no-op, stop에서 없으면 false/no-op으로 만듭니다. 원본 news start를 여러 번 누르면 여러 intervals가 생기고 하나의 timer variable에는 마지막 ID만 남아 이전 intervals를 모두 stop하지 못할 수 있습니다.",
        "stop 뒤 timerId=null로 되돌려 restart가 가능하게 하고 index reset/continue 정책을 정합니다. stop이 pause인지 full reset인지 이름과 UI label, test expected output에 명시합니다.",
        "component가 DOM에서 제거돼도 global timer는 자동 취소되지 않습니다. callback이 detached node와 state closure를 보유해 memory/오류를 만들 수 있어 mount owner가 dispose에서 timer와 listener를 함께 정리합니다.",
        "timer APIs는 같은 ID map을 공유해 clearTimeout/clearInterval이 상호 취소 가능할 수 있지만 의도를 보존하기 위해 matching clear API를 사용합니다. numeric ID value 자체를 업무 ID나 duration으로 해석하지 않습니다.",
      ],
      concepts: [
        { term: "timer handle", definition: "host timer entry를 취소하기 위해 반환되는 opaque identifier입니다.", detail: ["실행 순서/시간값이 아닙니다.", "owner가 저장하고 clear합니다."] },
        { term: "idempotent start/stop", definition: "같은 start 또는 stop action을 여러 번 호출해도 timer 수와 logical state가 한 번 호출한 것과 같은 lifecycle contract입니다.", detail: ["중복 interval을 막습니다.", "boolean/result로 상태를 알릴 수 있습니다."] },
        { term: "dispose", definition: "component/session 종료 시 timer·listener·observer·reference 같은 external resources를 해제하는 lifecycle operation입니다.", detail: ["DOM removal과 별개입니다.", "반복 mount leak을 막습니다."] },
      ],
      codeExamples: [
        {
          id: "interval-three-ticks-clear",
          title: "세 번 실행한 interval의 명시적 종료",
          language: "html",
          filename: "interval-three.html",
          purpose: "환경별 wall-clock 문자열 대신 count와 stopped state로 원본 세 번 interval 종료를 결정론적으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>interval clear</title></head>\n<body><pre id=\"out\"></pre><script>\n  const lines = [];\n  let count = 0;\n  const intervalId = setInterval(() => {\n    count += 1;\n    lines.push(`tick=${count}`);\n    if (count === 3) {\n      clearInterval(intervalId);\n      lines.push(`stopped=${count}`);\n      setTimeout(() => {\n        document.querySelector('#out').textContent = lines.join('\\n');\n      }, 0);\n    }\n  }, 5);\n</script></body></html>",
          walkthrough: [
            { lines: "3-5", explanation: "trace와 count를 준비하고 반환 timer handle을 저장합니다." },
            { lines: "6-10", explanation: "각 callback task에서 count를 하나씩 올리고 세 번째에 matching clear를 호출합니다." },
            { lines: "11-15", explanation: "종료 trace 뒤 별도 task에서 output을 render해 추가 interval tick이 없음을 확인합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 interval-three.html을 열고 결과 확인" },
          output: { value: "tick=1\ntick=2\ntick=3\nstopped=3", explanation: ["interval callback은 순차 task로 세 번 실행됩니다.", "세 번째 callback에서 clear해 이후 반복 scheduling을 중단합니다.", "wall-clock 시각이 아니라 logical count를 assertion합니다."] },
          experiments: [
            { change: "clearInterval을 제거합니다.", prediction: "count와 log가 계속 증가하고 test/page lifecycle이 끝나지 않습니다.", result: "반복 resource에는 종료 조건이 필수입니다." },
            { change: "clear 뒤 count=0을 설정합니다.", prediction: "stopped output 정책이 달라집니다.", result: "pause와 reset을 별도 API/contract로 정합니다." },
            { change: "callback work를 delay보다 길게 만듭니다.", prediction: "callback은 동시에 실행되지 않지만 cadence가 밀리고 task backlog/drift가 생길 수 있습니다.", result: "interval이 workload duration을 고려하지 않습니다." },
          ],
          sourceRefs: ["web-timer-source", "html-timers", "html-event-loops"],
        },
      ],
      diagnostics: [
        { symptom: "시작 button을 세 번 누른 뒤 stop을 눌러도 뉴스가 계속 바뀐다.", likelyCause: "중복 setInterval이 생성됐고 하나의 variable이 마지막 handle만 보유해 이전 timers가 orphaned됐습니다.", checks: ["active start count와 반환 handles를 계측합니다.", "start guard의 running state를 봅니다.", "mount/unmount마다 dispose가 호출되는지 확인합니다."], fix: "timerId!==null이면 start를 no-op하고 stop/dispose에서 clear 후 null로 되돌리며 component당 timer owner를 하나로 제한합니다.", prevention: "rapid double-click, repeated mount/unmount, stop-before-start/restart lifecycle test를 둡니다." },
      ],
    },
    {
      id: "callback-closure-this-errors",
      title: "나중에 호출되는 callback은 lexical state를 보존하지만 caller stack·method this·error boundary는 보존하지 않습니다",
      lead: "function을 전달하는 순간 무엇을 capture하고 누가 어떤 arguments/this로 언제 호출하는지 contract를 적습니다.",
      explanations: [
        "callback은 다른 function/API에 값으로 전달된 function입니다. timer에는 `timer1` reference를 전달해야 하며 `timer1()`을 전달하면 등록 시점에 즉시 호출한 return value가 전달됩니다.",
        "closure는 timerId, count, news, index, DOM root 같은 lexical bindings에 접근할 수 있습니다. convenient하지만 오래 사는 interval이 큰 object/removed DOM을 capture하면 memory retention과 stale state를 만듭니다.",
        "ordinary method를 `setTimeout(controller.tick,...)`처럼 분리해 전달하면 method call receiver가 사라져 this가 controller가 아닐 수 있습니다. arrow wrapper, bind 또는 this를 쓰지 않는 lexical function/module state를 선택합니다.",
        "timer callback의 synchronous throw는 해당 task에서 report됩니다. 다음 interval은 환경/API behavior에 따라 계속 scheduling될 수 있어 오류가 난 상태에서 반복 mutation이 이어질 수 있습니다. callback boundary가 error를 기록하고 stop/failure transition을 수행하게 합니다.",
        "callback nesting은 indentation보다 error/cancellation/ownership이 여러 갈래로 퍼지는 것이 문제입니다. 이름 있는 단계, result/error callback convention 또는 Promise/async로 dependency를 표현하고 single settlement를 보장합니다.",
        "DevTools에서 익명 arrow만 보이는 것보다 이름 있는 tick/render/stop functions와 operationId가 stack/telemetry를 이해하기 쉽습니다. 그러나 secret/news 사용자 content 전체를 log하지 않습니다.",
      ],
      concepts: [
        { term: "callback contract", definition: "host/library가 function을 언제, 몇 번, 어떤 arguments/this/error/cancellation 규칙으로 호출하는지에 대한 합의입니다.", detail: ["function reference를 전달합니다.", "lifecycle을 문서화합니다."] },
        { term: "stale closure", definition: "callback이 등록 시점 또는 과거 lifecycle의 state/reference를 계속 사용해 현재 UI와 어긋나는 현상입니다.", detail: ["generation/token으로 무효화할 수 있습니다.", "dispose에서 references를 끊습니다."] },
        { term: "async error boundary", definition: "나중 task/callback에서 발생한 error를 분류·report·cleanup·state transition하는 callback 내부 또는 runner 경계입니다.", detail: ["과거 caller try/catch가 아닙니다.", "중단/재시도 정책을 둡니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "setTimeout(controller.tick,1000) 안에서 this.items가 undefined다.", likelyCause: "method를 function value로 전달해 original receiver가 호출 형태에서 사라졌습니다.", checks: ["callback 등록 값이 method reference인지 invocation인지 봅니다.", "callback 안 this와 strict/module mode를 확인합니다.", "bind/arrow/lexical state 대안을 비교합니다."], fix: "`()=>controller.tick()` wrapper나 bound function을 한 번 저장하거나 this 없는 closure/controller function으로 설계합니다.", prevention: "callback invocation context를 type/test로 명시하고 add/remove에 동일 bound identity를 보존합니다." },
        { symptom: "timer callback에서 오류가 나도 interval이 계속 돌아 반복 error가 쌓인다.", likelyCause: "callback error boundary가 failure state와 clearInterval을 수행하지 않았습니다.", checks: ["첫 throw 뒤 timer running state와 callback count를 봅니다.", "global error telemetry만 있고 local cleanup이 없는지 확인합니다.", "retry 가능한 오류인지 분류합니다."], fix: "tick을 try/catch boundary로 감싸 예상 오류에서 stop/cleanup 후 사용자 recovery를 제공하고 programmer error도 operation context와 함께 report합니다.", prevention: "callback throw, render node missing, dispose race와 retry budget test를 둡니다." },
      ],
    },
    {
      id: "news-rotator-state-controller",
      title: "자동 뉴스는 timer가 아니라 index·running·render·pause를 소유하는 controller입니다",
      lead: "전역 timer와 cnt를 흩어 놓지 않고 start/stop/tick/dispose 불변식을 한 closure에 모읍니다.",
      explanations: [
        "원본 news 배열과 textContent 사용은 안전한 출발점입니다. start_news를 반복 호출하는 문제, 첫 뉴스가 2초 뒤에만 보이는 빈 상태, stop/restart index 정책, 접근성 자동 회전 제어를 controller에서 보강합니다.",
        "createRotator는 schedule/cancel/render dependencies를 받아 browser timer에서 분리합니다. production은 setInterval/clearInterval adapter, test는 callback Map을 가진 fake scheduler를 주입해 실제 2초를 기다리지 않습니다.",
        "start는 이미 running이면 false를 반환하고 첫 item을 즉시 render한 뒤 interval 하나를 설정합니다. tick은 current item을 render하고 modulo로 index를 순환시키며 empty items는 명시 error/empty state로 처리합니다.",
        "stop은 handle을 clear하고 null로 바꿔 재시작 가능하게 합니다. index를 유지하면 pause/resume, 0으로 바꾸면 reset이므로 두 semantics를 이름으로 분리할 수 있습니다. dispose는 stop과 DOM/controller references 정리를 수행합니다.",
        "자동 회전 content에는 명확한 pause/start button을 제공하고 focus가 component 안에 있거나 pointer hover일 때 pause하는 정책을 검토합니다. reduced motion preference와 사용자가 중지한 선택을 존중합니다.",
        "매 2초마다 aria-live assertive로 긴 뉴스 전체를 읽으면 screen reader 사용을 방해할 수 있습니다. carousel guidance에 따라 rotation control과 announcement mode를 설계하고 manual navigation에서는 selected item과 position을 적절히 알립니다.",
      ],
      concepts: [
        { term: "scheduler injection", definition: "시간 API를 직접 고정 호출하지 않고 schedule/cancel interface를 dependency로 받아 production timer와 fake test clock을 교체하는 설계입니다.", detail: ["결정론적 test가 가능합니다.", "timer policy를 한 곳에 둡니다."] },
        { term: "rotation controller", definition: "items·index·running handle·render·start/stop/dispose를 소유하는 component lifecycle object/closure입니다.", detail: ["중복 timer를 막습니다.", "pause/reset semantics를 명시합니다."] },
        { term: "auto-rotation pause", definition: "사용자 제어, focus/hover, visibility와 motion preference에 따라 자동 content 변경을 멈추는 접근성/UX policy입니다.", detail: ["pause button을 제공합니다.", "사용자 선택을 존중합니다."] },
      ],
      codeExamples: [
        {
          id: "news-rotator-fake-scheduler",
          title: "중복 시작을 막는 뉴스 controller와 fake scheduler",
          language: "html",
          filename: "news-controller.html",
          purpose: "실제 시간을 기다리지 않고 immediate first render, duplicate start, manual ticks, stop cleanup을 exact output으로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>news controller</title></head>\n<body><pre id=\"out\"></pre><script>\n  function createRotator(items, { schedule, cancel, render }) {\n    let timerId = null;\n    let index = 0;\n    function tick() {\n      render(items[index]);\n      index = (index + 1) % items.length;\n    }\n    return {\n      start() {\n        if (timerId !== null) return false;\n        tick();\n        timerId = schedule(tick, 2000);\n        return true;\n      },\n      stop() {\n        if (timerId === null) return false;\n        cancel(timerId);\n        timerId = null;\n        return true;\n      },\n    };\n  }\n  let nextId = 1;\n  const jobs = new Map();\n  const schedule = callback => { const id = nextId++; jobs.set(id, callback); return id; };\n  const cancel = id => jobs.delete(id);\n  const rendered = [];\n  const rotator = createRotator(['뉴스1', '뉴스2', '뉴스3'], { schedule, cancel, render:value => rendered.push(value) });\n  const lines = [];\n  lines.push(`start-first=${rotator.start()}`);\n  lines.push(`start-again=${rotator.start()}`);\n  lines.push(`pending=${jobs.size}`);\n  jobs.get(1)();\n  jobs.get(1)();\n  lines.push(`rendered=${rendered.join('|')}`);\n  lines.push(`stop=${rotator.stop()}`);\n  lines.push(`pending-after-stop=${jobs.size}`);\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-22", explanation: "controller closure가 timerId/index와 tick/start/stop lifecycle을 소유하고 중복 start를 no-op합니다." },
            { lines: "23-28", explanation: "callback Map 기반 fake scheduler가 handle을 만들고 cancel에서 제거합니다." },
            { lines: "29-39", explanation: "첫 start/중복 start, 두 manual ticks, stop 뒤 pending jobs를 실제 delay 없이 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 news-controller.html을 열고 결과 확인" },
          output: { value: "start-first=true\nstart-again=false\npending=1\nrendered=뉴스1|뉴스2|뉴스3\nstop=true\npending-after-stop=0", explanation: ["첫 start는 즉시 뉴스1을 render하고 job 하나를 만듭니다.", "두 번째 start는 false여서 중복 job이 생기지 않습니다.", "fake ticks가 뉴스2/뉴스3을 render하고 stop이 pending job을 제거합니다."] },
          experiments: [
            { change: "start guard를 제거하고 두 번 start합니다.", prediction: "jobs가 2가 되고 rotation speed/stop ownership이 깨집니다.", result: "running handle을 authoritative state로 둡니다." },
            { change: "stop 후 다시 start하고 저장된 새 job을 실행합니다.", prediction: "index 유지 정책이면 다음 cycle 뉴스1부터 이어집니다.", result: "pause/resume와 reset semantics를 test합니다." },
            { change: "items=[]로 생성합니다.", prediction: "현재 tick은 undefined/modulo NaN 문제가 생깁니다.", result: "constructor에서 non-empty items를 검증하거나 empty UI를 정의합니다." },
          ],
          sourceRefs: ["web-news-source", "html-timers", "wai-carousel"],
        },
      ],
      diagnostics: [
        { symptom: "뉴스가 두 배·세 배 속도로 바뀌고 stop 뒤에도 일부 rotation이 남는다.", likelyCause: "start가 매 click마다 새 interval을 만들고 마지막 handle만 저장했습니다.", checks: ["active schedule count와 running handle state를 봅니다.", "start return/no-op contract를 확인합니다.", "fake scheduler pending jobs로 재현합니다."], fix: "controller 하나가 handle/index를 소유하고 running 중 start를 거부하며 stop/dispose가 clear+null을 수행합니다.", prevention: "double-click/restart/dispose fake-clock lifecycle test를 둡니다." },
        { symptom: "screen reader가 2초마다 새 긴 뉴스를 읽어 다른 작업을 방해한다.", likelyCause: "자동 회전 region을 과도한 live announcement로 만들고 pause control/focus policy를 제공하지 않았습니다.", checks: ["live politeness와 rotation control accessible name을 확인합니다.", "focus/hover/reduced motion에서 자동 회전을 test합니다.", "manual navigation announcement를 분리합니다."], fix: "명확한 pause/start를 제공하고 APG carousel rotation behavior를 적용하며 자동 변화 announcement를 최소화합니다.", prevention: "screen-reader/keyboard/reduced-motion/visibility accessibility test를 둡니다." },
      ],
    },
    {
      id: "scheduling-choice-visibility-drift",
      title: "Interval·self-scheduling timeout·animation frame은 cadence·work completion·visibility 요구로 선택합니다",
      lead: "한 API를 모든 반복 작업에 쓰지 않고 다음 실행을 언제 계산해야 하는지와 숨김 상태 policy를 먼저 정합니다.",
      explanations: [
        "setInterval은 nominal cadence가 단순하지만 callback work가 길거나 async operation이 아직 끝나지 않아도 다음 ticks가 예정될 수 있습니다. JavaScript callback 자체는 동시에 실행되지 않아도 여러 network requests/logical operations가 겹칠 수 있습니다.",
        "self-scheduling setTimeout은 한 tick work가 완료된 뒤 다음 timer를 등록해 overlap/backlog를 줄이고 dynamic backoff를 적용하기 쉽습니다. 그러나 callback이 async라면 await/settlement 뒤 scheduling하도록 Promise 세션의 error/cancel model과 연결합니다.",
        "화면 animation은 requestAnimationFrame을 사용해 browser rendering cadence와 visibility policy에 맞춥니다. elapsed timestamp로 position을 계산하고 frame count를 시간으로 착각하지 않습니다.",
        "polling은 network/server push 가능성, retry backoff+jitter, offline/visibility, cache validator와 rate limit을 고려합니다. fixed 1초 timer로 모든 client가 동시에 요청하면 thundering herd가 생길 수 있습니다.",
        "visibilitychange에서 document.hidden이면 cosmetic rotation을 pause하고 visible 복귀 시 현재 elapsed/state를 재계산합니다. 중요한 deadline은 client timer가 아니라 server timestamp와 authoritative state로 검증합니다.",
        "drift correction은 intended next time과 performance.now 차이를 사용하되 missed ticks를 전부 한꺼번에 replay할지 latest state로 건너뛸지 domain policy를 정합니다. 뉴스 rotator는 latest/next item, 회계 job은 server-side durable scheduler처럼 요구가 다릅니다.",
      ],
      concepts: [
        { term: "self-scheduling timeout", definition: "현재 work 완료·결과를 확인한 뒤 다음 setTimeout을 등록하는 반복 pattern입니다.", detail: ["overlap을 줄입니다.", "backoff/동적 delay에 적합합니다."] },
        { term: "timer drift", definition: "요청한 nominal schedule과 실제 callback 실행 시각 차이가 work·event loop·throttling으로 누적되는 현상입니다.", detail: ["monotonic elapsed를 측정합니다.", "missed-tick policy를 정합니다."] },
        { term: "visibility policy", definition: "document가 hidden/visible일 때 timer·animation·polling을 pause, reduce 또는 resynchronize하는 lifecycle 규칙입니다.", detail: ["battery/network를 절약합니다.", "deadline은 server state로 검증합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "background에서 돌아온 뒤 countdown이 실제 시각보다 몇 분 늦다.", likelyCause: "throttled interval tick count를 elapsed time처럼 사용했습니다.", checks: ["visibility state와 actual monotonic/wall/server timestamps를 비교합니다.", "count-- 기반인지 deadline-now 기반인지 봅니다.", "missed ticks 복구 policy를 확인합니다."], fix: "authoritative deadline에서 현재 time을 빼 매 render 재계산하고 hidden/visible에서 pause/resync하며 server가 만료를 검증합니다.", prevention: "background/sleep/system-clock-change/offline 복귀 integration test를 둡니다." },
      ],
    },
    {
      id: "deterministic-testing-observability",
      title: "시간 code는 실제 sleep보다 fake clock·state trace·long-task 관측으로 검증합니다",
      lead: "테스트가 느리고 flaky하면 delay를 늘리지 말고 clock과 scheduler dependency를 통제합니다.",
      explanations: [
        "실제 2초를 기다리는 test는 CI 부하와 timer scheduling에 따라 flaky하고 suite를 느리게 만듭니다. scheduler를 주입하거나 test framework fake timers로 pending callbacks를 원하는 시점에 advance합니다.",
        "fake clock만으로 browser event loop와 paint/accessibility를 모두 증명할 수 없습니다. unit test에서 start/stop/index/error를 확인하고 소수의 real-browser test에서 task/microtask order, focus/visibility와 rendering behavior를 검증합니다.",
        "assertion은 locale wall-clock 문자열보다 logical trace, callback count, pending handles, running state와 monotonic range를 사용합니다. 정확 ms equality 대신 minimum/maximum budget을 환경에 맞게 둡니다.",
        "Long Tasks API와 Performance timeline은 main-thread blocking을 관찰하는 데 도움이 되지만 browser support·buffering·privacy resolution을 확인합니다. trace marker와 user interaction latency를 함께 분석합니다.",
        "timer telemetry는 operation type, requested delay bucket, actual delay bucket, visibility, cancellation reason 정도로 제한합니다. 뉴스 content, user identifiers, 전체 DOM이나 callback closure data를 log하지 않습니다.",
        "failure injection은 callback throw, missing DOM, stop during tick, repeated start, hidden/resume, offline/slow work를 포함합니다. cleanup invariant는 test 종료 후 pending timer/listener/observer가 0인지 확인합니다.",
      ],
      concepts: [
        { term: "fake clock/scheduler", definition: "test가 time advancement과 queued callbacks를 직접 통제하는 deterministic dependency입니다.", detail: ["실제 sleep을 제거합니다.", "pending jobs를 assert합니다."] },
        { term: "logical trace", definition: "환경별 시각 대신 sync/task/microtask/tick/stop 같은 의미 있는 state transition 순서를 기록한 검증 출력입니다.", detail: ["exact output이 안정적입니다.", "operation ID를 사용할 수 있습니다."] },
        { term: "long task", definition: "main thread를 오래 점유해 user interaction과 rendering을 지연시키는 task를 관측하는 performance model/API입니다.", detail: ["원인을 trace로 찾습니다.", "timer 지연과 구분합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "CI에서 timer test가 가끔 실패해 wait 시간을 2초에서 5초로 늘렸다.", likelyCause: "실제 clock/event loop 부하에 의존하는 flaky test를 delay 증가로 숨겼습니다.", checks: ["test가 actual sleep과 exact ms equality를 쓰는지 봅니다.", "scheduler dependency를 주입할 수 있는지 확인합니다.", "real-browser가 필요한 behavior와 unit lifecycle을 분리합니다."], fix: "fake scheduler로 callbacks를 advance하고 logical state를 assert하며 필요한 소수 E2E만 range/condition polling으로 검증합니다.", prevention: "test 종료 pending handle 0, no arbitrary sleep rule과 deterministic trace helper를 둡니다." },
      ],
      expertNotes: [
        "Task scheduling priority와 scheduler APIs는 지원·표준 상태를 확인해 progressive enhancement로 사용하고 core correctness를 특정 experimental API에만 의존하지 않습니다.",
        "Shared memory/Atomics/Workers 환경에서는 여러 agents의 happens-before와 data race를 별도 concurrency model로 학습해야 하며 현재 main-thread event loop 설명만으로 충분하지 않습니다.",
        "Timer resolution은 security/privacy 완화로 제한될 수 있습니다. 성능 측정에 불필요한 고해상도 fingerprinting 데이터를 수집하지 않습니다.",
      ],
    },
  ],
  lab: {
    title: "원본 한 줄 뉴스를 실행 모델·수명·접근성·fake time이 검증되는 rotation controller로 재구축하기",
    scenario: "현재 code는 start를 누를 때마다 interval을 추가하고 마지막 handle만 저장합니다. 첫 뉴스는 2초 동안 비어 있고 stop/reset 정책, error cleanup, background throttling, 자동 회전 접근성과 deterministic test가 없습니다.",
    setup: [
      "원본 day09 ex07/ex08/ex09 callback 파일 3개를 read-only evidence로 준비합니다.",
      "modern browser DevTools Performance와 fake scheduler, visible/hidden page scenario를 준비합니다.",
      "empty/1/여러 뉴스, rapid start/stop/restart, callback throw, missing/detached output root fixture를 준비합니다.",
      "keyboard·screen reader·reduced motion·focus/hover 자동 회전 pause scenario를 준비합니다.",
    ],
    steps: [
      "원본 sync/async 출력의 stack→timer registration→task execution 순서를 diagram/trace로 작성합니다.",
      "sync·microtask·timer exact example을 실행해 task/microtask/rendering boundary를 확인합니다.",
      "schedule/cancel/now dependencies와 items/index/timerId state를 소유하는 createRotator를 작성합니다.",
      "start를 idempotent하게 만들고 첫 item 즉시 render, stop/pause/reset/dispose semantics를 분리합니다.",
      "tick callback error에서 stop·failure UI·privacy-safe telemetry를 실행하고 stale generation을 무시합니다.",
      "visibilitychange/focus/hover/reduced-motion에서 auto rotation을 pause/resume하고 명확한 button label/state를 제공합니다.",
      "fake scheduler로 duplicate start, manual ticks, wrap, stop, restart, dispose, error를 실제 wait 없이 test합니다.",
      "real browser에서 background throttling, long task, keyboard/screen reader와 pending resources 0을 검증합니다.",
    ],
    expectedResult: [
      "sync/task/microtask 출력 순서가 실행 모델 설명과 일치하고 0ms를 synchronous로 오해하지 않습니다.",
      "어떤 rapid action에서도 active timer는 최대 하나이며 stop/dispose 뒤 pending job은 0입니다.",
      "첫 뉴스는 즉시 보이고 index wrap/restart 정책과 callback error 복구가 결정론적입니다.",
      "background 복귀에서 tick count를 시간으로 쓰지 않고 elapsed/current state로 resynchronize합니다.",
      "자동 회전은 사용자가 pause할 수 있고 focus/hover/motion preference와 screen-reader announcement를 존중합니다.",
      "tests는 arbitrary sleep 없이 빠르게 통과하고 telemetry에 news/user/DOM raw content가 없습니다.",
    ],
    cleanup: ["모든 interval/timeout을 clear하고 visibility/focus/listener와 fake scheduler jobs를 제거합니다.", "Performance recordings, DevTools saved node references와 synthetic news/error payload를 삭제합니다."],
    extensions: ["self-scheduling async timeout에 exponential backoff·jitter·AbortSignal을 추가합니다.", "Web Worker에서 CPU work를 처리하고 main thread message task로 render하는 pipeline을 비교합니다.", "requestAnimationFrame 기반 progress와 timer 기반 business deadline을 같은 page에서 분리 구현합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 동기/비동기 log를 stack·task·microtask exact trace로 다시 만들고 출력 순서를 설명하세요.", requirements: ["sync function call/return stack을 그립니다.", "queueMicrotask, Promise reaction, setTimeout 0을 포함합니다.", "현재 task와 checkpoint/next task를 구분합니다.", "긴 synchronous work가 0ms timer를 지연하는 결과를 실행합니다."], hints: ["timer callback은 등록 시 호출되지 않습니다.", "microtasks는 현재 stack이 빈 뒤 timer task 전에 처리됩니다."], expectedOutcome: "각 line이 어느 execution context/queue 단계에서 실행되는지 암기 없이 예측합니다.", solutionOutline: ["등록 순서와 실행 순서를 두 columns로 나눕니다.", "task 경계마다 stack과 microtask queue를 snapshot합니다."] },
    { difficulty: "응용", prompt: "중복 시작·pause/resume·error cleanup이 가능한 뉴스 rotator를 fake scheduler로 구현하세요.", requirements: ["items/index/timerId를 controller가 소유합니다.", "start/stop을 idempotent하게 만듭니다.", "첫 item immediate render와 empty/error state를 정의합니다.", "fake jobs로 ticks/wrap/restart/dispose를 검증합니다.", "pause control과 focus/hover/reduced-motion policy를 구현합니다."], hints: ["timerId null을 running invariant로 사용할 수 있습니다.", "자동 변경을 aria-live로 과도하게 읽지 않습니다."], expectedOutcome: "실제 시간을 기다리지 않고 lifecycle과 접근성이 검증된 rotation component가 완성됩니다.", solutionOutline: ["scheduler interface부터 만듭니다.", "production adapter와 fake adapter를 같은 contract로 test합니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 timer·polling·animation scheduling 및 cleanup 표준을 설계하세요.", requirements: ["task/microtask/rendering mental model을 포함합니다.", "interval/self-timeout/rAF/Worker 선택표를 만듭니다.", "visibility, drift, monotonic/server deadline, backoff/jitter 정책을 정의합니다.", "mount/dispose/error/cancel/stale generation contract를 포함합니다.", "fake-clock, real-browser, long-task, accessibility, privacy telemetry gate를 설계합니다."], hints: ["delay는 deadline이 아닙니다.", "client timer는 durable job scheduler나 server authorization이 아닙니다."], expectedOutcome: "기능팀이 중복 timer·flaky test·background drift·자동 회전 접근성 문제 없이 반복 작업을 구현하는 표준이 완성됩니다.", solutionOutline: ["work source→queue→callback→render→cleanup sequence를 그립니다.", "각 scheduler의 owner와 cancellation reason을 표로 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "setTimeout callback은 별도 thread에서 DOM과 동시에 실행되나요?", answer: "아닙니다. browser host가 task를 준비하고 관련 event loop가 선택하면 main-thread JavaScript stack에서 run-to-completion합니다." },
    { question: "0ms timeout은 현재 function return 전에 실행되나요?", answer: "아닙니다. 현재 task와 microtask checkpoint 뒤의 timer task로 실행됩니다." },
    { question: "모든 task가 하나의 global FIFO인가요?", answer: "아닙니다. 여러 task sources/queues와 event-loop selection rules가 있어 단일 FIFO는 단순화된 mental model입니다." },
    { question: "queueMicrotask와 Promise reaction은 보통 timer보다 언제 실행되나요?", answer: "현재 task가 끝난 뒤 microtask checkpoint에서, 다음 timer task가 선택되기 전에 실행됩니다." },
    { question: "microtask로 긴 work를 쪼개면 paint가 자동으로 중간마다 되나요?", answer: "아닙니다. recursive microtasks가 checkpoint를 계속 채우면 rendering과 tasks를 starvation시킬 수 있습니다." },
    { question: "timer delay 1000은 정확히 1000ms 뒤 실행을 보장하나요?", answer: "아닙니다. 최소 대기 기준이며 event loop 부하·clamp·background throttling으로 더 늦을 수 있습니다." },
    { question: "clearInterval은 현재 실행 중인 callback의 나머지 lines도 취소하나요?", answer: "아닙니다. 앞으로의 반복 scheduling을 취소하며 현재 callback은 return까지 계속됩니다." },
    { question: "start를 반복 호출하면 왜 마지막 stop으로 모두 멈추지 않을 수 있나요?", answer: "여러 intervals 중 마지막 handle만 variable에 남아 이전 handles가 orphaned될 수 있기 때문입니다." },
    { question: "script로 callback을 등록할 때 timer1과 timer1()의 차이는 무엇인가요?", answer: "timer1은 function reference를 나중 호출하도록 전달하고 timer1()은 지금 호출한 return value를 전달합니다." },
    { question: "background countdown을 tick count로 계산하면 왜 틀릴 수 있나요?", answer: "timer가 throttle될 수 있어 실제 elapsed time과 callback 횟수가 일치하지 않기 때문입니다." },
    { question: "시간 test에 실제 2초 sleep이 필수인가요?", answer: "아닙니다. lifecycle은 fake scheduler/clock으로 결정론적으로 test하고 일부 browser integration만 실제 scheduling을 검증합니다." },
    { question: "자동 회전 뉴스에 stop button만 있으면 접근성이 끝나나요?", answer: "아닙니다. focus/hover·motion preference·announcement·keyboard label/state와 사용자 pause 선택도 설계해야 합니다." },
  ],
  completionChecklist: [
    "execution context stack과 synchronous call/return을 단계별로 그렸다.",
    "host timer registration과 callback task execution을 다른 단계로 구분했다.",
    "task source/queue가 단일 global FIFO보다 복잡함을 설명했다.",
    "현재 task→microtask checkpoint→timer task→rendering 기회의 순서를 exact output으로 확인했다.",
    "recursive microtask starvation과 long synchronous task를 Performance trace로 진단했다.",
    "0ms/minimum delay, nested clamp와 background throttling을 deadline과 구분했다.",
    "duration에는 monotonic clock, 업무 deadline에는 server/authoritative time을 사용했다.",
    "interval handle과 running state를 owner 하나가 저장하고 중복 start를 막았다.",
    "stop/dispose에서 clear 후 handle=null과 listener/reference cleanup을 수행했다.",
    "callback reference/invocation, closure retention, this와 async error boundary를 test했다.",
    "interval/self-timeout/rAF/Worker를 workload와 visibility 요구로 선택했다.",
    "news rotation에 immediate first render, pause/reset policy와 접근성 control을 제공했다.",
    "fake scheduler로 ticks/error/restart/dispose를 arbitrary sleep 없이 검증했다.",
    "production telemetry에 user/news/raw DOM content 없이 delay/visibility/cancel state만 남겼다.",
  ],
  nextSessions: [],
  sources: [
    { id: "web-sync-async-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex07_callback.html", usedFor: ["synchronous four logs", "two setTimeout callbacks", "1 second delay", "first/third immediate order", "sync/async comments"], evidence: "첫째·셋째가 현재 stack에서 먼저 실행되고 둘째·넷째가 timer tasks로 이어지는 원본을 task/microtask/event-loop exact trace로 확장했습니다." },
    { id: "web-timer-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex08_callback.html", usedFor: ["callback definition", "setTimeout", "setInterval", "timer handle", "three-tick count", "clearInterval", "current time logging"], evidence: "세 번 뒤 interval handle을 clear하는 원본을 minimum delay·monotonic time·lifecycle/error/fake-clock 검증으로 보강했습니다." },
    { id: "web-news-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex09_callback.html", usedFor: ["news array", "timer/index globals", "start/stop", "textContent", "modulo-like wrap", "2-second rotation"], evidence: "한 줄 뉴스 start/stop 흐름을 중복 방지·immediate render·controller dispose·visibility와 자동 회전 접근성 capstone으로 확장했습니다." },
    { id: "ecma-execution-contexts", repository: "Ecma International TC39", path: "executable-code-and-execution-contexts.html#sec-execution-contexts", publicUrl: "https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html#sec-execution-contexts", usedFor: ["execution context stack", "running context", "call/return", "agent execution", "jobs"], evidence: "동기 function stack과 host callback 실행을 구분하는 ECMAScript language execution model의 기준으로 사용했습니다." },
    { id: "html-event-loops", repository: "WHATWG HTML Standard", path: "webappapis.html#event-loops", publicUrl: "https://html.spec.whatwg.org/multipage/webappapis.html#event-loops", usedFor: ["event loop", "tasks", "task queues/sources", "microtask checkpoint", "rendering update", "run-to-completion integration"], evidence: "browser task selection·microtask·rendering 순서를 단일 global FIFO로 과도하게 단순화하지 않는 current processing model에 사용했습니다." },
    { id: "html-microtasks", repository: "WHATWG HTML Standard", path: "webappapis.html#microtask-queuing", publicUrl: "https://html.spec.whatwg.org/multipage/webappapis.html#microtask-queuing", usedFor: ["queueMicrotask", "microtask queue", "checkpoint", "exception reporting", "starvation"], evidence: "queueMicrotask와 Promise reaction이 timer task 앞에서 실행되는 exact output과 recursive starvation 설명의 기준으로 사용했습니다." },
    { id: "html-timers", repository: "WHATWG HTML Standard", path: "timers-and-user-prompts.html#timers", publicUrl: "https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers", usedFor: ["setTimeout/setInterval", "timer initialization", "handles", "clear", "nesting level/minimum delay", "task scheduling"], evidence: "delay가 exact deadline이 아니며 timer handle·repeat·nested clamp를 갖는 current browser timer semantics의 기준으로 사용했습니다." },
    { id: "page-visibility", repository: "W3C Web Performance Working Group", path: "TR/page-visibility-2/", publicUrl: "https://www.w3.org/TR/page-visibility-2/", usedFor: ["document visibilityState", "hidden", "visibilitychange", "background policy", "resource reduction"], evidence: "hidden page에서 cosmetic rotation/polling을 pause하고 visible 복귀 시 resynchronize하는 lifecycle 기준으로 사용했습니다." },
    { id: "high-resolution-time", repository: "W3C Web Performance Working Group", path: "TR/hr-time-3/", publicUrl: "https://www.w3.org/TR/hr-time-3/", usedFor: ["performance.now", "time origin", "monotonic duration", "resolution/privacy", "clock comparison"], evidence: "timer drift와 duration을 wall-clock Date가 아닌 monotonic clock으로 측정하는 기준으로 사용했습니다." },
    { id: "long-tasks", repository: "W3C Web Performance Working Group", path: "TR/longtasks-1/", publicUrl: "https://www.w3.org/TR/longtasks-1/", usedFor: ["long task observation", "main-thread blocking", "attribution", "responsiveness", "performance testing"], evidence: "timer 지연의 원인이 timer API가 아니라 main-thread work인지 관찰하고 interaction latency를 진단하는 보강 자료로 사용했습니다." },
    { id: "wai-carousel", repository: "W3C WAI ARIA Authoring Practices Guide", path: "patterns/carousel/", publicUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/carousel/", usedFor: ["automatic rotation control", "pause on focus/hover", "keyboard", "live region", "accessible labeling"], evidence: "자동 뉴스 rotator의 pause/start control과 focus·hover·announcement behavior를 접근 가능한 carousel guidance로 보강했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본 세 파일은 synchronous logs, timeout/interval callback, timer handle clear와 뉴스 rotation을 직접 제공합니다. task sources·microtasks·rendering·clamp·visibility·monotonic time·long tasks는 공식 ECMAScript/WHATWG/W3C 규격으로 보강했습니다.",
      "Promise fulfillment/rejection, chaining, catch/finally와 thenable assimilation은 js-09에서 이 microtask/event-loop model 위에 이어집니다.",
      "fetch HTTP/JSON과 AbortController network cancellation은 js-10, XML DOMParser 응답 capstone은 js-11에서 timer timeout/cancellation 정책과 연결합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
