import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-06-dom-create-update-remove"],
  slug: "js-06-dom-create-update-remove",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 6,
  title: "DOM 요소 생성·삽입·내용 변경·삭제와 안전한 CRUD 렌더링",
  subtitle: "HTML 문자열을 이어 붙이는 대신 typed node를 만들고, 이동·복제·Fragment·detached reference·XSS 경계까지 추적합니다.",
  level: "중급",
  estimatedMinutes: 310,
  coreQuestion: "사용자 입력으로 동적 UI를 만들 때 어떤 DOM mutation API를 선택하고, 노드의 정체성·수명·보안·접근성·성능을 어떻게 함께 보장할까요?",
  summary: "원본의 과목 추가 목록, 클릭 삭제 목록, 동의 체크박스 예제를 출발점으로 DOM mutation을 문자열 편집이 아닌 node tree 연산으로 다시 배웁니다. createElement/createTextNode/textContent로 사용자 값을 text node에 넣고 innerHTML이 HTML parser와 injection sink를 여는 이유를 비교합니다. append·prepend·before·after·replaceWith·replaceChildren·insertBefore가 새 노드를 만들지 않고 기존 노드를 이동시킨다는 점과 cloneNode의 ID·listener 함정을 exact output으로 증명합니다. DocumentFragment와 template.content의 소비 semantics, read/write batching과 layout thrashing을 과장 없이 설명합니다. update와 full re-render가 focus·selection·listener·node identity에 미치는 영향, remove 뒤에도 JavaScript reference가 남아 isConnected=false인 detached node가 되는 수명을 추적합니다. 마지막에는 stable ID를 source of truth로 삼고 semantic button·event delegation·입력 검증·focus 복구·dispose를 갖춘 접근 가능한 할 일 CRUD를 설계합니다. Trusted Types와 CSP는 위험한 string sink를 통제하는 방어층이지 textContent와 server validation, contextual escaping을 대체하지 않는다는 전문가 경계까지 포함합니다.",
  objectives: [
    "createElement·createTextNode·textContent로 typed DOM subtree를 만들고 ownerDocument·namespace·node identity를 설명할 수 있다.",
    "append/prepend/before/after/replaceWith/replaceChildren/insertBefore의 위치·return·이동 semantics에 맞는 API를 선택할 수 있다.",
    "사용자 문자열을 textContent로 표시하는 경우와 innerHTML 같은 HTML parsing sink가 필요한 경우를 구분하고 XSS 방어층을 설계할 수 있다.",
    "DocumentFragment와 template.content를 재사용 가능한 조립·복제 경계로 사용하고 fragment가 삽입 후 비는 이유를 예측할 수 있다.",
    "부분 update와 전체 re-render가 node identity·listener·focus·selection에 미치는 차이를 테스트할 수 있다.",
    "remove된 detached node의 reference·listener·closure 수명을 isConnected와 heap 관점에서 진단할 수 있다.",
    "state 기반 CRUD 목록을 입력 검증·stable ID·event delegation·접근 가능한 삭제·성능 측정과 함께 구현할 수 있다.",
  ],
  prerequisites: [
    { title: "DOM 조회·collection·관계 탐색", reason: "수정할 root와 대상 node를 required/optional query contract로 찾고 현재 tree 연결 여부를 먼저 판단합니다.", sessionSlug: "js-05-dom-query-traversal" },
    { title: "DOM 이벤트 등록·전파와 위임", reason: "동적으로 추가되는 항목의 action을 stable parent listener 하나로 처리하고 listener 수명을 관리합니다.", sessionSlug: "js-03-event-model-listeners" },
    { title: "HTML 폼 controls와 validation", reason: "input value, submit semantics, button type, label과 오류 안내를 보존한 채 동적 목록을 만듭니다.", sessionSlug: "html-08-form-controls-validation" },
  ],
  keywords: ["DOM mutation", "createElement", "createTextNode", "textContent", "innerHTML", "append", "prepend", "replaceChildren", "remove", "cloneNode", "DocumentFragment", "template", "detached node", "isConnected", "XSS", "Trusted Types", "CSP", "layout thrashing", "CRUD", "event delegation"],
  chapters: [
    {
      id: "mutation-tree-identity-model",
      title: "DOM 수정은 HTML 파일을 다시 쓰는 일이 아니라 현재 node tree와 object identity를 바꾸는 연산입니다",
      lead: "화면의 글자만 보지 말고 mutation 전후 parent·children·isConnected와 JavaScript reference가 가리키는 object를 추적합니다.",
      explanations: [
        "브라우저가 HTML을 parse한 뒤 JavaScript가 다루는 대상은 source file 문자열이 아니라 Document에 연결된 Node object tree입니다. createElement는 source file에 tag를 기록하지 않고 현재 Document가 소유하는 새 Element object를 memory에 만듭니다.",
        "새 node는 생성 직후 parent가 없고 isConnected가 false입니다. parent에 삽입하면 tree relation이 정해지고 document 또는 연결된 shadow tree에 이어질 때 isConnected가 true가 됩니다. 같은 object를 다른 parent에 삽입하면 복사본이 생기지 않고 기존 위치에서 제거되어 이동합니다.",
        "node identity는 `a === b`로 비교할 수 있습니다. 같은 tagName·textContent·attribute를 가진 두 li도 별도 createElement 호출로 만들었다면 다른 object입니다. 반대로 variable 두 개가 같은 node를 가리키면 어느 쪽으로 수정해도 같은 object가 변합니다.",
        "DOM mutation algorithm은 hierarchy와 document constraints를 검사합니다. 자기 자신을 descendant에 넣거나 Document에 허용되지 않는 구조를 삽입하면 HierarchyRequestError 같은 DOMException이 날 수 있습니다. 임의 구조가 항상 자동 교정되는 HTML parser와 DOM API 호출을 같은 것으로 보지 않습니다.",
        "ownerDocument는 node를 만든 Document를 나타냅니다. iframe 또는 다른 Document에서 만든 node를 옮길 때 adopt/import semantics가 관여하고, SVG/MathML을 만들 때는 createElement가 아니라 정확한 namespaceURI를 가진 createElementNS가 필요합니다.",
        "원본 AddItem 예제의 createElement('li')와 createTextNode(subject)는 이 정신 모델의 좋은 출발점입니다. 여기서 입력 검증, stable identity, 안전한 action button, 상태와 render ownership까지 추가해야 실서비스 CRUD가 됩니다.",
      ],
      concepts: [
        { term: "node identity", definition: "tag·text가 같아도 각 DOM Node object가 갖는 고유한 reference 정체성입니다.", detail: ["strict equality로 비교합니다.", "삽입은 보통 같은 object를 이동합니다."] },
        { term: "connected node", definition: "node의 shadow-including root가 Document여서 현재 document tree에 연결된 상태입니다.", detail: ["isConnected로 관찰합니다.", "화면 표시 여부와 완전히 같지는 않습니다."] },
        { term: "ownerDocument", definition: "Node를 생성하고 소유하는 Document reference입니다.", detail: ["다른 document 이동을 구분합니다.", "namespace와 parsing context를 확인합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "한 목록에 복사하려고 append한 항목이 원래 목록에서 사라졌다.", likelyCause: "append는 기존 node를 clone하지 않고 새 parent로 이동시킵니다.", checks: ["삽입 전후 parentElement와 `original === queried`를 출력합니다.", "cloneNode 호출 여부를 확인합니다.", "같은 data record를 두 view에서 보여야 하는지 한 node를 옮겨야 하는지 요구를 구분합니다."], fix: "두 위치에 별도 표현이 필요하면 state에서 각각 render하거나 cloneNode 후 unique ID와 listener/state를 다시 설정합니다.", prevention: "move와 copy를 API 이름과 test assertion으로 구분하고 node identity를 snapshot에 포함합니다." },
      ],
    },
    {
      id: "create-text-safe-subtree",
      title: "createElement와 textContent로 구조와 데이터를 분리하면 사용자 입력이 tag로 해석되지 않습니다",
      lead: "HTML 구조는 code가 결정하고 사용자 값은 text node에만 넣는 것이 동적 UI의 기본 안전 경계입니다.",
      explanations: [
        "document.createElement('li')는 HTML Document에서 li Element를 만듭니다. property/attribute와 child를 단계적으로 설정한 뒤 root에 삽입하면 아직 미완성인 중간 UI를 document에 노출하지 않고 subtree를 조립할 수 있습니다.",
        "createTextNode(value) 또는 element.textContent=value는 string을 text data로 저장합니다. value가 `<img onerror=...>` 모양이어도 이 setter 자체는 HTML parser를 호출하지 않아 img Element나 event handler attribute가 만들어지지 않습니다.",
        "textContent setter는 기존 child 전체를 제거하고 주어진 text node로 대체합니다. 기존 descendant button/input/listener/focus가 필요하다면 container 전체 textContent를 바꾸지 말고 전용 span의 textContent만 갱신합니다.",
        "입력값 trim은 공백뿐인 과목을 거부하기 위한 product rule입니다. 원본 alert 뒤 focus 방식보다 submit event에서 inline error text와 aria-describedby를 제공하면 keyboard·screen reader 사용자가 문제와 복구 위치를 더 쉽게 이해합니다.",
        "사용자 입력을 안전하게 표시하는 것과 업무 데이터 검증은 별개입니다. textContent를 썼어도 길이·허용 문자·중복·server authorization을 검증해야 하며, URL/src/style 같은 다른 context property에 넣을 때는 해당 context의 scheme·type 정책이 필요합니다.",
        "DOM API를 쓴다는 사실만으로 모든 injection이 사라지지는 않습니다. setAttribute('onclick', untrusted), script.textContent, iframe.srcdoc, URL navigation처럼 실행 의미가 있는 sink는 피하거나 별도 정책으로 제한합니다.",
      ],
      concepts: [
        { term: "safe text sink", definition: "untrusted string을 markup이나 code로 parse하지 않고 text node data로 취급하는 할당 지점입니다.", detail: ["textContent/createTextNode가 대표적입니다.", "다른 URL/style/script context에는 자동 적용되지 않습니다."] },
        { term: "structure-data separation", definition: "허용할 element·attribute 구조는 code/template이 만들고 외부 값은 제한된 text/property 자리에만 넣는 설계입니다.", detail: ["review가 쉬워집니다.", "context별 validation은 여전히 필요합니다."] },
        { term: "subtree assembly", definition: "document에 연결하기 전에 parent와 descendants를 memory에서 완성한 뒤 한 경계로 삽입하는 과정입니다.", detail: ["중간 불완전 상태를 줄입니다.", "node identity가 유지됩니다."] },
      ],
      codeExamples: [
        {
          id: "safe-li-from-user-input",
          title: "tag처럼 보이는 입력을 text node로만 렌더링",
          language: "html",
          filename: "safe-subject-list.html",
          purpose: "원본 과목 추가 흐름에 공격처럼 보이는 문자열을 넣어 createElement+textContent가 실제 img node를 만들지 않는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>safe list</title></head>\n<body><ul id=\"subjects\"></ul><pre id=\"out\"></pre>\n<script>\n  const list = document.querySelector('#subjects');\n  function addSubject(raw) {\n    const value = raw.trim();\n    if (!value) return false;\n    const item = document.createElement('li');\n    item.textContent = value;\n    list.append(item);\n    return true;\n  }\n  addSubject('HTML');\n  addSubject('<img src=x onerror=alert(1)>');\n  document.querySelector('#out').textContent = [\n    `items=${list.children.length}`,\n    `images=${list.querySelectorAll('img').length}`,\n    `second=${list.lastElementChild.textContent}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "4-12", explanation: "입력을 trim/empty 검사한 뒤 허용 구조 li를 code로 만들고 value를 textContent에 넣습니다." },
            { lines: "13-14", explanation: "정상 문자열과 tag 모양 문자열을 같은 data path로 추가합니다." },
            { lines: "15-19", explanation: "child 수, 실제 img element 수, 표시 text를 DOM에서 다시 읽어 안정된 결과를 만듭니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 safe-subject-list.html을 열고 결과 확인" },
          output: { value: "items=2\nimages=0\nsecond=<img src=x onerror=alert(1)>", explanation: ["두 입력 모두 li이므로 items는 2입니다.", "두 번째 값은 HTML로 parse되지 않아 img element가 0개입니다.", "angle bracket를 포함한 원문은 textContent로 그대로 읽힙니다."] },
          experiments: [
            { change: "`item.textContent=value`를 `item.innerHTML=value`로 바꿉니다.", prediction: "img Element가 생겨 images가 1이 되고 onerror handler가 실행될 위험이 생깁니다.", result: "표시 text에 HTML parsing sink를 사용하면 안 됩니다." },
            { change: "공백 문자열을 addSubject에 전달합니다.", prediction: "false를 반환하고 items는 늘지 않습니다.", result: "안전한 rendering과 업무 validation을 별도 확인합니다." },
            { change: "li에 button을 추가한 뒤 li.textContent를 다시 설정합니다.", prediction: "기존 button child가 제거됩니다.", result: "변경할 text 전용 span을 따로 둡니다." },
          ],
          sourceRefs: ["web-dom-create-source", "dom-create-element", "html-dynamic-markup", "trusted-types"],
        },
      ],
      diagnostics: [
        { symptom: "과목 이름을 수정했더니 옆의 삭제 button과 그 listener가 사라졌다.", likelyCause: "li 전체의 textContent를 설정해 모든 기존 child node를 text 하나로 교체했습니다.", checks: ["설정 전후 children과 activeElement를 기록합니다.", "text 전용 descendant가 있는지 확인합니다.", "listener owner와 render 범위를 봅니다."], fix: "label span의 textContent만 갱신하거나 상태에서 의도한 subtree를 다시 render하고 focus를 복구합니다.", prevention: "DOM 구조 invariant와 action button 존재·keyboard focus regression test를 둡니다." },
      ],
    },
    {
      id: "insertion-move-clone-order",
      title: "삽입 API는 위치와 node 이동을 표현하고 cloneNode는 구조만 복제합니다",
      lead: "append와 clone을 혼동하지 않고 반환값·순서·listener·ID uniqueness까지 포함해 copy 정책을 정합니다.",
      explanations: [
        "parent.append(...nodesOrStrings)는 마지막 child 뒤에 여러 Node/string을 넣고 undefined를 반환합니다. appendChild(node)는 Node 하나를 마지막에 넣고 삽입한 node를 반환합니다. chaining이나 return 필요 여부를 문서화해 이름만 다른 동일 함수로 취급하지 않습니다.",
        "prepend는 첫 child 앞, Element.before/after는 자신과 같은 parent의 앞/뒤, replaceWith는 자신을 교체합니다. replaceChildren은 parent child 전체를 주어진 nodes/strings로 교체합니다. legacy-compatible 위치 제어에는 insertBefore(newNode, referenceNode)가 있고 referenceNode가 null이면 끝에 삽입됩니다.",
        "삽입 대상이 이미 tree에 있으면 mutation algorithm이 먼저 기존 parent에서 제거한 다음 새 위치에 넣습니다. 같은 목록 안에서 append(existing)를 호출하면 정렬 순서를 뒤로 옮기는 operation이 됩니다.",
        "cloneNode(true)는 descendant 구조와 attributes를 deep clone하지만 addEventListener로 등록한 listener, JavaScript object의 custom state, canvas bitmap 등 모든 runtime state를 복제하지 않습니다. inline handler attribute는 attribute로 복제될 수 있어 오히려 피해야 합니다.",
        "deep clone은 id/name도 복제하므로 같은 Document에 넣기 전에 unique ID와 label-for/aria-labelledby/data-id 관계를 갱신합니다. form control의 current value와 default value, custom element lifecycle도 component별 test가 필요합니다.",
        "두 view에 같은 record를 보여 줄 때 DOM clone을 source of truth로 쓰기보다 record ID와 state를 기반으로 각 view를 render하면 update consistency를 유지하기 쉽습니다.",
      ],
      concepts: [
        { term: "node move", definition: "이미 parent가 있는 동일 Node object를 다른 위치에 삽입해 기존 위치에서 제거하고 새 parent/순서에 두는 연산입니다.", detail: ["identity가 유지됩니다.", "listener도 같은 node와 함께 유지됩니다."] },
        { term: "deep clone", definition: "cloneNode(true)로 node와 descendant structure/attribute를 새 identity로 복제하는 연산입니다.", detail: ["addEventListener listener는 복제하지 않습니다.", "중복 ID를 고쳐야 합니다."] },
        { term: "replacement boundary", definition: "replaceWith/replaceChildren처럼 기존 node identity를 tree에서 제거하고 새 nodes로 바꾸는 경계입니다.", detail: ["focus/listener가 영향을 받습니다.", "state ownership을 명시합니다."] },
      ],
      codeExamples: [
        {
          id: "move-versus-clone",
          title: "기존 node 이동과 deep clone의 identity 비교",
          language: "html",
          filename: "move-clone.html",
          purpose: "append가 copy가 아니라 move임을 parent/identity/ID exact output으로 증명합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>move clone</title></head>\n<body><ul id=\"left\"><li id=\"original\"><span>A</span></li></ul><ul id=\"right\"></ul><pre id=\"out\"></pre>\n<script>\n  const left = document.querySelector('#left');\n  const right = document.querySelector('#right');\n  const original = document.querySelector('#original');\n  right.append(original);\n  const copy = original.cloneNode(true);\n  copy.id = 'copy';\n  right.append(copy);\n  document.querySelector('#out').textContent = [\n    `left=${left.children.length}`,\n    `right=${right.children.length}`,\n    `parent=${original.parentElement.id}`,\n    `clone-same=${copy === original}`,\n    `ids=${[...right.children].map(node => node.id).join(',')}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "4-7", explanation: "두 목록과 original node reference를 준비합니다." },
            { lines: "8-12", explanation: "original을 right로 이동한 뒤 새 identity의 deep clone을 만들고 duplicate ID를 copy로 바꿉니다." },
            { lines: "13-19", explanation: "원래 parent의 빈 상태, 새 parent child 수, object equality와 ID order를 출력합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 move-clone.html을 열고 결과 확인" },
          output: { value: "left=0\nright=2\nparent=right\nclone-same=false\nids=original,copy", explanation: ["original은 이동했으므로 left가 비었습니다.", "right에는 같은 original과 새 copy 두 object가 있습니다.", "clone은 별도 identity이며 ID를 명시적으로 변경했습니다."] },
          experiments: [
            { change: "copy.id 변경을 제거합니다.", prediction: "Document에 duplicate id가 생깁니다.", result: "clone된 reference attributes를 새 context에 맞게 다시 연결합니다." },
            { change: "original에 addEventListener를 등록한 뒤 original/copy를 click합니다.", prediction: "original listener는 유지되지만 copy에는 자동 복제되지 않습니다.", result: "delegation 또는 explicit component mount를 사용합니다." },
            { change: "right.prepend(original)을 마지막에 호출합니다.", prediction: "새 node가 생기지 않고 original이 right의 첫 child로 이동합니다.", result: "동일 parent 안 reorder도 move입니다." },
          ],
          sourceRefs: ["web-dom-create-source", "web-dom-remove-source", "dom-mutation"],
        },
      ],
      diagnostics: [
        { symptom: "clone한 card의 button이 보이지만 click listener가 실행되지 않는다.", likelyCause: "cloneNode는 addEventListener로 등록된 listener/runtime controller를 복제하지 않습니다.", checks: ["original/copy identity와 listener 등록 경로를 확인합니다.", "inline handler인지 addEventListener인지 구분합니다.", "duplicate id와 label/aria reference도 검사합니다."], fix: "stable parent delegation을 사용하거나 clone을 component mount 함수에 전달해 listener·state·unique references를 명시적으로 연결합니다.", prevention: "clone 직후 keyboard/click action과 unique ID accessibility audit를 자동화합니다." },
      ],
    },
    {
      id: "innerhtml-parser-trusted-types",
      title: "innerHTML은 편리한 문자열 setter가 아니라 HTML parser를 여는 injection boundary입니다",
      lead: "정말 markup parsing이 필요한 제한된 경계만 남기고, 나머지 동적 값은 safe DOM API로 구성합니다.",
      explanations: [
        "innerHTML setter는 string을 해당 element context에서 HTML fragment로 parse한 뒤 기존 children을 새 nodes로 교체합니다. `<li>` 문자열이 실제 li가 되고 descendant identity/listener/focus가 교체되므로 단순 text setter와 동작 범위가 다릅니다.",
        "untrusted string을 innerHTML에 넣으면 script tag만 막는 것으로 충분하지 않습니다. event handler attributes, javascript/data URL, SVG/MathML, parser mutation과 이후 code가 읽는 dangerous attributes 등 여러 DOM XSS vector가 있습니다.",
        "기본 선택은 createElement·textContent·명시적 safe property입니다. rich text가 업무상 필요하면 신뢰 경계를 정하고 검증된 sanitizer를 허용 정책과 버전으로 관리하며, 결과를 아무 context에나 재사용하지 않습니다. 자체 regex로 HTML을 sanitize하지 않습니다.",
        "Trusted Types는 Content Security Policy와 결합해 innerHTML 같은 injection sink가 policy가 만든 typed value만 받도록 강제할 수 있습니다. 하지만 policy가 입력을 그대로 통과시키면 안전해지지 않으며 URL·server template·SQL 등 다른 sink를 자동 보호하지 않습니다.",
        "CSP는 inline script와 resource source를 제한하는 중요한 defense in depth입니다. 허용 범위가 넓거나 nonce 관리가 틀리면 우회될 수 있고, CSP가 있으니 unsafe DOM assignment를 유지해도 된다는 뜻은 아닙니다.",
        "template element의 HTML은 author-controlled static markup으로 두고 template.content를 clone해 data slot만 textContent/property로 채우는 pattern이 구조 가독성과 보안을 함께 높입니다. 외부 HTML을 template.innerHTML로 넣는다면 같은 injection boundary입니다.",
        "innerHTML getter/logging도 privacy 문제를 만들 수 있습니다. subtree 전체에는 hidden input, CSRF token, 사용자 message가 있을 수 있으므로 production telemetry에 raw markup을 남기지 않고 count·state code·redacted metadata만 기록합니다.",
      ],
      concepts: [
        { term: "injection sink", definition: "string을 code/markup/URL 등 실행 또는 구조 의미가 있는 문맥으로 해석하는 API 지점입니다.", detail: ["innerHTML이 DOM XSS sink입니다.", "문맥별 방어가 다릅니다."] },
        { term: "sanitization", definition: "허용 정책에 따라 위험한 markup element/attribute/URL을 제거·변환하는 과정입니다.", detail: ["regex 대체가 아닙니다.", "library와 policy version을 관리합니다."] },
        { term: "Trusted Types", definition: "CSP와 함께 DOM XSS injection sink에 typed values를 요구하도록 돕는 Web Platform 방어 mechanism입니다.", detail: ["policy 품질이 핵심입니다.", "모든 XSS를 해결하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "댓글에 입력한 이미지 tag가 실제 요청을 보내거나 event handler가 실행된다.", likelyCause: "사용자 content를 innerHTML로 parse해 DOM subtree에 삽입했습니다.", checks: ["모든 innerHTML/outerHTML/insertAdjacentHTML/srcdoc/document.write sink를 inventory합니다.", "data flow를 source부터 sink까지 추적합니다.", "CSP/Trusted Types report와 sanitizer policy/version을 확인합니다."], fix: "일반 댓글은 textContent로 바꾸고 rich text만 검증된 sanitizer+strict allowlist+Trusted Types enforcement를 적용하며 저장 데이터도 server에서 검증합니다.", prevention: "DOM XSS payload corpus, CSP report-only→enforce rollout, sink lint와 dependency advisory 관리를 둡니다." },
      ],
      comparisons: [
        { title: "동적 content 생성 방식 선택", options: [
          { name: "createElement + textContent", chooseWhen: "구조가 application code에 알려져 있고 외부 값은 text/data일 때", avoidWhen: "복잡한 author-owned static markup을 줄 단위로 지나치게 장황하게 만들 때", tradeoffs: ["기본적으로 parsing injection을 피합니다.", "명시적이라 review가 쉽습니다.", "구조 code가 길어질 수 있습니다."] },
          { name: "template.content clone", chooseWhen: "반복되는 정적 구조를 HTML로 유지하고 data slot만 안전하게 채울 때", avoidWhen: "untrusted HTML string을 template에 넣으려 할 때", tradeoffs: ["authoring과 clone이 편합니다.", "ID/reference 갱신이 필요합니다.", "template 자체는 inert지만 삽입 후 동작을 검토합니다."] },
          { name: "sanitized rich HTML", chooseWhen: "업무 요구가 제한된 rich text를 실제 markup으로 표시해야 할 때", avoidWhen: "plain text면 충분하거나 sanitizer policy를 운영할 수 없을 때", tradeoffs: ["허용 기능을 제공할 수 있습니다.", "policy/library/URL context 유지 비용이 큽니다.", "Trusted Types/CSP는 보강층입니다."] },
        ] },
      ],
    },
    {
      id: "fragment-template-batching",
      title: "DocumentFragment와 template.content는 임시 조립 root이며 삽입할 때 자신이 아니라 children이 소비됩니다",
      lead: "Fragment를 단순 성능 주문처럼 외우지 않고 node ownership·clone·관찰 가능한 결과를 확인합니다.",
      explanations: [
        "DocumentFragment는 parent가 없는 lightweight tree root로 여러 child를 document 밖에서 조립할 수 있습니다. list.append(fragment)를 호출하면 fragment object 자체가 li child가 되는 것이 아니라 fragment의 children이 순서대로 list에 삽입되고 fragment는 비게 됩니다.",
        "fragment가 비는 것은 variable이 null이 되거나 object가 파괴됐다는 뜻이 아닙니다. 같은 fragment reference를 다시 사용할 수 있지만 기존 children은 이미 list로 이동했으므로 새 nodes를 다시 채워야 합니다.",
        "template element의 content는 DocumentFragment입니다. template markup은 document에 직접 render되지 않는 inert template contents로 보관되고 `template.content.cloneNode(true)`로 매 item마다 새 subtree identity를 만듭니다.",
        "Fragment는 code organization과 one-boundary insertion에 유용하지만 무조건 몇 배 빠르다고 주장하면 안 됩니다. 연결되지 않은 container에 여러 append를 해도 layout이 발생하지 않을 수 있고 browser engine이 mutation을 최적화합니다. 실제 데이터 크기와 device에서 profile합니다.",
        "진짜 layout thrashing은 write 뒤 offsetWidth/getBoundingClientRect/computed style 같은 layout-dependent read를 반복 교차해 synchronous style/layout을 강제할 때 발생합니다. 먼저 필요한 measurements를 읽고 mutations를 묶거나 requestAnimationFrame phase를 설계합니다.",
        "수만 개 항목은 Fragment만으로 해결되지 않습니다. pagination/windowing/virtualization을 고려하되 screen reader의 전체 item 수, keyboard navigation, search/find, focus preservation을 함께 설계합니다.",
      ],
      concepts: [
        { term: "DocumentFragment", definition: "document 밖에서 children을 보유하고 한 mutation 경계로 옮길 수 있는 Node tree root입니다.", detail: ["삽입 시 children이 이동합니다.", "삽입 후 fragment는 empty입니다."] },
        { term: "template contents", definition: "HTMLTemplateElement가 별도 DocumentFragment에 보관하는 inert author-defined subtree입니다.", detail: ["clone 후 data를 채웁니다.", "삽입 뒤 활성 동작을 검토합니다."] },
        { term: "read/write batching", definition: "layout-dependent reads와 DOM/style writes를 phase별로 묶어 불필요한 synchronous layout을 줄이는 전략입니다.", detail: ["profile로 검증합니다.", "focus/accessibility를 보존합니다."] },
      ],
      codeExamples: [
        {
          id: "fragment-consumption-order",
          title: "Fragment child 수와 삽입 순서 확인",
          language: "html",
          filename: "fragment-list.html",
          purpose: "세 과목을 fragment에 조립한 뒤 list에 append해 fragment가 비고 children identity가 이동하는 결과를 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>fragment</title></head>\n<body><ul id=\"list\"></ul><pre id=\"out\"></pre>\n<script>\n  const list = document.querySelector('#list');\n  const fragment = document.createDocumentFragment();\n  for (const subject of ['HTML', 'CSS', 'JavaScript']) {\n    const item = document.createElement('li');\n    item.textContent = subject;\n    fragment.append(item);\n  }\n  const before = fragment.childElementCount;\n  list.append(fragment);\n  document.querySelector('#out').textContent = [\n    `before-fragment=${before}`,\n    `after-fragment=${fragment.childElementCount}`,\n    `list=${list.childElementCount}`,\n    `order=${[...list.children].map(item => item.textContent).join('|')}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "4-10", explanation: "빈 fragment에 createElement/textContent로 li 세 개를 순서대로 조립합니다." },
            { lines: "11-12", explanation: "삽입 전 child 수를 저장하고 fragment를 list에 append해 children을 이동합니다." },
            { lines: "13-18", explanation: "fragment 소비 전후와 최종 list count/order를 stable output으로 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 fragment-list.html을 열고 결과 확인" },
          output: { value: "before-fragment=3\nafter-fragment=0\nlist=3\norder=HTML|CSS|JavaScript", explanation: ["삽입 전 fragment는 li 세 개를 소유합니다.", "append 뒤 세 li가 list로 이동해 fragment는 비었습니다.", "삽입 order는 fragment child tree order를 유지합니다."] },
          experiments: [
            { change: "list.append(fragment)를 두 번 연속 호출합니다.", prediction: "두 번째에는 fragment가 비어 있어 항목이 추가되지 않습니다.", result: "재사용하려면 새 children 또는 template clone이 필요합니다." },
            { change: "loop마다 list.append(item)을 호출해 output을 비교합니다.", prediction: "최종 DOM output은 같을 수 있습니다.", result: "성능 우열은 layout read와 workload를 포함해 측정합니다." },
            { change: "각 append 직후 list.getBoundingClientRect를 읽습니다.", prediction: "연결된 document에서 repeated layout cost가 커질 수 있습니다.", result: "read와 write를 batch하고 performance trace로 확인합니다." },
          ],
          sourceRefs: ["web-dom-create-source", "dom-fragment", "dom-mutation", "html-template"],
        },
      ],
      diagnostics: [
        { symptom: "같은 fragment를 두 번째 목록에 append했는데 아무 항목도 나타나지 않는다.", likelyCause: "첫 append가 fragment children을 첫 목록으로 이동시켜 fragment가 비었습니다.", checks: ["append 전후 fragment.childNodes.length를 확인합니다.", "첫 목록 child identity/parent를 확인합니다.", "copy가 필요한지 move가 필요한지 요구를 정합니다."], fix: "매 render마다 새 fragment를 채우거나 template.content.cloneNode(true)로 독립 subtree를 만듭니다.", prevention: "fragment 소비 후 empty invariant와 multi-render identity test를 둡니다." },
      ],
    },
    {
      id: "update-render-identity-focus",
      title: "부분 update와 전체 re-render는 같은 화면처럼 보여도 identity·focus·selection·listener 결과가 다릅니다",
      lead: "무엇이 source of truth인지 정하고 render boundary가 교체하는 node와 보존해야 할 사용자 상태를 명시합니다.",
      explanations: [
        "text label 하나만 바뀐다면 전용 node의 textContent를 수정하면 주변 input/button identity와 listener/focus를 유지할 수 있습니다. 구조가 크게 달라지면 state에서 subtree를 다시 render하는 편이 단순할 수 있지만 교체 비용과 lifecycle을 감수합니다.",
        "innerHTML='' 또는 replaceChildren(newTree)은 기존 descendants를 detach합니다. cached reference와 addEventListener listener는 과거 node에 남고 새로 보이는 node와 다릅니다. event delegation은 child마다 listener를 다시 붙이는 문제를 줄이지만 focus와 local form state는 자동 보존하지 않습니다.",
        "render 함수 안에서 DOM을 다시 읽어 domain state를 복원하면 checked/value/selection처럼 current UI state와 default attribute가 섞입니다. application state를 source of truth로 정하고 input event에서 state transition 후 deterministic render를 수행합니다.",
        "list item에는 array index보다 stable record ID를 사용합니다. 앞 item 삭제로 index가 바뀌어도 update/delete target을 정확히 찾고, keyed reconciliation을 쓰는 framework에서도 record identity를 보존할 수 있습니다.",
        "현재 focus가 교체되는 node 내부라면 render 전에 logical focus target ID와 selection을 기록하고 render 후 해당 action/input으로 복구합니다. 무조건 body나 첫 input으로 보내면 keyboard workflow가 끊깁니다.",
        "render는 가능하면 pure projection에 가깝게 두고 event listener 등록, timer, observer, network 같은 side effect는 mount/dispose owner가 관리합니다. 같은 component를 두 번 mount해 duplicate action이 발생하지 않게 idempotence 또는 AbortSignal cleanup을 사용합니다.",
      ],
      concepts: [
        { term: "source of truth", definition: "현재 목록과 항목 값을 결정하는 authoritative state로 DOM 또는 application state 중 ownership을 명시합니다.", detail: ["양쪽을 동시에 임의 수정하지 않습니다.", "transition과 render를 분리합니다."] },
        { term: "stable record ID", definition: "항목 순서·표시 text와 독립적으로 CRUD 대상의 정체성을 나타내는 key입니다.", detail: ["index를 ID로 쓰지 않습니다.", "data-id/action과 연결합니다."] },
        { term: "focus restoration", definition: "DOM 교체 뒤 사용자가 하던 keyboard 작업의 logical 위치로 focus를 되돌리는 lifecycle 단계입니다.", detail: ["삭제/편집 정책이 다릅니다.", "screen reader announcement도 고려합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "목록을 다시 그릴 때 입력 중이던 text와 cursor 위치가 사라지고 click이 두 번 실행된다.", likelyCause: "full re-render가 input identity/current state를 교체했고 mount 때 listener를 중복 등록했습니다.", checks: ["render 전후 activeElement와 node equality를 비교합니다.", "state가 input value를 보존하는지 확인합니다.", "listener mount/dispose 횟수와 AbortSignal을 계측합니다."], fix: "input state를 transition에 저장하고 필요한 node만 update하거나 focus/selection을 복구하며 listener owner를 stable root 하나로 제한하고 dispose합니다.", prevention: "typing 중 render, reorder/delete 후 focus, repeated mount/unmount E2E test를 둡니다." },
      ],
    },
    {
      id: "remove-detached-lifecycle",
      title: "remove는 tree 연결만 끊고 JavaScript variable·listener·closure를 자동으로 지우지 않습니다",
      lead: "화면에서 사라졌다는 사실과 object가 garbage collection 대상이 됐다는 사실을 분리합니다.",
      explanations: [
        "Element.remove()는 자신에게 parent가 있으면 그 parent에서 제거합니다. parent.removeChild(child)는 제거한 child를 반환하고 올바른 parent-child 관계가 아니면 NotFoundError가 날 수 있습니다. 어느 API든 JavaScript variable을 null로 바꾸지 않습니다.",
        "제거된 node는 parentElement가 null이고 document.contains(node)가 false, 보통 isConnected=false가 되지만 textContent와 attributes를 읽거나 다시 append할 수 있습니다. 원본 click-delete 예제에서 remove 뒤 reference를 보관하면 동일 object를 재삽입할 수 있습니다.",
        "detached node에 등록된 listener도 node와 함께 존재합니다. 외부 cache, global array, closure, observer가 node를 참조하면 garbage collector가 회수할 수 없어 반복 mount/delete에서 memory가 증가할 수 있습니다.",
        "event delegation을 쓰면 child별 listener 수를 줄일 수 있지만 component root와 controller를 global reference가 계속 보유하면 여전히 leak입니다. AbortController로 root listener를 dispose하고 observer/timer/subscription도 함께 해제합니다.",
        "삭제 UI는 destructive action의 중요도에 맞는 확인과 undo를 설계합니다. blocking confirm 하나에만 의존하지 말고 즉시 삭제+undo toast 또는 접근 가능한 modal을 product 요구에 따라 선택하며 keyboard focus와 live status를 제공합니다.",
        "삭제 뒤 focus가 제거된 button에 남을 수 없으므로 다음 항목의 삭제 button, 이전 항목, 또는 목록 heading/add input으로 deterministic하게 이동합니다. 항목 수 변화를 aria-live status로 간결하게 알리되 전체 목록을 반복 낭독하지 않습니다.",
      ],
      concepts: [
        { term: "detached node", definition: "JavaScript object reference는 존재하지만 현재 Document tree에 연결되지 않은 Node입니다.", detail: ["isConnected가 false입니다.", "다시 삽입할 수 있습니다."] },
        { term: "retaining reference", definition: "cache·closure·listener·observer 등이 object를 계속 가리켜 garbage collection을 막을 수 있는 reference입니다.", detail: ["heap snapshot의 retaining path를 봅니다.", "dispose ownership이 필요합니다."] },
        { term: "undoable deletion", definition: "삭제를 즉시 반영하되 제한 시간이나 명시 action으로 복구할 수 있게 하는 interaction model입니다.", detail: ["server transaction 정책이 필요합니다.", "focus/status를 설계합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "목록 항목을 반복 추가·삭제할수록 memory가 줄지 않고 event callback도 남는다.", likelyCause: "제거된 node를 cache/closure/observer가 계속 참조하거나 listener/subscription dispose가 빠졌습니다.", checks: ["isConnected=false nodes와 heap snapshot retaining paths를 봅니다.", "global Map/array와 devtools console references를 해제합니다.", "observer/timer/listener mount-dispose count를 비교합니다."], fix: "cache entry와 external references를 삭제하고 AbortController/observer.disconnect/timer clear를 component dispose에 묶으며 필요 없는 node reference를 보관하지 않습니다.", prevention: "반복 mount/add/remove soak test와 detached-node heap budget을 CI/프로파일링 절차에 둡니다." },
      ],
    },
    {
      id: "accessible-state-driven-crud",
      title: "CRUD 목록은 DOM을 임시 database로 쓰지 않고 stable state·semantic action·검증 가능한 render로 만듭니다",
      lead: "추가·수정·삭제 transition의 입력과 출력을 먼저 정의한 뒤 DOM을 그 state의 projection으로 취급합니다.",
      explanations: [
        "원본 AddItem은 작은 학습 예제로 충분하지만 대규모 기능에서는 li text를 다시 parse해 record를 찾으면 duplicate text·rename·공백 normalization에서 identity가 깨집니다. monotonic ID나 server ID를 data-id와 state Map에 연결합니다.",
        "submit event를 처리하면 Enter와 submit button이 같은 경로를 사용합니다. button에는 type을 명시하고 empty/길이/중복 validation은 error summary와 field association으로 안내합니다. disabled button만으로 invalid 이유를 숨기지 않습니다.",
        "각 li는 label span과 실제 button을 포함합니다. click 가능한 li 전체를 삭제 action으로 만들면 keyboard semantics와 accidental activation 문제가 생깁니다. button accessible name에는 어떤 항목을 삭제하는지 포함합니다.",
        "stable ul에 click listener 하나를 두고 target.closest('[data-action]')와 list.contains를 확인하면 동적 button도 처리됩니다. action과 data-id를 allowlist하고 Number conversion 실패·없는 record를 expected stale action으로 처리합니다.",
        "render마다 fragment에 새 nodes를 만들고 replaceChildren할 수 있지만 focus를 복구해야 합니다. 데이터가 많거나 input local state가 복잡하면 항목별 partial update/keyed rendering을 사용하고 실제 performance profile로 결정합니다.",
        "원본 동의 checkbox가 button.disabled를 바꾸는 예는 DOM property가 current interactive state를 나타내는 좋은 단서입니다. attribute/property/form state는 다음 세션에서 깊게 다루되, 여기서는 render가 current disabled property와 aria/status를 일관되게 설정해야 함을 확인합니다.",
        "client CRUD는 server authorization·concurrency·persistence를 대신하지 않습니다. optimistic update라면 request 실패에서 rollback/재시도/중복 submit을 처리하고, XSS-safe render와 별개로 권한을 server에서 다시 검사합니다.",
      ],
      concepts: [
        { term: "state transition", definition: "현재 state와 명시 action을 받아 다음 state 또는 validation error를 만드는 변경 규칙입니다.", detail: ["DOM event와 분리합니다.", "단위 테스트가 가능합니다."] },
        { term: "semantic action", definition: "button과 data-action처럼 사용자의 의도와 접근 가능한 interaction을 명시하는 control입니다.", detail: ["click 가능한 li를 피합니다.", "keyboard/name/focus를 제공합니다."] },
        { term: "deterministic render", definition: "같은 state에서 같은 의미의 DOM 구조와 text/action identity를 만드는 projection입니다.", detail: ["hidden mutable DOM state를 줄입니다.", "snapshot보다 semantic test를 우선합니다."] },
      ],
      codeExamples: [
        {
          id: "state-driven-crud-detached-reference",
          title: "stable ID CRUD와 삭제 후 detached reference 관찰",
          language: "html",
          filename: "todo-crud.html",
          purpose: "원본 추가·click 삭제를 state-driven render로 확장하고 add/update/remove 결과와 제거 전 node reference 수명을 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>todo CRUD</title></head>\n<body><ul id=\"todos\"></ul><pre id=\"out\"></pre>\n<script>\n  const list = document.querySelector('#todos');\n  const todos = new Map();\n  function render() {\n    const fragment = document.createDocumentFragment();\n    for (const todo of todos.values()) {\n      const item = document.createElement('li');\n      item.dataset.id = String(todo.id);\n      const label = document.createElement('span');\n      label.textContent = todo.text;\n      const button = document.createElement('button');\n      button.type = 'button';\n      button.textContent = '삭제';\n      button.setAttribute('aria-label', `삭제: ${todo.text}`);\n      item.append(label, button);\n      fragment.append(item);\n    }\n    list.replaceChildren(fragment);\n  }\n  function add(id, text) { todos.set(id, { id, text:text.trim() }); render(); }\n  function update(id, text) { todos.set(id, { ...todos.get(id), text:text.trim() }); render(); }\n  function remove(id) { todos.delete(id); render(); }\n  add(1, 'HTML');\n  add(2, 'CSS');\n  update(1, 'HTML5');\n  const removed = list.querySelector('[data-id=\"2\"]');\n  remove(2);\n  document.querySelector('#out').textContent = [\n    `state=${[...todos.values()].map(todo => `${todo.id}:${todo.text}`).join('|')}`,\n    `dom=${list.childElementCount}`,\n    `text=${list.querySelector('span').textContent}`,\n    `removed-connected=${removed.isConnected}`,\n    `removed-text=${removed.querySelector('span').textContent}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "4-22", explanation: "Map state를 순회해 semantic li/span/button subtree를 fragment에 만들고 replaceChildren으로 render합니다." },
            { lines: "23-25", explanation: "add/update/remove transition이 state를 바꾼 뒤 같은 render 경로를 호출합니다." },
            { lines: "26-30", explanation: "두 항목 추가, 첫 항목 수정, 둘째 node reference 저장 후 삭제를 deterministic하게 실행합니다." },
            { lines: "31-37", explanation: "최종 state/DOM과 삭제 전 reference의 isConnected/text를 함께 출력합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 todo-crud.html을 열고 결과 확인" },
          output: { value: "state=1:HTML5\ndom=1\ntext=HTML5\nremoved-connected=false\nremoved-text=CSS", explanation: ["state와 현재 DOM에는 수정된 1번 항목 하나만 남습니다.", "remove 후 과거 2번 node는 document에서 분리돼 isConnected=false입니다.", "JavaScript reference가 남아 detached node의 CSS text는 여전히 읽을 수 있습니다."] },
          experiments: [
            { change: "update key로 1 대신 배열 index를 사용하고 앞 항목을 먼저 삭제합니다.", prediction: "순서 변화로 다른 항목을 수정할 위험이 생깁니다.", result: "stable record ID를 action과 state에 사용합니다." },
            { change: "render마다 child button에 별도 listener를 추가합니다.", prediction: "기능은 되지만 mount ownership과 재연결 비용이 커집니다.", result: "stable list delegation과 dispose를 비교합니다." },
            { change: "remove 전 button에 focus하고 삭제 뒤 activeElement를 확인합니다.", prediction: "교체된 button focus가 사라져 body로 갈 수 있습니다.", result: "다음/이전 action 또는 add input으로 focus를 복구합니다." },
          ],
          sourceRefs: ["web-dom-create-source", "web-dom-remove-source", "web-dom-agreement-source", "dom-mutation", "dom-fragment", "wcag-focus-order"],
        },
      ],
      diagnostics: [
        { symptom: "목록 첫 항목을 삭제한 뒤 수정 button이 엉뚱한 항목을 바꾼다.", likelyCause: "현재 array index를 영구 ID처럼 data attribute/closure에 사용해 reorder/delete 뒤 의미가 변했습니다.", checks: ["event action의 data-id와 state key를 비교합니다.", "삭제·정렬 전후 record identity를 출력합니다.", "duplicate/stale action을 재현합니다."], fix: "order와 독립적인 stable record ID로 transition을 찾고 없는 ID는 stale state로 안전하게 처리합니다.", prevention: "prepend/delete/reorder/filter 뒤 update/delete property-based test와 E2E를 둡니다." },
        { symptom: "동적으로 추가한 li는 click 삭제가 되지만 keyboard로는 삭제할 수 없고 screen reader가 대상 이름을 말하지 않는다.", likelyCause: "li 자체 click만 처리하고 semantic button·accessible name·focus policy를 만들지 않았습니다.", checks: ["Tab/Enter/Space로 action을 실행합니다.", "accessibility tree의 role/name을 확인합니다.", "삭제 후 focus와 status announcement를 봅니다."], fix: "li 안에 type=button control을 두고 항목명을 포함한 accessible name, delegated click, 삭제 후 focus/aria-live status를 제공합니다.", prevention: "keyboard-only, screen-reader smoke, focus order와 target-size/accessibility review를 release gate에 둡니다." },
      ],
      expertNotes: [
        "MutationObserver는 external/third-party DOM 변화 integration에 유용하지만 own state transition을 대신하는 reactive store로 남용하지 않습니다. observer callback 자체 mutation과 record batching을 test합니다.",
        "Framework의 virtual DOM도 결국 host DOM mutation과 identity/focus lifecycle을 만납니다. key를 array index로 쓰거나 dangerouslySetInnerHTML을 사용하면 같은 문제가 다시 나타납니다.",
        "성능 측정은 node 수·mutation 수만 세지 말고 style/layout/paint, scripting, interaction latency, memory와 accessibility 동작을 함께 봅니다.",
      ],
    },
  ],
  lab: {
    title: "원본 과목 추가·삭제 목록을 보안·접근성·수명·성능이 검증되는 학습 계획 CRUD로 재구축하기",
    scenario: "현재 예제는 input text로 li 하나를 만들고 li click에서 confirm 후 remove합니다. 항목 identity, 수정, 안전한 rich/text 경계, keyboard action, focus 복구, listener dispose, 대량 삽입과 server 실패를 설명하지 못합니다.",
    setup: [
      "원본 day09 ex03/ex04/ex05 DOM 파일 3개를 read-only evidence로 준비합니다.",
      "modern browser DevTools의 Elements, Accessibility, Performance, Memory panel을 엽니다.",
      "empty/whitespace/duplicate/긴 한글/emoji/HTML-tag-like 문자열과 1·100·10,000개 항목 fixture를 준비합니다.",
      "keyboard-only, reduced motion, screen reader smoke와 popup confirm 대체 undo 흐름을 준비합니다.",
    ],
    steps: [
      "HTML form·label·input·submit·inline error·ul·status region을 semantic markup으로 만듭니다.",
      "Map/array state와 stable ID, add/update/remove action의 validation/error transition을 DOM 밖 pure function으로 작성합니다.",
      "createElement/textContent로 item label과 button을 조립하고 tag-like 입력이 element가 되지 않는지 검사합니다.",
      "template clone 또는 DocumentFragment를 사용해 batch render하고 fragment 소비 전후 child identity를 기록합니다.",
      "stable ul에 closest+contains delegation 하나를 mount하고 AbortSignal 기반 dispose를 구현합니다.",
      "수정은 label partial update와 full render 두 방식으로 구현해 identity/listener/focus/selection 차이를 측정합니다.",
      "삭제 뒤 next/previous/add-input focus와 undo/status를 구현하고 detached reference·heap retaining path를 확인합니다.",
      "read/write batching과 10,000개 rendering을 profile하고 pagination/windowing이 필요한 threshold를 접근성 요구와 함께 기록합니다.",
      "innerHTML sink inventory, Trusted Types report-only 정책, XSS payload와 privacy-safe telemetry를 검증합니다.",
    ],
    expectedResult: [
      "공백·중복·길이 오류는 항목을 만들지 않고 field와 연결된 복구 가능한 메시지를 제공합니다.",
      "HTML tag 모양 입력도 text로 보이며 img/script/event handler node가 만들어지지 않습니다.",
      "CRUD target은 reorder/filter/delete 뒤에도 stable ID로 정확하고 state와 rendered DOM이 일치합니다.",
      "동적 action을 keyboard로 실행하고 삭제/재렌더 뒤 logical focus와 간결한 status가 유지됩니다.",
      "remove된 node는 isConnected=false이고 외부 reference를 해제한 반복 test에서 detached-node memory가 누적되지 않습니다.",
      "Fragment/template 선택과 performance 결론은 exact trace/data로 설명되며 raw innerHTML·사용자 content를 log하지 않습니다.",
    ],
    cleanup: ["controller.abort, observer.disconnect, timer clear와 state/cache reference 해제를 실행합니다.", "DevTools console에 저장한 `$0`·temporary node reference와 synthetic payload를 제거합니다."],
    extensions: ["server persistence를 fake adapter로 추가해 optimistic add/delete 실패 rollback과 idempotency key를 구현합니다.", "Trusted Types report-only violation을 수집한 뒤 strict policy와 enforcement migration 문서를 만듭니다.", "10,000개 목록을 pagination과 accessible virtualization 두 방식으로 구현해 interaction latency와 keyboard/screen-reader 결과를 비교합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 AddItem을 createElement·textContent·semantic button으로 다시 만들고 move/clone/remove 결과를 표로 기록하세요.", requirements: ["empty trim validation과 inline error/focus를 제공합니다.", "tag처럼 보이는 입력에서 element 수 0을 확인합니다.", "append existing node와 cloneNode(true)의 identity/parent/ID/listener를 비교합니다.", "remove 뒤 reference의 parent/isConnected/text를 출력합니다."], hints: ["textContent setter는 기존 child를 모두 교체합니다.", "clone한 ID와 label/aria reference를 그대로 두지 않습니다."], expectedOutcome: "문자열이 아닌 node identity/tree mutation으로 add·move·copy·remove를 설명하고 exact output을 재현합니다.", solutionOutline: ["structure는 createElement, data는 textContent로 나눕니다.", "각 단계에서 ===, parentElement, isConnected를 기록합니다."] },
    { difficulty: "응용", prompt: "추가·이름 수정·삭제·undo가 가능한 접근 가능한 학습 계획 목록을 구현하세요.", requirements: ["stable ID state와 pure transition을 사용합니다.", "submit/keyboard/semantic buttons/accessible names를 제공합니다.", "stable root delegation과 dispose를 구현합니다.", "삭제 후 focus/status와 5초 undo를 제공합니다.", "Fragment 또는 template clone을 사용하고 innerHTML에 사용자 값을 넣지 않습니다."], hints: ["index는 reorder 뒤 record ID가 아닙니다.", "undo는 삭제 record와 이전 위치를 함께 보존합니다."], expectedOutcome: "동적 항목이 keyboard와 screen reader에서 사용 가능하고 CRUD/undo 뒤 state·DOM·focus가 일치합니다.", solutionOutline: ["action reducer와 render/mount/dispose를 분리합니다.", "role/name/state와 focus target을 E2E로 검사합니다."] },
    { difficulty: "설계", prompt: "교육 사이트 전체의 DOM mutation·rich text·component lifecycle 표준과 성능 예산을 설계하세요.", requirements: ["safe text/property와 dangerous sink inventory를 만듭니다.", "sanitizer/Trusted Types/CSP 적용·rollout·실패 정책을 정의합니다.", "node identity/key/mount/render/dispose/focus ownership을 명시합니다.", "Fragment/template/partial render/virtualization 선택표를 만듭니다.", "XSS·accessibility·detached memory·interaction latency 검증과 privacy-safe telemetry를 포함합니다."], hints: ["Trusted Types policy가 입력을 통과시키면 보호가 아닙니다.", "빠른 rendering과 전체 접근성 경험을 같은 예산에서 평가합니다."], expectedOutcome: "기능팀이 임의 innerHTML이나 listener leak 없이 일관된 CRUD component를 만들고 자동 검증할 수 있는 운영 표준이 완성됩니다.", solutionOutline: ["source→transform→sink와 state→render→dispose 흐름을 각각 그립니다.", "enforcement 전 report-only와 예외 제거 계획을 둡니다."] },
  ],
  reviewQuestions: [
    { question: "createElement 직후 node는 화면에 보이나요?", answer: "아닙니다. parent가 없는 detached node이며 연결된 tree에 삽입해야 document UI에 참여합니다." },
    { question: "append(existingNode)는 복사본을 만드나요?", answer: "아닙니다. 같은 node를 기존 위치에서 제거해 새 위치로 이동합니다." },
    { question: "append와 appendChild의 대표 차이는 무엇인가요?", answer: "append는 여러 Node/string을 받고 undefined를 반환하며 appendChild는 Node 하나를 받고 그 node를 반환합니다." },
    { question: "textContent에 `<img>`를 넣으면 img Element가 되나요?", answer: "아닙니다. 해당 setter는 값을 text로 취급해 HTML fragment로 parse하지 않습니다." },
    { question: "innerHTML은 왜 단순 text setter가 아닌가요?", answer: "string을 HTML fragment로 parse하고 기존 subtree를 교체하는 구조·identity·injection boundary이기 때문입니다." },
    { question: "cloneNode(true)는 listener도 복제하나요?", answer: "addEventListener로 등록한 listener는 복제하지 않으며 ID와 관련 references도 새 context에 맞게 고쳐야 합니다." },
    { question: "DocumentFragment를 parent에 append하면 fragment가 child로 남나요?", answer: "아닙니다. fragment children이 parent로 이동하고 fragment 자체는 빈 상태로 남습니다." },
    { question: "Fragment를 쓰면 항상 rendering이 빨라지나요?", answer: "보장되지 않습니다. 조립 경계에는 유용하지만 실제 layout reads, workload와 browser 최적화를 포함해 profile해야 합니다." },
    { question: "remove 후 variable은 자동으로 null인가요?", answer: "아닙니다. reference가 남으면 detached node를 계속 읽거나 다시 삽입할 수 있습니다." },
    { question: "isConnected=false면 object가 곧바로 garbage collection되나요?", answer: "아닙니다. cache·closure·listener 등 다른 retaining reference가 없어야 collection 대상이 될 수 있습니다." },
    { question: "목록 index를 record ID로 써도 되나요?", answer: "삭제·정렬·filter로 index 의미가 바뀌므로 지속 CRUD target에는 stable record ID를 사용합니다." },
    { question: "Trusted Types가 있으면 innerHTML에 아무 입력이나 넣어도 안전한가요?", answer: "아닙니다. strict policy와 sanitizer가 필요하며 다른 XSS/context/server validation을 대체하지 않습니다." },
  ],
  completionChecklist: [
    "DOM mutation 전후 node identity·parent·children·ownerDocument·isConnected를 설명했다.",
    "createElement/createTextNode/textContent로 구조와 외부 data를 분리했다.",
    "append/prepend/before/after/replaceWith/replaceChildren/insertBefore의 위치와 return을 선택했다.",
    "기존 node 삽입은 move이고 clone은 새 identity이며 listener/ID를 자동 해결하지 않음을 검증했다.",
    "innerHTML/outerHTML/insertAdjacentHTML/srcdoc/document.write sink를 inventory하고 plain text를 교체했다.",
    "rich text에는 검증된 sanitizer·strict allowlist·Trusted Types/CSP 방어층을 설계했다.",
    "DocumentFragment/template.content의 child 이동·clone·empty 결과를 exact output으로 확인했다.",
    "partial update와 full render의 focus·selection·listener·identity 차이를 test했다.",
    "remove된 detached node와 retaining reference를 isConnected·heap snapshot·dispose로 점검했다.",
    "stable ID state와 semantic button·delegation으로 add/update/delete/undo를 구현했다.",
    "validation error·삭제 후 focus·aria-live status와 keyboard/screen-reader 흐름을 검증했다.",
    "read/write batching·대량 목록을 profile하고 performance와 접근성 기준을 함께 기록했다.",
  ],
  nextSessions: [],
  sources: [
    { id: "web-dom-create-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex03_DOM.html", usedFor: ["DOMContentLoaded", "form click prevention", "createElement li", "createTextNode", "trim/empty/focus", "appendChild", "remove API comments"], evidence: "과목 입력을 li text node로 만들어 목록에 추가하는 원본 흐름을 safe text rendering·form semantics·stable CRUD state의 출발점으로 사용했습니다." },
    { id: "web-dom-remove-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex04_DOM.html", usedFor: ["dynamic item addition", "list click delegation", "tagName target", "confirm deletion", "Element.remove"], evidence: "동적으로 추가된 li를 parent click에서 삭제하는 예제를 closest/contains semantic action·detached reference·focus/undo lifecycle로 확장했습니다." },
    { id: "web-dom-agreement-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex05_DOM.html", usedFor: ["checkbox current state", "button disabled property", "interactive DOM mutation", "this/current control"], evidence: "동의 checkbox에 따라 button.disabled current property가 바뀌는 원본을 state-driven render의 interactive property 경계로 사용하고 상세 attribute/form 차이는 다음 세션에 연결했습니다." },
    { id: "dom-create-element", repository: "WHATWG DOM Standard", path: "#dom-document-createelement", publicUrl: "https://dom.spec.whatwg.org/#dom-document-createelement", usedFor: ["createElement", "local name validation", "ownerDocument", "custom elements", "namespace boundary"], evidence: "Document createElement의 current algorithm과 HTML/non-HTML document 차이를 typed node 생성 설명의 기준으로 사용했습니다." },
    { id: "dom-mutation", repository: "WHATWG DOM Standard", path: "#mutation-algorithms", publicUrl: "https://dom.spec.whatwg.org/#mutation-algorithms", usedFor: ["pre-insert/append/replace/remove", "node movement", "hierarchy validation", "fragment children insertion", "mutation records"], evidence: "DOM Living Standard의 insert/replace/remove algorithms를 parent·identity·order·exception 설명과 exact examples의 기준으로 사용했습니다." },
    { id: "dom-fragment", repository: "WHATWG DOM Standard", path: "#interface-documentfragment", publicUrl: "https://dom.spec.whatwg.org/#interface-documentfragment", usedFor: ["DocumentFragment tree root", "children", "query support", "consumption after insertion"], evidence: "DocumentFragment가 임시 parent/tree root이고 삽입 시 children이 이동하는 semantics를 공식 interface와 mutation algorithm에 맞췄습니다." },
    { id: "html-dynamic-markup", repository: "WHATWG HTML Standard", path: "multipage/dynamic-markup-insertion.html", publicUrl: "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html", usedFor: ["innerHTML", "outerHTML", "insertAdjacentHTML", "document.write", "fragment parsing", "injection sink"], evidence: "HTML fragment parsing과 dynamic markup insertion API를 textContent와 구분하고 dangerous string sink inventory의 기준으로 사용했습니다." },
    { id: "html-template", repository: "WHATWG HTML Standard", path: "multipage/scripting.html#the-template-element", publicUrl: "https://html.spec.whatwg.org/multipage/scripting.html#the-template-element", usedFor: ["template element", "template contents", "DocumentFragment clone", "inert author markup"], evidence: "반복 static structure를 template.content에 보관하고 clone한 뒤 safe data slot을 채우는 pattern을 current HTML template model로 보강했습니다." },
    { id: "trusted-types", repository: "W3C Web Application Security Working Group", path: "TR/trusted-types/", publicUrl: "https://www.w3.org/TR/trusted-types/", usedFor: ["injection sinks", "TrustedHTML", "policy", "CSP enforcement", "DOM XSS defense in depth"], evidence: "Trusted Types의 typed sink enforcement와 policy responsibility를 innerHTML migration·sanitizer 운영 경계에 사용했습니다." },
    { id: "wcag-focus-order", repository: "W3C Web Accessibility Initiative", path: "WCAG22/Understanding/focus-order.html", publicUrl: "https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html", usedFor: ["logical focus order", "DOM removal focus", "keyboard workflow", "dynamic CRUD accessibility"], evidence: "동적 항목 삭제·재렌더 뒤 의미와 운용성을 보존하는 focus 이동·검증 기준을 WCAG 2.2 이해 문서로 보강했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본 세 파일은 createElement/createTextNode/appendChild, delegated li remove, checkbox에 따른 disabled property를 직접 보여 줍니다. clone/Fragment/template, Trusted Types, focus/heap/performance와 state-driven CRUD는 WHATWG/W3C 규격으로 보강했습니다.",
      "attribute와 DOM property, boolean attribute, dataset/classList/style, form value/checked/disabled의 default/current 차이는 js-07에서 이 mutation·identity 모델 위에 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
