import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-07-dom-attributes-forms"],
  slug: "js-07-dom-attributes-forms",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 7,
  title: "속성·프로퍼티·class와 폼 상태 제어",
  subtitle: "HTML 초기 설정, DOM의 현재 값, CSS 시각 상태, 접근성 상태를 구분하고 하나의 전환 함수에서 동기화합니다.",
  level: "중급",
  estimatedMinutes: 320,
  coreQuestion: "HTML attribute와 DOM property가 달라질 수 있는 동적 폼에서 현재 사용자 상태를 정확히 읽고 class·hidden·ARIA·제출 데이터를 어떻게 일관되게 유지할까요?",
  summary: "원본의 전체 선택 checkbox, 공지 popup, display 기반 modal을 attribute/property/state mental model로 확장합니다. content attribute는 markup에 저장된 문자열 또는 부재이고 IDL property는 JavaScript interface의 typed current value이며, 각 property가 어떤 attribute를 어떻게 reflect하는지 API별로 확인합니다. disabled='false'도 true가 되는 boolean attribute presence semantics와 value/defaultValue, checked/defaultChecked, selected/defaultSelected, dirty flag, form.reset의 관계를 exact output으로 증명합니다. className 전체 교체 대신 classList token과 toggle(force)를 사용하고 hidden·style·computed style을 구분합니다. dataset의 이름 변환과 모든 값이 string이라는 경계, DOM metadata를 authorization·가격·업무 상태의 신뢰 근거로 사용하면 안 되는 이유를 다룹니다. FormData가 name 없는 control, disabled control, unchecked checkbox/radio를 제외하는 successful-control 모델과 일부 선택의 indeterminate property를 실행합니다. 마지막에는 공지 disclosure의 boolean source of truth 하나에서 hidden·class·aria-expanded·label을 동기화하고, 단순 overlay와 실제 modal dialog의 inertness·focus·Escape·return-focus 계약을 분리합니다. 시각 상태와 접근성 상태가 drift하지 않도록 불변식·reset·keyboard·accessibility tree·FormData를 함께 테스트합니다.",
  objectives: [
    "content attribute와 IDL property, internal/current state를 구분하고 reflection 여부를 API별로 확인할 수 있다.",
    "boolean attribute의 presence semantics를 적용해 disabled='false' 같은 오류를 진단할 수 있다.",
    "value/defaultValue·checked/defaultChecked·selected/defaultSelected와 dirty/reset 동작을 예측할 수 있다.",
    "classList·hidden·style·ARIA를 blind toggle 없이 원하는 최종 boolean state로 동기화할 수 있다.",
    "dataset의 dash-to-camel 변환·string coercion·삭제와 신뢰 경계를 설명할 수 있다.",
    "현재 form control property와 FormData entry list의 차이를 이해하고 누락 값을 명시적으로 normalize할 수 있다.",
    "전체·일부·없음 선택을 checked/indeterminate로 표현하고 필수·선택 동의 업무 규칙을 구현할 수 있다.",
    "disclosure와 modal dialog의 role·keyboard·focus·background interaction 계약을 구분하고 테스트할 수 있다.",
  ],
  prerequisites: [
    { title: "DOM 요소 생성·삽입·수정·삭제", reason: "현재 node identity를 유지하거나 교체하는 render 경계를 알고 property/class/state를 안전하게 갱신합니다.", sessionSlug: "js-06-dom-create-update-remove" },
    { title: "HTML 폼 controls와 validation", reason: "label·name·button type·native validation·제출 semantics를 알고 JavaScript current state와 FormData를 연결합니다.", sessionSlug: "html-08-form-controls-validation" },
    { title: "DOM 이벤트 등록·전파와 위임", reason: "input/change/submit/click/cancel event의 default action과 programmatic property change를 구분합니다.", sessionSlug: "js-03-event-model-listeners" },
  ],
  keywords: ["attribute", "IDL property", "reflection", "boolean attribute", "value", "defaultValue", "checked", "defaultChecked", "selected", "indeterminate", "dirty flag", "form.reset", "classList", "hidden", "dataset", "DOMStringMap", "FormData", "aria-expanded", "disclosure", "dialog", "modal", "focus management"],
  chapters: [
    {
      id: "attribute-property-reflection-model",
      title: "Attribute는 markup 문자열이고 property는 DOM interface의 typed 상태입니다",
      lead: "이름이 같아 보인다는 이유로 getAttribute와 element.property를 교환하지 말고 각 API의 source·type·reflection 규칙을 확인합니다.",
      explanations: [
        "content attribute는 HTML source 또는 DOM attribute map에 존재하는 이름과 문자열 값입니다. getAttribute(name)는 문자열 또는 없을 때 null, hasAttribute(name)는 존재 여부, setAttribute/removeAttribute/toggleAttribute는 attribute map을 바꿉니다.",
        "IDL property는 HTMLInputElement, HTMLButtonElement 같은 JavaScript interface에 정의된 property입니다. boolean·number·string·object 등 typed value를 반환하고 current interaction state 또는 다른 internal state를 표현할 수 있습니다.",
        "일부 property는 content attribute를 reflect합니다. reflection은 property get/set을 attribute parse/serialize 규칙과 연결하지만 모든 이름이 같은 property가 동일하게 반영되는 것은 아닙니다. property 정의마다 string, boolean, enum, URL, number 규칙을 공식 문서에서 확인합니다.",
        "id와 title 같은 단순 string reflection은 property 설정이 attribute 문자열에 보입니다. disabled처럼 boolean reflection은 attribute 존재를 true로, 부재를 false로 표현합니다. input.value처럼 current value와 default/attribute가 분리되는 property는 interaction 뒤 서로 달라질 수 있습니다.",
        "setAttribute는 값을 string으로 변환합니다. `setAttribute('disabled','false')`는 false boolean을 전달한 것이 아니라 disabled attribute를 값 'false'로 존재하게 만든 것입니다. current boolean을 바꾸려면 `button.disabled=false` 또는 removeAttribute를 사용합니다.",
        "property 자체도 source of truth인지 파생 값인지 구분합니다. DOM을 application database로 쓰면 re-render에서 상태가 사라질 수 있고 extension/user가 DOM을 바꿀 수 있습니다. 업무 state가 별도라면 render가 DOM property/attribute를 투영하도록 만듭니다.",
      ],
      concepts: [
        { term: "content attribute", definition: "Element의 attribute map에 저장되는 이름과 string 값 또는 부재로 HTML source에도 표현될 수 있습니다.", detail: ["getAttribute는 string/null입니다.", "markup의 default/configuration 역할이 많습니다."] },
        { term: "IDL property", definition: "DOM interface가 JavaScript에 노출하는 typed getter/setter 또는 현재 상태입니다.", detail: ["boolean/string/object 등이 가능합니다.", "attribute와 1:1이 아닐 수 있습니다."] },
        { term: "reflection", definition: "특정 IDL property가 정의된 parsing/serialization 규칙으로 content attribute를 읽고 쓰는 관계입니다.", detail: ["property마다 규칙이 다릅니다.", "boolean/enumerated/URL reflection을 구분합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "사용자가 input에 '서울'을 입력했는데 getAttribute('value')는 계속 '부산'이다.", likelyCause: "value content attribute/default와 current `.value` property를 같은 상태로 생각했습니다.", checks: ["input.value, defaultValue, getAttribute('value')를 나란히 출력합니다.", "사용자 또는 script가 current value를 바꿨는지 확인합니다.", "form reset 기준과 application source of truth를 정합니다."], fix: "현재 입력은 `.value`, reset baseline은 defaultValue/value attribute로 읽고 application state와 render ownership을 명시합니다.", prevention: "initial→user edit→attribute update→reset state matrix를 control type별 test합니다." },
      ],
    },
    {
      id: "boolean-enumerated-current-default",
      title: "Boolean attribute는 값의 철자가 아니라 존재 여부가 true이고, current와 default state는 별도입니다",
      lead: "disabled='false'를 false로 읽는 직관을 버리고 checked/value의 dirty current state까지 단계별로 추적합니다.",
      explanations: [
        "HTML boolean attribute는 존재하면 true, 없으면 false입니다. conforming source에서 present value는 empty string 또는 canonical name을 쓰며 문자열 'true'와 'false'는 boolean literal 문법이 아닙니다. 특히 disabled='false'도 attribute가 존재해 disabled입니다.",
        "enumerated attribute는 boolean과 다릅니다. 정해진 keyword, missing/empty/invalid default state를 가질 수 있어 arbitrary string을 Boolean으로 변환하면 안 됩니다. contenteditable, draggable, hidden=until-found 등은 각 state table을 확인합니다.",
        "input의 value attribute와 defaultValue는 reset 기준을 나타내고 `.value`는 current value입니다. 사용자가 입력하거나 script가 current value를 설정하면 dirty value flag가 관여해 이후 attribute/default 변경이 현재 표시값을 즉시 덮지 않을 수 있습니다.",
        "checkbox/radio의 checked attribute와 defaultChecked는 기본 checkedness, `.checked`는 current checkedness입니다. current checkedness가 dirty해진 뒤 checked attribute를 제거해도 current가 즉시 바뀌지 않을 수 있고 form.reset이 새 default로 되돌립니다.",
        "option도 selected attribute/defaultSelected와 current selected가 나뉩니다. select의 current choice는 select.value와 selectedOptions를 사용하고, multi-select에서 하나만 있다고 가정하지 않습니다.",
        "checkbox.indeterminate는 content attribute가 없는 property-only visual/current state입니다. checked와 독립적이며 form submission value를 직접 결정하지 않습니다. 전체 선택 UI는 all/some/none을 계산해 checked와 indeterminate를 모두 설정해야 합니다.",
      ],
      concepts: [
        { term: "boolean attribute", definition: "attribute 존재가 true, 부재가 false인 HTML microsyntax입니다.", detail: ["'false'도 present=true입니다.", "false는 attribute 제거로 표현합니다."] },
        { term: "dirty value/checkedness", definition: "사용자 또는 script가 control의 current state를 바꿔 default attribute 변화와 현재 상태의 자동 연결이 끊긴 상태를 설명하는 내부 flag입니다.", detail: ["current/default가 diverge합니다.", "reset이 default를 다시 적용합니다."] },
        { term: "indeterminate", definition: "checkbox가 일부 선택인 mixed 시각 상태임을 나타내는 property-only boolean입니다.", detail: ["checked와 독립입니다.", "submission value를 대신하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "attribute-property-default-reset",
          title: "value·checked·disabled의 attribute/current/default/reset 행렬",
          language: "html",
          filename: "attribute-property-reset.html",
          purpose: "boolean presence와 dirty current state가 attribute/default 변경 및 reset 뒤 어떻게 달라지는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>attribute property reset</title></head>\n<body><form id=\"profile\">\n  <input id=\"name\" value=\"initial\">\n  <input id=\"agree\" type=\"checkbox\" checked>\n  <button id=\"next\" type=\"button\" disabled=\"false\">다음</button>\n</form><pre id=\"out\"></pre>\n<script>\n  const form = document.querySelector('#profile');\n  const nameInput = document.querySelector('#name');\n  const agree = document.querySelector('#agree');\n  const next = document.querySelector('#next');\n  const lines = [];\n  lines.push(`initial:value=${nameInput.value}/default=${nameInput.defaultValue}/attr=${nameInput.getAttribute('value')}`);\n  lines.push(`initial:checked=${agree.checked}/default=${agree.defaultChecked}/attr=${agree.hasAttribute('checked')}`);\n  lines.push(`initial:disabled=${next.disabled}/attr=${next.hasAttribute('disabled')}`);\n  nameInput.value = 'current';\n  nameInput.setAttribute('value', 'new-default');\n  agree.checked = true;\n  agree.removeAttribute('checked');\n  next.disabled = false;\n  lines.push(`current:value=${nameInput.value}/default=${nameInput.defaultValue}/attr=${nameInput.getAttribute('value')}`);\n  lines.push(`current:checked=${agree.checked}/default=${agree.defaultChecked}/attr=${agree.hasAttribute('checked')}`);\n  lines.push(`current:disabled=${next.disabled}/attr=${next.hasAttribute('disabled')}`);\n  form.reset();\n  lines.push(`reset:value=${nameInput.value}/default=${nameInput.defaultValue}/attr=${nameInput.getAttribute('value')}`);\n  lines.push(`reset:checked=${agree.checked}/default=${agree.defaultChecked}/attr=${agree.hasAttribute('checked')}`);\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "2-6", explanation: "value/checked initial defaults와 non-conforming하지만 흔한 disabled='false' boolean presence fixture를 만듭니다." },
            { lines: "8-15", explanation: "current/default/attribute를 변경 전 각각 읽습니다." },
            { lines: "16-20", explanation: "current value/checked를 dirty하게 바꾸고 default attributes와 disabled current property를 갱신합니다." },
            { lines: "21-27", explanation: "변경 직후와 form.reset 뒤 current가 새 defaults로 돌아가는 결과를 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 attribute-property-reset.html을 열고 결과 확인" },
          output: { value: "initial:value=initial/default=initial/attr=initial\ninitial:checked=true/default=true/attr=true\ninitial:disabled=true/attr=true\ncurrent:value=current/default=new-default/attr=new-default\ncurrent:checked=true/default=false/attr=false\ncurrent:disabled=false/attr=false\nreset:value=new-default/default=new-default/attr=new-default\nreset:checked=false/default=false/attr=false", explanation: ["disabled='false'는 present boolean attribute라 initial disabled가 true입니다.", "current value/checked는 default attribute를 바꾼 직후에도 유지됩니다.", "reset은 새 defaultValue/defaultChecked를 current state에 다시 적용합니다."] },
          experiments: [
            { change: "next.setAttribute('disabled','false')를 실행합니다.", prediction: "next.disabled는 true가 됩니다.", result: "boolean false는 removeAttribute 또는 property=false로 표현합니다." },
            { change: "nameInput.value 설정 없이 value attribute만 바꿉니다.", prediction: "dirty하지 않은 current value는 새 default를 따라갈 수 있습니다.", result: "동일 API라도 current dirty state가 결과에 영향을 줍니다." },
            { change: "agree.indeterminate=true를 추가하고 FormData를 만듭니다.", prediction: "mixed 표시와 submission checkedness는 별도입니다.", result: "indeterminate를 업무 동의 값으로 저장하지 않습니다." },
          ],
          sourceRefs: ["web-dom-checkbox-state-source", "whatwg-boolean-attributes", "whatwg-attribute-reflection", "whatwg-input-state"],
        },
      ],
      diagnostics: [
        { symptom: "disabled='false'라고 썼는데 button이 비활성화된다.", likelyCause: "boolean attribute에 문자열 false를 사용했고 presence가 true를 뜻합니다.", checks: ["hasAttribute와 `.disabled`를 함께 확인합니다.", "boolean인지 enumerated attribute인지 공식 정의를 봅니다.", "template/framework가 false attribute를 omit하는지 inspect합니다."], fix: "HTML에서는 disabled attribute를 제거하고 JavaScript에서는 button.disabled=false를 설정합니다.", prevention: "boolean attribute serializer test와 rendered DOM inspection을 component test에 둡니다." },
      ],
    },
    {
      id: "form-current-state-events-reset",
      title: "현재 폼 상태는 property로 읽고 programmatic change·user event·reset default action을 구분합니다",
      lead: "값을 바꿨다는 사실과 input/change event가 발생했다는 사실을 같은 것으로 취급하지 않습니다.",
      explanations: [
        "text-like input과 select의 현재 값은 `.value`, checkbox/radio는 `.checked`, multi-select는 `.selectedOptions`를 사용합니다. checked attribute selector만 조회하면 사용자가 바꾼 current checkedness가 아니라 markup default를 찾을 수 있습니다.",
        "사용자가 typing/selection하면 적절한 input/change event가 user agent에서 발생하지만 script로 `control.value=...` 또는 `checked=...`를 설정해도 해당 event가 자동 dispatch되지 않습니다. event callback에만 파생 UI 갱신을 묶지 말고 state를 바꾼 code가 공용 render를 호출합니다.",
        "synthetic Event를 dispatch하면 listener는 실행되지만 browser의 trusted user interaction과 동일하지 않고 기본 control behavior가 자동 재현되지 않습니다. test는 domain transition 함수를 직접 호출하거나 실제 user interaction E2E를 사용합니다.",
        "form.reset() method와 type=reset button의 default action은 controls를 defaults로 되돌립니다. reset event timing과 cancelability를 고려해 파생 summary/class/button state도 reset 뒤 다시 계산합니다. 이름이 reset인 form control이 method property를 가리는 legacy named access도 피합니다.",
        "disabled control은 focus/interaction/submission에서 제외되는 semantics가 있고 aria-disabled='true'는 접근성 상태만 전달할 뿐 native behavior를 막지 않습니다. 실제 button을 비활성화할지, 활성 상태로 두고 validation reason을 보여 줄지 UX 요구를 정합니다.",
        "원본은 하나라도 checked면 다음 button을 활성화합니다. 실제 약관에서는 모든 필수 항목인지, 하나 이상인지, 선택 마케팅은 무관한지 product rule을 명시해야 합니다. UI condition을 some/every 이름만으로 결정하지 않습니다.",
      ],
      concepts: [
        { term: "current control state", definition: "사용자 interaction과 script assignment가 반영된 value·checked·selected 등 현재 DOM property 상태입니다.", detail: ["attribute selector와 다를 수 있습니다.", "submission/validation과 연결됩니다."] },
        { term: "programmatic change", definition: "script가 property를 직접 설정하는 변경으로 일반적으로 input/change user event를 자동 발생시키지 않습니다.", detail: ["공용 render를 호출합니다.", "synthetic event와 trusted input은 다릅니다."] },
        { term: "reset baseline", definition: "form.reset이 current state를 되돌릴 때 사용하는 defaultValue/defaultChecked/defaultSelected 계열 상태입니다.", detail: ["attributes 변경으로 갱신될 수 있습니다.", "파생 UI도 재계산합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "script가 모든 checkbox를 checked=true로 바꿨는데 summary와 다음 button이 갱신되지 않는다.", likelyCause: "property assignment가 change event를 자동 발생시킬 것이라고 기대했습니다.", checks: ["property 값과 event listener 호출 count를 따로 기록합니다.", "state change owner가 render를 직접 호출하는지 봅니다.", "synthetic event 남용 여부를 확인합니다."], fix: "event handler와 programmatic action 모두 동일한 transition/render 함수를 명시적으로 호출합니다.", prevention: "user click과 direct API update가 같은 invariant를 만드는 parity test를 둡니다." },
        { symptom: "form.reset 뒤 input 값은 돌아왔지만 summary·class·button disabled는 이전 상태다.", likelyCause: "native controls만 reset되고 JavaScript 파생 UI를 다시 render하지 않았습니다.", checks: ["reset 전후 current/default controls를 출력합니다.", "reset event/default action 뒤 render timing을 확인합니다.", "파생 state가 DOM에 중복 저장됐는지 봅니다."], fix: "reset lifecycle 뒤 current control state를 기준으로 summary/all/mixed/disabled/class/ARIA를 한 번 다시 계산합니다.", prevention: "edit→derived UI→reset→all invariants E2E를 둡니다." },
      ],
    },
    {
      id: "classlist-hidden-style-state",
      title: "classList는 token을, hidden은 semantic visibility를, style은 presentation을 다룹니다",
      lead: "한 boolean source에서 원하는 최종 상태를 계산하고 각 표현을 force 인수로 idempotent하게 갱신합니다.",
      explanations: [
        "element.className은 class attribute 전체 string을 읽고 씁니다. `className='is-open'`은 layout·theme·utility class까지 덮어쓸 수 있어 한 상태 token만 관리할 때 classList.add/remove/toggle/replace를 사용합니다.",
        "classList는 DOMTokenList입니다. toggle(token, force)의 force가 true면 token을 보장하고 false면 제거해 같은 render를 여러 번 호출해도 desired state가 유지됩니다. force 없이 blind toggle하면 duplicate event/re-render에서 상태가 반대로 뒤집힐 수 있습니다.",
        "빈 token은 SyntaxError, ASCII whitespace가 든 한 token은 InvalidCharacterError가 날 수 있습니다. 외부 문자열을 class token으로 직접 쓰지 않고 allowlisted state를 code의 fixed token으로 map합니다.",
        "hidden attribute/property는 content가 현재 관련 없음을 나타내고 user agent stylesheet가 보통 표시하지 않습니다. CSS가 hidden display를 override하지 않게 하고, hidden='until-found' 같은 별도 상태가 필요한 기능에서는 단순 boolean property로 모든 nuance를 덮지 않습니다.",
        "element.style은 inline declaration만 다룹니다. `.style.display`가 빈 문자열이어도 stylesheet 결과는 none일 수 있고, computedStyle은 cascade 뒤 computed value를 읽지만 layout/style calculation cost가 있습니다. 업무 open state를 computed display에서 역추론하지 않습니다.",
        "시각 애니메이션 class와 semantic hidden timing이 다르면 screen reader/keyboard가 보이지 않는 content에 접근하거나 transition을 못 볼 수 있습니다. opening/closing state machine, prefers-reduced-motion, transitionend fallback을 명시합니다.",
      ],
      concepts: [
        { term: "DOMTokenList", definition: "class·rel 같은 space-separated token attribute를 집합형 API로 관리하는 interface입니다.", detail: ["add/remove/contains/replace/toggle이 있습니다.", "toggle(force)가 idempotent합니다."] },
        { term: "derived visual state", definition: "authoritative boolean/application state에서 계산해 class/style/hidden으로 표현한 UI 상태입니다.", detail: ["DOM에서 다시 추론하지 않습니다.", "ARIA와 함께 갱신합니다."] },
        { term: "computed style", definition: "cascade와 inheritance 등을 적용한 뒤 user agent가 제공하는 resolved style view입니다.", detail: ["inline style과 다릅니다.", "반복 layout-dependent read 비용을 측정합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "공지 열기 뒤 layout/theme class가 모두 사라졌다.", likelyCause: "`className='is-open'`으로 전체 class attribute를 덮어썼습니다.", checks: ["변경 전후 className과 classList tokens를 비교합니다.", "CSS/JS가 소유하는 tokens를 분류합니다.", "blind toggle 중복 호출을 확인합니다."], fix: "`classList.toggle('is-open', open)`처럼 상태 token 하나만 원하는 boolean으로 갱신합니다.", prevention: "base classes 보존과 repeated render idempotence invariant test를 둡니다." },
      ],
    },
    {
      id: "dataset-metadata-trust-boundary",
      title: "dataset은 HTML data-* 문자열 metadata 경계이지 신뢰 가능한 업무 state 저장소가 아닙니다",
      lead: "이름 변환과 string coercion을 이해하고 DOM에서 읽은 값은 외부 입력처럼 parse·검증합니다.",
      explanations: [
        "HTML custom data attribute는 `data-*` 이름으로 page-specific metadata를 element에 둡니다. `data-course-id`는 `element.dataset.courseId`처럼 dash 뒤 ASCII lowercase가 uppercase로 변환된 DOMStringMap property로 접근합니다.",
        "dataset으로 읽은 값은 모두 string입니다. `data-max-items='10'`은 number 10이 아니므로 lexical comparison 전에 Number 변환과 finite/integer/range validation을 합니다. 'false'도 truthy string이므로 Boolean(value)를 업무 boolean parser로 쓰지 않습니다.",
        "dataset assignment는 값을 string으로 serialize합니다. null을 넣으면 attribute 제거가 아니라 문자열 'null'이 될 수 있으므로 제거는 `delete element.dataset.key` 또는 removeAttribute를 사용합니다.",
        "data-*는 record ID, action name, analytics category처럼 DOM과 controller 사이의 작은 metadata에 적합합니다. 큰 JSON graph, secret token, 개인정보, source-of-truth application state를 넣으면 markup 비대·동기화 drift·노출 위험이 커집니다.",
        "사용자, browser extension, XSS, DevTools는 DOM attribute를 바꿀 수 있습니다. data-role='admin', data-price, data-owner를 authorization·결제·server access 판정의 근거로 신뢰하지 않고 server/session/database에서 검증합니다.",
        "표준 semantic attribute/property가 이미 있으면 custom data copy를 만들지 않습니다. data-disabled 대신 button.disabled, data-checked 대신 input.checked를 사용해 native behavior·submission·accessibility와 상태가 갈라지지 않게 합니다.",
      ],
      concepts: [
        { term: "DOMStringMap", definition: "element의 custom data-* attributes를 camelCase property와 string values로 노출하는 dataset interface입니다.", detail: ["dash/case 변환이 있습니다.", "값은 string입니다."] },
        { term: "DOM metadata", definition: "특정 element의 controller action·record key 등 DOM integration에 필요한 작은 보조 정보입니다.", detail: ["source of truth와 구분합니다.", "parse/validation이 필요합니다."] },
        { term: "trust boundary", definition: "값을 권한·가격·명령에 사용하기 전에 공격자나 외부 actor가 바꿀 수 있는지 판단하고 재검증하는 경계입니다.", detail: ["DOM은 신뢰 경계 밖입니다.", "server authorization을 대체하지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "dataset-string-boundary",
          title: "data-* 이름 변환·문자열 type·반영·삭제",
          language: "html",
          filename: "dataset-boundary.html",
          purpose: "dataset 값이 string이고 assignment/delete가 실제 attribute에 반영되는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>dataset</title></head>\n<body><article id=\"card\" data-course-id=\"js-07\" data-max-items=\"3\" data-temporary=\"yes\"></article><pre id=\"out\"></pre>\n<script>\n  const card = document.querySelector('#card');\n  const lines = [];\n  lines.push(`course=${card.dataset.courseId}`);\n  lines.push(`raw=${card.dataset.maxItems},type=${typeof card.dataset.maxItems},number=${Number(card.dataset.maxItems)}`);\n  card.dataset.maxItems = '5';\n  lines.push(`after-set=${card.getAttribute('data-max-items')}`);\n  delete card.dataset.temporary;\n  lines.push(`temporary-present=${card.hasAttribute('data-temporary')}`);\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "2", explanation: "dash-form course-id/max-items/temporary custom data attributes를 선언합니다." },
            { lines: "5-7", explanation: "camelCase dataset access와 raw string/type/explicit number conversion을 기록합니다." },
            { lines: "8-11", explanation: "dataset assignment의 attribute reflection과 delete의 attribute removal을 확인합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 dataset-boundary.html을 열고 결과 확인" },
          output: { value: "course=js-07\nraw=3,type=string,number=3\nafter-set=5\ntemporary-present=false", explanation: ["course-id는 courseId property로 변환됩니다.", "maxItems는 숫자 모양이어도 string이며 명시 변환 뒤 number 3입니다.", "set/delete가 대응하는 data-* attribute를 갱신합니다."] },
          experiments: [
            { change: "card.dataset.maxItems=null을 설정합니다.", prediction: "attribute가 제거되지 않고 문자열 'null'로 serialize될 수 있습니다.", result: "부재는 delete로 표현합니다." },
            { change: "max-items를 '3items'로 바꿉니다.", prediction: "Number 결과는 NaN입니다.", result: "finite/integer/range를 validation합니다." },
            { change: "data-role='admin'을 바꿔 client 권한 분기를 통과시킵니다.", prediction: "DOM만 믿는 권한은 조작됩니다.", result: "server가 authoritative authorization을 수행합니다." },
          ],
          sourceRefs: ["whatwg-custom-data", "dom-standard"],
        },
      ],
      diagnostics: [
        { symptom: "dataset.maxItems '10'과 '2'를 정렬했더니 10이 먼저 온다.", likelyCause: "dataset string을 lexical order로 비교했습니다.", checks: ["typeof와 raw JSON string을 출력합니다.", "Number 결과의 finite/integer/range를 검사합니다.", "invalid/missing/null 문자열 정책을 확인합니다."], fix: "schema에 맞게 parse·validate한 number model로 비교하고 DOM에는 stable serialized metadata만 둡니다.", prevention: "missing/empty/leading-zero/NaN/Infinity/out-of-range dataset corpus test를 둡니다." },
        { symptom: "DevTools에서 data-role을 admin으로 바꾸자 관리자 기능이 실행된다.", likelyCause: "DOM dataset을 authorization source of truth로 신뢰했습니다.", checks: ["client action부터 server endpoint까지 권한 검사를 추적합니다.", "dataset 기반 가격/owner/role branch를 inventory합니다.", "직접 HTTP 요청으로 우회를 재현합니다."], fix: "client metadata는 UI routing key로만 사용하고 server가 authenticated identity와 resource authorization을 매 요청 검증합니다.", prevention: "권한 없는 direct request integration test와 tampered DOM E2E를 둡니다." },
      ],
    },
    {
      id: "formdata-entry-list-tristate",
      title: "FormData는 모든 property를 복사하지 않고 제출 가능한 controls의 entry list를 구성합니다",
      lead: "현재 화면 state와 실제 request payload를 나란히 확인하고 unchecked·disabled·no-name 누락을 false/empty 정책으로 처리합니다.",
      explanations: [
        "new FormData(form)는 HTML의 constructing the entry list 알고리즘에 따라 name/value entries를 만듭니다. 모든 descendants나 모든 properties를 JSON처럼 복사하는 API가 아닙니다.",
        "name이 없는 control, disabled control, unchecked checkbox/radio 등은 일반적으로 entries에서 제외됩니다. checkbox false가 `false` string으로 포함되지 않으므로 server는 absent를 false/empty list로 normalize하고 required agreement를 별도로 검증합니다.",
        "같은 name의 여러 checkbox는 여러 entries가 되어 get은 첫 값, getAll은 전체 값을 반환합니다. Object.fromEntries만 쓰면 duplicate names가 마지막 하나로 접혀 multi-value가 소실될 수 있습니다.",
        "select current value와 checkbox checkedness를 property에서 읽어 화면 summary를 만들고 같은 순간 FormData entries와 비교합니다. disabled로 숨긴 field 값이 client model에는 있어도 payload에는 없을 수 있습니다.",
        "원본 전체 선택 로직은 children 일부 선택 시 selectAll.checked=false만 설정하고 mixed visual state를 놓칩니다. `all=count>0&&every`, `some=some`, `indeterminate=some&&!all`을 매 render 계산합니다. every([])는 true이므로 count guard가 필요합니다.",
        "다음 button rule은 any/all-required/all을 product requirement로 이름 붙입니다. 필수 이용약관·개인정보는 모두 checked, 선택 marketing은 제출에 포함하되 진행 허용에는 영향 없도록 record metadata에서 required를 판단합니다.",
        "submit event에서는 preventDefault 여부와 native constraint validation을 의도적으로 결정합니다. 중복 submit, server validation, CSRF/authorization은 client disabled state만으로 해결되지 않습니다.",
      ],
      concepts: [
        { term: "form entry list", definition: "form submission 또는 FormData 생성 시 successful controls에서 name/value entries를 구성한 ordered list입니다.", detail: ["모든 DOM state가 포함되지 않습니다.", "duplicate names가 가능합니다."] },
        { term: "successful control", definition: "name·disabled·checked·submitter 등 조건을 충족해 form entry에 참여하는 control을 설명하는 모델입니다.", detail: ["unchecked checkbox는 제외됩니다.", "server가 absence를 해석합니다."] },
        { term: "tri-state aggregate", definition: "child selections가 none/some/all인지 checked와 indeterminate 두 properties로 표현하는 전체 선택 상태입니다.", detail: ["every([]) guard가 필요합니다.", "업무 required rule과 구분합니다."] },
      ],
      codeExamples: [
        {
          id: "formdata-tristate-current-state",
          title: "현재 value·FormData entries·전체 선택 mixed 상태 동기화",
          language: "html",
          filename: "formdata-tristate.html",
          purpose: "원본 전체 선택을 current properties, FormData duplicate entries와 indeterminate까지 확장해 세 상태 exact output을 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>form state</title></head>\n<body><form id=\"signup\">\n  <label>이름 <input name=\"displayName\" value=\"초기\"></label>\n  <label>요금제 <select name=\"plan\"><option value=\"basic\" selected>기본</option><option value=\"pro\">프로</option></select></label>\n  <label><input id=\"selectAll\" type=\"checkbox\"> 모두 동의</label>\n  <label><input class=\"agree\" type=\"checkbox\" name=\"agreements\" value=\"terms\" checked> 이용약관</label>\n  <label><input class=\"agree\" type=\"checkbox\" name=\"agreements\" value=\"privacy\"> 개인정보</label>\n  <label><input class=\"agree\" type=\"checkbox\" name=\"agreements\" value=\"marketing\" checked> 마케팅</label>\n  <button id=\"next\" type=\"submit\" disabled>다음</button>\n</form><pre id=\"out\"></pre>\n<script>\n  const form = document.querySelector('#signup');\n  const selectAll = document.querySelector('#selectAll');\n  const agrees = [...document.querySelectorAll('.agree')];\n  const next = document.querySelector('#next');\n  const lines = [];\n  form.elements.displayName.value = '민지';\n  form.elements.plan.value = 'pro';\n  function render(label) {\n    const checked = agrees.filter(item => item.checked);\n    const all = agrees.length > 0 && checked.length === agrees.length;\n    const some = checked.length > 0;\n    selectAll.checked = all;\n    selectAll.indeterminate = some && !all;\n    next.disabled = !all;\n    const data = new FormData(form);\n    const summary = `name=${form.elements.displayName.value},plan=${form.elements.plan.value},agreements=${data.getAll('agreements').join('|')}`;\n    lines.push(`${label}:${summary},all=${selectAll.checked},mixed=${selectAll.indeterminate},nextDisabled=${next.disabled}`);\n  }\n  render('initial');\n  agrees.forEach(item => { item.checked = true; });\n  render('after-all');\n  agrees[1].checked = false;\n  render('after-one-off');\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "2-9", explanation: "text/select, 전체 선택, 같은 name의 세 agreements와 disabled submit을 구성합니다." },
            { lines: "12-18", explanation: "현재 name/plan property를 programmatically 바꾸고 controls/references를 준비합니다." },
            { lines: "19-28", explanation: "all/some/mixed/disabled를 매번 계산하고 FormData.getAll로 실제 agreement entries를 읽습니다." },
            { lines: "29-34", explanation: "some→all→some 상태를 직접 만들고 공용 render를 호출해 exact output을 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 formdata-tristate.html을 열고 결과 확인" },
          output: { value: "initial:name=민지,plan=pro,agreements=terms|marketing,all=false,mixed=true,nextDisabled=true\nafter-all:name=민지,plan=pro,agreements=terms|privacy|marketing,all=true,mixed=false,nextDisabled=false\nafter-one-off:name=민지,plan=pro,agreements=terms|marketing,all=false,mixed=true,nextDisabled=true", explanation: ["initial과 after-one-off에는 privacy unchecked entry가 없어 getAll 결과가 terms|marketing입니다.", "모두 선택했을 때 checked=true, indeterminate=false, next enabled가 됩니다.", "property를 script로 바꾼 뒤 event가 아니라 render를 명시 호출했습니다."] },
          experiments: [
            { change: "privacy control을 checked이면서 disabled로 만듭니다.", prediction: "UI property는 checked여도 FormData entries에서는 제외됩니다.", result: "화면 summary와 payload contract를 함께 test합니다." },
            { change: "agreements name을 제거합니다.", prediction: "checked여도 FormData에 포함되지 않습니다.", result: "name은 submission contract입니다." },
            { change: "agrees를 빈 배열로 만들고 every만 사용합니다.", prediction: "every([])는 true가 됩니다.", result: "all 계산에 length>0 guard와 empty product state를 둡니다." },
          ],
          sourceRefs: ["web-dom-checkbox-state-source", "whatwg-input-state", "whatwg-form-entry-list"],
        },
      ],
      diagnostics: [
        { symptom: "FormData에 unchecked checkbox나 disabled field가 없어서 server가 key missing 오류를 낸다.", likelyCause: "form entry list가 모든 control을 포함한다고 가정하고 absent normalization/schema를 만들지 않았습니다.", checks: ["[...new FormData(form).entries()]를 privacy-safe fixture로 확인합니다.", "name/disabled/checked/submitter 조건을 검사합니다.", "multi-value를 getAll로 읽는지 봅니다."], fix: "server schema에서 absent checkbox를 false/empty list로 normalize하고 required fields를 검증하며 client/server contract test를 둡니다.", prevention: "checked/unchecked/disabled/no-name/multi-select/multiple same-name payload matrix를 자동화합니다." },
        { symptom: "항목이 하나도 없는데 전체 선택 checkbox가 checked=true가 된다.", likelyCause: "Array.every가 empty array에서 true인 vacuous truth를 반환합니다.", checks: ["collection length와 every/some 결과를 출력합니다.", "empty list의 UX requirement를 정의합니다.", "live/static collection 변화를 확인합니다."], fix: "`all=items.length>0&&items.every(...)`로 계산하고 empty에서는 checked/indeterminate=false와 안내 상태를 제공합니다.", prevention: "0/1/일부/전체/dynamic removal aggregate state test를 둡니다." },
      ],
    },
    {
      id: "disclosure-state-aria-sync",
      title: "Disclosure는 boolean source 하나에서 hidden·class·aria-expanded·label을 함께 갱신합니다",
      lead: "ARIA는 기능을 만들어 주는 code가 아니라 현재 기능 state를 접근성 API에 전달하는 계약입니다.",
      explanations: [
        "원본 notice는 별도 window를 닫는 content입니다. 같은 page에서 공지를 접고 펼치는 요구라면 native button과 controlled region으로 disclosure를 만들고 popup/window lifecycle과 혼합하지 않습니다.",
        "button은 기본 keyboard Enter/Space activation과 focus semantics를 제공합니다. div/span click handler에 role/tabindex/keyboard behavior를 다시 구현하기보다 실제 button을 사용합니다.",
        "aria-controls는 button이 제어하는 panel ID를 가리키고 aria-expanded는 현재 펼침 상태를 'true'/'false'로 전달합니다. 이 attribute를 바꾼다고 panel이 자동 show/hide되지는 않으므로 JavaScript가 hidden/class를 함께 갱신합니다.",
        "authoritative `open` boolean 하나를 state로 두고 render(open)이 button aria-expanded, panel.hidden, is-open class, button label/icon을 같은 호출에서 설정합니다. DOM attribute들을 각각 source로 다시 읽어 계산하면 drift가 순환합니다.",
        "toggle handler는 next state를 `!open`으로 한 번 계산한 뒤 render합니다. render 내부에서 각 표현을 blind toggle하지 않으므로 duplicate event나 initial hydration 후에도 idempotent합니다.",
        "expanded와 visible이 어긋나면 sighted keyboard user와 screen reader user가 다른 UI를 경험합니다. `expanded === !hidden`, `class contains is-open === open`, accessible name과 region relationship을 component/integration test로 고정합니다.",
      ],
      concepts: [
        { term: "disclosure", definition: "button이 연결된 content section의 표시/숨김을 전환하는 interaction pattern입니다.", detail: ["native button을 사용합니다.", "aria-expanded와 controls를 제공합니다."] },
        { term: "ARIA state", definition: "accessibility API에 현재 role/property/state를 전달하는 semantic metadata입니다.", detail: ["behavior를 자동 구현하지 않습니다.", "실제 UI와 동기화해야 합니다."] },
        { term: "UI invariant", definition: "여러 표현이 항상 같은 authoritative state를 나타내야 한다는 검증 가능한 관계입니다.", detail: ["expanded와 hidden을 연결합니다.", "repeated render에서도 유지합니다."] },
      ],
      codeExamples: [
        {
          id: "class-hidden-aria-dataset-sync",
          title: "공지 disclosure의 class·hidden·ARIA·dataset 동기화",
          language: "html",
          filename: "notice-disclosure.html",
          purpose: "한 open boolean에서 네 표현을 force 방식으로 갱신해 close→open→close invariant exact output을 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>disclosure</title></head>\n<body><button id=\"toggle\" type=\"button\" aria-expanded=\"false\" aria-controls=\"notice\" data-action=\"toggle-notice\">공지사항</button>\n<section id=\"notice\" class=\"notice\" hidden><h2>점검 안내</h2><p>금요일 22시 점검입니다.</p></section><pre id=\"out\"></pre>\n<script>\n  const button = document.querySelector('#toggle');\n  const panel = document.querySelector('#notice');\n  const lines = [];\n  function render(open, label) {\n    button.setAttribute('aria-expanded', String(open));\n    panel.hidden = !open;\n    panel.classList.toggle('is-open', open);\n    panel.dataset.state = open ? 'open' : 'closed';\n    lines.push(`${label}:expanded=${button.getAttribute('aria-expanded')},hidden=${panel.hidden},class=${panel.className},state=${panel.dataset.state}`);\n  }\n  render(false, 'initial');\n  render(true, 'open');\n  render(false, 'closed');\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "2-3", explanation: "native button과 controlled section을 aria-controls ID로 연결하고 initial hidden/expanded를 일치시킵니다." },
            { lines: "7-14", explanation: "render 하나가 aria-expanded, hidden, class token, diagnostic metadata를 desired open boolean으로 설정합니다." },
            { lines: "15-18", explanation: "같은 함수로 닫힘·열림·닫힘을 재현해 blind toggle 없이 idempotent 결과를 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 notice-disclosure.html을 열고 결과 확인" },
          output: { value: "initial:expanded=false,hidden=true,class=notice,state=closed\nopen:expanded=true,hidden=false,class=notice is-open,state=open\nclosed:expanded=false,hidden=true,class=notice,state=closed", explanation: ["expanded와 hidden은 항상 반대 boolean으로 일치합니다.", "is-open은 base notice class를 지우지 않고 원하는 상태에서만 존재합니다.", "dataset state는 관찰용 파생 metadata이지 authoritative state가 아닙니다."] },
          experiments: [
            { change: "classList.toggle에서 force 인수를 제거하고 render(true)를 두 번 호출합니다.", prediction: "두 번째 호출이 class를 제거해 open state와 drift합니다.", result: "desired boolean을 force로 전달합니다." },
            { change: "aria-expanded update를 제거합니다.", prediction: "화면은 열려도 accessibility state는 false로 남습니다.", result: "하나의 render에서 모든 표현을 갱신합니다." },
            { change: "button을 span으로 바꿉니다.", prediction: "기본 focus/Enter/Space button behavior가 사라집니다.", result: "semantic native control을 우선합니다." },
          ],
          sourceRefs: ["web-notice-popup-source", "dom-token-list", "wai-aria-expanded", "wai-disclosure"],
        },
      ],
      diagnostics: [
        { symptom: "화면 공지는 열렸지만 screen reader는 button을 '접힘'으로 알린다.", likelyCause: "style/class/hidden과 aria-expanded를 서로 다른 handler에서 갱신해 state가 drift했습니다.", checks: ["button attribute와 panel.hidden/class를 같은 순간 assert합니다.", "accessibility tree의 role/name/state를 확인합니다.", "duplicate/async render order를 추적합니다."], fix: "authoritative open boolean과 단일 render에서 모든 표현을 idempotent하게 설정합니다.", prevention: "expanded===!hidden===class state invariant와 keyboard/accessibility integration test를 둡니다." },
      ],
    },
    {
      id: "overlay-versus-modal-dialog",
      title: "화면 위에 보이는 overlay와 modal dialog의 상호작용·초점 계약은 다릅니다",
      lead: "display:block 하나로는 background inertness, dialog name, focus containment와 return focus가 생기지 않습니다.",
      explanations: [
        "원본 modal은 fixed overlay의 display를 block/none으로 바꾸므로 시각적으로는 modal처럼 보입니다. 그러나 close span은 button이 아니고 dialog role/name, background interaction 차단, initial focus, Tab 범위, opener focus return이 없습니다.",
        "native `<dialog>`의 showModal()은 dialog를 top layer에 modal로 표시하고 다른 document content를 inert하게 취급하는 platform behavior를 제공합니다. show()는 non-modal이며 open attribute를 직접 붙이는 것과 lifecycle/error/focus semantics가 다릅니다.",
        "dialog에는 aria-labelledby 또는 accessible name이 필요하고 content가 길면 initial focus 위치를 task와 읽기 순서에 맞게 선택합니다. 닫기 button은 실제 button이며 Escape의 cancel event와 close result를 product 정책으로 처리합니다.",
        "modal을 연 element reference를 저장하고 close 뒤 logical opener가 여전히 연결/사용 가능하면 focus를 돌려줍니다. opener가 삭제됐다면 다음 logical workflow target을 선택합니다.",
        "custom modal이 필요한 경우 APG contract에 따라 Tab/Shift+Tab을 내부에 유지하고 Escape, accessible name/description, initial/return focus, background inertness를 모두 구현합니다. role=dialog와 aria-modal=true만 추가해 behavior 결손을 숨기지 않습니다.",
        "backdrop click으로 닫기는 accidental dismissal과 pointer coordinate/event target 문제를 고려합니다. 중요한 입력은 명시적 close/cancel과 unsaved confirmation을 제공하고 backdrop policy를 test합니다.",
        "popup window의 window.close와 in-page dialog.close는 다른 lifecycle입니다. popup blocker/opener/origin은 JS04, DOM state와 dialog focus/accessibility는 현재 세션 범위로 분리합니다.",
      ],
      concepts: [
        { term: "modal dialog", definition: "사용자가 dialog를 닫거나 완료하기 전까지 바깥 content와 interaction할 수 없도록 하는 focused interaction context입니다.", detail: ["background가 inert합니다.", "focus와 accessible name을 관리합니다."] },
        { term: "top layer", definition: "modal dialog 등 특정 elements를 일반 stacking context 밖의 user-agent 관리 layer에 표시하는 platform model입니다.", detail: ["z-index overlay와 다릅니다.", "showModal이 사용합니다."] },
        { term: "return focus", definition: "dialog 종료 뒤 사용자의 workflow를 이어갈 logical opener 또는 다음 target으로 keyboard focus를 복구하는 절차입니다.", detail: ["opener 연결 여부를 확인합니다.", "삭제됐을 때 fallback이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "modal이 보이지만 Tab이 뒤 page로 이동하고 screen reader가 dialog라고 알리지 않는다.", likelyCause: "display overlay만 만들고 modal semantics·inertness·focus lifecycle을 구현하지 않았습니다.", checks: ["accessibility tree의 role/name/modal state를 봅니다.", "Tab/Shift+Tab/Escape와 initial/return focus를 실행합니다.", "background click/keyboard interaction 가능 여부를 검사합니다."], fix: "가능하면 native dialog.showModal/close와 labeled semantic content를 사용하고 custom이면 APG modal contract 전체를 구현합니다.", prevention: "keyboard-only, screen reader, background inertness, opener removal, nested/rapid open-close E2E를 둡니다." },
        { symptom: "닫기 X가 mouse로만 동작하고 keyboard focus를 받을 수 없다.", likelyCause: "span에 click listener만 붙여 visual icon을 button처럼 사용했습니다.", checks: ["Tab order와 element role/name을 확인합니다.", "Enter/Space activation을 test합니다.", "focus ring과 target size를 봅니다."], fix: "type=button과 명확한 accessible name을 사용하고 native click activation을 처리합니다.", prevention: "interactive behavior에는 native semantic element를 요구하는 lint/accessibility review를 둡니다." },
      ],
    },
    {
      id: "invariants-security-performance-testing",
      title: "State drift는 불변식·payload·keyboard·accessibility tree를 함께 검사해 예방합니다",
      lead: "DOM snapshot이 비슷해 보이는 것만 확인하지 말고 current/default/derived/submitted state가 합의한 계약을 만족하는지 검증합니다.",
      explanations: [
        "attribute/property test는 initial markup, user edit, programmatic current change, default attribute change, reset 순서의 matrix를 만듭니다. 한 시점 screenshot만으로 dirty flag와 FormData 차이를 확인할 수 없습니다.",
        "disclosure invariant는 `open===aria-expanded==='true'`, `open===!hidden`, `open===classList.contains('is-open')`입니다. render(false/true)를 반복하고 duplicate event, mount, route restore에서도 관계를 유지합니다.",
        "agreement invariant는 all/some/none, required subset, selectAll.checked/indeterminate, next.disabled, FormData getAll이 같은 control state를 해석해야 합니다. empty list와 동적 추가/삭제도 포함합니다.",
        "E2E는 pointer만 click하지 않고 Tab/Shift+Tab/Enter/Space/Escape, focus order/return, dialog background inertness와 accessible role/name/state를 확인합니다. ARIA attribute string snapshot만으로 실제 접근성 경험을 보장하지 않습니다.",
        "security test는 dataset tampering, DOM action ID 변조, direct server request를 포함합니다. client disabled·hidden·data-role은 보안 경계가 아니며 server authentication/authorization/validation과 CSRF 정책을 별도로 검증합니다.",
        "performance는 class/style write와 computed layout read를 반복 교차하지 않도록 batch합니다. 그러나 form 수십 개의 property 계산을 미리 micro-optimize하기보다 실제 interaction latency와 style/layout trace를 측정하고 maintainability를 우선합니다.",
        "telemetry에는 전체 FormData, hidden inputs, agreement text, raw DOM/innerHTML을 기록하지 않습니다. invariant failure code, control count, state booleans, redacted field names처럼 복구에 필요한 최소 정보만 남깁니다.",
      ],
      concepts: [
        { term: "state drift", definition: "한 logical state를 표현하는 property·class·ARIA·summary·payload가 서로 다른 값을 나타내는 결함입니다.", detail: ["단일 render로 줄입니다.", "불변식으로 발견합니다."] },
        { term: "semantic E2E test", definition: "DOM 구조뿐 아니라 role/name/state, keyboard/focus와 실제 FormData behavior를 사용자 workflow로 확인하는 test입니다.", detail: ["pointer-only를 피합니다.", "reset/empty/dynamic case를 포함합니다."] },
        { term: "client-side advisory state", definition: "disabled/hidden/dataset처럼 UX를 돕지만 공격자가 우회할 수 있어 server 보안을 대체하지 않는 state입니다.", detail: ["직접 request를 test합니다.", "authorization은 server가 수행합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "component test는 통과하지만 실제 submit payload에 필수 agreement가 없거나 modal keyboard 사용이 불가능하다.", likelyCause: "class/attribute snapshot만 검사하고 FormData entry list·current properties·keyboard/focus/accessibility behavior를 테스트하지 않았습니다.", checks: ["실제 FormData entries를 확인합니다.", "keyboard-only workflow와 accessibility tree를 검사합니다.", "initial/edit/reset/dynamic matrix가 있는지 봅니다."], fix: "state invariant unit test와 semantic browser E2E를 결합하고 server request validation까지 contract test합니다.", prevention: "모든 interactive component Definition of Done에 property/payload/keyboard/focus/ARIA/privacy checks를 포함합니다." },
      ],
      expertNotes: [
        "Web Components/custom elements의 reflected attributes는 attributeChangedCallback과 property upgrade timing을 추가로 다룹니다. property-before-definition과 reflection loop를 별도 component standard로 관리합니다.",
        "React 같은 framework에서 checked/value를 넘기는 controlled component와 defaultChecked/defaultValue를 쓰는 uncontrolled component를 섞으면 같은 current/default drift가 나타납니다.",
        "ARIA reflection IDL properties가 지원되는 runtime도 있지만 content attributes와 accessibility tree 결과를 공식 support matrix/E2E로 확인하고 semantic native element를 우선합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 전체 선택·공지·시각 모달을 state invariant가 검증되는 가입 동의 UI로 재구축하기",
    scenario: "현재 전체 선택은 일부 선택 mixed 상태와 필수/선택 규칙이 없고, script property 변경 뒤 event에 의존합니다. 공지는 별도 window close이고 modal은 display만 바꿔 keyboard·focus·dialog semantics가 빠져 있습니다.",
    setup: [
      "원본 day09 ex06, day08 ex10/ex11 세 파일을 read-only evidence로 준비합니다.",
      "modern browser DevTools Elements/Accessibility와 keyboard-only·screen reader smoke 환경을 엽니다.",
      "0/1/일부/전체, 필수/선택, checked/disabled/no-name, user/programmatic/reset form fixture를 준비합니다.",
      "dataset tamper/direct request, duplicate render/event, opener removal과 long dialog content scenario를 준비합니다.",
    ],
    steps: [
      "각 control의 attribute, default property, current property와 FormData entry를 initial/edit/default-change/reset 표로 기록합니다.",
      "필수 agreement metadata를 application state로 정의하고 all-required, any, all, mixed를 별도 계산합니다.",
      "전체 선택과 개별 change 모두 공용 transition/render를 호출해 checked·indeterminate·next.disabled·summary를 동기화합니다.",
      "current value/checked/selected와 실제 FormData getAll을 비교하고 absent checkbox를 server contract에서 normalize합니다.",
      "notice를 native button disclosure로 바꾸고 open boolean에서 hidden·class·aria-expanded·label을 force 설정합니다.",
      "기존 display overlay를 native dialog 또는 완전한 APG custom modal로 교체해 name·initial focus·Escape·inertness·return focus를 구현합니다.",
      "dataset에는 action/record ID만 두고 parse/allowlist하며 role/price/owner는 server가 재검증합니다.",
      "repeated render, reset, empty/dynamic agreements, keyboard, accessibility tree, FormData, tamper와 privacy-safe telemetry를 자동 test합니다.",
    ],
    expectedResult: [
      "boolean attribute와 current/default differences가 exact table과 browser output에 일치합니다.",
      "none/some/all 및 required subset에 따라 selectAll checked/indeterminate와 next disabled가 product rule대로 변합니다.",
      "화면 summary와 FormData entries의 포함/누락이 설명 가능하고 server가 absent/unauthorized 값을 검증합니다.",
      "공지 disclosure의 expanded/hidden/class/label invariants가 반복 render에서도 drift하지 않습니다.",
      "dialog는 keyboard focus를 내부 task에 두고 background를 비활성화하며 Escape/close 뒤 logical opener로 복구합니다.",
      "dataset 변조로 권한이 바뀌지 않고 production log에 raw FormData·DOM·개인정보가 없습니다.",
    ],
    cleanup: ["event listeners/AbortController와 dialog open state를 정리하고 opener focus를 복구합니다.", "synthetic agreement values, dataset tamper, DevTools saved DOM references와 test FormData를 제거합니다."],
    extensions: ["dynamic agreement 추가·삭제와 required policy version을 server schema와 동기화합니다.", "native dialog와 APG custom dialog를 accessibility/support/maintenance 기준으로 비교합니다.", "controlled/uncontrolled React form에서 value/defaultValue·checked/defaultChecked 경계를 같은 matrix로 재현합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "text·checkbox·button의 attribute/default/current/reset 행렬과 dataset string 경계를 재현하세요.", requirements: ["disabled='false'의 presence 결과를 설명합니다.", "value/defaultValue/getAttribute와 checked/defaultChecked/hasAttribute를 initial/edit/reset에서 기록합니다.", "dataset dash/camel, typeof, number parse, delete를 확인합니다.", "script property change가 change event를 자동 발생시키지 않음을 계측합니다."], hints: ["현재 화면 값은 property에서 읽습니다.", "boolean false는 attribute 제거입니다."], expectedOutcome: "각 상태 층과 reflection/dirty/reset 결과를 정확히 예측하고 browser exact output으로 증명합니다.", solutionOutline: ["변경을 한 번에 여러 개 하지 말고 단계별 snapshot을 남깁니다.", "attribute string/null과 property typed value를 다른 columns로 둡니다."] },
    { difficulty: "응용", prompt: "필수·선택 약관과 tri-state 전체 선택, FormData summary를 구현하세요.", requirements: ["none/some/all과 empty list를 처리합니다.", "필수 terms/privacy와 선택 marketing을 분리합니다.", "checked·indeterminate·button disabled·summary를 공용 render에서 갱신합니다.", "current properties와 FormData getAll 결과를 비교합니다.", "programmatic 전체 선택과 reset 뒤 render를 명시 호출합니다."], hints: ["every([])는 true입니다.", "unchecked checkbox는 FormData에 false로 들어가지 않습니다."], expectedOutcome: "어떤 선택/동적/리셋 순서에서도 UI와 payload가 업무 규칙에 맞고 state drift가 없습니다.", solutionOutline: ["agreement records에 id/value/required를 둡니다.", "derive 함수가 allRequired/all/some/entries를 반환하게 합니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 disclosure·modal·form state 표준과 검증 gate를 설계하세요.", requirements: ["attribute/property/default/current/reflection 선택표를 만듭니다.", "class/hidden/ARIA를 authoritative state에 연결하는 invariant를 정의합니다.", "native dialog와 custom APG dialog 선택 기준·focus lifecycle을 포함합니다.", "dataset 허용 용도와 server trust boundary를 정의합니다.", "FormData/keyboard/accessibility/tamper/privacy/performance test matrix를 만듭니다."], hints: ["ARIA는 behavior를 자동 구현하지 않습니다.", "보이는 overlay가 modal이라는 뜻은 아닙니다."], expectedOutcome: "팀이 boolean/dirtiness/payload/focus 결함 없이 일관된 interactive component를 구현·검증하는 운영 표준이 완성됩니다.", solutionOutline: ["logical state→derived DOM/accessibility/payload 흐름을 그립니다.", "각 표현 사이 equality/implication invariant를 executable test로 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "getAttribute가 반환하는 값의 기본 type은 무엇인가요?", answer: "attribute가 있으면 string, 없으면 null입니다. property의 typed current value와 다릅니다." },
    { question: "disabled='false'는 button을 활성화하나요?", answer: "아닙니다. boolean attribute는 존재하면 true이므로 제거하거나 `.disabled=false`로 설정합니다." },
    { question: "input.value와 getAttribute('value')는 언제 달라질 수 있나요?", answer: "사용자/script가 current value를 바꿔 dirty해진 뒤 attribute/default와 현재 값이 분리될 수 있습니다." },
    { question: "defaultChecked는 무엇을 나타내나요?", answer: "checked content attribute와 연결된 기본 checkedness로 reset 기준이며 current `.checked`와 달라질 수 있습니다." },
    { question: "checkbox.indeterminate는 checked=false와 같은가요?", answer: "아닙니다. 일부 선택을 나타내는 별도 property-only 상태이며 checked/submission과 독립적입니다." },
    { question: "script로 checked를 바꾸면 change event가 자동 발생하나요?", answer: "일반적으로 발생하지 않습니다. 변경 code가 공용 render/transition을 호출합니다." },
    { question: "classList.toggle(token, force)의 장점은 무엇인가요?", answer: "원하는 최종 존재 여부를 명시해 반복 호출에도 idempotent하고 다른 class tokens를 보존합니다." },
    { question: "dataset.maxItems가 '3'이면 number인가요?", answer: "아닙니다. dataset 값은 string이므로 parse와 finite/integer/range validation이 필요합니다." },
    { question: "unchecked checkbox는 FormData에 false로 들어가나요?", answer: "보통 entry 자체가 제외됩니다. server가 absence를 false/empty로 normalize합니다." },
    { question: "Array.every([])는 false인가요?", answer: "아닙니다. true이므로 전체 선택 all에는 length>0 guard가 필요합니다." },
    { question: "aria-expanded를 true로 바꾸면 panel이 자동으로 열리나요?", answer: "아닙니다. ARIA는 state를 전달하며 JavaScript가 hidden/class와 실제 behavior를 구현합니다." },
    { question: "fixed overlay와 display:block이면 modal dialog인가요?", answer: "아닙니다. background inertness, dialog role/name, initial/contained/return focus와 keyboard lifecycle이 필요합니다." },
  ],
  completionChecklist: [
    "content attribute string/null과 IDL property typed value를 구분했다.",
    "각 사용 property의 reflection·parse·serialize 규칙을 공식 문서에서 확인했다.",
    "boolean attribute false는 부재로 표현하고 disabled='false'를 제거했다.",
    "value/defaultValue·checked/defaultChecked·selected/defaultSelected current/default state를 test했다.",
    "programmatic property change와 user input/change event를 구분해 공용 render를 호출했다.",
    "form.reset 뒤 controls와 summary/class/disabled/ARIA 파생 상태를 다시 동기화했다.",
    "className 전체 교체 대신 classList.toggle(token, force)로 state token을 관리했다.",
    "hidden·inline style·computed style·application open state를 서로 다른 층으로 구분했다.",
    "dataset dash/camel·string coercion·delete를 처리하고 권한/가격/secret을 신뢰하지 않았다.",
    "FormData의 no-name/disabled/unchecked/multi-value entry rules를 client/server contract에 반영했다.",
    "none/some/all/empty와 required subset에서 checked·indeterminate·disabled를 정확히 계산했다.",
    "disclosure의 expanded·hidden·class·label을 하나의 boolean render에서 동기화했다.",
    "modal dialog의 accessible name·initial/contained/return focus·Escape·inert background를 검증했다.",
    "keyboard/accessibility tree/payload/tamper/privacy/state invariant E2E를 통과했다.",
  ],
  nextSessions: ["js-08-event-loop-timers-callback"],
  sources: [
    { id: "web-dom-checkbox-state-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex06_DOM.html", usedFor: ["checkbox checked property", "button disabled property", "select all", "some/every", "change listeners", "form state"], evidence: "전체 선택과 개별 동의가 checked/disabled current properties를 바꾸는 원본을 current/default, indeterminate, required policy와 FormData state machine으로 확장했습니다." },
    { id: "web-notice-popup-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex10_notice.html", usedFor: ["notice content", "close button", "window close boundary", "in-page disclosure redesign"], evidence: "별도 window의 공지/닫기 흐름을 popup lifecycle과 분리하고 native button·hidden·aria-expanded 기반 in-page disclosure의 content 근거로 사용했습니다." },
    { id: "web-modal-visual-state-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex11_modal.html", usedFor: ["fixed overlay", "style.display state", "open/close click", "Escape", "backdrop target", "missing dialog/focus semantics"], evidence: "display만 바꾸는 시각 overlay를 감사해 native dialog/APG modal의 name·inertness·keyboard·focus lifecycle 결손을 구체적으로 보강했습니다." },
    { id: "whatwg-attribute-reflection", repository: "WHATWG HTML Standard", path: "common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes", publicUrl: "https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes", usedFor: ["content attribute", "IDL attribute/property", "reflection", "type-specific getter/setter", "serialization"], evidence: "attribute string과 typed IDL reflection을 API별로 구분하는 current HTML model의 기준으로 사용했습니다." },
    { id: "whatwg-boolean-attributes", repository: "WHATWG HTML Standard", path: "common-microsyntaxes.html#boolean-attributes", publicUrl: "https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes", usedFor: ["presence true", "absence false", "disabled='false'", "conforming values"], evidence: "boolean attribute는 값 문자열이 아니라 존재로 state를 나타낸다는 규칙을 exact disabled example의 기준으로 사용했습니다." },
    { id: "whatwg-input-state", repository: "WHATWG HTML Standard", path: "input.html#the-input-element", publicUrl: "https://html.spec.whatwg.org/multipage/input.html#the-input-element", usedFor: ["value/defaultValue", "checked/defaultChecked", "dirty flags", "indeterminate", "input types", "reset"], evidence: "input의 default/current/dirtiness와 checkbox mixed state를 initial-edit-reset state matrix에 사용했습니다." },
    { id: "whatwg-form-entry-list", repository: "WHATWG HTML Standard", path: "form-control-infrastructure.html#constructing-form-data-set", publicUrl: "https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set", usedFor: ["FormData", "entry list", "name", "disabled", "unchecked checkbox", "duplicate names", "submitter"], evidence: "화면 current state와 실제 submission payload의 포함·누락 차이를 current form entry algorithm에 맞췄습니다." },
    { id: "whatwg-custom-data", repository: "WHATWG HTML Standard", path: "dom.html#custom-data-attribute", publicUrl: "https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute", usedFor: ["data-* naming", "dataset", "DOMStringMap", "private page metadata", "string values"], evidence: "dataset 이름 변환·string boundary·표준 attribute 우선과 application trust 경계를 공식 custom data model로 보강했습니다." },
    { id: "dom-token-list", repository: "WHATWG DOM Standard", path: "#interface-domtokenlist", publicUrl: "https://dom.spec.whatwg.org/#interface-domtokenlist", usedFor: ["classList", "add/remove/toggle/replace", "force argument", "token validation", "idempotence"], evidence: "class string 전체 조립 대신 fixed token state를 관리하는 API와 오류 조건을 current DOMTokenList interface에 맞췄습니다." },
    { id: "dom-standard", repository: "WHATWG DOM Standard", path: "DOMStringMap-related DOM integration", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["DOM interface boundary", "node/property state", "event/mutation integration"], evidence: "HTML-specific reflection과 DOM object state를 구분하는 공통 interface/tree 근거로 사용했습니다." },
    { id: "wai-aria-expanded", repository: "W3C WAI-ARIA 1.2", path: "#aria-expanded", publicUrl: "https://www.w3.org/TR/wai-aria-1.2/#aria-expanded", usedFor: ["expanded/collapsed state", "controlling element", "accessibility API", "state synchronization"], evidence: "button이 제어하는 content의 현재 expanded state를 실제 visibility와 동기화하는 semantic 기준으로 사용했습니다." },
    { id: "wai-disclosure", repository: "W3C WAI ARIA Authoring Practices Guide", path: "patterns/disclosure/", publicUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/", usedFor: ["disclosure button", "Enter/Space", "aria-expanded", "aria-controls", "show/hide pattern"], evidence: "공지 content를 native-button disclosure로 재설계한 keyboard·role/state contract에 사용했습니다." },
    { id: "whatwg-dialog", repository: "WHATWG HTML Standard", path: "interactive-elements.html#the-dialog-element", publicUrl: "https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element", usedFor: ["dialog", "show/showModal/close", "top layer", "inert background", "cancel/close", "focus"], evidence: "CSS overlay와 native modal dialog의 platform lifecycle 차이를 current HTML dialog algorithms로 보강했습니다." },
    { id: "wai-dialog", repository: "W3C WAI ARIA Authoring Practices Guide", path: "patterns/dialog-modal/", publicUrl: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/", usedFor: ["modal keyboard interaction", "focus containment", "initial focus", "return focus", "name/description", "Escape"], evidence: "native 또는 custom modal의 accessible interaction/focus 계약과 원본 결손 진단에 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본 전체 선택은 checked/disabled와 some/every를 직접 보여 주지만 indeterminate·empty every·필수/선택 policy·FormData/current-default 차이는 없습니다. HTML Standard의 input/form state model로 보강했습니다.",
      "원본 notice/modal은 popup close와 display overlay를 보여 주지만 disclosure ARIA와 실제 modal focus/inertness 계약은 없습니다. WAI-ARIA/APG 및 native dialog 규격으로 보강했습니다.",
      "event loop·timer·callback scheduling은 js-08에서, Promise state/error는 js-09에서 현재 property/render 전환과 비동기 작업 순서를 이어서 학습합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 390;
expertSession.chapters.push({
  id: "form-submission-validation-dialog-accessibility",
  title: "폼 제출·제약 검증·submitter·dialog를 하나의 사용자 작업 흐름으로 설계합니다",
  lead: "폼은 input 값을 모으는 상자가 아니라 label, 이름, 제약 검증, 제출 버튼의 의도, 성공 control entry list, 오류 복구와 완료 dialog focus까지 연결된 HTML 작업 단위입니다.",
  explanations: [
    "각 form control은 보이는 label과 programmatic name을 가져야 합니다. `<label for>`와 control id를 연결하거나 control을 label 안에 넣고, `name`은 FormData와 server parameter key를 결정합니다. placeholder는 입력 예시이지 지속되는 label이 아니며, 같은 id·중복 label target·빈 accessible name은 keyboard와 screen reader 모두의 작업 맥락을 약화합니다.",
    "form-associated control은 form 내부에 놓는 것이 가장 단순하지만 `form` attribute로 다른 위치의 form owner를 지정할 수도 있습니다. 이때 DOM ancestor만 보고 controls를 수집하지 말고 `form.elements`와 실제 entry-list 규칙을 확인합니다. disabled fieldset, disabled control, name 부재, unchecked checkbox/radio, 일부 button은 제출 entry에서 제외되며 readonly text control은 보통 제출되므로 disabled와 readonly를 업무적으로 교환하지 않습니다.",
    "native constraint validation은 required, minlength, maxlength, pattern, type, min/max/step 같은 제약과 ValidityState를 제공합니다. `checkValidity()`는 유효 여부를 검사하고 invalid event를 발생시킬 수 있으며, `reportValidity()`는 사용자에게 browser UI까지 요청합니다. client validation은 빠른 피드백일 뿐 보안 경계가 아니므로 server가 같은 schema·권한·업무 규칙을 다시 검증합니다.",
    "submit event는 form에 걸고 `event.submitter`로 어떤 submit button이 작업을 요청했는지 확인합니다. 저장·미리보기처럼 여러 버튼이 있으면 name/value 또는 allowlisted action을 사용합니다. Enter 제출과 접근성 동작을 보존하려면 click handler만 두지 말고 form submit을 중심에 둡니다.",
    "`form.requestSubmit(button?)`은 실제 제출 버튼을 누른 것처럼 submitter, constraint validation, submit event를 거칩니다. 반면 legacy `form.submit()`은 validation과 submit event를 우회하므로 일반 UI 흐름을 재현하는 API가 아닙니다. 이름이 `submit`인 control이 form.submit method를 가릴 수 있으므로 control name도 API와 충돌하지 않게 정합니다.",
    "submit listener에서 `preventDefault()`를 호출한 뒤 FormData를 만들면 그 시점의 successful controls를 snapshot합니다. submitter의 name/value까지 필요하면 `new FormData(form, event.submitter)` 지원 범위를 확인하거나 submitter 값을 명시적으로 추가합니다. checkbox absence, duplicate name, File, 빈 문자열을 JSON object 하나로 무손실 변환할 수 없으므로 entries/getAll 기반 server contract를 먼저 정의합니다.",
    "비동기 제출 중에는 중복 요청을 막되 사용자가 취소·오류 복구할 수 있어야 합니다. button disabled만으로 server idempotency가 생기지 않으므로 request identifier와 server-side 중복 방지 정책을 둡니다. 완료·오류 어느 경로에서도 busy state, AbortController, listener, focus를 정리하고 raw 개인정보나 FormData 전체를 console/telemetry에 남기지 않습니다.",
    "완료 확인이 modal이라면 native `<dialog>`의 `showModal()`을 우선 검토합니다. modal dialog는 top layer에 올라가고 바깥 문서가 inert가 되며, 적절한 heading/accessible name과 초기 focus, Escape cancel, close 뒤 논리적 opener로의 return focus가 필요합니다. 단순 fixed overlay와 `display:block`은 이 상호작용 계약을 제공하지 않습니다.",
    "dialog 안에 긴 설명이 있으면 첫 interactive control이 항상 최선의 초기 focus는 아닙니다. 내용 시작의 정적 요소에 tabindex=-1을 두는 APG 패턴, destructive action의 안전한 기본, viewport scroll을 고려합니다. close 뒤 opener가 제거되었다면 다음 논리적 작업으로 focus를 이동하고 body로 사라지게 두지 않습니다.",
    "검증은 마우스 성공 경로만 보지 않습니다. 빈 필수값의 invalid 순서, Enter 제출, 여러 submitter, programmatic requestSubmit, reset, double submit, network abort, server error, dialog Escape·Tab·return focus, Accessibility tree, 실제 FormData entries를 함께 관찰합니다. DevTools Elements의 properties와 attributes, Console event trace, Network payload를 같은 실행에서 비교해야 상태 drift를 찾을 수 있습니다.",
  ],
  concepts: [
    { term: "successful control", definition: "form entry list를 구성할 때 name·disabled·type·checkedness·submitter 등 규칙을 만족해 실제 제출 데이터에 포함되는 control입니다.", detail: ["화면에 보인다고 항상 포함되지 않습니다.", "duplicate names와 checkbox absence를 보존합니다."] },
    { term: "constraint validation", definition: "HTML control의 제약과 ValidityState, invalid/submit lifecycle을 이용하는 browser의 기본 검증 체계입니다.", detail: ["requestSubmit은 검증을 거칩니다.", "server validation을 대체하지 않습니다."] },
    { term: "submitter", definition: "현재 form submission을 시작한 submit button 또는 input으로 action intent와 override attributes를 제공할 수 있습니다.", detail: ["submit event의 event.submitter로 읽습니다.", "allowlisted 업무 action으로 변환합니다."] },
    { term: "modal focus lifecycle", definition: "dialog가 열릴 때 의미 있는 내부 위치로 focus를 이동하고 내부에 유지하며 닫힐 때 논리적 출발점으로 복구하는 전체 과정입니다.", detail: ["background inertness와 함께 검증합니다.", "opener가 사라지는 경우의 fallback도 정합니다."] },
  ],
  codeExamples: [
    {
      id: "request-submit-formdata-dialog-contract",
      title: "requestSubmit의 validation·FormData·native dialog 계약",
      language: "html",
      filename: "request-submit-dialog.html",
      purpose: "빈 required controls에서는 각 invalid event만 발생하고, 값을 채운 뒤에는 submitter를 포함한 entry list를 만들고 modal 완료 dialog를 여는 순서를 exact trace로 확인합니다.",
      code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>form contract</title></head>\n<body>\n  <form id=\"profile\">\n    <label for=\"name\">이름</label>\n    <input id=\"name\" name=\"name\" required>\n    <label><input id=\"agree\" name=\"agree\" type=\"checkbox\" required> 필수 약관 동의</label>\n    <button id=\"save\" name=\"action\" value=\"save\" type=\"submit\">저장</button>\n  </form>\n  <dialog id=\"done\" aria-labelledby=\"done-title\">\n    <h2 id=\"done-title\">저장 완료</h2>\n    <button id=\"close\" type=\"button\">확인</button>\n  </dialog>\n  <pre id=\"out\" aria-live=\"polite\"></pre>\n  <script>\n    const form = document.querySelector('#profile');\n    const nameInput = document.querySelector('#name');\n    const agree = document.querySelector('#agree');\n    const save = document.querySelector('#save');\n    const dialog = document.querySelector('#done');\n    const closeButton = document.querySelector('#close');\n    const out = document.querySelector('#out');\n    const trace = [];\n    const render = () => { out.textContent = trace.join('\\n'); };\n\n    form.addEventListener('invalid', (event) => {\n      trace.push(`invalid:${event.target.name}`);\n      render();\n    }, true);\n\n    form.addEventListener('submit', (event) => {\n      event.preventDefault();\n      const entries = new FormData(form, event.submitter);\n      trace.push(`submit:${new URLSearchParams(entries).toString()}`);\n      dialog.showModal();\n      trace.push(`dialog-open=${dialog.open}`);\n      render();\n      closeButton.focus();\n    });\n\n    closeButton.addEventListener('click', () => dialog.close('confirmed'));\n    form.requestSubmit(save);\n    nameInput.value = '홍길동';\n    agree.checked = true;\n    form.requestSubmit(save);\n  </script>\n</body>\n</html>",
      walkthrough: [
        { lines: "1-10", explanation: "지속되는 label, name, required, 명시적 submitter name/value를 갖는 최소 form을 만듭니다." },
        { lines: "11-15", explanation: "accessible heading과 닫기 button이 있는 native dialog를 정의합니다." },
        { lines: "18-27", explanation: "form/control/dialog references와 화면에 exact trace를 기록하는 render를 준비합니다." },
        { lines: "29-33", explanation: "capture invalid listener로 어떤 required control이 제출을 막았는지 순서대로 기록합니다." },
        { lines: "35-44", explanation: "submit을 가로채 submitter가 포함된 FormData entry list를 만들고 showModal 뒤 open state와 초기 focus를 기록합니다." },
        { lines: "46-49", explanation: "첫 requestSubmit은 빈 name에서 막히고, 값을 채운 두 번째 requestSubmit은 submit과 dialog 경로를 통과합니다." },
      ],
      run: { environment: ["최신 Chromium 또는 Firefox", "request-submit-dialog.html을 UTF-8로 저장", "DevTools Elements·Console·Network·Accessibility pane", "keyboard-only Tab·Shift+Tab·Escape"], command: "브라우저에서 request-submit-dialog.html을 열고 pre 출력, dialog top layer, focus 위치를 확인" },
      output: { value: "invalid:name\ninvalid:agree\nsubmit:name=%ED%99%8D%EA%B8%B8%EB%8F%99&agree=on&action=save\ndialog-open=true", explanation: ["첫 requestSubmit은 두 required controls에 tree order로 invalid를 발생시키고 submit event로 진행하지 않습니다.", "두 번째 제출은 current control state와 submitter action을 entry list에 포함합니다.", "showModal 뒤 dialog.open은 true이며 background inertness와 focus는 keyboard/Accessibility pane에서 추가 확인합니다."] },
      experiments: [
        { change: "agree.checked=true 줄을 제거합니다.", prediction: "name이 유효해진 뒤 invalid:agree가 추가되고 submit은 발생하지 않습니다.", result: "checkbox required도 native constraint validation과 entry-list checkedness에 연결됩니다." },
        { change: "requestSubmit(save)를 form.submit()으로 바꿉니다.", prediction: "constraint validation과 submit listener를 우회해 실제 navigation이 발생할 수 있습니다.", result: "legacy submit method는 사용자 제출 흐름 재현 API가 아닙니다." },
        { change: "dialog가 열린 뒤 Tab·Shift+Tab·Escape를 사용하고 닫은 뒤 activeElement를 확인합니다.", prediction: "focus가 modal 작업 안에 머물고 Escape로 닫힌 뒤 logical opener로 돌아가는 native behavior를 관찰할 수 있습니다.", result: "브라우저별 세부 focus와 제품의 명시적 return-focus 보완 여부를 기록합니다." },
      ],
      sourceRefs: ["web-modal-visual-state-source", "whatwg-form-entry-list", "whatwg-input-state", "whatwg-dialog", "wai-dialog"],
    },
  ],
  diagnostics: [
    { symptom: "저장 button click에서는 검증되지만 Enter로 제출하면 handler와 action이 누락된다.", likelyCause: "button click만 듣고 form submit과 event.submitter를 작업 경계로 사용하지 않았습니다.", checks: ["form submit listener 호출 여부를 기록합니다.", "Enter·requestSubmit·각 submit button에서 event.submitter를 확인합니다.", "button type/name/value와 implicit submission 조건을 검사합니다."], fix: "업무 로직을 form submit listener에 두고 submitter를 allowlisted action으로 변환하며 click은 보조 UI에만 사용합니다.", prevention: "mouse·keyboard·requestSubmit·여러 submitter parity 테스트를 둡니다." },
    { symptom: "완료 overlay가 열렸지만 Tab이 뒤 페이지 control로 이동하고 닫은 뒤 focus가 사라진다.", likelyCause: "CSS display overlay를 modal로 간주해 inertness와 focus lifecycle을 구현하지 않았습니다.", checks: ["Accessibility tree의 role/name을 확인합니다.", "Tab·Shift+Tab·Escape와 document.activeElement를 추적합니다.", "close 뒤 opener 연결 상태를 확인합니다."], fix: "native dialog showModal을 사용하거나 APG modal의 focus containment·Escape·return focus·background inertness를 완전하게 구현합니다.", prevention: "keyboard와 screen reader modal acceptance test를 배포 gate에 둡니다." },
  ],
  expertNotes: [
    "FormData(form, submitter)는 최신 browser 지원 범위를 확인하고 지원 대상이 넓다면 submitter entry를 명시적으로 추가하는 adapter를 테스트합니다. 같은 name의 다중 값을 Object.fromEntries로 접으면 정보가 소실됩니다.",
    "native validation message는 browser와 locale마다 다르므로 exact 문구에 의존하지 말고 ValidityState와 application의 접근 가능한 오류 요약·field association을 테스트합니다.",
  ],
});

expertSession.reviewQuestions.push(
  { question: "readonly와 disabled control은 제출 entry 관점에서 어떻게 다른가요?", answer: "readonly text control은 일반적으로 이름과 값을 제출하지만 disabled control은 successful control에서 제외됩니다. 두 속성은 UX와 업무 의미가 다릅니다." },
  { question: "form.requestSubmit()이 form.submit()보다 사용자 제출을 재현하기 좋은 이유는 무엇인가요?", answer: "requestSubmit은 submitter, constraint validation, submit event의 정상 lifecycle을 거치지만 legacy submit method는 이를 우회하기 때문입니다." },
  { question: "완료 overlay에 role=dialog만 추가하면 modal이 완성되나요?", answer: "아닙니다. accessible name, 초기·내부·복귀 focus, Escape, background inertness와 시각·접근성 상태 동기화까지 필요합니다." },
);
expertSession.completionChecklist.push(
  "label·name·form owner·submitter와 successful-control entry 규칙을 실제 FormData로 검증했다.",
  "requestSubmit·native constraint validation·server 재검증의 책임 경계를 설명할 수 있다.",
  "native dialog의 accessible name·초기/내부/복귀 focus·Escape·background inertness를 keyboard와 Accessibility pane에서 검증했다.",
);
