import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-02-callback-scope-closure"],
  slug: "js-02-callback-scope-closure",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 2,
  title: "함수 값·콜백·렉시컬 스코프와 클로저",
  subtitle: "함수 참조와 호출 결과를 분리하고, callback을 누가 언제 어떤 인자로 부르는지와 closure가 binding을 얼마나 오래 유지하는지 추적합니다.",
  level: "기초",
  estimatedMinutes: 260,
  coreQuestion: "함수를 다른 함수·이벤트·타이머에 전달했을 때 실행 시점과 argument·this·오류·수명은 누가 결정하며, lexical environment는 호출이 끝난 뒤 왜 계속 살아 있을 수 있을까요?",
  summary: "원본 greet(name,callback), `const res=sayHello`, addEventListener의 named/anonymous listener와 setInterval timer1을 하나의 callback contract로 연결합니다. function value와 call expression/return value, higher-order function, synchronous callback과 host-scheduled callback을 분리하고 callback return이 outer async function의 return이 아니라는 점을 실행합니다. block/function/module lexical scope와 name resolution·shadowing·TDZ를 environment chain으로 추적하고, closure가 outer binding 자체를 캡처해 독립 counter와 private state를 만드는 원리를 증명합니다. var loop closure와 let per-iteration binding, object retention/cleanup을 다룹니다. ordinary function의 dynamic this와 arrow의 lexical this, method 분리·call/apply/bind·DOM listener receiver를 구분합니다. 마지막에는 stable callback identity, removeEventListener/AbortSignal, timer ownership, error/cancellation과 fake scheduler를 가진 독립 news controller를 설계해 다음 이벤트·event loop 세션으로 이어집니다.",
  objectives: [
    "function value, call expression과 return value를 구분하고 callback API에 올바른 값을 전달할 수 있다.",
    "callback invoker가 실행 시점·횟수·argument·this·return/error 처리 규칙을 소유한다는 contract를 설명할 수 있다.",
    "lexical scope chain과 shadowing·TDZ를 source nesting에서 결정하고 동적 호출 순서와 혼동하지 않을 수 있다.",
    "closure가 outer binding을 캡처해 outer call 종료 뒤에도 state를 유지하고 서로 독립적인 instance를 만드는 과정을 추적할 수 있다.",
    "var loop의 공유 binding과 let per-iteration binding 차이, closure에 의한 object lifetime을 진단할 수 있다.",
    "ordinary function의 call-site this와 arrow function의 lexical this를 method·listener·timer·bind 사례에서 선택할 수 있다.",
    "stable callback identity, cleanup/AbortSignal, error/cancellation과 idempotent start/stop을 가진 callback lifecycle을 설계할 수 있다.",
  ],
  prerequisites: [
    { title: "값·변수·조건·반복과 함수 호출", reason: "function value/call, binding, execution context와 pure news transition을 callback·closure·this 수명으로 확장합니다.", sessionSlug: "js-01-values-control-functions" },
  ],
  keywords: ["first-class function", "callback", "higher-order function", "lexical scope", "environment record", "scope chain", "shadowing", "closure", "captured binding", "this", "arrow function", "call", "apply", "bind", "callback identity", "cleanup", "AbortSignal"],
  chapters: [
    {
      id: "function-value-call-callback-contract",
      title: "callback은 ‘나중에 실행되는 함수’가 아니라 다른 code에 호출 권한을 넘긴 callable value입니다",
      lead: "동기 배열 method도 callback을 쓰므로 시간보다 invoker와 호출 contract가 핵심입니다.",
      explanations: [
        "JavaScript function은 object이자 callable value라 binding, property, array element에 저장하고 argument/return으로 전달할 수 있습니다. `sayHello`는 function value를 읽고 `sayHello()`는 Call을 평가해 function body를 지금 실행하고 return value를 만듭니다.",
        "callback은 다른 function/host API에 호출하도록 전달된 function입니다. `greet('고길동',sayGoodbye)`에서는 greet가 synchronous invoker이고, `setTimeout(fn,2000)`에서는 HTML timer algorithm이 delay 이후 task에서 callback 호출을 준비합니다. callback이라는 말만으로 async 여부는 정해지지 않습니다.",
        "higher-order function은 function을 argument로 받거나 function을 반환합니다. invoker contract에는 callback 횟수(0/1/N), 순서, arguments, this value, return value 사용 여부, exception/error 처리, cancellation/cleanup이 포함됩니다.",
        "callback을 받는 code는 호출 전에 callable을 검증하거나 API type을 명시합니다. string이나 `handler()`의 return undefined를 callback 자리에 전달하면 등록 즉시 또는 호출 시 TypeError/무동작이 생깁니다. 오류 시점을 API마다 확인합니다.",
        "callback body에서 `return value`는 callback을 호출한 invoker에게 돌아갑니다. timer/event listener의 host가 그 return을 application result로 사용하지 않는다면 outer function이나 click caller가 그 값을 자동으로 받지 않습니다. 비동기 결과는 callback, Promise 또는 state/render channel로 전달합니다.",
        "anonymous function은 일회성 local behavior에 적합하지만 stack trace/cleanup identity/test에서 이름 있는 function이 유리할 수 있습니다. 함수 이름 여부와 inline/arrow 선택을 style 하나로 강제하지 않고 lifecycle과 this 요구를 기준으로 합니다.",
      ],
      concepts: [
        { term: "first-class function", definition: "다른 value처럼 변수·property에 저장하고 argument/return으로 전달할 수 있는 function value의 성질입니다.", detail: ["호출은 별도 `()` operation입니다.", "closure를 반환할 수 있습니다."] },
        { term: "callback invoker", definition: "전달받은 callback을 실제로 호출하며 시점·횟수·argument·this·return/error 규칙을 정하는 code/API입니다.", detail: ["greet, array method, DOM, timer가 예입니다.", "contract를 문서에서 확인합니다."] },
        { term: "higher-order function", definition: "function을 argument로 받거나 결과로 반환하는 function입니다.", detail: ["동기/비동기 모두 가능합니다.", "behavior를 data처럼 조합합니다."] },
      ],
      codeExamples: [
        {
          id: "reference-versus-call-result",
          title: "function 참조·직접 호출·callback 전달을 한 줄씩 분리하기",
          language: "javascript",
          filename: "callback-reference.mjs",
          purpose: "원본 `const res=sayHello`와 greet callback을 축소해 callback 자리에 call result를 전달하는 오류를 exact output으로 확인합니다.",
          code: "function formatGreeting(name) {\n  return `안녕 ${name}`;\n}\n\nfunction apply(value, callback) {\n  if (typeof callback !== \"function\") throw new TypeError(\"callback must be callable\");\n  return callback(value);\n}\n\nconsole.log(`reference=${typeof formatGreeting}`);\nconsole.log(`direct=${formatGreeting(\"둘리\")}`);\nconsole.log(`callback=${apply(\"도우너\", formatGreeting)}`);\ntry {\n  apply(\"또치\", formatGreeting(\"또치\"));\n} catch (error) {\n  console.log(`mistake=${error.name}`);\n}",
          walkthrough: [
            { lines: "1-3", explanation: "문자열을 반환하는 deterministic function을 선언합니다." },
            { lines: "5-8", explanation: "invoker가 callback callable을 검사하고 value argument로 한 번 호출해 return을 다시 반환합니다." },
            { lines: "10-12", explanation: "function value typeof, direct call result, function 참조를 전달한 callback result를 비교합니다." },
            { lines: "13-17", explanation: "formatGreeting을 먼저 호출해 string을 callback 자리에 넘기는 실수를 TypeError로 포착합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser module console"], command: "node callback-reference.mjs" },
          output: { value: "reference=function\ndirect=안녕 둘리\ncallback=안녕 도우너\nmistake=TypeError", explanation: ["formatGreeting 자체의 type은 function입니다.", "괄호를 붙인 직접 호출은 string을 만듭니다.", "callback 자리에는 callable function value를 전달해야 invoker가 정한 시점에 호출합니다."] },
          experiments: [
            { change: "apply의 return 앞 callback 호출을 두 번 수행합니다.", prediction: "callback invocation count가 두 번이 되며 side effect가 있다면 두 번 발생합니다.", result: "호출 횟수는 invoker contract입니다." },
            { change: "formatGreeting 대신 `name => formatGreeting(name).toUpperCase()`를 전달합니다.", prediction: "wrapper function이 받은 argument를 가공해 대문자 결과를 반환합니다.", result: "추가 argument/변환이 필요할 때 closure wrapper를 만듭니다." },
            { change: "apply에서 callback return을 버리고 undefined를 반환합니다.", prediction: "callback은 실행되지만 callback=undefined가 됩니다.", result: "callback 결과 사용 여부도 invoker contract입니다." },
          ],
          sourceRefs: ["web-callback-function-source", "ecma-functions-arrow", "ecma-call"],
        },
      ],
      diagnostics: [
        { symptom: "`addEventListener('click', save())`에서 page load 때 저장되고 click에는 실행되지 않는다.", likelyCause: "save function value 대신 save()의 즉시 호출 결과를 listener callback으로 전달했습니다.", checks: ["등록 expression에 괄호가 있는지 봅니다.", "save() return의 typeof를 확인합니다.", "argument가 필요해 wrapper를 만들려던 것인지 확인합니다."], fix: "`save`를 전달하거나 `event => save(id,event)` wrapper를 전달합니다.", prevention: "callback parameter type과 registration-time/call-time log를 test하고 lint로 no-confusing-void-expression을 검토합니다." },
      ],
    },
    {
      id: "sync-versus-host-scheduled-callback",
      title: "synchronous callback과 event/timer callback은 같은 function value지만 호출 stack과 결과 channel이 다릅니다",
      lead: "delay 숫자보다 현재 call이 끝나는지, host가 어떤 task에서 다시 호출하는지와 return을 누가 받는지를 봅니다.",
      explanations: [
        "`[1,2].map(fn)`은 map 호출 안에서 callback을 순서대로 호출하고 각 return을 새 array element로 사용합니다. callback throw는 map call을 중단시켜 caller로 전파됩니다. 이 callback은 synchronous입니다.",
        "DOM listener는 event dispatch 중 listener callback으로 호출되고 event object를 받습니다. HTML timer는 setTimeout/setInterval이 handler를 등록하고 timer task가 실행될 때 호출합니다. 등록 function은 timer ID를 즉시 반환하며 callback return value는 timeout caller의 return이 아닙니다.",
        "`return`으로 asynchronous callback 밖의 outer function result를 바꾸려는 code는 실패합니다. outer function은 callback이 호출되기 전에 이미 return할 수 있습니다. callback-based API에서는 completion callback을 호출하고, modern flow에서는 Promise/async를 사용합니다.",
        "callback error는 호출 주체에 따라 다르게 관찰됩니다. synchronous invoker의 try/catch는 callback throw를 잡을 수 있지만 timer 등록을 감싼 try/catch는 나중 task의 throw를 잡지 못합니다. callback 내부/central error boundary와 Promise rejection policy가 필요합니다.",
        "setInterval callback 실행 시간이 interval보다 길거나 main thread가 busy하면 정확한 주기로 병렬 실행되는 것이 아닙니다. delay는 최소 지연에 가깝고 task scheduling/throttling을 받습니다. timestamp 차이와 drift를 측정하고 정확한 clock/animation은 다른 primitive를 검토합니다.",
        "비동기 세부 event loop/task/microtask는 js-08/09에서 깊게 다룹니다. 여기서는 invoker가 지금 호출하는지 등록 후 host가 나중 호출하는지를 function contract에서 구분합니다.",
      ],
      concepts: [
        { term: "synchronous callback", definition: "invoker의 현재 call이 return하기 전에 호출·완료되는 callback입니다.", detail: ["map/filter/custom apply가 예입니다.", "return/throw가 현재 caller에 직접 연결됩니다."] },
        { term: "host-scheduled callback", definition: "browser host가 event/timer 등의 조건 뒤 별도 dispatch/task에서 호출하는 callback입니다.", detail: ["등록과 실행 stack이 다릅니다.", "cleanup과 lifetime이 필요합니다."] },
        { term: "completion channel", definition: "작업 결과·오류를 caller나 consumer에게 전달하는 callback/return/Promise/event/state 경로입니다.", detail: ["async callback return은 보통 outer return이 아닙니다.", "한 API에서 contract를 통일합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "function이 timer 안에서 값을 return하지만 caller는 항상 undefined를 받는다.", likelyCause: "outer function이 먼저 끝났고 callback return은 timer host에게 돌아갈 뿐 outer call result가 아닙니다.", checks: ["outer return 시각과 callback 실행 시각을 log합니다.", "callback return을 누가 소비하는지 API 문서를 확인합니다.", "Promise/completion callback이 있는지 봅니다."], fix: "outer API를 Promise로 반환하거나 명시적인 completion callback/state update를 사용하고 timer callback의 return에 의존하지 않습니다.", prevention: "async function signature와 success/error/cancel completion을 type/test에 명시합니다." },
      ],
    },
    {
      id: "lexical-scope-chain-shadowing",
      title: "lexical scope는 함수가 호출된 곳이 아니라 source에서 정의된 중첩 위치로 결정됩니다",
      lead: "name lookup은 현재 environment에서 outer environment로 올라가며 caller의 local variable을 동적으로 훔쳐보지 않습니다.",
      explanations: [
        "block의 let/const, function parameter/local, module/global binding은 lexical environment chain을 이룹니다. identifier를 평가하면 현재 environment에서 binding을 찾고 없으면 outer reference를 따라갑니다. 끝까지 없으면 unresolvable ReferenceError입니다.",
        "function object는 생성될 때 자신을 둘러싼 lexical environment에 대한 reference를 유지합니다. 어디서 호출되든 free variable은 정의 당시 chain에서 resolve됩니다. caller가 같은 이름 local을 가져도 lexical scope를 바꾸지 않습니다.",
        "inner scope가 outer와 같은 이름을 선언하면 shadowing입니다. outer binding은 사라진 것이 아니라 inner name resolution에서 가려집니다. 너무 많은 shadowing은 debugger Scope와 code review에서 혼란을 만들어 lint로 제한할 수 있습니다.",
        "let/const TDZ는 각 lexical scope마다 적용됩니다. inner block의 같은 이름 declaration 때문에 declaration 전 read가 outer를 보지 못하고 inner uninitialized binding에 걸려 ReferenceError가 날 수 있습니다.",
        "var는 function scope라 block을 탈출하고 for var loop의 callback들이 하나의 shared i binding을 캡처할 수 있습니다. let loop declaration은 iteration마다 새 per-iteration binding을 만들어 callback이 서로 다른 i를 봅니다.",
        "global binding은 test 간·script 간 암묵 dependency와 이름 충돌을 만듭니다. ES module scope, function factory와 explicit dependency argument로 줄이고 browser inline handler가 global name resolution에 기대는 legacy pattern을 점진적으로 제거합니다.",
      ],
      concepts: [
        { term: "lexical scope", definition: "source code의 block/function/module 중첩 구조로 identifier binding의 가시성을 정하는 규칙입니다.", detail: ["호출 위치와 다릅니다.", "closure의 기반입니다."] },
        { term: "scope chain", definition: "현재 lexical environment에서 outer environment로 이어지는 identifier lookup chain입니다.", detail: ["가장 가까운 binding이 선택됩니다.", "없는 name은 ReferenceError가 될 수 있습니다."] },
        { term: "shadowing", definition: "inner scope가 outer와 같은 이름 binding을 선언해 inner lookup에서 outer binding을 가리는 현상입니다.", detail: ["outer binding은 유지됩니다.", "TDZ와 결합할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "inner block declaration 전 `console.log(name)`이 outer name을 출력할 줄 알았는데 ReferenceError다.", likelyCause: "inner let name binding이 block 전체 lexical scope를 shadow하고 아직 TDZ에 있습니다.", checks: ["block 안 같은 이름 declaration을 찾습니다.", "lookup 대상 environment와 initialization 위치를 표시합니다.", "var/let 동작을 혼동했는지 봅니다."], fix: "inner declaration 전에 접근하지 않고 shadowing name을 구분하거나 declaration 위치를 dependency보다 앞에 둡니다.", prevention: "no-shadow/no-use-before-define와 작은 block scope를 적용합니다." },
      ],
    },
    {
      id: "closure-captured-bindings-independent-state",
      title: "closure는 값 snapshot이 아니라 함수 code와 접근 가능한 lexical binding의 조합입니다",
      lead: "outer function이 return해도 inner function이 binding을 참조하면 그 environment의 필요한 상태는 계속 도달 가능합니다.",
      explanations: [
        "`makeCounter` 호출마다 새로운 count binding이 생기고 반환된 inner function은 그 binding을 참조합니다. outer execution context는 stack에서 사라져도 closure를 통해 environment가 reachable하므로 garbage collection 대상이 아닙니다.",
        "closure는 생성 시 primitive 값을 무조건 복사한 snapshot이 아닙니다. 같은 binding을 공유한 여러 inner function은 한 function이 변경한 최신 값을 다른 function이 봅니다. 별도 outer call에서 만들어진 closure는 서로 다른 binding을 가집니다.",
        "closure로 private state와 configured callback을 만들 수 있습니다. `makeGreeter(prefix)`가 prefix를 캡처하거나 member ID를 캡처한 event handler를 반환합니다. module/class private field와 비교해 API/inspection/serialization 요구를 선택합니다.",
        "closure가 큰 DOM subtree, cache, response와 listener target을 캡처하고 listener/timer가 오래 살아 있으면 해당 object도 reachable해 memory 사용이 지속될 수 있습니다. closure 자체가 memory leak이 아니라 예상 수명보다 오래 유지되는 reference graph가 문제입니다.",
        "loop에서 var 하나를 여러 callback이 캡처하면 callback 실행 때 마지막 i를 모두 볼 수 있습니다. let per-iteration binding, function factory parameter 또는 data attribute/event delegation으로 의도를 명확히 합니다.",
        "DevTools Memory heap snapshot/retainers와 Performance monitor를 사용해 제거된 DOM이 listener/closure를 통해 유지되는지 봅니다. 사용자가 page를 떠나거나 component가 unmount될 때 cleanup을 수행합니다.",
      ],
      concepts: [
        { term: "closure", definition: "ECMAScript function object가 생성 당시 lexical environment를 통해 free binding에 계속 접근할 수 있는 동작/조합입니다.", detail: ["outer call 종료 후도 가능합니다.", "binding의 최신 상태를 볼 수 있습니다."] },
        { term: "captured binding", definition: "inner function이 자신의 local이 아닌 outer lexical environment에서 resolve해 사용하는 binding입니다.", detail: ["value snapshot과 다릅니다.", "여러 closure가 공유할 수 있습니다."] },
        { term: "reachability", definition: "현재 root에서 reference chain으로 object/environment에 도달할 수 있어 garbage collection할 수 없는 상태입니다.", detail: ["listener/timer가 root 역할을 할 수 있습니다.", "cleanup으로 chain을 끊습니다."] },
      ],
      codeExamples: [
        {
          id: "independent-closure-counters",
          title: "두 outer call이 만든 독립 counter와 한 closure family의 shared binding",
          language: "javascript",
          filename: "closure-counters.mjs",
          purpose: "closure가 outer count binding을 보존하고 같은 factory call의 methods는 공유하지만 다른 call과는 독립임을 exact output으로 확인합니다.",
          code: "function createCounter(label) {\n  let count = 0;\n  return {\n    increment(step = 1) { count += step; return `${label}:${count}`; },\n    read() { return `${label}:${count}`; },\n  };\n}\n\nconst left = createCounter(\"left\");\nconst right = createCounter(\"right\");\nconsole.log(left.increment());\nconsole.log(left.increment(2));\nconsole.log(right.increment());\nconsole.log(left.read());\nconsole.log(right.read());",
          walkthrough: [
            { lines: "1-7", explanation: "각 factory call이 label/count binding을 만들고 increment/read 두 method closure가 그 binding을 공유합니다." },
            { lines: "9-10", explanation: "left/right는 서로 다른 factory call이라 별도 environment를 가집니다." },
            { lines: "11-15", explanation: "left만 1+2 증가해 3, right는 1이며 각 read가 최신 shared binding을 봅니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser module console"], command: "node closure-counters.mjs" },
          output: { value: "left:1\nleft:3\nright:1\nleft:3\nright:1", explanation: ["left increment/read는 같은 count binding을 공유합니다.", "right는 새 outer call의 독립 count입니다.", "outer createCounter가 return한 뒤에도 binding은 closure에서 도달 가능합니다."] },
          experiments: [
            { change: "createCounter 밖에 global count를 선언하고 local let을 제거합니다.", prediction: "left/right가 하나의 global count를 공유합니다.", result: "state를 어느 environment에 두는지가 instance 독립성을 결정합니다." },
            { change: "increment와 read를 각각 다른 createCounter call에서 꺼냅니다.", prediction: "서로 count를 공유하지 않습니다.", result: "같은 source function이라도 factory invocation environment가 다릅니다." },
            { change: "count object `{value:0}`를 factory argument로 받고 두 counter에 같은 object를 전달합니다.", prediction: "두 closure가 argument binding을 거쳐 같은 object state를 공유할 수 있습니다.", result: "binding 독립성과 nested object identity 공유를 구분합니다." },
          ],
          sourceRefs: ["web-timer-callback-source", "ecma-execution-environments", "ecma-functions-arrow"],
        },
      ],
      diagnostics: [
        { symptom: "for(var i=0;i<3;i++)로 만든 세 버튼 callback이 모두 3을 출력한다.", likelyCause: "세 closure가 function-scoped var i 하나를 공유하고 event가 실행될 때 loop 종료 후 값 3을 읽습니다.", checks: ["loop declaration이 var인지 let인지 봅니다.", "callback 생성/실행 시각과 i 값을 기록합니다.", "하나의 shared binding인지 iteration binding인지 그립니다."], fix: "for(let i=...) per-iteration binding 또는 factory parameter로 현재 값을 캡처하고 data/event delegation 설계도 검토합니다.", prevention: "각 index callback이 0/1/2를 출력하는 regression test를 둡니다." },
        { symptom: "component를 제거해도 큰 image/data object가 memory snapshot에 남는다.", likelyCause: "document/window의 listener 또는 active timer callback closure가 component DOM/data를 계속 참조합니다.", checks: ["heap retainer path를 listener/timer까지 추적합니다.", "cleanup이 동일 callback identity로 실행됐는지 봅니다.", "AbortController/timer ID와 component lifecycle을 기록합니다."], fix: "unmount/dispose에서 listener abort/remove와 timer clear를 수행하고 불필요한 large object capture를 줄입니다.", prevention: "mount/unmount 반복 뒤 listener/timer/heap growth가 안정적인 lifecycle test를 둡니다." },
      ],
    },
    {
      id: "loop-closure-per-iteration",
      title: "loop callback은 생성 시점의 binding 구조와 실행 시점을 모두 추적합니다",
      lead: "let으로 바꾸면 끝이라는 암기 대신 shared binding·per-iteration environment·data snapshot의 차이를 이해합니다.",
      explanations: [
        "for statement의 lexical declaration `let i`는 iteration마다 per-iteration environment를 만들 수 있어 각 closure가 해당 iteration의 i binding을 참조합니다. var i는 function/global environment의 하나의 binding입니다.",
        "callback이 즉시 실행되면 var loop도 0/1/2를 볼 수 있어 버그가 숨습니다. event/timer처럼 loop 종료 뒤 실행될 때 shared final value가 드러납니다. 생성 시각과 호출 시각을 분리합니다.",
        "object item을 let으로 캡처해도 item object가 나중에 mutation되면 closure는 최신 property를 봅니다. 생성 당시 label snapshot이 필요하면 primitive `const label=item.label`을 iteration 안에서 만들거나 immutable data contract를 사용합니다.",
        "DOM element마다 별도 listener closure를 만들면 index를 쉽게 캡처하지만 큰 list에서는 등록/cleanup 비용이 늘어납니다. parent event delegation과 element dataset/stable ID lookup을 비교합니다.",
        "async callback을 array.forEach에 전달해도 forEach가 returned Promise를 기다리지는 않습니다. per-iteration binding 문제와 async sequencing 문제는 별도이며 후속 Promise 세션에서 for...of/Promise.all을 선택합니다.",
      ],
      concepts: [
        { term: "per-iteration environment", definition: "for lexical declaration에서 각 iteration closure가 독립 loop binding을 보게 만드는 새 lexical environment입니다.", detail: ["let/const loop에 관련됩니다.", "var shared binding과 다릅니다."] },
        { term: "snapshot versus live state", definition: "생성 당시 primitive 값을 별도 binding에 보존하는 것과 같은 object/binding의 나중 변경을 계속 관찰하는 것의 구분입니다.", detail: ["요구에 따라 선택합니다.", "closure는 기본적으로 binding을 참조합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "각 row callback에 item을 캡처했지만 나중에 목록을 수정하자 과거 label 대신 새 label이 나온다.", likelyCause: "closure가 생성 당시 text snapshot이 아니라 같은 mutable item object를 참조합니다.", checks: ["item identity와 mutation owner를 확인합니다.", "callback이 읽는 시각을 기록합니다.", "snapshot이 필요한 field와 live state가 필요한 field를 구분합니다."], fix: "생성 당시 primitive snapshot을 local const로 캡처하거나 stable ID로 current store를 조회하는 명시적 정책을 선택합니다.", prevention: "item mutation 전/후 callback expected behavior를 contract test합니다." },
      ],
    },
    {
      id: "ordinary-this-arrow-bind",
      title: "ordinary function의 this는 호출 방식에서, arrow의 this는 둘러싼 lexical context에서 옵니다",
      lead: "‘this는 자기 자신’이나 ‘arrow가 더 현대적’이라는 문장 대신 call-site와 function kind를 함께 봅니다.",
      explanations: [
        "ordinary function은 [[ThisMode]]와 call semantics에 따라 this가 결정됩니다. `obj.method()`는 property reference의 base obj를 receiver로 사용하고, module/strict mode의 bare `method()`는 this가 undefined일 수 있습니다. non-strict classic script의 global substitution을 새 code에 기대지 않습니다.",
        "Function.prototype.call/apply는 ordinary function을 explicit this와 arguments로 호출하고 bind는 this/leading arguments가 고정된 새 bound function을 반환합니다. bind를 반복 호출하면 새 identity가 생겨 removeEventListener에 원본과 다른 function을 전달하는 실수가 생깁니다.",
        "arrow function은 own this binding, arguments, super, new.target을 만들지 않고 lexical environment에서 resolve합니다. 그래서 object literal method 자체를 arrow로 쓰면 object가 this가 되지 않으며, ordinary method 안에서 nested callback이 method receiver를 계속 써야 할 때 유용합니다.",
        "DOM event listener callback은 DOM dispatch contract에 따라 event와 callback this/currentTarget 관계가 있지만 arrow는 lexical this를 유지합니다. code의 목적에는 event.currentTarget이 가장 명시적이며 target/currentTarget 차이는 다음 event model 세션에서 깊게 다룹니다.",
        "setTimeout에 bare object method를 전달하면 host가 `obj.method()` 형태로 호출하지 않아 receiver를 잃을 수 있습니다. wrapper `()=>obj.method()` 또는 bound function을 만들고 cleanup identity/argument를 함께 관리합니다.",
        "this를 state access shortcut으로 남용하면 function 재사용/테스트가 호출 방식에 민감해집니다. 명시적 parameter/closure가 더 분명한 경우가 많으며 class/event API가 receiver를 요구할 때 this contract를 문서화합니다.",
      ],
      concepts: [
        { term: "call-site this", definition: "ordinary function이 어떤 reference/receiver와 호출되었는지에 따라 정해지는 this value입니다.", detail: ["method/bare/call/apply/bind가 다릅니다.", "정의 위치만으로 정해지지 않습니다."] },
        { term: "lexical this", definition: "arrow function이 own this를 만들지 않고 outer lexical context의 this를 사용하는 동작입니다.", detail: ["call/apply로 바뀌지 않습니다.", "object method로 무조건 적합한 것은 아닙니다."] },
        { term: "bound function", definition: "target function의 this와 선택적 leading arguments를 고정한 새 callable object입니다.", detail: ["원본과 identity가 다릅니다.", "listener cleanup용 reference를 저장합니다."] },
      ],
      codeExamples: [
        {
          id: "ordinary-arrow-this",
          title: "method·bare call·bind·arrow lexical this 비교",
          language: "javascript",
          filename: "this-calls.mjs",
          purpose: "module strict context에서 ordinary method receiver 손실과 bound/arrow lexical receiver를 deterministic output으로 확인합니다.",
          code: "const receiver = {\n  label: \"team\",\n  regular() { return this.label; },\n  makeArrow() { return () => this.label; },\n};\n\nconsole.log(`method=${receiver.regular()}`);\nconst detached = receiver.regular;\ntry {\n  console.log(detached());\n} catch (error) {\n  console.log(`detached=${error.name}`);\n}\nconst bound = detached.bind(receiver);\nconsole.log(`bound=${bound()}`);\nconst arrow = receiver.makeArrow();\nconsole.log(`arrow=${arrow.call({ label: \"other\" })}`);",
          walkthrough: [
            { lines: "1-5", explanation: "ordinary method와 method receiver를 lexical this로 캡처해 arrow를 반환하는 method를 정의합니다." },
            { lines: "7-13", explanation: "method call은 team을 반환하지만 detached bare call의 this는 module에서 undefined라 TypeError입니다." },
            { lines: "14-15", explanation: "bind로 receiver를 고정한 새 function은 team을 반환합니다." },
            { lines: "16-17", explanation: "makeArrow 호출 때의 this를 캡처한 arrow는 call로 other를 줘도 team을 유지합니다." },
          ],
          run: { environment: ["Node.js 22+ ES module(.mjs)"], command: "node this-calls.mjs" },
          output: { value: "method=team\ndetached=TypeError\nbound=team\narrow=team", explanation: ["ordinary method의 this는 receiver가 있는 호출 표현식에서 team입니다.", "분리된 ordinary function은 receiver를 잃습니다.", "bound function과 lexical arrow는 서로 다른 방식으로 team을 유지합니다."] },
          experiments: [
            { change: "receiver.regular을 arrow property `regular:()=>this.label`로 바꿉니다.", prediction: "receiver가 arrow의 this가 아니어서 method=team이 유지되지 않습니다.", result: "arrow를 object method 대체로 무조건 쓰지 않습니다." },
            { change: "bound.call({label:'other'})를 호출합니다.", prediction: "bind된 this가 우선해 team을 반환합니다.", result: "bound function의 this는 call로 다시 바뀌지 않습니다." },
            { change: "`const bound1=detached.bind(receiver); const bound2=detached.bind(receiver)`를 비교합니다.", prediction: "bound1===bound2는 false입니다.", result: "listener 등록/해제에는 동일 bound reference를 저장해야 합니다." },
          ],
          sourceRefs: ["web-event-listener-source", "ecma-ordinary-this", "ecma-functions-arrow"],
        },
      ],
      diagnostics: [
        { symptom: "setTimeout(obj.save,0)에서 save 안의 this.id가 undefined다.", likelyCause: "method를 bare callback value로 전달해 obj receiver를 잃었습니다.", checks: ["등록 callback identity와 호출 형태를 봅니다.", "function이 ordinary/arrow/bound 중 무엇인지 확인합니다.", "this 대신 explicit id argument가 더 적절한지 검토합니다."], fix: "`()=>obj.save()` wrapper 또는 저장한 `obj.save.bind(obj)`를 사용하거나 save(id)를 explicit parameter function으로 재설계합니다.", prevention: "method-as-callback lint/test와 receiver loss fixture를 둡니다." },
        { symptom: "arrow event listener에서 this가 클릭 element라고 기대했지만 outer undefined/object다.", likelyCause: "arrow는 DOM invoker가 제공할 this를 받지 않고 lexical this를 사용합니다.", checks: ["listener가 arrow인지 ordinary인지 봅니다.", "event.currentTarget과 target을 출력합니다.", "outer this가 어디서 왔는지 확인합니다."], fix: "element가 필요하면 event.currentTarget을 명시적으로 사용하고 this contract가 필요한 경우 ordinary listener를 사용합니다.", prevention: "listener code에서 currentTarget을 기본으로 쓰고 arrow/ordinary 선택 이유를 review합니다." },
      ],
    },
    {
      id: "callback-identity-cleanup-errors",
      title: "callback lifecycle은 등록한 동일 identity, owner, cleanup, error와 cancellation을 함께 관리합니다",
      lead: "callback이 작동하는 순간뿐 아니라 더 이상 호출되면 안 되는 순간을 API에 포함합니다.",
      explanations: [
        "removeEventListener는 type/callback/capture match가 필요합니다. 등록과 해제에서 각각 새 arrow 또는 bind를 만들면 identity가 달라 listener가 남습니다. callback reference를 변수/instance field에 보관합니다.",
        "addEventListener options의 once는 첫 invocation 뒤 제거하고 signal은 AbortController abort로 관련 listener를 함께 제거할 수 있습니다. passive는 preventDefault contract와 performance에 영향을 주므로 이벤트 종류/필요에 맞게 선택합니다.",
        "timer는 setTimeout/setInterval ID를 owner가 보관하고 clear합니다. start가 중복 timer를 만들지 않게 running/timer invariant를 두고 stop/dispose를 idempotent하게 만듭니다. page visibility/unmount도 lifecycle event입니다.",
        "callback closure가 state를 캡처할 때 state owner와 mutation API를 제한합니다. 외부에서 state object를 직접 바꾸게 하면 callback invariant가 깨집니다. snapshot method는 defensive copy/plain value를 반환합니다.",
        "callback이 throw하면 synchronous invoker는 caller가 처리할 수 있지만 event/timer host boundary에서는 central reporting과 UI recovery를 별도 설계합니다. 사용자 message, sanitized error code/context와 development stack을 분리합니다.",
        "cancellation은 failure가 아닐 수 있습니다. AbortError/stop/dispose를 expected state로 분류하고 callback이 cleanup 이후 stale DOM/state를 수정하지 않게 generation/active flag를 확인합니다.",
      ],
      concepts: [
        { term: "callback identity", definition: "등록과 제거에서 같은 function object인지 구분하는 object identity입니다.", detail: ["같은 source arrow를 다시 써도 새 identity입니다.", "bound function도 새 identity입니다."] },
        { term: "lifecycle owner", definition: "callback/effect를 등록하고 언제 해제할지 책임지는 component/module/object입니다.", detail: ["timer/listener ID/reference를 보관합니다.", "dispose를 제공합니다."] },
        { term: "stale callback", definition: "요청·component·state가 이미 교체/종료된 뒤 늦게 호출되어 현재 상태를 잘못 수정하는 callback입니다.", detail: ["active/generation/abort로 막습니다.", "cleanup race를 test합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "removeEventListener를 호출했는데 click callback이 계속 실행된다.", likelyCause: "등록과 제거에 서로 다른 anonymous/bound function identity 또는 다른 capture option을 사용했습니다.", checks: ["등록/제거 callback ===를 확인합니다.", "event type과 capture boolean을 비교합니다.", "중복 등록 횟수와 AbortSignal 상태를 봅니다."], fix: "stable callback reference/options를 저장해 동일하게 제거하거나 하나의 AbortController signal로 listener lifecycle을 관리합니다.", prevention: "mount→click→unmount→click에서 post-unmount call count 0을 test합니다." },
      ],
    },
    {
      id: "closure-news-controller-capstone",
      title: "closure factory와 주입된 scheduler로 독립적이고 test 가능한 뉴스 controller를 만듭니다",
      lead: "global cnt/timer를 없애고 schedule/cancel callback contract를 밖에서 주입해 실제 시간 없이 lifecycle을 검증합니다.",
      explanations: [
        "controller factory 호출마다 items, index, timerId binding을 새로 만들면 page에 두 ticker가 있어도 상태가 섞이지 않습니다. public method만 state를 바꾸고 snapshot은 필요한 plain value만 제공합니다.",
        "scheduler와 cancel function을 dependency로 받으면 production은 setInterval/clearInterval, test는 callback을 저장하고 수동 fire하는 fake를 사용합니다. closure behavior와 time passage를 분리합니다.",
        "start는 timerId가 null일 때만 schedule하고 이미 running이면 false를 반환해 idempotent합니다. stop은 current ID를 cancel하고 null로 바꾸며 이미 stopped여도 안전합니다. active timer<=1 invariant를 유지합니다.",
        "tick callback은 next transition을 호출하고 onValue callback에 plain text/index를 넘깁니다. onValue가 throw할 때 timer를 계속할지 stop/report할지 policy를 정합니다. production UI는 textContent와 connected state를 확인합니다.",
        "items가 empty면 factory에서 fail fast하거나 explicit empty state를 반환합니다. runtime source update를 지원하려면 index reset/preserve와 current item identity를 별도 action으로 설계합니다.",
        "dispose는 stop과 외부 listener cleanup을 결합하고 이후 start를 거부하는 상태까지 확장할 수 있습니다. page/component lifecycle이 controller lifetime의 owner입니다.",
      ],
      concepts: [
        { term: "dependency injection", definition: "function이 직접 global API를 고정 호출하지 않고 필요한 schedule/cancel/render behavior를 argument로 받는 설계입니다.", detail: ["fake test가 쉽습니다.", "contract가 명시됩니다."] },
        { term: "factory instance", definition: "factory function의 한 호출이 만든 독립 captured state와 public methods 묶음입니다.", detail: ["호출마다 environment가 다릅니다.", "global state 충돌을 줄입니다."] },
        { term: "fake scheduler", definition: "실제 시간을 기다리지 않고 등록 callback/ID/cancel을 기록하고 test가 수동 호출하는 대체 구현입니다.", detail: ["deterministic lifecycle test를 만듭니다.", "실제 event loop integration test도 별도 필요합니다."] },
      ],
      codeExamples: [
        {
          id: "closure-news-controller",
          title: "fake scheduler로 start 중복·tick·stop을 정확히 검증",
          language: "javascript",
          filename: "news-controller.mjs",
          purpose: "원본 setInterval news를 closure instance와 injected callback lifecycle로 바꾸고 실제 대기 없이 exact output을 만듭니다.",
          code: "function createFakeScheduler() {\n  let callback = null;\n  return {\n    schedule(fn) { callback = fn; return 7; },\n    cancel(id) { if (id === 7) callback = null; },\n    fire() { if (callback) callback(); },\n  };\n}\n\nfunction createNewsController(items, scheduler, onValue) {\n  let index = -1;\n  let timerId = null;\n  const tick = () => {\n    index = (index + 1) % items.length;\n    onValue(`${index}:${items[index]}`);\n  };\n  return {\n    start() {\n      if (timerId !== null) return false;\n      timerId = scheduler.schedule(tick);\n      return true;\n    },\n    stop() {\n      if (timerId === null) return false;\n      scheduler.cancel(timerId);\n      timerId = null;\n      return true;\n    },\n    snapshot() { return { index, running: timerId !== null }; },\n  };\n}\n\nconst output = [];\nconst scheduler = createFakeScheduler();\nconst controller = createNewsController([\"A\", \"B\"], scheduler, value => output.push(value));\nconsole.log(`start1=${controller.start()}`);\nconsole.log(`start2=${controller.start()}`);\nscheduler.fire(); scheduler.fire();\nconsole.log(`ticks=${output.join('|')}`);\nconsole.log(`stop=${controller.stop()}`);\nscheduler.fire();\nconsole.log(`state=${JSON.stringify(controller.snapshot())}`);",
          walkthrough: [
            { lines: "1-8", explanation: "fake scheduler closure가 callback을 저장하고 ID 7 cancel 및 manual fire를 제공합니다." },
            { lines: "10-28", explanation: "controller closure가 index/timerId를 캡처하고 stable tick, idempotent start/stop과 snapshot을 반환합니다." },
            { lines: "31-39", explanation: "start 두 번, fire 두 번, stop 후 fire를 실행해 중복 schedule과 stale tick을 검증합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser module console"], command: "node news-controller.mjs" },
          output: { value: "start1=true\nstart2=false\nticks=0:A|1:B\nstop=true\nstate={\"index\":1,\"running\":false}", explanation: ["두 번째 start는 active timer invariant 때문에 false입니다.", "수동 fire 두 번이 A/B를 순서대로 전달합니다.", "stop 뒤 fire는 callback이 없어 상태를 바꾸지 않고 running=false입니다."] },
          experiments: [
            { change: "controller를 같은 scheduler에 하나 더 만들고 start합니다.", prediction: "현재 fake는 callback 하나만 저장해 서로 덮으므로 scheduler contract가 multi-ID를 지원해야 합니다.", result: "test double도 production API의 필요한 concurrency semantics를 구현해야 합니다." },
            { change: "items를 빈 array로 전달합니다.", prediction: "modulo 0과 undefined 문제가 생깁니다.", result: "factory entry에서 non-empty validation/error contract를 추가합니다." },
            { change: "stop에서 timerId=null을 제거합니다.", prediction: "stop 후 start가 계속 false여서 재시작할 수 없습니다.", result: "effect cleanup과 logical state transition을 함께 갱신합니다." },
          ],
          sourceRefs: ["web-timer-callback-source", "html-timers", "ecma-execution-environments"],
        },
      ],
      diagnostics: [
        { symptom: "두 news widget의 index와 stop 동작이 서로 섞인다.", likelyCause: "module/global cnt와 timer ID 하나를 여러 widget이 공유합니다.", checks: ["factory 호출당 captured binding이 생기는지 봅니다.", "timer ID owner와 DOM target을 instance별로 기록합니다.", "한 widget stop이 어떤 ID를 cancel하는지 확인합니다."], fix: "widget마다 controller factory instance를 만들고 scheduler/render dependency와 dispose owner를 명시합니다.", prevention: "두 instance를 교차 start/tick/stop하는 isolation test를 둡니다." },
      ],
      expertNotes: [
        "specification에서 closure가 단일 named object type으로 노출되는 것은 아닙니다. function object의 [[Environment]]와 lexical environment 연결을 observable behavior로 설명합니다.",
        "bind는 편리하지만 per-render/per-call에서 무분별하게 새 bound function을 만들면 identity·allocation·cleanup 문제가 생깁니다. stable wrapper를 lifecycle owner에 한 번 생성합니다.",
        "WeakRef/FinalizationRegistry로 일반 listener cleanup을 대체하지 않습니다. garbage collection timing은 비결정적이며 명시적 dispose/abort가 user-visible resource lifecycle의 기준입니다.",
      ],
    },
  ],
  lab: {
    title: "원본 greet·event·timer callback을 독립 controller와 안전한 lifecycle로 리팩터링하기",
    scenario: "현재 code는 inline onclick, anonymous listener, global cnt/timer와 method receiver 가정이 섞여 있습니다. handler()를 등록해 즉시 실행하거나 listener 제거가 실패하고, widget 두 개의 state가 충돌하며 unmount 뒤 callback이 남습니다.",
    setup: [
      "원본 function/event/timer 세 파일을 read-only evidence로 준비하고 callback 등록·호출 시점을 표로 만듭니다.",
      "Node.js module test와 browser DOM fixture, fake scheduler와 listener call counter를 준비합니다.",
      "ordinary/arrow/bound function, var/let loop, one/two widget, mount/unmount fixture를 준비합니다.",
      "callback contract마다 invoker·count·arguments·this·return·error·cancel/cleanup owner를 빈 표로 만듭니다.",
    ],
    steps: [
      "모든 `fn`과 `fn()`을 표시하고 registration-time과 invocation-time output을 예측합니다.",
      "greet/apply synchronous callback의 argument/return/throw contract를 구현해 exact test합니다.",
      "global counter를 factory closure로 바꾸고 두 instance가 독립 binding을 갖는지 교차 실행합니다.",
      "var/let loop callback과 mutable item snapshot/live-state 차이를 delayed invocation으로 재현합니다.",
      "ordinary method/bare/bind/arrow와 DOM event.currentTarget 결과를 표로 비교합니다.",
      "listener/timer callback identity를 owner에 저장하고 remove/abort/clear를 idempotent dispose에 연결합니다.",
      "fake scheduler controller에서 start-start-tick-tick-stop-late-tick과 two-instance sequence를 검증합니다.",
      "browser integration에서 keyboard click, unmount 후 call count 0, heap retainer와 sanitized error reporting을 확인합니다.",
    ],
    expectedResult: [
      "callback 자리에 즉시 호출 결과가 들어가는 사례가 0이고 callable validation/error가 명확합니다.",
      "lexical lookup과 closure state가 source nesting/outer invocation별로 예측한 값과 일치합니다.",
      "ordinary/arrow/bind/DOM currentTarget을 목적에 맞게 사용해 receiver loss가 없습니다.",
      "widget instance마다 index/timer/listener가 독립이고 active timer<=1 invariant가 유지됩니다.",
      "dispose/abort 이후 stale callback이 state/DOM을 수정하지 않고 listener/timer/large object가 불필요하게 retained되지 않습니다.",
      "callback invoker·result/error/cancel contract와 exact run/output이 독립 학습 문서에 남습니다.",
    ],
    cleanup: ["fake scheduler callback과 browser listener/timer를 dispose하고 heap snapshot 실험 object를 release합니다.", "inline onclick/global helper와 debug alert/log를 제거하고 module entry에서만 DOM adapter를 연결합니다."],
    extensions: ["AbortController 하나로 여러 listener와 fetch lifecycle을 묶는 controller를 설계합니다.", "Node test runner fake timers 또는 browser test clock과 직접 만든 fake scheduler 차이를 비교합니다.", "다음 세션에서 capture/target/bubble과 event delegation으로 listener 수를 줄입니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "function 참조, 직접 호출 결과와 synchronous/timer callback의 등록·실행 순서를 예측하고 출력하세요.", requirements: ["fn/typeof fn/fn()/return을 구분합니다.", "callback에 argument와 return을 전달합니다.", "handler() 등록 실수를 재현·수정합니다.", "동기 callback과 timer callback의 outer return을 비교합니다."], hints: ["괄호 평가 시점을 표시합니다.", "callback return을 누가 소비하는지 적습니다."], expectedOutcome: "모든 call이 언제 몇 번 실행되고 결과가 어디로 가는지 정확히 설명합니다.", solutionOutline: ["등록 log와 callback body log를 분리합니다.", "invoker contract 표를 먼저 작성합니다."] },
    { difficulty: "응용", prompt: "두 독립 counter와 세 delayed row callback을 closure로 구현하고 var/let·snapshot/live 차이를 test하세요.", requirements: ["factory call별 state isolation을 증명합니다.", "increment/read closure가 같은 binding을 공유합니다.", "var shared final index bug와 let fix를 재현합니다.", "mutable item과 primitive snapshot 결과를 비교합니다.", "heap/lifecycle owner를 문서화합니다."], hints: ["closure는 값보다 binding을 캡처한다고 생각합니다.", "callback 생성과 호출 시점을 나눕니다."], expectedOutcome: "scope/environment 구조로 모든 output과 object lifetime을 설명합니다.", solutionOutline: ["environment diagram에 factory call/iteration별 binding을 그립니다.", "test가 callback을 나중에 수동 호출하게 합니다."] },
    { difficulty: "설계", prompt: "DOM widget의 callback·this·cleanup 표준 controller API를 설계하세요.", requirements: ["listener/timer invoker contract와 stable identity를 정의합니다.", "ordinary/arrow/event.currentTarget 선택 기준을 정합니다.", "idempotent mount/start/stop/dispose와 AbortSignal을 포함합니다.", "error/cancel/stale callback/large capture policy를 정의합니다.", "two-instance·mount/unmount·late call·heap regression test를 설계합니다."], hints: ["callback 생성 owner와 제거 owner가 같아야 합니다.", "this가 없어도 explicit parameter/closure가 더 명확한지 비교합니다."], expectedOutcome: "framework 없이도 여러 widget이 충돌·누수 없이 동작하는 implementation-ready lifecycle specification이 완성됩니다.", solutionOutline: ["상태 invariant와 resource table을 먼저 만듭니다.", "fake scheduler/listener target interface를 주입합니다."] },
  ],
  reviewQuestions: [
    { question: "callback은 항상 비동기 함수인가요?", answer: "아닙니다. map/custom apply처럼 현재 call 안에서 동기 호출될 수도 있습니다. 핵심은 다른 invoker에 호출 권한을 전달한다는 점입니다." },
    { question: "handler와 handler()의 차이는 무엇인가요?", answer: "handler는 function value이고 handler()는 지금 호출해 return value를 만드는 expression입니다." },
    { question: "timer callback의 return value가 outer function return이 되나요?", answer: "아닙니다. outer call은 먼저 끝날 수 있고 timer host는 callback return을 일반 application result로 전달하지 않습니다." },
    { question: "lexical scope는 함수를 누가 호출했는지로 바뀌나요?", answer: "아닙니다. function이 source에서 정의된 lexical environment chain을 사용합니다." },
    { question: "closure는 outer 변수 값을 생성 당시 복사하나요?", answer: "일반적으로 captured binding을 통해 최신 값을 보며, 같은 binding을 공유한 closure끼리 변경을 관찰합니다." },
    { question: "factory를 두 번 호출한 counter는 왜 독립인가요?", answer: "각 outer call이 새로운 lexical environment와 count binding을 만들기 때문입니다." },
    { question: "var loop callback이 모두 마지막 index를 보는 이유는 무엇인가요?", answer: "모든 closure가 function-scoped var binding 하나를 공유하고 나중 실행될 때 final value를 읽기 때문입니다." },
    { question: "ordinary function과 arrow의 this 차이는 무엇인가요?", answer: "ordinary function은 호출 방식에서 this를 받고 arrow는 own this 없이 outer lexical this를 사용합니다." },
    { question: "bind한 function 두 개는 같은 identity인가요?", answer: "아닙니다. bind 호출마다 새 function object이므로 listener cleanup에는 저장한 같은 reference가 필요합니다." },
    { question: "removeEventListener에 같은 모양의 새 arrow를 주면 제거되나요?", answer: "아닙니다. 등록한 callback과 다른 object identity이므로 제거되지 않습니다." },
    { question: "closure 자체가 memory leak인가요?", answer: "아닙니다. 필요한 state 유지에 유용하며 listener/timer가 예상 수명보다 오래 reference graph를 유지할 때 문제가 됩니다." },
    { question: "DOM listener에서 element를 얻으려면 arrow의 this를 써야 하나요?", answer: "아닙니다. arrow는 lexical this를 쓰므로 event.currentTarget을 명시적으로 사용하는 편이 분명합니다." },
  ],
  completionChecklist: [
    "function value·call expression·return value와 callback 자리의 type을 구분했다.",
    "callback invoker의 시점·횟수·arguments·this·return/error/cancel contract를 작성했다.",
    "동기 callback과 event/timer host-scheduled callback의 stack/result channel을 구분했다.",
    "lexical scope chain·shadowing·TDZ를 source nesting에서 추적했다.",
    "closure가 binding을 보존/공유하고 factory call별 독립 state를 만드는 결과를 실행했다.",
    "var shared loop binding과 let per-iteration binding, snapshot/live state를 구분했다.",
    "ordinary method/bare/call/apply/bind와 arrow lexical this를 비교했다.",
    "DOM code에서는 target 목적에 따라 event.currentTarget과 callback kind를 선택했다.",
    "등록과 cleanup에 동일 callback identity/options를 사용하고 AbortSignal/timer ID owner를 정했다.",
    "fake scheduler controller에서 start 중복·tick·stop·late callback과 instance isolation을 검증했다.",
    "callback이 캡처한 DOM/large object의 lifetime과 dispose/heap test를 문서화했다.",
  ],
  nextSessions: ["js-03-event-model-listeners"],
  sources: [
    { id: "web-callback-function-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex01_function.html", usedFor: ["greet callback", "function reference versus call", "named/anonymous/arrow function", "setTimeout registration", "inline onclick"], evidence: "greet(name,callback), sayGoodbye, const res=sayHello, 두 timer wrapper를 callback invoker·function identity·this/closure의 출발점으로 사용했습니다." },
    { id: "web-event-listener-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex03_event.html", usedFor: ["addEventListener", "named/anonymous listener", "click/mouse callbacks", "method receiver contrast", "listener lifecycle"], evidence: "네이버 link named listener와 클릭/mouseover/mouseout anonymous listener를 callback 시점·identity·this/currentTarget·cleanup 분석에 반영했습니다." },
    { id: "web-timer-callback-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex08_callback.html", usedFor: ["setInterval callback", "timer ID", "captured cnt", "three-run cleanup", "function declaration callback"], evidence: "global cnt와 chk를 캡처한 timer1이 세 번 뒤 clearInterval하는 흐름을 closure state·effect owner·fake scheduler controller로 확장했습니다." },
    { id: "ecma-functions-arrow", repository: "TC39 ECMAScript Language Specification", path: "multipage/ecmascript-language-functions-and-classes.html#sec-arrow-function-definitions", publicUrl: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-arrow-function-definitions", usedFor: ["function/arrow creation", "lexical this", "parameter/body", "function object environment"], evidence: "ordinary/arrow function과 lexical this·environment 차이를 current ECMAScript specification에 맞춰 설명했습니다." },
    { id: "ecma-execution-environments", repository: "TC39 ECMAScript Language Specification", path: "multipage/executable-code-and-execution-contexts.html", publicUrl: "https://tc39.es/ecma262/multipage/executable-code-and-execution-contexts.html", usedFor: ["lexical environment", "environment chain", "function declaration instantiation", "captured binding", "execution context lifetime"], evidence: "scope chain과 closure binding을 단순 value snapshot이 아닌 environment reference로 설명하는 근거로 사용했습니다." },
    { id: "ecma-ordinary-this", repository: "TC39 ECMAScript Language Specification", path: "multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinarycallbindthis", publicUrl: "https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinarycallbindthis", usedFor: ["ordinary call this", "strict/global this mode", "receiver binding", "method/detached call"], evidence: "ordinary function this가 object 정의가 아니라 call semantics에서 binding되는 규칙을 기준으로 사용했습니다." },
    { id: "ecma-call", repository: "TC39 ECMAScript Language Specification", path: "multipage/abstract-operations.html#sec-call", publicUrl: "https://tc39.es/ecma262/multipage/abstract-operations.html#sec-call", usedFor: ["callable validation", "Call operation", "thisValue/arguments", "callback invocation"], evidence: "callback invoker가 callable을 this/argument list로 호출하는 language-level 기반으로 사용했습니다." },
    { id: "dom-event-listener", repository: "WHATWG DOM Standard", path: "#concept-event-listener", publicUrl: "https://dom.spec.whatwg.org/#concept-event-listener", usedFor: ["event listener callback", "callback identity", "capture/once/passive/signal", "removeEventListener", "currentTarget"], evidence: "listener record와 add/remove/abort lifecycle을 DOM Standard에 맞춰 다음 event model의 준비 범위로 설명했습니다." },
    { id: "html-timers", repository: "WHATWG HTML Standard", path: "multipage/timers-and-user-prompts.html#timers", publicUrl: "https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers", usedFor: ["setTimeout/setInterval", "handler invocation", "timer ID/clear", "delay/task", "callback return boundary"], evidence: "원본 timer callback을 HTML timer initialization/clear semantics와 연결하고 fake scheduler가 보존해야 할 lifecycle contract를 확인했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본 세 파일은 function 참조·greet callback, DOM listener와 timer ID/count closure를 직접 제공합니다. lexical environment, per-iteration binding, bind/arrow this, listener identity/AbortSignal, memory reachability는 TC39/WHATWG 표준에 따라 보강했습니다.",
      "event capture/target/bubble/delegation과 preventDefault는 js-03, task/microtask와 timer drift는 js-08, Promise error propagation은 js-09에서 각각 독립적으로 더 깊게 다룹니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 340;
expertSession.chapters.push(
  {
    id: "callback-ownership-cancellation-reentrancy",
    title: "callback 등록을 소유권·취소·재진입·오류 격리 계약으로 설계합니다",
    lead: "callback을 넘긴다는 것은 나중에 호출될 함수 reference뿐 아니라 누가 언제 몇 번 호출하고, 어떻게 해제하며, 실행 중 상태가 다시 바뀔 수 있는지를 함께 넘기는 일입니다. 이 절은 DOM·timer·구독 API 어디서든 적용되는 lifetime 계약을 독립적으로 정리합니다.",
    explanations: [
      "callback API 문서에는 호출 시점, 최대 호출 횟수, argument shape, this binding, 반환값 사용 여부, throw 처리, 취소 방법이 있어야 합니다. Array.map callback과 event listener는 둘 다 함수지만 map은 동기적으로 입력 수만큼 호출하고, listener는 host가 향후 event마다 호출하며 명시 해제 전까지 살아 있을 수 있습니다.",
      "removeEventListener는 같은 type·callback identity·capture 조건을 사용해야 합니다. 매번 새 arrow를 만들면 원래 reference와 다르므로 제거되지 않습니다. listener group이 component lifetime과 같다면 AbortController 하나의 signal을 여러 등록에 전달하고 unmount에서 abort하는 방식이 해제 지점을 한 곳으로 모읍니다.",
      "`once: true`는 첫 dispatch 뒤 listener를 제거하지만 callback 내부 async 작업이 중복되지 않는다는 뜻은 아닙니다. event가 빠르게 들어오고 callback이 Promise를 시작한다면 in-flight flag, queue, idempotency key가 별도로 필요합니다. disabled UI만으로 backend 중복 효과가 막히지는 않습니다.",
      "재진입은 callback 실행 중 같은 event를 다시 dispatch하거나 observable state 변경이 또 callback을 호출하는 상황입니다. iteration 중 listener 목록을 바꾸거나 상태를 반쯤 갱신한 채 재진입하면 invariant가 깨집니다. 먼저 완성된 새 상태를 계산하고 commit한 뒤 외부 callback을 알리거나, dispatch queue로 다음 turn에 처리합니다.",
      "한 listener의 throw가 다른 처리와 host에 미치는 효과는 API마다 다릅니다. 모든 callback을 `try/catch`로 삼켜서는 안 되며, plugin처럼 서로 격리가 필요한 경계에서는 각 오류에 plugin id·cause를 붙여 수집하고 핵심 invariant 위반은 상위 오류 채널로 전파합니다. 사용자 데이터 전체를 오류 메시지에 넣지 않습니다.",
      "구독 함수가 unsubscribe 함수를 반환하면 closure가 정확한 target·callback identity를 보존할 수 있습니다. 반환된 cleanup은 여러 번 호출해도 같은 결과인 idempotent 동작이 좋습니다. 이미 abort된 signal로 새 listener를 등록하면 callback이 활성화되지 않는 경계도 테스트합니다.",
    ],
    concepts: [
      { term: "callback ownership", definition: "callback reference의 등록·호출·해제를 어느 객체나 lifecycle이 책임지는지 정한 계약입니다.", detail: ["소유자가 cleanup을 호출합니다.", "listener identity와 capture 조건을 보존합니다."] },
      { term: "reentrancy", definition: "현재 callback 실행이 끝나기 전에 같은 상태 기계나 callback 흐름이 다시 진입하는 현상입니다.", detail: ["동기 dispatch와 setter callback에서도 발생합니다.", "원자적 상태 commit 또는 queue가 필요할 수 있습니다."] },
      { term: "idempotent cleanup", definition: "cleanup을 한 번 이상 호출해도 첫 호출 이후 상태가 더 나빠지지 않는 해제 동작입니다.", detail: ["AbortController.abort는 반복 호출을 안전하게 다룰 수 있습니다.", "component unmount 중복에 강합니다."] },
    ],
    codeExamples: [
      {
        id: "eventtarget-abort-once-lifetime",
        title: "EventTarget의 signal cleanup과 once 호출 횟수",
        language: "javascript",
        filename: "listener-lifetime.mjs",
        purpose: "Node가 제공하는 표준 EventTarget·AbortController로 여러 dispatch, once, 일괄 abort와 WeakMap lifetime metadata를 결정적으로 검증합니다.",
        code: "class AmountEvent extends Event {\n  constructor(amount) {\n    super('amount');\n    this.amount = amount;\n  }\n}\n\nconst target = new EventTarget();\nconst controller = new AbortController();\nconst lifetimes = new WeakMap([[target, controller]]);\nlet total = 0;\nlet onceCalls = 0;\n\ntarget.addEventListener('amount', (event) => {\n  total += event.amount;\n}, { signal: controller.signal });\ntarget.addEventListener('amount', () => {\n  onceCalls += 1;\n}, { once: true });\n\ntarget.dispatchEvent(new AmountEvent(2));\ntarget.dispatchEvent(new AmountEvent(3));\nlifetimes.get(target).abort();\ntarget.dispatchEvent(new AmountEvent(5));\n\nconsole.log(`total=${total}`);\nconsole.log(`once=${onceCalls}`);",
        walkthrough: [
          { lines: "1-6", explanation: "Event를 상속해 amount payload를 가진 합성 event type을 만듭니다." },
          { lines: "8-12", explanation: "target과 lifetime controller를 만들고 WeakMap에 target별 cleanup metadata를 연결합니다." },
          { lines: "14-19", explanation: "누적 listener는 signal에, 호출 횟수 listener는 once option에 연결합니다." },
          { lines: "21-24", explanation: "두 번 dispatch한 뒤 controller를 abort하고 세 번째 event가 누적 listener에 도달하지 않는지 확인합니다." },
          { lines: "26-27", explanation: "누적 값과 once listener의 정확한 한 번 호출을 출력합니다." },
        ],
        run: { environment: ["Node.js 18 이상", "listener-lifetime.mjs를 UTF-8로 저장"], command: "node listener-lifetime.mjs" },
        output: { value: "total=5\nonce=1", explanation: ["signal listener는 amount 2와 3만 처리해 total 5가 됩니다.", "once listener는 첫 event 뒤 제거되어 정확히 한 번 호출됩니다.", "abort 뒤 amount 5는 signal에 연결된 listener를 호출하지 않습니다."] },
        experiments: [
          { change: "abort 호출을 제거합니다.", prediction: "세 번째 amount 5도 누적되어 total=10이 됩니다.", result: "cleanup이 callback lifetime을 실제로 끝내는 지점임을 확인합니다." },
          { change: "once option을 제거합니다.", prediction: "onceCalls가 세 번으로 증가합니다.", result: "listener reference와 호출 횟수 정책이 별도 option임을 확인합니다." },
        ],
        sourceRefs: ["dom-event-listener", "ecma-functions-arrow", "ecma-execution-environments", "ecma-keyed-collections-02"],
      },
    ],
    diagnostics: [
      { symptom: "화면을 열고 닫을수록 한 번의 동작이 여러 번 실행된다.", likelyCause: "mount마다 listener를 등록하지만 같은 identity로 제거하거나 signal을 abort하지 않아 callback이 누적됐습니다.", checks: ["등록·cleanup 호출 횟수를 component instance id로 셉니다.", "remove에 전달한 callback과 capture가 원본과 같은지 확인합니다.", "이미 종료된 instance가 closure에 남는지 heap snapshot retaining path를 봅니다."], fix: "등록 소유자가 unsubscribe 또는 AbortController를 보관하고 lifecycle 종료에서 idempotent cleanup을 호출합니다.", prevention: "mount→event→unmount→event 통합 테스트에서 마지막 event가 이전 instance를 호출하지 않음을 검증합니다." },
      { symptom: "callback 안에서 상태를 갱신하면 같은 callback이 재귀적으로 다시 실행된다.", likelyCause: "동기 observable setter나 dispatch가 현재 처리 중인 흐름에 재진입했습니다.", checks: ["callback entry depth를 개발 fixture로 기록합니다.", "외부 callback 호출 전에 상태 invariant가 완성되는지 봅니다.", "동기 dispatch와 queued dispatch를 구분합니다."], fix: "새 상태를 먼저 원자적으로 commit하고 알림을 나중에 보내거나 명시 queue와 reentrancy guard를 둡니다.", prevention: "재진입 입력과 cleanup 중 dispatch를 상태 기계 테스트에 포함합니다." },
    ],
    expertNotes: ["EventTarget listener가 error를 throw했을 때 보고 방식은 host 구현과 API 경계에 의존하므로 plugin 격리 요구는 자체 dispatcher에서 명시합니다.", "AbortSignal은 소유권을 표현하지만 business transaction rollback을 대신하지 않습니다. 이미 발생한 외부 효과의 보상은 별도입니다."],
  },
  {
    id: "closure-reachability-weak-metadata-memory-profile",
    title: "closure reachability와 WeakMap을 이해하고 메모리 누수를 retaining path로 진단합니다",
    lead: "closure가 살아 있는 동안 캡처한 binding과 그 binding이 가리키는 객체도 도달 가능할 수 있습니다. ‘closure는 메모리 누수’가 아니라 필요 이상 긴 lifetime과 큰 object graph를 캡처하는 소유권 불일치가 문제입니다.",
    explanations: [
      "garbage collector는 scope가 끝났는지가 아니라 root에서 객체까지 도달 가능한지를 기준으로 회수 가능성을 판단합니다. 전역 registry→listener→closure→DOM subtree 경로가 남으면 화면에서 remove된 node도 메모리에 유지될 수 있습니다. 변수를 null로 만드는 것보다 registry 해제와 timer 취소처럼 실제 root 연결을 끊는 일이 우선입니다.",
      "closure는 사용한 모든 lexical 이름을 개념적으로 기억하지만 engine의 최적화 세부에 의존해 메모리 크기를 추측하지 않습니다. callback이 필요한 primitive id만 캡처하도록 하고 큰 response·node·cache는 lifetime이 짧은 local 또는 명시 store에서 조회합니다.",
      "Map은 key를 강하게 참조하므로 node/object별 metadata store가 key를 회수되지 못하게 할 수 있습니다. WeakMap은 key가 다른 곳에서 도달 불가능할 때 metadata 때문에 key가 살아남지 않도록 설계됐으며 key 열거를 제공하지 않습니다. 전체 항목을 순회·통계해야 한다면 WeakMap만으로 해결할 수 없고 명시 cleanup이 있는 Map이 필요할 수 있습니다.",
      "WeakRef와 FinalizationRegistry는 GC 시점이 관찰 불가능하고 실행되지 않을 수도 있어 correctness·파일 close·구독 해제에 쓰지 않습니다. cache 최적화 같은 보조 기능에서도 strong fallback과 nondeterministic 테스트 한계를 이해해야 합니다.",
      "Chrome DevTools Memory에서 반복 시나리오 전후 heap snapshot을 찍고, detached node 또는 큰 객체의 retaining path를 따라 root까지 올라갑니다. allocation instrumentation은 어느 사용자 행동에서 늘었는지 보여 줍니다. 강제 GC 뒤 감소 여부만으로 결론내지 말고 동일 시나리오를 여러 번 반복해 plateau를 봅니다.",
      "메모리 테스트는 정확한 byte golden보다 lifecycle invariant가 안정적입니다. cleanup 뒤 registry size 0, listener가 더 호출되지 않음, timer id 해제, store에서 id 삭제를 검증합니다. WeakMap은 열거할 수 없으므로 동작 테스트와 heap profile을 함께 사용합니다.",
    ],
    concepts: [
      { term: "reachability", definition: "global·실행 stack·host registry 같은 root에서 참조 경로를 따라 객체에 도달할 수 있는 상태입니다.", detail: ["도달 가능하면 보통 GC 대상이 아닙니다.", "closure도 참조 경로의 한 node입니다."] },
      { term: "retaining path", definition: "회수될 것으로 기대한 객체를 root에서 계속 도달 가능하게 만드는 참조 연결의 연쇄입니다.", detail: ["heap snapshot에서 원인 소유자를 찾습니다.", "detached DOM 자체보다 누가 보유하는지가 핵심입니다."] },
      { term: "weak keyed metadata", definition: "object key가 다른 곳에서 사라질 때 metadata store만으로 key 생존을 강제하지 않는 WeakMap/WeakSet 관계입니다.", detail: ["key를 열거할 수 없습니다.", "명시 자원 cleanup을 대체하지 않습니다."] },
    ],
    codeExamples: [],
    diagnostics: [
      { symptom: "DOM에서는 제거된 component가 heap snapshot의 Detached 트리에 계속 남는다.", likelyCause: "전역 listener·timer·registry callback closure가 component node 또는 큰 state를 캡처한 채 root에서 도달 가능합니다.", checks: ["snapshot retaining path를 root까지 추적합니다.", "unmount 후 listener·timer·registry count를 확인합니다.", "callback이 실제 필요한 값보다 큰 object graph를 캡처하는지 봅니다."], fix: "lifecycle cleanup으로 root 연결을 끊고 metadata가 객체 lifetime을 따라야 하면 WeakMap을 검토합니다.", prevention: "반복 mount/unmount 후 호출 0·registry 0 lifecycle 테스트와 주기적 heap profile을 둡니다." },
    ],
    comparisons: [
      { title: "객체별 metadata를 Map과 WeakMap 중 어디에 저장할까요?", options: [
        { name: "Map", chooseWhen: "항목 열거·size·명시 lifecycle 관리가 필요하고 cleanup을 확실히 수행할 때", avoidWhen: "store만의 key 참조가 object lifetime을 불필요하게 늘릴 때", tradeoffs: ["관찰과 디버깅이 쉽습니다.", "key를 강하게 보유합니다.", "삭제 책임이 명시적입니다."] },
        { name: "WeakMap", chooseWhen: "metadata lifetime이 object key lifetime과 같고 열거가 필요 없을 때", avoidWhen: "전체 metadata를 순회·직렬화·정확히 count해야 할 때", tradeoffs: ["store 때문에 key가 유지되지 않습니다.", "GC 시점을 관찰할 수 없습니다.", "열거 API가 없습니다."] },
      ] },
    ],
    expertNotes: ["메모리 profile에 사용자 콘텐츠가 포함될 수 있으므로 공유 artifact는 합성 fixture로 재현하거나 민감 데이터를 제거합니다.", "WeakMap 도입은 강한 참조 하나를 약하게 바꿀 뿐이며 다른 listener·array가 key를 보유하면 객체는 계속 살아 있습니다."],
  },
);

expertSession.reviewQuestions.push(
  { question: "callback API가 문서화해야 할 lifetime 정보는 무엇인가요?", answer: "누가 언제 몇 번 호출하는지, arguments·this·반환·throw를 어떻게 다루는지, 어떤 identity와 방법으로 취소·cleanup하는지를 명시해야 합니다." },
  { question: "closure가 scope 종료 후에도 데이터를 유지할 수 있는 이유는 무엇인가요?", answer: "함수 객체가 필요한 lexical binding을 참조하고 그 함수가 root에서 도달 가능한 동안 binding의 객체 graph도 도달 가능할 수 있기 때문입니다." },
  { question: "WeakMap이 explicit cleanup을 대체하지 못하는 이유는 무엇인가요?", answer: "GC 시점이 보장되지 않고 listener·timer·외부 자원은 WeakMap key 회수와 별개이며, 다른 strong reference가 있으면 key도 계속 살아 있기 때문입니다." },
);
expertSession.completionChecklist.push(
  "callback 등록의 호출 횟수·argument·this·오류·취소 계약을 작성할 수 있다.",
  "listener identity와 AbortSignal을 이용해 idempotent cleanup을 구현할 수 있다.",
  "재진입 전에 상태 invariant를 commit하거나 queue로 격리할 수 있다.",
  "heap snapshot의 retaining path로 closure·listener·detached DOM 소유자를 찾을 수 있다.",
);
expertSession.sources.push(
  { id: "ecma-keyed-collections-02", repository: "TC39 ECMAScript Language Specification", path: "multipage/keyed-collections.html", publicUrl: "https://tc39.es/ecma262/multipage/keyed-collections.html", usedFor: ["Map", "WeakMap", "weak key semantics", "열거 제한"], evidence: "Map과 WeakMap의 observable key 보유·열거 차이를 closure metadata와 memory lifetime 설명에 연결했습니다." },
);
