import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-04-built-in-objects"],
  slug: "js-04-built-in-objects",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 4,
  title: "Date·Math·Number·String과 Window 내장 기능을 경계 중심으로 사용하기",
  subtitle: "메서드 이름을 암기하는 대신 시간대·난수 구간·숫자 문법·Unicode 문자열·popup/navigation의 입력과 보장 범위를 실행 결과로 검증합니다.",
  level: "기초",
  estimatedMinutes: 290,
  coreQuestion: "표준 built-in과 browser host API가 어떤 type·범위·시간대·보안 조건을 기대하며, 모호한 입력을 어떻게 검증해 재현 가능한 결과로 바꿀까요?",
  summary: "원본 Date 연속 독서 일수, Math.random 추첨, Number/parseInt 비교, String 검색·추출·치환·분할, window.open 공지를 전부 감사합니다. ECMAScript built-in/intrinsic/prototype method와 DOM/Window host API를 구분하고 primitive wrapper를 new로 만들지 않는 이유를 설명합니다. Date를 epoch milliseconds의 instant와 local/UTC calendar projection으로 나누고 ISO offset·invalid date·월 0-index·DST의 24시간과 달력 하루 차이를 다룹니다. Math.random의 [0,1)와 inclusive integer 공식을 dependency-injected deterministic random으로 검증하고 암호/추첨 공정성에는 Web Crypto·서버 정책이 필요한 이유를 밝힙니다. Number와 parseInt/parseFloat의 전체 변환/접두 parse, NaN·finite·safe integer·binary64 rounding과 money를 다룹니다. String immutability, UTF-16 code unit·code point·grapheme, slice/substring/replace/split/trim/Intl을 exact output으로 실행합니다. 마지막에는 window/open/location/URL, popup blocker·opener isolation·same-origin·user activation과 testable adapter를 설계합니다.",
  objectives: [
    "ECMAScript built-in object/function과 browser Window/DOM host API를 구분하고 static/prototype method 호출 위치를 설명할 수 있다.",
    "Date의 epoch milliseconds, UTC/local projection, ISO offset, invalid date와 calendar day/duration day를 구분할 수 있다.",
    "Math.random의 반열린 구간에서 unbiased 범위 정수를 계산하고 deterministic random dependency로 경계를 test할 수 있다.",
    "Number·parseInt·parseFloat의 허용 문법과 NaN/finite/integer/safe range를 구분해 input parser를 선택할 수 있다.",
    "binary64 정밀도·signed zero·BigInt·money rounding 한계를 알고 domain에 맞는 numeric representation을 선택할 수 있다.",
    "String의 불변성, UTF-16 length와 code point/grapheme 차이를 이해하고 검색·slice·replace·split·trim 결과를 저장할 수 있다.",
    "window.open/location/URL의 user activation·popup·opener·same-origin·navigation 경계를 adapter와 error state로 처리할 수 있다.",
  ],
  prerequisites: [
    { title: "값·변수·조건·반복과 함수 호출", reason: "primitive/object, 명시적 conversion, function contract와 dependency injection 위에서 built-in method를 정확히 선택합니다.", sessionSlug: "js-01-values-control-functions" },
    { title: "DOM 이벤트와 기본 동작", reason: "window.open이 click user activation과 popup policy에 의존하고 navigation default/URL security boundary가 있음을 연결합니다.", sessionSlug: "js-03-event-model-listeners" },
  ],
  keywords: ["built-in object", "Date", "epoch milliseconds", "UTC", "time zone", "ISO 8601", "Math.random", "inclusive range", "crypto.getRandomValues", "Number", "parseInt", "parseFloat", "NaN", "safe integer", "binary64", "String", "UTF-16", "code point", "grapheme", "Intl", "Window", "window.open", "location", "URL"],
  chapters: [
    {
      id: "builtins-intrinsics-host-wrappers",
      title: "표준 built-in과 browser host object를 먼저 분류해야 runtime·test·보안 contract가 보입니다",
      lead: "Date·Math·Number·String은 ECMAScript에, window·document·location은 browser host에 속합니다.",
      explanations: [
        "ECMAScript specification은 Number, String, Date, Math, Array 같은 standard built-in object/function과 prototype method를 정의합니다. browser Window, Document, Location, setTimeout은 HTML/DOM 등 web platform host가 제공합니다. Node에서 window가 없는 것은 JavaScript가 없어서가 아닙니다.",
        "Math는 function constructor가 아니라 namespace-like ordinary object로 static function/random/constant를 제공합니다. Number와 String은 conversion function으로 호출할 수 있고 `new Number(1)`/`new String('x')`는 wrapper object를 만들어 truthiness·===가 달라지므로 일반 data에는 primitive를 사용합니다.",
        "primitive string에서 `text.trim()`이 가능한 것은 property access/call semantics가 String prototype method를 사용할 수 있게 하기 때문이지 primitive 내부가 mutable object가 된다는 뜻은 아닙니다. method는 새 string을 반환합니다.",
        "static method와 instance/prototype method를 구분합니다. Number.isNaN(value)는 Number constructor의 property이고 text.slice는 String value를 receiver로 한 method입니다. Java처럼 모든 기능을 new instance에서 찾지 않습니다.",
        "built-in도 input coercion과 abrupt error를 가질 수 있습니다. Math.max는 Number coercion을 수행할 수 있고 String method는 null/undefined receiver에서 실패합니다. public boundary에서 type을 먼저 검증해 hidden coercion을 좁힙니다.",
        "test에서는 current clock/random/window popup을 직접 고정 호출하지 않고 `now`, `random`, `openWindow` dependency를 argument로 주입합니다. deterministic pure core와 host adapter를 분리하면 edge case를 기다리지 않고 재현합니다.",
      ],
      concepts: [
        { term: "built-in object", definition: "ECMAScript implementation이 language specification에 따라 제공하는 standard object입니다.", detail: ["Date/Math/Number/String 등이 있습니다.", "host object와 구분합니다."] },
        { term: "host-defined API", definition: "browser/Node 같은 host가 ECMAScript 바깥 specification 또는 환경 계약으로 제공하는 API입니다.", detail: ["Window/DOM이 대표적입니다.", "runtime마다 존재 여부가 다릅니다."] },
        { term: "wrapper object", definition: "Number/String/Boolean primitive를 object 형태로 감싼 object입니다.", detail: ["new Number/String이 만듭니다.", "일반 값에는 primitive를 우선합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "`if (new Boolean(false))`가 true branch로 간다.", likelyCause: "false primitive가 아니라 truthy object wrapper를 만들었습니다.", checks: ["typeof와 instanceof, valueOf 결과를 비교합니다.", "new Boolean/Number/String 사용을 검색합니다.", "API가 primitive를 요구하는지 봅니다."], fix: "conversion은 `Boolean(value)`, `Number(value)`, `String(value)`처럼 new 없이 primitive로 만들고 wrapper object를 제거합니다.", prevention: "no-new-wrappers lint rule과 primitive type assertion을 적용합니다." },
      ],
    },
    {
      id: "date-instant-epoch-utc-local",
      title: "Date는 한 instant의 epoch milliseconds를 저장하고 local/UTC calendar field로 투영합니다",
      lead: "Date object가 시간대 자체를 저장한다고 생각하지 말고 동일 instant를 어떤 zone 기준 field로 읽는지 구분합니다.",
      explanations: [
        "Date의 time value는 UTC 1970-01-01T00:00:00Z 기준 milliseconds 수로 instant를 나타냅니다. `getTime()`/valueOf는 그 number를 반환하고 invalid date는 NaN time value를 가질 수 있습니다.",
        "getFullYear/getMonth/getDate/getHours는 host local time zone 기준 field이고 getUTCFullYear/getUTCMonth/getUTCDate/getUTCHours는 UTC 기준입니다. getMonth는 0~11이라 display month는 +1이지만 직접 field 조합보다 Intl.DateTimeFormat을 우선합니다.",
        "ISO date-time string에 `Z` 또는 explicit offset을 포함하면 instant 해석이 분명합니다. date-only `YYYY-MM-DD`와 offset 없는 date-time, implementation-dependent non-standard string을 섞지 않습니다. API contract에 accepted syntax와 time zone 의미를 명시합니다.",
        "`new Date(year,monthIndex,day)`는 local component constructor이며 month가 0-based이고 overflow가 normalize될 수 있습니다. invalid user date를 constructor normalization에 맡기지 않고 입력 component와 round-trip field를 검증합니다.",
        "원본 `new Date('2026-02-16')`부터 today까지 milliseconds를 86,400,000으로 나눈 결과는 elapsed 24-hour blocks에 가깝습니다. 사용자의 local 달력에서 ‘연속 며칠’은 DST로 어떤 하루가 23/25시간일 수 있어 local date identifier 또는 time-zone-aware calendar 계산이 필요합니다.",
        "현재 시간 `new Date()`는 test마다 바뀝니다. function에 `nowMs`/clock을 주입하고 fixed instant로 expected output을 만듭니다. server/client zone과 locale도 test matrix에 명시합니다.",
      ],
      concepts: [
        { term: "instant", definition: "timeline 위의 한 시점을 나타내는 값으로 Date에서는 epoch milliseconds time value로 표현됩니다.", detail: ["time zone projection과 다릅니다.", "동일 instant를 여러 local field로 볼 수 있습니다."] },
        { term: "UTC/local accessor", definition: "같은 Date time value를 UTC 또는 host local time zone의 calendar component로 읽는 method family입니다.", detail: ["getUTC...와 get...을 구분합니다.", "혼용하면 날짜가 바뀔 수 있습니다."] },
        { term: "invalid Date", definition: "time value가 NaN이라 유효한 instant를 나타내지 못하는 Date object입니다.", detail: ["object 자체는 truthy입니다.", "Number.isNaN(date.getTime())로 검사합니다."] },
      ],
      codeExamples: [
        {
          id: "fixed-date-utc-duration",
          title: "고정 ISO instant의 UTC field와 elapsed day 계산",
          language: "javascript",
          filename: "date-utc.mjs",
          purpose: "host local time zone과 무관한 ISO Z input·UTC accessor·fixed duration output으로 Date 정신 모델을 검증합니다.",
          code: "const start = new Date(\"2026-02-16T00:00:00Z\");\nconst end = new Date(\"2026-02-26T12:00:00Z\");\nconst elapsedMs = end.getTime() - start.getTime();\nconst elapsedDays = elapsedMs / 86_400_000;\n\nconsole.log(`iso=${start.toISOString()}`);\nconsole.log(`utc=${start.getUTCFullYear()}-${String(start.getUTCMonth() + 1).padStart(2, \"0\")}-${String(start.getUTCDate()).padStart(2, \"0\")}`);\nconsole.log(`ms=${elapsedMs}`);\nconsole.log(`days=${elapsedDays}`);\nconsole.log(`invalid=${Number.isNaN(new Date(\"not-a-date\").getTime())}`);",
          walkthrough: [
            { lines: "1-2", explanation: "두 ISO string에 Z를 포함해 UTC instant를 명시합니다." },
            { lines: "3-4", explanation: "epoch millisecond difference와 exact 24-hour unit의 elapsed duration을 계산합니다." },
            { lines: "6-10", explanation: "canonical ISO, UTC year/month/day, milliseconds/day와 invalid time value를 출력합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser", "host time zone과 무관한 UTC output"], command: "node date-utc.mjs" },
          output: { value: "iso=2026-02-16T00:00:00.000Z\nutc=2026-02-16\nms=907200000\ndays=10.5\ninvalid=true", explanation: ["start ISO와 UTC field는 host zone에 관계없이 같습니다.", "10일 12시간은 907,200,000ms와 10.5 elapsed days입니다.", "invalid Date object는 truthy일 수 있으므로 getTime NaN을 검사합니다."] },
          experiments: [
            { change: "UTC accessor를 local getFullYear/getMonth/getDate로 바꿉니다.", prediction: "host time zone에 따라 local date가 2월 15일 또는 16일 등 달라질 수 있습니다.", result: "exact test에는 zone을 고정하거나 UTC를 사용합니다." },
            { change: "end를 local DST transition 전후 instant로 바꿉니다.", prediction: "elapsed 24-hour 수와 local calendar date count가 다를 수 있습니다.", result: "duration과 calendar day requirement를 분리합니다." },
            { change: "start input을 `02/16/2026`으로 바꿉니다.", prediction: "non-standard/locale-like parsing portability를 보장하기 어렵습니다.", result: "versioned ISO grammar와 explicit offset을 사용합니다." },
          ],
          sourceRefs: ["web-date-source", "ecma-numbers-dates", "ecma-intl"],
        },
      ],
      diagnostics: [
        { symptom: "서버에서는 2월 16일인데 한국 browser에서는 표시/연속일 계산이 하루 다르다.", likelyCause: "UTC instant와 local calendar date accessor/string parsing을 섞었습니다.", checks: ["raw ISO의 Z/offset과 epoch ms를 기록합니다.", "getUTC...와 get... 결과 및 resolved timeZone을 비교합니다.", "요구가 elapsed duration인지 local calendar date인지 확인합니다."], fix: "API instant에는 offset/Z를 포함하고 표시 zone을 Intl에 명시하며 calendar streak는 해당 zone의 date identifier로 계산합니다.", prevention: "UTC/KST/미주 DST zone과 자정 경계 contract test를 둡니다." },
      ],
    },
    {
      id: "date-format-calendar-timezone",
      title: "날짜 표시는 문자열 이어붙이기보다 Intl locale·timeZone option으로, 계산은 명시적 단위로 합니다",
      lead: "month +1만 고쳐도 locale order·calendar·digits·time zone name·DST 문제는 남습니다.",
      explanations: [
        "Intl.DateTimeFormat은 locale과 options, optional timeZone을 받아 Date instant를 사용자 표현으로 format합니다. output punctuation/space는 runtime locale data에 따라 달라질 수 있어 사람에게 보여 주는 text를 무조건 exact string snapshot으로 고정하지 않습니다.",
        "API/storage에는 canonical ISO instant 또는 explicit local date schema를 쓰고 presentation에서 Intl을 사용합니다. localized display string을 다시 parse해 business logic에 넣지 않습니다.",
        "date-only birthday, 예약 local wall time, global instant은 서로 다른 domain type입니다. Date 하나로 모두 표현하면 server zone/default conversion이 섞입니다. `{year,month,day}`와 time zone ID, instant를 requirement에 따라 분리합니다.",
        "날짜 더하기에서 `setDate(getDate()+1)`은 local calendar normalization을 수행하고 `ms+86400000`은 elapsed 24시간을 더합니다. DST 전후 결과가 다를 수 있으므로 ‘내일 같은 시각’과 ‘24시간 후’를 구분합니다.",
        "Date.now는 현재 epoch milliseconds number를 반환해 latency/duration의 단순 wall clock에 쓸 수 있지만 monotonic 성능 측정에는 performance.now를 검토합니다. system clock adjustment와 privacy precision을 고려합니다.",
        "invalid/ambiguous input은 사용자에게 field별로 되돌리고 server에서도 재검증합니다. Date.parse 결과가 finite인지, component가 round-trip하는지와 allowed range를 검사합니다.",
      ],
      concepts: [
        { term: "calendar date versus duration", definition: "특정 time zone/calendar의 연·월·일 변화와 timeline에서 경과한 milliseconds/seconds의 구분입니다.", detail: ["DST에서 달라질 수 있습니다.", "요구에 따라 연산을 선택합니다."] },
        { term: "Intl.DateTimeFormat", definition: "locale·timeZone·field option에 따라 date/time을 국제화해 표현하는 ECMAScript Intl built-in입니다.", detail: ["display용입니다.", "localized output 재파싱을 피합니다."] },
        { term: "wall time", definition: "특정 지역 시계에 표시되는 local date/time으로 같은 표현이 time zone/DST 규칙 없이는 하나의 instant를 결정하지 못할 수 있습니다.", detail: ["time zone ID와 함께 저장할 수 있습니다.", "global instant와 분리합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "매일 오전 9시 예약을 이전 실행 시각+24시간으로 만들자 DST 이후 10시에 실행된다.", likelyCause: "local calendar recurrence를 elapsed duration으로 계산했습니다.", checks: ["요구가 24시간 후인지 local 09:00인지 확인합니다.", "zone ID와 DST transition을 확인합니다.", "instant sequence와 local projection을 표로 봅니다."], fix: "local recurrence rule+time zone에서 다음 wall time을 resolve하고 gap/overlap policy를 명시한 뒤 instant로 변환합니다.", prevention: "DST spring/fall transition과 zone rule 변경 fixture를 schedule test에 둡니다." },
      ],
    },
    {
      id: "math-random-rounding-range",
      title: "Math.random은 0 이상 1 미만 pseudo-random Number이고 정수 범위 공식은 반열린 구간을 보존합니다",
      lead: "floor/ceil/round를 감으로 바꾸지 말고 각 random interval이 어느 정수 bucket에 mapping되는지 계산합니다.",
      explanations: [
        "Math.random()은 0<=r<1의 Number를 반환합니다. inclusive integer min..max를 만들려면 span=max-min+1, `floor(r*span)+min`입니다. min/max는 safe integer로 검증하고 min<=max를 요구합니다.",
        "`Math.ceil(r*max)`는 r=0일 때 0을 만들 수 있어 1..max를 보장하지 않습니다. `round`는 edge bucket 폭이 절반이 되어 분포가 불균등합니다. floor 공식의 각 bucket 폭은 이상적으로 같습니다.",
        "Math.random algorithm/seed는 implementation-defined 성격이 있고 재현 가능한 simulation/test seed API가 아닙니다. random function을 주입하거나 목적에 맞는 seeded PRNG library/version을 사용하고 seed/config를 artifact에 남깁니다.",
        "추첨은 단순 random 함수보다 참가자 중복/마감 snapshot/감사 log/공정성/규정과 예측·조작 방지 요구가 중요합니다. security-sensitive token/lottery에는 Math.random을 쓰지 않고 Web Crypto getRandomValues 또는 신뢰 가능한 server service와 rejection sampling을 사용합니다.",
        "getRandomValues raw integer를 modulo span으로 단순 줄이면 source range가 span의 배수가 아닐 때 modulo bias가 생깁니다. 허용 가능한 largest multiple 아래 값만 받아들이는 rejection sampling을 검증된 library로 구현합니다.",
        "Math.floor/ceil/trunc/round는 음수에서 ‘버림’이라는 한국어가 모호합니다. floor는 -Infinity 방향, ceil은 +Infinity, trunc는 0 방향입니다. 금액·표시 rounding은 decimal/domain 규칙을 따릅니다.",
      ],
      concepts: [
        { term: "half-open interval", definition: "한쪽 경계는 포함하고 다른 쪽은 제외하는 구간으로 Math.random은 [0,1)입니다.", detail: ["1은 나오지 않습니다.", "floor bucket 공식의 기반입니다."] },
        { term: "pseudo-random", definition: "algorithm 상태에서 생성되는 난수처럼 보이는 sequence로 보안 예측 저항성과 동일하지 않습니다.", detail: ["Math.random seed를 application이 표준 방식으로 제어하지 못합니다.", "용도별 generator를 고릅니다."] },
        { term: "modulo bias", definition: "균등한 source integer 범위를 나머지 연산으로 더 작은 span에 mapping할 때 bucket 크기가 달라지는 편향입니다.", detail: ["security/random selection에 영향 줍니다.", "rejection sampling을 사용합니다."] },
      ],
      codeExamples: [
        {
          id: "deterministic-random-range",
          title: "주입한 random으로 inclusive 1~10 경계 bucket 검증",
          language: "javascript",
          filename: "random-range.mjs",
          purpose: "실제 random을 기다리지 않고 r=0,0.5,1 직전이 각각 min,중간,max로 mapping되는 공식과 validation을 exact output으로 확인합니다.",
          code: "function randomIntInclusive(min, max, random = Math.random) {\n  if (!Number.isSafeInteger(min) || !Number.isSafeInteger(max) || min > max) {\n    throw new RangeError(\"invalid integer range\");\n  }\n  const value = random();\n  if (!(value >= 0 && value < 1)) throw new RangeError(\"random must be in [0, 1)\");\n  return Math.floor(value * (max - min + 1)) + min;\n}\n\nconst samples = [0, 0.5, 0.999999];\nconst results = samples.map(sample => randomIntInclusive(1, 10, () => sample));\nconsole.log(`samples=${samples.join(',')}`);\nconsole.log(`results=${results.join(',')}`);\nconsole.log(`single=${randomIntInclusive(7, 7, () => 0.25)}`);",
          walkthrough: [
            { lines: "1-4", explanation: "min/max safe integer와 ordered inclusive range를 검증합니다." },
            { lines: "5-7", explanation: "injected random contract [0,1)을 검사하고 span bucket에 floor+min을 적용합니다." },
            { lines: "10-14", explanation: "0/중간/1 직전과 single-value range를 deterministic하게 실행합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser"], command: "node random-range.mjs" },
          output: { value: "samples=0,0.5,0.999999\nresults=1,6,10\nsingle=7", explanation: ["r=0은 min 1, r=0.5는 floor(5)+1=6입니다.", "1은 나오지 않지만 1 직전은 마지막 bucket 10입니다.", "min=max인 range는 어떤 valid r에도 그 값입니다."] },
          experiments: [
            { change: "Math.floor를 Math.round로 바꿉니다.", prediction: "결과 일부는 범위 안이지만 edge bucket 폭이 달라 균등 공식이 아닙니다.", result: "많은 sample frequency test로 edge bias를 관찰합니다." },
            { change: "random이 1을 반환하게 합니다.", prediction: "contract RangeError가 납니다.", result: "dependency fake도 production contract [0,1)을 지켜야 합니다." },
            { change: "range를 -3..3으로 바꿉니다.", prediction: "0은 -3, 0.5는 0, 1 직전은 3입니다.", result: "min offset 공식은 음수에도 적용됩니다." },
          ],
          sourceRefs: ["web-math-source", "ecma-numbers-dates", "webcrypto"],
        },
      ],
      diagnostics: [
        { symptom: "1~10 추첨에서 1과 10이 중간 숫자보다 절반쯤 나온다.", likelyCause: "`Math.round(Math.random()*9)+1`처럼 round를 사용해 양 끝 bucket 폭이 절반입니다.", checks: ["r interval을 결과별로 표로 나눕니다.", "대량 deterministic/통계 sample frequency를 봅니다.", "inclusive span 공식과 비교합니다."], fix: "`Math.floor(r*(max-min+1))+min`을 쓰고 range/input을 검증합니다.", prevention: "r=0/각 bucket boundary/1 직전과 frequency sanity test를 둡니다." },
      ],
    },
    {
      id: "number-conversion-nan-parser",
      title: "Number는 전체 numeric string을 변환하고 parseInt/parseFloat는 허용된 prefix를 읽다가 멈춥니다",
      lead: "세 API 중 ‘더 좋은 것’이 아니라 입력 contract가 전체 숫자인지 prefix token인지로 선택합니다.",
      explanations: [
        "Number(value)는 ECMAScript ToNumber semantics에 따라 boolean·null·string 등을 변환하며 string은 전체 numeric grammar가 맞아야 합니다. whitespace/empty string은 0이 될 수 있어 form parser는 empty를 먼저 분리합니다.",
        "parseInt(string,radix)는 string으로 변환한 뒤 앞 whitespace/sign과 radix에 맞는 integer digit prefix를 읽고 첫 invalid character에서 멈춥니다. digit가 하나도 없으면 NaN입니다. radix를 명시해 intention을 드러냅니다.",
        "parseFloat도 decimal prefix를 읽어 10.457px를 10.457로 만들 수 있습니다. CSS unit parser처럼 prefix+unit을 별도 검증하는 목적에는 쓸 수 있지만 일반 금액/점수 input 전체 검증에는 trailing junk를 거부해야 합니다.",
        "global isNaN은 argument를 Number로 coercion한 뒤 판단해 빈 string 등을 숫자가 아니지 않다고 볼 수 있습니다. Number.isNaN은 actual Number NaN만 true여서 parser 결과 검사에 명확합니다. finite에는 Number.isFinite를 사용합니다.",
        "NaN은 숫자 type의 invalid numeric result이며 자기 자신과 ===가 false입니다. `result === NaN`을 쓰지 않습니다. invalid value가 계산을 통해 전파되므로 boundary에서 reason/path와 함께 막습니다.",
        "Number.isInteger는 1.0과 1을 모두 integer로 보고 binary representation 한계를 따릅니다. safe integer range 밖은 JSON/다른 language와 정확히 교환되지 않을 수 있어 Number.isSafeInteger와 string/BigInt contract를 검토합니다.",
      ],
      concepts: [
        { term: "full conversion versus prefix parse", definition: "입력 전체가 numeric grammar여야 하는 Number와 시작 부분의 valid digit까지만 소비하는 parseInt/parseFloat의 차이입니다.", detail: ["trailing junk 처리에 영향 줍니다.", "input contract로 선택합니다."] },
        { term: "NaN", definition: "Number type 안에서 valid numeric result가 아님을 나타내는 특별한 value입니다.", detail: ["typeof는 number입니다.", "Number.isNaN으로 검사합니다."] },
        { term: "radix", definition: "parseInt가 digit를 해석할 진법 base입니다.", detail: ["2~36 범위가 일반적입니다.", "application code에서 명시합니다."] },
      ],
      codeExamples: [
        {
          id: "number-parse-matrix",
          title: "Number·parseInt·parseFloat 변환 matrix",
          language: "javascript",
          filename: "number-parsers.mjs",
          purpose: "원본 변환 예제를 compact matrix로 재실행해 empty·decimal·trailing/leading junk·hex가 API별로 어떻게 다른지 exact output으로 확인합니다.",
          code: "const show = value => Number.isNaN(value) ? \"NaN\" : String(value);\nconst inputs = [\"\", \" 10 \", \"10.457\", \"10A\", \"A10\", \"0x10\"];\nfor (const input of inputs) {\n  console.log(`${JSON.stringify(input)}:Number=${show(Number(input))},int10=${show(Number.parseInt(input, 10))},float=${show(Number.parseFloat(input))}`);\n}\nconsole.log(`global-isNaN-empty=${isNaN(\"\")}`);\nconsole.log(`number-isNaN-empty=${Number.isNaN(\"\")}`);",
          walkthrough: [
            { lines: "1", explanation: "NaN은 JSON/string comparison에서 특별하므로 stable `NaN` label로 출력합니다." },
            { lines: "2-5", explanation: "여섯 input에서 full Number, radix 10 integer prefix, float prefix를 비교합니다." },
            { lines: "6-7", explanation: "coercing global isNaN과 non-coercing Number.isNaN을 empty string으로 대조합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 modern browser"], command: "node number-parsers.mjs" },
          output: { value: "\"\":Number=0,int10=NaN,float=NaN\n\" 10 \":Number=10,int10=10,float=10\n\"10.457\":Number=10.457,int10=10,float=10.457\n\"10A\":Number=NaN,int10=10,float=10\n\"A10\":Number=NaN,int10=NaN,float=NaN\n\"0x10\":Number=16,int10=0,float=0\nglobal-isNaN-empty=false\nnumber-isNaN-empty=false", explanation: ["Number empty string은 0이라 empty precheck가 필요합니다.", "prefix parser는 10A를 10으로 받아들이고 radix10 parseInt는 0x10을 첫 0까지만 읽습니다.", "Number.isNaN은 string 자체를 coercion하지 않습니다."] },
          experiments: [
            { change: "parseInt radix 10을 생략합니다.", prediction: "일부 prefix 처리 규칙이 의도와 달라질 수 있어 code review에서 base가 불명확합니다.", result: "정수 text contract에서는 radix를 명시합니다." },
            { change: "inputs에 `Infinity`와 `1e3`를 추가합니다.", prediction: "Number/parseFloat는 Infinity/1000을 만들 수 있고 parseInt('1e3',10)는 1입니다.", result: "finite/허용 lexical grammar를 변환 후에도 검사합니다." },
            { change: "Number.isNaN(Number(input))을 출력합니다.", prediction: "empty는 false(0), A10은 true입니다.", result: "변환과 검사 단계를 한 expression에 숨기기보다 reason을 분리합니다." },
          ],
          sourceRefs: ["web-number-source", "ecma-numbers-dates"],
        },
      ],
      diagnostics: [
        { symptom: "사용자가 10원이라고 입력했는데 parseInt가 10으로 받아 결제가 진행된다.", likelyCause: "전체 금액 grammar를 요구하면서 prefix parser를 사용해 trailing text를 묵인했습니다.", checks: ["raw/trimmed input과 parser consumption을 기록합니다.", "허용 currency/decimal grammar를 명시합니다.", "Number와 parseInt result를 비교합니다."], fix: "locale-independent canonical input은 전체 grammar/schema로 검증하고 UI localized money는 전용 parser/서버 재검증을 사용합니다.", prevention: "trailing unit/junk/exponent/separator/empty/overflow negative fixture를 둡니다." },
      ],
    },
    {
      id: "number-precision-money-bigint",
      title: "Number 연산은 binary64 정밀도와 safe integer 경계를 가지므로 domain 오차 허용을 정합니다",
      lead: "화면 rounding과 저장/정산 exactness를 같은 Math.floor 한 줄로 처리하지 않습니다.",
      explanations: [
        "Number는 binary floating-point라 0.1 같은 decimal fraction을 정확히 나타내지 못해 `0.1+0.2`가 0.3과 strict equal이 아닐 수 있습니다. 측정값 비교에는 tolerance를 요구에 맞게 쓰고 금액은 smallest integer unit 또는 decimal library를 고려합니다.",
        "Number.MAX_SAFE_INTEGER 범위 밖 integer는 인접 integer를 구분하지 못할 수 있습니다. database bigint/id를 JSON number로 보내지 않고 decimal string 또는 negotiated BigInt serialization을 사용합니다.",
        "BigInt는 arbitrary-size integer이지만 Number와 arithmetic에 자동 혼합되지 않고 fraction이 없으며 JSON.stringify 기본 처리가 실패합니다. API/schema/storage 전체가 BigInt/string contract를 이해해야 합니다.",
        "원본 `Math.floor(s1/s2*10)/10`은 양수에서 소수 첫째 자리 아래를 내림하지만 음수에서는 -Infinity 방향이고 display rounding/financial rounding과 다릅니다. Intl.NumberFormat은 표시를 담당하되 exact business rounding policy를 별도 구현합니다.",
        "-0은 일부 계산에서 나타나며 String에서는 0처럼 보일 수 있습니다. Object.is(value,-0), reciprocal 등에서 차이가 있습니다. 대부분 UI에서는 normalize할 수 있지만 scientific/domain semantics를 확인합니다.",
        "overflow/underflow/Infinity/NaN을 boundary에서 검증하고 계산 중 intermediate도 finite인지 확인합니다. user input validation만으로 division by zero와 algorithm overflow가 모두 해결되지는 않습니다.",
      ],
      concepts: [
        { term: "binary64", definition: "ECMAScript Number가 주로 따르는 IEEE 754 double-precision binary floating-point representation입니다.", detail: ["일부 decimal을 근사합니다.", "NaN/Infinity/signed zero를 포함합니다."] },
        { term: "safe integer", definition: "Number가 정확히 표현하고 비교할 수 있다고 보장되는 integer 범위 안의 값입니다.", detail: ["Number.isSafeInteger로 검사합니다.", "큰 ID는 string을 고려합니다."] },
        { term: "smallest currency unit", definition: "원/센트처럼 금액을 fractional decimal 대신 정수 최소 단위로 저장·연산하는 model입니다.", detail: ["currency별 소수 자릿수가 다릅니다.", "세금/환율 rounding policy가 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "0.1+0.2 합계 검증이 0.3과 다르거나 누적 금액이 1원씩 어긋난다.", likelyCause: "binary64 근사 값을 exact decimal money처럼 비교·누적했습니다.", checks: ["raw IEEE Number 연산과 표시 rounding을 구분합니다.", "currency minor unit/rounding rule을 확인합니다.", "입력·중간·저장 type을 inventory합니다."], fix: "금액을 검증된 decimal 또는 smallest-unit integer로 모델링하고 단계별 rounding policy를 하나의 domain module에 둡니다.", prevention: "0.1/0.2, halfway, negative, tax/discount order와 large total golden test를 둡니다." },
      ],
    },
    {
      id: "string-immutable-unicode-methods",
      title: "String은 immutable UTF-16 code-unit sequence이며 사용자가 보는 글자 수는 별도 segmentation 문제입니다",
      lead: "length와 charAt index가 언제 code unit을 세고 emoji·결합문자를 쪼개는지 이해합니다.",
      explanations: [
        "ECMAScript String value는 UTF-16 code unit sequence입니다. length, charAt, index 접근과 slice index는 code unit 기준입니다. BMP 밖 code point는 surrogate pair 두 unit을 써 length가 사용자 글자 수보다 큽니다.",
        "for...of와 spread는 string iterator를 통해 code point 단위로 순회하지만 skin-tone/ZWJ/combining mark로 구성된 grapheme cluster 하나가 여러 code point일 수 있습니다. UI 글자 제한/커서는 Intl.Segmenter 등 locale-aware grapheme segmentation을 검토합니다.",
        "String은 immutable이라 replace/trim/toUpperCase/slice가 원본을 바꾸지 않고 새 string을 반환합니다. 원본의 `str1.replace(...)`와 `str1.split(',')`만 호출하고 결과를 저장하지 않으면 str1은 그대로입니다.",
        "indexOf/includes/startsWith/endsWith는 case/Unicode normalization/locale 요구를 자동 해결하지 않습니다. 사용자 검색은 locale, case folding, normalization, accent 정책을 명시하고 Intl.Collator를 검토합니다.",
        "slice(begin,end)는 음수 index를 지원하고 substring은 argument handling이 다르며 deprecated substr는 새 code에서 피합니다. begin inclusive/end exclusive를 test합니다.",
        "split은 separator를 제거한 array를 반환하며 comma 뒤 whitespace가 element에 남습니다. map(item=>item.trim()).filter(Boolean) 같은 normalization이 필요하지만 meaningful empty field를 제거해도 되는지 schema를 봅니다.",
        "replace string pattern은 첫 match만 바꾸고 replaceAll 또는 global RegExp는 여러 match를 처리합니다. replacement string의 `$&` 등 special pattern과 untrusted regex ReDoS/escaping을 고려합니다.",
      ],
      concepts: [
        { term: "UTF-16 code unit", definition: "ECMAScript String의 length/index 기본 단위인 16-bit 값입니다.", detail: ["한 Unicode code point가 두 unit일 수 있습니다.", "surrogate를 반으로 자르지 않게 합니다."] },
        { term: "code point", definition: "Unicode character set의 scalar/assigned value 단위로 string iterator가 surrogate pair를 결합해 순회합니다.", detail: ["grapheme와 다릅니다.", "emoji modifier가 별도 code point일 수 있습니다."] },
        { term: "grapheme cluster", definition: "사용자가 하나의 글자로 인식하는 Unicode code point sequence입니다.", detail: ["Intl.Segmenter로 나눌 수 있습니다.", "locale/Unicode version 영향을 받습니다."] },
      ],
      codeExamples: [
        {
          id: "string-immutable-unicode",
          title: "치환·분할 원본 불변성과 code unit/code point/grapheme 수 비교",
          language: "javascript",
          filename: "string-unicode.mjs",
          purpose: "원본 String 예제를 Unicode-aware pipeline으로 확장해 method return 저장과 emoji length 단위 차이를 exact output으로 확인합니다.",
          code: "const source = \" Apple, Banana, Kiwi \";\nconst replaced = source.replace(\"Banana\", \"Mango\");\nconst items = source.trim().split(\",\").map(item => item.trim());\nconst emoji = \"👍🏽\";\nconst graphemes = [...new Intl.Segmenter(\"ko\", { granularity:\"grapheme\" }).segment(emoji)];\n\nconsole.log(`source=${JSON.stringify(source)}`);\nconsole.log(`replaced=${JSON.stringify(replaced)}`);\nconsole.log(`items=${items.join('|')}`);\nconsole.log(`source-has-banana=${source.includes(\"Banana\")}`);\nconsole.log(`code-units=${emoji.length}`);\nconsole.log(`code-points=${[...emoji].length}`);\nconsole.log(`graphemes=${graphemes.length}`);",
          walkthrough: [
            { lines: "1-3", explanation: "replace 결과와 trim/split/map normalization을 새 binding에 저장합니다." },
            { lines: "4-5", explanation: "thumbs-up+skin tone sequence를 code point iterator와 grapheme segmenter로 준비합니다." },
            { lines: "7-13", explanation: "원본/새 결과와 code unit·point·grapheme 수를 stable output으로 비교합니다." },
          ],
          run: { environment: ["Node.js 22+ 또는 Intl.Segmenter를 지원하는 modern browser"], command: "node string-unicode.mjs" },
          output: { value: "source=\" Apple, Banana, Kiwi \"\nreplaced=\" Apple, Mango, Kiwi \"\nitems=Apple|Banana|Kiwi\nsource-has-banana=true\ncode-units=4\ncode-points=2\ngraphemes=1", explanation: ["replace는 새 string을 만들고 source에는 Banana가 남습니다.", "👍와 skin-tone modifier는 각각 surrogate pair라 4 code units, 2 code points입니다.", "사용자는 두 code point 조합을 grapheme 하나로 인식합니다."] },
          experiments: [
            { change: "replace result를 저장하지 않고 source.replace만 호출합니다.", prediction: "source output은 변하지 않습니다.", result: "immutable method return을 사용해야 합니다." },
            { change: "emoji를 가족 ZWJ emoji로 바꿉니다.", prediction: "code unit/point 수는 더 커져도 grapheme는 보통 1입니다.", result: "UI length 제한을 code unit에 두지 않습니다." },
            { change: "split 뒤 trim map을 제거합니다.", prediction: "둘째/셋째 item 앞에 whitespace가 남습니다.", result: "delimiter와 surrounding whitespace grammar를 명시합니다." },
          ],
          sourceRefs: ["web-string-source", "ecma-text-processing", "ecma-intl"],
        },
      ],
      diagnostics: [
        { symptom: "닉네임 최대 2글자인데 emoji 하나가 length 4라 거부된다.", likelyCause: "사용자-visible grapheme 요구에 UTF-16 code unit length를 사용했습니다.", checks: ["code unit/code point/grapheme count를 비교합니다.", "server/database limit 단위(byte/code point/grapheme)를 확인합니다.", "Unicode/locale policy를 정합니다."], fix: "UI 글자 요구는 Intl.Segmenter 기반 grapheme를 사용하고 storage byte/index limit과 별도로 검증합니다.", prevention: "한글 jamo/combining accent/skin tone/ZWJ flag emoji corpus를 client/server contract test합니다." },
      ],
    },
    {
      id: "window-location-url-popup-security",
      title: "Window·Location·URL은 browser navigation capability이므로 user activation·origin·opener·failure를 처리합니다",
      lead: "window.open은 단순 새 객체 생성이 아니라 popup policy와 browsing context/security를 건드립니다.",
      explanations: [
        "window는 current browsing context의 WindowProxy/global host interface를 노출하고 location은 current document URL/navigation과 연결됩니다. Node pure module에서 직접 사용하지 않고 browser adapter를 둡니다.",
        "window.open(url,target,features)는 새/기존 browsing context를 요청하지만 popup blocker와 user preference에 의해 null을 반환할 수 있습니다. 원본처럼 click handler의 직접 user activation 안에서 호출하고 null state에 fallback 안내를 제공합니다.",
        "새 window가 opener를 통해 원본 Window에 접근/이동시키는 위험을 줄이기 위해 noopener 관계와 COOP 등 정책을 검토합니다. untrusted URL을 target/features string에 직접 넣지 않고 허용 origin/path를 URL API로 검증합니다.",
        "same-origin policy 때문에 cross-origin Window의 DOM/location 세부 접근은 제한됩니다. postMessage를 사용할 경우 exact targetOrigin과 message schema/source/origin을 검증합니다. `*`를 secret data에 쓰지 않습니다.",
        "Location assign/replace/reload와 href setting은 navigation/history semantics가 다릅니다. router/API가 있다면 direct reload와 history state를 구분하고 open redirect가 되지 않게 destination allowlist를 둡니다.",
        "URL constructor는 base와 relative URL을 표준 parse해 protocol/origin/path/searchParams/hash를 제공합니다. string startsWith로 origin을 검사하면 username/confusable/subdomain/encoding을 놓칠 수 있어 parsed URL의 protocol/origin/host를 exact compare합니다.",
        "popup window dimensions/position은 user agent가 무시/제한할 수 있고 mobile에서는 tab/full-screen이 될 수 있습니다. 중요한 content/task를 popup에만 의존하지 않고 same-page dialog/route와 progressive fallback을 제공합니다.",
      ],
      concepts: [
        { term: "user activation", definition: "사용자 입력으로부터 온 transient/sticky activation state로 popup·clipboard 등 일부 powerful feature 허용에 사용됩니다.", detail: ["async delay 뒤 소실될 수 있습니다.", "synthetic click과 같지 않습니다."] },
        { term: "WindowProxy/opener", definition: "browsing context의 window를 참조하는 proxy와 새 context가 연 원본 context를 가리킬 수 있는 관계입니다.", detail: ["cross-origin access가 제한됩니다.", "noopener/COOP를 검토합니다."] },
        { term: "URL parser", definition: "base/relative input을 URL Standard algorithm으로 구조화해 protocol·origin·host·path·query·fragment를 제공하는 API입니다.", detail: ["문자열 이어붙이기보다 안전합니다.", "허용 origin/scheme을 검증합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "window.open 반환값이 null인데 다음 줄에서 focus를 호출해 TypeError가 난다.", likelyCause: "popup blocker/user preference가 새 context를 허용하지 않았는데 성공을 가정했습니다.", checks: ["호출이 trusted user activation 안인지 봅니다.", "return이 null인지 기록합니다.", "browser popup setting과 async delay를 확인합니다."], fix: "return null을 expected state로 처리해 same-tab link/inline notice fallback을 제공하고 essential task를 popup에만 두지 않습니다.", prevention: "allowed/blocked/mobile/new-tab preference E2E와 keyboard activation test를 둡니다." },
        { symptom: "`https://trusted.example.evil.test`가 startsWith 검사에 통과해 redirect된다.", likelyCause: "raw URL prefix string으로 origin을 검증했습니다.", checks: ["new URL로 protocol/origin/hostname을 출력합니다.", "userinfo/port/punycode/relative/backslash case를 test합니다.", "허용 destination scope를 정의합니다."], fix: "URL parser 뒤 exact allowlisted protocol+origin/route를 비교하고 server도 redirect target을 재검증합니다.", prevention: "open-redirect adversarial URL corpus와 server/client parity test를 둡니다." },
      ],
      expertNotes: [
        "Date/Intl output은 host time-zone database와 locale data update에 영향을 받을 수 있습니다. exact business data와 localized presentation snapshot을 분리하고 environment version을 기록합니다.",
        "random statistical quality와 fairness는 세 sample output으로 증명되지 않습니다. generator selection, entropy/source, audit/threat model과 statistical validation을 별도 전문가 절차로 다룹니다.",
        "Unicode normalization(NFC/NFD)과 locale collation은 security identifier equality와 사용자 search에서 서로 다른 정책이 필요합니다. display name과 account ID를 같은 comparison으로 처리하지 않습니다.",
      ],
    },
  ],
  lab: {
    title: "연속 독서·추첨·숫자 입력·문자열 목록·공지 popup을 검증 가능한 utility layer로 재구축하기",
    scenario: "현재 code는 current Date와 local parse를 직접 사용하고 Math.random을 test할 수 없으며 Number/parseInt를 섞습니다. String return을 버리고 popup 성공·URL을 신뢰해 zone/DST·NaN·Unicode·popup blocker에서 오작동합니다.",
    setup: [
      "원본 Date/Math/Number/Window/String file 5개를 read-only evidence로 준비합니다.",
      "Node.js 22+와 browser, UTC/KST/미주 DST time zone, fixed clock/random/openWindow fake를 준비합니다.",
      "empty/partial/exponent/hex/Infinity/safe-boundary numeric과 combining/emoji/ZWJ string fixture를 준비합니다.",
      "popup allowed/blocked, trusted/untrusted URL와 user activation/async-delay scenario를 준비합니다.",
    ],
    steps: [
      "각 API를 ECMAScript built-in/Intl/browser host로 분류하고 runtime adapter boundary를 표시합니다.",
      "Date input은 ISO+offset/UTC instant로 parse하고 invalid를 검사하며 elapsed duration과 local calendar streak를 분리합니다.",
      "now/locale/timeZone을 주입해 UTC exact output과 localized presentation을 별도 test합니다.",
      "inclusive random integer function에 random dependency와 range validation을 넣고 boundary/frequency/security 용도를 분리합니다.",
      "Number/parseInt/parseFloat matrix에서 accepted lexical grammar를 정하고 empty·NaN·finite·range·safe integer를 검증합니다.",
      "String transform return을 새 binding에 저장하고 code unit/code point/grapheme와 normalization/search policy를 test합니다.",
      "new URL로 popup destination을 allowlist하고 click user activation 안에서 open 후 null/noopener/fallback을 처리합니다.",
      "utility마다 exact command/output, user error, sanitized telemetry와 cross-zone/runtime regression matrix를 문서화합니다.",
    ],
    expectedResult: [
      "고정 instant/UTC elapsed output은 host zone과 무관하고 local calendar requirement는 zone/DST policy를 가집니다.",
      "random boundary는 min/max에 정확히 mapping되고 test는 실제 random을 기다리지 않으며 security 용도는 Math.random과 분리됩니다.",
      "모든 numeric input은 parser 선택 근거와 empty/trailing/NaN/finite/range/safe 결과를 가집니다.",
      "String source는 immutable하게 보존되고 Unicode visible length와 storage/code-unit length가 구분됩니다.",
      "popup blocked/untrusted URL/cross-origin을 expected state로 처리하고 essential notice fallback이 있습니다.",
      "current time/random/locale/window global이 pure domain function에 직접 숨어 있지 않습니다.",
    ],
    cleanup: ["실험 popup을 닫고 fake clock/random/locale override와 debug output을 reset합니다.", "prompt/alert/document.write, non-standard date string과 actual secret/user URL fixture를 production code에서 제거합니다."],
    extensions: ["Temporal 지원/폴리필이 target에 적합한지 Date+time-zone library와 비교하는 ADR을 작성합니다.", "Web Crypto rejection sampling과 server-audited draw protocol을 별도 security lab에서 검증합니다.", "Intl.Collator/NumberFormat/DateTimeFormat/Segmenter를 locale matrix와 golden semantic test로 확장합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "고정 Date·random sample·Number parser·String transform 예제의 모든 output을 먼저 계산하고 실행하세요.", requirements: ["UTC/local accessor와 month index를 비교합니다.", "r=0/0.5/1직전 range 결과를 계산합니다.", "Number/parseInt/parseFloat input matrix를 작성합니다.", "replace/split return과 Unicode 세 길이를 출력합니다."], hints: ["현재 시간/실제 난수를 exact test에 쓰지 않습니다.", "String method return을 새 binding에 저장합니다."], expectedOutcome: "각 built-in의 input/output/단위와 coercion을 설명하고 exact output이 일치합니다.", solutionOutline: ["API별 accepted input·unit·return/error 표를 만듭니다.", "edge value를 dependency로 주입합니다."] },
    { difficulty: "응용", prompt: "독서 streak와 추첨 form을 time-zone-aware하고 test 가능하게 재작성하세요.", requirements: ["instant/local date와 elapsed/calendar day를 구분합니다.", "invalid/미래 날짜/DST를 처리합니다.", "응모자 수는 empty/full integer/range로 검증합니다.", "random dependency와 inclusive formula를 사용합니다.", "DOM에는 textContent로 성공/오류 state를 렌더링합니다."], hints: ["86,400,000ms와 local 하루가 항상 같지 않습니다.", "Number 전에 empty를 검사합니다."], expectedOutcome: "zone과 random에 관계없이 deterministic test가 있고 사용자 입력 오류가 이유별로 보입니다.", solutionOutline: ["parse→domain calculation→format/render adapter를 나눕니다.", "clock/random을 parameter로 받습니다."] },
    { difficulty: "설계", prompt: "browser utility library의 date/number/text/navigation contract를 설계하세요.", requirements: ["ECMAScript/Intl/host boundary와 supported environment를 정의합니다.", "ISO/zone/calendar, numeric grammar/precision/money, Unicode segmentation/normalization 정책을 정합니다.", "popup/URL/origin/user activation/noopener/fallback security를 포함합니다.", "dependency injection과 exact/locale-sensitive test를 분리합니다.", "error/redaction/telemetry/browser/runtime update matrix를 설계합니다."], hints: ["localized display string을 data format으로 재사용하지 않습니다.", "Math.random과 cryptographic randomness를 용도별로 분리합니다."], expectedOutcome: "여러 page가 같은 경계 규칙을 재사용하고 zone·locale·Unicode·popup policy 변화에 회귀하지 않는 implementation-ready specification이 완성됩니다.", solutionOutline: ["domain type과 adapter를 먼저 분리합니다.", "각 API의 failure/limit/owner를 표로 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "Date는 time zone을 내부에 저장하나요?", answer: "Date time value는 epoch milliseconds instant이며 local/UTC accessor와 formatter가 zone 기준 field로 투영합니다." },
    { question: "getMonth는 1~12를 반환하나요?", answer: "아닙니다. 0~11이며 표시에는 Intl 사용을 우선합니다." },
    { question: "연속 local 날짜 수와 milliseconds/86400000은 항상 같나요?", answer: "아닙니다. DST 등으로 local 하루가 23/25시간일 수 있어 calendar와 duration 요구를 구분합니다." },
    { question: "Math.random은 1을 반환할 수 있나요?", answer: "표준 범위는 0 이상 1 미만입니다." },
    { question: "inclusive min~max 정수 공식은 무엇인가요?", answer: "`Math.floor(r*(max-min+1))+min`이며 min/max/range를 검증합니다." },
    { question: "Math.random을 password/token/공정 추첨에 써도 되나요?", answer: "아닙니다. 보안/감사 요구에는 Web Crypto나 검증된 server protocol을 사용합니다." },
    { question: "Number와 parseInt의 핵심 차이는 무엇인가요?", answer: "Number는 전체 numeric string 변환을 요구하고 parseInt는 radix에 맞는 integer prefix를 읽다가 invalid 문자에서 멈춥니다." },
    { question: "NaN을 `value===NaN`으로 확인할 수 있나요?", answer: "아닙니다. Number.isNaN을 사용합니다." },
    { question: "0.1+0.2가 정확히 0.3이 아닐 수 있는 이유는 무엇인가요?", answer: "Number가 binary64라 일부 decimal fraction을 근사하기 때문입니다." },
    { question: "String replace가 원본을 바꾸나요?", answer: "아닙니다. 새 string을 반환하므로 결과를 저장해야 합니다." },
    { question: "string.length는 사용자가 보는 글자 수인가요?", answer: "UTF-16 code unit 수이며 code point/grapheme 수와 다를 수 있습니다." },
    { question: "window.open은 항상 Window reference를 반환하나요?", answer: "아닙니다. popup policy 등으로 null일 수 있어 fallback을 처리합니다." },
  ],
  completionChecklist: [
    "ECMAScript built-in/Intl과 browser Window host API를 구분했다.",
    "primitive conversion과 new wrapper object의 truthiness/identity 차이를 확인했다.",
    "Date epoch ms·ISO offset·UTC/local accessor·invalid date를 정확히 처리했다.",
    "elapsed duration과 local calendar day/DST recurrence를 분리했다.",
    "Intl formatter에 locale/timeZone을 명시하고 localized output을 data로 재파싱하지 않았다.",
    "Math.random [0,1)와 inclusive range bucket을 deterministic random으로 test했다.",
    "security random과 seeded reproducibility/fair draw를 Math.random에서 분리했다.",
    "Number/parseInt/parseFloat와 empty·NaN·finite·integer·safe range를 구분했다.",
    "binary64 money/precision/BigInt/JSON contract를 domain 요구에 맞췄다.",
    "String return 불변성, slice/replace/split/trim과 Unicode unit/point/grapheme를 확인했다.",
    "URL parser·allowlisted origin과 popup user activation/null/noopener/fallback을 처리했다.",
    "clock/random/locale/window dependency를 주입해 exact regression test를 만들었다.",
  ],
  nextSessions: ["js-05-dom-query-traversal"],
  sources: [
    { id: "web-date-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex06_object.html", usedFor: ["current/specific Date", "getTime difference", "milliseconds to days", "book streak", "Date object categories"], evidence: "today와 2026-02-16의 millisecond 차이를 floor day로 표시하는 전체 흐름을 instant/calendar/DST·fixed clock test로 확장했습니다." },
    { id: "web-math-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex07_object.html", usedFor: ["Math floor/ceil/round", "Math.random", "prompt Number", "1..su winner", "NaN validation"], evidence: "응모자 수 prompt와 `floor(random*su)+1`을 inclusive bucket·dependency injection·security/fairness boundary의 실제 근거로 사용했습니다." },
    { id: "web-number-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex08_object.html", usedFor: ["number/string arithmetic coercion", "Number versus parseInt/parseFloat", "NaN cases", "decimal truncation", "boolean conversion"], evidence: "원본 전체 conversion matrix를 exact compact matrix로 재검증하고 empty/radix/finite/safe/money policy까지 확장했습니다." },
    { id: "web-window-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex09_object.html", usedFor: ["click window.open", "relative notice URL", "window name/features", "popup size/position"], evidence: "공지 popup을 user activation·null blocker·URL allowlist·opener/same-origin·fallback navigation 사례로 보강했습니다." },
    { id: "web-string-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex12_object.html", usedFor: ["primitive/wrapper String", "length/charAt/indexOf", "slice/substring/substr", "replace immutability", "split/trim/map"], evidence: "Hello/Apple-Banana-Kiwi의 원본 불변성/검색·추출·분할 예제를 UTF-16/code point/grapheme·Intl/normalization까지 확장했습니다." },
    { id: "ecma-numbers-dates", repository: "TC39 ECMAScript Language Specification", path: "multipage/numbers-and-dates.html", publicUrl: "https://tc39.es/ecma262/multipage/numbers-and-dates.html", usedFor: ["Number/Math/Date built-ins", "random range", "NaN/finite/integer", "Date time value/parse/accessor", "rounding"], evidence: "Number·Math·Date의 current specification algorithm과 property를 numeric/date exact examples의 기준으로 사용했습니다." },
    { id: "ecma-text-processing", repository: "TC39 ECMAScript Language Specification", path: "multipage/text-processing.html", publicUrl: "https://tc39.es/ecma262/multipage/text-processing.html", usedFor: ["String UTF-16 model", "length/index/iterator", "search/slice/replace/split/trim", "Unicode code point"], evidence: "String immutability와 code-unit method semantics를 Unicode example의 표준 기준으로 사용했습니다." },
    { id: "ecma-intl", repository: "TC39 ECMAScript Internationalization API Specification", path: "ecma402/", publicUrl: "https://tc39.es/ecma402/", usedFor: ["DateTimeFormat", "NumberFormat", "Collator", "Segmenter", "locale/timeZone options"], evidence: "localized presentation과 grapheme segmentation을 canonical data/logic에서 분리하는 공식 Intl 기준으로 사용했습니다." },
    { id: "html-window-open", repository: "WHATWG HTML Standard", path: "multipage/nav-history-apis.html#dom-open", publicUrl: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-open", usedFor: ["window.open", "target/features", "popup/blocking", "WindowProxy", "opener/navigation"], evidence: "원본 popup의 success/null/context/opener contract를 browser standard에 맞춰 설명했습니다." },
    { id: "url-standard", repository: "WHATWG URL Standard", path: "URL", publicUrl: "https://url.spec.whatwg.org/", usedFor: ["URL constructor/parser", "origin/host/path/query", "relative base", "allowlist/security"], evidence: "raw string destination 검사 대신 parsed URL component로 navigation을 검증하는 기준으로 사용했습니다." },
    { id: "webcrypto", repository: "W3C Web Cryptography", path: "TR/webcrypto/", publicUrl: "https://www.w3.org/TR/webcrypto/", usedFor: ["crypto.getRandomValues", "security randomness", "integer sampling foundation", "browser powerful API"], evidence: "Math.random을 security/fairness-sensitive randomness에서 분리하는 Web Crypto source로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 5,
    filesUsed: 5,
    uncoveredNotes: [
      "원본 5개는 Date elapsed day, correct inclusive random formula, 풍부한 Number/parser matrix, popup과 String immutable method를 직접 제공합니다. UTC/local/DST·Intl·safe integer/money·Unicode grapheme·popup/origin security는 TC39/WHATWG/W3C 표준으로 보강했습니다.",
      "DOM tree 조회/조작은 js-05/06, timer scheduling precision은 js-08, network URL/CORS는 js-10에서 built-in/host 경계를 다시 연결합니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 360;
expertSession.chapters.push(
  {
    id: "map-set-weak-collections-intl-segmentation",
    title: "Object·Map·Set·WeakMap과 Unicode segmentation을 데이터 계약에 맞춰 선택합니다",
    lead: "built-in은 편의 함수 목록이 아니라 값 semantics와 자료구조 계약입니다. key 종류·중복·순서·열거·lifetime을 먼저 정하고 Object, Map, Set, WeakMap을 선택하며 사용자가 보는 문자열 단위는 code unit이 아니라 locale-aware grapheme·word일 수 있음을 연결합니다.",
    explanations: [
      "Object property key는 string 또는 symbol이며 일반 record와 JSON shape에 자연스럽습니다. Map은 모든 ECMAScript 값을 key로 사용할 수 있고 명시적 size·has·get·set·entries API와 insertion order iteration을 제공합니다. prototype 상속이나 `__proto__` 같은 이름과 섞이지 않는 dictionary가 필요하면 Map 또는 Object.create(null)을 검토합니다.",
      "Map key 비교는 SameValueZero 계열 semantics를 사용해 NaN key를 다시 찾을 수 있고 +0/-0을 같은 key로 취급합니다. object key는 내용이 같은지가 아니라 identity가 같아야 합니다. `{id:1}` 두 객체는 서로 다른 key이므로 domain id string을 key로 쓸지 실제 instance metadata를 key로 쓸지 정합니다.",
      "Set은 중복 없는 membership과 insertion order iteration을 제공합니다. 배열 중복 제거에는 `[...new Set(values)]`가 간단하지만 무엇이 같은 값인지 SameValueZero 기준이며 object 내용 중복은 제거하지 않습니다. case-insensitive string이나 domain composite key는 먼저 canonicalize하거나 Map으로 key를 구성합니다.",
      "WeakMap·WeakSet은 object/symbol key를 약하게 보유해 metadata 때문에 key lifetime이 늘지 않도록 하지만 열거·size를 제공하지 않습니다. cache hit/miss를 정확히 count하거나 직렬화해야 하면 명시 cleanup Map이 더 적합할 수 있습니다. GC timing을 business logic으로 사용하지 않습니다.",
      "Map과 Set의 평균 접근 성능은 specification이 구현 전략을 고정하지 않으므로 무조건 O(1)이라고 계약하지 않습니다. 배열 linear scan과 실제 workload를 profile하고 memory overhead·iteration·key construction 비용까지 봅니다. 작은 정적 목록은 배열이 더 단순할 수 있습니다.",
      "JavaScript String.length와 index는 UTF-16 code unit 기준입니다. `Array.from`·spread는 code point 단위로 개선하지만 ZWJ emoji·combining mark 하나의 사용자 인식 문자가 여러 code point일 수 있습니다. `Intl.Segmenter`의 grapheme·word·sentence granularity로 locale-sensitive UI 커서·문자 수·검색 token 경계를 만듭니다.",
      "locale formatting 결과 문자열을 다시 parse해 business 값으로 쓰지 않습니다. Intl.NumberFormat·DateTimeFormat은 표시 계층이며 저장·계산은 원래 number·instant·currency minor unit을 유지합니다. snapshot test는 실행 환경 ICU·locale data version이 바뀔 수 있으므로 지원 runtime을 고정하거나 핵심 parts를 검증합니다.",
    ],
    concepts: [
      { term: "SameValueZero", definition: "Set membership과 Map key에서 사용되는 값 동일성 계열로 NaN을 자기 자신과 같게 보고 +0과 -0을 같은 값으로 취급합니다.", detail: ["object는 identity를 비교합니다.", "domain 내용 동등성은 canonical key가 필요합니다."] },
      { term: "weak collection", definition: "key를 강하게 유지하지 않아 다른 strong reference가 사라질 때 key 회수를 방해하지 않는 WeakMap·WeakSet입니다.", detail: ["열거와 size가 없습니다.", "explicit resource cleanup을 대신하지 않습니다."] },
      { term: "grapheme cluster", definition: "사용자가 한 문자로 인식하는 Unicode code point의 묶음입니다.", detail: ["emoji ZWJ sequence와 combining mark가 포함될 수 있습니다.", "Intl.Segmenter로 locale-aware boundary를 얻습니다."] },
    ],
    codeExamples: [
      {
        id: "map-set-intl-segmenter-contract",
        title: "Map·Set 순서와 사용자 인식 문자 segmentation",
        language: "javascript",
        filename: "collections-segmenter.mjs",
        purpose: "keyed collection의 insertion order·중복 제거와 Intl.Segmenter의 grapheme 단위를 Node에서 exact 출력으로 검증합니다.",
        code: "const visits = new Map([['Ada', 2], ['Linus', 1]]);\nvisits.set('Ada', visits.get('Ada') + 1);\nvisits.set('Grace', 1);\n\nconst topics = new Set(['JS', 'DOM', 'JS', 'CSS']);\nconst segmenter = new Intl.Segmenter('ko', { granularity: 'grapheme' });\nconst graphemes = [...segmenter.segment('A👩‍💻한')].map((part) => part.segment);\n\nconsole.log(JSON.stringify([...visits]));\nconsole.log(JSON.stringify([...topics]));\nconsole.log(JSON.stringify(graphemes));",
        walkthrough: [
          { lines: "1-3", explanation: "기존 Ada key의 값을 갱신해도 원래 insertion 위치는 유지하고 새 Grace key를 끝에 추가합니다." },
          { lines: "5-7", explanation: "Set은 중복 JS를 제거하고 Segmenter는 ZWJ emoji를 사용자 인식 grapheme 하나로 나눕니다." },
          { lines: "9-11", explanation: "Map entries, Set values, grapheme 배열을 JSON으로 고정해 순서와 단위를 검증합니다." },
        ],
        run: { environment: ["Node.js 18 이상과 Intl.Segmenter 지원", "collections-segmenter.mjs를 UTF-8로 저장"], command: "node collections-segmenter.mjs" },
        output: { value: "[[\"Ada\",3],[\"Linus\",1],[\"Grace\",1]]\n[\"JS\",\"DOM\",\"CSS\"]\n[\"A\",\"👩‍💻\",\"한\"]", explanation: ["Map update는 Ada의 위치를 옮기지 않습니다.", "Set은 첫 등장 순서를 유지하며 중복 JS 하나를 제거합니다.", "👩‍💻는 여러 code point지만 grapheme 하나입니다."] },
        experiments: [
          { change: "Map key를 매번 새 `{name:'Ada'}` object로 바꿉니다.", prediction: "내용이 같아 보여도 object identity가 달라 별도 entries가 생깁니다.", result: "instance metadata와 domain value key를 구분해야 함을 확인합니다." },
          { change: "graphemes 대신 `[...'A👩‍💻한']`을 출력합니다.", prediction: "ZWJ와 emoji 구성 code point가 여러 항목으로 분리됩니다.", result: "code point iteration도 사용자 인식 문자 경계를 보장하지 않음을 확인합니다." },
        ],
        sourceRefs: ["ecma-keyed-collections-04", "ecma-data-structures-04", "ecma-intl"],
      },
    ],
    diagnostics: [
      { symptom: "같은 id를 가진 object를 Map에서 조회했는데 undefined다.", likelyCause: "조회 때 새 object literal을 만들어 저장 당시 key와 identity가 다릅니다.", checks: ["set과 get에 사용한 key의 `===` 결과를 확인합니다.", "domain id와 instance identity 중 무엇이 key 계약인지 정합니다.", "직렬화·복원 뒤 object identity가 바뀌는지 봅니다."], fix: "value identity가 기준이면 안정적인 primitive id를 canonical key로 쓰고 instance metadata만 object key를 사용합니다.", prevention: "key 생성 함수를 중앙화하고 같은 내용/다른 identity fixture를 테스트합니다." },
      { symptom: "문자 제한 3자를 통과한 emoji 문자열이 UI에서 잘린다.", likelyCause: "String.length의 UTF-16 code unit 수를 사용자 인식 grapheme 수로 오해했습니다.", checks: ["length·spread·Intl.Segmenter 결과를 비교합니다.", "ZWJ emoji와 combining mark fixture를 넣습니다.", "server와 client가 같은 길이 정책인지 확인합니다."], fix: "제품의 문자 단위를 명시하고 grapheme 기준이면 Intl.Segmenter 또는 합의된 Unicode library를 사용합니다.", prevention: "ASCII·한글·emoji·combining sequence 경계를 공유 validation test에 포함합니다." },
    ],
    expertNotes: ["Object.groupBy와 Map.groupBy 같은 최신 built-in은 지원 runtime matrix를 확인하고 fallback을 결정한 뒤 사용합니다.", "정렬·locale 비교에는 Intl.Collator를 재사용할 수 있지만 locale option과 sensitivity가 domain 동등성인지 표시 순서인지 구분합니다."],
  },
  {
    id: "url-origin-popup-capability-security",
    title: "URL parsing·origin allowlist·popup capability를 문자열 연결과 분리합니다",
    lead: "window·location·open은 ECMAScript built-in이 아니라 browser host capability입니다. 외부 URL을 문자열 prefix로 검사하지 않고 URL parser로 구조화한 뒤 scheme·origin·path 정책을 적용하며, 새 창은 사용자 activation·opener 격리·실패 가능성을 계약화합니다.",
    explanations: [
      "`new URL(input, base)`는 상대 URL을 기준 URL에 resolve하고 protocol·hostname·port·origin·pathname을 구조화합니다. `startsWith('https://safe.example')`는 `https://safe.example.evil.test`를 오인할 수 있으므로 canonical `url.origin === allowedOrigin`처럼 component를 비교합니다.",
      "허용 scheme을 먼저 제한합니다. navigation input에서 `javascript:`·`data:` 등 code/content 실행 가능 scheme을 막고 일반적으로 https를 allowlist합니다. URL constructor가 성공했다는 사실은 목적지가 신뢰된다는 뜻이 아닙니다. redirect와 DNS·server policy도 별도 경계입니다.",
      "window.open은 popup blocker 때문에 null을 반환할 수 있고 user activation 안에서 호출해야 성공 가능성이 높습니다. 반환값을 검사하며 새 창이 원래 창을 제어할 필요가 없다면 noopener를 사용합니다. noreferrer는 referrer 전달도 막는 별도 privacy 선택입니다.",
      "`target='_blank'`의 현대 browser 보호에만 의존하지 말고 application 정책에 noopener 의도를 명시합니다. 외부 링크는 사용자에게 목적지를 알리고 keyboard focus가 갑자기 새 context로 이동하는 경험을 고려합니다. popup을 핵심 workflow 유일 경로로 만들지 않습니다.",
      "URLSearchParams는 query를 parse·serialize하지만 같은 key 여러 개, plus/space, empty value 의미를 제품 schema가 결정해야 합니다. auth token·개인정보를 query에 넣으면 history·referrer·log에 남을 수 있습니다.",
      "테스트는 상대 URL, 정확한 origin, 비슷한 hostname, port 차이, http, javascript scheme, malformed input을 포함합니다. popup 자체는 synthetic click만으로 user activation을 재현할 수 없으므로 실제 browser에서 버튼 클릭과 null fallback을 확인합니다.",
    ],
    concepts: [
      { term: "origin", definition: "URL의 scheme·host·port 조합으로 browser 보안 경계의 핵심 식별자입니다.", detail: ["path는 origin에 포함되지 않습니다.", "기본 port canonicalization을 URL parser에 맡깁니다."] },
      { term: "opener capability", definition: "새 browsing context가 window.opener를 통해 원래 창에 접근할 수 있는 관계입니다.", detail: ["noopener로 불필요한 관계를 끊습니다.", "same-origin 여부에 따라 접근 범위가 달라집니다."] },
      { term: "user activation", definition: "사용자의 실제 click·keyboard 동작에서 비롯된 제한 시간의 browser capability 상태입니다.", detail: ["popup·clipboard 같은 API 허용에 영향을 줍니다.", "synthetic event가 동일 권한을 만들지 않습니다."] },
    ],
    codeExamples: [
      {
        id: "url-origin-popup-decision",
        title: "URL parser와 origin allowlist 기반 popup 결정",
        language: "html",
        filename: "safe-popup-url.html",
        purpose: "고정 base를 기준으로 상대·외부·javascript URL을 판정하고, 허용 URL만 실제 사용자 버튼에서 noopener popup으로 여는 최소 문서입니다.",
        code: "<!doctype html>\n<html lang=\"ko\">\n<head><meta charset=\"utf-8\"><title>safe popup</title></head>\n<body>\n  <button id=\"open\" type=\"button\">가이드 열기</button>\n  <pre id=\"result\"></pre>\n  <script type=\"module\">\n    const base = new URL('https://learn.example/course/');\n    const decide = (raw) => {\n      const url = new URL(raw, base);\n      const allowed = url.protocol === 'https:' && url.origin === base.origin;\n      return { raw, protocol: url.protocol, allowed, url };\n    };\n    const cases = ['/guide', 'https://evil.example/', 'javascript:alert(1)'];\n    const lines = cases.map((raw) => {\n      const decision = decide(raw);\n      return `${decision.protocol}|${decision.allowed}`;\n    });\n    document.querySelector('#result').textContent = lines.join('\\n');\n    console.log(lines.join('\\n'));\n\n    document.querySelector('#open').addEventListener('click', () => {\n      const decision = decide('/guide');\n      const popup = window.open(decision.url, '_blank', 'noopener,noreferrer');\n      if (!popup) console.log('popup-blocked');\n    });\n  </script>\n</body>\n</html>",
        walkthrough: [
          { lines: "1-6", explanation: "native button과 결과 영역이 있는 최소 문서를 만듭니다." },
          { lines: "7-13", explanation: "고정 https base로 URL을 parse하고 protocol과 정확한 origin을 모두 검사합니다." },
          { lines: "14-20", explanation: "상대 경로·외부 origin·javascript scheme의 구조화 판정을 화면과 console에 남깁니다." },
          { lines: "22-26", explanation: "실제 사용자 click에서만 허용 URL을 noopener,noreferrer로 열고 popup blocker의 null 반환을 처리합니다." },
          { lines: "27-29", explanation: "script와 문서를 닫습니다. popup 성공 여부는 browser 설정에 따라 달라지므로 첫 세 줄만 exact 결과입니다." },
        ],
        run: { environment: ["현대 브라우저", "safe-popup-url.html을 UTF-8로 저장", "popup 허용·차단 두 설정을 확인"], command: "브라우저에서 safe-popup-url.html을 열어 첫 세 줄을 확인하고 버튼을 실제 클릭" },
        output: { value: "https:|true\nhttps:|false\njavascript:|false", explanation: ["상대 /guide는 base의 https origin 안으로 resolve되어 허용됩니다.", "외부 https origin은 scheme이 맞아도 거부됩니다.", "javascript scheme은 명시적으로 거부됩니다. popup 결과는 user activation과 browser policy 때문에 별도 관찰합니다."] },
        experiments: [
          { change: "origin 비교를 href.startsWith('https://learn.example')로 바꿉니다.", prediction: "비슷한 hostname이나 encoding corner case를 잘못 허용할 수 있습니다.", result: "문자열 prefix가 아니라 parser component를 비교해야 함을 확인합니다." },
          { change: "noopener를 제거하고 same-origin test page를 엽니다.", prediction: "새 창이 opener reference를 가질 수 있습니다.", result: "필요 없는 browsing-context capability를 끊는 보안 원칙을 확인합니다." },
        ],
        sourceRefs: ["web-window-source", "html-window-open", "url-standard"],
      },
    ],
    diagnostics: [
      { symptom: "허용 domain prefix를 쓴 피싱 URL이 통과한다.", likelyCause: "URL을 문자열 startsWith로 검사해 hostname component 경계를 구분하지 못했습니다.", checks: ["URL constructor로 protocol·hostname·port·origin을 출력합니다.", "allowed.example.evil.test fixture를 넣습니다.", "punycode와 default port canonicalization을 확인합니다."], fix: "URL parser 결과의 scheme과 canonical origin을 allowlist와 비교합니다.", prevention: "유사 hostname·port·scheme·malformed URL security corpus를 고정합니다." },
      { symptom: "window.open 반환 객체를 사용하다 null dereference가 난다.", likelyCause: "popup blocker 또는 user activation 부족으로 open이 null을 반환할 수 있다는 계약을 처리하지 않았습니다.", checks: ["실제 사용자 click stack 안 호출인지 확인합니다.", "popup 차단 설정에서 재현합니다.", "핵심 workflow에 same-page fallback이 있는지 봅니다."], fix: "반환값을 검사하고 링크·현재 창 이동 같은 접근 가능한 fallback을 제공합니다.", prevention: "허용·차단 browser 통합 테스트와 keyboard activation을 함께 검증합니다." },
    ],
    expertNotes: ["외부 URL allowlist가 SSRF를 직접 막는 것은 아닙니다. browser navigation과 server-side fetch는 서로 다른 trust boundary입니다.", "새 창의 focus·announcement는 사용자 경험에 영향을 주므로 링크 텍스트에서 새 context를 예고하는 제품 정책을 검토합니다."],
  },
);

expertSession.reviewQuestions.push(
  { question: "Map에서 내용이 같은 두 object가 다른 key인 이유는 무엇인가요?", answer: "object key는 구조 내용이 아니라 identity로 비교되므로 각각 새로 만든 object는 다른 key입니다." },
  { question: "String.length가 사용자에게 보이는 문자 수가 아닐 수 있는 이유는 무엇인가요?", answer: "length는 UTF-16 code unit 수이고 emoji ZWJ·combining mark는 여러 code unit/code point가 하나의 grapheme을 만들 수 있기 때문입니다." },
  { question: "URL allowlist에 startsWith 대신 origin 비교가 필요한 이유는 무엇인가요?", answer: "origin은 parser가 canonicalize한 scheme·host·port 경계를 비교하지만 문자열 prefix는 유사 hostname과 encoding 경계를 오인할 수 있기 때문입니다." },
);
expertSession.completionChecklist.push(
  "Object·Map·Set·WeakMap을 key type·동등성·열거·lifetime 기준으로 선택할 수 있다.",
  "Intl.Segmenter로 code unit·code point·grapheme 차이를 검증할 수 있다.",
  "URL parser의 scheme·origin·path를 분리해 allowlist를 구현할 수 있다.",
  "window.open의 user activation·null 반환·noopener·접근성 fallback을 설계할 수 있다.",
);
expertSession.sources.push(
  { id: "ecma-keyed-collections-04", repository: "TC39 ECMAScript Language Specification", path: "multipage/keyed-collections.html", publicUrl: "https://tc39.es/ecma262/multipage/keyed-collections.html", usedFor: ["Map", "Set", "WeakMap", "WeakSet", "SameValueZero"], evidence: "keyed collection의 key semantics·iteration·weak lifetime을 자료구조 선택과 memory 설명에 사용했습니다." },
  { id: "ecma-data-structures-04", repository: "TC39 ECMAScript Language Specification", path: "multipage/indexed-collections.html", publicUrl: "https://tc39.es/ecma262/multipage/indexed-collections.html", usedFor: ["Array iteration", "collection conversion", "insertion order 비교"], evidence: "indexed collection과 keyed collection의 API·iteration 차이를 실행 예제 근거로 교차 확인했습니다." },
);
