import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-09-promise-state-error"],
  slug: "js-09-promise-state-error",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 9,
  title: "Promise 상태, 체이닝, 값 전달과 오류 전파",
  subtitle: "pending·fulfilled·rejected와 resolution을 구분하고, then이 만든 새 Promise를 따라 값·thenable·throw·복구·cleanup을 추적합니다.",
  level: "중급",
  estimatedMinutes: 340,
  coreQuestion: "미래의 단일 결과를 Promise로 표현할 때 각 단계의 반환값과 오류가 어떤 새 Promise 상태를 만들며, 취소·병렬 조합·관측까지 어떻게 안전하게 설계할까요?",
  summary: "원본의 success boolean Promise와 2초 뒤 prompt 결과 Promise를 specification-level 상태·resolution·chain 모델로 확장합니다. Promise constructor executor는 즉시 동기 호출되지만 then/catch/finally handlers는 settled Promise에도 microtask로 실행된다는 순서를 exact output으로 증명합니다. pending·fulfilled·rejected와 settled를 구분하고, resolve가 다른 Promise/thenable을 채택하면 resolved이면서 아직 pending일 수 있다는 fate/state 차이를 설명합니다. then은 원본을 바꾸지 않고 항상 새 Promise를 반환하며 handler가 plain value를 return하면 fulfill, Promise/thenable을 return하면 채택, throw하면 reject, return을 빠뜨리면 undefined로 fulfill되는 규칙을 실행합니다. 원본처럼 then과 catch를 sibling으로 달 때 then handler 오류가 별도 catch로 가지 않는 문제, catch에서 정상값을 반환하면 chain이 복구되는 의미, finally가 value/reason을 변환하지 않고 통과시키되 throw/rejected return은 결과를 덮는 경계를 다룹니다. Promise.all/allSettled/race/any의 fail-fast·input order·first settlement·AggregateError 선택 기준과 empty edge case를 포함합니다. callback API wrapping은 executor의 synchronous throw, single settlement, cleanup과 Error reason을 보장하고 AbortSignal로 underlying operation을 취소합니다. Promise.race timeout이 loser를 자동 취소하지 않는다는 점도 명확히 합니다. async/await이 Promise 의미를 바꾸지 않는 문법이라는 연결, floating Promise·unhandled rejection·privacy-safe telemetry·fake dependency 기반 test까지 완성합니다.",
  objectives: [
    "Promise의 pending·fulfilled·rejected·settled state와 resolved fate를 구분해 state transition을 설명할 수 있다.",
    "constructor executor의 동기 실행과 reaction handler의 microtask 실행 순서를 exact output으로 예측할 수 있다.",
    "resolve/reject/throw/thenable adoption과 첫 settlement만 유효한 규칙을 적용할 수 있다.",
    "then이 반환하는 새 Promise에서 plain value·undefined·Promise·thenable·throw가 다음 state를 어떻게 결정하는지 추적할 수 있다.",
    "catch placement·복구·rethrow와 finally pass-through/override semantics를 오류 taxonomy에 맞게 설계할 수 있다.",
    "all·allSettled·race·any를 dependency·partial failure·winner·fallback 요구에 맞게 선택할 수 있다.",
    "callback API를 cleanup·single completion·Error reason·AbortSignal을 갖는 Promise API로 감쌀 수 있다.",
    "async/await, unhandled rejection, floating Promise와 deterministic test/telemetry 경계를 설명할 수 있다.",
  ],
  prerequisites: [
    { title: "이벤트 루프·timer·callback", reason: "Promise reaction이 현재 task 뒤 microtask checkpoint에서 실행되고 timer task보다 먼저 올 수 있는 실행 모델을 사용합니다.", sessionSlug: "js-08-event-loop-timers-callback" },
    { title: "콜백·scope·closure", reason: "executor와 handlers가 closure로 operation state/cleanup을 보유하고 function reference로 전달됩니다.", sessionSlug: "js-02-callback-scope-closure" },
  ],
  keywords: ["Promise", "pending", "fulfilled", "rejected", "settled", "resolved", "executor", "resolve", "reject", "then", "catch", "finally", "microtask", "Promise resolution", "thenable", "chaining", "missing return", "error propagation", "Promise.all", "allSettled", "race", "any", "AggregateError", "AbortSignal", "unhandledrejection", "async", "await"],
  chapters: [
    {
      id: "future-result-state-fate",
      title: "Promise는 미래의 단일 completion을 나타내며 state와 fate를 구분합니다",
      lead: "성공/실패 callback 두 개를 단순히 묶은 상자가 아니라 한 번 결정되는 결과와 그 결과를 구독하는 reaction graph로 봅니다.",
      explanations: [
        "Promise object는 아직 결과가 없는 pending, value와 함께 완료된 fulfilled, reason과 함께 실패한 rejected state 중 하나입니다. fulfilled와 rejected를 합쳐 settled라고 하며 한번 settled되면 다른 state/value/reason으로 바뀌지 않습니다.",
        "resolved는 fulfilled와 같은 단어가 아닙니다. resolve가 plain value를 받아 바로 fulfill할 수도 있지만 다른 Promise/thenable을 받아 그 결과를 채택하면 fate는 고정됐어도 adopted Promise가 끝날 때까지 state는 pending일 수 있습니다.",
        "Promise는 진행률이 여러 번 오는 stream이나 여러 event를 표현하지 않습니다. 단일 completion에는 적합하지만 지속 data는 async iterator, event target, observable/stream 등 별도 abstraction을 검토합니다.",
        "원본 ex10은 success boolean에 따라 resolve 또는 reject를 호출해 가장 단순한 단일 settlement를 보여 줍니다. 실제 operation에서는 validation failure, network failure, cancellation과 programmer error를 reason/type으로 분류해야 합니다.",
        "settled Promise는 value/reason을 외부에서 property로 동기 조회하는 API를 제공하지 않습니다. then/catch/await를 통해 결과를 받으며 DevTools 표시를 application control flow로 사용하지 않습니다.",
        "Promise를 만들었다고 underlying work가 자동으로 background thread에서 실행되는 것은 아닙니다. executor의 synchronous code는 현재 stack에서 실행되고 timer/fetch/worker 같은 host operation만 해당 execution model에 따라 비동기로 진행됩니다.",
      ],
      concepts: [
        { term: "pending/fulfilled/rejected", definition: "Promise의 현재 state로 아직 결과 없음, value로 정상 완료, reason으로 실패 완료를 나타냅니다.", detail: ["fulfilled/rejected는 settled입니다.", "settled 뒤 state는 바뀌지 않습니다."] },
        { term: "resolved fate", definition: "Promise가 자체 value로 완료하거나 다른 Promise/thenable의 결과를 채택하도록 결정되어 더 이상 외부 resolve/reject로 fate를 바꿀 수 없는 상태입니다.", detail: ["pending일 수 있습니다.", "fulfilled와 동의어가 아닙니다."] },
        { term: "single completion", definition: "operation이 value 또는 reason 하나로 한 번만 끝난다는 Promise contract입니다.", detail: ["progress stream과 다릅니다.", "중복 callback을 무시/정리합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "Promise에 진행률을 여러 번 resolve했는데 첫 값만 보인다.", likelyCause: "single-settlement abstraction을 multi-event stream처럼 사용했습니다.", checks: ["operation이 단일 completion인지 progress/events인지 분류합니다.", "resolve/reject 호출 횟수와 첫 호출을 기록합니다.", "listener/async iterator/stream이 더 적합한지 봅니다."], fix: "최종 결과는 Promise 하나로, progress는 별도 callback/event/stream channel로 분리하고 completion 뒤 progress를 중단합니다.", prevention: "API contract에 cardinality와 completion/cancellation을 명시하고 duplicate-callback test를 둡니다." },
      ],
    },
    {
      id: "constructor-executor-settlement",
      title: "Promise constructor executor는 즉시 동기 실행되고 resolve/reject는 reaction 실행 예약을 시작합니다",
      lead: "executor 자체를 비동기로 착각하지 않고 어디서 synchronous throw가 reject로 변환되는지 추적합니다.",
      explanations: [
        "`new Promise(executor)`는 executor function을 resolve/reject functions와 함께 constructor 호출 중 즉시 호출합니다. executor 시작/끝 log는 new Promise 다음 line보다 먼저 나옵니다.",
        "executor가 resolve(value)를 호출하면 Promise resolution procedure가 value를 처리합니다. reject(reason)는 rejected state로 전환합니다. 첫 유효 settlement 이후 추가 resolve/reject 호출은 Promise 결과를 바꾸지 않지만 호출 뒤 executor code 자체는 return할 때까지 계속 실행됩니다.",
        "executor가 resolve/reject 전후 synchronous throw를 하면 아직 unsettled인 경우 rejection reason이 됩니다. 이미 resolve가 fate를 정한 뒤 throw해도 settled result를 뒤집지 않습니다. 이 차이를 error telemetry에서 혼동하지 않습니다.",
        "executor return value는 Promise result로 사용되지 않습니다. `return 3`이 아니라 resolve(3)를 호출해야 하며 async function을 executor로 넘기는 anti-pattern은 외부 constructor가 async executor가 반환한 Promise를 추적하지 않아 오류가 떠다닐 수 있습니다.",
        "reject reason은 기술적으로 어떤 value도 가능하지만 Error 또는 domain Error subclass를 사용해 name/message/cause/stack과 classification을 보존합니다. 원본의 문자열 '작업실패'는 학습 출력에는 단순하지만 운영 진단에는 부족합니다.",
        "직접 new Promise를 쓰는 주된 경우는 callback-style host/library API를 한 번의 completion으로 감쌀 때입니다. 이미 Promise를 반환하는 API를 불필요하게 new Promise로 다시 감싸지 않습니다.",
      ],
      concepts: [
        { term: "executor", definition: "Promise construction 중 동기 호출되어 resolve/reject capabilities로 underlying operation을 연결하는 function입니다.", detail: ["return value는 무시됩니다.", "synchronous throw는 rejection이 될 수 있습니다."] },
        { term: "resolve function", definition: "value/Promise/thenable에 Promise resolution procedure를 적용해 promise fate를 결정하는 capability입니다.", detail: ["항상 즉시 fulfilled는 아닙니다.", "thenable을 채택할 수 있습니다."] },
        { term: "rejection reason", definition: "Promise가 rejected된 이유 value로 운영 code에서는 Error object와 domain metadata를 사용하는 것이 좋습니다.", detail: ["문자열만 쓰지 않습니다.", "사용자 message와 internal detail을 분리합니다."] },
      ],
      codeExamples: [
        {
          id: "executor-sync-reaction-microtask",
          title: "동기 executor와 microtask reaction·timer 순서",
          language: "html",
          filename: "promise-executor-order.html",
          purpose: "resolve가 executor를 멈추거나 handler를 즉시 호출하지 않는다는 사실을 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>promise order</title></head>\n<body><pre id=\"out\"></pre><script>\n  const lines = [];\n  const promise = new Promise((resolve, reject) => {\n    lines.push('executor-start');\n    resolve('ok');\n    reject(new Error('late'));\n    lines.push('executor-end');\n  });\n  promise.then(value => lines.push(`then=${value}`));\n  setTimeout(() => {\n    lines.push('timer');\n    document.querySelector('#out').textContent = lines.join('\\n');\n  }, 0);\n  lines.push('sync-end');\n</script></body></html>",
          walkthrough: [
            { lines: "3-9", explanation: "constructor가 executor를 즉시 실행하고 첫 resolve 뒤 late reject는 결과를 바꾸지 않지만 executor-end는 계속 기록합니다." },
            { lines: "10", explanation: "fulfilled reaction을 등록하며 callback은 현재 stack이 끝난 뒤 microtask로 실행됩니다." },
            { lines: "11-15", explanation: "timer task가 최종 output을 만들고 현재 script는 sync-end를 먼저 기록합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 promise-executor-order.html을 열고 결과 확인" },
          output: { value: "executor-start\nexecutor-end\nsync-end\nthen=ok\ntimer", explanation: ["executor는 new Promise 중 동기 실행됩니다.", "resolve 뒤 executor-end와 script sync-end가 먼저 완료됩니다.", "then reaction microtask가 timer task보다 먼저 실행되고 late reject는 무시됩니다."] },
          experiments: [
            { change: "resolve 전에 throw new Error('boom')을 넣습니다.", prediction: "Promise가 rejected되고 then fulfillment handler는 실행되지 않습니다.", result: "executor synchronous throw가 rejection이 됩니다." },
            { change: "resolve 후 throw를 넣습니다.", prediction: "이미 정해진 fulfilled ok를 뒤집지 않습니다.", result: "first settlement/fate가 유지됩니다." },
            { change: "executor에 async를 붙이고 await 뒤 throw합니다.", prediction: "outer Promise constructor가 returned async Promise를 자동 채택하지 않아 unhandled rejection 위험이 생깁니다.", result: "async executor를 피합니다." },
          ],
          sourceRefs: ["web-promise-basic-source", "tc39-promise-constructor", "html-microtasks"],
        },
      ],
      diagnostics: [
        { symptom: "new Promise(async (resolve)=>{ await work(); throw error; })의 catch가 오류를 못 잡거나 pending으로 남는다.", likelyCause: "Promise constructor가 async executor의 반환 Promise를 결과로 사용하지 않고 explicit resolve/reject만 추적합니다.", checks: ["executor에 async가 붙었는지 검색합니다.", "모든 code path가 resolve/reject하는지 봅니다.", "이미 Promise인 work를 직접 return할 수 있는지 확인합니다."], fix: "async function 자체를 사용해 Promise를 반환하거나 non-async executor에서 callback API만 연결하고 rejection을 명시 전달합니다.", prevention: "no-async-promise-executor lint와 pending/error path tests를 둡니다." },
      ],
    },
    {
      id: "then-new-promise-resolution",
      title: "then은 원본을 바꾸지 않고 새 Promise를 반환하며 handler completion이 새 결과를 결정합니다",
      lead: "각 화살표마다 return/throw와 그 결과 Promise의 state/value/reason을 표로 적습니다.",
      explanations: [
        "`next = current.then(onFulfilled, onRejected)`는 즉시 별도 next Promise를 반환합니다. current가 fulfill/reject되면 적절한 handler가 microtask에서 호출되고 handler completion이 next의 결과를 결정합니다.",
        "handler가 plain value를 return하면 next는 그 value로 fulfilled됩니다. return을 생략하면 JavaScript function의 implicit undefined가 반환되어 next는 undefined로 fulfilled됩니다. async operation을 호출만 하고 return하지 않는 누락 return이 흔한 순서 버그입니다.",
        "handler가 Promise 또는 thenable을 return하면 next가 그 결과를 채택해 완료까지 기다립니다. nested then을 시작해 놓고 return하지 않으면 outer chain은 기다리지 않습니다.",
        "handler가 throw하면 next가 그 error로 rejected됩니다. 반대로 rejected current에 rejection handler가 없으면 reason이 next로 전달되고 fulfilled current에 fulfillment handler가 없으면 value가 전달됩니다.",
        "같은 original Promise에 여러 then을 달면 reactions가 각각 새 branch를 만듭니다. 한 branch의 변환/오류가 다른 sibling branch로 자동 전달되지 않습니다. dependency라면 반환된 Promise에 이어 chain을 만듭니다.",
        "thenable은 callable then property를 가진 foreign object일 수 있으며 resolution procedure가 호출·중복 settlement·throw를 규칙에 따라 처리합니다. 임의 object의 then getter가 code를 실행할 수 있어 untrusted thenable을 단순 data로 생각하지 않습니다.",
        "자기 자신을 return하는 Promise cycle은 TypeError rejection이 됩니다. graph가 복잡해지면 명시적 named steps와 single chain/async function으로 ownership을 단순화합니다.",
      ],
      concepts: [
        { term: "promise chain", definition: "각 then/catch/finally가 반환한 새 Promise를 다음 단계가 구독해 value/reason을 연결하는 graph입니다.", detail: ["원본은 변하지 않습니다.", "return이 dependency를 연결합니다."] },
        { term: "thenable adoption", definition: "Promise resolution이 then method를 가진 object/Promise의 최종 결과를 채택하는 과정입니다.", detail: ["비동기 완료를 기다립니다.", "foreign code/throw를 고려합니다."] },
        { term: "missing return", definition: "handler에서 시작한 value/Promise를 return하지 않아 다음 Promise가 undefined로 너무 일찍 fulfilled되는 결함입니다.", detail: ["nested async work를 기다리지 않습니다.", "lint/type으로 잡습니다."] },
      ],
      codeExamples: [
        {
          id: "missing-return-versus-adoption",
          title: "누락 return과 Promise adoption 비교",
          language: "html",
          filename: "promise-return.html",
          purpose: "같은 inner Promise를 호출만 한 branch와 return한 branch의 next value를 exact output으로 비교합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>promise return</title></head>\n<body><pre id=\"out\"></pre><script>\n  function inner(value) {\n    return Promise.resolve(`${value}-inner`);\n  }\n  const broken = Promise.resolve('start').then(value => {\n    inner(value);\n  });\n  const fixed = Promise.resolve('start').then(value => {\n    return inner(value);\n  });\n  Promise.all([broken, fixed]).then(([brokenValue, fixedValue]) => {\n    document.querySelector('#out').textContent = [\n      `broken=${brokenValue}`,\n      `fixed=${fixedValue}`\n    ].join('\\n');\n  });\n</script></body></html>",
          walkthrough: [
            { lines: "3-5", explanation: "inner는 fulfilled Promise를 명시적으로 반환합니다." },
            { lines: "6-8", explanation: "broken handler는 inner return을 버려 implicit undefined로 완료됩니다." },
            { lines: "9-11", explanation: "fixed handler는 inner Promise를 return해 next가 its result를 채택합니다." },
            { lines: "12-17", explanation: "두 branches가 모두 settle된 뒤 values를 같은 output에서 비교합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 promise-return.html을 열고 결과 확인" },
          output: { value: "broken=undefined\nfixed=start-inner", explanation: ["broken then handler의 implicit return은 undefined입니다.", "fixed branch는 returned Promise를 채택해 start-inner를 받습니다."] },
          experiments: [
            { change: "inner가 timer 뒤 resolve하도록 바꿉니다.", prediction: "broken은 timer를 기다리지 않고 undefined로 먼저 settle하며 fixed는 기다립니다.", result: "return이 sequencing dependency를 연결합니다." },
            { change: "inner를 reject하게 만듭니다.", prediction: "broken inner rejection은 outer catch와 분리되어 unhandled 위험이 있고 fixed rejection은 chain으로 전파됩니다.", result: "floating Promise를 만들지 않습니다." },
            { change: "concise arrow `value=>inner(value)`로 바꿉니다.", prediction: "expression return으로 fixed와 동일합니다.", result: "brace를 쓰면 explicit return을 확인합니다." },
          ],
          sourceRefs: ["tc39-promise-then", "html-microtasks"],
        },
      ],
      diagnostics: [
        { symptom: "다음 then이 network/data 완료 전 실행되고 value가 undefined다.", likelyCause: "이전 handler가 Promise/value를 return하지 않아 next Promise가 undefined로 fulfilled됐습니다.", checks: ["각 then handler의 모든 branches에 return이 있는지 봅니다.", "nested Promise가 floating인지 추적합니다.", "TypeScript return type과 no-floating-promises lint를 확인합니다."], fix: "dependent Promise를 return하거나 async handler에서 await+return하고 chain을 하나의 owner에 연결합니다.", prevention: "success/failure timing test와 explicit return/no-floating Promise static analysis를 둡니다." },
      ],
    },
    {
      id: "chain-values-errors-recovery",
      title: "값과 오류는 같은 chain의 두 경로이며 catch의 정상 return은 실패를 복구합니다",
      lead: "catch가 log만 하고 끝날 때 다음 단계가 정상 undefined로 진행된다는 사실을 의도적으로 결정합니다.",
      explanations: [
        "fulfilled path에서 throw하면 반환된 next Promise가 rejected되고 이후 fulfillment handlers를 건너뛰어 가장 가까운 rejection handler/catch로 이동합니다. reject와 throw를 서로 다른 channel로 따로 관리하지 않습니다.",
        "catch(onRejected)는 `then(undefined,onRejected)`와 같은 형태로 새 Promise를 반환합니다. handler가 fallback value를 정상 return하면 chain은 그 value로 fulfilled되어 이후 then이 실행됩니다.",
        "복구할 수 없는 error를 catch에서 log만 하고 return하면 오류를 삼켜 성공처럼 보이게 됩니다. rethrow하거나 `return Promise.reject(error)`로 전파하고, retry/fallback이 실제 성공 의미일 때만 value로 복구합니다.",
        "원본 ex10의 `myPromise.then(...); myPromise.catch(...);`는 두 sibling branches입니다. original rejection은 catch branch가 처리하지만 then fulfillment handler가 throw한 error는 then이 반환한 별도 Promise에 있으므로 sibling catch가 처리하지 못합니다. `.then(...).catch(...)`로 이어야 합니다.",
        "error taxonomy는 ValidationError, AbortError, NetworkError, HTTP application error처럼 사용자 action과 retry policy가 다른 categories를 둡니다. 문자열 비교보다 class/code/cause를 사용하고 사용자 message에는 internal stack/token을 노출하지 않습니다.",
        "여러 catch를 두면 좁은 scope에서 복구한 뒤 다음 stage를 계속할 수 있습니다. 너무 큰 final catch 하나는 어느 step이 실패했는지 잃을 수 있어 operation context/cause를 보강합니다.",
      ],
      concepts: [
        { term: "rejection propagation", definition: "rejection handler가 없는 chain stages를 reason이 통과해 다음 rejection handler로 전달되는 규칙입니다.", detail: ["throw도 rejection이 됩니다.", "같은 chain에 연결해야 합니다."] },
        { term: "error recovery", definition: "catch가 fallback value/Promise를 정상 반환해 rejected path를 fulfilled path로 전환하는 의도적 처리입니다.", detail: ["다음 then이 실행됩니다.", "단순 logging과 구분합니다."] },
        { term: "sibling branch", definition: "같은 original Promise에 독립 then/catch를 달아 서로 다른 returned Promises를 만든 구조입니다.", detail: ["한 branch 오류가 다른 branch에 가지 않습니다.", "dependency에는 chain을 사용합니다."] },
      ],
      codeExamples: [
        {
          id: "chain-throw-catch-recover-finally",
          title: "값 변환·중간 throw·catch 복구·finally 통과",
          language: "html",
          filename: "promise-chain-error.html",
          purpose: "각 handler completion이 다음 Promise의 value/reason을 바꾸는 전체 흐름을 exact output으로 추적합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>promise chain</title></head>\n<body><pre id=\"out\"></pre><script>\n  const lines = [];\n  Promise.resolve(2)\n    .then(value => {\n      lines.push(`step1=${value}`);\n      return value * 3;\n    })\n    .then(value => {\n      lines.push(`step2=${value}`);\n      throw new Error(`boom:${value}`);\n    })\n    .then(() => lines.push('skipped'))\n    .catch(error => {\n      lines.push(`catch=${error.message}`);\n      return 10;\n    })\n    .finally(() => lines.push('finally'))\n    .then(value => {\n      lines.push(`recovered=${value}`);\n      document.querySelector('#out').textContent = lines.join('\\n');\n    });\n</script></body></html>",
          walkthrough: [
            { lines: "4-8", explanation: "2를 받아 trace한 뒤 plain value 6으로 다음 Promise를 fulfill합니다." },
            { lines: "9-13", explanation: "6에서 Error를 throw해 next를 reject하고 다음 fulfillment-only stage를 건너뜁니다." },
            { lines: "14-18", explanation: "catch가 message를 기록하고 10을 return해 chain을 fulfilled로 복구합니다." },
            { lines: "19-23", explanation: "finally가 cleanup trace만 남기고 recovered value 10을 다음 then에 통과시킵니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 promise-chain-error.html을 열고 결과 확인" },
          output: { value: "step1=2\nstep2=6\ncatch=boom:6\nfinally\nrecovered=10", explanation: ["첫 return이 6을 전달합니다.", "throw 때문에 skipped handler는 실행되지 않습니다.", "catch return 10이 복구 value가 되고 finally는 이를 보존합니다."] },
          experiments: [
            { change: "catch의 return 10 대신 throw error를 사용합니다.", prediction: "finally는 실행되지만 마지막 fulfillment then은 실행되지 않고 chain은 rejected로 남습니다.", result: "복구와 재전파를 명시합니다." },
            { change: "then과 catch를 같은 original에 sibling으로 분리합니다.", prediction: "then handler 내부 throw를 sibling catch가 처리하지 못합니다.", result: "returned Promise chain을 이어 잡습니다." },
            { change: "finally에서 throw new Error('cleanup')을 실행합니다.", prediction: "원래 recovered value 대신 cleanup rejection이 최종 결과가 됩니다.", result: "finally도 실패할 수 있는 boundary입니다." },
          ],
          sourceRefs: ["web-promise-input-source", "tc39-promise-then", "tc39-promise-finally"],
        },
      ],
      diagnostics: [
        { symptom: "catch에서 오류를 console.log했더니 이후 저장 성공 UI가 실행된다.", likelyCause: "catch handler가 정상 return(undefined)해 chain을 fulfilled로 복구했지만 실제 업무는 실패였습니다.", checks: ["catch 이후 then이 무엇을 성공으로 해석하는지 봅니다.", "복구 가능한 오류 taxonomy와 fallback을 정의합니다.", "rethrow/return rejected Promise가 필요한지 확인합니다."], fix: "실제 fallback 성공에서만 명시 value를 return하고 복구 불가 오류는 context/cause를 보강해 rethrow하며 최종 UI는 result type을 확인합니다.", prevention: "각 error category의 recover/rethrow outcome test와 no-console-only-catch review를 둡니다." },
        { symptom: "then handler의 TypeError가 unhandled인데 바로 아래 `original.catch`는 실행되지 않는다.", likelyCause: "catch가 original Promise의 sibling이고 then이 반환한 새 rejected Promise에 연결되지 않았습니다.", checks: ["then return value를 변수로 저장해 branch graph를 그립니다.", "catch receiver가 original인지 returned chain인지 봅니다.", "floating Promise lint를 확인합니다."], fix: "`original.then(handler).catch(...)`처럼 반환 chain을 catch하거나 각 branch가 자기 catch/await owner를 갖게 합니다.", prevention: "Promise return values를 버리지 않고 branch별 terminal handler ownership을 code review합니다." },
      ],
    },
    {
      id: "finally-cleanup-pass-through",
      title: "finally는 value/reason을 몰라도 실행되는 cleanup stage이며 정상 완료 시 원래 결과를 통과시킵니다",
      lead: "spinner·lock·timer 정리는 finally에 두되 성공 data 변환과 실패 복구는 then/catch에 둡니다.",
      explanations: [
        "finally(onFinally)는 fulfillment value나 rejection reason을 argument로 받지 않는 cleanup-oriented handler입니다. 정상 return 또는 fulfilled Promise를 반환하면 원래 value/reason이 다음 chain에 보존됩니다.",
        "finally에서 throw하거나 rejected Promise를 반환하면 cleanup failure가 원래 결과를 덮고 새 rejection이 됩니다. resource cleanup 실패가 중요한 경우 cause/aggregate 정책을 정해 원래 오류도 관측 가능하게 합니다.",
        "원본 ex11의 finally '수고하셨습니다'는 성공·실패 모두 실행되는 성질을 보여 줍니다. 실제 UI에서는 loading=false, timer clear, listener detach처럼 성공/실패 공통 cleanup을 둡니다.",
        "finally에서 성공 value를 return해 변환하려 해도 정상 value는 대체되지 않습니다. 결과 변환은 then, fallback은 catch에서 수행합니다. 반대로 finally callback 내부 async cleanup은 Promise를 return하면 chain이 완료를 기다립니다.",
        "cleanup을 여러 곳 then/catch에 복제하면 한 branch에서 빠뜨리기 쉽습니다. acquire와 release owner를 같은 function boundary에 두고 idempotent cleanup을 만듭니다.",
        "AbortSignal listener, timeout handle, button disabled, spinner와 operation generation을 finally에서 정리하되 새 operation이 이미 시작된 race에서는 current generation인지 확인해 다른 요청의 UI를 끄지 않습니다.",
      ],
      concepts: [
        { term: "pass-through cleanup", definition: "성공 value 또는 실패 reason을 변환하지 않고 양쪽 outcome에서 공통 resource/UI 정리를 수행하는 finally 역할입니다.", detail: ["argument가 없습니다.", "정상 completion은 original outcome을 보존합니다."] },
        { term: "cleanup override", definition: "finally callback이 throw/reject해 original outcome 대신 cleanup failure가 최종 rejection이 되는 상황입니다.", detail: ["원래 error 보존을 고려합니다.", "cleanup도 test합니다."] },
        { term: "generation guard", definition: "비동기 operation마다 token을 두어 늦은 finally가 더 최신 operation의 UI/resource state를 잘못 정리하지 않게 하는 검사입니다.", detail: ["race를 막습니다.", "AbortSignal과 함께 쓸 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "오래된 요청의 finally가 새 요청 spinner와 disabled state를 꺼 버린다.", likelyCause: "여러 overlapping operations가 같은 UI cleanup을 ownership/generation 확인 없이 공유했습니다.", checks: ["operation start/settle 순서와 IDs를 trace합니다.", "finally가 current operation인지 확인하는지 봅니다.", "button/spinner owner를 분리합니다."], fix: "generation/token 또는 reference equality로 current operation만 shared UI를 정리하고 각 operation resource는 자체 finally에서 idempotent하게 해제합니다.", prevention: "slow-old/fast-new 역순 settlement race test를 둡니다." },
      ],
    },
    {
      id: "promise-combinators-concurrency",
      title: "all·allSettled·race·any는 시작 도구가 아니라 여러 input outcomes를 조합하는 정책입니다",
      lead: "어떤 실패가 전체 실패인지, partial result가 필요한지, first settlement와 first success 중 무엇인지 먼저 정합니다.",
      explanations: [
        "Promise.all(iterable)은 모든 inputs가 fulfill하면 input order의 values array로 fulfill하고 하나라도 reject하면 그 first observed rejection으로 reject합니다. completion order가 달라도 result array order는 input order입니다.",
        "Promise.allSettled는 모든 inputs가 settle될 때까지 기다려 각 input order에 status와 value 또는 reason records를 반환합니다. 독립 widgets처럼 partial success/failure를 모두 보여 줄 때 적합합니다.",
        "Promise.race는 first settled input의 value 또는 reason을 따릅니다. first success가 아니라 빠른 실패도 winner입니다. timeout Promise와 race해도 losing fetch/timer가 자동 취소되지 않아 underlying cancellation/cleanup이 필요합니다.",
        "Promise.any는 first fulfilled input을 따르고 모두 reject하면 AggregateError로 reject합니다. fallback mirrors 중 하나의 성공이 충분할 때 사용하며 individual errors의 privacy-safe aggregation 정책을 둡니다.",
        "combinators가 inputs를 '동시에 시작'하는 것은 아닙니다. iterable에 넣기 전에 function을 호출해 Promises를 만들었다면 work는 이미 시작했을 수 있습니다. concurrency limit이 필요하면 task functions queue/pool을 사용합니다.",
        "empty iterable edge case도 다릅니다. all/allSettled는 fulfilled empty result, race는 pending forever, any는 AggregateError rejection이 될 수 있어 dynamic input이 0개일 때 product behavior를 따로 처리합니다.",
      ],
      concepts: [
        { term: "fail-fast aggregate", definition: "Promise.all처럼 하나의 rejection으로 전체 aggregate를 reject하는 dependency policy입니다.", detail: ["all dependencies가 필요할 때 씁니다.", "losers를 자동 취소하지 않습니다."] },
        { term: "settled outcome record", definition: "allSettled가 각 input에 대해 status와 value/reason을 보존하는 record입니다.", detail: ["partial failure를 표시합니다.", "input order를 보존합니다."] },
        { term: "first settlement vs first fulfillment", definition: "race는 성공/실패 중 먼저 settle, any는 성공 중 먼저 fulfill을 선택하는 차이입니다.", detail: ["timeout/fallback policy가 다릅니다.", "any all-reject는 AggregateError입니다."] },
      ],
      codeExamples: [
        {
          id: "promise-combinator-policy",
          title: "completion order·partial failure·first settle·first success 비교",
          language: "html",
          filename: "promise-combinators.html",
          purpose: "all result order, allSettled records, race와 any의 선택 결과를 한 exact output으로 비교합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>promise combinators</title></head>\n<body><pre id=\"out\"></pre><script>\n  const slow = new Promise(resolve => setTimeout(() => resolve('slow'), 10));\n  const fast = Promise.resolve('fast');\n  const failedForSettled = Promise.reject(new Error('no'));\n  const failedForAny = Promise.reject(new Error('skip'));\n  Promise.all([\n    Promise.all([slow, fast]),\n    Promise.allSettled([fast, failedForSettled]),\n    Promise.race([slow, fast]),\n    Promise.any([failedForAny, Promise.resolve('winner')])\n  ]).then(([allValues, settled, raced, anyValue]) => {\n    const settledText = settled.map(item => item.status === 'fulfilled'\n      ? `${item.status}:${item.value}`\n      : `${item.status}:${item.reason.message}`).join('|');\n    document.querySelector('#out').textContent = [\n      `all=${allValues.join('|')}`,\n      `settled=${settledText}`,\n      `race=${raced}`,\n      `any=${anyValue}`\n    ].join('\\n');\n  });\n</script></body></html>",
          walkthrough: [
            { lines: "3-6", explanation: "slow/fast와 두 독립 rejected inputs를 생성해 즉시 handlers가 붙도록 준비합니다." },
            { lines: "7-12", explanation: "네 combinator Promises를 outer all로 모아 결과를 한 시점에 비교합니다." },
            { lines: "13-21", explanation: "all values/input order, settled status/value/reason, race/any winners를 stable strings로 출력합니다." },
          ],
          run: { environment: ["Promise.allSettled/any를 지원하는 modern browser"], command: "browser에서 promise-combinators.html을 열고 결과 확인" },
          output: { value: "all=slow|fast\nsettled=fulfilled:fast|rejected:no\nrace=fast\nany=winner", explanation: ["slow가 늦어도 all values는 input order slow|fast입니다.", "allSettled는 success와 failure를 모두 input order로 보존합니다.", "race는 먼저 settled fast, any는 rejected input을 건너 first fulfilled winner를 선택합니다."] },
          experiments: [
            { change: "race 첫 input을 즉시 rejected Promise로 바꿉니다.", prediction: "race는 빠른 실패로 reject합니다.", result: "race는 first success가 아닙니다." },
            { change: "any inputs를 모두 reject하게 합니다.", prediction: "AggregateError로 reject합니다.", result: "errors와 fallback failure UI를 처리합니다." },
            { change: "all input 중 하나를 reject하게 합니다.", prediction: "outer dependency aggregate가 fail-fast reject하지만 이미 시작한 다른 operations는 계속될 수 있습니다.", result: "AbortSignal/cleanup을 별도 연결합니다." },
          ],
          sourceRefs: ["tc39-promise-combinators", "html-microtasks"],
        },
      ],
      diagnostics: [
        { symptom: "Promise.race timeout은 reject했지만 network request가 계속되어 뒤늦게 side effect를 만든다.", likelyCause: "race가 losing Promise/underlying operation을 자동 취소한다고 가정했습니다.", checks: ["loser의 AbortSignal/cleanup handle을 확인합니다.", "timeout settlement 뒤 network log/side effect를 봅니다.", "operation idempotency와 stale result guard를 검사합니다."], fix: "AbortController로 underlying operation을 abort하고 timeout handle을 finally에서 clear하며 server side effect에는 idempotency/authorization을 둡니다.", prevention: "timeout winner 뒤 loser cancellation·late settlement·resource cleanup test를 둡니다." },
      ],
    },
    {
      id: "callback-wrapping-abort-timeout",
      title: "Callback API를 Promise로 감쌀 때 single completion·cleanup·cancellation을 함께 변환합니다",
      lead: "resolve/reject만 추가하지 말고 listener/timer/operation handle을 누가 언제 해제하는지 계약에 포함합니다.",
      explanations: [
        "Node-style `(error,value)` 또는 event callback을 Promise로 감쌀 때 executor에서 listener를 등록하고 첫 completion에서 cleanup한 뒤 error면 reject(Error), value면 resolve합니다. callback이 여러 번 올 수 있으면 settled guard와 unsubscribe를 사용합니다.",
        "registration 자체가 synchronous throw할 수 있으므로 executor throw→rejection 규칙을 활용하되 cleanup handle이 만들어진 단계와 실패 단계를 구분합니다. resolve/reject 후에도 callback body가 계속되므로 cleanup/return 순서를 명시합니다.",
        "Promise 자체에는 보편적인 cancel method가 없습니다. AbortSignal을 function argument로 받아 이미 aborted면 즉시 AbortError rejection, 이후 abort event에서 underlying timer/request/listener를 취소하고 reject합니다.",
        "settlement와 abort가 거의 동시에 오면 첫 settlement만 Promise를 결정하지만 loser event의 external side effects/cleanup은 남을 수 있습니다. one-shot finish function이 settled guard와 cleanup을 한 곳에서 처리합니다.",
        "timeout은 AbortSignal.timeout 같은 지원되는 mechanism 또는 controller+timer로 underlying work를 취소합니다. Promise.race만 붙이면 wrapper result는 끝나도 callback subscription과 work가 살아 있을 수 있습니다.",
        "이미 Promise를 반환하는 fetch를 new Promise로 다시 감싸는 Promise constructor anti-pattern은 stack/error/cancellation을 복잡하게 합니다. fetch Promise를 return하고 response validation/abort를 chain 또는 async function에서 처리합니다.",
      ],
      concepts: [
        { term: "promisification", definition: "callback/event 기반 단일 completion API를 resolve/reject와 cleanup을 가진 Promise-returning API로 변환하는 과정입니다.", detail: ["multi-event에는 부적합할 수 있습니다.", "unsubscribe를 포함합니다."] },
        { term: "AbortSignal", definition: "caller가 underlying asynchronous activity 중단을 요청하고 API가 abort reason/cleanup에 반응하게 하는 shared cancellation signal입니다.", detail: ["Promise settlement와 별개입니다.", "listener를 정리합니다."] },
        { term: "one-shot finish", definition: "성공·실패·abort·timeout 중 첫 outcome만 적용하고 공통 cleanup을 한 번 수행하는 wrapper boundary입니다.", detail: ["race를 관리합니다.", "외부 resource를 해제합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "Promise는 reject됐는데 callback listener와 timeout이 남아 memory와 duplicate action이 쌓인다.", likelyCause: "wrapper가 value/reason만 변환하고 unsubscribe/clear/abort cleanup을 completion과 묶지 않았습니다.", checks: ["resolve/reject/abort/timeout 각 path의 cleanup call count를 봅니다.", "callback이 multi-fire인지 확인합니다.", "settled 뒤 external side effect를 추적합니다."], fix: "idempotent finish function에서 settled guard→unsubscribe/clear→resolve/reject 순서를 관리하고 AbortSignal을 underlying API에 전달합니다.", prevention: "success/error/abort/timeout/simultaneous race 뒤 pending listeners/timers 0을 test합니다." },
      ],
    },
    {
      id: "async-await-sequencing",
      title: "async/await은 Promise state·reaction·error 전파를 바꾸지 않고 순차 code처럼 표현합니다",
      lead: "await가 thread를 block하는 것이 아니라 async function을 suspend하고 continuation을 reaction으로 연결한다는 모델을 유지합니다.",
      explanations: [
        "async function을 호출하면 항상 Promise를 반환합니다. return value는 fulfillment value가 되고 throw는 rejection reason이 됩니다. caller가 await/return/catch하지 않으면 floating Promise 문제는 그대로입니다.",
        "await expression은 operand를 Promise resolution으로 처리하고 async function execution을 suspend합니다. surrounding main thread/event loop는 다른 work를 처리하고 settlement 뒤 continuation이 다시 실행됩니다.",
        "try/catch/finally는 await된 rejection을 synchronous-looking control flow로 다루지만 catch recovery/rethrow와 finally override semantics는 Promise chain과 같습니다. await하지 않은 spawned Promise의 error는 바깥 try/catch가 잡지 못합니다.",
        "서로 독립인 operations를 `await first(); await second();`로 쓰면 불필요하게 sequential할 수 있습니다. 둘을 먼저 시작하고 Promise.all로 기다리되 concurrency limit·fail/cancel policy를 적용합니다.",
        "반대로 second가 first result를 필요로 하면 sequential await가 dependency를 명확히 합니다. 무조건 Promise.all로 병렬화해 rate limit·resource contention·ordering invariant를 깨지 않습니다.",
        "top-level await은 module graph loading/evaluation에 영향을 주므로 app boot에서 느린 network를 무조건 기다리지 않고 fallback/lazy boundary와 failure UI를 설계합니다.",
      ],
      concepts: [
        { term: "async function", definition: "호출 시 Promise를 반환하고 return/throw를 fulfillment/rejection으로 변환하는 ECMAScript function form입니다.", detail: ["Promise semantics를 유지합니다.", "floating result를 관리합니다."] },
        { term: "await suspension", definition: "Promise-like operand completion까지 async function의 이후 execution을 중단하고 caller/event loop에 제어를 돌려주는 동작입니다.", detail: ["thread blocking이 아닙니다.", "continuation은 비동기입니다."] },
        { term: "structured sequencing", definition: "dependency가 있는 operations는 sequential await, 독립 operations는 explicit aggregate/concurrency policy로 ownership을 표현하는 방식입니다.", detail: ["오류 범위를 명확히 합니다.", "불필요한 waterfall을 피합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "try/catch 안에서 `startAsync()`를 호출했는데 await하지 않아 rejection을 잡지 못한다.", likelyCause: "Promise가 현재 async control flow에 연결되지 않은 floating operation이 됐습니다.", checks: ["call에 await/return/void+owned error handler가 있는지 봅니다.", "function return type과 linter를 확인합니다.", "fire-and-forget의 lifecycle/error owner를 찾습니다."], fix: "dependency면 await/return하고 의도적 background task면 명시 helper가 catch/report/cancel lifecycle을 소유하게 합니다.", prevention: "no-floating-promises와 background task registry/cleanup test를 둡니다." },
      ],
    },
    {
      id: "unhandled-observability-testing",
      title: "Unhandled rejection은 최종 안전망 신호이지 application error handling 전략이 아닙니다",
      lead: "모든 Promise branch에 owner를 두고 global event에는 최소한의 redacted 진단만 남깁니다.",
      explanations: [
        "browser host는 rejected Promise에 handler가 없는지 추적해 unhandledrejection event를 report할 수 있고 나중 handler가 붙으면 rejectionhandled가 이어질 수 있습니다. report timing은 microtask/host tracking과 연결되므로 즉시 synchronous throw처럼 생각하지 않습니다.",
        "global unhandledrejection listener에서 preventDefault로 console만 조용히 하면 실제 결함을 숨길 수 있습니다. 최종 telemetry와 crash/failure boundary로 사용하되 기능별 catch/retry/user recovery는 local owner가 처리합니다.",
        "rejection reason에 request body, token, 개인정보, 전체 response를 넣거나 global log로 serialize하지 않습니다. Error code/name, operation, sanitized cause와 correlation ID만 수집하고 user message는 별도 mapping합니다.",
        "test는 fulfilled/rejected/thenable/throw/missing return/catch recovery/finally failure/combinator empty/cancel race를 포함합니다. 실제 sleep/prompt/network 대신 injected callback/clock/fake response로 settlement를 제어합니다.",
        "Promise test가 끝났다고 assertion function이 return하기 전에 Promise를 return/await해야 합니다. test runner가 chain을 모르면 rejection이 다음 test에 나타나거나 false pass할 수 있습니다.",
        "DevTools async stack과 operation trace는 원인 연결을 돕지만 production code는 Error cause와 named stages를 보존합니다. catch에서 새 Error를 만들 때 original을 cause로 연결해 root를 잃지 않습니다.",
      ],
      concepts: [
        { term: "unhandled rejection", definition: "host가 적절한 rejection handler 없이 남았다고 판단한 rejected Promise에 대해 보고하는 상태/event입니다.", detail: ["local handling을 대체하지 않습니다.", "later handler가 붙을 수 있습니다."] },
        { term: "floating Promise", definition: "caller가 await/return/chain/catch하거나 명시적 background owner에 등록하지 않아 completion과 error가 관리되지 않는 Promise입니다.", detail: ["unhandled 위험이 있습니다.", "lifecycle/cancel도 잃습니다."] },
        { term: "error cause chain", definition: "higher-level Error가 lower-level original error를 cause로 보존해 abstraction context와 root cause를 함께 전달하는 구조입니다.", detail: ["secret을 redaction합니다.", "retry/user message classification을 둡니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "테스트는 통과했는데 잠시 뒤 unhandled rejection이 다음 테스트에서 발생한다.", likelyCause: "test가 Promise를 return/await하지 않거나 nested/floating Promise의 settlement를 기다리지 않았습니다.", checks: ["test callback return과 awaits를 확인합니다.", "then handler 내부 Promise return 누락을 찾습니다.", "fake scheduler pending jobs/unhandled listeners를 검사합니다."], fix: "모든 async work를 test Promise chain에 연결하고 rejection assertion을 await하며 종료 시 pending operations 0을 확인합니다.", prevention: "no-floating static analysis와 unhandled rejection fail-fast test harness를 둡니다." },
      ],
      expertNotes: [
        "Promise reactions를 무한 chain으로 enqueue하면 microtask starvation이 가능합니다. Promise를 썼다는 이유로 CPU work가 thread 밖으로 이동하지 않습니다.",
        "Unhandled rejection 정책은 browser/Node/test runner마다 다를 수 있어 runtime 공식 문서와 deployment configuration을 확인합니다.",
        "대량 작업을 Promise.all로 한꺼번에 시작하면 memory/socket/rate limit을 소진할 수 있습니다. bounded concurrency queue와 backpressure를 설계합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 prompt Promise를 취소·timeout·검증·오류 관측이 가능한 비동기 입력 검증 pipeline으로 재구축하기",
    scenario: "현재 예제는 2초 뒤 blocking prompt를 열고 문자열 reason을 reject합니다. prompt 취소/null과 input validation을 섞고, sibling catch·timeout cleanup·AbortSignal·loading state·deterministic test가 없습니다.",
    setup: [
      "원본 day09 ex10/ex11 Promise 파일 2개를 read-only evidence로 준비합니다.",
      "prompt 대신 injected `readInput({signal})` callback adapter와 fake timer/input outcomes를 준비합니다.",
      "hello/다른 값/empty/null, synchronous registration throw, delayed success/failure, abort/timeout race fixture를 준비합니다.",
      "browser unhandledrejection fail harness와 privacy-safe operation trace를 준비합니다.",
    ],
    steps: [
      "executor synchronous order와 pending→fulfilled/rejected, first settlement를 exact trace로 확인합니다.",
      "callback input adapter를 Promise로 감싸 one-shot finish가 cleanup·Error reject·AbortSignal을 처리하게 합니다.",
      "trim/validation은 named then stage에서 value를 return하고 invalid는 ValidationError를 throw합니다.",
      "다음 stage는 transformed value/Promise를 반드시 return하고 missing-return regression을 작성합니다.",
      "catch에서 abort/validation/operational/programmer error를 분류해 recover/rethrow/user message를 결정합니다.",
      "finally에서 timer/listener/loading을 generation-safe하게 정리하고 cleanup rejection policy를 test합니다.",
      "independent validators에는 allSettled, required dependencies에는 all, fallback sources에는 any를 적용합니다.",
      "async/await 버전을 같은 observable output으로 구현하고 floating Promise/unhandled rejection을 0으로 만듭니다.",
    ],
    expectedResult: [
      "executor와 handlers의 sync/microtask 순서, then return/throw/adoption 결과가 exact output과 일치합니다.",
      "성공·검증 실패·operation 실패·abort·timeout마다 Promise는 한 번 settle되고 listeners/timers는 0입니다.",
      "catch는 복구 가능한 오류만 value로 전환하고 나머지는 cause를 보존해 전파합니다.",
      "finally는 원래 outcome을 보존하며 overlapping operation의 newer loading state를 끄지 않습니다.",
      "combinator 정책이 partial/fail-fast/fallback 요구와 일치하고 losers의 underlying work를 명시 취소합니다.",
      "tests는 prompt/network/sleep 없이 deterministic하며 log에 입력값·token·raw Error data가 없습니다.",
    ],
    cleanup: ["AbortController를 abort하고 timer/listener/fake callbacks 및 unhandled test listener를 제거합니다.", "synthetic input/errors, DevTools Promise references와 telemetry fixtures를 삭제합니다."],
    extensions: ["callback adapter에 progress EventTarget을 별도 channel로 추가해 Promise single completion과 분리합니다.", "bounded-concurrency validator pool과 allSettled report를 구현합니다.", "fetch pipeline에 AbortSignal timeout, response schema validation과 retry/idempotency를 연결합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 성공/실패 Promise를 executor·microtask·first settlement trace와 Error reason으로 다시 작성하세요.", requirements: ["executor/sync/then/timer order를 기록합니다.", "resolve 뒤 reject와 throw가 결과를 바꾸는지 확인합니다.", "문자열 reject를 Error subclass로 바꿉니다.", "same original sibling과 returned chain catch 차이를 재현합니다."], hints: ["executor는 즉시 실행됩니다.", "then callback은 settled Promise에도 microtask입니다."], expectedOutcome: "Promise state/fate와 handler scheduling을 exact output으로 설명하고 올바른 chain에 오류를 연결합니다.", solutionOutline: ["각 Promise에 P0/P1 ID를 붙여 graph를 그립니다.", "state와 handler queue를 시간 순서로 기록합니다."] },
    { difficulty: "응용", prompt: "누락 return·catch recovery·finally cleanup이 검증되는 입력 validation pipeline을 구현하세요.", requirements: ["각 then이 plain value 또는 Promise를 return합니다.", "ValidationError/AbortError/operational error를 분류합니다.", "복구 가능한 default만 catch에서 return하고 나머지는 cause와 rethrow합니다.", "finally에서 loading/timer/listener를 idempotent하게 정리합니다.", "fake inputs로 success/failure/abort/race를 test합니다."], hints: ["catch의 정상 return은 fulfilled recovery입니다.", "finally throw는 original outcome을 덮습니다."], expectedOutcome: "모든 branches가 한 terminal owner로 연결되고 unhandled/floating Promise와 resource leak이 없습니다.", solutionOutline: ["stage별 input/output/error table을 만듭니다.", "one-shot finish와 generation guard를 구현합니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 Promise·async error·cancellation·concurrency 표준을 설계하세요.", requirements: ["return/throw/thenable/catch/finally contract를 정의합니다.", "Error taxonomy·cause·user message·privacy telemetry를 포함합니다.", "AbortSignal/timeout/loser cleanup과 background task ownership을 정합니다.", "all/allSettled/race/any 및 bounded concurrency 선택표를 만듭니다.", "unhandled/floating/fake dependency/empty/race test gate를 설계합니다."], hints: ["Promise.race는 loser를 취소하지 않습니다.", "Promise.all은 work concurrency limit이 아닙니다."], expectedOutcome: "팀이 swallowed errors·missing return·unhandled rejection·request leak 없이 비동기 기능을 구현하는 운영 표준이 완성됩니다.", solutionOutline: ["Promise graph와 underlying resource lifecycle을 별도로 그립니다.", "각 terminal outcome에 owner/cleanup/telemetry를 배정합니다."] },
  ],
  reviewQuestions: [
    { question: "Promise의 세 state는 무엇인가요?", answer: "pending, fulfilled, rejected이며 fulfilled/rejected를 settled라고 합니다." },
    { question: "resolved와 fulfilled는 항상 같은 뜻인가요?", answer: "아닙니다. 다른 pending Promise를 채택해 fate는 resolved지만 state는 아직 pending일 수 있습니다." },
    { question: "Promise executor는 비동기로 호출되나요?", answer: "아닙니다. constructor 중 즉시 동기 호출되고 reactions가 microtask로 실행됩니다." },
    { question: "resolve를 호출하면 executor의 다음 lines가 중단되나요?", answer: "아닙니다. executor는 return/throw까지 계속되지만 이후 settlement 호출은 결과를 바꾸지 않습니다." },
    { question: "then은 original Promise를 수정하나요?", answer: "아닙니다. 항상 새 Promise를 반환하고 handler completion이 새 결과를 결정합니다." },
    { question: "then handler에서 return을 생략하면 다음 value는 무엇인가요?", answer: "implicit undefined가 반환되어 다음 Promise가 undefined로 fulfilled됩니다." },
    { question: "catch가 value를 return하면 chain은 계속 rejected인가요?", answer: "아닙니다. 정상 return value로 fulfilled되어 복구되고 이후 fulfillment then이 실행됩니다." },
    { question: "같은 original의 sibling catch가 then handler throw를 잡나요?", answer: "아닙니다. then이 반환한 새 Promise에 catch를 연결해야 합니다." },
    { question: "finally의 정상 return value가 original fulfillment value를 바꾸나요?", answer: "보통 바꾸지 않고 original outcome을 통과시킵니다. throw/rejected return은 override합니다." },
    { question: "Promise.all result order는 completion order인가요?", answer: "아닙니다. 모든 성공 시 input order를 보존합니다." },
    { question: "Promise.race timeout이 fetch를 자동 abort하나요?", answer: "아닙니다. loser/underlying work는 AbortSignal 등으로 별도 취소해야 합니다." },
    { question: "await는 main thread를 block하나요?", answer: "아닙니다. async function을 suspend하고 Promise settlement 뒤 continuation을 실행합니다." },
  ],
  completionChecklist: [
    "pending·fulfilled·rejected·settled와 resolved fate를 구분했다.",
    "Promise single completion과 multi-event/progress abstraction을 분리했다.",
    "executor synchronous 실행과 reaction microtask 순서를 exact output으로 검증했다.",
    "first settlement, executor throw와 Error rejection reason을 처리했다.",
    "then마다 새 Promise를 표시하고 handler return/undefined/Promise/thenable/throw 결과를 추적했다.",
    "누락 return과 nested/floating Promise를 lint·type·timing test로 차단했다.",
    "sibling branch와 dependency chain을 구분해 올바른 returned Promise에 catch를 연결했다.",
    "catch recovery와 rethrow를 error taxonomy에 따라 결정하고 cause를 보존했다.",
    "finally pass-through/override와 generation-safe resource cleanup을 test했다.",
    "all/allSettled/race/any의 failure·order·empty·loser semantics를 요구에 맞게 선택했다.",
    "callback wrapping에서 single finish·unsubscribe·timer clear·Error reject를 보장했다.",
    "AbortSignal로 underlying work를 취소하고 Promise.race loser를 정리했다.",
    "async/await sequential/concurrent ownership과 floating background task를 관리했다.",
    "unhandled rejection을 final safety telemetry로만 사용하고 secret/user data를 redaction했다.",
    "fake dependencies로 모든 settlement/race를 arbitrary sleep 없이 검증했다.",
  ],
  nextSessions: [],
  sources: [
    { id: "web-promise-basic-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex10_promise.html", usedFor: ["Promise definition comments", "constructor", "resolve/reject", "success boolean", "then/catch", "string messages", "sibling branches"], evidence: "success boolean에 따라 resolve/reject하고 then/catch를 별도로 등록하는 원본을 state/fate·Error reason·returned-chain catch와 microtask 모델로 확장했습니다." },
    { id: "web-promise-input-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex11_promise.html", usedFor: ["timer inside Promise", "delayed prompt", "input success/failure", "then-catch-finally chain", "common cleanup message"], evidence: "2초 뒤 prompt 값을 검사하는 원본을 injected input·validation Error·AbortSignal·timeout·finally cleanup과 deterministic test pipeline으로 확장했습니다." },
    { id: "tc39-promise-objects", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-promise-objects", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-objects", usedFor: ["Promise internal state/result/reactions", "fulfill/reject", "resolution", "jobs", "single settlement"], evidence: "Promise state·reaction records와 resolution procedure를 모든 chain/state 설명의 normative 기준으로 사용했습니다." },
    { id: "tc39-promise-constructor", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-promise-constructor", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-constructor", usedFor: ["executor synchronous call", "resolve/reject functions", "executor throw", "return ignored", "constructor requirements"], evidence: "executor가 즉시 실행되고 synchronous throw가 rejection으로 변환되는 exact example과 wrapper boundary의 기준으로 사용했습니다." },
    { id: "tc39-promise-then", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-promise.prototype.then", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.prototype.then", usedFor: ["then new Promise", "fulfill/reject handlers", "value/reason forwarding", "reaction jobs", "return/throw chaining"], evidence: "handler completion마다 새 Promise value/reason이 결정되는 chain과 sibling branch 차이의 기준으로 사용했습니다." },
    { id: "tc39-promise-finally", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-promise.prototype.finally", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.prototype.finally", usedFor: ["finally callback", "value/reason pass-through", "cleanup promise", "throw/reject override"], evidence: "공통 cleanup이 original outcome을 보존하고 cleanup failure가 override하는 semantics의 기준으로 사용했습니다." },
    { id: "tc39-promise-combinators", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-promise.all", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.all", usedFor: ["Promise.all", "allSettled", "race", "any", "AggregateError", "input order/empty iterable"], evidence: "네 composition policies의 exact output·failure/empty/ordering 선택 기준을 current ECMAScript algorithms로 보강했습니다." },
    { id: "tc39-async-functions", repository: "Ecma International TC39", path: "control-abstraction-objects.html#sec-async-function-objects", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-async-function-objects", usedFor: ["async function Promise return", "await suspension", "return/throw", "continuation", "sequential/concurrent composition"], evidence: "async/await이 Promise meaning을 바꾸지 않는 syntax/control abstraction임을 연결하는 기준으로 사용했습니다." },
    { id: "html-microtasks", repository: "WHATWG HTML Standard", path: "webappapis.html#microtask-queuing", publicUrl: "https://html.spec.whatwg.org/multipage/webappapis.html#microtask-queuing", usedFor: ["microtask queue/checkpoint", "Promise reaction timing", "timer order", "starvation", "exception reporting"], evidence: "settled Promise handler도 synchronous stack 뒤 microtask에서 실행되는 browser exact order를 JS08 event-loop model과 연결했습니다." },
    { id: "html-unhandled-rejections", repository: "WHATWG HTML Standard", path: "webappapis.html#unhandled-promise-rejections", publicUrl: "https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections", usedFor: ["unhandled promise rejection tracking", "rejectionhandled", "global events", "host reporting", "privacy"], evidence: "floating/unhandled Promise를 local error strategy와 구분하고 final telemetry로 다루는 browser host model의 기준으로 사용했습니다." },
    { id: "dom-abort", repository: "WHATWG DOM Standard", path: "#aborting-ongoing-activities", publicUrl: "https://dom.spec.whatwg.org/#aborting-ongoing-activities", usedFor: ["AbortController", "AbortSignal", "abort reason", "already aborted", "underlying operation cleanup", "listener lifecycle"], evidence: "Promise 자체 settlement와 underlying asynchronous activity cancellation을 분리하고 timeout/race loser를 정리하는 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 2,
    filesUsed: 2,
    uncoveredNotes: [
      "원본 두 파일은 resolve/reject와 then/catch/finally, timer-delayed input을 직접 제공합니다. state versus fate, thenable adoption, returned-chain graph, missing return, combinators, AbortSignal과 unhandled tracking은 ECMAScript/WHATWG 표준으로 보강했습니다.",
      "원본 reject 이유는 문자열이고 prompt는 blocking/suppression/null 문제를 가집니다. 공개 수업은 Error taxonomy와 injected input adapter로 바꿔 결정론적·복구 가능한 실행을 제공합니다.",
      "실제 fetch Response/HTTP status/JSON parsing과 AbortController network 적용은 js-10에서 이 Promise/error/cancellation model 위에 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
