import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-05-dom-query-traversal"],
  slug: "js-05-dom-query-traversal",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 5,
  title: "DOM 노드 조회·collection·관계 탐색과 안전한 경계",
  subtitle: "HTML parser가 만든 Document tree에서 Element와 Text를 구분하고, selector 결과의 null·정적/live collection·detached reference까지 추적합니다.",
  level: "중급",
  estimatedMinutes: 265,
  coreQuestion: "DOM tree에서 원하는 node를 최소 결합으로 찾고, 문서가 변해도 collection과 parent/child/sibling 관계를 안전하게 순회하려면 어떤 API와 불변식을 선택해야 할까요?",
  summary: "원본 section>article 세 개와 msg/res 예제를 DOM tree/query mental model로 확장합니다. HTML source와 parser가 만든 Document/Element/Text/Comment node tree가 항상 같은 들여쓰기 그림이 아니며 browser error recovery가 node를 재배치할 수 있음을 다룹니다. getElementById·getElementsByClassName/TagName과 querySelector/All을 root scope·CSS selector·null/empty·SyntaxError 기준으로 비교합니다. querySelectorAll static NodeList와 getElementsBy... live HTMLCollection을 mutation 전후 exact output으로 증명합니다. childNodes/firstChild/nextSibling의 모든 node와 children/firstElementChild/nextElementSibling의 element-only traversal, parentElement/closest/matches/contains/getRootNode를 실행합니다. textContent/innerText/innerHTML read 차이와 layout flush·XSS 경계를 예고하고, caching·detached/stale reference·Shadow DOM·MutationObserver·query performance를 owner/lifecycle 관점에서 정리합니다. 마지막에는 required query helper와 optional/collection state, semantic selector contract와 DOM tree inspector를 완성합니다.",
  objectives: [
    "HTML source token과 parser가 만든 Document·Element·Text·Comment node tree를 구분해 실제 parent/child 관계를 그릴 수 있다.",
    "getElementById/getElementsByClassName/TagName과 querySelector/All의 root·selector·return/null/collection 차이를 선택할 수 있다.",
    "selector SyntaxError, dynamic user selector injection과 duplicate id를 진단하고 stable semantic hook을 설계할 수 있다.",
    "querySelectorAll static NodeList와 live HTMLCollection이 DOM mutation 뒤 어떻게 달라지는지 예측할 수 있다.",
    "Node-level childNodes/firstChild/sibling과 Element-level children/firstElementChild/sibling을 whitespace text 포함 여부로 구분할 수 있다.",
    "parentElement·closest·matches·contains·getRootNode를 사용해 구조 결합을 제한하고 delegation boundary를 확인할 수 있다.",
    "null/detached/stale reference와 repeated query·layout-dependent read를 lifecycle/performance test로 관리할 수 있다.",
  ],
  prerequisites: [
    { title: "DOM 이벤트 등록·전파와 위임", reason: "event target/currentTarget에서 시작해 stable container와 actionable descendant를 query/traverse하는 API를 깊게 학습합니다.", sessionSlug: "js-03-event-model-listeners" },
    { title: "CSS 조합·속성·pseudo selector", reason: "querySelector가 CSS selector grammar와 tree matching을 재사용하므로 compound/complex selector 의미를 알고 있습니다.", sessionSlug: "css-03-combinators-attributes-pseudo" },
    { title: "HTML 문서 구조와 DOM tree", reason: "parser가 element/text/comment node와 document tree를 만드는 기초를 JavaScript API로 다시 관찰합니다.", sessionSlug: "html-01-document-anatomy-dom-tree" },
  ],
  keywords: ["DOM", "Document", "Node", "Element", "Text", "querySelector", "querySelectorAll", "getElementById", "NodeList", "HTMLCollection", "static", "live", "childNodes", "children", "closest", "matches", "contains", "getRootNode", "detached node", "Shadow DOM"],
  chapters: [
    {
      id: "source-parser-node-tree",
      title: "DOM은 HTML 문자열 목록이 아니라 parser가 만든 typed node tree입니다",
      lead: "들여쓰기와 tag 모양만 보고 child 수를 세지 말고 nodeType·nodeName·parentNode를 실제로 관찰합니다.",
      explanations: [
        "HTML parser는 source token을 읽어 Document 아래 html/head/body와 Element·Text·Comment 등 node를 만듭니다. 일부 element는 source에 생략되어도 implied 생성되고 invalid nesting은 tree-construction error recovery로 재배치될 수 있습니다.",
        "Element는 tag name/namespace/attribute와 child node를 가진 Node subtype입니다. text는 Element property가 아니라 Text node로 존재합니다. source의 newline과 indentation spaces도 Text node가 되어 childNodes에 포함될 수 있습니다.",
        "Document는 page tree root 역할을 하지만 documentElement는 html Element이고 body/head는 해당 descendants입니다. DocumentFragment와 ShadowRoot도 별도 root/tree 경계입니다.",
        "nodeType은 ELEMENT_NODE=1, TEXT_NODE=3, COMMENT_NODE=8, DOCUMENT_NODE=9 등으로 종류를 구분합니다. nodeName은 element/tag/text에 따라 표현이 달라지고 namespace-aware code는 localName/namespaceURI를 봅니다.",
        "원본 `#wrap` 아래 article 세 개 사이 줄바꿈은 element children 외 Text node를 만듭니다. children length는 3이지만 childNodes length는 source whitespace에 따라 7 등 더 클 수 있습니다.",
        "DOM tree와 CSS box/accessibility tree는 같지 않습니다. display:none, pseudo-element, generated box, role/aria와 browser correction이 별도 representation을 만듭니다. query API는 주로 DOM node tree를 봅니다.",
      ],
      concepts: [
        { term: "DOM node", definition: "Document tree에 참여하는 Node interface 계열 object로 Element·Text·Comment·Document 등이 있습니다.", detail: ["각 node type이 다릅니다.", "parent/children/sibling 관계를 가집니다."] },
        { term: "tree construction", definition: "HTML parser가 token과 error-recovery 규칙으로 DOM node parent/child 관계를 만드는 단계입니다.", detail: ["source indentation과 별개입니다.", "implied/reparented element가 생길 수 있습니다."] },
        { term: "tree root", definition: "parent가 없는 tree의 최상위 node로 document, fragment, shadow root 등이 될 수 있습니다.", detail: ["query scope에 영향 줍니다.", "getRootNode로 확인합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "`ul.childNodes.length`가 li 개수보다 크다.", likelyCause: "HTML indentation newline/spaces가 Text node로 포함됐습니다.", checks: ["childNodes를 nodeType/nodeName/JSON.stringify(textContent)로 출력합니다.", "children length와 비교합니다.", "source whitespace와 parser-created nodes를 확인합니다."], fix: "element만 필요하면 children/firstElementChild/nextElementSibling을 사용하고 text processing이면 whitespace policy를 명시합니다.", prevention: "pretty/minified markup 둘 다 traversal test하고 node/element API 선택을 code review에 기록합니다." },
      ],
    },
    {
      id: "query-apis-root-return-contract",
      title: "query API는 검색 root·matching language·단일/collection return contract로 선택합니다",
      lead: "ID라서 querySelector, class라서 getElements...처럼 외우지 않고 호출자가 어떤 결과 상태를 처리할지 정합니다.",
      explanations: [
        "document.getElementById(id)는 Document에서 해당 ID value의 element를 하나 반환하거나 null입니다. ID는 document에서 unique하도록 HTML을 고치고 duplicate ID가 있을 때 어느 element가 반환될지 application logic으로 기대하지 않습니다.",
        "querySelector(selectors)는 Document/Element/DocumentFragment root 아래 selector와 match하는 첫 Element 또는 null을 반환합니다. querySelectorAll은 matching Elements를 tree order의 static NodeList로 반환하며 0개도 empty collection이지 null이 아닙니다.",
        "getElementsByClassName과 getElementsByTagName은 Document뿐 아니라 Element root에도 있고 live HTMLCollection을 반환합니다. 이름은 ‘array’가 아니며 Array method 전체가 없고 mutation에 반응합니다.",
        "Element root의 querySelector는 descendants를 찾지만 selector 전체의 scoping semantics를 이해합니다. immediate child만 찾을 때 `:scope > .item`을 사용해 nested item을 섞지 않습니다.",
        "단일 required node는 `requireElement(root,selector)`처럼 missing에서 context가 있는 error를 내고, optional UI는 null branch, 복수 결과는 empty state를 명시합니다. 무조건 optional chaining으로 기능을 조용히 끄지 않습니다.",
        "원본 `querySelectorAll('#box3')`은 ID 하나인데도 NodeList를 반환합니다. API가 항상 collection을 반환하는 것과 HTML ID uniqueness는 별도입니다. required one이라면 querySelector/getElementById가 의도를 더 잘 드러냅니다.",
      ],
      concepts: [
        { term: "query root", definition: "selector/collection search가 시작되고 결과가 제한되는 Document·Element·DocumentFragment입니다.", detail: ["global document query를 줄입니다.", "component boundary를 만듭니다."] },
        { term: "single-query null", definition: "querySelector/getElementById가 일치 element가 없을 때 반환하는 null 상태입니다.", detail: ["required/optional 정책이 필요합니다.", "property 접근 전 처리합니다."] },
        { term: "empty collection", definition: "복수 query가 일치 0개일 때 길이 0인 collection을 반환하는 정상 상태입니다.", detail: ["null과 다릅니다.", "for...of는 0회 실행됩니다."] },
      ],
      codeExamples: [
        {
          id: "dom-query-contracts",
          title: "ID·first·all·compound·missing 결과 비교",
          language: "html",
          filename: "dom-queries.html",
          purpose: "원본 wrap/article 세 개를 사용해 단일 null과 static collection empty, CSS complex selector 결과를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>DOM queries</title></head>\n<body><section id=\"wrap\">\n  <article class=\"box\" id=\"box1\">TEXT1</article>\n  <article class=\"box featured\" id=\"box2\">TEXT2</article>\n  <article class=\"box\" id=\"box3\">TEXT3</article>\n</section><pre id=\"out\"></pre>\n<script>\n  const wrap = document.getElementById('wrap');\n  const all = wrap.querySelectorAll(':scope > article.box');\n  document.querySelector('#out').textContent = [\n    `id=${document.getElementById('box1').id}`,\n    `first=${wrap.querySelector('.box').id}`,\n    `all=${all.length}`,\n    `compound=${wrap.querySelector('article.box.featured').id}`,\n    `missing=${wrap.querySelector('.missing')}`,\n    `all-missing=${wrap.querySelectorAll('.missing').length}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-7", explanation: "wrap direct child article 세 개와 featured state를 선언합니다." },
            { lines: "10-11", explanation: "ID로 root를 찾고 :scope direct-child selector의 static NodeList를 얻습니다." },
            { lines: "12-19", explanation: "ID/first/all/compound와 missing single/collection을 stable string/count로 출력합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 dom-queries.html을 열고 결과 확인" },
          output: { value: "id=box1\nfirst=box1\nall=3\ncompound=box2\nmissing=null\nall-missing=0", explanation: ["querySelector는 tree order의 첫 box1을 반환합니다.", "querySelectorAll은 세 개 또는 empty NodeList를 반환합니다.", "단일 missing은 null로 string interpolation됩니다."] },
          experiments: [
            { change: "box1 앞에 nested `.box`를 wrap 안 다른 div에 추가합니다.", prediction: "wrap.querySelector('.box')는 새 nested box가 첫 tree-order면 달라지지만 :scope>article collection은 3개를 유지합니다.", result: "selector가 intended structural boundary를 표현해야 합니다." },
            { change: "box2에도 id=box1을 중복 부여합니다.", prediction: "HTML conformance가 깨지고 ID query 의존 결과가 모호해집니다.", result: "duplicate id를 build/test에서 차단합니다." },
            { change: "invalid selector `article[`를 querySelector에 전달합니다.", prediction: "null이 아니라 SyntaxError DOMException을 throw합니다.", result: "selector syntax failure와 no match를 구분합니다." },
          ],
          sourceRefs: ["web-dom-overview-source", "web-dom-query-source", "dom-standard", "selectors-4"],
        },
      ],
      diagnostics: [
        { symptom: "Cannot read properties of null (reading 'textContent')가 난다.", likelyCause: "단일 query no-match/null을 required element처럼 즉시 사용했거나 script timing/root/selector가 틀렸습니다.", checks: ["query return과 root/selector를 console assertion합니다.", "script defer/module/DOM readiness를 확인합니다.", "ID duplicate/typo와 component가 route에 존재하는지 봅니다."], fix: "required helper로 context error를 내거나 optional state를 명시적으로 분기하고 selector/root/timing을 교정합니다.", prevention: "route/state별 required selector smoke test와 strict null typecheck를 둡니다." },
      ],
    },
    {
      id: "selector-syntax-scope-injection",
      title: "querySelector는 CSS selector parser를 사용하므로 invalid syntax와 dynamic value escaping을 처리합니다",
      lead: "사용자 문자열을 `#${value}`에 바로 넣으면 no-match가 아니라 SyntaxError나 의도하지 않은 selector가 될 수 있습니다.",
      explanations: [
        "querySelector(All) argument는 selector list로 parse됩니다. invalid selector는 SyntaxError DOMException을 throw하고 valid but no-match는 null/empty collection입니다. try/catch를 no-match 처리로 뭉치지 않습니다.",
        "CSS ID/class identifier에 dynamic value를 넣어야 하면 CSS.escape를 사용해 identifier token으로 escape합니다. attribute selector quoted value 조립은 별도 string/selector escaping이 필요해 stable ID를 getElementById로 찾거나 data collection을 query 후 property equality로 filter하는 편이 안전할 수 있습니다.",
        "selector injection은 JavaScript code execution과 동일하진 않지만 공격자가 예상보다 넓은 node/secret-bearing input을 선택하게 해 logic/privacy 문제를 만들 수 있습니다. user selector 기능은 allowlisted grammar/root/result count를 제한합니다.",
        "`:scope`는 Element query의 reference element를 명시해 direct child/relative 구조를 표현합니다. `.component .item` 같은 global structural selector를 component root의 `:scope > [data-role=item]`으로 좁힙니다.",
        "CSS presentation class를 JS hook으로 쓰면 redesign에서 기능이 깨집니다. id, data-role/data-action 또는 component ref처럼 semantic/stable hook을 정하고 CSS class와 ownership을 문서화합니다.",
        "복잡한 :has/:nth-child selector로 domain state를 매번 탐색하기보다 state/store에서 record를 찾고 DOM은 render result로 취급할 수 있습니다. selector power와 maintainability를 균형 있게 씁니다.",
      ],
      concepts: [
        { term: "selector SyntaxError", definition: "query API의 selector string이 Selectors grammar로 parse되지 않을 때 throw되는 DOMException입니다.", detail: ["no-match null과 다릅니다.", "dynamic selector를 검증합니다."] },
        { term: ":scope", definition: "scoped selector evaluation에서 reference/scoping root element를 나타내는 pseudo-class입니다.", detail: ["direct child query에 유용합니다.", "component root 결합을 줄입니다."] },
        { term: "semantic query hook", definition: "presentation 변화와 분리해 JS/automation이 element 역할을 찾도록 정한 id/data-role/ref contract입니다.", detail: ["ownership을 문서화합니다.", "중복/유일성 규칙이 필요합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "사용자 입력이 `a]`일 때 querySelector가 null 대신 SyntaxError로 UI 전체를 멈춘다.", likelyCause: "dynamic input을 selector token에 직접 삽입했습니다.", checks: ["최종 selector string과 stack을 안전하게 기록합니다.", "input이 identifier/attribute value/full selector 중 어떤 contract인지 확인합니다.", "getElementById/Map lookup으로 대체 가능한지 봅니다."], fix: "full selector 입력을 허용하지 말고 stable key lookup을 사용하거나 context에 맞는 escaping/allowlist와 try/catch error state를 적용합니다.", prevention: "quote/bracket/hash/backslash/Unicode dynamic key adversarial test를 둡니다." },
      ],
    },
    {
      id: "static-nodelist-live-htmlcollection",
      title: "querySelectorAll NodeList는 query 시점 snapshot이고 getElementsBy... HTMLCollection은 DOM 변화에 live입니다",
      lead: "둘 다 for...of가 가능해 보여도 mutation loop의 길이와 element가 달라질 수 있습니다.",
      explanations: [
        "querySelectorAll은 static NodeList를 반환해 이후 matching element를 append/remove해도 같은 collection membership이 자동 갱신되지 않습니다. node object 자체 property 변화는 같은 reference에서 보일 수 있습니다.",
        "getElementsByClassName/TagName과 element.children은 live HTMLCollection이라 tree가 바뀌면 length/index/named property가 즉시 반영됩니다. loop 중 remove/add하면 index가 당겨져 item을 건너뛸 수 있습니다.",
        "NodeList/HTMLCollection은 Array가 아닙니다. forEach 지원은 collection 종류/runtime에 따라 확인하고 map/filter가 필요하면 `Array.from(collection)` 또는 spread로 snapshot array를 만듭니다.",
        "live collection이 자동 reactive state manager라는 뜻은 아닙니다. query 조건/DOM mutation마다 access cost와 예측 복잡성이 있어 rendering code에서는 explicit state/snapshot을 선호합니다.",
        "static NodeList에 detached element reference가 남으면 DOM에서 제거됐어도 collection과 code reference가 살아 있는 동안 object에 접근할 수 있습니다. isConnected/getRootNode와 lifecycle을 확인합니다.",
        "mutation observer는 DOM 변경 record를 microtask timing으로 관찰하는 별도 API이며 live collection과 다릅니다. third-party mutation integration에서만 사용하고 own render는 explicit state transition으로 관리합니다.",
      ],
      concepts: [
        { term: "static NodeList", definition: "querySelectorAll 호출 시 matching element 집합을 고정한 collection입니다.", detail: ["이후 membership이 자동 갱신되지 않습니다.", "각 node reference는 살아 있습니다."] },
        { term: "live HTMLCollection", definition: "관련 root tree의 현재 matching elements를 access 시 반영하는 collection입니다.", detail: ["DOM mutation 뒤 length/index가 변합니다.", "mutation loop를 조심합니다."] },
        { term: "collection snapshot", definition: "live/static collection을 Array.from/spread로 현재 순서의 일반 array에 복사한 값입니다.", detail: ["안정적 iteration에 씁니다.", "node object 자체는 deep copy되지 않습니다."] },
      ],
      codeExamples: [
        {
          id: "static-versus-live-collection",
          title: "element append 전후 static/live membership 비교",
          language: "html",
          filename: "dom-collections.html",
          purpose: "같은 `.box` 조건에서 querySelectorAll과 getElementsByClassName이 DOM append 후 각각 2/3으로 달라지는 exact output을 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>DOM collections</title></head>\n<body><section id=\"wrap\"><article class=\"box\" id=\"a\">A</article><article class=\"box\" id=\"b\">B</article></section><pre id=\"out\"></pre>\n<script>\n  const wrap = document.querySelector('#wrap');\n  const staticBoxes = wrap.querySelectorAll('.box');\n  const liveBoxes = wrap.getElementsByClassName('box');\n  const before = `before=${staticBoxes.length}/${liveBoxes.length}`;\n  const added = document.createElement('article');\n  added.className = 'box'; added.id = 'c'; added.textContent = 'C';\n  wrap.append(added);\n  const after = `after=${staticBoxes.length}/${liveBoxes.length}`;\n  document.querySelector('#out').textContent = [before, after, `static=${[...staticBoxes].map(node => node.id).join(',')}`, `live=${[...liveBoxes].map(node => node.id).join(',')}`].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3", explanation: "초기 box A/B 두 개와 root를 만듭니다." },
            { lines: "5-8", explanation: "동일 root/조건으로 static NodeList와 live HTMLCollection 및 초기 길이를 얻습니다." },
            { lines: "9-12", explanation: "새 matching article C를 DOM에 append합니다." },
            { lines: "13-14", explanation: "append 후 length와 각 collection membership ID를 snapshot해 출력합니다." },
          ],
          run: { environment: ["modern browser"], command: "browser에서 dom-collections.html을 열고 결과 확인" },
          output: { value: "before=2/2\nafter=2/3\nstatic=a,b\nlive=a,b,c", explanation: ["static query 결과에는 C가 추가되지 않습니다.", "live collection은 DOM의 현재 세 box를 반영합니다.", "필요한 semantics를 모르고 두 API를 바꾸면 mutation behavior가 달라집니다."] },
          experiments: [
            { change: "C append 뒤 새 querySelectorAll을 호출합니다.", prediction: "새 static NodeList는 a,b,c 세 개입니다.", result: "static은 영원히 과거라는 뜻이 아니라 각 query 시점 snapshot입니다." },
            { change: "for(let i=0;i<liveBoxes.length;i++) wrap.removeChild(liveBoxes[i])를 실행합니다.", prediction: "collection이 줄며 index가 당겨져 일부 element를 건너뜁니다.", result: "mutation 전 Array.from snapshot 또는 뒤에서 순회합니다." },
            { change: "B의 class box를 제거합니다.", prediction: "live는 즉시 a,c가 되지만 기존 static membership에는 b reference가 남습니다.", result: "matching membership과 node identity/state를 구분합니다." },
          ],
          sourceRefs: ["web-dom-query-source", "dom-standard", "dom-collections"],
        },
      ],
      diagnostics: [
        { symptom: "live collection을 앞에서 remove하는 loop가 element 절반만 삭제한다.", likelyCause: "삭제마다 collection이 갱신되어 다음 element가 현재 index로 당겨졌는데 i도 증가했습니다.", checks: ["iteration별 length/index/id를 기록합니다.", "collection constructor API가 live인지 확인합니다.", "DOM mutation이 loop 안 어디서 일어나는지 봅니다."], fix: "Array.from snapshot을 순회하거나 while(collection.length) 첫/끝을 제거하며 의도를 명시합니다.", prevention: "0/1/4 item mutation loop 결과와 collection type assertion을 둡니다." },
      ],
    },
    {
      id: "node-versus-element-traversal",
      title: "Node traversal은 text/comment를 포함하고 Element traversal은 element 관계만 제공합니다",
      lead: "firstChild가 첫 tag라고 가정하지 말고 필요한 data model에 맞는 family를 일관되게 사용합니다.",
      explanations: [
        "parentNode/childNodes/firstChild/lastChild/previousSibling/nextSibling은 모든 Node type을 대상으로 합니다. indentation Text node와 Comment도 결과에 들어옵니다.",
        "parentElement/children/firstElementChild/lastElementChild/previousElementSibling/nextElementSibling은 Element 중심으로 이동합니다. element UI 구조를 탐색할 때 더 안정적입니다.",
        "Text node의 parentElement는 owner element일 수 있지만 Text 자체에는 querySelector가 없습니다. event.target은 보통 Element가 아닐 가능성도 일반 EventTarget API에서 고려해 instanceof Element guard를 둡니다.",
        "Element.children은 live HTMLCollection이고 childNodes는 일반적으로 live NodeList 성격을 가집니다. traversal 중 mutation을 섞지 않고 먼저 target snapshot/relationship을 계산합니다.",
        "closest는 자신을 포함해 ancestor element selector를 찾고 parentElement chain loop를 줄입니다. matches는 현재 element가 selector에 맞는지, contains는 inclusive descendant인지 확인합니다.",
        "구조를 여러 parentElement.parentElement처럼 고정하면 wrapper 하나 추가에 깨집니다. semantic closest/data owner 또는 explicit reference를 사용하고 ancestor가 없을 수 있는 root case를 처리합니다.",
      ],
      concepts: [
        { term: "Node traversal family", definition: "parentNode·childNodes·firstChild·nextSibling처럼 모든 node 종류를 포함하는 관계 API입니다.", detail: ["Text/Comment가 포함됩니다.", "document processing에 필요합니다."] },
        { term: "Element traversal family", definition: "parentElement·children·firstElementChild·nextElementSibling처럼 element만 대상으로 하는 관계 API입니다.", detail: ["UI element 구조에 적합합니다.", "children은 live입니다."] },
        { term: "inclusive descendant", definition: "node 자신 또는 그 descendants를 포함하는 tree 관계로 contains는 자신에 대해서도 true입니다.", detail: ["delegation boundary에 씁니다.", "strict descendant가 필요하면 identity도 비교합니다."] },
      ],
      codeExamples: [
        {
          id: "node-element-relations",
          title: "들여쓰기 Text node와 li Element 관계 비교",
          language: "html",
          filename: "dom-relations.html",
          purpose: "동일 ul에서 childNodes/children과 firstChild/firstElementChild, parent/sibling 관계를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>DOM relations</title></head>\n<body><ul id=\"list\">\n  <li id=\"a\">A</li>\n  <li id=\"b\"><span>B</span></li>\n</ul><pre id=\"out\"></pre>\n<script>\n  const list = document.querySelector('#list');\n  const a = document.querySelector('#a');\n  const b = document.querySelector('#b');\n  document.querySelector('#out').textContent = [\n    `childNodes=${list.childNodes.length}`,\n    `children=${list.children.length}`,\n    `firstChild=${list.firstChild.nodeName}`,\n    `firstElement=${list.firstElementChild.id}`,\n    `b-parent=${b.parentElement.id}`,\n    `a-next=${a.nextElementSibling.id}`,\n    `b-text=${b.textContent}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-6", explanation: "ul 내부 newline/indentation text와 li A/B, nested span을 만듭니다." },
            { lines: "9-11", explanation: "root와 두 li를 stable selector로 찾습니다." },
            { lines: "12-20", explanation: "모든 node/element count와 first node, parent/next element, descendant text를 출력합니다." },
          ],
          run: { environment: ["HTML source whitespace를 그대로 보존해 여는 modern browser"], command: "browser에서 dom-relations.html을 열고 결과 확인" },
          output: { value: "childNodes=5\nchildren=2\nfirstChild=#text\nfirstElement=a\nb-parent=list\na-next=b\nb-text=B", explanation: ["ul 안 세 whitespace Text segment와 li 두 개가 childNodes 5입니다.", "children은 li 두 Element만 셉니다.", "firstChild는 #text지만 firstElementChild는 a입니다."] },
          experiments: [
            { change: "ul markup의 모든 newline/space를 제거합니다.", prediction: "childNodes도 2가 되고 firstChild가 LI가 됩니다.", result: "Node traversal을 formatting whitespace에 의존하지 않습니다." },
            { change: "A/B 사이 comment를 추가합니다.", prediction: "childNodes가 Comment까지 늘지만 children은 2를 유지합니다.", result: "node type을 필요에 따라 filter합니다." },
            { change: "b 안 span 뒤 text C를 추가합니다.", prediction: "b.textContent는 BC가 되고 child element 관계는 그대로입니다.", result: "textContent는 descendant text 전체를 결합합니다." },
          ],
          sourceRefs: ["web-dom-overview-source", "web-dom-query-source", "dom-standard", "html-tree-construction"],
        },
      ],
      diagnostics: [
        { symptom: "firstChild.style 접근에서 undefined/TypeError가 난다.", likelyCause: "firstChild가 whitespace Text node라 HTMLElement style property가 없습니다.", checks: ["nodeType/nodeName을 출력합니다.", "firstElementChild와 비교합니다.", "element가 없을 수 있는 empty root를 test합니다."], fix: "element UI가 목적이면 firstElementChild를 쓰고 null을 처리합니다. text가 목적이면 nodeType을 분기합니다.", prevention: "pretty/minified/empty/comment markup traversal fixture를 둡니다." },
      ],
    },
    {
      id: "text-read-innertext-innerhtml",
      title: "textContent·innerText·innerHTML read는 서로 다른 DOM/render/serialization layer를 봅니다",
      lead: "원본에서 결과가 비슷해 보여도 숨김 text, descendant markup, layout 계산과 security 의미가 다릅니다.",
      explanations: [
        "textContent는 node subtree의 descendant text data를 결합하고 Element에 set하면 child를 text node로 교체합니다. markup처럼 보이는 string도 text로 표시되어 untrusted text sink의 기본입니다.",
        "innerText는 rendered text 관점의 style/layout-sensitive behavior를 가지며 hidden content, line breaks와 rendering state 영향을 받습니다. read가 style/layout 계산을 요구할 수 있어 data extraction 기본으로 쓰지 않습니다.",
        "innerHTML read는 descendant markup serialization string을 반환하고 set은 HTML parser를 실행해 nodes를 교체합니다. untrusted data를 set하면 XSS sink가 될 수 있어 다음 js-06에서 createElement/textContent/Trusted Types/sanitization을 깊게 다룹니다.",
        "원본 res.textContent=`<h2>...`는 literal `<h2>` text를 만들고 res2.innerHTML은 실제 h2 element를 만듭니다. 이 차이는 style 문제가 아니라 parse/DOM structure와 security boundary입니다.",
        "textContent를 search/index용으로 읽을 때 hidden instruction/descendant spacing이 결합될 수 있습니다. specific field element를 query하고 trim/normalization contract를 명시합니다.",
        "document.write/writeln은 parser와 document stream에 개입해 load 후 document를 교체할 수 있고 modern component output에 사용하지 않습니다. DOM API와 explicit output element를 사용합니다.",
      ],
      concepts: [
        { term: "textContent", definition: "node subtree의 text content를 읽거나 child를 text로 교체하는 DOM property입니다.", detail: ["markup을 parse하지 않습니다.", "descendant text를 포함합니다."] },
        { term: "innerText", definition: "rendered text 개념과 CSS/layout을 고려하는 HTMLElement property입니다.", detail: ["textContent와 결과가 다를 수 있습니다.", "layout-sensitive read를 조심합니다."] },
        { term: "innerHTML", definition: "element descendants의 HTML serialization을 읽거나 string을 HTML parser로 parse해 교체하는 property입니다.", detail: ["injection sink입니다.", "node/listener identity를 교체할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "사용자 이름 `<img ...>`을 innerHTML로 표시했더니 element/event가 실행된다.", likelyCause: "data string을 HTML parser sink에 넣어 markup으로 재해석했습니다.", checks: ["innerHTML/insertAdjacentHTML/document.write 사용을 검색합니다.", "value source/trust/sanitizer를 추적합니다.", "DOM에 unexpected element가 생겼는지 봅니다."], fix: "plain text는 textContent, structured UI는 createElement/property/append를 사용하고 rich HTML만 검증된 sanitizer/Trusted Types policy로 제한합니다.", prevention: "XSS payload fixture, CSP/Trusted Types와 unsafe sink lint를 둡니다." },
      ],
    },
    {
      id: "closest-root-shadow-boundary",
      title: "closest·contains·getRootNode와 Shadow DOM boundary로 traversal 책임을 component 안에 가둡니다",
      lead: "document 전체 구조를 가정하지 않고 현재 node가 어느 root/owner에 속하는지 확인합니다.",
      explanations: [
        "element.closest(selector)는 자신부터 ancestor element를 올라가 첫 match를 반환하거나 null입니다. event delegation에서 action/row/component owner를 찾되 target이 Element인지 검사합니다.",
        "container.contains(candidate)는 자신을 포함한 descendant 관계를 확인합니다. closest가 intended container 밖 element를 찾는 case를 막고 detached candidate도 처리합니다.",
        "getRootNode()는 Document 또는 ShadowRoot를 반환하고 `{composed:true}`는 shadow-including root를 볼 수 있습니다. document.querySelector는 shadow root 내부를 관통하지 않으므로 component가 shadowRoot reference에서 query합니다.",
        "slot/Shadow DOM에서는 light DOM parent 관계와 composed/rendered tree가 다릅니다. assignedSlot/assignedElements, event composedPath를 목적별로 사용하고 parentElement chain으로 화면 구조를 추측하지 않습니다.",
        "iframe은 별도 Document/browsing context이며 same-origin일 때만 contentDocument 접근이 가능합니다. cross-origin DOM을 query하려 하지 않고 postMessage schema/origin contract를 사용합니다.",
        "component public API는 내부 selector/class 구조를 외부가 query하지 않게 method/property/custom event를 제공합니다. E2E test도 role/name public surface를 우선하고 implementation hook은 제한합니다.",
      ],
      concepts: [
        { term: "getRootNode", definition: "node가 속한 tree의 root Document/ShadowRoot를 반환하는 Node method입니다.", detail: ["composed option이 있습니다.", "query scope를 확인합니다."] },
        { term: "ShadowRoot", definition: "shadow tree의 document fragment-like root로 component DOM encapsulation boundary를 만듭니다.", detail: ["document query가 내부를 관통하지 않습니다.", "open/closed mode가 있습니다."] },
        { term: "public component surface", definition: "외부 code가 internal DOM selector 대신 사용하는 property/method/event/semantic interaction contract입니다.", detail: ["refactor 결합을 줄입니다.", "encapsulation을 유지합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "custom element 내부 button이 화면에 보이는데 document.querySelector로 null이다.", likelyCause: "button이 ShadowRoot tree 안에 있어 document query scope가 관통하지 않습니다.", checks: ["host.shadowRoot와 node.getRootNode를 확인합니다.", "shadow mode open/closed를 봅니다.", "외부가 내부 button에 직접 의존해야 하는지 검토합니다."], fix: "component 내부에서 shadowRoot query하고 외부에는 public method/property/custom event와 accessible semantic surface를 제공합니다.", prevention: "public API/role-name 기반 test와 Shadow DOM boundary 문서를 둡니다." },
      ],
    },
    {
      id: "cache-detached-performance-observation",
      title: "query caching은 owner lifetime 안에서만 하고 detached/stale reference와 layout-dependent read를 측정합니다",
      lead: "같은 selector를 반복하지 않는 최적화가 route 교체 뒤 과거 element를 계속 쓰는 버그가 될 수 있습니다.",
      explanations: [
        "mount에서 required root/controls를 한 번 query해 closure/controller에 저장하면 반복 event에서 global query를 줄이고 owner가 명확해집니다. dispose에서 listener/reference를 release합니다.",
        "element.remove 또는 subtree replacement 뒤 variable은 같은 object를 계속 참조하지만 isConnected=false일 수 있습니다. 과거 node를 수정해도 현재 화면은 바뀌지 않습니다. re-render ownership과 ref 갱신을 정합니다.",
        "innerHTML로 parent subtree를 교체하면 cached child와 listener가 detached되고 새 matching child는 다른 identity입니다. data state에서 DOM을 다시 render하거나 keyed reconciliation/public API를 사용합니다.",
        "querySelector 자체는 많은 UI에서 충분히 빠릅니다. 복잡한 selector를 deep tree/high-frequency loop에서 반복할 때 Performance profile을 보고 root를 좁히거나 Map/state lookup을 사용합니다.",
        "getBoundingClientRect/offsetWidth/innerText 같은 layout-dependent read와 style/DOM write를 교차하면 forced synchronous layout이 반복될 수 있습니다. reads를 batch한 뒤 writes를 수행하고 animation frame을 사용합니다.",
        "MutationObserver는 third-party/slot/content change integration에 유용하지만 observer callback도 batch record와 subtree lifetime을 관리해야 합니다. own state render 결과를 다시 observe해 loop를 만들지 않습니다.",
        "selector/result count, missing required node, duplicate IDs는 development/test telemetry에 남기되 user text/PII나 전체 innerHTML을 production log로 수집하지 않습니다.",
      ],
      concepts: [
        { term: "detached node", definition: "DOM object reference는 남아 있지만 현재 Document tree에 연결되지 않은 node입니다.", detail: ["isConnected가 false일 수 있습니다.", "listener/closure가 retention할 수 있습니다."] },
        { term: "stale reference", definition: "현재 UI의 새 node 대신 교체 전 과거 node를 가리키는 cached reference입니다.", detail: ["identity가 다릅니다.", "mount/render lifecycle에서 갱신합니다."] },
        { term: "layout thrashing", definition: "DOM/style write와 layout-dependent read를 반복 교차해 browser가 synchronous style/layout을 여러 번 수행하는 성능 문제입니다.", detail: ["read/write를 batch합니다.", "profile로 확인합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "button textContent를 바꿨는데 화면의 button은 그대로다.", likelyCause: "cached button이 parent innerHTML/re-render로 교체되어 detached됐고 새 button은 다른 object입니다.", checks: ["cached.isConnected와 getRootNode를 확인합니다.", "현재 query result === cached를 비교합니다.", "subtree 교체 owner를 찾습니다."], fix: "innerHTML 교체를 제거하고 stable node를 update하거나 re-render 후 reference/listener를 owner가 다시 mount하며 state를 source of truth로 둡니다.", prevention: "render 전후 node identity/isConnected와 event call regression을 test합니다." },
      ],
      expertNotes: [
        "DOM selector matching은 CSS cascade specificity를 계산해 winner를 고르는 과정과 다릅니다. selector가 element에 match하는지만 사용하며 querySelector는 tree-order first를 반환합니다.",
        "HTMLCollection의 named property access는 ID/name과 property 이름 충돌/legacy behavior를 만들 수 있어 index/iteration과 explicit query를 사용합니다.",
        "접근성 tree query는 DOM API와 별개입니다. testing-library role/name query와 browser accessibility snapshot을 DOM structural selector와 함께 사용합니다.",
      ],
    },
  ],
  lab: {
    title: "원본 wrap/article와 message DOM을 query contract·tree inspector·lifecycle-safe controller로 재작성하기",
    scenario: "현재 code는 global document query, null 미처리, live/static collection 혼용, firstChild=Element 가정과 document.write를 사용합니다. wrapper/whitespace/re-render/Shadow DOM에서 깨지고 cached node가 detached됩니다.",
    setup: [
      "원본 DOM file 3개를 read-only evidence로 준비하고 browser DevTools Elements/Console을 엽니다.",
      "pretty/minified/comment/nested/empty/duplicate-id/invalid-selector/dynamic-add-remove fixture를 준비합니다.",
      "required/optional/collection selector contract와 stable data-role hook을 먼저 문서화합니다.",
      "mount/dispose/re-render와 ShadowRoot/open iframe-like boundary test를 준비합니다.",
    ],
    steps: [
      "HTML source와 actual DOM을 nodeType/name/text/parent/children 표로 비교합니다.",
      "global query를 component root의 :scope/stable hooks로 좁히고 required/optional/empty 결과를 분리합니다.",
      "invalid/dynamic selector를 SyntaxError/no-match로 분류하고 user input selector 삽입을 제거합니다.",
      "static NodeList와 live HTMLCollection을 append/remove/class change 전후 exact snapshot합니다.",
      "Node/Element traversal family를 pretty/minified/comment markup에서 비교합니다.",
      "closest/matches/contains/getRootNode로 owner/delegation/Shadow DOM boundary를 확인합니다.",
      "textContent/innerText/innerHTML read 결과와 layout/XSS 비용을 분류하고 document.write를 제거합니다.",
      "subtree re-render 뒤 cached identity/isConnected, listener dispose와 privacy-safe missing/duplicate telemetry를 test합니다.",
    ],
    expectedResult: [
      "모든 required query는 존재하거나 context error를 내고 optional/collection empty는 정상 state로 처리됩니다.",
      "selector root와 :scope가 component boundary를 지켜 wrapper/nested item이 결과를 오염시키지 않습니다.",
      "static/live membership과 Node/Element whitespace 결과가 정확한 실행 output과 일치합니다.",
      "dynamic item/delegation은 closest+contains로 안전하고 ShadowRoot 내부는 public API/own root에서 처리됩니다.",
      "re-render 뒤 stale detached node를 수정하지 않고 mount/dispose가 current reference/listener를 소유합니다.",
      "query/DOM log에 전체 innerHTML·사용자 개인정보·private path가 없습니다.",
    ],
    cleanup: ["synthetic duplicate ID, invalid selector, dynamic nodes와 MutationObserver를 제거하고 controller dispose를 실행합니다.", "DevTools DOM breakpoint와 debug node references를 해제해 heap retention 측정에 영향을 주지 않게 합니다."],
    extensions: ["TreeWalker/NodeIterator로 text/comment를 filter하며 recursive traversal과 비교합니다.", "open ShadowRoot component와 slot assignedElements/public custom event를 구현합니다.", "WPT-style DOM query/collection/traversal matrix를 여러 browser에서 실행합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 wrap/article를 모든 query API로 조회하고 return type·null/empty·live/static을 표로 작성하세요.", requirements: ["getElementById/class/tag와 querySelector/All을 모두 실행합니다.", "required missing과 invalid selector를 분리합니다.", "append/class remove 후 collection 길이를 비교합니다.", "prototype/constructor가 아니라 실제 observable API를 기록합니다."], hints: ["복수 query는 0개여도 null이 아닙니다.", "getElementsBy... collection은 live인지 mutation 뒤 확인합니다."], expectedOutcome: "각 API를 의도와 result lifecycle에 맞게 선택하고 exact output을 설명합니다.", solutionOutline: ["root·matching·return·live·failure column을 만듭니다.", "mutation 전후를 같은 reference에서 읽습니다."] },
    { difficulty: "응용", prompt: "DOM 관계 inspector를 만들어 선택 node의 node/element parent·children·siblings·root를 안전하게 출력하세요.", requirements: ["pretty/minified/comment/text fixture를 지원합니다.", "nodeType/name/text snippet을 redaction/길이 제한합니다.", "Node와 Element traversal을 나란히 보여 줍니다.", "closest/contains/getRootNode/ShadowRoot를 표시합니다.", "detached node를 별도 state로 분류합니다."], hints: ["firstChild가 Element라고 가정하지 않습니다.", "순환 parent reference를 JSON.stringify하지 않습니다."], expectedOutcome: "어떤 node type/root에서도 throw 없이 실제 tree relation과 formatting whitespace 차이를 설명합니다.", solutionOutline: ["plain summary record로 normalize한 뒤 render합니다.", "max depth/node/text length limit을 둡니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 DOM query hook·component boundary·lifecycle 표준을 설계하세요.", requirements: ["required/optional/collection query helper와 error code를 정의합니다.", "data-role/id/ref/CSS class ownership과 duplicate 정책을 정합니다.", "static/live collection과 mutation iteration policy를 만듭니다.", "Shadow DOM/iframe/public surface와 event delegation boundary를 포함합니다.", "mount/re-render/dispose, stale/isConnected, performance/privacy test를 설계합니다."], hints: ["presentation class를 JS public API로 만들지 않습니다.", "DOM이 source of truth인지 application state가 source인지 명시합니다."], expectedOutcome: "markup refactor와 dynamic render에도 깨지지 않고 missing/stale/query 비용을 관측 가능한 component contract가 완성됩니다.", solutionOutline: ["tree ownership과 root를 먼저 그립니다.", "query 결과 lifetime과 invalidation event를 표로 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "DOM은 HTML source 문자열과 완전히 같은 tree인가요?", answer: "항상 아닙니다. parser가 implied element/error recovery와 whitespace Text node를 포함한 DOM tree를 만듭니다." },
    { question: "querySelector no-match는 무엇을 반환하나요?", answer: "null입니다. invalid selector는 SyntaxError를 throw할 수 있습니다." },
    { question: "querySelectorAll no-match는 null인가요?", answer: "아닙니다. length 0의 static NodeList입니다." },
    { question: "getElementsByClassName 결과는 Array인가요?", answer: "아닙니다. live HTMLCollection이며 필요하면 Array.from으로 snapshot합니다." },
    { question: "static NodeList는 node property 변화도 못 보나요?", answer: "membership만 query 시점에 고정되고 포함 node object 자체의 property 변화는 같은 reference에서 보입니다." },
    { question: "childNodes와 children의 차이는 무엇인가요?", answer: "childNodes는 Text/Comment 등 모든 child Node, children은 child Element만 포함합니다." },
    { question: "firstChild는 항상 첫 tag element인가요?", answer: "아닙니다. indentation whitespace Text node일 수 있어 element가 필요하면 firstElementChild를 사용합니다." },
    { question: "contains는 자기 자신에 대해서도 true인가요?", answer: "네. inclusive descendant relation이므로 strict descendant면 identity를 추가 비교합니다." },
    { question: "document.querySelector가 ShadowRoot 내부를 찾나요?", answer: "아닙니다. 해당 shadow root 또는 component public API를 사용합니다." },
    { question: "element.remove 후 variable도 null이 되나요?", answer: "아닙니다. object reference는 남을 수 있고 isConnected=false인 detached node가 됩니다." },
    { question: "textContent와 innerHTML의 핵심 차이는 무엇인가요?", answer: "textContent는 text data를 다루고 innerHTML setter는 string을 HTML로 parse하는 injection/structure boundary입니다." },
  ],
  completionChecklist: [
    "HTML source와 parser-created Document/Element/Text/Comment tree를 구분했다.",
    "query root·selector·single/collection·null/empty return contract를 문서화했다.",
    "invalid selector SyntaxError와 user dynamic selector escaping/allowlist를 처리했다.",
    "getElementById와 unique ID, :scope semantic hook으로 component query를 좁혔다.",
    "static NodeList와 live HTMLCollection을 mutation 전후 exact output으로 확인했다.",
    "mutation loop 전에 live collection을 snapshot하거나 안전한 방향으로 처리했다.",
    "Node/Element parent·child·sibling family와 whitespace/comment 결과를 구분했다.",
    "closest·matches·contains·getRootNode와 Shadow DOM/public surface를 사용했다.",
    "textContent·innerText·innerHTML read/sink/layout/security 차이를 설명했다.",
    "cached node identity·isConnected·re-render invalidation과 dispose를 검증했다.",
    "query/layout read performance와 privacy-safe missing/duplicate telemetry를 측정했다.",
  ],
  nextSessions: ["js-06-dom-create-update-remove"],
  sources: [
    { id: "web-dom-overview-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day08/ex14_DOM.html", usedFor: ["DOM definition", "wrap/article tree", "id/class/tag query list", "querySelector overview", "empty article structure"], evidence: "section#wrap 아래 세 article의 최소 tree와 query API 주석을 parser node model·semantic root query의 출발점으로 사용했습니다." },
    { id: "web-dom-query-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex01_DOM.html", usedFor: ["getElementById/class/tag", "querySelector/All", "single/multiple result", "innerText/textContent", "for-of collection"], evidence: "TEXT1~3 전체 조회/출력 흐름을 null/empty·static/live collection과 exact query contract로 확장했습니다." },
    { id: "web-dom-text-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex02_DOM.html", usedFor: ["textContent getter/setter", "innerHTML contrast", "query repetition", "style/property write", "document output"], evidence: "Hello/Welcome/message 복사와 literal h2 versus parsed h2를 text/read/sink boundary 및 caching/lifecycle 준비 범위로 사용했습니다." },
    { id: "dom-standard", repository: "WHATWG DOM Standard", path: "DOM node/query/traversal", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["Node/Element/Document tree", "ParentNode querySelector(All)", "traversal relations", "closest/matches/contains/getRootNode", "collections", "ShadowRoot"], evidence: "2026-07-12 current DOM living standard의 node tree/query/collection/traversal API를 모든 exact example의 기준으로 사용했습니다." },
    { id: "dom-collections", repository: "WHATWG DOM Standard", path: "#old-style-collections", publicUrl: "https://dom.spec.whatwg.org/#old-style-collections", usedFor: ["NodeList/HTMLCollection", "live/static behavior", "length/item/named property", "mutation iteration"], evidence: "querySelectorAll static NodeList와 legacy live HTMLCollection의 membership 차이를 공식 collection semantics에 맞췄습니다." },
    { id: "selectors-4", repository: "W3C CSS Working Group", path: "TR/selectors-4/", publicUrl: "https://www.w3.org/TR/selectors-4/", usedFor: ["selector syntax/matching", "compound/complex selectors", ":scope", "invalid selector", "tree order"], evidence: "querySelector가 사용하는 CSS selector predicate와 scoped/invalid matching을 current Selectors Level 4로 보강했습니다." },
    { id: "html-tree-construction", repository: "WHATWG HTML Standard", path: "multipage/parsing.html#tree-construction", publicUrl: "https://html.spec.whatwg.org/multipage/parsing.html#tree-construction", usedFor: ["HTML parser DOM construction", "implied/reparented elements", "whitespace text", "source versus tree"], evidence: "HTML source indentation/tag nesting과 실제 DOM tree가 항상 동일하지 않은 parser mental model의 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "원본 세 파일은 DOM 정의와 모든 기본 query API, single/multiple/text/HTML 결과를 충실히 제공합니다. parser error recovery, Node/Element traversal, static/live mutation, selector injection, detached/Shadow DOM/performance는 WHATWG/W3C 표준으로 보강했습니다.",
      "실제 create/append/remove/DocumentFragment와 XSS-safe rendering은 js-06, attribute/property/class/form current state는 js-07에서 이 query/lifecycle 모델 위에 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
