import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-10-fetch-json-http"],
  slug: "js-10-fetch-json-http",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 10,
  title: "fetch로 JSON을 요청하고 HTTP 실패를 구분하기",
  subtitle: "Request·Response·body stream·HTTP status·JSON schema·CORS·AbortSignal을 분리해 로딩부터 취소까지 검증합니다.",
  level: "중급",
  estimatedMinutes: 350,
  coreQuestion: "fetch가 돌려준 Response를 HTTP·body·data schema·UI state 경계로 나누어 처리하고, 네트워크·상태 코드·파싱·취소 실패를 어떻게 정확히 구분할까요?",
  summary: "원본의 sample.txt fetch와 Promise chain/async-await 예제를 정확히 보존하되 인벤토리의 JSON 목표와 원본 text 차이를 명시합니다. fetch는 Request를 만들고 Fetch/HTTP/CORS/cache/service-worker processing을 거쳐 Response를 반환하는 low-level API이며, 일반적인 404/500 Response만으로 Promise가 reject되지 않아 response.ok/status를 업무 규칙으로 검사해야 합니다. network/CORS/invalid request/abort rejection, HTTP failure, body decode/JSON syntax, runtime schema, safe rendering failure를 서로 다른 Error types와 사용자 복구로 나눕니다. Response body는 stream이고 text/json 호출은 비동기 소비이며 한번 읽으면 bodyUsed가 true가 되어 다시 읽을 수 없으므로 필요하면 소비 전에 clone합니다. JSON은 JavaScript object literal이 아니고 comments/trailing comma/undefined를 허용하지 않으며 파싱 성공은 schema 신뢰를 뜻하지 않습니다. unknown payload를 runtime validation한 뒤 createElement/textContent로 렌더링해 JSON string 속 HTML 모양 값이 element로 실행되지 않게 합니다. Request URL은 URL/URLSearchParams로 구성하고 Accept와 Content-Type, method safety/idempotency, credentials/cache/redirect를 구분합니다. CORS는 browser read 권한 protocol이지 authentication/authorization/CSRF 방어가 아니며 no-cors는 opaque response를 만들어 해결책이 아닙니다. AbortController로 이전 검색을 취소하고 generation/reference guard로 stale result를 막으며, loading/data/empty/http/parse/schema/abort 상태를 접근 가능한 UI로 만듭니다. 실제 server 없이 Response/fake fetch로 결정론적 tests를 수행하고 production에서는 HTTPS·CSP connect-src·payload size/streaming·privacy-safe telemetry를 검증합니다.",
  objectives: [
    "fetch의 Request→policy/cache/service worker/network/CORS→Response 흐름과 Promise settlement를 설명할 수 있다.",
    "Response.ok/status/type/url/headers를 사용해 network rejection과 HTTP failure를 구분할 수 있다.",
    "Body stream의 bodyUsed·single consumption·clone과 text/json parsing failure를 예측할 수 있다.",
    "JSON syntax parse와 runtime schema validation을 분리하고 unknown data를 domain model로 정규화할 수 있다.",
    "외부 payload를 createElement/textContent로 안전하게 렌더링하고 empty/loading/error UI를 제공할 수 있다.",
    "URLSearchParams·method·Accept/Content-Type·credentials·cache·redirect를 API contract에 맞게 구성할 수 있다.",
    "same-origin policy·CORS preflight/credentials와 CSRF/authorization/CSP를 다른 보안 경계로 설명할 수 있다.",
    "AbortSignal과 latest-request guard로 stale response·timeout·component disposal을 처리할 수 있다.",
  ],
  prerequisites: [
    { title: "Promise 상태·체이닝·오류 전파", reason: "fetch와 body readers의 Promises를 return/await하고 HTTP·parse·schema Error를 같은 chain에서 분류합니다.", sessionSlug: "js-09-promise-state-error" },
    { title: "DOM 생성·안전한 CRUD 렌더링", reason: "검증된 response data만 createElement/textContent로 목록에 투영하고 innerHTML injection을 피합니다.", sessionSlug: "js-06-dom-create-update-remove" },
    { title: "URL·Window built-ins", reason: "raw string concatenation 대신 URL/URLSearchParams로 endpoint와 query를 구조적으로 만듭니다.", sessionSlug: "js-04-built-in-objects" },
  ],
  keywords: ["fetch", "Request", "Response", "Headers", "HTTP", "status", "ok", "body", "ReadableStream", "bodyUsed", "clone", "text", "json", "JSON", "schema validation", "Content-Type", "Accept", "URLSearchParams", "CORS", "same-origin policy", "preflight", "credentials", "CSRF", "AbortController", "AbortSignal", "opaque response", "CSP connect-src", "stale response"],
  chapters: [
    {
      id: "fetch-request-response-pipeline",
      title: "fetch는 URL 문자열 편의 함수가 아니라 Request와 Response를 연결하는 platform pipeline입니다",
      lead: "호출·request 구성·policy/cache/service worker/network·headers 도착·body 소비 단계를 분리합니다.",
      explanations: [
        "fetch(input, init)는 Request 정보를 만들고 Promise를 즉시 반환합니다. browser는 URL scheme, method/headers/body, cache, credentials, redirect, service worker, mixed content, CSP와 CORS 등을 Fetch Standard에 따라 처리합니다.",
        "fetch Promise가 fulfilled됐다는 것은 application data가 유효하다는 뜻이 아닙니다. Response를 얻은 뒤 status/headers/body를 별도 처리해야 하며 body 전체가 이미 JSON object로 memory에 있다는 뜻도 아닙니다.",
        "원본 ex12는 click에서 fetch('sample.txt'), response.text(), log.textContent를 chain으로 연결합니다. 상대 URL은 current document URL을 기준으로 resolve되므로 file 위치·base element·deployment path가 바뀌면 target도 달라집니다.",
        "원본 ex13은 같은 흐름을 async/await와 try/catch로 바꾸고 response.ok를 검사합니다. 두 syntax의 Promise 의미는 같으며 await를 써도 HTTP success와 body parse를 명시해야 합니다.",
        "Request URL은 `new URL(endpoint, location.origin)`과 URLSearchParams로 만들면 &, =, Unicode, space를 올바르게 encode할 수 있습니다. 외부가 전체 endpoint를 정하면 허용 scheme/origin/path를 parsed URL로 제한합니다.",
        "file://로 HTML을 직접 열면 opaque origin/local access 정책 때문에 relative fetch가 development HTTP server와 다르게 실패할 수 있습니다. local server와 production-like origin에서 실행합니다.",
      ],
      concepts: [
        { term: "Request", definition: "URL·method·headers·body·mode·credentials·cache·redirect·signal 등 fetch input을 구조화한 object입니다.", detail: ["browser policies가 적용됩니다.", "body 수명과 clone을 가집니다."] },
        { term: "Response", definition: "status·headers·URL/type과 아직 소비되지 않을 수 있는 body를 나타내는 fetch 결과 object입니다.", detail: ["HTTP 실패도 Response일 수 있습니다.", "body reader는 Promise입니다."] },
        { term: "fetch pipeline", definition: "request 생성부터 policy/cache/service worker/network/CORS/response filtering/body delivery를 잇는 processing model입니다.", detail: ["단순 socket call이 아닙니다.", "각 boundary가 실패할 수 있습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "HTML을 double-click해 열었더니 sample.txt fetch가 TypeError로 실패한다.", likelyCause: "file origin/local resource policy가 HTTP server 환경과 달라 relative fetch가 허용되지 않았습니다.", checks: ["location.protocol/origin과 resolved URL을 확인합니다.", "DevTools Network/console의 CORS/local resource error를 봅니다.", "같은 files를 local HTTP server에서 실행합니다."], fix: "development server로 same-origin HTTP(S)에서 제공하고 production base/path contract를 test합니다.", prevention: "실행 명령과 CI static-server browser smoke를 제공하고 file:// 지원을 가정하지 않습니다." },
      ],
    },
    {
      id: "network-http-parse-error-taxonomy",
      title: "fetch rejection과 HTTP failure는 다르므로 network·HTTP·parse·schema·abort 오류를 분류합니다",
      lead: "catch 하나에서 모두 '인터넷 오류'라고 하지 않고 어느 boundary까지 성공했는지 보존합니다.",
      explanations: [
        "fetch Promise는 network error, request construction/policy failure, CORS blocked response, abort 등에서 reject될 수 있습니다. 일반적인 HTTP 404/500은 server가 Response를 보냈으므로 Promise가 fulfill되고 response.ok가 false입니다.",
        "Response.ok는 status 200~299 범위인지 나타냅니다. endpoint contract에서 200 JSON, 201 Location, 202 async job, 204 no body처럼 accepted statuses와 body expectation을 별도 정의합니다.",
        "HTTP failure body가 JSON error envelope일 수도, HTML proxy page일 수도, empty일 수도 있습니다. error body를 무조건 json()해 syntax error로 원 status를 잃지 말고 status/media type을 먼저 보존합니다.",
        "response.json rejection은 body stream/decoding/JSON syntax failure일 수 있고 status와 별개입니다. JSON parse 성공 뒤 property/type/range가 틀리면 SchemaError로 분리합니다.",
        "AbortError는 user/newer request/navigation/timeout 같은 cancellation reason에 따라 expected silent state 또는 timeout 안내가 됩니다. offline/network/CORS와 같은 메시지로 처리하지 않습니다.",
        "Error에는 status, code, retryable, cause, operation ID 정도만 두고 body/token/PII를 넣지 않습니다. 사용자 메시지는 internal stack을 직접 출력하지 않고 category와 recovery action으로 mapping합니다.",
      ],
      concepts: [
        { term: "network error", definition: "JavaScript가 usable Response를 받지 못해 fetch Promise가 reject되는 Fetch-layer failure입니다.", detail: ["CORS blocking도 client에서는 유사할 수 있습니다.", "HTTP 500과 다릅니다."] },
        { term: "HTTP failure", definition: "Response는 도착했지만 status가 endpoint의 success contract를 만족하지 않는 protocol/application outcome입니다.", detail: ["ok/status를 검사합니다.", "body를 안전하게 decode합니다."] },
        { term: "error taxonomy", definition: "NetworkError·HttpError·ParseError·SchemaError·AbortError처럼 recovery가 다른 failures를 boundary별로 분류한 체계입니다.", detail: ["cause를 보존합니다.", "사용자 메시지와 분리합니다."] },
      ],
      codeExamples: [
        {
          id: "http-versus-json-parse-error",
          title: "HTTP 404 JSON error와 200 invalid JSON 분리",
          language: "html",
          filename: "fetch-error-taxonomy.html",
          purpose: "실제 server 없이 Response objects로 status failure와 body syntax failure가 다른 Error class가 되는지 exact output으로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>fetch errors</title></head>\n<body><pre id=\"out\"></pre><script type=\"module\">\n  class HttpError extends Error { constructor(status, data) { super(`HTTP ${status}`); this.name='HttpError'; this.status=status; this.data=data; } }\n  class ParseError extends Error { constructor() { super('invalid-json'); this.name='ParseError'; } }\n  async function decodeJson(response) {\n    const text = await response.text();\n    let data;\n    try { data = JSON.parse(text); } catch { throw new ParseError(); }\n    if (!response.ok) throw new HttpError(response.status, data);\n    return data;\n  }\n  const lines = [];\n  try { await decodeJson(new Response(JSON.stringify({code:'NOT_FOUND'}), {status:404, headers:{'Content-Type':'application/json'}})); }\n  catch (error) { lines.push(`http=${error.name}:${error.status}:${error.data.code}`); }\n  try { await decodeJson(new Response('{broken', {status:200, headers:{'Content-Type':'application/json'}})); }\n  catch (error) { lines.push(`parse=${error.name}:${error.message}`); }\n  document.querySelector('#out').textContent = lines.join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-5", explanation: "status/data를 보존하는 HttpError와 JSON syntax 전용 ParseError를 정의합니다." },
            { lines: "6-12", explanation: "body를 한 번 text로 읽고 syntax를 분류한 뒤 ok가 아니면 original status/data로 throw합니다." },
            { lines: "14-18", explanation: "404 valid JSON과 200 invalid JSON을 독립 실행해 boundary별 결과를 기록합니다." },
          ],
          run: { environment: ["Response와 module top-level await를 지원하는 modern browser"], command: "browser에서 fetch-error-taxonomy.html을 열고 결과 확인" },
          output: { value: "http=HttpError:404:NOT_FOUND\nparse=ParseError:invalid-json", explanation: ["첫 Response는 JSON syntax가 valid하지만 status 404라 HttpError입니다.", "둘째는 status 200이어도 body syntax가 invalid해 ParseError입니다."] },
          experiments: [
            { change: "204 empty Response를 decodeJson에 전달합니다.", prediction: "무조건 JSON.parse하면 ParseError가 납니다.", result: "status contract에서 no-content를 별도 처리합니다." },
            { change: "404 body를 HTML로 바꿉니다.", prediction: "parse failure가 원 status를 가릴 수 있습니다.", result: "status/media type과 safe error decoder를 보존합니다." },
            { change: "HttpError를 throw하지 않고 data를 return합니다.", prediction: "caller가 error envelope를 정상 data로 렌더할 수 있습니다.", result: "success contract를 boundary에서 강제합니다." },
          ],
          sourceRefs: ["web-fetch-async-source", "fetch-standard", "fetch-response", "http-semantics", "json-rfc"],
        },
      ],
      diagnostics: [
        { symptom: "404인데 catch가 실행되지 않고 undefined data 오류가 뒤에서 난다.", likelyCause: "fetch가 HTTP status만으로 reject된다고 가정하고 response.ok/status 검사를 생략했습니다.", checks: ["Network status와 response.ok/status를 기록합니다.", "body decoder 전 success contract를 확인합니다.", "redirect/opaque type도 봅니다."], fix: "Response boundary에서 accepted status를 검사하고 HttpError로 throw한 뒤 error body/UI를 분리합니다.", prevention: "200/201/204/400/401/404/409/429/500 fixtures를 둡니다." },
      ],
    },
    {
      id: "response-body-stream-consumption",
      title: "Response body는 한 번 소비되는 stream이며 text/json은 별도 비동기 parsing 작업입니다",
      lead: "Response object와 body data를 같은 것으로 생각하지 않고 bodyUsed·clone·size·media type을 관리합니다.",
      explanations: [
        "Response에는 status/headers 외에 Body mixin의 body stream이 있습니다. text(), json(), arrayBuffer(), blob(), formData()는 body를 읽고 representation으로 변환하는 Promises입니다.",
        "body를 소비하면 bodyUsed가 true가 되고 같은 Response에서 다시 읽으면 TypeError가 날 수 있습니다. logging과 parsing이 둘 다 필요하면 소비 전에 clone하지만 큰 body를 무제한 복제하면 buffering/memory 비용이 커집니다.",
        "response.json()은 Content-Type을 schema gate로 삼지 않고 body를 읽어 JSON parse합니다. media type을 contract check하고도 syntax/schema validation을 해야 합니다.",
        "text mojibake가 나면 HTML meta가 아니라 HTTP Content-Type/charset과 actual bytes를 확인합니다. 원본 sample.txt의 한글도 server encoding/header가 맞아야 합니다.",
        "대형 NDJSON/streaming data는 전체 json() load 대신 response.body와 incremental decoder/parser를 검토합니다. chunk boundary가 text line이나 JSON token boundary와 일치한다고 가정하지 않습니다.",
        "Content-Length가 없거나 compressed/streamed일 수 있어 header 하나만으로 size를 신뢰하지 않습니다. server limit, streaming byte count와 abort를 함께 둡니다.",
      ],
      concepts: [
        { term: "body stream", definition: "Response representation bytes를 순차 제공하는 ReadableStream이며 null일 수도 있습니다.", detail: ["consumer가 읽습니다.", "backpressure/abort와 연결됩니다."] },
        { term: "bodyUsed", definition: "body가 이미 읽히기 시작해 다른 reader로 재사용할 수 없는지 나타내는 observable 상태입니다.", detail: ["두 번째 read가 실패할 수 있습니다.", "reader owner를 하나로 둡니다."] },
        { term: "Response clone", definition: "body stream을 tee해 별도 Response branches로 소비하게 하는 operation입니다.", detail: ["소비 전에 호출합니다.", "large-body buffering 비용이 있습니다."] },
      ],
      codeExamples: [
        {
          id: "fetch-text-body-single-use",
          title: "실제 fetch Response text 소비·clone·bodyUsed",
          language: "html",
          filename: "fetch-body.html",
          purpose: "server 없이 data URL을 실제 fetch해 원본 sample.txt 흐름과 body single-consumption을 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>fetch body</title></head>\n<body><pre id=\"out\"></pre><script type=\"module\">\n  const response = await fetch('data:text/plain;charset=utf-8,%EC%95%88%EB%85%95');\n  const copy = response.clone();\n  const text = await response.text();\n  let rereadError = 'none';\n  try { await response.text(); } catch (error) { rereadError = error.name; }\n  const copyText = await copy.text();\n  document.querySelector('#out').textContent = [\n    `status=${response.status}`, `ok=${response.ok}`, `bodyUsed=${response.bodyUsed}`,\n    `text=${text}`, `clone=${copyText}`, `reread=${rereadError}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3", explanation: "UTF-8 data URL을 실제 Fetch API로 요청해 Response를 받습니다." },
            { lines: "4-8", explanation: "소비 전에 clone하고 original body를 읽은 뒤 재소비 오류와 clone branch를 확인합니다." },
            { lines: "9-12", explanation: "status/ok/bodyUsed와 texts, 재읽기 오류를 stable output으로 기록합니다." },
          ],
          run: { environment: ["data URL fetch와 module top-level await를 지원하는 modern browser"], command: "browser에서 fetch-body.html을 열고 결과 확인" },
          output: { value: "status=200\nok=true\nbodyUsed=true\ntext=안녕\nclone=안녕\nreread=TypeError", explanation: ["data URL Response는 status 200/ok true입니다.", "original을 읽어 bodyUsed=true이고 재읽기는 TypeError입니다.", "소비 전 clone branch는 같은 text를 읽습니다."] },
          experiments: [
            { change: "clone을 response.text 뒤 호출합니다.", prediction: "이미 사용된 body라 clone이 TypeError를 throw할 수 있습니다.", result: "branch는 소비 전에 결정합니다." },
            { change: "text 대신 json을 호출합니다.", prediction: "안녕은 JSON grammar가 아니므로 parse rejection입니다.", result: "reader를 media contract에 맞춥니다." },
            { change: "큰 response를 clone해 한 branch를 느리게 읽습니다.", prediction: "tee buffering/memory 비용이 커질 수 있습니다.", result: "raw-body logging/clone을 제한합니다." },
          ],
          sourceRefs: ["web-fetch-text-source", "web-sample-text-source", "fetch-standard", "fetch-response"],
        },
      ],
      diagnostics: [
        { symptom: "response.json 뒤 error log에서 response.text를 읽으려다 consumed 오류가 난다.", likelyCause: "하나의 body stream을 두 번 소비했습니다.", checks: ["bodyUsed와 reader call sites를 확인합니다.", "logging middleware와 decoder가 각각 읽는지 봅니다.", "clone timing과 payload size를 측정합니다."], fix: "decoder 하나가 제한 raw text를 한 번 읽어 parse/status context를 만들거나 소비 전 필요한 경우만 clone합니다.", prevention: "single-reader ownership과 bodyUsed/large-response tests를 둡니다." },
      ],
    },
    {
      id: "json-schema-safe-render",
      title: "JSON parsing 성공은 data schema·신뢰·안전한 HTML을 보장하지 않습니다",
      lead: "bytes→JSON value→validated domain records→safe DOM의 네 경계를 각각 실패 가능하게 둡니다.",
      explanations: [
        "JSON은 object, array, string, number, true, false, null을 표현합니다. JavaScript object literal과 달리 comments, trailing comma, undefined, function, BigInt를 표현하지 않습니다.",
        "JSON number는 interoperable precision 한계가 있어 큰 database ID/정수/decimal money를 JavaScript Number로 그대로 보내면 손실될 수 있습니다. API schema에서 string/decimal representation을 선택합니다.",
        "response.json 결과는 runtime에서 unknown입니다. Array.isArray, record object/null, required types, finite/range, enum, nested depth/length를 검증하고 extra fields/version policy를 정합니다.",
        "TypeScript interface는 compile-time check일 뿐 network JSON을 runtime 검증하지 않습니다. schema library 또는 explicit parser가 path-aware error와 version migration을 제공합니다.",
        "검증된 title도 HTML로 parse할 이유는 없습니다. createElement/textContent로 표시하면 `<img onerror>` 모양 string이 text로 남습니다. URL/src/style은 해당 sink context 검증이 별도입니다.",
        "대량/깊은 payload는 CPU/memory denial과 UI blocking을 만듭니다. server pagination/limits와 client maximum records/string/depth 및 render batching을 둡니다.",
      ],
      concepts: [
        { term: "JSON value", definition: "RFC 8259 grammar로 parse된 data이며 application domain type은 아닙니다.", detail: ["syntax만 보장합니다.", "runtime schema가 필요합니다."] },
        { term: "runtime schema validation", definition: "외부 unknown value의 shape·types·ranges·enums·limits를 검사해 domain model로 변환하는 boundary입니다.", detail: ["TypeScript만으로 대체되지 않습니다.", "path-aware errors가 유용합니다."] },
        { term: "safe data rendering", definition: "외부 data를 markup parsing 없이 context-appropriate text/property에 넣고 URL/style sinks는 별도 검증하는 과정입니다.", detail: ["textContent가 기본입니다.", "schema validation과 XSS 방어는 별개입니다."] },
      ],
      codeExamples: [
        {
          id: "json-schema-safe-list-render",
          title: "JSON parse·runtime validation·textContent 목록 렌더링",
          language: "html",
          filename: "json-safe-list.html",
          purpose: "HTML tag처럼 보이는 valid JSON string도 safe DOM boundary에서 element가 되지 않는지 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>JSON safe list</title></head>\n<body><ul id=\"courses\"></ul><pre id=\"out\"></pre><script type=\"module\">\n  function parseCourses(value) {\n    if (!Array.isArray(value)) throw new TypeError('courses must be an array');\n    return value.map((item, index) => {\n      if (item === null || typeof item !== 'object') throw new TypeError(`courses[${index}] must be an object`);\n      if (!Number.isSafeInteger(item.id) || typeof item.title !== 'string') throw new TypeError(`courses[${index}] invalid`);\n      return { id:item.id, title:item.title };\n    });\n  }\n  const response = new Response(JSON.stringify([{id:1,title:'JavaScript'},{id:2,title:'<img src=x onerror=alert(1)>'}]), {headers:{'Content-Type':'application/json'}});\n  const courses = parseCourses(await response.json());\n  const list = document.querySelector('#courses');\n  for (const course of courses) {\n    const item = document.createElement('li');\n    item.dataset.id = String(course.id);\n    item.textContent = course.title;\n    list.append(item);\n  }\n  document.querySelector('#out').textContent = [`items=${list.childElementCount}`, `images=${list.querySelectorAll('img').length}`, `second=${list.lastElementChild.textContent}`].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-10", explanation: "unknown JSON을 array/record/safe-integer/string 조건으로 domain records에 normalize합니다." },
            { lines: "11-12", explanation: "정상 title과 HTML 모양 title을 JSON Response로 만들고 reader+parser를 실행합니다." },
            { lines: "13-20", explanation: "structure는 createElement, value는 textContent로 렌더링합니다." },
            { lines: "21", explanation: "item 수, 실제 img element 수와 표시 text를 확인합니다." },
          ],
          run: { environment: ["Response와 module top-level await를 지원하는 modern browser"], command: "browser에서 json-safe-list.html을 열고 결과 확인" },
          output: { value: "items=2\nimages=0\nsecond=<img src=x onerror=alert(1)>", explanation: ["JSON records 두 개가 li 두 개가 됩니다.", "두 번째 title은 textContent라 img element가 0개입니다.", "원문 string은 text로 읽을 수 있습니다."] },
          experiments: [
            { change: "둘째 id를 string '2'로 바꿉니다.", prediction: "JSON syntax는 valid하지만 schema parser가 TypeError를 throw합니다.", result: "parse와 validation은 별도입니다." },
            { change: "textContent를 innerHTML로 바꿉니다.", prediction: "img element와 event attribute 위험이 생깁니다.", result: "schema validation이 XSS sink를 안전하게 만들지 않습니다." },
            { change: "매우 큰 title/array를 전달합니다.", prediction: "valid schema라도 memory/rendering 문제가 생깁니다.", result: "size/count limits와 pagination을 둡니다." },
          ],
          sourceRefs: ["json-rfc", "fetch-response", "web-fetch-async-source", "dom-mutation-source"],
        },
      ],
      diagnostics: [
        { symptom: "response.json은 성공했는데 courses.map/item.title에서 TypeError가 난다.", likelyCause: "JSON syntax 성공을 expected schema 성공으로 오해했습니다.", checks: ["top-level type/null/required fields를 fixture로 확인합니다.", "API schema/version/content type을 봅니다.", "TypeScript assertion만 있는지 확인합니다."], fix: "network boundary에서 unknown을 runtime parser로 validate/normalize하고 SchemaError와 version mismatch UI를 제공합니다.", prevention: "missing/null/wrong type/large/deep/versioned payload tests를 둡니다." },
      ],
    },
    {
      id: "cors-credentials-security",
      title: "CORS는 cross-origin response 공유 protocol이지 authentication·authorization·CSRF 방어가 아닙니다",
      lead: "origin, preflight, credentials, opaque response와 CSP connect-src 역할을 분리합니다.",
      explanations: [
        "origin은 scheme, host, port tuple입니다. path가 같아도 port/scheme이 다르면 cross-origin이고 browser same-origin policy가 script read/access를 제한합니다.",
        "CORS는 request Origin과 server Access-Control-Allow-* response로 response 공유를 허용합니다. client가 임의 header로 허용을 만들 수 없고 server가 origin/method/headers/credentials를 정확히 설정합니다.",
        "non-safelisted method/headers/content type은 OPTIONS preflight를 만들 수 있습니다. preflight가 실패하면 endpoint가 server-to-server에서는 동작해도 browser script가 usable Response를 받지 못합니다.",
        "mode:'no-cors'는 bypass가 아닙니다. 요청/headers가 제한되고 opaque Response status 0과 unreadable headers/body를 받아 JSON API에 쓸 수 없습니다.",
        "credentialed CORS에서 wildcard origin과 credentials를 함께 쓰지 않고 exact validated origin과 Vary: Origin/cache를 고려합니다. origin을 검증 없이 echo하면 공격 origin을 승인할 수 있습니다.",
        "CORS는 request 전송 자체/CSRF를 완전히 막지 않고 authorization도 아닙니다. cookie 기반 state change는 SameSite/CSRF token/origin check와 server 권한 검사가 필요합니다.",
        "CSP connect-src는 page가 fetch/XHR/WebSocket 등으로 연결할 destinations를 제한하는 defense in depth입니다. server security와 URL allowlist를 대체하지 않습니다.",
      ],
      concepts: [
        { term: "origin", definition: "URL의 scheme·host·port로 정의되는 web security boundary입니다.", detail: ["path는 포함되지 않습니다.", "same-site와 다릅니다."] },
        { term: "CORS preflight", definition: "특정 cross-origin request 전에 browser가 OPTIONS로 method/headers/credentials 공유 허용을 확인하는 단계입니다.", detail: ["server 응답이 필요합니다.", "모든 요청에 생기지는 않습니다."] },
        { term: "opaque response", definition: "no-cors cross-origin fetch 등에서 script에 status/headers/body를 숨기는 filtered Response입니다.", detail: ["status가 0일 수 있습니다.", "JSON body를 읽을 수 없습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "서버 로그에는 200인데 browser는 CORS TypeError이고 body를 못 본다.", likelyCause: "server가 request origin/credentials에 맞는 CORS response를 제공하지 않았거나 preflight가 실패했습니다.", checks: ["Network에서 OPTIONS/actual request와 Origin/Access-Control fields를 봅니다.", "scheme-host-port와 credentials mode를 확인합니다.", "server allowlist/Vary/cache를 검사합니다."], fix: "server가 최소 허용 origin/method/headers/credentials를 정확히 응답하고 preflight/actual에 같은 policy를 적용합니다.", prevention: "allowed/denied origin과 credentialed/preflight integration tests를 둡니다." },
        { symptom: "no-cors로 바꾸니 status 0이고 JSON을 읽을 수 없다.", likelyCause: "opaque Response를 CORS 우회로 사용했습니다.", checks: ["response.type/status/body access를 확인합니다.", "third-party API CORS 지원을 확인합니다.", "controlled backend proxy 필요성을 봅니다."], fix: "server가 올바른 CORS를 제공하거나 same-origin backend proxy를 사용하고 proxy에서 auth/allowlist/SSRF를 검증합니다.", prevention: "no-cors data API workaround를 금지합니다." },
      ],
    },
    {
      id: "abort-latest-request-lifecycle",
      title: "AbortSignal은 underlying fetch를 중단하고 latest-request ownership은 늦은 결과가 UI를 덮지 못하게 합니다",
      lead: "Promise를 무시하는 것과 network/body work를 취소하는 것을 구분하고 controller 수명을 action/component에 묶습니다.",
      explanations: [
        "fetch에 signal을 전달하고 controller.abort(reason)를 호출하면 ongoing fetch/body consumption이 abort될 수 있고 Promise가 reason/AbortError로 reject됩니다. 이미 aborted signal은 시작 전 실패할 수 있습니다.",
        "검색어가 바뀌면 이전 controller를 abort하고 새 controller를 current로 저장합니다. finally에서 current===controller일 때만 loading/current를 정리해 오래된 operation이 새 UI를 끄지 않게 합니다.",
        "abort가 server side effect를 되감는다는 보장은 없습니다. client connection 취소와 server transaction cancellation/idempotency는 별도입니다.",
        "timeout은 controller+timer 또는 지원되는 signal composition으로 underlying fetch를 abort합니다. Promise.race만 쓰면 losing work가 남을 수 있습니다.",
        "headers 뒤 body.json 중에도 abort될 수 있으므로 try/catch는 fetch call만이 아니라 body/schema pipeline 전체를 포함합니다.",
        "unmount/route change에서 controller를 abort하고 DOM reference를 dispose합니다. superseded/user cancellation은 generic red error toast가 아니라 quiet state일 수 있습니다.",
      ],
      concepts: [
        { term: "abort propagation", definition: "AbortSignal을 fetch/body/child operations에 전달해 caller cancellation이 activity와 cleanup에 전파되게 하는 pattern입니다.", detail: ["Promise 무시와 다릅니다.", "reason을 분류합니다."] },
        { term: "latest-request wins", definition: "새 operation 시작 시 이전 것을 취소하고 current token/reference가 일치하는 결과만 shared UI에 반영하는 policy입니다.", detail: ["stale overwrite를 막습니다.", "finally도 guard합니다."] },
        { term: "stale response", definition: "오래 전에 시작한 request가 늦게 완료되어 현재 query와 다른 결과를 쓰려는 응답입니다.", detail: ["abort와 generation guard를 씁니다.", "HTTP cache와 다른 개념입니다."] },
      ],
      codeExamples: [
        {
          id: "abort-stale-search-request",
          title: "이전 검색 취소와 current controller 정리",
          language: "html",
          filename: "fetch-latest.html",
          purpose: "AbortSignal을 존중하는 fake fetch로 old rejection, new result와 generation-safe finally를 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>latest fetch</title></head>\n<body><pre id=\"out\"></pre><script type=\"module\">\n  function fakeFetch(query, { signal, delay }) {\n    return new Promise((resolve, reject) => {\n      const timer = setTimeout(() => resolve(new Response(JSON.stringify({query}), {headers:{'Content-Type':'application/json'}})), delay);\n      signal.addEventListener('abort', () => { clearTimeout(timer); reject(signal.reason); }, {once:true});\n    });\n  }\n  let current = null;\n  async function search(query, delay) {\n    current?.abort(new DOMException('superseded', 'AbortError'));\n    const controller = new AbortController();\n    current = controller;\n    try {\n      const response = await fakeFetch(query, {signal:controller.signal, delay});\n      const data = await response.json();\n      return `${query}=${data.query}`;\n    } catch (error) {\n      if (error.name === 'AbortError') return `${query}=aborted`;\n      throw error;\n    } finally {\n      if (current === controller) current = null;\n    }\n  }\n  const first = search('old', 20);\n  const second = search('new', 0);\n  const results = await Promise.all([first, second]);\n  document.querySelector('#out').textContent = [...results, `current=${current === null ? 'none' : 'active'}`].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-8", explanation: "fake fetch가 timer Response를 만들고 abort event에서 timer clear와 reason rejection을 수행합니다." },
            { lines: "9-23", explanation: "search는 previous abort, current controller, fetch+json, AbortError 분류와 guarded finally를 소유합니다." },
            { lines: "24-27", explanation: "old 직후 new가 취소하고 두 outcomes 및 final state를 기록합니다." },
          ],
          run: { environment: ["AbortController·Response·module top-level await를 지원하는 modern browser"], command: "browser에서 fetch-latest.html을 열고 결과 확인" },
          output: { value: "old=aborted\nnew=new\ncurrent=none", explanation: ["new search가 old controller를 abort합니다.", "new response JSON만 성공 result가 됩니다.", "reference-guarded finally가 current를 정확히 정리합니다."] },
          experiments: [
            { change: "previous abort를 제거합니다.", prediction: "둘 다 완료하며 unguarded render면 stale UI가 생길 수 있습니다.", result: "abort와 result token guard를 함께 씁니다." },
            { change: "finally reference check를 제거합니다.", prediction: "old finally가 new loading/current ownership을 지울 수 있습니다.", result: "operation identity를 확인합니다." },
            { change: "abort listener의 clearTimeout을 제거합니다.", prediction: "Promise는 rejection을 유지해도 underlying timer가 계속 실행됩니다.", result: "settlement와 resource cancellation을 함께 처리합니다." },
          ],
          sourceRefs: ["dom-abort", "fetch-standard", "web-fetch-async-source", "tc39-promise-source"],
        },
      ],
      diagnostics: [
        { symptom: "빠르게 검색하면 이전 query 결과가 새 화면을 덮어쓴다.", likelyCause: "multiple fetches를 취소/identify하지 않고 completion order대로 shared DOM에 render했습니다.", checks: ["request IDs와 start/settle/render order를 trace합니다.", "current controller/generation guard를 확인합니다.", "finally가 newer loading state를 지우는지 봅니다."], fix: "새 request에서 이전 signal을 abort하고 current token이 일치하는 response만 render/cleanup합니다.", prevention: "slow-old/fast-new, abort-after-headers, route disposal race tests를 둡니다." },
      ],
    },
    {
      id: "http-semantics-retry-cache-security",
      title: "HTTP method·status·headers는 retry·cache·credentials·side effect 계약을 전달합니다",
      lead: "모든 non-2xx에 같은 alert/retry를 적용하지 않고 protocol과 업무 의미를 함께 읽습니다.",
      explanations: [
        "GET/HEAD는 safe semantics를 기대하고 body를 사용하지 않습니다. POST/PUT/PATCH/DELETE의 idempotency는 server contract와 함께 보며 자동 retry 전에 side effect/idempotency key를 검토합니다.",
        "Accept는 원하는 response media type, Content-Type은 보낸 representation의 media type입니다. JSON body에는 JSON.stringify+application/json을 쓰되 GET에 불필요한 custom headers로 preflight를 만들지 않습니다.",
        "2xx에서도 200 body, 201 resource/Location, 202 accepted, 204 no content가 다릅니다. 401 authentication, 403 authorization, 404 absence/privacy, 409 conflict, 412 precondition, 422 validation, 429 rate limit은 recovery가 다릅니다.",
        "5xx/network error를 모두 retry하지 않습니다. safe/idempotent operation, Retry-After, exponential backoff+jitter, attempt/deadline budget, user cancellation을 고려합니다. POST response loss는 server side effect가 없었다는 증거가 아닙니다.",
        "fetch redirect default는 follow이며 final response.url/redirected와 credential/cross-origin redirect를 검토합니다. statusText는 비거나 locale/user message에 부적합할 수 있어 stable code를 씁니다.",
        "HTTP cache는 Cache-Control, ETag/Last-Modified, Vary와 request cache mode에 따라 동작합니다. 모든 요청에 no-store를 붙이거나 stale data를 무조건 error로 해석하지 않습니다.",
        "Authorization/token을 URL/query/log에 넣지 않고 browser bundle에 server secret을 포함하지 않습니다. HTTPS/mixed-content, CSP connect-src와 server auth/authorization을 defense in depth로 둡니다.",
      ],
      concepts: [
        { term: "HTTP semantics", definition: "method/status/fields가 request intent, representation, cache와 outcome을 전달하는 protocol meaning입니다.", detail: ["status별 recovery가 다릅니다.", "application contract와 결합합니다."] },
        { term: "retry budget", definition: "idempotency·attempt count·deadline·backoff/jitter·server hints로 재시도를 제한하는 policy입니다.", detail: ["모든 오류를 재시도하지 않습니다.", "cancellation을 존중합니다."] },
        { term: "Accept vs Content-Type", definition: "Accept는 원하는 response, Content-Type은 현재 message body의 media type을 설명하는 fields입니다.", detail: ["서로 대체하지 않습니다.", "CORS preflight와 parsing에 영향 줍니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "POST 저장 timeout 뒤 자동 재시도해 record가 두 개 생긴다.", likelyCause: "response를 못 받은 것과 server side effect가 없었던 것을 동일시해 non-idempotent operation을 반복했습니다.", checks: ["server transaction logs와 idempotency key를 확인합니다.", "client attempts/deadline을 봅니다.", "response loss 시점을 구분합니다."], fix: "server-supported idempotency key/result lookup을 사용하고 불확실 outcome UI를 제공하며 무조건 POST retry를 제거합니다.", prevention: "response-loss/duplicate-submit/idempotency integration test를 둡니다." },
      ],
    },
    {
      id: "remote-data-ui-testing-observability",
      title: "Fetch UI는 idle·loading·data·empty·error·aborted를 명시하고 protocol fixtures로 검증합니다",
      lead: "console.log 하나로 끝내지 않고 사용자가 지금 할 수 있는 action과 재시도 가능성을 state machine으로 보여 줍니다.",
      explanations: [
        "load action은 idle→loading→success-data/success-empty/http/network/parse/schema/aborted transition을 가집니다. refresh/search에서 previous data를 유지할지 skeleton으로 바꿀지 정책을 정합니다.",
        "loading 중 button disabled만 하면 이유를 알기 어렵습니다. aria-busy/status와 cancel/retry를 제공하고 focus를 무조건 error region으로 빼앗지 않습니다.",
        "empty array는 success data 없음이고 404/204와 같지 않습니다. endpoint contract에 따라 empty collection, missing resource와 no-content action을 구분합니다.",
        "unit tests는 Response/fake fetch로 status/body/schema/abort를 만들고 integration은 local mock HTTP server/service worker로 actual headers, redirects, CORS/preflight, streaming/cache를 확인합니다.",
        "mock이 body single-use나 browser CORS를 우회할 수 있으므로 unit과 real-browser protocol tests가 모두 필요합니다. production endpoint 의존 flaky tests를 피합니다.",
        "telemetry에는 method template, route name, status/error category, duration/size bucket, abort reason과 correlation ID만 기록합니다. query/body/Authorization/cookies/raw response/PII는 redaction합니다.",
        "performance는 request waterfall, cache/TTFB/download, parse/schema, DOM render를 분리합니다. 대형 JSON/render long task와 concurrency/rate limit을 profile합니다.",
      ],
      concepts: [
        { term: "remote-data state machine", definition: "request lifecycle을 idle/loading/data/empty/error/aborted states와 transitions로 모델링한 UI contract입니다.", detail: ["previous data policy가 있습니다.", "retry/cancel을 제공합니다."] },
        { term: "protocol fixture", definition: "status·headers·body bytes·delay·abort·CORS/redirect를 재현하는 mock Response 또는 local server scenario입니다.", detail: ["unit/browser를 나눕니다.", "production network를 쓰지 않습니다."] },
        { term: "privacy-safe network telemetry", definition: "content/credentials를 제외하고 route·status/category·duration/size buckets와 correlation만 수집하는 policy입니다.", detail: ["raw body를 log하지 않습니다.", "server trace와 연결합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "fetch 실패 후 화면은 계속 로딩이고 button도 비활성화다.", likelyCause: "success path에서만 loading을 해제하거나 operation ownership이 없습니다.", checks: ["error/abort/schema branches와 finally를 trace합니다.", "current generation check를 확인합니다.", "UI transition table과 DOM invariant를 비교합니다."], fix: "generation-safe finally에서 loading resource를 정리하고 error/aborted state와 retry/cancel action을 render합니다.", prevention: "각 terminal outcome과 overlapping request에서 aria-busy/button/status invariants를 E2E test합니다." },
      ],
      expertNotes: [
        "Service Worker가 offline/cache Response를 반환할 수 있어 fetch success를 origin network success로 단정하지 않습니다.",
        "NDJSON streaming parser는 chunk split, TextDecoder state, line/item limits, abort와 backpressure를 별도 전문가 실습으로 다룹니다.",
        "Private Network Access 등 browser policies는 진화할 수 있으므로 internal address fetch를 CORS 하나로 보호하지 않고 server/network authorization을 둡니다.",
      ],
    },
  ],
  lab: {
    title: "원본 sample.txt loader를 JSON 과정 목록·오류 분류·취소·접근 가능한 상태가 있는 data client로 진화시키기",
    scenario: "현재 code는 text를 읽어 pre에 넣고 console error 또는 generic message만 표시합니다. 인벤토리는 JSON이지만 원본은 text이며 status/body/schema/CORS/abort/stale/UI lifecycle이 분리되지 않았습니다.",
    setup: [
      "원본 ex12/ex13과 sample.txt 세 파일을 read-only evidence로 준비합니다.",
      "local mock HTTP server에 200 text/JSON, 204, 404 JSON, 500 HTML, invalid JSON, wrong schema, slow/stream/CORS endpoints를 만듭니다.",
      "AbortController, slow-old/fast-new, route disposal, offline와 credentialed cross-origin scenarios를 준비합니다.",
      "keyboard/status/aria-busy와 large/malicious-looking JSON values, privacy log inspection을 준비합니다.",
    ],
    steps: [
      "원본 text loader를 실행해 resolved URL, status/ok/Content-Type/bodyUsed와 text output을 기록합니다.",
      "Request builder에 URLSearchParams, Accept, method/body/Content-Type와 credentials contract를 구현합니다.",
      "fetch→accepted status→media/body parse→runtime schema→domain model stages와 Error classes를 작성합니다.",
      "JSON course list를 createElement/textContent로 render하고 data/empty/loading/error/aborted state를 분리합니다.",
      "새 검색에서 이전 controller를 abort하고 generation/reference guard로 stale render/finally를 막습니다.",
      "CORS allowed/denied, preflight, credentialed origin과 no-cors opaque response를 local origins에서 재현합니다.",
      "404/500/204/invalid JSON/wrong schema/large body/timeout/abort를 fixtures와 real browser로 test합니다.",
      "CSP connect-src, HTTPS/mixed-content, runtime limits와 redacted telemetry를 점검합니다.",
    ],
    expectedResult: [
      "원본 text와 확장 JSON flow가 source coverage에 구분되고 response reader/media contract가 일치합니다.",
      "network·HTTP·parse·schema·abort errors가 다른 class/message/retry policy로 처리됩니다.",
      "Response body를 한 owner만 소비하고 clone/stream/size 비용을 명시합니다.",
      "unknown JSON은 runtime validation 후 safe text DOM으로 렌더되어 tag-like string이 element가 되지 않습니다.",
      "rapid searches와 route disposal 뒤 stale UI/pending fetch/timer/listener가 없습니다.",
      "CORS/credentials/CSRF/authorization/CSP가 역할을 나누고 logs에 URL query/body/token/PII가 없습니다.",
    ],
    cleanup: ["current controller를 abort하고 mock server/service worker/cache/test origins와 pending timers/listeners를 정리합니다.", "synthetic credentials/payloads, DevTools requests와 body references를 제거합니다."],
    extensions: ["NDJSON stream을 TextDecoderStream과 line parser로 처리하고 abort/backpressure/limits를 구현합니다.", "ETag conditional GET과 offline stale-while-revalidate UI를 비교합니다.", "bounded concurrency detail loader와 allSettled partial-error report를 구현합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 sample.txt fetch를 status·Content-Type·bodyUsed·text output과 error taxonomy로 다시 작성하세요.", requirements: ["local HTTP server에서 실행합니다.", "response.ok/status를 body reader 전 확인합니다.", "body single-use와 clone 결과를 재현합니다.", "network/404/invalid decoding을 분류합니다.", "console-only error 대신 status/retry를 제공합니다."], hints: ["404도 Response로 fulfill될 수 있습니다.", "Response와 body text는 다른 단계입니다."], expectedOutcome: "원본 text loader의 protocol/body 상태를 설명하고 재현 가능한 output과 복구 UI를 제공합니다.", solutionOutline: ["request/response/body/UI snapshots를 나눕니다.", "HttpError와 NetworkError를 별도 처리합니다."] },
    { difficulty: "응용", prompt: "취소 가능한 JSON 과정 검색 목록을 runtime schema와 safe DOM으로 구현하세요.", requirements: ["URLSearchParams와 Accept를 사용합니다.", "status/media/json/schema stages를 분리합니다.", "data/empty/loading/http/parse/schema/abort UI를 구현합니다.", "이전 request abort와 generation guard를 둡니다.", "textContent로 렌더하고 URL fields는 allowlist합니다."], hints: ["TypeScript assertion은 runtime validation이 아닙니다.", "finally도 current operation인지 확인합니다."], expectedOutcome: "rapid query와 malformed/malicious payload에서도 stale/XSS/leak 없이 정확한 상태를 표시합니다.", solutionOutline: ["unknown→Course parser와 load-state reducer를 먼저 만듭니다.", "fake Response와 local server tests를 나눕니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 HTTP data client·CORS·retry·telemetry 표준을 설계하세요.", requirements: ["Request URL/method/headers/body/credentials contract를 정의합니다.", "status/body/schema/Error taxonomy와 recovery를 표로 만듭니다.", "CORS/preflight/credentials와 CSRF/auth/CSP 역할을 분리합니다.", "abort/timeout/idempotency/backoff/cache/redirect/stream limits를 포함합니다.", "protocol fixtures, browser integration, accessibility/performance/privacy gates를 설계합니다."], hints: ["race timeout은 loser를 자동 취소하지 않습니다.", "CORS는 server authorization이 아닙니다."], expectedOutcome: "팀이 HTTP/JSON/CORS/stale/security 결함 없이 remote-data 기능을 운영하는 표준이 완성됩니다.", solutionOutline: ["Request→Response→Body→Domain→UI와 cancellation 흐름을 각각 그립니다.", "endpoint별 success/status/media/schema 표를 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "fetch Promise는 404에서 자동 reject되나요?", answer: "일반적으로 아닙니다. Response로 fulfill되고 response.ok/status를 검사해야 합니다." },
    { question: "response.json은 Response 생성과 동시에 완료돼 있나요?", answer: "아닙니다. body stream을 비동기로 소비·JSON parse하는 Promise를 반환합니다." },
    { question: "Response body를 text와 json으로 두 번 읽을 수 있나요?", answer: "같은 body는 보통 한 번만 소비합니다. 필요하면 소비 전에 clone하되 비용을 고려합니다." },
    { question: "JSON.parse 성공이면 Course[]라고 믿어도 되나요?", answer: "아닙니다. syntax만 valid하며 runtime schema/type/range/size validation이 필요합니다." },
    { question: "Content-Type과 Accept의 차이는 무엇인가요?", answer: "Content-Type은 현재 body representation, Accept는 원하는 response media types를 설명합니다." },
    { question: "204 Response에서 항상 json을 호출해야 하나요?", answer: "아닙니다. no-content contract이면 body parsing 없이 처리합니다." },
    { question: "mode:no-cors가 CORS 오류를 해결하나요?", answer: "아닙니다. opaque Response로 status/body를 읽지 못해 JSON API 해결책이 아닙니다." },
    { question: "CORS가 authorization과 CSRF를 대신하나요?", answer: "아닙니다. CORS는 response sharing protocol이며 server auth/authorization/CSRF 방어가 별도입니다." },
    { question: "Promise.race timeout만으로 fetch가 중단되나요?", answer: "아닙니다. AbortSignal을 fetch에 전달해 underlying request/body를 취소해야 합니다." },
    { question: "이전 검색을 abort하면 stale UI 문제가 완전히 끝나나요?", answer: "result/finally generation guard도 두어 late/non-cancelable work가 current UI를 건드리지 않게 합니다." },
    { question: "TypeScript interface가 network JSON을 runtime 검증하나요?", answer: "아닙니다. compile-time 정보이므로 explicit schema parser가 필요합니다." },
    { question: "statusText를 사용자 error message로 써도 되나요?", answer: "비거나 runtime에 따라 달라질 수 있어 stable code와 localized application message를 사용합니다." },
  ],
  completionChecklist: [
    "fetch Request→policy/cache/service worker/network/CORS→Response→body pipeline을 설명했다.",
    "relative URL/deployment base를 확인하고 URLSearchParams로 query를 구성했다.",
    "method/idempotency와 Accept/Content-Type/credentials/cache/redirect를 endpoint contract로 정했다.",
    "network rejection과 HTTP status failure를 response.ok/status로 구분했다.",
    "200/201/202/204와 주요 4xx/5xx의 body/retry/recovery를 정의했다.",
    "Response bodyUsed/single reader/clone과 large/streaming 비용을 검증했다.",
    "JSON syntax failure와 runtime schema/size/precision validation을 분리했다.",
    "external values를 textContent와 context-specific URL/property validation으로 렌더링했다.",
    "CORS/preflight/credentials/opaque response를 same-origin policy와 연결했다.",
    "CORS와 CSRF/authentication/authorization/CSP connect-src를 별도 방어층으로 설계했다.",
    "AbortSignal로 previous/timeout/dispose fetch와 body consumption을 취소했다.",
    "current generation/reference가 일치하는 operation만 render/finally cleanup했다.",
    "idle/loading/data/empty/http/network/parse/schema/aborted UI와 retry/cancel을 제공했다.",
    "fake Response와 local HTTP/CORS server로 unit/protocol/browser tests를 통과했다.",
    "URL/body/headers/token/cookies/raw response/PII를 telemetry에서 redaction했다.",
  ],
  nextSessions: ["js-11-fetch-xml-domparser-capstone"],
  sources: [
    { id: "web-fetch-text-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex12_fetch.html", usedFor: ["fetch introduction", "click loader", "relative sample.txt", "Promise then chain", "Response.text", "textContent", "catch logging"], evidence: "sample.txt를 fetch→text→pre에 표시하는 원본 chain을 Request/Response/body ownership·error UI와 exact example의 출발점으로 사용했습니다." },
    { id: "web-fetch-async-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex13_fetch.html", usedFor: ["async click handler", "await fetch", "Response.ok", "Error throw", "Response.text", "try/catch", "user error text"], evidence: "ok 검사와 async/await 원본을 status/body/error taxonomy·AbortSignal·JSON schema pipeline으로 확장했습니다." },
    { id: "web-sample-text-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/sample.txt", usedFor: ["actual text payload", "Korean UTF-8 text", "repeated lines", "Response.text result", "source-versus-inventory JSON mismatch"], evidence: "원본 target이 JSON이 아니라 반복 한글 plain text임을 확인해 text lesson을 보존하고 JSON 확장 범위를 명시했습니다." },
    { id: "fetch-standard", repository: "WHATWG Fetch Standard", path: "Fetch Standard", publicUrl: "https://fetch.spec.whatwg.org/", usedFor: ["request/response/body infrastructure", "fetch pipeline", "network error", "redirect/cache/service worker", "credentials", "abort"], evidence: "browser fetch processing과 Request/Response/body/security semantics의 normative 기준으로 사용했습니다." },
    { id: "fetch-response", repository: "WHATWG Fetch Standard", path: "#response-class", publicUrl: "https://fetch.spec.whatwg.org/#response-class", usedFor: ["status/ok/type/url/headers", "Body mixin", "bodyUsed", "clone", "text/json readers"], evidence: "HTTP failure와 body parsing·clone examples의 API 기준으로 사용했습니다." },
    { id: "fetch-cors", repository: "WHATWG Fetch Standard", path: "#http-cors-protocol", publicUrl: "https://fetch.spec.whatwg.org/#http-cors-protocol", usedFor: ["CORS requests/responses", "preflight", "credentials", "allowed origins/methods/headers", "opaque response", "Origin/Vary"], evidence: "response sharing과 server CORS configuration을 authentication/CSRF와 구분하는 기준으로 사용했습니다." },
    { id: "http-semantics", repository: "IETF RFC Editor", path: "RFC 9110 HTTP Semantics", publicUrl: "https://www.rfc-editor.org/rfc/rfc9110", usedFor: ["methods", "status codes", "fields", "representation", "redirect", "retry/idempotency", "cache validators"], evidence: "status별 recovery, method idempotency와 Accept/Content-Type semantics를 보강했습니다." },
    { id: "json-rfc", repository: "IETF RFC Editor", path: "RFC 8259 JSON", publicUrl: "https://www.rfc-editor.org/rfc/rfc8259", usedFor: ["JSON grammar/types", "object/array/string/number", "interoperability", "encoding", "numeric precision", "parser boundary"], evidence: "원본 text와 JSON을 구분하고 syntax·number/string limits와 schema boundary를 설명하는 기준으로 사용했습니다." },
    { id: "dom-abort", repository: "WHATWG DOM Standard", path: "#aborting-ongoing-activities", publicUrl: "https://dom.spec.whatwg.org/#aborting-ongoing-activities", usedFor: ["AbortController/Signal", "abort reason", "already aborted", "abort event", "resource cleanup", "signal composition"], evidence: "previous search/timeout/disposal에서 underlying fetch와 fake adapter를 취소하는 lifecycle의 기준으로 사용했습니다." },
    { id: "csp-connect-src", repository: "W3C Web Application Security Working Group", path: "CSP3 connect-src", publicUrl: "https://www.w3.org/TR/CSP3/#directive-connect-src", usedFor: ["allowed connection sources", "fetch/XHR/WebSocket defense", "report/enforce", "destination restriction"], evidence: "page network destinations를 제한하는 deployment defense를 CORS/server authorization과 분리했습니다." },
    { id: "dom-mutation-source", repository: "WHATWG DOM Standard", path: "DOM create/append/textContent", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["safe list creation", "textContent", "node insertion", "external value rendering"], evidence: "validated JSON records를 HTML parsing 없이 safe nodes로 렌더링하는 기준으로 사용했습니다." },
    { id: "tc39-promise-source", repository: "Ecma International TC39", path: "Promise/async function semantics", publicUrl: "https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-objects", usedFor: ["fetch/body Promise chaining", "async/await", "error propagation", "Promise.all", "settlement/cancellation distinction"], evidence: "fetch와 readers의 Promise lifecycle을 이전 세션의 language semantics와 연결했습니다." },
  ],
  sourceCoverage: {
    filesRead: 3,
    filesUsed: 3,
    uncoveredNotes: [
      "인벤토리 제목/목표는 JSON이지만 두 HTML 원본 모두 sample.txt를 Response.text로 읽고 실제 sample.txt도 반복 한글 plain text입니다. text 흐름을 삭제하지 않고 설명한 뒤 JSON/RFC/schema 확장을 별도 경계로 추가했습니다.",
      "원본은 relative fetch, then/async-await, ok와 generic catch를 제공합니다. Request options, body stream/clone, status taxonomy, JSON schema, CORS/credentials, abort/stale/CSP/streaming은 공식 규격으로 보강했습니다.",
      "XML response text를 DOMParser로 parse하고 namespace/parsererror를 처리하는 비교 capstone은 js-11에서 JSON pipeline과 나란히 이어집니다.",
    ],
  },
} satisfies DetailedSession;

export default session;

const expertSession = session as DetailedSession;
expertSession.level = "전문가";
expertSession.estimatedMinutes = 430;
expertSession.chapters.push(
  {
    id: "content-type-encoding-streaming-backpressure",
    title: "Content-Type·byte decoding·ReadableStream·backpressure 경계를 보존합니다",
    lead: "fetch 결과는 곧바로 JSON object가 아니라 status·headers와 byte stream을 가진 Response입니다. media type을 확인하고 body를 한 번 소비하며 decoder·parser·schema 단계를 분리합니다.",
    explanations: [
      "Response body는 nullable ReadableStream이며 `text()`, `json()`, `arrayBuffer()`, `blob()` 같은 convenience method는 stream을 소비해 Promise를 반환합니다. `bodyUsed`는 body가 disturbed되었는지 보여 주고, 한 번 읽은 같은 Response를 다시 읽으면 TypeError가 날 수 있습니다. 두 consumer가 정말 필요하면 읽기 전에 clone하되 큰 body의 buffering 비용을 측정합니다.",
      "HTTP status와 media type은 parser 선택 전에 검사합니다. fetch Promise는 HTTP 404/500만으로 reject되지 않으므로 `response.ok` 또는 허용 status 집합을 확인하고, Content-Type을 case-insensitive media type으로 parse해 `application/json`이나 정의된 `+json`만 JSON parser로 보냅니다. 잘못된 server의 HTML 오류 page를 JSON.parse error 하나로 뭉개지 않습니다.",
      "Content-Type의 charset parameter는 representation metadata지만 Fetch의 `Response.text()` decoding 규칙과 각 body mixin method의 실제 규격을 확인해야 합니다. 임의 charset을 반드시 지원해야 하면 `arrayBuffer()`로 bytes를 얻고 allowlisted TextDecoder label을 사용하며, unsupported label·invalid sequence·BOM·declared/actual mismatch 정책을 명시합니다.",
      "UTF-8 multi-byte character는 network chunk 경계에서 나뉠 수 있습니다. chunk마다 `new TextDecoder().decode(chunk)`를 독립 호출하면 replacement character가 생길 수 있으므로 하나의 decoder에 `{ stream: true }`를 사용하고 끝에서 빈 decode로 flush합니다. `fatal:true`는 invalid bytes를 오류로 만들지만 제품이 replacement를 허용할지는 데이터 contract로 결정합니다.",
      "`response.body.getReader()`를 호출하면 stream이 lock됩니다. read loop는 `{ value, done }`를 처리하고 정상 종료에서 decoder를 flush하며, 취소·오류·size limit에서는 reader.cancel과 AbortController를 연결합니다. lock을 해제한다고 이미 소비한 body가 재사용되는 것은 아니며, reader·signal의 소유자를 명확히 합니다.",
      "streaming은 전체 buffering을 줄이고 점진 처리를 가능하게 하지만 JSON document 하나는 일반 JSON.parse 전에 완전한 text가 필요합니다. NDJSON처럼 record framing이 있는 format이나 검증된 incremental parser가 없다면 chunk 경계에서 임의 JSON substring을 parse하지 않습니다. streaming parser는 depth·token length·duplicate key·partial record 오류 계약까지 별도 검토합니다.",
      "backpressure는 consumer 속도를 producer에게 전달하는 stream 계약입니다. Web Streams의 desiredSize와 pull을 이해하지 않고 start에서 대량 chunk를 모두 enqueue하면 memory 이점이 줄어듭니다. network body에서는 user agent가 source를 관리하지만 transform pipeline도 각 stage의 queue size와 취소 전파를 보존해야 합니다.",
      "Content-Length는 progress hint이지 무조건 신뢰할 수 있는 안전한 실제 크기가 아닙니다. 압축, transfer encoding, CORS header exposure, 잘못된 server 값이 있고 decompressed size는 더 클 수 있습니다. 읽은 byte/character/record 수를 직접 제한하고 초과 시 reader와 fetch를 중단하며 partial data를 성공으로 render하지 않습니다.",
      "decode된 JSON syntax와 application schema는 별도 gate입니다. JSON.parse 성공 뒤에도 object/array, required keys, string length, finite numeric range, URL scheme, enum을 검사하고 unknown keys 정책을 정합니다. 숫자 precision이 중요한 ID·금액은 wire string 또는 lossless contract를 사용합니다.",
      "test fixture는 multi-byte 문자를 byte 중간에서 분할하고, empty body, 204, wrong Content-Type, invalid UTF-8, truncated JSON, oversize, mid-stream error, abort를 포함합니다. browser DevTools Network의 Headers·Timing·Response와 code의 status/content-type/bodyUsed trace를 대조하면 transport·decode·parse·schema 단계가 섞인 오류를 찾을 수 있습니다.",
    ],
    concepts: [
      { term: "disturbed body", definition: "Response 또는 Request body stream이 읽히거나 취소되어 다시 소비할 수 없는 상태입니다.", detail: ["bodyUsed로 일부 상태를 관찰합니다.", "clone은 소비 전에 결정합니다."] },
      { term: "streaming decode", definition: "한 TextDecoder가 chunk 사이의 불완전한 multi-byte sequence 상태를 유지하며 bytes를 text로 변환하는 방식입니다.", detail: ["decode에 stream:true를 사용합니다.", "끝에서 flush하고 invalid-byte 정책을 정합니다."] },
      { term: "backpressure", definition: "consumer 처리 속도와 queue 여유를 upstream producer에 전달해 무제한 buffering을 피하는 stream 흐름 제어입니다.", detail: ["cancel/error도 upstream에 전파합니다.", "queue size를 profile합니다."] },
    ],
    codeExamples: [
      {
        id: "utf8-stream-response-contract",
        title: "한글 byte가 chunk 사이에서 갈리는 Response stream을 안전하게 decode",
        language: "javascript",
        filename: "response-stream.mjs",
        purpose: "synthetic HTTP Response의 status·Content-Type을 검사하고 하나의 streaming TextDecoder로 UTF-8 bytes를 복원한 뒤 JSON schema 경계와 bodyUsed를 exact 확인합니다.",
        code: "const bytes = new TextEncoder().encode('{\"message\":\"안녕\",\"count\":2}');\nconst firstMultibyte = bytes.findIndex((byte) => byte >= 0x80);\nconst split = firstMultibyte + 1;\n\nconst stream = new ReadableStream({\n  start(controller) {\n    controller.enqueue(bytes.slice(0, split));\n    controller.enqueue(bytes.slice(split));\n    controller.close();\n  },\n});\n\nconst response = new Response(stream, {\n  status: 206,\n  headers: {\n    'content-type': 'application/json; charset=utf-8',\n    'cache-control': 'no-store',\n  },\n});\n\nconsole.log(`status=${response.status}, ok=${response.ok}`);\nconsole.log(`content-type=${response.headers.get('content-type')}`);\n\nconst reader = response.body.getReader();\nconst decoder = new TextDecoder('utf-8', { fatal: true });\nlet text = '';\nwhile (true) {\n  const { value, done } = await reader.read();\n  if (done) break;\n  text += decoder.decode(value, { stream: true });\n}\ntext += decoder.decode();\n\nconst data = JSON.parse(text);\nif (typeof data.message !== 'string' || !Number.isInteger(data.count)) {\n  throw new TypeError('SCHEMA_ERROR');\n}\nconsole.log(`message=${data.message}, count=${data.count}`);\nconsole.log(`bodyUsed=${response.bodyUsed}`);",
        walkthrough: [
          { lines: "1-3", explanation: "JSON UTF-8 bytes에서 첫 multi-byte character의 첫 byte 뒤를 찾아 의도적으로 잘못된 문자 경계에서 나눕니다." },
          { lines: "5-10", explanation: "두 chunk를 enqueue하고 close하는 최소 ReadableStream source를 만듭니다." },
          { lines: "12-19", explanation: "206 status와 JSON media type, no-store metadata를 가진 synthetic Response를 구성합니다." },
          { lines: "21-22", explanation: "body를 읽기 전에 status/ok와 실제 Content-Type header를 관찰합니다." },
          { lines: "24-32", explanation: "reader와 단일 fatal UTF-8 decoder를 사용해 chunk 사이 decoder state를 유지하고 마지막에 flush합니다." },
          { lines: "34-39", explanation: "완전한 text만 JSON.parse하고 최소 schema를 검증한 뒤 domain 값과 disturbed body 상태를 출력합니다." },
        ],
        run: { environment: ["Node.js 20 이상", "response-stream.mjs를 UTF-8로 저장"], command: "node response-stream.mjs" },
        output: { value: "status=206, ok=true\ncontent-type=application/json; charset=utf-8\nmessage=안녕, count=2\nbodyUsed=true", explanation: ["206도 2xx이므로 Response.ok는 true지만 application이 partial content를 허용하는지는 별도 정책입니다.", "한글 byte가 chunk 사이에서 나뉘어도 한 decoder의 streaming state가 원문을 복원합니다.", "reader가 body를 소비한 뒤 bodyUsed는 true이고 같은 Response를 다시 읽지 않습니다."] },
        experiments: [
          { change: "각 chunk에서 새 TextDecoder로 stream 옵션 없이 decode합니다.", prediction: "분할된 첫 한글 문자가 replacement character들로 손상될 수 있습니다.", result: "network chunk와 character boundary가 일치하지 않음을 확인합니다." },
          { change: "Content-Type을 text/html로 바꾸되 JSON.parse는 그대로 둡니다.", prediction: "synthetic data는 우연히 parse되지만 production pipeline은 media-type mismatch로 먼저 실패해야 합니다.", result: "body 내용 sniffing보다 명시적 representation contract를 우선합니다." },
          { change: "browser fetch adapter에서 다른 origin·credentials 요청을 실행하고 DevTools Network의 preflight, CORS error, Cache와 CSP console을 관찰합니다.", prediction: "JavaScript에 Response가 노출되기 전 정책 단계에서 실패하거나 cache에 의해 network 전송이 달라질 수 있습니다.", result: "CORS·CSP·cache·HTTP·body parsing을 서로 다른 진단 층으로 기록합니다." },
        ],
        sourceRefs: ["fetch-standard", "fetch-response", "fetch-cors", "http-semantics", "json-rfc", "csp-connect-src", "tc39-promise-source"],
      },
    ],
    diagnostics: [
      { symptom: "stream으로 받은 한글 JSON이 간헐적으로 깨져 replacement character와 parse error가 생긴다.", likelyCause: "각 network chunk를 독립 TextDecoder로 decode해 multi-byte sequence가 chunk 경계에서 끊겼습니다.", checks: ["raw byte fixture를 multi-byte 중간에서 분할해 재현합니다.", "하나의 decoder와 stream:true 사용 여부를 확인합니다.", "마지막 decoder flush와 fatal policy를 검사합니다."], fix: "하나의 TextDecoder instance로 모든 chunk를 streaming decode하고 종료에서 flush한 뒤 완전한 framing 단위만 parser에 전달합니다.", prevention: "모든 지원 문자와 split offset을 순회하는 byte-boundary test를 둡니다." },
      { symptom: "대용량 응답 취소 뒤에도 memory가 유지되고 network download가 계속된다.", likelyCause: "UI Promise만 버리고 reader.cancel·fetch AbortController·buffer references를 정리하지 않았습니다.", checks: ["Network pending/transfer와 heap retaining path를 확인합니다.", "reader lock, controller signal, accumulated chunks owner를 추적합니다.", "size-limit/error/finally 모든 종료 경로를 비교합니다."], fix: "한 lifecycle owner가 reader.cancel과 controller.abort를 실행하고 buffers/references를 해제하며 stale render를 generation으로 차단합니다.", prevention: "oversize·mid-stream error·user cancel 뒤 pending resource와 retained buffer가 0인지 통합 테스트합니다." },
    ],
    expertNotes: ["Response.text의 decoding 의미와 charset 지원을 일반 HTTP library의 동작과 혼동하지 말고 Fetch Standard 및 실제 target runtime으로 검증합니다.", "JSON streaming이 필요하면 임의 chunk parse가 아니라 명시적 framing format과 검증된 incremental parser, record별 size/depth/schema limit를 선택합니다."],
  },
  {
    id: "cors-cache-status-network-observability",
    title: "CORS·cache·status·CSP를 분리해 HTTP 실패를 관측하고 복구합니다",
    lead: "fetch TypeError 하나를 모두 네트워크 장애라고 부르지 않습니다. browser policy, HTTP representation, cache, body decode, application schema를 단계별로 분류하고 DevTools evidence로 확인합니다.",
    explanations: [
      "fetch가 reject하는 TypeError는 DNS/TLS/connection 실패뿐 아니라 CORS·mixed content·CSP 같은 browser policy 차단도 포함할 수 있고 script에 세부 원인이 제한될 수 있습니다. Console과 Network panel을 함께 보고, 사용자에게 내부 보안 정책 문구 대신 안전한 복구 메시지를 제공합니다.",
      "CORS는 browser가 다른 origin response를 script에 노출할지 정하는 HTTP 기반 공유 protocol입니다. server 인증·인가나 CSRF 방어를 대신하지 않으며 curl/server-to-server 요청을 막지 않습니다. 허용 origin은 요청 Origin을 검증해 정확히 반환하고 credentials와 wildcard 조합 제한, `Vary: Origin` cache 분리를 지킵니다.",
      "simple request 조건을 벗어난 method/header/content type은 preflight OPTIONS를 유발할 수 있습니다. preflight 성공과 실제 요청 성공은 별개이며 redirect·credentials·allowed headers/methods를 Network panel에서 각각 확인합니다. client에서 임의 Access-Control-Allow-Origin request header를 추가해 해결할 수 없습니다.",
      "credentials option은 cookie 전송·response exposure와 SameSite/secure cookie 정책에 연결됩니다. cross-origin credential 요청은 명시적 origin과 Access-Control-Allow-Credentials가 필요하지만 이것이 사용자의 업무 권한을 증명하지 않습니다. server는 session/token 검증과 object-level authorization을 수행합니다.",
      "CSP `connect-src`는 page가 fetch/XHR/WebSocket/EventSource 등으로 연결할 destination을 제한하는 defense-in-depth입니다. CORS가 허용해도 CSP가 막을 수 있고 그 반대도 가능하므로 두 정책을 하나로 설명하지 않습니다. report-only로 필요한 origin을 inventory한 뒤 최소 allowlist를 enforce합니다.",
      "HTTP status는 복구 정책의 input입니다. 204는 성공이지만 JSON body를 기대하면 안 되고, 304는 일반 fetch application code가 직접 처리하는 응답과 cache revalidation 맥락을 구분하며, 401과 403, 404, 409, 412, 422, 429, 5xx를 모두 generic retry로 만들지 않습니다.",
      "retry는 method idempotency, request body 재생 가능성, Retry-After, exponential backoff와 jitter, 총 deadline, abort를 고려합니다. POST가 업무적으로 idempotent하지 않다면 자동 retry가 중복 생성·결제를 만들 수 있으므로 idempotency key와 server contract 없이는 재전송하지 않습니다.",
      "browser HTTP cache는 Cache-Control, validators(ETag/Last-Modified), freshness, Vary와 request cache mode의 영향을 받습니다. `cache: 'no-store'`를 습관적으로 붙이면 성능과 offline behavior를 잃고, 반대로 private 사용자 응답을 public shared cache에 두면 정보 노출 위험이 있습니다. representation별 cacheability를 server와 함께 설계합니다.",
      "DevTools Network의 Disable cache는 도구가 열린 동안 test 조건을 바꿀 수 있습니다. 정상 cache, hard reload, service worker bypass, offline, slow network를 분리하고 Size/Transferred, from memory/disk cache, request/response headers, Timing을 저장합니다. 테스트에서 cache를 지웠다는 사실도 재현 절차에 기록합니다.",
      "관측 event는 phase, safe endpoint template, method, status, duration, response size bucket, retry count, abort category, schema error code 정도로 제한합니다. Authorization, cookie, query PII, raw response body를 기록하지 않습니다. correlation id는 server log와 연결하되 사용자에게 공개해도 안전한 값인지 검토합니다.",
    ],
    concepts: [
      { term: "CORS", definition: "browser가 origin 간 요청과 response 노출을 HTTP headers와 preflight로 조정하는 공유 protocol입니다.", detail: ["server authorization을 대체하지 않습니다.", "credential·cache Vary 정책과 함께 봅니다."] },
      { term: "cache validator", definition: "ETag 또는 Last-Modified처럼 client가 가진 representation이 여전히 유효한지 조건부 요청으로 확인하는 metadata입니다.", detail: ["freshness와 다릅니다.", "Vary가 cache key 선택에 영향을 줍니다."] },
      { term: "network failure taxonomy", definition: "policy/network, HTTP status, media/decode, syntax, schema, stale/cancel 단계로 실패를 분류해 서로 다른 복구와 telemetry를 적용하는 체계입니다.", detail: ["fetch TypeError 하나로 합치지 않습니다.", "DevTools evidence와 application code를 연결합니다."] },
    ],
    codeExamples: [],
    diagnostics: [
      { symptom: "서버는 200을 기록했지만 browser fetch는 TypeError이고 JavaScript에서 status를 읽을 수 없다.", likelyCause: "응답이 도착했어도 CORS·CSP·mixed-content 같은 browser policy에서 script exposure가 차단됐습니다.", checks: ["Console의 policy 오류와 Network의 request/preflight를 함께 확인합니다.", "Origin·ACAO·credentials·Vary와 CSP connect-src를 검사합니다.", "같은 요청의 curl 성공을 CORS 성공 증거로 오해하지 않습니다."], fix: "server의 정확한 CORS allowlist/credentials/Vary와 page CSP destination을 최소 권한으로 수정하고 client가 response header를 위조하려 하지 않게 합니다.", prevention: "허용/거부 origin·credential·preflight·CSP 조합을 배포 환경 browser E2E로 검증합니다." },
      { symptom: "새 배포 뒤 일부 사용자만 오래된 JSON schema를 받아 parser가 실패한다.", likelyCause: "Cache-Control/validator/Vary/version contract가 불완전하거나 service worker/cache layer가 오래된 representation을 재사용합니다.", checks: ["Age·Cache-Control·ETag·Vary·ServiceWorker source를 Network에서 봅니다.", "URL/version과 response schema version을 비교합니다.", "memory/disk/CDN/service-worker cache를 각각 우회해 재현합니다."], fix: "versioned representation과 올바른 freshness/validator/Vary, safe migration adapter를 적용하고 private data cacheability를 재검토합니다.", prevention: "old/new schema와 cache revalidation을 포함한 rolling-deploy contract test를 둡니다." },
    ],
    expertNotes: ["CORS error 세부 정보는 보안상 JavaScript에 노출되지 않을 수 있으므로 production UI가 Console 문구에 의존하지 않게 하고 server observability와 correlation을 준비합니다.", "cache mode와 HTTP Cache-Control은 같은 층이 아닙니다. request option 하나로 CDN·shared cache·service worker의 모든 behavior를 통제한다고 가정하지 않습니다."],
  },
);

expertSession.reviewQuestions.push(
  { question: "Response.ok가 true이면 JSON body와 schema도 유효한가요?", answer: "아닙니다. ok는 200~299 status 범위만 나타내며 Content-Type, byte decoding, JSON syntax와 application schema는 별도 검증해야 합니다." },
  { question: "CORS를 허용하면 server authorization도 충족되나요?", answer: "아닙니다. CORS는 browser의 cross-origin response 노출 정책이며 server는 인증·인가·CSRF·object-level 권한을 별도로 검증해야 합니다." },
  { question: "ReadableStream chunk마다 새 TextDecoder를 써도 되는 이유가 있나요?", answer: "문자 경계가 chunk와 정확히 일치한다고 보장된 특수 contract가 아니라면 안 됩니다. 하나의 decoder와 stream:true로 불완전한 multi-byte sequence를 이어야 합니다." },
);
expertSession.completionChecklist.push(
  "status·Content-Type·byte decoding·JSON syntax·schema를 독립된 gate와 오류 code로 분리했다.",
  "ReadableStream의 lock·bodyUsed·cancel·backpressure와 UTF-8 streaming decoder lifecycle을 검증했다.",
  "CORS preflight/credentials/Vary와 CSP connect-src, server authorization의 책임을 구분했다.",
  "Cache-Control·validators·Vary·service worker를 DevTools Network evidence와 rolling-deploy test로 확인했다.",
);
