import type { DetailedSession } from "../../types";

const session = {
  schemaVersion: 2,
  inventoryIds: ["js-11-fetch-xml-domparser-capstone"],
  slug: "js-11-fetch-xml-domparser-capstone",
  courseId: "javascript",
  moduleId: "01-javascript-dom-async",
  order: 11,
  title: "XML fetch, DOMParser와 날씨 UI 종합",
  subtitle: "Response text를 strict XML Document로 파싱하고 namespace·nullable schema·safe table·JSON adapter까지 하나의 pipeline으로 완성합니다.",
  level: "고급",
  estimatedMinutes: 385,
  coreQuestion: "기본 namespace와 누락 attributes가 있는 외부 XML을 fetch·parse·validate·normalize해, JSON과 같은 view model로 안전하고 접근 가능하게 렌더링하려면 어떤 경계가 필요할까요?",
  summary: "JavaScript 과정의 capstone으로 원본 weather XML 두 벌과 XML/JSON fetch pages를 전부 감사합니다. 두 weather.xml은 byte-identical하고 `xmlns='current'` 아래 local 97개를 가지며 서울은 station 108·5.7°C·흐림, `ta`가 없는 행은 고창 한 건입니다. fetch Response는 XML object를 자동 생성하지 않으므로 status/media/body를 확인하고 text를 한 번 읽은 뒤 DOMParser.parseFromString(text,'application/xml')로 별도 XML Document를 만듭니다. HTML parser의 error recovery와 XML parser의 well-formedness failure를 비교하고 parsererror Document를 Error로 승격합니다. XML declaration encoding은 JavaScript string을 파싱하는 DOMParser에서 byte decoder를 다시 제어하지 않는다는 경계를 설명합니다. 기본 namespace가 element 이름에 적용되고 unprefixed attributes에는 적용되지 않는 규칙, namespaceURI/localName/getElementsByTagNameNS와 XPath resolver를 사용해 prefix spelling에 의존하지 않습니다. local text/stn_id/ta/desc를 unknown DOM에서 추출해 station ID string·temperature number|null·description string view model로 검증하고, missing과 0.0/negative를 truthiness로 섞지 않습니다. 원본의 innerHTML 문자열 표는 XML/JSON 외부 값으로 XSS와 CSS injection을 열고, 함께 있는 JSON 예제는 response.json을 두 번 호출해 body-consumed 오류가 납니다. 이를 semantic table·createElement·textContent와 validated style/property로 교정합니다. XML/JSON adapters가 같은 WeatherRow[]를 반환하게 만들어 filter/sort/render/error UI를 재사용하고, malformed XML·wrong namespace·missing/invalid attributes·duplicate stations·large payload·abort/stale response를 browser fixtures로 검증합니다. browser DOMParser를 server-side XXE 안전 설정으로 일반화하지 않고 DTD/external entity·size limits는 parser/runtime별로 검증하며, 큰 XML에는 server transform·Worker·streaming parser 대안을 비교합니다.",
  objectives: [
    "fetch Response text와 XML Document를 구분하고 HTTP/media/body/parser/schema 경계를 순서대로 구현할 수 있다.",
    "DOMParser의 HTML/XML MIME modes와 well-formedness parsererror 결과를 정확히 진단할 수 있다.",
    "namespaceURI·localName·getElementsByTagNameNS/XPath resolver로 prefix-independent XML query를 작성할 수 있다.",
    "XML element text와 attributes를 string·number|null domain model로 검증하고 missing·0·negative를 구분할 수 있다.",
    "외부 XML/JSON values를 semantic table의 textContent/property로 안전하게 렌더링할 수 있다.",
    "XML과 JSON adapters를 공통 WeatherRow view model로 통합해 filter·empty·error UI를 재사용할 수 있다.",
    "CORS·AbortSignal·latest request·schema/version과 parser/server security를 전체 pipeline에서 관리할 수 있다.",
    "malformed/namespace/missing/duplicate/large/malicious fixtures와 원본 97-row evidence로 회귀 테스트를 만들 수 있다.",
  ],
  prerequisites: [
    { title: "fetch·HTTP·JSON", reason: "status/ok, body single consumption, CORS, AbortSignal과 remote-data UI를 XML response에도 그대로 적용합니다.", sessionSlug: "js-10-fetch-json-http" },
    { title: "XML element·attribute·namespace", reason: "default namespace와 unprefixed attributes, expanded name을 DOM API query에 연결합니다.", sessionSlug: "xml-02-elements-attributes-namespace" },
    { title: "DOM 생성·안전한 렌더링", reason: "원본 innerHTML string table을 semantic nodes/textContent로 교체해 외부 data를 markup으로 parse하지 않습니다.", sessionSlug: "js-06-dom-create-update-remove" },
  ],
  keywords: ["XML fetch", "DOMParser", "XMLDocument", "application/xml", "parsererror", "well-formed", "namespaceURI", "localName", "getElementsByTagNameNS", "XPath", "namespace resolver", "attribute", "nullable schema", "weather", "view model", "XMLSerializer", "XSD", "XXE", "DTD", "safe table", "JSON adapter", "capstone"],
  chapters: [
    {
      id: "source-audit-fetch-text-parse-pipeline",
      title: "XML fetch는 Response text→XML Document→domain model→HTML DOM의 네 representation을 통과합니다",
      lead: "각 단계의 type과 owner를 적어 XML 문자열, XML DOM, 화면 DOM을 섞지 않습니다.",
      explanations: [
        "원본 ex14/test는 weather.xml을 fetch하고 response.ok를 검사한 뒤 response.text로 JavaScript string을 얻습니다. Fetch API는 Content-Type이 XML이어도 application-specific XML object로 자동 변환하지 않습니다.",
        "DOMParser.parseFromString(text,'application/xml')는 current page document와 별도인 XML Document를 새로 만듭니다. 그 XML nodes를 query해 plain WeatherRow records로 normalize한 뒤 current HTML Document에서 table nodes를 생성합니다.",
        "이 네 representation을 분리하면 XML element를 current page에 무심코 import해 script/style/custom namespace behavior를 섞는 일을 피하고 JSON adapter와 동일한 domain validation/render를 재사용할 수 있습니다.",
        "HTTP status와 Content-Type은 parser 전에 확인합니다. server/proxy가 500 HTML을 보내면 DOMParser XML error가 나더라도 root cause는 HTTP failure이므로 HttpError와 XmlParseError context를 보존합니다.",
        "Response body는 한 번만 소비합니다. 원본 ex15 JSON page는 console.log(response.json())로 첫 reader를 시작한 뒤 다시 await response.json()을 호출해 body-consumed TypeError가 날 수 있습니다. XML도 text를 log/parse한다고 두 번 읽지 않습니다.",
        "CORS 때문에 외부 날씨 URL을 local file로 저장한 원본 판단은 당시 실행 evidence입니다. 해결책이 반드시 Spring인 것은 아니며 upstream CORS 설정, same-origin controlled backend proxy 또는 data ingestion job을 auth/allowlist/cache와 함께 설계합니다.",
      ],
      concepts: [
        { term: "representation pipeline", definition: "HTTP body bytes/string, parsed XML DOM, validated domain model, rendered HTML DOM으로 data representation을 단계별 변환하는 구조입니다.", detail: ["각 단계 오류를 분리합니다.", "JSON과 view model을 공유합니다."] },
        { term: "XMLDocument", definition: "XML parser가 만든 별도 Document node tree로 current page HTML Document와 content type·namespace/parser behavior가 다릅니다.", detail: ["query는 XML tree에서 합니다.", "화면에는 safe projection을 만듭니다."] },
        { term: "adapter boundary", definition: "XML/JSON 같은 wire format을 common domain/view model로 변환해 downstream UI를 format-independent하게 만드는 경계입니다.", detail: ["schema validation을 소유합니다.", "format-specific DOM을 leak하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "XML endpoint 대신 proxy HTML error page를 받아 parsererror만 표시된다.", likelyCause: "HTTP status/media type을 보존하지 않고 모든 body를 XML parse해 protocol failure를 format error로 바꿨습니다.", checks: ["response.status/ok/url/Content-Type을 먼저 확인합니다.", "body의 제한된 safe prefix와 server correlation을 봅니다.", "redirect/login/proxy response 여부를 확인합니다."], fix: "HTTP/media contract를 통과한 body만 XML parser로 보내고 HttpError와 XmlParseError에 stage/context를 분리합니다.", prevention: "200 XML, 404 JSON, 500 HTML, login redirect와 wrong media fixtures를 둡니다." },
      ],
    },
    {
      id: "domparser-modes-errors-encoding",
      title: "DOMParser는 MIME mode에 따라 HTML error recovery 또는 strict XML parser를 선택합니다",
      lead: "parseFromString이 throw하지 않았다는 사실만으로 XML 성공을 선언하지 않고 returned Document를 검사합니다.",
      explanations: [
        "parseFromString의 text/html mode는 HTML parser를 사용해 omitted/invalid markup을 error recovery하며 HTML Document를 만듭니다. application/xml, text/xml, application/xhtml+xml, image/svg+xml은 XML parser를 사용합니다.",
        "malformed XML은 일반적으로 parseFromString 호출 자체가 exception을 throw하는 대신 returned Document에 error를 설명하는 parsererror element를 포함합니다. documentElement.localName 또는 getElementsByTagNameNS('*','parsererror')로 검사하고 application error로 승격합니다.",
        "parsererror node의 namespace/text/markup은 browser 구현 detail이 섞일 수 있어 전체 message를 사용자에게 노출하거나 exact text snapshot으로 test하지 않습니다. error 존재 boolean과 sanitized category만 안정적으로 사용합니다.",
        "application/xml mode는 case-sensitive tag names, single root, quoted attributes, proper close/nesting과 namespace well-formedness를 요구합니다. HTML처럼 tag를 자동 닫아 주거나 대소문자를 normalize한다고 기대하지 않습니다.",
        "DOMParser는 이미 JavaScript DOMString인 input을 parse하고 resulting document encoding은 UTF-8입니다. string 안 XML declaration/meta가 byte decoding을 다시 바꾸지 않습니다. encoding 문제는 Response bytes→string 단계에서 해결합니다.",
        "DOMParser parsing 자체에서 scripts가 실행되지 않더라도 no-sanitization parser이며 parsed nodes/strings를 active HTML에 unsafe insert하면 위험해집니다. XML을 security sanitizer로 사용하지 않습니다.",
      ],
      concepts: [
        { term: "well-formedness", definition: "XML 문서가 single root, balanced/case-sensitive names, quoted attributes, legal characters와 namespace rules를 만족하는 문법 조건입니다.", detail: ["schema validity와 다릅니다.", "malformed input은 parsererror입니다."] },
        { term: "parsererror Document", definition: "XML parse failure를 설명하는 error element가 포함된 returned Document로 browser code가 명시 검사해야 합니다.", detail: ["throw만 기다리지 않습니다.", "message는 구현 detail입니다."] },
        { term: "parser mode", definition: "DOMParser MIME type이 HTML error-recovery parser 또는 XML strict parser를 선택하는 계약입니다.", detail: ["text/html과 application/xml이 다릅니다.", "unsupported type은 TypeError입니다."] },
      ],
      codeExamples: [
        {
          id: "xml-versus-html-parser-errors",
          title: "valid/malformed XML과 HTML error recovery 비교",
          language: "html",
          filename: "parser-modes.html",
          purpose: "parseFromString return만 보지 않고 XML parsererror와 HTML root 결과를 exact boolean/name으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>parser modes</title></head>\n<body><pre id=\"out\"></pre><script>\n  const parser = new DOMParser();\n  const valid = parser.parseFromString('<root><item/></root>', 'application/xml');\n  const invalid = parser.parseFromString('<root><item></root>', 'application/xml');\n  const html = parser.parseFromString('<p>A<p>B', 'text/html');\n  const hasError = doc => doc.documentElement.localName === 'parsererror' || doc.getElementsByTagNameNS('*', 'parsererror').length > 0;\n  document.querySelector('#out').textContent = [\n    `valid-error=${hasError(valid)}`,\n    `invalid-error=${hasError(invalid)}`,\n    `html-root=${html.documentElement.tagName}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-6", explanation: "같은 DOMParser로 well-formed XML, mismatched XML과 invalid-looking HTML을 MIME mode별로 parse합니다." },
            { lines: "7", explanation: "document root localName과 wildcard namespace parsererror descendants를 portable boolean으로 검사합니다." },
            { lines: "8-12", explanation: "error message text 대신 stable success/error booleans와 HTML root를 출력합니다." },
          ],
          run: { environment: ["DOMParser를 지원하는 modern browser"], command: "browser에서 parser-modes.html을 열고 결과 확인" },
          output: { value: "valid-error=false\ninvalid-error=true\nhtml-root=HTML", explanation: ["well-formed XML에는 parsererror가 없습니다.", "mismatched XML은 error Document를 만듭니다.", "HTML parser는 markup을 복구해 HTML root를 만듭니다."] },
          experiments: [
            { change: "MIME type을 application/json으로 바꿉니다.", prediction: "지원 DOMParser type이 아니라 TypeError를 throw합니다.", result: "JSON은 JSON.parse/Response.json을 사용합니다." },
            { change: "Root와 root의 대소문자를 다르게 닫습니다.", prediction: "XML은 case-sensitive라 parsererror입니다.", result: "HTML tag normalization을 XML에 적용하지 않습니다." },
            { change: "invalid를 text/html로 parse합니다.", prediction: "HTML parser가 tree를 복구해 parsererror 대신 HTML Document를 만듭니다.", result: "MIME mode가 correctness contract입니다." },
          ],
          sourceRefs: ["web-weather-fetch-source", "html-domparser", "xml-standard"],
        },
      ],
      diagnostics: [
        { symptom: "malformed XML인데 try/catch가 실행되지 않아 빈 목록이 성공으로 표시된다.", likelyCause: "parseFromString이 returned parsererror Document를 검사해야 하는 behavior를 몰랐습니다.", checks: ["documentElement.localName/namespaceURI를 출력합니다.", "getElementsByTagNameNS('*','parsererror')를 확인합니다.", "query 전에 parse assertion이 있는지 봅니다."], fix: "parseXml helper가 parsererror를 즉시 XmlParseError로 변환하고 downstream adapter는 성공 Document만 받게 합니다.", prevention: "mismatched tag, illegal char, duplicate root, bad namespace fixtures를 둡니다." },
      ],
    },
    {
      id: "namespace-aware-query",
      title: "기본 namespace는 element expanded names를 바꾸므로 prefix spelling이 아니라 namespaceURI+localName으로 조회합니다",
      lead: "원본 current namespace를 문자열 장식으로 보지 않고 data contract 일부로 검증합니다.",
      explanations: [
        "weather root의 `xmlns='current'`는 prefix 없는 current/weather/local elements를 namespace URI current에 둡니다. element.localName은 local, namespaceURI는 current입니다.",
        "default namespace는 prefix 없는 attributes에 자동 적용되지 않습니다. local의 stn_id, icon, desc, ta는 namespace가 없는 attributes이므로 getAttribute('ta')로 읽습니다. namespaced attribute는 getAttributeNS를 사용합니다.",
        "querySelectorAll('local')이 현재 browser fixture에서 match할 수 있어도 CSS selector namespace support와 format evolution에 의존한 contract를 만들지 않습니다. `getElementsByTagNameNS('current','local')` 또는 TreeWalker/localName+namespaceURI filter를 사용합니다.",
        "producer가 prefix w:를 도입해 `<w:local>`로 바꿔도 namespace URI/local name이 같으면 namespace-aware adapter는 계속 동작합니다. raw tagName 또는 prefix text 비교는 불필요하게 깨집니다.",
        "XPath를 사용할 때 expression의 prefix는 source prefix와 같을 필요가 없고 namespace resolver가 prefix→URI를 매핑합니다. `//w:local[@stn_id='108']`와 resolver w→current처럼 명시합니다.",
        "namespace URI가 unexpected/null이면 zero rows로 조용히 성공하지 않고 schema/version error를 냅니다. wildcard `*` query는 migration/debug에는 유용하지만 production contract를 느슨하게 만들 수 있습니다.",
      ],
      concepts: [
        { term: "expanded name", definition: "XML name을 namespace URI와 local name pair로 식별하는 모델입니다.", detail: ["prefix spelling과 독립적입니다.", "element identity의 일부입니다."] },
        { term: "default namespace", definition: "xmlns='URI'가 prefix 없는 element names에 적용하는 namespace binding입니다.", detail: ["unprefixed attributes에는 적용되지 않습니다.", "descendants에 상속될 수 있습니다."] },
        { term: "namespace resolver", definition: "XPath expression prefix를 실제 namespace URI에 연결하는 callback/map입니다.", detail: ["source prefix와 달라도 됩니다.", "unknown prefix는 query failure가 됩니다."] },
      ],
      codeExamples: [
        {
          id: "namespace-weather-extraction",
          title: "current namespace의 서울과 누락 온도 추출",
          language: "html",
          filename: "weather-namespace.html",
          purpose: "원본 weather 구조를 줄인 fixture에서 namespace-aware element query와 no-namespace attributes/null을 exact output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>weather namespace</title></head>\n<body><pre id=\"out\"></pre><script>\n  const source = `<current xmlns=\"current\"><weather><local stn_id=\"108\" desc=\"흐림\" ta=\"5.7\">서울</local><local stn_id=\"172\" desc=\"흐림\">고창</local></weather></current>`;\n  const doc = new DOMParser().parseFromString(source, 'application/xml');\n  const locals = [...doc.getElementsByTagNameNS('current', 'local')];\n  const seoul = locals.find(node => node.getAttribute('stn_id') === '108');\n  const gochang = locals.find(node => node.textContent.trim() === '고창');\n  document.querySelector('#out').textContent = [\n    `root=${doc.documentElement.localName}`,\n    `namespace=${doc.documentElement.namespaceURI}`,\n    `locals=${locals.length}`,\n    `seoul=${seoul.getAttribute('stn_id')}|${seoul.textContent.trim()}|${seoul.getAttribute('ta')}|${seoul.getAttribute('desc')}`,\n    `gochang-temp=${gochang.getAttribute('ta') ?? 'missing'}`\n  ].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-4", explanation: "default current namespace와 서울/고창 두 local elements를 XML string으로 parse합니다." },
            { lines: "5-7", explanation: "expanded name으로 local elements를 snapshot하고 station/text로 records를 찾습니다." },
            { lines: "8-14", explanation: "root local/namespace, row count, 서울 attributes와 missing ta null을 출력합니다." },
          ],
          run: { environment: ["DOMParser/getElementsByTagNameNS를 지원하는 modern browser"], command: "browser에서 weather-namespace.html을 열고 결과 확인" },
          output: { value: "root=current\nnamespace=current\nlocals=2\nseoul=108|서울|5.7|흐림\ngochang-temp=missing", explanation: ["root expanded name은 current namespace의 current입니다.", "namespace-aware query가 두 local을 찾습니다.", "고창에는 ta attribute가 없어 getAttribute가 null이고 missing으로 표시됩니다."] },
          experiments: [
            { change: "source elements에 w prefix를 붙이고 xmlns:w=current를 선언합니다.", prediction: "namespace-aware query 결과는 그대로 두 개입니다.", result: "prefix spelling과 adapter를 분리합니다." },
            { change: "namespace URI를 current-v2로 바꿉니다.", prediction: "current query는 0개이며 schema/version error로 처리해야 합니다.", result: "silent empty와 wrong namespace를 구분합니다." },
            { change: "ta='0.0'을 추가합니다.", prediction: "getAttribute는 '0.0'이고 missing이 아닙니다.", result: "truthiness가 아니라 null을 검사합니다." },
          ],
          sourceRefs: ["web-weather-xml-day09", "web-weather-xml-data", "xml-namespaces", "dom-namespace-query"],
        },
      ],
      diagnostics: [
        { symptom: "XML은 정상인데 local rows가 0개다.", likelyCause: "expected namespace URI가 다르거나 prefix/tagName/raw selector에 의존했습니다.", checks: ["documentElement/local sample의 namespaceURI/localName/prefix를 출력합니다.", "expected URI와 producer version을 비교합니다.", "getElementsByTagNameNS 결과와 parsererror를 분리합니다."], fix: "namespace URI+localName adapter를 사용하고 unexpected namespace는 SchemaError로 표시합니다.", prevention: "default/prefixed/wrong/missing namespace fixtures와 producer contract test를 둡니다." },
      ],
    },
    {
      id: "xml-record-schema-normalization",
      title: "Element text와 attributes는 모두 raw strings/null이므로 domain type·range·uniqueness를 검증합니다",
      lead: "ta가 없음을 0°C로 만들거나 stn_id를 숫자로 바꿔 leading zero를 잃지 않습니다.",
      explanations: [
        "textContent는 descendant text 전체를 string으로 반환하므로 station name은 trim하고 empty/length를 검증합니다. mixed content가 허용되는 schema라면 단순 textContent가 원하는 의미인지 별도 parser가 필요합니다.",
        "getAttribute는 attribute가 있으면 string, 없으면 null입니다. `?? ''`로 즉시 뭉개면 missing과 actual empty를 구분하지 못해 원본처럼 table은 보이지만 data quality가 숨겨집니다.",
        "temperature는 attr===null이면 null, 있으면 Number(raw) 후 Number.isFinite와 domain range를 검사합니다. raw '0.0'과 '-0.9'는 valid이고 `if(!raw)`/`if(!temperature)`로 missing 처리하면 0을 잃습니다.",
        "stn_id는 identifier이므로 digit처럼 보여도 string으로 유지하고 non-empty/unique를 검사합니다. icon도 code string이며 desc는 allowed length/string이고 HTML/CSS로 직접 해석하지 않습니다.",
        "weather year/month/day/hour attributes는 local observation metadata지만 timezone/offset이 없습니다. 임의로 Date UTC/local instant를 만들지 않고 schema context나 server metadata로 zone을 명시합니다.",
        "실제 원본은 97 locals, ta missing 1(고창 stn_id 172), 서울 stn_id 108/ta 5.7/desc 흐림입니다. 두 weather files의 동일 hash와 이 counts를 golden evidence로 두되 upstream refresh가 의도된 경우 versioned fixture를 갱신합니다.",
        "XSD는 document structure/type constraints를 formalize할 수 있지만 browser DOMParser가 자동 XSD validation을 수행하지 않습니다. server/tooling validation 또는 application adapter checks를 별도로 실행합니다.",
      ],
      concepts: [
        { term: "wire value", definition: "XML text/attribute에서 얻은 raw string 또는 null로 domain value가 되기 전 representation입니다.", detail: ["parse/validate합니다.", "missing/empty/zero를 구분합니다."] },
        { term: "nullable domain field", definition: "실제 data absence를 null로 명시하고 valid number/string과 구분하는 model field입니다.", detail: ["UI fallback이 명확합니다.", "0과 missing이 다릅니다."] },
        { term: "golden fixture", definition: "원본 count/key values/hash처럼 parser/adapter 회귀를 잡는 versioned expected evidence입니다.", detail: ["의도된 source update 절차가 필요합니다.", "전체 snapshot만 의존하지 않습니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "고창 온도가 0°C로 표시되거나 0.0°C 관측이 '자료 없음'으로 보인다.", likelyCause: "missing attribute null, empty string, parsed zero를 truthiness/default Number로 섞었습니다.", checks: ["raw getAttribute result와 parsed number를 나란히 기록합니다.", "attr===null branch를 확인합니다.", "0.0/negative/missing/invalid fixtures를 test합니다."], fix: "missing은 null, present raw는 strict numeric parser로 처리하고 renderer는 value===null만 자료 없음으로 표시합니다.", prevention: "missing/empty/0.0/-0.9/NaN/Infinity/out-of-range table tests를 둡니다." },
      ],
    },
    {
      id: "safe-semantic-table-render",
      title: "XML/JSON 외부 값은 HTML 문자열이 아니라 semantic table nodes와 textContent로 렌더링합니다",
      lead: "원본 output concatenation을 제거해 name·desc·color가 markup/CSS code가 되는 경계를 닫습니다.",
      explanations: [
        "원본 ex14/test는 local text/ta/desc를 `<td>` 문자열 사이에 이어 붙이고 log.innerHTML에 넣습니다. upstream XML text/attribute에 markup이 들어오면 current HTML parser가 element/event attribute로 해석할 수 있습니다.",
        "table, caption, thead/tbody/tr/th/td를 createElement로 만들고 th.scope='col', cell.textContent를 설정합니다. temperature는 validated number를 Intl.NumberFormat과 °C unit으로 표현하고 null은 '자료 없음'으로 표시합니다.",
        "원본 ex15도 product name/price/brand/colors를 innerHTML로 합칩니다. response.json을 두 번 읽는 body bug 외에 remote color를 inline style string에 넣습니다. `#RRGGBB` allowlist 후 style.backgroundColor property에만 넣고 accessible color name/text를 제공합니다.",
        "caption과 heading은 표의 purpose/source/time을 설명하고 small-screen에서는 horizontal scroll 또는 cards 전환을 semantic table access와 함께 test합니다. color만으로 날씨 상태를 전달하지 않습니다.",
        "DocumentFragment로 rows를 조립하고 replaceChildren하되 focus와 current filter를 보존합니다. 97 rows는 manageable하지만 search마다 전체 re-render할지 partial hide/filter할지는 profile합니다.",
        "empty success, loading, malformed/schema error와 no-match search는 서로 다른 status message입니다. table을 empty로 둔 채 모든 상태를 '데이터 없음'이라고 하지 않습니다.",
      ],
      concepts: [
        { term: "semantic data table", definition: "caption·header cells/scope·rows/cells 관계로 tabular data를 구조화해 visual과 accessibility meaning을 함께 제공하는 table입니다.", detail: ["caption/source를 제공합니다.", "missing value를 text로 명시합니다."] },
        { term: "context-safe sink", definition: "외부 value를 code/markup으로 parse하지 않고 해당 UI context의 text/property로 제한해 넣는 지점입니다.", detail: ["textContent가 기본입니다.", "style/URL은 allowlist합니다."] },
        { term: "formatting boundary", definition: "validated domain value를 locale·unit·missing label로 display string에 변환하는 renderer layer입니다.", detail: ["parse와 분리합니다.", "raw precision/policy를 보존합니다."] },
      ],
      codeExamples: [
        {
          id: "xml-safe-weather-table",
          title: "nullable 온도와 tag 모양 지역명을 safe table로 렌더링",
          language: "html",
          filename: "weather-safe-table.html",
          purpose: "XML entity-decoded text가 HTML markup으로 재해석되지 않고 missing temperature가 명시 label로 보이는지 exact DOM output으로 확인합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>safe weather table</title></head>\n<body><table><caption>현재 날씨</caption><thead><tr><th scope=\"col\">지역</th><th scope=\"col\">온도</th></tr></thead><tbody id=\"body\"></tbody></table><pre id=\"out\"></pre><script>\n  const source = `<current xmlns=\"current\"><weather><local stn_id=\"108\" ta=\"5.7\">서울</local><local stn_id=\"999\">&lt;img src=x onerror=alert(1)&gt;</local></weather></current>`;\n  const doc = new DOMParser().parseFromString(source, 'application/xml');\n  const rows = [...doc.getElementsByTagNameNS('current','local')].map(node => {\n    const raw = node.getAttribute('ta');\n    const temperature = raw === null ? null : Number(raw);\n    if (temperature !== null && !Number.isFinite(temperature)) throw new TypeError('invalid temperature');\n    return { id:node.getAttribute('stn_id'), name:node.textContent.trim(), temperature };\n  });\n  const body = document.querySelector('#body');\n  for (const row of rows) {\n    const tr = document.createElement('tr');\n    for (const value of [row.name, row.temperature === null ? '자료 없음' : `${row.temperature} °C`]) {\n      const td = document.createElement('td'); td.textContent = value; tr.append(td);\n    }\n    body.append(tr);\n  }\n  document.querySelector('#out').textContent = [`rows=${body.rows.length}`, `images=${body.querySelectorAll('img').length}`, `missing=${body.rows[1].cells[1].textContent}`, `second=${body.rows[1].cells[0].textContent}`].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3-4", explanation: "default namespace와 normal/malicious-looking entity text, missing ta fixture를 parse합니다." },
            { lines: "5-11", explanation: "namespace rows를 string ID/name과 number|null로 validate/normalize합니다." },
            { lines: "12-19", explanation: "semantic tbody rows/cells를 createElement/textContent로 만들고 missing label/unit을 format합니다." },
            { lines: "20", explanation: "row/image count와 missing/decoded text를 DOM에서 확인합니다." },
          ],
          run: { environment: ["DOMParser와 table DOM API를 지원하는 modern browser"], command: "browser에서 weather-safe-table.html을 열고 결과 확인" },
          output: { value: "rows=2\nimages=0\nmissing=자료 없음\nsecond=<img src=x onerror=alert(1)>", explanation: ["두 domain records가 두 table rows가 됩니다.", "entity-decoded tag 모양 text는 textContent라 img가 0개입니다.", "누락 ta는 0이 아니라 자료 없음입니다."] },
          experiments: [
            { change: "td.textContent 대신 row HTML을 innerHTML로 넣습니다.", prediction: "두 번째 name이 img element로 parse될 위험이 생깁니다.", result: "wire/schema validation과 HTML sink safety를 별도 보장합니다." },
            { change: "ta='0.0'을 둘째 row에 추가합니다.", prediction: "자료 없음이 아니라 0 °C로 표시됩니다.", result: "null과 zero를 구분합니다." },
            { change: "temperature Number validation을 제거하고 ta='x'를 넣습니다.", prediction: "NaN °C 같은 잘못된 UI가 생깁니다.", result: "domain boundary에서 finite/range를 검사합니다." },
          ],
          sourceRefs: ["web-weather-fetch-source", "web-weather-test-source", "web-weather-xml-day09", "dom-standard", "trusted-types"],
        },
      ],
      diagnostics: [
        { symptom: "지역명 XML에 `<img>` 모양 text가 들어오자 실제 image/request가 생긴다.", likelyCause: "XML text를 HTML string에 concatenate해 innerHTML로 다시 parse했습니다.", checks: ["innerHTML/insertAdjacentHTML/string template sinks를 찾습니다.", "XML entity-decoding 뒤 final string을 inspect합니다.", "safe node creation path를 확인합니다."], fix: "semantic nodes를 code로 만들고 external values는 textContent, validated style/URL properties에만 넣습니다.", prevention: "tag/event/SVG/entity-like payload corpus와 DOM element count/CSP tests를 둡니다." },
      ],
    },
    {
      id: "xml-json-common-view-model",
      title: "XML과 JSON adapters는 같은 WeatherRow view model을 반환해 UI와 업무 규칙을 공유합니다",
      lead: "wire format 분기를 component 전체에 퍼뜨리지 않고 parser/adapter에서 끝냅니다.",
      explanations: [
        "XML adapter는 namespace-aware DOM query와 attributes/text를 읽고 JSON adapter는 runtime object schema를 읽지만 둘 다 `{id,name,temperature,description}` records를 반환합니다.",
        "공통 normalize 단계는 trim, identifier uniqueness, temperature number|null/range, description length/enum과 source timestamp/version을 검사합니다. adapter 결과에 XML Element나 raw JSON object를 남기지 않습니다.",
        "renderer/filter/sort/export는 WeatherRow만 의존해 format별 innerHTML/UI duplicate를 제거합니다. XML/JSON output parity test는 같은 fixture semantics가 같은 records를 만드는지 확인합니다.",
        "원본 ex15 `new Error('Http 오류 : ', response.status)`는 Error constructor의 numeric 둘째 argument가 message에 붙지 않습니다. `new HttpError(response.status)`처럼 property를 명시하고 Error options는 supported cause object로 사용합니다.",
        "ex15 external makeup API는 availability/CORS/schema가 변할 수 있어 교육 exact output source로 의존하지 않습니다. saved versioned fixture 또는 local mock으로 product_colors/name/price/brand schema를 검증합니다.",
        "format negotiation을 server가 지원하면 Accept application/json/application/xml을 명시하고 Content-Type에 따라 adapter를 선택합니다. suffix나 body 첫 글자 추측으로 parser를 고르지 않습니다.",
      ],
      concepts: [
        { term: "view model", definition: "wire format과 분리되어 renderer가 필요한 validated fields와 null/format policy만 갖는 application record입니다.", detail: ["XML/JSON이 공유합니다.", "DOM nodes를 포함하지 않습니다."] },
        { term: "adapter parity", definition: "서로 다른 wire representations가 같은 semantic input일 때 동일한 normalized domain records를 만드는 성질입니다.", detail: ["cross-format tests로 확인합니다.", "schema versions를 명시합니다."] },
        { term: "content negotiation", definition: "Accept/Content-Type을 통해 client/server가 response representation format을 합의하는 HTTP mechanism입니다.", detail: ["media type으로 adapter를 선택합니다.", "CORS/cache Vary를 고려합니다."] },
      ],
      codeExamples: [
        {
          id: "xml-json-adapter-parity",
          title: "동일 서울 관측의 XML/JSON view model parity",
          language: "html",
          filename: "weather-adapters.html",
          purpose: "wire query 방법은 달라도 normalized records와 검색 결과가 같아야 함을 exact output으로 검증합니다.",
          code: "<!doctype html>\n<html lang=\"ko\"><head><meta charset=\"utf-8\"><title>adapter parity</title></head>\n<body><pre id=\"out\"></pre><script>\n  const normalize = value => ({ id:String(value.id), name:String(value.name).trim(), temperature:value.temperature === null ? null : Number(value.temperature), description:String(value.description) });\n  function fromXml(text) {\n    const doc = new DOMParser().parseFromString(text, 'application/xml');\n    return [...doc.getElementsByTagNameNS('current','local')].map(node => normalize({ id:node.getAttribute('stn_id'), name:node.textContent, temperature:node.getAttribute('ta'), description:node.getAttribute('desc') }));\n  }\n  function fromJson(value) {\n    if (!Array.isArray(value)) throw new TypeError('array required');\n    return value.map(item => normalize(item));\n  }\n  const xmlRows = fromXml(`<current xmlns=\"current\"><local stn_id=\"108\" ta=\"5.7\" desc=\"흐림\">서울</local></current>`);\n  const jsonRows = fromJson([{id:'108',name:'서울',temperature:5.7,description:'흐림'}]);\n  const format = row => `${row.id}:${row.name}:${row.temperature}:${row.description}`;\n  document.querySelector('#out').textContent = [`same=${JSON.stringify(xmlRows) === JSON.stringify(jsonRows)}`, `xml=${format(xmlRows[0])}`, `json=${format(jsonRows[0])}`, `filter=${xmlRows.filter(row => row.name.includes('서')).map(row => row.name).join('|')}`].join('\\n');\n</script></body></html>",
          walkthrough: [
            { lines: "3", explanation: "두 adapters가 공유하는 primitive/null normalization shape를 정의합니다." },
            { lines: "4-10", explanation: "XML은 namespace DOM, JSON은 array schema를 통해 같은 normalize function으로 들어갑니다." },
            { lines: "11-14", explanation: "동일 서울 fixture를 각 format으로 만들고 structural equality, formatted row와 common filter를 출력합니다." },
          ],
          run: { environment: ["DOMParser를 지원하는 modern browser"], command: "browser에서 weather-adapters.html을 열고 결과 확인" },
          output: { value: "same=true\nxml=108:서울:5.7:흐림\njson=108:서울:5.7:흐림\nfilter=서울", explanation: ["두 adapters가 property order/type까지 같은 record를 만듭니다.", "format/render input이 wire format과 무관합니다.", "검색 filter를 공통 rows에 한 번 적용합니다."] },
          experiments: [
            { change: "JSON temperature를 string '5.7'로 바꿉니다.", prediction: "현재 normalize는 같은 number로 만들지만 strict schema라면 format mismatch를 reject할 수도 있습니다.", result: "coercion 허용 policy를 문서화합니다." },
            { change: "XML namespace를 current-v2로 바꿉니다.", prediction: "current adapter가 0 rows가 되므로 silent parity가 아니라 version error를 내야 합니다.", result: "namespace/schema version을 assert합니다." },
            { change: "JSON name에 surrounding spaces를 추가합니다.", prediction: "shared trim policy로 parity를 유지합니다.", result: "normalization을 adapter 뒤 공통 단계에 둡니다." },
          ],
          sourceRefs: ["web-weather-fetch-source", "web-makeup-json-source", "xml-namespaces", "json-rfc-source"],
        },
      ],
      diagnostics: [
        { symptom: "XML 화면과 JSON 화면의 missing/temperature/search 결과가 다르다.", likelyCause: "format별 components가 parsing·coercion·render rules를 중복 구현했습니다.", checks: ["두 adapter outputs를 common schema로 snapshot합니다.", "null/zero/string-number/trim policy를 비교합니다.", "renderer가 raw Element/JSON을 읽는지 봅니다."], fix: "format adapters를 WeatherRow[] boundary에 모으고 common validator/renderer/filter를 재사용합니다.", prevention: "semantic-equivalent XML/JSON parity corpus와 shared view-model type tests를 둡니다." },
      ],
    },
    {
      id: "search-state-accessibility-lifecycle",
      title: "지역 검색 UI는 remote-data state와 local filter state를 분리하고 stale fetch를 취소합니다",
      lead: "검색어가 바뀔 때 매번 network를 부를지 loaded rows를 filter할지 명확히 하고 no-match와 load failure를 구분합니다.",
      explanations: [
        "static weather snapshot이면 한 번 load/parse한 WeatherRow[]를 application state에 보관하고 query input에서 local filter합니다. live server search라면 debounce, AbortSignal, latest request guard와 query URL encoding을 적용합니다.",
        "empty query는 all rows 또는 validation 안내 중 product rule을 정하고 trim/Unicode normalization/locale case policy를 사용합니다. station ID exact search와 name contains search를 구분합니다.",
        "no-match는 load success이며 status에 '검색 결과 0개'와 clear action을 제공합니다. malformed XML, wrong namespace, missing required fields, HTTP/CORS는 retry 가능한 load errors입니다.",
        "table caption/status에는 observation date/source와 result count를 제공하고 aria-live는 검색 결과 count처럼 간결한 update에 사용합니다. 매 keypress마다 97 rows 전체를 낭독하지 않습니다.",
        "load/search/cancel button과 input label을 native controls로 만들고 loading aria-busy, keyboard focus, error/retry를 유지합니다. re-render 뒤 input focus/cursor를 잃지 않습니다.",
        "route/unmount에서 current fetch를 abort하고 event/timer references를 dispose합니다. old parse/render task가 취소 불가능하면 generation token이 current인지 확인합니다.",
      ],
      concepts: [
        { term: "remote vs derived state", definition: "loaded source rows/error/loading과 query에서 계산한 filtered rows/no-match를 서로 다른 state layers로 관리하는 model입니다.", detail: ["failure와 no-match가 다릅니다.", "재fetch 여부가 명확합니다."] },
        { term: "search normalization", definition: "trim·Unicode/case/locale와 ID/name mode를 정해 user query와 record를 비교하는 policy입니다.", detail: ["원본 data를 바꾸지 않습니다.", "highlight index와 일치해야 합니다."] },
        { term: "result announcement", definition: "검색/로드 상태와 count를 screen reader에 간결하게 알리고 table content 자체의 반복 낭독을 피하는 접근성 pattern입니다.", detail: ["aria-live를 절제합니다.", "focus는 유지합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "지역 검색 결과가 0개일 때 'XML 파싱 실패'로 표시된다.", likelyCause: "valid empty filter result와 load/parser/schema error를 하나의 falsy branch로 처리했습니다.", checks: ["remote load state와 filtered length를 별도 출력합니다.", "namespace mismatch zero rows와 legitimate no-match를 구분합니다.", "query normalization을 확인합니다."], fix: "loaded WeatherRow[] 성공을 먼저 확정하고 filter no-match state를 별도 render하며 wrong namespace/schema는 adapter에서 Error로 냅니다.", prevention: "loaded-empty/no-match/wrong-namespace/parsererror/network matrix를 E2E test합니다." },
      ],
    },
    {
      id: "xml-security-performance-testing",
      title: "XML capstone은 DTD/entity·size·DOM memory·CORS·version과 parser runtime 차이를 threat/test model에 포함합니다",
      lead: "browser DOMParser 한 번의 성공을 server XML parser와 대형 production feed 안전성으로 일반화하지 않습니다.",
      explanations: [
        "XML의 DTD/entity features는 parser/runtime configuration에 따라 external entity access, local file/network disclosure, entity expansion denial 같은 위험을 만들 수 있습니다. server-side parser에서는 DTD/external entity/XInclude 관련 기능을 명시적으로 비활성화하고 allowlist/limits를 검증합니다.",
        "browser DOMParser는 scripting disabled XML Document를 만들지만 sanitizer가 아닙니다. parsed strings/nodes를 active HTML에 unsafe import/innerHTML하면 XSS boundary가 다시 열립니다. safe view-model projection을 유지합니다.",
        "DOM parsing은 전체 tree를 memory에 만들므로 payload bytes보다 큰 memory와 traversal cost가 듭니다. maximum response size/depth/node/text/attribute count와 timeout/abort를 server/client에 둡니다.",
        "Web platform에 보편적인 built-in streaming XML domain parser가 없으므로 매우 큰 feeds는 server-side SAX/StAX transform, Worker parser 또는 audited library를 고려합니다. custom regex/chunk XML parser를 만들지 않습니다.",
        "schema/version은 root namespace/local name, required weather/date attributes와 station uniqueness로 검사하고 XSD validation이 필요하면 supported server/toolchain에서 수행합니다. DOMParser가 XSD를 자동 적용하지 않습니다.",
        "tests는 malformed XML, wrong/default/prefixed namespace, missing ta, 0/negative/invalid number, duplicate stn_id, malicious text, DTD/entity fixture, huge/deep data, HTTP/CORS/abort/stale를 포함합니다.",
        "두 original weather files의 same SHA-256, 97 rows, missing-ta one, Seoul golden record를 provenance report에 기록합니다. 다만 weather snapshot date가 고정된 학습 fixture이며 현재 실시간 날씨라고 표시하지 않습니다.",
      ],
      concepts: [
        { term: "XXE/entity threat", definition: "XML entity/DTD resolution이 external resources 또는 exponential expansion을 통해 disclosure/SSRF/denial을 만들 수 있는 parser threat family입니다.", detail: ["runtime별 secure config가 필요합니다.", "browser success를 server에 일반화하지 않습니다."] },
        { term: "DOM memory amplification", definition: "XML bytes를 node/attribute/text objects와 indexes로 materialize하며 input 크기보다 큰 memory/CPU를 쓰는 현상입니다.", detail: ["size/depth/node limits를 둡니다.", "stream/server transform을 고려합니다."] },
        { term: "schema/version gate", definition: "root expanded name, required structure/attributes/types/uniqueness와 version을 확인해 wrong-but-well-formed XML을 거부하는 boundary입니다.", detail: ["well-formedness만으로 부족합니다.", "XSD/application validation을 선택합니다."] },
      ],
      codeExamples: [],
      diagnostics: [
        { symptom: "작은 XML은 되지만 큰 feed에서 tab memory와 UI가 멈춘다.", likelyCause: "Response text와 full XML DOM, arrays/table nodes를 동시에 보유해 memory amplification과 main-thread parse/render long task가 발생했습니다.", checks: ["payload bytes, node/attribute counts와 heap/Performance trace를 측정합니다.", "Response clone/raw log retained copies를 찾습니다.", "server pagination/transform 가능성을 봅니다."], fix: "size/depth/count limits와 abort를 적용하고 server-side streaming transform/pagination 또는 Worker/audited streaming parser로 이동하며 render를 batch/virtualize합니다.", prevention: "near-limit/over-limit/deep/entity-bomb fixtures와 memory/interaction budget을 둡니다." },
      ],
      expertNotes: [
        "XMLSerializer로 document를 다시 string화하면 semantically equivalent하지만 prefix/attribute order/empty element spelling이 달라질 수 있습니다. canonicalization/signature 요구는 전용 표준/tooling을 사용합니다.",
        "XPath는 복잡한 query에 유용하지만 dynamic expression string injection과 namespace resolver를 관리합니다. simple fixed extraction에는 DOM traversal이 더 명확할 수 있습니다.",
        "Weather observation의 hour/date에 timezone이 없으므로 현재 시각/실시간으로 추정하지 않고 fixture metadata로 표시합니다.",
      ],
    },
  ],
  lab: {
    title: "97개 지역 날씨 XML을 namespace-aware·nullable·safe·검색 가능한 UI로 만들고 JSON adapter와 통합하기",
    scenario: "현재 code는 local selector와 문자열 table/innerHTML을 사용하고 missing ta를 빈 문자열로 숨깁니다. parsererror message, namespace/version, duplicate ID, CORS/abort/stale, JSON body double-read와 external values security가 완전하지 않습니다.",
    setup: [
      "원본 ex14/ex15/test와 동일 hash의 두 weather.xml을 read-only evidence로 준비합니다.",
      "local HTTP server와 200 XML, malformed, wrong namespace, missing/invalid/duplicate/large/DTD, slow/CORS fixtures를 준비합니다.",
      "97 rows·missing ta one·Seoul 108/5.7/흐림 golden assertions와 XML/JSON semantic parity fixture를 준비합니다.",
      "keyboard/screen reader, mobile table, AbortSignal/latest request와 privacy/performance inspection을 준비합니다.",
    ],
    steps: [
      "fetch status/media/body를 한 번 읽고 parsererror를 검사하는 parseXmlDocument helper를 만듭니다.",
      "root namespaceURI/localName과 weather structure/version을 assert하고 current namespace local elements를 snapshot합니다.",
      "각 local을 string ID/name/desc와 finite number|null temperature로 변환하며 unique/range/length를 검사합니다.",
      "JSON fixture adapter도 같은 WeatherRow[]를 반환하게 하고 semantic parity tests를 작성합니다.",
      "caption/header scope/units/missing label을 가진 table을 createElement/textContent로 render합니다.",
      "지역명/ID filter와 no-match/result count/status를 구현하고 input focus와 concise announcement를 유지합니다.",
      "새 load에서 이전 fetch를 abort하고 generation guard로 parse/render/finally stale mutation을 막습니다.",
      "malformed/wrong namespace/missing/invalid/duplicate/malicious/large/CORS/abort와 source golden tests를 실행합니다.",
      "server XML parser의 DTD/external entity secure settings, limits와 redacted telemetry/provenance를 문서화합니다.",
    ],
    expectedResult: [
      "두 source XML의 동일 hash와 97 records, 고창 missing temperature, 서울 golden record가 재현됩니다.",
      "malformed XML은 parsererror→XmlParseError, wrong namespace/schema는 SchemaError로 no-match와 구분됩니다.",
      "0/negative/missing temperature가 각각 정확히 표시되고 duplicate/invalid data가 silent coercion되지 않습니다.",
      "XML/JSON adapters가 동일 view model을 만들고 renderer/filter는 wire format에 의존하지 않습니다.",
      "tag-like XML/JSON text가 actual element/style code가 되지 않고 semantic table/keyboard/status가 접근 가능합니다.",
      "abort/dispose/oversize 뒤 pending network/listeners/nodes가 없고 telemetry에 raw XML/JSON/PII가 없습니다.",
    ],
    cleanup: ["current AbortController와 search/listener/observer를 정리하고 mock server/service worker/cache를 종료합니다.", "large/entity/malicious fixtures와 DevTools saved XML/HTML node/body references를 제거합니다."],
    extensions: ["server-side SAX/StAX XML→validated JSON transform과 browser DOMParser 접근을 memory/latency로 비교합니다.", "XPath namespace resolver로 precipitation/snow attributes query와 fixed DOM traversal을 비교합니다.", "versioned XSD/tool validation과 application adapter errors를 CI provenance report에 통합합니다."],
  },
  exercises: [
    { difficulty: "따라하기", prompt: "원본 weather.xml에서 서울 record와 고창 missing ta를 namespace-aware API로 추출하세요.", requirements: ["parsererror를 검사합니다.", "root namespaceURI/localName을 assert합니다.", "getElementsByTagNameNS로 locals를 찾습니다.", "ta null/0/negative를 구분합니다.", "97 count와 Seoul/gap golden evidence를 기록합니다."], hints: ["default namespace는 elements에 적용됩니다.", "getAttribute가 없으면 null입니다."], expectedOutcome: "prefix에 의존하지 않고 원본 structure·count·nullable values를 exact output으로 설명합니다.", solutionOutline: ["Document→root gate→namespace rows→raw record→validated record 순으로 helper를 나눕니다.", "truthiness 대신 null과 Number.isFinite를 사용합니다."] },
    { difficulty: "응용", prompt: "지역 검색·empty/error/loading/abort와 safe semantic table을 갖는 날씨 UI를 구현하세요.", requirements: ["WeatherRow adapter와 remote/filter states를 분리합니다.", "createElement/textContent, caption/th scope/unit/missing label을 사용합니다.", "no-match와 parser/schema/network errors를 구분합니다.", "AbortSignal/latest generation과 disposal을 구현합니다.", "malicious text와 mobile/keyboard/screen reader를 test합니다."], hints: ["innerHTML은 XML data를 다시 HTML로 parse합니다.", "검색 query 변경이 local filter인지 remote fetch인지 명시합니다."], expectedOutcome: "모든 source/error/query 상태에서 stale/XSS 없이 접근 가능한 table과 복구 action을 제공합니다.", solutionOutline: ["adapter/parser와 renderer/controller를 분리합니다.", "fixture-driven state transition table을 만듭니다."] },
    { difficulty: "설계", prompt: "교육 사이트의 XML ingestion·namespace/schema·security·format adapter 표준을 설계하세요.", requirements: ["HTTP/media/body/DOMParser/parsererror/schema stages를 정의합니다.", "namespace/XPath, missing/type/range/unique/version policy를 만듭니다.", "XML/JSON common model과 content negotiation을 포함합니다.", "DTD/entity/XXE, size/depth/node limits와 server/browser parser 차이를 다룹니다.", "CORS/abort/stale/accessibility/performance/privacy/provenance test gates를 설계합니다."], hints: ["well-formed는 schema-valid와 다릅니다.", "DOMParser는 server parser secure config를 대신하지 않습니다."], expectedOutcome: "팀이 XML/JSON wire formats를 안전하고 일관된 domain/UI로 변환하고 운영하는 capstone 표준이 완성됩니다.", solutionOutline: ["bytes→text→document→records→view 흐름과 trust boundaries를 그립니다.", "parser/runtime별 feature/limit matrix를 만듭니다."] },
  ],
  reviewQuestions: [
    { question: "fetch가 XML Content-Type이면 자동 XMLDocument를 반환하나요?", answer: "아닙니다. Response body를 text로 읽고 DOMParser 같은 parser를 명시적으로 사용합니다." },
    { question: "malformed XML에서 parseFromString이 항상 throw하나요?", answer: "아닙니다. error elements가 든 Document를 반환할 수 있어 parsererror를 검사합니다." },
    { question: "text/html과 application/xml parser mode는 같은가요?", answer: "아닙니다. HTML은 error recovery, XML은 well-formedness/namespace rules를 엄격히 적용합니다." },
    { question: "weather.xml의 local elements namespace는 무엇인가요?", answer: "default declaration 때문에 namespaceURI current입니다." },
    { question: "default namespace가 ta attribute에도 적용되나요?", answer: "아닙니다. prefix 없는 attributes는 no namespace라 getAttribute('ta')로 읽습니다." },
    { question: "prefix가 바뀌면 getElementsByTagNameNS 결과도 깨지나요?", answer: "namespace URI와 local name이 같으면 prefix spelling이 달라도 유지됩니다." },
    { question: "누락 ta와 ta='0.0'을 어떻게 구분하나요?", answer: "raw getAttribute가 null인지 먼저 확인하고 present string만 number로 parse합니다." },
    { question: "DOMParser가 XSD schema validation도 자동 수행하나요?", answer: "아닙니다. 별도 server/tool/application validation이 필요합니다." },
    { question: "XML text를 innerHTML table string에 넣어도 안전한가요?", answer: "아닙니다. entity-decoded external text가 HTML markup으로 재해석될 수 있어 textContent를 사용합니다." },
    { question: "response.json을 console.log와 실제 변수용으로 두 번 호출할 수 있나요?", answer: "같은 Response body는 single-use라 한 번 읽고 결과를 log/use해야 합니다." },
    { question: "XML과 JSON UI를 각각 만들어야 하나요?", answer: "format-specific adapters가 공통 view model을 반환하면 renderer/filter/error UI를 공유할 수 있습니다." },
    { question: "browser DOMParser 동작만 보면 server XXE 설정도 안전한가요?", answer: "아닙니다. server parser/runtime의 DTD/external entity/XInclude와 limits를 명시 검증합니다." },
  ],
  completionChecklist: [
    "HTTP/media/body/text/XML Document/domain/HTML DOM representations를 분리했다.",
    "Response body를 한 번만 읽고 status/Content-Type context를 parser error와 함께 보존했다.",
    "DOMParser MIME mode와 parsererror Document를 exact fixture로 검증했다.",
    "XML declaration encoding과 JavaScript string/Response decoding 경계를 설명했다.",
    "root namespaceURI/localName과 expected schema/version을 assert했다.",
    "getElementsByTagNameNS 또는 resolver-based XPath로 prefix-independent query를 작성했다.",
    "unprefixed attribute namespace와 getAttribute null semantics를 구분했다.",
    "station ID/string, name/desc, temperature number|null/range/unique를 validation했다.",
    "missing·0.0·negative·invalid ta를 truthiness 없이 처리했다.",
    "97 rows·missing ta one·Seoul record와 duplicate weather hash를 provenance test했다.",
    "semantic table/caption/th scope/unit/missing label을 createElement/textContent로 렌더링했다.",
    "외부 color/URL/style은 allowlist/property로 제한하고 innerHTML을 제거했다.",
    "XML/JSON adapters가 같은 WeatherRow model과 filter/renderer를 재사용했다.",
    "remote load·local filter·no-match·error·abort state와 concise accessibility announcement를 분리했다.",
    "AbortSignal/generation/dispose로 stale fetch/parse/render를 막았다.",
    "DTD/entity/server parser settings와 size/depth/node/memory limits를 threat model에 포함했다.",
    "malformed/namespace/schema/missing/duplicate/malicious/large/CORS/abort fixtures를 통과했다.",
  ],
  nextSessions: ["jquery-01-ready-selectors"],
  sources: [
    { id: "web-weather-fetch-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex14_fetch.html", usedFor: ["weather XML fetch", "status/text", "DOMParser application/xml", "parsererror", "local query", "ta/desc attributes", "innerHTML table"], evidence: "날씨 XML fetch→parse→table 전체 원본을 namespace/schema/safe DOM/error pipeline capstone의 중심 evidence로 사용했습니다." },
    { id: "web-makeup-json-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/ex15_fetch.html", usedFor: ["external JSON fetch", "double response.json", "top5", "product colors", "Error status bug", "innerHTML/style injection", "XML/JSON comparison"], evidence: "같은 단원의 JSON page를 body double-consumption·Error constructor·external values audit와 common view-model adapter 비교에 사용했습니다." },
    { id: "web-weather-test-source", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/test.html", usedFor: ["duplicate weather implementation", "CORS/local fallback comments", "parsererror", "attribute null fallback", "string table"], evidence: "ex14와 독립적으로 반복 구현된 날씨 flow를 code-review/provenance evidence와 safe refactor regression source로 사용했습니다." },
    { id: "web-weather-xml-day09", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/day09/weather.xml", usedFor: ["default current namespace", "weather timestamp attributes", "97 local elements", "Seoul record", "missing ta Gochang", "rain/snow optional attributes"], evidence: "실제 namespace/data values를 읽어 97 rows, missing ta one, Seoul 108|5.7|흐림과 nullable schema golden evidence를 만들었습니다." },
    { id: "web-weather-xml-data", repository: "webstudy 학습 원본", path: "myweb/src/main/webapp/data/weather.xml", usedFor: ["duplicate location fixture", "byte-identical hash", "deployment paths", "source deduplication", "provenance"], evidence: "day09 weather.xml과 SHA-256이 동일한 복사본임을 확인해 duplicate fixture drift와 deployment path를 provenance review에 포함했습니다." },
    { id: "html-domparser", repository: "WHATWG HTML Standard", path: "dynamic-markup-insertion.html#domparsing", publicUrl: "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#domparsing", usedFor: ["DOMParser interface", "supported MIME types", "HTML/XML parser selection", "parser error Document", "UTF-8 result", "scripting disabled/no sanitization"], evidence: "parseFromString mode·error·encoding/security semantics와 parser-mode exact example의 current normative 기준으로 사용했습니다." },
    { id: "dom-namespace-query", repository: "WHATWG DOM Standard", path: "#dom-document-getelementsbytagnamens", publicUrl: "https://dom.spec.whatwg.org/#dom-document-getelementsbytagnamens", usedFor: ["namespaceURI/localName", "getElementsByTagNameNS", "collection", "element query", "prefix-independent traversal"], evidence: "current namespace local extraction과 wrong namespace behavior를 expanded-name DOM APIs에 맞췄습니다." },
    { id: "dom-xpath", repository: "WHATWG DOM Standard", path: "#xpath", publicUrl: "https://dom.spec.whatwg.org/#xpath", usedFor: ["XPath evaluator", "namespace resolver", "result types", "fixed queries", "dynamic expression caution"], evidence: "복잡한 namespace-aware XML query 대안과 resolver contract를 current DOM XPath interface로 보강했습니다." },
    { id: "dom-standard", repository: "WHATWG DOM Standard", path: "Node/Document/Element/textContent/mutation", publicUrl: "https://dom.spec.whatwg.org/", usedFor: ["XML/HTML node trees", "attributes/text", "safe HTML node creation", "DocumentFragment", "query/traversal"], evidence: "parsed XML tree와 current HTML rendering tree를 분리하고 safe table nodes를 생성하는 기준으로 사용했습니다." },
    { id: "xml-standard", repository: "W3C", path: "XML 1.0 Fifth Edition", publicUrl: "https://www.w3.org/TR/xml/", usedFor: ["well-formedness", "documents/elements/attributes", "character/entity/DTD", "encoding declaration", "validity"], evidence: "HTML error recovery와 다른 XML syntax/well-formedness 및 DTD/entity threat context의 기준으로 사용했습니다." },
    { id: "xml-namespaces", repository: "W3C", path: "Namespaces in XML 1.0 Third Edition", publicUrl: "https://www.w3.org/TR/xml-names/", usedFor: ["namespace name/prefix/default namespace", "expanded names", "attribute namespace", "namespace well-formedness"], evidence: "weather default namespace와 unprefixed ta/desc attributes, prefix-independent adapter를 설명하는 기준으로 사용했습니다." },
    { id: "xml-schema", repository: "W3C", path: "XML Schema 1.1 Structures", publicUrl: "https://www.w3.org/TR/xmlschema11-1/", usedFor: ["schema components", "validation", "types", "constraints", "versioned contracts"], evidence: "well-formedness와 schema validity를 구분하고 XSD/tool/application validation 선택을 보강했습니다." },
    { id: "fetch-response", repository: "WHATWG Fetch Standard", path: "#response-class", publicUrl: "https://fetch.spec.whatwg.org/#response-class", usedFor: ["status/ok/headers", "Response.text/json", "bodyUsed", "clone", "CORS/abort integration"], evidence: "XML/JSON body를 한 번 읽고 HTTP/CORS/abort context를 보존하는 upstream pipeline 기준으로 재사용했습니다." },
    { id: "trusted-types", repository: "W3C Web Application Security Working Group", path: "TR/trusted-types/", publicUrl: "https://www.w3.org/TR/trusted-types/", usedFor: ["DOM parsing/injection sinks", "TrustedHTML", "policy", "innerHTML migration", "defense in depth"], evidence: "external XML/JSON strings를 HTML/CSS code로 재해석하지 않는 safe rendering과 sink inventory를 보강했습니다." },
    { id: "json-rfc-source", repository: "IETF RFC Editor", path: "RFC 8259 JSON", publicUrl: "https://www.rfc-editor.org/rfc/rfc8259", usedFor: ["JSON wire model", "XML/JSON adapter parity", "runtime schema boundary", "number/string semantics"], evidence: "같은 semantic weather data를 XML/JSON wire formats에서 공통 model로 만드는 비교 기준으로 사용했습니다." },
  ],
  sourceCoverage: {
    filesRead: 5,
    filesUsed: 5,
    uncoveredNotes: [
      "다섯 inventory files를 모두 사용했습니다. 두 weather.xml은 byte-identical하고 97 local records, missing ta one(Gochang 172), Seoul 108|5.7|흐림을 source audit로 확인했습니다.",
      "원본 XML pages는 parsererror/null fallback을 갖지만 default namespace contract, type/range/uniqueness, safe DOM, abort/state와 large/security limits가 없습니다. WHATWG/W3C standards로 보강했습니다.",
      "원본 JSON page는 response.json을 두 번 소비하고 remote values를 innerHTML/style string에 넣습니다. JS10 body/schema 모델과 JS06 safe DOM을 적용해 XML/JSON common adapter capstone으로 교정했습니다.",
    ],
  },
} satisfies DetailedSession;

export default session;
